#include "aux_macro.h"
#include "../malloc_2.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(13););
printStats();
void* p0 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p1 = last_address;
PRINT_POINTER(srealloc(p1,184););
printStats();
void* p2 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p3 = last_address;
PRINT_POINTER(scalloc(156,60););
printStats();
void* p4 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p5 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p6 = last_address;
PRINT_POINTER(scalloc(6,236););
printStats();
void* p7 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(scalloc(183,127););
printStats();
void* p8 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p9 = last_address;
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(smalloc(47););
printStats();
void* p10 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
PRINT_POINTER(smalloc(9););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(136,114););
printStats();
void* p12 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
PRINT_POINTER(smalloc(174););
printStats();
void* p13 = last_address;
PRINT_POINTER(srealloc(p13,40););
printStats();
void* p14 = last_address;
DEBUG_PRINT(sfree(p12););
printStats();
DEBUG_PRINT(sfree(p3););
printStats();
PRINT_POINTER(smalloc(109););
printStats();
void* p15 = last_address;
PRINT_POINTER(srealloc(p9,42););
printStats();
void* p16 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p17 = last_address;
PRINT_POINTER(srealloc(p8,144););
printStats();
void* p18 = last_address;
PRINT_POINTER(scalloc(233,220););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p20 = last_address;
PRINT_POINTER(scalloc(99,30););
printStats();
void* p21 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p22 = last_address;
PRINT_POINTER(srealloc(p18,159););
printStats();
void* p23 = last_address;
PRINT_POINTER(srealloc(p21,231););
printStats();
void* p24 = last_address;
PRINT_POINTER(scalloc(128,136););
printStats();
void* p25 = last_address;
PRINT_POINTER(srealloc(p17,97););
printStats();
void* p26 = last_address;
DEBUG_PRINT(sfree(p20););
printStats();
PRINT_POINTER(srealloc(p23,120););
printStats();
void* p27 = last_address;
PRINT_POINTER(scalloc(82,208););
printStats();
void* p28 = last_address;
PRINT_POINTER(srealloc(p27,55););
printStats();
void* p29 = last_address;
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(scalloc(34,144););
printStats();
void* p30 = last_address;
PRINT_POINTER(srealloc(p19,190););
printStats();
void* p31 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(scalloc(200,33););
printStats();
void* p32 = last_address;
PRINT_POINTER(srealloc(p11,232););
printStats();
void* p33 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
DEBUG_PRINT(sfree(p5););
printStats();
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(scalloc(150,60););
printStats();
void* p34 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
DEBUG_PRINT(sfree(p26););
printStats();
PRINT_POINTER(srealloc(p32,104););
printStats();
void* p35 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(scalloc(196,171););
printStats();
void* p36 = last_address;
DEBUG_PRINT(sfree(p10););
printStats();
DEBUG_PRINT(sfree(p35););
printStats();
DEBUG_PRINT(sfree(p36););
printStats();
PRINT_POINTER(smalloc(16););
printStats();
void* p37 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
DEBUG_PRINT(sfree(p24););
printStats();
DEBUG_PRINT(sfree(p31););
printStats();
DEBUG_PRINT(sfree(p30););
printStats();
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(smalloc(210););
printStats();
void* p38 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(scalloc(214,5););
printStats();
void* p39 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p28,10););
printStats();
void* p41 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p42 = last_address;
PRINT_POINTER(scalloc(60,36););
printStats();
void* p43 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
PRINT_POINTER(smalloc(40););
printStats();
void* p44 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p45 = last_address;
PRINT_POINTER(srealloc(p40,154););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p47 = last_address;
PRINT_POINTER(scalloc(246,225););
printStats();
void* p48 = last_address;
DEBUG_PRINT(sfree(p47););
printStats();
PRINT_POINTER(srealloc(p39,236););
printStats();
void* p49 = last_address;
PRINT_POINTER(srealloc(p44,146););
printStats();
void* p50 = last_address;
DEBUG_PRINT(sfree(p48););
printStats();
PRINT_POINTER(srealloc(p46,91););
printStats();
void* p51 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p52 = last_address;
PRINT_POINTER(scalloc(131,158););
printStats();
void* p53 = last_address;
PRINT_POINTER(srealloc(p45,239););
printStats();
void* p54 = last_address;
PRINT_POINTER(srealloc(p51,77););
printStats();
void* p55 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p56 = last_address;
PRINT_POINTER(scalloc(31,219););
printStats();
void* p57 = last_address;
PRINT_POINTER(srealloc(p49,176););
printStats();
void* p58 = last_address;
PRINT_POINTER(scalloc(201,22););
printStats();
void* p59 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p60 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p61 = last_address;
PRINT_POINTER(srealloc(p58,88););
printStats();
void* p62 = last_address;
DEBUG_PRINT(sfree(p55););
printStats();
PRINT_POINTER(srealloc(p53,214););
printStats();
void* p63 = last_address;
PRINT_POINTER(srealloc(p54,70););
printStats();
void* p64 = last_address;
PRINT_POINTER(srealloc(p38,205););
printStats();
void* p65 = last_address;
PRINT_POINTER(srealloc(p65,104););
printStats();
void* p66 = last_address;
PRINT_POINTER(scalloc(87,28););
printStats();
void* p67 = last_address;
PRINT_POINTER(scalloc(68,65););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p52,104););
printStats();
void* p69 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(srealloc(p69,179););
printStats();
void* p70 = last_address;
DEBUG_PRINT(sfree(p61););
printStats();
PRINT_POINTER(smalloc(32););
printStats();
void* p71 = last_address;
PRINT_POINTER(srealloc(p64,133););
printStats();
void* p72 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p73 = last_address;
PRINT_POINTER(srealloc(p70,231););
printStats();
void* p74 = last_address;
PRINT_POINTER(srealloc(p66,34););
printStats();
void* p75 = last_address;
PRINT_POINTER(smalloc(221););
printStats();
void* p76 = last_address;
DEBUG_PRINT(sfree(p74););
printStats();
PRINT_POINTER(srealloc(p75,249););
printStats();
void* p77 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(scalloc(124,161););
printStats();
void* p78 = last_address;
DEBUG_PRINT(sfree(p42););
printStats();
PRINT_POINTER(srealloc(p56,74););
printStats();
void* p79 = last_address;
PRINT_POINTER(srealloc(p76,71););
printStats();
void* p80 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p81 = last_address;
PRINT_POINTER(srealloc(p80,85););
printStats();
void* p82 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(srealloc(p71,139););
printStats();
void* p83 = last_address;
PRINT_POINTER(scalloc(142,27););
printStats();
void* p84 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p85 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p67,202););
printStats();
void* p87 = last_address;
DEBUG_PRINT(sfree(p81););
printStats();
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(smalloc(239););
printStats();
void* p88 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(smalloc(153););
printStats();
void* p89 = last_address;
PRINT_POINTER(scalloc(88,243););
printStats();
void* p90 = last_address;
PRINT_POINTER(scalloc(10,74););
printStats();
void* p91 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p92 = last_address;
PRINT_POINTER(srealloc(p88,190););
printStats();
void* p93 = last_address;
PRINT_POINTER(scalloc(120,157););
printStats();
void* p94 = last_address;
DEBUG_PRINT(sfree(p93););
printStats();
PRINT_POINTER(srealloc(p87,231););
printStats();
void* p95 = last_address;
PRINT_POINTER(srealloc(p79,150););
printStats();
void* p96 = last_address;
PRINT_POINTER(scalloc(226,73););
printStats();
void* p97 = last_address;
PRINT_POINTER(srealloc(p57,205););
printStats();
void* p98 = last_address;
PRINT_POINTER(srealloc(p82,32););
printStats();
void* p99 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p100 = last_address;
DEBUG_PRINT(sfree(p63););
printStats();
DEBUG_PRINT(sfree(p91););
printStats();
DEBUG_PRINT(sfree(p62););
printStats();
DEBUG_PRINT(sfree(p98););
printStats();
DEBUG_PRINT(sfree(p77););
printStats();
PRINT_POINTER(scalloc(12,143););
printStats();
void* p101 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p102 = last_address;
DEBUG_PRINT(sfree(p83););
printStats();
PRINT_POINTER(scalloc(12,21););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p73,215););
printStats();
void* p104 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p105 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p106 = last_address;
PRINT_POINTER(scalloc(91,25););
printStats();
void* p107 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p108 = last_address;
PRINT_POINTER(srealloc(p68,166););
printStats();
void* p109 = last_address;
PRINT_POINTER(srealloc(p108,84););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p102,12););
printStats();
void* p111 = last_address;
PRINT_POINTER(srealloc(p104,105););
printStats();
void* p112 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(srealloc(p95,176););
printStats();
void* p113 = last_address;
DEBUG_PRINT(sfree(p99););
printStats();
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(smalloc(212););
printStats();
void* p114 = last_address;
PRINT_POINTER(srealloc(p90,235););
printStats();
void* p115 = last_address;
PRINT_POINTER(srealloc(p111,125););
printStats();
void* p116 = last_address;
PRINT_POINTER(srealloc(p101,163););
printStats();
void* p117 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p118 = last_address;
PRINT_POINTER(scalloc(142,111););
printStats();
void* p119 = last_address;
DEBUG_PRINT(sfree(p84););
printStats();
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(scalloc(9,207););
printStats();
void* p120 = last_address;
PRINT_POINTER(scalloc(109,55););
printStats();
void* p121 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p122 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p123 = last_address;
PRINT_POINTER(srealloc(p114,41););
printStats();
void* p124 = last_address;
PRINT_POINTER(srealloc(p115,38););
printStats();
void* p125 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
DEBUG_PRINT(sfree(p121););
printStats();
DEBUG_PRINT(sfree(p92););
printStats();
PRINT_POINTER(scalloc(66,13););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(1,110););
printStats();
void* p127 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p128 = last_address;
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(srealloc(p103,173););
printStats();
void* p129 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p130 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p131 = last_address;
PRINT_POINTER(srealloc(p106,120););
printStats();
void* p132 = last_address;
PRINT_POINTER(scalloc(2,241););
printStats();
void* p133 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p134 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p135 = last_address;
PRINT_POINTER(scalloc(111,113););
printStats();
void* p136 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p137 = last_address;
PRINT_POINTER(srealloc(p105,144););
printStats();
void* p138 = last_address;
PRINT_POINTER(srealloc(p118,16););
printStats();
void* p139 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p140 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p132,241););
printStats();
void* p142 = last_address;
DEBUG_PRINT(sfree(p139););
printStats();
PRINT_POINTER(srealloc(p96,191););
printStats();
void* p143 = last_address;
PRINT_POINTER(srealloc(p112,124););
printStats();
void* p144 = last_address;
PRINT_POINTER(scalloc(198,113););
printStats();
void* p145 = last_address;
PRINT_POINTER(scalloc(247,122););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p133););
printStats();
PRINT_POINTER(srealloc(p128,120););
printStats();
void* p147 = last_address;
PRINT_POINTER(srealloc(p130,141););
printStats();
void* p148 = last_address;
PRINT_POINTER(scalloc(107,114););
printStats();
void* p149 = last_address;
DEBUG_PRINT(sfree(p140););
printStats();
PRINT_POINTER(srealloc(p131,83););
printStats();
void* p150 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p151 = last_address;
PRINT_POINTER(scalloc(25,0););
printStats();
void* p152 = last_address;
PRINT_POINTER(scalloc(60,70););
printStats();
void* p153 = last_address;
PRINT_POINTER(srealloc(p151,204););
printStats();
void* p154 = last_address;
PRINT_POINTER(srealloc(p117,105););
printStats();
void* p155 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p156 = last_address;
PRINT_POINTER(scalloc(144,112););
printStats();
void* p157 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p158 = last_address;
PRINT_POINTER(srealloc(p110,242););
printStats();
void* p159 = last_address;
PRINT_POINTER(scalloc(78,101););
printStats();
void* p160 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p161 = last_address;
DEBUG_PRINT(sfree(p154););
printStats();
DEBUG_PRINT(sfree(p160););
printStats();
PRINT_POINTER(smalloc(149););
printStats();
void* p162 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p163 = last_address;
DEBUG_PRINT(sfree(p138););
printStats();
PRINT_POINTER(scalloc(93,113););
printStats();
void* p164 = last_address;
DEBUG_PRINT(sfree(p144););
printStats();
DEBUG_PRINT(sfree(p163););
printStats();
PRINT_POINTER(scalloc(14,76););
printStats();
void* p165 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p166 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p167 = last_address;
PRINT_POINTER(scalloc(230,131););
printStats();
void* p168 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p169 = last_address;
PRINT_POINTER(srealloc(p153,236););
printStats();
void* p170 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p171 = last_address;
DEBUG_PRINT(sfree(p107););
printStats();
PRINT_POINTER(smalloc(156););
printStats();
void* p172 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p173 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p174 = last_address;
PRINT_POINTER(srealloc(p97,8););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p174););
printStats();
DEBUG_PRINT(sfree(p155););
printStats();
PRINT_POINTER(smalloc(116););
printStats();
void* p176 = last_address;
DEBUG_PRINT(sfree(p136););
printStats();
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(scalloc(163,175););
printStats();
void* p177 = last_address;
PRINT_POINTER(srealloc(p126,17););
printStats();
void* p178 = last_address;
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p179 = last_address;
PRINT_POINTER(scalloc(71,212););
printStats();
void* p180 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p181 = last_address;
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(smalloc(58););
printStats();
void* p182 = last_address;
PRINT_POINTER(scalloc(243,238););
printStats();
void* p183 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p184 = last_address;
PRINT_POINTER(srealloc(p183,171););
printStats();
void* p185 = last_address;
PRINT_POINTER(srealloc(p129,51););
printStats();
void* p186 = last_address;
PRINT_POINTER(srealloc(p164,59););
printStats();
void* p187 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p188 = last_address;
PRINT_POINTER(scalloc(90,14););
printStats();
void* p189 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(smalloc(118););
printStats();
void* p190 = last_address;
PRINT_POINTER(scalloc(72,141););
printStats();
void* p191 = last_address;
PRINT_POINTER(scalloc(26,196););
printStats();
void* p192 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p193 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p194 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p195 = last_address;
PRINT_POINTER(srealloc(p162,149););
printStats();
void* p196 = last_address;
PRINT_POINTER(srealloc(p194,66););
printStats();
void* p197 = last_address;
PRINT_POINTER(scalloc(70,127););
printStats();
void* p198 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p199 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(srealloc(p184,236););
printStats();
void* p200 = last_address;
PRINT_POINTER(scalloc(68,92););
printStats();
void* p201 = last_address;
PRINT_POINTER(scalloc(28,125););
printStats();
void* p202 = last_address;
PRINT_POINTER(srealloc(p188,112););
printStats();
void* p203 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p204 = last_address;
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(smalloc(18););
printStats();
void* p205 = last_address;
DEBUG_PRINT(sfree(p169););
printStats();
PRINT_POINTER(srealloc(p179,202););
printStats();
void* p206 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(smalloc(149););
printStats();
void* p207 = last_address;
PRINT_POINTER(scalloc(219,241););
printStats();
void* p208 = last_address;
PRINT_POINTER(scalloc(48,174););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(94,9););
printStats();
void* p210 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p211 = last_address;
DEBUG_PRINT(sfree(p158););
printStats();
PRINT_POINTER(srealloc(p171,0););
printStats();
void* p212 = last_address;
DEBUG_PRINT(sfree(p202););
printStats();
PRINT_POINTER(smalloc(211););
printStats();
void* p213 = last_address;
PRINT_POINTER(scalloc(121,216););
printStats();
void* p214 = last_address;
PRINT_POINTER(scalloc(233,37););
printStats();
void* p215 = last_address;
PRINT_POINTER(scalloc(98,27););
printStats();
void* p216 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
DEBUG_PRINT(sfree(p137););
printStats();
DEBUG_PRINT(sfree(p125););
printStats();
PRINT_POINTER(smalloc(134););
printStats();
void* p217 = last_address;
PRINT_POINTER(scalloc(143,188););
printStats();
void* p218 = last_address;
PRINT_POINTER(srealloc(p178,214););
printStats();
void* p219 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p220 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p221 = last_address;
DEBUG_PRINT(sfree(p145););
printStats();
PRINT_POINTER(srealloc(p220,10););
printStats();
void* p222 = last_address;
PRINT_POINTER(scalloc(62,47););
printStats();
void* p223 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(scalloc(87,10););
printStats();
void* p224 = last_address;
PRINT_POINTER(scalloc(13,67););
printStats();
void* p225 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p226 = last_address;
DEBUG_PRINT(sfree(p204););
printStats();
PRINT_POINTER(srealloc(p190,58););
printStats();
void* p227 = last_address;
PRINT_POINTER(scalloc(114,64););
printStats();
void* p228 = last_address;
PRINT_POINTER(scalloc(44,233););
printStats();
void* p229 = last_address;
PRINT_POINTER(srealloc(p207,39););
printStats();
void* p230 = last_address;
PRINT_POINTER(srealloc(p198,129););
printStats();
void* p231 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p232 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
PRINT_POINTER(scalloc(231,145););
printStats();
void* p233 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p234 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p235 = last_address;
PRINT_POINTER(srealloc(p189,153););
printStats();
void* p236 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p237 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p235,87););
printStats();
void* p239 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(srealloc(p223,239););
printStats();
void* p240 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p241 = last_address;
PRINT_POINTER(scalloc(81,83););
printStats();
void* p242 = last_address;
PRINT_POINTER(srealloc(p195,199););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p226););
printStats();
PRINT_POINTER(smalloc(34););
printStats();
void* p244 = last_address;
PRINT_POINTER(srealloc(p225,6););
printStats();
void* p245 = last_address;
PRINT_POINTER(scalloc(2,104););
printStats();
void* p246 = last_address;
PRINT_POINTER(scalloc(181,10););
printStats();
void* p247 = last_address;
PRINT_POINTER(srealloc(p224,218););
printStats();
void* p248 = last_address;
PRINT_POINTER(srealloc(p227,47););
printStats();
void* p249 = last_address;
PRINT_POINTER(srealloc(p150,61););
printStats();
void* p250 = last_address;
PRINT_POINTER(scalloc(110,60););
printStats();
void* p251 = last_address;
PRINT_POINTER(scalloc(213,82););
printStats();
void* p252 = last_address;
DEBUG_PRINT(sfree(p245););
printStats();
PRINT_POINTER(srealloc(p192,20););
printStats();
void* p253 = last_address;
PRINT_POINTER(srealloc(p234,106););
printStats();
void* p254 = last_address;
PRINT_POINTER(srealloc(p244,224););
printStats();
void* p255 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(smalloc(237););
printStats();
void* p256 = last_address;
PRINT_POINTER(srealloc(p135,14););
printStats();
void* p257 = last_address;
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(srealloc(p191,162););
printStats();
void* p258 = last_address;
PRINT_POINTER(srealloc(p201,204););
printStats();
void* p259 = last_address;
PRINT_POINTER(srealloc(p218,110););
printStats();
void* p260 = last_address;
PRINT_POINTER(srealloc(p253,25););
printStats();
void* p261 = last_address;
DEBUG_PRINT(sfree(p233););
printStats();
PRINT_POINTER(scalloc(27,175););
printStats();
void* p262 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p263 = last_address;
PRINT_POINTER(scalloc(199,76););
printStats();
void* p264 = last_address;
PRINT_POINTER(scalloc(200,209););
printStats();
void* p265 = last_address;
PRINT_POINTER(scalloc(176,24););
printStats();
void* p266 = last_address;
PRINT_POINTER(scalloc(150,87););
printStats();
void* p267 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p268 = last_address;
PRINT_POINTER(scalloc(201,152););
printStats();
void* p269 = last_address;
PRINT_POINTER(scalloc(29,239););
printStats();
void* p270 = last_address;
PRINT_POINTER(scalloc(4,41););
printStats();
void* p271 = last_address;
DEBUG_PRINT(sfree(p263););
printStats();
DEBUG_PRINT(sfree(p252););
printStats();
DEBUG_PRINT(sfree(p170););
printStats();
DEBUG_PRINT(sfree(p257););
printStats();
PRINT_POINTER(smalloc(16););
printStats();
void* p272 = last_address;
PRINT_POINTER(scalloc(130,177););
printStats();
void* p273 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p274 = last_address;
DEBUG_PRINT(sfree(p249););
printStats();
PRINT_POINTER(smalloc(27););
printStats();
void* p275 = last_address;
PRINT_POINTER(srealloc(p185,210););
printStats();
void* p276 = last_address;
PRINT_POINTER(scalloc(178,151););
printStats();
void* p277 = last_address;
PRINT_POINTER(srealloc(p268,169););
printStats();
void* p278 = last_address;
DEBUG_PRINT(sfree(p231););
printStats();
PRINT_POINTER(smalloc(95););
printStats();
void* p279 = last_address;
PRINT_POINTER(scalloc(157,80););
printStats();
void* p280 = last_address;
PRINT_POINTER(scalloc(206,11););
printStats();
void* p281 = last_address;
PRINT_POINTER(srealloc(p216,78););
printStats();
void* p282 = last_address;
PRINT_POINTER(scalloc(141,70););
printStats();
void* p283 = last_address;
DEBUG_PRINT(sfree(p282););
printStats();
PRINT_POINTER(srealloc(p237,125););
printStats();
void* p284 = last_address;
PRINT_POINTER(scalloc(89,234););
printStats();
void* p285 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p286 = last_address;
DEBUG_PRINT(sfree(p156););
printStats();
PRINT_POINTER(srealloc(p182,47););
printStats();
void* p287 = last_address;
PRINT_POINTER(scalloc(84,26););
printStats();
void* p288 = last_address;
DEBUG_PRINT(sfree(p217););
printStats();
DEBUG_PRINT(sfree(p120););
printStats();
PRINT_POINTER(smalloc(20););
printStats();
void* p289 = last_address;
DEBUG_PRINT(sfree(p265););
printStats();
PRINT_POINTER(smalloc(178););
printStats();
void* p290 = last_address;
PRINT_POINTER(scalloc(158,53););
printStats();
void* p291 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
PRINT_POINTER(smalloc(236););
printStats();
void* p292 = last_address;
PRINT_POINTER(srealloc(p285,76););
printStats();
void* p293 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p294 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p295 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p296 = last_address;
DEBUG_PRINT(sfree(p172););
printStats();
DEBUG_PRINT(sfree(p247););
printStats();
DEBUG_PRINT(sfree(p187););
printStats();
PRINT_POINTER(smalloc(51););
printStats();
void* p297 = last_address;
PRINT_POINTER(scalloc(29,71););
printStats();
void* p298 = last_address;
PRINT_POINTER(srealloc(p283,139););
printStats();
void* p299 = last_address;
PRINT_POINTER(srealloc(p275,96););
printStats();
void* p300 = last_address;
PRINT_POINTER(srealloc(p236,129););
printStats();
void* p301 = last_address;
PRINT_POINTER(scalloc(5,216););
printStats();
void* p302 = last_address;
PRINT_POINTER(scalloc(79,141););
printStats();
void* p303 = last_address;
PRINT_POINTER(scalloc(7,232););
printStats();
void* p304 = last_address;
PRINT_POINTER(srealloc(p181,215););
printStats();
void* p305 = last_address;
DEBUG_PRINT(sfree(p200););
printStats();
PRINT_POINTER(scalloc(179,229););
printStats();
void* p306 = last_address;
PRINT_POINTER(scalloc(215,59););
printStats();
void* p307 = last_address;
PRINT_POINTER(scalloc(1,91););
printStats();
void* p308 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p309 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p310 = last_address;
PRINT_POINTER(scalloc(155,103););
printStats();
void* p311 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p312 = last_address;
PRINT_POINTER(srealloc(p281,155););
printStats();
void* p313 = last_address;
PRINT_POINTER(srealloc(p214,87););
printStats();
void* p314 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p315 = last_address;
DEBUG_PRINT(sfree(p157););
printStats();
PRINT_POINTER(scalloc(235,224););
printStats();
void* p316 = last_address;
PRINT_POINTER(scalloc(234,147););
printStats();
void* p317 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p318 = last_address;
DEBUG_PRINT(sfree(p311););
printStats();
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(smalloc(66););
printStats();
void* p319 = last_address;
PRINT_POINTER(srealloc(p289,171););
printStats();
void* p320 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p321 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p322 = last_address;
PRINT_POINTER(srealloc(p256,158););
printStats();
void* p323 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p324 = last_address;
PRINT_POINTER(srealloc(p272,101););
printStats();
void* p325 = last_address;
PRINT_POINTER(srealloc(p205,142););
printStats();
void* p326 = last_address;
PRINT_POINTER(scalloc(93,182););
printStats();
void* p327 = last_address;
PRINT_POINTER(scalloc(64,90););
printStats();
void* p328 = last_address;
PRINT_POINTER(scalloc(49,29););
printStats();
void* p329 = last_address;
PRINT_POINTER(srealloc(p277,33););
printStats();
void* p330 = last_address;
DEBUG_PRINT(sfree(p259););
printStats();
PRINT_POINTER(srealloc(p239,22););
printStats();
void* p331 = last_address;
PRINT_POINTER(srealloc(p295,32););
printStats();
void* p332 = last_address;
PRINT_POINTER(srealloc(p312,176););
printStats();
void* p333 = last_address;
DEBUG_PRINT(sfree(p264););
printStats();
PRINT_POINTER(scalloc(58,213););
printStats();
void* p334 = last_address;
DEBUG_PRINT(sfree(p298););
printStats();
PRINT_POINTER(srealloc(p219,177););
printStats();
void* p335 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p336 = last_address;
PRINT_POINTER(srealloc(p278,58););
printStats();
void* p337 = last_address;
PRINT_POINTER(scalloc(81,210););
printStats();
void* p338 = last_address;
PRINT_POINTER(srealloc(p329,188););
printStats();
void* p339 = last_address;
DEBUG_PRINT(sfree(p240););
printStats();
DEBUG_PRINT(sfree(p309););
printStats();
PRINT_POINTER(scalloc(68,119););
printStats();
void* p340 = last_address;
DEBUG_PRINT(sfree(p330););
printStats();
PRINT_POINTER(smalloc(14););
printStats();
void* p341 = last_address;
PRINT_POINTER(srealloc(p301,241););
printStats();
void* p342 = last_address;
DEBUG_PRINT(sfree(p342););
printStats();
PRINT_POINTER(smalloc(103););
printStats();
void* p343 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p344 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p345 = last_address;
PRINT_POINTER(scalloc(147,154););
printStats();
void* p346 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p347 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(scalloc(72,233););
printStats();
void* p348 = last_address;
DEBUG_PRINT(sfree(p343););
printStats();
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(scalloc(121,114););
printStats();
void* p349 = last_address;
PRINT_POINTER(srealloc(p210,190););
printStats();
void* p350 = last_address;
PRINT_POINTER(scalloc(156,38););
printStats();
void* p351 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p352 = last_address;
PRINT_POINTER(srealloc(p232,113););
printStats();
void* p353 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p354 = last_address;
PRINT_POINTER(scalloc(117,167););
printStats();
void* p355 = last_address;
PRINT_POINTER(srealloc(p345,60););
printStats();
void* p356 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p357 = last_address;
PRINT_POINTER(scalloc(154,162););
printStats();
void* p358 = last_address;
PRINT_POINTER(srealloc(p332,30););
printStats();
void* p359 = last_address;
PRINT_POINTER(srealloc(p321,36););
printStats();
void* p360 = last_address;
DEBUG_PRINT(sfree(p299););
printStats();
PRINT_POINTER(srealloc(p356,134););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(80););
printStats();
void* p362 = last_address;
DEBUG_PRINT(sfree(p335););
printStats();
PRINT_POINTER(scalloc(94,13););
printStats();
void* p363 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p364 = last_address;
PRINT_POINTER(srealloc(p193,215););
printStats();
void* p365 = last_address;
PRINT_POINTER(srealloc(p276,70););
printStats();
void* p366 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p367 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p368 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p369 = last_address;
PRINT_POINTER(srealloc(p167,203););
printStats();
void* p370 = last_address;
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(srealloc(p243,106););
printStats();
void* p371 = last_address;
PRINT_POINTER(scalloc(221,138););
printStats();
void* p372 = last_address;
PRINT_POINTER(scalloc(202,56););
printStats();
void* p373 = last_address;
PRINT_POINTER(scalloc(178,27););
printStats();
void* p374 = last_address;
DEBUG_PRINT(sfree(p340););
printStats();
PRINT_POINTER(scalloc(51,10););
printStats();
void* p375 = last_address;
DEBUG_PRINT(sfree(p286););
printStats();
DEBUG_PRINT(sfree(p307););
printStats();
PRINT_POINTER(scalloc(108,241););
printStats();
void* p376 = last_address;
PRINT_POINTER(srealloc(p273,71););
printStats();
void* p377 = last_address;
DEBUG_PRINT(sfree(p258););
printStats();
PRINT_POINTER(srealloc(p228,28););
printStats();
void* p378 = last_address;
DEBUG_PRINT(sfree(p288););
printStats();
DEBUG_PRINT(sfree(p352););
printStats();
DEBUG_PRINT(sfree(p165););
printStats();
DEBUG_PRINT(sfree(p320););
printStats();
PRINT_POINTER(scalloc(194,51););
printStats();
void* p379 = last_address;
DEBUG_PRINT(sfree(p300););
printStats();
PRINT_POINTER(smalloc(96););
printStats();
void* p380 = last_address;
PRINT_POINTER(srealloc(p355,7););
printStats();
void* p381 = last_address;
PRINT_POINTER(srealloc(p212,99););
printStats();
void* p382 = last_address;
DEBUG_PRINT(sfree(p306););
printStats();
PRINT_POINTER(scalloc(207,115););
printStats();
void* p383 = last_address;
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(scalloc(151,126););
printStats();
void* p384 = last_address;
PRINT_POINTER(srealloc(p199,149););
printStats();
void* p385 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p386 = last_address;
DEBUG_PRINT(sfree(p317););
printStats();
PRINT_POINTER(scalloc(236,34););
printStats();
void* p387 = last_address;
DEBUG_PRINT(sfree(p322););
printStats();
DEBUG_PRINT(sfree(p143););
printStats();
PRINT_POINTER(scalloc(124,113););
printStats();
void* p388 = last_address;
DEBUG_PRINT(sfree(p348););
printStats();
PRINT_POINTER(smalloc(67););
printStats();
void* p389 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p390 = last_address;
PRINT_POINTER(srealloc(p161,228););
printStats();
void* p391 = last_address;
PRINT_POINTER(srealloc(p387,89););
printStats();
void* p392 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p393 = last_address;
PRINT_POINTER(scalloc(196,67););
printStats();
void* p394 = last_address;
PRINT_POINTER(srealloc(p370,216););
printStats();
void* p395 = last_address;
DEBUG_PRINT(sfree(p395););
printStats();
PRINT_POINTER(srealloc(p261,160););
printStats();
void* p396 = last_address;
PRINT_POINTER(srealloc(p122,144););
printStats();
void* p397 = last_address;
PRINT_POINTER(scalloc(182,60););
printStats();
void* p398 = last_address;
PRINT_POINTER(scalloc(240,112););
printStats();
void* p399 = last_address;
PRINT_POINTER(srealloc(p339,133););
printStats();
void* p400 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p401 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p402 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p403 = last_address;
PRINT_POINTER(scalloc(140,7););
printStats();
void* p404 = last_address;
PRINT_POINTER(srealloc(p382,124););
printStats();
void* p405 = last_address;
DEBUG_PRINT(sfree(p325););
printStats();
PRINT_POINTER(scalloc(173,158););
printStats();
void* p406 = last_address;
PRINT_POINTER(scalloc(249,0););
printStats();
void* p407 = last_address;
DEBUG_PRINT(sfree(p357););
printStats();
PRINT_POINTER(srealloc(p127,35););
printStats();
void* p408 = last_address;
PRINT_POINTER(srealloc(p246,72););
printStats();
void* p409 = last_address;
PRINT_POINTER(srealloc(p305,186););
printStats();
void* p410 = last_address;
DEBUG_PRINT(sfree(p374););
printStats();
PRINT_POINTER(scalloc(8,49););
printStats();
void* p411 = last_address;
PRINT_POINTER(srealloc(p409,233););
printStats();
void* p412 = last_address;
PRINT_POINTER(srealloc(p274,175););
printStats();
void* p413 = last_address;
PRINT_POINTER(srealloc(p392,46););
printStats();
void* p414 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p415 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p416 = last_address;
PRINT_POINTER(srealloc(p294,246););
printStats();
void* p417 = last_address;
PRINT_POINTER(srealloc(p358,181););
printStats();
void* p418 = last_address;
PRINT_POINTER(srealloc(p407,16););
printStats();
void* p419 = last_address;
PRINT_POINTER(srealloc(p293,73););
printStats();
void* p420 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p421 = last_address;
PRINT_POINTER(srealloc(p86,12););
printStats();
void* p422 = last_address;
DEBUG_PRINT(sfree(p341););
printStats();
PRINT_POINTER(scalloc(53,244););
printStats();
void* p423 = last_address;
PRINT_POINTER(srealloc(p350,121););
printStats();
void* p424 = last_address;
PRINT_POINTER(srealloc(p213,3););
printStats();
void* p425 = last_address;
PRINT_POINTER(srealloc(p403,15););
printStats();
void* p426 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p427 = last_address;
PRINT_POINTER(scalloc(246,15););
printStats();
void* p428 = last_address;
DEBUG_PRINT(sfree(p284););
printStats();
PRINT_POINTER(smalloc(131););
printStats();
void* p429 = last_address;
PRINT_POINTER(scalloc(70,162););
printStats();
void* p430 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p431 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p432 = last_address;
DEBUG_PRINT(sfree(p430););
printStats();
DEBUG_PRINT(sfree(p230););
printStats();
PRINT_POINTER(scalloc(26,195););
printStats();
void* p433 = last_address;
PRINT_POINTER(srealloc(p381,170););
printStats();
void* p434 = last_address;
PRINT_POINTER(scalloc(7,216););
printStats();
void* p435 = last_address;
PRINT_POINTER(srealloc(p371,58););
printStats();
void* p436 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p437 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p438 = last_address;
PRINT_POINTER(srealloc(p432,142););
printStats();
void* p439 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p440 = last_address;
PRINT_POINTER(srealloc(p437,7););
printStats();
void* p441 = last_address;
DEBUG_PRINT(sfree(p314););
printStats();
PRINT_POINTER(scalloc(230,67););
printStats();
void* p442 = last_address;
PRINT_POINTER(srealloc(p316,8););
printStats();
void* p443 = last_address;
DEBUG_PRINT(sfree(p397););
printStats();
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(smalloc(211););
printStats();
void* p444 = last_address;
PRINT_POINTER(scalloc(94,76););
printStats();
void* p445 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p446 = last_address;
DEBUG_PRINT(sfree(p421););
printStats();
PRINT_POINTER(smalloc(106););
printStats();
void* p447 = last_address;
PRINT_POINTER(srealloc(p336,217););
printStats();
void* p448 = last_address;
PRINT_POINTER(srealloc(p419,102););
printStats();
void* p449 = last_address;
PRINT_POINTER(srealloc(p326,172););
printStats();
void* p450 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p451 = last_address;
PRINT_POINTER(srealloc(p323,68););
printStats();
void* p452 = last_address;
PRINT_POINTER(srealloc(p415,77););
printStats();
void* p453 = last_address;
PRINT_POINTER(scalloc(139,99););
printStats();
void* p454 = last_address;
PRINT_POINTER(srealloc(p444,47););
printStats();
void* p455 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p456 = last_address;
PRINT_POINTER(srealloc(p267,233););
printStats();
void* p457 = last_address;
PRINT_POINTER(srealloc(p328,17););
printStats();
void* p458 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p459 = last_address;
DEBUG_PRINT(sfree(p436););
printStats();
PRINT_POINTER(srealloc(p349,8););
printStats();
void* p460 = last_address;
PRINT_POINTER(srealloc(p396,58););
printStats();
void* p461 = last_address;
PRINT_POINTER(scalloc(16,220););
printStats();
void* p462 = last_address;
PRINT_POINTER(scalloc(40,246););
printStats();
void* p463 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p464 = last_address;
PRINT_POINTER(scalloc(242,154););
printStats();
void* p465 = last_address;
PRINT_POINTER(scalloc(161,225););
printStats();
void* p466 = last_address;
PRINT_POINTER(srealloc(p280,172););
printStats();
void* p467 = last_address;
PRINT_POINTER(srealloc(p269,53););
printStats();
void* p468 = last_address;
PRINT_POINTER(srealloc(p440,86););
printStats();
void* p469 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p470 = last_address;
DEBUG_PRINT(sfree(p366););
printStats();
PRINT_POINTER(scalloc(2,91););
printStats();
void* p471 = last_address;
PRINT_POINTER(scalloc(190,232););
printStats();
void* p472 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p473 = last_address;
DEBUG_PRINT(sfree(p331););
printStats();
DEBUG_PRINT(sfree(p412););
printStats();
PRINT_POINTER(srealloc(p221,40););
printStats();
void* p474 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p475 = last_address;
PRINT_POINTER(scalloc(228,60););
printStats();
void* p476 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p477 = last_address;
PRINT_POINTER(scalloc(176,80););
printStats();
void* p478 = last_address;
PRINT_POINTER(scalloc(102,140););
printStats();
void* p479 = last_address;
PRINT_POINTER(srealloc(p433,204););
printStats();
void* p480 = last_address;
DEBUG_PRINT(sfree(p360););
printStats();
PRINT_POINTER(srealloc(p424,190););
printStats();
void* p481 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p482 = last_address;
DEBUG_PRINT(sfree(p353););
printStats();
PRINT_POINTER(scalloc(182,195););
printStats();
void* p483 = last_address;
DEBUG_PRINT(sfree(p472););
printStats();
PRINT_POINTER(smalloc(136););
printStats();
void* p484 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p485 = last_address;
PRINT_POINTER(srealloc(p482,153););
printStats();
void* p486 = last_address;
PRINT_POINTER(srealloc(p401,108););
printStats();
void* p487 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p488 = last_address;
PRINT_POINTER(srealloc(p481,106););
printStats();
void* p489 = last_address;
PRINT_POINTER(srealloc(p416,157););
printStats();
void* p490 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p491 = last_address;
DEBUG_PRINT(sfree(p319););
printStats();
PRINT_POINTER(smalloc(104););
printStats();
void* p492 = last_address;
PRINT_POINTER(scalloc(238,169););
printStats();
void* p493 = last_address;
PRINT_POINTER(srealloc(p410,189););
printStats();
void* p494 = last_address;
PRINT_POINTER(scalloc(106,104););
printStats();
void* p495 = last_address;
DEBUG_PRINT(sfree(p310););
printStats();
DEBUG_PRINT(sfree(p337););
printStats();
PRINT_POINTER(smalloc(200););
printStats();
void* p496 = last_address;
PRINT_POINTER(srealloc(p292,54););
printStats();
void* p497 = last_address;
DEBUG_PRINT(sfree(p248););
printStats();
PRINT_POINTER(scalloc(16,113););
printStats();
void* p498 = last_address;
PRINT_POINTER(srealloc(p384,208););
printStats();
void* p499 = last_address;
DEBUG_PRINT(sfree(p238););
printStats();
PRINT_POINTER(srealloc(p379,5););
printStats();
void* p500 = last_address;
DEBUG_PRINT(sfree(p393););
printStats();
PRINT_POINTER(srealloc(p242,196););
printStats();
void* p501 = last_address;
PRINT_POINTER(scalloc(3,19););
printStats();
void* p502 = last_address;
DEBUG_PRINT(sfree(p279););
printStats();
DEBUG_PRINT(sfree(p347););
printStats();
DEBUG_PRINT(sfree(p455););
printStats();
PRINT_POINTER(srealloc(p324,137););
printStats();
void* p503 = last_address;
DEBUG_PRINT(sfree(p385););
printStats();
PRINT_POINTER(scalloc(171,113););
printStats();
void* p504 = last_address;
DEBUG_PRINT(sfree(p499););
printStats();
PRINT_POINTER(scalloc(125,234););
printStats();
void* p505 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p506 = last_address;
DEBUG_PRINT(sfree(p291););
printStats();
DEBUG_PRINT(sfree(p146););
printStats();
DEBUG_PRINT(sfree(p402););
printStats();
PRINT_POINTER(scalloc(143,235););
printStats();
void* p507 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p508 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p509 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p510 = last_address;
PRINT_POINTER(srealloc(p475,143););
printStats();
void* p511 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p512 = last_address;
PRINT_POINTER(srealloc(p372,68););
printStats();
void* p513 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p514 = last_address;
PRINT_POINTER(scalloc(86,121););
printStats();
void* p515 = last_address;
PRINT_POINTER(srealloc(p478,70););
printStats();
void* p516 = last_address;
PRINT_POINTER(scalloc(211,87););
printStats();
void* p517 = last_address;
DEBUG_PRINT(sfree(p515););
printStats();
PRINT_POINTER(smalloc(65););
printStats();
void* p518 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p519 = last_address;
PRINT_POINTER(scalloc(164,152););
printStats();
void* p520 = last_address;
DEBUG_PRINT(sfree(p513););
printStats();
PRINT_POINTER(smalloc(136););
printStats();
void* p521 = last_address;
PRINT_POINTER(scalloc(1,78););
printStats();
void* p522 = last_address;
PRINT_POINTER(srealloc(p509,227););
printStats();
void* p523 = last_address;
PRINT_POINTER(scalloc(32,137););
printStats();
void* p524 = last_address;
DEBUG_PRINT(sfree(p439););
printStats();
DEBUG_PRINT(sfree(p404););
printStats();
PRINT_POINTER(smalloc(212););
printStats();
void* p525 = last_address;
DEBUG_PRINT(sfree(p297););
printStats();
PRINT_POINTER(srealloc(p222,86););
printStats();
void* p526 = last_address;
DEBUG_PRINT(sfree(p260););
printStats();
DEBUG_PRINT(sfree(p460););
printStats();
PRINT_POINTER(srealloc(p418,194););
printStats();
void* p527 = last_address;
PRINT_POINTER(srealloc(p518,179););
printStats();
void* p528 = last_address;
PRINT_POINTER(scalloc(71,3););
printStats();
void* p529 = last_address;
DEBUG_PRINT(sfree(p514););
printStats();
PRINT_POINTER(scalloc(107,57););
printStats();
void* p530 = last_address;
PRINT_POINTER(scalloc(113,118););
printStats();
void* p531 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p532 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p533 = last_address;
PRINT_POINTER(scalloc(176,37););
printStats();
void* p534 = last_address;
PRINT_POINTER(scalloc(206,111););
printStats();
void* p535 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p536 = last_address;
DEBUG_PRINT(sfree(p490););
printStats();
PRINT_POINTER(scalloc(7,168););
printStats();
void* p537 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p538 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p539 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p540 = last_address;
PRINT_POINTER(scalloc(63,221););
printStats();
void* p541 = last_address;
PRINT_POINTER(srealloc(p334,93););
printStats();
void* p542 = last_address;
PRINT_POINTER(scalloc(233,94););
printStats();
void* p543 = last_address;
PRINT_POINTER(srealloc(p522,143););
printStats();
void* p544 = last_address;
PRINT_POINTER(srealloc(p527,41););
printStats();
void* p545 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p546 = last_address;
PRINT_POINTER(srealloc(p211,28););
printStats();
void* p547 = last_address;
PRINT_POINTER(scalloc(96,101););
printStats();
void* p548 = last_address;
PRINT_POINTER(scalloc(9,147););
printStats();
void* p549 = last_address;
PRINT_POINTER(scalloc(188,52););
printStats();
void* p550 = last_address;
DEBUG_PRINT(sfree(p390););
printStats();
PRINT_POINTER(srealloc(p177,133););
printStats();
void* p551 = last_address;
PRINT_POINTER(srealloc(p362,119););
printStats();
void* p552 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p553 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p554 = last_address;
PRINT_POINTER(srealloc(p494,63););
printStats();
void* p555 = last_address;
DEBUG_PRINT(sfree(p344););
printStats();
PRINT_POINTER(srealloc(p303,127););
printStats();
void* p556 = last_address;
DEBUG_PRINT(sfree(p504););
printStats();
PRINT_POINTER(srealloc(p521,18););
printStats();
void* p557 = last_address;
PRINT_POINTER(srealloc(p215,212););
printStats();
void* p558 = last_address;
PRINT_POINTER(srealloc(p470,149););
printStats();
void* p559 = last_address;
DEBUG_PRINT(sfree(p487););
printStats();
PRINT_POINTER(srealloc(p454,75););
printStats();
void* p560 = last_address;
PRINT_POINTER(scalloc(135,51););
printStats();
void* p561 = last_address;
PRINT_POINTER(scalloc(237,171););
printStats();
void* p562 = last_address;
PRINT_POINTER(srealloc(p496,247););
printStats();
void* p563 = last_address;
PRINT_POINTER(srealloc(p517,172););
printStats();
void* p564 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p565 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(scalloc(60,88););
printStats();
void* p566 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p567 = last_address;
DEBUG_PRINT(sfree(p560););
printStats();
DEBUG_PRINT(sfree(p477););
printStats();
PRINT_POINTER(scalloc(212,123););
printStats();
void* p568 = last_address;
PRINT_POINTER(scalloc(36,193););
printStats();
void* p569 = last_address;
DEBUG_PRINT(sfree(p363););
printStats();
DEBUG_PRINT(sfree(p489););
printStats();
PRINT_POINTER(srealloc(p427,221););
printStats();
void* p570 = last_address;
PRINT_POINTER(srealloc(p351,18););
printStats();
void* p571 = last_address;
DEBUG_PRINT(sfree(p539););
printStats();
PRINT_POINTER(scalloc(201,90););
printStats();
void* p572 = last_address;
PRINT_POINTER(srealloc(p383,183););
printStats();
void* p573 = last_address;
PRINT_POINTER(srealloc(p492,101););
printStats();
void* p574 = last_address;
PRINT_POINTER(scalloc(91,121););
printStats();
void* p575 = last_address;
PRINT_POINTER(scalloc(147,57););
printStats();
void* p576 = last_address;
PRINT_POINTER(srealloc(p484,209););
printStats();
void* p577 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p578 = last_address;
DEBUG_PRINT(sfree(p563););
printStats();
DEBUG_PRINT(sfree(p463););
printStats();
PRINT_POINTER(smalloc(188););
printStats();
void* p579 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p580 = last_address;
PRINT_POINTER(scalloc(170,46););
printStats();
void* p581 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p582 = last_address;
DEBUG_PRINT(sfree(p486););
printStats();
PRINT_POINTER(smalloc(56););
printStats();
void* p583 = last_address;
PRINT_POINTER(srealloc(p498,190););
printStats();
void* p584 = last_address;
DEBUG_PRINT(sfree(p473););
printStats();
PRINT_POINTER(scalloc(107,206););
printStats();
void* p585 = last_address;
PRINT_POINTER(scalloc(39,12););
printStats();
void* p586 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p587 = last_address;
DEBUG_PRINT(sfree(p422););
printStats();
DEBUG_PRINT(sfree(p471););
printStats();
DEBUG_PRINT(sfree(p459););
printStats();
DEBUG_PRINT(sfree(p562););
printStats();
PRINT_POINTER(srealloc(p467,129););
printStats();
void* p588 = last_address;
DEBUG_PRINT(sfree(p365););
printStats();
PRINT_POINTER(srealloc(p361,75););
printStats();
void* p589 = last_address;
PRINT_POINTER(scalloc(120,4););
printStats();
void* p590 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p591 = last_address;
DEBUG_PRINT(sfree(p388););
printStats();
PRINT_POINTER(scalloc(136,78););
printStats();
void* p592 = last_address;
PRINT_POINTER(srealloc(p488,168););
printStats();
void* p593 = last_address;
PRINT_POINTER(srealloc(p510,40););
printStats();
void* p594 = last_address;
PRINT_POINTER(scalloc(50,175););
printStats();
void* p595 = last_address;
DEBUG_PRINT(sfree(p338););
printStats();
PRINT_POINTER(scalloc(2,25););
printStats();
void* p596 = last_address;
PRINT_POINTER(scalloc(91,41););
printStats();
void* p597 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p598 = last_address;
DEBUG_PRINT(sfree(p434););
printStats();
PRINT_POINTER(srealloc(p398,131););
printStats();
void* p599 = last_address;
DEBUG_PRINT(sfree(p538););
printStats();
PRINT_POINTER(smalloc(21););
printStats();
void* p600 = last_address;
DEBUG_PRINT(sfree(p254););
printStats();
PRINT_POINTER(smalloc(126););
printStats();
void* p601 = last_address;
DEBUG_PRINT(sfree(p535););
printStats();
DEBUG_PRINT(sfree(p428););
printStats();
PRINT_POINTER(smalloc(192););
printStats();
void* p602 = last_address;
DEBUG_PRINT(sfree(p445););
printStats();
PRINT_POINTER(scalloc(246,4););
printStats();
void* p603 = last_address;
PRINT_POINTER(scalloc(36,8););
printStats();
void* p604 = last_address;
PRINT_POINTER(scalloc(228,185););
printStats();
void* p605 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p606 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p607 = last_address;
PRINT_POINTER(srealloc(p602,223););
printStats();
void* p608 = last_address;
PRINT_POINTER(scalloc(37,190););
printStats();
void* p609 = last_address;
DEBUG_PRINT(sfree(p318););
printStats();
PRINT_POINTER(scalloc(103,159););
printStats();
void* p610 = last_address;
DEBUG_PRINT(sfree(p542););
printStats();
PRINT_POINTER(scalloc(88,43););
printStats();
void* p611 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p612 = last_address;
PRINT_POINTER(scalloc(47,222););
printStats();
void* p613 = last_address;
PRINT_POINTER(scalloc(88,157););
printStats();
void* p614 = last_address;
DEBUG_PRINT(sfree(p456););
printStats();
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(smalloc(86););
printStats();
void* p615 = last_address;
PRINT_POINTER(srealloc(p442,235););
printStats();
void* p616 = last_address;
PRINT_POINTER(scalloc(57,171););
printStats();
void* p617 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p618 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p619 = last_address;
DEBUG_PRINT(sfree(p400););
printStats();
PRINT_POINTER(smalloc(143););
printStats();
void* p620 = last_address;
PRINT_POINTER(scalloc(138,125););
printStats();
void* p621 = last_address;
PRINT_POINTER(srealloc(p308,185););
printStats();
void* p622 = last_address;
PRINT_POINTER(srealloc(p601,87););
printStats();
void* p623 = last_address;
DEBUG_PRINT(sfree(p426););
printStats();
PRINT_POINTER(scalloc(153,66););
printStats();
void* p624 = last_address;
PRINT_POINTER(scalloc(193,207););
printStats();
void* p625 = last_address;
PRINT_POINTER(srealloc(p149,12););
printStats();
void* p626 = last_address;
PRINT_POINTER(srealloc(p449,205););
printStats();
void* p627 = last_address;
PRINT_POINTER(scalloc(66,167););
printStats();
void* p628 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p629 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p630 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p631 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p632 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p633 = last_address;
DEBUG_PRINT(sfree(p485););
printStats();
PRINT_POINTER(smalloc(94););
printStats();
void* p634 = last_address;
PRINT_POINTER(srealloc(p598,243););
printStats();
void* p635 = last_address;
DEBUG_PRINT(sfree(p287););
printStats();
DEBUG_PRINT(sfree(p270););
printStats();
DEBUG_PRINT(sfree(p571););
printStats();
PRINT_POINTER(scalloc(44,69););
printStats();
void* p636 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p637 = last_address;
DEBUG_PRINT(sfree(p271););
printStats();
PRINT_POINTER(srealloc(p408,68););
printStats();
void* p638 = last_address;
PRINT_POINTER(scalloc(148,191););
printStats();
void* p639 = last_address;
DEBUG_PRINT(sfree(p631););
printStats();
DEBUG_PRINT(sfree(p556););
printStats();
PRINT_POINTER(smalloc(208););
printStats();
void* p640 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p641 = last_address;
DEBUG_PRINT(sfree(p508););
printStats();
PRINT_POINTER(srealloc(p565,109););
printStats();
void* p642 = last_address;
DEBUG_PRINT(sfree(p468););
printStats();
DEBUG_PRINT(sfree(p417););
printStats();
PRINT_POINTER(scalloc(149,95););
printStats();
void* p643 = last_address;
PRINT_POINTER(scalloc(217,53););
printStats();
void* p644 = last_address;
DEBUG_PRINT(sfree(p519););
printStats();
PRINT_POINTER(smalloc(225););
printStats();
void* p645 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p646 = last_address;
PRINT_POINTER(srealloc(p364,161););
printStats();
void* p647 = last_address;
DEBUG_PRINT(sfree(p617););
printStats();
PRINT_POINTER(smalloc(3););
printStats();
void* p648 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p649 = last_address;
PRINT_POINTER(srealloc(p435,185););
printStats();
void* p650 = last_address;
PRINT_POINTER(srealloc(p497,185););
printStats();
void* p651 = last_address;
PRINT_POINTER(srealloc(p564,149););
printStats();
void* p652 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p653 = last_address;
DEBUG_PRINT(sfree(p650););
printStats();
DEBUG_PRINT(sfree(p622););
printStats();
PRINT_POINTER(smalloc(119););
printStats();
void* p654 = last_address;
DEBUG_PRINT(sfree(p599););
printStats();
DEBUG_PRINT(sfree(p391););
printStats();
DEBUG_PRINT(sfree(p640););
printStats();
DEBUG_PRINT(sfree(p479););
printStats();
PRINT_POINTER(smalloc(78););
printStats();
void* p655 = last_address;
DEBUG_PRINT(sfree(p623););
printStats();
PRINT_POINTER(srealloc(p612,82););
printStats();
void* p656 = last_address;
PRINT_POINTER(srealloc(p600,205););
printStats();
void* p657 = last_address;
PRINT_POINTER(scalloc(160,145););
printStats();
void* p658 = last_address;
PRINT_POINTER(scalloc(117,65););
printStats();
void* p659 = last_address;
DEBUG_PRINT(sfree(p570););
printStats();
DEBUG_PRINT(sfree(p530););
printStats();
PRINT_POINTER(srealloc(p588,75););
printStats();
void* p660 = last_address;
DEBUG_PRINT(sfree(p558););
printStats();
PRINT_POINTER(scalloc(45,67););
printStats();
void* p661 = last_address;
PRINT_POINTER(scalloc(73,164););
printStats();
void* p662 = last_address;
PRINT_POINTER(scalloc(224,91););
printStats();
void* p663 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p664 = last_address;
PRINT_POINTER(srealloc(p608,1););
printStats();
void* p665 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p666 = last_address;
PRINT_POINTER(scalloc(58,248););
printStats();
void* p667 = last_address;
PRINT_POINTER(scalloc(142,223););
printStats();
void* p668 = last_address;
PRINT_POINTER(scalloc(68,142););
printStats();
void* p669 = last_address;
PRINT_POINTER(scalloc(92,8););
printStats();
void* p670 = last_address;
PRINT_POINTER(scalloc(148,134););
printStats();
void* p671 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p672 = last_address;
PRINT_POINTER(scalloc(55,155););
printStats();
void* p673 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p674 = last_address;
PRINT_POINTER(scalloc(41,13););
printStats();
void* p675 = last_address;
PRINT_POINTER(srealloc(p431,88););
printStats();
void* p676 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p677 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p678 = last_address;
PRINT_POINTER(srealloc(p262,113););
printStats();
void* p679 = last_address;
PRINT_POINTER(scalloc(77,77););
printStats();
void* p680 = last_address;
DEBUG_PRINT(sfree(p548););
printStats();
DEBUG_PRINT(sfree(p679););
printStats();
DEBUG_PRINT(sfree(p673););
printStats();
PRINT_POINTER(scalloc(67,127););
printStats();
void* p681 = last_address;
DEBUG_PRINT(sfree(p585););
printStats();
PRINT_POINTER(scalloc(128,118););
printStats();
void* p682 = last_address;
DEBUG_PRINT(sfree(p580););
printStats();
PRINT_POINTER(scalloc(23,194););
printStats();
void* p683 = last_address;
DEBUG_PRINT(sfree(p536););
printStats();
DEBUG_PRINT(sfree(p607););
printStats();
PRINT_POINTER(smalloc(57););
printStats();
void* p684 = last_address;
DEBUG_PRINT(sfree(p446););
printStats();
DEBUG_PRINT(sfree(p503););
printStats();
PRINT_POINTER(scalloc(34,20););
printStats();
void* p685 = last_address;
PRINT_POINTER(srealloc(p656,68););
printStats();
void* p686 = last_address;
PRINT_POINTER(srealloc(p648,15););
printStats();
void* p687 = last_address;
PRINT_POINTER(scalloc(121,218););
printStats();
void* p688 = last_address;
DEBUG_PRINT(sfree(p448););
printStats();
PRINT_POINTER(scalloc(185,157););
printStats();
void* p689 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p690 = last_address;
DEBUG_PRINT(sfree(p359););
printStats();
PRINT_POINTER(srealloc(p516,169););
printStats();
void* p691 = last_address;
PRINT_POINTER(scalloc(219,42););
printStats();
void* p692 = last_address;
DEBUG_PRINT(sfree(p637););
printStats();
DEBUG_PRINT(sfree(p655););
printStats();
PRINT_POINTER(srealloc(p572,230););
printStats();
void* p693 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p694 = last_address;
PRINT_POINTER(srealloc(p627,162););
printStats();
void* p695 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p696 = last_address;
DEBUG_PRINT(sfree(p466););
printStats();
PRINT_POINTER(srealloc(p480,238););
printStats();
void* p697 = last_address;
PRINT_POINTER(srealloc(p594,57););
printStats();
void* p698 = last_address;
PRINT_POINTER(scalloc(150,236););
printStats();
void* p699 = last_address;
PRINT_POINTER(srealloc(p690,61););
printStats();
void* p700 = last_address;
PRINT_POINTER(srealloc(p649,101););
printStats();
void* p701 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p702 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p703 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p704 = last_address;
PRINT_POINTER(srealloc(p642,88););
printStats();
void* p705 = last_address;
DEBUG_PRINT(sfree(p266););
printStats();
DEBUG_PRINT(sfree(p447););
printStats();
DEBUG_PRINT(sfree(p543););
printStats();
PRINT_POINTER(scalloc(194,86););
printStats();
void* p706 = last_address;
PRINT_POINTER(scalloc(158,96););
printStats();
void* p707 = last_address;
PRINT_POINTER(srealloc(p453,143););
printStats();
void* p708 = last_address;
PRINT_POINTER(srealloc(p566,41););
printStats();
void* p709 = last_address;
DEBUG_PRINT(sfree(p394););
printStats();
PRINT_POINTER(srealloc(p632,141););
printStats();
void* p710 = last_address;
DEBUG_PRINT(sfree(p376););
printStats();
PRINT_POINTER(scalloc(165,23););
printStats();
void* p711 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p712 = last_address;
DEBUG_PRINT(sfree(p441););
printStats();
PRINT_POINTER(srealloc(p613,196););
printStats();
void* p713 = last_address;
PRINT_POINTER(srealloc(p553,19););
printStats();
void* p714 = last_address;
PRINT_POINTER(srealloc(p592,41););
printStats();
void* p715 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p716 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p717 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p718 = last_address;
DEBUG_PRINT(sfree(p593););
printStats();
PRINT_POINTER(scalloc(151,33););
printStats();
void* p719 = last_address;
PRINT_POINTER(srealloc(p618,197););
printStats();
void* p720 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p721 = last_address;
DEBUG_PRINT(sfree(p354););
printStats();
PRINT_POINTER(scalloc(185,84););
printStats();
void* p722 = last_address;
PRINT_POINTER(srealloc(p643,117););
printStats();
void* p723 = last_address;
PRINT_POINTER(scalloc(208,230););
printStats();
void* p724 = last_address;
PRINT_POINTER(scalloc(8,36););
printStats();
void* p725 = last_address;
PRINT_POINTER(scalloc(119,87););
printStats();
void* p726 = last_address;
DEBUG_PRINT(sfree(p550););
printStats();
DEBUG_PRINT(sfree(p554););
printStats();
PRINT_POINTER(srealloc(p369,196););
printStats();
void* p727 = last_address;
DEBUG_PRINT(sfree(p616););
printStats();
PRINT_POINTER(srealloc(p327,210););
printStats();
void* p728 = last_address;
PRINT_POINTER(srealloc(p720,202););
printStats();
void* p729 = last_address;
PRINT_POINTER(srealloc(p255,116););
printStats();
void* p730 = last_address;
DEBUG_PRINT(sfree(p501););
printStats();
DEBUG_PRINT(sfree(p694););
printStats();
PRINT_POINTER(scalloc(59,173););
printStats();
void* p731 = last_address;
PRINT_POINTER(srealloc(p452,194););
printStats();
void* p732 = last_address;
PRINT_POINTER(scalloc(124,58););
printStats();
void* p733 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p734 = last_address;
PRINT_POINTER(scalloc(152,99););
printStats();
void* p735 = last_address;
PRINT_POINTER(scalloc(22,62););
printStats();
void* p736 = last_address;
DEBUG_PRINT(sfree(p653););
printStats();
DEBUG_PRINT(sfree(p685););
printStats();
DEBUG_PRINT(sfree(p629););
printStats();
PRINT_POINTER(srealloc(p713,218););
printStats();
void* p737 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p738 = last_address;
DEBUG_PRINT(sfree(p664););
printStats();
PRINT_POINTER(scalloc(55,137););
printStats();
void* p739 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p740 = last_address;
PRINT_POINTER(srealloc(p671,249););
printStats();
void* p741 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
PRINT_POINTER(srealloc(p333,119););
printStats();
void* p742 = last_address;
DEBUG_PRINT(sfree(p461););
printStats();
PRINT_POINTER(scalloc(87,102););
printStats();
void* p743 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p744 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p745 = last_address;
PRINT_POINTER(srealloc(p737,13););
printStats();
void* p746 = last_address;
PRINT_POINTER(srealloc(p663,16););
printStats();
void* p747 = last_address;
DEBUG_PRINT(sfree(p534););
printStats();
PRINT_POINTER(srealloc(p597,128););
printStats();
void* p748 = last_address;
PRINT_POINTER(srealloc(p707,108););
printStats();
void* p749 = last_address;
PRINT_POINTER(srealloc(p589,124););
printStats();
void* p750 = last_address;
DEBUG_PRINT(sfree(p568););
printStats();
PRINT_POINTER(scalloc(17,158););
printStats();
void* p751 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p752 = last_address;
PRINT_POINTER(scalloc(179,111););
printStats();
void* p753 = last_address;
PRINT_POINTER(srealloc(p625,175););
printStats();
void* p754 = last_address;
PRINT_POINTER(srealloc(p197,116););
printStats();
void* p755 = last_address;
PRINT_POINTER(scalloc(151,147););
printStats();
void* p756 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p757 = last_address;
DEBUG_PRINT(sfree(p670););
printStats();
PRINT_POINTER(smalloc(151););
printStats();
void* p758 = last_address;
PRINT_POINTER(scalloc(28,137););
printStats();
void* p759 = last_address;
DEBUG_PRINT(sfree(p290););
printStats();
DEBUG_PRINT(sfree(p624););
printStats();
DEBUG_PRINT(sfree(p741););
printStats();
PRINT_POINTER(scalloc(145,240););
printStats();
void* p760 = last_address;
DEBUG_PRINT(sfree(p757););
printStats();
PRINT_POINTER(srealloc(p555,3););
printStats();
void* p761 = last_address;
DEBUG_PRINT(sfree(p667););
printStats();
PRINT_POINTER(smalloc(197););
printStats();
void* p762 = last_address;
DEBUG_PRINT(sfree(p724););
printStats();
PRINT_POINTER(scalloc(22,105););
printStats();
void* p763 = last_address;
DEBUG_PRINT(sfree(p450););
printStats();
PRINT_POINTER(scalloc(26,244););
printStats();
void* p764 = last_address;
PRINT_POINTER(srealloc(p373,116););
printStats();
void* p765 = last_address;
PRINT_POINTER(scalloc(34,39););
printStats();
void* p766 = last_address;
PRINT_POINTER(srealloc(p688,172););
printStats();
void* p767 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p768 = last_address;
DEBUG_PRINT(sfree(p541););
printStats();
PRINT_POINTER(scalloc(125,116););
printStats();
void* p769 = last_address;
PRINT_POINTER(srealloc(p742,188););
printStats();
void* p770 = last_address;
PRINT_POINTER(scalloc(236,5););
printStats();
void* p771 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p772 = last_address;
PRINT_POINTER(scalloc(68,13););
printStats();
void* p773 = last_address;
DEBUG_PRINT(sfree(p677););
printStats();
DEBUG_PRINT(sfree(p573););
printStats();
PRINT_POINTER(srealloc(p728,91););
printStats();
void* p774 = last_address;
DEBUG_PRINT(sfree(p749););
printStats();
PRINT_POINTER(scalloc(173,143););
printStats();
void* p775 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p776 = last_address;
PRINT_POINTER(scalloc(232,9););
printStats();
void* p777 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p778 = last_address;
PRINT_POINTER(srealloc(p346,146););
printStats();
void* p779 = last_address;
DEBUG_PRINT(sfree(p502););
printStats();
PRINT_POINTER(scalloc(150,182););
printStats();
void* p780 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p781 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p782 = last_address;
DEBUG_PRINT(sfree(p750););
printStats();
PRINT_POINTER(smalloc(184););
printStats();
void* p783 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p784 = last_address;
DEBUG_PRINT(sfree(p389););
printStats();
DEBUG_PRINT(sfree(p770););
printStats();
PRINT_POINTER(srealloc(p683,0););
printStats();
void* p785 = last_address;
DEBUG_PRINT(sfree(p552););
printStats();
PRINT_POINTER(srealloc(p771,171););
printStats();
void* p786 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p787 = last_address;
PRINT_POINTER(srealloc(p505,184););
printStats();
void* p788 = last_address;
DEBUG_PRINT(sfree(p531););
printStats();
PRINT_POINTER(srealloc(p715,17););
printStats();
void* p789 = last_address;
DEBUG_PRINT(sfree(p380););
printStats();
PRINT_POINTER(scalloc(29,204););
printStats();
void* p790 = last_address;
DEBUG_PRINT(sfree(p735););
printStats();
PRINT_POINTER(srealloc(p405,175););
printStats();
void* p791 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p792 = last_address;
PRINT_POINTER(scalloc(21,50););
printStats();
void* p793 = last_address;
PRINT_POINTER(srealloc(p635,242););
printStats();
void* p794 = last_address;
DEBUG_PRINT(sfree(p551););
printStats();
DEBUG_PRINT(sfree(p251););
printStats();
DEBUG_PRINT(sfree(p586););
printStats();
PRINT_POINTER(srealloc(p425,1););
printStats();
void* p795 = last_address;
PRINT_POINTER(srealloc(p457,26););
printStats();
void* p796 = last_address;
PRINT_POINTER(scalloc(98,12););
printStats();
void* p797 = last_address;
PRINT_POINTER(srealloc(p465,224););
printStats();
void* p798 = last_address;
PRINT_POINTER(srealloc(p657,199););
printStats();
void* p799 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p800 = last_address;
PRINT_POINTER(srealloc(p654,58););
printStats();
void* p801 = last_address;
PRINT_POINTER(scalloc(232,178););
printStats();
void* p802 = last_address;
PRINT_POINTER(srealloc(p802,32););
printStats();
void* p803 = last_address;
PRINT_POINTER(srealloc(p567,178););
printStats();
void* p804 = last_address;
PRINT_POINTER(scalloc(23,226););
printStats();
void* p805 = last_address;
PRINT_POINTER(scalloc(246,121););
printStats();
void* p806 = last_address;
PRINT_POINTER(srealloc(p761,17););
printStats();
void* p807 = last_address;
PRINT_POINTER(srealloc(p803,53););
printStats();
void* p808 = last_address;
DEBUG_PRINT(sfree(p438););
printStats();
PRINT_POINTER(srealloc(p794,75););
printStats();
void* p809 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p810 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p811 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p812 = last_address;
PRINT_POINTER(srealloc(p695,216););
printStats();
void* p813 = last_address;
PRINT_POINTER(srealloc(p628,111););
printStats();
void* p814 = last_address;
PRINT_POINTER(srealloc(p813,142););
printStats();
void* p815 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p816 = last_address;
PRINT_POINTER(srealloc(p714,58););
printStats();
void* p817 = last_address;
PRINT_POINTER(srealloc(p710,248););
printStats();
void* p818 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p819 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p820 = last_address;
PRINT_POINTER(scalloc(4,168););
printStats();
void* p821 = last_address;
DEBUG_PRINT(sfree(p520););
printStats();
PRINT_POINTER(srealloc(p739,31););
printStats();
void* p822 = last_address;
PRINT_POINTER(srealloc(p429,237););
printStats();
void* p823 = last_address;
PRINT_POINTER(scalloc(175,87););
printStats();
void* p824 = last_address;
PRINT_POINTER(srealloc(p464,196););
printStats();
void* p825 = last_address;
PRINT_POINTER(scalloc(90,88););
printStats();
void* p826 = last_address;
PRINT_POINTER(srealloc(p645,1););
printStats();
void* p827 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p828 = last_address;
DEBUG_PRINT(sfree(p754););
printStats();
PRINT_POINTER(srealloc(p636,245););
printStats();
void* p829 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p830 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p831 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p832 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p833 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p834 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p835 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p836 = last_address;
PRINT_POINTER(srealloc(p605,231););
printStats();
void* p837 = last_address;
DEBUG_PRINT(sfree(p811););
printStats();
PRINT_POINTER(scalloc(51,192););
printStats();
void* p838 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p839 = last_address;
PRINT_POINTER(scalloc(22,2););
printStats();
void* p840 = last_address;
PRINT_POINTER(srealloc(p610,69););
printStats();
void* p841 = last_address;
DEBUG_PRINT(sfree(p168););
printStats();
PRINT_POINTER(srealloc(p722,3););
printStats();
void* p842 = last_address;
PRINT_POINTER(srealloc(p561,78););
printStats();
void* p843 = last_address;
PRINT_POINTER(scalloc(43,232););
printStats();
void* p844 = last_address;
DEBUG_PRINT(sfree(p458););
printStats();
PRINT_POINTER(srealloc(p620,183););
printStats();
void* p845 = last_address;
PRINT_POINTER(scalloc(224,100););
printStats();
void* p846 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p847 = last_address;
DEBUG_PRINT(sfree(p793););
printStats();
DEBUG_PRINT(sfree(p787););
printStats();
PRINT_POINTER(scalloc(92,86););
printStats();
void* p848 = last_address;
DEBUG_PRINT(sfree(p841););
printStats();
PRINT_POINTER(srealloc(p752,139););
printStats();
void* p849 = last_address;
DEBUG_PRINT(sfree(p832););
printStats();
PRINT_POINTER(smalloc(31););
printStats();
void* p850 = last_address;
PRINT_POINTER(scalloc(22,41););
printStats();
void* p851 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p852 = last_address;
PRINT_POINTER(srealloc(p775,140););
printStats();
void* p853 = last_address;
PRINT_POINTER(scalloc(166,121););
printStats();
void* p854 = last_address;
PRINT_POINTER(scalloc(166,173););
printStats();
void* p855 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p856 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p857 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p858 = last_address;
DEBUG_PRINT(sfree(p806););
printStats();
PRINT_POINTER(srealloc(p544,221););
printStats();
void* p859 = last_address;
PRINT_POINTER(scalloc(80,160););
printStats();
void* p860 = last_address;
PRINT_POINTER(scalloc(87,42););
printStats();
void* p861 = last_address;
PRINT_POINTER(srealloc(p619,151););
printStats();
void* p862 = last_address;
DEBUG_PRINT(sfree(p812););
printStats();
PRINT_POINTER(smalloc(22););
printStats();
void* p863 = last_address;
PRINT_POINTER(scalloc(57,19););
printStats();
void* p864 = last_address;
PRINT_POINTER(scalloc(118,163););
printStats();
void* p865 = last_address;
DEBUG_PRINT(sfree(p854););
printStats();
PRINT_POINTER(scalloc(68,106););
printStats();
void* p866 = last_address;
PRINT_POINTER(srealloc(p678,159););
printStats();
void* p867 = last_address;
DEBUG_PRINT(sfree(p816););
printStats();
PRINT_POINTER(scalloc(157,98););
printStats();
void* p868 = last_address;
DEBUG_PRINT(sfree(p547););
printStats();
PRINT_POINTER(scalloc(68,19););
printStats();
void* p869 = last_address;
PRINT_POINTER(scalloc(237,124););
printStats();
void* p870 = last_address;
DEBUG_PRINT(sfree(p414););
printStats();
PRINT_POINTER(smalloc(182););
printStats();
void* p871 = last_address;
PRINT_POINTER(scalloc(225,13););
printStats();
void* p872 = last_address;
DEBUG_PRINT(sfree(p833););
printStats();
PRINT_POINTER(smalloc(128););
printStats();
void* p873 = last_address;
PRINT_POINTER(scalloc(11,77););
printStats();
void* p874 = last_address;
DEBUG_PRINT(sfree(p873););
printStats();
PRINT_POINTER(smalloc(54););
printStats();
void* p875 = last_address;
DEBUG_PRINT(sfree(p859););
printStats();
PRINT_POINTER(srealloc(p800,126););
printStats();
void* p876 = last_address;
PRINT_POINTER(scalloc(83,103););
printStats();
void* p877 = last_address;
PRINT_POINTER(scalloc(222,19););
printStats();
void* p878 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p879 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p880 = last_address;
DEBUG_PRINT(sfree(p604););
printStats();
PRINT_POINTER(srealloc(p500,152););
printStats();
void* p881 = last_address;
PRINT_POINTER(scalloc(176,0););
printStats();
void* p882 = last_address;
PRINT_POINTER(srealloc(p818,74););
printStats();
void* p883 = last_address;
PRINT_POINTER(scalloc(164,66););
printStats();
void* p884 = last_address;
PRINT_POINTER(scalloc(57,215););
printStats();
void* p885 = last_address;
PRINT_POINTER(srealloc(p229,241););
printStats();
void* p886 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p887 = last_address;
PRINT_POINTER(srealloc(p687,222););
printStats();
void* p888 = last_address;
PRINT_POINTER(srealloc(p540,213););
printStats();
void* p889 = last_address;
DEBUG_PRINT(sfree(p524););
printStats();
PRINT_POINTER(scalloc(202,222););
printStats();
void* p890 = last_address;
PRINT_POINTER(scalloc(15,182););
printStats();
void* p891 = last_address;
PRINT_POINTER(srealloc(p476,39););
printStats();
void* p892 = last_address;
PRINT_POINTER(srealloc(p845,187););
printStats();
void* p893 = last_address;
DEBUG_PRINT(sfree(p755););
printStats();
PRINT_POINTER(smalloc(15););
printStats();
void* p894 = last_address;
PRINT_POINTER(srealloc(p778,195););
printStats();
void* p895 = last_address;
PRINT_POINTER(srealloc(p529,133););
printStats();
void* p896 = last_address;
PRINT_POINTER(srealloc(p578,215););
printStats();
void* p897 = last_address;
PRINT_POINTER(scalloc(133,38););
printStats();
void* p898 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p899 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p900 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p901 = last_address;
PRINT_POINTER(scalloc(121,115););
printStats();
void* p902 = last_address;
PRINT_POINTER(scalloc(51,141););
printStats();
void* p903 = last_address;
PRINT_POINTER(srealloc(p836,88););
printStats();
void* p904 = last_address;
PRINT_POINTER(scalloc(34,96););
printStats();
void* p905 = last_address;
PRINT_POINTER(srealloc(p575,89););
printStats();
void* p906 = last_address;
DEBUG_PRINT(sfree(p304););
printStats();
PRINT_POINTER(srealloc(p451,42););
printStats();
void* p907 = last_address;
DEBUG_PRINT(sfree(p889););
printStats();
PRINT_POINTER(scalloc(174,113););
printStats();
void* p908 = last_address;
DEBUG_PRINT(sfree(p587););
printStats();
PRINT_POINTER(scalloc(216,45););
printStats();
void* p909 = last_address;
PRINT_POINTER(scalloc(244,160););
printStats();
void* p910 = last_address;
PRINT_POINTER(scalloc(63,137););
printStats();
void* p911 = last_address;
PRINT_POINTER(srealloc(p644,104););
printStats();
void* p912 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p913 = last_address;
PRINT_POINTER(scalloc(45,18););
printStats();
void* p914 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p915 = last_address;
PRINT_POINTER(srealloc(p697,199););
printStats();
void* p916 = last_address;
PRINT_POINTER(scalloc(237,162););
printStats();
void* p917 = last_address;
DEBUG_PRINT(sfree(p899););
printStats();
PRINT_POINTER(srealloc(p703,45););
printStats();
void* p918 = last_address;
DEBUG_PRINT(sfree(p888););
printStats();
PRINT_POINTER(scalloc(93,95););
printStats();
void* p919 = last_address;
DEBUG_PRINT(sfree(p577););
printStats();
PRINT_POINTER(smalloc(39););
printStats();
void* p920 = last_address;
PRINT_POINTER(srealloc(p733,230););
printStats();
void* p921 = last_address;
DEBUG_PRINT(sfree(p621););
printStats();
DEBUG_PRINT(sfree(p528););
printStats();
DEBUG_PRINT(sfree(p582););
printStats();
PRINT_POINTER(srealloc(p848,57););
printStats();
void* p922 = last_address;
PRINT_POINTER(srealloc(p917,50););
printStats();
void* p923 = last_address;
DEBUG_PRINT(sfree(p779););
printStats();
PRINT_POINTER(scalloc(57,185););
printStats();
void* p924 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p925 = last_address;
PRINT_POINTER(srealloc(p891,91););
printStats();
void* p926 = last_address;
DEBUG_PRINT(sfree(p705););
printStats();
DEBUG_PRINT(sfree(p878););
printStats();
PRINT_POINTER(srealloc(p751,2););
printStats();
void* p927 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p928 = last_address;
PRINT_POINTER(srealloc(p512,109););
printStats();
void* p929 = last_address;
DEBUG_PRINT(sfree(p590););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p930 = last_address;
DEBUG_PRINT(sfree(p858););
printStats();
DEBUG_PRINT(sfree(p814););
printStats();
DEBUG_PRINT(sfree(p526););
printStats();
DEBUG_PRINT(sfree(p647););
printStats();
PRINT_POINTER(srealloc(p881,107););
printStats();
void* p931 = last_address;
DEBUG_PRINT(sfree(p680););
printStats();
DEBUG_PRINT(sfree(p368););
printStats();
PRINT_POINTER(srealloc(p399,110););
printStats();
void* p932 = last_address;
PRINT_POINTER(scalloc(98,38););
printStats();
void* p933 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p934 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p935 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p936 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p937 = last_address;
PRINT_POINTER(scalloc(140,72););
printStats();
void* p938 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p939 = last_address;
PRINT_POINTER(scalloc(238,204););
printStats();
void* p940 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p941 = last_address;
PRINT_POINTER(srealloc(p759,181););
printStats();
void* p942 = last_address;
PRINT_POINTER(scalloc(196,11););
printStats();
void* p943 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p944 = last_address;
DEBUG_PRINT(sfree(p851););
printStats();
PRINT_POINTER(scalloc(97,136););
printStats();
void* p945 = last_address;
DEBUG_PRINT(sfree(p885););
printStats();
PRINT_POINTER(scalloc(222,49););
printStats();
void* p946 = last_address;
DEBUG_PRINT(sfree(p918););
printStats();
DEBUG_PRINT(sfree(p721););
printStats();
PRINT_POINTER(srealloc(p579,35););
printStats();
void* p947 = last_address;
PRINT_POINTER(scalloc(35,224););
printStats();
void* p948 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p949 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p950 = last_address;
DEBUG_PRINT(sfree(p375););
printStats();
PRINT_POINTER(srealloc(p934,106););
printStats();
void* p951 = last_address;
PRINT_POINTER(srealloc(p880,22););
printStats();
void* p952 = last_address;
PRINT_POINTER(srealloc(p767,201););
printStats();
void* p953 = last_address;
PRINT_POINTER(srealloc(p850,2););
printStats();
void* p954 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p955 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p956 = last_address;
PRINT_POINTER(scalloc(188,7););
printStats();
void* p957 = last_address;
PRINT_POINTER(scalloc(163,87););
printStats();
void* p958 = last_address;
DEBUG_PRINT(sfree(p819););
printStats();
PRINT_POINTER(smalloc(129););
printStats();
void* p959 = last_address;
DEBUG_PRINT(sfree(p611););
printStats();
PRINT_POINTER(srealloc(p684,154););
printStats();
void* p960 = last_address;
PRINT_POINTER(srealloc(p826,128););
printStats();
void* p961 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p962 = last_address;
DEBUG_PRINT(sfree(p596););
printStats();
PRINT_POINTER(scalloc(175,58););
printStats();
void* p963 = last_address;
PRINT_POINTER(scalloc(141,28););
printStats();
void* p964 = last_address;
PRINT_POINTER(scalloc(33,62););
printStats();
void* p965 = last_address;
PRINT_POINTER(srealloc(p855,57););
printStats();
void* p966 = last_address;
PRINT_POINTER(scalloc(81,212););
printStats();
void* p967 = last_address;
PRINT_POINTER(scalloc(94,78););
printStats();
void* p968 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p969 = last_address;
PRINT_POINTER(srealloc(p675,46););
printStats();
void* p970 = last_address;
PRINT_POINTER(scalloc(202,133););
printStats();
void* p971 = last_address;
DEBUG_PRINT(sfree(p583););
printStats();
PRINT_POINTER(scalloc(125,91););
printStats();
void* p972 = last_address;
PRINT_POINTER(scalloc(226,59););
printStats();
void* p973 = last_address;
PRINT_POINTER(scalloc(82,30););
printStats();
void* p974 = last_address;
PRINT_POINTER(scalloc(195,168););
printStats();
void* p975 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p976 = last_address;
PRINT_POINTER(scalloc(64,131););
printStats();
void* p977 = last_address;
PRINT_POINTER(scalloc(2,73););
printStats();
void* p978 = last_address;
PRINT_POINTER(srealloc(p595,34););
printStats();
void* p979 = last_address;
DEBUG_PRINT(sfree(p892););
printStats();
PRINT_POINTER(smalloc(149););
printStats();
void* p980 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p981 = last_address;
PRINT_POINTER(srealloc(p796,8););
printStats();
void* p982 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p983 = last_address;
PRINT_POINTER(srealloc(p909,70););
printStats();
void* p984 = last_address;
PRINT_POINTER(scalloc(80,6););
printStats();
void* p985 = last_address;
DEBUG_PRINT(sfree(p817););
printStats();
PRINT_POINTER(scalloc(4,132););
printStats();
void* p986 = last_address;
PRINT_POINTER(scalloc(186,135););
printStats();
void* p987 = last_address;
DEBUG_PRINT(sfree(p966););
printStats();
DEBUG_PRINT(sfree(p756););
printStats();
PRINT_POINTER(srealloc(p868,115););
printStats();
void* p988 = last_address;
PRINT_POINTER(scalloc(90,137););
printStats();
void* p989 = last_address;
PRINT_POINTER(srealloc(p935,160););
printStats();
void* p990 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p991 = last_address;
PRINT_POINTER(scalloc(218,187););
printStats();
void* p992 = last_address;
PRINT_POINTER(scalloc(193,77););
printStats();
void* p993 = last_address;
PRINT_POINTER(srealloc(p987,64););
printStats();
void* p994 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p995 = last_address;
PRINT_POINTER(scalloc(40,205););
printStats();
void* p996 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p997 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p998 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p999 = last_address;
PRINT_POINTER(srealloc(p932,25););
printStats();
void* p1000 = last_address;
PRINT_POINTER(srealloc(p835,216););
printStats();
void* p1001 = last_address;
PRINT_POINTER(scalloc(97,182););
printStats();
void* p1002 = last_address;
PRINT_POINTER(srealloc(p823,95););
printStats();
void* p1003 = last_address;
}
