#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(170););
printStats();
void* p0 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p1 = last_address;
PRINT_POINTER(srealloc(p1,12););
printStats();
void* p2 = last_address;
PRINT_POINTER(srealloc(p0,161););
printStats();
void* p3 = last_address;
PRINT_POINTER(scalloc(40,150););
printStats();
void* p4 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
PRINT_POINTER(srealloc(p2,50););
printStats();
void* p5 = last_address;
PRINT_POINTER(srealloc(p3,140););
printStats();
void* p6 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p7 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
PRINT_POINTER(scalloc(74,50););
printStats();
void* p8 = last_address;
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(scalloc(108,140););
printStats();
void* p9 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p10 = last_address;
PRINT_POINTER(scalloc(144,5););
printStats();
void* p11 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
PRINT_POINTER(scalloc(149,42););
printStats();
void* p12 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p13 = last_address;
DEBUG_PRINT(sfree(p12););
printStats();
PRINT_POINTER(scalloc(247,232););
printStats();
void* p14 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(srealloc(p6,34););
printStats();
void* p15 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(smalloc(216););
printStats();
void* p16 = last_address;
PRINT_POINTER(scalloc(85,211););
printStats();
void* p17 = last_address;
DEBUG_PRINT(sfree(p10););
printStats();
PRINT_POINTER(scalloc(221,149););
printStats();
void* p18 = last_address;
PRINT_POINTER(scalloc(125,147););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p20 = last_address;
PRINT_POINTER(scalloc(174,238););
printStats();
void* p21 = last_address;
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(srealloc(p13,234););
printStats();
void* p22 = last_address;
PRINT_POINTER(srealloc(p22,52););
printStats();
void* p23 = last_address;
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(smalloc(223););
printStats();
void* p24 = last_address;
PRINT_POINTER(srealloc(p9,129););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(105,39););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p20,126););
printStats();
void* p27 = last_address;
PRINT_POINTER(srealloc(p27,184););
printStats();
void* p28 = last_address;
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(scalloc(220,100););
printStats();
void* p29 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(smalloc(43););
printStats();
void* p30 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p31 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
DEBUG_PRINT(sfree(p23););
printStats();
PRINT_POINTER(srealloc(p14,216););
printStats();
void* p32 = last_address;
PRINT_POINTER(scalloc(247,13););
printStats();
void* p33 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p34 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p35 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p36 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(237,223););
printStats();
void* p38 = last_address;
PRINT_POINTER(scalloc(182,20););
printStats();
void* p39 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p40 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p41 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p42 = last_address;
PRINT_POINTER(scalloc(234,120););
printStats();
void* p43 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p44 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p45 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p46 = last_address;
PRINT_POINTER(srealloc(p19,115););
printStats();
void* p47 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
PRINT_POINTER(smalloc(224););
printStats();
void* p48 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p49 = last_address;
PRINT_POINTER(scalloc(35,169););
printStats();
void* p50 = last_address;
PRINT_POINTER(srealloc(p47,21););
printStats();
void* p51 = last_address;
PRINT_POINTER(scalloc(149,48););
printStats();
void* p52 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
DEBUG_PRINT(sfree(p26););
printStats();
PRINT_POINTER(smalloc(31););
printStats();
void* p53 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
PRINT_POINTER(scalloc(125,46););
printStats();
void* p54 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p55 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p56 = last_address;
PRINT_POINTER(srealloc(p51,215););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(136,144););
printStats();
void* p58 = last_address;
DEBUG_PRINT(sfree(p32););
printStats();
PRINT_POINTER(srealloc(p54,113););
printStats();
void* p59 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p60 = last_address;
DEBUG_PRINT(sfree(p30););
printStats();
PRINT_POINTER(scalloc(148,214););
printStats();
void* p61 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p62 = last_address;
PRINT_POINTER(srealloc(p25,114););
printStats();
void* p63 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p64 = last_address;
DEBUG_PRINT(sfree(p52););
printStats();
DEBUG_PRINT(sfree(p44););
printStats();
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(scalloc(249,157););
printStats();
void* p65 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p66 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p67 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p68 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(smalloc(70););
printStats();
void* p69 = last_address;
PRINT_POINTER(srealloc(p36,139););
printStats();
void* p70 = last_address;
PRINT_POINTER(srealloc(p42,26););
printStats();
void* p71 = last_address;
PRINT_POINTER(srealloc(p49,229););
printStats();
void* p72 = last_address;
PRINT_POINTER(scalloc(81,136););
printStats();
void* p73 = last_address;
PRINT_POINTER(scalloc(206,23););
printStats();
void* p74 = last_address;
PRINT_POINTER(srealloc(p74,0););
printStats();
void* p75 = last_address;
PRINT_POINTER(srealloc(p63,199););
printStats();
void* p76 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p77 = last_address;
PRINT_POINTER(srealloc(p71,5););
printStats();
void* p78 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p79 = last_address;
DEBUG_PRINT(sfree(p57););
printStats();
DEBUG_PRINT(sfree(p59););
printStats();
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(scalloc(53,83););
printStats();
void* p80 = last_address;
DEBUG_PRINT(sfree(p68););
printStats();
PRINT_POINTER(scalloc(100,165););
printStats();
void* p81 = last_address;
PRINT_POINTER(scalloc(175,75););
printStats();
void* p82 = last_address;
PRINT_POINTER(scalloc(186,99););
printStats();
void* p83 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(srealloc(p80,129););
printStats();
void* p84 = last_address;
PRINT_POINTER(srealloc(p64,138););
printStats();
void* p85 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p86 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(srealloc(p67,87););
printStats();
void* p87 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p88 = last_address;
DEBUG_PRINT(sfree(p56););
printStats();
PRINT_POINTER(smalloc(83););
printStats();
void* p89 = last_address;
PRINT_POINTER(scalloc(59,34););
printStats();
void* p90 = last_address;
PRINT_POINTER(srealloc(p58,110););
printStats();
void* p91 = last_address;
PRINT_POINTER(scalloc(68,193););
printStats();
void* p92 = last_address;
PRINT_POINTER(srealloc(p69,198););
printStats();
void* p93 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p94 = last_address;
PRINT_POINTER(scalloc(172,219););
printStats();
void* p95 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p96 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p97 = last_address;
PRINT_POINTER(scalloc(97,31););
printStats();
void* p98 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
PRINT_POINTER(scalloc(194,150););
printStats();
void* p99 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p100 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p101 = last_address;
PRINT_POINTER(srealloc(p39,81););
printStats();
void* p102 = last_address;
PRINT_POINTER(scalloc(248,202););
printStats();
void* p103 = last_address;
PRINT_POINTER(scalloc(124,231););
printStats();
void* p104 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p105 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p106 = last_address;
PRINT_POINTER(scalloc(228,106););
printStats();
void* p107 = last_address;
PRINT_POINTER(scalloc(128,194););
printStats();
void* p108 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
DEBUG_PRINT(sfree(p48););
printStats();
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(srealloc(p107,249););
printStats();
void* p109 = last_address;
PRINT_POINTER(srealloc(p94,192););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p79,69););
printStats();
void* p111 = last_address;
PRINT_POINTER(scalloc(217,238););
printStats();
void* p112 = last_address;
PRINT_POINTER(scalloc(221,72););
printStats();
void* p113 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p114 = last_address;
PRINT_POINTER(srealloc(p72,9););
printStats();
void* p115 = last_address;
DEBUG_PRINT(sfree(p81););
printStats();
PRINT_POINTER(smalloc(132););
printStats();
void* p116 = last_address;
PRINT_POINTER(scalloc(36,122););
printStats();
void* p117 = last_address;
PRINT_POINTER(scalloc(68,108););
printStats();
void* p118 = last_address;
PRINT_POINTER(srealloc(p118,119););
printStats();
void* p119 = last_address;
PRINT_POINTER(scalloc(106,213););
printStats();
void* p120 = last_address;
PRINT_POINTER(scalloc(228,64););
printStats();
void* p121 = last_address;
PRINT_POINTER(scalloc(183,201););
printStats();
void* p122 = last_address;
PRINT_POINTER(scalloc(206,10););
printStats();
void* p123 = last_address;
PRINT_POINTER(scalloc(27,156););
printStats();
void* p124 = last_address;
PRINT_POINTER(scalloc(162,139););
printStats();
void* p125 = last_address;
PRINT_POINTER(scalloc(220,201););
printStats();
void* p126 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p127 = last_address;
DEBUG_PRINT(sfree(p96););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p128 = last_address;
PRINT_POINTER(scalloc(87,13););
printStats();
void* p129 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(smalloc(114););
printStats();
void* p130 = last_address;
PRINT_POINTER(scalloc(195,152););
printStats();
void* p131 = last_address;
PRINT_POINTER(scalloc(202,76););
printStats();
void* p132 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p133 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p134 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
DEBUG_PRINT(sfree(p121););
printStats();
PRINT_POINTER(srealloc(p127,95););
printStats();
void* p135 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p136 = last_address;
PRINT_POINTER(scalloc(36,236););
printStats();
void* p137 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(srealloc(p65,95););
printStats();
void* p138 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(smalloc(40););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p66););
printStats();
PRINT_POINTER(smalloc(13););
printStats();
void* p140 = last_address;
DEBUG_PRINT(sfree(p137););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p130,105););
printStats();
void* p142 = last_address;
PRINT_POINTER(srealloc(p141,88););
printStats();
void* p143 = last_address;
PRINT_POINTER(scalloc(104,143););
printStats();
void* p144 = last_address;
PRINT_POINTER(scalloc(242,97););
printStats();
void* p145 = last_address;
DEBUG_PRINT(sfree(p132););
printStats();
PRINT_POINTER(srealloc(p90,122););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(srealloc(p123,230););
printStats();
void* p147 = last_address;
PRINT_POINTER(scalloc(68,41););
printStats();
void* p148 = last_address;
PRINT_POINTER(scalloc(220,233););
printStats();
void* p149 = last_address;
PRINT_POINTER(srealloc(p128,188););
printStats();
void* p150 = last_address;
DEBUG_PRINT(sfree(p95););
printStats();
PRINT_POINTER(smalloc(42););
printStats();
void* p151 = last_address;
PRINT_POINTER(scalloc(180,65););
printStats();
void* p152 = last_address;
DEBUG_PRINT(sfree(p93););
printStats();
PRINT_POINTER(smalloc(173););
printStats();
void* p153 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(srealloc(p126,99););
printStats();
void* p154 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p155 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(scalloc(92,144););
printStats();
void* p156 = last_address;
PRINT_POINTER(scalloc(36,129););
printStats();
void* p157 = last_address;
PRINT_POINTER(srealloc(p111,137););
printStats();
void* p158 = last_address;
PRINT_POINTER(srealloc(p149,168););
printStats();
void* p159 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p160 = last_address;
PRINT_POINTER(srealloc(p133,49););
printStats();
void* p161 = last_address;
PRINT_POINTER(srealloc(p87,239););
printStats();
void* p162 = last_address;
PRINT_POINTER(srealloc(p100,1););
printStats();
void* p163 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p164 = last_address;
PRINT_POINTER(srealloc(p122,232););
printStats();
void* p165 = last_address;
PRINT_POINTER(srealloc(p125,210););
printStats();
void* p166 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p167 = last_address;
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(srealloc(p136,24););
printStats();
void* p168 = last_address;
PRINT_POINTER(srealloc(p151,67););
printStats();
void* p169 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
DEBUG_PRINT(sfree(p167););
printStats();
PRINT_POINTER(srealloc(p134,155););
printStats();
void* p170 = last_address;
PRINT_POINTER(srealloc(p131,54););
printStats();
void* p171 = last_address;
PRINT_POINTER(scalloc(84,8););
printStats();
void* p172 = last_address;
PRINT_POINTER(scalloc(44,90););
printStats();
void* p173 = last_address;
PRINT_POINTER(scalloc(69,120););
printStats();
void* p174 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p53););
printStats();
DEBUG_PRINT(sfree(p153););
printStats();
DEBUG_PRINT(sfree(p82););
printStats();
PRINT_POINTER(smalloc(14););
printStats();
void* p176 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p177 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p178 = last_address;
PRINT_POINTER(srealloc(p161,152););
printStats();
void* p179 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p180 = last_address;
PRINT_POINTER(scalloc(23,219););
printStats();
void* p181 = last_address;
PRINT_POINTER(scalloc(32,76););
printStats();
void* p182 = last_address;
PRINT_POINTER(srealloc(p170,183););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(171,76););
printStats();
void* p184 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p185 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p186 = last_address;
PRINT_POINTER(srealloc(p75,166););
printStats();
void* p187 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p188 = last_address;
PRINT_POINTER(srealloc(p135,111););
printStats();
void* p189 = last_address;
PRINT_POINTER(srealloc(p148,29););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p191 = last_address;
PRINT_POINTER(scalloc(168,142););
printStats();
void* p192 = last_address;
PRINT_POINTER(scalloc(76,204););
printStats();
void* p193 = last_address;
PRINT_POINTER(scalloc(34,117););
printStats();
void* p194 = last_address;
PRINT_POINTER(srealloc(p173,75););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(srealloc(p150,187););
printStats();
void* p196 = last_address;
DEBUG_PRINT(sfree(p108););
printStats();
DEBUG_PRINT(sfree(p179););
printStats();
PRINT_POINTER(smalloc(167););
printStats();
void* p197 = last_address;
DEBUG_PRINT(sfree(p193););
printStats();
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(srealloc(p140,159););
printStats();
void* p198 = last_address;
PRINT_POINTER(srealloc(p92,82););
printStats();
void* p199 = last_address;
DEBUG_PRINT(sfree(p138););
printStats();
DEBUG_PRINT(sfree(p84););
printStats();
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(smalloc(176););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p76,104););
printStats();
void* p201 = last_address;
DEBUG_PRINT(sfree(p184););
printStats();
PRINT_POINTER(scalloc(143,195););
printStats();
void* p202 = last_address;
DEBUG_PRINT(sfree(p192););
printStats();
PRINT_POINTER(srealloc(p189,82););
printStats();
void* p203 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p204 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p205 = last_address;
PRINT_POINTER(scalloc(106,24););
printStats();
void* p206 = last_address;
PRINT_POINTER(srealloc(p180,207););
printStats();
void* p207 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p208 = last_address;
DEBUG_PRINT(sfree(p201););
printStats();
DEBUG_PRINT(sfree(p195););
printStats();
PRINT_POINTER(scalloc(193,20););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(53,43););
printStats();
void* p210 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p211 = last_address;
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(scalloc(36,220););
printStats();
void* p212 = last_address;
PRINT_POINTER(scalloc(193,248););
printStats();
void* p213 = last_address;
PRINT_POINTER(scalloc(249,220););
printStats();
void* p214 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p215 = last_address;
PRINT_POINTER(scalloc(149,99););
printStats();
void* p216 = last_address;
DEBUG_PRINT(sfree(p215););
printStats();
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(scalloc(101,202););
printStats();
void* p217 = last_address;
PRINT_POINTER(srealloc(p199,237););
printStats();
void* p218 = last_address;
PRINT_POINTER(srealloc(p85,132););
printStats();
void* p219 = last_address;
PRINT_POINTER(srealloc(p88,229););
printStats();
void* p220 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p221 = last_address;
PRINT_POINTER(srealloc(p115,236););
printStats();
void* p222 = last_address;
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(smalloc(14););
printStats();
void* p223 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p224 = last_address;
DEBUG_PRINT(sfree(p35););
printStats();
PRINT_POINTER(srealloc(p61,220););
printStats();
void* p225 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p226 = last_address;
PRINT_POINTER(scalloc(58,71););
printStats();
void* p227 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
PRINT_POINTER(srealloc(p157,241););
printStats();
void* p228 = last_address;
PRINT_POINTER(scalloc(233,225););
printStats();
void* p229 = last_address;
PRINT_POINTER(srealloc(p171,199););
printStats();
void* p230 = last_address;
DEBUG_PRINT(sfree(p228););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p231 = last_address;
DEBUG_PRINT(sfree(p162););
printStats();
PRINT_POINTER(scalloc(236,34););
printStats();
void* p232 = last_address;
PRINT_POINTER(srealloc(p117,79););
printStats();
void* p233 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p234 = last_address;
PRINT_POINTER(srealloc(p120,233););
printStats();
void* p235 = last_address;
PRINT_POINTER(srealloc(p229,211););
printStats();
void* p236 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p237 = last_address;
PRINT_POINTER(srealloc(p158,217););
printStats();
void* p238 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p239 = last_address;
DEBUG_PRINT(sfree(p200););
printStats();
DEBUG_PRINT(sfree(p160););
printStats();
PRINT_POINTER(scalloc(147,97););
printStats();
void* p240 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p241 = last_address;
PRINT_POINTER(srealloc(p237,5););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p144););
printStats();
PRINT_POINTER(scalloc(23,156););
printStats();
void* p243 = last_address;
PRINT_POINTER(srealloc(p198,93););
printStats();
void* p244 = last_address;
PRINT_POINTER(srealloc(p185,42););
printStats();
void* p245 = last_address;
DEBUG_PRINT(sfree(p139););
printStats();
DEBUG_PRINT(sfree(p208););
printStats();
PRINT_POINTER(srealloc(p55,84););
printStats();
void* p246 = last_address;
PRINT_POINTER(srealloc(p143,207););
printStats();
void* p247 = last_address;
PRINT_POINTER(srealloc(p190,86););
printStats();
void* p248 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p249 = last_address;
DEBUG_PRINT(sfree(p224););
printStats();
DEBUG_PRINT(sfree(p225););
printStats();
PRINT_POINTER(scalloc(156,246););
printStats();
void* p250 = last_address;
PRINT_POINTER(srealloc(p104,153););
printStats();
void* p251 = last_address;
PRINT_POINTER(srealloc(p233,1););
printStats();
void* p252 = last_address;
PRINT_POINTER(srealloc(p168,165););
printStats();
void* p253 = last_address;
PRINT_POINTER(scalloc(128,107););
printStats();
void* p254 = last_address;
DEBUG_PRINT(sfree(p105););
printStats();
PRINT_POINTER(srealloc(p253,191););
printStats();
void* p255 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p256 = last_address;
DEBUG_PRINT(sfree(p234););
printStats();
PRINT_POINTER(smalloc(73););
printStats();
void* p257 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
DEBUG_PRINT(sfree(p169););
printStats();
DEBUG_PRINT(sfree(p243););
printStats();
PRINT_POINTER(srealloc(p238,2););
printStats();
void* p258 = last_address;
PRINT_POINTER(srealloc(p62,132););
printStats();
void* p259 = last_address;
PRINT_POINTER(srealloc(p73,219););
printStats();
void* p260 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p261 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p262 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p263 = last_address;
DEBUG_PRINT(sfree(p257););
printStats();
PRINT_POINTER(scalloc(56,48););
printStats();
void* p264 = last_address;
DEBUG_PRINT(sfree(p103););
printStats();
PRINT_POINTER(srealloc(p241,196););
printStats();
void* p265 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p266 = last_address;
DEBUG_PRINT(sfree(p252););
printStats();
PRINT_POINTER(srealloc(p260,180););
printStats();
void* p267 = last_address;
DEBUG_PRINT(sfree(p206););
printStats();
PRINT_POINTER(smalloc(143););
printStats();
void* p268 = last_address;
PRINT_POINTER(srealloc(p258,225););
printStats();
void* p269 = last_address;
PRINT_POINTER(srealloc(p267,243););
printStats();
void* p270 = last_address;
DEBUG_PRINT(sfree(p256););
printStats();
PRINT_POINTER(scalloc(204,213););
printStats();
void* p271 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p272 = last_address;
DEBUG_PRINT(sfree(p155););
printStats();
PRINT_POINTER(srealloc(p99,155););
printStats();
void* p273 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p274 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p275 = last_address;
DEBUG_PRINT(sfree(p249););
printStats();
PRINT_POINTER(smalloc(204););
printStats();
void* p276 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p277 = last_address;
PRINT_POINTER(scalloc(152,37););
printStats();
void* p278 = last_address;
PRINT_POINTER(scalloc(12,144););
printStats();
void* p279 = last_address;
PRINT_POINTER(scalloc(6,104););
printStats();
void* p280 = last_address;
PRINT_POINTER(srealloc(p174,194););
printStats();
void* p281 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p282 = last_address;
PRINT_POINTER(scalloc(241,96););
printStats();
void* p283 = last_address;
PRINT_POINTER(scalloc(170,12););
printStats();
void* p284 = last_address;
PRINT_POINTER(scalloc(92,165););
printStats();
void* p285 = last_address;
PRINT_POINTER(scalloc(97,160););
printStats();
void* p286 = last_address;
PRINT_POINTER(scalloc(60,32););
printStats();
void* p287 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p288 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p289 = last_address;
PRINT_POINTER(srealloc(p236,190););
printStats();
void* p290 = last_address;
PRINT_POINTER(srealloc(p216,243););
printStats();
void* p291 = last_address;
PRINT_POINTER(srealloc(p205,35););
printStats();
void* p292 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p293 = last_address;
PRINT_POINTER(scalloc(76,75););
printStats();
void* p294 = last_address;
PRINT_POINTER(scalloc(222,197););
printStats();
void* p295 = last_address;
PRINT_POINTER(scalloc(147,34););
printStats();
void* p296 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p297 = last_address;
DEBUG_PRINT(sfree(p292););
printStats();
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(scalloc(33,51););
printStats();
void* p298 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
PRINT_POINTER(smalloc(15););
printStats();
void* p299 = last_address;
DEBUG_PRINT(sfree(p239););
printStats();
PRINT_POINTER(smalloc(152););
printStats();
void* p300 = last_address;
PRINT_POINTER(scalloc(238,120););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p302 = last_address;
PRINT_POINTER(scalloc(59,61););
printStats();
void* p303 = last_address;
DEBUG_PRINT(sfree(p145););
printStats();
PRINT_POINTER(scalloc(23,87););
printStats();
void* p304 = last_address;
PRINT_POINTER(scalloc(187,236););
printStats();
void* p305 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p306 = last_address;
DEBUG_PRINT(sfree(p268););
printStats();
DEBUG_PRINT(sfree(p282););
printStats();
PRINT_POINTER(scalloc(142,107););
printStats();
void* p307 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p308 = last_address;
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(scalloc(89,198););
printStats();
void* p309 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p310 = last_address;
PRINT_POINTER(scalloc(106,27););
printStats();
void* p311 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p312 = last_address;
PRINT_POINTER(scalloc(172,175););
printStats();
void* p313 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p314 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p315 = last_address;
DEBUG_PRINT(sfree(p262););
printStats();
PRINT_POINTER(srealloc(p176,11););
printStats();
void* p316 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p317 = last_address;
PRINT_POINTER(srealloc(p295,131););
printStats();
void* p318 = last_address;
PRINT_POINTER(srealloc(p309,172););
printStats();
void* p319 = last_address;
PRINT_POINTER(srealloc(p154,98););
printStats();
void* p320 = last_address;
DEBUG_PRINT(sfree(p255););
printStats();
PRINT_POINTER(srealloc(p265,237););
printStats();
void* p321 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p322 = last_address;
PRINT_POINTER(scalloc(208,249););
printStats();
void* p323 = last_address;
PRINT_POINTER(scalloc(138,237););
printStats();
void* p324 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p325 = last_address;
PRINT_POINTER(scalloc(126,96););
printStats();
void* p326 = last_address;
PRINT_POINTER(scalloc(173,77););
printStats();
void* p327 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p328 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p329 = last_address;
PRINT_POINTER(srealloc(p261,241););
printStats();
void* p330 = last_address;
DEBUG_PRINT(sfree(p191););
printStats();
PRINT_POINTER(scalloc(214,72););
printStats();
void* p331 = last_address;
PRINT_POINTER(scalloc(192,135););
printStats();
void* p332 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p333 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p334 = last_address;
PRINT_POINTER(srealloc(p203,81););
printStats();
void* p335 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p336 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p337 = last_address;
PRINT_POINTER(srealloc(p313,27););
printStats();
void* p338 = last_address;
PRINT_POINTER(scalloc(76,64););
printStats();
void* p339 = last_address;
PRINT_POINTER(scalloc(21,194););
printStats();
void* p340 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p341 = last_address;
PRINT_POINTER(scalloc(93,145););
printStats();
void* p342 = last_address;
DEBUG_PRINT(sfree(p266););
printStats();
PRINT_POINTER(srealloc(p299,116););
printStats();
void* p343 = last_address;
PRINT_POINTER(scalloc(163,84););
printStats();
void* p344 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p345 = last_address;
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(srealloc(p344,23););
printStats();
void* p346 = last_address;
DEBUG_PRINT(sfree(p214););
printStats();
PRINT_POINTER(smalloc(53););
printStats();
void* p347 = last_address;
DEBUG_PRINT(sfree(p321););
printStats();
PRINT_POINTER(smalloc(190););
printStats();
void* p348 = last_address;
DEBUG_PRINT(sfree(p106););
printStats();
PRINT_POINTER(srealloc(p333,53););
printStats();
void* p349 = last_address;
DEBUG_PRINT(sfree(p242););
printStats();
PRINT_POINTER(srealloc(p202,180););
printStats();
void* p350 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p351 = last_address;
DEBUG_PRINT(sfree(p307););
printStats();
PRINT_POINTER(scalloc(108,187););
printStats();
void* p352 = last_address;
DEBUG_PRINT(sfree(p246););
printStats();
PRINT_POINTER(srealloc(p338,102););
printStats();
void* p353 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p354 = last_address;
PRINT_POINTER(scalloc(247,237););
printStats();
void* p355 = last_address;
DEBUG_PRINT(sfree(p248););
printStats();
PRINT_POINTER(smalloc(103););
printStats();
void* p356 = last_address;
DEBUG_PRINT(sfree(p317););
printStats();
PRINT_POINTER(srealloc(p335,161););
printStats();
void* p357 = last_address;
DEBUG_PRINT(sfree(p259););
printStats();
PRINT_POINTER(scalloc(86,211););
printStats();
void* p358 = last_address;
PRINT_POINTER(srealloc(p329,142););
printStats();
void* p359 = last_address;
PRINT_POINTER(scalloc(41,81););
printStats();
void* p360 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p361 = last_address;
DEBUG_PRINT(sfree(p279););
printStats();
DEBUG_PRINT(sfree(p277););
printStats();
PRINT_POINTER(srealloc(p345,95););
printStats();
void* p362 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p363 = last_address;
PRINT_POINTER(scalloc(55,10););
printStats();
void* p364 = last_address;
PRINT_POINTER(scalloc(72,22););
printStats();
void* p365 = last_address;
PRINT_POINTER(scalloc(105,24););
printStats();
void* p366 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p367 = last_address;
PRINT_POINTER(srealloc(p300,93););
printStats();
void* p368 = last_address;
PRINT_POINTER(srealloc(p78,194););
printStats();
void* p369 = last_address;
PRINT_POINTER(scalloc(153,110););
printStats();
void* p370 = last_address;
PRINT_POINTER(scalloc(61,165););
printStats();
void* p371 = last_address;
DEBUG_PRINT(sfree(p164););
printStats();
PRINT_POINTER(srealloc(p318,105););
printStats();
void* p372 = last_address;
PRINT_POINTER(scalloc(46,205););
printStats();
void* p373 = last_address;
PRINT_POINTER(scalloc(158,4););
printStats();
void* p374 = last_address;
DEBUG_PRINT(sfree(p220););
printStats();
PRINT_POINTER(scalloc(117,71););
printStats();
void* p375 = last_address;
PRINT_POINTER(srealloc(p232,219););
printStats();
void* p376 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p377 = last_address;
PRINT_POINTER(scalloc(37,57););
printStats();
void* p378 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p379 = last_address;
PRINT_POINTER(scalloc(189,136););
printStats();
void* p380 = last_address;
DEBUG_PRINT(sfree(p311););
printStats();
PRINT_POINTER(scalloc(56,139););
printStats();
void* p381 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p382 = last_address;
PRINT_POINTER(srealloc(p288,221););
printStats();
void* p383 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p384 = last_address;
PRINT_POINTER(scalloc(94,23););
printStats();
void* p385 = last_address;
PRINT_POINTER(srealloc(p294,76););
printStats();
void* p386 = last_address;
PRINT_POINTER(srealloc(p263,9););
printStats();
void* p387 = last_address;
DEBUG_PRINT(sfree(p212););
printStats();
PRINT_POINTER(srealloc(p213,103););
printStats();
void* p388 = last_address;
PRINT_POINTER(srealloc(p379,79););
printStats();
void* p389 = last_address;
PRINT_POINTER(srealloc(p383,217););
printStats();
void* p390 = last_address;
PRINT_POINTER(scalloc(69,173););
printStats();
void* p391 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p392 = last_address;
PRINT_POINTER(srealloc(p340,15););
printStats();
void* p393 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p394 = last_address;
PRINT_POINTER(scalloc(93,195););
printStats();
void* p395 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p396 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
PRINT_POINTER(srealloc(p336,40););
printStats();
void* p397 = last_address;
DEBUG_PRINT(sfree(p301););
printStats();
PRINT_POINTER(srealloc(p376,97););
printStats();
void* p398 = last_address;
DEBUG_PRINT(sfree(p146););
printStats();
PRINT_POINTER(smalloc(183););
printStats();
void* p399 = last_address;
PRINT_POINTER(scalloc(104,222););
printStats();
void* p400 = last_address;
DEBUG_PRINT(sfree(p240););
printStats();
PRINT_POINTER(scalloc(243,171););
printStats();
void* p401 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p402 = last_address;
DEBUG_PRINT(sfree(p348););
printStats();
PRINT_POINTER(srealloc(p197,122););
printStats();
void* p403 = last_address;
PRINT_POINTER(srealloc(p372,197););
printStats();
void* p404 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p405 = last_address;
PRINT_POINTER(srealloc(p388,160););
printStats();
void* p406 = last_address;
DEBUG_PRINT(sfree(p371););
printStats();
PRINT_POINTER(smalloc(245););
printStats();
void* p407 = last_address;
DEBUG_PRINT(sfree(p381););
printStats();
PRINT_POINTER(srealloc(p373,159););
printStats();
void* p408 = last_address;
PRINT_POINTER(srealloc(p280,203););
printStats();
void* p409 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p410 = last_address;
PRINT_POINTER(scalloc(138,167););
printStats();
void* p411 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p412 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p413 = last_address;
DEBUG_PRINT(sfree(p325););
printStats();
PRINT_POINTER(smalloc(78););
printStats();
void* p414 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p415 = last_address;
PRINT_POINTER(srealloc(p129,4););
printStats();
void* p416 = last_address;
PRINT_POINTER(srealloc(p219,121););
printStats();
void* p417 = last_address;
DEBUG_PRINT(sfree(p411););
printStats();
PRINT_POINTER(smalloc(28););
printStats();
void* p418 = last_address;
PRINT_POINTER(scalloc(51,213););
printStats();
void* p419 = last_address;
PRINT_POINTER(scalloc(35,36););
printStats();
void* p420 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p421 = last_address;
PRINT_POINTER(scalloc(91,67););
printStats();
void* p422 = last_address;
PRINT_POINTER(scalloc(58,88););
printStats();
void* p423 = last_address;
PRINT_POINTER(scalloc(85,213););
printStats();
void* p424 = last_address;
DEBUG_PRINT(sfree(p183););
printStats();
PRINT_POINTER(scalloc(248,167););
printStats();
void* p425 = last_address;
DEBUG_PRINT(sfree(p357););
printStats();
PRINT_POINTER(smalloc(189););
printStats();
void* p426 = last_address;
PRINT_POINTER(srealloc(p392,44););
printStats();
void* p427 = last_address;
PRINT_POINTER(scalloc(86,104););
printStats();
void* p428 = last_address;
PRINT_POINTER(scalloc(110,43););
printStats();
void* p429 = last_address;
DEBUG_PRINT(sfree(p305););
printStats();
PRINT_POINTER(srealloc(p356,172););
printStats();
void* p430 = last_address;
PRINT_POINTER(scalloc(203,247););
printStats();
void* p431 = last_address;
PRINT_POINTER(srealloc(p424,54););
printStats();
void* p432 = last_address;
DEBUG_PRINT(sfree(p369););
printStats();
PRINT_POINTER(scalloc(202,157););
printStats();
void* p433 = last_address;
DEBUG_PRINT(sfree(p410););
printStats();
DEBUG_PRINT(sfree(p207););
printStats();
DEBUG_PRINT(sfree(p324););
printStats();
PRINT_POINTER(smalloc(66););
printStats();
void* p434 = last_address;
PRINT_POINTER(scalloc(132,85););
printStats();
void* p435 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p436 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p437 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p438 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p439 = last_address;
DEBUG_PRINT(sfree(p247););
printStats();
PRINT_POINTER(scalloc(100,220););
printStats();
void* p440 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p441 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p442 = last_address;
DEBUG_PRINT(sfree(p435););
printStats();
DEBUG_PRINT(sfree(p330););
printStats();
PRINT_POINTER(scalloc(174,117););
printStats();
void* p443 = last_address;
PRINT_POINTER(srealloc(p320,79););
printStats();
void* p444 = last_address;
PRINT_POINTER(scalloc(90,36););
printStats();
void* p445 = last_address;
PRINT_POINTER(scalloc(53,40););
printStats();
void* p446 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p447 = last_address;
DEBUG_PRINT(sfree(p378););
printStats();
PRINT_POINTER(smalloc(36););
printStats();
void* p448 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p449 = last_address;
DEBUG_PRINT(sfree(p423););
printStats();
PRINT_POINTER(scalloc(144,114););
printStats();
void* p450 = last_address;
DEBUG_PRINT(sfree(p441););
printStats();
PRINT_POINTER(smalloc(87););
printStats();
void* p451 = last_address;
PRINT_POINTER(srealloc(p319,107););
printStats();
void* p452 = last_address;
PRINT_POINTER(srealloc(p432,189););
printStats();
void* p453 = last_address;
PRINT_POINTER(scalloc(137,73););
printStats();
void* p454 = last_address;
PRINT_POINTER(srealloc(p346,209););
printStats();
void* p455 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p456 = last_address;
DEBUG_PRINT(sfree(p182););
printStats();
PRINT_POINTER(smalloc(209););
printStats();
void* p457 = last_address;
PRINT_POINTER(scalloc(170,117););
printStats();
void* p458 = last_address;
PRINT_POINTER(srealloc(p406,236););
printStats();
void* p459 = last_address;
PRINT_POINTER(scalloc(175,128););
printStats();
void* p460 = last_address;
PRINT_POINTER(scalloc(222,24););
printStats();
void* p461 = last_address;
PRINT_POINTER(scalloc(94,48););
printStats();
void* p462 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p463 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p464 = last_address;
PRINT_POINTER(srealloc(p245,232););
printStats();
void* p465 = last_address;
PRINT_POINTER(srealloc(p188,201););
printStats();
void* p466 = last_address;
PRINT_POINTER(scalloc(132,161););
printStats();
void* p467 = last_address;
PRINT_POINTER(srealloc(p165,164););
printStats();
void* p468 = last_address;
PRINT_POINTER(scalloc(54,39););
printStats();
void* p469 = last_address;
PRINT_POINTER(scalloc(116,220););
printStats();
void* p470 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p471 = last_address;
PRINT_POINTER(scalloc(27,47););
printStats();
void* p472 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p473 = last_address;
PRINT_POINTER(srealloc(p274,59););
printStats();
void* p474 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p475 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p476 = last_address;
DEBUG_PRINT(sfree(p306););
printStats();
PRINT_POINTER(srealloc(p414,140););
printStats();
void* p477 = last_address;
DEBUG_PRINT(sfree(p341););
printStats();
DEBUG_PRINT(sfree(p289););
printStats();
PRINT_POINTER(scalloc(205,41););
printStats();
void* p478 = last_address;
PRINT_POINTER(scalloc(148,98););
printStats();
void* p479 = last_address;
DEBUG_PRINT(sfree(p297););
printStats();
DEBUG_PRINT(sfree(p428););
printStats();
PRINT_POINTER(smalloc(140););
printStats();
void* p480 = last_address;
PRINT_POINTER(scalloc(75,119););
printStats();
void* p481 = last_address;
DEBUG_PRINT(sfree(p419););
printStats();
PRINT_POINTER(srealloc(p355,152););
printStats();
void* p482 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p483 = last_address;
PRINT_POINTER(smalloc(80););
printStats();
void* p484 = last_address;
DEBUG_PRINT(sfree(p463););
printStats();
PRINT_POINTER(smalloc(141););
printStats();
void* p485 = last_address;
PRINT_POINTER(scalloc(222,120););
printStats();
void* p486 = last_address;
PRINT_POINTER(scalloc(62,106););
printStats();
void* p487 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p488 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p489 = last_address;
PRINT_POINTER(scalloc(65,78););
printStats();
void* p490 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
DEBUG_PRINT(sfree(p211););
printStats();
PRINT_POINTER(srealloc(p364,248););
printStats();
void* p491 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p492 = last_address;
DEBUG_PRINT(sfree(p331););
printStats();
DEBUG_PRINT(sfree(p264););
printStats();
DEBUG_PRINT(sfree(p489););
printStats();
DEBUG_PRINT(sfree(p462););
printStats();
PRINT_POINTER(srealloc(p436,48););
printStats();
void* p493 = last_address;
PRINT_POINTER(scalloc(196,8););
printStats();
void* p494 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p495 = last_address;
PRINT_POINTER(scalloc(228,59););
printStats();
void* p496 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p497 = last_address;
DEBUG_PRINT(sfree(p286););
printStats();
PRINT_POINTER(smalloc(74););
printStats();
void* p498 = last_address;
PRINT_POINTER(scalloc(64,21););
printStats();
void* p499 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p500 = last_address;
PRINT_POINTER(scalloc(50,97););
printStats();
void* p501 = last_address;
DEBUG_PRINT(sfree(p110););
printStats();
PRINT_POINTER(smalloc(133););
printStats();
void* p502 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p503 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p504 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p505 = last_address;
PRINT_POINTER(srealloc(p194,249););
printStats();
void* p506 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p507 = last_address;
PRINT_POINTER(srealloc(p386,92););
printStats();
void* p508 = last_address;
PRINT_POINTER(srealloc(p459,246););
printStats();
void* p509 = last_address;
DEBUG_PRINT(sfree(p502););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p510 = last_address;
DEBUG_PRINT(sfree(p453););
printStats();
PRINT_POINTER(srealloc(p454,151););
printStats();
void* p511 = last_address;
PRINT_POINTER(srealloc(p316,247););
printStats();
void* p512 = last_address;
DEBUG_PRINT(sfree(p156););
printStats();
PRINT_POINTER(smalloc(22););
printStats();
void* p513 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p514 = last_address;
PRINT_POINTER(scalloc(38,180););
printStats();
void* p515 = last_address;
DEBUG_PRINT(sfree(p478););
printStats();
PRINT_POINTER(scalloc(23,75););
printStats();
void* p516 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p517 = last_address;
PRINT_POINTER(scalloc(195,188););
printStats();
void* p518 = last_address;
DEBUG_PRINT(sfree(p389););
printStats();
PRINT_POINTER(scalloc(248,11););
printStats();
void* p519 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p520 = last_address;
PRINT_POINTER(scalloc(174,89););
printStats();
void* p521 = last_address;
PRINT_POINTER(srealloc(p422,137););
printStats();
void* p522 = last_address;
PRINT_POINTER(scalloc(18,17););
printStats();
void* p523 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p524 = last_address;
PRINT_POINTER(srealloc(p362,40););
printStats();
void* p525 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p526 = last_address;
PRINT_POINTER(scalloc(0,36););
printStats();
void* p527 = last_address;
PRINT_POINTER(srealloc(p465,136););
printStats();
void* p528 = last_address;
PRINT_POINTER(srealloc(p439,78););
printStats();
void* p529 = last_address;
DEBUG_PRINT(sfree(p486););
printStats();
PRINT_POINTER(scalloc(136,131););
printStats();
void* p530 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p531 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p532 = last_address;
DEBUG_PRINT(sfree(p488););
printStats();
DEBUG_PRINT(sfree(p530););
printStats();
PRINT_POINTER(smalloc(66););
printStats();
void* p533 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p534 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p535 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p536 = last_address;
PRINT_POINTER(scalloc(147,222););
printStats();
void* p537 = last_address;
DEBUG_PRINT(sfree(p275););
printStats();
DEBUG_PRINT(sfree(p516););
printStats();
PRINT_POINTER(scalloc(8,176););
printStats();
void* p538 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p539 = last_address;
PRINT_POINTER(scalloc(186,188););
printStats();
void* p540 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p541 = last_address;
PRINT_POINTER(srealloc(p278,34););
printStats();
void* p542 = last_address;
PRINT_POINTER(srealloc(p83,52););
printStats();
void* p543 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p544 = last_address;
PRINT_POINTER(scalloc(200,220););
printStats();
void* p545 = last_address;
PRINT_POINTER(srealloc(p473,78););
printStats();
void* p546 = last_address;
PRINT_POINTER(srealloc(p447,118););
printStats();
void* p547 = last_address;
PRINT_POINTER(scalloc(50,112););
printStats();
void* p548 = last_address;
PRINT_POINTER(srealloc(p387,8););
printStats();
void* p549 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p550 = last_address;
PRINT_POINTER(scalloc(61,184););
printStats();
void* p551 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p552 = last_address;
PRINT_POINTER(scalloc(127,218););
printStats();
void* p553 = last_address;
PRINT_POINTER(scalloc(171,193););
printStats();
void* p554 = last_address;
DEBUG_PRINT(sfree(p363););
printStats();
PRINT_POINTER(scalloc(94,161););
printStats();
void* p555 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p556 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p557 = last_address;
PRINT_POINTER(srealloc(p377,97););
printStats();
void* p558 = last_address;
PRINT_POINTER(scalloc(40,236););
printStats();
void* p559 = last_address;
PRINT_POINTER(scalloc(137,169););
printStats();
void* p560 = last_address;
DEBUG_PRINT(sfree(p291););
printStats();
PRINT_POINTER(smalloc(15););
printStats();
void* p561 = last_address;
DEBUG_PRINT(sfree(p484););
printStats();
DEBUG_PRINT(sfree(p433););
printStats();
DEBUG_PRINT(sfree(p496););
printStats();
PRINT_POINTER(scalloc(93,192););
printStats();
void* p562 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p563 = last_address;
DEBUG_PRINT(sfree(p500););
printStats();
PRINT_POINTER(smalloc(243););
printStats();
void* p564 = last_address;
DEBUG_PRINT(sfree(p521););
printStats();
PRINT_POINTER(srealloc(p442,211););
printStats();
void* p565 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p566 = last_address;
DEBUG_PRINT(sfree(p534););
printStats();
PRINT_POINTER(scalloc(217,154););
printStats();
void* p567 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p568 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p569 = last_address;
PRINT_POINTER(srealloc(p487,202););
printStats();
void* p570 = last_address;
PRINT_POINTER(scalloc(186,103););
printStats();
void* p571 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p572 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p573 = last_address;
PRINT_POINTER(srealloc(p568,36););
printStats();
void* p574 = last_address;
DEBUG_PRINT(sfree(p391););
printStats();
PRINT_POINTER(scalloc(197,92););
printStats();
void* p575 = last_address;
PRINT_POINTER(srealloc(p546,34););
printStats();
void* p576 = last_address;
PRINT_POINTER(srealloc(p350,0););
printStats();
void* p577 = last_address;
DEBUG_PRINT(sfree(p504););
printStats();
PRINT_POINTER(smalloc(21););
printStats();
void* p578 = last_address;
DEBUG_PRINT(sfree(p251););
printStats();
PRINT_POINTER(smalloc(103););
printStats();
void* p579 = last_address;
PRINT_POINTER(srealloc(p451,24););
printStats();
void* p580 = last_address;
PRINT_POINTER(scalloc(228,173););
printStats();
void* p581 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p582 = last_address;
PRINT_POINTER(srealloc(p418,95););
printStats();
void* p583 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p584 = last_address;
DEBUG_PRINT(sfree(p544););
printStats();
PRINT_POINTER(smalloc(16););
printStats();
void* p585 = last_address;
PRINT_POINTER(scalloc(206,183););
printStats();
void* p586 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p587 = last_address;
PRINT_POINTER(srealloc(p563,102););
printStats();
void* p588 = last_address;
DEBUG_PRINT(sfree(p458););
printStats();
PRINT_POINTER(smalloc(75););
printStats();
void* p589 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p590 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p591 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p592 = last_address;
PRINT_POINTER(srealloc(p507,14););
printStats();
void* p593 = last_address;
PRINT_POINTER(srealloc(p269,35););
printStats();
void* p594 = last_address;
PRINT_POINTER(scalloc(52,174););
printStats();
void* p595 = last_address;
PRINT_POINTER(scalloc(62,147););
printStats();
void* p596 = last_address;
DEBUG_PRINT(sfree(p564););
printStats();
PRINT_POINTER(smalloc(4););
printStats();
void* p597 = last_address;
PRINT_POINTER(scalloc(67,128););
printStats();
void* p598 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p599 = last_address;
DEBUG_PRINT(sfree(p328););
printStats();
DEBUG_PRINT(sfree(p273););
printStats();
PRINT_POINTER(smalloc(45););
printStats();
void* p600 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p601 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p602 = last_address;
PRINT_POINTER(scalloc(45,135););
printStats();
void* p603 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p604 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p605 = last_address;
PRINT_POINTER(srealloc(p494,228););
printStats();
void* p606 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p607 = last_address;
PRINT_POINTER(srealloc(p310,55););
printStats();
void* p608 = last_address;
PRINT_POINTER(srealloc(p327,69););
printStats();
void* p609 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p610 = last_address;
DEBUG_PRINT(sfree(p235););
printStats();
PRINT_POINTER(smalloc(40););
printStats();
void* p611 = last_address;
PRINT_POINTER(srealloc(p455,43););
printStats();
void* p612 = last_address;
PRINT_POINTER(scalloc(234,240););
printStats();
void* p613 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p614 = last_address;
PRINT_POINTER(srealloc(p595,208););
printStats();
void* p615 = last_address;
PRINT_POINTER(scalloc(109,162););
printStats();
void* p616 = last_address;
PRINT_POINTER(srealloc(p124,142););
printStats();
void* p617 = last_address;
PRINT_POINTER(srealloc(p598,66););
printStats();
void* p618 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p619 = last_address;
PRINT_POINTER(srealloc(p547,220););
printStats();
void* p620 = last_address;
PRINT_POINTER(srealloc(p620,208););
printStats();
void* p621 = last_address;
PRINT_POINTER(srealloc(p361,138););
printStats();
void* p622 = last_address;
PRINT_POINTER(scalloc(33,95););
printStats();
void* p623 = last_address;
PRINT_POINTER(srealloc(p612,208););
printStats();
void* p624 = last_address;
PRINT_POINTER(scalloc(198,157););
printStats();
void* p625 = last_address;
PRINT_POINTER(srealloc(p481,57););
printStats();
void* p626 = last_address;
PRINT_POINTER(srealloc(p404,203););
printStats();
void* p627 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p628 = last_address;
PRINT_POINTER(srealloc(p181,72););
printStats();
void* p629 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p630 = last_address;
DEBUG_PRINT(sfree(p217););
printStats();
PRINT_POINTER(scalloc(226,112););
printStats();
void* p631 = last_address;
PRINT_POINTER(srealloc(p409,241););
printStats();
void* p632 = last_address;
PRINT_POINTER(scalloc(7,91););
printStats();
void* p633 = last_address;
PRINT_POINTER(scalloc(123,67););
printStats();
void* p634 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p635 = last_address;
PRINT_POINTER(srealloc(p342,23););
printStats();
void* p636 = last_address;
PRINT_POINTER(srealloc(p400,138););
printStats();
void* p637 = last_address;
PRINT_POINTER(srealloc(p622,208););
printStats();
void* p638 = last_address;
PRINT_POINTER(scalloc(16,125););
printStats();
void* p639 = last_address;
PRINT_POINTER(scalloc(39,135););
printStats();
void* p640 = last_address;
DEBUG_PRINT(sfree(p415););
printStats();
PRINT_POINTER(smalloc(88););
printStats();
void* p641 = last_address;
PRINT_POINTER(scalloc(36,13););
printStats();
void* p642 = last_address;
PRINT_POINTER(scalloc(234,117););
printStats();
void* p643 = last_address;
PRINT_POINTER(srealloc(p429,121););
printStats();
void* p644 = last_address;
DEBUG_PRINT(sfree(p438););
printStats();
DEBUG_PRINT(sfree(p513););
printStats();
PRINT_POINTER(smalloc(119););
printStats();
void* p645 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p646 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p647 = last_address;
DEBUG_PRINT(sfree(p370););
printStats();
PRINT_POINTER(scalloc(128,18););
printStats();
void* p648 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p649 = last_address;
DEBUG_PRINT(sfree(p503););
printStats();
PRINT_POINTER(smalloc(122););
printStats();
void* p650 = last_address;
PRINT_POINTER(scalloc(11,77););
printStats();
void* p651 = last_address;
DEBUG_PRINT(sfree(p573););
printStats();
DEBUG_PRINT(sfree(p532););
printStats();
DEBUG_PRINT(sfree(p326););
printStats();
PRINT_POINTER(scalloc(155,52););
printStats();
void* p652 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p653 = last_address;
PRINT_POINTER(scalloc(141,130););
printStats();
void* p654 = last_address;
PRINT_POINTER(scalloc(245,30););
printStats();
void* p655 = last_address;
PRINT_POINTER(srealloc(p584,207););
printStats();
void* p656 = last_address;
PRINT_POINTER(scalloc(32,228););
printStats();
void* p657 = last_address;
PRINT_POINTER(srealloc(p652,83););
printStats();
void* p658 = last_address;
PRINT_POINTER(scalloc(161,41););
printStats();
void* p659 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p660 = last_address;
PRINT_POINTER(scalloc(78,130););
printStats();
void* p661 = last_address;
PRINT_POINTER(srealloc(p434,142););
printStats();
void* p662 = last_address;
PRINT_POINTER(scalloc(14,11););
printStats();
void* p663 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p664 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p665 = last_address;
PRINT_POINTER(scalloc(149,120););
printStats();
void* p666 = last_address;
DEBUG_PRINT(sfree(p457););
printStats();
PRINT_POINTER(srealloc(p285,200););
printStats();
void* p667 = last_address;
PRINT_POINTER(srealloc(p375,0););
printStats();
void* p668 = last_address;
DEBUG_PRINT(sfree(p613););
printStats();
PRINT_POINTER(scalloc(151,115););
printStats();
void* p669 = last_address;
PRINT_POINTER(srealloc(p559,114););
printStats();
void* p670 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p671 = last_address;
PRINT_POINTER(srealloc(p343,11););
printStats();
void* p672 = last_address;
DEBUG_PRINT(sfree(p308););
printStats();
PRINT_POINTER(scalloc(168,157););
printStats();
void* p673 = last_address;
PRINT_POINTER(srealloc(p557,15););
printStats();
void* p674 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p675 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p676 = last_address;
DEBUG_PRINT(sfree(p524););
printStats();
PRINT_POINTER(scalloc(161,10););
printStats();
void* p677 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p678 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p679 = last_address;
DEBUG_PRINT(sfree(p533););
printStats();
PRINT_POINTER(scalloc(210,149););
printStats();
void* p680 = last_address;
PRINT_POINTER(scalloc(145,197););
printStats();
void* p681 = last_address;
DEBUG_PRINT(sfree(p359););
printStats();
DEBUG_PRINT(sfree(p499););
printStats();
PRINT_POINTER(scalloc(14,62););
printStats();
void* p682 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p683 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p684 = last_address;
PRINT_POINTER(srealloc(p667,167););
printStats();
void* p685 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p686 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p687 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p688 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
DEBUG_PRINT(sfree(p650););
printStats();
PRINT_POINTER(smalloc(131););
printStats();
void* p689 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p690 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p691 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p692 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p693 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p694 = last_address;
PRINT_POINTER(scalloc(234,102););
printStats();
void* p695 = last_address;
PRINT_POINTER(scalloc(5,135););
printStats();
void* p696 = last_address;
PRINT_POINTER(srealloc(p172,196););
printStats();
void* p697 = last_address;
PRINT_POINTER(scalloc(146,43););
printStats();
void* p698 = last_address;
PRINT_POINTER(scalloc(53,153););
printStats();
void* p699 = last_address;
DEBUG_PRINT(sfree(p367););
printStats();
PRINT_POINTER(smalloc(244););
printStats();
void* p700 = last_address;
DEBUG_PRINT(sfree(p408););
printStats();
DEBUG_PRINT(sfree(p490););
printStats();
DEBUG_PRINT(sfree(p163););
printStats();
PRINT_POINTER(srealloc(p697,146););
printStats();
void* p701 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p702 = last_address;
PRINT_POINTER(srealloc(p599,122););
printStats();
void* p703 = last_address;
DEBUG_PRINT(sfree(p608););
printStats();
PRINT_POINTER(scalloc(50,181););
printStats();
void* p704 = last_address;
PRINT_POINTER(scalloc(67,104););
printStats();
void* p705 = last_address;
DEBUG_PRINT(sfree(p293););
printStats();
PRINT_POINTER(srealloc(p688,219););
printStats();
void* p706 = last_address;
PRINT_POINTER(scalloc(225,54););
printStats();
void* p707 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p708 = last_address;
DEBUG_PRINT(sfree(p449););
printStats();
PRINT_POINTER(scalloc(47,112););
printStats();
void* p709 = last_address;
PRINT_POINTER(srealloc(p543,110););
printStats();
void* p710 = last_address;
PRINT_POINTER(scalloc(138,8););
printStats();
void* p711 = last_address;
DEBUG_PRINT(sfree(p360););
printStats();
DEBUG_PRINT(sfree(p687););
printStats();
PRINT_POINTER(srealloc(p572,130););
printStats();
void* p712 = last_address;
PRINT_POINTER(scalloc(196,111););
printStats();
void* p713 = last_address;
DEBUG_PRINT(sfree(p624););
printStats();
PRINT_POINTER(scalloc(80,214););
printStats();
void* p714 = last_address;
DEBUG_PRINT(sfree(p707););
printStats();
PRINT_POINTER(smalloc(101););
printStats();
void* p715 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p716 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p717 = last_address;
DEBUG_PRINT(sfree(p491););
printStats();
PRINT_POINTER(smalloc(143););
printStats();
void* p718 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p719 = last_address;
PRINT_POINTER(srealloc(p446,243););
printStats();
void* p720 = last_address;
PRINT_POINTER(srealloc(p505,11););
printStats();
void* p721 = last_address;
DEBUG_PRINT(sfree(p601););
printStats();
PRINT_POINTER(smalloc(48););
printStats();
void* p722 = last_address;
PRINT_POINTER(srealloc(p506,222););
printStats();
void* p723 = last_address;
PRINT_POINTER(scalloc(181,230););
printStats();
void* p724 = last_address;
PRINT_POINTER(srealloc(p664,217););
printStats();
void* p725 = last_address;
PRINT_POINTER(srealloc(p639,130););
printStats();
void* p726 = last_address;
PRINT_POINTER(scalloc(238,116););
printStats();
void* p727 = last_address;
PRINT_POINTER(srealloc(p654,174););
printStats();
void* p728 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p729 = last_address;
PRINT_POINTER(scalloc(247,69););
printStats();
void* p730 = last_address;
PRINT_POINTER(srealloc(p298,41););
printStats();
void* p731 = last_address;
DEBUG_PRINT(sfree(p728););
printStats();
PRINT_POINTER(smalloc(68););
printStats();
void* p732 = last_address;
DEBUG_PRINT(sfree(p399););
printStats();
DEBUG_PRINT(sfree(p714););
printStats();
PRINT_POINTER(srealloc(p635,120););
printStats();
void* p733 = last_address;
DEBUG_PRINT(sfree(p644););
printStats();
DEBUG_PRINT(sfree(p661););
printStats();
PRINT_POINTER(scalloc(176,162););
printStats();
void* p734 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p735 = last_address;
DEBUG_PRINT(sfree(p187););
printStats();
PRINT_POINTER(scalloc(179,69););
printStats();
void* p736 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p737 = last_address;
PRINT_POINTER(scalloc(177,174););
printStats();
void* p738 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p739 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p740 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p741 = last_address;
PRINT_POINTER(srealloc(p600,165););
printStats();
void* p742 = last_address;
PRINT_POINTER(srealloc(p589,92););
printStats();
void* p743 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p744 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p745 = last_address;
DEBUG_PRINT(sfree(p492););
printStats();
DEBUG_PRINT(sfree(p304););
printStats();
PRINT_POINTER(scalloc(156,147););
printStats();
void* p746 = last_address;
DEBUG_PRINT(sfree(p401););
printStats();
DEBUG_PRINT(sfree(p660););
printStats();
PRINT_POINTER(scalloc(248,176););
printStats();
void* p747 = last_address;
PRINT_POINTER(srealloc(p565,57););
printStats();
void* p748 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p749 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p750 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p751 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p752 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p753 = last_address;
PRINT_POINTER(scalloc(152,151););
printStats();
void* p754 = last_address;
DEBUG_PRINT(sfree(p570););
printStats();
PRINT_POINTER(srealloc(p512,64););
printStats();
void* p755 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p756 = last_address;
PRINT_POINTER(srealloc(p537,119););
printStats();
void* p757 = last_address;
PRINT_POINTER(srealloc(p460,92););
printStats();
void* p758 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p759 = last_address;
PRINT_POINTER(scalloc(150,239););
printStats();
void* p760 = last_address;
DEBUG_PRINT(sfree(p302););
printStats();
PRINT_POINTER(smalloc(54););
printStats();
void* p761 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p762 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p763 = last_address;
PRINT_POINTER(srealloc(p626,101););
printStats();
void* p764 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p765 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p766 = last_address;
PRINT_POINTER(srealloc(p352,61););
printStats();
void* p767 = last_address;
DEBUG_PRINT(sfree(p641););
printStats();
PRINT_POINTER(scalloc(159,202););
printStats();
void* p768 = last_address;
PRINT_POINTER(srealloc(p631,30););
printStats();
void* p769 = last_address;
PRINT_POINTER(scalloc(103,199););
printStats();
void* p770 = last_address;
PRINT_POINTER(srealloc(p493,87););
printStats();
void* p771 = last_address;
PRINT_POINTER(srealloc(p230,173););
printStats();
void* p772 = last_address;
PRINT_POINTER(srealloc(p575,140););
printStats();
void* p773 = last_address;
PRINT_POINTER(scalloc(135,29););
printStats();
void* p774 = last_address;
PRINT_POINTER(scalloc(150,19););
printStats();
void* p775 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p776 = last_address;
DEBUG_PRINT(sfree(p630););
printStats();
DEBUG_PRINT(sfree(p708););
printStats();
DEBUG_PRINT(sfree(p643););
printStats();
PRINT_POINTER(scalloc(241,127););
printStats();
void* p777 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p778 = last_address;
PRINT_POINTER(srealloc(p640,9););
printStats();
void* p779 = last_address;
PRINT_POINTER(srealloc(p725,0););
printStats();
void* p780 = last_address;
DEBUG_PRINT(sfree(p479););
printStats();
PRINT_POINTER(smalloc(166););
printStats();
void* p781 = last_address;
PRINT_POINTER(srealloc(p555,190););
printStats();
void* p782 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p783 = last_address;
DEBUG_PRINT(sfree(p485););
printStats();
PRINT_POINTER(srealloc(p780,8););
printStats();
void* p784 = last_address;
PRINT_POINTER(srealloc(p540,92););
printStats();
void* p785 = last_address;
PRINT_POINTER(scalloc(224,110););
printStats();
void* p786 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p787 = last_address;
PRINT_POINTER(srealloc(p743,135););
printStats();
void* p788 = last_address;
PRINT_POINTER(srealloc(p618,66););
printStats();
void* p789 = last_address;
DEBUG_PRINT(sfree(p773););
printStats();
PRINT_POINTER(scalloc(8,73););
printStats();
void* p790 = last_address;
PRINT_POINTER(scalloc(205,196););
printStats();
void* p791 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p792 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p793 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p794 = last_address;
PRINT_POINTER(scalloc(175,47););
printStats();
void* p795 = last_address;
PRINT_POINTER(scalloc(130,28););
printStats();
void* p796 = last_address;
PRINT_POINTER(srealloc(p394,59););
printStats();
void* p797 = last_address;
DEBUG_PRINT(sfree(p659););
printStats();
PRINT_POINTER(scalloc(247,11););
printStats();
void* p798 = last_address;
PRINT_POINTER(srealloc(p421,31););
printStats();
void* p799 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p800 = last_address;
PRINT_POINTER(scalloc(47,151););
printStats();
void* p801 = last_address;
PRINT_POINTER(srealloc(p475,55););
printStats();
void* p802 = last_address;
PRINT_POINTER(srealloc(p440,235););
printStats();
void* p803 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p804 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p805 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p806 = last_address;
PRINT_POINTER(scalloc(248,168););
printStats();
void* p807 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p808 = last_address;
PRINT_POINTER(scalloc(181,194););
printStats();
void* p809 = last_address;
PRINT_POINTER(srealloc(p633,105););
printStats();
void* p810 = last_address;
DEBUG_PRINT(sfree(p596););
printStats();
DEBUG_PRINT(sfree(p425););
printStats();
DEBUG_PRINT(sfree(p587););
printStats();
PRINT_POINTER(smalloc(71););
printStats();
void* p811 = last_address;
PRINT_POINTER(srealloc(p605,205););
printStats();
void* p812 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p813 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p814 = last_address;
DEBUG_PRINT(sfree(p672););
printStats();
DEBUG_PRINT(sfree(p585););
printStats();
PRINT_POINTER(srealloc(p774,37););
printStats();
void* p815 = last_address;
PRINT_POINTER(srealloc(p726,151););
printStats();
void* p816 = last_address;
PRINT_POINTER(srealloc(p254,23););
printStats();
void* p817 = last_address;
PRINT_POINTER(scalloc(192,102););
printStats();
void* p818 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
DEBUG_PRINT(sfree(p525););
printStats();
PRINT_POINTER(smalloc(108););
printStats();
void* p819 = last_address;
DEBUG_PRINT(sfree(p472););
printStats();
PRINT_POINTER(scalloc(226,111););
printStats();
void* p820 = last_address;
PRINT_POINTER(srealloc(p778,120););
printStats();
void* p821 = last_address;
DEBUG_PRINT(sfree(p735););
printStats();
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(srealloc(p384,211););
printStats();
void* p822 = last_address;
PRINT_POINTER(scalloc(208,136););
printStats();
void* p823 = last_address;
DEBUG_PRINT(sfree(p763););
printStats();
PRINT_POINTER(smalloc(146););
printStats();
void* p824 = last_address;
PRINT_POINTER(scalloc(101,12););
printStats();
void* p825 = last_address;
DEBUG_PRINT(sfree(p807););
printStats();
PRINT_POINTER(smalloc(231););
printStats();
void* p826 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
DEBUG_PRINT(sfree(p800););
printStats();
PRINT_POINTER(scalloc(211,172););
printStats();
void* p827 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p828 = last_address;
PRINT_POINTER(scalloc(156,191););
printStats();
void* p829 = last_address;
PRINT_POINTER(scalloc(172,192););
printStats();
void* p830 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p831 = last_address;
DEBUG_PRINT(sfree(p698););
printStats();
PRINT_POINTER(srealloc(p692,63););
printStats();
void* p832 = last_address;
PRINT_POINTER(scalloc(138,59););
printStats();
void* p833 = last_address;
PRINT_POINTER(scalloc(41,196););
printStats();
void* p834 = last_address;
DEBUG_PRINT(sfree(p785););
printStats();
PRINT_POINTER(srealloc(p675,202););
printStats();
void* p835 = last_address;
PRINT_POINTER(srealloc(p811,167););
printStats();
void* p836 = last_address;
DEBUG_PRINT(sfree(p347););
printStats();
PRINT_POINTER(smalloc(71););
printStats();
void* p837 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p838 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p839 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p840 = last_address;
DEBUG_PRINT(sfree(p804););
printStats();
PRINT_POINTER(srealloc(p474,240););
printStats();
void* p841 = last_address;
DEBUG_PRINT(sfree(p531););
printStats();
PRINT_POINTER(scalloc(75,183););
printStats();
void* p842 = last_address;
DEBUG_PRINT(sfree(p566););
printStats();
PRINT_POINTER(srealloc(p314,169););
printStats();
void* p843 = last_address;
DEBUG_PRINT(sfree(p396););
printStats();
DEBUG_PRINT(sfree(p781););
printStats();
PRINT_POINTER(smalloc(239););
printStats();
void* p844 = last_address;
PRINT_POINTER(srealloc(p756,24););
printStats();
void* p845 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p846 = last_address;
DEBUG_PRINT(sfree(p562););
printStats();
PRINT_POINTER(scalloc(108,55););
printStats();
void* p847 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p848 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p849 = last_address;
PRINT_POINTER(scalloc(25,180););
printStats();
void* p850 = last_address;
DEBUG_PRINT(sfree(p727););
printStats();
PRINT_POINTER(scalloc(78,63););
printStats();
void* p851 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p852 = last_address;
PRINT_POINTER(srealloc(p594,249););
printStats();
void* p853 = last_address;
PRINT_POINTER(srealloc(p509,15););
printStats();
void* p854 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p855 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p856 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p857 = last_address;
PRINT_POINTER(srealloc(p857,240););
printStats();
void* p858 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p859 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p860 = last_address;
PRINT_POINTER(srealloc(p703,234););
printStats();
void* p861 = last_address;
PRINT_POINTER(srealloc(p627,101););
printStats();
void* p862 = last_address;
DEBUG_PRINT(sfree(p607););
printStats();
PRINT_POINTER(smalloc(37););
printStats();
void* p863 = last_address;
DEBUG_PRINT(sfree(p724););
printStats();
PRINT_POINTER(scalloc(142,51););
printStats();
void* p864 = last_address;
PRINT_POINTER(srealloc(p705,213););
printStats();
void* p865 = last_address;
PRINT_POINTER(srealloc(p427,92););
printStats();
void* p866 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p867 = last_address;
PRINT_POINTER(scalloc(20,136););
printStats();
void* p868 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p869 = last_address;
PRINT_POINTER(srealloc(p844,148););
printStats();
void* p870 = last_address;
PRINT_POINTER(scalloc(57,95););
printStats();
void* p871 = last_address;
PRINT_POINTER(srealloc(p541,161););
printStats();
void* p872 = last_address;
DEBUG_PRINT(sfree(p690););
printStats();
PRINT_POINTER(smalloc(112););
printStats();
void* p873 = last_address;
PRINT_POINTER(srealloc(p276,34););
printStats();
void* p874 = last_address;
PRINT_POINTER(scalloc(114,156););
printStats();
void* p875 = last_address;
PRINT_POINTER(srealloc(p602,87););
printStats();
void* p876 = last_address;
PRINT_POINTER(scalloc(57,50););
printStats();
void* p877 = last_address;
DEBUG_PRINT(sfree(p671););
printStats();
PRINT_POINTER(scalloc(176,150););
printStats();
void* p878 = last_address;
PRINT_POINTER(scalloc(224,66););
printStats();
void* p879 = last_address;
PRINT_POINTER(scalloc(171,30););
printStats();
void* p880 = last_address;
PRINT_POINTER(srealloc(p647,103););
printStats();
void* p881 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p882 = last_address;
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(srealloc(p552,135););
printStats();
void* p883 = last_address;
PRINT_POINTER(srealloc(p777,22););
printStats();
void* p884 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(srealloc(p856,144););
printStats();
void* p885 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p886 = last_address;
PRINT_POINTER(srealloc(p592,30););
printStats();
void* p887 = last_address;
PRINT_POINTER(scalloc(220,73););
printStats();
void* p888 = last_address;
PRINT_POINTER(srealloc(p287,120););
printStats();
void* p889 = last_address;
PRINT_POINTER(srealloc(p868,40););
printStats();
void* p890 = last_address;
DEBUG_PRINT(sfree(p862););
printStats();
PRINT_POINTER(srealloc(p837,10););
printStats();
void* p891 = last_address;
PRINT_POINTER(srealloc(p758,118););
printStats();
void* p892 = last_address;
PRINT_POINTER(scalloc(167,231););
printStats();
void* p893 = last_address;
PRINT_POINTER(srealloc(p497,195););
printStats();
void* p894 = last_address;
PRINT_POINTER(scalloc(237,143););
printStats();
void* p895 = last_address;
DEBUG_PRINT(sfree(p888););
printStats();
PRINT_POINTER(srealloc(p448,78););
printStats();
void* p896 = last_address;
PRINT_POINTER(srealloc(p477,81););
printStats();
void* p897 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p898 = last_address;
PRINT_POINTER(srealloc(p579,239););
printStats();
void* p899 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p900 = last_address;
PRINT_POINTER(srealloc(p715,188););
printStats();
void* p901 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p902 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p903 = last_address;
PRINT_POINTER(scalloc(227,163););
printStats();
void* p904 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p905 = last_address;
PRINT_POINTER(scalloc(115,22););
printStats();
void* p906 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p907 = last_address;
PRINT_POINTER(srealloc(p679,171););
printStats();
void* p908 = last_address;
PRINT_POINTER(srealloc(p529,249););
printStats();
void* p909 = last_address;
PRINT_POINTER(srealloc(p615,95););
printStats();
void* p910 = last_address;
PRINT_POINTER(srealloc(p886,91););
printStats();
void* p911 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p912 = last_address;
PRINT_POINTER(scalloc(114,69););
printStats();
void* p913 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p914 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p915 = last_address;
DEBUG_PRINT(sfree(p649););
printStats();
PRINT_POINTER(smalloc(153););
printStats();
void* p916 = last_address;
DEBUG_PRINT(sfree(p709););
printStats();
PRINT_POINTER(scalloc(166,190););
printStats();
void* p917 = last_address;
DEBUG_PRINT(sfree(p227););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p918 = last_address;
PRINT_POINTER(srealloc(p699,131););
printStats();
void* p919 = last_address;
DEBUG_PRINT(sfree(p616););
printStats();
PRINT_POINTER(srealloc(p397,201););
printStats();
void* p920 = last_address;
DEBUG_PRINT(sfree(p771););
printStats();
PRINT_POINTER(srealloc(p920,211););
printStats();
void* p921 = last_address;
PRINT_POINTER(srealloc(p770,108););
printStats();
void* p922 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p923 = last_address;
PRINT_POINTER(scalloc(19,218););
printStats();
void* p924 = last_address;
DEBUG_PRINT(sfree(p351););
printStats();
PRINT_POINTER(scalloc(15,117););
printStats();
void* p925 = last_address;
PRINT_POINTER(scalloc(89,174););
printStats();
void* p926 = last_address;
PRINT_POINTER(srealloc(p795,228););
printStats();
void* p927 = last_address;
PRINT_POINTER(scalloc(115,116););
printStats();
void* p928 = last_address;
DEBUG_PRINT(sfree(p903););
printStats();
PRINT_POINTER(scalloc(174,28););
printStats();
void* p929 = last_address;
DEBUG_PRINT(sfree(p588););
printStats();
DEBUG_PRINT(sfree(p838););
printStats();
PRINT_POINTER(srealloc(p766,232););
printStats();
void* p930 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p931 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p932 = last_address;
PRINT_POINTER(scalloc(148,2););
printStats();
void* p933 = last_address;
PRINT_POINTER(srealloc(p863,105););
printStats();
void* p934 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p935 = last_address;
DEBUG_PRINT(sfree(p353););
printStats();
PRINT_POINTER(srealloc(p412,42););
printStats();
void* p936 = last_address;
DEBUG_PRINT(sfree(p829););
printStats();
PRINT_POINTER(srealloc(p653,10););
printStats();
void* p937 = last_address;
PRINT_POINTER(srealloc(p719,213););
printStats();
void* p938 = last_address;
PRINT_POINTER(srealloc(p590,38););
printStats();
void* p939 = last_address;
PRINT_POINTER(srealloc(p896,73););
printStats();
void* p940 = last_address;
DEBUG_PRINT(sfree(p686););
printStats();
PRINT_POINTER(srealloc(p713,176););
printStats();
void* p941 = last_address;
PRINT_POINTER(scalloc(4,53););
printStats();
void* p942 = last_address;
PRINT_POINTER(scalloc(67,183););
printStats();
void* p943 = last_address;
PRINT_POINTER(srealloc(p711,220););
printStats();
void* p944 = last_address;
PRINT_POINTER(scalloc(203,12););
printStats();
void* p945 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p946 = last_address;
DEBUG_PRINT(sfree(p871););
printStats();
DEBUG_PRINT(sfree(p909););
printStats();
PRINT_POINTER(srealloc(p933,229););
printStats();
void* p947 = last_address;
PRINT_POINTER(srealloc(p843,187););
printStats();
void* p948 = last_address;
PRINT_POINTER(scalloc(213,42););
printStats();
void* p949 = last_address;
DEBUG_PRINT(sfree(p431););
printStats();
PRINT_POINTER(smalloc(117););
printStats();
void* p950 = last_address;
PRINT_POINTER(scalloc(144,9););
printStats();
void* p951 = last_address;
PRINT_POINTER(srealloc(p466,188););
printStats();
void* p952 = last_address;
PRINT_POINTER(scalloc(111,163););
printStats();
void* p953 = last_address;
PRINT_POINTER(scalloc(64,154););
printStats();
void* p954 = last_address;
PRINT_POINTER(scalloc(223,64););
printStats();
void* p955 = last_address;
DEBUG_PRINT(sfree(p638););
printStats();
PRINT_POINTER(smalloc(122););
printStats();
void* p956 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p957 = last_address;
DEBUG_PRINT(sfree(p746););
printStats();
DEBUG_PRINT(sfree(p847););
printStats();
PRINT_POINTER(scalloc(115,8););
printStats();
void* p958 = last_address;
PRINT_POINTER(scalloc(140,178););
printStats();
void* p959 = last_address;
PRINT_POINTER(scalloc(183,229););
printStats();
void* p960 = last_address;
PRINT_POINTER(scalloc(117,33););
printStats();
void* p961 = last_address;
PRINT_POINTER(srealloc(p816,13););
printStats();
void* p962 = last_address;
PRINT_POINTER(scalloc(113,222););
printStats();
void* p963 = last_address;
PRINT_POINTER(srealloc(p818,27););
printStats();
void* p964 = last_address;
PRINT_POINTER(scalloc(214,6););
printStats();
void* p965 = last_address;
DEBUG_PRINT(sfree(p891););
printStats();
DEBUG_PRINT(sfree(p808););
printStats();
PRINT_POINTER(smalloc(230););
printStats();
void* p966 = last_address;
PRINT_POINTER(scalloc(14,63););
printStats();
void* p967 = last_address;
DEBUG_PRINT(sfree(p924););
printStats();
PRINT_POINTER(scalloc(95,7););
printStats();
void* p968 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p969 = last_address;
DEBUG_PRINT(sfree(p925););
printStats();
PRINT_POINTER(srealloc(p689,197););
printStats();
void* p970 = last_address;
DEBUG_PRINT(sfree(p884););
printStats();
PRINT_POINTER(scalloc(109,165););
printStats();
void* p971 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p972 = last_address;
DEBUG_PRINT(sfree(p437););
printStats();
PRINT_POINTER(srealloc(p966,151););
printStats();
void* p973 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p974 = last_address;
PRINT_POINTER(srealloc(p916,177););
printStats();
void* p975 = last_address;
PRINT_POINTER(srealloc(p975,30););
printStats();
void* p976 = last_address;
PRINT_POINTER(scalloc(220,162););
printStats();
void* p977 = last_address;
DEBUG_PRINT(sfree(p874););
printStats();
PRINT_POINTER(smalloc(105););
printStats();
void* p978 = last_address;
DEBUG_PRINT(sfree(p934););
printStats();
PRINT_POINTER(srealloc(p545,184););
printStats();
void* p979 = last_address;
PRINT_POINTER(scalloc(59,7););
printStats();
void* p980 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p981 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p982 = last_address;
DEBUG_PRINT(sfree(p553););
printStats();
PRINT_POINTER(smalloc(32););
printStats();
void* p983 = last_address;
PRINT_POINTER(scalloc(225,171););
printStats();
void* p984 = last_address;
PRINT_POINTER(scalloc(122,85););
printStats();
void* p985 = last_address;
DEBUG_PRINT(sfree(p523););
printStats();
PRINT_POINTER(smalloc(136););
printStats();
void* p986 = last_address;
PRINT_POINTER(scalloc(93,240););
printStats();
void* p987 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p988 = last_address;
PRINT_POINTER(srealloc(p820,168););
printStats();
void* p989 = last_address;
PRINT_POINTER(scalloc(16,94););
printStats();
void* p990 = last_address;
PRINT_POINTER(scalloc(60,43););
printStats();
void* p991 = last_address;
DEBUG_PRINT(sfree(p754););
printStats();
PRINT_POINTER(srealloc(p700,127););
printStats();
void* p992 = last_address;
PRINT_POINTER(scalloc(43,221););
printStats();
void* p993 = last_address;
PRINT_POINTER(scalloc(187,89););
printStats();
void* p994 = last_address;
DEBUG_PRINT(sfree(p380););
printStats();
PRINT_POINTER(srealloc(p967,114););
printStats();
void* p995 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p996 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p997 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p998 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p999 = last_address;
DEBUG_PRINT(sfree(p768););
printStats();
DEBUG_PRINT(sfree(p476););
printStats();
DEBUG_PRINT(sfree(p296););
printStats();
DEBUG_PRINT(sfree(p956););
printStats();
PRINT_POINTER(srealloc(p762,150););
printStats();
void* p1000 = last_address;
DEBUG_PRINT(sfree(p822););
printStats();
PRINT_POINTER(scalloc(172,236););
printStats();
void* p1001 = last_address;
PRINT_POINTER(scalloc(103,16););
printStats();
void* p1002 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p1003 = last_address;
DEBUG_PRINT(sfree(p815););
printStats();
DEBUG_PRINT(sfree(p893););
printStats();
DEBUG_PRINT(sfree(p177););
printStats();
DEBUG_PRINT(sfree(p681););
printStats();
PRINT_POINTER(smalloc(10););
printStats();
void* p1004 = last_address;
DEBUG_PRINT(sfree(p730););
printStats();
DEBUG_PRINT(sfree(p831););
printStats();
DEBUG_PRINT(sfree(p755););
printStats();
PRINT_POINTER(smalloc(238););
printStats();
void* p1005 = last_address;
PRINT_POINTER(scalloc(249,116););
printStats();
void* p1006 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p1007 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p1008 = last_address;
DEBUG_PRINT(sfree(p852););
printStats();
DEBUG_PRINT(sfree(p368););
printStats();
DEBUG_PRINT(sfree(p883););
printStats();
DEBUG_PRINT(sfree(p950););
printStats();
PRINT_POINTER(smalloc(3););
printStats();
void* p1009 = last_address;
DEBUG_PRINT(sfree(p928););
printStats();
PRINT_POINTER(scalloc(20,8););
printStats();
void* p1010 = last_address;
DEBUG_PRINT(sfree(p772););
printStats();
PRINT_POINTER(srealloc(p744,173););
printStats();
void* p1011 = last_address;
PRINT_POINTER(srealloc(p904,196););
printStats();
void* p1012 = last_address;
PRINT_POINTER(srealloc(p737,88););
printStats();
void* p1013 = last_address;
PRINT_POINTER(scalloc(198,53););
printStats();
void* p1014 = last_address;
PRINT_POINTER(scalloc(142,7););
printStats();
void* p1015 = last_address;
DEBUG_PRINT(sfree(p932););
printStats();
PRINT_POINTER(smalloc(86););
printStats();
void* p1016 = last_address;
DEBUG_PRINT(sfree(p636););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p1017 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p1018 = last_address;
DEBUG_PRINT(sfree(p833););
printStats();
PRINT_POINTER(smalloc(172););
printStats();
void* p1019 = last_address;
PRINT_POINTER(srealloc(p970,59););
printStats();
void* p1020 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p1021 = last_address;
PRINT_POINTER(srealloc(p416,92););
printStats();
void* p1022 = last_address;
PRINT_POINTER(scalloc(24,217););
printStats();
void* p1023 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p1024 = last_address;
PRINT_POINTER(scalloc(63,1););
printStats();
void* p1025 = last_address;
PRINT_POINTER(srealloc(p921,111););
printStats();
void* p1026 = last_address;
DEBUG_PRINT(sfree(p986););
printStats();
PRINT_POINTER(srealloc(p395,171););
printStats();
void* p1027 = last_address;
DEBUG_PRINT(sfree(p542););
printStats();
PRINT_POINTER(scalloc(36,145););
printStats();
void* p1028 = last_address;
DEBUG_PRINT(sfree(p1019););
printStats();
PRINT_POINTER(smalloc(159););
printStats();
void* p1029 = last_address;
DEBUG_PRINT(sfree(p914););
printStats();
PRINT_POINTER(srealloc(p809,32););
printStats();
void* p1030 = last_address;
PRINT_POINTER(scalloc(244,233););
printStats();
void* p1031 = last_address;
PRINT_POINTER(srealloc(p706,226););
printStats();
void* p1032 = last_address;
PRINT_POINTER(scalloc(207,174););
printStats();
void* p1033 = last_address;
DEBUG_PRINT(sfree(p382););
printStats();
PRINT_POINTER(smalloc(234););
printStats();
void* p1034 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p1035 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p1036 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p1037 = last_address;
PRINT_POINTER(srealloc(p495,187););
printStats();
void* p1038 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p1039 = last_address;
DEBUG_PRINT(sfree(p749););
printStats();
PRINT_POINTER(smalloc(172););
printStats();
void* p1040 = last_address;
PRINT_POINTER(srealloc(p981,179););
printStats();
void* p1041 = last_address;
PRINT_POINTER(srealloc(p753,128););
printStats();
void* p1042 = last_address;
PRINT_POINTER(scalloc(116,239););
printStats();
void* p1043 = last_address;
PRINT_POINTER(scalloc(53,43););
printStats();
void* p1044 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p1045 = last_address;
PRINT_POINTER(srealloc(p860,18););
printStats();
void* p1046 = last_address;
PRINT_POINTER(scalloc(5,240););
printStats();
void* p1047 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p1048 = last_address;
DEBUG_PRINT(sfree(p937););
printStats();
DEBUG_PRINT(sfree(p178););
printStats();
DEBUG_PRINT(sfree(p869););
printStats();
DEBUG_PRINT(sfree(p1042););
printStats();
DEBUG_PRINT(sfree(p1028););
printStats();
DEBUG_PRINT(sfree(p957););
printStats();
PRINT_POINTER(scalloc(211,12););
printStats();
void* p1049 = last_address;
PRINT_POINTER(scalloc(162,106););
printStats();
void* p1050 = last_address;
PRINT_POINTER(srealloc(p908,54););
printStats();
void* p1051 = last_address;
PRINT_POINTER(scalloc(197,154););
printStats();
void* p1052 = last_address;
PRINT_POINTER(scalloc(7,62););
printStats();
void* p1053 = last_address;
PRINT_POINTER(srealloc(p1002,76););
printStats();
void* p1054 = last_address;
PRINT_POINTER(scalloc(40,168););
printStats();
void* p1055 = last_address;
PRINT_POINTER(smalloc(221););
printStats();
void* p1056 = last_address;
DEBUG_PRINT(sfree(p1000););
printStats();
PRINT_POINTER(scalloc(130,190););
printStats();
void* p1057 = last_address;
PRINT_POINTER(srealloc(p1048,151););
printStats();
void* p1058 = last_address;
PRINT_POINTER(scalloc(97,104););
printStats();
void* p1059 = last_address;
DEBUG_PRINT(sfree(p890););
printStats();
PRINT_POINTER(srealloc(p899,206););
printStats();
void* p1060 = last_address;
PRINT_POINTER(srealloc(p673,80););
printStats();
void* p1061 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p1062 = last_address;
DEBUG_PRINT(sfree(p536););
printStats();
PRINT_POINTER(srealloc(p1045,93););
printStats();
void* p1063 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p1064 = last_address;
PRINT_POINTER(scalloc(131,155););
printStats();
void* p1065 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p1066 = last_address;
DEBUG_PRINT(sfree(p393););
printStats();
PRINT_POINTER(srealloc(p567,225););
printStats();
void* p1067 = last_address;
DEBUG_PRINT(sfree(p1066););
printStats();
PRINT_POINTER(smalloc(208););
printStats();
void* p1068 = last_address;
PRINT_POINTER(srealloc(p586,230););
printStats();
void* p1069 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p1070 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p1071 = last_address;
PRINT_POINTER(scalloc(207,207););
printStats();
void* p1072 = last_address;
PRINT_POINTER(scalloc(200,89););
printStats();
void* p1073 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p1074 = last_address;
DEBUG_PRINT(sfree(p850););
printStats();
PRINT_POINTER(scalloc(132,217););
printStats();
void* p1075 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p1076 = last_address;
DEBUG_PRINT(sfree(p666););
printStats();
PRINT_POINTER(srealloc(p936,123););
printStats();
void* p1077 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p1078 = last_address;
PRINT_POINTER(srealloc(p791,81););
printStats();
void* p1079 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p1080 = last_address;
PRINT_POINTER(scalloc(237,184););
printStats();
void* p1081 = last_address;
}
