#include "aux_macro.h"
#include "../malloc_2.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(167,115););
printStats();
void* p0 = last_address;
PRINT_POINTER(srealloc(p0,220););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(smalloc(109););
printStats();
void* p2 = last_address;
PRINT_POINTER(scalloc(41,213););
printStats();
void* p3 = last_address;
PRINT_POINTER(srealloc(p3,149););
printStats();
void* p4 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p5 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
PRINT_POINTER(srealloc(p5,215););
printStats();
void* p6 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p7 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(smalloc(1););
printStats();
void* p8 = last_address;
PRINT_POINTER(srealloc(p7,185););
printStats();
void* p9 = last_address;
PRINT_POINTER(scalloc(172,150););
printStats();
void* p10 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p11 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p12 = last_address;
PRINT_POINTER(srealloc(p8,13););
printStats();
void* p13 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p14 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p15 = last_address;
PRINT_POINTER(srealloc(p10,188););
printStats();
void* p16 = last_address;
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(srealloc(p11,152););
printStats();
void* p17 = last_address;
DEBUG_PRINT(sfree(p6););
printStats();
DEBUG_PRINT(sfree(p12););
printStats();
PRINT_POINTER(scalloc(219,191););
printStats();
void* p18 = last_address;
PRINT_POINTER(srealloc(p13,142););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p20 = last_address;
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(smalloc(184););
printStats();
void* p21 = last_address;
PRINT_POINTER(scalloc(214,243););
printStats();
void* p22 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p23 = last_address;
PRINT_POINTER(srealloc(p20,99););
printStats();
void* p24 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(194,103););
printStats();
void* p26 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p27 = last_address;
PRINT_POINTER(srealloc(p19,171););
printStats();
void* p28 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(smalloc(12););
printStats();
void* p29 = last_address;
DEBUG_PRINT(sfree(p26););
printStats();
DEBUG_PRINT(sfree(p24););
printStats();
DEBUG_PRINT(sfree(p25););
printStats();
PRINT_POINTER(scalloc(84,119););
printStats();
void* p30 = last_address;
PRINT_POINTER(scalloc(74,4););
printStats();
void* p31 = last_address;
PRINT_POINTER(srealloc(p15,188););
printStats();
void* p32 = last_address;
PRINT_POINTER(scalloc(105,83););
printStats();
void* p33 = last_address;
PRINT_POINTER(srealloc(p23,10););
printStats();
void* p34 = last_address;
PRINT_POINTER(scalloc(128,247););
printStats();
void* p35 = last_address;
PRINT_POINTER(scalloc(3,246););
printStats();
void* p36 = last_address;
PRINT_POINTER(scalloc(83,46););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(139,131););
printStats();
void* p38 = last_address;
PRINT_POINTER(scalloc(239,75););
printStats();
void* p39 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p39,248););
printStats();
void* p41 = last_address;
DEBUG_PRINT(sfree(p32););
printStats();
DEBUG_PRINT(sfree(p31););
printStats();
PRINT_POINTER(scalloc(161,115););
printStats();
void* p42 = last_address;
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(scalloc(128,236););
printStats();
void* p43 = last_address;
DEBUG_PRINT(sfree(p9););
printStats();
PRINT_POINTER(srealloc(p27,236););
printStats();
void* p44 = last_address;
PRINT_POINTER(scalloc(213,169););
printStats();
void* p45 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(scalloc(24,185););
printStats();
void* p46 = last_address;
PRINT_POINTER(scalloc(66,40););
printStats();
void* p47 = last_address;
PRINT_POINTER(scalloc(33,202););
printStats();
void* p48 = last_address;
PRINT_POINTER(srealloc(p41,103););
printStats();
void* p49 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p50 = last_address;
PRINT_POINTER(srealloc(p40,227););
printStats();
void* p51 = last_address;
PRINT_POINTER(scalloc(131,128););
printStats();
void* p52 = last_address;
PRINT_POINTER(scalloc(230,201););
printStats();
void* p53 = last_address;
PRINT_POINTER(srealloc(p47,62););
printStats();
void* p54 = last_address;
PRINT_POINTER(scalloc(35,52););
printStats();
void* p55 = last_address;
PRINT_POINTER(scalloc(196,60););
printStats();
void* p56 = last_address;
DEBUG_PRINT(sfree(p53););
printStats();
PRINT_POINTER(smalloc(212););
printStats();
void* p57 = last_address;
PRINT_POINTER(srealloc(p55,95););
printStats();
void* p58 = last_address;
PRINT_POINTER(scalloc(111,232););
printStats();
void* p59 = last_address;
PRINT_POINTER(scalloc(205,83););
printStats();
void* p60 = last_address;
PRINT_POINTER(scalloc(205,202););
printStats();
void* p61 = last_address;
PRINT_POINTER(srealloc(p43,89););
printStats();
void* p62 = last_address;
PRINT_POINTER(scalloc(38,120););
printStats();
void* p63 = last_address;
PRINT_POINTER(srealloc(p42,72););
printStats();
void* p64 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p65 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p66 = last_address;
PRINT_POINTER(scalloc(230,117););
printStats();
void* p67 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(scalloc(84,136););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p61,1););
printStats();
void* p69 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
PRINT_POINTER(smalloc(84););
printStats();
void* p70 = last_address;
PRINT_POINTER(scalloc(246,70););
printStats();
void* p71 = last_address;
PRINT_POINTER(scalloc(107,139););
printStats();
void* p72 = last_address;
PRINT_POINTER(srealloc(p65,245););
printStats();
void* p73 = last_address;
PRINT_POINTER(scalloc(22,128););
printStats();
void* p74 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p75 = last_address;
PRINT_POINTER(srealloc(p60,33););
printStats();
void* p76 = last_address;
PRINT_POINTER(scalloc(125,32););
printStats();
void* p77 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p78 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
DEBUG_PRINT(sfree(p56););
printStats();
PRINT_POINTER(scalloc(219,166););
printStats();
void* p79 = last_address;
PRINT_POINTER(scalloc(125,231););
printStats();
void* p80 = last_address;
PRINT_POINTER(scalloc(99,224););
printStats();
void* p81 = last_address;
PRINT_POINTER(scalloc(211,108););
printStats();
void* p82 = last_address;
PRINT_POINTER(srealloc(p44,191););
printStats();
void* p83 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p84 = last_address;
PRINT_POINTER(srealloc(p49,225););
printStats();
void* p85 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p86 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p87 = last_address;
DEBUG_PRINT(sfree(p71););
printStats();
PRINT_POINTER(srealloc(p85,83););
printStats();
void* p88 = last_address;
PRINT_POINTER(scalloc(17,79););
printStats();
void* p89 = last_address;
PRINT_POINTER(scalloc(236,73););
printStats();
void* p90 = last_address;
PRINT_POINTER(srealloc(p33,157););
printStats();
void* p91 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(smalloc(178););
printStats();
void* p92 = last_address;
DEBUG_PRINT(sfree(p52););
printStats();
DEBUG_PRINT(sfree(p79););
printStats();
DEBUG_PRINT(sfree(p54););
printStats();
PRINT_POINTER(scalloc(214,124););
printStats();
void* p93 = last_address;
PRINT_POINTER(scalloc(170,17););
printStats();
void* p94 = last_address;
PRINT_POINTER(scalloc(146,180););
printStats();
void* p95 = last_address;
PRINT_POINTER(srealloc(p69,220););
printStats();
void* p96 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p97 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p98 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p99 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p100 = last_address;
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(smalloc(214););
printStats();
void* p101 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
DEBUG_PRINT(sfree(p76););
printStats();
PRINT_POINTER(srealloc(p97,98););
printStats();
void* p102 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p103 = last_address;
PRINT_POINTER(scalloc(142,119););
printStats();
void* p104 = last_address;
DEBUG_PRINT(sfree(p92););
printStats();
PRINT_POINTER(srealloc(p63,171););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p103,151););
printStats();
void* p106 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p107 = last_address;
DEBUG_PRINT(sfree(p87););
printStats();
PRINT_POINTER(srealloc(p82,7););
printStats();
void* p108 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p109 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p110 = last_address;
PRINT_POINTER(scalloc(204,159););
printStats();
void* p111 = last_address;
PRINT_POINTER(scalloc(141,66););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p107,207););
printStats();
void* p113 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p114 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p115 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(scalloc(116,223););
printStats();
void* p116 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(smalloc(37););
printStats();
void* p117 = last_address;
PRINT_POINTER(scalloc(177,226););
printStats();
void* p118 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p119 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
DEBUG_PRINT(sfree(p57););
printStats();
PRINT_POINTER(srealloc(p101,31););
printStats();
void* p120 = last_address;
PRINT_POINTER(scalloc(164,87););
printStats();
void* p121 = last_address;
PRINT_POINTER(scalloc(17,6););
printStats();
void* p122 = last_address;
DEBUG_PRINT(sfree(p112););
printStats();
PRINT_POINTER(smalloc(123););
printStats();
void* p123 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
PRINT_POINTER(smalloc(178););
printStats();
void* p124 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p125 = last_address;
PRINT_POINTER(srealloc(p74,212););
printStats();
void* p126 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p127 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p128 = last_address;
DEBUG_PRINT(sfree(p99););
printStats();
PRINT_POINTER(scalloc(21,221););
printStats();
void* p129 = last_address;
PRINT_POINTER(srealloc(p127,238););
printStats();
void* p130 = last_address;
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(srealloc(p104,233););
printStats();
void* p131 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p132 = last_address;
DEBUG_PRINT(sfree(p117););
printStats();
PRINT_POINTER(smalloc(101););
printStats();
void* p133 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p134 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
DEBUG_PRINT(sfree(p93););
printStats();
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(scalloc(203,172););
printStats();
void* p135 = last_address;
PRINT_POINTER(srealloc(p30,43););
printStats();
void* p136 = last_address;
PRINT_POINTER(scalloc(105,172););
printStats();
void* p137 = last_address;
PRINT_POINTER(srealloc(p134,13););
printStats();
void* p138 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p139 = last_address;
PRINT_POINTER(srealloc(p48,131););
printStats();
void* p140 = last_address;
PRINT_POINTER(srealloc(p59,31););
printStats();
void* p141 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p142 = last_address;
PRINT_POINTER(srealloc(p62,43););
printStats();
void* p143 = last_address;
PRINT_POINTER(srealloc(p64,112););
printStats();
void* p144 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p145 = last_address;
PRINT_POINTER(scalloc(153,20););
printStats();
void* p146 = last_address;
PRINT_POINTER(srealloc(p124,34););
printStats();
void* p147 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p148 = last_address;
PRINT_POINTER(srealloc(p106,165););
printStats();
void* p149 = last_address;
PRINT_POINTER(srealloc(p113,42););
printStats();
void* p150 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(scalloc(218,98););
printStats();
void* p151 = last_address;
DEBUG_PRINT(sfree(p115););
printStats();
PRINT_POINTER(scalloc(91,169););
printStats();
void* p152 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(scalloc(148,85););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(20,204););
printStats();
void* p154 = last_address;
PRINT_POINTER(scalloc(35,40););
printStats();
void* p155 = last_address;
PRINT_POINTER(scalloc(242,86););
printStats();
void* p156 = last_address;
PRINT_POINTER(scalloc(101,245););
printStats();
void* p157 = last_address;
PRINT_POINTER(srealloc(p35,166););
printStats();
void* p158 = last_address;
PRINT_POINTER(scalloc(105,217););
printStats();
void* p159 = last_address;
PRINT_POINTER(scalloc(72,52););
printStats();
void* p160 = last_address;
PRINT_POINTER(scalloc(54,14););
printStats();
void* p161 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p162 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p163 = last_address;
PRINT_POINTER(scalloc(201,182););
printStats();
void* p164 = last_address;
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(scalloc(60,88););
printStats();
void* p165 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
PRINT_POINTER(scalloc(2,119););
printStats();
void* p166 = last_address;
DEBUG_PRINT(sfree(p165););
printStats();
PRINT_POINTER(scalloc(247,208););
printStats();
void* p167 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(srealloc(p86,127););
printStats();
void* p168 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p169 = last_address;
PRINT_POINTER(scalloc(33,244););
printStats();
void* p170 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
PRINT_POINTER(smalloc(26););
printStats();
void* p171 = last_address;
DEBUG_PRINT(sfree(p67););
printStats();
PRINT_POINTER(srealloc(p133,190););
printStats();
void* p172 = last_address;
PRINT_POINTER(srealloc(p130,53););
printStats();
void* p173 = last_address;
DEBUG_PRINT(sfree(p108););
printStats();
PRINT_POINTER(srealloc(p80,127););
printStats();
void* p174 = last_address;
PRINT_POINTER(scalloc(203,54););
printStats();
void* p175 = last_address;
PRINT_POINTER(scalloc(209,17););
printStats();
void* p176 = last_address;
PRINT_POINTER(scalloc(55,219););
printStats();
void* p177 = last_address;
PRINT_POINTER(srealloc(p88,73););
printStats();
void* p178 = last_address;
PRINT_POINTER(srealloc(p170,46););
printStats();
void* p179 = last_address;
PRINT_POINTER(scalloc(66,122););
printStats();
void* p180 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p181 = last_address;
PRINT_POINTER(scalloc(4,99););
printStats();
void* p182 = last_address;
PRINT_POINTER(scalloc(109,154););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(84,149););
printStats();
void* p184 = last_address;
PRINT_POINTER(srealloc(p128,150););
printStats();
void* p185 = last_address;
PRINT_POINTER(scalloc(137,154););
printStats();
void* p186 = last_address;
PRINT_POINTER(scalloc(228,147););
printStats();
void* p187 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p188 = last_address;
PRINT_POINTER(srealloc(p179,28););
printStats();
void* p189 = last_address;
PRINT_POINTER(srealloc(p131,61););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p191 = last_address;
PRINT_POINTER(scalloc(216,128););
printStats();
void* p192 = last_address;
DEBUG_PRINT(sfree(p149););
printStats();
PRINT_POINTER(smalloc(62););
printStats();
void* p193 = last_address;
PRINT_POINTER(scalloc(104,199););
printStats();
void* p194 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
PRINT_POINTER(srealloc(p68,156););
printStats();
void* p195 = last_address;
PRINT_POINTER(scalloc(38,146););
printStats();
void* p196 = last_address;
DEBUG_PRINT(sfree(p83););
printStats();
PRINT_POINTER(scalloc(174,109););
printStats();
void* p197 = last_address;
PRINT_POINTER(srealloc(p145,98););
printStats();
void* p198 = last_address;
PRINT_POINTER(scalloc(93,226););
printStats();
void* p199 = last_address;
DEBUG_PRINT(sfree(p58););
printStats();
PRINT_POINTER(smalloc(131););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p51,183););
printStats();
void* p201 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p202 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p203 = last_address;
PRINT_POINTER(scalloc(74,17););
printStats();
void* p204 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p205 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(srealloc(p125,188););
printStats();
void* p206 = last_address;
PRINT_POINTER(scalloc(199,77););
printStats();
void* p207 = last_address;
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(srealloc(p153,208););
printStats();
void* p208 = last_address;
PRINT_POINTER(scalloc(33,149););
printStats();
void* p209 = last_address;
DEBUG_PRINT(sfree(p154););
printStats();
PRINT_POINTER(srealloc(p188,188););
printStats();
void* p210 = last_address;
PRINT_POINTER(srealloc(p202,8););
printStats();
void* p211 = last_address;
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(srealloc(p164,145););
printStats();
void* p212 = last_address;
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(srealloc(p138,8););
printStats();
void* p213 = last_address;
PRINT_POINTER(srealloc(p142,186););
printStats();
void* p214 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p215 = last_address;
PRINT_POINTER(scalloc(59,220););
printStats();
void* p216 = last_address;
PRINT_POINTER(srealloc(p143,106););
printStats();
void* p217 = last_address;
PRINT_POINTER(scalloc(42,53););
printStats();
void* p218 = last_address;
DEBUG_PRINT(sfree(p194););
printStats();
PRINT_POINTER(scalloc(221,129););
printStats();
void* p219 = last_address;
PRINT_POINTER(scalloc(221,27););
printStats();
void* p220 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p221 = last_address;
PRINT_POINTER(scalloc(99,198););
printStats();
void* p222 = last_address;
PRINT_POINTER(scalloc(182,35););
printStats();
void* p223 = last_address;
PRINT_POINTER(scalloc(245,25););
printStats();
void* p224 = last_address;
DEBUG_PRINT(sfree(p192););
printStats();
DEBUG_PRINT(sfree(p211););
printStats();
DEBUG_PRINT(sfree(p132););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p225 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(srealloc(p183,146););
printStats();
void* p226 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p227 = last_address;
PRINT_POINTER(srealloc(p209,100););
printStats();
void* p228 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p229 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(srealloc(p122,28););
printStats();
void* p230 = last_address;
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(srealloc(p226,38););
printStats();
void* p231 = last_address;
PRINT_POINTER(scalloc(225,110););
printStats();
void* p232 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p233 = last_address;
PRINT_POINTER(srealloc(p111,224););
printStats();
void* p234 = last_address;
PRINT_POINTER(srealloc(p191,110););
printStats();
void* p235 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
DEBUG_PRINT(sfree(p187););
printStats();
PRINT_POINTER(smalloc(195););
printStats();
void* p236 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p237 = last_address;
PRINT_POINTER(srealloc(p228,184););
printStats();
void* p238 = last_address;
PRINT_POINTER(scalloc(217,33););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p118,144););
printStats();
void* p240 = last_address;
PRINT_POINTER(srealloc(p28,127););
printStats();
void* p241 = last_address;
PRINT_POINTER(scalloc(141,179););
printStats();
void* p242 = last_address;
PRINT_POINTER(srealloc(p204,41););
printStats();
void* p243 = last_address;
PRINT_POINTER(scalloc(204,211););
printStats();
void* p244 = last_address;
PRINT_POINTER(scalloc(231,184););
printStats();
void* p245 = last_address;
PRINT_POINTER(scalloc(167,34););
printStats();
void* p246 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p247 = last_address;
PRINT_POINTER(srealloc(p95,242););
printStats();
void* p248 = last_address;
PRINT_POINTER(srealloc(p156,61););
printStats();
void* p249 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p250 = last_address;
PRINT_POINTER(srealloc(p199,18););
printStats();
void* p251 = last_address;
PRINT_POINTER(srealloc(p173,143););
printStats();
void* p252 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p253 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p254 = last_address;
PRINT_POINTER(scalloc(73,66););
printStats();
void* p255 = last_address;
DEBUG_PRINT(sfree(p241););
printStats();
PRINT_POINTER(scalloc(97,144););
printStats();
void* p256 = last_address;
PRINT_POINTER(scalloc(244,249););
printStats();
void* p257 = last_address;
DEBUG_PRINT(sfree(p140););
printStats();
DEBUG_PRINT(sfree(p198););
printStats();
PRINT_POINTER(srealloc(p253,163););
printStats();
void* p258 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p259 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p260 = last_address;
PRINT_POINTER(scalloc(7,26););
printStats();
void* p261 = last_address;
PRINT_POINTER(srealloc(p167,26););
printStats();
void* p262 = last_address;
PRINT_POINTER(scalloc(212,192););
printStats();
void* p263 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p264 = last_address;
PRINT_POINTER(srealloc(p250,208););
printStats();
void* p265 = last_address;
PRINT_POINTER(scalloc(176,57););
printStats();
void* p266 = last_address;
PRINT_POINTER(srealloc(p135,169););
printStats();
void* p267 = last_address;
DEBUG_PRINT(sfree(p163););
printStats();
PRINT_POINTER(srealloc(p229,93););
printStats();
void* p268 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p269 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
PRINT_POINTER(srealloc(p223,36););
printStats();
void* p270 = last_address;
DEBUG_PRINT(sfree(p265););
printStats();
DEBUG_PRINT(sfree(p159););
printStats();
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(smalloc(70););
printStats();
void* p271 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p272 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p273 = last_address;
PRINT_POINTER(srealloc(p219,30););
printStats();
void* p274 = last_address;
PRINT_POINTER(srealloc(p168,61););
printStats();
void* p275 = last_address;
PRINT_POINTER(scalloc(115,202););
printStats();
void* p276 = last_address;
PRINT_POINTER(scalloc(88,49););
printStats();
void* p277 = last_address;
PRINT_POINTER(scalloc(107,54););
printStats();
void* p278 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p279 = last_address;
PRINT_POINTER(srealloc(p160,66););
printStats();
void* p280 = last_address;
PRINT_POINTER(scalloc(53,177););
printStats();
void* p281 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
PRINT_POINTER(smalloc(222););
printStats();
void* p282 = last_address;
DEBUG_PRINT(sfree(p213););
printStats();
DEBUG_PRINT(sfree(p230););
printStats();
PRINT_POINTER(srealloc(p96,190););
printStats();
void* p283 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p284 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
PRINT_POINTER(srealloc(p193,19););
printStats();
void* p285 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p286 = last_address;
PRINT_POINTER(scalloc(147,156););
printStats();
void* p287 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
PRINT_POINTER(smalloc(216););
printStats();
void* p288 = last_address;
PRINT_POINTER(scalloc(114,51););
printStats();
void* p289 = last_address;
DEBUG_PRINT(sfree(p217););
printStats();
PRINT_POINTER(scalloc(216,49););
printStats();
void* p290 = last_address;
PRINT_POINTER(srealloc(p157,89););
printStats();
void* p291 = last_address;
PRINT_POINTER(scalloc(247,234););
printStats();
void* p292 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
PRINT_POINTER(smalloc(145););
printStats();
void* p293 = last_address;
PRINT_POINTER(scalloc(104,68););
printStats();
void* p294 = last_address;
PRINT_POINTER(scalloc(25,212););
printStats();
void* p295 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p296 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(scalloc(96,45););
printStats();
void* p297 = last_address;
PRINT_POINTER(srealloc(p286,151););
printStats();
void* p298 = last_address;
PRINT_POINTER(srealloc(p126,81););
printStats();
void* p299 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p300 = last_address;
DEBUG_PRINT(sfree(p292););
printStats();
DEBUG_PRINT(sfree(p277););
printStats();
PRINT_POINTER(scalloc(4,152););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p302 = last_address;
PRINT_POINTER(srealloc(p271,122););
printStats();
void* p303 = last_address;
PRINT_POINTER(scalloc(26,158););
printStats();
void* p304 = last_address;
PRINT_POINTER(srealloc(p298,88););
printStats();
void* p305 = last_address;
PRINT_POINTER(scalloc(188,46););
printStats();
void* p306 = last_address;
PRINT_POINTER(scalloc(153,215););
printStats();
void* p307 = last_address;
PRINT_POINTER(scalloc(1,213););
printStats();
void* p308 = last_address;
PRINT_POINTER(srealloc(p214,108););
printStats();
void* p309 = last_address;
DEBUG_PRINT(sfree(p238););
printStats();
PRINT_POINTER(smalloc(72););
printStats();
void* p310 = last_address;
PRINT_POINTER(scalloc(122,129););
printStats();
void* p311 = last_address;
PRINT_POINTER(srealloc(p275,207););
printStats();
void* p312 = last_address;
PRINT_POINTER(srealloc(p136,121););
printStats();
void* p313 = last_address;
PRINT_POINTER(srealloc(p251,223););
printStats();
void* p314 = last_address;
DEBUG_PRINT(sfree(p221););
printStats();
PRINT_POINTER(scalloc(2,139););
printStats();
void* p315 = last_address;
PRINT_POINTER(srealloc(p311,91););
printStats();
void* p316 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p317 = last_address;
PRINT_POINTER(scalloc(223,131););
printStats();
void* p318 = last_address;
PRINT_POINTER(scalloc(41,12););
printStats();
void* p319 = last_address;
DEBUG_PRINT(sfree(p314););
printStats();
DEBUG_PRINT(sfree(p185););
printStats();
PRINT_POINTER(scalloc(4,167););
printStats();
void* p320 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p321 = last_address;
PRINT_POINTER(scalloc(153,132););
printStats();
void* p322 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p323 = last_address;
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(scalloc(100,32););
printStats();
void* p324 = last_address;
PRINT_POINTER(scalloc(72,93););
printStats();
void* p325 = last_address;
DEBUG_PRINT(sfree(p84););
printStats();
PRINT_POINTER(srealloc(p270,46););
printStats();
void* p326 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p327 = last_address;
PRINT_POINTER(srealloc(p120,95););
printStats();
void* p328 = last_address;
PRINT_POINTER(srealloc(p255,81););
printStats();
void* p329 = last_address;
PRINT_POINTER(srealloc(p318,74););
printStats();
void* p330 = last_address;
PRINT_POINTER(scalloc(213,181););
printStats();
void* p331 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p332 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p333 = last_address;
PRINT_POINTER(scalloc(46,7););
printStats();
void* p334 = last_address;
PRINT_POINTER(scalloc(96,150););
printStats();
void* p335 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p336 = last_address;
PRINT_POINTER(srealloc(p300,102););
printStats();
void* p337 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p338 = last_address;
PRINT_POINTER(srealloc(p312,208););
printStats();
void* p339 = last_address;
PRINT_POINTER(srealloc(p335,113););
printStats();
void* p340 = last_address;
PRINT_POINTER(scalloc(58,216););
printStats();
void* p341 = last_address;
PRINT_POINTER(srealloc(p301,104););
printStats();
void* p342 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p343 = last_address;
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(srealloc(p172,110););
printStats();
void* p344 = last_address;
PRINT_POINTER(srealloc(p330,23););
printStats();
void* p345 = last_address;
PRINT_POINTER(scalloc(38,141););
printStats();
void* p346 = last_address;
DEBUG_PRINT(sfree(p81););
printStats();
DEBUG_PRINT(sfree(p174););
printStats();
DEBUG_PRINT(sfree(p308););
printStats();
DEBUG_PRINT(sfree(p248););
printStats();
PRINT_POINTER(smalloc(140););
printStats();
void* p347 = last_address;
PRINT_POINTER(srealloc(p89,21););
printStats();
void* p348 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p349 = last_address;
DEBUG_PRINT(sfree(p336););
printStats();
PRINT_POINTER(srealloc(p267,70););
printStats();
void* p350 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p351 = last_address;
PRINT_POINTER(srealloc(p171,237););
printStats();
void* p352 = last_address;
DEBUG_PRINT(sfree(p283););
printStats();
DEBUG_PRINT(sfree(p246););
printStats();
DEBUG_PRINT(sfree(p291););
printStats();
PRINT_POINTER(scalloc(169,19););
printStats();
void* p353 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p354 = last_address;
PRINT_POINTER(scalloc(19,227););
printStats();
void* p355 = last_address;
DEBUG_PRINT(sfree(p331););
printStats();
DEBUG_PRINT(sfree(p332););
printStats();
PRINT_POINTER(scalloc(100,63););
printStats();
void* p356 = last_address;
PRINT_POINTER(srealloc(p66,240););
printStats();
void* p357 = last_address;
PRINT_POINTER(srealloc(p73,131););
printStats();
void* p358 = last_address;
DEBUG_PRINT(sfree(p341););
printStats();
PRINT_POINTER(srealloc(p252,104););
printStats();
void* p359 = last_address;
DEBUG_PRINT(sfree(p195););
printStats();
DEBUG_PRINT(sfree(p184););
printStats();
DEBUG_PRINT(sfree(p110););
printStats();
PRINT_POINTER(scalloc(230,53););
printStats();
void* p360 = last_address;
PRINT_POINTER(scalloc(2,245););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p362 = last_address;
DEBUG_PRINT(sfree(p304););
printStats();
PRINT_POINTER(srealloc(p262,17););
printStats();
void* p363 = last_address;
PRINT_POINTER(srealloc(p189,184););
printStats();
void* p364 = last_address;
PRINT_POINTER(srealloc(p240,147););
printStats();
void* p365 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p366 = last_address;
DEBUG_PRINT(sfree(p169););
printStats();
PRINT_POINTER(scalloc(201,139););
printStats();
void* p367 = last_address;
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(srealloc(p351,234););
printStats();
void* p368 = last_address;
PRINT_POINTER(srealloc(p353,237););
printStats();
void* p369 = last_address;
PRINT_POINTER(scalloc(126,46););
printStats();
void* p370 = last_address;
DEBUG_PRINT(sfree(p307););
printStats();
PRINT_POINTER(smalloc(227););
printStats();
void* p371 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p372 = last_address;
DEBUG_PRINT(sfree(p233););
printStats();
PRINT_POINTER(scalloc(111,222););
printStats();
void* p373 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p374 = last_address;
PRINT_POINTER(srealloc(p316,145););
printStats();
void* p375 = last_address;
DEBUG_PRINT(sfree(p256););
printStats();
PRINT_POINTER(srealloc(p347,191););
printStats();
void* p376 = last_address;
PRINT_POINTER(srealloc(p276,55););
printStats();
void* p377 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p378 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
DEBUG_PRINT(sfree(p297););
printStats();
PRINT_POINTER(smalloc(7););
printStats();
void* p379 = last_address;
PRINT_POINTER(srealloc(p296,197););
printStats();
void* p380 = last_address;
PRINT_POINTER(srealloc(p302,24););
printStats();
void* p381 = last_address;
PRINT_POINTER(srealloc(p324,62););
printStats();
void* p382 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p383 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p384 = last_address;
DEBUG_PRINT(sfree(p280););
printStats();
PRINT_POINTER(scalloc(74,32););
printStats();
void* p385 = last_address;
DEBUG_PRINT(sfree(p317););
printStats();
DEBUG_PRINT(sfree(p340););
printStats();
PRINT_POINTER(scalloc(92,44););
printStats();
void* p386 = last_address;
DEBUG_PRINT(sfree(p369););
printStats();
PRINT_POINTER(smalloc(58););
printStats();
void* p387 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p388 = last_address;
DEBUG_PRINT(sfree(p245););
printStats();
DEBUG_PRINT(sfree(p310););
printStats();
PRINT_POINTER(srealloc(p346,233););
printStats();
void* p389 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p390 = last_address;
DEBUG_PRINT(sfree(p371););
printStats();
PRINT_POINTER(srealloc(p320,38););
printStats();
void* p391 = last_address;
PRINT_POINTER(scalloc(88,66););
printStats();
void* p392 = last_address;
PRINT_POINTER(srealloc(p321,105););
printStats();
void* p393 = last_address;
DEBUG_PRINT(sfree(p326););
printStats();
PRINT_POINTER(srealloc(p137,242););
printStats();
void* p394 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p395 = last_address;
PRINT_POINTER(srealloc(p361,56););
printStats();
void* p396 = last_address;
PRINT_POINTER(scalloc(104,26););
printStats();
void* p397 = last_address;
DEBUG_PRINT(sfree(p299););
printStats();
DEBUG_PRINT(sfree(p105););
printStats();
PRINT_POINTER(smalloc(236););
printStats();
void* p398 = last_address;
PRINT_POINTER(srealloc(p261,27););
printStats();
void* p399 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p400 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p401 = last_address;
DEBUG_PRINT(sfree(p220););
printStats();
DEBUG_PRINT(sfree(p285););
printStats();
PRINT_POINTER(srealloc(p306,162););
printStats();
void* p402 = last_address;
PRINT_POINTER(srealloc(p322,61););
printStats();
void* p403 = last_address;
DEBUG_PRINT(sfree(p378););
printStats();
PRINT_POINTER(srealloc(p268,74););
printStats();
void* p404 = last_address;
PRINT_POINTER(scalloc(64,152););
printStats();
void* p405 = last_address;
PRINT_POINTER(scalloc(110,113););
printStats();
void* p406 = last_address;
DEBUG_PRINT(sfree(p349););
printStats();
PRINT_POINTER(srealloc(p259,17););
printStats();
void* p407 = last_address;
PRINT_POINTER(srealloc(p399,14););
printStats();
void* p408 = last_address;
PRINT_POINTER(srealloc(p305,198););
printStats();
void* p409 = last_address;
DEBUG_PRINT(sfree(p385););
printStats();
PRINT_POINTER(scalloc(51,172););
printStats();
void* p410 = last_address;
PRINT_POINTER(scalloc(154,221););
printStats();
void* p411 = last_address;
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(scalloc(70,246););
printStats();
void* p412 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p413 = last_address;
PRINT_POINTER(srealloc(p260,240););
printStats();
void* p414 = last_address;
DEBUG_PRINT(sfree(p327););
printStats();
PRINT_POINTER(scalloc(171,171););
printStats();
void* p415 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p416 = last_address;
PRINT_POINTER(scalloc(26,133););
printStats();
void* p417 = last_address;
DEBUG_PRINT(sfree(p373););
printStats();
PRINT_POINTER(srealloc(p394,187););
printStats();
void* p418 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p419 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(smalloc(179););
printStats();
void* p420 = last_address;
DEBUG_PRINT(sfree(p419););
printStats();
PRINT_POINTER(srealloc(p367,17););
printStats();
void* p421 = last_address;
PRINT_POINTER(scalloc(86,143););
printStats();
void* p422 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p423 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p424 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p425 = last_address;
DEBUG_PRINT(sfree(p338););
printStats();
PRINT_POINTER(smalloc(36););
printStats();
void* p426 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p427 = last_address;
PRINT_POINTER(scalloc(52,20););
printStats();
void* p428 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p429 = last_address;
PRINT_POINTER(srealloc(p319,132););
printStats();
void* p430 = last_address;
DEBUG_PRINT(sfree(p249););
printStats();
DEBUG_PRINT(sfree(p329););
printStats();
PRINT_POINTER(scalloc(60,228););
printStats();
void* p431 = last_address;
PRINT_POINTER(srealloc(p387,2););
printStats();
void* p432 = last_address;
PRINT_POINTER(srealloc(p365,60););
printStats();
void* p433 = last_address;
PRINT_POINTER(srealloc(p427,12););
printStats();
void* p434 = last_address;
DEBUG_PRINT(sfree(p182););
printStats();
PRINT_POINTER(srealloc(p75,189););
printStats();
void* p435 = last_address;
PRINT_POINTER(scalloc(168,158););
printStats();
void* p436 = last_address;
DEBUG_PRINT(sfree(p342););
printStats();
PRINT_POINTER(scalloc(183,227););
printStats();
void* p437 = last_address;
PRINT_POINTER(srealloc(p374,87););
printStats();
void* p438 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p439 = last_address;
PRINT_POINTER(srealloc(p417,168););
printStats();
void* p440 = last_address;
PRINT_POINTER(srealloc(p281,213););
printStats();
void* p441 = last_address;
DEBUG_PRINT(sfree(p345););
printStats();
DEBUG_PRINT(sfree(p235););
printStats();
PRINT_POINTER(srealloc(p379,94););
printStats();
void* p442 = last_address;
PRINT_POINTER(srealloc(p243,8););
printStats();
void* p443 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p444 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p445 = last_address;
DEBUG_PRINT(sfree(p356););
printStats();
PRINT_POINTER(srealloc(p216,151););
printStats();
void* p446 = last_address;
DEBUG_PRINT(sfree(p438););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p447 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p448 = last_address;
PRINT_POINTER(scalloc(149,106););
printStats();
void* p449 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p450 = last_address;
PRINT_POINTER(scalloc(38,192););
printStats();
void* p451 = last_address;
PRINT_POINTER(srealloc(p177,69););
printStats();
void* p452 = last_address;
PRINT_POINTER(srealloc(p350,26););
printStats();
void* p453 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p454 = last_address;
PRINT_POINTER(srealloc(p359,218););
printStats();
void* p455 = last_address;
PRINT_POINTER(scalloc(166,49););
printStats();
void* p456 = last_address;
PRINT_POINTER(srealloc(p151,21););
printStats();
void* p457 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p458 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p459 = last_address;
DEBUG_PRINT(sfree(p418););
printStats();
DEBUG_PRINT(sfree(p395););
printStats();
DEBUG_PRINT(sfree(p266););
printStats();
PRINT_POINTER(smalloc(237););
printStats();
void* p460 = last_address;
PRINT_POINTER(srealloc(p224,163););
printStats();
void* p461 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p462 = last_address;
PRINT_POINTER(scalloc(92,123););
printStats();
void* p463 = last_address;
DEBUG_PRINT(sfree(p231););
printStats();
PRINT_POINTER(smalloc(90););
printStats();
void* p464 = last_address;
PRINT_POINTER(srealloc(p323,174););
printStats();
void* p465 = last_address;
PRINT_POINTER(srealloc(p447,182););
printStats();
void* p466 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p467 = last_address;
PRINT_POINTER(scalloc(7,215););
printStats();
void* p468 = last_address;
DEBUG_PRINT(sfree(p215););
printStats();
PRINT_POINTER(smalloc(201););
printStats();
void* p469 = last_address;
PRINT_POINTER(scalloc(100,18););
printStats();
void* p470 = last_address;
PRINT_POINTER(srealloc(p444,56););
printStats();
void* p471 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p472 = last_address;
PRINT_POINTER(scalloc(55,49););
printStats();
void* p473 = last_address;
PRINT_POINTER(scalloc(190,47););
printStats();
void* p474 = last_address;
PRINT_POINTER(srealloc(p288,18););
printStats();
void* p475 = last_address;
PRINT_POINTER(scalloc(162,220););
printStats();
void* p476 = last_address;
PRINT_POINTER(srealloc(p161,37););
printStats();
void* p477 = last_address;
PRINT_POINTER(srealloc(p200,49););
printStats();
void* p478 = last_address;
DEBUG_PRINT(sfree(p402););
printStats();
PRINT_POINTER(srealloc(p303,194););
printStats();
void* p479 = last_address;
DEBUG_PRINT(sfree(p475););
printStats();
PRINT_POINTER(srealloc(p155,23););
printStats();
void* p480 = last_address;
PRINT_POINTER(srealloc(p397,58););
printStats();
void* p481 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p482 = last_address;
PRINT_POINTER(scalloc(92,126););
printStats();
void* p483 = last_address;
PRINT_POINTER(srealloc(p284,76););
printStats();
void* p484 = last_address;
DEBUG_PRINT(sfree(p457););
printStats();
DEBUG_PRINT(sfree(p448););
printStats();
PRINT_POINTER(scalloc(122,80););
printStats();
void* p485 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p486 = last_address;
PRINT_POINTER(scalloc(83,133););
printStats();
void* p487 = last_address;
PRINT_POINTER(srealloc(p287,145););
printStats();
void* p488 = last_address;
PRINT_POINTER(scalloc(8,110););
printStats();
void* p489 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p490 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p491 = last_address;
PRINT_POINTER(scalloc(136,133););
printStats();
void* p492 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p493 = last_address;
PRINT_POINTER(scalloc(51,169););
printStats();
void* p494 = last_address;
PRINT_POINTER(srealloc(p180,212););
printStats();
void* p495 = last_address;
DEBUG_PRINT(sfree(p236););
printStats();
PRINT_POINTER(srealloc(p463,126););
printStats();
void* p496 = last_address;
PRINT_POINTER(scalloc(115,163););
printStats();
void* p497 = last_address;
PRINT_POINTER(scalloc(189,209););
printStats();
void* p498 = last_address;
PRINT_POINTER(scalloc(0,147););
printStats();
void* p499 = last_address;
DEBUG_PRINT(sfree(p492););
printStats();
DEBUG_PRINT(sfree(p360););
printStats();
PRINT_POINTER(smalloc(109););
printStats();
void* p500 = last_address;
PRINT_POINTER(srealloc(p263,174););
printStats();
void* p501 = last_address;
PRINT_POINTER(scalloc(51,63););
printStats();
void* p502 = last_address;
PRINT_POINTER(scalloc(243,244););
printStats();
void* p503 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p504 = last_address;
PRINT_POINTER(srealloc(p343,171););
printStats();
void* p505 = last_address;
DEBUG_PRINT(sfree(p227););
printStats();
DEBUG_PRINT(sfree(p433););
printStats();
PRINT_POINTER(srealloc(p232,196););
printStats();
void* p506 = last_address;
DEBUG_PRINT(sfree(p459););
printStats();
PRINT_POINTER(scalloc(154,36););
printStats();
void* p507 = last_address;
PRINT_POINTER(srealloc(p430,155););
printStats();
void* p508 = last_address;
PRINT_POINTER(scalloc(71,85););
printStats();
void* p509 = last_address;
PRINT_POINTER(srealloc(p435,28););
printStats();
void* p510 = last_address;
PRINT_POINTER(srealloc(p393,87););
printStats();
void* p511 = last_address;
PRINT_POINTER(srealloc(p333,17););
printStats();
void* p512 = last_address;
PRINT_POINTER(scalloc(169,86););
printStats();
void* p513 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p514 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p515 = last_address;
DEBUG_PRINT(sfree(p477););
printStats();
PRINT_POINTER(smalloc(73););
printStats();
void* p516 = last_address;
DEBUG_PRINT(sfree(p507););
printStats();
PRINT_POINTER(srealloc(p494,109););
printStats();
void* p517 = last_address;
PRINT_POINTER(scalloc(190,14););
printStats();
void* p518 = last_address;
PRINT_POINTER(srealloc(p450,88););
printStats();
void* p519 = last_address;
PRINT_POINTER(srealloc(p472,65););
printStats();
void* p520 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p521 = last_address;
PRINT_POINTER(srealloc(p162,168););
printStats();
void* p522 = last_address;
PRINT_POINTER(srealloc(p139,67););
printStats();
void* p523 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p524 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p525 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p526 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p527 = last_address;
DEBUG_PRINT(sfree(p498););
printStats();
PRINT_POINTER(scalloc(247,131););
printStats();
void* p528 = last_address;
PRINT_POINTER(srealloc(p522,60););
printStats();
void* p529 = last_address;
PRINT_POINTER(scalloc(32,146););
printStats();
void* p530 = last_address;
PRINT_POINTER(srealloc(p428,104););
printStats();
void* p531 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p532 = last_address;
PRINT_POINTER(srealloc(p513,47););
printStats();
void* p533 = last_address;
PRINT_POINTER(scalloc(186,197););
printStats();
void* p534 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p535 = last_address;
PRINT_POINTER(scalloc(135,224););
printStats();
void* p536 = last_address;
PRINT_POINTER(scalloc(173,11););
printStats();
void* p537 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p538 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p539 = last_address;
DEBUG_PRINT(sfree(p429););
printStats();
PRINT_POINTER(scalloc(191,183););
printStats();
void* p540 = last_address;
PRINT_POINTER(scalloc(175,82););
printStats();
void* p541 = last_address;
DEBUG_PRINT(sfree(p440););
printStats();
DEBUG_PRINT(sfree(p420););
printStats();
PRINT_POINTER(srealloc(p464,41););
printStats();
void* p542 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p543 = last_address;
PRINT_POINTER(scalloc(50,143););
printStats();
void* p544 = last_address;
PRINT_POINTER(scalloc(245,182););
printStats();
void* p545 = last_address;
PRINT_POINTER(srealloc(p485,246););
printStats();
void* p546 = last_address;
PRINT_POINTER(srealloc(p461,137););
printStats();
void* p547 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p548 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p549 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p550 = last_address;
PRINT_POINTER(srealloc(p508,206););
printStats();
void* p551 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p552 = last_address;
DEBUG_PRINT(sfree(p408););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p553 = last_address;
PRINT_POINTER(srealloc(p514,201););
printStats();
void* p554 = last_address;
PRINT_POINTER(scalloc(47,150););
printStats();
void* p555 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p556 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p557 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p558 = last_address;
DEBUG_PRINT(sfree(p471););
printStats();
PRINT_POINTER(smalloc(187););
printStats();
void* p559 = last_address;
PRINT_POINTER(srealloc(p234,195););
printStats();
void* p560 = last_address;
PRINT_POINTER(srealloc(p436,175););
printStats();
void* p561 = last_address;
DEBUG_PRINT(sfree(p497););
printStats();
PRINT_POINTER(smalloc(137););
printStats();
void* p562 = last_address;
PRINT_POINTER(scalloc(244,44););
printStats();
void* p563 = last_address;
PRINT_POINTER(scalloc(205,12););
printStats();
void* p564 = last_address;
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(smalloc(228););
printStats();
void* p565 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p566 = last_address;
PRINT_POINTER(scalloc(237,245););
printStats();
void* p567 = last_address;
PRINT_POINTER(scalloc(11,14););
printStats();
void* p568 = last_address;
DEBUG_PRINT(sfree(p486););
printStats();
DEBUG_PRINT(sfree(p309););
printStats();
DEBUG_PRINT(sfree(p414););
printStats();
PRINT_POINTER(smalloc(165););
printStats();
void* p569 = last_address;
PRINT_POINTER(srealloc(p439,17););
printStats();
void* p570 = last_address;
DEBUG_PRINT(sfree(p538););
printStats();
PRINT_POINTER(smalloc(43););
printStats();
void* p571 = last_address;
PRINT_POINTER(srealloc(p382,66););
printStats();
void* p572 = last_address;
PRINT_POINTER(srealloc(p519,158););
printStats();
void* p573 = last_address;
DEBUG_PRINT(sfree(p561););
printStats();
PRINT_POINTER(srealloc(p482,34););
printStats();
void* p574 = last_address;
PRINT_POINTER(srealloc(p355,167););
printStats();
void* p575 = last_address;
DEBUG_PRINT(sfree(p470););
printStats();
PRINT_POINTER(smalloc(163););
printStats();
void* p576 = last_address;
DEBUG_PRINT(sfree(p515););
printStats();
PRINT_POINTER(scalloc(179,31););
printStats();
void* p577 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p578 = last_address;
PRINT_POINTER(scalloc(40,103););
printStats();
void* p579 = last_address;
PRINT_POINTER(scalloc(25,5););
printStats();
void* p580 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p581 = last_address;
PRINT_POINTER(scalloc(194,162););
printStats();
void* p582 = last_address;
PRINT_POINTER(srealloc(p534,75););
printStats();
void* p583 = last_address;
PRINT_POINTER(scalloc(2,175););
printStats();
void* p584 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p585 = last_address;
PRINT_POINTER(srealloc(p552,219););
printStats();
void* p586 = last_address;
DEBUG_PRINT(sfree(p544););
printStats();
DEBUG_PRINT(sfree(p567););
printStats();
PRINT_POINTER(scalloc(232,97););
printStats();
void* p587 = last_address;
PRINT_POINTER(srealloc(p571,43););
printStats();
void* p588 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p589 = last_address;
PRINT_POINTER(scalloc(117,142););
printStats();
void* p590 = last_address;
PRINT_POINTER(scalloc(127,147););
printStats();
void* p591 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p592 = last_address;
DEBUG_PRINT(sfree(p569););
printStats();
PRINT_POINTER(smalloc(212););
printStats();
void* p593 = last_address;
PRINT_POINTER(scalloc(87,119););
printStats();
void* p594 = last_address;
PRINT_POINTER(srealloc(p536,125););
printStats();
void* p595 = last_address;
PRINT_POINTER(srealloc(p483,230););
printStats();
void* p596 = last_address;
PRINT_POINTER(scalloc(42,152););
printStats();
void* p597 = last_address;
PRINT_POINTER(srealloc(p352,173););
printStats();
void* p598 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p599 = last_address;
PRINT_POINTER(srealloc(p568,119););
printStats();
void* p600 = last_address;
PRINT_POINTER(srealloc(p598,220););
printStats();
void* p601 = last_address;
DEBUG_PRINT(sfree(p443););
printStats();
PRINT_POINTER(scalloc(176,243););
printStats();
void* p602 = last_address;
PRINT_POINTER(srealloc(p409,234););
printStats();
void* p603 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p604 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p605 = last_address;
DEBUG_PRINT(sfree(p452););
printStats();
PRINT_POINTER(srealloc(p597,104););
printStats();
void* p606 = last_address;
PRINT_POINTER(srealloc(p466,216););
printStats();
void* p607 = last_address;
DEBUG_PRINT(sfree(p392););
printStats();
DEBUG_PRINT(sfree(p576););
printStats();
PRINT_POINTER(scalloc(223,228););
printStats();
void* p608 = last_address;
DEBUG_PRINT(sfree(p421););
printStats();
PRINT_POINTER(smalloc(176););
printStats();
void* p609 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p610 = last_address;
PRINT_POINTER(scalloc(131,64););
printStats();
void* p611 = last_address;
PRINT_POINTER(scalloc(199,147););
printStats();
void* p612 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p613 = last_address;
PRINT_POINTER(srealloc(p212,246););
printStats();
void* p614 = last_address;
PRINT_POINTER(srealloc(p535,180););
printStats();
void* p615 = last_address;
PRINT_POINTER(srealloc(p615,148););
printStats();
void* p616 = last_address;
PRINT_POINTER(scalloc(216,39););
printStats();
void* p617 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p618 = last_address;
PRINT_POINTER(srealloc(p473,98););
printStats();
void* p619 = last_address;
PRINT_POINTER(scalloc(19,164););
printStats();
void* p620 = last_address;
PRINT_POINTER(srealloc(p503,16););
printStats();
void* p621 = last_address;
DEBUG_PRINT(sfree(p588););
printStats();
PRINT_POINTER(smalloc(126););
printStats();
void* p622 = last_address;
DEBUG_PRINT(sfree(p454););
printStats();
PRINT_POINTER(scalloc(154,5););
printStats();
void* p623 = last_address;
PRINT_POINTER(scalloc(73,116););
printStats();
void* p624 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p625 = last_address;
PRINT_POINTER(scalloc(156,43););
printStats();
void* p626 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p627 = last_address;
DEBUG_PRINT(sfree(p518););
printStats();
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(scalloc(139,217););
printStats();
void* p628 = last_address;
DEBUG_PRINT(sfree(p264););
printStats();
PRINT_POINTER(scalloc(128,85););
printStats();
void* p629 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p630 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p631 = last_address;
PRINT_POINTER(srealloc(p521,53););
printStats();
void* p632 = last_address;
DEBUG_PRINT(sfree(p512););
printStats();
PRINT_POINTER(smalloc(205););
printStats();
void* p633 = last_address;
DEBUG_PRINT(sfree(p548););
printStats();
DEBUG_PRINT(sfree(p468););
printStats();
PRINT_POINTER(scalloc(125,13););
printStats();
void* p634 = last_address;
DEBUG_PRINT(sfree(p611););
printStats();
PRINT_POINTER(scalloc(185,196););
printStats();
void* p635 = last_address;
PRINT_POINTER(scalloc(18,206););
printStats();
void* p636 = last_address;
DEBUG_PRINT(sfree(p626););
printStats();
PRINT_POINTER(smalloc(162););
printStats();
void* p637 = last_address;
PRINT_POINTER(scalloc(54,126););
printStats();
void* p638 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p639 = last_address;
PRINT_POINTER(srealloc(p375,226););
printStats();
void* p640 = last_address;
PRINT_POINTER(srealloc(p196,240););
printStats();
void* p641 = last_address;
PRINT_POINTER(scalloc(61,163););
printStats();
void* p642 = last_address;
DEBUG_PRINT(sfree(p641););
printStats();
PRINT_POINTER(scalloc(114,27););
printStats();
void* p643 = last_address;
PRINT_POINTER(scalloc(70,12););
printStats();
void* p644 = last_address;
PRINT_POINTER(srealloc(p540,227););
printStats();
void* p645 = last_address;
PRINT_POINTER(scalloc(39,133););
printStats();
void* p646 = last_address;
DEBUG_PRINT(sfree(p605););
printStats();
DEBUG_PRINT(sfree(p396););
printStats();
PRINT_POINTER(srealloc(p624,191););
printStats();
void* p647 = last_address;
PRINT_POINTER(srealloc(p425,129););
printStats();
void* p648 = last_address;
PRINT_POINTER(srealloc(p630,51););
printStats();
void* p649 = last_address;
PRINT_POINTER(srealloc(p449,181););
printStats();
void* p650 = last_address;
DEBUG_PRINT(sfree(p646););
printStats();
PRINT_POINTER(scalloc(33,176););
printStats();
void* p651 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p652 = last_address;
PRINT_POINTER(scalloc(210,153););
printStats();
void* p653 = last_address;
PRINT_POINTER(scalloc(77,146););
printStats();
void* p654 = last_address;
DEBUG_PRINT(sfree(p388););
printStats();
DEBUG_PRINT(sfree(p446););
printStats();
PRINT_POINTER(srealloc(p632,210););
printStats();
void* p655 = last_address;
PRINT_POINTER(scalloc(175,186););
printStats();
void* p656 = last_address;
PRINT_POINTER(scalloc(221,40););
printStats();
void* p657 = last_address;
PRINT_POINTER(srealloc(p618,226););
printStats();
void* p658 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p659 = last_address;
PRINT_POINTER(srealloc(p566,226););
printStats();
void* p660 = last_address;
PRINT_POINTER(srealloc(p643,194););
printStats();
void* p661 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p662 = last_address;
DEBUG_PRINT(sfree(p460););
printStats();
PRINT_POINTER(scalloc(105,23););
printStats();
void* p663 = last_address;
PRINT_POINTER(srealloc(p495,4););
printStats();
void* p664 = last_address;
PRINT_POINTER(scalloc(69,138););
printStats();
void* p665 = last_address;
PRINT_POINTER(srealloc(p525,171););
printStats();
void* p666 = last_address;
PRINT_POINTER(srealloc(p490,59););
printStats();
void* p667 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p668 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p669 = last_address;
}
