#include "aux_macro.h"
#include "../malloc_4.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(235,168););
printStats();
void* p0 = last_address;
PRINT_POINTER(scalloc(162,194););
printStats();
void* p1 = last_address;
PRINT_POINTER(scalloc(5,13););
printStats();
void* p2 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(scalloc(71,76););
printStats();
void* p3 = last_address;
DEBUG_PRINT(sfree(p3););
printStats();
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(scalloc(125,57););
printStats();
void* p4 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(srealloc(p4,199););
printStats();
void* p5 = last_address;
PRINT_POINTER(srealloc(p5,25););
printStats();
void* p6 = last_address;
PRINT_POINTER(srealloc(p6,194););
printStats();
void* p7 = last_address;
PRINT_POINTER(srealloc(p7,225););
printStats();
void* p8 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(smalloc(222););
printStats();
void* p9 = last_address;
PRINT_POINTER(scalloc(113,81););
printStats();
void* p10 = last_address;
PRINT_POINTER(scalloc(69,181););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(73,120););
printStats();
void* p12 = last_address;
PRINT_POINTER(srealloc(p12,216););
printStats();
void* p13 = last_address;
PRINT_POINTER(srealloc(p10,64););
printStats();
void* p14 = last_address;
PRINT_POINTER(scalloc(194,215););
printStats();
void* p15 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p16 = last_address;
DEBUG_PRINT(sfree(p9););
printStats();
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(srealloc(p11,16););
printStats();
void* p17 = last_address;
PRINT_POINTER(srealloc(p14,101););
printStats();
void* p18 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p19 = last_address;
PRINT_POINTER(scalloc(30,222););
printStats();
void* p20 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p21 = last_address;
PRINT_POINTER(srealloc(p20,203););
printStats();
void* p22 = last_address;
PRINT_POINTER(srealloc(p18,48););
printStats();
void* p23 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(srealloc(p23,74););
printStats();
void* p24 = last_address;
PRINT_POINTER(scalloc(117,31););
printStats();
void* p25 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p26 = last_address;
DEBUG_PRINT(sfree(p13););
printStats();
PRINT_POINTER(scalloc(141,102););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(srealloc(p25,204););
printStats();
void* p28 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p29 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p30 = last_address;
PRINT_POINTER(srealloc(p27,52););
printStats();
void* p31 = last_address;
PRINT_POINTER(scalloc(55,15););
printStats();
void* p32 = last_address;
PRINT_POINTER(scalloc(167,87););
printStats();
void* p33 = last_address;
DEBUG_PRINT(sfree(p19););
printStats();
DEBUG_PRINT(sfree(p32););
printStats();
PRINT_POINTER(scalloc(192,75););
printStats();
void* p34 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p35 = last_address;
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(scalloc(21,135););
printStats();
void* p36 = last_address;
PRINT_POINTER(scalloc(123,197););
printStats();
void* p37 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
PRINT_POINTER(smalloc(172););
printStats();
void* p38 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p39 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p40 = last_address;
PRINT_POINTER(scalloc(176,36););
printStats();
void* p41 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p42 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(scalloc(171,111););
printStats();
void* p43 = last_address;
PRINT_POINTER(srealloc(p38,233););
printStats();
void* p44 = last_address;
PRINT_POINTER(srealloc(p43,88););
printStats();
void* p45 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(srealloc(p22,223););
printStats();
void* p46 = last_address;
PRINT_POINTER(scalloc(13,180););
printStats();
void* p47 = last_address;
DEBUG_PRINT(sfree(p35););
printStats();
PRINT_POINTER(scalloc(41,149););
printStats();
void* p48 = last_address;
PRINT_POINTER(srealloc(p45,187););
printStats();
void* p49 = last_address;
PRINT_POINTER(srealloc(p39,16););
printStats();
void* p50 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p51 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
DEBUG_PRINT(sfree(p46););
printStats();
PRINT_POINTER(smalloc(99););
printStats();
void* p52 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p53 = last_address;
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(smalloc(66););
printStats();
void* p54 = last_address;
PRINT_POINTER(srealloc(p52,80););
printStats();
void* p55 = last_address;
PRINT_POINTER(srealloc(p26,98););
printStats();
void* p56 = last_address;
DEBUG_PRINT(sfree(p49););
printStats();
PRINT_POINTER(scalloc(22,118););
printStats();
void* p57 = last_address;
PRINT_POINTER(srealloc(p34,179););
printStats();
void* p58 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p59 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(scalloc(149,206););
printStats();
void* p60 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p61 = last_address;
PRINT_POINTER(scalloc(157,99););
printStats();
void* p62 = last_address;
PRINT_POINTER(srealloc(p29,239););
printStats();
void* p63 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
PRINT_POINTER(srealloc(p40,224););
printStats();
void* p64 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(scalloc(29,172););
printStats();
void* p65 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p66 = last_address;
PRINT_POINTER(scalloc(183,219););
printStats();
void* p67 = last_address;
DEBUG_PRINT(sfree(p48););
printStats();
PRINT_POINTER(scalloc(114,92););
printStats();
void* p68 = last_address;
PRINT_POINTER(scalloc(32,222););
printStats();
void* p69 = last_address;
PRINT_POINTER(scalloc(126,110););
printStats();
void* p70 = last_address;
PRINT_POINTER(srealloc(p28,225););
printStats();
void* p71 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p72 = last_address;
PRINT_POINTER(srealloc(p68,173););
printStats();
void* p73 = last_address;
PRINT_POINTER(srealloc(p73,225););
printStats();
void* p74 = last_address;
PRINT_POINTER(srealloc(p55,208););
printStats();
void* p75 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p76 = last_address;
PRINT_POINTER(srealloc(p53,60););
printStats();
void* p77 = last_address;
PRINT_POINTER(scalloc(102,115););
printStats();
void* p78 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(scalloc(6,64););
printStats();
void* p79 = last_address;
PRINT_POINTER(srealloc(p65,164););
printStats();
void* p80 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p81 = last_address;
PRINT_POINTER(srealloc(p63,91););
printStats();
void* p82 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p83 = last_address;
PRINT_POINTER(scalloc(103,179););
printStats();
void* p84 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p85 = last_address;
DEBUG_PRINT(sfree(p80););
printStats();
PRINT_POINTER(smalloc(156););
printStats();
void* p86 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p87 = last_address;
PRINT_POINTER(scalloc(157,57););
printStats();
void* p88 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p89 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p90 = last_address;
PRINT_POINTER(scalloc(168,147););
printStats();
void* p91 = last_address;
PRINT_POINTER(scalloc(26,44););
printStats();
void* p92 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
DEBUG_PRINT(sfree(p86););
printStats();
DEBUG_PRINT(sfree(p71););
printStats();
PRINT_POINTER(scalloc(157,143););
printStats();
void* p93 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p94 = last_address;
DEBUG_PRINT(sfree(p82););
printStats();
PRINT_POINTER(scalloc(18,129););
printStats();
void* p95 = last_address;
PRINT_POINTER(srealloc(p30,158););
printStats();
void* p96 = last_address;
PRINT_POINTER(srealloc(p61,52););
printStats();
void* p97 = last_address;
PRINT_POINTER(srealloc(p93,143););
printStats();
void* p98 = last_address;
PRINT_POINTER(scalloc(77,171););
printStats();
void* p99 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p100 = last_address;
PRINT_POINTER(scalloc(13,76););
printStats();
void* p101 = last_address;
PRINT_POINTER(srealloc(p54,29););
printStats();
void* p102 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p103 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p104 = last_address;
PRINT_POINTER(srealloc(p88,218););
printStats();
void* p105 = last_address;
PRINT_POINTER(scalloc(115,35););
printStats();
void* p106 = last_address;
PRINT_POINTER(scalloc(174,248););
printStats();
void* p107 = last_address;
DEBUG_PRINT(sfree(p56););
printStats();
PRINT_POINTER(srealloc(p99,135););
printStats();
void* p108 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(smalloc(232););
printStats();
void* p109 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p110 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p111 = last_address;
PRINT_POINTER(scalloc(34,177););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p96,38););
printStats();
void* p113 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p114 = last_address;
PRINT_POINTER(scalloc(139,231););
printStats();
void* p115 = last_address;
PRINT_POINTER(scalloc(230,165););
printStats();
void* p116 = last_address;
PRINT_POINTER(scalloc(36,102););
printStats();
void* p117 = last_address;
PRINT_POINTER(scalloc(22,152););
printStats();
void* p118 = last_address;
PRINT_POINTER(srealloc(p76,75););
printStats();
void* p119 = last_address;
DEBUG_PRINT(sfree(p75););
printStats();
DEBUG_PRINT(sfree(p103););
printStats();
PRINT_POINTER(scalloc(233,66););
printStats();
void* p120 = last_address;
PRINT_POINTER(srealloc(p101,248););
printStats();
void* p121 = last_address;
DEBUG_PRINT(sfree(p62););
printStats();
PRINT_POINTER(srealloc(p109,187););
printStats();
void* p122 = last_address;
PRINT_POINTER(scalloc(45,119););
printStats();
void* p123 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p124 = last_address;
PRINT_POINTER(srealloc(p106,76););
printStats();
void* p125 = last_address;
PRINT_POINTER(srealloc(p74,105););
printStats();
void* p126 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p127 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(srealloc(p57,34););
printStats();
void* p128 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
PRINT_POINTER(scalloc(225,128););
printStats();
void* p129 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(smalloc(203););
printStats();
void* p130 = last_address;
PRINT_POINTER(scalloc(121,20););
printStats();
void* p131 = last_address;
PRINT_POINTER(scalloc(150,103););
printStats();
void* p132 = last_address;
PRINT_POINTER(srealloc(p130,226););
printStats();
void* p133 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p134 = last_address;
DEBUG_PRINT(sfree(p120););
printStats();
PRINT_POINTER(scalloc(241,35););
printStats();
void* p135 = last_address;
PRINT_POINTER(scalloc(239,223););
printStats();
void* p136 = last_address;
PRINT_POINTER(srealloc(p133,53););
printStats();
void* p137 = last_address;
PRINT_POINTER(scalloc(182,6););
printStats();
void* p138 = last_address;
DEBUG_PRINT(sfree(p135););
printStats();
PRINT_POINTER(scalloc(142,166););
printStats();
void* p139 = last_address;
PRINT_POINTER(srealloc(p44,123););
printStats();
void* p140 = last_address;
DEBUG_PRINT(sfree(p92););
printStats();
DEBUG_PRINT(sfree(p112););
printStats();
PRINT_POINTER(srealloc(p128,156););
printStats();
void* p141 = last_address;
DEBUG_PRINT(sfree(p132););
printStats();
PRINT_POINTER(scalloc(104,113););
printStats();
void* p142 = last_address;
PRINT_POINTER(scalloc(27,130););
printStats();
void* p143 = last_address;
PRINT_POINTER(scalloc(190,29););
printStats();
void* p144 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(scalloc(218,26););
printStats();
void* p145 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p146 = last_address;
PRINT_POINTER(scalloc(176,119););
printStats();
void* p147 = last_address;
PRINT_POINTER(scalloc(95,59););
printStats();
void* p148 = last_address;
PRINT_POINTER(srealloc(p123,66););
printStats();
void* p149 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p150 = last_address;
PRINT_POINTER(srealloc(p77,67););
printStats();
void* p151 = last_address;
DEBUG_PRINT(sfree(p66););
printStats();
PRINT_POINTER(srealloc(p47,68););
printStats();
void* p152 = last_address;
PRINT_POINTER(srealloc(p140,103););
printStats();
void* p153 = last_address;
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(srealloc(p137,222););
printStats();
void* p154 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p155 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p156 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p157 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p158 = last_address;
PRINT_POINTER(srealloc(p116,62););
printStats();
void* p159 = last_address;
DEBUG_PRINT(sfree(p149););
printStats();
PRINT_POINTER(smalloc(36););
printStats();
void* p160 = last_address;
PRINT_POINTER(srealloc(p105,39););
printStats();
void* p161 = last_address;
PRINT_POINTER(scalloc(187,214););
printStats();
void* p162 = last_address;
PRINT_POINTER(scalloc(196,95););
printStats();
void* p163 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p164 = last_address;
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(smalloc(129););
printStats();
void* p165 = last_address;
PRINT_POINTER(srealloc(p144,189););
printStats();
void* p166 = last_address;
PRINT_POINTER(srealloc(p78,18););
printStats();
void* p167 = last_address;
PRINT_POINTER(srealloc(p113,104););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(6,30););
printStats();
void* p169 = last_address;
PRINT_POINTER(scalloc(155,118););
printStats();
void* p170 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p171 = last_address;
PRINT_POINTER(srealloc(p146,211););
printStats();
void* p172 = last_address;
PRINT_POINTER(srealloc(p148,21););
printStats();
void* p173 = last_address;
DEBUG_PRINT(sfree(p58););
printStats();
DEBUG_PRINT(sfree(p83););
printStats();
DEBUG_PRINT(sfree(p158););
printStats();
PRINT_POINTER(smalloc(113););
printStats();
void* p174 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p169););
printStats();
PRINT_POINTER(srealloc(p91,19););
printStats();
void* p176 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p177 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(srealloc(p79,180););
printStats();
void* p178 = last_address;
PRINT_POINTER(srealloc(p72,41););
printStats();
void* p179 = last_address;
DEBUG_PRINT(sfree(p172););
printStats();
PRINT_POINTER(srealloc(p111,68););
printStats();
void* p180 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p181 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
DEBUG_PRINT(sfree(p161););
printStats();
PRINT_POINTER(scalloc(243,225););
printStats();
void* p182 = last_address;
PRINT_POINTER(srealloc(p117,231););
printStats();
void* p183 = last_address;
DEBUG_PRINT(sfree(p67););
printStats();
PRINT_POINTER(scalloc(181,228););
printStats();
void* p184 = last_address;
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(srealloc(p153,2););
printStats();
void* p185 = last_address;
PRINT_POINTER(srealloc(p180,1););
printStats();
void* p186 = last_address;
PRINT_POINTER(scalloc(74,174););
printStats();
void* p187 = last_address;
DEBUG_PRINT(sfree(p183););
printStats();
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(smalloc(230););
printStats();
void* p188 = last_address;
DEBUG_PRINT(sfree(p187););
printStats();
DEBUG_PRINT(sfree(p185););
printStats();
PRINT_POINTER(scalloc(91,175););
printStats();
void* p189 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p190 = last_address;
PRINT_POINTER(scalloc(107,38););
printStats();
void* p191 = last_address;
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(srealloc(p136,249););
printStats();
void* p192 = last_address;
DEBUG_PRINT(sfree(p110););
printStats();
DEBUG_PRINT(sfree(p168););
printStats();
PRINT_POINTER(smalloc(116););
printStats();
void* p193 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p194 = last_address;
PRINT_POINTER(scalloc(103,156););
printStats();
void* p195 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p196 = last_address;
PRINT_POINTER(srealloc(p182,186););
printStats();
void* p197 = last_address;
DEBUG_PRINT(sfree(p104););
printStats();
PRINT_POINTER(scalloc(188,239););
printStats();
void* p198 = last_address;
PRINT_POINTER(srealloc(p42,203););
printStats();
void* p199 = last_address;
PRINT_POINTER(scalloc(19,47););
printStats();
void* p200 = last_address;
PRINT_POINTER(scalloc(213,96););
printStats();
void* p201 = last_address;
PRINT_POINTER(srealloc(p81,124););
printStats();
void* p202 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
PRINT_POINTER(smalloc(104););
printStats();
void* p203 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p204 = last_address;
PRINT_POINTER(srealloc(p202,90););
printStats();
void* p205 = last_address;
DEBUG_PRINT(sfree(p201););
printStats();
PRINT_POINTER(smalloc(15););
printStats();
void* p206 = last_address;
DEBUG_PRINT(sfree(p171););
printStats();
PRINT_POINTER(srealloc(p150,244););
printStats();
void* p207 = last_address;
PRINT_POINTER(srealloc(p125,171););
printStats();
void* p208 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p209 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p210 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(131,185););
printStats();
void* p212 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p213 = last_address;
PRINT_POINTER(srealloc(p173,13););
printStats();
void* p214 = last_address;
DEBUG_PRINT(sfree(p177););
printStats();
PRINT_POINTER(scalloc(174,133););
printStats();
void* p215 = last_address;
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(srealloc(p189,14););
printStats();
void* p216 = last_address;
PRINT_POINTER(srealloc(p155,31););
printStats();
void* p217 = last_address;
PRINT_POINTER(srealloc(p209,110););
printStats();
void* p218 = last_address;
PRINT_POINTER(scalloc(24,186););
printStats();
void* p219 = last_address;
DEBUG_PRINT(sfree(p212););
printStats();
PRINT_POINTER(srealloc(p50,118););
printStats();
void* p220 = last_address;
DEBUG_PRINT(sfree(p174););
printStats();
PRINT_POINTER(smalloc(110););
printStats();
void* p221 = last_address;
PRINT_POINTER(srealloc(p206,35););
printStats();
void* p222 = last_address;
PRINT_POINTER(scalloc(130,225););
printStats();
void* p223 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(smalloc(70););
printStats();
void* p224 = last_address;
DEBUG_PRINT(sfree(p157););
printStats();
DEBUG_PRINT(sfree(p165););
printStats();
PRINT_POINTER(srealloc(p118,52););
printStats();
void* p225 = last_address;
DEBUG_PRINT(sfree(p84););
printStats();
PRINT_POINTER(srealloc(p195,74););
printStats();
void* p226 = last_address;
PRINT_POINTER(srealloc(p205,213););
printStats();
void* p227 = last_address;
PRINT_POINTER(srealloc(p121,69););
printStats();
void* p228 = last_address;
PRINT_POINTER(srealloc(p219,180););
printStats();
void* p229 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p230 = last_address;
PRINT_POINTER(scalloc(243,216););
printStats();
void* p231 = last_address;
DEBUG_PRINT(sfree(p139););
printStats();
DEBUG_PRINT(sfree(p134););
printStats();
DEBUG_PRINT(sfree(p221););
printStats();
PRINT_POINTER(scalloc(31,30););
printStats();
void* p232 = last_address;
PRINT_POINTER(scalloc(228,110););
printStats();
void* p233 = last_address;
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(scalloc(35,127););
printStats();
void* p234 = last_address;
PRINT_POINTER(srealloc(p218,80););
printStats();
void* p235 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p236 = last_address;
PRINT_POINTER(srealloc(p220,184););
printStats();
void* p237 = last_address;
PRINT_POINTER(srealloc(p184,57););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p235,186););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p188,212););
printStats();
void* p240 = last_address;
PRINT_POINTER(scalloc(236,236););
printStats();
void* p241 = last_address;
DEBUG_PRINT(sfree(p234););
printStats();
DEBUG_PRINT(sfree(p237););
printStats();
PRINT_POINTER(srealloc(p200,124););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p216););
printStats();
PRINT_POINTER(scalloc(179,147););
printStats();
void* p243 = last_address;
PRINT_POINTER(srealloc(p191,25););
printStats();
void* p244 = last_address;
PRINT_POINTER(srealloc(p211,190););
printStats();
void* p245 = last_address;
PRINT_POINTER(scalloc(161,23););
printStats();
void* p246 = last_address;
PRINT_POINTER(scalloc(68,93););
printStats();
void* p247 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p248 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p249 = last_address;
PRINT_POINTER(scalloc(242,245););
printStats();
void* p250 = last_address;
PRINT_POINTER(srealloc(p162,48););
printStats();
void* p251 = last_address;
PRINT_POINTER(srealloc(p217,245););
printStats();
void* p252 = last_address;
PRINT_POINTER(scalloc(133,209););
printStats();
void* p253 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p254 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p255 = last_address;
DEBUG_PRINT(sfree(p225););
printStats();
DEBUG_PRINT(sfree(p193););
printStats();
PRINT_POINTER(srealloc(p255,204););
printStats();
void* p256 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p257 = last_address;
PRINT_POINTER(scalloc(212,73););
printStats();
void* p258 = last_address;
PRINT_POINTER(srealloc(p192,202););
printStats();
void* p259 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p260 = last_address;
DEBUG_PRINT(sfree(p198););
printStats();
DEBUG_PRINT(sfree(p204););
printStats();
PRINT_POINTER(smalloc(67););
printStats();
void* p261 = last_address;
PRINT_POINTER(scalloc(193,117););
printStats();
void* p262 = last_address;
PRINT_POINTER(srealloc(p156,57););
printStats();
void* p263 = last_address;
PRINT_POINTER(srealloc(p215,30););
printStats();
void* p264 = last_address;
PRINT_POINTER(scalloc(53,155););
printStats();
void* p265 = last_address;
PRINT_POINTER(scalloc(146,179););
printStats();
void* p266 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(smalloc(223););
printStats();
void* p267 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
PRINT_POINTER(scalloc(109,249););
printStats();
void* p268 = last_address;
PRINT_POINTER(srealloc(p231,131););
printStats();
void* p269 = last_address;
PRINT_POINTER(scalloc(57,131););
printStats();
void* p270 = last_address;
PRINT_POINTER(scalloc(148,156););
printStats();
void* p271 = last_address;
PRINT_POINTER(scalloc(149,168););
printStats();
void* p272 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p273 = last_address;
PRINT_POINTER(srealloc(p262,28););
printStats();
void* p274 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
DEBUG_PRINT(sfree(p210););
printStats();
DEBUG_PRINT(sfree(p178););
printStats();
PRINT_POINTER(scalloc(175,229););
printStats();
void* p275 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p276 = last_address;
PRINT_POINTER(srealloc(p176,62););
printStats();
void* p277 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p278 = last_address;
PRINT_POINTER(scalloc(6,176););
printStats();
void* p279 = last_address;
PRINT_POINTER(srealloc(p160,73););
printStats();
void* p280 = last_address;
PRINT_POINTER(srealloc(p151,154););
printStats();
void* p281 = last_address;
DEBUG_PRINT(sfree(p124););
printStats();
DEBUG_PRINT(sfree(p100););
printStats();
DEBUG_PRINT(sfree(p278););
printStats();
PRINT_POINTER(srealloc(p97,178););
printStats();
void* p282 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p283 = last_address;
PRINT_POINTER(srealloc(p245,183););
printStats();
void* p284 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p285 = last_address;
PRINT_POINTER(srealloc(p207,113););
printStats();
void* p286 = last_address;
PRINT_POINTER(srealloc(p95,81););
printStats();
void* p287 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p288 = last_address;
PRINT_POINTER(scalloc(174,99););
printStats();
void* p289 = last_address;
DEBUG_PRINT(sfree(p154););
printStats();
DEBUG_PRINT(sfree(p241););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p290 = last_address;
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(smalloc(107););
printStats();
void* p291 = last_address;
PRINT_POINTER(srealloc(p138,30););
printStats();
void* p292 = last_address;
DEBUG_PRINT(sfree(p249););
printStats();
PRINT_POINTER(srealloc(p87,106););
printStats();
void* p293 = last_address;
PRINT_POINTER(srealloc(p285,72););
printStats();
void* p294 = last_address;
PRINT_POINTER(scalloc(148,129););
printStats();
void* p295 = last_address;
DEBUG_PRINT(sfree(p163););
printStats();
PRINT_POINTER(srealloc(p259,167););
printStats();
void* p296 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p297 = last_address;
PRINT_POINTER(srealloc(p131,139););
printStats();
void* p298 = last_address;
DEBUG_PRINT(sfree(p288););
printStats();
DEBUG_PRINT(sfree(p277););
printStats();
PRINT_POINTER(scalloc(4,194););
printStats();
void* p299 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(srealloc(p122,47););
printStats();
void* p300 = last_address;
PRINT_POINTER(scalloc(167,120););
printStats();
void* p301 = last_address;
PRINT_POINTER(srealloc(p167,32););
printStats();
void* p302 = last_address;
PRINT_POINTER(srealloc(p284,26););
printStats();
void* p303 = last_address;
PRINT_POINTER(scalloc(141,90););
printStats();
void* p304 = last_address;
PRINT_POINTER(scalloc(248,12););
printStats();
void* p305 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p306 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p307 = last_address;
DEBUG_PRINT(sfree(p107););
printStats();
PRINT_POINTER(srealloc(p222,165););
printStats();
void* p308 = last_address;
DEBUG_PRINT(sfree(p227););
printStats();
DEBUG_PRINT(sfree(p280););
printStats();
PRINT_POINTER(smalloc(93););
printStats();
void* p309 = last_address;
PRINT_POINTER(scalloc(228,116););
printStats();
void* p310 = last_address;
DEBUG_PRINT(sfree(p294););
printStats();
DEBUG_PRINT(sfree(p179););
printStats();
DEBUG_PRINT(sfree(p302););
printStats();
PRINT_POINTER(scalloc(21,73););
printStats();
void* p311 = last_address;
PRINT_POINTER(scalloc(98,78););
printStats();
void* p312 = last_address;
PRINT_POINTER(scalloc(68,120););
printStats();
void* p313 = last_address;
DEBUG_PRINT(sfree(p268););
printStats();
DEBUG_PRINT(sfree(p300););
printStats();
PRINT_POINTER(srealloc(p170,41););
printStats();
void* p314 = last_address;
DEBUG_PRINT(sfree(p256););
printStats();
DEBUG_PRINT(sfree(p313););
printStats();
DEBUG_PRINT(sfree(p213););
printStats();
DEBUG_PRINT(sfree(p282););
printStats();
PRINT_POINTER(srealloc(p310,162););
printStats();
void* p315 = last_address;
DEBUG_PRINT(sfree(p286););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p316 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p317 = last_address;
PRINT_POINTER(scalloc(172,216););
printStats();
void* p318 = last_address;
PRINT_POINTER(srealloc(p190,207););
printStats();
void* p319 = last_address;
PRINT_POINTER(scalloc(72,240););
printStats();
void* p320 = last_address;
PRINT_POINTER(scalloc(182,135););
printStats();
void* p321 = last_address;
PRINT_POINTER(srealloc(p271,57););
printStats();
void* p322 = last_address;
PRINT_POINTER(scalloc(156,10););
printStats();
void* p323 = last_address;
PRINT_POINTER(scalloc(74,237););
printStats();
void* p324 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p325 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p326 = last_address;
PRINT_POINTER(srealloc(p260,165););
printStats();
void* p327 = last_address;
PRINT_POINTER(srealloc(p281,73););
printStats();
void* p328 = last_address;
DEBUG_PRINT(sfree(p267););
printStats();
PRINT_POINTER(srealloc(p276,247););
printStats();
void* p329 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p330 = last_address;
PRINT_POINTER(srealloc(p292,117););
printStats();
void* p331 = last_address;
PRINT_POINTER(srealloc(p324,177););
printStats();
void* p332 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p333 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p334 = last_address;
PRINT_POINTER(scalloc(133,18););
printStats();
void* p335 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p336 = last_address;
DEBUG_PRINT(sfree(p240););
printStats();
PRINT_POINTER(scalloc(141,175););
printStats();
void* p337 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p338 = last_address;
PRINT_POINTER(scalloc(171,179););
printStats();
void* p339 = last_address;
PRINT_POINTER(scalloc(43,232););
printStats();
void* p340 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p341 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p342 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p343 = last_address;
PRINT_POINTER(scalloc(205,206););
printStats();
void* p344 = last_address;
PRINT_POINTER(scalloc(26,104););
printStats();
void* p345 = last_address;
DEBUG_PRINT(sfree(p279););
printStats();
PRINT_POINTER(srealloc(p126,59););
printStats();
void* p346 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p347 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p348 = last_address;
PRINT_POINTER(srealloc(p248,66););
printStats();
void* p349 = last_address;
PRINT_POINTER(scalloc(132,81););
printStats();
void* p350 = last_address;
PRINT_POINTER(scalloc(54,196););
printStats();
void* p351 = last_address;
DEBUG_PRINT(sfree(p298););
printStats();
PRINT_POINTER(srealloc(p246,22););
printStats();
void* p352 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p353 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p354 = last_address;
DEBUG_PRINT(sfree(p330););
printStats();
DEBUG_PRINT(sfree(p350););
printStats();
PRINT_POINTER(smalloc(44););
printStats();
void* p355 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p356 = last_address;
PRINT_POINTER(srealloc(p334,90););
printStats();
void* p357 = last_address;
PRINT_POINTER(scalloc(170,220););
printStats();
void* p358 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p359 = last_address;
PRINT_POINTER(scalloc(194,187););
printStats();
void* p360 = last_address;
DEBUG_PRINT(sfree(p315););
printStats();
DEBUG_PRINT(sfree(p214););
printStats();
PRINT_POINTER(srealloc(p143,69););
printStats();
void* p361 = last_address;
PRINT_POINTER(srealloc(p348,178););
printStats();
void* p362 = last_address;
PRINT_POINTER(scalloc(135,164););
printStats();
void* p363 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p364 = last_address;
PRINT_POINTER(srealloc(p283,42););
printStats();
void* p365 = last_address;
DEBUG_PRINT(sfree(p254););
printStats();
PRINT_POINTER(smalloc(69););
printStats();
void* p366 = last_address;
DEBUG_PRINT(sfree(p328););
printStats();
PRINT_POINTER(scalloc(214,84););
printStats();
void* p367 = last_address;
PRINT_POINTER(scalloc(161,127););
printStats();
void* p368 = last_address;
PRINT_POINTER(scalloc(187,70););
printStats();
void* p369 = last_address;
PRINT_POINTER(srealloc(p287,198););
printStats();
void* p370 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p371 = last_address;
PRINT_POINTER(scalloc(228,183););
printStats();
void* p372 = last_address;
PRINT_POINTER(srealloc(p258,3););
printStats();
void* p373 = last_address;
PRINT_POINTER(scalloc(62,175););
printStats();
void* p374 = last_address;
PRINT_POINTER(scalloc(10,67););
printStats();
void* p375 = last_address;
PRINT_POINTER(srealloc(p338,147););
printStats();
void* p376 = last_address;
PRINT_POINTER(srealloc(p335,133););
printStats();
void* p377 = last_address;
DEBUG_PRINT(sfree(p239););
printStats();
PRINT_POINTER(srealloc(p347,176););
printStats();
void* p378 = last_address;
DEBUG_PRINT(sfree(p371););
printStats();
PRINT_POINTER(scalloc(76,157););
printStats();
void* p379 = last_address;
PRINT_POINTER(scalloc(8,170););
printStats();
void* p380 = last_address;
DEBUG_PRINT(sfree(p325););
printStats();
PRINT_POINTER(srealloc(p365,210););
printStats();
void* p381 = last_address;
PRINT_POINTER(srealloc(p311,3););
printStats();
void* p382 = last_address;
DEBUG_PRINT(sfree(p299););
printStats();
PRINT_POINTER(smalloc(39););
printStats();
void* p383 = last_address;
DEBUG_PRINT(sfree(p261););
printStats();
PRINT_POINTER(scalloc(219,180););
printStats();
void* p384 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p385 = last_address;
DEBUG_PRINT(sfree(p367););
printStats();
DEBUG_PRINT(sfree(p368););
printStats();
DEBUG_PRINT(sfree(p323););
printStats();
PRINT_POINTER(smalloc(187););
printStats();
void* p386 = last_address;
PRINT_POINTER(srealloc(p375,177););
printStats();
void* p387 = last_address;
PRINT_POINTER(srealloc(p386,167););
printStats();
void* p388 = last_address;
PRINT_POINTER(srealloc(p243,171););
printStats();
void* p389 = last_address;
DEBUG_PRINT(sfree(p363););
printStats();
PRINT_POINTER(srealloc(p387,42););
printStats();
void* p390 = last_address;
PRINT_POINTER(srealloc(p115,193););
printStats();
void* p391 = last_address;
PRINT_POINTER(scalloc(145,190););
printStats();
void* p392 = last_address;
PRINT_POINTER(srealloc(p329,123););
printStats();
void* p393 = last_address;
PRINT_POINTER(srealloc(p314,122););
printStats();
void* p394 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p395 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
DEBUG_PRINT(sfree(p273););
printStats();
PRINT_POINTER(srealloc(p366,204););
printStats();
void* p396 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p397 = last_address;
DEBUG_PRINT(sfree(p263););
printStats();
PRINT_POINTER(scalloc(58,14););
printStats();
void* p398 = last_address;
PRINT_POINTER(srealloc(p398,226););
printStats();
void* p399 = last_address;
PRINT_POINTER(scalloc(199,199););
printStats();
void* p400 = last_address;
PRINT_POINTER(scalloc(241,18););
printStats();
void* p401 = last_address;
PRINT_POINTER(srealloc(p399,111););
printStats();
void* p402 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p403 = last_address;
PRINT_POINTER(scalloc(31,43););
printStats();
void* p404 = last_address;
PRINT_POINTER(srealloc(p344,216););
printStats();
void* p405 = last_address;
PRINT_POINTER(scalloc(238,33););
printStats();
void* p406 = last_address;
PRINT_POINTER(srealloc(p229,47););
printStats();
void* p407 = last_address;
PRINT_POINTER(scalloc(99,236););
printStats();
void* p408 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p409 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p410 = last_address;
PRINT_POINTER(srealloc(p393,125););
printStats();
void* p411 = last_address;
PRINT_POINTER(srealloc(p194,172););
printStats();
void* p412 = last_address;
PRINT_POINTER(scalloc(130,223););
printStats();
void* p413 = last_address;
PRINT_POINTER(srealloc(p251,82););
printStats();
void* p414 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p415 = last_address;
PRINT_POINTER(srealloc(p377,236););
printStats();
void* p416 = last_address;
PRINT_POINTER(srealloc(p380,221););
printStats();
void* p417 = last_address;
PRINT_POINTER(scalloc(179,183););
printStats();
void* p418 = last_address;
DEBUG_PRINT(sfree(p318););
printStats();
PRINT_POINTER(scalloc(151,111););
printStats();
void* p419 = last_address;
DEBUG_PRINT(sfree(p129););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p420 = last_address;
DEBUG_PRINT(sfree(p411););
printStats();
PRINT_POINTER(scalloc(61,225););
printStats();
void* p421 = last_address;
PRINT_POINTER(scalloc(28,202););
printStats();
void* p422 = last_address;
PRINT_POINTER(scalloc(85,110););
printStats();
void* p423 = last_address;
PRINT_POINTER(scalloc(240,44););
printStats();
void* p424 = last_address;
DEBUG_PRINT(sfree(p327););
printStats();
PRINT_POINTER(srealloc(p378,0););
printStats();
void* p425 = last_address;
PRINT_POINTER(scalloc(111,51););
printStats();
void* p426 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p427 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p428 = last_address;
PRINT_POINTER(scalloc(190,21););
printStats();
void* p429 = last_address;
DEBUG_PRINT(sfree(p364););
printStats();
DEBUG_PRINT(sfree(p361););
printStats();
DEBUG_PRINT(sfree(p336););
printStats();
PRINT_POINTER(scalloc(104,113););
printStats();
void* p430 = last_address;
DEBUG_PRINT(sfree(p345););
printStats();
PRINT_POINTER(scalloc(231,137););
printStats();
void* p431 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p432 = last_address;
PRINT_POINTER(scalloc(224,54););
printStats();
void* p433 = last_address;
PRINT_POINTER(scalloc(44,198););
printStats();
void* p434 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p435 = last_address;
PRINT_POINTER(srealloc(p429,169););
printStats();
void* p436 = last_address;
DEBUG_PRINT(sfree(p322););
printStats();
PRINT_POINTER(smalloc(64););
printStats();
void* p437 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p438 = last_address;
PRINT_POINTER(srealloc(p355,185););
printStats();
void* p439 = last_address;
PRINT_POINTER(srealloc(p396,45););
printStats();
void* p440 = last_address;
PRINT_POINTER(srealloc(p391,2););
printStats();
void* p441 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p442 = last_address;
PRINT_POINTER(srealloc(p435,129););
printStats();
void* p443 = last_address;
PRINT_POINTER(srealloc(p244,169););
printStats();
void* p444 = last_address;
PRINT_POINTER(srealloc(p408,15););
printStats();
void* p445 = last_address;
PRINT_POINTER(scalloc(226,7););
printStats();
void* p446 = last_address;
PRINT_POINTER(scalloc(214,236););
printStats();
void* p447 = last_address;
DEBUG_PRINT(sfree(p414););
printStats();
PRINT_POINTER(srealloc(p164,86););
printStats();
void* p448 = last_address;
PRINT_POINTER(srealloc(p312,31););
printStats();
void* p449 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p450 = last_address;
PRINT_POINTER(scalloc(176,186););
printStats();
void* p451 = last_address;
PRINT_POINTER(srealloc(p357,174););
printStats();
void* p452 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p453 = last_address;
PRINT_POINTER(scalloc(127,177););
printStats();
void* p454 = last_address;
PRINT_POINTER(scalloc(5,158););
printStats();
void* p455 = last_address;
PRINT_POINTER(srealloc(p346,127););
printStats();
void* p456 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p457 = last_address;
DEBUG_PRINT(sfree(p370););
printStats();
PRINT_POINTER(scalloc(177,188););
printStats();
void* p458 = last_address;
PRINT_POINTER(scalloc(241,40););
printStats();
void* p459 = last_address;
DEBUG_PRINT(sfree(p439););
printStats();
PRINT_POINTER(scalloc(46,203););
printStats();
void* p460 = last_address;
PRINT_POINTER(scalloc(154,212););
printStats();
void* p461 = last_address;
DEBUG_PRINT(sfree(p454););
printStats();
PRINT_POINTER(smalloc(144););
printStats();
void* p462 = last_address;
PRINT_POINTER(srealloc(p422,107););
printStats();
void* p463 = last_address;
DEBUG_PRINT(sfree(p331););
printStats();
PRINT_POINTER(smalloc(99););
printStats();
void* p464 = last_address;
PRINT_POINTER(srealloc(p445,77););
printStats();
void* p465 = last_address;
DEBUG_PRINT(sfree(p224););
printStats();
PRINT_POINTER(smalloc(42););
printStats();
void* p466 = last_address;
PRINT_POINTER(scalloc(137,223););
printStats();
void* p467 = last_address;
DEBUG_PRINT(sfree(p466););
printStats();
PRINT_POINTER(scalloc(128,134););
printStats();
void* p468 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p469 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p470 = last_address;
DEBUG_PRINT(sfree(p252););
printStats();
PRINT_POINTER(scalloc(195,185););
printStats();
void* p471 = last_address;
PRINT_POINTER(scalloc(119,134););
printStats();
void* p472 = last_address;
PRINT_POINTER(scalloc(19,14););
printStats();
void* p473 = last_address;
PRINT_POINTER(scalloc(90,130););
printStats();
void* p474 = last_address;
DEBUG_PRINT(sfree(p301););
printStats();
PRINT_POINTER(scalloc(168,231););
printStats();
void* p475 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p476 = last_address;
PRINT_POINTER(srealloc(p464,17););
printStats();
void* p477 = last_address;
DEBUG_PRINT(sfree(p474););
printStats();
DEBUG_PRINT(sfree(p421););
printStats();
PRINT_POINTER(smalloc(40););
printStats();
void* p478 = last_address;
PRINT_POINTER(srealloc(p424,222););
printStats();
void* p479 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p480 = last_address;
PRINT_POINTER(scalloc(85,21););
printStats();
void* p481 = last_address;
PRINT_POINTER(srealloc(p379,143););
printStats();
void* p482 = last_address;
PRINT_POINTER(srealloc(p469,77););
printStats();
void* p483 = last_address;
PRINT_POINTER(scalloc(119,158););
printStats();
void* p484 = last_address;
PRINT_POINTER(scalloc(101,72););
printStats();
void* p485 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p486 = last_address;
DEBUG_PRINT(sfree(p458););
printStats();
PRINT_POINTER(scalloc(62,48););
printStats();
void* p487 = last_address;
PRINT_POINTER(scalloc(206,191););
printStats();
void* p488 = last_address;
PRINT_POINTER(srealloc(p453,118););
printStats();
void* p489 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p490 = last_address;
PRINT_POINTER(scalloc(131,86););
printStats();
void* p491 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p492 = last_address;
DEBUG_PRINT(sfree(p297););
printStats();
PRINT_POINTER(smalloc(118););
printStats();
void* p493 = last_address;
PRINT_POINTER(srealloc(p339,182););
printStats();
void* p494 = last_address;
PRINT_POINTER(srealloc(p415,119););
printStats();
void* p495 = last_address;
PRINT_POINTER(scalloc(120,66););
printStats();
void* p496 = last_address;
DEBUG_PRINT(sfree(p484););
printStats();
PRINT_POINTER(smalloc(213););
printStats();
void* p497 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p498 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p499 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p500 = last_address;
DEBUG_PRINT(sfree(p490););
printStats();
DEBUG_PRINT(sfree(p303););
printStats();
DEBUG_PRINT(sfree(p461););
printStats();
PRINT_POINTER(smalloc(238););
printStats();
void* p501 = last_address;
PRINT_POINTER(scalloc(72,181););
printStats();
void* p502 = last_address;
PRINT_POINTER(scalloc(9,100););
printStats();
void* p503 = last_address;
PRINT_POINTER(scalloc(41,11););
printStats();
void* p504 = last_address;
PRINT_POINTER(srealloc(p423,188););
printStats();
void* p505 = last_address;
PRINT_POINTER(scalloc(106,8););
printStats();
void* p506 = last_address;
PRINT_POINTER(srealloc(p449,43););
printStats();
void* p507 = last_address;
PRINT_POINTER(scalloc(130,118););
printStats();
void* p508 = last_address;
PRINT_POINTER(srealloc(p247,148););
printStats();
void* p509 = last_address;
DEBUG_PRINT(sfree(p501););
printStats();
PRINT_POINTER(scalloc(134,226););
printStats();
void* p510 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p511 = last_address;
DEBUG_PRINT(sfree(p400););
printStats();
PRINT_POINTER(srealloc(p228,48););
printStats();
void* p512 = last_address;
PRINT_POINTER(srealloc(p372,220););
printStats();
void* p513 = last_address;
PRINT_POINTER(srealloc(p410,221););
printStats();
void* p514 = last_address;
PRINT_POINTER(srealloc(p428,125););
printStats();
void* p515 = last_address;
PRINT_POINTER(scalloc(227,94););
printStats();
void* p516 = last_address;
DEBUG_PRINT(sfree(p319););
printStats();
PRINT_POINTER(scalloc(162,77););
printStats();
void* p517 = last_address;
PRINT_POINTER(srealloc(p406,153););
printStats();
void* p518 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p519 = last_address;
PRINT_POINTER(srealloc(p253,24););
printStats();
void* p520 = last_address;
DEBUG_PRINT(sfree(p340););
printStats();
DEBUG_PRINT(sfree(p446););
printStats();
DEBUG_PRINT(sfree(p352););
printStats();
DEBUG_PRINT(sfree(p384););
printStats();
DEBUG_PRINT(sfree(p520););
printStats();
PRINT_POINTER(scalloc(73,208););
printStats();
void* p521 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p522 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p523 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p524 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p525 = last_address;
PRINT_POINTER(srealloc(p465,153););
printStats();
void* p526 = last_address;
PRINT_POINTER(scalloc(129,217););
printStats();
void* p527 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p528 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p529 = last_address;
DEBUG_PRINT(sfree(p493););
printStats();
PRINT_POINTER(srealloc(p472,156););
printStats();
void* p530 = last_address;
PRINT_POINTER(srealloc(p522,186););
printStats();
void* p531 = last_address;
DEBUG_PRINT(sfree(p242););
printStats();
PRINT_POINTER(smalloc(14););
printStats();
void* p532 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p533 = last_address;
PRINT_POINTER(scalloc(118,143););
printStats();
void* p534 = last_address;
DEBUG_PRINT(sfree(p441););
printStats();
PRINT_POINTER(srealloc(p208,226););
printStats();
void* p535 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p536 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p537 = last_address;
PRINT_POINTER(scalloc(89,60););
printStats();
void* p538 = last_address;
PRINT_POINTER(scalloc(195,234););
printStats();
void* p539 = last_address;
DEBUG_PRINT(sfree(p455););
printStats();
PRINT_POINTER(srealloc(p432,72););
printStats();
void* p540 = last_address;
PRINT_POINTER(scalloc(240,93););
printStats();
void* p541 = last_address;
PRINT_POINTER(srealloc(p388,166););
printStats();
void* p542 = last_address;
DEBUG_PRINT(sfree(p530););
printStats();
PRINT_POINTER(srealloc(p417,114););
printStats();
void* p543 = last_address;
DEBUG_PRINT(sfree(p226););
printStats();
PRINT_POINTER(scalloc(38,220););
printStats();
void* p544 = last_address;
PRINT_POINTER(scalloc(91,231););
printStats();
void* p545 = last_address;
PRINT_POINTER(srealloc(p397,127););
printStats();
void* p546 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p547 = last_address;
PRINT_POINTER(srealloc(p440,133););
printStats();
void* p548 = last_address;
PRINT_POINTER(scalloc(16,54););
printStats();
void* p549 = last_address;
PRINT_POINTER(srealloc(p482,212););
printStats();
void* p550 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p551 = last_address;
DEBUG_PRINT(sfree(p316););
printStats();
PRINT_POINTER(smalloc(173););
printStats();
void* p552 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p553 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p554 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p555 = last_address;
PRINT_POINTER(scalloc(49,32););
printStats();
void* p556 = last_address;
PRINT_POINTER(srealloc(p236,122););
printStats();
void* p557 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p558 = last_address;
DEBUG_PRINT(sfree(p544););
printStats();
DEBUG_PRINT(sfree(p543););
printStats();
PRINT_POINTER(smalloc(249););
printStats();
void* p559 = last_address;
DEBUG_PRINT(sfree(p296););
printStats();
PRINT_POINTER(srealloc(p533,90););
printStats();
void* p560 = last_address;
DEBUG_PRINT(sfree(p521););
printStats();
PRINT_POINTER(smalloc(213););
printStats();
void* p561 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p562 = last_address;
PRINT_POINTER(srealloc(p376,168););
printStats();
void* p563 = last_address;
PRINT_POINTER(srealloc(p489,30););
printStats();
void* p564 = last_address;
DEBUG_PRINT(sfree(p547););
printStats();
PRINT_POINTER(scalloc(34,76););
printStats();
void* p565 = last_address;
PRINT_POINTER(scalloc(168,2););
printStats();
void* p566 = last_address;
PRINT_POINTER(srealloc(p427,18););
printStats();
void* p567 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p568 = last_address;
PRINT_POINTER(scalloc(2,40););
printStats();
void* p569 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p570 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p571 = last_address;
PRINT_POINTER(scalloc(59,83););
printStats();
void* p572 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p573 = last_address;
PRINT_POINTER(scalloc(19,100););
printStats();
void* p574 = last_address;
PRINT_POINTER(scalloc(51,137););
printStats();
void* p575 = last_address;
DEBUG_PRINT(sfree(p304););
printStats();
DEBUG_PRINT(sfree(p558););
printStats();
PRINT_POINTER(smalloc(133););
printStats();
void* p576 = last_address;
DEBUG_PRINT(sfree(p476););
printStats();
PRINT_POINTER(srealloc(p572,212););
printStats();
void* p577 = last_address;
PRINT_POINTER(srealloc(p425,183););
printStats();
void* p578 = last_address;
DEBUG_PRINT(sfree(p488););
printStats();
PRINT_POINTER(srealloc(p351,135););
printStats();
void* p579 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p580 = last_address;
PRINT_POINTER(srealloc(p341,183););
printStats();
void* p581 = last_address;
PRINT_POINTER(srealloc(p487,106););
printStats();
void* p582 = last_address;
PRINT_POINTER(srealloc(p575,82););
printStats();
void* p583 = last_address;
PRINT_POINTER(scalloc(164,130););
printStats();
void* p584 = last_address;
DEBUG_PRINT(sfree(p337););
printStats();
DEBUG_PRINT(sfree(p459););
printStats();
PRINT_POINTER(srealloc(p584,157););
printStats();
void* p585 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p586 = last_address;
PRINT_POINTER(scalloc(116,134););
printStats();
void* p587 = last_address;
PRINT_POINTER(srealloc(p577,81););
printStats();
void* p588 = last_address;
PRINT_POINTER(scalloc(189,113););
printStats();
void* p589 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p590 = last_address;
DEBUG_PRINT(sfree(p528););
printStats();
PRINT_POINTER(scalloc(233,15););
printStats();
void* p591 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p592 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p593 = last_address;
PRINT_POINTER(srealloc(p438,175););
printStats();
void* p594 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p595 = last_address;
PRINT_POINTER(srealloc(p495,1););
printStats();
void* p596 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p597 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p598 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p599 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p600 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p601 = last_address;
PRINT_POINTER(srealloc(p290,74););
printStats();
void* p602 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p603 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p604 = last_address;
PRINT_POINTER(srealloc(p320,218););
printStats();
void* p605 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p606 = last_address;
PRINT_POINTER(scalloc(138,130););
printStats();
void* p607 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p608 = last_address;
DEBUG_PRINT(sfree(p556););
printStats();
PRINT_POINTER(scalloc(123,106););
printStats();
void* p609 = last_address;
DEBUG_PRINT(sfree(p467););
printStats();
PRINT_POINTER(srealloc(p433,242););
printStats();
void* p610 = last_address;
DEBUG_PRINT(sfree(p608););
printStats();
PRINT_POINTER(smalloc(26););
printStats();
void* p611 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p612 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p613 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p614 = last_address;
PRINT_POINTER(scalloc(130,153););
printStats();
void* p615 = last_address;
PRINT_POINTER(scalloc(145,93););
printStats();
void* p616 = last_address;
PRINT_POINTER(srealloc(p612,177););
printStats();
void* p617 = last_address;
DEBUG_PRINT(sfree(p538););
printStats();
PRINT_POINTER(scalloc(230,198););
printStats();
void* p618 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p619 = last_address;
DEBUG_PRINT(sfree(p514););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p620 = last_address;
DEBUG_PRINT(sfree(p512););
printStats();
PRINT_POINTER(srealloc(p307,237););
printStats();
void* p621 = last_address;
PRINT_POINTER(srealloc(p607,192););
printStats();
void* p622 = last_address;
DEBUG_PRINT(sfree(p508););
printStats();
PRINT_POINTER(smalloc(182););
printStats();
void* p623 = last_address;
PRINT_POINTER(srealloc(p402,86););
printStats();
void* p624 = last_address;
PRINT_POINTER(scalloc(38,1););
printStats();
void* p625 = last_address;
DEBUG_PRINT(sfree(p257););
printStats();
PRINT_POINTER(smalloc(112););
printStats();
void* p626 = last_address;
DEBUG_PRINT(sfree(p510););
printStats();
PRINT_POINTER(scalloc(127,16););
printStats();
void* p627 = last_address;
PRINT_POINTER(scalloc(222,61););
printStats();
void* p628 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p629 = last_address;
PRINT_POINTER(srealloc(p555,238););
printStats();
void* p630 = last_address;
DEBUG_PRINT(sfree(p629););
printStats();
PRINT_POINTER(scalloc(97,10););
printStats();
void* p631 = last_address;
PRINT_POINTER(scalloc(227,40););
printStats();
void* p632 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p633 = last_address;
DEBUG_PRINT(sfree(p604););
printStats();
PRINT_POINTER(srealloc(p485,189););
printStats();
void* p634 = last_address;
DEBUG_PRINT(sfree(p597););
printStats();
PRINT_POINTER(srealloc(p333,56););
printStats();
void* p635 = last_address;
PRINT_POINTER(scalloc(158,247););
printStats();
void* p636 = last_address;
DEBUG_PRINT(sfree(p486););
printStats();
PRINT_POINTER(scalloc(133,219););
printStats();
void* p637 = last_address;
PRINT_POINTER(srealloc(p516,138););
printStats();
void* p638 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p639 = last_address;
PRINT_POINTER(scalloc(132,116););
printStats();
void* p640 = last_address;
PRINT_POINTER(srealloc(p545,218););
printStats();
void* p641 = last_address;
PRINT_POINTER(srealloc(p373,72););
printStats();
void* p642 = last_address;
DEBUG_PRINT(sfree(p611););
printStats();
PRINT_POINTER(scalloc(157,100););
printStats();
void* p643 = last_address;
DEBUG_PRINT(sfree(p326););
printStats();
PRINT_POINTER(scalloc(43,229););
printStats();
void* p644 = last_address;
PRINT_POINTER(scalloc(114,134););
printStats();
void* p645 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p646 = last_address;
PRINT_POINTER(srealloc(p636,140););
printStats();
void* p647 = last_address;
DEBUG_PRINT(sfree(p230););
printStats();
PRINT_POINTER(srealloc(p559,30););
printStats();
void* p648 = last_address;
DEBUG_PRINT(sfree(p266););
printStats();
PRINT_POINTER(scalloc(228,72););
printStats();
void* p649 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p650 = last_address;
DEBUG_PRINT(sfree(p525););
printStats();
PRINT_POINTER(smalloc(31););
printStats();
void* p651 = last_address;
DEBUG_PRINT(sfree(p343););
printStats();
PRINT_POINTER(scalloc(202,18););
printStats();
void* p652 = last_address;
PRINT_POINTER(srealloc(p591,33););
printStats();
void* p653 = last_address;
PRINT_POINTER(scalloc(158,154););
printStats();
void* p654 = last_address;
PRINT_POINTER(scalloc(190,87););
printStats();
void* p655 = last_address;
PRINT_POINTER(scalloc(246,166););
printStats();
void* p656 = last_address;
PRINT_POINTER(scalloc(178,39););
printStats();
void* p657 = last_address;
PRINT_POINTER(srealloc(p342,185););
printStats();
void* p658 = last_address;
PRINT_POINTER(srealloc(p550,9););
printStats();
void* p659 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p660 = last_address;
PRINT_POINTER(scalloc(236,32););
printStats();
void* p661 = last_address;
DEBUG_PRINT(sfree(p499););
printStats();
PRINT_POINTER(scalloc(77,218););
printStats();
void* p662 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p663 = last_address;
PRINT_POINTER(scalloc(82,70););
printStats();
void* p664 = last_address;
PRINT_POINTER(scalloc(71,121););
printStats();
void* p665 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p666 = last_address;
PRINT_POINTER(srealloc(p552,207););
printStats();
void* p667 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p668 = last_address;
PRINT_POINTER(scalloc(202,219););
printStats();
void* p669 = last_address;
PRINT_POINTER(scalloc(187,96););
printStats();
void* p670 = last_address;
DEBUG_PRINT(sfree(p416););
printStats();
PRINT_POINTER(smalloc(131););
printStats();
void* p671 = last_address;
DEBUG_PRINT(sfree(p635););
printStats();
PRINT_POINTER(scalloc(125,164););
printStats();
void* p672 = last_address;
DEBUG_PRINT(sfree(p477););
printStats();
PRINT_POINTER(smalloc(146););
printStats();
void* p673 = last_address;
DEBUG_PRINT(sfree(p542););
printStats();
DEBUG_PRINT(sfree(p494););
printStats();
DEBUG_PRINT(sfree(p426););
printStats();
DEBUG_PRINT(sfree(p431););
printStats();
PRINT_POINTER(scalloc(223,110););
printStats();
void* p674 = last_address;
PRINT_POINTER(scalloc(3,31););
printStats();
void* p675 = last_address;
PRINT_POINTER(scalloc(163,37););
printStats();
void* p676 = last_address;
PRINT_POINTER(srealloc(p675,140););
printStats();
void* p677 = last_address;
PRINT_POINTER(scalloc(82,226););
printStats();
void* p678 = last_address;
PRINT_POINTER(scalloc(201,93););
printStats();
void* p679 = last_address;
PRINT_POINTER(srealloc(p650,246););
printStats();
void* p680 = last_address;
PRINT_POINTER(srealloc(p616,61););
printStats();
void* p681 = last_address;
PRINT_POINTER(srealloc(p420,102););
printStats();
void* p682 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p683 = last_address;
PRINT_POINTER(scalloc(0,42););
printStats();
void* p684 = last_address;
DEBUG_PRINT(sfree(p359););
printStats();
PRINT_POINTER(srealloc(p480,148););
printStats();
void* p685 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p686 = last_address;
PRINT_POINTER(srealloc(p232,212););
printStats();
void* p687 = last_address;
PRINT_POINTER(srealloc(p513,89););
printStats();
void* p688 = last_address;
PRINT_POINTER(scalloc(24,105););
printStats();
void* p689 = last_address;
PRINT_POINTER(srealloc(p503,144););
printStats();
void* p690 = last_address;
PRINT_POINTER(srealloc(p596,241););
printStats();
void* p691 = last_address;
PRINT_POINTER(scalloc(193,39););
printStats();
void* p692 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p693 = last_address;
DEBUG_PRINT(sfree(p623););
printStats();
PRINT_POINTER(scalloc(249,180););
printStats();
void* p694 = last_address;
PRINT_POINTER(srealloc(p652,162););
printStats();
void* p695 = last_address;
PRINT_POINTER(scalloc(189,142););
printStats();
void* p696 = last_address;
DEBUG_PRINT(sfree(p638););
printStats();
PRINT_POINTER(scalloc(223,210););
printStats();
void* p697 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p698 = last_address;
PRINT_POINTER(scalloc(222,10););
printStats();
void* p699 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p700 = last_address;
PRINT_POINTER(scalloc(71,211););
printStats();
void* p701 = last_address;
PRINT_POINTER(scalloc(133,235););
printStats();
void* p702 = last_address;
DEBUG_PRINT(sfree(p653););
printStats();
PRINT_POINTER(smalloc(99););
printStats();
void* p703 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p704 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p705 = last_address;
DEBUG_PRINT(sfree(p651););
printStats();
DEBUG_PRINT(sfree(p573););
printStats();
DEBUG_PRINT(sfree(p640););
printStats();
PRINT_POINTER(srealloc(p270,128););
printStats();
void* p706 = last_address;
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(srealloc(p362,33););
printStats();
void* p707 = last_address;
PRINT_POINTER(srealloc(p665,76););
printStats();
void* p708 = last_address;
DEBUG_PRINT(sfree(p603););
printStats();
PRINT_POINTER(srealloc(p690,177););
printStats();
void* p709 = last_address;
DEBUG_PRINT(sfree(p269););
printStats();
PRINT_POINTER(scalloc(176,121););
printStats();
void* p710 = last_address;
DEBUG_PRINT(sfree(p523););
printStats();
PRINT_POINTER(scalloc(170,89););
printStats();
void* p711 = last_address;
DEBUG_PRINT(sfree(p394););
printStats();
PRINT_POINTER(scalloc(65,116););
printStats();
void* p712 = last_address;
PRINT_POINTER(scalloc(52,98););
printStats();
void* p713 = last_address;
PRINT_POINTER(scalloc(93,193););
printStats();
void* p714 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p715 = last_address;
DEBUG_PRINT(sfree(p671););
printStats();
PRINT_POINTER(srealloc(p306,88););
printStats();
void* p716 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p717 = last_address;
PRINT_POINTER(scalloc(68,192););
printStats();
void* p718 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p719 = last_address;
DEBUG_PRINT(sfree(p457););
printStats();
PRINT_POINTER(smalloc(64););
printStats();
void* p720 = last_address;
PRINT_POINTER(srealloc(p626,13););
printStats();
void* p721 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p722 = last_address;
DEBUG_PRINT(sfree(p715););
printStats();
DEBUG_PRINT(sfree(p564););
printStats();
PRINT_POINTER(scalloc(237,177););
printStats();
void* p723 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p724 = last_address;
PRINT_POINTER(srealloc(p709,210););
printStats();
void* p725 = last_address;
PRINT_POINTER(srealloc(p578,221););
printStats();
void* p726 = last_address;
DEBUG_PRINT(sfree(p699););
printStats();
PRINT_POINTER(smalloc(90););
printStats();
void* p727 = last_address;
PRINT_POINTER(srealloc(p693,154););
printStats();
void* p728 = last_address;
PRINT_POINTER(scalloc(35,87););
printStats();
void* p729 = last_address;
PRINT_POINTER(srealloc(p360,21););
printStats();
void* p730 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p731 = last_address;
PRINT_POINTER(srealloc(p655,224););
printStats();
void* p732 = last_address;
DEBUG_PRINT(sfree(p716););
printStats();
DEBUG_PRINT(sfree(p701););
printStats();
PRINT_POINTER(srealloc(p732,36););
printStats();
void* p733 = last_address;
PRINT_POINTER(scalloc(63,216););
printStats();
void* p734 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p735 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p736 = last_address;
PRINT_POINTER(srealloc(p456,126););
printStats();
void* p737 = last_address;
DEBUG_PRINT(sfree(p625););
printStats();
PRINT_POINTER(srealloc(p621,198););
printStats();
void* p738 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p739 = last_address;
PRINT_POINTER(srealloc(p382,178););
printStats();
void* p740 = last_address;
DEBUG_PRINT(sfree(p628););
printStats();
PRINT_POINTER(smalloc(196););
printStats();
void* p741 = last_address;
DEBUG_PRINT(sfree(p450););
printStats();
DEBUG_PRINT(sfree(p672););
printStats();
PRINT_POINTER(srealloc(p265,217););
printStats();
void* p742 = last_address;
PRINT_POINTER(scalloc(8,54););
printStats();
void* p743 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p744 = last_address;
DEBUG_PRINT(sfree(p413););
printStats();
DEBUG_PRINT(sfree(p498););
printStats();
PRINT_POINTER(scalloc(89,212););
printStats();
void* p745 = last_address;
PRINT_POINTER(srealloc(p694,20););
printStats();
void* p746 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p747 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p748 = last_address;
PRINT_POINTER(scalloc(43,120););
printStats();
void* p749 = last_address;
PRINT_POINTER(scalloc(74,207););
printStats();
void* p750 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p751 = last_address;
PRINT_POINTER(scalloc(245,30););
printStats();
void* p752 = last_address;
PRINT_POINTER(srealloc(p434,50););
printStats();
void* p753 = last_address;
PRINT_POINTER(srealloc(p595,148););
printStats();
void* p754 = last_address;
PRINT_POINTER(scalloc(138,45););
printStats();
void* p755 = last_address;
PRINT_POINTER(scalloc(103,192););
printStats();
void* p756 = last_address;
DEBUG_PRINT(sfree(p527););
printStats();
PRINT_POINTER(scalloc(193,117););
printStats();
void* p757 = last_address;
DEBUG_PRINT(sfree(p687););
printStats();
PRINT_POINTER(smalloc(166););
printStats();
void* p758 = last_address;
PRINT_POINTER(srealloc(p727,191););
printStats();
void* p759 = last_address;
PRINT_POINTER(srealloc(p708,188););
printStats();
void* p760 = last_address;
DEBUG_PRINT(sfree(p475););
printStats();
PRINT_POINTER(scalloc(167,195););
printStats();
void* p761 = last_address;
DEBUG_PRINT(sfree(p418););
printStats();
DEBUG_PRINT(sfree(p444););
printStats();
PRINT_POINTER(srealloc(p761,74););
printStats();
void* p762 = last_address;
PRINT_POINTER(scalloc(138,181););
printStats();
void* p763 = last_address;
DEBUG_PRINT(sfree(p463););
printStats();
DEBUG_PRINT(sfree(p567););
printStats();
PRINT_POINTER(srealloc(p751,203););
printStats();
void* p764 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p765 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p766 = last_address;
DEBUG_PRINT(sfree(p587););
printStats();
DEBUG_PRINT(sfree(p518););
printStats();
PRINT_POINTER(scalloc(234,175););
printStats();
void* p767 = last_address;
DEBUG_PRINT(sfree(p627););
printStats();
PRINT_POINTER(scalloc(181,203););
printStats();
void* p768 = last_address;
PRINT_POINTER(srealloc(p718,167););
printStats();
void* p769 = last_address;
PRINT_POINTER(scalloc(75,31););
printStats();
void* p770 = last_address;
PRINT_POINTER(scalloc(169,67););
printStats();
void* p771 = last_address;
PRINT_POINTER(srealloc(p755,221););
printStats();
void* p772 = last_address;
PRINT_POINTER(srealloc(p747,71););
printStats();
void* p773 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p774 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p775 = last_address;
DEBUG_PRINT(sfree(p637););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p776 = last_address;
PRINT_POINTER(srealloc(p374,221););
printStats();
void* p777 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p778 = last_address;
PRINT_POINTER(srealloc(p668,0););
printStats();
void* p779 = last_address;
PRINT_POINTER(scalloc(29,98););
printStats();
void* p780 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p781 = last_address;
DEBUG_PRINT(sfree(p614););
printStats();
PRINT_POINTER(srealloc(p763,53););
printStats();
void* p782 = last_address;
PRINT_POINTER(scalloc(90,37););
printStats();
void* p783 = last_address;
PRINT_POINTER(srealloc(p753,156););
printStats();
void* p784 = last_address;
PRINT_POINTER(srealloc(p676,134););
printStats();
void* p785 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p786 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p787 = last_address;
PRINT_POINTER(scalloc(121,161););
printStats();
void* p788 = last_address;
DEBUG_PRINT(sfree(p553););
printStats();
PRINT_POINTER(scalloc(228,103););
printStats();
void* p789 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p790 = last_address;
PRINT_POINTER(srealloc(p633,192););
printStats();
void* p791 = last_address;
PRINT_POINTER(scalloc(172,173););
printStats();
void* p792 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p793 = last_address;
PRINT_POINTER(srealloc(p505,139););
printStats();
void* p794 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p795 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p796 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p797 = last_address;
PRINT_POINTER(srealloc(p583,14););
printStats();
void* p798 = last_address;
PRINT_POINTER(srealloc(p656,68););
printStats();
void* p799 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p800 = last_address;
PRINT_POINTER(srealloc(p787,2););
printStats();
void* p801 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p802 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p803 = last_address;
PRINT_POINTER(scalloc(184,127););
printStats();
void* p804 = last_address;
DEBUG_PRINT(sfree(p401););
printStats();
PRINT_POINTER(scalloc(209,239););
printStats();
void* p805 = last_address;
PRINT_POINTER(scalloc(186,211););
printStats();
void* p806 = last_address;
DEBUG_PRINT(sfree(p585););
printStats();
PRINT_POINTER(smalloc(173););
printStats();
void* p807 = last_address;
PRINT_POINTER(srealloc(p742,36););
printStats();
void* p808 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p809 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p810 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p811 = last_address;
PRINT_POINTER(scalloc(151,33););
printStats();
void* p812 = last_address;
DEBUG_PRINT(sfree(p734););
printStats();
PRINT_POINTER(smalloc(36););
printStats();
void* p813 = last_address;
PRINT_POINTER(srealloc(p507,189););
printStats();
void* p814 = last_address;
DEBUG_PRINT(sfree(p305););
printStats();
PRINT_POINTER(srealloc(p471,21););
printStats();
void* p815 = last_address;
DEBUG_PRINT(sfree(p772););
printStats();
PRINT_POINTER(scalloc(176,214););
printStats();
void* p816 = last_address;
PRINT_POINTER(srealloc(p592,191););
printStats();
void* p817 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p818 = last_address;
PRINT_POINTER(scalloc(56,1););
printStats();
void* p819 = last_address;
DEBUG_PRINT(sfree(p754););
printStats();
DEBUG_PRINT(sfree(p561););
printStats();
PRINT_POINTER(srealloc(p613,184););
printStats();
void* p820 = last_address;
PRINT_POINTER(srealloc(p497,221););
printStats();
void* p821 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p822 = last_address;
PRINT_POINTER(srealloc(p570,159););
printStats();
void* p823 = last_address;
PRINT_POINTER(srealloc(p565,160););
printStats();
void* p824 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p825 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p826 = last_address;
PRINT_POINTER(scalloc(139,78););
printStats();
void* p827 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p828 = last_address;
DEBUG_PRINT(sfree(p783););
printStats();
PRINT_POINTER(smalloc(228););
printStats();
void* p829 = last_address;
PRINT_POINTER(scalloc(236,35););
printStats();
void* p830 = last_address;
PRINT_POINTER(srealloc(p643,241););
printStats();
void* p831 = last_address;
PRINT_POINTER(scalloc(85,20););
printStats();
void* p832 = last_address;
PRINT_POINTER(scalloc(142,172););
printStats();
void* p833 = last_address;
DEBUG_PRINT(sfree(p515););
printStats();
PRINT_POINTER(srealloc(p534,92););
printStats();
void* p834 = last_address;
DEBUG_PRINT(sfree(p412););
printStats();
PRINT_POINTER(srealloc(p610,52););
printStats();
void* p835 = last_address;
PRINT_POINTER(srealloc(p821,172););
printStats();
void* p836 = last_address;
PRINT_POINTER(scalloc(58,2););
printStats();
void* p837 = last_address;
PRINT_POINTER(srealloc(p321,219););
printStats();
void* p838 = last_address;
PRINT_POINTER(srealloc(p403,242););
printStats();
void* p839 = last_address;
DEBUG_PRINT(sfree(p524););
printStats();
PRINT_POINTER(scalloc(194,44););
printStats();
void* p840 = last_address;
PRINT_POINTER(srealloc(p801,75););
printStats();
void* p841 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p842 = last_address;
PRINT_POINTER(scalloc(139,106););
printStats();
void* p843 = last_address;
PRINT_POINTER(scalloc(195,227););
printStats();
void* p844 = last_address;
DEBUG_PRINT(sfree(p404););
printStats();
PRINT_POINTER(srealloc(p631,129););
printStats();
void* p845 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p846 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p847 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p848 = last_address;
PRINT_POINTER(scalloc(199,4););
printStats();
void* p849 = last_address;
PRINT_POINTER(srealloc(p818,145););
printStats();
void* p850 = last_address;
DEBUG_PRINT(sfree(p648););
printStats();
PRINT_POINTER(scalloc(200,148););
printStats();
void* p851 = last_address;
PRINT_POINTER(srealloc(p663,209););
printStats();
void* p852 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p853 = last_address;
PRINT_POINTER(scalloc(114,33););
printStats();
void* p854 = last_address;
DEBUG_PRINT(sfree(p828););
printStats();
PRINT_POINTER(smalloc(158););
printStats();
void* p855 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p856 = last_address;
DEBUG_PRINT(sfree(p762););
printStats();
PRINT_POINTER(scalloc(148,229););
printStats();
void* p857 = last_address;
PRINT_POINTER(scalloc(225,27););
printStats();
void* p858 = last_address;
DEBUG_PRINT(sfree(p641););
printStats();
PRINT_POINTER(srealloc(p196,141););
printStats();
void* p859 = last_address;
PRINT_POINTER(srealloc(p852,109););
printStats();
void* p860 = last_address;
DEBUG_PRINT(sfree(p680););
printStats();
PRINT_POINTER(smalloc(100););
printStats();
void* p861 = last_address;
PRINT_POINTER(srealloc(p541,142););
printStats();
void* p862 = last_address;
PRINT_POINTER(scalloc(7,205););
printStats();
void* p863 = last_address;
PRINT_POINTER(srealloc(p782,25););
printStats();
void* p864 = last_address;
DEBUG_PRINT(sfree(p535););
printStats();
PRINT_POINTER(smalloc(238););
printStats();
void* p865 = last_address;
DEBUG_PRINT(sfree(p844););
printStats();
DEBUG_PRINT(sfree(p704););
printStats();
DEBUG_PRINT(sfree(p630););
printStats();
PRINT_POINTER(srealloc(p767,115););
printStats();
void* p866 = last_address;
PRINT_POINTER(srealloc(p661,147););
printStats();
void* p867 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p868 = last_address;
DEBUG_PRINT(sfree(p470););
printStats();
PRINT_POINTER(srealloc(p233,185););
printStats();
void* p869 = last_address;
PRINT_POINTER(srealloc(p758,58););
printStats();
void* p870 = last_address;
PRINT_POINTER(srealloc(p447,6););
printStats();
void* p871 = last_address;
PRINT_POINTER(srealloc(p395,131););
printStats();
void* p872 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p873 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p874 = last_address;
PRINT_POINTER(scalloc(14,190););
printStats();
void* p875 = last_address;
PRINT_POINTER(srealloc(p405,226););
printStats();
void* p876 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p877 = last_address;
PRINT_POINTER(srealloc(p786,17););
printStats();
void* p878 = last_address;
PRINT_POINTER(srealloc(p462,209););
printStats();
void* p879 = last_address;
DEBUG_PRINT(sfree(p848););
printStats();
DEBUG_PRINT(sfree(p737););
printStats();
PRINT_POINTER(srealloc(p822,121););
printStats();
void* p880 = last_address;
PRINT_POINTER(srealloc(p589,142););
printStats();
void* p881 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p882 = last_address;
PRINT_POINTER(srealloc(p580,72););
printStats();
void* p883 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p884 = last_address;
PRINT_POINTER(scalloc(104,63););
printStats();
void* p885 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p886 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p887 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p888 = last_address;
DEBUG_PRINT(sfree(p771););
printStats();
DEBUG_PRINT(sfree(p874););
printStats();
PRINT_POINTER(smalloc(248););
printStats();
void* p889 = last_address;
DEBUG_PRINT(sfree(p519););
printStats();
PRINT_POINTER(srealloc(p532,163););
printStats();
void* p890 = last_address;
}
