#include "aux_macro.h"
#include "../malloc_2.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(90););
printStats();
void* p0 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p1 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p2 = last_address;
PRINT_POINTER(scalloc(247,105););
printStats();
void* p3 = last_address;
PRINT_POINTER(scalloc(75,246););
printStats();
void* p4 = last_address;
PRINT_POINTER(scalloc(9,17););
printStats();
void* p5 = last_address;
PRINT_POINTER(srealloc(p5,78););
printStats();
void* p6 = last_address;
PRINT_POINTER(srealloc(p6,115););
printStats();
void* p7 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p8 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p9 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p10 = last_address;
PRINT_POINTER(srealloc(p1,40););
printStats();
void* p11 = last_address;
PRINT_POINTER(srealloc(p0,100););
printStats();
void* p12 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
PRINT_POINTER(srealloc(p10,146););
printStats();
void* p13 = last_address;
PRINT_POINTER(srealloc(p8,38););
printStats();
void* p14 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p15 = last_address;
PRINT_POINTER(scalloc(48,24););
printStats();
void* p16 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p17 = last_address;
PRINT_POINTER(srealloc(p7,226););
printStats();
void* p18 = last_address;
PRINT_POINTER(scalloc(26,194););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p20 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(scalloc(157,206););
printStats();
void* p21 = last_address;
PRINT_POINTER(scalloc(187,65););
printStats();
void* p22 = last_address;
PRINT_POINTER(srealloc(p17,197););
printStats();
void* p23 = last_address;
PRINT_POINTER(scalloc(247,90););
printStats();
void* p24 = last_address;
PRINT_POINTER(srealloc(p9,201););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(134,35););
printStats();
void* p26 = last_address;
DEBUG_PRINT(sfree(p26););
printStats();
PRINT_POINTER(smalloc(178););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p27););
printStats();
PRINT_POINTER(scalloc(34,233););
printStats();
void* p28 = last_address;
PRINT_POINTER(srealloc(p21,193););
printStats();
void* p29 = last_address;
PRINT_POINTER(srealloc(p22,151););
printStats();
void* p30 = last_address;
DEBUG_PRINT(sfree(p30););
printStats();
PRINT_POINTER(srealloc(p12,52););
printStats();
void* p31 = last_address;
PRINT_POINTER(srealloc(p31,128););
printStats();
void* p32 = last_address;
PRINT_POINTER(scalloc(175,50););
printStats();
void* p33 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p34 = last_address;
DEBUG_PRINT(sfree(p3););
printStats();
DEBUG_PRINT(sfree(p29););
printStats();
DEBUG_PRINT(sfree(p25););
printStats();
PRINT_POINTER(smalloc(7););
printStats();
void* p35 = last_address;
PRINT_POINTER(srealloc(p32,164););
printStats();
void* p36 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
PRINT_POINTER(srealloc(p19,240););
printStats();
void* p37 = last_address;
DEBUG_PRINT(sfree(p13););
printStats();
PRINT_POINTER(srealloc(p23,189););
printStats();
void* p38 = last_address;
PRINT_POINTER(srealloc(p15,70););
printStats();
void* p39 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p40,108););
printStats();
void* p41 = last_address;
PRINT_POINTER(srealloc(p14,193););
printStats();
void* p42 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(scalloc(229,163););
printStats();
void* p43 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(smalloc(121););
printStats();
void* p44 = last_address;
PRINT_POINTER(srealloc(p20,67););
printStats();
void* p45 = last_address;
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(smalloc(249););
printStats();
void* p46 = last_address;
PRINT_POINTER(srealloc(p39,125););
printStats();
void* p47 = last_address;
PRINT_POINTER(srealloc(p37,203););
printStats();
void* p48 = last_address;
DEBUG_PRINT(sfree(p16););
printStats();
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(srealloc(p43,45););
printStats();
void* p49 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p50 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p51 = last_address;
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(scalloc(72,102););
printStats();
void* p52 = last_address;
PRINT_POINTER(scalloc(21,43););
printStats();
void* p53 = last_address;
PRINT_POINTER(srealloc(p52,45););
printStats();
void* p54 = last_address;
PRINT_POINTER(srealloc(p51,103););
printStats();
void* p55 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(srealloc(p44,220););
printStats();
void* p56 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(238,230););
printStats();
void* p58 = last_address;
PRINT_POINTER(scalloc(0,240););
printStats();
void* p59 = last_address;
PRINT_POINTER(scalloc(58,213););
printStats();
void* p60 = last_address;
PRINT_POINTER(scalloc(244,244););
printStats();
void* p61 = last_address;
PRINT_POINTER(srealloc(p61,69););
printStats();
void* p62 = last_address;
DEBUG_PRINT(sfree(p56););
printStats();
PRINT_POINTER(smalloc(60););
printStats();
void* p63 = last_address;
PRINT_POINTER(scalloc(127,198););
printStats();
void* p64 = last_address;
DEBUG_PRINT(sfree(p55););
printStats();
PRINT_POINTER(scalloc(21,68););
printStats();
void* p65 = last_address;
PRINT_POINTER(srealloc(p53,163););
printStats();
void* p66 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(smalloc(96););
printStats();
void* p67 = last_address;
PRINT_POINTER(srealloc(p36,95););
printStats();
void* p68 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p69 = last_address;
PRINT_POINTER(scalloc(187,235););
printStats();
void* p70 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(smalloc(158););
printStats();
void* p71 = last_address;
PRINT_POINTER(scalloc(107,145););
printStats();
void* p72 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p73 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p74 = last_address;
PRINT_POINTER(srealloc(p70,125););
printStats();
void* p75 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p76 = last_address;
DEBUG_PRINT(sfree(p74););
printStats();
PRINT_POINTER(srealloc(p66,187););
printStats();
void* p77 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p78 = last_address;
PRINT_POINTER(scalloc(233,41););
printStats();
void* p79 = last_address;
PRINT_POINTER(scalloc(37,130););
printStats();
void* p80 = last_address;
PRINT_POINTER(srealloc(p75,223););
printStats();
void* p81 = last_address;
PRINT_POINTER(srealloc(p67,240););
printStats();
void* p82 = last_address;
PRINT_POINTER(scalloc(100,203););
printStats();
void* p83 = last_address;
DEBUG_PRINT(sfree(p79););
printStats();
PRINT_POINTER(smalloc(65););
printStats();
void* p84 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(smalloc(90););
printStats();
void* p85 = last_address;
PRINT_POINTER(srealloc(p42,20););
printStats();
void* p86 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p87 = last_address;
PRINT_POINTER(scalloc(164,27););
printStats();
void* p88 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p89 = last_address;
DEBUG_PRINT(sfree(p88););
printStats();
PRINT_POINTER(srealloc(p47,10););
printStats();
void* p90 = last_address;
PRINT_POINTER(scalloc(175,34););
printStats();
void* p91 = last_address;
PRINT_POINTER(scalloc(186,4););
printStats();
void* p92 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p93 = last_address;
PRINT_POINTER(srealloc(p91,247););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p95 = last_address;
PRINT_POINTER(srealloc(p73,91););
printStats();
void* p96 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p97 = last_address;
PRINT_POINTER(srealloc(p81,74););
printStats();
void* p98 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p99 = last_address;
PRINT_POINTER(scalloc(75,59););
printStats();
void* p100 = last_address;
PRINT_POINTER(srealloc(p71,82););
printStats();
void* p101 = last_address;
PRINT_POINTER(scalloc(116,28););
printStats();
void* p102 = last_address;
PRINT_POINTER(srealloc(p95,169););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p90,50););
printStats();
void* p104 = last_address;
PRINT_POINTER(scalloc(86,80););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p76,38););
printStats();
void* p106 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p107 = last_address;
DEBUG_PRINT(sfree(p87););
printStats();
PRINT_POINTER(srealloc(p63,239););
printStats();
void* p108 = last_address;
PRINT_POINTER(srealloc(p50,127););
printStats();
void* p109 = last_address;
PRINT_POINTER(srealloc(p78,61););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p48,127););
printStats();
void* p111 = last_address;
PRINT_POINTER(scalloc(217,52););
printStats();
void* p112 = last_address;
PRINT_POINTER(scalloc(111,219););
printStats();
void* p113 = last_address;
PRINT_POINTER(scalloc(10,212););
printStats();
void* p114 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(smalloc(69););
printStats();
void* p115 = last_address;
PRINT_POINTER(srealloc(p101,75););
printStats();
void* p116 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p117 = last_address;
PRINT_POINTER(scalloc(242,170););
printStats();
void* p118 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p119 = last_address;
PRINT_POINTER(srealloc(p119,49););
printStats();
void* p120 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p121 = last_address;
PRINT_POINTER(scalloc(6,29););
printStats();
void* p122 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
PRINT_POINTER(scalloc(85,28););
printStats();
void* p123 = last_address;
PRINT_POINTER(srealloc(p84,247););
printStats();
void* p124 = last_address;
DEBUG_PRINT(sfree(p110););
printStats();
DEBUG_PRINT(sfree(p102););
printStats();
PRINT_POINTER(smalloc(218););
printStats();
void* p125 = last_address;
DEBUG_PRINT(sfree(p68););
printStats();
DEBUG_PRINT(sfree(p108););
printStats();
DEBUG_PRINT(sfree(p92););
printStats();
PRINT_POINTER(smalloc(21););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(46,36););
printStats();
void* p127 = last_address;
DEBUG_PRINT(sfree(p113););
printStats();
DEBUG_PRINT(sfree(p64););
printStats();
DEBUG_PRINT(sfree(p99););
printStats();
PRINT_POINTER(srealloc(p107,171););
printStats();
void* p128 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p129 = last_address;
DEBUG_PRINT(sfree(p93););
printStats();
PRINT_POINTER(srealloc(p106,220););
printStats();
void* p130 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(smalloc(227););
printStats();
void* p131 = last_address;
PRINT_POINTER(scalloc(72,211););
printStats();
void* p132 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p133 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p134 = last_address;
PRINT_POINTER(scalloc(145,238););
printStats();
void* p135 = last_address;
PRINT_POINTER(srealloc(p94,66););
printStats();
void* p136 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p137 = last_address;
DEBUG_PRINT(sfree(p103););
printStats();
DEBUG_PRINT(sfree(p128););
printStats();
PRINT_POINTER(smalloc(39););
printStats();
void* p138 = last_address;
DEBUG_PRINT(sfree(p105););
printStats();
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(scalloc(146,37););
printStats();
void* p139 = last_address;
PRINT_POINTER(scalloc(139,59););
printStats();
void* p140 = last_address;
PRINT_POINTER(scalloc(63,68););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p120,219););
printStats();
void* p142 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
DEBUG_PRINT(sfree(p139););
printStats();
PRINT_POINTER(smalloc(14););
printStats();
void* p143 = last_address;
PRINT_POINTER(srealloc(p86,237););
printStats();
void* p144 = last_address;
PRINT_POINTER(srealloc(p72,69););
printStats();
void* p145 = last_address;
PRINT_POINTER(srealloc(p112,35););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
DEBUG_PRINT(sfree(p123););
printStats();
DEBUG_PRINT(sfree(p35););
printStats();
PRINT_POINTER(srealloc(p126,121););
printStats();
void* p147 = last_address;
PRINT_POINTER(scalloc(6,6););
printStats();
void* p148 = last_address;
PRINT_POINTER(srealloc(p96,34););
printStats();
void* p149 = last_address;
DEBUG_PRINT(sfree(p125););
printStats();
PRINT_POINTER(srealloc(p58,157););
printStats();
void* p150 = last_address;
PRINT_POINTER(srealloc(p146,66););
printStats();
void* p151 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(srealloc(p127,155););
printStats();
void* p152 = last_address;
DEBUG_PRINT(sfree(p115););
printStats();
DEBUG_PRINT(sfree(p140););
printStats();
PRINT_POINTER(smalloc(24););
printStats();
void* p153 = last_address;
PRINT_POINTER(srealloc(p83,130););
printStats();
void* p154 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p155 = last_address;
DEBUG_PRINT(sfree(p111););
printStats();
PRINT_POINTER(srealloc(p129,116););
printStats();
void* p156 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p157 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p158 = last_address;
DEBUG_PRINT(sfree(p136););
printStats();
PRINT_POINTER(srealloc(p137,129););
printStats();
void* p159 = last_address;
DEBUG_PRINT(sfree(p141););
printStats();
DEBUG_PRINT(sfree(p151););
printStats();
DEBUG_PRINT(sfree(p138););
printStats();
PRINT_POINTER(smalloc(131););
printStats();
void* p160 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(smalloc(147););
printStats();
void* p161 = last_address;
PRINT_POINTER(scalloc(224,154););
printStats();
void* p162 = last_address;
PRINT_POINTER(srealloc(p160,117););
printStats();
void* p163 = last_address;
PRINT_POINTER(scalloc(245,61););
printStats();
void* p164 = last_address;
PRINT_POINTER(scalloc(217,114););
printStats();
void* p165 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
DEBUG_PRINT(sfree(p153););
printStats();
PRINT_POINTER(scalloc(202,69););
printStats();
void* p166 = last_address;
PRINT_POINTER(srealloc(p104,53););
printStats();
void* p167 = last_address;
PRINT_POINTER(scalloc(126,151););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(171,143););
printStats();
void* p169 = last_address;
PRINT_POINTER(srealloc(p122,108););
printStats();
void* p170 = last_address;
DEBUG_PRINT(sfree(p121););
printStats();
DEBUG_PRINT(sfree(p167););
printStats();
PRINT_POINTER(smalloc(99););
printStats();
void* p171 = last_address;
PRINT_POINTER(scalloc(219,25););
printStats();
void* p172 = last_address;
PRINT_POINTER(scalloc(145,68););
printStats();
void* p173 = last_address;
PRINT_POINTER(scalloc(179,128););
printStats();
void* p174 = last_address;
DEBUG_PRINT(sfree(p65););
printStats();
PRINT_POINTER(srealloc(p133,12););
printStats();
void* p175 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p176 = last_address;
PRINT_POINTER(scalloc(70,19););
printStats();
void* p177 = last_address;
PRINT_POINTER(srealloc(p80,28););
printStats();
void* p178 = last_address;
PRINT_POINTER(srealloc(p168,189););
printStats();
void* p179 = last_address;
PRINT_POINTER(scalloc(229,219););
printStats();
void* p180 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(srealloc(p134,42););
printStats();
void* p181 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(scalloc(181,235););
printStats();
void* p182 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(smalloc(110););
printStats();
void* p183 = last_address;
PRINT_POINTER(srealloc(p176,69););
printStats();
void* p184 = last_address;
PRINT_POINTER(scalloc(89,133););
printStats();
void* p185 = last_address;
DEBUG_PRINT(sfree(p162););
printStats();
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(scalloc(47,92););
printStats();
void* p186 = last_address;
PRINT_POINTER(scalloc(153,61););
printStats();
void* p187 = last_address;
PRINT_POINTER(scalloc(152,203););
printStats();
void* p188 = last_address;
PRINT_POINTER(scalloc(13,87););
printStats();
void* p189 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p190 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(scalloc(35,138););
printStats();
void* p191 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p192 = last_address;
PRINT_POINTER(scalloc(5,16););
printStats();
void* p193 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p194 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p195 = last_address;
PRINT_POINTER(srealloc(p154,68););
printStats();
void* p196 = last_address;
PRINT_POINTER(scalloc(234,38););
printStats();
void* p197 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p198 = last_address;
PRINT_POINTER(srealloc(p191,171););
printStats();
void* p199 = last_address;
PRINT_POINTER(scalloc(146,58););
printStats();
void* p200 = last_address;
DEBUG_PRINT(sfree(p184););
printStats();
PRINT_POINTER(scalloc(51,204););
printStats();
void* p201 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p202 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p203 = last_address;
PRINT_POINTER(srealloc(p49,176););
printStats();
void* p204 = last_address;
DEBUG_PRINT(sfree(p202););
printStats();
PRINT_POINTER(smalloc(76););
printStats();
void* p205 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p206 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p207 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p208 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(214,4););
printStats();
void* p210 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
PRINT_POINTER(scalloc(113,18););
printStats();
void* p211 = last_address;
PRINT_POINTER(srealloc(p174,89););
printStats();
void* p212 = last_address;
PRINT_POINTER(scalloc(169,4););
printStats();
void* p213 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p214 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p215 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p216 = last_address;
PRINT_POINTER(scalloc(57,77););
printStats();
void* p217 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p218 = last_address;
PRINT_POINTER(scalloc(190,0););
printStats();
void* p219 = last_address;
PRINT_POINTER(scalloc(216,35););
printStats();
void* p220 = last_address;
PRINT_POINTER(srealloc(p193,167););
printStats();
void* p221 = last_address;
DEBUG_PRINT(sfree(p219););
printStats();
PRINT_POINTER(smalloc(123););
printStats();
void* p222 = last_address;
PRINT_POINTER(srealloc(p213,69););
printStats();
void* p223 = last_address;
DEBUG_PRINT(sfree(p135););
printStats();
PRINT_POINTER(scalloc(150,217););
printStats();
void* p224 = last_address;
PRINT_POINTER(srealloc(p89,142););
printStats();
void* p225 = last_address;
PRINT_POINTER(scalloc(118,196););
printStats();
void* p226 = last_address;
PRINT_POINTER(scalloc(137,104););
printStats();
void* p227 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p228 = last_address;
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(scalloc(159,112););
printStats();
void* p229 = last_address;
DEBUG_PRINT(sfree(p204););
printStats();
PRINT_POINTER(scalloc(208,166););
printStats();
void* p230 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p231 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p232 = last_address;
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(smalloc(66););
printStats();
void* p233 = last_address;
PRINT_POINTER(scalloc(18,237););
printStats();
void* p234 = last_address;
PRINT_POINTER(scalloc(234,156););
printStats();
void* p235 = last_address;
PRINT_POINTER(srealloc(p183,231););
printStats();
void* p236 = last_address;
PRINT_POINTER(scalloc(88,41););
printStats();
void* p237 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p182,67););
printStats();
void* p239 = last_address;
PRINT_POINTER(scalloc(76,61););
printStats();
void* p240 = last_address;
DEBUG_PRINT(sfree(p149););
printStats();
PRINT_POINTER(scalloc(3,191););
printStats();
void* p241 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p188););
printStats();
PRINT_POINTER(srealloc(p220,29););
printStats();
void* p243 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p244 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p245 = last_address;
PRINT_POINTER(srealloc(p195,38););
printStats();
void* p246 = last_address;
PRINT_POINTER(srealloc(p242,4););
printStats();
void* p247 = last_address;
DEBUG_PRINT(sfree(p171););
printStats();
DEBUG_PRINT(sfree(p217););
printStats();
PRINT_POINTER(srealloc(p227,154););
printStats();
void* p248 = last_address;
PRINT_POINTER(srealloc(p178,87););
printStats();
void* p249 = last_address;
PRINT_POINTER(scalloc(241,110););
printStats();
void* p250 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p251 = last_address;
DEBUG_PRINT(sfree(p225););
printStats();
PRINT_POINTER(srealloc(p24,210););
printStats();
void* p252 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p253 = last_address;
PRINT_POINTER(srealloc(p164,5););
printStats();
void* p254 = last_address;
DEBUG_PRINT(sfree(p156););
printStats();
PRINT_POINTER(scalloc(201,201););
printStats();
void* p255 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p256 = last_address;
PRINT_POINTER(scalloc(201,77););
printStats();
void* p257 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p258 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p259 = last_address;
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(srealloc(p198,93););
printStats();
void* p260 = last_address;
DEBUG_PRINT(sfree(p158););
printStats();
DEBUG_PRINT(sfree(p252););
printStats();
PRINT_POINTER(srealloc(p230,188););
printStats();
void* p261 = last_address;
PRINT_POINTER(scalloc(174,27););
printStats();
void* p262 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p263 = last_address;
PRINT_POINTER(srealloc(p240,161););
printStats();
void* p264 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
PRINT_POINTER(smalloc(234););
printStats();
void* p265 = last_address;
PRINT_POINTER(srealloc(p143,190););
printStats();
void* p266 = last_address;
PRINT_POINTER(srealloc(p232,215););
printStats();
void* p267 = last_address;
PRINT_POINTER(scalloc(227,152););
printStats();
void* p268 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p269 = last_address;
PRINT_POINTER(srealloc(p196,192););
printStats();
void* p270 = last_address;
PRINT_POINTER(scalloc(120,209););
printStats();
void* p271 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
DEBUG_PRINT(sfree(p155););
printStats();
PRINT_POINTER(smalloc(204););
printStats();
void* p272 = last_address;
DEBUG_PRINT(sfree(p169););
printStats();
DEBUG_PRINT(sfree(p237););
printStats();
PRINT_POINTER(srealloc(p189,113););
printStats();
void* p273 = last_address;
DEBUG_PRINT(sfree(p192););
printStats();
PRINT_POINTER(smalloc(182););
printStats();
void* p274 = last_address;
DEBUG_PRINT(sfree(p187););
printStats();
DEBUG_PRINT(sfree(p226););
printStats();
PRINT_POINTER(smalloc(10););
printStats();
void* p275 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p276 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p277 = last_address;
PRINT_POINTER(srealloc(p228,165););
printStats();
void* p278 = last_address;
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(scalloc(202,210););
printStats();
void* p279 = last_address;
PRINT_POINTER(scalloc(31,199););
printStats();
void* p280 = last_address;
PRINT_POINTER(scalloc(72,213););
printStats();
void* p281 = last_address;
PRINT_POINTER(scalloc(208,58););
printStats();
void* p282 = last_address;
DEBUG_PRINT(sfree(p249););
printStats();
PRINT_POINTER(smalloc(69););
printStats();
void* p283 = last_address;
DEBUG_PRINT(sfree(p234););
printStats();
PRINT_POINTER(srealloc(p275,7););
printStats();
void* p284 = last_address;
PRINT_POINTER(scalloc(80,184););
printStats();
void* p285 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p286 = last_address;
PRINT_POINTER(scalloc(226,126););
printStats();
void* p287 = last_address;
PRINT_POINTER(scalloc(173,35););
printStats();
void* p288 = last_address;
PRINT_POINTER(srealloc(p180,0););
printStats();
void* p289 = last_address;
PRINT_POINTER(srealloc(p288,246););
printStats();
void* p290 = last_address;
DEBUG_PRINT(sfree(p283););
printStats();
PRINT_POINTER(scalloc(244,34););
printStats();
void* p291 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p292 = last_address;
DEBUG_PRINT(sfree(p177););
printStats();
PRINT_POINTER(smalloc(247););
printStats();
void* p293 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p294 = last_address;
DEBUG_PRINT(sfree(p117););
printStats();
PRINT_POINTER(smalloc(74););
printStats();
void* p295 = last_address;
DEBUG_PRINT(sfree(p241););
printStats();
PRINT_POINTER(smalloc(15););
printStats();
void* p296 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p297 = last_address;
PRINT_POINTER(srealloc(p274,125););
printStats();
void* p298 = last_address;
DEBUG_PRINT(sfree(p265););
printStats();
PRINT_POINTER(srealloc(p261,159););
printStats();
void* p299 = last_address;
PRINT_POINTER(srealloc(p208,218););
printStats();
void* p300 = last_address;
PRINT_POINTER(srealloc(p266,128););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p302 = last_address;
PRINT_POINTER(scalloc(90,107););
printStats();
void* p303 = last_address;
PRINT_POINTER(srealloc(p207,228););
printStats();
void* p304 = last_address;
PRINT_POINTER(scalloc(164,174););
printStats();
void* p305 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p306 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
PRINT_POINTER(smalloc(221););
printStats();
void* p307 = last_address;
DEBUG_PRINT(sfree(p284););
printStats();
PRINT_POINTER(srealloc(p289,48););
printStats();
void* p308 = last_address;
PRINT_POINTER(srealloc(p206,170););
printStats();
void* p309 = last_address;
PRINT_POINTER(scalloc(132,118););
printStats();
void* p310 = last_address;
PRINT_POINTER(scalloc(186,205););
printStats();
void* p311 = last_address;
PRINT_POINTER(scalloc(91,124););
printStats();
void* p312 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p313 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p314 = last_address;
PRINT_POINTER(srealloc(p251,33););
printStats();
void* p315 = last_address;
PRINT_POINTER(srealloc(p221,211););
printStats();
void* p316 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p317 = last_address;
DEBUG_PRINT(sfree(p291););
printStats();
PRINT_POINTER(scalloc(87,101););
printStats();
void* p318 = last_address;
DEBUG_PRINT(sfree(p292););
printStats();
PRINT_POINTER(smalloc(176););
printStats();
void* p319 = last_address;
DEBUG_PRINT(sfree(p286););
printStats();
PRINT_POINTER(smalloc(169););
printStats();
void* p320 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p321 = last_address;
DEBUG_PRINT(sfree(p247););
printStats();
PRINT_POINTER(srealloc(p304,57););
printStats();
void* p322 = last_address;
PRINT_POINTER(srealloc(p194,169););
printStats();
void* p323 = last_address;
DEBUG_PRINT(sfree(p319););
printStats();
PRINT_POINTER(smalloc(71););
printStats();
void* p324 = last_address;
PRINT_POINTER(scalloc(96,36););
printStats();
void* p325 = last_address;
DEBUG_PRINT(sfree(p301););
printStats();
PRINT_POINTER(smalloc(20););
printStats();
void* p326 = last_address;
PRINT_POINTER(scalloc(197,12););
printStats();
void* p327 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p328 = last_address;
DEBUG_PRINT(sfree(p296););
printStats();
PRINT_POINTER(smalloc(197););
printStats();
void* p329 = last_address;
PRINT_POINTER(scalloc(180,40););
printStats();
void* p330 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p331 = last_address;
PRINT_POINTER(scalloc(83,57););
printStats();
void* p332 = last_address;
PRINT_POINTER(srealloc(p57,214););
printStats();
void* p333 = last_address;
DEBUG_PRINT(sfree(p282););
printStats();
PRINT_POINTER(smalloc(160););
printStats();
void* p334 = last_address;
PRINT_POINTER(scalloc(65,166););
printStats();
void* p335 = last_address;
PRINT_POINTER(scalloc(192,140););
printStats();
void* p336 = last_address;
DEBUG_PRINT(sfree(p328););
printStats();
DEBUG_PRINT(sfree(p279););
printStats();
PRINT_POINTER(srealloc(p250,188););
printStats();
void* p337 = last_address;
PRINT_POINTER(scalloc(96,241););
printStats();
void* p338 = last_address;
PRINT_POINTER(srealloc(p269,101););
printStats();
void* p339 = last_address;
PRINT_POINTER(scalloc(14,199););
printStats();
void* p340 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p341 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p342 = last_address;
DEBUG_PRINT(sfree(p231););
printStats();
DEBUG_PRINT(sfree(p233););
printStats();
PRINT_POINTER(smalloc(203););
printStats();
void* p343 = last_address;
PRINT_POINTER(srealloc(p256,183););
printStats();
void* p344 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p345 = last_address;
PRINT_POINTER(scalloc(109,57););
printStats();
void* p346 = last_address;
PRINT_POINTER(scalloc(198,70););
printStats();
void* p347 = last_address;
PRINT_POINTER(scalloc(195,220););
printStats();
void* p348 = last_address;
PRINT_POINTER(srealloc(p340,49););
printStats();
void* p349 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p350 = last_address;
PRINT_POINTER(scalloc(57,192););
printStats();
void* p351 = last_address;
PRINT_POINTER(srealloc(p299,44););
printStats();
void* p352 = last_address;
DEBUG_PRINT(sfree(p270););
printStats();
PRINT_POINTER(srealloc(p308,172););
printStats();
void* p353 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p354 = last_address;
PRINT_POINTER(scalloc(221,170););
printStats();
void* p355 = last_address;
PRINT_POINTER(scalloc(141,77););
printStats();
void* p356 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
PRINT_POINTER(smalloc(44););
printStats();
void* p357 = last_address;
DEBUG_PRINT(sfree(p229););
printStats();
PRINT_POINTER(srealloc(p307,5););
printStats();
void* p358 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p359 = last_address;
DEBUG_PRINT(sfree(p161););
printStats();
PRINT_POINTER(srealloc(p353,212););
printStats();
void* p360 = last_address;
PRINT_POINTER(srealloc(p355,205););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p362 = last_address;
PRINT_POINTER(scalloc(201,179););
printStats();
void* p363 = last_address;
PRINT_POINTER(srealloc(p324,162););
printStats();
void* p364 = last_address;
PRINT_POINTER(srealloc(p150,223););
printStats();
void* p365 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p366 = last_address;
PRINT_POINTER(scalloc(222,70););
printStats();
void* p367 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p368 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p369 = last_address;
PRINT_POINTER(scalloc(20,140););
printStats();
void* p370 = last_address;
DEBUG_PRINT(sfree(p258););
printStats();
PRINT_POINTER(smalloc(163););
printStats();
void* p371 = last_address;
PRINT_POINTER(srealloc(p276,157););
printStats();
void* p372 = last_address;
PRINT_POINTER(srealloc(p253,182););
printStats();
void* p373 = last_address;
PRINT_POINTER(srealloc(p281,101););
printStats();
void* p374 = last_address;
PRINT_POINTER(scalloc(109,90););
printStats();
void* p375 = last_address;
PRINT_POINTER(srealloc(p212,153););
printStats();
void* p376 = last_address;
DEBUG_PRINT(sfree(p311););
printStats();
PRINT_POINTER(smalloc(230););
printStats();
void* p377 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p378 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p379 = last_address;
DEBUG_PRINT(sfree(p318););
printStats();
PRINT_POINTER(srealloc(p163,125););
printStats();
void* p380 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p381 = last_address;
PRINT_POINTER(srealloc(p302,119););
printStats();
void* p382 = last_address;
DEBUG_PRINT(sfree(p190););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p383 = last_address;
PRINT_POINTER(srealloc(p326,117););
printStats();
void* p384 = last_address;
PRINT_POINTER(srealloc(p375,120););
printStats();
void* p385 = last_address;
DEBUG_PRINT(sfree(p338););
printStats();
DEBUG_PRINT(sfree(p298););
printStats();
PRINT_POINTER(srealloc(p345,67););
printStats();
void* p386 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p387 = last_address;
PRINT_POINTER(scalloc(0,5););
printStats();
void* p388 = last_address;
PRINT_POINTER(scalloc(239,196););
printStats();
void* p389 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
PRINT_POINTER(srealloc(p82,93););
printStats();
void* p390 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p391 = last_address;
DEBUG_PRINT(sfree(p376););
printStats();
PRINT_POINTER(srealloc(p165,94););
printStats();
void* p392 = last_address;
PRINT_POINTER(srealloc(p391,134););
printStats();
void* p393 = last_address;
PRINT_POINTER(scalloc(132,175););
printStats();
void* p394 = last_address;
PRINT_POINTER(srealloc(p332,44););
printStats();
void* p395 = last_address;
PRINT_POINTER(srealloc(p175,98););
printStats();
void* p396 = last_address;
DEBUG_PRINT(sfree(p365););
printStats();
PRINT_POINTER(scalloc(199,14););
printStats();
void* p397 = last_address;
PRINT_POINTER(scalloc(226,181););
printStats();
void* p398 = last_address;
PRINT_POINTER(scalloc(70,146););
printStats();
void* p399 = last_address;
DEBUG_PRINT(sfree(p372););
printStats();
PRINT_POINTER(srealloc(p329,104););
printStats();
void* p400 = last_address;
DEBUG_PRINT(sfree(p354););
printStats();
PRINT_POINTER(smalloc(197););
printStats();
void* p401 = last_address;
PRINT_POINTER(srealloc(p271,131););
printStats();
void* p402 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p403 = last_address;
DEBUG_PRINT(sfree(p314););
printStats();
PRINT_POINTER(scalloc(167,91););
printStats();
void* p404 = last_address;
PRINT_POINTER(srealloc(p264,171););
printStats();
void* p405 = last_address;
PRINT_POINTER(scalloc(55,147););
printStats();
void* p406 = last_address;
DEBUG_PRINT(sfree(p209););
printStats();
DEBUG_PRINT(sfree(p305););
printStats();
DEBUG_PRINT(sfree(p285););
printStats();
PRINT_POINTER(smalloc(115););
printStats();
void* p407 = last_address;
PRINT_POINTER(scalloc(178,158););
printStats();
void* p408 = last_address;
DEBUG_PRINT(sfree(p216););
printStats();
PRINT_POINTER(scalloc(162,119););
printStats();
void* p409 = last_address;
PRINT_POINTER(srealloc(p268,194););
printStats();
void* p410 = last_address;
PRINT_POINTER(scalloc(65,70););
printStats();
void* p411 = last_address;
PRINT_POINTER(srealloc(p199,0););
printStats();
void* p412 = last_address;
PRINT_POINTER(srealloc(p145,227););
printStats();
void* p413 = last_address;
PRINT_POINTER(srealloc(p277,35););
printStats();
void* p414 = last_address;
PRINT_POINTER(srealloc(p330,241););
printStats();
void* p415 = last_address;
PRINT_POINTER(srealloc(p392,197););
printStats();
void* p416 = last_address;
PRINT_POINTER(srealloc(p131,68););
printStats();
void* p417 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p418 = last_address;
PRINT_POINTER(srealloc(p331,81););
printStats();
void* p419 = last_address;
PRINT_POINTER(srealloc(p243,91););
printStats();
void* p420 = last_address;
PRINT_POINTER(srealloc(p224,167););
printStats();
void* p421 = last_address;
PRINT_POINTER(scalloc(120,187););
printStats();
void* p422 = last_address;
PRINT_POINTER(scalloc(117,123););
printStats();
void* p423 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
PRINT_POINTER(smalloc(71););
printStats();
void* p424 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p425 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p426 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p427 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p428 = last_address;
DEBUG_PRINT(sfree(p382););
printStats();
PRINT_POINTER(smalloc(65););
printStats();
void* p429 = last_address;
PRINT_POINTER(srealloc(p278,49););
printStats();
void* p430 = last_address;
PRINT_POINTER(srealloc(p246,192););
printStats();
void* p431 = last_address;
PRINT_POINTER(scalloc(104,172););
printStats();
void* p432 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p433 = last_address;
PRINT_POINTER(srealloc(p397,19););
printStats();
void* p434 = last_address;
PRINT_POINTER(srealloc(p379,48););
printStats();
void* p435 = last_address;
PRINT_POINTER(scalloc(244,52););
printStats();
void* p436 = last_address;
DEBUG_PRINT(sfree(p435););
printStats();
PRINT_POINTER(smalloc(69););
printStats();
void* p437 = last_address;
PRINT_POINTER(srealloc(p420,62););
printStats();
void* p438 = last_address;
PRINT_POINTER(scalloc(246,181););
printStats();
void* p439 = last_address;
DEBUG_PRINT(sfree(p343););
printStats();
PRINT_POINTER(srealloc(p238,244););
printStats();
void* p440 = last_address;
PRINT_POINTER(srealloc(p236,205););
printStats();
void* p441 = last_address;
PRINT_POINTER(scalloc(11,10););
printStats();
void* p442 = last_address;
DEBUG_PRINT(sfree(p377););
printStats();
DEBUG_PRINT(sfree(p293););
printStats();
PRINT_POINTER(srealloc(p416,249););
printStats();
void* p443 = last_address;
PRINT_POINTER(srealloc(p367,111););
printStats();
void* p444 = last_address;
PRINT_POINTER(scalloc(177,199););
printStats();
void* p445 = last_address;
PRINT_POINTER(scalloc(128,54););
printStats();
void* p446 = last_address;
DEBUG_PRINT(sfree(p244););
printStats();
PRINT_POINTER(scalloc(130,25););
printStats();
void* p447 = last_address;
PRINT_POINTER(scalloc(240,76););
printStats();
void* p448 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p449 = last_address;
PRINT_POINTER(srealloc(p214,54););
printStats();
void* p450 = last_address;
PRINT_POINTER(srealloc(p336,1););
printStats();
void* p451 = last_address;
DEBUG_PRINT(sfree(p260););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p452 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p453 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p454 = last_address;
PRINT_POINTER(scalloc(152,109););
printStats();
void* p455 = last_address;
PRINT_POINTER(scalloc(99,183););
printStats();
void* p456 = last_address;
DEBUG_PRINT(sfree(p412););
printStats();
PRINT_POINTER(scalloc(70,51););
printStats();
void* p457 = last_address;
PRINT_POINTER(srealloc(p172,130););
printStats();
void* p458 = last_address;
DEBUG_PRINT(sfree(p327););
printStats();
PRINT_POINTER(srealloc(p408,37););
printStats();
void* p459 = last_address;
PRINT_POINTER(srealloc(p294,224););
printStats();
void* p460 = last_address;
PRINT_POINTER(scalloc(9,19););
printStats();
void* p461 = last_address;
PRINT_POINTER(scalloc(194,157););
printStats();
void* p462 = last_address;
PRINT_POINTER(scalloc(30,46););
printStats();
void* p463 = last_address;
DEBUG_PRINT(sfree(p245););
printStats();
PRINT_POINTER(smalloc(67););
printStats();
void* p464 = last_address;
PRINT_POINTER(scalloc(248,171););
printStats();
void* p465 = last_address;
DEBUG_PRINT(sfree(p347););
printStats();
PRINT_POINTER(smalloc(222););
printStats();
void* p466 = last_address;
PRINT_POINTER(srealloc(p457,75););
printStats();
void* p467 = last_address;
PRINT_POINTER(srealloc(p461,102););
printStats();
void* p468 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p469 = last_address;
DEBUG_PRINT(sfree(p344););
printStats();
DEBUG_PRINT(sfree(p371););
printStats();
DEBUG_PRINT(sfree(p348););
printStats();
PRINT_POINTER(smalloc(99););
printStats();
void* p470 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p471 = last_address;
DEBUG_PRINT(sfree(p310););
printStats();
PRINT_POINTER(scalloc(86,24););
printStats();
void* p472 = last_address;
PRINT_POINTER(scalloc(143,207););
printStats();
void* p473 = last_address;
PRINT_POINTER(scalloc(111,82););
printStats();
void* p474 = last_address;
DEBUG_PRINT(sfree(p438););
printStats();
DEBUG_PRINT(sfree(p378););
printStats();
PRINT_POINTER(scalloc(64,124););
printStats();
void* p475 = last_address;
PRINT_POINTER(srealloc(p361,132););
printStats();
void* p476 = last_address;
PRINT_POINTER(scalloc(101,133););
printStats();
void* p477 = last_address;
PRINT_POINTER(scalloc(209,1););
printStats();
void* p478 = last_address;
PRINT_POINTER(srealloc(p356,228););
printStats();
void* p479 = last_address;
PRINT_POINTER(scalloc(148,120););
printStats();
void* p480 = last_address;
DEBUG_PRINT(sfree(p366););
printStats();
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(scalloc(210,246););
printStats();
void* p481 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p482 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p483 = last_address;
PRINT_POINTER(scalloc(203,141););
printStats();
void* p484 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p485 = last_address;
PRINT_POINTER(srealloc(p235,168););
printStats();
void* p486 = last_address;
PRINT_POINTER(srealloc(p452,94););
printStats();
void* p487 = last_address;
PRINT_POINTER(srealloc(p459,221););
printStats();
void* p488 = last_address;
DEBUG_PRINT(sfree(p321););
printStats();
PRINT_POINTER(scalloc(230,115););
printStats();
void* p489 = last_address;
PRINT_POINTER(scalloc(30,183););
printStats();
void* p490 = last_address;
PRINT_POINTER(scalloc(196,95););
printStats();
void* p491 = last_address;
PRINT_POINTER(srealloc(p468,241););
printStats();
void* p492 = last_address;
PRINT_POINTER(srealloc(p446,73););
printStats();
void* p493 = last_address;
PRINT_POINTER(scalloc(53,155););
printStats();
void* p494 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p495 = last_address;
PRINT_POINTER(scalloc(228,161););
printStats();
void* p496 = last_address;
DEBUG_PRINT(sfree(p465););
printStats();
PRINT_POINTER(srealloc(p485,170););
printStats();
void* p497 = last_address;
PRINT_POINTER(srealloc(p464,4););
printStats();
void* p498 = last_address;
PRINT_POINTER(srealloc(p346,145););
printStats();
void* p499 = last_address;
PRINT_POINTER(srealloc(p297,166););
printStats();
void* p500 = last_address;
DEBUG_PRINT(sfree(p433););
printStats();
PRINT_POINTER(srealloc(p363,194););
printStats();
void* p501 = last_address;
PRINT_POINTER(srealloc(p380,167););
printStats();
void* p502 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p503 = last_address;
DEBUG_PRINT(sfree(p406););
printStats();
DEBUG_PRINT(sfree(p370););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p504 = last_address;
PRINT_POINTER(scalloc(246,98););
printStats();
void* p505 = last_address;
PRINT_POINTER(scalloc(154,131););
printStats();
void* p506 = last_address;
PRINT_POINTER(scalloc(201,195););
printStats();
void* p507 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p508 = last_address;
PRINT_POINTER(srealloc(p337,165););
printStats();
void* p509 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p510 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p511 = last_address;
PRINT_POINTER(scalloc(241,94););
printStats();
void* p512 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p513 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p514 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p515 = last_address;
PRINT_POINTER(srealloc(p130,43););
printStats();
void* p516 = last_address;
PRINT_POINTER(srealloc(p403,203););
printStats();
void* p517 = last_address;
DEBUG_PRINT(sfree(p493););
printStats();
PRINT_POINTER(srealloc(p351,227););
printStats();
void* p518 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p519 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p520 = last_address;
PRINT_POINTER(srealloc(p442,37););
printStats();
void* p521 = last_address;
DEBUG_PRINT(sfree(p396););
printStats();
PRINT_POINTER(scalloc(235,212););
printStats();
void* p522 = last_address;
PRINT_POINTER(scalloc(59,241););
printStats();
void* p523 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p524 = last_address;
PRINT_POINTER(scalloc(123,49););
printStats();
void* p525 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p526 = last_address;
DEBUG_PRINT(sfree(p498););
printStats();
DEBUG_PRINT(sfree(p445););
printStats();
PRINT_POINTER(srealloc(p262,195););
printStats();
void* p527 = last_address;
PRINT_POINTER(scalloc(200,119););
printStats();
void* p528 = last_address;
DEBUG_PRINT(sfree(p316););
printStats();
PRINT_POINTER(srealloc(p263,195););
printStats();
void* p529 = last_address;
PRINT_POINTER(scalloc(155,221););
printStats();
void* p530 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p531 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
PRINT_POINTER(srealloc(p303,194););
printStats();
void* p532 = last_address;
PRINT_POINTER(scalloc(119,142););
printStats();
void* p533 = last_address;
PRINT_POINTER(scalloc(152,25););
printStats();
void* p534 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p535 = last_address;
PRINT_POINTER(srealloc(p419,85););
printStats();
void* p536 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p537 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p538 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p539 = last_address;
PRINT_POINTER(srealloc(p424,17););
printStats();
void* p540 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p541 = last_address;
DEBUG_PRINT(sfree(p426););
printStats();
DEBUG_PRINT(sfree(p471););
printStats();
PRINT_POINTER(srealloc(p295,136););
printStats();
void* p542 = last_address;
PRINT_POINTER(srealloc(p467,37););
printStats();
void* p543 = last_address;
PRINT_POINTER(srealloc(p512,32););
printStats();
void* p544 = last_address;
PRINT_POINTER(srealloc(p341,29););
printStats();
void* p545 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p546 = last_address;
PRINT_POINTER(srealloc(p387,20););
printStats();
void* p547 = last_address;
PRINT_POINTER(srealloc(p423,91););
printStats();
void* p548 = last_address;
PRINT_POINTER(srealloc(p513,5););
printStats();
void* p549 = last_address;
PRINT_POINTER(scalloc(213,138););
printStats();
void* p550 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p551 = last_address;
PRINT_POINTER(srealloc(p523,157););
printStats();
void* p552 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p553 = last_address;
DEBUG_PRINT(sfree(p441););
printStats();
DEBUG_PRINT(sfree(p400););
printStats();
DEBUG_PRINT(sfree(p522););
printStats();
PRINT_POINTER(smalloc(119););
printStats();
void* p554 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p555 = last_address;
PRINT_POINTER(scalloc(198,199););
printStats();
void* p556 = last_address;
PRINT_POINTER(scalloc(21,94););
printStats();
void* p557 = last_address;
DEBUG_PRINT(sfree(p437););
printStats();
PRINT_POINTER(smalloc(5););
printStats();
void* p558 = last_address;
PRINT_POINTER(srealloc(p554,200););
printStats();
void* p559 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p560 = last_address;
DEBUG_PRINT(sfree(p211););
printStats();
DEBUG_PRINT(sfree(p460););
printStats();
PRINT_POINTER(smalloc(70););
printStats();
void* p561 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p562 = last_address;
PRINT_POINTER(srealloc(p350,220););
printStats();
void* p563 = last_address;
PRINT_POINTER(srealloc(p556,37););
printStats();
void* p564 = last_address;
DEBUG_PRINT(sfree(p368););
printStats();
DEBUG_PRINT(sfree(p456););
printStats();
DEBUG_PRINT(sfree(p487););
printStats();
PRINT_POINTER(srealloc(p215,20););
printStats();
void* p565 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p566 = last_address;
PRINT_POINTER(srealloc(p415,110););
printStats();
void* p567 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p568 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p569 = last_address;
DEBUG_PRINT(sfree(p381););
printStats();
PRINT_POINTER(smalloc(194););
printStats();
void* p570 = last_address;
PRINT_POINTER(scalloc(234,223););
printStats();
void* p571 = last_address;
PRINT_POINTER(srealloc(p422,172););
printStats();
void* p572 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p573 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p574 = last_address;
DEBUG_PRINT(sfree(p404););
printStats();
PRINT_POINTER(scalloc(194,173););
printStats();
void* p575 = last_address;
PRINT_POINTER(scalloc(236,123););
printStats();
void* p576 = last_address;
PRINT_POINTER(scalloc(189,244););
printStats();
void* p577 = last_address;
DEBUG_PRINT(sfree(p542););
printStats();
PRINT_POINTER(srealloc(p559,142););
printStats();
void* p578 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p579 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p580 = last_address;
DEBUG_PRINT(sfree(p516););
printStats();
PRINT_POINTER(smalloc(13););
printStats();
void* p581 = last_address;
DEBUG_PRINT(sfree(p572););
printStats();
PRINT_POINTER(srealloc(p339,62););
printStats();
void* p582 = last_address;
DEBUG_PRINT(sfree(p575););
printStats();
DEBUG_PRINT(sfree(p570););
printStats();
PRINT_POINTER(smalloc(191););
printStats();
void* p583 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p584 = last_address;
PRINT_POINTER(scalloc(37,136););
printStats();
void* p585 = last_address;
PRINT_POINTER(srealloc(p410,208););
printStats();
void* p586 = last_address;
PRINT_POINTER(scalloc(199,124););
printStats();
void* p587 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p588 = last_address;
DEBUG_PRINT(sfree(p545););
printStats();
PRINT_POINTER(srealloc(p383,12););
printStats();
void* p589 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p590 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p591 = last_address;
PRINT_POINTER(scalloc(201,185););
printStats();
void* p592 = last_address;
DEBUG_PRINT(sfree(p536););
printStats();
PRINT_POINTER(smalloc(113););
printStats();
void* p593 = last_address;
DEBUG_PRINT(sfree(p320););
printStats();
DEBUG_PRINT(sfree(p532););
printStats();
DEBUG_PRINT(sfree(p561););
printStats();
PRINT_POINTER(scalloc(178,177););
printStats();
void* p594 = last_address;
PRINT_POINTER(srealloc(p454,151););
printStats();
void* p595 = last_address;
DEBUG_PRINT(sfree(p520););
printStats();
PRINT_POINTER(scalloc(118,209););
printStats();
void* p596 = last_address;
PRINT_POINTER(scalloc(106,109););
printStats();
void* p597 = last_address;
PRINT_POINTER(scalloc(179,191););
printStats();
void* p598 = last_address;
DEBUG_PRINT(sfree(p443););
printStats();
PRINT_POINTER(srealloc(p546,196););
printStats();
void* p599 = last_address;
PRINT_POINTER(srealloc(p448,178););
printStats();
void* p600 = last_address;
DEBUG_PRINT(sfree(p257););
printStats();
PRINT_POINTER(scalloc(139,159););
printStats();
void* p601 = last_address;
PRINT_POINTER(srealloc(p436,141););
printStats();
void* p602 = last_address;
DEBUG_PRINT(sfree(p421););
printStats();
DEBUG_PRINT(sfree(p490););
printStats();
PRINT_POINTER(scalloc(144,22););
printStats();
void* p603 = last_address;
PRINT_POINTER(scalloc(150,12););
printStats();
void* p604 = last_address;
PRINT_POINTER(scalloc(226,138););
printStats();
void* p605 = last_address;
PRINT_POINTER(scalloc(200,38););
printStats();
void* p606 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p607 = last_address;
DEBUG_PRINT(sfree(p430););
printStats();
PRINT_POINTER(smalloc(20););
printStats();
void* p608 = last_address;
PRINT_POINTER(srealloc(p369,75););
printStats();
void* p609 = last_address;
DEBUG_PRINT(sfree(p475););
printStats();
PRINT_POINTER(srealloc(p486,31););
printStats();
void* p610 = last_address;
PRINT_POINTER(srealloc(p569,116););
printStats();
void* p611 = last_address;
PRINT_POINTER(srealloc(p494,27););
printStats();
void* p612 = last_address;
PRINT_POINTER(scalloc(46,94););
printStats();
void* p613 = last_address;
PRINT_POINTER(scalloc(76,46););
printStats();
void* p614 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p615 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p616 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p617 = last_address;
PRINT_POINTER(scalloc(55,119););
printStats();
void* p618 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p619 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p620 = last_address;
DEBUG_PRINT(sfree(p533););
printStats();
PRINT_POINTER(srealloc(p389,109););
printStats();
void* p621 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p622 = last_address;
DEBUG_PRINT(sfree(p491););
printStats();
PRINT_POINTER(scalloc(131,109););
printStats();
void* p623 = last_address;
DEBUG_PRINT(sfree(p585););
printStats();
PRINT_POINTER(srealloc(p584,223););
printStats();
void* p624 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p625 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p626 = last_address;
DEBUG_PRINT(sfree(p618););
printStats();
PRINT_POINTER(smalloc(200););
printStats();
void* p627 = last_address;
DEBUG_PRINT(sfree(p579););
printStats();
PRINT_POINTER(smalloc(67););
printStats();
void* p628 = last_address;
PRINT_POINTER(srealloc(p453,10););
printStats();
void* p629 = last_address;
PRINT_POINTER(scalloc(96,170););
printStats();
void* p630 = last_address;
PRINT_POINTER(scalloc(147,239););
printStats();
void* p631 = last_address;
DEBUG_PRINT(sfree(p388););
printStats();
PRINT_POINTER(srealloc(p432,172););
printStats();
void* p632 = last_address;
PRINT_POINTER(scalloc(160,15););
printStats();
void* p633 = last_address;
PRINT_POINTER(scalloc(212,145););
printStats();
void* p634 = last_address;
PRINT_POINTER(scalloc(146,57););
printStats();
void* p635 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p636 = last_address;
PRINT_POINTER(scalloc(229,168););
printStats();
void* p637 = last_address;
PRINT_POINTER(srealloc(p482,162););
printStats();
void* p638 = last_address;
PRINT_POINTER(scalloc(79,148););
printStats();
void* p639 = last_address;
DEBUG_PRINT(sfree(p248););
printStats();
PRINT_POINTER(scalloc(1,114););
printStats();
void* p640 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p641 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p642 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p643 = last_address;
PRINT_POINTER(scalloc(183,55););
printStats();
void* p644 = last_address;
PRINT_POINTER(srealloc(p480,185););
printStats();
void* p645 = last_address;
PRINT_POINTER(scalloc(232,166););
printStats();
void* p646 = last_address;
DEBUG_PRINT(sfree(p254););
printStats();
PRINT_POINTER(smalloc(205););
printStats();
void* p647 = last_address;
PRINT_POINTER(scalloc(28,191););
printStats();
void* p648 = last_address;
DEBUG_PRINT(sfree(p623););
printStats();
PRINT_POINTER(srealloc(p431,217););
printStats();
void* p649 = last_address;
PRINT_POINTER(scalloc(181,215););
printStats();
void* p650 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p651 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p652 = last_address;
PRINT_POINTER(srealloc(p473,45););
printStats();
void* p653 = last_address;
PRINT_POINTER(srealloc(p352,222););
printStats();
void* p654 = last_address;
PRINT_POINTER(srealloc(p534,173););
printStats();
void* p655 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p656 = last_address;
PRINT_POINTER(srealloc(p374,105););
printStats();
void* p657 = last_address;
PRINT_POINTER(srealloc(p596,191););
printStats();
void* p658 = last_address;
DEBUG_PRINT(sfree(p576););
printStats();
PRINT_POINTER(srealloc(p472,91););
printStats();
void* p659 = last_address;
PRINT_POINTER(scalloc(85,101););
printStats();
void* p660 = last_address;
DEBUG_PRINT(sfree(p511););
printStats();
DEBUG_PRINT(sfree(p132););
printStats();
PRINT_POINTER(scalloc(105,61););
printStats();
void* p661 = last_address;
PRINT_POINTER(srealloc(p564,53););
printStats();
void* p662 = last_address;
PRINT_POINTER(scalloc(170,103););
printStats();
void* p663 = last_address;
DEBUG_PRINT(sfree(p649););
printStats();
PRINT_POINTER(srealloc(p552,17););
printStats();
void* p664 = last_address;
DEBUG_PRINT(sfree(p555););
printStats();
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(scalloc(193,247););
printStats();
void* p665 = last_address;
PRINT_POINTER(smalloc(80););
printStats();
void* p666 = last_address;
PRINT_POINTER(scalloc(122,128););
printStats();
void* p667 = last_address;
PRINT_POINTER(scalloc(234,209););
printStats();
void* p668 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p669 = last_address;
PRINT_POINTER(scalloc(203,131););
printStats();
void* p670 = last_address;
PRINT_POINTER(scalloc(147,14););
printStats();
void* p671 = last_address;
DEBUG_PRINT(sfree(p558););
printStats();
PRINT_POINTER(smalloc(86););
printStats();
void* p672 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p673 = last_address;
DEBUG_PRINT(sfree(p607););
printStats();
DEBUG_PRINT(sfree(p619););
printStats();
PRINT_POINTER(scalloc(158,189););
printStats();
void* p674 = last_address;
PRINT_POINTER(srealloc(p594,2););
printStats();
void* p675 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p676 = last_address;
PRINT_POINTER(scalloc(25,187););
printStats();
void* p677 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p678 = last_address;
DEBUG_PRINT(sfree(p489););
printStats();
DEBUG_PRINT(sfree(p385););
printStats();
PRINT_POINTER(srealloc(p539,233););
printStats();
void* p679 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p680 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p681 = last_address;
DEBUG_PRINT(sfree(p553););
printStats();
PRINT_POINTER(smalloc(106););
printStats();
void* p682 = last_address;
DEBUG_PRINT(sfree(p621););
printStats();
PRINT_POINTER(scalloc(192,168););
printStats();
void* p683 = last_address;
PRINT_POINTER(srealloc(p255,76););
printStats();
void* p684 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p685 = last_address;
PRINT_POINTER(srealloc(p514,177););
printStats();
void* p686 = last_address;
PRINT_POINTER(srealloc(p273,122););
printStats();
void* p687 = last_address;
PRINT_POINTER(scalloc(200,117););
printStats();
void* p688 = last_address;
PRINT_POINTER(scalloc(245,53););
printStats();
void* p689 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p690 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p691 = last_address;
PRINT_POINTER(srealloc(p574,108););
printStats();
void* p692 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p693 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p694 = last_address;
PRINT_POINTER(srealloc(p306,129););
printStats();
void* p695 = last_address;
PRINT_POINTER(srealloc(p690,130););
printStats();
void* p696 = last_address;
PRINT_POINTER(scalloc(203,14););
printStats();
void* p697 = last_address;
DEBUG_PRINT(sfree(p547););
printStats();
DEBUG_PRINT(sfree(p309););
printStats();
PRINT_POINTER(smalloc(134););
printStats();
void* p698 = last_address;
PRINT_POINTER(srealloc(p627,53););
printStats();
void* p699 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p700 = last_address;
DEBUG_PRINT(sfree(p531););
printStats();
PRINT_POINTER(srealloc(p586,21););
printStats();
void* p701 = last_address;
PRINT_POINTER(srealloc(p651,5););
printStats();
void* p702 = last_address;
PRINT_POINTER(scalloc(218,211););
printStats();
void* p703 = last_address;
DEBUG_PRINT(sfree(p587););
printStats();
PRINT_POINTER(srealloc(p201,107););
printStats();
void* p704 = last_address;
PRINT_POINTER(srealloc(p650,83););
printStats();
void* p705 = last_address;
PRINT_POINTER(scalloc(27,131););
printStats();
void* p706 = last_address;
DEBUG_PRINT(sfree(p538););
printStats();
PRINT_POINTER(srealloc(p508,35););
printStats();
void* p707 = last_address;
PRINT_POINTER(srealloc(p407,222););
printStats();
void* p708 = last_address;
PRINT_POINTER(srealloc(p179,167););
printStats();
void* p709 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p710 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p711 = last_address;
DEBUG_PRINT(sfree(p612););
printStats();
PRINT_POINTER(scalloc(183,83););
printStats();
void* p712 = last_address;
PRINT_POINTER(scalloc(46,229););
printStats();
void* p713 = last_address;
PRINT_POINTER(srealloc(p507,105););
printStats();
void* p714 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p715 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p716 = last_address;
DEBUG_PRINT(sfree(p658););
printStats();
DEBUG_PRINT(sfree(p517););
printStats();
PRINT_POINTER(srealloc(p470,216););
printStats();
void* p717 = last_address;
PRINT_POINTER(srealloc(p529,32););
printStats();
void* p718 = last_address;
DEBUG_PRINT(sfree(p613););
printStats();
PRINT_POINTER(smalloc(205););
printStats();
void* p719 = last_address;
PRINT_POINTER(scalloc(124,199););
printStats();
void* p720 = last_address;
DEBUG_PRINT(sfree(p315););
printStats();
PRINT_POINTER(srealloc(p401,225););
printStats();
void* p721 = last_address;
PRINT_POINTER(srealloc(p667,52););
printStats();
void* p722 = last_address;
PRINT_POINTER(srealloc(p595,44););
printStats();
void* p723 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p724 = last_address;
PRINT_POINTER(scalloc(18,192););
printStats();
void* p725 = last_address;
DEBUG_PRINT(sfree(p395););
printStats();
DEBUG_PRINT(sfree(p342););
printStats();
PRINT_POINTER(scalloc(176,20););
printStats();
void* p726 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p727 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p728 = last_address;
PRINT_POINTER(scalloc(178,10););
printStats();
void* p729 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p730 = last_address;
DEBUG_PRINT(sfree(p632););
printStats();
PRINT_POINTER(scalloc(8,131););
printStats();
void* p731 = last_address;
DEBUG_PRINT(sfree(p726););
printStats();
PRINT_POINTER(smalloc(46););
printStats();
void* p732 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p733 = last_address;
PRINT_POINTER(srealloc(p653,172););
printStats();
void* p734 = last_address;
PRINT_POINTER(srealloc(p641,191););
printStats();
void* p735 = last_address;
DEBUG_PRINT(sfree(p515););
printStats();
PRINT_POINTER(srealloc(p540,100););
printStats();
void* p736 = last_address;
PRINT_POINTER(scalloc(23,248););
printStats();
void* p737 = last_address;
PRINT_POINTER(srealloc(p462,220););
printStats();
void* p738 = last_address;
DEBUG_PRINT(sfree(p488););
printStats();
PRINT_POINTER(scalloc(173,109););
printStats();
void* p739 = last_address;
DEBUG_PRINT(sfree(p402););
printStats();
PRINT_POINTER(smalloc(21););
printStats();
void* p740 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p741 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p742 = last_address;
PRINT_POINTER(srealloc(p720,79););
printStats();
void* p743 = last_address;
DEBUG_PRINT(sfree(p524););
printStats();
PRINT_POINTER(scalloc(57,82););
printStats();
void* p744 = last_address;
DEBUG_PRINT(sfree(p674););
printStats();
DEBUG_PRINT(sfree(p664););
printStats();
PRINT_POINTER(scalloc(207,116););
printStats();
void* p745 = last_address;
PRINT_POINTER(scalloc(72,10););
printStats();
void* p746 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p747 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p748 = last_address;
DEBUG_PRINT(sfree(p660););
printStats();
PRINT_POINTER(smalloc(74););
printStats();
void* p749 = last_address;
PRINT_POINTER(srealloc(p616,149););
printStats();
void* p750 = last_address;
PRINT_POINTER(srealloc(p678,148););
printStats();
void* p751 = last_address;
PRINT_POINTER(scalloc(127,175););
printStats();
void* p752 = last_address;
PRINT_POINTER(scalloc(248,44););
printStats();
void* p753 = last_address;
PRINT_POINTER(srealloc(p360,1););
printStats();
void* p754 = last_address;
PRINT_POINTER(srealloc(p754,137););
printStats();
void* p755 = last_address;
PRINT_POINTER(srealloc(p753,5););
printStats();
void* p756 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p757 = last_address;
DEBUG_PRINT(sfree(p701););
printStats();
DEBUG_PRINT(sfree(p455););
printStats();
PRINT_POINTER(srealloc(p317,102););
printStats();
void* p758 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p759 = last_address;
DEBUG_PRINT(sfree(p267););
printStats();
PRINT_POINTER(srealloc(p672,182););
printStats();
void* p760 = last_address;
PRINT_POINTER(scalloc(1,71););
printStats();
void* p761 = last_address;
PRINT_POINTER(scalloc(227,32););
printStats();
void* p762 = last_address;
DEBUG_PRINT(sfree(p525););
printStats();
PRINT_POINTER(smalloc(97););
printStats();
void* p763 = last_address;
DEBUG_PRINT(sfree(p620););
printStats();
PRINT_POINTER(srealloc(p501,87););
printStats();
void* p764 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p765 = last_address;
PRINT_POINTER(scalloc(153,215););
printStats();
void* p766 = last_address;
DEBUG_PRINT(sfree(p704););
printStats();
PRINT_POINTER(srealloc(p563,202););
printStats();
void* p767 = last_address;
PRINT_POINTER(scalloc(73,120););
printStats();
void* p768 = last_address;
PRINT_POINTER(scalloc(89,150););
printStats();
void* p769 = last_address;
PRINT_POINTER(scalloc(80,205););
printStats();
void* p770 = last_address;
PRINT_POINTER(srealloc(p635,80););
printStats();
void* p771 = last_address;
PRINT_POINTER(srealloc(p390,248););
printStats();
void* p772 = last_address;
PRINT_POINTER(srealloc(p601,170););
printStats();
void* p773 = last_address;
PRINT_POINTER(srealloc(p518,244););
printStats();
void* p774 = last_address;
PRINT_POINTER(srealloc(p411,164););
printStats();
void* p775 = last_address;
PRINT_POINTER(srealloc(p697,192););
printStats();
void* p776 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p777 = last_address;
DEBUG_PRINT(sfree(p662););
printStats();
PRINT_POINTER(scalloc(227,143););
printStats();
void* p778 = last_address;
PRINT_POINTER(scalloc(209,123););
printStats();
void* p779 = last_address;
DEBUG_PRINT(sfree(p712););
printStats();
DEBUG_PRINT(sfree(p611););
printStats();
PRINT_POINTER(smalloc(179););
printStats();
void* p780 = last_address;
PRINT_POINTER(srealloc(p728,184););
printStats();
void* p781 = last_address;
PRINT_POINTER(scalloc(41,154););
printStats();
void* p782 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p783 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p784 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p785 = last_address;
DEBUG_PRINT(sfree(p429););
printStats();
DEBUG_PRINT(sfree(p719););
printStats();
PRINT_POINTER(srealloc(p740,97););
printStats();
void* p786 = last_address;
PRINT_POINTER(scalloc(228,4););
printStats();
void* p787 = last_address;
PRINT_POINTER(scalloc(103,8););
printStats();
void* p788 = last_address;
PRINT_POINTER(srealloc(p434,52););
printStats();
void* p789 = last_address;
PRINT_POINTER(scalloc(231,205););
printStats();
void* p790 = last_address;
DEBUG_PRINT(sfree(p727););
printStats();
DEBUG_PRINT(sfree(p624););
printStats();
DEBUG_PRINT(sfree(p747););
printStats();
PRINT_POINTER(smalloc(151););
printStats();
void* p791 = last_address;
PRINT_POINTER(scalloc(166,136););
printStats();
void* p792 = last_address;
PRINT_POINTER(srealloc(p444,207););
printStats();
void* p793 = last_address;
PRINT_POINTER(srealloc(p661,169););
printStats();
void* p794 = last_address;
PRINT_POINTER(srealloc(p478,29););
printStats();
void* p795 = last_address;
DEBUG_PRINT(sfree(p357););
printStats();
PRINT_POINTER(srealloc(p741,160););
printStats();
void* p796 = last_address;
PRINT_POINTER(srealloc(p557,113););
printStats();
void* p797 = last_address;
PRINT_POINTER(srealloc(p622,237););
printStats();
void* p798 = last_address;
DEBUG_PRINT(sfree(p449););
printStats();
PRINT_POINTER(scalloc(65,14););
printStats();
void* p799 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p800 = last_address;
DEBUG_PRINT(sfree(p780););
printStats();
PRINT_POINTER(scalloc(57,239););
printStats();
void* p801 = last_address;
DEBUG_PRINT(sfree(p583););
printStats();
PRINT_POINTER(srealloc(p384,145););
printStats();
void* p802 = last_address;
PRINT_POINTER(scalloc(16,120););
printStats();
void* p803 = last_address;
PRINT_POINTER(srealloc(p528,201););
printStats();
void* p804 = last_address;
DEBUG_PRINT(sfree(p725););
printStats();
PRINT_POINTER(smalloc(4););
printStats();
void* p805 = last_address;
DEBUG_PRINT(sfree(p560););
printStats();
PRINT_POINTER(srealloc(p742,19););
printStats();
void* p806 = last_address;
DEBUG_PRINT(sfree(p721););
printStats();
PRINT_POINTER(srealloc(p578,217););
printStats();
void* p807 = last_address;
PRINT_POINTER(srealloc(p709,122););
printStats();
void* p808 = last_address;
DEBUG_PRINT(sfree(p716););
printStats();
PRINT_POINTER(scalloc(177,180););
printStats();
void* p809 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p810 = last_address;
PRINT_POINTER(scalloc(34,108););
printStats();
void* p811 = last_address;
PRINT_POINTER(srealloc(p450,115););
printStats();
void* p812 = last_address;
DEBUG_PRINT(sfree(p608););
printStats();
PRINT_POINTER(srealloc(p590,106););
printStats();
void* p813 = last_address;
PRINT_POINTER(srealloc(p812,16););
printStats();
void* p814 = last_address;
DEBUG_PRINT(sfree(p706););
printStats();
PRINT_POINTER(scalloc(159,37););
printStats();
void* p815 = last_address;
DEBUG_PRINT(sfree(p405););
printStats();
PRINT_POINTER(srealloc(p447,58););
printStats();
void* p816 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p817 = last_address;
PRINT_POINTER(srealloc(p647,209););
printStats();
void* p818 = last_address;
DEBUG_PRINT(sfree(p373););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p819 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p820 = last_address;
PRINT_POINTER(srealloc(p788,193););
printStats();
void* p821 = last_address;
PRINT_POINTER(srealloc(p699,248););
printStats();
void* p822 = last_address;
PRINT_POINTER(scalloc(15,246););
printStats();
void* p823 = last_address;
PRINT_POINTER(scalloc(8,172););
printStats();
void* p824 = last_address;
PRINT_POINTER(scalloc(36,11););
printStats();
void* p825 = last_address;
DEBUG_PRINT(sfree(p333););
printStats();
PRINT_POINTER(srealloc(p440,189););
printStats();
void* p826 = last_address;
PRINT_POINTER(srealloc(p822,50););
printStats();
void* p827 = last_address;
PRINT_POINTER(srealloc(p683,221););
printStats();
void* p828 = last_address;
PRINT_POINTER(scalloc(142,153););
printStats();
void* p829 = last_address;
PRINT_POINTER(scalloc(69,232););
printStats();
void* p830 = last_address;
DEBUG_PRINT(sfree(p656););
printStats();
PRINT_POINTER(smalloc(194););
printStats();
void* p831 = last_address;
PRINT_POINTER(srealloc(p210,133););
printStats();
void* p832 = last_address;
DEBUG_PRINT(sfree(p777););
printStats();
PRINT_POINTER(srealloc(p481,197););
printStats();
void* p833 = last_address;
DEBUG_PRINT(sfree(p811););
printStats();
PRINT_POINTER(smalloc(85););
printStats();
void* p834 = last_address;
DEBUG_PRINT(sfree(p417););
printStats();
PRINT_POINTER(smalloc(143););
printStats();
void* p835 = last_address;
PRINT_POINTER(scalloc(108,213););
printStats();
void* p836 = last_address;
PRINT_POINTER(srealloc(p738,11););
printStats();
void* p837 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p838 = last_address;
PRINT_POINTER(srealloc(p762,111););
printStats();
void* p839 = last_address;
PRINT_POINTER(srealloc(p483,26););
printStats();
void* p840 = last_address;
DEBUG_PRINT(sfree(p825););
printStats();
DEBUG_PRINT(sfree(p551););
printStats();
PRINT_POINTER(smalloc(11););
printStats();
void* p841 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p842 = last_address;
DEBUG_PRINT(sfree(p364););
printStats();
DEBUG_PRINT(sfree(p638););
printStats();
PRINT_POINTER(srealloc(p729,184););
printStats();
void* p843 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p844 = last_address;
PRINT_POINTER(scalloc(60,175););
printStats();
void* p845 = last_address;
PRINT_POINTER(scalloc(91,156););
printStats();
void* p846 = last_address;
PRINT_POINTER(scalloc(25,146););
printStats();
void* p847 = last_address;
DEBUG_PRINT(sfree(p790););
printStats();
PRINT_POINTER(scalloc(18,49););
printStats();
void* p848 = last_address;
PRINT_POINTER(scalloc(155,218););
printStats();
void* p849 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p850 = last_address;
PRINT_POINTER(scalloc(131,218););
printStats();
void* p851 = last_address;
DEBUG_PRINT(sfree(p693););
printStats();
PRINT_POINTER(scalloc(121,192););
printStats();
void* p852 = last_address;
DEBUG_PRINT(sfree(p565););
printStats();
PRINT_POINTER(scalloc(107,248););
printStats();
void* p853 = last_address;
PRINT_POINTER(scalloc(239,237););
printStats();
void* p854 = last_address;
PRINT_POINTER(scalloc(115,159););
printStats();
void* p855 = last_address;
PRINT_POINTER(srealloc(p598,138););
printStats();
void* p856 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p857 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p858 = last_address;
PRINT_POINTER(srealloc(p824,222););
printStats();
void* p859 = last_address;
PRINT_POINTER(scalloc(198,217););
printStats();
void* p860 = last_address;
PRINT_POINTER(srealloc(p698,200););
printStats();
void* p861 = last_address;
PRINT_POINTER(scalloc(156,65););
printStats();
void* p862 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p863 = last_address;
DEBUG_PRINT(sfree(p821););
printStats();
PRINT_POINTER(srealloc(p815,71););
printStats();
void* p864 = last_address;
PRINT_POINTER(srealloc(p804,35););
printStats();
void* p865 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p866 = last_address;
DEBUG_PRINT(sfree(p492););
printStats();
PRINT_POINTER(smalloc(126););
printStats();
void* p867 = last_address;
DEBUG_PRINT(sfree(p802););
printStats();
PRINT_POINTER(scalloc(54,226););
printStats();
void* p868 = last_address;
PRINT_POINTER(scalloc(164,151););
printStats();
void* p869 = last_address;
DEBUG_PRINT(sfree(p711););
printStats();
PRINT_POINTER(scalloc(107,208););
printStats();
void* p870 = last_address;
PRINT_POINTER(scalloc(136,176););
printStats();
void* p871 = last_address;
PRINT_POINTER(scalloc(53,74););
printStats();
void* p872 = last_address;
PRINT_POINTER(scalloc(161,114););
printStats();
void* p873 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p874 = last_address;
PRINT_POINTER(scalloc(133,107););
printStats();
void* p875 = last_address;
PRINT_POINTER(srealloc(p799,160););
printStats();
void* p876 = last_address;
PRINT_POINTER(scalloc(158,158););
printStats();
void* p877 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p878 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p879 = last_address;
PRINT_POINTER(scalloc(89,216););
printStats();
void* p880 = last_address;
PRINT_POINTER(scalloc(67,244););
printStats();
void* p881 = last_address;
DEBUG_PRINT(sfree(p640););
printStats();
DEBUG_PRINT(sfree(p784););
printStats();
PRINT_POINTER(scalloc(148,102););
printStats();
void* p882 = last_address;
DEBUG_PRINT(sfree(p806););
printStats();
DEBUG_PRINT(sfree(p801););
printStats();
DEBUG_PRINT(sfree(p671););
printStats();
DEBUG_PRINT(sfree(p259););
printStats();
DEBUG_PRINT(sfree(p637););
printStats();
DEBUG_PRINT(sfree(p477););
printStats();
DEBUG_PRINT(sfree(p562););
printStats();
PRINT_POINTER(smalloc(208););
printStats();
void* p883 = last_address;
DEBUG_PRINT(sfree(p800););
printStats();
DEBUG_PRINT(sfree(p722););
printStats();
DEBUG_PRINT(sfree(p860););
printStats();
DEBUG_PRINT(sfree(p673););
printStats();
DEBUG_PRINT(sfree(p642););
printStats();
PRINT_POINTER(scalloc(8,238););
printStats();
void* p884 = last_address;
PRINT_POINTER(srealloc(p836,21););
printStats();
void* p885 = last_address;
DEBUG_PRINT(sfree(p631););
printStats();
PRINT_POINTER(srealloc(p758,194););
printStats();
void* p886 = last_address;
DEBUG_PRINT(sfree(p544););
printStats();
PRINT_POINTER(smalloc(58););
printStats();
void* p887 = last_address;
DEBUG_PRINT(sfree(p736););
printStats();
DEBUG_PRINT(sfree(p886););
printStats();
PRINT_POINTER(scalloc(106,184););
printStats();
void* p888 = last_address;
DEBUG_PRINT(sfree(p730););
printStats();
PRINT_POINTER(smalloc(240););
printStats();
void* p889 = last_address;
PRINT_POINTER(srealloc(p322,148););
printStats();
void* p890 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p891 = last_address;
PRINT_POINTER(scalloc(192,121););
printStats();
void* p892 = last_address;
DEBUG_PRINT(sfree(p810););
printStats();
PRINT_POINTER(smalloc(83););
printStats();
void* p893 = last_address;
PRINT_POINTER(srealloc(p830,54););
printStats();
void* p894 = last_address;
PRINT_POINTER(scalloc(129,137););
printStats();
void* p895 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p896 = last_address;
PRINT_POINTER(srealloc(p769,76););
printStats();
void* p897 = last_address;
DEBUG_PRINT(sfree(p639););
printStats();
DEBUG_PRINT(sfree(p682););
printStats();
PRINT_POINTER(srealloc(p882,185););
printStats();
void* p898 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p899 = last_address;
PRINT_POINTER(scalloc(217,143););
printStats();
void* p900 = last_address;
DEBUG_PRINT(sfree(p828););
printStats();
PRINT_POINTER(srealloc(p805,87););
printStats();
void* p901 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p902 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p903 = last_address;
DEBUG_PRINT(sfree(p549););
printStats();
PRINT_POINTER(scalloc(52,35););
printStats();
void* p904 = last_address;
DEBUG_PRINT(sfree(p548););
printStats();
PRINT_POINTER(scalloc(120,38););
printStats();
void* p905 = last_address;
PRINT_POINTER(scalloc(221,187););
printStats();
void* p906 = last_address;
PRINT_POINTER(srealloc(p782,9););
printStats();
void* p907 = last_address;
DEBUG_PRINT(sfree(p484););
printStats();
PRINT_POINTER(srealloc(p550,132););
printStats();
void* p908 = last_address;
PRINT_POINTER(srealloc(p875,167););
printStats();
void* p909 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p910 = last_address;
PRINT_POINTER(srealloc(p850,209););
printStats();
void* p911 = last_address;
PRINT_POINTER(srealloc(p849,192););
printStats();
void* p912 = last_address;
PRINT_POINTER(scalloc(203,43););
printStats();
void* p913 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p914 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p915 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p916 = last_address;
DEBUG_PRINT(sfree(p896););
printStats();
PRINT_POINTER(scalloc(105,171););
printStats();
void* p917 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p918 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p919 = last_address;
PRINT_POINTER(scalloc(242,51););
printStats();
void* p920 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p921 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p922 = last_address;
DEBUG_PRINT(sfree(p922););
printStats();
DEBUG_PRINT(sfree(p567););
printStats();
PRINT_POINTER(scalloc(108,194););
printStats();
void* p923 = last_address;
PRINT_POINTER(scalloc(168,123););
printStats();
void* p924 = last_address;
DEBUG_PRINT(sfree(p714););
printStats();
PRINT_POINTER(srealloc(p787,191););
printStats();
void* p925 = last_address;
PRINT_POINTER(srealloc(p751,173););
printStats();
void* p926 = last_address;
PRINT_POINTER(srealloc(p841,148););
printStats();
void* p927 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p928 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p929 = last_address;
PRINT_POINTER(srealloc(p505,87););
printStats();
void* p930 = last_address;
DEBUG_PRINT(sfree(p768););
printStats();
PRINT_POINTER(scalloc(212,15););
printStats();
void* p931 = last_address;
DEBUG_PRINT(sfree(p796););
printStats();
PRINT_POINTER(smalloc(173););
printStats();
void* p932 = last_address;
DEBUG_PRINT(sfree(p427););
printStats();
PRINT_POINTER(srealloc(p503,235););
printStats();
void* p933 = last_address;
PRINT_POINTER(srealloc(p541,44););
printStats();
void* p934 = last_address;
PRINT_POINTER(srealloc(p767,11););
printStats();
void* p935 = last_address;
PRINT_POINTER(srealloc(p643,168););
printStats();
void* p936 = last_address;
PRINT_POINTER(scalloc(94,94););
printStats();
void* p937 = last_address;
PRINT_POINTER(srealloc(p763,118););
printStats();
void* p938 = last_address;
PRINT_POINTER(srealloc(p795,172););
printStats();
void* p939 = last_address;
PRINT_POINTER(scalloc(106,131););
printStats();
void* p940 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p941 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p942 = last_address;
PRINT_POINTER(srealloc(p941,135););
printStats();
void* p943 = last_address;
DEBUG_PRINT(sfree(p859););
printStats();
PRINT_POINTER(srealloc(p394,145););
printStats();
void* p944 = last_address;
PRINT_POINTER(srealloc(p750,82););
printStats();
void* p945 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p946 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p947 = last_address;
DEBUG_PRINT(sfree(p760););
printStats();
DEBUG_PRINT(sfree(p280););
printStats();
PRINT_POINTER(scalloc(171,12););
printStats();
void* p948 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p949 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p950 = last_address;
PRINT_POINTER(scalloc(60,182););
printStats();
void* p951 = last_address;
PRINT_POINTER(scalloc(159,15););
printStats();
void* p952 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p953 = last_address;
DEBUG_PRINT(sfree(p335););
printStats();
PRINT_POINTER(smalloc(87););
printStats();
void* p954 = last_address;
DEBUG_PRINT(sfree(p868););
printStats();
PRINT_POINTER(scalloc(198,23););
printStats();
void* p955 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p956 = last_address;
PRINT_POINTER(srealloc(p839,127););
printStats();
void* p957 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p958 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p959 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p960 = last_address;
PRINT_POINTER(srealloc(p851,224););
printStats();
void* p961 = last_address;
DEBUG_PRINT(sfree(p906););
printStats();
PRINT_POINTER(srealloc(p568,208););
printStats();
void* p962 = last_address;
DEBUG_PRINT(sfree(p604););
printStats();
DEBUG_PRINT(sfree(p630););
printStats();
DEBUG_PRINT(sfree(p865););
printStats();
PRINT_POINTER(scalloc(16,177););
printStats();
void* p963 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p964 = last_address;
PRINT_POINTER(scalloc(40,222););
printStats();
void* p965 = last_address;
DEBUG_PRINT(sfree(p393););
printStats();
PRINT_POINTER(srealloc(p837,134););
printStats();
void* p966 = last_address;
DEBUG_PRINT(sfree(p439););
printStats();
PRINT_POINTER(smalloc(101););
printStats();
void* p967 = last_address;
PRINT_POINTER(scalloc(241,116););
printStats();
void* p968 = last_address;
PRINT_POINTER(srealloc(p530,38););
printStats();
void* p969 = last_address;
PRINT_POINTER(scalloc(131,96););
printStats();
void* p970 = last_address;
PRINT_POINTER(srealloc(p759,235););
printStats();
void* p971 = last_address;
DEBUG_PRINT(sfree(p573););
printStats();
DEBUG_PRINT(sfree(p797););
printStats();
DEBUG_PRINT(sfree(p537););
printStats();
PRINT_POINTER(smalloc(239););
printStats();
void* p972 = last_address;
DEBUG_PRINT(sfree(p629););
printStats();
DEBUG_PRINT(sfree(p755););
printStats();
DEBUG_PRINT(sfree(p881););
printStats();
DEBUG_PRINT(sfree(p582););
printStats();
PRINT_POINTER(smalloc(3););
printStats();
void* p973 = last_address;
PRINT_POINTER(scalloc(186,197););
printStats();
void* p974 = last_address;
DEBUG_PRINT(sfree(p743););
printStats();
PRINT_POINTER(scalloc(124,43););
printStats();
void* p975 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p976 = last_address;
PRINT_POINTER(scalloc(160,143););
printStats();
void* p977 = last_address;
DEBUG_PRINT(sfree(p877););
printStats();
DEBUG_PRINT(sfree(p466););
printStats();
DEBUG_PRINT(sfree(p893););
printStats();
PRINT_POINTER(smalloc(146););
printStats();
void* p978 = last_address;
PRINT_POINTER(srealloc(p54,26););
printStats();
void* p979 = last_address;
PRINT_POINTER(srealloc(p588,43););
printStats();
void* p980 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p981 = last_address;
PRINT_POINTER(scalloc(78,19););
printStats();
void* p982 = last_address;
PRINT_POINTER(scalloc(93,67););
printStats();
void* p983 = last_address;
PRINT_POINTER(srealloc(p535,6););
printStats();
void* p984 = last_address;
PRINT_POINTER(srealloc(p832,11););
printStats();
void* p985 = last_address;
DEBUG_PRINT(sfree(p978););
printStats();
PRINT_POINTER(smalloc(127););
printStats();
void* p986 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p987 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p988 = last_address;
DEBUG_PRINT(sfree(p857););
printStats();
DEBUG_PRINT(sfree(p766););
printStats();
PRINT_POINTER(smalloc(106););
printStats();
void* p989 = last_address;
PRINT_POINTER(srealloc(p908,171););
printStats();
void* p990 = last_address;
PRINT_POINTER(scalloc(64,32););
printStats();
void* p991 = last_address;
PRINT_POINTER(scalloc(118,187););
printStats();
void* p992 = last_address;
PRINT_POINTER(srealloc(p715,78););
printStats();
void* p993 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p994 = last_address;
DEBUG_PRINT(sfree(p930););
printStats();
PRINT_POINTER(smalloc(36););
printStats();
void* p995 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p996 = last_address;
DEBUG_PRINT(sfree(p920););
printStats();
DEBUG_PRINT(sfree(p853););
printStats();
PRINT_POINTER(scalloc(124,34););
printStats();
void* p997 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p998 = last_address;
DEBUG_PRINT(sfree(p713););
printStats();
PRINT_POINTER(srealloc(p617,236););
printStats();
void* p999 = last_address;
PRINT_POINTER(srealloc(p994,116););
printStats();
void* p1000 = last_address;
DEBUG_PRINT(sfree(p792););
printStats();
PRINT_POINTER(scalloc(139,76););
printStats();
void* p1001 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p1002 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p1003 = last_address;
PRINT_POINTER(scalloc(138,200););
printStats();
void* p1004 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p1005 = last_address;
DEBUG_PRINT(sfree(p675););
printStats();
PRINT_POINTER(smalloc(154););
printStats();
void* p1006 = last_address;
DEBUG_PRINT(sfree(p980););
printStats();
PRINT_POINTER(smalloc(229););
printStats();
void* p1007 = last_address;
DEBUG_PRINT(sfree(p1005););
printStats();
PRINT_POINTER(smalloc(163););
printStats();
void* p1008 = last_address;
DEBUG_PRINT(sfree(p636););
printStats();
PRINT_POINTER(srealloc(p474,63););
printStats();
void* p1009 = last_address;
DEBUG_PRINT(sfree(p1003););
printStats();
PRINT_POINTER(scalloc(78,165););
printStats();
void* p1010 = last_address;
PRINT_POINTER(srealloc(p807,126););
printStats();
void* p1011 = last_address;
PRINT_POINTER(srealloc(p655,115););
printStats();
void* p1012 = last_address;
}
