#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(214,213););
printStats();
void* p0 = last_address;
PRINT_POINTER(srealloc(p0,77););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(scalloc(1,230););
printStats();
void* p2 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p3 = last_address;
PRINT_POINTER(srealloc(p3,248););
printStats();
void* p4 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p5 = last_address;
PRINT_POINTER(scalloc(151,164););
printStats();
void* p6 = last_address;
DEBUG_PRINT(sfree(p5););
printStats();
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(srealloc(p4,161););
printStats();
void* p7 = last_address;
PRINT_POINTER(scalloc(73,231););
printStats();
void* p8 = last_address;
PRINT_POINTER(srealloc(p8,178););
printStats();
void* p9 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p10 = last_address;
PRINT_POINTER(scalloc(217,34););
printStats();
void* p11 = last_address;
PRINT_POINTER(srealloc(p9,19););
printStats();
void* p12 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
DEBUG_PRINT(sfree(p7););
printStats();
PRINT_POINTER(srealloc(p12,166););
printStats();
void* p13 = last_address;
DEBUG_PRINT(sfree(p13););
printStats();
DEBUG_PRINT(sfree(p10););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p14 = last_address;
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(scalloc(182,31););
printStats();
void* p15 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(scalloc(156,76););
printStats();
void* p16 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p17 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p18 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p19 = last_address;
PRINT_POINTER(scalloc(96,219););
printStats();
void* p20 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p21 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p22 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(smalloc(5););
printStats();
void* p23 = last_address;
DEBUG_PRINT(sfree(p19););
printStats();
PRINT_POINTER(scalloc(8,151););
printStats();
void* p24 = last_address;
PRINT_POINTER(srealloc(p21,78););
printStats();
void* p25 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(smalloc(2););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p23,89););
printStats();
void* p27 = last_address;
PRINT_POINTER(scalloc(78,238););
printStats();
void* p28 = last_address;
PRINT_POINTER(scalloc(146,232););
printStats();
void* p29 = last_address;
PRINT_POINTER(scalloc(223,180););
printStats();
void* p30 = last_address;
PRINT_POINTER(srealloc(p16,240););
printStats();
void* p31 = last_address;
PRINT_POINTER(srealloc(p30,205););
printStats();
void* p32 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p33 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p34 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
PRINT_POINTER(scalloc(68,104););
printStats();
void* p35 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p36 = last_address;
PRINT_POINTER(scalloc(100,124););
printStats();
void* p37 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p38 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p39 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p39,217););
printStats();
void* p41 = last_address;
PRINT_POINTER(scalloc(23,120););
printStats();
void* p42 = last_address;
PRINT_POINTER(srealloc(p34,130););
printStats();
void* p43 = last_address;
PRINT_POINTER(srealloc(p36,223););
printStats();
void* p44 = last_address;
PRINT_POINTER(scalloc(235,87););
printStats();
void* p45 = last_address;
DEBUG_PRINT(sfree(p44););
printStats();
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(smalloc(245););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p47 = last_address;
PRINT_POINTER(scalloc(16,110););
printStats();
void* p48 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p49 = last_address;
PRINT_POINTER(srealloc(p24,238););
printStats();
void* p50 = last_address;
PRINT_POINTER(scalloc(99,24););
printStats();
void* p51 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p52 = last_address;
PRINT_POINTER(srealloc(p43,175););
printStats();
void* p53 = last_address;
PRINT_POINTER(scalloc(194,183););
printStats();
void* p54 = last_address;
PRINT_POINTER(srealloc(p52,120););
printStats();
void* p55 = last_address;
PRINT_POINTER(srealloc(p17,114););
printStats();
void* p56 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(45,8););
printStats();
void* p58 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p59 = last_address;
PRINT_POINTER(srealloc(p38,134););
printStats();
void* p60 = last_address;
PRINT_POINTER(scalloc(163,95););
printStats();
void* p61 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p62 = last_address;
PRINT_POINTER(scalloc(142,92););
printStats();
void* p63 = last_address;
PRINT_POINTER(scalloc(92,210););
printStats();
void* p64 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p65 = last_address;
PRINT_POINTER(scalloc(61,57););
printStats();
void* p66 = last_address;
PRINT_POINTER(scalloc(62,72););
printStats();
void* p67 = last_address;
PRINT_POINTER(srealloc(p62,109););
printStats();
void* p68 = last_address;
PRINT_POINTER(scalloc(160,61););
printStats();
void* p69 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p70 = last_address;
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(smalloc(85););
printStats();
void* p71 = last_address;
PRINT_POINTER(scalloc(223,245););
printStats();
void* p72 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p73 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p74 = last_address;
DEBUG_PRINT(sfree(p47););
printStats();
PRINT_POINTER(scalloc(28,32););
printStats();
void* p75 = last_address;
PRINT_POINTER(srealloc(p60,9););
printStats();
void* p76 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p77 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
DEBUG_PRINT(sfree(p55););
printStats();
PRINT_POINTER(scalloc(177,171););
printStats();
void* p78 = last_address;
DEBUG_PRINT(sfree(p35););
printStats();
PRINT_POINTER(srealloc(p74,185););
printStats();
void* p79 = last_address;
PRINT_POINTER(srealloc(p71,29););
printStats();
void* p80 = last_address;
PRINT_POINTER(scalloc(7,104););
printStats();
void* p81 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p83 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p84 = last_address;
PRINT_POINTER(scalloc(233,77););
printStats();
void* p85 = last_address;
PRINT_POINTER(srealloc(p49,195););
printStats();
void* p86 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p87 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p88 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(scalloc(207,8););
printStats();
void* p89 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p90 = last_address;
PRINT_POINTER(scalloc(206,71););
printStats();
void* p91 = last_address;
DEBUG_PRINT(sfree(p20););
printStats();
PRINT_POINTER(srealloc(p67,248););
printStats();
void* p92 = last_address;
DEBUG_PRINT(sfree(p75););
printStats();
PRINT_POINTER(smalloc(204););
printStats();
void* p93 = last_address;
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(srealloc(p76,63););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p95 = last_address;
PRINT_POINTER(scalloc(237,162););
printStats();
void* p96 = last_address;
PRINT_POINTER(scalloc(178,167););
printStats();
void* p97 = last_address;
PRINT_POINTER(srealloc(p45,241););
printStats();
void* p98 = last_address;
PRINT_POINTER(srealloc(p94,49););
printStats();
void* p99 = last_address;
PRINT_POINTER(scalloc(8,241););
printStats();
void* p100 = last_address;
DEBUG_PRINT(sfree(p63););
printStats();
DEBUG_PRINT(sfree(p93););
printStats();
PRINT_POINTER(scalloc(72,194););
printStats();
void* p101 = last_address;
PRINT_POINTER(srealloc(p66,42););
printStats();
void* p102 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(smalloc(123););
printStats();
void* p103 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p104 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p95,85););
printStats();
void* p106 = last_address;
PRINT_POINTER(srealloc(p68,142););
printStats();
void* p107 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p108 = last_address;
PRINT_POINTER(scalloc(141,80););
printStats();
void* p109 = last_address;
DEBUG_PRINT(sfree(p73););
printStats();
DEBUG_PRINT(sfree(p99););
printStats();
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(scalloc(171,98););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p46,155););
printStats();
void* p111 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p112 = last_address;
PRINT_POINTER(scalloc(222,70););
printStats();
void* p113 = last_address;
PRINT_POINTER(scalloc(168,217););
printStats();
void* p114 = last_address;
DEBUG_PRINT(sfree(p104););
printStats();
PRINT_POINTER(scalloc(200,62););
printStats();
void* p115 = last_address;
PRINT_POINTER(srealloc(p54,247););
printStats();
void* p116 = last_address;
PRINT_POINTER(scalloc(190,28););
printStats();
void* p117 = last_address;
DEBUG_PRINT(sfree(p56););
printStats();
PRINT_POINTER(scalloc(117,189););
printStats();
void* p118 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p119 = last_address;
PRINT_POINTER(scalloc(68,183););
printStats();
void* p120 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p121 = last_address;
PRINT_POINTER(scalloc(103,40););
printStats();
void* p122 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p123 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p124 = last_address;
DEBUG_PRINT(sfree(p124););
printStats();
DEBUG_PRINT(sfree(p105););
printStats();
PRINT_POINTER(scalloc(38,9););
printStats();
void* p125 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(2,93););
printStats();
void* p127 = last_address;
PRINT_POINTER(scalloc(158,100););
printStats();
void* p128 = last_address;
PRINT_POINTER(scalloc(101,198););
printStats();
void* p129 = last_address;
PRINT_POINTER(srealloc(p92,219););
printStats();
void* p130 = last_address;
PRINT_POINTER(srealloc(p29,99););
printStats();
void* p131 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p132 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p133 = last_address;
PRINT_POINTER(scalloc(22,122););
printStats();
void* p134 = last_address;
DEBUG_PRINT(sfree(p126););
printStats();
PRINT_POINTER(srealloc(p131,29););
printStats();
void* p135 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p136 = last_address;
DEBUG_PRINT(sfree(p81););
printStats();
PRINT_POINTER(srealloc(p136,18););
printStats();
void* p137 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p138 = last_address;
PRINT_POINTER(scalloc(204,17););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(srealloc(p109,201););
printStats();
void* p140 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p141 = last_address;
PRINT_POINTER(scalloc(139,205););
printStats();
void* p142 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p143 = last_address;
PRINT_POINTER(srealloc(p98,197););
printStats();
void* p144 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p145 = last_address;
PRINT_POINTER(srealloc(p120,70););
printStats();
void* p146 = last_address;
PRINT_POINTER(scalloc(221,217););
printStats();
void* p147 = last_address;
PRINT_POINTER(scalloc(198,220););
printStats();
void* p148 = last_address;
PRINT_POINTER(srealloc(p146,33););
printStats();
void* p149 = last_address;
DEBUG_PRINT(sfree(p138););
printStats();
PRINT_POINTER(smalloc(43););
printStats();
void* p150 = last_address;
PRINT_POINTER(scalloc(83,37););
printStats();
void* p151 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p152 = last_address;
DEBUG_PRINT(sfree(p135););
printStats();
PRINT_POINTER(smalloc(151););
printStats();
void* p153 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(scalloc(189,92););
printStats();
void* p154 = last_address;
PRINT_POINTER(srealloc(p84,16););
printStats();
void* p155 = last_address;
DEBUG_PRINT(sfree(p61););
printStats();
PRINT_POINTER(scalloc(154,180););
printStats();
void* p156 = last_address;
DEBUG_PRINT(sfree(p110););
printStats();
PRINT_POINTER(smalloc(201););
printStats();
void* p157 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
DEBUG_PRINT(sfree(p86););
printStats();
DEBUG_PRINT(sfree(p155););
printStats();
PRINT_POINTER(smalloc(197););
printStats();
void* p158 = last_address;
PRINT_POINTER(scalloc(28,160););
printStats();
void* p159 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p160 = last_address;
DEBUG_PRINT(sfree(p151););
printStats();
PRINT_POINTER(smalloc(184););
printStats();
void* p161 = last_address;
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(smalloc(9););
printStats();
void* p162 = last_address;
PRINT_POINTER(srealloc(p161,171););
printStats();
void* p163 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p164 = last_address;
PRINT_POINTER(srealloc(p130,138););
printStats();
void* p165 = last_address;
PRINT_POINTER(srealloc(p112,169););
printStats();
void* p166 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
DEBUG_PRINT(sfree(p87););
printStats();
PRINT_POINTER(smalloc(84););
printStats();
void* p167 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(241,17););
printStats();
void* p169 = last_address;
PRINT_POINTER(srealloc(p134,4););
printStats();
void* p170 = last_address;
PRINT_POINTER(srealloc(p96,123););
printStats();
void* p171 = last_address;
PRINT_POINTER(scalloc(245,236););
printStats();
void* p172 = last_address;
PRINT_POINTER(srealloc(p48,192););
printStats();
void* p173 = last_address;
PRINT_POINTER(scalloc(141,76););
printStats();
void* p174 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p175 = last_address;
PRINT_POINTER(scalloc(88,59););
printStats();
void* p176 = last_address;
PRINT_POINTER(srealloc(p145,240););
printStats();
void* p177 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p178 = last_address;
DEBUG_PRINT(sfree(p144););
printStats();
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(srealloc(p148,224););
printStats();
void* p179 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p180 = last_address;
PRINT_POINTER(scalloc(11,13););
printStats();
void* p181 = last_address;
PRINT_POINTER(scalloc(99,40););
printStats();
void* p182 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p183 = last_address;
PRINT_POINTER(srealloc(p182,207););
printStats();
void* p184 = last_address;
PRINT_POINTER(srealloc(p133,173););
printStats();
void* p185 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(scalloc(219,226););
printStats();
void* p186 = last_address;
PRINT_POINTER(srealloc(p115,215););
printStats();
void* p187 = last_address;
PRINT_POINTER(srealloc(p177,225););
printStats();
void* p188 = last_address;
PRINT_POINTER(scalloc(217,134););
printStats();
void* p189 = last_address;
PRINT_POINTER(srealloc(p88,13););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p191 = last_address;
DEBUG_PRINT(sfree(p58););
printStats();
PRINT_POINTER(scalloc(36,147););
printStats();
void* p192 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(smalloc(18););
printStats();
void* p193 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p194 = last_address;
PRINT_POINTER(scalloc(9,89););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p65););
printStats();
PRINT_POINTER(scalloc(103,190););
printStats();
void* p196 = last_address;
DEBUG_PRINT(sfree(p121););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p197 = last_address;
PRINT_POINTER(scalloc(42,91););
printStats();
void* p198 = last_address;
DEBUG_PRINT(sfree(p111););
printStats();
PRINT_POINTER(srealloc(p32,76););
printStats();
void* p199 = last_address;
DEBUG_PRINT(sfree(p167););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p163,247););
printStats();
void* p201 = last_address;
PRINT_POINTER(srealloc(p31,178););
printStats();
void* p202 = last_address;
PRINT_POINTER(srealloc(p119,181););
printStats();
void* p203 = last_address;
PRINT_POINTER(srealloc(p164,215););
printStats();
void* p204 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p205 = last_address;
PRINT_POINTER(scalloc(79,198););
printStats();
void* p206 = last_address;
PRINT_POINTER(scalloc(47,90););
printStats();
void* p207 = last_address;
DEBUG_PRINT(sfree(p157););
printStats();
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(smalloc(222););
printStats();
void* p208 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(smalloc(206););
printStats();
void* p209 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p210 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(123,68););
printStats();
void* p212 = last_address;
PRINT_POINTER(srealloc(p188,70););
printStats();
void* p213 = last_address;
DEBUG_PRINT(sfree(p192););
printStats();
DEBUG_PRINT(sfree(p180););
printStats();
PRINT_POINTER(srealloc(p158,220););
printStats();
void* p214 = last_address;
PRINT_POINTER(scalloc(18,179););
printStats();
void* p215 = last_address;
PRINT_POINTER(srealloc(p175,113););
printStats();
void* p216 = last_address;
PRINT_POINTER(srealloc(p183,23););
printStats();
void* p217 = last_address;
PRINT_POINTER(srealloc(p27,126););
printStats();
void* p218 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p219 = last_address;
DEBUG_PRINT(sfree(p118););
printStats();
DEBUG_PRINT(sfree(p184););
printStats();
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(scalloc(150,237););
printStats();
void* p220 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p221 = last_address;
PRINT_POINTER(srealloc(p213,142););
printStats();
void* p222 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p223 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p224 = last_address;
PRINT_POINTER(srealloc(p26,136););
printStats();
void* p225 = last_address;
PRINT_POINTER(srealloc(p137,78););
printStats();
void* p226 = last_address;
PRINT_POINTER(scalloc(51,98););
printStats();
void* p227 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p228 = last_address;
DEBUG_PRINT(sfree(p125););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p229 = last_address;
PRINT_POINTER(scalloc(226,127););
printStats();
void* p230 = last_address;
DEBUG_PRINT(sfree(p57););
printStats();
PRINT_POINTER(srealloc(p197,151););
printStats();
void* p231 = last_address;
PRINT_POINTER(srealloc(p91,169););
printStats();
void* p232 = last_address;
PRINT_POINTER(scalloc(19,136););
printStats();
void* p233 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p234 = last_address;
PRINT_POINTER(scalloc(125,157););
printStats();
void* p235 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(scalloc(73,235););
printStats();
void* p236 = last_address;
PRINT_POINTER(srealloc(p123,177););
printStats();
void* p237 = last_address;
PRINT_POINTER(scalloc(33,90););
printStats();
void* p238 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p239 = last_address;
DEBUG_PRINT(sfree(p235););
printStats();
PRINT_POINTER(scalloc(166,154););
printStats();
void* p240 = last_address;
PRINT_POINTER(srealloc(p108,175););
printStats();
void* p241 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p178););
printStats();
PRINT_POINTER(srealloc(p233,86););
printStats();
void* p243 = last_address;
PRINT_POINTER(srealloc(p153,154););
printStats();
void* p244 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(srealloc(p169,118););
printStats();
void* p245 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p246 = last_address;
PRINT_POINTER(srealloc(p170,205););
printStats();
void* p247 = last_address;
DEBUG_PRINT(sfree(p139););
printStats();
PRINT_POINTER(scalloc(97,238););
printStats();
void* p248 = last_address;
DEBUG_PRINT(sfree(p187););
printStats();
PRINT_POINTER(smalloc(25););
printStats();
void* p249 = last_address;
PRINT_POINTER(scalloc(227,202););
printStats();
void* p250 = last_address;
PRINT_POINTER(scalloc(232,184););
printStats();
void* p251 = last_address;
PRINT_POINTER(srealloc(p191,207););
printStats();
void* p252 = last_address;
PRINT_POINTER(scalloc(168,217););
printStats();
void* p253 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p254 = last_address;
PRINT_POINTER(srealloc(p208,222););
printStats();
void* p255 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p256 = last_address;
PRINT_POINTER(scalloc(60,13););
printStats();
void* p257 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p258 = last_address;
PRINT_POINTER(scalloc(183,201););
printStats();
void* p259 = last_address;
DEBUG_PRINT(sfree(p185););
printStats();
PRINT_POINTER(srealloc(p231,112););
printStats();
void* p260 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p261 = last_address;
DEBUG_PRINT(sfree(p227););
printStats();
DEBUG_PRINT(sfree(p256););
printStats();
PRINT_POINTER(srealloc(p220,187););
printStats();
void* p262 = last_address;
PRINT_POINTER(srealloc(p238,68););
printStats();
void* p263 = last_address;
PRINT_POINTER(srealloc(p258,229););
printStats();
void* p264 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p265 = last_address;
DEBUG_PRINT(sfree(p79););
printStats();
DEBUG_PRINT(sfree(p255););
printStats();
PRINT_POINTER(srealloc(p248,88););
printStats();
void* p266 = last_address;
DEBUG_PRINT(sfree(p207););
printStats();
DEBUG_PRINT(sfree(p129););
printStats();
DEBUG_PRINT(sfree(p241););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p267 = last_address;
PRINT_POINTER(srealloc(p141,161););
printStats();
void* p268 = last_address;
PRINT_POINTER(scalloc(50,202););
printStats();
void* p269 = last_address;
PRINT_POINTER(srealloc(p264,110););
printStats();
void* p270 = last_address;
DEBUG_PRINT(sfree(p234););
printStats();
PRINT_POINTER(srealloc(p156,193););
printStats();
void* p271 = last_address;
PRINT_POINTER(srealloc(p190,203););
printStats();
void* p272 = last_address;
PRINT_POINTER(srealloc(p270,149););
printStats();
void* p273 = last_address;
PRINT_POINTER(scalloc(248,133););
printStats();
void* p274 = last_address;
PRINT_POINTER(srealloc(p236,139););
printStats();
void* p275 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(srealloc(p271,164););
printStats();
void* p276 = last_address;
PRINT_POINTER(scalloc(180,121););
printStats();
void* p277 = last_address;
PRINT_POINTER(scalloc(106,231););
printStats();
void* p278 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p279 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p280 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p281 = last_address;
PRINT_POINTER(scalloc(20,22););
printStats();
void* p282 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
PRINT_POINTER(scalloc(64,203););
printStats();
void* p283 = last_address;
PRINT_POINTER(scalloc(217,138););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p82,197););
printStats();
void* p285 = last_address;
PRINT_POINTER(srealloc(p281,46););
printStats();
void* p286 = last_address;
DEBUG_PRINT(sfree(p279););
printStats();
PRINT_POINTER(smalloc(191););
printStats();
void* p287 = last_address;
DEBUG_PRINT(sfree(p262););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p288 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p289 = last_address;
DEBUG_PRINT(sfree(p267););
printStats();
PRINT_POINTER(scalloc(82,171););
printStats();
void* p290 = last_address;
PRINT_POINTER(srealloc(p242,90););
printStats();
void* p291 = last_address;
PRINT_POINTER(scalloc(189,111););
printStats();
void* p292 = last_address;
PRINT_POINTER(scalloc(30,115););
printStats();
void* p293 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p294 = last_address;
PRINT_POINTER(srealloc(p128,199););
printStats();
void* p295 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p296 = last_address;
PRINT_POINTER(scalloc(45,2););
printStats();
void* p297 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p298 = last_address;
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(scalloc(67,10););
printStats();
void* p299 = last_address;
DEBUG_PRINT(sfree(p217););
printStats();
DEBUG_PRINT(sfree(p223););
printStats();
DEBUG_PRINT(sfree(p83););
printStats();
PRINT_POINTER(srealloc(p285,44););
printStats();
void* p300 = last_address;
PRINT_POINTER(scalloc(107,42););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p302 = last_address;
PRINT_POINTER(srealloc(p280,178););
printStats();
void* p303 = last_address;
PRINT_POINTER(srealloc(p253,54););
printStats();
void* p304 = last_address;
DEBUG_PRINT(sfree(p172););
printStats();
DEBUG_PRINT(sfree(p273););
printStats();
PRINT_POINTER(scalloc(162,98););
printStats();
void* p305 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p306 = last_address;
PRINT_POINTER(srealloc(p226,219););
printStats();
void* p307 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p308 = last_address;
PRINT_POINTER(srealloc(p301,32););
printStats();
void* p309 = last_address;
DEBUG_PRINT(sfree(p143););
printStats();
PRINT_POINTER(smalloc(13););
printStats();
void* p310 = last_address;
PRINT_POINTER(scalloc(155,203););
printStats();
void* p311 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p312 = last_address;
DEBUG_PRINT(sfree(p179););
printStats();
PRINT_POINTER(srealloc(p245,34););
printStats();
void* p313 = last_address;
PRINT_POINTER(srealloc(p291,12););
printStats();
void* p314 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p315 = last_address;
PRINT_POINTER(srealloc(p168,9););
printStats();
void* p316 = last_address;
PRINT_POINTER(scalloc(167,90););
printStats();
void* p317 = last_address;
PRINT_POINTER(srealloc(p240,227););
printStats();
void* p318 = last_address;
PRINT_POINTER(srealloc(p314,121););
printStats();
void* p319 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p320 = last_address;
PRINT_POINTER(srealloc(p289,115););
printStats();
void* p321 = last_address;
PRINT_POINTER(srealloc(p150,145););
printStats();
void* p322 = last_address;
PRINT_POINTER(srealloc(p80,138););
printStats();
void* p323 = last_address;
PRINT_POINTER(scalloc(168,31););
printStats();
void* p324 = last_address;
PRINT_POINTER(srealloc(p294,131););
printStats();
void* p325 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p326 = last_address;
DEBUG_PRINT(sfree(p206););
printStats();
DEBUG_PRINT(sfree(p317););
printStats();
DEBUG_PRINT(sfree(p237););
printStats();
PRINT_POINTER(srealloc(p293,26););
printStats();
void* p327 = last_address;
DEBUG_PRINT(sfree(p276););
printStats();
PRINT_POINTER(smalloc(122););
printStats();
void* p328 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p329 = last_address;
DEBUG_PRINT(sfree(p216););
printStats();
PRINT_POINTER(smalloc(69););
printStats();
void* p330 = last_address;
DEBUG_PRINT(sfree(p265););
printStats();
DEBUG_PRINT(sfree(p257););
printStats();
PRINT_POINTER(srealloc(p286,165););
printStats();
void* p331 = last_address;
PRINT_POINTER(srealloc(p303,197););
printStats();
void* p332 = last_address;
DEBUG_PRINT(sfree(p325););
printStats();
PRINT_POINTER(scalloc(201,232););
printStats();
void* p333 = last_address;
PRINT_POINTER(scalloc(74,199););
printStats();
void* p334 = last_address;
DEBUG_PRINT(sfree(p278););
printStats();
PRINT_POINTER(smalloc(117););
printStats();
void* p335 = last_address;
DEBUG_PRINT(sfree(p259););
printStats();
PRINT_POINTER(smalloc(225););
printStats();
void* p336 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p337 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p338 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
DEBUG_PRINT(sfree(p310););
printStats();
PRINT_POINTER(scalloc(244,225););
printStats();
void* p339 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p340 = last_address;
DEBUG_PRINT(sfree(p331););
printStats();
DEBUG_PRINT(sfree(p122););
printStats();
DEBUG_PRINT(sfree(p160););
printStats();
PRINT_POINTER(scalloc(139,185););
printStats();
void* p341 = last_address;
PRINT_POINTER(srealloc(p102,133););
printStats();
void* p342 = last_address;
PRINT_POINTER(scalloc(50,105););
printStats();
void* p343 = last_address;
PRINT_POINTER(srealloc(p247,98););
printStats();
void* p344 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(scalloc(119,35););
printStats();
void* p345 = last_address;
DEBUG_PRINT(sfree(p326););
printStats();
PRINT_POINTER(smalloc(177););
printStats();
void* p346 = last_address;
PRINT_POINTER(srealloc(p341,104););
printStats();
void* p347 = last_address;
PRINT_POINTER(srealloc(p284,150););
printStats();
void* p348 = last_address;
PRINT_POINTER(scalloc(40,137););
printStats();
void* p349 = last_address;
DEBUG_PRINT(sfree(p244););
printStats();
PRINT_POINTER(smalloc(186););
printStats();
void* p350 = last_address;
DEBUG_PRINT(sfree(p297););
printStats();
PRINT_POINTER(scalloc(242,206););
printStats();
void* p351 = last_address;
PRINT_POINTER(srealloc(p261,145););
printStats();
void* p352 = last_address;
DEBUG_PRINT(sfree(p198););
printStats();
PRINT_POINTER(scalloc(97,106););
printStats();
void* p353 = last_address;
DEBUG_PRINT(sfree(p311););
printStats();
PRINT_POINTER(scalloc(194,14););
printStats();
void* p354 = last_address;
PRINT_POINTER(scalloc(234,112););
printStats();
void* p355 = last_address;
DEBUG_PRINT(sfree(p299););
printStats();
PRINT_POINTER(scalloc(36,120););
printStats();
void* p356 = last_address;
DEBUG_PRINT(sfree(p352););
printStats();
PRINT_POINTER(smalloc(218););
printStats();
void* p357 = last_address;
DEBUG_PRINT(sfree(p53););
printStats();
PRINT_POINTER(smalloc(8););
printStats();
void* p358 = last_address;
PRINT_POINTER(srealloc(p339,39););
printStats();
void* p359 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p360 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p362 = last_address;
PRINT_POINTER(srealloc(p358,30););
printStats();
void* p363 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p364 = last_address;
DEBUG_PRINT(sfree(p324););
printStats();
DEBUG_PRINT(sfree(p340););
printStats();
PRINT_POINTER(smalloc(61););
printStats();
void* p365 = last_address;
PRINT_POINTER(scalloc(18,3););
printStats();
void* p366 = last_address;
DEBUG_PRINT(sfree(p343););
printStats();
PRINT_POINTER(scalloc(170,127););
printStats();
void* p367 = last_address;
PRINT_POINTER(srealloc(p364,94););
printStats();
void* p368 = last_address;
PRINT_POINTER(scalloc(45,98););
printStats();
void* p369 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p370 = last_address;
PRINT_POINTER(scalloc(151,246););
printStats();
void* p371 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p372 = last_address;
PRINT_POINTER(scalloc(25,223););
printStats();
void* p373 = last_address;
PRINT_POINTER(scalloc(6,80););
printStats();
void* p374 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p375 = last_address;
PRINT_POINTER(scalloc(25,8););
printStats();
void* p376 = last_address;
DEBUG_PRINT(sfree(p372););
printStats();
PRINT_POINTER(srealloc(p290,211););
printStats();
void* p377 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p378 = last_address;
PRINT_POINTER(srealloc(p302,9););
printStats();
void* p379 = last_address;
PRINT_POINTER(srealloc(p336,83););
printStats();
void* p380 = last_address;
PRINT_POINTER(srealloc(p373,191););
printStats();
void* p381 = last_address;
PRINT_POINTER(srealloc(p374,111););
printStats();
void* p382 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p383 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p384 = last_address;
DEBUG_PRINT(sfree(p381););
printStats();
PRINT_POINTER(smalloc(157););
printStats();
void* p385 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(srealloc(p229,56););
printStats();
void* p386 = last_address;
DEBUG_PRINT(sfree(p243););
printStats();
PRINT_POINTER(srealloc(p201,163););
printStats();
void* p387 = last_address;
PRINT_POINTER(srealloc(p386,29););
printStats();
void* p388 = last_address;
PRINT_POINTER(scalloc(63,126););
printStats();
void* p389 = last_address;
PRINT_POINTER(scalloc(182,92););
printStats();
void* p390 = last_address;
PRINT_POINTER(srealloc(p365,21););
printStats();
void* p391 = last_address;
PRINT_POINTER(srealloc(p296,60););
printStats();
void* p392 = last_address;
DEBUG_PRINT(sfree(p383););
printStats();
PRINT_POINTER(smalloc(193););
printStats();
void* p393 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p394 = last_address;
PRINT_POINTER(srealloc(p348,132););
printStats();
void* p395 = last_address;
PRINT_POINTER(srealloc(p346,244););
printStats();
void* p396 = last_address;
PRINT_POINTER(srealloc(p254,215););
printStats();
void* p397 = last_address;
DEBUG_PRINT(sfree(p391););
printStats();
PRINT_POINTER(srealloc(p162,235););
printStats();
void* p398 = last_address;
DEBUG_PRINT(sfree(p246););
printStats();
DEBUG_PRINT(sfree(p322););
printStats();
PRINT_POINTER(srealloc(p307,61););
printStats();
void* p399 = last_address;
PRINT_POINTER(srealloc(p318,196););
printStats();
void* p400 = last_address;
PRINT_POINTER(srealloc(p298,20););
printStats();
void* p401 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p402 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
DEBUG_PRINT(sfree(p159););
printStats();
DEBUG_PRINT(sfree(p189););
printStats();
PRINT_POINTER(scalloc(146,176););
printStats();
void* p403 = last_address;
PRINT_POINTER(srealloc(p320,157););
printStats();
void* p404 = last_address;
PRINT_POINTER(scalloc(126,142););
printStats();
void* p405 = last_address;
DEBUG_PRINT(sfree(p269););
printStats();
PRINT_POINTER(scalloc(136,71););
printStats();
void* p406 = last_address;
PRINT_POINTER(srealloc(p78,152););
printStats();
void* p407 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p408 = last_address;
PRINT_POINTER(srealloc(p399,42););
printStats();
void* p409 = last_address;
PRINT_POINTER(srealloc(p385,61););
printStats();
void* p410 = last_address;
DEBUG_PRINT(sfree(p350););
printStats();
PRINT_POINTER(smalloc(232););
printStats();
void* p411 = last_address;
DEBUG_PRINT(sfree(p195););
printStats();
PRINT_POINTER(srealloc(p215,197););
printStats();
void* p412 = last_address;
PRINT_POINTER(srealloc(p369,50););
printStats();
void* p413 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p414 = last_address;
DEBUG_PRINT(sfree(p397););
printStats();
PRINT_POINTER(smalloc(246););
printStats();
void* p415 = last_address;
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(smalloc(134););
printStats();
void* p416 = last_address;
DEBUG_PRINT(sfree(p389););
printStats();
DEBUG_PRINT(sfree(p332););
printStats();
PRINT_POINTER(srealloc(p327,94););
printStats();
void* p417 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p418 = last_address;
DEBUG_PRINT(sfree(p401););
printStats();
PRINT_POINTER(scalloc(159,248););
printStats();
void* p419 = last_address;
PRINT_POINTER(scalloc(144,182););
printStats();
void* p420 = last_address;
PRINT_POINTER(srealloc(p378,55););
printStats();
void* p421 = last_address;
DEBUG_PRINT(sfree(p347););
printStats();
DEBUG_PRINT(sfree(p395););
printStats();
PRINT_POINTER(srealloc(p174,180););
printStats();
void* p422 = last_address;
PRINT_POINTER(srealloc(p400,46););
printStats();
void* p423 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
PRINT_POINTER(smalloc(89););
printStats();
void* p424 = last_address;
DEBUG_PRINT(sfree(p211););
printStats();
PRINT_POINTER(smalloc(74););
printStats();
void* p425 = last_address;
PRINT_POINTER(srealloc(p165,210););
printStats();
void* p426 = last_address;
PRINT_POINTER(srealloc(p356,224););
printStats();
void* p427 = last_address;
PRINT_POINTER(scalloc(185,105););
printStats();
void* p428 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
PRINT_POINTER(srealloc(p232,39););
printStats();
void* p429 = last_address;
PRINT_POINTER(srealloc(p404,195););
printStats();
void* p430 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p431 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p432 = last_address;
PRINT_POINTER(scalloc(196,185););
printStats();
void* p433 = last_address;
PRINT_POINTER(scalloc(226,248););
printStats();
void* p434 = last_address;
PRINT_POINTER(scalloc(19,69););
printStats();
void* p435 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p436 = last_address;
PRINT_POINTER(srealloc(p316,49););
printStats();
void* p437 = last_address;
PRINT_POINTER(srealloc(p305,44););
printStats();
void* p438 = last_address;
DEBUG_PRINT(sfree(p426););
printStats();
PRINT_POINTER(scalloc(207,177););
printStats();
void* p439 = last_address;
DEBUG_PRINT(sfree(p194););
printStats();
PRINT_POINTER(scalloc(232,173););
printStats();
void* p440 = last_address;
DEBUG_PRINT(sfree(p319););
printStats();
PRINT_POINTER(srealloc(p379,42););
printStats();
void* p441 = last_address;
DEBUG_PRINT(sfree(p287););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p442 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p443 = last_address;
PRINT_POINTER(srealloc(p430,241););
printStats();
void* p444 = last_address;
PRINT_POINTER(srealloc(p202,183););
printStats();
void* p445 = last_address;
PRINT_POINTER(scalloc(242,205););
printStats();
void* p446 = last_address;
DEBUG_PRINT(sfree(p440););
printStats();
PRINT_POINTER(scalloc(150,55););
printStats();
void* p447 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p448 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p449 = last_address;
DEBUG_PRINT(sfree(p380););
printStats();
PRINT_POINTER(smalloc(243););
printStats();
void* p450 = last_address;
PRINT_POINTER(scalloc(119,166););
printStats();
void* p451 = last_address;
PRINT_POINTER(srealloc(p357,3););
printStats();
void* p452 = last_address;
PRINT_POINTER(srealloc(p171,34););
printStats();
void* p453 = last_address;
PRINT_POINTER(scalloc(69,246););
printStats();
void* p454 = last_address;
PRINT_POINTER(scalloc(0,130););
printStats();
void* p455 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p456 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p457 = last_address;
PRINT_POINTER(scalloc(27,182););
printStats();
void* p458 = last_address;
DEBUG_PRINT(sfree(p457););
printStats();
DEBUG_PRINT(sfree(p338););
printStats();
PRINT_POINTER(smalloc(85););
printStats();
void* p459 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p460 = last_address;
PRINT_POINTER(scalloc(123,31););
printStats();
void* p461 = last_address;
PRINT_POINTER(srealloc(p394,121););
printStats();
void* p462 = last_address;
DEBUG_PRINT(sfree(p351););
printStats();
PRINT_POINTER(smalloc(77););
printStats();
void* p463 = last_address;
PRINT_POINTER(scalloc(179,205););
printStats();
void* p464 = last_address;
PRINT_POINTER(srealloc(p214,154););
printStats();
void* p465 = last_address;
DEBUG_PRINT(sfree(p193););
printStats();
PRINT_POINTER(smalloc(243););
printStats();
void* p466 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p467 = last_address;
DEBUG_PRINT(sfree(p422););
printStats();
DEBUG_PRINT(sfree(p392););
printStats();
PRINT_POINTER(srealloc(p415,182););
printStats();
void* p468 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p469 = last_address;
PRINT_POINTER(scalloc(229,214););
printStats();
void* p470 = last_address;
DEBUG_PRINT(sfree(p437););
printStats();
DEBUG_PRINT(sfree(p388););
printStats();
PRINT_POINTER(scalloc(8,42););
printStats();
void* p471 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p472 = last_address;
PRINT_POINTER(srealloc(p471,97););
printStats();
void* p473 = last_address;
DEBUG_PRINT(sfree(p306););
printStats();
DEBUG_PRINT(sfree(p329););
printStats();
PRINT_POINTER(scalloc(238,65););
printStats();
void* p474 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p475 = last_address;
PRINT_POINTER(srealloc(p424,101););
printStats();
void* p476 = last_address;
DEBUG_PRINT(sfree(p101););
printStats();
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(srealloc(p219,88););
printStats();
void* p477 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p478 = last_address;
DEBUG_PRINT(sfree(p425););
printStats();
PRINT_POINTER(scalloc(189,97););
printStats();
void* p479 = last_address;
PRINT_POINTER(srealloc(p107,201););
printStats();
void* p480 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p481 = last_address;
PRINT_POINTER(scalloc(181,117););
printStats();
void* p482 = last_address;
PRINT_POINTER(srealloc(p277,208););
printStats();
void* p483 = last_address;
PRINT_POINTER(scalloc(151,249););
printStats();
void* p484 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p485 = last_address;
DEBUG_PRINT(sfree(p366););
printStats();
PRINT_POINTER(smalloc(112););
printStats();
void* p486 = last_address;
PRINT_POINTER(srealloc(p353,22););
printStats();
void* p487 = last_address;
DEBUG_PRINT(sfree(p363););
printStats();
PRINT_POINTER(srealloc(p225,226););
printStats();
void* p488 = last_address;
PRINT_POINTER(srealloc(p480,157););
printStats();
void* p489 = last_address;
PRINT_POINTER(scalloc(149,22););
printStats();
void* p490 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p491 = last_address;
PRINT_POINTER(scalloc(245,142););
printStats();
void* p492 = last_address;
PRINT_POINTER(scalloc(170,98););
printStats();
void* p493 = last_address;
PRINT_POINTER(scalloc(178,122););
printStats();
void* p494 = last_address;
PRINT_POINTER(scalloc(134,89););
printStats();
void* p495 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p496 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p497 = last_address;
PRINT_POINTER(scalloc(76,176););
printStats();
void* p498 = last_address;
PRINT_POINTER(scalloc(239,239););
printStats();
void* p499 = last_address;
PRINT_POINTER(srealloc(p292,38););
printStats();
void* p500 = last_address;
DEBUG_PRINT(sfree(p481););
printStats();
PRINT_POINTER(srealloc(p431,88););
printStats();
void* p501 = last_address;
DEBUG_PRINT(sfree(p412););
printStats();
DEBUG_PRINT(sfree(p466););
printStats();
PRINT_POINTER(scalloc(200,212););
printStats();
void* p502 = last_address;
PRINT_POINTER(srealloc(p462,72););
printStats();
void* p503 = last_address;
DEBUG_PRINT(sfree(p367););
printStats();
PRINT_POINTER(scalloc(17,49););
printStats();
void* p504 = last_address;
DEBUG_PRINT(sfree(p476););
printStats();
PRINT_POINTER(srealloc(p461,93););
printStats();
void* p505 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p506 = last_address;
PRINT_POINTER(scalloc(225,64););
printStats();
void* p507 = last_address;
PRINT_POINTER(scalloc(76,85););
printStats();
void* p508 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p509 = last_address;
PRINT_POINTER(srealloc(p445,27););
printStats();
void* p510 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p511 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p512 = last_address;
PRINT_POINTER(scalloc(197,94););
printStats();
void* p513 = last_address;
PRINT_POINTER(scalloc(144,133););
printStats();
void* p514 = last_address;
PRINT_POINTER(scalloc(86,145););
printStats();
void* p515 = last_address;
PRINT_POINTER(srealloc(p442,8););
printStats();
void* p516 = last_address;
PRINT_POINTER(scalloc(248,94););
printStats();
void* p517 = last_address;
DEBUG_PRINT(sfree(p304););
printStats();
PRINT_POINTER(smalloc(120););
printStats();
void* p518 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p519 = last_address;
PRINT_POINTER(srealloc(p495,124););
printStats();
void* p520 = last_address;
PRINT_POINTER(srealloc(p407,228););
printStats();
void* p521 = last_address;
DEBUG_PRINT(sfree(p362););
printStats();
PRINT_POINTER(scalloc(56,125););
printStats();
void* p522 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p523 = last_address;
PRINT_POINTER(srealloc(p470,95););
printStats();
void* p524 = last_address;
DEBUG_PRINT(sfree(p452););
printStats();
DEBUG_PRINT(sfree(p520););
printStats();
PRINT_POINTER(srealloc(p460,212););
printStats();
void* p525 = last_address;
PRINT_POINTER(srealloc(p349,219););
printStats();
void* p526 = last_address;
DEBUG_PRINT(sfree(p230););
printStats();
PRINT_POINTER(srealloc(p506,247););
printStats();
void* p527 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p528 = last_address;
DEBUG_PRINT(sfree(p483););
printStats();
DEBUG_PRINT(sfree(p508););
printStats();
DEBUG_PRINT(sfree(p228););
printStats();
PRINT_POINTER(srealloc(p454,1););
printStats();
void* p529 = last_address;
PRINT_POINTER(scalloc(93,27););
printStats();
void* p530 = last_address;
DEBUG_PRINT(sfree(p275););
printStats();
PRINT_POINTER(scalloc(166,143););
printStats();
void* p531 = last_address;
PRINT_POINTER(scalloc(129,180););
printStats();
void* p532 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p533 = last_address;
DEBUG_PRINT(sfree(p42););
printStats();
DEBUG_PRINT(sfree(p300););
printStats();
PRINT_POINTER(srealloc(p140,159););
printStats();
void* p534 = last_address;
PRINT_POINTER(srealloc(p402,59););
printStats();
void* p535 = last_address;
PRINT_POINTER(scalloc(71,106););
printStats();
void* p536 = last_address;
DEBUG_PRINT(sfree(p497););
printStats();
PRINT_POINTER(srealloc(p199,125););
printStats();
void* p537 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p538 = last_address;
PRINT_POINTER(srealloc(p393,118););
printStats();
void* p539 = last_address;
PRINT_POINTER(srealloc(p420,174););
printStats();
void* p540 = last_address;
PRINT_POINTER(scalloc(117,29););
printStats();
void* p541 = last_address;
PRINT_POINTER(srealloc(p429,91););
printStats();
void* p542 = last_address;
PRINT_POINTER(srealloc(p428,221););
printStats();
void* p543 = last_address;
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(srealloc(p453,143););
printStats();
void* p544 = last_address;
DEBUG_PRINT(sfree(p396););
printStats();
DEBUG_PRINT(sfree(p263););
printStats();
PRINT_POINTER(srealloc(p463,189););
printStats();
void* p545 = last_address;
PRINT_POINTER(srealloc(p527,18););
printStats();
void* p546 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p547 = last_address;
PRINT_POINTER(srealloc(p516,185););
printStats();
void* p548 = last_address;
PRINT_POINTER(srealloc(p449,53););
printStats();
void* p549 = last_address;
DEBUG_PRINT(sfree(p528););
printStats();
PRINT_POINTER(srealloc(p288,133););
printStats();
void* p550 = last_address;
DEBUG_PRINT(sfree(p507););
printStats();
PRINT_POINTER(smalloc(137););
printStats();
void* p551 = last_address;
DEBUG_PRINT(sfree(p538););
printStats();
DEBUG_PRINT(sfree(p418););
printStats();
PRINT_POINTER(scalloc(235,141););
printStats();
void* p552 = last_address;
PRINT_POINTER(scalloc(49,106););
printStats();
void* p553 = last_address;
PRINT_POINTER(scalloc(223,219););
printStats();
void* p554 = last_address;
DEBUG_PRINT(sfree(p514););
printStats();
PRINT_POINTER(srealloc(p132,106););
printStats();
void* p555 = last_address;
PRINT_POINTER(scalloc(195,227););
printStats();
void* p556 = last_address;
PRINT_POINTER(srealloc(p413,97););
printStats();
void* p557 = last_address;
DEBUG_PRINT(sfree(p547););
printStats();
PRINT_POINTER(srealloc(p549,207););
printStats();
void* p558 = last_address;
DEBUG_PRINT(sfree(p308););
printStats();
PRINT_POINTER(scalloc(161,5););
printStats();
void* p559 = last_address;
DEBUG_PRINT(sfree(p503););
printStats();
PRINT_POINTER(smalloc(164););
printStats();
void* p560 = last_address;
DEBUG_PRINT(sfree(p212););
printStats();
PRINT_POINTER(smalloc(121););
printStats();
void* p561 = last_address;
PRINT_POINTER(srealloc(p218,48););
printStats();
void* p562 = last_address;
PRINT_POINTER(scalloc(218,233););
printStats();
void* p563 = last_address;
DEBUG_PRINT(sfree(p478););
printStats();
PRINT_POINTER(scalloc(85,77););
printStats();
void* p564 = last_address;
PRINT_POINTER(scalloc(159,58););
printStats();
void* p565 = last_address;
PRINT_POINTER(srealloc(p446,137););
printStats();
void* p566 = last_address;
PRINT_POINTER(scalloc(63,154););
printStats();
void* p567 = last_address;
PRINT_POINTER(srealloc(p417,64););
printStats();
void* p568 = last_address;
DEBUG_PRINT(sfree(p361););
printStats();
DEBUG_PRINT(sfree(p283););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p569 = last_address;
PRINT_POINTER(scalloc(153,94););
printStats();
void* p570 = last_address;
DEBUG_PRINT(sfree(p441););
printStats();
PRINT_POINTER(smalloc(77););
printStats();
void* p571 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p572 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p573 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p574 = last_address;
PRINT_POINTER(scalloc(206,15););
printStats();
void* p575 = last_address;
PRINT_POINTER(scalloc(96,140););
printStats();
void* p576 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p577 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p578 = last_address;
DEBUG_PRINT(sfree(p436););
printStats();
DEBUG_PRINT(sfree(p328););
printStats();
DEBUG_PRINT(sfree(p368););
printStats();
PRINT_POINTER(smalloc(5););
printStats();
void* p579 = last_address;
DEBUG_PRINT(sfree(p540););
printStats();
PRINT_POINTER(smalloc(26););
printStats();
void* p580 = last_address;
PRINT_POINTER(srealloc(p569,124););
printStats();
void* p581 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p582 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p583 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p584 = last_address;
PRINT_POINTER(scalloc(128,64););
printStats();
void* p585 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p586 = last_address;
DEBUG_PRINT(sfree(p563););
printStats();
PRINT_POINTER(scalloc(144,217););
printStats();
void* p587 = last_address;
DEBUG_PRINT(sfree(p403););
printStats();
PRINT_POINTER(smalloc(138););
printStats();
void* p588 = last_address;
PRINT_POINTER(scalloc(111,3););
printStats();
void* p589 = last_address;
PRINT_POINTER(scalloc(241,119););
printStats();
void* p590 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p591 = last_address;
PRINT_POINTER(scalloc(54,56););
printStats();
void* p592 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p593 = last_address;
DEBUG_PRINT(sfree(p337););
printStats();
PRINT_POINTER(srealloc(p587,72););
printStats();
void* p594 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p595 = last_address;
PRINT_POINTER(scalloc(219,180););
printStats();
void* p596 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p597 = last_address;
PRINT_POINTER(scalloc(49,138););
printStats();
void* p598 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p599 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p600 = last_address;
PRINT_POINTER(scalloc(95,31););
printStats();
void* p601 = last_address;
DEBUG_PRINT(sfree(p154););
printStats();
PRINT_POINTER(srealloc(p421,130););
printStats();
void* p602 = last_address;
PRINT_POINTER(scalloc(134,48););
printStats();
void* p603 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p604 = last_address;
PRINT_POINTER(scalloc(194,247););
printStats();
void* p605 = last_address;
PRINT_POINTER(scalloc(16,225););
printStats();
void* p606 = last_address;
PRINT_POINTER(srealloc(p354,61););
printStats();
void* p607 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p608 = last_address;
PRINT_POINTER(srealloc(p588,28););
printStats();
void* p609 = last_address;
PRINT_POINTER(srealloc(p416,122););
printStats();
void* p610 = last_address;
PRINT_POINTER(srealloc(p472,46););
printStats();
void* p611 = last_address;
PRINT_POINTER(scalloc(151,186););
printStats();
void* p612 = last_address;
DEBUG_PRINT(sfree(p473););
printStats();
PRINT_POINTER(scalloc(59,246););
printStats();
void* p613 = last_address;
PRINT_POINTER(srealloc(p541,196););
printStats();
void* p614 = last_address;
PRINT_POINTER(srealloc(p546,75););
printStats();
void* p615 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p616 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p617 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p618 = last_address;
PRINT_POINTER(scalloc(161,60););
printStats();
void* p619 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p620 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p621 = last_address;
PRINT_POINTER(srealloc(p550,60););
printStats();
void* p622 = last_address;
DEBUG_PRINT(sfree(p580););
printStats();
DEBUG_PRINT(sfree(p594););
printStats();
PRINT_POINTER(scalloc(183,7););
printStats();
void* p623 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p624 = last_address;
PRINT_POINTER(srealloc(p552,179););
printStats();
void* p625 = last_address;
PRINT_POINTER(srealloc(p530,111););
printStats();
void* p626 = last_address;
DEBUG_PRINT(sfree(p200););
printStats();
PRINT_POINTER(srealloc(p251,23););
printStats();
void* p627 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p628 = last_address;
PRINT_POINTER(srealloc(p479,213););
printStats();
void* p629 = last_address;
DEBUG_PRINT(sfree(p465););
printStats();
PRINT_POINTER(srealloc(p321,89););
printStats();
void* p630 = last_address;
PRINT_POINTER(scalloc(154,81););
printStats();
void* p631 = last_address;
PRINT_POINTER(scalloc(202,247););
printStats();
void* p632 = last_address;
DEBUG_PRINT(sfree(p597););
printStats();
DEBUG_PRINT(sfree(p444););
printStats();
PRINT_POINTER(srealloc(p627,90););
printStats();
void* p633 = last_address;
PRINT_POINTER(srealloc(p464,152););
printStats();
void* p634 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p635 = last_address;
PRINT_POINTER(srealloc(p599,249););
printStats();
void* p636 = last_address;
PRINT_POINTER(srealloc(p526,142););
printStats();
void* p637 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p638 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p639 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p640 = last_address;
PRINT_POINTER(scalloc(108,28););
printStats();
void* p641 = last_address;
PRINT_POINTER(srealloc(p432,11););
printStats();
void* p642 = last_address;
PRINT_POINTER(scalloc(63,194););
printStats();
void* p643 = last_address;
PRINT_POINTER(scalloc(228,56););
printStats();
void* p644 = last_address;
PRINT_POINTER(srealloc(p593,143););
printStats();
void* p645 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p646 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p647 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p648 = last_address;
PRINT_POINTER(srealloc(p625,74););
printStats();
void* p649 = last_address;
PRINT_POINTER(scalloc(194,18););
printStats();
void* p650 = last_address;
DEBUG_PRINT(sfree(p375););
printStats();
PRINT_POINTER(smalloc(198););
printStats();
void* p651 = last_address;
PRINT_POINTER(scalloc(204,53););
printStats();
void* p652 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
DEBUG_PRINT(sfree(p615););
printStats();
PRINT_POINTER(scalloc(75,54););
printStats();
void* p653 = last_address;
DEBUG_PRINT(sfree(p628););
printStats();
}
