#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(109,5););
printStats();
void* p0 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(scalloc(130,15););
printStats();
void* p2 = last_address;
PRINT_POINTER(scalloc(52,140););
printStats();
void* p3 = last_address;
PRINT_POINTER(srealloc(p2,22););
printStats();
void* p4 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p5 = last_address;
PRINT_POINTER(srealloc(p5,153););
printStats();
void* p6 = last_address;
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(scalloc(119,216););
printStats();
void* p7 = last_address;
PRINT_POINTER(srealloc(p7,12););
printStats();
void* p8 = last_address;
PRINT_POINTER(scalloc(85,33););
printStats();
void* p9 = last_address;
PRINT_POINTER(scalloc(123,94););
printStats();
void* p10 = last_address;
PRINT_POINTER(scalloc(108,1););
printStats();
void* p11 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
PRINT_POINTER(smalloc(35););
printStats();
void* p12 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p13 = last_address;
PRINT_POINTER(srealloc(p9,227););
printStats();
void* p14 = last_address;
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(scalloc(19,236););
printStats();
void* p15 = last_address;
PRINT_POINTER(srealloc(p13,227););
printStats();
void* p16 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(srealloc(p12,188););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(169,74););
printStats();
void* p18 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p20 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p21 = last_address;
PRINT_POINTER(scalloc(164,5););
printStats();
void* p22 = last_address;
PRINT_POINTER(scalloc(150,147););
printStats();
void* p23 = last_address;
PRINT_POINTER(scalloc(146,0););
printStats();
void* p24 = last_address;
DEBUG_PRINT(sfree(p23););
printStats();
DEBUG_PRINT(sfree(p19););
printStats();
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(scalloc(98,149););
printStats();
void* p25 = last_address;
PRINT_POINTER(srealloc(p18,123););
printStats();
void* p26 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
PRINT_POINTER(scalloc(3,141););
printStats();
void* p27 = last_address;
PRINT_POINTER(srealloc(p26,48););
printStats();
void* p28 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p29 = last_address;
PRINT_POINTER(srealloc(p27,187););
printStats();
void* p30 = last_address;
PRINT_POINTER(srealloc(p22,14););
printStats();
void* p31 = last_address;
PRINT_POINTER(scalloc(233,49););
printStats();
void* p32 = last_address;
PRINT_POINTER(scalloc(74,121););
printStats();
void* p33 = last_address;
DEBUG_PRINT(sfree(p30););
printStats();
DEBUG_PRINT(sfree(p29););
printStats();
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(srealloc(p10,134););
printStats();
void* p34 = last_address;
PRINT_POINTER(scalloc(119,172););
printStats();
void* p35 = last_address;
PRINT_POINTER(scalloc(224,176););
printStats();
void* p36 = last_address;
PRINT_POINTER(scalloc(9,8););
printStats();
void* p37 = last_address;
PRINT_POINTER(srealloc(p20,193););
printStats();
void* p38 = last_address;
PRINT_POINTER(scalloc(63,28););
printStats();
void* p39 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(smalloc(89););
printStats();
void* p40 = last_address;
DEBUG_PRINT(sfree(p35););
printStats();
PRINT_POINTER(scalloc(37,48););
printStats();
void* p41 = last_address;
PRINT_POINTER(scalloc(217,137););
printStats();
void* p42 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p43 = last_address;
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(srealloc(p42,220););
printStats();
void* p44 = last_address;
PRINT_POINTER(scalloc(91,14););
printStats();
void* p45 = last_address;
PRINT_POINTER(scalloc(180,88););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p47 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p48 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(srealloc(p37,171););
printStats();
void* p49 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
PRINT_POINTER(scalloc(62,107););
printStats();
void* p50 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(scalloc(123,6););
printStats();
void* p51 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p52 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p53 = last_address;
PRINT_POINTER(scalloc(76,201););
printStats();
void* p54 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
DEBUG_PRINT(sfree(p49););
printStats();
DEBUG_PRINT(sfree(p53););
printStats();
PRINT_POINTER(scalloc(1,208););
printStats();
void* p55 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
PRINT_POINTER(scalloc(71,164););
printStats();
void* p56 = last_address;
PRINT_POINTER(scalloc(8,132););
printStats();
void* p57 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p58 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
PRINT_POINTER(scalloc(2,65););
printStats();
void* p59 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p60 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p61 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p62 = last_address;
PRINT_POINTER(srealloc(p60,126););
printStats();
void* p63 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p64 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p65 = last_address;
DEBUG_PRINT(sfree(p65););
printStats();
PRINT_POINTER(srealloc(p63,61););
printStats();
void* p66 = last_address;
PRINT_POINTER(srealloc(p16,216););
printStats();
void* p67 = last_address;
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(scalloc(168,30););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p33,18););
printStats();
void* p69 = last_address;
PRINT_POINTER(scalloc(116,98););
printStats();
void* p70 = last_address;
PRINT_POINTER(scalloc(174,177););
printStats();
void* p71 = last_address;
PRINT_POINTER(scalloc(177,182););
printStats();
void* p72 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(smalloc(68););
printStats();
void* p73 = last_address;
DEBUG_PRINT(sfree(p40););
printStats();
DEBUG_PRINT(sfree(p48););
printStats();
PRINT_POINTER(scalloc(148,8););
printStats();
void* p74 = last_address;
PRINT_POINTER(srealloc(p74,23););
printStats();
void* p75 = last_address;
DEBUG_PRINT(sfree(p71););
printStats();
PRINT_POINTER(scalloc(12,90););
printStats();
void* p76 = last_address;
DEBUG_PRINT(sfree(p3););
printStats();
PRINT_POINTER(smalloc(38););
printStats();
void* p77 = last_address;
PRINT_POINTER(srealloc(p69,34););
printStats();
void* p78 = last_address;
PRINT_POINTER(srealloc(p56,138););
printStats();
void* p79 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
PRINT_POINTER(srealloc(p77,56););
printStats();
void* p80 = last_address;
PRINT_POINTER(scalloc(151,8););
printStats();
void* p81 = last_address;
PRINT_POINTER(srealloc(p44,5););
printStats();
void* p82 = last_address;
PRINT_POINTER(srealloc(p55,159););
printStats();
void* p83 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p84 = last_address;
PRINT_POINTER(scalloc(95,93););
printStats();
void* p85 = last_address;
PRINT_POINTER(srealloc(p67,74););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p84,208););
printStats();
void* p87 = last_address;
PRINT_POINTER(srealloc(p78,208););
printStats();
void* p88 = last_address;
PRINT_POINTER(srealloc(p62,173););
printStats();
void* p89 = last_address;
PRINT_POINTER(srealloc(p58,192););
printStats();
void* p90 = last_address;
PRINT_POINTER(srealloc(p59,82););
printStats();
void* p91 = last_address;
PRINT_POINTER(srealloc(p83,163););
printStats();
void* p92 = last_address;
PRINT_POINTER(scalloc(218,201););
printStats();
void* p93 = last_address;
DEBUG_PRINT(sfree(p57););
printStats();
PRINT_POINTER(scalloc(166,109););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p95 = last_address;
PRINT_POINTER(scalloc(189,65););
printStats();
void* p96 = last_address;
DEBUG_PRINT(sfree(p96););
printStats();
PRINT_POINTER(srealloc(p79,197););
printStats();
void* p97 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p98 = last_address;
PRINT_POINTER(srealloc(p90,118););
printStats();
void* p99 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p100 = last_address;
PRINT_POINTER(scalloc(48,146););
printStats();
void* p101 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p102 = last_address;
DEBUG_PRINT(sfree(p95););
printStats();
PRINT_POINTER(srealloc(p89,62););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p76,192););
printStats();
void* p104 = last_address;
PRINT_POINTER(srealloc(p81,11););
printStats();
void* p105 = last_address;
PRINT_POINTER(scalloc(193,49););
printStats();
void* p106 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p107 = last_address;
PRINT_POINTER(scalloc(108,196););
printStats();
void* p108 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p109 = last_address;
PRINT_POINTER(srealloc(p91,61););
printStats();
void* p110 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(scalloc(167,105););
printStats();
void* p111 = last_address;
DEBUG_PRINT(sfree(p47););
printStats();
PRINT_POINTER(smalloc(105););
printStats();
void* p112 = last_address;
PRINT_POINTER(scalloc(134,121););
printStats();
void* p113 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p114 = last_address;
PRINT_POINTER(srealloc(p66,16););
printStats();
void* p115 = last_address;
DEBUG_PRINT(sfree(p54););
printStats();
PRINT_POINTER(srealloc(p92,103););
printStats();
void* p116 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
PRINT_POINTER(smalloc(132););
printStats();
void* p117 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p118 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
DEBUG_PRINT(sfree(p73););
printStats();
PRINT_POINTER(smalloc(94););
printStats();
void* p119 = last_address;
DEBUG_PRINT(sfree(p108););
printStats();
PRINT_POINTER(scalloc(205,87););
printStats();
void* p120 = last_address;
PRINT_POINTER(srealloc(p87,240););
printStats();
void* p121 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(srealloc(p105,200););
printStats();
void* p122 = last_address;
PRINT_POINTER(srealloc(p112,125););
printStats();
void* p123 = last_address;
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(scalloc(7,193););
printStats();
void* p124 = last_address;
PRINT_POINTER(srealloc(p99,30););
printStats();
void* p125 = last_address;
PRINT_POINTER(srealloc(p120,168););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(70,118););
printStats();
void* p127 = last_address;
PRINT_POINTER(scalloc(63,59););
printStats();
void* p128 = last_address;
DEBUG_PRINT(sfree(p117););
printStats();
DEBUG_PRINT(sfree(p128););
printStats();
PRINT_POINTER(smalloc(112););
printStats();
void* p129 = last_address;
PRINT_POINTER(scalloc(42,126););
printStats();
void* p130 = last_address;
PRINT_POINTER(srealloc(p104,153););
printStats();
void* p131 = last_address;
PRINT_POINTER(scalloc(181,111););
printStats();
void* p132 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p133 = last_address;
DEBUG_PRINT(sfree(p131););
printStats();
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(srealloc(p68,63););
printStats();
void* p134 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p135 = last_address;
PRINT_POINTER(scalloc(10,5););
printStats();
void* p136 = last_address;
PRINT_POINTER(srealloc(p100,15););
printStats();
void* p137 = last_address;
PRINT_POINTER(scalloc(102,11););
printStats();
void* p138 = last_address;
DEBUG_PRINT(sfree(p129););
printStats();
PRINT_POINTER(srealloc(p125,137););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p133););
printStats();
PRINT_POINTER(scalloc(247,237););
printStats();
void* p140 = last_address;
PRINT_POINTER(srealloc(p93,41););
printStats();
void* p141 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p142 = last_address;
DEBUG_PRINT(sfree(p111););
printStats();
PRINT_POINTER(scalloc(75,5););
printStats();
void* p143 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p144 = last_address;
PRINT_POINTER(srealloc(p136,23););
printStats();
void* p145 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(smalloc(206););
printStats();
void* p146 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p147 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p148 = last_address;
PRINT_POINTER(srealloc(p113,47););
printStats();
void* p149 = last_address;
DEBUG_PRINT(sfree(p75););
printStats();
PRINT_POINTER(scalloc(30,89););
printStats();
void* p150 = last_address;
PRINT_POINTER(scalloc(61,75););
printStats();
void* p151 = last_address;
PRINT_POINTER(srealloc(p143,72););
printStats();
void* p152 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(srealloc(p146,154););
printStats();
void* p153 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p154 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(smalloc(175););
printStats();
void* p155 = last_address;
PRINT_POINTER(srealloc(p126,93););
printStats();
void* p156 = last_address;
PRINT_POINTER(srealloc(p115,209););
printStats();
void* p157 = last_address;
PRINT_POINTER(scalloc(74,94););
printStats();
void* p158 = last_address;
PRINT_POINTER(scalloc(189,42););
printStats();
void* p159 = last_address;
PRINT_POINTER(smalloc(80););
printStats();
void* p160 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p161 = last_address;
PRINT_POINTER(srealloc(p152,72););
printStats();
void* p162 = last_address;
PRINT_POINTER(scalloc(35,65););
printStats();
void* p163 = last_address;
PRINT_POINTER(srealloc(p141,121););
printStats();
void* p164 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p165 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(srealloc(p154,8););
printStats();
void* p166 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p167 = last_address;
PRINT_POINTER(srealloc(p159,186););
printStats();
void* p168 = last_address;
PRINT_POINTER(srealloc(p162,102););
printStats();
void* p169 = last_address;
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(scalloc(200,14););
printStats();
void* p170 = last_address;
PRINT_POINTER(scalloc(123,137););
printStats();
void* p171 = last_address;
PRINT_POINTER(srealloc(p167,181););
printStats();
void* p172 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p173 = last_address;
DEBUG_PRINT(sfree(p140););
printStats();
PRINT_POINTER(scalloc(213,182););
printStats();
void* p174 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p175 = last_address;
PRINT_POINTER(srealloc(p147,49););
printStats();
void* p176 = last_address;
DEBUG_PRINT(sfree(p156););
printStats();
PRINT_POINTER(srealloc(p61,30););
printStats();
void* p177 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(scalloc(3,235););
printStats();
void* p178 = last_address;
DEBUG_PRINT(sfree(p144););
printStats();
DEBUG_PRINT(sfree(p168););
printStats();
DEBUG_PRINT(sfree(p149););
printStats();
DEBUG_PRINT(sfree(p153););
printStats();
PRINT_POINTER(srealloc(p107,43););
printStats();
void* p179 = last_address;
DEBUG_PRINT(sfree(p163););
printStats();
DEBUG_PRINT(sfree(p103););
printStats();
PRINT_POINTER(srealloc(p52,246););
printStats();
void* p180 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p181 = last_address;
PRINT_POINTER(srealloc(p174,63););
printStats();
void* p182 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p183 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p184 = last_address;
PRINT_POINTER(scalloc(93,190););
printStats();
void* p185 = last_address;
PRINT_POINTER(scalloc(124,178););
printStats();
void* p186 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p187 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p188 = last_address;
PRINT_POINTER(srealloc(p186,35););
printStats();
void* p189 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p190 = last_address;
DEBUG_PRINT(sfree(p121););
printStats();
PRINT_POINTER(smalloc(0););
printStats();
void* p191 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
DEBUG_PRINT(sfree(p161););
printStats();
PRINT_POINTER(srealloc(p106,103););
printStats();
void* p192 = last_address;
PRINT_POINTER(srealloc(p137,6););
printStats();
void* p193 = last_address;
PRINT_POINTER(scalloc(151,43););
printStats();
void* p194 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
PRINT_POINTER(srealloc(p122,240););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(smalloc(151););
printStats();
void* p196 = last_address;
PRINT_POINTER(srealloc(p32,183););
printStats();
void* p197 = last_address;
PRINT_POINTER(srealloc(p31,219););
printStats();
void* p198 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p199 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p200 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p201 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p202 = last_address;
PRINT_POINTER(srealloc(p189,27););
printStats();
void* p203 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p204 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p205 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p206 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p207 = last_address;
PRINT_POINTER(smalloc(221););
printStats();
void* p208 = last_address;
PRINT_POINTER(srealloc(p164,217););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(86,221););
printStats();
void* p210 = last_address;
PRINT_POINTER(scalloc(56,200););
printStats();
void* p211 = last_address;
DEBUG_PRINT(sfree(p88););
printStats();
PRINT_POINTER(smalloc(134););
printStats();
void* p212 = last_address;
PRINT_POINTER(scalloc(123,2););
printStats();
void* p213 = last_address;
PRINT_POINTER(scalloc(114,135););
printStats();
void* p214 = last_address;
PRINT_POINTER(srealloc(p198,25););
printStats();
void* p215 = last_address;
PRINT_POINTER(scalloc(212,206););
printStats();
void* p216 = last_address;
PRINT_POINTER(srealloc(p216,214););
printStats();
void* p217 = last_address;
PRINT_POINTER(scalloc(20,137););
printStats();
void* p218 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p219 = last_address;
DEBUG_PRINT(sfree(p185););
printStats();
PRINT_POINTER(scalloc(37,157););
printStats();
void* p220 = last_address;
DEBUG_PRINT(sfree(p201););
printStats();
DEBUG_PRINT(sfree(p145););
printStats();
PRINT_POINTER(srealloc(p213,249););
printStats();
void* p221 = last_address;
DEBUG_PRINT(sfree(p182););
printStats();
PRINT_POINTER(srealloc(p139,59););
printStats();
void* p222 = last_address;
PRINT_POINTER(srealloc(p200,220););
printStats();
void* p223 = last_address;
PRINT_POINTER(srealloc(p101,126););
printStats();
void* p224 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(srealloc(p205,224););
printStats();
void* p225 = last_address;
PRINT_POINTER(srealloc(p215,179););
printStats();
void* p226 = last_address;
PRINT_POINTER(scalloc(249,82););
printStats();
void* p227 = last_address;
PRINT_POINTER(srealloc(p212,11););
printStats();
void* p228 = last_address;
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(srealloc(p211,218););
printStats();
void* p229 = last_address;
PRINT_POINTER(scalloc(95,144););
printStats();
void* p230 = last_address;
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(smalloc(68););
printStats();
void* p231 = last_address;
PRINT_POINTER(srealloc(p110,108););
printStats();
void* p232 = last_address;
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(scalloc(215,18););
printStats();
void* p233 = last_address;
PRINT_POINTER(srealloc(p127,30););
printStats();
void* p234 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p235 = last_address;
PRINT_POINTER(scalloc(101,0););
printStats();
void* p236 = last_address;
PRINT_POINTER(srealloc(p4,149););
printStats();
void* p237 = last_address;
DEBUG_PRINT(sfree(p230););
printStats();
PRINT_POINTER(smalloc(94););
printStats();
void* p238 = last_address;
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(smalloc(159););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p135,91););
printStats();
void* p240 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p241 = last_address;
PRINT_POINTER(srealloc(p207,226););
printStats();
void* p242 = last_address;
PRINT_POINTER(srealloc(p170,123););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p241););
printStats();
PRINT_POINTER(srealloc(p222,135););
printStats();
void* p244 = last_address;
PRINT_POINTER(srealloc(p202,152););
printStats();
void* p245 = last_address;
DEBUG_PRINT(sfree(p208););
printStats();
PRINT_POINTER(smalloc(94););
printStats();
void* p246 = last_address;
DEBUG_PRINT(sfree(p235););
printStats();
PRINT_POINTER(scalloc(13,93););
printStats();
void* p247 = last_address;
PRINT_POINTER(scalloc(187,116););
printStats();
void* p248 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(srealloc(p160,236););
printStats();
void* p249 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p250 = last_address;
PRINT_POINTER(srealloc(p180,55););
printStats();
void* p251 = last_address;
PRINT_POINTER(scalloc(168,178););
printStats();
void* p252 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p253 = last_address;
PRINT_POINTER(srealloc(p178,38););
printStats();
void* p254 = last_address;
PRINT_POINTER(srealloc(p225,103););
printStats();
void* p255 = last_address;
PRINT_POINTER(scalloc(33,8););
printStats();
void* p256 = last_address;
PRINT_POINTER(srealloc(p236,92););
printStats();
void* p257 = last_address;
PRINT_POINTER(scalloc(78,161););
printStats();
void* p258 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p259 = last_address;
DEBUG_PRINT(sfree(p245););
printStats();
PRINT_POINTER(srealloc(p224,63););
printStats();
void* p260 = last_address;
PRINT_POINTER(scalloc(199,101););
printStats();
void* p261 = last_address;
DEBUG_PRINT(sfree(p82););
printStats();
PRINT_POINTER(scalloc(181,59););
printStats();
void* p262 = last_address;
PRINT_POINTER(scalloc(165,226););
printStats();
void* p263 = last_address;
PRINT_POINTER(srealloc(p234,185););
printStats();
void* p264 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p265 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p266 = last_address;
PRINT_POINTER(scalloc(4,171););
printStats();
void* p267 = last_address;
PRINT_POINTER(srealloc(p169,191););
printStats();
void* p268 = last_address;
PRINT_POINTER(srealloc(p166,175););
printStats();
void* p269 = last_address;
DEBUG_PRINT(sfree(p258););
printStats();
PRINT_POINTER(srealloc(p261,88););
printStats();
void* p270 = last_address;
PRINT_POINTER(srealloc(p195,211););
printStats();
void* p271 = last_address;
PRINT_POINTER(scalloc(65,222););
printStats();
void* p272 = last_address;
PRINT_POINTER(scalloc(48,101););
printStats();
void* p273 = last_address;
DEBUG_PRINT(sfree(p157););
printStats();
PRINT_POINTER(smalloc(116););
printStats();
void* p274 = last_address;
PRINT_POINTER(srealloc(p242,225););
printStats();
void* p275 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p276 = last_address;
DEBUG_PRINT(sfree(p255););
printStats();
PRINT_POINTER(scalloc(148,141););
printStats();
void* p277 = last_address;
DEBUG_PRINT(sfree(p238););
printStats();
PRINT_POINTER(srealloc(p142,214););
printStats();
void* p278 = last_address;
PRINT_POINTER(srealloc(p256,96););
printStats();
void* p279 = last_address;
PRINT_POINTER(srealloc(p259,137););
printStats();
void* p280 = last_address;
DEBUG_PRINT(sfree(p191););
printStats();
DEBUG_PRINT(sfree(p270););
printStats();
PRINT_POINTER(scalloc(52,172););
printStats();
void* p281 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p282 = last_address;
DEBUG_PRINT(sfree(p228););
printStats();
PRINT_POINTER(smalloc(74););
printStats();
void* p283 = last_address;
DEBUG_PRINT(sfree(p233););
printStats();
DEBUG_PRINT(sfree(p279););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p284 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p285 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p286 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p287 = last_address;
PRINT_POINTER(srealloc(p266,126););
printStats();
void* p288 = last_address;
PRINT_POINTER(srealloc(p251,102););
printStats();
void* p289 = last_address;
PRINT_POINTER(scalloc(78,228););
printStats();
void* p290 = last_address;
PRINT_POINTER(srealloc(p203,1););
printStats();
void* p291 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p292 = last_address;
PRINT_POINTER(srealloc(p130,79););
printStats();
void* p293 = last_address;
DEBUG_PRINT(sfree(p262););
printStats();
PRINT_POINTER(scalloc(121,85););
printStats();
void* p294 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p295 = last_address;
DEBUG_PRINT(sfree(p278););
printStats();
PRINT_POINTER(scalloc(231,160););
printStats();
void* p296 = last_address;
PRINT_POINTER(srealloc(p291,123););
printStats();
void* p297 = last_address;
DEBUG_PRINT(sfree(p158););
printStats();
DEBUG_PRINT(sfree(p226););
printStats();
PRINT_POINTER(smalloc(117););
printStats();
void* p298 = last_address;
DEBUG_PRINT(sfree(p237););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p299 = last_address;
PRINT_POINTER(scalloc(52,52););
printStats();
void* p300 = last_address;
DEBUG_PRINT(sfree(p280););
printStats();
DEBUG_PRINT(sfree(p165););
printStats();
PRINT_POINTER(smalloc(152););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p302 = last_address;
DEBUG_PRINT(sfree(p194););
printStats();
PRINT_POINTER(scalloc(151,50););
printStats();
void* p303 = last_address;
DEBUG_PRINT(sfree(p289););
printStats();
PRINT_POINTER(smalloc(126););
printStats();
void* p304 = last_address;
PRINT_POINTER(srealloc(p204,198););
printStats();
void* p305 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(smalloc(117););
printStats();
void* p306 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p307 = last_address;
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p308 = last_address;
PRINT_POINTER(srealloc(p305,239););
printStats();
void* p309 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p310 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p311 = last_address;
DEBUG_PRINT(sfree(p268););
printStats();
PRINT_POINTER(smalloc(219););
printStats();
void* p312 = last_address;
PRINT_POINTER(scalloc(22,212););
printStats();
void* p313 = last_address;
PRINT_POINTER(srealloc(p297,245););
printStats();
void* p314 = last_address;
PRINT_POINTER(srealloc(p172,96););
printStats();
void* p315 = last_address;
PRINT_POINTER(srealloc(p177,24););
printStats();
void* p316 = last_address;
PRINT_POINTER(scalloc(91,158););
printStats();
void* p317 = last_address;
PRINT_POINTER(srealloc(p217,217););
printStats();
void* p318 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p319 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p320 = last_address;
PRINT_POINTER(srealloc(p273,80););
printStats();
void* p321 = last_address;
PRINT_POINTER(srealloc(p171,230););
printStats();
void* p322 = last_address;
DEBUG_PRINT(sfree(p269););
printStats();
PRINT_POINTER(srealloc(p151,68););
printStats();
void* p323 = last_address;
DEBUG_PRINT(sfree(p263););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p324 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
DEBUG_PRINT(sfree(p219););
printStats();
DEBUG_PRINT(sfree(p307););
printStats();
PRINT_POINTER(srealloc(p277,214););
printStats();
void* p325 = last_address;
PRINT_POINTER(srealloc(p299,81););
printStats();
void* p326 = last_address;
PRINT_POINTER(scalloc(71,234););
printStats();
void* p327 = last_address;
PRINT_POINTER(scalloc(63,209););
printStats();
void* p328 = last_address;
PRINT_POINTER(scalloc(131,68););
printStats();
void* p329 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p330 = last_address;
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(scalloc(213,221););
printStats();
void* p331 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p332 = last_address;
PRINT_POINTER(srealloc(p321,141););
printStats();
void* p333 = last_address;
PRINT_POINTER(srealloc(p248,112););
printStats();
void* p334 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p335 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p336 = last_address;
DEBUG_PRINT(sfree(p80););
printStats();
PRINT_POINTER(scalloc(26,93););
printStats();
void* p337 = last_address;
PRINT_POINTER(srealloc(p283,61););
printStats();
void* p338 = last_address;
DEBUG_PRINT(sfree(p300););
printStats();
PRINT_POINTER(smalloc(18););
printStats();
void* p339 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p340 = last_address;
DEBUG_PRINT(sfree(p303););
printStats();
PRINT_POINTER(smalloc(8););
printStats();
void* p341 = last_address;
PRINT_POINTER(srealloc(p296,237););
printStats();
void* p342 = last_address;
PRINT_POINTER(srealloc(p284,8););
printStats();
void* p343 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p344 = last_address;
DEBUG_PRINT(sfree(p319););
printStats();
DEBUG_PRINT(sfree(p276););
printStats();
PRINT_POINTER(smalloc(189););
printStats();
void* p345 = last_address;
PRINT_POINTER(srealloc(p232,146););
printStats();
void* p346 = last_address;
PRINT_POINTER(scalloc(196,19););
printStats();
void* p347 = last_address;
PRINT_POINTER(srealloc(p155,192););
printStats();
void* p348 = last_address;
PRINT_POINTER(srealloc(p190,103););
printStats();
void* p349 = last_address;
DEBUG_PRINT(sfree(p274););
printStats();
DEBUG_PRINT(sfree(p102););
printStats();
PRINT_POINTER(srealloc(p322,52););
printStats();
void* p350 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p351 = last_address;
PRINT_POINTER(srealloc(p214,52););
printStats();
void* p352 = last_address;
PRINT_POINTER(scalloc(107,17););
printStats();
void* p353 = last_address;
PRINT_POINTER(srealloc(p337,191););
printStats();
void* p354 = last_address;
PRINT_POINTER(scalloc(67,106););
printStats();
void* p355 = last_address;
PRINT_POINTER(scalloc(92,193););
printStats();
void* p356 = last_address;
DEBUG_PRINT(sfree(p320););
printStats();
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(srealloc(p302,208););
printStats();
void* p357 = last_address;
PRINT_POINTER(scalloc(152,26););
printStats();
void* p358 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p359 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p360 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p361 = last_address;
PRINT_POINTER(scalloc(1,215););
printStats();
void* p362 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p363 = last_address;
PRINT_POINTER(scalloc(190,88););
printStats();
void* p364 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p365 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p366 = last_address;
PRINT_POINTER(scalloc(213,246););
printStats();
void* p367 = last_address;
PRINT_POINTER(srealloc(p179,11););
printStats();
void* p368 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p369 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(srealloc(p281,173););
printStats();
void* p370 = last_address;
DEBUG_PRINT(sfree(p326););
printStats();
PRINT_POINTER(scalloc(49,116););
printStats();
void* p371 = last_address;
PRINT_POINTER(scalloc(23,154););
printStats();
void* p372 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p373 = last_address;
PRINT_POINTER(scalloc(99,50););
printStats();
void* p374 = last_address;
PRINT_POINTER(srealloc(p325,226););
printStats();
void* p375 = last_address;
PRINT_POINTER(srealloc(p221,138););
printStats();
void* p376 = last_address;
PRINT_POINTER(scalloc(208,18););
printStats();
void* p377 = last_address;
DEBUG_PRINT(sfree(p206););
printStats();
PRINT_POINTER(srealloc(p323,246););
printStats();
void* p378 = last_address;
PRINT_POINTER(srealloc(p247,81););
printStats();
void* p379 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p380 = last_address;
PRINT_POINTER(scalloc(119,64););
printStats();
void* p381 = last_address;
DEBUG_PRINT(sfree(p292););
printStats();
PRINT_POINTER(smalloc(135););
printStats();
void* p382 = last_address;
PRINT_POINTER(scalloc(35,96););
printStats();
void* p383 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p384 = last_address;
PRINT_POINTER(srealloc(p227,215););
printStats();
void* p385 = last_address;
PRINT_POINTER(scalloc(121,8););
printStats();
void* p386 = last_address;
PRINT_POINTER(scalloc(223,28););
printStats();
void* p387 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p388 = last_address;
DEBUG_PRINT(sfree(p370););
printStats();
PRINT_POINTER(scalloc(126,231););
printStats();
void* p389 = last_address;
PRINT_POINTER(srealloc(p311,100););
printStats();
void* p390 = last_address;
DEBUG_PRINT(sfree(p360););
printStats();
PRINT_POINTER(smalloc(224););
printStats();
void* p391 = last_address;
PRINT_POINTER(srealloc(p310,201););
printStats();
void* p392 = last_address;
PRINT_POINTER(srealloc(p295,153););
printStats();
void* p393 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p394 = last_address;
PRINT_POINTER(scalloc(241,222););
printStats();
void* p395 = last_address;
PRINT_POINTER(srealloc(p338,170););
printStats();
void* p396 = last_address;
PRINT_POINTER(srealloc(p246,45););
printStats();
void* p397 = last_address;
DEBUG_PRINT(sfree(p298););
printStats();
PRINT_POINTER(smalloc(108););
printStats();
void* p398 = last_address;
PRINT_POINTER(srealloc(p332,231););
printStats();
void* p399 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p400 = last_address;
PRINT_POINTER(srealloc(p398,179););
printStats();
void* p401 = last_address;
DEBUG_PRINT(sfree(p275););
printStats();
PRINT_POINTER(smalloc(120););
printStats();
void* p402 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p403 = last_address;
DEBUG_PRINT(sfree(p361););
printStats();
PRINT_POINTER(scalloc(247,69););
printStats();
void* p404 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p405 = last_address;
PRINT_POINTER(scalloc(201,239););
printStats();
void* p406 = last_address;
PRINT_POINTER(srealloc(p401,61););
printStats();
void* p407 = last_address;
DEBUG_PRINT(sfree(p265););
printStats();
PRINT_POINTER(smalloc(211););
printStats();
void* p408 = last_address;
PRINT_POINTER(scalloc(214,116););
printStats();
void* p409 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p410 = last_address;
DEBUG_PRINT(sfree(p331););
printStats();
PRINT_POINTER(srealloc(p45,21););
printStats();
void* p411 = last_address;
PRINT_POINTER(scalloc(116,172););
printStats();
void* p412 = last_address;
DEBUG_PRINT(sfree(p193););
printStats();
PRINT_POINTER(scalloc(135,161););
printStats();
void* p413 = last_address;
PRINT_POINTER(srealloc(p371,248););
printStats();
void* p414 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p415 = last_address;
PRINT_POINTER(srealloc(p264,170););
printStats();
void* p416 = last_address;
DEBUG_PRINT(sfree(p324););
printStats();
PRINT_POINTER(srealloc(p318,19););
printStats();
void* p417 = last_address;
PRINT_POINTER(scalloc(190,107););
printStats();
void* p418 = last_address;
PRINT_POINTER(srealloc(p366,194););
printStats();
void* p419 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p420 = last_address;
DEBUG_PRINT(sfree(p188););
printStats();
PRINT_POINTER(scalloc(69,240););
printStats();
void* p421 = last_address;
PRINT_POINTER(scalloc(237,28););
printStats();
void* p422 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p423 = last_address;
PRINT_POINTER(srealloc(p382,63););
printStats();
void* p424 = last_address;
PRINT_POINTER(srealloc(p355,212););
printStats();
void* p425 = last_address;
PRINT_POINTER(scalloc(171,236););
printStats();
void* p426 = last_address;
DEBUG_PRINT(sfree(p288););
printStats();
DEBUG_PRINT(sfree(p192););
printStats();
DEBUG_PRINT(sfree(p375););
printStats();
PRINT_POINTER(smalloc(239););
printStats();
void* p427 = last_address;
PRINT_POINTER(srealloc(p304,23););
printStats();
void* p428 = last_address;
PRINT_POINTER(scalloc(131,128););
printStats();
void* p429 = last_address;
PRINT_POINTER(srealloc(p390,156););
printStats();
void* p430 = last_address;
PRINT_POINTER(srealloc(p402,52););
printStats();
void* p431 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p432 = last_address;
PRINT_POINTER(srealloc(p404,182););
printStats();
void* p433 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p434 = last_address;
DEBUG_PRINT(sfree(p397););
printStats();
PRINT_POINTER(smalloc(144););
printStats();
void* p435 = last_address;
PRINT_POINTER(scalloc(234,208););
printStats();
void* p436 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p437 = last_address;
DEBUG_PRINT(sfree(p437););
printStats();
PRINT_POINTER(scalloc(161,238););
printStats();
void* p438 = last_address;
PRINT_POINTER(srealloc(p301,213););
printStats();
void* p439 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p440 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p441 = last_address;
PRINT_POINTER(srealloc(p132,227););
printStats();
void* p442 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p443 = last_address;
PRINT_POINTER(scalloc(225,163););
printStats();
void* p444 = last_address;
PRINT_POINTER(srealloc(p249,82););
printStats();
void* p445 = last_address;
DEBUG_PRINT(sfree(p441););
printStats();
PRINT_POINTER(smalloc(51););
printStats();
void* p446 = last_address;
PRINT_POINTER(scalloc(170,191););
printStats();
void* p447 = last_address;
PRINT_POINTER(srealloc(p399,97););
printStats();
void* p448 = last_address;
DEBUG_PRINT(sfree(p423););
printStats();
PRINT_POINTER(srealloc(p348,33););
printStats();
void* p449 = last_address;
PRINT_POINTER(scalloc(132,1););
printStats();
void* p450 = last_address;
PRINT_POINTER(srealloc(p405,132););
printStats();
void* p451 = last_address;
DEBUG_PRINT(sfree(p362););
printStats();
PRINT_POINTER(smalloc(183););
printStats();
void* p452 = last_address;
PRINT_POINTER(scalloc(107,186););
printStats();
void* p453 = last_address;
PRINT_POINTER(scalloc(233,117););
printStats();
void* p454 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p455 = last_address;
PRINT_POINTER(srealloc(p339,170););
printStats();
void* p456 = last_address;
DEBUG_PRINT(sfree(p333););
printStats();
DEBUG_PRINT(sfree(p272););
printStats();
PRINT_POINTER(scalloc(172,109););
printStats();
void* p457 = last_address;
DEBUG_PRINT(sfree(p429););
printStats();
PRINT_POINTER(smalloc(70););
printStats();
void* p458 = last_address;
PRINT_POINTER(srealloc(p359,55););
printStats();
void* p459 = last_address;
PRINT_POINTER(scalloc(161,242););
printStats();
void* p460 = last_address;
PRINT_POINTER(scalloc(199,9););
printStats();
void* p461 = last_address;
PRINT_POINTER(scalloc(0,118););
printStats();
void* p462 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p463 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p464 = last_address;
DEBUG_PRINT(sfree(p452););
printStats();
PRINT_POINTER(srealloc(p229,239););
printStats();
void* p465 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p466 = last_address;
PRINT_POINTER(scalloc(54,59););
printStats();
void* p467 = last_address;
PRINT_POINTER(srealloc(p353,210););
printStats();
void* p468 = last_address;
PRINT_POINTER(scalloc(169,91););
printStats();
void* p469 = last_address;
PRINT_POINTER(srealloc(p187,173););
printStats();
void* p470 = last_address;
PRINT_POINTER(scalloc(59,140););
printStats();
void* p471 = last_address;
DEBUG_PRINT(sfree(p267););
printStats();
PRINT_POINTER(scalloc(217,75););
printStats();
void* p472 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p473 = last_address;
DEBUG_PRINT(sfree(p408););
printStats();
DEBUG_PRINT(sfree(p342););
printStats();
PRINT_POINTER(srealloc(p421,220););
printStats();
void* p474 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p475 = last_address;
PRINT_POINTER(scalloc(165,248););
printStats();
void* p476 = last_address;
PRINT_POINTER(srealloc(p286,102););
printStats();
void* p477 = last_address;
PRINT_POINTER(scalloc(10,239););
printStats();
void* p478 = last_address;
PRINT_POINTER(srealloc(p448,158););
printStats();
void* p479 = last_address;
DEBUG_PRINT(sfree(p260););
printStats();
PRINT_POINTER(srealloc(p433,203););
printStats();
void* p480 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p481 = last_address;
PRINT_POINTER(srealloc(p442,21););
printStats();
void* p482 = last_address;
DEBUG_PRINT(sfree(p335););
printStats();
PRINT_POINTER(srealloc(p367,157););
printStats();
void* p483 = last_address;
PRINT_POINTER(srealloc(p240,50););
printStats();
void* p484 = last_address;
DEBUG_PRINT(sfree(p454););
printStats();
PRINT_POINTER(scalloc(112,177););
printStats();
void* p485 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p486 = last_address;
PRINT_POINTER(srealloc(p376,103););
printStats();
void* p487 = last_address;
PRINT_POINTER(srealloc(p345,228););
printStats();
void* p488 = last_address;
PRINT_POINTER(srealloc(p373,33););
printStats();
void* p489 = last_address;
DEBUG_PRINT(sfree(p391););
printStats();
PRINT_POINTER(scalloc(145,206););
printStats();
void* p490 = last_address;
PRINT_POINTER(scalloc(196,131););
printStats();
void* p491 = last_address;
PRINT_POINTER(scalloc(58,221););
printStats();
void* p492 = last_address;
PRINT_POINTER(srealloc(p138,192););
printStats();
void* p493 = last_address;
DEBUG_PRINT(sfree(p465););
printStats();
DEBUG_PRINT(sfree(p455););
printStats();
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(scalloc(118,104););
printStats();
void* p494 = last_address;
PRINT_POINTER(srealloc(p383,76););
printStats();
void* p495 = last_address;
DEBUG_PRINT(sfree(p440););
printStats();
DEBUG_PRINT(sfree(p394););
printStats();
PRINT_POINTER(smalloc(7););
printStats();
void* p496 = last_address;
DEBUG_PRINT(sfree(p420););
printStats();
PRINT_POINTER(scalloc(38,62););
printStats();
void* p497 = last_address;
PRINT_POINTER(srealloc(p374,78););
printStats();
void* p498 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p499 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p500 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p501 = last_address;
PRINT_POINTER(scalloc(159,158););
printStats();
void* p502 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
PRINT_POINTER(smalloc(246););
printStats();
void* p503 = last_address;
PRINT_POINTER(scalloc(191,109););
printStats();
void* p504 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p505 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p506 = last_address;
PRINT_POINTER(srealloc(p271,162););
printStats();
void* p507 = last_address;
DEBUG_PRINT(sfree(p239););
printStats();
DEBUG_PRINT(sfree(p487););
printStats();
PRINT_POINTER(scalloc(74,155););
printStats();
void* p508 = last_address;
PRINT_POINTER(srealloc(p407,94););
printStats();
void* p509 = last_address;
PRINT_POINTER(scalloc(249,157););
printStats();
void* p510 = last_address;
PRINT_POINTER(scalloc(235,93););
printStats();
void* p511 = last_address;
DEBUG_PRINT(sfree(p481););
printStats();
PRINT_POINTER(smalloc(11););
printStats();
void* p512 = last_address;
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(smalloc(11););
printStats();
void* p513 = last_address;
PRINT_POINTER(scalloc(204,8););
printStats();
void* p514 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p515 = last_address;
PRINT_POINTER(scalloc(215,153););
printStats();
void* p516 = last_address;
DEBUG_PRINT(sfree(p257););
printStats();
PRINT_POINTER(smalloc(104););
printStats();
void* p517 = last_address;
PRINT_POINTER(scalloc(174,15););
printStats();
void* p518 = last_address;
PRINT_POINTER(scalloc(2,80););
printStats();
void* p519 = last_address;
DEBUG_PRINT(sfree(p482););
printStats();
PRINT_POINTER(srealloc(p389,33););
printStats();
void* p520 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p521 = last_address;
PRINT_POINTER(scalloc(79,175););
printStats();
void* p522 = last_address;
PRINT_POINTER(srealloc(p243,165););
printStats();
void* p523 = last_address;
PRINT_POINTER(srealloc(p220,203););
printStats();
void* p524 = last_address;
PRINT_POINTER(scalloc(152,66););
printStats();
void* p525 = last_address;
PRINT_POINTER(srealloc(p328,29););
printStats();
void* p526 = last_address;
PRINT_POINTER(srealloc(p498,23););
printStats();
void* p527 = last_address;
PRINT_POINTER(srealloc(p317,130););
printStats();
void* p528 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p529 = last_address;
DEBUG_PRINT(sfree(p496););
printStats();
PRINT_POINTER(smalloc(166););
printStats();
void* p530 = last_address;
PRINT_POINTER(scalloc(59,126););
printStats();
void* p531 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p532 = last_address;
DEBUG_PRINT(sfree(p529););
printStats();
DEBUG_PRINT(sfree(p196););
printStats();
PRINT_POINTER(smalloc(15););
printStats();
void* p533 = last_address;
DEBUG_PRINT(sfree(p416););
printStats();
PRINT_POINTER(srealloc(p403,118););
printStats();
void* p534 = last_address;
PRINT_POINTER(scalloc(113,18););
printStats();
void* p535 = last_address;
PRINT_POINTER(scalloc(40,187););
printStats();
void* p536 = last_address;
PRINT_POINTER(scalloc(177,71););
printStats();
void* p537 = last_address;
PRINT_POINTER(srealloc(p523,148););
printStats();
void* p538 = last_address;
PRINT_POINTER(scalloc(41,237););
printStats();
void* p539 = last_address;
PRINT_POINTER(srealloc(p197,248););
printStats();
void* p540 = last_address;
PRINT_POINTER(scalloc(200,76););
printStats();
void* p541 = last_address;
PRINT_POINTER(scalloc(230,75););
printStats();
void* p542 = last_address;
PRINT_POINTER(srealloc(p356,24););
printStats();
void* p543 = last_address;
PRINT_POINTER(scalloc(192,61););
printStats();
void* p544 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p545 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p546 = last_address;
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(srealloc(p460,126););
printStats();
void* p547 = last_address;
PRINT_POINTER(srealloc(p543,199););
printStats();
void* p548 = last_address;
DEBUG_PRINT(sfree(p309););
printStats();
PRINT_POINTER(smalloc(95););
printStats();
void* p549 = last_address;
PRINT_POINTER(srealloc(p520,52););
printStats();
void* p550 = last_address;
PRINT_POINTER(scalloc(206,107););
printStats();
void* p551 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p552 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p553 = last_address;
PRINT_POINTER(srealloc(p509,234););
printStats();
void* p554 = last_address;
DEBUG_PRINT(sfree(p484););
printStats();
DEBUG_PRINT(sfree(p544););
printStats();
PRINT_POINTER(smalloc(117););
printStats();
void* p555 = last_address;
PRINT_POINTER(scalloc(111,194););
printStats();
void* p556 = last_address;
PRINT_POINTER(scalloc(162,2););
printStats();
void* p557 = last_address;
PRINT_POINTER(scalloc(122,225););
printStats();
void* p558 = last_address;
DEBUG_PRINT(sfree(p456););
printStats();
PRINT_POINTER(scalloc(206,63););
printStats();
void* p559 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p560 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p561 = last_address;
PRINT_POINTER(scalloc(104,171););
printStats();
void* p562 = last_address;
PRINT_POINTER(srealloc(p473,110););
printStats();
void* p563 = last_address;
DEBUG_PRINT(sfree(p516););
printStats();
DEBUG_PRINT(sfree(p480););
printStats();
PRINT_POINTER(srealloc(p541,17););
printStats();
void* p564 = last_address;
DEBUG_PRINT(sfree(p519););
printStats();
PRINT_POINTER(srealloc(p514,233););
printStats();
void* p565 = last_address;
DEBUG_PRINT(sfree(p458););
printStats();
PRINT_POINTER(srealloc(p395,89););
printStats();
void* p566 = last_address;
DEBUG_PRINT(sfree(p346););
printStats();
PRINT_POINTER(srealloc(p493,153););
printStats();
void* p567 = last_address;
PRINT_POINTER(srealloc(p462,193););
printStats();
void* p568 = last_address;
PRINT_POINTER(scalloc(100,190););
printStats();
void* p569 = last_address;
PRINT_POINTER(scalloc(156,195););
printStats();
void* p570 = last_address;
PRINT_POINTER(srealloc(p547,84););
printStats();
void* p571 = last_address;
PRINT_POINTER(srealloc(p550,12););
printStats();
void* p572 = last_address;
DEBUG_PRINT(sfree(p558););
printStats();
PRINT_POINTER(smalloc(188););
printStats();
void* p573 = last_address;
PRINT_POINTER(srealloc(p497,50););
printStats();
void* p574 = last_address;
PRINT_POINTER(scalloc(57,225););
printStats();
void* p575 = last_address;
PRINT_POINTER(srealloc(p478,36););
printStats();
void* p576 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p577 = last_address;
PRINT_POINTER(scalloc(208,195););
printStats();
void* p578 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p579 = last_address;
PRINT_POINTER(scalloc(210,75););
printStats();
void* p580 = last_address;
PRINT_POINTER(scalloc(77,92););
printStats();
void* p581 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p582 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p583 = last_address;
PRINT_POINTER(scalloc(239,170););
printStats();
void* p584 = last_address;
PRINT_POINTER(scalloc(126,4););
printStats();
void* p585 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p586 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p587 = last_address;
PRINT_POINTER(srealloc(p244,136););
printStats();
void* p588 = last_address;
PRINT_POINTER(scalloc(167,44););
printStats();
void* p589 = last_address;
PRINT_POINTER(scalloc(141,9););
printStats();
void* p590 = last_address;
PRINT_POINTER(scalloc(8,139););
printStats();
void* p591 = last_address;
PRINT_POINTER(scalloc(204,151););
printStats();
void* p592 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p593 = last_address;
PRINT_POINTER(srealloc(p451,70););
printStats();
void* p594 = last_address;
PRINT_POINTER(scalloc(89,107););
printStats();
void* p595 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p596 = last_address;
DEBUG_PRINT(sfree(p577););
printStats();
DEBUG_PRINT(sfree(p489););
printStats();
PRINT_POINTER(srealloc(p387,211););
printStats();
void* p597 = last_address;
DEBUG_PRINT(sfree(p372););
printStats();
PRINT_POINTER(srealloc(p445,74););
printStats();
void* p598 = last_address;
DEBUG_PRINT(sfree(p561););
printStats();
PRINT_POINTER(smalloc(6););
printStats();
void* p599 = last_address;
PRINT_POINTER(srealloc(p559,186););
printStats();
void* p600 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p601 = last_address;
PRINT_POINTER(srealloc(p574,163););
printStats();
void* p602 = last_address;
PRINT_POINTER(scalloc(100,155););
printStats();
void* p603 = last_address;
PRINT_POINTER(srealloc(p539,115););
printStats();
void* p604 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p605 = last_address;
PRINT_POINTER(scalloc(224,224););
printStats();
void* p606 = last_address;
PRINT_POINTER(scalloc(114,3););
printStats();
void* p607 = last_address;
PRINT_POINTER(scalloc(15,47););
printStats();
void* p608 = last_address;
DEBUG_PRINT(sfree(p363););
printStats();
PRINT_POINTER(scalloc(49,177););
printStats();
void* p609 = last_address;
PRINT_POINTER(srealloc(p545,77););
printStats();
void* p610 = last_address;
PRINT_POINTER(scalloc(225,138););
printStats();
void* p611 = last_address;
PRINT_POINTER(srealloc(p341,147););
printStats();
void* p612 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p613 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p614 = last_address;
PRINT_POINTER(scalloc(156,75););
printStats();
void* p615 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p616 = last_address;
PRINT_POINTER(scalloc(201,229););
printStats();
void* p617 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p618 = last_address;
DEBUG_PRINT(sfree(p510););
printStats();
PRINT_POINTER(srealloc(p488,170););
printStats();
void* p619 = last_address;
DEBUG_PRINT(sfree(p316););
printStats();
PRINT_POINTER(scalloc(152,113););
printStats();
void* p620 = last_address;
DEBUG_PRINT(sfree(p557););
printStats();
DEBUG_PRINT(sfree(p396););
printStats();
PRINT_POINTER(scalloc(140,147););
printStats();
void* p621 = last_address;
DEBUG_PRINT(sfree(p410););
printStats();
PRINT_POINTER(scalloc(173,59););
printStats();
void* p622 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p623 = last_address;
DEBUG_PRINT(sfree(p471););
printStats();
DEBUG_PRINT(sfree(p567););
printStats();
PRINT_POINTER(scalloc(209,98););
printStats();
void* p624 = last_address;
DEBUG_PRINT(sfree(p535););
printStats();
DEBUG_PRINT(sfree(p476););
printStats();
PRINT_POINTER(srealloc(p431,14););
printStats();
void* p625 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p626 = last_address;
PRINT_POINTER(scalloc(204,106););
printStats();
void* p627 = last_address;
DEBUG_PRINT(sfree(p415););
printStats();
PRINT_POINTER(srealloc(p566,17););
printStats();
void* p628 = last_address;
PRINT_POINTER(srealloc(p369,206););
printStats();
void* p629 = last_address;
DEBUG_PRINT(sfree(p553););
printStats();
PRINT_POINTER(srealloc(p393,155););
printStats();
void* p630 = last_address;
PRINT_POINTER(scalloc(153,128););
printStats();
void* p631 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p632 = last_address;
PRINT_POINTER(scalloc(237,193););
printStats();
void* p633 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p634 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p635 = last_address;
DEBUG_PRINT(sfree(p591););
printStats();
PRINT_POINTER(smalloc(133););
printStats();
void* p636 = last_address;
DEBUG_PRINT(sfree(p628););
printStats();
DEBUG_PRINT(sfree(p609););
printStats();
DEBUG_PRINT(sfree(p485););
printStats();
PRINT_POINTER(srealloc(p461,179););
printStats();
void* p637 = last_address;
DEBUG_PRINT(sfree(p364););
printStats();
PRINT_POINTER(scalloc(2,126););
printStats();
void* p638 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p639 = last_address;
PRINT_POINTER(srealloc(p601,83););
printStats();
void* p640 = last_address;
PRINT_POINTER(srealloc(p522,188););
printStats();
void* p641 = last_address;
PRINT_POINTER(scalloc(33,217););
printStats();
void* p642 = last_address;
PRINT_POINTER(srealloc(p579,67););
printStats();
void* p643 = last_address;
PRINT_POINTER(srealloc(p542,71););
printStats();
void* p644 = last_address;
DEBUG_PRINT(sfree(p632););
printStats();
PRINT_POINTER(scalloc(242,176););
printStats();
void* p645 = last_address;
DEBUG_PRINT(sfree(p450););
printStats();
DEBUG_PRINT(sfree(p623););
printStats();
DEBUG_PRINT(sfree(p349););
printStats();
PRINT_POINTER(srealloc(p350,48););
printStats();
void* p646 = last_address;
PRINT_POINTER(srealloc(p592,138););
printStats();
void* p647 = last_address;
DEBUG_PRINT(sfree(p380););
printStats();
PRINT_POINTER(srealloc(p639,113););
printStats();
void* p648 = last_address;
PRINT_POINTER(srealloc(p646,41););
printStats();
void* p649 = last_address;
PRINT_POINTER(srealloc(p572,1););
printStats();
void* p650 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p651 = last_address;
PRINT_POINTER(scalloc(213,27););
printStats();
void* p652 = last_address;
PRINT_POINTER(srealloc(p470,77););
printStats();
void* p653 = last_address;
PRINT_POINTER(srealloc(p527,104););
printStats();
void* p654 = last_address;
DEBUG_PRINT(sfree(p412););
printStats();
PRINT_POINTER(smalloc(108););
printStats();
void* p655 = last_address;
DEBUG_PRINT(sfree(p486););
printStats();
PRINT_POINTER(smalloc(48););
printStats();
void* p656 = last_address;
DEBUG_PRINT(sfree(p379););
printStats();
DEBUG_PRINT(sfree(p368););
printStats();
PRINT_POINTER(scalloc(85,17););
printStats();
void* p657 = last_address;
PRINT_POINTER(scalloc(82,102););
printStats();
void* p658 = last_address;
PRINT_POINTER(scalloc(201,20););
printStats();
void* p659 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p660 = last_address;
PRINT_POINTER(srealloc(p384,122););
printStats();
void* p661 = last_address;
PRINT_POINTER(scalloc(105,151););
printStats();
void* p662 = last_address;
DEBUG_PRINT(sfree(p490););
printStats();
PRINT_POINTER(smalloc(4););
printStats();
void* p663 = last_address;
PRINT_POINTER(scalloc(47,79););
printStats();
void* p664 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
PRINT_POINTER(srealloc(p560,235););
printStats();
void* p665 = last_address;
PRINT_POINTER(scalloc(184,208););
printStats();
void* p666 = last_address;
PRINT_POINTER(scalloc(142,6););
printStats();
void* p667 = last_address;
PRINT_POINTER(srealloc(p282,51););
printStats();
void* p668 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p669 = last_address;
PRINT_POINTER(scalloc(183,84););
printStats();
void* p670 = last_address;
DEBUG_PRINT(sfree(p643););
printStats();
PRINT_POINTER(scalloc(64,75););
printStats();
void* p671 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p672 = last_address;
PRINT_POINTER(srealloc(p354,197););
printStats();
void* p673 = last_address;
DEBUG_PRINT(sfree(p377););
printStats();
DEBUG_PRINT(sfree(p385););
printStats();
DEBUG_PRINT(sfree(p500););
printStats();
PRINT_POINTER(scalloc(166,181););
printStats();
void* p674 = last_address;
DEBUG_PRINT(sfree(p590););
printStats();
PRINT_POINTER(scalloc(128,98););
printStats();
void* p675 = last_address;
PRINT_POINTER(srealloc(p528,191););
printStats();
void* p676 = last_address;
PRINT_POINTER(scalloc(99,189););
printStats();
void* p677 = last_address;
PRINT_POINTER(scalloc(159,71););
printStats();
void* p678 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p679 = last_address;
PRINT_POINTER(scalloc(148,191););
printStats();
void* p680 = last_address;
PRINT_POINTER(scalloc(113,36););
printStats();
void* p681 = last_address;
DEBUG_PRINT(sfree(p585););
printStats();
PRINT_POINTER(smalloc(105););
printStats();
void* p682 = last_address;
PRINT_POINTER(scalloc(17,90););
printStats();
void* p683 = last_address;
PRINT_POINTER(scalloc(207,186););
printStats();
void* p684 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p685 = last_address;
DEBUG_PRINT(sfree(p610););
printStats();
PRINT_POINTER(scalloc(90,239););
printStats();
void* p686 = last_address;
PRINT_POINTER(srealloc(p651,89););
printStats();
void* p687 = last_address;
PRINT_POINTER(scalloc(47,93););
printStats();
void* p688 = last_address;
PRINT_POINTER(scalloc(51,214););
printStats();
void* p689 = last_address;
DEBUG_PRINT(sfree(p619););
printStats();
PRINT_POINTER(scalloc(196,135););
printStats();
void* p690 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p691 = last_address;
PRINT_POINTER(srealloc(p648,221););
printStats();
void* p692 = last_address;
PRINT_POINTER(scalloc(243,44););
printStats();
void* p693 = last_address;
PRINT_POINTER(scalloc(101,24););
printStats();
void* p694 = last_address;
PRINT_POINTER(srealloc(p183,61););
printStats();
void* p695 = last_address;
DEBUG_PRINT(sfree(p518););
printStats();
PRINT_POINTER(scalloc(44,19););
printStats();
void* p696 = last_address;
PRINT_POINTER(srealloc(p351,150););
printStats();
void* p697 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p698 = last_address;
PRINT_POINTER(srealloc(p438,184););
printStats();
void* p699 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p700 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p701 = last_address;
DEBUG_PRINT(sfree(p290););
printStats();
PRINT_POINTER(smalloc(2););
printStats();
void* p702 = last_address;
PRINT_POINTER(scalloc(38,219););
printStats();
void* p703 = last_address;
PRINT_POINTER(scalloc(223,246););
printStats();
void* p704 = last_address;
PRINT_POINTER(scalloc(111,237););
printStats();
void* p705 = last_address;
PRINT_POINTER(scalloc(155,91););
printStats();
void* p706 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p707 = last_address;
PRINT_POINTER(scalloc(105,134););
printStats();
void* p708 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p709 = last_address;
PRINT_POINTER(scalloc(155,44););
printStats();
void* p710 = last_address;
DEBUG_PRINT(sfree(p418););
printStats();
PRINT_POINTER(srealloc(p644,189););
printStats();
void* p711 = last_address;
PRINT_POINTER(srealloc(p419,190););
printStats();
void* p712 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p713 = last_address;
DEBUG_PRINT(sfree(p457););
printStats();
PRINT_POINTER(srealloc(p468,135););
printStats();
void* p714 = last_address;
DEBUG_PRINT(sfree(p430););
printStats();
PRINT_POINTER(srealloc(p620,39););
printStats();
void* p715 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p716 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p717 = last_address;
PRINT_POINTER(srealloc(p709,31););
printStats();
void* p718 = last_address;
DEBUG_PRINT(sfree(p357););
printStats();
PRINT_POINTER(srealloc(p692,194););
printStats();
void* p719 = last_address;
PRINT_POINTER(scalloc(58,42););
printStats();
void* p720 = last_address;
PRINT_POINTER(srealloc(p650,39););
printStats();
void* p721 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p722 = last_address;
PRINT_POINTER(scalloc(47,46););
printStats();
void* p723 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p724 = last_address;
DEBUG_PRINT(sfree(p652););
printStats();
PRINT_POINTER(smalloc(219););
printStats();
void* p725 = last_address;
PRINT_POINTER(srealloc(p308,125););
printStats();
void* p726 = last_address;
DEBUG_PRINT(sfree(p571););
printStats();
PRINT_POINTER(smalloc(141););
printStats();
void* p727 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p728 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p729 = last_address;
PRINT_POINTER(scalloc(89,163););
printStats();
void* p730 = last_address;
PRINT_POINTER(scalloc(158,6););
printStats();
void* p731 = last_address;
DEBUG_PRINT(sfree(p507););
printStats();
PRINT_POINTER(smalloc(206););
printStats();
void* p732 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p733 = last_address;
PRINT_POINTER(scalloc(193,219););
printStats();
void* p734 = last_address;
DEBUG_PRINT(sfree(p467););
printStats();
DEBUG_PRINT(sfree(p505););
printStats();
DEBUG_PRINT(sfree(p483););
printStats();
DEBUG_PRINT(sfree(p717););
printStats();
PRINT_POINTER(scalloc(171,96););
printStats();
void* p735 = last_address;
DEBUG_PRINT(sfree(p718););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p736 = last_address;
PRINT_POINTER(srealloc(p716,26););
printStats();
void* p737 = last_address;
PRINT_POINTER(scalloc(96,230););
printStats();
void* p738 = last_address;
PRINT_POINTER(srealloc(p683,114););
printStats();
void* p739 = last_address;
PRINT_POINTER(srealloc(p734,98););
printStats();
void* p740 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p741 = last_address;
PRINT_POINTER(srealloc(p253,20););
printStats();
void* p742 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p743 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p744 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p745 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p746 = last_address;
PRINT_POINTER(srealloc(p575,69););
printStats();
void* p747 = last_address;
PRINT_POINTER(srealloc(p491,8););
printStats();
void* p748 = last_address;
DEBUG_PRINT(sfree(p400););
printStats();
PRINT_POINTER(scalloc(59,42););
printStats();
void* p749 = last_address;
DEBUG_PRINT(sfree(p746););
printStats();
PRINT_POINTER(scalloc(238,104););
printStats();
void* p750 = last_address;
PRINT_POINTER(scalloc(117,189););
printStats();
void* p751 = last_address;
DEBUG_PRINT(sfree(p712););
printStats();
DEBUG_PRINT(sfree(p715););
printStats();
PRINT_POINTER(srealloc(p658,76););
printStats();
void* p752 = last_address;
DEBUG_PRINT(sfree(p536););
printStats();
PRINT_POINTER(smalloc(66););
printStats();
void* p753 = last_address;
PRINT_POINTER(scalloc(107,226););
printStats();
void* p754 = last_address;
DEBUG_PRINT(sfree(p708););
printStats();
PRINT_POINTER(scalloc(63,22););
printStats();
void* p755 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p756 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p757 = last_address;
PRINT_POINTER(srealloc(p702,116););
printStats();
void* p758 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p759 = last_address;
PRINT_POINTER(srealloc(p653,165););
printStats();
void* p760 = last_address;
DEBUG_PRINT(sfree(p681););
printStats();
PRINT_POINTER(srealloc(p530,167););
printStats();
void* p761 = last_address;
PRINT_POINTER(srealloc(p624,134););
printStats();
void* p762 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p763 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p764 = last_address;
DEBUG_PRINT(sfree(p469););
printStats();
DEBUG_PRINT(sfree(p688););
printStats();
PRINT_POINTER(smalloc(21););
printStats();
void* p765 = last_address;
PRINT_POINTER(srealloc(p596,40););
printStats();
void* p766 = last_address;
PRINT_POINTER(scalloc(64,62););
printStats();
void* p767 = last_address;
DEBUG_PRINT(sfree(p637););
printStats();
PRINT_POINTER(smalloc(15););
printStats();
void* p768 = last_address;
PRINT_POINTER(scalloc(140,52););
printStats();
void* p769 = last_address;
PRINT_POINTER(scalloc(178,114););
printStats();
void* p770 = last_address;
PRINT_POINTER(scalloc(162,173););
printStats();
void* p771 = last_address;
PRINT_POINTER(srealloc(p479,36););
printStats();
void* p772 = last_address;
DEBUG_PRINT(sfree(p689););
printStats();
PRINT_POINTER(smalloc(67););
printStats();
void* p773 = last_address;
PRINT_POINTER(scalloc(121,72););
printStats();
void* p774 = last_address;
PRINT_POINTER(scalloc(239,181););
printStats();
void* p775 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p776 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p777 = last_address;
PRINT_POINTER(scalloc(137,118););
printStats();
void* p778 = last_address;
PRINT_POINTER(scalloc(125,21););
printStats();
void* p779 = last_address;
PRINT_POINTER(scalloc(123,65););
printStats();
void* p780 = last_address;
PRINT_POINTER(scalloc(183,180););
printStats();
void* p781 = last_address;
DEBUG_PRINT(sfree(p633););
printStats();
DEBUG_PRINT(sfree(p466););
printStats();
PRINT_POINTER(smalloc(108););
printStats();
void* p782 = last_address;
DEBUG_PRINT(sfree(p583););
printStats();
PRINT_POINTER(srealloc(p602,75););
printStats();
void* p783 = last_address;
DEBUG_PRINT(sfree(p731););
printStats();
PRINT_POINTER(scalloc(73,207););
printStats();
void* p784 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p785 = last_address;
PRINT_POINTER(scalloc(49,64););
printStats();
void* p786 = last_address;
PRINT_POINTER(srealloc(p775,205););
printStats();
void* p787 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p788 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p789 = last_address;
PRINT_POINTER(srealloc(p604,113););
printStats();
void* p790 = last_address;
PRINT_POINTER(srealloc(p640,180););
printStats();
void* p791 = last_address;
PRINT_POINTER(srealloc(p721,136););
printStats();
void* p792 = last_address;
PRINT_POINTER(srealloc(p695,162););
printStats();
void* p793 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p794 = last_address;
PRINT_POINTER(srealloc(p327,61););
printStats();
void* p795 = last_address;
PRINT_POINTER(scalloc(168,42););
printStats();
void* p796 = last_address;
DEBUG_PRINT(sfree(p684););
printStats();
PRINT_POINTER(scalloc(179,249););
printStats();
void* p797 = last_address;
PRINT_POINTER(srealloc(p614,79););
printStats();
void* p798 = last_address;
PRINT_POINTER(srealloc(p287,7););
printStats();
void* p799 = last_address;
DEBUG_PRINT(sfree(p568););
printStats();
PRINT_POINTER(srealloc(p723,19););
printStats();
void* p800 = last_address;
DEBUG_PRINT(sfree(p724););
printStats();
PRINT_POINTER(scalloc(22,176););
printStats();
void* p801 = last_address;
PRINT_POINTER(srealloc(p531,88););
printStats();
void* p802 = last_address;
DEBUG_PRINT(sfree(p756););
printStats();
PRINT_POINTER(smalloc(143););
printStats();
void* p803 = last_address;
DEBUG_PRINT(sfree(p778););
printStats();
PRINT_POINTER(srealloc(p706,134););
printStats();
void* p804 = last_address;
DEBUG_PRINT(sfree(p569););
printStats();
PRINT_POINTER(smalloc(14););
printStats();
void* p805 = last_address;
PRINT_POINTER(srealloc(p666,0););
printStats();
void* p806 = last_address;
PRINT_POINTER(scalloc(76,42););
printStats();
void* p807 = last_address;
PRINT_POINTER(srealloc(p726,212););
printStats();
void* p808 = last_address;
PRINT_POINTER(scalloc(111,238););
printStats();
void* p809 = last_address;
PRINT_POINTER(srealloc(p340,128););
printStats();
void* p810 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p811 = last_address;
PRINT_POINTER(scalloc(62,90););
printStats();
void* p812 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p813 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p814 = last_address;
DEBUG_PRINT(sfree(p611););
printStats();
PRINT_POINTER(srealloc(p622,83););
printStats();
void* p815 = last_address;
PRINT_POINTER(scalloc(109,90););
printStats();
void* p816 = last_address;
PRINT_POINTER(srealloc(p254,63););
printStats();
void* p817 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p818 = last_address;
DEBUG_PRINT(sfree(p600););
printStats();
PRINT_POINTER(scalloc(190,159););
printStats();
void* p819 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p820 = last_address;
PRINT_POINTER(srealloc(p696,80););
printStats();
void* p821 = last_address;
DEBUG_PRINT(sfree(p343););
printStats();
PRINT_POINTER(srealloc(p808,112););
printStats();
void* p822 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p823 = last_address;
PRINT_POINTER(smalloc(221););
printStats();
void* p824 = last_address;
PRINT_POINTER(scalloc(128,92););
printStats();
void* p825 = last_address;
}
