#include "aux_macro.h"
#include "../malloc_2.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(198,199););
printStats();
void* p0 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p1 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p2 = last_address;
PRINT_POINTER(srealloc(p0,155););
printStats();
void* p3 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(srealloc(p1,35););
printStats();
void* p4 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
PRINT_POINTER(srealloc(p3,222););
printStats();
void* p5 = last_address;
PRINT_POINTER(srealloc(p5,166););
printStats();
void* p6 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p7 = last_address;
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(srealloc(p7,189););
printStats();
void* p8 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(scalloc(202,237););
printStats();
void* p9 = last_address;
DEBUG_PRINT(sfree(p9););
printStats();
PRINT_POINTER(smalloc(183););
printStats();
void* p10 = last_address;
PRINT_POINTER(srealloc(p10,33););
printStats();
void* p11 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p12 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p13 = last_address;
DEBUG_PRINT(sfree(p12););
printStats();
PRINT_POINTER(srealloc(p13,23););
printStats();
void* p14 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p15 = last_address;
PRINT_POINTER(scalloc(31,174););
printStats();
void* p16 = last_address;
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(srealloc(p16,2););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(159,220););
printStats();
void* p18 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p20 = last_address;
DEBUG_PRINT(sfree(p19););
printStats();
PRINT_POINTER(smalloc(119););
printStats();
void* p21 = last_address;
PRINT_POINTER(srealloc(p15,190););
printStats();
void* p22 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(scalloc(176,62););
printStats();
void* p23 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p24 = last_address;
DEBUG_PRINT(sfree(p23););
printStats();
PRINT_POINTER(smalloc(135););
printStats();
void* p25 = last_address;
PRINT_POINTER(srealloc(p20,136););
printStats();
void* p26 = last_address;
PRINT_POINTER(scalloc(216,17););
printStats();
void* p27 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p28 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
PRINT_POINTER(scalloc(66,41););
printStats();
void* p29 = last_address;
PRINT_POINTER(srealloc(p24,153););
printStats();
void* p30 = last_address;
PRINT_POINTER(srealloc(p27,226););
printStats();
void* p31 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p32 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p33 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p34 = last_address;
PRINT_POINTER(scalloc(226,190););
printStats();
void* p35 = last_address;
PRINT_POINTER(scalloc(6,23););
printStats();
void* p36 = last_address;
PRINT_POINTER(scalloc(146,131););
printStats();
void* p37 = last_address;
PRINT_POINTER(srealloc(p34,144););
printStats();
void* p38 = last_address;
PRINT_POINTER(scalloc(177,33););
printStats();
void* p39 = last_address;
PRINT_POINTER(scalloc(19,27););
printStats();
void* p40 = last_address;
PRINT_POINTER(scalloc(107,137););
printStats();
void* p41 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p42 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
PRINT_POINTER(smalloc(68););
printStats();
void* p43 = last_address;
PRINT_POINTER(srealloc(p26,169););
printStats();
void* p44 = last_address;
PRINT_POINTER(srealloc(p32,125););
printStats();
void* p45 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(smalloc(90););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p47 = last_address;
PRINT_POINTER(scalloc(28,170););
printStats();
void* p48 = last_address;
PRINT_POINTER(srealloc(p48,162););
printStats();
void* p49 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p50 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(srealloc(p44,237););
printStats();
void* p51 = last_address;
PRINT_POINTER(srealloc(p41,234););
printStats();
void* p52 = last_address;
PRINT_POINTER(scalloc(200,225););
printStats();
void* p53 = last_address;
DEBUG_PRINT(sfree(p52););
printStats();
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(scalloc(211,3););
printStats();
void* p54 = last_address;
PRINT_POINTER(scalloc(19,115););
printStats();
void* p55 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p56 = last_address;
DEBUG_PRINT(sfree(p55););
printStats();
PRINT_POINTER(smalloc(234););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(216,114););
printStats();
void* p58 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p59 = last_address;
PRINT_POINTER(scalloc(241,117););
printStats();
void* p60 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(srealloc(p58,1););
printStats();
void* p61 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p62 = last_address;
PRINT_POINTER(scalloc(57,248););
printStats();
void* p63 = last_address;
PRINT_POINTER(srealloc(p47,58););
printStats();
void* p64 = last_address;
DEBUG_PRINT(sfree(p63););
printStats();
PRINT_POINTER(smalloc(240););
printStats();
void* p65 = last_address;
PRINT_POINTER(srealloc(p50,202););
printStats();
void* p66 = last_address;
DEBUG_PRINT(sfree(p62););
printStats();
DEBUG_PRINT(sfree(p57););
printStats();
PRINT_POINTER(scalloc(18,207););
printStats();
void* p67 = last_address;
PRINT_POINTER(srealloc(p56,138););
printStats();
void* p68 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(srealloc(p21,238););
printStats();
void* p69 = last_address;
PRINT_POINTER(scalloc(180,48););
printStats();
void* p70 = last_address;
PRINT_POINTER(scalloc(10,151););
printStats();
void* p71 = last_address;
PRINT_POINTER(srealloc(p64,44););
printStats();
void* p72 = last_address;
PRINT_POINTER(scalloc(193,158););
printStats();
void* p73 = last_address;
PRINT_POINTER(srealloc(p33,242););
printStats();
void* p74 = last_address;
PRINT_POINTER(scalloc(77,225););
printStats();
void* p75 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p76 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p77 = last_address;
DEBUG_PRINT(sfree(p66););
printStats();
DEBUG_PRINT(sfree(p49););
printStats();
PRINT_POINTER(srealloc(p71,168););
printStats();
void* p78 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p79 = last_address;
DEBUG_PRINT(sfree(p35););
printStats();
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(srealloc(p74,50););
printStats();
void* p80 = last_address;
PRINT_POINTER(srealloc(p42,54););
printStats();
void* p81 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p82 = last_address;
PRINT_POINTER(scalloc(131,109););
printStats();
void* p83 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p84 = last_address;
PRINT_POINTER(srealloc(p36,166););
printStats();
void* p85 = last_address;
PRINT_POINTER(scalloc(124,105););
printStats();
void* p86 = last_address;
DEBUG_PRINT(sfree(p67););
printStats();
PRINT_POINTER(srealloc(p76,129););
printStats();
void* p87 = last_address;
PRINT_POINTER(srealloc(p85,192););
printStats();
void* p88 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p89 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p90 = last_address;
PRINT_POINTER(scalloc(206,142););
printStats();
void* p91 = last_address;
PRINT_POINTER(scalloc(159,26););
printStats();
void* p92 = last_address;
PRINT_POINTER(scalloc(232,104););
printStats();
void* p93 = last_address;
DEBUG_PRINT(sfree(p61););
printStats();
PRINT_POINTER(srealloc(p28,124););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p95 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p96 = last_address;
PRINT_POINTER(scalloc(187,103););
printStats();
void* p97 = last_address;
PRINT_POINTER(srealloc(p95,47););
printStats();
void* p98 = last_address;
DEBUG_PRINT(sfree(p53););
printStats();
PRINT_POINTER(srealloc(p92,74););
printStats();
void* p99 = last_address;
PRINT_POINTER(scalloc(34,109););
printStats();
void* p100 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p101 = last_address;
DEBUG_PRINT(sfree(p73););
printStats();
DEBUG_PRINT(sfree(p68););
printStats();
PRINT_POINTER(srealloc(p84,17););
printStats();
void* p102 = last_address;
PRINT_POINTER(srealloc(p17,10););
printStats();
void* p103 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p104 = last_address;
PRINT_POINTER(srealloc(p29,123););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p96,124););
printStats();
void* p106 = last_address;
DEBUG_PRINT(sfree(p82););
printStats();
PRINT_POINTER(scalloc(178,226););
printStats();
void* p107 = last_address;
PRINT_POINTER(scalloc(167,119););
printStats();
void* p108 = last_address;
PRINT_POINTER(scalloc(133,157););
printStats();
void* p109 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(scalloc(130,212););
printStats();
void* p110 = last_address;
PRINT_POINTER(scalloc(195,2););
printStats();
void* p111 = last_address;
DEBUG_PRINT(sfree(p99););
printStats();
DEBUG_PRINT(sfree(p102););
printStats();
DEBUG_PRINT(sfree(p46););
printStats();
PRINT_POINTER(srealloc(p93,164););
printStats();
void* p112 = last_address;
PRINT_POINTER(scalloc(155,182););
printStats();
void* p113 = last_address;
PRINT_POINTER(srealloc(p98,162););
printStats();
void* p114 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p115 = last_address;
PRINT_POINTER(scalloc(129,148););
printStats();
void* p116 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p117 = last_address;
PRINT_POINTER(srealloc(p115,10););
printStats();
void* p118 = last_address;
PRINT_POINTER(scalloc(62,112););
printStats();
void* p119 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p120 = last_address;
PRINT_POINTER(srealloc(p83,235););
printStats();
void* p121 = last_address;
PRINT_POINTER(scalloc(1,193););
printStats();
void* p122 = last_address;
PRINT_POINTER(srealloc(p121,6););
printStats();
void* p123 = last_address;
PRINT_POINTER(scalloc(231,216););
printStats();
void* p124 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(smalloc(59););
printStats();
void* p125 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p126 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
PRINT_POINTER(scalloc(103,201););
printStats();
void* p127 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p128 = last_address;
PRINT_POINTER(srealloc(p70,227););
printStats();
void* p129 = last_address;
PRINT_POINTER(srealloc(p109,204););
printStats();
void* p130 = last_address;
PRINT_POINTER(scalloc(115,39););
printStats();
void* p131 = last_address;
PRINT_POINTER(srealloc(p87,196););
printStats();
void* p132 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p133 = last_address;
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(scalloc(102,51););
printStats();
void* p134 = last_address;
PRINT_POINTER(srealloc(p78,92););
printStats();
void* p135 = last_address;
PRINT_POINTER(scalloc(231,200););
printStats();
void* p136 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p137 = last_address;
PRINT_POINTER(srealloc(p135,59););
printStats();
void* p138 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p112););
printStats();
PRINT_POINTER(scalloc(158,174););
printStats();
void* p140 = last_address;
PRINT_POINTER(scalloc(113,124););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p106,151););
printStats();
void* p142 = last_address;
PRINT_POINTER(scalloc(184,113););
printStats();
void* p143 = last_address;
DEBUG_PRINT(sfree(p122););
printStats();
PRINT_POINTER(smalloc(148););
printStats();
void* p144 = last_address;
DEBUG_PRINT(sfree(p30););
printStats();
PRINT_POINTER(srealloc(p118,201););
printStats();
void* p145 = last_address;
PRINT_POINTER(scalloc(197,245););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p105););
printStats();
DEBUG_PRINT(sfree(p136););
printStats();
PRINT_POINTER(srealloc(p143,117););
printStats();
void* p147 = last_address;
PRINT_POINTER(srealloc(p54,160););
printStats();
void* p148 = last_address;
PRINT_POINTER(scalloc(59,224););
printStats();
void* p149 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p150 = last_address;
PRINT_POINTER(srealloc(p59,191););
printStats();
void* p151 = last_address;
DEBUG_PRINT(sfree(p145););
printStats();
PRINT_POINTER(smalloc(87););
printStats();
void* p152 = last_address;
PRINT_POINTER(scalloc(104,111););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(67,57););
printStats();
void* p154 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(srealloc(p65,211););
printStats();
void* p155 = last_address;
PRINT_POINTER(srealloc(p116,21););
printStats();
void* p156 = last_address;
PRINT_POINTER(srealloc(p149,223););
printStats();
void* p157 = last_address;
PRINT_POINTER(srealloc(p43,3););
printStats();
void* p158 = last_address;
PRINT_POINTER(scalloc(75,78););
printStats();
void* p159 = last_address;
DEBUG_PRINT(sfree(p140););
printStats();
DEBUG_PRINT(sfree(p79););
printStats();
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p160 = last_address;
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(srealloc(p88,94););
printStats();
void* p161 = last_address;
PRINT_POINTER(scalloc(37,162););
printStats();
void* p162 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p163 = last_address;
DEBUG_PRINT(sfree(p160););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p164 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p165 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(smalloc(217););
printStats();
void* p166 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p167 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p168 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(srealloc(p147,81););
printStats();
void* p169 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p170 = last_address;
PRINT_POINTER(srealloc(p151,133););
printStats();
void* p171 = last_address;
DEBUG_PRINT(sfree(p167););
printStats();
DEBUG_PRINT(sfree(p171););
printStats();
PRINT_POINTER(scalloc(127,186););
printStats();
void* p172 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p173 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p174 = last_address;
PRINT_POINTER(scalloc(21,108););
printStats();
void* p175 = last_address;
PRINT_POINTER(srealloc(p120,44););
printStats();
void* p176 = last_address;
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(smalloc(110););
printStats();
void* p177 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p178 = last_address;
PRINT_POINTER(srealloc(p104,68););
printStats();
void* p179 = last_address;
PRINT_POINTER(srealloc(p141,80););
printStats();
void* p180 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p181 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p182 = last_address;
PRINT_POINTER(srealloc(p142,63););
printStats();
void* p183 = last_address;
DEBUG_PRINT(sfree(p177););
printStats();
PRINT_POINTER(srealloc(p161,31););
printStats();
void* p184 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p185 = last_address;
DEBUG_PRINT(sfree(p126););
printStats();
PRINT_POINTER(srealloc(p80,45););
printStats();
void* p186 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p187 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p188 = last_address;
PRINT_POINTER(scalloc(123,22););
printStats();
void* p189 = last_address;
DEBUG_PRINT(sfree(p131););
printStats();
PRINT_POINTER(smalloc(210););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p191 = last_address;
PRINT_POINTER(scalloc(178,178););
printStats();
void* p192 = last_address;
PRINT_POINTER(srealloc(p163,21););
printStats();
void* p193 = last_address;
PRINT_POINTER(scalloc(241,65););
printStats();
void* p194 = last_address;
PRINT_POINTER(scalloc(72,49););
printStats();
void* p195 = last_address;
PRINT_POINTER(srealloc(p86,99););
printStats();
void* p196 = last_address;
DEBUG_PRINT(sfree(p174););
printStats();
PRINT_POINTER(scalloc(135,63););
printStats();
void* p197 = last_address;
PRINT_POINTER(srealloc(p138,73););
printStats();
void* p198 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p199 = last_address;
PRINT_POINTER(srealloc(p185,152););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p197,156););
printStats();
void* p201 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p202 = last_address;
DEBUG_PRINT(sfree(p193););
printStats();
PRINT_POINTER(scalloc(92,107););
printStats();
void* p203 = last_address;
PRINT_POINTER(srealloc(p164,158););
printStats();
void* p204 = last_address;
PRINT_POINTER(smalloc(221););
printStats();
void* p205 = last_address;
PRINT_POINTER(srealloc(p183,243););
printStats();
void* p206 = last_address;
DEBUG_PRINT(sfree(p156););
printStats();
PRINT_POINTER(srealloc(p198,156););
printStats();
void* p207 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
DEBUG_PRINT(sfree(p129););
printStats();
DEBUG_PRINT(sfree(p155););
printStats();
PRINT_POINTER(srealloc(p205,247););
printStats();
void* p208 = last_address;
PRINT_POINTER(scalloc(194,87););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(210,62););
printStats();
void* p210 = last_address;
PRINT_POINTER(srealloc(p189,44););
printStats();
void* p211 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p212 = last_address;
PRINT_POINTER(scalloc(154,6););
printStats();
void* p213 = last_address;
PRINT_POINTER(srealloc(p146,113););
printStats();
void* p214 = last_address;
PRINT_POINTER(srealloc(p148,145););
printStats();
void* p215 = last_address;
DEBUG_PRINT(sfree(p153););
printStats();
DEBUG_PRINT(sfree(p195););
printStats();
PRINT_POINTER(scalloc(187,184););
printStats();
void* p216 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(srealloc(p169,179););
printStats();
void* p217 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p218 = last_address;
DEBUG_PRINT(sfree(p180););
printStats();
PRINT_POINTER(srealloc(p168,103););
printStats();
void* p219 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p220 = last_address;
PRINT_POINTER(srealloc(p132,93););
printStats();
void* p221 = last_address;
PRINT_POINTER(scalloc(69,44););
printStats();
void* p222 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(srealloc(p154,93););
printStats();
void* p223 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p224 = last_address;
DEBUG_PRINT(sfree(p192););
printStats();
DEBUG_PRINT(sfree(p107););
printStats();
PRINT_POINTER(srealloc(p204,25););
printStats();
void* p225 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p226 = last_address;
DEBUG_PRINT(sfree(p212););
printStats();
DEBUG_PRINT(sfree(p214););
printStats();
DEBUG_PRINT(sfree(p175););
printStats();
DEBUG_PRINT(sfree(p75););
printStats();
DEBUG_PRINT(sfree(p119););
printStats();
PRINT_POINTER(srealloc(p103,74););
printStats();
void* p227 = last_address;
PRINT_POINTER(scalloc(236,121););
printStats();
void* p228 = last_address;
PRINT_POINTER(scalloc(165,177););
printStats();
void* p229 = last_address;
PRINT_POINTER(scalloc(53,93););
printStats();
void* p230 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p231 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p232 = last_address;
PRINT_POINTER(scalloc(145,157););
printStats();
void* p233 = last_address;
DEBUG_PRINT(sfree(p211););
printStats();
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(scalloc(87,148););
printStats();
void* p234 = last_address;
PRINT_POINTER(scalloc(117,103););
printStats();
void* p235 = last_address;
PRINT_POINTER(scalloc(144,171););
printStats();
void* p236 = last_address;
PRINT_POINTER(scalloc(51,128););
printStats();
void* p237 = last_address;
DEBUG_PRINT(sfree(p201););
printStats();
PRINT_POINTER(smalloc(11););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p108,14););
printStats();
void* p239 = last_address;
PRINT_POINTER(scalloc(182,236););
printStats();
void* p240 = last_address;
PRINT_POINTER(srealloc(p218,97););
printStats();
void* p241 = last_address;
PRINT_POINTER(srealloc(p225,49););
printStats();
void* p242 = last_address;
PRINT_POINTER(scalloc(94,228););
printStats();
void* p243 = last_address;
PRINT_POINTER(scalloc(180,4););
printStats();
void* p244 = last_address;
DEBUG_PRINT(sfree(p128););
printStats();
PRINT_POINTER(scalloc(30,247););
printStats();
void* p245 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p246 = last_address;
DEBUG_PRINT(sfree(p206););
printStats();
DEBUG_PRINT(sfree(p239););
printStats();
DEBUG_PRINT(sfree(p178););
printStats();
PRINT_POINTER(scalloc(32,133););
printStats();
void* p247 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p248 = last_address;
PRINT_POINTER(srealloc(p215,78););
printStats();
void* p249 = last_address;
PRINT_POINTER(srealloc(p235,228););
printStats();
void* p250 = last_address;
DEBUG_PRINT(sfree(p244););
printStats();
PRINT_POINTER(srealloc(p165,69););
printStats();
void* p251 = last_address;
PRINT_POINTER(scalloc(137,182););
printStats();
void* p252 = last_address;
DEBUG_PRINT(sfree(p243););
printStats();
PRINT_POINTER(srealloc(p252,174););
printStats();
void* p253 = last_address;
PRINT_POINTER(scalloc(16,201););
printStats();
void* p254 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p255 = last_address;
PRINT_POINTER(scalloc(156,196););
printStats();
void* p256 = last_address;
PRINT_POINTER(scalloc(53,83););
printStats();
void* p257 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p258 = last_address;
PRINT_POINTER(scalloc(3,209););
printStats();
void* p259 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p260 = last_address;
PRINT_POINTER(scalloc(79,108););
printStats();
void* p261 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p262 = last_address;
PRINT_POINTER(srealloc(p260,159););
printStats();
void* p263 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p264 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p265 = last_address;
PRINT_POINTER(scalloc(177,33););
printStats();
void* p266 = last_address;
DEBUG_PRINT(sfree(p221););
printStats();
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(scalloc(124,23););
printStats();
void* p267 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p268 = last_address;
PRINT_POINTER(srealloc(p237,77););
printStats();
void* p269 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p270 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
DEBUG_PRINT(sfree(p234););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p271 = last_address;
PRINT_POINTER(srealloc(p176,83););
printStats();
void* p272 = last_address;
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(smalloc(44););
printStats();
void* p273 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p274 = last_address;
PRINT_POINTER(srealloc(p162,188););
printStats();
void* p275 = last_address;
PRINT_POINTER(srealloc(p270,232););
printStats();
void* p276 = last_address;
DEBUG_PRINT(sfree(p157););
printStats();
PRINT_POINTER(smalloc(176););
printStats();
void* p277 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p278 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p279 = last_address;
PRINT_POINTER(srealloc(p208,74););
printStats();
void* p280 = last_address;
DEBUG_PRINT(sfree(p137););
printStats();
PRINT_POINTER(scalloc(206,69););
printStats();
void* p281 = last_address;
PRINT_POINTER(srealloc(p190,79););
printStats();
void* p282 = last_address;
PRINT_POINTER(scalloc(143,51););
printStats();
void* p283 = last_address;
DEBUG_PRINT(sfree(p247););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p284 = last_address;
DEBUG_PRINT(sfree(p278););
printStats();
PRINT_POINTER(srealloc(p209,234););
printStats();
void* p285 = last_address;
PRINT_POINTER(srealloc(p188,145););
printStats();
void* p286 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p287 = last_address;
DEBUG_PRINT(sfree(p283););
printStats();
DEBUG_PRINT(sfree(p158););
printStats();
PRINT_POINTER(srealloc(p284,188););
printStats();
void* p288 = last_address;
PRINT_POINTER(srealloc(p277,107););
printStats();
void* p289 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p290 = last_address;
PRINT_POINTER(scalloc(85,164););
printStats();
void* p291 = last_address;
PRINT_POINTER(scalloc(77,119););
printStats();
void* p292 = last_address;
PRINT_POINTER(scalloc(152,81););
printStats();
void* p293 = last_address;
PRINT_POINTER(scalloc(116,222););
printStats();
void* p294 = last_address;
PRINT_POINTER(scalloc(49,197););
printStats();
void* p295 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p296 = last_address;
PRINT_POINTER(srealloc(p236,136););
printStats();
void* p297 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p298 = last_address;
PRINT_POINTER(scalloc(148,77););
printStats();
void* p299 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p300 = last_address;
PRINT_POINTER(srealloc(p232,66););
printStats();
void* p301 = last_address;
PRINT_POINTER(srealloc(p281,66););
printStats();
void* p302 = last_address;
DEBUG_PRINT(sfree(p241););
printStats();
PRINT_POINTER(smalloc(177););
printStats();
void* p303 = last_address;
PRINT_POINTER(scalloc(93,198););
printStats();
void* p304 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p305 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p306 = last_address;
PRINT_POINTER(scalloc(21,207););
printStats();
void* p307 = last_address;
PRINT_POINTER(scalloc(42,135););
printStats();
void* p308 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p309 = last_address;
DEBUG_PRINT(sfree(p251););
printStats();
DEBUG_PRINT(sfree(p306););
printStats();
DEBUG_PRINT(sfree(p117););
printStats();
PRINT_POINTER(smalloc(38););
printStats();
void* p310 = last_address;
PRINT_POINTER(srealloc(p282,39););
printStats();
void* p311 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p312 = last_address;
PRINT_POINTER(srealloc(p266,92););
printStats();
void* p313 = last_address;
PRINT_POINTER(srealloc(p267,125););
printStats();
void* p314 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
PRINT_POINTER(srealloc(p219,153););
printStats();
void* p315 = last_address;
PRINT_POINTER(scalloc(225,28););
printStats();
void* p316 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p317 = last_address;
PRINT_POINTER(srealloc(p246,227););
printStats();
void* p318 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p319 = last_address;
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p320 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p321 = last_address;
PRINT_POINTER(scalloc(55,56););
printStats();
void* p322 = last_address;
PRINT_POINTER(scalloc(90,240););
printStats();
void* p323 = last_address;
DEBUG_PRINT(sfree(p304););
printStats();
PRINT_POINTER(scalloc(115,160););
printStats();
void* p324 = last_address;
PRINT_POINTER(srealloc(p111,37););
printStats();
void* p325 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p326 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p327 = last_address;
PRINT_POINTER(srealloc(p114,237););
printStats();
void* p328 = last_address;
DEBUG_PRINT(sfree(p310););
printStats();
PRINT_POINTER(smalloc(75););
printStats();
void* p329 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p330 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p331 = last_address;
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(smalloc(97););
printStats();
void* p332 = last_address;
DEBUG_PRINT(sfree(p292););
printStats();
PRINT_POINTER(smalloc(117););
printStats();
void* p333 = last_address;
DEBUG_PRINT(sfree(p217););
printStats();
PRINT_POINTER(scalloc(17,73););
printStats();
void* p334 = last_address;
DEBUG_PRINT(sfree(p320););
printStats();
DEBUG_PRINT(sfree(p322););
printStats();
DEBUG_PRINT(sfree(p332););
printStats();
PRINT_POINTER(scalloc(155,143););
printStats();
void* p335 = last_address;
DEBUG_PRINT(sfree(p81););
printStats();
PRINT_POINTER(smalloc(174););
printStats();
void* p336 = last_address;
}
