#include "aux_macro.h"
#include "../malloc_2.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(209););
printStats();
void* p0 = last_address;
PRINT_POINTER(scalloc(235,127););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(smalloc(203););
printStats();
void* p2 = last_address;
PRINT_POINTER(srealloc(p2,64););
printStats();
void* p3 = last_address;
PRINT_POINTER(srealloc(p3,66););
printStats();
void* p4 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
PRINT_POINTER(scalloc(86,195););
printStats();
void* p5 = last_address;
PRINT_POINTER(scalloc(242,106););
printStats();
void* p6 = last_address;
PRINT_POINTER(scalloc(244,153););
printStats();
void* p7 = last_address;
PRINT_POINTER(srealloc(p6,155););
printStats();
void* p8 = last_address;
PRINT_POINTER(srealloc(p8,105););
printStats();
void* p9 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(scalloc(47,216););
printStats();
void* p10 = last_address;
PRINT_POINTER(scalloc(155,224););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(214,213););
printStats();
void* p12 = last_address;
PRINT_POINTER(srealloc(p12,184););
printStats();
void* p13 = last_address;
DEBUG_PRINT(sfree(p13););
printStats();
PRINT_POINTER(smalloc(121););
printStats();
void* p14 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
PRINT_POINTER(srealloc(p10,128););
printStats();
void* p15 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p16 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p17 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(smalloc(193););
printStats();
void* p18 = last_address;
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(scalloc(76,243););
printStats();
void* p19 = last_address;
PRINT_POINTER(srealloc(p9,30););
printStats();
void* p20 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p21 = last_address;
PRINT_POINTER(scalloc(157,141););
printStats();
void* p22 = last_address;
PRINT_POINTER(srealloc(p18,171););
printStats();
void* p23 = last_address;
DEBUG_PRINT(sfree(p20););
printStats();
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(scalloc(151,40););
printStats();
void* p24 = last_address;
DEBUG_PRINT(sfree(p19););
printStats();
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(scalloc(207,24););
printStats();
void* p25 = last_address;
DEBUG_PRINT(sfree(p23););
printStats();
PRINT_POINTER(smalloc(21););
printStats();
void* p26 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(srealloc(p24,209););
printStats();
void* p27 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p28 = last_address;
PRINT_POINTER(scalloc(195,124););
printStats();
void* p29 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p30 = last_address;
DEBUG_PRINT(sfree(p27););
printStats();
PRINT_POINTER(srealloc(p26,93););
printStats();
void* p31 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p32 = last_address;
PRINT_POINTER(srealloc(p28,92););
printStats();
void* p33 = last_address;
PRINT_POINTER(scalloc(120,238););
printStats();
void* p34 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p35 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
DEBUG_PRINT(sfree(p30););
printStats();
DEBUG_PRINT(sfree(p32););
printStats();
PRINT_POINTER(scalloc(181,15););
printStats();
void* p36 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p37 = last_address;
PRINT_POINTER(srealloc(p35,185););
printStats();
void* p38 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p39 = last_address;
PRINT_POINTER(srealloc(p37,140););
printStats();
void* p40 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(srealloc(p36,200););
printStats();
void* p41 = last_address;
PRINT_POINTER(srealloc(p40,127););
printStats();
void* p42 = last_address;
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(scalloc(160,207););
printStats();
void* p43 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p44 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
PRINT_POINTER(smalloc(71););
printStats();
void* p45 = last_address;
PRINT_POINTER(scalloc(179,112););
printStats();
void* p46 = last_address;
PRINT_POINTER(scalloc(241,135););
printStats();
void* p47 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p48 = last_address;
PRINT_POINTER(scalloc(137,153););
printStats();
void* p49 = last_address;
DEBUG_PRINT(sfree(p42););
printStats();
PRINT_POINTER(scalloc(136,223););
printStats();
void* p50 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(srealloc(p34,0););
printStats();
void* p51 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
PRINT_POINTER(smalloc(232););
printStats();
void* p52 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
DEBUG_PRINT(sfree(p49););
printStats();
DEBUG_PRINT(sfree(p52););
printStats();
PRINT_POINTER(scalloc(135,68););
printStats();
void* p53 = last_address;
PRINT_POINTER(scalloc(22,105););
printStats();
void* p54 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p55 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p56 = last_address;
PRINT_POINTER(srealloc(p47,240););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(89,20););
printStats();
void* p58 = last_address;
PRINT_POINTER(scalloc(70,50););
printStats();
void* p59 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p60 = last_address;
PRINT_POINTER(srealloc(p60,70););
printStats();
void* p61 = last_address;
PRINT_POINTER(srealloc(p53,86););
printStats();
void* p62 = last_address;
PRINT_POINTER(scalloc(9,122););
printStats();
void* p63 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p64 = last_address;
PRINT_POINTER(scalloc(142,35););
printStats();
void* p65 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p66 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p67 = last_address;
PRINT_POINTER(scalloc(157,115););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p54,93););
printStats();
void* p69 = last_address;
PRINT_POINTER(scalloc(63,190););
printStats();
void* p70 = last_address;
PRINT_POINTER(srealloc(p67,195););
printStats();
void* p71 = last_address;
PRINT_POINTER(srealloc(p57,186););
printStats();
void* p72 = last_address;
PRINT_POINTER(scalloc(239,137););
printStats();
void* p73 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(srealloc(p44,209););
printStats();
void* p74 = last_address;
PRINT_POINTER(srealloc(p65,150););
printStats();
void* p75 = last_address;
PRINT_POINTER(scalloc(24,97););
printStats();
void* p76 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p77 = last_address;
DEBUG_PRINT(sfree(p55););
printStats();
DEBUG_PRINT(sfree(p71););
printStats();
PRINT_POINTER(srealloc(p48,228););
printStats();
void* p78 = last_address;
PRINT_POINTER(srealloc(p76,92););
printStats();
void* p79 = last_address;
PRINT_POINTER(scalloc(146,194););
printStats();
void* p80 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p81 = last_address;
PRINT_POINTER(srealloc(p75,143););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p83 = last_address;
PRINT_POINTER(srealloc(p50,91););
printStats();
void* p84 = last_address;
DEBUG_PRINT(sfree(p63););
printStats();
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(smalloc(191););
printStats();
void* p85 = last_address;
DEBUG_PRINT(sfree(p58););
printStats();
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(scalloc(220,131););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p80,32););
printStats();
void* p87 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p88 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
PRINT_POINTER(scalloc(83,121););
printStats();
void* p89 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p90 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(srealloc(p74,41););
printStats();
void* p91 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p92 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
DEBUG_PRINT(sfree(p66););
printStats();
DEBUG_PRINT(sfree(p70););
printStats();
DEBUG_PRINT(sfree(p87););
printStats();
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(scalloc(6,82););
printStats();
void* p93 = last_address;
PRINT_POINTER(scalloc(45,243););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p95 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p96 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(smalloc(134););
printStats();
void* p97 = last_address;
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(smalloc(31););
printStats();
void* p98 = last_address;
DEBUG_PRINT(sfree(p79););
printStats();
PRINT_POINTER(srealloc(p88,137););
printStats();
void* p99 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p100 = last_address;
PRINT_POINTER(srealloc(p94,95););
printStats();
void* p101 = last_address;
PRINT_POINTER(scalloc(191,35););
printStats();
void* p102 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p103 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p104 = last_address;
PRINT_POINTER(scalloc(182,53););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p104,132););
printStats();
void* p106 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p107 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(scalloc(105,23););
printStats();
void* p108 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p109 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p110 = last_address;
PRINT_POINTER(scalloc(173,119););
printStats();
void* p111 = last_address;
PRINT_POINTER(scalloc(65,137););
printStats();
void* p112 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p113 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p114 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p115 = last_address;
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(srealloc(p92,0););
printStats();
void* p116 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p117 = last_address;
DEBUG_PRINT(sfree(p111););
printStats();
PRINT_POINTER(srealloc(p99,170););
printStats();
void* p118 = last_address;
PRINT_POINTER(scalloc(64,207););
printStats();
void* p119 = last_address;
PRINT_POINTER(scalloc(239,51););
printStats();
void* p120 = last_address;
PRINT_POINTER(srealloc(p85,12););
printStats();
void* p121 = last_address;
PRINT_POINTER(srealloc(p110,61););
printStats();
void* p122 = last_address;
DEBUG_PRINT(sfree(p93););
printStats();
DEBUG_PRINT(sfree(p68););
printStats();
PRINT_POINTER(srealloc(p117,232););
printStats();
void* p123 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
DEBUG_PRINT(sfree(p120););
printStats();
DEBUG_PRINT(sfree(p115););
printStats();
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(smalloc(87););
printStats();
void* p124 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p125 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
DEBUG_PRINT(sfree(p125););
printStats();
PRINT_POINTER(smalloc(179););
printStats();
void* p126 = last_address;
DEBUG_PRINT(sfree(p112););
printStats();
DEBUG_PRINT(sfree(p108););
printStats();
PRINT_POINTER(srealloc(p106,68););
printStats();
void* p127 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p128 = last_address;
PRINT_POINTER(scalloc(148,14););
printStats();
void* p129 = last_address;
PRINT_POINTER(scalloc(41,1););
printStats();
void* p130 = last_address;
PRINT_POINTER(srealloc(p118,203););
printStats();
void* p131 = last_address;
PRINT_POINTER(scalloc(88,241););
printStats();
void* p132 = last_address;
PRINT_POINTER(srealloc(p132,29););
printStats();
void* p133 = last_address;
PRINT_POINTER(scalloc(3,230););
printStats();
void* p134 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(smalloc(47););
printStats();
void* p135 = last_address;
PRINT_POINTER(scalloc(237,107););
printStats();
void* p136 = last_address;
DEBUG_PRINT(sfree(p62););
printStats();
DEBUG_PRINT(sfree(p81););
printStats();
PRINT_POINTER(smalloc(85););
printStats();
void* p137 = last_address;
PRINT_POINTER(srealloc(p124,117););
printStats();
void* p138 = last_address;
PRINT_POINTER(srealloc(p107,30););
printStats();
void* p139 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p140 = last_address;
PRINT_POINTER(srealloc(p56,103););
printStats();
void* p141 = last_address;
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(srealloc(p131,96););
printStats();
void* p142 = last_address;
DEBUG_PRINT(sfree(p136););
printStats();
PRINT_POINTER(scalloc(156,180););
printStats();
void* p143 = last_address;
PRINT_POINTER(scalloc(48,57););
printStats();
void* p144 = last_address;
PRINT_POINTER(scalloc(40,26););
printStats();
void* p145 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
DEBUG_PRINT(sfree(p135););
printStats();
PRINT_POINTER(srealloc(p123,3););
printStats();
void* p146 = last_address;
PRINT_POINTER(srealloc(p96,10););
printStats();
void* p147 = last_address;
PRINT_POINTER(scalloc(154,68););
printStats();
void* p148 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(smalloc(237););
printStats();
void* p149 = last_address;
PRINT_POINTER(srealloc(p86,199););
printStats();
void* p150 = last_address;
PRINT_POINTER(scalloc(169,110););
printStats();
void* p151 = last_address;
PRINT_POINTER(scalloc(43,215););
printStats();
void* p152 = last_address;
PRINT_POINTER(srealloc(p137,65););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(59,60););
printStats();
void* p154 = last_address;
PRINT_POINTER(scalloc(3,56););
printStats();
void* p155 = last_address;
PRINT_POINTER(srealloc(p146,80););
printStats();
void* p156 = last_address;
DEBUG_PRINT(sfree(p121););
printStats();
PRINT_POINTER(srealloc(p153,115););
printStats();
void* p157 = last_address;
PRINT_POINTER(scalloc(71,50););
printStats();
void* p158 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p159 = last_address;
DEBUG_PRINT(sfree(p83););
printStats();
PRINT_POINTER(smalloc(131););
printStats();
void* p160 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p161 = last_address;
DEBUG_PRINT(sfree(p95););
printStats();
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(srealloc(p149,245););
printStats();
void* p162 = last_address;
PRINT_POINTER(scalloc(116,202););
printStats();
void* p163 = last_address;
DEBUG_PRINT(sfree(p105););
printStats();
PRINT_POINTER(scalloc(65,178););
printStats();
void* p164 = last_address;
PRINT_POINTER(scalloc(106,157););
printStats();
void* p165 = last_address;
DEBUG_PRINT(sfree(p158););
printStats();
PRINT_POINTER(smalloc(96););
printStats();
void* p166 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p167 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p168 = last_address;
DEBUG_PRINT(sfree(p165););
printStats();
DEBUG_PRINT(sfree(p82););
printStats();
PRINT_POINTER(smalloc(177););
printStats();
void* p169 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p170 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p171 = last_address;
PRINT_POINTER(srealloc(p116,193););
printStats();
void* p172 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p173 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p174 = last_address;
PRINT_POINTER(srealloc(p150,14););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p164););
printStats();
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(srealloc(p156,170););
printStats();
void* p176 = last_address;
PRINT_POINTER(scalloc(45,104););
printStats();
void* p177 = last_address;
DEBUG_PRINT(sfree(p168););
printStats();
PRINT_POINTER(scalloc(143,213););
printStats();
void* p178 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p179 = last_address;
PRINT_POINTER(scalloc(143,23););
printStats();
void* p180 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p181 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p182 = last_address;
PRINT_POINTER(srealloc(p114,213););
printStats();
void* p183 = last_address;
PRINT_POINTER(srealloc(p144,239););
printStats();
void* p184 = last_address;
DEBUG_PRINT(sfree(p160););
printStats();
PRINT_POINTER(srealloc(p41,14););
printStats();
void* p185 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p186 = last_address;
PRINT_POINTER(scalloc(97,155););
printStats();
void* p187 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p188 = last_address;
DEBUG_PRINT(sfree(p178););
printStats();
PRINT_POINTER(smalloc(234););
printStats();
void* p189 = last_address;
PRINT_POINTER(srealloc(p128,78););
printStats();
void* p190 = last_address;
PRINT_POINTER(scalloc(171,26););
printStats();
void* p191 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p192 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p193 = last_address;
PRINT_POINTER(srealloc(p143,206););
printStats();
void* p194 = last_address;
PRINT_POINTER(srealloc(p182,0););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p133););
printStats();
PRINT_POINTER(scalloc(94,55););
printStats();
void* p196 = last_address;
PRINT_POINTER(scalloc(128,193););
printStats();
void* p197 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p198 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
PRINT_POINTER(smalloc(33););
printStats();
void* p199 = last_address;
PRINT_POINTER(srealloc(p140,136););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p163,163););
printStats();
void* p201 = last_address;
PRINT_POINTER(scalloc(8,67););
printStats();
void* p202 = last_address;
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(smalloc(1););
printStats();
void* p203 = last_address;
PRINT_POINTER(scalloc(90,159););
printStats();
void* p204 = last_address;
PRINT_POINTER(srealloc(p195,215););
printStats();
void* p205 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p206 = last_address;
PRINT_POINTER(srealloc(p154,182););
printStats();
void* p207 = last_address;
PRINT_POINTER(srealloc(p151,172););
printStats();
void* p208 = last_address;
PRINT_POINTER(srealloc(p145,144););
printStats();
void* p209 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p210 = last_address;
PRINT_POINTER(scalloc(217,19););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(192,40););
printStats();
void* p212 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p213 = last_address;
PRINT_POINTER(srealloc(p203,237););
printStats();
void* p214 = last_address;
PRINT_POINTER(srealloc(p208,23););
printStats();
void* p215 = last_address;
PRINT_POINTER(scalloc(15,103););
printStats();
void* p216 = last_address;
PRINT_POINTER(scalloc(126,24););
printStats();
void* p217 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p218 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p219 = last_address;
DEBUG_PRINT(sfree(p206););
printStats();
DEBUG_PRINT(sfree(p130););
printStats();
DEBUG_PRINT(sfree(p207););
printStats();
DEBUG_PRINT(sfree(p194););
printStats();
PRINT_POINTER(srealloc(p171,188););
printStats();
void* p220 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p221 = last_address;
DEBUG_PRINT(sfree(p213););
printStats();
PRINT_POINTER(scalloc(191,188););
printStats();
void* p222 = last_address;
PRINT_POINTER(scalloc(55,153););
printStats();
void* p223 = last_address;
PRINT_POINTER(srealloc(p212,154););
printStats();
void* p224 = last_address;
DEBUG_PRINT(sfree(p191););
printStats();
PRINT_POINTER(smalloc(195););
printStats();
void* p225 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p226 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p227 = last_address;
DEBUG_PRINT(sfree(p122););
printStats();
PRINT_POINTER(srealloc(p225,53););
printStats();
void* p228 = last_address;
DEBUG_PRINT(sfree(p129););
printStats();
DEBUG_PRINT(sfree(p84););
printStats();
PRINT_POINTER(scalloc(246,131););
printStats();
void* p229 = last_address;
PRINT_POINTER(scalloc(82,171););
printStats();
void* p230 = last_address;
PRINT_POINTER(srealloc(p197,16););
printStats();
void* p231 = last_address;
PRINT_POINTER(scalloc(84,162););
printStats();
void* p232 = last_address;
DEBUG_PRINT(sfree(p174););
printStats();
PRINT_POINTER(scalloc(242,82););
printStats();
void* p233 = last_address;
PRINT_POINTER(scalloc(84,175););
printStats();
void* p234 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p235 = last_address;
PRINT_POINTER(srealloc(p175,104););
printStats();
void* p236 = last_address;
PRINT_POINTER(scalloc(62,94););
printStats();
void* p237 = last_address;
DEBUG_PRINT(sfree(p161););
printStats();
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(srealloc(p152,88););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p177,69););
printStats();
void* p239 = last_address;
PRINT_POINTER(scalloc(235,152););
printStats();
void* p240 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p241 = last_address;
PRINT_POINTER(srealloc(p219,171););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p227););
printStats();
PRINT_POINTER(smalloc(246););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p204););
printStats();
DEBUG_PRINT(sfree(p126););
printStats();
PRINT_POINTER(smalloc(160););
printStats();
void* p244 = last_address;
PRINT_POINTER(scalloc(47,230););
printStats();
void* p245 = last_address;
DEBUG_PRINT(sfree(p190););
printStats();
PRINT_POINTER(smalloc(170););
printStats();
void* p246 = last_address;
DEBUG_PRINT(sfree(p200););
printStats();
PRINT_POINTER(srealloc(p100,171););
printStats();
void* p247 = last_address;
DEBUG_PRINT(sfree(p221););
printStats();
PRINT_POINTER(srealloc(p98,224););
printStats();
void* p248 = last_address;
PRINT_POINTER(scalloc(22,204););
printStats();
void* p249 = last_address;
PRINT_POINTER(srealloc(p244,159););
printStats();
void* p250 = last_address;
PRINT_POINTER(srealloc(p193,117););
printStats();
void* p251 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p252 = last_address;
PRINT_POINTER(scalloc(70,200););
printStats();
void* p253 = last_address;
PRINT_POINTER(scalloc(31,178););
printStats();
void* p254 = last_address;
PRINT_POINTER(scalloc(31,88););
printStats();
void* p255 = last_address;
PRINT_POINTER(scalloc(126,118););
printStats();
void* p256 = last_address;
PRINT_POINTER(srealloc(p166,55););
printStats();
void* p257 = last_address;
DEBUG_PRINT(sfree(p228););
printStats();
PRINT_POINTER(smalloc(198););
printStats();
void* p258 = last_address;
PRINT_POINTER(srealloc(p187,209););
printStats();
void* p259 = last_address;
PRINT_POINTER(srealloc(p202,3););
printStats();
void* p260 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p261 = last_address;
PRINT_POINTER(scalloc(138,47););
printStats();
void* p262 = last_address;
PRINT_POINTER(srealloc(p260,245););
printStats();
void* p263 = last_address;
DEBUG_PRINT(sfree(p220););
printStats();
PRINT_POINTER(smalloc(231););
printStats();
void* p264 = last_address;
PRINT_POINTER(srealloc(p229,68););
printStats();
void* p265 = last_address;
PRINT_POINTER(scalloc(131,173););
printStats();
void* p266 = last_address;
PRINT_POINTER(scalloc(222,154););
printStats();
void* p267 = last_address;
PRINT_POINTER(scalloc(110,174););
printStats();
void* p268 = last_address;
PRINT_POINTER(srealloc(p155,46););
printStats();
void* p269 = last_address;
PRINT_POINTER(srealloc(p234,149););
printStats();
void* p270 = last_address;
PRINT_POINTER(scalloc(155,98););
printStats();
void* p271 = last_address;
PRINT_POINTER(scalloc(224,169););
printStats();
void* p272 = last_address;
DEBUG_PRINT(sfree(p236););
printStats();
PRINT_POINTER(smalloc(233););
printStats();
void* p273 = last_address;
PRINT_POINTER(srealloc(p226,187););
printStats();
void* p274 = last_address;
PRINT_POINTER(srealloc(p61,9););
printStats();
void* p275 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p276 = last_address;
PRINT_POINTER(srealloc(p184,201););
printStats();
void* p277 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p278 = last_address;
PRINT_POINTER(srealloc(p217,227););
printStats();
void* p279 = last_address;
PRINT_POINTER(srealloc(p256,219););
printStats();
void* p280 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p281 = last_address;
PRINT_POINTER(scalloc(100,37););
printStats();
void* p282 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p283 = last_address;
PRINT_POINTER(srealloc(p167,165););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p235,237););
printStats();
void* p285 = last_address;
PRINT_POINTER(srealloc(p237,87););
printStats();
void* p286 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p287 = last_address;
DEBUG_PRINT(sfree(p259););
printStats();
PRINT_POINTER(srealloc(p157,127););
printStats();
void* p288 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p289 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
PRINT_POINTER(scalloc(218,16););
printStats();
void* p290 = last_address;
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(smalloc(174););
printStats();
void* p291 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p292 = last_address;
PRINT_POINTER(scalloc(22,150););
printStats();
void* p293 = last_address;
PRINT_POINTER(srealloc(p238,125););
printStats();
void* p294 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
DEBUG_PRINT(sfree(p275););
printStats();
DEBUG_PRINT(sfree(p258););
printStats();
DEBUG_PRINT(sfree(p183););
printStats();
PRINT_POINTER(scalloc(86,201););
printStats();
void* p295 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p296 = last_address;
}
