#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(168,201););
printStats();
void* p0 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(scalloc(90,103););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(scalloc(103,82););
printStats();
void* p2 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(scalloc(15,183););
printStats();
void* p3 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p4 = last_address;
PRINT_POINTER(scalloc(224,64););
printStats();
void* p5 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p6 = last_address;
PRINT_POINTER(scalloc(13,186););
printStats();
void* p7 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p8 = last_address;
PRINT_POINTER(scalloc(15,22););
printStats();
void* p9 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
PRINT_POINTER(smalloc(31););
printStats();
void* p10 = last_address;
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(scalloc(222,231););
printStats();
void* p11 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p12 = last_address;
PRINT_POINTER(scalloc(239,18););
printStats();
void* p13 = last_address;
PRINT_POINTER(srealloc(p12,159););
printStats();
void* p14 = last_address;
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(smalloc(92););
printStats();
void* p15 = last_address;
PRINT_POINTER(srealloc(p11,104););
printStats();
void* p16 = last_address;
PRINT_POINTER(srealloc(p15,107););
printStats();
void* p17 = last_address;
PRINT_POINTER(srealloc(p13,56););
printStats();
void* p18 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(srealloc(p8,99););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p20 = last_address;
PRINT_POINTER(srealloc(p9,81););
printStats();
void* p21 = last_address;
PRINT_POINTER(srealloc(p19,129););
printStats();
void* p22 = last_address;
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(srealloc(p3,87););
printStats();
void* p23 = last_address;
PRINT_POINTER(srealloc(p23,137););
printStats();
void* p24 = last_address;
PRINT_POINTER(scalloc(238,244););
printStats();
void* p25 = last_address;
PRINT_POINTER(srealloc(p14,13););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p20,0););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p26););
printStats();
PRINT_POINTER(scalloc(175,68););
printStats();
void* p28 = last_address;
PRINT_POINTER(srealloc(p25,158););
printStats();
void* p29 = last_address;
PRINT_POINTER(srealloc(p21,89););
printStats();
void* p30 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p31 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
PRINT_POINTER(srealloc(p10,209););
printStats();
void* p32 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(smalloc(174););
printStats();
void* p33 = last_address;
PRINT_POINTER(srealloc(p29,1););
printStats();
void* p34 = last_address;
PRINT_POINTER(srealloc(p31,35););
printStats();
void* p35 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p36 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(204,106););
printStats();
void* p38 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(smalloc(226););
printStats();
void* p39 = last_address;
PRINT_POINTER(scalloc(168,43););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p35,202););
printStats();
void* p41 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
PRINT_POINTER(smalloc(26););
printStats();
void* p42 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p43 = last_address;
PRINT_POINTER(scalloc(53,223););
printStats();
void* p44 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
PRINT_POINTER(smalloc(198););
printStats();
void* p45 = last_address;
PRINT_POINTER(srealloc(p27,6););
printStats();
void* p46 = last_address;
PRINT_POINTER(srealloc(p32,128););
printStats();
void* p47 = last_address;
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(srealloc(p43,60););
printStats();
void* p48 = last_address;
PRINT_POINTER(scalloc(76,180););
printStats();
void* p49 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p50 = last_address;
PRINT_POINTER(scalloc(219,33););
printStats();
void* p51 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p52 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p53 = last_address;
PRINT_POINTER(srealloc(p22,218););
printStats();
void* p54 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(smalloc(114););
printStats();
void* p55 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p56 = last_address;
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(scalloc(203,87););
printStats();
void* p57 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p58 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p59 = last_address;
PRINT_POINTER(srealloc(p42,232););
printStats();
void* p60 = last_address;
DEBUG_PRINT(sfree(p56););
printStats();
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(scalloc(199,120););
printStats();
void* p61 = last_address;
DEBUG_PRINT(sfree(p47););
printStats();
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(srealloc(p61,116););
printStats();
void* p62 = last_address;
PRINT_POINTER(srealloc(p48,137););
printStats();
void* p63 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p64 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p65 = last_address;
PRINT_POINTER(scalloc(136,142););
printStats();
void* p66 = last_address;
PRINT_POINTER(scalloc(70,15););
printStats();
void* p67 = last_address;
PRINT_POINTER(scalloc(244,22););
printStats();
void* p68 = last_address;
PRINT_POINTER(scalloc(32,180););
printStats();
void* p69 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p70 = last_address;
PRINT_POINTER(scalloc(241,201););
printStats();
void* p71 = last_address;
PRINT_POINTER(scalloc(61,243););
printStats();
void* p72 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p73 = last_address;
DEBUG_PRINT(sfree(p63););
printStats();
DEBUG_PRINT(sfree(p70););
printStats();
DEBUG_PRINT(sfree(p62););
printStats();
PRINT_POINTER(srealloc(p57,140););
printStats();
void* p74 = last_address;
PRINT_POINTER(scalloc(34,90););
printStats();
void* p75 = last_address;
PRINT_POINTER(scalloc(56,84););
printStats();
void* p76 = last_address;
DEBUG_PRINT(sfree(p30););
printStats();
PRINT_POINTER(srealloc(p46,227););
printStats();
void* p77 = last_address;
PRINT_POINTER(scalloc(97,247););
printStats();
void* p78 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(srealloc(p52,108););
printStats();
void* p79 = last_address;
PRINT_POINTER(srealloc(p71,245););
printStats();
void* p80 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p81 = last_address;
DEBUG_PRINT(sfree(p68););
printStats();
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(scalloc(44,159););
printStats();
void* p82 = last_address;
PRINT_POINTER(scalloc(148,230););
printStats();
void* p83 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
DEBUG_PRINT(sfree(p55););
printStats();
PRINT_POINTER(smalloc(156););
printStats();
void* p84 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(srealloc(p79,61););
printStats();
void* p85 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p85,26););
printStats();
void* p87 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p88 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p89 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
DEBUG_PRINT(sfree(p88););
printStats();
PRINT_POINTER(scalloc(148,96););
printStats();
void* p90 = last_address;
PRINT_POINTER(scalloc(155,138););
printStats();
void* p91 = last_address;
PRINT_POINTER(srealloc(p73,190););
printStats();
void* p92 = last_address;
PRINT_POINTER(scalloc(43,69););
printStats();
void* p93 = last_address;
DEBUG_PRINT(sfree(p66););
printStats();
PRINT_POINTER(smalloc(202););
printStats();
void* p94 = last_address;
DEBUG_PRINT(sfree(p65););
printStats();
PRINT_POINTER(scalloc(111,40););
printStats();
void* p95 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(scalloc(134,79););
printStats();
void* p96 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p97 = last_address;
PRINT_POINTER(scalloc(210,13););
printStats();
void* p98 = last_address;
PRINT_POINTER(scalloc(164,223););
printStats();
void* p99 = last_address;
DEBUG_PRINT(sfree(p80););
printStats();
PRINT_POINTER(smalloc(153););
printStats();
void* p100 = last_address;
PRINT_POINTER(srealloc(p99,48););
printStats();
void* p101 = last_address;
DEBUG_PRINT(sfree(p74););
printStats();
PRINT_POINTER(smalloc(114););
printStats();
void* p102 = last_address;
PRINT_POINTER(srealloc(p54,198););
printStats();
void* p103 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p104 = last_address;
DEBUG_PRINT(sfree(p87););
printStats();
DEBUG_PRINT(sfree(p84););
printStats();
DEBUG_PRINT(sfree(p83););
printStats();
PRINT_POINTER(scalloc(15,202););
printStats();
void* p105 = last_address;
PRINT_POINTER(scalloc(135,84););
printStats();
void* p106 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p107 = last_address;
PRINT_POINTER(scalloc(172,154););
printStats();
void* p108 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p109 = last_address;
PRINT_POINTER(srealloc(p94,41););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p91,62););
printStats();
void* p111 = last_address;
PRINT_POINTER(scalloc(163,11););
printStats();
void* p112 = last_address;
DEBUG_PRINT(sfree(p107););
printStats();
PRINT_POINTER(smalloc(53););
printStats();
void* p113 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p114 = last_address;
DEBUG_PRINT(sfree(p95););
printStats();
PRINT_POINTER(srealloc(p58,25););
printStats();
void* p115 = last_address;
PRINT_POINTER(scalloc(238,44););
printStats();
void* p116 = last_address;
DEBUG_PRINT(sfree(p92););
printStats();
PRINT_POINTER(scalloc(214,198););
printStats();
void* p117 = last_address;
PRINT_POINTER(scalloc(160,191););
printStats();
void* p118 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p119 = last_address;
PRINT_POINTER(scalloc(114,170););
printStats();
void* p120 = last_address;
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(scalloc(58,110););
printStats();
void* p121 = last_address;
DEBUG_PRINT(sfree(p96););
printStats();
PRINT_POINTER(smalloc(238););
printStats();
void* p122 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p123 = last_address;
PRINT_POINTER(scalloc(215,12););
printStats();
void* p124 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(scalloc(225,4););
printStats();
void* p125 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(scalloc(36,24););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(138,71););
printStats();
void* p127 = last_address;
PRINT_POINTER(scalloc(25,198););
printStats();
void* p128 = last_address;
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(srealloc(p103,17););
printStats();
void* p129 = last_address;
PRINT_POINTER(srealloc(p82,235););
printStats();
void* p130 = last_address;
PRINT_POINTER(srealloc(p112,127););
printStats();
void* p131 = last_address;
DEBUG_PRINT(sfree(p125););
printStats();
PRINT_POINTER(scalloc(21,137););
printStats();
void* p132 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
DEBUG_PRINT(sfree(p116););
printStats();
PRINT_POINTER(srealloc(p89,80););
printStats();
void* p133 = last_address;
PRINT_POINTER(srealloc(p86,110););
printStats();
void* p134 = last_address;
DEBUG_PRINT(sfree(p81););
printStats();
DEBUG_PRINT(sfree(p130););
printStats();
PRINT_POINTER(srealloc(p40,22););
printStats();
void* p135 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p136 = last_address;
PRINT_POINTER(scalloc(184,96););
printStats();
void* p137 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(smalloc(101););
printStats();
void* p138 = last_address;
PRINT_POINTER(scalloc(103,126););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p28););
printStats();
DEBUG_PRINT(sfree(p121););
printStats();
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(scalloc(45,154););
printStats();
void* p140 = last_address;
PRINT_POINTER(srealloc(p137,47););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p132,249););
printStats();
void* p142 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p143 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p144 = last_address;
DEBUG_PRINT(sfree(p129););
printStats();
DEBUG_PRINT(sfree(p126););
printStats();
DEBUG_PRINT(sfree(p117););
printStats();
PRINT_POINTER(scalloc(107,217););
printStats();
void* p145 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p108););
printStats();
DEBUG_PRINT(sfree(p144););
printStats();
DEBUG_PRINT(sfree(p98););
printStats();
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(srealloc(p109,169););
printStats();
void* p147 = last_address;
DEBUG_PRINT(sfree(p133););
printStats();
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(smalloc(87););
printStats();
void* p148 = last_address;
PRINT_POINTER(srealloc(p140,100););
printStats();
void* p149 = last_address;
PRINT_POINTER(scalloc(84,204););
printStats();
void* p150 = last_address;
PRINT_POINTER(srealloc(p143,227););
printStats();
void* p151 = last_address;
PRINT_POINTER(scalloc(7,20););
printStats();
void* p152 = last_address;
PRINT_POINTER(srealloc(p93,135););
printStats();
void* p153 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p154 = last_address;
PRINT_POINTER(srealloc(p128,80););
printStats();
void* p155 = last_address;
PRINT_POINTER(srealloc(p150,187););
printStats();
void* p156 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p157 = last_address;
PRINT_POINTER(scalloc(20,52););
printStats();
void* p158 = last_address;
PRINT_POINTER(srealloc(p111,183););
printStats();
void* p159 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
DEBUG_PRINT(sfree(p155););
printStats();
PRINT_POINTER(smalloc(177););
printStats();
void* p160 = last_address;
PRINT_POINTER(srealloc(p138,140););
printStats();
void* p161 = last_address;
PRINT_POINTER(scalloc(30,0););
printStats();
void* p162 = last_address;
DEBUG_PRINT(sfree(p161););
printStats();
PRINT_POINTER(smalloc(237););
printStats();
void* p163 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p164 = last_address;
DEBUG_PRINT(sfree(p67););
printStats();
PRINT_POINTER(scalloc(76,219););
printStats();
void* p165 = last_address;
PRINT_POINTER(srealloc(p151,17););
printStats();
void* p166 = last_address;
PRINT_POINTER(scalloc(243,211););
printStats();
void* p167 = last_address;
PRINT_POINTER(srealloc(p119,23););
printStats();
void* p168 = last_address;
PRINT_POINTER(srealloc(p149,12););
printStats();
void* p169 = last_address;
PRINT_POINTER(srealloc(p152,84););
printStats();
void* p170 = last_address;
PRINT_POINTER(scalloc(89,248););
printStats();
void* p171 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p172 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
DEBUG_PRINT(sfree(p167););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p173 = last_address;
PRINT_POINTER(srealloc(p170,17););
printStats();
void* p174 = last_address;
DEBUG_PRINT(sfree(p106););
printStats();
PRINT_POINTER(scalloc(168,117););
printStats();
void* p175 = last_address;
PRINT_POINTER(scalloc(48,245););
printStats();
void* p176 = last_address;
PRINT_POINTER(scalloc(150,184););
printStats();
void* p177 = last_address;
DEBUG_PRINT(sfree(p49););
printStats();
PRINT_POINTER(smalloc(104););
printStats();
void* p178 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p179 = last_address;
PRINT_POINTER(scalloc(78,206););
printStats();
void* p180 = last_address;
PRINT_POINTER(srealloc(p156,23););
printStats();
void* p181 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p182 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
DEBUG_PRINT(sfree(p115););
printStats();
PRINT_POINTER(smalloc(164););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(204,60););
printStats();
void* p184 = last_address;
PRINT_POINTER(scalloc(85,43););
printStats();
void* p185 = last_address;
PRINT_POINTER(scalloc(66,76););
printStats();
void* p186 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p187 = last_address;
DEBUG_PRINT(sfree(p146););
printStats();
PRINT_POINTER(scalloc(34,235););
printStats();
void* p188 = last_address;
PRINT_POINTER(srealloc(p157,160););
printStats();
void* p189 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p191 = last_address;
PRINT_POINTER(scalloc(64,36););
printStats();
void* p192 = last_address;
PRINT_POINTER(scalloc(82,141););
printStats();
void* p193 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p194 = last_address;
DEBUG_PRINT(sfree(p135););
printStats();
DEBUG_PRINT(sfree(p160););
printStats();
PRINT_POINTER(smalloc(197););
printStats();
void* p195 = last_address;
PRINT_POINTER(srealloc(p78,14););
printStats();
void* p196 = last_address;
PRINT_POINTER(srealloc(p127,2););
printStats();
void* p197 = last_address;
PRINT_POINTER(srealloc(p110,151););
printStats();
void* p198 = last_address;
PRINT_POINTER(srealloc(p193,50););
printStats();
void* p199 = last_address;
DEBUG_PRINT(sfree(p174););
printStats();
PRINT_POINTER(scalloc(139,235););
printStats();
void* p200 = last_address;
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(srealloc(p190,6););
printStats();
void* p201 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p202 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p203 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p204 = last_address;
PRINT_POINTER(srealloc(p185,110););
printStats();
void* p205 = last_address;
DEBUG_PRINT(sfree(p122););
printStats();
PRINT_POINTER(smalloc(198););
printStats();
void* p206 = last_address;
PRINT_POINTER(scalloc(145,169););
printStats();
void* p207 = last_address;
PRINT_POINTER(srealloc(p145,103););
printStats();
void* p208 = last_address;
PRINT_POINTER(scalloc(162,110););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(32,152););
printStats();
void* p210 = last_address;
PRINT_POINTER(srealloc(p208,56););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(38,90););
printStats();
void* p212 = last_address;
PRINT_POINTER(scalloc(242,180););
printStats();
void* p213 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(scalloc(121,235););
printStats();
void* p214 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
DEBUG_PRINT(sfree(p162););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p215 = last_address;
DEBUG_PRINT(sfree(p200););
printStats();
PRINT_POINTER(smalloc(243););
printStats();
void* p216 = last_address;
PRINT_POINTER(scalloc(27,213););
printStats();
void* p217 = last_address;
PRINT_POINTER(scalloc(135,93););
printStats();
void* p218 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
DEBUG_PRINT(sfree(p105););
printStats();
PRINT_POINTER(scalloc(206,124););
printStats();
void* p219 = last_address;
PRINT_POINTER(scalloc(71,130););
printStats();
void* p220 = last_address;
DEBUG_PRINT(sfree(p153););
printStats();
PRINT_POINTER(smalloc(120););
printStats();
void* p221 = last_address;
PRINT_POINTER(scalloc(46,48););
printStats();
void* p222 = last_address;
PRINT_POINTER(scalloc(131,214););
printStats();
void* p223 = last_address;
PRINT_POINTER(srealloc(p154,87););
printStats();
void* p224 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p225 = last_address;
DEBUG_PRINT(sfree(p221););
printStats();
PRINT_POINTER(scalloc(11,11););
printStats();
void* p226 = last_address;
}
