#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(21););
printStats();
void* p0 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(scalloc(41,52););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(smalloc(178););
printStats();
void* p2 = last_address;
PRINT_POINTER(srealloc(p2,214););
printStats();
void* p3 = last_address;
PRINT_POINTER(scalloc(16,220););
printStats();
void* p4 = last_address;
PRINT_POINTER(srealloc(p4,103););
printStats();
void* p5 = last_address;
PRINT_POINTER(scalloc(133,204););
printStats();
void* p6 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p7 = last_address;
DEBUG_PRINT(sfree(p3););
printStats();
PRINT_POINTER(scalloc(20,121););
printStats();
void* p8 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p9 = last_address;
DEBUG_PRINT(sfree(p9););
printStats();
PRINT_POINTER(smalloc(234););
printStats();
void* p10 = last_address;
PRINT_POINTER(srealloc(p7,172););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(98,32););
printStats();
void* p12 = last_address;
PRINT_POINTER(scalloc(82,70););
printStats();
void* p13 = last_address;
PRINT_POINTER(scalloc(110,116););
printStats();
void* p14 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p15 = last_address;
PRINT_POINTER(srealloc(p13,229););
printStats();
void* p16 = last_address;
PRINT_POINTER(scalloc(81,142););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(195,125););
printStats();
void* p18 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
DEBUG_PRINT(sfree(p16););
printStats();
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(scalloc(208,202););
printStats();
void* p19 = last_address;
PRINT_POINTER(srealloc(p10,116););
printStats();
void* p20 = last_address;
PRINT_POINTER(scalloc(3,81););
printStats();
void* p21 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p22 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p23 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(scalloc(195,4););
printStats();
void* p24 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
PRINT_POINTER(scalloc(76,128););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(148,168););
printStats();
void* p26 = last_address;
DEBUG_PRINT(sfree(p26););
printStats();
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(scalloc(81,120););
printStats();
void* p27 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p28 = last_address;
PRINT_POINTER(scalloc(158,191););
printStats();
void* p29 = last_address;
DEBUG_PRINT(sfree(p23););
printStats();
PRINT_POINTER(smalloc(184););
printStats();
void* p30 = last_address;
PRINT_POINTER(srealloc(p12,47););
printStats();
void* p31 = last_address;
PRINT_POINTER(scalloc(193,3););
printStats();
void* p32 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p33 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p34 = last_address;
DEBUG_PRINT(sfree(p32););
printStats();
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(scalloc(79,26););
printStats();
void* p35 = last_address;
PRINT_POINTER(srealloc(p29,120););
printStats();
void* p36 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p37 = last_address;
PRINT_POINTER(srealloc(p34,190););
printStats();
void* p38 = last_address;
PRINT_POINTER(scalloc(245,239););
printStats();
void* p39 = last_address;
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(smalloc(53););
printStats();
void* p40 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(srealloc(p21,75););
printStats();
void* p41 = last_address;
PRINT_POINTER(scalloc(225,200););
printStats();
void* p42 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p43 = last_address;
PRINT_POINTER(scalloc(160,103););
printStats();
void* p44 = last_address;
PRINT_POINTER(srealloc(p20,78););
printStats();
void* p45 = last_address;
PRINT_POINTER(srealloc(p25,11););
printStats();
void* p46 = last_address;
PRINT_POINTER(srealloc(p39,153););
printStats();
void* p47 = last_address;
PRINT_POINTER(srealloc(p35,139););
printStats();
void* p48 = last_address;
PRINT_POINTER(scalloc(7,24););
printStats();
void* p49 = last_address;
PRINT_POINTER(srealloc(p19,206););
printStats();
void* p50 = last_address;
PRINT_POINTER(srealloc(p50,32););
printStats();
void* p51 = last_address;
PRINT_POINTER(scalloc(16,3););
printStats();
void* p52 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
DEBUG_PRINT(sfree(p42););
printStats();
PRINT_POINTER(srealloc(p47,11););
printStats();
void* p53 = last_address;
PRINT_POINTER(scalloc(29,222););
printStats();
void* p54 = last_address;
PRINT_POINTER(scalloc(196,114););
printStats();
void* p55 = last_address;
PRINT_POINTER(scalloc(210,42););
printStats();
void* p56 = last_address;
PRINT_POINTER(scalloc(5,25););
printStats();
void* p57 = last_address;
PRINT_POINTER(srealloc(p56,177););
printStats();
void* p58 = last_address;
PRINT_POINTER(scalloc(192,199););
printStats();
void* p59 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(srealloc(p53,173););
printStats();
void* p60 = last_address;
PRINT_POINTER(scalloc(31,26););
printStats();
void* p61 = last_address;
PRINT_POINTER(scalloc(206,125););
printStats();
void* p62 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p63 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p64 = last_address;
PRINT_POINTER(srealloc(p8,109););
printStats();
void* p65 = last_address;
PRINT_POINTER(srealloc(p55,77););
printStats();
void* p66 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p67 = last_address;
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(srealloc(p28,92););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p30,31););
printStats();
void* p69 = last_address;
PRINT_POINTER(scalloc(20,197););
printStats();
void* p70 = last_address;
PRINT_POINTER(srealloc(p61,87););
printStats();
void* p71 = last_address;
PRINT_POINTER(srealloc(p49,151););
printStats();
void* p72 = last_address;
PRINT_POINTER(scalloc(170,39););
printStats();
void* p73 = last_address;
PRINT_POINTER(srealloc(p45,243););
printStats();
void* p74 = last_address;
PRINT_POINTER(scalloc(5,64););
printStats();
void* p75 = last_address;
DEBUG_PRINT(sfree(p73););
printStats();
PRINT_POINTER(scalloc(213,30););
printStats();
void* p76 = last_address;
PRINT_POINTER(scalloc(178,78););
printStats();
void* p77 = last_address;
PRINT_POINTER(srealloc(p44,7););
printStats();
void* p78 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p79 = last_address;
PRINT_POINTER(srealloc(p41,175););
printStats();
void* p80 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p81 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p83 = last_address;
PRINT_POINTER(scalloc(3,242););
printStats();
void* p84 = last_address;
PRINT_POINTER(scalloc(156,1););
printStats();
void* p85 = last_address;
PRINT_POINTER(scalloc(161,132););
printStats();
void* p86 = last_address;
PRINT_POINTER(scalloc(21,28););
printStats();
void* p87 = last_address;
PRINT_POINTER(srealloc(p43,214););
printStats();
void* p88 = last_address;
PRINT_POINTER(scalloc(239,75););
printStats();
void* p89 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p90 = last_address;
PRINT_POINTER(srealloc(p62,99););
printStats();
void* p91 = last_address;
PRINT_POINTER(scalloc(124,19););
printStats();
void* p92 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(smalloc(214););
printStats();
void* p93 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p95 = last_address;
PRINT_POINTER(srealloc(p59,220););
printStats();
void* p96 = last_address;
PRINT_POINTER(srealloc(p90,176););
printStats();
void* p97 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p98 = last_address;
PRINT_POINTER(srealloc(p80,22););
printStats();
void* p99 = last_address;
PRINT_POINTER(srealloc(p11,8););
printStats();
void* p100 = last_address;
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(smalloc(231););
printStats();
void* p101 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p102 = last_address;
PRINT_POINTER(srealloc(p38,153););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p99,137););
printStats();
void* p104 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p105 = last_address;
PRINT_POINTER(scalloc(168,87););
printStats();
void* p106 = last_address;
PRINT_POINTER(scalloc(6,238););
printStats();
void* p107 = last_address;
PRINT_POINTER(srealloc(p84,147););
printStats();
void* p108 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p109 = last_address;
PRINT_POINTER(scalloc(74,140););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p97,84););
printStats();
void* p111 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
DEBUG_PRINT(sfree(p110););
printStats();
PRINT_POINTER(scalloc(175,29););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p67,241););
printStats();
void* p113 = last_address;
PRINT_POINTER(scalloc(160,84););
printStats();
void* p114 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
PRINT_POINTER(srealloc(p93,146););
printStats();
void* p115 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p116 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
PRINT_POINTER(smalloc(94););
printStats();
void* p117 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p118 = last_address;
DEBUG_PRINT(sfree(p83););
printStats();
DEBUG_PRINT(sfree(p87););
printStats();
PRINT_POINTER(smalloc(116););
printStats();
void* p119 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(smalloc(122););
printStats();
void* p120 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p121 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p122 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p123 = last_address;
PRINT_POINTER(srealloc(p123,53););
printStats();
void* p124 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(scalloc(31,164););
printStats();
void* p125 = last_address;
PRINT_POINTER(srealloc(p124,136););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(145,59););
printStats();
void* p127 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(srealloc(p76,193););
printStats();
void* p128 = last_address;
PRINT_POINTER(srealloc(p102,192););
printStats();
void* p129 = last_address;
DEBUG_PRINT(sfree(p128););
printStats();
DEBUG_PRINT(sfree(p58););
printStats();
DEBUG_PRINT(sfree(p117););
printStats();
PRINT_POINTER(srealloc(p65,138););
printStats();
void* p130 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p131 = last_address;
DEBUG_PRINT(sfree(p122););
printStats();
PRINT_POINTER(smalloc(40););
printStats();
void* p132 = last_address;
PRINT_POINTER(scalloc(217,133););
printStats();
void* p133 = last_address;
PRINT_POINTER(scalloc(69,211););
printStats();
void* p134 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p135 = last_address;
PRINT_POINTER(scalloc(155,201););
printStats();
void* p136 = last_address;
PRINT_POINTER(srealloc(p108,180););
printStats();
void* p137 = last_address;
PRINT_POINTER(srealloc(p71,150););
printStats();
void* p138 = last_address;
PRINT_POINTER(scalloc(244,31););
printStats();
void* p139 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p140 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p141 = last_address;
PRINT_POINTER(scalloc(36,121););
printStats();
void* p142 = last_address;
PRINT_POINTER(scalloc(114,107););
printStats();
void* p143 = last_address;
PRINT_POINTER(srealloc(p92,228););
printStats();
void* p144 = last_address;
PRINT_POINTER(scalloc(111,115););
printStats();
void* p145 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p146 = last_address;
PRINT_POINTER(scalloc(231,185););
printStats();
void* p147 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p148 = last_address;
PRINT_POINTER(srealloc(p148,79););
printStats();
void* p149 = last_address;
DEBUG_PRINT(sfree(p106););
printStats();
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(scalloc(169,222););
printStats();
void* p150 = last_address;
DEBUG_PRINT(sfree(p145););
printStats();
PRINT_POINTER(smalloc(189););
printStats();
void* p151 = last_address;
DEBUG_PRINT(sfree(p48););
printStats();
PRINT_POINTER(smalloc(90););
printStats();
void* p152 = last_address;
PRINT_POINTER(srealloc(p109,234););
printStats();
void* p153 = last_address;
DEBUG_PRINT(sfree(p105););
printStats();
PRINT_POINTER(srealloc(p77,69););
printStats();
void* p154 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p155 = last_address;
PRINT_POINTER(scalloc(241,13););
printStats();
void* p156 = last_address;
PRINT_POINTER(scalloc(44,186););
printStats();
void* p157 = last_address;
PRINT_POINTER(srealloc(p129,246););
printStats();
void* p158 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p159 = last_address;
PRINT_POINTER(srealloc(p126,244););
printStats();
void* p160 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(scalloc(175,77););
printStats();
void* p161 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p162 = last_address;
PRINT_POINTER(srealloc(p52,148););
printStats();
void* p163 = last_address;
PRINT_POINTER(scalloc(135,137););
printStats();
void* p164 = last_address;
PRINT_POINTER(srealloc(p142,44););
printStats();
void* p165 = last_address;
PRINT_POINTER(srealloc(p160,30););
printStats();
void* p166 = last_address;
PRINT_POINTER(srealloc(p154,142););
printStats();
void* p167 = last_address;
PRINT_POINTER(srealloc(p107,40););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(16,225););
printStats();
void* p169 = last_address;
PRINT_POINTER(scalloc(30,222););
printStats();
void* p170 = last_address;
DEBUG_PRINT(sfree(p27););
printStats();
DEBUG_PRINT(sfree(p138););
printStats();
DEBUG_PRINT(sfree(p167););
printStats();
PRINT_POINTER(srealloc(p140,28););
printStats();
void* p171 = last_address;
DEBUG_PRINT(sfree(p125););
printStats();
PRINT_POINTER(scalloc(146,65););
printStats();
void* p172 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p173 = last_address;
PRINT_POINTER(scalloc(134,212););
printStats();
void* p174 = last_address;
DEBUG_PRINT(sfree(p146););
printStats();
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(srealloc(p115,177););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p135););
printStats();
DEBUG_PRINT(sfree(p74););
printStats();
PRINT_POINTER(scalloc(57,230););
printStats();
void* p176 = last_address;
PRINT_POINTER(srealloc(p134,132););
printStats();
void* p177 = last_address;
PRINT_POINTER(srealloc(p68,232););
printStats();
void* p178 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p179 = last_address;
PRINT_POINTER(scalloc(2,226););
printStats();
void* p180 = last_address;
PRINT_POINTER(scalloc(58,40););
printStats();
void* p181 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p182 = last_address;
PRINT_POINTER(scalloc(203,91););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(38,59););
printStats();
void* p184 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p185 = last_address;
PRINT_POINTER(scalloc(56,13););
printStats();
void* p186 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
PRINT_POINTER(srealloc(p184,138););
printStats();
void* p187 = last_address;
PRINT_POINTER(scalloc(103,219););
printStats();
void* p188 = last_address;
PRINT_POINTER(srealloc(p149,117););
printStats();
void* p189 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p190 = last_address;
PRINT_POINTER(srealloc(p182,93););
printStats();
void* p191 = last_address;
DEBUG_PRINT(sfree(p121););
printStats();
PRINT_POINTER(scalloc(39,137););
printStats();
void* p192 = last_address;
DEBUG_PRINT(sfree(p137););
printStats();
PRINT_POINTER(srealloc(p119,222););
printStats();
void* p193 = last_address;
PRINT_POINTER(srealloc(p174,117););
printStats();
void* p194 = last_address;
PRINT_POINTER(scalloc(194,68););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(smalloc(15););
printStats();
void* p196 = last_address;
PRINT_POINTER(srealloc(p60,87););
printStats();
void* p197 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p198 = last_address;
PRINT_POINTER(scalloc(91,146););
printStats();
void* p199 = last_address;
DEBUG_PRINT(sfree(p170););
printStats();
DEBUG_PRINT(sfree(p189););
printStats();
PRINT_POINTER(smalloc(215););
printStats();
void* p200 = last_address;
PRINT_POINTER(scalloc(101,4););
printStats();
void* p201 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p202 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p203 = last_address;
DEBUG_PRINT(sfree(p168););
printStats();
PRINT_POINTER(srealloc(p157,161););
printStats();
void* p204 = last_address;
PRINT_POINTER(scalloc(79,186););
printStats();
void* p205 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p206 = last_address;
PRINT_POINTER(srealloc(p139,210););
printStats();
void* p207 = last_address;
DEBUG_PRINT(sfree(p192););
printStats();
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(scalloc(67,121););
printStats();
void* p208 = last_address;
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(srealloc(p82,219););
printStats();
void* p209 = last_address;
PRINT_POINTER(srealloc(p172,42););
printStats();
void* p210 = last_address;
PRINT_POINTER(scalloc(63,204););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(24,122););
printStats();
void* p212 = last_address;
PRINT_POINTER(srealloc(p152,171););
printStats();
void* p213 = last_address;
PRINT_POINTER(srealloc(p96,218););
printStats();
void* p214 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p215 = last_address;
PRINT_POINTER(srealloc(p155,7););
printStats();
void* p216 = last_address;
PRINT_POINTER(scalloc(101,25););
printStats();
void* p217 = last_address;
PRINT_POINTER(scalloc(102,202););
printStats();
void* p218 = last_address;
PRINT_POINTER(srealloc(p118,163););
printStats();
void* p219 = last_address;
PRINT_POINTER(srealloc(p217,241););
printStats();
void* p220 = last_address;
PRINT_POINTER(srealloc(p185,31););
printStats();
void* p221 = last_address;
DEBUG_PRINT(sfree(p95););
printStats();
PRINT_POINTER(scalloc(235,109););
printStats();
void* p222 = last_address;
PRINT_POINTER(scalloc(71,88););
printStats();
void* p223 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p224 = last_address;
PRINT_POINTER(scalloc(159,41););
printStats();
void* p225 = last_address;
PRINT_POINTER(scalloc(109,1););
printStats();
void* p226 = last_address;
PRINT_POINTER(scalloc(60,25););
printStats();
void* p227 = last_address;
PRINT_POINTER(scalloc(28,125););
printStats();
void* p228 = last_address;
PRINT_POINTER(srealloc(p225,111););
printStats();
void* p229 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p230 = last_address;
PRINT_POINTER(scalloc(190,179););
printStats();
void* p231 = last_address;
PRINT_POINTER(scalloc(39,235););
printStats();
void* p232 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p233 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(srealloc(p232,170););
printStats();
void* p234 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p235 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p236 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p237 = last_address;
PRINT_POINTER(srealloc(p220,54););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p196,181););
printStats();
void* p239 = last_address;
PRINT_POINTER(scalloc(59,2););
printStats();
void* p240 = last_address;
PRINT_POINTER(scalloc(105,104););
printStats();
void* p241 = last_address;
PRINT_POINTER(scalloc(86,51););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
PRINT_POINTER(scalloc(234,38););
printStats();
void* p243 = last_address;
PRINT_POINTER(srealloc(p89,80););
printStats();
void* p244 = last_address;
PRINT_POINTER(srealloc(p193,178););
printStats();
void* p245 = last_address;
PRINT_POINTER(scalloc(105,48););
printStats();
void* p246 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p247 = last_address;
PRINT_POINTER(srealloc(p233,68););
printStats();
void* p248 = last_address;
PRINT_POINTER(srealloc(p156,55););
printStats();
void* p249 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p250 = last_address;
PRINT_POINTER(srealloc(p219,175););
printStats();
void* p251 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p252 = last_address;
PRINT_POINTER(scalloc(10,38););
printStats();
void* p253 = last_address;
PRINT_POINTER(srealloc(p188,89););
printStats();
void* p254 = last_address;
PRINT_POINTER(scalloc(170,30););
printStats();
void* p255 = last_address;
DEBUG_PRINT(sfree(p190););
printStats();
PRINT_POINTER(scalloc(128,169););
printStats();
void* p256 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p257 = last_address;
PRINT_POINTER(scalloc(1,11););
printStats();
void* p258 = last_address;
DEBUG_PRINT(sfree(p241););
printStats();
DEBUG_PRINT(sfree(p206););
printStats();
PRINT_POINTER(smalloc(204););
printStats();
void* p259 = last_address;
DEBUG_PRINT(sfree(p213););
printStats();
PRINT_POINTER(srealloc(p144,53););
printStats();
void* p260 = last_address;
PRINT_POINTER(scalloc(248,20););
printStats();
void* p261 = last_address;
PRINT_POINTER(srealloc(p75,126););
printStats();
void* p262 = last_address;
PRINT_POINTER(srealloc(p218,236););
printStats();
void* p263 = last_address;
DEBUG_PRINT(sfree(p214););
printStats();
DEBUG_PRINT(sfree(p204););
printStats();
DEBUG_PRINT(sfree(p243););
printStats();
PRINT_POINTER(smalloc(198););
printStats();
void* p264 = last_address;
PRINT_POINTER(srealloc(p251,52););
printStats();
void* p265 = last_address;
PRINT_POINTER(scalloc(179,163););
printStats();
void* p266 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p267 = last_address;
PRINT_POINTER(srealloc(p198,234););
printStats();
void* p268 = last_address;
DEBUG_PRINT(sfree(p212););
printStats();
PRINT_POINTER(srealloc(p259,109););
printStats();
void* p269 = last_address;
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(scalloc(91,239););
printStats();
void* p270 = last_address;
PRINT_POINTER(srealloc(p230,85););
printStats();
void* p271 = last_address;
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(smalloc(84););
printStats();
void* p272 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p273 = last_address;
PRINT_POINTER(srealloc(p183,184););
printStats();
void* p274 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p275 = last_address;
PRINT_POINTER(srealloc(p63,237););
printStats();
void* p276 = last_address;
PRINT_POINTER(srealloc(p171,247););
printStats();
void* p277 = last_address;
PRINT_POINTER(srealloc(p176,7););
printStats();
void* p278 = last_address;
PRINT_POINTER(srealloc(p258,91););
printStats();
void* p279 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p280 = last_address;
PRINT_POINTER(scalloc(158,96););
printStats();
void* p281 = last_address;
PRINT_POINTER(scalloc(179,208););
printStats();
void* p282 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
DEBUG_PRINT(sfree(p201););
printStats();
PRINT_POINTER(srealloc(p207,187););
printStats();
void* p283 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(smalloc(119););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p158,101););
printStats();
void* p285 = last_address;
DEBUG_PRINT(sfree(p266););
printStats();
PRINT_POINTER(smalloc(94););
printStats();
void* p286 = last_address;
PRINT_POINTER(scalloc(69,158););
printStats();
void* p287 = last_address;
PRINT_POINTER(srealloc(p54,173););
printStats();
void* p288 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p289 = last_address;
PRINT_POINTER(srealloc(p238,67););
printStats();
void* p290 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p291 = last_address;
PRINT_POINTER(scalloc(37,115););
printStats();
void* p292 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p293 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p294 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p295 = last_address;
DEBUG_PRINT(sfree(p153););
printStats();
PRINT_POINTER(smalloc(185););
printStats();
void* p296 = last_address;
DEBUG_PRINT(sfree(p216););
printStats();
PRINT_POINTER(scalloc(236,168););
printStats();
void* p297 = last_address;
PRINT_POINTER(srealloc(p136,84););
printStats();
void* p298 = last_address;
PRINT_POINTER(scalloc(162,143););
printStats();
void* p299 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p300 = last_address;
DEBUG_PRINT(sfree(p194););
printStats();
PRINT_POINTER(smalloc(50););
printStats();
void* p301 = last_address;
DEBUG_PRINT(sfree(p246););
printStats();
PRINT_POINTER(scalloc(13,52););
printStats();
void* p302 = last_address;
PRINT_POINTER(srealloc(p277,60););
printStats();
void* p303 = last_address;
PRINT_POINTER(scalloc(192,62););
printStats();
void* p304 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p305 = last_address;
PRINT_POINTER(scalloc(107,154););
printStats();
void* p306 = last_address;
PRINT_POINTER(scalloc(201,167););
printStats();
void* p307 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p308 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
DEBUG_PRINT(sfree(p269););
printStats();
DEBUG_PRINT(sfree(p239););
printStats();
DEBUG_PRINT(sfree(p57););
printStats();
PRINT_POINTER(smalloc(21););
printStats();
void* p309 = last_address;
PRINT_POINTER(srealloc(p131,131););
printStats();
void* p310 = last_address;
DEBUG_PRINT(sfree(p267););
printStats();
PRINT_POINTER(srealloc(p273,169););
printStats();
void* p311 = last_address;
DEBUG_PRINT(sfree(p271););
printStats();
PRINT_POINTER(srealloc(p166,198););
printStats();
void* p312 = last_address;
DEBUG_PRINT(sfree(p163););
printStats();
DEBUG_PRINT(sfree(p164););
printStats();
PRINT_POINTER(smalloc(133););
printStats();
void* p313 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p314 = last_address;
PRINT_POINTER(srealloc(p304,113););
printStats();
void* p315 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p316 = last_address;
PRINT_POINTER(scalloc(93,109););
printStats();
void* p317 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p318 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p319 = last_address;
PRINT_POINTER(srealloc(p282,1););
printStats();
void* p320 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p321 = last_address;
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(srealloc(p132,184););
printStats();
void* p322 = last_address;
PRINT_POINTER(srealloc(p81,167););
printStats();
void* p323 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
PRINT_POINTER(scalloc(222,73););
printStats();
void* p324 = last_address;
PRINT_POINTER(srealloc(p249,238););
printStats();
void* p325 = last_address;
DEBUG_PRINT(sfree(p310););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p326 = last_address;
DEBUG_PRINT(sfree(p299););
printStats();
PRINT_POINTER(smalloc(78););
printStats();
void* p327 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p328 = last_address;
DEBUG_PRINT(sfree(p248););
printStats();
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(smalloc(48););
printStats();
void* p329 = last_address;
DEBUG_PRINT(sfree(p285););
printStats();
PRINT_POINTER(scalloc(151,140););
printStats();
void* p330 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p331 = last_address;
PRINT_POINTER(scalloc(103,88););
printStats();
void* p332 = last_address;
DEBUG_PRINT(sfree(p254););
printStats();
DEBUG_PRINT(sfree(p264););
printStats();
PRINT_POINTER(srealloc(p161,187););
printStats();
void* p333 = last_address;
PRINT_POINTER(scalloc(189,201););
printStats();
void* p334 = last_address;
DEBUG_PRINT(sfree(p66););
printStats();
PRINT_POINTER(srealloc(p332,180););
printStats();
void* p335 = last_address;
PRINT_POINTER(scalloc(220,203););
printStats();
void* p336 = last_address;
PRINT_POINTER(srealloc(p276,194););
printStats();
void* p337 = last_address;
DEBUG_PRINT(sfree(p305););
printStats();
PRINT_POINTER(scalloc(23,155););
printStats();
void* p338 = last_address;
PRINT_POINTER(scalloc(218,97););
printStats();
void* p339 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
DEBUG_PRINT(sfree(p290););
printStats();
PRINT_POINTER(srealloc(p319,179););
printStats();
void* p340 = last_address;
PRINT_POINTER(scalloc(174,51););
printStats();
void* p341 = last_address;
PRINT_POINTER(srealloc(p300,126););
printStats();
void* p342 = last_address;
PRINT_POINTER(scalloc(106,101););
printStats();
void* p343 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(scalloc(221,74););
printStats();
void* p344 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p345 = last_address;
PRINT_POINTER(srealloc(p325,144););
printStats();
void* p346 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p347 = last_address;
PRINT_POINTER(srealloc(p255,23););
printStats();
void* p348 = last_address;
DEBUG_PRINT(sfree(p331););
printStats();
DEBUG_PRINT(sfree(p328););
printStats();
DEBUG_PRINT(sfree(p344););
printStats();
PRINT_POINTER(scalloc(33,30););
printStats();
void* p349 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p350 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p351 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p352 = last_address;
PRINT_POINTER(scalloc(111,84););
printStats();
void* p353 = last_address;
DEBUG_PRINT(sfree(p227););
printStats();
PRINT_POINTER(srealloc(p350,246););
printStats();
void* p354 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p355 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
DEBUG_PRINT(sfree(p348););
printStats();
PRINT_POINTER(srealloc(p355,204););
printStats();
void* p356 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p357 = last_address;
DEBUG_PRINT(sfree(p335););
printStats();
PRINT_POINTER(srealloc(p268,143););
printStats();
void* p358 = last_address;
PRINT_POINTER(scalloc(105,218););
printStats();
void* p359 = last_address;
PRINT_POINTER(scalloc(220,113););
printStats();
void* p360 = last_address;
DEBUG_PRINT(sfree(p278););
printStats();
PRINT_POINTER(srealloc(p40,76););
printStats();
void* p361 = last_address;
PRINT_POINTER(srealloc(p245,180););
printStats();
void* p362 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p363 = last_address;
DEBUG_PRINT(sfree(p347););
printStats();
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(smalloc(200););
printStats();
void* p364 = last_address;
PRINT_POINTER(srealloc(p191,104););
printStats();
void* p365 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p366 = last_address;
DEBUG_PRINT(sfree(p283););
printStats();
PRINT_POINTER(smalloc(249););
printStats();
void* p367 = last_address;
DEBUG_PRINT(sfree(p362););
printStats();
DEBUG_PRINT(sfree(p263););
printStats();
DEBUG_PRINT(sfree(p322););
printStats();
PRINT_POINTER(srealloc(p151,160););
printStats();
void* p368 = last_address;
DEBUG_PRINT(sfree(p236););
printStats();
PRINT_POINTER(srealloc(p339,160););
printStats();
void* p369 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p370 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p371 = last_address;
PRINT_POINTER(srealloc(p111,239););
printStats();
void* p372 = last_address;
PRINT_POINTER(srealloc(p257,137););
printStats();
void* p373 = last_address;
PRINT_POINTER(srealloc(p356,171););
printStats();
void* p374 = last_address;
DEBUG_PRINT(sfree(p359););
printStats();
PRINT_POINTER(scalloc(3,2););
printStats();
void* p375 = last_address;
PRINT_POINTER(scalloc(1,134););
printStats();
void* p376 = last_address;
PRINT_POINTER(srealloc(p309,71););
printStats();
void* p377 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p378 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p379 = last_address;
PRINT_POINTER(scalloc(76,174););
printStats();
void* p380 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p381 = last_address;
PRINT_POINTER(srealloc(p274,97););
printStats();
void* p382 = last_address;
DEBUG_PRINT(sfree(p361););
printStats();
DEBUG_PRINT(sfree(p208););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p383 = last_address;
PRINT_POINTER(srealloc(p211,199););
printStats();
void* p384 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p385 = last_address;
DEBUG_PRINT(sfree(p221););
printStats();
PRINT_POINTER(smalloc(195););
printStats();
void* p386 = last_address;
PRINT_POINTER(scalloc(68,200););
printStats();
void* p387 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p388 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p389 = last_address;
DEBUG_PRINT(sfree(p375););
printStats();
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(scalloc(20,213););
printStats();
void* p390 = last_address;
PRINT_POINTER(scalloc(31,34););
printStats();
void* p391 = last_address;
PRINT_POINTER(scalloc(122,125););
printStats();
void* p392 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p393 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p394 = last_address;
PRINT_POINTER(scalloc(43,99););
printStats();
void* p395 = last_address;
PRINT_POINTER(scalloc(56,172););
printStats();
void* p396 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p397 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p398 = last_address;
PRINT_POINTER(scalloc(234,235););
printStats();
void* p399 = last_address;
PRINT_POINTER(scalloc(35,96););
printStats();
void* p400 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p401 = last_address;
DEBUG_PRINT(sfree(p242););
printStats();
DEBUG_PRINT(sfree(p377););
printStats();
PRINT_POINTER(scalloc(89,92););
printStats();
void* p402 = last_address;
DEBUG_PRINT(sfree(p390););
printStats();
PRINT_POINTER(scalloc(184,177););
printStats();
void* p403 = last_address;
PRINT_POINTER(srealloc(p202,39););
printStats();
void* p404 = last_address;
DEBUG_PRINT(sfree(p364););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p405 = last_address;
PRINT_POINTER(scalloc(157,49););
printStats();
void* p406 = last_address;
PRINT_POINTER(srealloc(p338,70););
printStats();
void* p407 = last_address;
PRINT_POINTER(srealloc(p306,122););
printStats();
void* p408 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p409 = last_address;
PRINT_POINTER(scalloc(25,96););
printStats();
void* p410 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p411 = last_address;
DEBUG_PRINT(sfree(p177););
printStats();
PRINT_POINTER(srealloc(p363,9););
printStats();
void* p412 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p413 = last_address;
DEBUG_PRINT(sfree(p389););
printStats();
DEBUG_PRINT(sfree(p284););
printStats();
DEBUG_PRINT(sfree(p234););
printStats();
DEBUG_PRINT(sfree(p178););
printStats();
PRINT_POINTER(srealloc(p120,196););
printStats();
void* p414 = last_address;
DEBUG_PRINT(sfree(p289););
printStats();
DEBUG_PRINT(sfree(p337););
printStats();
PRINT_POINTER(smalloc(136););
printStats();
void* p415 = last_address;
DEBUG_PRINT(sfree(p400););
printStats();
DEBUG_PRINT(sfree(p371););
printStats();
PRINT_POINTER(smalloc(27););
printStats();
void* p416 = last_address;
PRINT_POINTER(srealloc(p280,106););
printStats();
void* p417 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p418 = last_address;
PRINT_POINTER(srealloc(p228,100););
printStats();
void* p419 = last_address;
PRINT_POINTER(srealloc(p237,75););
printStats();
void* p420 = last_address;
PRINT_POINTER(scalloc(215,198););
printStats();
void* p421 = last_address;
DEBUG_PRINT(sfree(p366););
printStats();
PRINT_POINTER(scalloc(177,17););
printStats();
void* p422 = last_address;
DEBUG_PRINT(sfree(p256););
printStats();
PRINT_POINTER(scalloc(148,207););
printStats();
void* p423 = last_address;
PRINT_POINTER(scalloc(73,214););
printStats();
void* p424 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p425 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p426 = last_address;
PRINT_POINTER(srealloc(p346,181););
printStats();
void* p427 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p428 = last_address;
PRINT_POINTER(scalloc(51,120););
printStats();
void* p429 = last_address;
PRINT_POINTER(scalloc(132,163););
printStats();
void* p430 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p431 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p432 = last_address;
PRINT_POINTER(srealloc(p324,151););
printStats();
void* p433 = last_address;
PRINT_POINTER(scalloc(158,42););
printStats();
void* p434 = last_address;
PRINT_POINTER(srealloc(p261,216););
printStats();
void* p435 = last_address;
PRINT_POINTER(scalloc(182,148););
printStats();
void* p436 = last_address;
PRINT_POINTER(srealloc(p88,217););
printStats();
void* p437 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p438 = last_address;
PRINT_POINTER(scalloc(242,171););
printStats();
void* p439 = last_address;
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(srealloc(p427,40););
printStats();
void* p440 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p441 = last_address;
PRINT_POINTER(srealloc(p333,148););
printStats();
void* p442 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p443 = last_address;
DEBUG_PRINT(sfree(p103););
printStats();
PRINT_POINTER(srealloc(p318,99););
printStats();
void* p444 = last_address;
PRINT_POINTER(scalloc(129,17););
printStats();
void* p445 = last_address;
DEBUG_PRINT(sfree(p298););
printStats();
DEBUG_PRINT(sfree(p425););
printStats();
PRINT_POINTER(scalloc(223,143););
printStats();
void* p446 = last_address;
PRINT_POINTER(scalloc(128,87););
printStats();
void* p447 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p448 = last_address;
PRINT_POINTER(srealloc(p315,123););
printStats();
void* p449 = last_address;
PRINT_POINTER(srealloc(p426,172););
printStats();
void* p450 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p451 = last_address;
DEBUG_PRINT(sfree(p444););
printStats();
DEBUG_PRINT(sfree(p291););
printStats();
PRINT_POINTER(smalloc(181););
printStats();
void* p452 = last_address;
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(scalloc(117,195););
printStats();
void* p453 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p454 = last_address;
DEBUG_PRINT(sfree(p406););
printStats();
PRINT_POINTER(srealloc(p293,182););
printStats();
void* p455 = last_address;
PRINT_POINTER(srealloc(p292,118););
printStats();
void* p456 = last_address;
DEBUG_PRINT(sfree(p244););
printStats();
PRINT_POINTER(smalloc(144););
printStats();
void* p457 = last_address;
PRINT_POINTER(scalloc(96,101););
printStats();
void* p458 = last_address;
PRINT_POINTER(srealloc(p113,136););
printStats();
void* p459 = last_address;
PRINT_POINTER(srealloc(p327,233););
printStats();
void* p460 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p461 = last_address;
PRINT_POINTER(srealloc(p391,164););
printStats();
void* p462 = last_address;
PRINT_POINTER(srealloc(p179,240););
printStats();
void* p463 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p464 = last_address;
PRINT_POINTER(srealloc(p442,228););
printStats();
void* p465 = last_address;
PRINT_POINTER(srealloc(p407,236););
printStats();
void* p466 = last_address;
PRINT_POINTER(scalloc(30,16););
printStats();
void* p467 = last_address;
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(smalloc(195););
printStats();
void* p468 = last_address;
PRINT_POINTER(srealloc(p415,231););
printStats();
void* p469 = last_address;
PRINT_POINTER(scalloc(102,23););
printStats();
void* p470 = last_address;
PRINT_POINTER(scalloc(230,19););
printStats();
void* p471 = last_address;
DEBUG_PRINT(sfree(p465););
printStats();
DEBUG_PRINT(sfree(p416););
printStats();
PRINT_POINTER(smalloc(172););
printStats();
void* p472 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p473 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p474 = last_address;
PRINT_POINTER(srealloc(p231,132););
printStats();
void* p475 = last_address;
PRINT_POINTER(srealloc(p345,166););
printStats();
void* p476 = last_address;
PRINT_POINTER(srealloc(p397,186););
printStats();
void* p477 = last_address;
PRINT_POINTER(scalloc(159,129););
printStats();
void* p478 = last_address;
DEBUG_PRINT(sfree(p471););
printStats();
PRINT_POINTER(smalloc(208););
printStats();
void* p479 = last_address;
DEBUG_PRINT(sfree(p432););
printStats();
PRINT_POINTER(smalloc(166););
printStats();
void* p480 = last_address;
DEBUG_PRINT(sfree(p420););
printStats();
PRINT_POINTER(smalloc(122););
printStats();
void* p481 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p482 = last_address;
DEBUG_PRINT(sfree(p477););
printStats();
DEBUG_PRINT(sfree(p403););
printStats();
PRINT_POINTER(smalloc(2););
printStats();
void* p483 = last_address;
PRINT_POINTER(srealloc(p402,120););
printStats();
void* p484 = last_address;
PRINT_POINTER(srealloc(p260,244););
printStats();
void* p485 = last_address;
PRINT_POINTER(srealloc(p423,165););
printStats();
void* p486 = last_address;
PRINT_POINTER(srealloc(p417,124););
printStats();
void* p487 = last_address;
PRINT_POINTER(scalloc(67,32););
printStats();
void* p488 = last_address;
DEBUG_PRINT(sfree(p373););
printStats();
PRINT_POINTER(smalloc(198););
printStats();
void* p489 = last_address;
PRINT_POINTER(scalloc(207,131););
printStats();
void* p490 = last_address;
PRINT_POINTER(srealloc(p112,2););
printStats();
void* p491 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p492 = last_address;
PRINT_POINTER(scalloc(177,195););
printStats();
void* p493 = last_address;
PRINT_POINTER(srealloc(p253,94););
printStats();
void* p494 = last_address;
PRINT_POINTER(srealloc(p469,59););
printStats();
void* p495 = last_address;
PRINT_POINTER(scalloc(146,167););
printStats();
void* p496 = last_address;
DEBUG_PRINT(sfree(p281););
printStats();
PRINT_POINTER(srealloc(p79,86););
printStats();
void* p497 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p498 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p499 = last_address;
DEBUG_PRINT(sfree(p262););
printStats();
PRINT_POINTER(srealloc(p453,199););
printStats();
void* p500 = last_address;
PRINT_POINTER(srealloc(p294,33););
printStats();
void* p501 = last_address;
DEBUG_PRINT(sfree(p385););
printStats();
PRINT_POINTER(srealloc(p247,84););
printStats();
void* p502 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p503 = last_address;
DEBUG_PRINT(sfree(p483););
printStats();
PRINT_POINTER(scalloc(30,203););
printStats();
void* p504 = last_address;
PRINT_POINTER(scalloc(223,86););
printStats();
void* p505 = last_address;
DEBUG_PRINT(sfree(p405););
printStats();
DEBUG_PRINT(sfree(p287););
printStats();
PRINT_POINTER(scalloc(129,75););
printStats();
void* p506 = last_address;
DEBUG_PRINT(sfree(p372););
printStats();
DEBUG_PRINT(sfree(p478););
printStats();
PRINT_POINTER(srealloc(p422,67););
printStats();
void* p507 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
PRINT_POINTER(srealloc(p387,180););
printStats();
void* p508 = last_address;
PRINT_POINTER(scalloc(1,235););
printStats();
void* p509 = last_address;
PRINT_POINTER(srealloc(p430,12););
printStats();
void* p510 = last_address;
PRINT_POINTER(srealloc(p252,117););
printStats();
void* p511 = last_address;
PRINT_POINTER(srealloc(p409,58););
printStats();
void* p512 = last_address;
PRINT_POINTER(scalloc(231,198););
printStats();
void* p513 = last_address;
PRINT_POINTER(srealloc(p316,229););
printStats();
void* p514 = last_address;
PRINT_POINTER(srealloc(p500,154););
printStats();
void* p515 = last_address;
PRINT_POINTER(srealloc(p401,64););
printStats();
void* p516 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p517 = last_address;
PRINT_POINTER(srealloc(p379,151););
printStats();
void* p518 = last_address;
DEBUG_PRINT(sfree(p275););
printStats();
PRINT_POINTER(scalloc(92,172););
printStats();
void* p519 = last_address;
PRINT_POINTER(srealloc(p367,231););
printStats();
void* p520 = last_address;
DEBUG_PRINT(sfree(p352););
printStats();
PRINT_POINTER(smalloc(168););
printStats();
void* p521 = last_address;
PRINT_POINTER(scalloc(208,111););
printStats();
void* p522 = last_address;
DEBUG_PRINT(sfree(p479););
printStats();
PRINT_POINTER(scalloc(167,194););
printStats();
void* p523 = last_address;
PRINT_POINTER(srealloc(p460,107););
printStats();
void* p524 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p525 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p526 = last_address;
PRINT_POINTER(srealloc(p464,101););
printStats();
void* p527 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p528 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p529 = last_address;
PRINT_POINTER(scalloc(100,12););
printStats();
void* p530 = last_address;
DEBUG_PRINT(sfree(p475););
printStats();
PRINT_POINTER(scalloc(113,179););
printStats();
void* p531 = last_address;
PRINT_POINTER(scalloc(154,107););
printStats();
void* p532 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p533 = last_address;
DEBUG_PRINT(sfree(p143););
printStats();
PRINT_POINTER(scalloc(95,17););
printStats();
void* p534 = last_address;
DEBUG_PRINT(sfree(p455););
printStats();
DEBUG_PRINT(sfree(p360););
printStats();
PRINT_POINTER(srealloc(p374,209););
printStats();
void* p535 = last_address;
PRINT_POINTER(srealloc(p527,201););
printStats();
void* p536 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p537 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p538 = last_address;
PRINT_POINTER(scalloc(217,84););
printStats();
void* p539 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p540 = last_address;
DEBUG_PRINT(sfree(p491););
printStats();
PRINT_POINTER(scalloc(81,227););
printStats();
void* p541 = last_address;
PRINT_POINTER(scalloc(203,173););
printStats();
void* p542 = last_address;
PRINT_POINTER(scalloc(219,211););
printStats();
void* p543 = last_address;
PRINT_POINTER(srealloc(p369,6););
printStats();
void* p544 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p545 = last_address;
PRINT_POINTER(srealloc(p448,47););
printStats();
void* p546 = last_address;
PRINT_POINTER(srealloc(p495,6););
printStats();
void* p547 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p548 = last_address;
PRINT_POINTER(srealloc(p434,173););
printStats();
void* p549 = last_address;
PRINT_POINTER(scalloc(208,192););
printStats();
void* p550 = last_address;
PRINT_POINTER(scalloc(116,246););
printStats();
void* p551 = last_address;
PRINT_POINTER(srealloc(p439,85););
printStats();
void* p552 = last_address;
PRINT_POINTER(srealloc(p357,18););
printStats();
void* p553 = last_address;
DEBUG_PRINT(sfree(p535););
printStats();
PRINT_POINTER(srealloc(p454,175););
printStats();
void* p554 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p555 = last_address;
DEBUG_PRINT(sfree(p456););
printStats();
PRINT_POINTER(smalloc(234););
printStats();
void* p556 = last_address;
DEBUG_PRINT(sfree(p384););
printStats();
PRINT_POINTER(smalloc(87););
printStats();
void* p557 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p558 = last_address;
PRINT_POINTER(srealloc(p553,170););
printStats();
void* p559 = last_address;
PRINT_POINTER(scalloc(179,107););
printStats();
void* p560 = last_address;
DEBUG_PRINT(sfree(p457););
printStats();
PRINT_POINTER(srealloc(p410,129););
printStats();
void* p561 = last_address;
DEBUG_PRINT(sfree(p461););
printStats();
PRINT_POINTER(srealloc(p296,79););
printStats();
void* p562 = last_address;
PRINT_POINTER(scalloc(75,198););
printStats();
void* p563 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p564 = last_address;
PRINT_POINTER(scalloc(68,86););
printStats();
void* p565 = last_address;
PRINT_POINTER(srealloc(p302,38););
printStats();
void* p566 = last_address;
DEBUG_PRINT(sfree(p547););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p567 = last_address;
PRINT_POINTER(srealloc(p435,155););
printStats();
void* p568 = last_address;
PRINT_POINTER(srealloc(p472,150););
printStats();
void* p569 = last_address;
PRINT_POINTER(srealloc(p311,116););
printStats();
void* p570 = last_address;
DEBUG_PRINT(sfree(p130););
printStats();
PRINT_POINTER(smalloc(180););
printStats();
void* p571 = last_address;
DEBUG_PRINT(sfree(p320););
printStats();
PRINT_POINTER(smalloc(142););
printStats();
void* p572 = last_address;
DEBUG_PRINT(sfree(p481););
printStats();
DEBUG_PRINT(sfree(p542););
printStats();
PRINT_POINTER(srealloc(p159,96););
printStats();
void* p573 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p574 = last_address;
PRINT_POINTER(scalloc(225,141););
printStats();
void* p575 = last_address;
PRINT_POINTER(scalloc(239,156););
printStats();
void* p576 = last_address;
PRINT_POINTER(scalloc(15,220););
printStats();
void* p577 = last_address;
PRINT_POINTER(scalloc(228,231););
printStats();
void* p578 = last_address;
PRINT_POINTER(srealloc(p520,207););
printStats();
void* p579 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p580 = last_address;
PRINT_POINTER(scalloc(116,59););
printStats();
void* p581 = last_address;
PRINT_POINTER(srealloc(p489,88););
printStats();
void* p582 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p583 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p584 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p585 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p586 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p587 = last_address;
DEBUG_PRINT(sfree(p382););
printStats();
PRINT_POINTER(srealloc(p504,47););
printStats();
void* p588 = last_address;
DEBUG_PRINT(sfree(p437););
printStats();
PRINT_POINTER(srealloc(p516,224););
printStats();
void* p589 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(srealloc(p341,209););
printStats();
void* p590 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p591 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p592 = last_address;
DEBUG_PRINT(sfree(p582););
printStats();
PRINT_POINTER(smalloc(192););
printStats();
void* p593 = last_address;
PRINT_POINTER(srealloc(p447,173););
printStats();
void* p594 = last_address;
DEBUG_PRINT(sfree(p393););
printStats();
PRINT_POINTER(scalloc(147,200););
printStats();
void* p595 = last_address;
DEBUG_PRINT(sfree(p526););
printStats();
PRINT_POINTER(scalloc(186,111););
printStats();
void* p596 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p597 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p598 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p599 = last_address;
DEBUG_PRINT(sfree(p529););
printStats();
PRINT_POINTER(scalloc(15,234););
printStats();
void* p600 = last_address;
DEBUG_PRINT(sfree(p490););
printStats();
PRINT_POINTER(smalloc(190););
printStats();
void* p601 = last_address;
DEBUG_PRINT(sfree(p540););
printStats();
PRINT_POINTER(scalloc(150,176););
printStats();
void* p602 = last_address;
PRINT_POINTER(scalloc(47,48););
printStats();
void* p603 = last_address;
PRINT_POINTER(scalloc(239,29););
printStats();
void* p604 = last_address;
PRINT_POINTER(scalloc(17,23););
printStats();
void* p605 = last_address;
DEBUG_PRINT(sfree(p458););
printStats();
PRINT_POINTER(scalloc(112,97););
printStats();
void* p606 = last_address;
DEBUG_PRINT(sfree(p340););
printStats();
PRINT_POINTER(smalloc(51););
printStats();
void* p607 = last_address;
DEBUG_PRINT(sfree(p449););
printStats();
PRINT_POINTER(scalloc(25,12););
printStats();
void* p608 = last_address;
PRINT_POINTER(scalloc(188,236););
printStats();
void* p609 = last_address;
DEBUG_PRINT(sfree(p354););
printStats();
DEBUG_PRINT(sfree(p599););
printStats();
PRINT_POINTER(smalloc(88););
printStats();
void* p610 = last_address;
DEBUG_PRINT(sfree(p187););
printStats();
DEBUG_PRINT(sfree(p590););
printStats();
PRINT_POINTER(scalloc(160,135););
printStats();
void* p611 = last_address;
DEBUG_PRINT(sfree(p370););
printStats();
DEBUG_PRINT(sfree(p514););
printStats();
PRINT_POINTER(srealloc(p534,168););
printStats();
void* p612 = last_address;
PRINT_POINTER(scalloc(31,47););
printStats();
void* p613 = last_address;
PRINT_POINTER(srealloc(p564,126););
printStats();
void* p614 = last_address;
PRINT_POINTER(scalloc(52,113););
printStats();
void* p615 = last_address;
PRINT_POINTER(scalloc(34,211););
printStats();
void* p616 = last_address;
PRINT_POINTER(srealloc(p133,89););
printStats();
void* p617 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p618 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p619 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p620 = last_address;
PRINT_POINTER(scalloc(109,9););
printStats();
void* p621 = last_address;
DEBUG_PRINT(sfree(p486););
printStats();
PRINT_POINTER(srealloc(p597,44););
printStats();
void* p622 = last_address;
PRINT_POINTER(scalloc(131,124););
printStats();
void* p623 = last_address;
PRINT_POINTER(srealloc(p270,121););
printStats();
void* p624 = last_address;
PRINT_POINTER(srealloc(p165,62););
printStats();
void* p625 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p626 = last_address;
DEBUG_PRINT(sfree(p524););
printStats();
PRINT_POINTER(srealloc(p519,190););
printStats();
void* p627 = last_address;
PRINT_POINTER(scalloc(224,131););
printStats();
void* p628 = last_address;
PRINT_POINTER(srealloc(p265,144););
printStats();
void* p629 = last_address;
PRINT_POINTER(scalloc(201,147););
printStats();
void* p630 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p631 = last_address;
PRINT_POINTER(srealloc(p342,182););
printStats();
void* p632 = last_address;
PRINT_POINTER(scalloc(210,148););
printStats();
void* p633 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p634 = last_address;
DEBUG_PRINT(sfree(p554););
printStats();
PRINT_POINTER(smalloc(165););
printStats();
void* p635 = last_address;
PRINT_POINTER(srealloc(p573,30););
printStats();
void* p636 = last_address;
DEBUG_PRINT(sfree(p630););
printStats();
PRINT_POINTER(smalloc(45););
printStats();
void* p637 = last_address;
DEBUG_PRINT(sfree(p598););
printStats();
DEBUG_PRINT(sfree(p421););
printStats();
PRINT_POINTER(scalloc(137,34););
printStats();
void* p638 = last_address;
PRINT_POINTER(scalloc(26,212););
printStats();
void* p639 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p640 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p641 = last_address;
PRINT_POINTER(scalloc(237,216););
printStats();
void* p642 = last_address;
PRINT_POINTER(srealloc(p611,212););
printStats();
void* p643 = last_address;
PRINT_POINTER(scalloc(134,140););
printStats();
void* p644 = last_address;
PRINT_POINTER(srealloc(p321,85););
printStats();
void* p645 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p646 = last_address;
DEBUG_PRINT(sfree(p636););
printStats();
PRINT_POINTER(srealloc(p505,188););
printStats();
void* p647 = last_address;
PRINT_POINTER(scalloc(68,57););
printStats();
void* p648 = last_address;
DEBUG_PRINT(sfree(p620););
printStats();
PRINT_POINTER(scalloc(193,176););
printStats();
void* p649 = last_address;
PRINT_POINTER(scalloc(230,43););
printStats();
void* p650 = last_address;
DEBUG_PRINT(sfree(p640););
printStats();
PRINT_POINTER(smalloc(192););
printStats();
void* p651 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p652 = last_address;
PRINT_POINTER(scalloc(117,27););
printStats();
void* p653 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p654 = last_address;
PRINT_POINTER(scalloc(65,51););
printStats();
void* p655 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p656 = last_address;
PRINT_POINTER(scalloc(34,100););
printStats();
void* p657 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p658 = last_address;
PRINT_POINTER(srealloc(p644,174););
printStats();
void* p659 = last_address;
PRINT_POINTER(srealloc(p396,37););
printStats();
void* p660 = last_address;
DEBUG_PRINT(sfree(p365););
printStats();
PRINT_POINTER(smalloc(36););
printStats();
void* p661 = last_address;
DEBUG_PRINT(sfree(p563););
printStats();
PRINT_POINTER(scalloc(227,42););
printStats();
void* p662 = last_address;
PRINT_POINTER(scalloc(116,225););
printStats();
void* p663 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p664 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p665 = last_address;
PRINT_POINTER(srealloc(p537,224););
printStats();
void* p666 = last_address;
DEBUG_PRINT(sfree(p561););
printStats();
PRINT_POINTER(srealloc(p476,115););
printStats();
void* p667 = last_address;
PRINT_POINTER(srealloc(p647,191););
printStats();
void* p668 = last_address;
DEBUG_PRINT(sfree(p330););
printStats();
PRINT_POINTER(smalloc(86););
printStats();
void* p669 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p670 = last_address;
PRINT_POINTER(srealloc(p438,79););
printStats();
void* p671 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p672 = last_address;
DEBUG_PRINT(sfree(p612););
printStats();
DEBUG_PRINT(sfree(p452););
printStats();
DEBUG_PRINT(sfree(p601););
printStats();
DEBUG_PRINT(sfree(p424););
printStats();
PRINT_POINTER(scalloc(115,36););
printStats();
void* p673 = last_address;
PRINT_POINTER(scalloc(95,45););
printStats();
void* p674 = last_address;
PRINT_POINTER(srealloc(p428,139););
printStats();
void* p675 = last_address;
PRINT_POINTER(scalloc(200,155););
printStats();
void* p676 = last_address;
PRINT_POINTER(srealloc(p279,212););
printStats();
void* p677 = last_address;
PRINT_POINTER(scalloc(195,39););
printStats();
void* p678 = last_address;
DEBUG_PRINT(sfree(p473););
printStats();
PRINT_POINTER(smalloc(120););
printStats();
void* p679 = last_address;
PRINT_POINTER(scalloc(199,79););
printStats();
void* p680 = last_address;
PRINT_POINTER(srealloc(p574,34););
printStats();
void* p681 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p682 = last_address;
PRINT_POINTER(srealloc(p585,153););
printStats();
void* p683 = last_address;
PRINT_POINTER(scalloc(152,76););
printStats();
void* p684 = last_address;
DEBUG_PRINT(sfree(p645););
printStats();
PRINT_POINTER(srealloc(p383,109););
printStats();
void* p685 = last_address;
PRINT_POINTER(srealloc(p288,0););
printStats();
void* p686 = last_address;
PRINT_POINTER(srealloc(p513,118););
printStats();
void* p687 = last_address;
DEBUG_PRINT(sfree(p667););
printStats();
PRINT_POINTER(scalloc(128,205););
printStats();
void* p688 = last_address;
DEBUG_PRINT(sfree(p562););
printStats();
PRINT_POINTER(smalloc(204););
printStats();
void* p689 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p690 = last_address;
DEBUG_PRINT(sfree(p662););
printStats();
PRINT_POINTER(srealloc(p577,37););
printStats();
void* p691 = last_address;
PRINT_POINTER(scalloc(128,43););
printStats();
void* p692 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p693 = last_address;
PRINT_POINTER(scalloc(135,177););
printStats();
void* p694 = last_address;
DEBUG_PRINT(sfree(p559););
printStats();
DEBUG_PRINT(sfree(p664););
printStats();
PRINT_POINTER(scalloc(103,107););
printStats();
void* p695 = last_address;
PRINT_POINTER(scalloc(228,6););
printStats();
void* p696 = last_address;
PRINT_POINTER(srealloc(p431,171););
printStats();
void* p697 = last_address;
DEBUG_PRINT(sfree(p680););
printStats();
DEBUG_PRINT(sfree(p301););
printStats();
PRINT_POINTER(smalloc(197););
printStats();
void* p698 = last_address;
PRINT_POINTER(scalloc(103,213););
printStats();
void* p699 = last_address;
DEBUG_PRINT(sfree(p581););
printStats();
DEBUG_PRINT(sfree(p555););
printStats();
DEBUG_PRINT(sfree(p550););
printStats();
PRINT_POINTER(scalloc(99,56););
printStats();
void* p700 = last_address;
PRINT_POINTER(scalloc(92,173););
printStats();
void* p701 = last_address;
PRINT_POINTER(srealloc(p482,242););
printStats();
void* p702 = last_address;
PRINT_POINTER(srealloc(p671,100););
printStats();
void* p703 = last_address;
PRINT_POINTER(srealloc(p295,16););
printStats();
void* p704 = last_address;
DEBUG_PRINT(sfree(p669););
printStats();
PRINT_POINTER(scalloc(116,117););
printStats();
void* p705 = last_address;
PRINT_POINTER(srealloc(p488,232););
printStats();
void* p706 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p707 = last_address;
PRINT_POINTER(scalloc(73,24););
printStats();
void* p708 = last_address;
DEBUG_PRINT(sfree(p440););
printStats();
PRINT_POINTER(smalloc(214););
printStats();
void* p709 = last_address;
PRINT_POINTER(srealloc(p696,234););
printStats();
void* p710 = last_address;
PRINT_POINTER(srealloc(p657,83););
printStats();
void* p711 = last_address;
DEBUG_PRINT(sfree(p709););
printStats();
PRINT_POINTER(smalloc(156););
printStats();
void* p712 = last_address;
DEBUG_PRINT(sfree(p531););
printStats();
PRINT_POINTER(smalloc(97););
printStats();
void* p713 = last_address;
PRINT_POINTER(srealloc(p508,196););
printStats();
void* p714 = last_address;
DEBUG_PRINT(sfree(p635););
printStats();
PRINT_POINTER(scalloc(9,84););
printStats();
void* p715 = last_address;
DEBUG_PRINT(sfree(p215););
printStats();
PRINT_POINTER(scalloc(17,183););
printStats();
void* p716 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p717 = last_address;
PRINT_POINTER(scalloc(130,187););
printStats();
void* p718 = last_address;
PRINT_POINTER(srealloc(p162,199););
printStats();
void* p719 = last_address;
PRINT_POINTER(srealloc(p378,137););
printStats();
void* p720 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p721 = last_address;
PRINT_POINTER(srealloc(p567,61););
printStats();
void* p722 = last_address;
DEBUG_PRINT(sfree(p541););
printStats();
PRINT_POINTER(srealloc(p704,69););
printStats();
void* p723 = last_address;
PRINT_POINTER(srealloc(p710,78););
printStats();
void* p724 = last_address;
DEBUG_PRINT(sfree(p578););
printStats();
PRINT_POINTER(srealloc(p678,66););
printStats();
void* p725 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p726 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p727 = last_address;
PRINT_POINTER(srealloc(p656,147););
printStats();
void* p728 = last_address;
DEBUG_PRINT(sfree(p349););
printStats();
PRINT_POINTER(smalloc(190););
printStats();
void* p729 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p730 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p731 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p732 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p733 = last_address;
PRINT_POINTER(srealloc(p336,232););
printStats();
void* p734 = last_address;
PRINT_POINTER(srealloc(p722,36););
printStats();
void* p735 = last_address;
PRINT_POINTER(scalloc(129,114););
printStats();
void* p736 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p737 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p738 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p739 = last_address;
PRINT_POINTER(srealloc(p463,126););
printStats();
void* p740 = last_address;
PRINT_POINTER(scalloc(229,189););
printStats();
void* p741 = last_address;
DEBUG_PRINT(sfree(p586););
printStats();
DEBUG_PRINT(sfree(p492););
printStats();
DEBUG_PRINT(sfree(p658););
printStats();
PRINT_POINTER(srealloc(p615,180););
printStats();
void* p742 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p743 = last_address;
PRINT_POINTER(scalloc(132,64););
printStats();
void* p744 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p745 = last_address;
PRINT_POINTER(scalloc(24,145););
printStats();
void* p746 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p747 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p748 = last_address;
PRINT_POINTER(scalloc(224,158););
printStats();
void* p749 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p750 = last_address;
PRINT_POINTER(scalloc(249,182););
printStats();
void* p751 = last_address;
PRINT_POINTER(srealloc(p503,58););
printStats();
void* p752 = last_address;
PRINT_POINTER(srealloc(p634,16););
printStats();
void* p753 = last_address;
PRINT_POINTER(scalloc(48,110););
printStats();
void* p754 = last_address;
DEBUG_PRINT(sfree(p741););
printStats();
PRINT_POINTER(srealloc(p312,149););
printStats();
void* p755 = last_address;
DEBUG_PRINT(sfree(p631););
printStats();
DEBUG_PRINT(sfree(p543););
printStats();
PRINT_POINTER(srealloc(p743,101););
printStats();
void* p756 = last_address;
PRINT_POINTER(srealloc(p694,131););
printStats();
void* p757 = last_address;
DEBUG_PRINT(sfree(p723););
printStats();
PRINT_POINTER(scalloc(90,29););
printStats();
void* p758 = last_address;
PRINT_POINTER(srealloc(p646,42););
printStats();
void* p759 = last_address;
PRINT_POINTER(srealloc(p536,133););
printStats();
void* p760 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p761 = last_address;
PRINT_POINTER(srealloc(p622,11););
printStats();
void* p762 = last_address;
DEBUG_PRINT(sfree(p736););
printStats();
PRINT_POINTER(smalloc(92););
printStats();
void* p763 = last_address;
PRINT_POINTER(scalloc(99,135););
printStats();
void* p764 = last_address;
DEBUG_PRINT(sfree(p751););
printStats();
PRINT_POINTER(smalloc(24););
printStats();
void* p765 = last_address;
PRINT_POINTER(srealloc(p735,11););
printStats();
void* p766 = last_address;
PRINT_POINTER(scalloc(190,127););
printStats();
void* p767 = last_address;
PRINT_POINTER(srealloc(p748,185););
printStats();
void* p768 = last_address;
PRINT_POINTER(srealloc(p169,18););
printStats();
void* p769 = last_address;
DEBUG_PRINT(sfree(p411););
printStats();
DEBUG_PRINT(sfree(p104););
printStats();
PRINT_POINTER(srealloc(p314,234););
printStats();
void* p770 = last_address;
PRINT_POINTER(scalloc(86,200););
printStats();
void* p771 = last_address;
PRINT_POINTER(scalloc(11,126););
printStats();
void* p772 = last_address;
PRINT_POINTER(srealloc(p571,60););
printStats();
void* p773 = last_address;
PRINT_POINTER(scalloc(81,135););
printStats();
void* p774 = last_address;
PRINT_POINTER(scalloc(19,144););
printStats();
void* p775 = last_address;
DEBUG_PRINT(sfree(p511););
printStats();
PRINT_POINTER(srealloc(p229,193););
printStats();
void* p776 = last_address;
PRINT_POINTER(srealloc(p651,163););
printStats();
void* p777 = last_address;
DEBUG_PRINT(sfree(p568););
printStats();
DEBUG_PRINT(sfree(p728););
printStats();
PRINT_POINTER(scalloc(57,127););
printStats();
void* p778 = last_address;
PRINT_POINTER(scalloc(205,200););
printStats();
void* p779 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p780 = last_address;
DEBUG_PRINT(sfree(p754););
printStats();
PRINT_POINTER(scalloc(0,203););
printStats();
void* p781 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p782 = last_address;
PRINT_POINTER(scalloc(142,104););
printStats();
void* p783 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p784 = last_address;
DEBUG_PRINT(sfree(p466););
printStats();
PRINT_POINTER(smalloc(124););
printStats();
void* p785 = last_address;
PRINT_POINTER(scalloc(172,72););
printStats();
void* p786 = last_address;
PRINT_POINTER(scalloc(175,172););
printStats();
void* p787 = last_address;
DEBUG_PRINT(sfree(p353););
printStats();
PRINT_POINTER(smalloc(169););
printStats();
void* p788 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p789 = last_address;
PRINT_POINTER(srealloc(p780,126););
printStats();
void* p790 = last_address;
PRINT_POINTER(srealloc(p588,84););
printStats();
void* p791 = last_address;
DEBUG_PRINT(sfree(p286););
printStats();
DEBUG_PRINT(sfree(p693););
printStats();
PRINT_POINTER(smalloc(154););
printStats();
void* p792 = last_address;
PRINT_POINTER(scalloc(33,20););
printStats();
void* p793 = last_address;
PRINT_POINTER(scalloc(65,73););
printStats();
void* p794 = last_address;
DEBUG_PRINT(sfree(p470););
printStats();
PRINT_POINTER(smalloc(2););
printStats();
void* p795 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p796 = last_address;
PRINT_POINTER(srealloc(p663,9););
printStats();
void* p797 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p798 = last_address;
PRINT_POINTER(scalloc(211,34););
printStats();
void* p799 = last_address;
DEBUG_PRINT(sfree(p781););
printStats();
PRINT_POINTER(srealloc(p677,227););
printStats();
void* p800 = last_address;
PRINT_POINTER(scalloc(48,164););
printStats();
void* p801 = last_address;
PRINT_POINTER(scalloc(42,163););
printStats();
void* p802 = last_address;
PRINT_POINTER(srealloc(p623,167););
printStats();
void* p803 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p804 = last_address;
PRINT_POINTER(srealloc(p674,203););
printStats();
void* p805 = last_address;
DEBUG_PRINT(sfree(p762););
printStats();
PRINT_POINTER(smalloc(38););
printStats();
void* p806 = last_address;
PRINT_POINTER(srealloc(p777,94););
printStats();
void* p807 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p808 = last_address;
PRINT_POINTER(scalloc(191,32););
printStats();
void* p809 = last_address;
PRINT_POINTER(scalloc(208,19););
printStats();
void* p810 = last_address;
PRINT_POINTER(srealloc(p625,101););
printStats();
void* p811 = last_address;
PRINT_POINTER(scalloc(121,219););
printStats();
void* p812 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p813 = last_address;
DEBUG_PRINT(sfree(p769););
printStats();
PRINT_POINTER(scalloc(105,163););
printStats();
void* p814 = last_address;
DEBUG_PRINT(sfree(p665););
printStats();
PRINT_POINTER(scalloc(113,79););
printStats();
void* p815 = last_address;
PRINT_POINTER(srealloc(p813,73););
printStats();
void* p816 = last_address;
DEBUG_PRINT(sfree(p746););
printStats();
PRINT_POINTER(smalloc(178););
printStats();
void* p817 = last_address;
PRINT_POINTER(srealloc(p450,92););
printStats();
void* p818 = last_address;
PRINT_POINTER(scalloc(148,10););
printStats();
void* p819 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p820 = last_address;
PRINT_POINTER(scalloc(243,138););
printStats();
void* p821 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p822 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p823 = last_address;
DEBUG_PRINT(sfree(p715););
printStats();
PRINT_POINTER(smalloc(76););
printStats();
void* p824 = last_address;
PRINT_POINTER(scalloc(118,180););
printStats();
void* p825 = last_address;
PRINT_POINTER(scalloc(67,207););
printStats();
void* p826 = last_address;
PRINT_POINTER(scalloc(202,234););
printStats();
void* p827 = last_address;
DEBUG_PRINT(sfree(p761););
printStats();
DEBUG_PRINT(sfree(p730););
printStats();
PRINT_POINTER(scalloc(189,238););
printStats();
void* p828 = last_address;
PRINT_POINTER(srealloc(p740,203););
printStats();
void* p829 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p830 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p831 = last_address;
PRINT_POINTER(scalloc(216,249););
printStats();
void* p832 = last_address;
PRINT_POINTER(scalloc(79,54););
printStats();
void* p833 = last_address;
PRINT_POINTER(srealloc(p515,155););
printStats();
void* p834 = last_address;
PRINT_POINTER(srealloc(p637,159););
printStats();
void* p835 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p836 = last_address;
DEBUG_PRINT(sfree(p404););
printStats();
PRINT_POINTER(srealloc(p548,57););
printStats();
void* p837 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p838 = last_address;
PRINT_POINTER(srealloc(p467,212););
printStats();
void* p839 = last_address;
DEBUG_PRINT(sfree(p602););
printStats();
PRINT_POINTER(smalloc(53););
printStats();
void* p840 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p841 = last_address;
DEBUG_PRINT(sfree(p661););
printStats();
PRINT_POINTER(smalloc(216););
printStats();
void* p842 = last_address;
PRINT_POINTER(scalloc(129,67););
printStats();
void* p843 = last_address;
PRINT_POINTER(srealloc(p842,147););
printStats();
void* p844 = last_address;
PRINT_POINTER(scalloc(152,40););
printStats();
void* p845 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p846 = last_address;
DEBUG_PRINT(sfree(p681););
printStats();
PRINT_POINTER(smalloc(238););
printStats();
void* p847 = last_address;
PRINT_POINTER(srealloc(p557,237););
printStats();
void* p848 = last_address;
PRINT_POINTER(srealloc(p834,158););
printStats();
void* p849 = last_address;
PRINT_POINTER(srealloc(p757,37););
printStats();
void* p850 = last_address;
PRINT_POINTER(srealloc(p832,17););
printStats();
void* p851 = last_address;
PRINT_POINTER(scalloc(51,192););
printStats();
void* p852 = last_address;
PRINT_POINTER(srealloc(p843,113););
printStats();
void* p853 = last_address;
PRINT_POINTER(scalloc(84,63););
printStats();
void* p854 = last_address;
DEBUG_PRINT(sfree(p854););
printStats();
PRINT_POINTER(scalloc(159,225););
printStats();
void* p855 = last_address;
PRINT_POINTER(scalloc(114,248););
printStats();
void* p856 = last_address;
PRINT_POINTER(srealloc(p856,213););
printStats();
void* p857 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p858 = last_address;
PRINT_POINTER(scalloc(141,9););
printStats();
void* p859 = last_address;
DEBUG_PRINT(sfree(p522););
printStats();
PRINT_POINTER(smalloc(209););
printStats();
void* p860 = last_address;
DEBUG_PRINT(sfree(p433););
printStats();
DEBUG_PRINT(sfree(p326););
printStats();
PRINT_POINTER(srealloc(p837,100););
printStats();
void* p861 = last_address;
PRINT_POINTER(scalloc(122,67););
printStats();
void* p862 = last_address;
PRINT_POINTER(scalloc(36,201););
printStats();
void* p863 = last_address;
PRINT_POINTER(srealloc(p796,72););
printStats();
void* p864 = last_address;
PRINT_POINTER(srealloc(p845,12););
printStats();
void* p865 = last_address;
PRINT_POINTER(scalloc(43,178););
printStats();
void* p866 = last_address;
PRINT_POINTER(srealloc(p698,22););
printStats();
void* p867 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p868 = last_address;
DEBUG_PRINT(sfree(p510););
printStats();
PRINT_POINTER(srealloc(p308,56););
printStats();
void* p869 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p870 = last_address;
PRINT_POINTER(scalloc(177,2););
printStats();
void* p871 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p872 = last_address;
DEBUG_PRINT(sfree(p860););
printStats();
PRINT_POINTER(smalloc(125););
printStats();
void* p873 = last_address;
PRINT_POINTER(scalloc(171,176););
printStats();
void* p874 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p875 = last_address;
PRINT_POINTER(srealloc(p570,94););
printStats();
void* p876 = last_address;
DEBUG_PRINT(sfree(p501););
printStats();
DEBUG_PRINT(sfree(p760););
printStats();
PRINT_POINTER(smalloc(146););
printStats();
void* p877 = last_address;
PRINT_POINTER(scalloc(240,112););
printStats();
void* p878 = last_address;
DEBUG_PRINT(sfree(p731););
printStats();
PRINT_POINTER(smalloc(215););
printStats();
void* p879 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p880 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p881 = last_address;
PRINT_POINTER(scalloc(22,69););
printStats();
void* p882 = last_address;
PRINT_POINTER(scalloc(205,19););
printStats();
void* p883 = last_address;
PRINT_POINTER(scalloc(27,52););
printStats();
void* p884 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p885 = last_address;
PRINT_POINTER(scalloc(217,143););
printStats();
void* p886 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p887 = last_address;
PRINT_POINTER(scalloc(15,11););
printStats();
void* p888 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p889 = last_address;
PRINT_POINTER(scalloc(30,140););
printStats();
void* p890 = last_address;
PRINT_POINTER(scalloc(166,42););
printStats();
void* p891 = last_address;
PRINT_POINTER(scalloc(219,160););
printStats();
void* p892 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p893 = last_address;
PRINT_POINTER(srealloc(p859,76););
printStats();
void* p894 = last_address;
PRINT_POINTER(srealloc(p100,238););
printStats();
void* p895 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p896 = last_address;
PRINT_POINTER(srealloc(p725,220););
printStats();
void* p897 = last_address;
PRINT_POINTER(scalloc(147,145););
printStats();
void* p898 = last_address;
PRINT_POINTER(srealloc(p546,98););
printStats();
void* p899 = last_address;
PRINT_POINTER(scalloc(151,41););
printStats();
void* p900 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p901 = last_address;
PRINT_POINTER(scalloc(225,242););
printStats();
void* p902 = last_address;
PRINT_POINTER(srealloc(p494,38););
printStats();
void* p903 = last_address;
DEBUG_PRINT(sfree(p889););
printStats();
PRINT_POINTER(smalloc(141););
printStats();
void* p904 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p905 = last_address;
PRINT_POINTER(srealloc(p899,67););
printStats();
void* p906 = last_address;
PRINT_POINTER(srealloc(p881,74););
printStats();
void* p907 = last_address;
DEBUG_PRINT(sfree(p888););
printStats();
PRINT_POINTER(srealloc(p592,117););
printStats();
void* p908 = last_address;
PRINT_POINTER(srealloc(p900,173););
printStats();
void* p909 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p910 = last_address;
DEBUG_PRINT(sfree(p767););
printStats();
PRINT_POINTER(smalloc(238););
printStats();
void* p911 = last_address;
PRINT_POINTER(srealloc(p866,104););
printStats();
void* p912 = last_address;
PRINT_POINTER(scalloc(135,71););
printStats();
void* p913 = last_address;
DEBUG_PRINT(sfree(p195););
printStats();
PRINT_POINTER(smalloc(172););
printStats();
void* p914 = last_address;
PRINT_POINTER(scalloc(78,81););
printStats();
void* p915 = last_address;
PRINT_POINTER(scalloc(224,150););
printStats();
void* p916 = last_address;
DEBUG_PRINT(sfree(p804););
printStats();
PRINT_POINTER(scalloc(77,66););
printStats();
void* p917 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p918 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p919 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p920 = last_address;
PRINT_POINTER(scalloc(17,240););
printStats();
void* p921 = last_address;
DEBUG_PRINT(sfree(p774););
printStats();
PRINT_POINTER(srealloc(p462,170););
printStats();
void* p922 = last_address;
DEBUG_PRINT(sfree(p749););
printStats();
DEBUG_PRINT(sfree(p498););
printStats();
PRINT_POINTER(srealloc(p713,222););
printStats();
void* p923 = last_address;
DEBUG_PRINT(sfree(p868););
printStats();
DEBUG_PRINT(sfree(p507););
printStats();
PRINT_POINTER(scalloc(157,199););
printStats();
void* p924 = last_address;
PRINT_POINTER(scalloc(248,65););
printStats();
void* p925 = last_address;
PRINT_POINTER(scalloc(181,172););
printStats();
void* p926 = last_address;
PRINT_POINTER(scalloc(144,57););
printStats();
void* p927 = last_address;
DEBUG_PRINT(sfree(p610););
printStats();
PRINT_POINTER(srealloc(p642,234););
printStats();
void* p928 = last_address;
}
