#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(89););
printStats();
void* p0 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(smalloc(5););
printStats();
void* p1 = last_address;
PRINT_POINTER(srealloc(p1,147););
printStats();
void* p2 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p3 = last_address;
PRINT_POINTER(srealloc(p2,7););
printStats();
void* p4 = last_address;
PRINT_POINTER(scalloc(232,234););
printStats();
void* p5 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p6 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p7 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p8 = last_address;
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(srealloc(p4,244););
printStats();
void* p9 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(scalloc(130,78););
printStats();
void* p10 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(147,112););
printStats();
void* p12 = last_address;
PRINT_POINTER(srealloc(p12,241););
printStats();
void* p13 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p14 = last_address;
PRINT_POINTER(scalloc(222,155););
printStats();
void* p15 = last_address;
PRINT_POINTER(scalloc(154,7););
printStats();
void* p16 = last_address;
PRINT_POINTER(scalloc(134,8););
printStats();
void* p17 = last_address;
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(smalloc(108););
printStats();
void* p18 = last_address;
PRINT_POINTER(scalloc(249,39););
printStats();
void* p19 = last_address;
PRINT_POINTER(srealloc(p17,151););
printStats();
void* p20 = last_address;
PRINT_POINTER(scalloc(210,241););
printStats();
void* p21 = last_address;
PRINT_POINTER(srealloc(p11,0););
printStats();
void* p22 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
PRINT_POINTER(scalloc(121,139););
printStats();
void* p23 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p24 = last_address;
PRINT_POINTER(scalloc(128,150););
printStats();
void* p25 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
PRINT_POINTER(scalloc(146,236););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p13,62););
printStats();
void* p27 = last_address;
PRINT_POINTER(srealloc(p10,6););
printStats();
void* p28 = last_address;
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(srealloc(p16,215););
printStats();
void* p29 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p30 = last_address;
PRINT_POINTER(srealloc(p24,94););
printStats();
void* p31 = last_address;
PRINT_POINTER(scalloc(64,61););
printStats();
void* p32 = last_address;
DEBUG_PRINT(sfree(p32););
printStats();
DEBUG_PRINT(sfree(p3););
printStats();
PRINT_POINTER(scalloc(188,241););
printStats();
void* p33 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(smalloc(88););
printStats();
void* p34 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p35 = last_address;
PRINT_POINTER(srealloc(p27,178););
printStats();
void* p36 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
DEBUG_PRINT(sfree(p9););
printStats();
PRINT_POINTER(smalloc(186););
printStats();
void* p37 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p38 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
PRINT_POINTER(srealloc(p35,56););
printStats();
void* p39 = last_address;
PRINT_POINTER(srealloc(p33,17););
printStats();
void* p40 = last_address;
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(srealloc(p20,194););
printStats();
void* p41 = last_address;
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(scalloc(217,41););
printStats();
void* p42 = last_address;
PRINT_POINTER(srealloc(p19,126););
printStats();
void* p43 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(srealloc(p30,16););
printStats();
void* p44 = last_address;
PRINT_POINTER(scalloc(201,212););
printStats();
void* p45 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p46 = last_address;
DEBUG_PRINT(sfree(p44););
printStats();
PRINT_POINTER(smalloc(33););
printStats();
void* p47 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p48 = last_address;
PRINT_POINTER(srealloc(p38,71););
printStats();
void* p49 = last_address;
PRINT_POINTER(scalloc(165,17););
printStats();
void* p50 = last_address;
PRINT_POINTER(scalloc(234,8););
printStats();
void* p51 = last_address;
DEBUG_PRINT(sfree(p47););
printStats();
PRINT_POINTER(smalloc(233););
printStats();
void* p52 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p53 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p54 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p55 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
PRINT_POINTER(smalloc(159););
printStats();
void* p56 = last_address;
DEBUG_PRINT(sfree(p56););
printStats();
PRINT_POINTER(smalloc(103););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(249,27););
printStats();
void* p58 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p59 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(smalloc(113););
printStats();
void* p60 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p61 = last_address;
PRINT_POINTER(srealloc(p55,96););
printStats();
void* p62 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p63 = last_address;
PRINT_POINTER(srealloc(p62,1););
printStats();
void* p64 = last_address;
DEBUG_PRINT(sfree(p52););
printStats();
PRINT_POINTER(srealloc(p22,105););
printStats();
void* p65 = last_address;
PRINT_POINTER(scalloc(5,90););
printStats();
void* p66 = last_address;
DEBUG_PRINT(sfree(p49););
printStats();
PRINT_POINTER(srealloc(p53,164););
printStats();
void* p67 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p68 = last_address;
DEBUG_PRINT(sfree(p67););
printStats();
PRINT_POINTER(srealloc(p43,87););
printStats();
void* p69 = last_address;
PRINT_POINTER(scalloc(121,241););
printStats();
void* p70 = last_address;
PRINT_POINTER(srealloc(p26,211););
printStats();
void* p71 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p72 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(scalloc(73,58););
printStats();
void* p73 = last_address;
PRINT_POINTER(scalloc(134,102););
printStats();
void* p74 = last_address;
PRINT_POINTER(scalloc(1,174););
printStats();
void* p75 = last_address;
PRINT_POINTER(scalloc(140,157););
printStats();
void* p76 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
DEBUG_PRINT(sfree(p63););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p77 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(smalloc(234););
printStats();
void* p78 = last_address;
PRINT_POINTER(scalloc(140,188););
printStats();
void* p79 = last_address;
PRINT_POINTER(scalloc(155,26););
printStats();
void* p80 = last_address;
DEBUG_PRINT(sfree(p68););
printStats();
PRINT_POINTER(smalloc(46););
printStats();
void* p81 = last_address;
PRINT_POINTER(srealloc(p48,56););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p83 = last_address;
PRINT_POINTER(scalloc(161,132););
printStats();
void* p84 = last_address;
PRINT_POINTER(srealloc(p82,226););
printStats();
void* p85 = last_address;
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(srealloc(p76,57););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p71,160););
printStats();
void* p87 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
PRINT_POINTER(scalloc(103,79););
printStats();
void* p88 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
PRINT_POINTER(srealloc(p57,196););
printStats();
void* p89 = last_address;
PRINT_POINTER(scalloc(7,30););
printStats();
void* p90 = last_address;
PRINT_POINTER(scalloc(94,9););
printStats();
void* p91 = last_address;
PRINT_POINTER(scalloc(127,185););
printStats();
void* p92 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p93 = last_address;
PRINT_POINTER(srealloc(p58,233););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p95 = last_address;
PRINT_POINTER(scalloc(193,32););
printStats();
void* p96 = last_address;
PRINT_POINTER(srealloc(p72,113););
printStats();
void* p97 = last_address;
PRINT_POINTER(scalloc(234,93););
printStats();
void* p98 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p99 = last_address;
DEBUG_PRINT(sfree(p96););
printStats();
PRINT_POINTER(smalloc(153););
printStats();
void* p100 = last_address;
PRINT_POINTER(srealloc(p74,186););
printStats();
void* p101 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p102 = last_address;
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(scalloc(146,60););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p100,75););
printStats();
void* p104 = last_address;
PRINT_POINTER(srealloc(p34,199););
printStats();
void* p105 = last_address;
PRINT_POINTER(scalloc(49,71););
printStats();
void* p106 = last_address;
PRINT_POINTER(srealloc(p103,131););
printStats();
void* p107 = last_address;
PRINT_POINTER(srealloc(p80,210););
printStats();
void* p108 = last_address;
PRINT_POINTER(srealloc(p61,221););
printStats();
void* p109 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p92,133););
printStats();
void* p111 = last_address;
PRINT_POINTER(srealloc(p81,90););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p99,78););
printStats();
void* p113 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p114 = last_address;
PRINT_POINTER(scalloc(135,78););
printStats();
void* p115 = last_address;
PRINT_POINTER(srealloc(p93,31););
printStats();
void* p116 = last_address;
PRINT_POINTER(scalloc(82,84););
printStats();
void* p117 = last_address;
DEBUG_PRINT(sfree(p104););
printStats();
PRINT_POINTER(srealloc(p95,179););
printStats();
void* p118 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p119 = last_address;
PRINT_POINTER(scalloc(97,76););
printStats();
void* p120 = last_address;
PRINT_POINTER(srealloc(p113,42););
printStats();
void* p121 = last_address;
DEBUG_PRINT(sfree(p105););
printStats();
PRINT_POINTER(smalloc(94););
printStats();
void* p122 = last_address;
PRINT_POINTER(srealloc(p83,170););
printStats();
void* p123 = last_address;
PRINT_POINTER(scalloc(168,221););
printStats();
void* p124 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p125 = last_address;
PRINT_POINTER(srealloc(p125,99););
printStats();
void* p126 = last_address;
PRINT_POINTER(srealloc(p84,117););
printStats();
void* p127 = last_address;
DEBUG_PRINT(sfree(p106););
printStats();
DEBUG_PRINT(sfree(p120););
printStats();
DEBUG_PRINT(sfree(p127););
printStats();
DEBUG_PRINT(sfree(p122););
printStats();
PRINT_POINTER(scalloc(173,39););
printStats();
void* p128 = last_address;
PRINT_POINTER(scalloc(1,161););
printStats();
void* p129 = last_address;
DEBUG_PRINT(sfree(p65););
printStats();
PRINT_POINTER(srealloc(p111,137););
printStats();
void* p130 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p131 = last_address;
DEBUG_PRINT(sfree(p112););
printStats();
PRINT_POINTER(smalloc(57););
printStats();
void* p132 = last_address;
DEBUG_PRINT(sfree(p108););
printStats();
PRINT_POINTER(srealloc(p66,21););
printStats();
void* p133 = last_address;
PRINT_POINTER(scalloc(156,23););
printStats();
void* p134 = last_address;
DEBUG_PRINT(sfree(p117););
printStats();
PRINT_POINTER(scalloc(66,243););
printStats();
void* p135 = last_address;
PRINT_POINTER(srealloc(p64,98););
printStats();
void* p136 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(scalloc(219,98););
printStats();
void* p137 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p138 = last_address;
PRINT_POINTER(scalloc(180,43););
printStats();
void* p139 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p140 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p141 = last_address;
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(smalloc(97););
printStats();
void* p142 = last_address;
PRINT_POINTER(scalloc(181,49););
printStats();
void* p143 = last_address;
PRINT_POINTER(scalloc(132,54););
printStats();
void* p144 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p145 = last_address;
PRINT_POINTER(srealloc(p142,184););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p107););
printStats();
DEBUG_PRINT(sfree(p131););
printStats();
DEBUG_PRINT(sfree(p129););
printStats();
DEBUG_PRINT(sfree(p139););
printStats();
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(scalloc(208,204););
printStats();
void* p147 = last_address;
PRINT_POINTER(srealloc(p110,240););
printStats();
void* p148 = last_address;
DEBUG_PRINT(sfree(p132););
printStats();
PRINT_POINTER(scalloc(103,87););
printStats();
void* p149 = last_address;
PRINT_POINTER(srealloc(p137,236););
printStats();
void* p150 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p151 = last_address;
PRINT_POINTER(srealloc(p128,36););
printStats();
void* p152 = last_address;
PRINT_POINTER(srealloc(p109,153););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(133,189););
printStats();
void* p154 = last_address;
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(scalloc(30,62););
printStats();
void* p155 = last_address;
DEBUG_PRINT(sfree(p145););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p156 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p157 = last_address;
PRINT_POINTER(scalloc(216,20););
printStats();
void* p158 = last_address;
PRINT_POINTER(scalloc(88,79););
printStats();
void* p159 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p160 = last_address;
PRINT_POINTER(scalloc(97,162););
printStats();
void* p161 = last_address;
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(smalloc(22););
printStats();
void* p162 = last_address;
PRINT_POINTER(scalloc(179,50););
printStats();
void* p163 = last_address;
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(scalloc(70,197););
printStats();
void* p164 = last_address;
PRINT_POINTER(srealloc(p140,119););
printStats();
void* p165 = last_address;
PRINT_POINTER(srealloc(p73,118););
printStats();
void* p166 = last_address;
PRINT_POINTER(srealloc(p115,138););
printStats();
void* p167 = last_address;
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(scalloc(175,130););
printStats();
void* p168 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
PRINT_POINTER(smalloc(96););
printStats();
void* p169 = last_address;
DEBUG_PRINT(sfree(p87););
printStats();
PRINT_POINTER(scalloc(29,133););
printStats();
void* p170 = last_address;
PRINT_POINTER(srealloc(p45,40););
printStats();
void* p171 = last_address;
PRINT_POINTER(srealloc(p42,5););
printStats();
void* p172 = last_address;
PRINT_POINTER(scalloc(91,120););
printStats();
void* p173 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p174 = last_address;
PRINT_POINTER(scalloc(164,219););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p176 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p177 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(srealloc(p136,198););
printStats();
void* p178 = last_address;
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(srealloc(p133,123););
printStats();
void* p179 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p180 = last_address;
PRINT_POINTER(srealloc(p75,195););
printStats();
void* p181 = last_address;
PRINT_POINTER(scalloc(234,212););
printStats();
void* p182 = last_address;
PRINT_POINTER(srealloc(p135,32););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(166,88););
printStats();
void* p184 = last_address;
PRINT_POINTER(srealloc(p94,58););
printStats();
void* p185 = last_address;
PRINT_POINTER(scalloc(79,65););
printStats();
void* p186 = last_address;
DEBUG_PRINT(sfree(p146););
printStats();
PRINT_POINTER(scalloc(5,138););
printStats();
void* p187 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p188 = last_address;
DEBUG_PRINT(sfree(p178););
printStats();
PRINT_POINTER(smalloc(42););
printStats();
void* p189 = last_address;
PRINT_POINTER(srealloc(p41,247););
printStats();
void* p190 = last_address;
DEBUG_PRINT(sfree(p168););
printStats();
DEBUG_PRINT(sfree(p164););
printStats();
PRINT_POINTER(smalloc(80););
printStats();
void* p191 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p192 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p193 = last_address;
DEBUG_PRINT(sfree(p160););
printStats();
DEBUG_PRINT(sfree(p126););
printStats();
DEBUG_PRINT(sfree(p174););
printStats();
PRINT_POINTER(srealloc(p152,89););
printStats();
void* p194 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(srealloc(p163,142););
printStats();
void* p196 = last_address;
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(smalloc(83););
printStats();
void* p197 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p198 = last_address;
PRINT_POINTER(scalloc(169,96););
printStats();
void* p199 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(srealloc(p156,249););
printStats();
void* p200 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p201 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p202 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p203 = last_address;
PRINT_POINTER(scalloc(62,4););
printStats();
void* p204 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p205 = last_address;
DEBUG_PRINT(sfree(p161););
printStats();
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(smalloc(138););
printStats();
void* p206 = last_address;
PRINT_POINTER(scalloc(20,131););
printStats();
void* p207 = last_address;
PRINT_POINTER(scalloc(6,41););
printStats();
void* p208 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
PRINT_POINTER(srealloc(p79,36););
printStats();
void* p209 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
PRINT_POINTER(scalloc(239,249););
printStats();
void* p210 = last_address;
PRINT_POINTER(scalloc(3,229););
printStats();
void* p211 = last_address;
PRINT_POINTER(srealloc(p177,121););
printStats();
void* p212 = last_address;
PRINT_POINTER(scalloc(46,181););
printStats();
void* p213 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p214 = last_address;
PRINT_POINTER(srealloc(p165,247););
printStats();
void* p215 = last_address;
PRINT_POINTER(srealloc(p155,50););
printStats();
void* p216 = last_address;
PRINT_POINTER(scalloc(245,139););
printStats();
void* p217 = last_address;
DEBUG_PRINT(sfree(p193););
printStats();
PRINT_POINTER(smalloc(131););
printStats();
void* p218 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p219 = last_address;
PRINT_POINTER(scalloc(2,59););
printStats();
void* p220 = last_address;
PRINT_POINTER(scalloc(57,191););
printStats();
void* p221 = last_address;
PRINT_POINTER(srealloc(p207,7););
printStats();
void* p222 = last_address;
DEBUG_PRINT(sfree(p182););
printStats();
PRINT_POINTER(srealloc(p90,203););
printStats();
void* p223 = last_address;
PRINT_POINTER(srealloc(p169,155););
printStats();
void* p224 = last_address;
DEBUG_PRINT(sfree(p162););
printStats();
PRINT_POINTER(smalloc(54););
printStats();
void* p225 = last_address;
PRINT_POINTER(srealloc(p189,211););
printStats();
void* p226 = last_address;
PRINT_POINTER(srealloc(p175,102););
printStats();
void* p227 = last_address;
PRINT_POINTER(scalloc(36,178););
printStats();
void* p228 = last_address;
DEBUG_PRINT(sfree(p180););
printStats();
PRINT_POINTER(scalloc(119,4););
printStats();
void* p229 = last_address;
PRINT_POINTER(scalloc(236,80););
printStats();
void* p230 = last_address;
DEBUG_PRINT(sfree(p121););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p231 = last_address;
DEBUG_PRINT(sfree(p203););
printStats();
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(scalloc(41,233););
printStats();
void* p232 = last_address;
PRINT_POINTER(srealloc(p54,41););
printStats();
void* p233 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p234 = last_address;
DEBUG_PRINT(sfree(p225););
printStats();
PRINT_POINTER(scalloc(98,188););
printStats();
void* p235 = last_address;
DEBUG_PRINT(sfree(p183););
printStats();
PRINT_POINTER(scalloc(162,79););
printStats();
void* p236 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(smalloc(142););
printStats();
void* p237 = last_address;
DEBUG_PRINT(sfree(p151););
printStats();
PRINT_POINTER(scalloc(74,240););
printStats();
void* p238 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p212,225););
printStats();
void* p240 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p241 = last_address;
DEBUG_PRINT(sfree(p167););
printStats();
PRINT_POINTER(scalloc(157,171););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p153););
printStats();
PRINT_POINTER(srealloc(p218,36););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p206););
printStats();
PRINT_POINTER(srealloc(p102,186););
printStats();
void* p244 = last_address;
DEBUG_PRINT(sfree(p238););
printStats();
PRINT_POINTER(srealloc(p219,193););
printStats();
void* p245 = last_address;
PRINT_POINTER(srealloc(p230,92););
printStats();
void* p246 = last_address;
DEBUG_PRINT(sfree(p143););
printStats();
PRINT_POINTER(srealloc(p171,6););
printStats();
void* p247 = last_address;
DEBUG_PRINT(sfree(p149););
printStats();
PRINT_POINTER(smalloc(147););
printStats();
void* p248 = last_address;
PRINT_POINTER(scalloc(201,217););
printStats();
void* p249 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p250 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p251 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p252 = last_address;
PRINT_POINTER(scalloc(223,162););
printStats();
void* p253 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p254 = last_address;
PRINT_POINTER(srealloc(p248,114););
printStats();
void* p255 = last_address;
PRINT_POINTER(scalloc(188,247););
printStats();
void* p256 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p257 = last_address;
PRINT_POINTER(scalloc(48,218););
printStats();
void* p258 = last_address;
PRINT_POINTER(srealloc(p214,238););
printStats();
void* p259 = last_address;
PRINT_POINTER(srealloc(p157,170););
printStats();
void* p260 = last_address;
PRINT_POINTER(srealloc(p254,90););
printStats();
void* p261 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p262 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p263 = last_address;
DEBUG_PRINT(sfree(p253););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p264 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
DEBUG_PRINT(sfree(p239););
printStats();
PRINT_POINTER(srealloc(p192,0););
printStats();
void* p265 = last_address;
PRINT_POINTER(scalloc(142,117););
printStats();
void* p266 = last_address;
PRINT_POINTER(scalloc(61,88););
printStats();
void* p267 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p268 = last_address;
PRINT_POINTER(srealloc(p188,21););
printStats();
void* p269 = last_address;
PRINT_POINTER(srealloc(p240,136););
printStats();
void* p270 = last_address;
DEBUG_PRINT(sfree(p256););
printStats();
PRINT_POINTER(scalloc(185,215););
printStats();
void* p271 = last_address;
PRINT_POINTER(srealloc(p269,181););
printStats();
void* p272 = last_address;
DEBUG_PRINT(sfree(p205););
printStats();
DEBUG_PRINT(sfree(p271););
printStats();
PRINT_POINTER(srealloc(p202,20););
printStats();
void* p273 = last_address;
PRINT_POINTER(scalloc(38,45););
printStats();
void* p274 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p275 = last_address;
PRINT_POINTER(scalloc(143,53););
printStats();
void* p276 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p277 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p278 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p279 = last_address;
PRINT_POINTER(scalloc(226,92););
printStats();
void* p280 = last_address;
PRINT_POINTER(scalloc(243,28););
printStats();
void* p281 = last_address;
PRINT_POINTER(scalloc(135,243););
printStats();
void* p282 = last_address;
PRINT_POINTER(srealloc(p243,9););
printStats();
void* p283 = last_address;
PRINT_POINTER(srealloc(p259,24););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p197,160););
printStats();
void* p285 = last_address;
DEBUG_PRINT(sfree(p226););
printStats();
PRINT_POINTER(scalloc(21,226););
printStats();
void* p286 = last_address;
PRINT_POINTER(scalloc(181,61););
printStats();
void* p287 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p288 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p289 = last_address;
DEBUG_PRINT(sfree(p255););
printStats();
PRINT_POINTER(srealloc(p190,109););
printStats();
void* p290 = last_address;
PRINT_POINTER(scalloc(124,160););
printStats();
void* p291 = last_address;
PRINT_POINTER(srealloc(p198,178););
printStats();
void* p292 = last_address;
PRINT_POINTER(srealloc(p185,128););
printStats();
void* p293 = last_address;
PRINT_POINTER(srealloc(p286,182););
printStats();
void* p294 = last_address;
DEBUG_PRINT(sfree(p158););
printStats();
PRINT_POINTER(srealloc(p224,91););
printStats();
void* p295 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p296 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p297 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(srealloc(p272,231););
printStats();
void* p298 = last_address;
DEBUG_PRINT(sfree(p217););
printStats();
DEBUG_PRINT(sfree(p281););
printStats();
DEBUG_PRINT(sfree(p213););
printStats();
PRINT_POINTER(scalloc(75,158););
printStats();
void* p299 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p300 = last_address;
DEBUG_PRINT(sfree(p251););
printStats();
PRINT_POINTER(srealloc(p263,226););
printStats();
void* p301 = last_address;
PRINT_POINTER(scalloc(174,202););
printStats();
void* p302 = last_address;
PRINT_POINTER(srealloc(p227,121););
printStats();
void* p303 = last_address;
PRINT_POINTER(srealloc(p273,122););
printStats();
void* p304 = last_address;
PRINT_POINTER(scalloc(241,23););
printStats();
void* p305 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p306 = last_address;
PRINT_POINTER(scalloc(7,2););
printStats();
void* p307 = last_address;
PRINT_POINTER(scalloc(237,104););
printStats();
void* p308 = last_address;
PRINT_POINTER(scalloc(175,161););
printStats();
void* p309 = last_address;
PRINT_POINTER(srealloc(p233,132););
printStats();
void* p310 = last_address;
PRINT_POINTER(scalloc(152,192););
printStats();
void* p311 = last_address;
PRINT_POINTER(scalloc(162,7););
printStats();
void* p312 = last_address;
PRINT_POINTER(scalloc(99,151););
printStats();
void* p313 = last_address;
PRINT_POINTER(scalloc(200,53););
printStats();
void* p314 = last_address;
PRINT_POINTER(srealloc(p216,186););
printStats();
void* p315 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p316 = last_address;
PRINT_POINTER(scalloc(83,63););
printStats();
void* p317 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p318 = last_address;
PRINT_POINTER(srealloc(p275,223););
printStats();
void* p319 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p320 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p321 = last_address;
PRINT_POINTER(srealloc(p130,48););
printStats();
void* p322 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p323 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p324 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
DEBUG_PRINT(sfree(p318););
printStats();
PRINT_POINTER(srealloc(p296,214););
printStats();
void* p325 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p326 = last_address;
DEBUG_PRINT(sfree(p299););
printStats();
PRINT_POINTER(srealloc(p289,14););
printStats();
void* p327 = last_address;
PRINT_POINTER(scalloc(36,69););
printStats();
void* p328 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p329 = last_address;
PRINT_POINTER(scalloc(3,43););
printStats();
void* p330 = last_address;
PRINT_POINTER(srealloc(p249,60););
printStats();
void* p331 = last_address;
PRINT_POINTER(scalloc(192,229););
printStats();
void* p332 = last_address;
PRINT_POINTER(scalloc(152,19););
printStats();
void* p333 = last_address;
PRINT_POINTER(srealloc(p229,192););
printStats();
void* p334 = last_address;
PRINT_POINTER(scalloc(72,172););
printStats();
void* p335 = last_address;
PRINT_POINTER(scalloc(161,106););
printStats();
void* p336 = last_address;
PRINT_POINTER(scalloc(137,91););
printStats();
void* p337 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p338 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p339 = last_address;
PRINT_POINTER(srealloc(p237,226););
printStats();
void* p340 = last_address;
DEBUG_PRINT(sfree(p88););
printStats();
PRINT_POINTER(scalloc(171,240););
printStats();
void* p341 = last_address;
PRINT_POINTER(srealloc(p270,99););
printStats();
void* p342 = last_address;
PRINT_POINTER(srealloc(p247,242););
printStats();
void* p343 = last_address;
DEBUG_PRINT(sfree(p311););
printStats();
PRINT_POINTER(srealloc(p310,2););
printStats();
void* p344 = last_address;
PRINT_POINTER(scalloc(225,187););
printStats();
void* p345 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p346 = last_address;
DEBUG_PRINT(sfree(p279););
printStats();
DEBUG_PRINT(sfree(p23););
printStats();
PRINT_POINTER(scalloc(202,117););
printStats();
void* p347 = last_address;
DEBUG_PRINT(sfree(p195););
printStats();
PRINT_POINTER(srealloc(p221,152););
printStats();
void* p348 = last_address;
PRINT_POINTER(scalloc(174,16););
printStats();
void* p349 = last_address;
PRINT_POINTER(scalloc(147,201););
printStats();
void* p350 = last_address;
PRINT_POINTER(srealloc(p331,72););
printStats();
void* p351 = last_address;
PRINT_POINTER(srealloc(p245,114););
printStats();
void* p352 = last_address;
PRINT_POINTER(scalloc(206,186););
printStats();
void* p353 = last_address;
PRINT_POINTER(scalloc(120,180););
printStats();
void* p354 = last_address;
PRINT_POINTER(srealloc(p333,54););
printStats();
void* p355 = last_address;
PRINT_POINTER(scalloc(8,133););
printStats();
void* p356 = last_address;
PRINT_POINTER(srealloc(p316,124););
printStats();
void* p357 = last_address;
DEBUG_PRINT(sfree(p357););
printStats();
PRINT_POINTER(scalloc(142,157););
printStats();
void* p358 = last_address;
DEBUG_PRINT(sfree(p260););
printStats();
PRINT_POINTER(scalloc(230,163););
printStats();
void* p359 = last_address;
PRINT_POINTER(srealloc(p336,23););
printStats();
void* p360 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p362 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p363 = last_address;
PRINT_POINTER(srealloc(p314,15););
printStats();
void* p364 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p365 = last_address;
PRINT_POINTER(scalloc(17,97););
printStats();
void* p366 = last_address;
PRINT_POINTER(scalloc(241,165););
printStats();
void* p367 = last_address;
PRINT_POINTER(srealloc(p332,226););
printStats();
void* p368 = last_address;
PRINT_POINTER(scalloc(162,208););
printStats();
void* p369 = last_address;
DEBUG_PRINT(sfree(p204););
printStats();
PRINT_POINTER(srealloc(p327,9););
printStats();
void* p370 = last_address;
PRINT_POINTER(srealloc(p348,180););
printStats();
void* p371 = last_address;
PRINT_POINTER(srealloc(p361,137););
printStats();
void* p372 = last_address;
PRINT_POINTER(srealloc(p367,71););
printStats();
void* p373 = last_address;
DEBUG_PRINT(sfree(p267););
printStats();
PRINT_POINTER(smalloc(11););
printStats();
void* p374 = last_address;
DEBUG_PRINT(sfree(p354););
printStats();
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p375 = last_address;
PRINT_POINTER(scalloc(234,83););
printStats();
void* p376 = last_address;
PRINT_POINTER(scalloc(31,248););
printStats();
void* p377 = last_address;
DEBUG_PRINT(sfree(p346););
printStats();
PRINT_POINTER(srealloc(p288,88););
printStats();
void* p378 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p379 = last_address;
DEBUG_PRINT(sfree(p317););
printStats();
PRINT_POINTER(smalloc(59););
printStats();
void* p380 = last_address;
PRINT_POINTER(scalloc(172,122););
printStats();
void* p381 = last_address;
PRINT_POINTER(srealloc(p343,110););
printStats();
void* p382 = last_address;
PRINT_POINTER(srealloc(p352,44););
printStats();
void* p383 = last_address;
PRINT_POINTER(srealloc(p365,111););
printStats();
void* p384 = last_address;
DEBUG_PRINT(sfree(p376););
printStats();
DEBUG_PRINT(sfree(p381););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p385 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p386 = last_address;
PRINT_POINTER(srealloc(p320,188););
printStats();
void* p387 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p388 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p389 = last_address;
DEBUG_PRINT(sfree(p366););
printStats();
DEBUG_PRINT(sfree(p257););
printStats();
PRINT_POINTER(scalloc(187,155););
printStats();
void* p390 = last_address;
PRINT_POINTER(srealloc(p277,169););
printStats();
void* p391 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p392 = last_address;
PRINT_POINTER(scalloc(163,116););
printStats();
void* p393 = last_address;
DEBUG_PRINT(sfree(p266););
printStats();
PRINT_POINTER(smalloc(84););
printStats();
void* p394 = last_address;
PRINT_POINTER(srealloc(p305,145););
printStats();
void* p395 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p396 = last_address;
PRINT_POINTER(scalloc(124,231););
printStats();
void* p397 = last_address;
PRINT_POINTER(srealloc(p363,234););
printStats();
void* p398 = last_address;
PRINT_POINTER(scalloc(189,155););
printStats();
void* p399 = last_address;
DEBUG_PRINT(sfree(p359););
printStats();
DEBUG_PRINT(sfree(p278););
printStats();
PRINT_POINTER(scalloc(103,174););
printStats();
void* p400 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p401 = last_address;
PRINT_POINTER(scalloc(73,18););
printStats();
void* p402 = last_address;
PRINT_POINTER(srealloc(p334,133););
printStats();
void* p403 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p404 = last_address;
PRINT_POINTER(scalloc(243,106););
printStats();
void* p405 = last_address;
PRINT_POINTER(scalloc(6,88););
printStats();
void* p406 = last_address;
DEBUG_PRINT(sfree(p304););
printStats();
DEBUG_PRINT(sfree(p400););
printStats();
DEBUG_PRINT(sfree(p398););
printStats();
DEBUG_PRINT(sfree(p297););
printStats();
PRINT_POINTER(smalloc(70););
printStats();
void* p407 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p408 = last_address;
DEBUG_PRINT(sfree(p322););
printStats();
PRINT_POINTER(srealloc(p395,156););
printStats();
void* p409 = last_address;
PRINT_POINTER(srealloc(p330,23););
printStats();
void* p410 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p411 = last_address;
PRINT_POINTER(scalloc(194,224););
printStats();
void* p412 = last_address;
PRINT_POINTER(scalloc(145,30););
printStats();
void* p413 = last_address;
PRINT_POINTER(scalloc(125,83););
printStats();
void* p414 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p415 = last_address;
PRINT_POINTER(scalloc(40,220););
printStats();
void* p416 = last_address;
PRINT_POINTER(srealloc(p312,218););
printStats();
void* p417 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p418 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p419 = last_address;
DEBUG_PRINT(sfree(p368););
printStats();
PRINT_POINTER(smalloc(156););
printStats();
void* p420 = last_address;
PRINT_POINTER(srealloc(p154,132););
printStats();
void* p421 = last_address;
PRINT_POINTER(scalloc(196,206););
printStats();
void* p422 = last_address;
DEBUG_PRINT(sfree(p235););
printStats();
PRINT_POINTER(smalloc(31););
printStats();
void* p423 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p424 = last_address;
PRINT_POINTER(scalloc(91,159););
printStats();
void* p425 = last_address;
DEBUG_PRINT(sfree(p378););
printStats();
DEBUG_PRINT(sfree(p391););
printStats();
PRINT_POINTER(srealloc(p335,88););
printStats();
void* p426 = last_address;
PRINT_POINTER(srealloc(p285,39););
printStats();
void* p427 = last_address;
DEBUG_PRINT(sfree(p292););
printStats();
PRINT_POINTER(scalloc(40,166););
printStats();
void* p428 = last_address;
PRINT_POINTER(srealloc(p201,219););
printStats();
void* p429 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(smalloc(242););
printStats();
void* p430 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p431 = last_address;
PRINT_POINTER(scalloc(239,51););
printStats();
void* p432 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p433 = last_address;
PRINT_POINTER(srealloc(p319,110););
printStats();
void* p434 = last_address;
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p435 = last_address;
DEBUG_PRINT(sfree(p420););
printStats();
PRINT_POINTER(scalloc(29,55););
printStats();
void* p436 = last_address;
PRINT_POINTER(scalloc(51,47););
printStats();
void* p437 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p438 = last_address;
PRINT_POINTER(scalloc(7,92););
printStats();
void* p439 = last_address;
PRINT_POINTER(srealloc(p429,42););
printStats();
void* p440 = last_address;
PRINT_POINTER(srealloc(p306,136););
printStats();
void* p441 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
PRINT_POINTER(scalloc(95,183););
printStats();
void* p442 = last_address;
PRINT_POINTER(scalloc(56,245););
printStats();
void* p443 = last_address;
DEBUG_PRINT(sfree(p404););
printStats();
PRINT_POINTER(scalloc(122,112););
printStats();
void* p444 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p445 = last_address;
PRINT_POINTER(srealloc(p261,138););
printStats();
void* p446 = last_address;
PRINT_POINTER(srealloc(p412,198););
printStats();
void* p447 = last_address;
DEBUG_PRINT(sfree(p442););
printStats();
PRINT_POINTER(srealloc(p434,119););
printStats();
void* p448 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p449 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p450 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p451 = last_address;
PRINT_POINTER(scalloc(114,34););
printStats();
void* p452 = last_address;
DEBUG_PRINT(sfree(p341););
printStats();
PRINT_POINTER(srealloc(p379,203););
printStats();
void* p453 = last_address;
DEBUG_PRINT(sfree(p300););
printStats();
PRINT_POINTER(scalloc(110,175););
printStats();
void* p454 = last_address;
DEBUG_PRINT(sfree(p179););
printStats();
DEBUG_PRINT(sfree(p215););
printStats();
DEBUG_PRINT(sfree(p407););
printStats();
PRINT_POINTER(srealloc(p173,145););
printStats();
void* p455 = last_address;
DEBUG_PRINT(sfree(p258););
printStats();
PRINT_POINTER(srealloc(p436,115););
printStats();
void* p456 = last_address;
PRINT_POINTER(scalloc(31,117););
printStats();
void* p457 = last_address;
DEBUG_PRINT(sfree(p242););
printStats();
PRINT_POINTER(srealloc(p375,248););
printStats();
void* p458 = last_address;
DEBUG_PRINT(sfree(p449););
printStats();
PRINT_POINTER(scalloc(60,175););
printStats();
void* p459 = last_address;
DEBUG_PRINT(sfree(p431););
printStats();
DEBUG_PRINT(sfree(p355););
printStats();
PRINT_POINTER(scalloc(130,206););
printStats();
void* p460 = last_address;
DEBUG_PRINT(sfree(p347););
printStats();
PRINT_POINTER(smalloc(165););
printStats();
void* p461 = last_address;
PRINT_POINTER(scalloc(225,156););
printStats();
void* p462 = last_address;
PRINT_POINTER(srealloc(p450,175););
printStats();
void* p463 = last_address;
DEBUG_PRINT(sfree(p293););
printStats();
PRINT_POINTER(srealloc(p194,83););
printStats();
void* p464 = last_address;
PRINT_POINTER(srealloc(p377,124););
printStats();
void* p465 = last_address;
PRINT_POINTER(scalloc(235,37););
printStats();
void* p466 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p467 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p468 = last_address;
PRINT_POINTER(srealloc(p172,163););
printStats();
void* p469 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p470 = last_address;
PRINT_POINTER(scalloc(214,13););
printStats();
void* p471 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p472 = last_address;
DEBUG_PRINT(sfree(p458););
printStats();
DEBUG_PRINT(sfree(p390););
printStats();
PRINT_POINTER(smalloc(219););
printStats();
void* p473 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
PRINT_POINTER(scalloc(245,39););
printStats();
void* p474 = last_address;
PRINT_POINTER(srealloc(p413,156););
printStats();
void* p475 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p476 = last_address;
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(srealloc(p418,230););
printStats();
void* p477 = last_address;
PRINT_POINTER(scalloc(51,247););
printStats();
void* p478 = last_address;
PRINT_POINTER(srealloc(p461,242););
printStats();
void* p479 = last_address;
PRINT_POINTER(srealloc(p244,105););
printStats();
void* p480 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p481 = last_address;
PRINT_POINTER(srealloc(p386,131););
printStats();
void* p482 = last_address;
DEBUG_PRINT(sfree(p432););
printStats();
DEBUG_PRINT(sfree(p191););
printStats();
PRINT_POINTER(smalloc(87););
printStats();
void* p483 = last_address;
DEBUG_PRINT(sfree(p439););
printStats();
PRINT_POINTER(smalloc(128););
printStats();
void* p484 = last_address;
DEBUG_PRINT(sfree(p342););
printStats();
PRINT_POINTER(smalloc(12););
printStats();
void* p485 = last_address;
PRINT_POINTER(srealloc(p323,204););
printStats();
void* p486 = last_address;
PRINT_POINTER(scalloc(93,154););
printStats();
void* p487 = last_address;
PRINT_POINTER(scalloc(174,203););
printStats();
void* p488 = last_address;
DEBUG_PRINT(sfree(p349););
printStats();
DEBUG_PRINT(sfree(p303););
printStats();
DEBUG_PRINT(sfree(p468););
printStats();
DEBUG_PRINT(sfree(p480););
printStats();
PRINT_POINTER(smalloc(35););
printStats();
void* p489 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p490 = last_address;
PRINT_POINTER(srealloc(p208,0););
printStats();
void* p491 = last_address;
PRINT_POINTER(srealloc(p338,0););
printStats();
void* p492 = last_address;
PRINT_POINTER(srealloc(p280,119););
printStats();
void* p493 = last_address;
PRINT_POINTER(srealloc(p401,235););
printStats();
void* p494 = last_address;
PRINT_POINTER(srealloc(p417,31););
printStats();
void* p495 = last_address;
PRINT_POINTER(scalloc(184,36););
printStats();
void* p496 = last_address;
DEBUG_PRINT(sfree(p264););
printStats();
PRINT_POINTER(smalloc(226););
printStats();
void* p497 = last_address;
DEBUG_PRINT(sfree(p441););
printStats();
PRINT_POINTER(smalloc(25););
printStats();
void* p498 = last_address;
DEBUG_PRINT(sfree(p478););
printStats();
PRINT_POINTER(smalloc(142););
printStats();
void* p499 = last_address;
DEBUG_PRINT(sfree(p302););
printStats();
DEBUG_PRINT(sfree(p445););
printStats();
DEBUG_PRINT(sfree(p315););
printStats();
DEBUG_PRINT(sfree(p493););
printStats();
PRINT_POINTER(smalloc(154););
printStats();
void* p500 = last_address;
PRINT_POINTER(srealloc(p408,84););
printStats();
void* p501 = last_address;
PRINT_POINTER(scalloc(210,241););
printStats();
void* p502 = last_address;
PRINT_POINTER(srealloc(p369,185););
printStats();
void* p503 = last_address;
PRINT_POINTER(srealloc(p295,0););
printStats();
void* p504 = last_address;
PRINT_POINTER(scalloc(242,67););
printStats();
void* p505 = last_address;
PRINT_POINTER(srealloc(p232,81););
printStats();
void* p506 = last_address;
PRINT_POINTER(scalloc(56,9););
printStats();
void* p507 = last_address;
DEBUG_PRINT(sfree(p184););
printStats();
DEBUG_PRINT(sfree(p466););
printStats();
PRINT_POINTER(scalloc(3,203););
printStats();
void* p508 = last_address;
PRINT_POINTER(srealloc(p488,114););
printStats();
void* p509 = last_address;
DEBUG_PRINT(sfree(p246););
printStats();
PRINT_POINTER(scalloc(100,139););
printStats();
void* p510 = last_address;
PRINT_POINTER(srealloc(p428,207););
printStats();
void* p511 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p512 = last_address;
PRINT_POINTER(srealloc(p276,134););
printStats();
void* p513 = last_address;
PRINT_POINTER(scalloc(210,241););
printStats();
void* p514 = last_address;
DEBUG_PRINT(sfree(p393););
printStats();
PRINT_POINTER(scalloc(43,122););
printStats();
void* p515 = last_address;
PRINT_POINTER(srealloc(p486,144););
printStats();
void* p516 = last_address;
DEBUG_PRINT(sfree(p419););
printStats();
PRINT_POINTER(scalloc(155,136););
printStats();
void* p517 = last_address;
DEBUG_PRINT(sfree(p507););
printStats();
DEBUG_PRINT(sfree(p497););
printStats();
PRINT_POINTER(smalloc(105););
printStats();
void* p518 = last_address;
DEBUG_PRINT(sfree(p516););
printStats();
PRINT_POINTER(srealloc(p465,17););
printStats();
void* p519 = last_address;
PRINT_POINTER(scalloc(123,42););
printStats();
void* p520 = last_address;
DEBUG_PRINT(sfree(p402););
printStats();
PRINT_POINTER(srealloc(p410,136););
printStats();
void* p521 = last_address;
DEBUG_PRINT(sfree(p364););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p522 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p523 = last_address;
DEBUG_PRINT(sfree(p307););
printStats();
PRINT_POINTER(scalloc(172,116););
printStats();
void* p524 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p525 = last_address;
DEBUG_PRINT(sfree(p351););
printStats();
PRINT_POINTER(smalloc(106););
printStats();
void* p526 = last_address;
DEBUG_PRINT(sfree(p340););
printStats();
PRINT_POINTER(scalloc(234,233););
printStats();
void* p527 = last_address;
DEBUG_PRINT(sfree(p394););
printStats();
PRINT_POINTER(srealloc(p353,170););
printStats();
void* p528 = last_address;
DEBUG_PRINT(sfree(p406););
printStats();
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(scalloc(7,220););
printStats();
void* p529 = last_address;
PRINT_POINTER(srealloc(p325,225););
printStats();
void* p530 = last_address;
PRINT_POINTER(srealloc(p443,44););
printStats();
void* p531 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p532 = last_address;
PRINT_POINTER(srealloc(p371,24););
printStats();
void* p533 = last_address;
PRINT_POINTER(srealloc(p523,131););
printStats();
void* p534 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p535 = last_address;
PRINT_POINTER(scalloc(159,99););
printStats();
void* p536 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p537 = last_address;
DEBUG_PRINT(sfree(p388););
printStats();
PRINT_POINTER(srealloc(p482,240););
printStats();
void* p538 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p539 = last_address;
DEBUG_PRINT(sfree(p383););
printStats();
PRINT_POINTER(srealloc(p309,3););
printStats();
void* p540 = last_address;
PRINT_POINTER(scalloc(64,17););
printStats();
void* p541 = last_address;
PRINT_POINTER(scalloc(223,70););
printStats();
void* p542 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p543 = last_address;
PRINT_POINTER(srealloc(p382,172););
printStats();
void* p544 = last_address;
PRINT_POINTER(scalloc(9,87););
printStats();
void* p545 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p546 = last_address;
PRINT_POINTER(scalloc(128,122););
printStats();
void* p547 = last_address;
DEBUG_PRINT(sfree(p537););
printStats();
PRINT_POINTER(scalloc(182,217););
printStats();
void* p548 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p549 = last_address;
PRINT_POINTER(srealloc(p298,53););
printStats();
void* p550 = last_address;
PRINT_POINTER(scalloc(77,182););
printStats();
void* p551 = last_address;
DEBUG_PRINT(sfree(p489););
printStats();
PRINT_POINTER(srealloc(p372,34););
printStats();
void* p552 = last_address;
PRINT_POINTER(srealloc(p464,88););
printStats();
void* p553 = last_address;
PRINT_POINTER(scalloc(224,226););
printStats();
void* p554 = last_address;
PRINT_POINTER(srealloc(p492,91););
printStats();
void* p555 = last_address;
PRINT_POINTER(srealloc(p479,215););
printStats();
void* p556 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p557 = last_address;
DEBUG_PRINT(sfree(p236););
printStats();
PRINT_POINTER(scalloc(19,244););
printStats();
void* p558 = last_address;
PRINT_POINTER(srealloc(p337,24););
printStats();
void* p559 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p560 = last_address;
DEBUG_PRINT(sfree(p558););
printStats();
PRINT_POINTER(smalloc(248););
printStats();
void* p561 = last_address;
DEBUG_PRINT(sfree(p425););
printStats();
PRINT_POINTER(scalloc(168,221););
printStats();
void* p562 = last_address;
PRINT_POINTER(srealloc(p546,241););
printStats();
void* p563 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p564 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p565 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p566 = last_address;
DEBUG_PRINT(sfree(p339););
printStats();
DEBUG_PRINT(sfree(p399););
printStats();
PRINT_POINTER(smalloc(51););
printStats();
void* p567 = last_address;
PRINT_POINTER(srealloc(p504,151););
printStats();
void* p568 = last_address;
PRINT_POINTER(srealloc(p513,185););
printStats();
void* p569 = last_address;
DEBUG_PRINT(sfree(p463););
printStats();
PRINT_POINTER(srealloc(p502,97););
printStats();
void* p570 = last_address;
DEBUG_PRINT(sfree(p510););
printStats();
PRINT_POINTER(srealloc(p514,245););
printStats();
void* p571 = last_address;
PRINT_POINTER(scalloc(233,243););
printStats();
void* p572 = last_address;
PRINT_POINTER(srealloc(p424,210););
printStats();
void* p573 = last_address;
DEBUG_PRINT(sfree(p527););
printStats();
PRINT_POINTER(smalloc(152););
printStats();
void* p574 = last_address;
PRINT_POINTER(scalloc(246,54););
printStats();
void* p575 = last_address;
DEBUG_PRINT(sfree(p531););
printStats();
PRINT_POINTER(srealloc(p567,5););
printStats();
void* p576 = last_address;
PRINT_POINTER(scalloc(76,193););
printStats();
void* p577 = last_address;
DEBUG_PRINT(sfree(p573););
printStats();
PRINT_POINTER(smalloc(179););
printStats();
void* p578 = last_address;
PRINT_POINTER(scalloc(115,123););
printStats();
void* p579 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p580 = last_address;
PRINT_POINTER(srealloc(p435,130););
printStats();
void* p581 = last_address;
DEBUG_PRINT(sfree(p569););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p582 = last_address;
PRINT_POINTER(srealloc(p552,165););
printStats();
void* p583 = last_address;
PRINT_POINTER(srealloc(p557,132););
printStats();
void* p584 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p585 = last_address;
DEBUG_PRINT(sfree(p392););
printStats();
PRINT_POINTER(srealloc(p563,191););
printStats();
void* p586 = last_address;
DEBUG_PRINT(sfree(p512););
printStats();
PRINT_POINTER(smalloc(96););
printStats();
void* p587 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p588 = last_address;
DEBUG_PRINT(sfree(p553););
printStats();
DEBUG_PRINT(sfree(p581););
printStats();
PRINT_POINTER(scalloc(112,140););
printStats();
void* p589 = last_address;
DEBUG_PRINT(sfree(p574););
printStats();
PRINT_POINTER(smalloc(115););
printStats();
void* p590 = last_address;
PRINT_POINTER(scalloc(228,181););
printStats();
void* p591 = last_address;
PRINT_POINTER(scalloc(110,45););
printStats();
void* p592 = last_address;
DEBUG_PRINT(sfree(p500););
printStats();
DEBUG_PRINT(sfree(p389););
printStats();
DEBUG_PRINT(sfree(p566););
printStats();
DEBUG_PRINT(sfree(p290););
printStats();
DEBUG_PRINT(sfree(p503););
printStats();
PRINT_POINTER(scalloc(37,10););
printStats();
void* p593 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p594 = last_address;
PRINT_POINTER(srealloc(p467,15););
printStats();
void* p595 = last_address;
PRINT_POINTER(scalloc(174,222););
printStats();
void* p596 = last_address;
PRINT_POINTER(scalloc(66,76););
printStats();
void* p597 = last_address;
PRINT_POINTER(srealloc(p328,46););
printStats();
void* p598 = last_address;
PRINT_POINTER(scalloc(237,186););
printStats();
void* p599 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p600 = last_address;
PRINT_POINTER(srealloc(p473,88););
printStats();
void* p601 = last_address;
DEBUG_PRINT(sfree(p415););
printStats();
PRINT_POINTER(smalloc(20););
printStats();
void* p602 = last_address;
DEBUG_PRINT(sfree(p220););
printStats();
DEBUG_PRINT(sfree(p509););
printStats();
DEBUG_PRINT(sfree(p313););
printStats();
DEBUG_PRINT(sfree(p580););
printStats();
DEBUG_PRINT(sfree(p427););
printStats();
PRINT_POINTER(srealloc(p471,166););
printStats();
void* p603 = last_address;
DEBUG_PRINT(sfree(p548););
printStats();
PRINT_POINTER(scalloc(137,82););
printStats();
void* p604 = last_address;
PRINT_POINTER(srealloc(p534,176););
printStats();
void* p605 = last_address;
PRINT_POINTER(srealloc(p409,45););
printStats();
void* p606 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p607 = last_address;
DEBUG_PRINT(sfree(p526););
printStats();
PRINT_POINTER(srealloc(p579,86););
printStats();
void* p608 = last_address;
PRINT_POINTER(scalloc(68,245););
printStats();
void* p609 = last_address;
PRINT_POINTER(srealloc(p535,16););
printStats();
void* p610 = last_address;
PRINT_POINTER(srealloc(p460,39););
printStats();
void* p611 = last_address;
DEBUG_PRINT(sfree(p423););
printStats();
PRINT_POINTER(scalloc(41,77););
printStats();
void* p612 = last_address;
PRINT_POINTER(scalloc(123,165););
printStats();
void* p613 = last_address;
DEBUG_PRINT(sfree(p345););
printStats();
DEBUG_PRINT(sfree(p484););
printStats();
PRINT_POINTER(srealloc(p501,93););
printStats();
void* p614 = last_address;
PRINT_POINTER(scalloc(192,160););
printStats();
void* p615 = last_address;
PRINT_POINTER(srealloc(p459,50););
printStats();
void* p616 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p617 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p618 = last_address;
PRINT_POINTER(scalloc(44,170););
printStats();
void* p619 = last_address;
PRINT_POINTER(scalloc(22,55););
printStats();
void* p620 = last_address;
DEBUG_PRINT(sfree(p605););
printStats();
PRINT_POINTER(scalloc(211,99););
printStats();
void* p621 = last_address;
PRINT_POINTER(scalloc(27,217););
printStats();
void* p622 = last_address;
DEBUG_PRINT(sfree(p613););
printStats();
PRINT_POINTER(scalloc(209,97););
printStats();
void* p623 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p624 = last_address;
PRINT_POINTER(srealloc(p576,151););
printStats();
void* p625 = last_address;
PRINT_POINTER(scalloc(220,106););
printStats();
void* p626 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p627 = last_address;
DEBUG_PRINT(sfree(p555););
printStats();
PRINT_POINTER(smalloc(63););
printStats();
void* p628 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p629 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p630 = last_address;
PRINT_POINTER(scalloc(173,239););
printStats();
void* p631 = last_address;
DEBUG_PRINT(sfree(p528););
printStats();
PRINT_POINTER(scalloc(168,244););
printStats();
void* p632 = last_address;
DEBUG_PRINT(sfree(p559););
printStats();
DEBUG_PRINT(sfree(p589););
printStats();
PRINT_POINTER(scalloc(230,79););
printStats();
void* p633 = last_address;
DEBUG_PRINT(sfree(p144););
printStats();
PRINT_POINTER(smalloc(140););
printStats();
void* p634 = last_address;
PRINT_POINTER(scalloc(18,0););
printStats();
void* p635 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p636 = last_address;
PRINT_POINTER(srealloc(p617,120););
printStats();
void* p637 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p638 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p639 = last_address;
DEBUG_PRINT(sfree(p556););
printStats();
PRINT_POINTER(smalloc(221););
printStats();
void* p640 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p641 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p642 = last_address;
PRINT_POINTER(scalloc(19,157););
printStats();
void* p643 = last_address;
PRINT_POINTER(scalloc(56,163););
printStats();
void* p644 = last_address;
PRINT_POINTER(scalloc(140,8););
printStats();
void* p645 = last_address;
PRINT_POINTER(scalloc(25,61););
printStats();
void* p646 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p647 = last_address;
PRINT_POINTER(srealloc(p595,98););
printStats();
void* p648 = last_address;
}
