#include "aux_macro.h"
#include "../malloc_4.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(173,130););
printStats();
void* p0 = last_address;
PRINT_POINTER(scalloc(141,110););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(scalloc(59,100););
printStats();
void* p2 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p3 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(scalloc(110,210););
printStats();
void* p4 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
PRINT_POINTER(srealloc(p3,42););
printStats();
void* p5 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p6 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p7 = last_address;
PRINT_POINTER(scalloc(113,56););
printStats();
void* p8 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p9 = last_address;
PRINT_POINTER(scalloc(115,48););
printStats();
void* p10 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(207,195););
printStats();
void* p12 = last_address;
PRINT_POINTER(srealloc(p9,156););
printStats();
void* p13 = last_address;
PRINT_POINTER(scalloc(106,39););
printStats();
void* p14 = last_address;
PRINT_POINTER(srealloc(p14,20););
printStats();
void* p15 = last_address;
DEBUG_PRINT(sfree(p13););
printStats();
DEBUG_PRINT(sfree(p12););
printStats();
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(smalloc(43););
printStats();
void* p16 = last_address;
PRINT_POINTER(srealloc(p15,168););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(119,102););
printStats();
void* p18 = last_address;
PRINT_POINTER(srealloc(p6,145););
printStats();
void* p19 = last_address;
PRINT_POINTER(srealloc(p16,181););
printStats();
void* p20 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p21 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
PRINT_POINTER(smalloc(0););
printStats();
void* p22 = last_address;
PRINT_POINTER(smalloc(221););
printStats();
void* p23 = last_address;
DEBUG_PRINT(sfree(p20););
printStats();
PRINT_POINTER(srealloc(p19,229););
printStats();
void* p24 = last_address;
PRINT_POINTER(scalloc(170,93););
printStats();
void* p25 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p18,46););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p26););
printStats();
PRINT_POINTER(srealloc(p10,120););
printStats();
void* p28 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p29 = last_address;
DEBUG_PRINT(sfree(p17););
printStats();
DEBUG_PRINT(sfree(p24););
printStats();
PRINT_POINTER(smalloc(61););
printStats();
void* p30 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p31 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
PRINT_POINTER(srealloc(p30,230););
printStats();
void* p32 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p33 = last_address;
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(smalloc(95););
printStats();
void* p34 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p35 = last_address;
PRINT_POINTER(scalloc(233,143););
printStats();
void* p36 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p37 = last_address;
PRINT_POINTER(srealloc(p11,49););
printStats();
void* p38 = last_address;
PRINT_POINTER(scalloc(213,154););
printStats();
void* p39 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
DEBUG_PRINT(sfree(p32););
printStats();
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(scalloc(168,72););
printStats();
void* p40 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
PRINT_POINTER(smalloc(75););
printStats();
void* p41 = last_address;
PRINT_POINTER(srealloc(p33,15););
printStats();
void* p42 = last_address;
PRINT_POINTER(srealloc(p42,115););
printStats();
void* p43 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p44 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p45 = last_address;
PRINT_POINTER(srealloc(p27,66););
printStats();
void* p46 = last_address;
PRINT_POINTER(scalloc(239,175););
printStats();
void* p47 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
PRINT_POINTER(srealloc(p22,22););
printStats();
void* p48 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p49 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p50 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p51 = last_address;
PRINT_POINTER(srealloc(p46,218););
printStats();
void* p52 = last_address;
PRINT_POINTER(srealloc(p49,176););
printStats();
void* p53 = last_address;
PRINT_POINTER(scalloc(134,153););
printStats();
void* p54 = last_address;
PRINT_POINTER(scalloc(148,54););
printStats();
void* p55 = last_address;
DEBUG_PRINT(sfree(p52););
printStats();
PRINT_POINTER(srealloc(p50,135););
printStats();
void* p56 = last_address;
PRINT_POINTER(scalloc(61,126););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(132,242););
printStats();
void* p58 = last_address;
PRINT_POINTER(scalloc(127,220););
printStats();
void* p59 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p60 = last_address;
PRINT_POINTER(scalloc(137,221););
printStats();
void* p61 = last_address;
PRINT_POINTER(srealloc(p58,44););
printStats();
void* p62 = last_address;
PRINT_POINTER(scalloc(96,42););
printStats();
void* p63 = last_address;
PRINT_POINTER(srealloc(p59,152););
printStats();
void* p64 = last_address;
DEBUG_PRINT(sfree(p63););
printStats();
PRINT_POINTER(scalloc(55,72););
printStats();
void* p65 = last_address;
PRINT_POINTER(scalloc(200,71););
printStats();
void* p66 = last_address;
PRINT_POINTER(srealloc(p44,103););
printStats();
void* p67 = last_address;
DEBUG_PRINT(sfree(p53););
printStats();
PRINT_POINTER(srealloc(p62,21););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p47,54););
printStats();
void* p69 = last_address;
DEBUG_PRINT(sfree(p55););
printStats();
PRINT_POINTER(smalloc(35););
printStats();
void* p70 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p71 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
PRINT_POINTER(srealloc(p45,33););
printStats();
void* p72 = last_address;
PRINT_POINTER(srealloc(p69,125););
printStats();
void* p73 = last_address;
PRINT_POINTER(srealloc(p56,134););
printStats();
void* p74 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p75 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p76 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p77 = last_address;
PRINT_POINTER(srealloc(p77,33););
printStats();
void* p78 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p79 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p80 = last_address;
PRINT_POINTER(scalloc(162,175););
printStats();
void* p81 = last_address;
PRINT_POINTER(scalloc(217,11););
printStats();
void* p82 = last_address;
DEBUG_PRINT(sfree(p75););
printStats();
PRINT_POINTER(scalloc(156,110););
printStats();
void* p83 = last_address;
DEBUG_PRINT(sfree(p35););
printStats();
DEBUG_PRINT(sfree(p61););
printStats();
DEBUG_PRINT(sfree(p67););
printStats();
PRINT_POINTER(scalloc(231,28););
printStats();
void* p84 = last_address;
PRINT_POINTER(scalloc(224,247););
printStats();
void* p85 = last_address;
PRINT_POINTER(scalloc(244,215););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p64,36););
printStats();
void* p87 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(srealloc(p34,65););
printStats();
void* p88 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p89 = last_address;
DEBUG_PRINT(sfree(p65););
printStats();
PRINT_POINTER(srealloc(p76,145););
printStats();
void* p90 = last_address;
PRINT_POINTER(srealloc(p88,30););
printStats();
void* p91 = last_address;
PRINT_POINTER(srealloc(p57,225););
printStats();
void* p92 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(smalloc(142););
printStats();
void* p93 = last_address;
PRINT_POINTER(srealloc(p51,27););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p95 = last_address;
PRINT_POINTER(srealloc(p70,124););
printStats();
void* p96 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p97 = last_address;
PRINT_POINTER(srealloc(p85,86););
printStats();
void* p98 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p99 = last_address;
PRINT_POINTER(srealloc(p96,220););
printStats();
void* p100 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(smalloc(182););
printStats();
void* p101 = last_address;
PRINT_POINTER(scalloc(133,133););
printStats();
void* p102 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(srealloc(p86,239););
printStats();
void* p103 = last_address;
DEBUG_PRINT(sfree(p54););
printStats();
DEBUG_PRINT(sfree(p73););
printStats();
DEBUG_PRINT(sfree(p79););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p104 = last_address;
PRINT_POINTER(srealloc(p99,133););
printStats();
void* p105 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p106 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p107 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p108 = last_address;
PRINT_POINTER(srealloc(p108,16););
printStats();
void* p109 = last_address;
PRINT_POINTER(scalloc(63,95););
printStats();
void* p110 = last_address;
DEBUG_PRINT(sfree(p107););
printStats();
PRINT_POINTER(srealloc(p90,115););
printStats();
void* p111 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
DEBUG_PRINT(sfree(p23););
printStats();
PRINT_POINTER(srealloc(p71,173););
printStats();
void* p112 = last_address;
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(scalloc(177,186););
printStats();
void* p113 = last_address;
PRINT_POINTER(scalloc(31,99););
printStats();
void* p114 = last_address;
PRINT_POINTER(scalloc(27,21););
printStats();
void* p115 = last_address;
PRINT_POINTER(scalloc(113,103););
printStats();
void* p116 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(smalloc(241););
printStats();
void* p117 = last_address;
PRINT_POINTER(srealloc(p116,177););
printStats();
void* p118 = last_address;
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(scalloc(115,151););
printStats();
void* p119 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p120 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(srealloc(p104,193););
printStats();
void* p121 = last_address;
PRINT_POINTER(scalloc(147,233););
printStats();
void* p122 = last_address;
PRINT_POINTER(srealloc(p117,62););
printStats();
void* p123 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
DEBUG_PRINT(sfree(p37););
printStats();
DEBUG_PRINT(sfree(p115););
printStats();
PRINT_POINTER(smalloc(26););
printStats();
void* p124 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p125 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
PRINT_POINTER(smalloc(221););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(246,1););
printStats();
void* p127 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p128 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p129 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p130 = last_address;
PRINT_POINTER(srealloc(p84,134););
printStats();
void* p131 = last_address;
PRINT_POINTER(scalloc(172,16););
printStats();
void* p132 = last_address;
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(smalloc(39););
printStats();
void* p133 = last_address;
PRINT_POINTER(srealloc(p131,208););
printStats();
void* p134 = last_address;
DEBUG_PRINT(sfree(p129););
printStats();
PRINT_POINTER(smalloc(163););
printStats();
void* p135 = last_address;
PRINT_POINTER(scalloc(124,16););
printStats();
void* p136 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p137 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p138 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
PRINT_POINTER(scalloc(145,196););
printStats();
void* p139 = last_address;
PRINT_POINTER(srealloc(p121,27););
printStats();
void* p140 = last_address;
PRINT_POINTER(srealloc(p28,79););
printStats();
void* p141 = last_address;
DEBUG_PRINT(sfree(p92););
printStats();
PRINT_POINTER(scalloc(106,10););
printStats();
void* p142 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p143 = last_address;
PRINT_POINTER(srealloc(p126,92););
printStats();
void* p144 = last_address;
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(smalloc(26););
printStats();
void* p145 = last_address;
DEBUG_PRINT(sfree(p83););
printStats();
DEBUG_PRINT(sfree(p128););
printStats();
PRINT_POINTER(smalloc(11););
printStats();
void* p146 = last_address;
PRINT_POINTER(srealloc(p68,13););
printStats();
void* p147 = last_address;
PRINT_POINTER(srealloc(p93,166););
printStats();
void* p148 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p149 = last_address;
PRINT_POINTER(srealloc(p123,151););
printStats();
void* p150 = last_address;
PRINT_POINTER(scalloc(199,133););
printStats();
void* p151 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p152 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(210,229););
printStats();
void* p154 = last_address;
PRINT_POINTER(scalloc(133,29););
printStats();
void* p155 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
PRINT_POINTER(scalloc(119,201););
printStats();
void* p156 = last_address;
PRINT_POINTER(scalloc(185,118););
printStats();
void* p157 = last_address;
PRINT_POINTER(scalloc(247,187););
printStats();
void* p158 = last_address;
PRINT_POINTER(srealloc(p100,195););
printStats();
void* p159 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p160 = last_address;
DEBUG_PRINT(sfree(p66););
printStats();
PRINT_POINTER(smalloc(36););
printStats();
void* p161 = last_address;
DEBUG_PRINT(sfree(p140););
printStats();
PRINT_POINTER(srealloc(p139,249););
printStats();
void* p162 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p163 = last_address;
DEBUG_PRINT(sfree(p95););
printStats();
PRINT_POINTER(scalloc(32,62););
printStats();
void* p164 = last_address;
PRINT_POINTER(srealloc(p161,202););
printStats();
void* p165 = last_address;
PRINT_POINTER(scalloc(99,190););
printStats();
void* p166 = last_address;
PRINT_POINTER(scalloc(38,193););
printStats();
void* p167 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p168 = last_address;
DEBUG_PRINT(sfree(p156););
printStats();
PRINT_POINTER(scalloc(166,113););
printStats();
void* p169 = last_address;
PRINT_POINTER(srealloc(p80,213););
printStats();
void* p170 = last_address;
DEBUG_PRINT(sfree(p112););
printStats();
PRINT_POINTER(scalloc(88,53););
printStats();
void* p171 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p172 = last_address;
PRINT_POINTER(scalloc(179,111););
printStats();
void* p173 = last_address;
DEBUG_PRINT(sfree(p122););
printStats();
PRINT_POINTER(smalloc(215););
printStats();
void* p174 = last_address;
PRINT_POINTER(scalloc(37,72););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p168););
printStats();
DEBUG_PRINT(sfree(p110););
printStats();
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(scalloc(157,184););
printStats();
void* p176 = last_address;
DEBUG_PRINT(sfree(p164););
printStats();
PRINT_POINTER(srealloc(p137,132););
printStats();
void* p177 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p178 = last_address;
PRINT_POINTER(scalloc(64,246););
printStats();
void* p179 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p180 = last_address;
PRINT_POINTER(srealloc(p81,182););
printStats();
void* p181 = last_address;
PRINT_POINTER(scalloc(138,177););
printStats();
void* p182 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p183 = last_address;
PRINT_POINTER(srealloc(p180,72););
printStats();
void* p184 = last_address;
PRINT_POINTER(scalloc(94,121););
printStats();
void* p185 = last_address;
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(srealloc(p101,90););
printStats();
void* p186 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p187 = last_address;
PRINT_POINTER(scalloc(83,214););
printStats();
void* p188 = last_address;
DEBUG_PRINT(sfree(p135););
printStats();
DEBUG_PRINT(sfree(p155););
printStats();
PRINT_POINTER(smalloc(195););
printStats();
void* p189 = last_address;
PRINT_POINTER(srealloc(p153,245););
printStats();
void* p190 = last_address;
PRINT_POINTER(srealloc(p143,196););
printStats();
void* p191 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p192 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p193 = last_address;
PRINT_POINTER(scalloc(197,17););
printStats();
void* p194 = last_address;
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(scalloc(11,11););
printStats();
void* p195 = last_address;
PRINT_POINTER(scalloc(247,197););
printStats();
void* p196 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p197 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p198 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p199 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(scalloc(198,115););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p193,83););
printStats();
void* p201 = last_address;
DEBUG_PRINT(sfree(p136););
printStats();
PRINT_POINTER(srealloc(p105,25););
printStats();
void* p202 = last_address;
DEBUG_PRINT(sfree(p179););
printStats();
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(srealloc(p198,101););
printStats();
void* p203 = last_address;
PRINT_POINTER(scalloc(83,135););
printStats();
void* p204 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p205 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p206 = last_address;
DEBUG_PRINT(sfree(p162););
printStats();
DEBUG_PRINT(sfree(p194););
printStats();
DEBUG_PRINT(sfree(p138););
printStats();
PRINT_POINTER(smalloc(93););
printStats();
void* p207 = last_address;
PRINT_POINTER(srealloc(p205,99););
printStats();
void* p208 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(smalloc(155););
printStats();
void* p209 = last_address;
PRINT_POINTER(srealloc(p82,93););
printStats();
void* p210 = last_address;
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(smalloc(26););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(114,128););
printStats();
void* p212 = last_address;
DEBUG_PRINT(sfree(p190););
printStats();
PRINT_POINTER(scalloc(134,213););
printStats();
void* p213 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p214 = last_address;
PRINT_POINTER(scalloc(108,223););
printStats();
void* p215 = last_address;
DEBUG_PRINT(sfree(p208););
printStats();
PRINT_POINTER(scalloc(206,217););
printStats();
void* p216 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p217 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p218 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
DEBUG_PRINT(sfree(p144););
printStats();
DEBUG_PRINT(sfree(p183););
printStats();
PRINT_POINTER(scalloc(218,234););
printStats();
void* p219 = last_address;
DEBUG_PRINT(sfree(p103););
printStats();
DEBUG_PRINT(sfree(p133););
printStats();
PRINT_POINTER(scalloc(77,231););
printStats();
void* p220 = last_address;
PRINT_POINTER(srealloc(p192,209););
printStats();
void* p221 = last_address;
PRINT_POINTER(srealloc(p218,118););
printStats();
void* p222 = last_address;
PRINT_POINTER(srealloc(p200,71););
printStats();
void* p223 = last_address;
PRINT_POINTER(srealloc(p212,155););
printStats();
void* p224 = last_address;
PRINT_POINTER(srealloc(p87,44););
printStats();
void* p225 = last_address;
PRINT_POINTER(srealloc(p223,88););
printStats();
void* p226 = last_address;
PRINT_POINTER(srealloc(p207,32););
printStats();
void* p227 = last_address;
PRINT_POINTER(scalloc(153,237););
printStats();
void* p228 = last_address;
PRINT_POINTER(scalloc(33,247););
printStats();
void* p229 = last_address;
PRINT_POINTER(scalloc(88,1););
printStats();
void* p230 = last_address;
PRINT_POINTER(srealloc(p177,34););
printStats();
void* p231 = last_address;
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(scalloc(162,110););
printStats();
void* p232 = last_address;
DEBUG_PRINT(sfree(p158););
printStats();
PRINT_POINTER(smalloc(19););
printStats();
void* p233 = last_address;
DEBUG_PRINT(sfree(p48););
printStats();
PRINT_POINTER(srealloc(p222,81););
printStats();
void* p234 = last_address;
DEBUG_PRINT(sfree(p216););
printStats();
PRINT_POINTER(scalloc(230,205););
printStats();
void* p235 = last_address;
PRINT_POINTER(srealloc(p188,198););
printStats();
void* p236 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p237 = last_address;
DEBUG_PRINT(sfree(p167););
printStats();
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(scalloc(88,69););
printStats();
void* p238 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p239 = last_address;
PRINT_POINTER(scalloc(162,180););
printStats();
void* p240 = last_address;
DEBUG_PRINT(sfree(p240););
printStats();
PRINT_POINTER(srealloc(p175,99););
printStats();
void* p241 = last_address;
PRINT_POINTER(srealloc(p106,139););
printStats();
void* p242 = last_address;
PRINT_POINTER(srealloc(p151,132););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(srealloc(p237,20););
printStats();
void* p244 = last_address;
DEBUG_PRINT(sfree(p224););
printStats();
PRINT_POINTER(srealloc(p132,78););
printStats();
void* p245 = last_address;
PRINT_POINTER(scalloc(190,32););
printStats();
void* p246 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p247 = last_address;
PRINT_POINTER(srealloc(p226,165););
printStats();
void* p248 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
PRINT_POINTER(scalloc(169,37););
printStats();
void* p249 = last_address;
DEBUG_PRINT(sfree(p195););
printStats();
PRINT_POINTER(scalloc(107,83););
printStats();
void* p250 = last_address;
DEBUG_PRINT(sfree(p230););
printStats();
PRINT_POINTER(scalloc(115,168););
printStats();
void* p251 = last_address;
DEBUG_PRINT(sfree(p74););
printStats();
PRINT_POINTER(scalloc(212,108););
printStats();
void* p252 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p253 = last_address;
PRINT_POINTER(srealloc(p244,135););
printStats();
void* p254 = last_address;
PRINT_POINTER(scalloc(113,57););
printStats();
void* p255 = last_address;
PRINT_POINTER(scalloc(61,147););
printStats();
void* p256 = last_address;
DEBUG_PRINT(sfree(p182););
printStats();
DEBUG_PRINT(sfree(p219););
printStats();
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(smalloc(241););
printStats();
void* p257 = last_address;
PRINT_POINTER(srealloc(p206,170););
printStats();
void* p258 = last_address;
PRINT_POINTER(scalloc(100,193););
printStats();
void* p259 = last_address;
PRINT_POINTER(scalloc(210,218););
printStats();
void* p260 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p261 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p262 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(scalloc(213,178););
printStats();
void* p263 = last_address;
PRINT_POINTER(scalloc(34,186););
printStats();
void* p264 = last_address;
PRINT_POINTER(srealloc(p169,1););
printStats();
void* p265 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p266 = last_address;
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(srealloc(p256,205););
printStats();
void* p267 = last_address;
PRINT_POINTER(srealloc(p259,100););
printStats();
void* p268 = last_address;
PRINT_POINTER(scalloc(239,128););
printStats();
void* p269 = last_address;
PRINT_POINTER(srealloc(p173,25););
printStats();
void* p270 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p271 = last_address;
PRINT_POINTER(srealloc(p154,11););
printStats();
void* p272 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p273 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p274 = last_address;
PRINT_POINTER(scalloc(186,35););
printStats();
void* p275 = last_address;
PRINT_POINTER(srealloc(p275,54););
printStats();
void* p276 = last_address;
DEBUG_PRINT(sfree(p189););
printStats();
PRINT_POINTER(srealloc(p191,164););
printStats();
void* p277 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
PRINT_POINTER(scalloc(2,66););
printStats();
void* p278 = last_address;
PRINT_POINTER(srealloc(p184,8););
printStats();
void* p279 = last_address;
PRINT_POINTER(srealloc(p204,237););
printStats();
void* p280 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p281 = last_address;
PRINT_POINTER(scalloc(240,45););
printStats();
void* p282 = last_address;
DEBUG_PRINT(sfree(p130););
printStats();
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(srealloc(p261,94););
printStats();
void* p283 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p281,222););
printStats();
void* p285 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p286 = last_address;
PRINT_POINTER(srealloc(p270,102););
printStats();
void* p287 = last_address;
PRINT_POINTER(srealloc(p174,56););
printStats();
void* p288 = last_address;
PRINT_POINTER(scalloc(142,219););
printStats();
void* p289 = last_address;
PRINT_POINTER(scalloc(219,29););
printStats();
void* p290 = last_address;
PRINT_POINTER(srealloc(p260,121););
printStats();
void* p291 = last_address;
PRINT_POINTER(srealloc(p257,67););
printStats();
void* p292 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p293 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p294 = last_address;
PRINT_POINTER(srealloc(p196,16););
printStats();
void* p295 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p296 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p297 = last_address;
PRINT_POINTER(srealloc(p276,88););
printStats();
void* p298 = last_address;
DEBUG_PRINT(sfree(p172););
printStats();
PRINT_POINTER(srealloc(p157,190););
printStats();
void* p299 = last_address;
DEBUG_PRINT(sfree(p202););
printStats();
PRINT_POINTER(srealloc(p290,98););
printStats();
void* p300 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p302 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p303 = last_address;
PRINT_POINTER(srealloc(p251,1););
printStats();
void* p304 = last_address;
PRINT_POINTER(srealloc(p292,37););
printStats();
void* p305 = last_address;
PRINT_POINTER(scalloc(120,28););
printStats();
void* p306 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p307 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p308 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p309 = last_address;
PRINT_POINTER(scalloc(139,130););
printStats();
void* p310 = last_address;
PRINT_POINTER(scalloc(101,15););
printStats();
void* p311 = last_address;
PRINT_POINTER(scalloc(203,197););
printStats();
void* p312 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p313 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p314 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p315 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p316 = last_address;
DEBUG_PRINT(sfree(p306););
printStats();
PRINT_POINTER(scalloc(88,145););
printStats();
void* p317 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p318 = last_address;
PRINT_POINTER(srealloc(p296,40););
printStats();
void* p319 = last_address;
DEBUG_PRINT(sfree(p266););
printStats();
PRINT_POINTER(scalloc(41,20););
printStats();
void* p320 = last_address;
PRINT_POINTER(srealloc(p288,224););
printStats();
void* p321 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p322 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p323 = last_address;
PRINT_POINTER(srealloc(p228,182););
printStats();
void* p324 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p325 = last_address;
PRINT_POINTER(srealloc(p25,191););
printStats();
void* p326 = last_address;
PRINT_POINTER(scalloc(7,44););
printStats();
void* p327 = last_address;
DEBUG_PRINT(sfree(p163););
printStats();
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(scalloc(176,118););
printStats();
void* p328 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p329 = last_address;
PRINT_POINTER(srealloc(p319,93););
printStats();
void* p330 = last_address;
PRINT_POINTER(scalloc(107,225););
printStats();
void* p331 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p332 = last_address;
DEBUG_PRINT(sfree(p185););
printStats();
PRINT_POINTER(smalloc(89););
printStats();
void* p333 = last_address;
PRINT_POINTER(scalloc(39,71););
printStats();
void* p334 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p335 = last_address;
PRINT_POINTER(scalloc(114,234););
printStats();
void* p336 = last_address;
PRINT_POINTER(srealloc(p111,173););
printStats();
void* p337 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(scalloc(18,82););
printStats();
void* p338 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p339 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p340 = last_address;
PRINT_POINTER(srealloc(p298,41););
printStats();
void* p341 = last_address;
PRINT_POINTER(srealloc(p331,119););
printStats();
void* p342 = last_address;
DEBUG_PRINT(sfree(p309););
printStats();
PRINT_POINTER(scalloc(145,219););
printStats();
void* p343 = last_address;
PRINT_POINTER(scalloc(5,205););
printStats();
void* p344 = last_address;
PRINT_POINTER(srealloc(p337,117););
printStats();
void* p345 = last_address;
PRINT_POINTER(srealloc(p307,84););
printStats();
void* p346 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p347 = last_address;
DEBUG_PRINT(sfree(p293););
printStats();
PRINT_POINTER(smalloc(101););
printStats();
void* p348 = last_address;
DEBUG_PRINT(sfree(p78););
printStats();
DEBUG_PRINT(sfree(p334););
printStats();
PRINT_POINTER(scalloc(123,231););
printStats();
void* p349 = last_address;
PRINT_POINTER(scalloc(179,186););
printStats();
void* p350 = last_address;
DEBUG_PRINT(sfree(p287););
printStats();
PRINT_POINTER(scalloc(36,146););
printStats();
void* p351 = last_address;
PRINT_POINTER(srealloc(p295,28););
printStats();
void* p352 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p353 = last_address;
DEBUG_PRINT(sfree(p286););
printStats();
DEBUG_PRINT(sfree(p213););
printStats();
DEBUG_PRINT(sfree(p280););
printStats();
PRINT_POINTER(srealloc(p336,146););
printStats();
void* p354 = last_address;
PRINT_POINTER(srealloc(p324,140););
printStats();
void* p355 = last_address;
PRINT_POINTER(srealloc(p278,151););
printStats();
void* p356 = last_address;
DEBUG_PRINT(sfree(p344););
printStats();
PRINT_POINTER(scalloc(45,96););
printStats();
void* p357 = last_address;
PRINT_POINTER(scalloc(154,26););
printStats();
void* p358 = last_address;
DEBUG_PRINT(sfree(p352););
printStats();
DEBUG_PRINT(sfree(p234););
printStats();
PRINT_POINTER(srealloc(p325,69););
printStats();
void* p359 = last_address;
PRINT_POINTER(scalloc(188,116););
printStats();
void* p360 = last_address;
DEBUG_PRINT(sfree(p273););
printStats();
PRINT_POINTER(scalloc(29,171););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(221););
printStats();
void* p362 = last_address;
DEBUG_PRINT(sfree(p171););
printStats();
DEBUG_PRINT(sfree(p221););
printStats();
DEBUG_PRINT(sfree(p269););
printStats();
PRINT_POINTER(smalloc(192););
printStats();
void* p363 = last_address;
PRINT_POINTER(srealloc(p340,211););
printStats();
void* p364 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p365 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
PRINT_POINTER(scalloc(113,20););
printStats();
void* p366 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p367 = last_address;
PRINT_POINTER(scalloc(36,25););
printStats();
void* p368 = last_address;
PRINT_POINTER(scalloc(12,3););
printStats();
void* p369 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p370 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p371 = last_address;
PRINT_POINTER(srealloc(p233,109););
printStats();
void* p372 = last_address;
PRINT_POINTER(scalloc(146,86););
printStats();
void* p373 = last_address;
DEBUG_PRINT(sfree(p366););
printStats();
DEBUG_PRINT(sfree(p301););
printStats();
DEBUG_PRINT(sfree(p285););
printStats();
PRINT_POINTER(smalloc(236););
printStats();
void* p374 = last_address;
PRINT_POINTER(scalloc(93,205););
printStats();
void* p375 = last_address;
PRINT_POINTER(srealloc(p367,33););
printStats();
void* p376 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(scalloc(15,153););
printStats();
void* p377 = last_address;
PRINT_POINTER(srealloc(p374,127););
printStats();
void* p378 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p379 = last_address;
PRINT_POINTER(scalloc(101,181););
printStats();
void* p380 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p381 = last_address;
PRINT_POINTER(srealloc(p335,158););
printStats();
void* p382 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p383 = last_address;
PRINT_POINTER(srealloc(p310,64););
printStats();
void* p384 = last_address;
PRINT_POINTER(srealloc(p215,200););
printStats();
void* p385 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p386 = last_address;
DEBUG_PRINT(sfree(p341););
printStats();
PRINT_POINTER(smalloc(94););
printStats();
void* p387 = last_address;
PRINT_POINTER(srealloc(p376,109););
printStats();
void* p388 = last_address;
PRINT_POINTER(srealloc(p348,94););
printStats();
void* p389 = last_address;
PRINT_POINTER(srealloc(p381,93););
printStats();
void* p390 = last_address;
PRINT_POINTER(scalloc(204,214););
printStats();
void* p391 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p392 = last_address;
PRINT_POINTER(srealloc(p357,201););
printStats();
void* p393 = last_address;
DEBUG_PRINT(sfree(p345););
printStats();
PRINT_POINTER(smalloc(137););
printStats();
void* p394 = last_address;
PRINT_POINTER(scalloc(150,84););
printStats();
void* p395 = last_address;
DEBUG_PRINT(sfree(p364););
printStats();
DEBUG_PRINT(sfree(p369););
printStats();
PRINT_POINTER(srealloc(p368,158););
printStats();
void* p396 = last_address;
PRINT_POINTER(scalloc(193,238););
printStats();
void* p397 = last_address;
PRINT_POINTER(srealloc(p372,201););
printStats();
void* p398 = last_address;
PRINT_POINTER(srealloc(p388,77););
printStats();
void* p399 = last_address;
DEBUG_PRINT(sfree(p245););
printStats();
PRINT_POINTER(smalloc(60););
printStats();
void* p400 = last_address;
PRINT_POINTER(srealloc(p284,129););
printStats();
void* p401 = last_address;
PRINT_POINTER(srealloc(p178,91););
printStats();
void* p402 = last_address;
PRINT_POINTER(scalloc(20,248););
printStats();
void* p403 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p404 = last_address;
PRINT_POINTER(scalloc(76,24););
printStats();
void* p405 = last_address;
DEBUG_PRINT(sfree(p397););
printStats();
PRINT_POINTER(scalloc(217,102););
printStats();
void* p406 = last_address;
PRINT_POINTER(srealloc(p347,93););
printStats();
void* p407 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p408 = last_address;
DEBUG_PRINT(sfree(p399););
printStats();
DEBUG_PRINT(sfree(p262););
printStats();
DEBUG_PRINT(sfree(p283););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p409 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p410 = last_address;
PRINT_POINTER(srealloc(p291,67););
printStats();
void* p411 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p412 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p413 = last_address;
PRINT_POINTER(srealloc(p313,192););
printStats();
void* p414 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p415 = last_address;
PRINT_POINTER(srealloc(p370,165););
printStats();
void* p416 = last_address;
DEBUG_PRINT(sfree(p398););
printStats();
PRINT_POINTER(smalloc(205););
printStats();
void* p417 = last_address;
PRINT_POINTER(srealloc(p342,81););
printStats();
void* p418 = last_address;
PRINT_POINTER(scalloc(75,234););
printStats();
void* p419 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p420 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p421 = last_address;
PRINT_POINTER(srealloc(p387,127););
printStats();
void* p422 = last_address;
PRINT_POINTER(scalloc(235,114););
printStats();
void* p423 = last_address;
PRINT_POINTER(scalloc(165,52););
printStats();
void* p424 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p425 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p426 = last_address;
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(smalloc(118););
printStats();
void* p427 = last_address;
PRINT_POINTER(scalloc(62,157););
printStats();
void* p428 = last_address;
DEBUG_PRINT(sfree(p330););
printStats();
PRINT_POINTER(smalloc(124););
printStats();
void* p429 = last_address;
PRINT_POINTER(scalloc(193,78););
printStats();
void* p430 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p431 = last_address;
PRINT_POINTER(scalloc(153,186););
printStats();
void* p432 = last_address;
PRINT_POINTER(scalloc(87,206););
printStats();
void* p433 = last_address;
DEBUG_PRINT(sfree(p363););
printStats();
PRINT_POINTER(smalloc(142););
printStats();
void* p434 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p435 = last_address;
PRINT_POINTER(scalloc(163,240););
printStats();
void* p436 = last_address;
PRINT_POINTER(srealloc(p351,121););
printStats();
void* p437 = last_address;
PRINT_POINTER(scalloc(249,52););
printStats();
void* p438 = last_address;
PRINT_POINTER(scalloc(180,39););
printStats();
void* p439 = last_address;
PRINT_POINTER(scalloc(75,27););
printStats();
void* p440 = last_address;
PRINT_POINTER(srealloc(p145,191););
printStats();
void* p441 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p442 = last_address;
PRINT_POINTER(scalloc(172,226););
printStats();
void* p443 = last_address;
PRINT_POINTER(srealloc(p350,175););
printStats();
void* p444 = last_address;
DEBUG_PRINT(sfree(p225););
printStats();
PRINT_POINTER(scalloc(118,111););
printStats();
void* p445 = last_address;
DEBUG_PRINT(sfree(p120););
printStats();
PRINT_POINTER(scalloc(144,213););
printStats();
void* p446 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p447 = last_address;
DEBUG_PRINT(sfree(p289););
printStats();
DEBUG_PRINT(sfree(p210););
printStats();
DEBUG_PRINT(sfree(p423););
printStats();
DEBUG_PRINT(sfree(p380););
printStats();
DEBUG_PRINT(sfree(p201););
printStats();
PRINT_POINTER(srealloc(p318,149););
printStats();
void* p448 = last_address;
PRINT_POINTER(scalloc(100,25););
printStats();
void* p449 = last_address;
DEBUG_PRINT(sfree(p391););
printStats();
PRINT_POINTER(srealloc(p339,12););
printStats();
void* p450 = last_address;
DEBUG_PRINT(sfree(p411););
printStats();
PRINT_POINTER(scalloc(169,183););
printStats();
void* p451 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p452 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p453 = last_address;
PRINT_POINTER(srealloc(p271,106););
printStats();
void* p454 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p455 = last_address;
DEBUG_PRINT(sfree(p265););
printStats();
PRINT_POINTER(scalloc(232,16););
printStats();
void* p456 = last_address;
PRINT_POINTER(srealloc(p445,183););
printStats();
void* p457 = last_address;
PRINT_POINTER(srealloc(p326,235););
printStats();
void* p458 = last_address;
DEBUG_PRINT(sfree(p252););
printStats();
PRINT_POINTER(scalloc(225,170););
printStats();
void* p459 = last_address;
DEBUG_PRINT(sfree(p232););
printStats();
PRINT_POINTER(srealloc(p441,26););
printStats();
void* p460 = last_address;
PRINT_POINTER(srealloc(p400,96););
printStats();
void* p461 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p462 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p463 = last_address;
DEBUG_PRINT(sfree(p315););
printStats();
PRINT_POINTER(scalloc(237,129););
printStats();
void* p464 = last_address;
PRINT_POINTER(scalloc(130,217););
printStats();
void* p465 = last_address;
PRINT_POINTER(scalloc(174,170););
printStats();
void* p466 = last_address;
DEBUG_PRINT(sfree(p241););
printStats();
PRINT_POINTER(smalloc(8););
printStats();
void* p467 = last_address;
DEBUG_PRINT(sfree(p425););
printStats();
DEBUG_PRINT(sfree(p440););
printStats();
PRINT_POINTER(scalloc(63,74););
printStats();
void* p468 = last_address;
DEBUG_PRINT(sfree(p247););
printStats();
PRINT_POINTER(srealloc(p267,178););
printStats();
void* p469 = last_address;
PRINT_POINTER(scalloc(154,241););
printStats();
void* p470 = last_address;
DEBUG_PRINT(sfree(p302););
printStats();
PRINT_POINTER(srealloc(p379,185););
printStats();
void* p471 = last_address;
PRINT_POINTER(scalloc(231,247););
printStats();
void* p472 = last_address;
PRINT_POINTER(scalloc(185,229););
printStats();
void* p473 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p474 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p475 = last_address;
DEBUG_PRINT(sfree(p435););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p476 = last_address;
PRINT_POINTER(srealloc(p417,41););
printStats();
void* p477 = last_address;
DEBUG_PRINT(sfree(p404););
printStats();
PRINT_POINTER(smalloc(173););
printStats();
void* p478 = last_address;
PRINT_POINTER(srealloc(p321,64););
printStats();
void* p479 = last_address;
PRINT_POINTER(scalloc(181,49););
printStats();
void* p480 = last_address;
PRINT_POINTER(scalloc(111,198););
printStats();
void* p481 = last_address;
PRINT_POINTER(scalloc(59,159););
printStats();
void* p482 = last_address;
PRINT_POINTER(scalloc(164,247););
printStats();
void* p483 = last_address;
PRINT_POINTER(srealloc(p390,22););
printStats();
void* p484 = last_address;
PRINT_POINTER(srealloc(p297,6););
printStats();
void* p485 = last_address;
PRINT_POINTER(srealloc(p439,200););
printStats();
void* p486 = last_address;
PRINT_POINTER(scalloc(178,200););
printStats();
void* p487 = last_address;
DEBUG_PRINT(sfree(p328););
printStats();
PRINT_POINTER(srealloc(p312,7););
printStats();
void* p488 = last_address;
PRINT_POINTER(scalloc(12,207););
printStats();
void* p489 = last_address;
PRINT_POINTER(srealloc(p447,11););
printStats();
void* p490 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p491 = last_address;
DEBUG_PRINT(sfree(p463););
printStats();
PRINT_POINTER(scalloc(247,163););
printStats();
void* p492 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p493 = last_address;
DEBUG_PRINT(sfree(p444););
printStats();
DEBUG_PRINT(sfree(p432););
printStats();
DEBUG_PRINT(sfree(p211););
printStats();
DEBUG_PRINT(sfree(p433););
printStats();
PRINT_POINTER(smalloc(145););
printStats();
void* p494 = last_address;
PRINT_POINTER(scalloc(216,2););
printStats();
void* p495 = last_address;
PRINT_POINTER(scalloc(84,33););
printStats();
void* p496 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p497 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p498 = last_address;
PRINT_POINTER(scalloc(207,93););
printStats();
void* p499 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p500 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p501 = last_address;
PRINT_POINTER(scalloc(51,17););
printStats();
void* p502 = last_address;
PRINT_POINTER(srealloc(p254,82););
printStats();
void* p503 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p504 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p505 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p506 = last_address;
DEBUG_PRINT(sfree(p361););
printStats();
PRINT_POINTER(scalloc(201,8););
printStats();
void* p507 = last_address;
PRINT_POINTER(scalloc(44,1););
printStats();
void* p508 = last_address;
PRINT_POINTER(scalloc(110,172););
printStats();
void* p509 = last_address;
PRINT_POINTER(scalloc(203,111););
printStats();
void* p510 = last_address;
DEBUG_PRINT(sfree(p355););
printStats();
PRINT_POINTER(smalloc(84););
printStats();
void* p511 = last_address;
DEBUG_PRINT(sfree(p305););
printStats();
DEBUG_PRINT(sfree(p327););
printStats();
PRINT_POINTER(srealloc(p406,238););
printStats();
void* p512 = last_address;
DEBUG_PRINT(sfree(p356););
printStats();
PRINT_POINTER(srealloc(p502,115););
printStats();
void* p513 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p514 = last_address;
DEBUG_PRINT(sfree(p481););
printStats();
PRINT_POINTER(smalloc(244););
printStats();
void* p515 = last_address;
DEBUG_PRINT(sfree(p165););
printStats();
PRINT_POINTER(scalloc(186,69););
printStats();
void* p516 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p517 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p518 = last_address;
PRINT_POINTER(srealloc(p505,175););
printStats();
void* p519 = last_address;
PRINT_POINTER(srealloc(p474,225););
printStats();
void* p520 = last_address;
DEBUG_PRINT(sfree(p424););
printStats();
DEBUG_PRINT(sfree(p428););
printStats();
PRINT_POINTER(srealloc(p490,229););
printStats();
void* p521 = last_address;
DEBUG_PRINT(sfree(p299););
printStats();
DEBUG_PRINT(sfree(p454););
printStats();
PRINT_POINTER(smalloc(215););
printStats();
void* p522 = last_address;
PRINT_POINTER(scalloc(241,102););
printStats();
void* p523 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p524 = last_address;
DEBUG_PRINT(sfree(p393););
printStats();
PRINT_POINTER(smalloc(248););
printStats();
void* p525 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p526 = last_address;
DEBUG_PRINT(sfree(p486););
printStats();
PRINT_POINTER(srealloc(p518,70););
printStats();
void* p527 = last_address;
DEBUG_PRINT(sfree(p452););
printStats();
DEBUG_PRINT(sfree(p300););
printStats();
PRINT_POINTER(srealloc(p343,48););
printStats();
void* p528 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p529 = last_address;
PRINT_POINTER(srealloc(p258,2););
printStats();
void* p530 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p531 = last_address;
DEBUG_PRINT(sfree(p462););
printStats();
DEBUG_PRINT(sfree(p457););
printStats();
PRINT_POINTER(srealloc(p437,64););
printStats();
void* p532 = last_address;
DEBUG_PRINT(sfree(p421););
printStats();
PRINT_POINTER(srealloc(p385,222););
printStats();
void* p533 = last_address;
DEBUG_PRINT(sfree(p396););
printStats();
DEBUG_PRINT(sfree(p496););
printStats();
DEBUG_PRINT(sfree(p365););
printStats();
DEBUG_PRINT(sfree(p450););
printStats();
PRINT_POINTER(scalloc(86,159););
printStats();
void* p534 = last_address;
DEBUG_PRINT(sfree(p362););
printStats();
PRINT_POINTER(smalloc(192););
printStats();
void* p535 = last_address;
PRINT_POINTER(scalloc(184,171););
printStats();
void* p536 = last_address;
PRINT_POINTER(srealloc(p401,210););
printStats();
void* p537 = last_address;
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(scalloc(188,41););
printStats();
void* p538 = last_address;
DEBUG_PRINT(sfree(p408););
printStats();
PRINT_POINTER(smalloc(1););
printStats();
void* p539 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p540 = last_address;
DEBUG_PRINT(sfree(p478););
printStats();
PRINT_POINTER(scalloc(202,52););
printStats();
void* p541 = last_address;
PRINT_POINTER(scalloc(147,208););
printStats();
void* p542 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p543 = last_address;
DEBUG_PRINT(sfree(p419););
printStats();
DEBUG_PRINT(sfree(p243););
printStats();
PRINT_POINTER(scalloc(165,193););
printStats();
void* p544 = last_address;
DEBUG_PRINT(sfree(p303););
printStats();
DEBUG_PRINT(sfree(p227););
printStats();
DEBUG_PRINT(sfree(p217););
printStats();
PRINT_POINTER(smalloc(9););
printStats();
void* p545 = last_address;
PRINT_POINTER(srealloc(p203,191););
printStats();
void* p546 = last_address;
PRINT_POINTER(scalloc(142,137););
printStats();
void* p547 = last_address;
PRINT_POINTER(scalloc(56,91););
printStats();
void* p548 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p549 = last_address;
PRINT_POINTER(srealloc(p543,17););
printStats();
void* p550 = last_address;
PRINT_POINTER(scalloc(24,207););
printStats();
void* p551 = last_address;
PRINT_POINTER(scalloc(60,238););
printStats();
void* p552 = last_address;
DEBUG_PRINT(sfree(p382););
printStats();
PRINT_POINTER(srealloc(p527,40););
printStats();
void* p553 = last_address;
PRINT_POINTER(srealloc(p220,207););
printStats();
void* p554 = last_address;
PRINT_POINTER(scalloc(52,212););
printStats();
void* p555 = last_address;
PRINT_POINTER(srealloc(p415,192););
printStats();
void* p556 = last_address;
PRINT_POINTER(srealloc(p438,205););
printStats();
void* p557 = last_address;
PRINT_POINTER(scalloc(117,12););
printStats();
void* p558 = last_address;
PRINT_POINTER(srealloc(p333,158););
printStats();
void* p559 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p560 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p561 = last_address;
DEBUG_PRINT(sfree(p547););
printStats();
PRINT_POINTER(srealloc(p353,158););
printStats();
void* p562 = last_address;
DEBUG_PRINT(sfree(p239););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p563 = last_address;
PRINT_POINTER(scalloc(227,82););
printStats();
void* p564 = last_address;
DEBUG_PRINT(sfree(p467););
printStats();
PRINT_POINTER(scalloc(228,38););
printStats();
void* p565 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p566 = last_address;
PRINT_POINTER(scalloc(48,120););
printStats();
void* p567 = last_address;
DEBUG_PRINT(sfree(p389););
printStats();
PRINT_POINTER(scalloc(217,47););
printStats();
void* p568 = last_address;
PRINT_POINTER(scalloc(173,166););
printStats();
void* p569 = last_address;
PRINT_POINTER(srealloc(p323,32););
printStats();
void* p570 = last_address;
DEBUG_PRINT(sfree(p282););
printStats();
DEBUG_PRINT(sfree(p494););
printStats();
DEBUG_PRINT(sfree(p359););
printStats();
DEBUG_PRINT(sfree(p409););
printStats();
PRINT_POINTER(srealloc(p384,11););
printStats();
void* p571 = last_address;
DEBUG_PRINT(sfree(p149););
printStats();
PRINT_POINTER(srealloc(p483,51););
printStats();
void* p572 = last_address;
PRINT_POINTER(scalloc(119,209););
printStats();
void* p573 = last_address;
PRINT_POINTER(srealloc(p533,154););
printStats();
void* p574 = last_address;
PRINT_POINTER(scalloc(23,107););
printStats();
void* p575 = last_address;
PRINT_POINTER(srealloc(p532,154););
printStats();
void* p576 = last_address;
DEBUG_PRINT(sfree(p459););
printStats();
PRINT_POINTER(srealloc(p540,182););
printStats();
void* p577 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p578 = last_address;
PRINT_POINTER(scalloc(128,77););
printStats();
void* p579 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p580 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p581 = last_address;
PRINT_POINTER(srealloc(p375,193););
printStats();
void* p582 = last_address;
PRINT_POINTER(scalloc(118,84););
printStats();
void* p583 = last_address;
PRINT_POINTER(srealloc(p277,98););
printStats();
void* p584 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p585 = last_address;
PRINT_POINTER(srealloc(p442,49););
printStats();
void* p586 = last_address;
PRINT_POINTER(srealloc(p554,43););
printStats();
void* p587 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p588 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p589 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p590 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p591 = last_address;
DEBUG_PRINT(sfree(p464););
printStats();
PRINT_POINTER(smalloc(173););
printStats();
void* p592 = last_address;
DEBUG_PRINT(sfree(p422););
printStats();
DEBUG_PRINT(sfree(p473););
printStats();
DEBUG_PRINT(sfree(p246););
printStats();
PRINT_POINTER(smalloc(80););
printStats();
void* p593 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p594 = last_address;
PRINT_POINTER(scalloc(243,159););
printStats();
void* p595 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p596 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p597 = last_address;
DEBUG_PRINT(sfree(p584););
printStats();
PRINT_POINTER(srealloc(p536,33););
printStats();
void* p598 = last_address;
DEBUG_PRINT(sfree(p506););
printStats();
PRINT_POINTER(smalloc(100););
printStats();
void* p599 = last_address;
PRINT_POINTER(scalloc(157,132););
printStats();
void* p600 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p601 = last_address;
DEBUG_PRINT(sfree(p489););
printStats();
PRINT_POINTER(scalloc(100,221););
printStats();
void* p602 = last_address;
DEBUG_PRINT(sfree(p255););
printStats();
PRINT_POINTER(srealloc(p317,124););
printStats();
void* p603 = last_address;
PRINT_POINTER(scalloc(26,244););
printStats();
void* p604 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p605 = last_address;
DEBUG_PRINT(sfree(p349););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p606 = last_address;
DEBUG_PRINT(sfree(p601););
printStats();
PRINT_POINTER(scalloc(123,249););
printStats();
void* p607 = last_address;
DEBUG_PRINT(sfree(p465););
printStats();
PRINT_POINTER(scalloc(104,104););
printStats();
void* p608 = last_address;
PRINT_POINTER(srealloc(p519,197););
printStats();
void* p609 = last_address;
DEBUG_PRINT(sfree(p525););
printStats();
PRINT_POINTER(scalloc(123,54););
printStats();
void* p610 = last_address;
PRINT_POINTER(srealloc(p523,33););
printStats();
void* p611 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p612 = last_address;
DEBUG_PRINT(sfree(p371););
printStats();
PRINT_POINTER(smalloc(7););
printStats();
void* p613 = last_address;
DEBUG_PRINT(sfree(p511););
printStats();
DEBUG_PRINT(sfree(p500););
printStats();
PRINT_POINTER(smalloc(127););
printStats();
void* p614 = last_address;
PRINT_POINTER(scalloc(49,173););
printStats();
void* p615 = last_address;
PRINT_POINTER(scalloc(246,106););
printStats();
void* p616 = last_address;
PRINT_POINTER(srealloc(p509,156););
printStats();
void* p617 = last_address;
PRINT_POINTER(srealloc(p311,102););
printStats();
void* p618 = last_address;
DEBUG_PRINT(sfree(p561););
printStats();
PRINT_POINTER(smalloc(93););
printStats();
void* p619 = last_address;
PRINT_POINTER(srealloc(p565,173););
printStats();
void* p620 = last_address;
PRINT_POINTER(srealloc(p516,15););
printStats();
void* p621 = last_address;
DEBUG_PRINT(sfree(p552););
printStats();
PRINT_POINTER(srealloc(p451,200););
printStats();
void* p622 = last_address;
DEBUG_PRINT(sfree(p484););
printStats();
DEBUG_PRINT(sfree(p542););
printStats();
DEBUG_PRINT(sfree(p521););
printStats();
PRINT_POINTER(smalloc(114););
printStats();
void* p623 = last_address;
PRINT_POINTER(srealloc(p606,8););
printStats();
void* p624 = last_address;
PRINT_POINTER(srealloc(p583,23););
printStats();
void* p625 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p626 = last_address;
PRINT_POINTER(scalloc(49,97););
printStats();
void* p627 = last_address;
PRINT_POINTER(scalloc(122,203););
printStats();
void* p628 = last_address;
PRINT_POINTER(srealloc(p125,21););
printStats();
void* p629 = last_address;
DEBUG_PRINT(sfree(p559););
printStats();
DEBUG_PRINT(sfree(p429););
printStats();
PRINT_POINTER(scalloc(9,193););
printStats();
void* p630 = last_address;
PRINT_POINTER(srealloc(p551,179););
printStats();
void* p631 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p632 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p633 = last_address;
DEBUG_PRINT(sfree(p605););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p634 = last_address;
PRINT_POINTER(scalloc(123,53););
printStats();
void* p635 = last_address;
DEBUG_PRINT(sfree(p495););
printStats();
PRINT_POINTER(scalloc(139,101););
printStats();
void* p636 = last_address;
PRINT_POINTER(scalloc(73,17););
printStats();
void* p637 = last_address;
PRINT_POINTER(scalloc(3,210););
printStats();
void* p638 = last_address;
DEBUG_PRINT(sfree(p529););
printStats();
PRINT_POINTER(smalloc(219););
printStats();
void* p639 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p640 = last_address;
PRINT_POINTER(scalloc(217,64););
printStats();
void* p641 = last_address;
DEBUG_PRINT(sfree(p378););
printStats();
PRINT_POINTER(scalloc(246,158););
printStats();
void* p642 = last_address;
PRINT_POINTER(scalloc(3,129););
printStats();
void* p643 = last_address;
PRINT_POINTER(scalloc(60,72););
printStats();
void* p644 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p645 = last_address;
DEBUG_PRINT(sfree(p624););
printStats();
PRINT_POINTER(smalloc(131););
printStats();
void* p646 = last_address;
PRINT_POINTER(srealloc(p632,144););
printStats();
void* p647 = last_address;
PRINT_POINTER(scalloc(148,78););
printStats();
void* p648 = last_address;
PRINT_POINTER(srealloc(p431,29););
printStats();
void* p649 = last_address;
PRINT_POINTER(srealloc(p238,247););
printStats();
void* p650 = last_address;
DEBUG_PRINT(sfree(p249););
printStats();
PRINT_POINTER(smalloc(149););
printStats();
void* p651 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p652 = last_address;
PRINT_POINTER(srealloc(p253,116););
printStats();
void* p653 = last_address;
DEBUG_PRINT(sfree(p146););
printStats();
PRINT_POINTER(scalloc(193,169););
printStats();
void* p654 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p655 = last_address;
PRINT_POINTER(srealloc(p446,163););
printStats();
void* p656 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p657 = last_address;
PRINT_POINTER(srealloc(p534,107););
printStats();
void* p658 = last_address;
PRINT_POINTER(scalloc(194,62););
printStats();
void* p659 = last_address;
DEBUG_PRINT(sfree(p587););
printStats();
PRINT_POINTER(srealloc(p548,219););
printStats();
void* p660 = last_address;
DEBUG_PRINT(sfree(p553););
printStats();
PRINT_POINTER(srealloc(p410,30););
printStats();
void* p661 = last_address;
PRINT_POINTER(srealloc(p460,125););
printStats();
void* p662 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p663 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p664 = last_address;
DEBUG_PRINT(sfree(p373););
printStats();
PRINT_POINTER(srealloc(p648,60););
printStats();
void* p665 = last_address;
DEBUG_PRINT(sfree(p557););
printStats();
DEBUG_PRINT(sfree(p639););
printStats();
DEBUG_PRINT(sfree(p487););
printStats();
PRINT_POINTER(smalloc(144););
printStats();
void* p666 = last_address;
PRINT_POINTER(srealloc(p475,114););
printStats();
void* p667 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p668 = last_address;
PRINT_POINTER(scalloc(183,101););
printStats();
void* p669 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p670 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p671 = last_address;
DEBUG_PRINT(sfree(p581););
printStats();
PRINT_POINTER(smalloc(244););
printStats();
void* p672 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p673 = last_address;
PRINT_POINTER(scalloc(125,172););
printStats();
void* p674 = last_address;
PRINT_POINTER(srealloc(p405,17););
printStats();
void* p675 = last_address;
PRINT_POINTER(scalloc(153,172););
printStats();
void* p676 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p677 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p678 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p679 = last_address;
PRINT_POINTER(srealloc(p514,51););
printStats();
void* p680 = last_address;
DEBUG_PRINT(sfree(p515););
printStats();
PRINT_POINTER(scalloc(196,82););
printStats();
void* p681 = last_address;
PRINT_POINTER(scalloc(201,163););
printStats();
void* p682 = last_address;
PRINT_POINTER(scalloc(217,88););
printStats();
void* p683 = last_address;
PRINT_POINTER(scalloc(75,222););
printStats();
void* p684 = last_address;
PRINT_POINTER(srealloc(p621,214););
printStats();
void* p685 = last_address;
PRINT_POINTER(srealloc(p662,58););
printStats();
void* p686 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p687 = last_address;
DEBUG_PRINT(sfree(p470););
printStats();
PRINT_POINTER(srealloc(p572,189););
printStats();
void* p688 = last_address;
PRINT_POINTER(smalloc(80););
printStats();
void* p689 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p690 = last_address;
PRINT_POINTER(scalloc(54,3););
printStats();
void* p691 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p692 = last_address;
DEBUG_PRINT(sfree(p620););
printStats();
PRINT_POINTER(smalloc(76););
printStats();
void* p693 = last_address;
PRINT_POINTER(srealloc(p573,151););
printStats();
void* p694 = last_address;
PRINT_POINTER(scalloc(65,79););
printStats();
void* p695 = last_address;
DEBUG_PRINT(sfree(p640););
printStats();
PRINT_POINTER(scalloc(108,82););
printStats();
void* p696 = last_address;
PRINT_POINTER(srealloc(p629,37););
printStats();
void* p697 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p698 = last_address;
PRINT_POINTER(srealloc(p214,21););
printStats();
void* p699 = last_address;
DEBUG_PRINT(sfree(p609););
printStats();
PRINT_POINTER(srealloc(p503,101););
printStats();
void* p700 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p701 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p702 = last_address;
PRINT_POINTER(srealloc(p691,229););
printStats();
void* p703 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p704 = last_address;
PRINT_POINTER(srealloc(p589,159););
printStats();
void* p705 = last_address;
DEBUG_PRINT(sfree(p501););
printStats();
PRINT_POINTER(smalloc(95););
printStats();
void* p706 = last_address;
PRINT_POINTER(srealloc(p160,205););
printStats();
void* p707 = last_address;
DEBUG_PRINT(sfree(p643););
printStats();
DEBUG_PRINT(sfree(p599););
printStats();
PRINT_POINTER(smalloc(237););
printStats();
void* p708 = last_address;
PRINT_POINTER(srealloc(p420,197););
printStats();
void* p709 = last_address;
PRINT_POINTER(srealloc(p528,169););
printStats();
void* p710 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p711 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p712 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p713 = last_address;
PRINT_POINTER(srealloc(p242,85););
printStats();
void* p714 = last_address;
PRINT_POINTER(srealloc(p426,46););
printStats();
void* p715 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p716 = last_address;
PRINT_POINTER(scalloc(161,69););
printStats();
void* p717 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p718 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p719 = last_address;
DEBUG_PRINT(sfree(p570););
printStats();
PRINT_POINTER(srealloc(p530,123););
printStats();
void* p720 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p721 = last_address;
DEBUG_PRINT(sfree(p670););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p722 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p723 = last_address;
PRINT_POINTER(srealloc(p578,144););
printStats();
void* p724 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p725 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p726 = last_address;
DEBUG_PRINT(sfree(p590););
printStats();
PRINT_POINTER(scalloc(139,179););
printStats();
void* p727 = last_address;
PRINT_POINTER(scalloc(114,130););
printStats();
void* p728 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p729 = last_address;
DEBUG_PRINT(sfree(p706););
printStats();
PRINT_POINTER(smalloc(13););
printStats();
void* p730 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p731 = last_address;
PRINT_POINTER(srealloc(p702,174););
printStats();
void* p732 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p733 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p734 = last_address;
PRINT_POINTER(scalloc(152,4););
printStats();
void* p735 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p736 = last_address;
DEBUG_PRINT(sfree(p320););
printStats();
PRINT_POINTER(smalloc(50););
printStats();
void* p737 = last_address;
PRINT_POINTER(scalloc(53,163););
printStats();
void* p738 = last_address;
PRINT_POINTER(scalloc(18,31););
printStats();
void* p739 = last_address;
PRINT_POINTER(srealloc(p304,156););
printStats();
void* p740 = last_address;
DEBUG_PRINT(sfree(p714););
printStats();
DEBUG_PRINT(sfree(p545););
printStats();
PRINT_POINTER(srealloc(p229,213););
printStats();
void* p741 = last_address;
PRINT_POINTER(scalloc(180,15););
printStats();
void* p742 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p743 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p744 = last_address;
DEBUG_PRINT(sfree(p724););
printStats();
DEBUG_PRINT(sfree(p732););
printStats();
PRINT_POINTER(srealloc(p480,97););
printStats();
void* p745 = last_address;
PRINT_POINTER(srealloc(p264,177););
printStats();
void* p746 = last_address;
PRINT_POINTER(srealloc(p579,237););
printStats();
void* p747 = last_address;
PRINT_POINTER(scalloc(184,166););
printStats();
void* p748 = last_address;
PRINT_POINTER(scalloc(63,162););
printStats();
void* p749 = last_address;
PRINT_POINTER(scalloc(115,39););
printStats();
void* p750 = last_address;
PRINT_POINTER(srealloc(p314,238););
printStats();
void* p751 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p752 = last_address;
PRINT_POINTER(srealloc(p504,0););
printStats();
void* p753 = last_address;
DEBUG_PRINT(sfree(p394););
printStats();
PRINT_POINTER(scalloc(126,183););
printStats();
void* p754 = last_address;
PRINT_POINTER(scalloc(23,44););
printStats();
void* p755 = last_address;
DEBUG_PRINT(sfree(p709););
printStats();
PRINT_POINTER(smalloc(66););
printStats();
void* p756 = last_address;
DEBUG_PRINT(sfree(p466););
printStats();
DEBUG_PRINT(sfree(p507););
printStats();
PRINT_POINTER(smalloc(113););
printStats();
void* p757 = last_address;
PRINT_POINTER(srealloc(p332,168););
printStats();
void* p758 = last_address;
DEBUG_PRINT(sfree(p610););
printStats();
PRINT_POINTER(srealloc(p510,190););
printStats();
void* p759 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p760 = last_address;
DEBUG_PRINT(sfree(p679););
printStats();
DEBUG_PRINT(sfree(p689););
printStats();
PRINT_POINTER(scalloc(7,187););
printStats();
void* p761 = last_address;
PRINT_POINTER(scalloc(19,110););
printStats();
void* p762 = last_address;
PRINT_POINTER(srealloc(p526,142););
printStats();
void* p763 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p764 = last_address;
DEBUG_PRINT(sfree(p488););
printStats();
PRINT_POINTER(smalloc(75););
printStats();
void* p765 = last_address;
PRINT_POINTER(srealloc(p538,177););
printStats();
void* p766 = last_address;
DEBUG_PRINT(sfree(p745););
printStats();
DEBUG_PRINT(sfree(p477););
printStats();
PRINT_POINTER(scalloc(247,157););
printStats();
void* p767 = last_address;
PRINT_POINTER(srealloc(p535,242););
printStats();
void* p768 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p769 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p770 = last_address;
DEBUG_PRINT(sfree(p634););
printStats();
DEBUG_PRINT(sfree(p727););
printStats();
PRINT_POINTER(scalloc(70,41););
printStats();
void* p771 = last_address;
PRINT_POINTER(srealloc(p716,101););
printStats();
void* p772 = last_address;
PRINT_POINTER(scalloc(115,160););
printStats();
void* p773 = last_address;
PRINT_POINTER(srealloc(p631,11););
printStats();
void* p774 = last_address;
PRINT_POINTER(scalloc(182,164););
printStats();
void* p775 = last_address;
PRINT_POINTER(scalloc(185,236););
printStats();
void* p776 = last_address;
PRINT_POINTER(srealloc(p414,175););
printStats();
void* p777 = last_address;
DEBUG_PRINT(sfree(p741););
printStats();
PRINT_POINTER(scalloc(45,174););
printStats();
void* p778 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p779 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p780 = last_address;
DEBUG_PRINT(sfree(p697););
printStats();
PRINT_POINTER(smalloc(118););
printStats();
void* p781 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p782 = last_address;
PRINT_POINTER(srealloc(p576,31););
printStats();
void* p783 = last_address;
PRINT_POINTER(srealloc(p701,216););
printStats();
void* p784 = last_address;
PRINT_POINTER(scalloc(249,34););
printStats();
void* p785 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p786 = last_address;
PRINT_POINTER(srealloc(p645,223););
printStats();
void* p787 = last_address;
PRINT_POINTER(scalloc(5,190););
printStats();
void* p788 = last_address;
DEBUG_PRINT(sfree(p436););
printStats();
PRINT_POINTER(srealloc(p615,180););
printStats();
void* p789 = last_address;
PRINT_POINTER(scalloc(22,93););
printStats();
void* p790 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p791 = last_address;
PRINT_POINTER(srealloc(p730,198););
printStats();
void* p792 = last_address;
DEBUG_PRINT(sfree(p789););
printStats();
PRINT_POINTER(srealloc(p694,185););
printStats();
void* p793 = last_address;
PRINT_POINTER(scalloc(204,39););
printStats();
void* p794 = last_address;
PRINT_POINTER(scalloc(209,102););
printStats();
void* p795 = last_address;
DEBUG_PRINT(sfree(p568););
printStats();
DEBUG_PRINT(sfree(p492););
printStats();
PRINT_POINTER(srealloc(p769,35););
printStats();
void* p796 = last_address;
PRINT_POINTER(srealloc(p755,234););
printStats();
void* p797 = last_address;
PRINT_POINTER(scalloc(87,105););
printStats();
void* p798 = last_address;
PRINT_POINTER(srealloc(p751,225););
printStats();
void* p799 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p800 = last_address;
PRINT_POINTER(srealloc(p625,199););
printStats();
void* p801 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p802 = last_address;
PRINT_POINTER(scalloc(130,214););
printStats();
void* p803 = last_address;
DEBUG_PRINT(sfree(p461););
printStats();
PRINT_POINTER(smalloc(50););
printStats();
void* p804 = last_address;
PRINT_POINTER(srealloc(p636,72););
printStats();
void* p805 = last_address;
PRINT_POINTER(scalloc(141,103););
printStats();
void* p806 = last_address;
PRINT_POINTER(scalloc(225,213););
printStats();
void* p807 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p808 = last_address;
DEBUG_PRINT(sfree(p788););
printStats();
DEBUG_PRINT(sfree(p628););
printStats();
PRINT_POINTER(srealloc(p531,24););
printStats();
void* p809 = last_address;
DEBUG_PRINT(sfree(p659););
printStats();
DEBUG_PRINT(sfree(p796););
printStats();
DEBUG_PRINT(sfree(p616););
printStats();
PRINT_POINTER(srealloc(p696,240););
printStats();
void* p810 = last_address;
PRINT_POINTER(srealloc(p712,165););
printStats();
void* p811 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p812 = last_address;
PRINT_POINTER(srealloc(p704,83););
printStats();
void* p813 = last_address;
DEBUG_PRINT(sfree(p346););
printStats();
PRINT_POINTER(smalloc(249););
printStats();
void* p814 = last_address;
PRINT_POINTER(scalloc(108,33););
printStats();
void* p815 = last_address;
PRINT_POINTER(scalloc(111,36););
printStats();
void* p816 = last_address;
DEBUG_PRINT(sfree(p580););
printStats();
PRINT_POINTER(scalloc(242,220););
printStats();
void* p817 = last_address;
PRINT_POINTER(srealloc(p746,59););
printStats();
void* p818 = last_address;
PRINT_POINTER(srealloc(p630,164););
printStats();
void* p819 = last_address;
PRINT_POINTER(srealloc(p790,160););
printStats();
void* p820 = last_address;
DEBUG_PRINT(sfree(p649););
printStats();
DEBUG_PRINT(sfree(p541););
printStats();
PRINT_POINTER(smalloc(31););
printStats();
void* p821 = last_address;
PRINT_POINTER(scalloc(108,70););
printStats();
void* p822 = last_address;
PRINT_POINTER(srealloc(p666,145););
printStats();
void* p823 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p824 = last_address;
PRINT_POINTER(srealloc(p395,162););
printStats();
void* p825 = last_address;
PRINT_POINTER(srealloc(p595,63););
printStats();
void* p826 = last_address;
DEBUG_PRINT(sfree(p594););
printStats();
PRINT_POINTER(scalloc(148,196););
printStats();
void* p827 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p828 = last_address;
DEBUG_PRINT(sfree(p813););
printStats();
PRINT_POINTER(smalloc(168););
printStats();
void* p829 = last_address;
PRINT_POINTER(scalloc(42,132););
printStats();
void* p830 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p831 = last_address;
PRINT_POINTER(srealloc(p805,41););
printStats();
void* p832 = last_address;
PRINT_POINTER(scalloc(211,103););
printStats();
void* p833 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p834 = last_address;
PRINT_POINTER(scalloc(75,144););
printStats();
void* p835 = last_address;
PRINT_POINTER(srealloc(p758,125););
printStats();
void* p836 = last_address;
DEBUG_PRINT(sfree(p383););
printStats();
PRINT_POINTER(scalloc(159,219););
printStats();
void* p837 = last_address;
PRINT_POINTER(srealloc(p832,77););
printStats();
void* p838 = last_address;
PRINT_POINTER(scalloc(40,203););
printStats();
void* p839 = last_address;
PRINT_POINTER(srealloc(p674,14););
printStats();
void* p840 = last_address;
DEBUG_PRINT(sfree(p563););
printStats();
PRINT_POINTER(scalloc(132,8););
printStats();
void* p841 = last_address;
PRINT_POINTER(srealloc(p692,186););
printStats();
void* p842 = last_address;
PRINT_POINTER(scalloc(1,101););
printStats();
void* p843 = last_address;
PRINT_POINTER(scalloc(75,125););
printStats();
void* p844 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p845 = last_address;
PRINT_POINTER(scalloc(165,4););
printStats();
void* p846 = last_address;
PRINT_POINTER(scalloc(114,151););
printStats();
void* p847 = last_address;
DEBUG_PRINT(sfree(p690););
printStats();
PRINT_POINTER(srealloc(p663,244););
printStats();
void* p848 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p849 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p850 = last_address;
PRINT_POINTER(scalloc(229,240););
printStats();
void* p851 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p852 = last_address;
DEBUG_PRINT(sfree(p338););
printStats();
PRINT_POINTER(srealloc(p517,239););
printStats();
void* p853 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p854 = last_address;
PRINT_POINTER(scalloc(58,132););
printStats();
void* p855 = last_address;
PRINT_POINTER(scalloc(119,44););
printStats();
void* p856 = last_address;
DEBUG_PRINT(sfree(p768););
printStats();
PRINT_POINTER(smalloc(132););
printStats();
void* p857 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p858 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p859 = last_address;
DEBUG_PRINT(sfree(p825););
printStats();
PRINT_POINTER(srealloc(p720,81););
printStats();
void* p860 = last_address;
PRINT_POINTER(scalloc(104,124););
printStats();
void* p861 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p862 = last_address;
PRINT_POINTER(scalloc(95,228););
printStats();
void* p863 = last_address;
PRINT_POINTER(srealloc(p654,11););
printStats();
void* p864 = last_address;
DEBUG_PRINT(sfree(p683););
printStats();
PRINT_POINTER(scalloc(240,139););
printStats();
void* p865 = last_address;
PRINT_POINTER(scalloc(30,35););
printStats();
void* p866 = last_address;
PRINT_POINTER(srealloc(p322,123););
printStats();
void* p867 = last_address;
PRINT_POINTER(scalloc(88,192););
printStats();
void* p868 = last_address;
DEBUG_PRINT(sfree(p638););
printStats();
DEBUG_PRINT(sfree(p830););
printStats();
PRINT_POINTER(smalloc(42););
printStats();
void* p869 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p870 = last_address;
PRINT_POINTER(srealloc(p787,55););
printStats();
void* p871 = last_address;
DEBUG_PRINT(sfree(p471););
printStats();
PRINT_POINTER(smalloc(242););
printStats();
void* p872 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p873 = last_address;
PRINT_POINTER(scalloc(75,26););
printStats();
void* p874 = last_address;
PRINT_POINTER(srealloc(p738,42););
printStats();
void* p875 = last_address;
PRINT_POINTER(scalloc(197,145););
printStats();
void* p876 = last_address;
DEBUG_PRINT(sfree(p677););
printStats();
PRINT_POINTER(smalloc(71););
printStats();
void* p877 = last_address;
DEBUG_PRINT(sfree(p469););
printStats();
PRINT_POINTER(smalloc(83););
printStats();
void* p878 = last_address;
PRINT_POINTER(srealloc(p872,124););
printStats();
void* p879 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p880 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p881 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p882 = last_address;
PRINT_POINTER(srealloc(p802,177););
printStats();
void* p883 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p884 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p885 = last_address;
DEBUG_PRINT(sfree(p479););
printStats();
DEBUG_PRINT(sfree(p591););
printStats();
PRINT_POINTER(smalloc(70););
printStats();
void* p886 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p887 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p888 = last_address;
PRINT_POINTER(scalloc(147,138););
printStats();
void* p889 = last_address;
PRINT_POINTER(scalloc(236,25););
printStats();
void* p890 = last_address;
PRINT_POINTER(srealloc(p827,133););
printStats();
void* p891 = last_address;
DEBUG_PRINT(sfree(p759););
printStats();
PRINT_POINTER(smalloc(196););
printStats();
void* p892 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p893 = last_address;
PRINT_POINTER(scalloc(184,117););
printStats();
void* p894 = last_address;
PRINT_POINTER(srealloc(p430,102););
printStats();
void* p895 = last_address;
PRINT_POINTER(srealloc(p603,165););
printStats();
void* p896 = last_address;
PRINT_POINTER(srealloc(p785,32););
printStats();
void* p897 = last_address;
DEBUG_PRINT(sfree(p598););
printStats();
PRINT_POINTER(scalloc(195,223););
printStats();
void* p898 = last_address;
DEBUG_PRINT(sfree(p520););
printStats();
DEBUG_PRINT(sfree(p687););
printStats();
PRINT_POINTER(srealloc(p723,188););
printStats();
void* p899 = last_address;
PRINT_POINTER(srealloc(p187,94););
printStats();
void* p900 = last_address;
PRINT_POINTER(scalloc(45,202););
printStats();
void* p901 = last_address;
PRINT_POINTER(srealloc(p652,230););
printStats();
void* p902 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p903 = last_address;
PRINT_POINTER(srealloc(p817,16););
printStats();
void* p904 = last_address;
DEBUG_PRINT(sfree(p248););
printStats();
PRINT_POINTER(srealloc(p646,223););
printStats();
void* p905 = last_address;
DEBUG_PRINT(sfree(p617););
printStats();
DEBUG_PRINT(sfree(p851););
printStats();
PRINT_POINTER(srealloc(p597,52););
printStats();
void* p906 = last_address;
PRINT_POINTER(srealloc(p593,157););
printStats();
void* p907 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p908 = last_address;
DEBUG_PRINT(sfree(p600););
printStats();
PRINT_POINTER(srealloc(p879,19););
printStats();
void* p909 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p910 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p911 = last_address;
DEBUG_PRINT(sfree(p656););
printStats();
PRINT_POINTER(smalloc(182););
printStats();
void* p912 = last_address;
PRINT_POINTER(srealloc(p834,15););
printStats();
void* p913 = last_address;
DEBUG_PRINT(sfree(p909););
printStats();
PRINT_POINTER(smalloc(34););
printStats();
void* p914 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p915 = last_address;
PRINT_POINTER(srealloc(p731,166););
printStats();
void* p916 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p917 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p918 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p919 = last_address;
PRINT_POINTER(srealloc(p812,124););
printStats();
void* p920 = last_address;
DEBUG_PRINT(sfree(p647););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p921 = last_address;
DEBUG_PRINT(sfree(p917););
printStats();
PRINT_POINTER(scalloc(58,10););
printStats();
void* p922 = last_address;
DEBUG_PRINT(sfree(p907););
printStats();
DEBUG_PRINT(sfree(p449););
printStats();
DEBUG_PRINT(sfree(p748););
printStats();
PRINT_POINTER(smalloc(217););
printStats();
void* p923 = last_address;
PRINT_POINTER(scalloc(122,27););
printStats();
void* p924 = last_address;
PRINT_POINTER(srealloc(p412,147););
printStats();
void* p925 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p926 = last_address;
DEBUG_PRINT(sfree(p566););
printStats();
PRINT_POINTER(smalloc(28););
printStats();
void* p927 = last_address;
PRINT_POINTER(srealloc(p799,154););
printStats();
void* p928 = last_address;
PRINT_POINTER(srealloc(p604,224););
printStats();
void* p929 = last_address;
PRINT_POINTER(scalloc(13,166););
printStats();
void* p930 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p931 = last_address;
PRINT_POINTER(srealloc(p890,180););
printStats();
void* p932 = last_address;
DEBUG_PRINT(sfree(p763););
printStats();
DEBUG_PRINT(sfree(p472););
printStats();
DEBUG_PRINT(sfree(p848););
printStats();
DEBUG_PRINT(sfree(p611););
printStats();
PRINT_POINTER(smalloc(54););
printStats();
void* p933 = last_address;
PRINT_POINTER(srealloc(p916,177););
printStats();
void* p934 = last_address;
PRINT_POINTER(srealloc(p857,232););
printStats();
void* p935 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p936 = last_address;
PRINT_POINTER(scalloc(29,73););
printStats();
void* p937 = last_address;
PRINT_POINTER(scalloc(84,58););
printStats();
void* p938 = last_address;
DEBUG_PRINT(sfree(p930););
printStats();
PRINT_POINTER(smalloc(23););
printStats();
void* p939 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p940 = last_address;
PRINT_POINTER(scalloc(101,170););
printStats();
void* p941 = last_address;
PRINT_POINTER(scalloc(208,181););
printStats();
void* p942 = last_address;
PRINT_POINTER(scalloc(199,52););
printStats();
void* p943 = last_address;
PRINT_POINTER(scalloc(72,127););
printStats();
void* p944 = last_address;
PRINT_POINTER(srealloc(p713,241););
printStats();
void* p945 = last_address;
PRINT_POINTER(scalloc(46,180););
printStats();
void* p946 = last_address;
PRINT_POINTER(scalloc(183,13););
printStats();
void* p947 = last_address;
PRINT_POINTER(scalloc(67,188););
printStats();
void* p948 = last_address;
PRINT_POINTER(scalloc(119,45););
printStats();
void* p949 = last_address;
PRINT_POINTER(srealloc(p619,0););
printStats();
void* p950 = last_address;
PRINT_POINTER(srealloc(p860,6););
printStats();
void* p951 = last_address;
DEBUG_PRINT(sfree(p912););
printStats();
PRINT_POINTER(smalloc(64););
printStats();
void* p952 = last_address;
PRINT_POINTER(scalloc(220,8););
printStats();
void* p953 = last_address;
PRINT_POINTER(srealloc(p608,147););
printStats();
void* p954 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p955 = last_address;
DEBUG_PRINT(sfree(p862););
printStats();
DEBUG_PRINT(sfree(p650););
printStats();
PRINT_POINTER(srealloc(p882,85););
printStats();
void* p956 = last_address;
DEBUG_PRINT(sfree(p760););
printStats();
PRINT_POINTER(smalloc(245););
printStats();
void* p957 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p958 = last_address;
DEBUG_PRINT(sfree(p698););
printStats();
PRINT_POINTER(srealloc(p840,139););
printStats();
void* p959 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p960 = last_address;
PRINT_POINTER(srealloc(p766,164););
printStats();
void* p961 = last_address;
PRINT_POINTER(srealloc(p896,6););
printStats();
void* p962 = last_address;
DEBUG_PRINT(sfree(p910););
printStats();
PRINT_POINTER(scalloc(33,208););
printStats();
void* p963 = last_address;
DEBUG_PRINT(sfree(p476););
printStats();
DEBUG_PRINT(sfree(p836););
printStats();
DEBUG_PRINT(sfree(p626););
printStats();
PRINT_POINTER(scalloc(167,54););
printStats();
void* p964 = last_address;
PRINT_POINTER(scalloc(233,138););
printStats();
void* p965 = last_address;
DEBUG_PRINT(sfree(p934););
printStats();
PRINT_POINTER(smalloc(82););
printStats();
void* p966 = last_address;
PRINT_POINTER(scalloc(131,122););
printStats();
void* p967 = last_address;
DEBUG_PRINT(sfree(p845););
printStats();
PRINT_POINTER(scalloc(147,67););
printStats();
void* p968 = last_address;
PRINT_POINTER(scalloc(17,105););
printStats();
void* p969 = last_address;
PRINT_POINTER(scalloc(136,242););
printStats();
void* p970 = last_address;
PRINT_POINTER(scalloc(134,85););
printStats();
void* p971 = last_address;
PRINT_POINTER(scalloc(54,10););
printStats();
void* p972 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p973 = last_address;
PRINT_POINTER(srealloc(p675,66););
printStats();
void* p974 = last_address;
DEBUG_PRINT(sfree(p971););
printStats();
PRINT_POINTER(scalloc(156,232););
printStats();
void* p975 = last_address;
DEBUG_PRINT(sfree(p835););
printStats();
DEBUG_PRINT(sfree(p867););
printStats();
PRINT_POINTER(scalloc(79,192););
printStats();
void* p976 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p977 = last_address;
PRINT_POINTER(scalloc(126,164););
printStats();
void* p978 = last_address;
PRINT_POINTER(scalloc(170,204););
printStats();
void* p979 = last_address;
DEBUG_PRINT(sfree(p513););
printStats();
PRINT_POINTER(smalloc(208););
printStats();
void* p980 = last_address;
PRINT_POINTER(scalloc(53,115););
printStats();
void* p981 = last_address;
PRINT_POINTER(srealloc(p976,81););
printStats();
void* p982 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p983 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p984 = last_address;
DEBUG_PRINT(sfree(p734););
printStats();
PRINT_POINTER(scalloc(161,92););
printStats();
void* p985 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p986 = last_address;
PRINT_POINTER(srealloc(p936,154););
printStats();
void* p987 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p988 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p989 = last_address;
DEBUG_PRINT(sfree(p806););
printStats();
PRINT_POINTER(scalloc(229,230););
printStats();
void* p990 = last_address;
PRINT_POINTER(scalloc(80,191););
printStats();
void* p991 = last_address;
PRINT_POINTER(srealloc(p753,56););
printStats();
void* p992 = last_address;
PRINT_POINTER(srealloc(p762,236););
printStats();
void* p993 = last_address;
DEBUG_PRINT(sfree(p726););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p994 = last_address;
PRINT_POINTER(srealloc(p808,99););
printStats();
void* p995 = last_address;
DEBUG_PRINT(sfree(p574););
printStats();
PRINT_POINTER(smalloc(243););
printStats();
void* p996 = last_address;
PRINT_POINTER(srealloc(p279,67););
printStats();
void* p997 = last_address;
PRINT_POINTER(scalloc(157,162););
printStats();
void* p998 = last_address;
PRINT_POINTER(srealloc(p448,84););
printStats();
void* p999 = last_address;
DEBUG_PRINT(sfree(p776););
printStats();
DEBUG_PRINT(sfree(p673););
printStats();
PRINT_POINTER(smalloc(175););
printStats();
void* p1000 = last_address;
PRINT_POINTER(scalloc(1,162););
printStats();
void* p1001 = last_address;
DEBUG_PRINT(sfree(p764););
printStats();
PRINT_POINTER(srealloc(p905,213););
printStats();
void* p1002 = last_address;
DEBUG_PRINT(sfree(p792););
printStats();
PRINT_POINTER(scalloc(197,46););
printStats();
void* p1003 = last_address;
PRINT_POINTER(srealloc(p904,211););
printStats();
void* p1004 = last_address;
PRINT_POINTER(scalloc(84,236););
printStats();
void* p1005 = last_address;
PRINT_POINTER(scalloc(116,12););
printStats();
void* p1006 = last_address;
PRINT_POINTER(scalloc(27,192););
printStats();
void* p1007 = last_address;
PRINT_POINTER(srealloc(p875,24););
printStats();
void* p1008 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p1009 = last_address;
PRINT_POINTER(scalloc(218,97););
printStats();
void* p1010 = last_address;
DEBUG_PRINT(sfree(p592););
printStats();
PRINT_POINTER(scalloc(85,64););
printStats();
void* p1011 = last_address;
PRINT_POINTER(srealloc(p708,193););
printStats();
void* p1012 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p1013 = last_address;
DEBUG_PRINT(sfree(p577););
printStats();
DEBUG_PRINT(sfree(p782););
printStats();
PRINT_POINTER(scalloc(152,248););
printStats();
void* p1014 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p1015 = last_address;
PRINT_POINTER(scalloc(148,59););
printStats();
void* p1016 = last_address;
PRINT_POINTER(scalloc(128,134););
printStats();
void* p1017 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p1018 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p1019 = last_address;
DEBUG_PRINT(sfree(p823););
printStats();
PRINT_POINTER(smalloc(147););
printStats();
void* p1020 = last_address;
PRINT_POINTER(scalloc(76,108););
printStats();
void* p1021 = last_address;
PRINT_POINTER(scalloc(125,25););
printStats();
void* p1022 = last_address;
PRINT_POINTER(srealloc(p880,158););
printStats();
void* p1023 = last_address;
PRINT_POINTER(scalloc(162,173););
printStats();
void* p1024 = last_address;
DEBUG_PRINT(sfree(p994););
printStats();
PRINT_POINTER(smalloc(47););
printStats();
void* p1025 = last_address;
PRINT_POINTER(scalloc(27,67););
printStats();
void* p1026 = last_address;
DEBUG_PRINT(sfree(p843););
printStats();
DEBUG_PRINT(sfree(p891););
printStats();
DEBUG_PRINT(sfree(p985););
printStats();
DEBUG_PRINT(sfree(p537););
printStats();
DEBUG_PRINT(sfree(p715););
printStats();
PRINT_POINTER(smalloc(102););
printStats();
void* p1027 = last_address;
DEBUG_PRINT(sfree(p926););
printStats();
PRINT_POINTER(srealloc(p800,34););
printStats();
void* p1028 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p1029 = last_address;
PRINT_POINTER(scalloc(245,224););
printStats();
void* p1030 = last_address;
PRINT_POINTER(srealloc(p1017,233););
printStats();
void* p1031 = last_address;
PRINT_POINTER(srealloc(p966,148););
printStats();
void* p1032 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p1033 = last_address;
DEBUG_PRINT(sfree(p571););
printStats();
PRINT_POINTER(srealloc(p667,81););
printStats();
void* p1034 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p1035 = last_address;
PRINT_POINTER(srealloc(p854,114););
printStats();
void* p1036 = last_address;
PRINT_POINTER(srealloc(p1032,241););
printStats();
void* p1037 = last_address;
PRINT_POINTER(scalloc(124,222););
printStats();
void* p1038 = last_address;
DEBUG_PRINT(sfree(p1030););
printStats();
PRINT_POINTER(scalloc(112,5););
printStats();
void* p1039 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p1040 = last_address;
PRINT_POINTER(srealloc(p699,213););
printStats();
void* p1041 = last_address;
DEBUG_PRINT(sfree(p982););
printStats();
PRINT_POINTER(srealloc(p665,14););
printStats();
void* p1042 = last_address;
}
