#include "aux_macro.h"
#include "../malloc_4.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(194););
printStats();
void* p0 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(smalloc(138););
printStats();
void* p1 = last_address;
PRINT_POINTER(scalloc(248,240););
printStats();
void* p2 = last_address;
PRINT_POINTER(srealloc(p1,8););
printStats();
void* p3 = last_address;
PRINT_POINTER(srealloc(p3,1););
printStats();
void* p4 = last_address;
PRINT_POINTER(scalloc(2,7););
printStats();
void* p5 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
PRINT_POINTER(smalloc(238););
printStats();
void* p6 = last_address;
PRINT_POINTER(srealloc(p2,42););
printStats();
void* p7 = last_address;
PRINT_POINTER(srealloc(p5,216););
printStats();
void* p8 = last_address;
PRINT_POINTER(srealloc(p8,150););
printStats();
void* p9 = last_address;
PRINT_POINTER(scalloc(171,41););
printStats();
void* p10 = last_address;
PRINT_POINTER(srealloc(p10,106););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(124,202););
printStats();
void* p12 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p13 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p14 = last_address;
PRINT_POINTER(scalloc(179,59););
printStats();
void* p15 = last_address;
DEBUG_PRINT(sfree(p12););
printStats();
DEBUG_PRINT(sfree(p7););
printStats();
DEBUG_PRINT(sfree(p9););
printStats();
PRINT_POINTER(scalloc(61,25););
printStats();
void* p16 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(134,90););
printStats();
void* p18 = last_address;
PRINT_POINTER(scalloc(70,56););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p20 = last_address;
PRINT_POINTER(scalloc(139,211););
printStats();
void* p21 = last_address;
PRINT_POINTER(scalloc(227,168););
printStats();
void* p22 = last_address;
PRINT_POINTER(srealloc(p6,81););
printStats();
void* p23 = last_address;
PRINT_POINTER(scalloc(224,244););
printStats();
void* p24 = last_address;
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(scalloc(79,89););
printStats();
void* p25 = last_address;
DEBUG_PRINT(sfree(p19););
printStats();
DEBUG_PRINT(sfree(p11););
printStats();
PRINT_POINTER(smalloc(229););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p21,228););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p27););
printStats();
PRINT_POINTER(scalloc(148,106););
printStats();
void* p28 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(scalloc(92,169););
printStats();
void* p29 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p30 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p31 = last_address;
PRINT_POINTER(scalloc(61,35););
printStats();
void* p32 = last_address;
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(smalloc(138););
printStats();
void* p33 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p34 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p35 = last_address;
PRINT_POINTER(srealloc(p30,66););
printStats();
void* p36 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(srealloc(p20,181););
printStats();
void* p37 = last_address;
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(srealloc(p31,182););
printStats();
void* p38 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p39 = last_address;
PRINT_POINTER(scalloc(138,20););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p24,25););
printStats();
void* p41 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(scalloc(199,19););
printStats();
void* p42 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p43 = last_address;
PRINT_POINTER(scalloc(90,216););
printStats();
void* p44 = last_address;
PRINT_POINTER(srealloc(p29,132););
printStats();
void* p45 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(scalloc(129,60););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p47 = last_address;
PRINT_POINTER(srealloc(p13,184););
printStats();
void* p48 = last_address;
PRINT_POINTER(srealloc(p40,102););
printStats();
void* p49 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
DEBUG_PRINT(sfree(p49););
printStats();
DEBUG_PRINT(sfree(p42););
printStats();
DEBUG_PRINT(sfree(p48););
printStats();
PRINT_POINTER(srealloc(p43,207););
printStats();
void* p50 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p51 = last_address;
PRINT_POINTER(srealloc(p47,109););
printStats();
void* p52 = last_address;
PRINT_POINTER(srealloc(p51,215););
printStats();
void* p53 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p54 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p55 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p56 = last_address;
DEBUG_PRINT(sfree(p44););
printStats();
PRINT_POINTER(scalloc(142,183););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(174,41););
printStats();
void* p58 = last_address;
PRINT_POINTER(srealloc(p35,66););
printStats();
void* p59 = last_address;
PRINT_POINTER(scalloc(90,235););
printStats();
void* p60 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p61 = last_address;
PRINT_POINTER(srealloc(p32,104););
printStats();
void* p62 = last_address;
PRINT_POINTER(scalloc(106,47););
printStats();
void* p63 = last_address;
PRINT_POINTER(srealloc(p62,22););
printStats();
void* p64 = last_address;
PRINT_POINTER(scalloc(201,219););
printStats();
void* p65 = last_address;
PRINT_POINTER(scalloc(53,181););
printStats();
void* p66 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p67 = last_address;
DEBUG_PRINT(sfree(p26););
printStats();
PRINT_POINTER(smalloc(64););
printStats();
void* p68 = last_address;
PRINT_POINTER(scalloc(1,114););
printStats();
void* p69 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p70 = last_address;
PRINT_POINTER(scalloc(60,143););
printStats();
void* p71 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
DEBUG_PRINT(sfree(p65););
printStats();
PRINT_POINTER(srealloc(p59,224););
printStats();
void* p72 = last_address;
PRINT_POINTER(srealloc(p61,153););
printStats();
void* p73 = last_address;
PRINT_POINTER(srealloc(p28,137););
printStats();
void* p74 = last_address;
PRINT_POINTER(scalloc(86,111););
printStats();
void* p75 = last_address;
DEBUG_PRINT(sfree(p68););
printStats();
PRINT_POINTER(scalloc(142,16););
printStats();
void* p76 = last_address;
PRINT_POINTER(srealloc(p54,212););
printStats();
void* p77 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p78 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p79 = last_address;
DEBUG_PRINT(sfree(p53););
printStats();
PRINT_POINTER(srealloc(p74,65););
printStats();
void* p80 = last_address;
PRINT_POINTER(scalloc(26,28););
printStats();
void* p81 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
DEBUG_PRINT(sfree(p67););
printStats();
DEBUG_PRINT(sfree(p71););
printStats();
PRINT_POINTER(smalloc(87););
printStats();
void* p82 = last_address;
PRINT_POINTER(scalloc(244,176););
printStats();
void* p83 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(smalloc(76););
printStats();
void* p84 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p85 = last_address;
PRINT_POINTER(srealloc(p64,60););
printStats();
void* p86 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
DEBUG_PRINT(sfree(p46););
printStats();
PRINT_POINTER(scalloc(179,140););
printStats();
void* p87 = last_address;
PRINT_POINTER(scalloc(28,210););
printStats();
void* p88 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(scalloc(58,159););
printStats();
void* p89 = last_address;
PRINT_POINTER(srealloc(p87,217););
printStats();
void* p90 = last_address;
PRINT_POINTER(srealloc(p63,171););
printStats();
void* p91 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p92 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p93 = last_address;
PRINT_POINTER(scalloc(129,236););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p95 = last_address;
DEBUG_PRINT(sfree(p80););
printStats();
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(smalloc(167););
printStats();
void* p96 = last_address;
PRINT_POINTER(scalloc(167,33););
printStats();
void* p97 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p98 = last_address;
PRINT_POINTER(srealloc(p57,150););
printStats();
void* p99 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p100 = last_address;
PRINT_POINTER(srealloc(p76,93););
printStats();
void* p101 = last_address;
PRINT_POINTER(srealloc(p60,15););
printStats();
void* p102 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
PRINT_POINTER(srealloc(p96,184););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p82,44););
printStats();
void* p104 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p105 = last_address;
PRINT_POINTER(scalloc(196,243););
printStats();
void* p106 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p107 = last_address;
PRINT_POINTER(srealloc(p107,241););
printStats();
void* p108 = last_address;
PRINT_POINTER(scalloc(57,184););
printStats();
void* p109 = last_address;
PRINT_POINTER(srealloc(p70,237););
printStats();
void* p110 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
DEBUG_PRINT(sfree(p56););
printStats();
PRINT_POINTER(srealloc(p37,142););
printStats();
void* p111 = last_address;
PRINT_POINTER(scalloc(14,201););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p100,78););
printStats();
void* p113 = last_address;
PRINT_POINTER(scalloc(233,161););
printStats();
void* p114 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p115 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(scalloc(112,157););
printStats();
void* p116 = last_address;
DEBUG_PRINT(sfree(p73););
printStats();
PRINT_POINTER(smalloc(108););
printStats();
void* p117 = last_address;
PRINT_POINTER(scalloc(49,9););
printStats();
void* p118 = last_address;
PRINT_POINTER(scalloc(75,213););
printStats();
void* p119 = last_address;
PRINT_POINTER(srealloc(p14,233););
printStats();
void* p120 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(scalloc(28,11););
printStats();
void* p121 = last_address;
DEBUG_PRINT(sfree(p110););
printStats();
PRINT_POINTER(smalloc(141););
printStats();
void* p122 = last_address;
PRINT_POINTER(srealloc(p77,142););
printStats();
void* p123 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p124 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p125 = last_address;
PRINT_POINTER(srealloc(p115,126););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(44,238););
printStats();
void* p127 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(srealloc(p75,61););
printStats();
void* p128 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p129 = last_address;
PRINT_POINTER(scalloc(221,177););
printStats();
void* p130 = last_address;
PRINT_POINTER(scalloc(249,209););
printStats();
void* p131 = last_address;
DEBUG_PRINT(sfree(p104););
printStats();
DEBUG_PRINT(sfree(p99););
printStats();
PRINT_POINTER(srealloc(p119,115););
printStats();
void* p132 = last_address;
PRINT_POINTER(scalloc(159,205););
printStats();
void* p133 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
PRINT_POINTER(scalloc(245,135););
printStats();
void* p134 = last_address;
PRINT_POINTER(srealloc(p58,24););
printStats();
void* p135 = last_address;
PRINT_POINTER(srealloc(p124,213););
printStats();
void* p136 = last_address;
PRINT_POINTER(scalloc(180,114););
printStats();
void* p137 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
PRINT_POINTER(srealloc(p122,52););
printStats();
void* p138 = last_address;
PRINT_POINTER(srealloc(p106,36););
printStats();
void* p139 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p140 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p141 = last_address;
DEBUG_PRINT(sfree(p93););
printStats();
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(srealloc(p118,75););
printStats();
void* p142 = last_address;
DEBUG_PRINT(sfree(p132););
printStats();
DEBUG_PRINT(sfree(p131););
printStats();
PRINT_POINTER(smalloc(234););
printStats();
void* p143 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(srealloc(p133,60););
printStats();
void* p144 = last_address;
DEBUG_PRINT(sfree(p103););
printStats();
DEBUG_PRINT(sfree(p92););
printStats();
PRINT_POINTER(srealloc(p144,5););
printStats();
void* p145 = last_address;
DEBUG_PRINT(sfree(p78););
printStats();
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(srealloc(p95,142););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p88););
printStats();
PRINT_POINTER(srealloc(p136,48););
printStats();
void* p147 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
PRINT_POINTER(scalloc(24,206););
printStats();
void* p148 = last_address;
PRINT_POINTER(srealloc(p66,204););
printStats();
void* p149 = last_address;
PRINT_POINTER(srealloc(p138,109););
printStats();
void* p150 = last_address;
DEBUG_PRINT(sfree(p146););
printStats();
PRINT_POINTER(scalloc(198,227););
printStats();
void* p151 = last_address;
DEBUG_PRINT(sfree(p117););
printStats();
PRINT_POINTER(srealloc(p139,226););
printStats();
void* p152 = last_address;
PRINT_POINTER(srealloc(p150,105););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(140,16););
printStats();
void* p154 = last_address;
PRINT_POINTER(scalloc(52,68););
printStats();
void* p155 = last_address;
PRINT_POINTER(srealloc(p79,6););
printStats();
void* p156 = last_address;
PRINT_POINTER(scalloc(200,50););
printStats();
void* p157 = last_address;
PRINT_POINTER(srealloc(p111,242););
printStats();
void* p158 = last_address;
PRINT_POINTER(srealloc(p127,44););
printStats();
void* p159 = last_address;
PRINT_POINTER(scalloc(6,180););
printStats();
void* p160 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p161 = last_address;
PRINT_POINTER(scalloc(136,164););
printStats();
void* p162 = last_address;
DEBUG_PRINT(sfree(p154););
printStats();
PRINT_POINTER(smalloc(8););
printStats();
void* p163 = last_address;
PRINT_POINTER(scalloc(92,25););
printStats();
void* p164 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
PRINT_POINTER(scalloc(151,161););
printStats();
void* p165 = last_address;
PRINT_POINTER(srealloc(p121,21););
printStats();
void* p166 = last_address;
PRINT_POINTER(scalloc(216,115););
printStats();
void* p167 = last_address;
PRINT_POINTER(srealloc(p143,48););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(125,230););
printStats();
void* p169 = last_address;
PRINT_POINTER(scalloc(182,64););
printStats();
void* p170 = last_address;
DEBUG_PRINT(sfree(p156););
printStats();
PRINT_POINTER(scalloc(26,175););
printStats();
void* p171 = last_address;
DEBUG_PRINT(sfree(p145););
printStats();
PRINT_POINTER(scalloc(214,12););
printStats();
void* p172 = last_address;
DEBUG_PRINT(sfree(p84););
printStats();
PRINT_POINTER(scalloc(25,217););
printStats();
void* p173 = last_address;
PRINT_POINTER(srealloc(p159,14););
printStats();
void* p174 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
DEBUG_PRINT(sfree(p172););
printStats();
PRINT_POINTER(scalloc(46,247););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(scalloc(136,74););
printStats();
void* p176 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p177 = last_address;
PRINT_POINTER(srealloc(p83,46););
printStats();
void* p178 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p179 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p180 = last_address;
PRINT_POINTER(srealloc(p55,24););
printStats();
void* p181 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p182 = last_address;
DEBUG_PRINT(sfree(p129););
printStats();
PRINT_POINTER(smalloc(122););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(209,200););
printStats();
void* p184 = last_address;
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(smalloc(71););
printStats();
void* p185 = last_address;
DEBUG_PRINT(sfree(p126););
printStats();
PRINT_POINTER(smalloc(28););
printStats();
void* p186 = last_address;
DEBUG_PRINT(sfree(p184););
printStats();
PRINT_POINTER(smalloc(185););
printStats();
void* p187 = last_address;
PRINT_POINTER(srealloc(p182,54););
printStats();
void* p188 = last_address;
PRINT_POINTER(srealloc(p135,229););
printStats();
void* p189 = last_address;
PRINT_POINTER(srealloc(p105,135););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p191 = last_address;
PRINT_POINTER(srealloc(p185,177););
printStats();
void* p192 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p193 = last_address;
PRINT_POINTER(srealloc(p171,115););
printStats();
void* p194 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p195 = last_address;
PRINT_POINTER(scalloc(69,85););
printStats();
void* p196 = last_address;
PRINT_POINTER(scalloc(206,51););
printStats();
void* p197 = last_address;
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(smalloc(2););
printStats();
void* p198 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
PRINT_POINTER(scalloc(166,89););
printStats();
void* p199 = last_address;
PRINT_POINTER(srealloc(p183,200););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p169,168););
printStats();
void* p201 = last_address;
PRINT_POINTER(scalloc(177,85););
printStats();
void* p202 = last_address;
PRINT_POINTER(srealloc(p157,66););
printStats();
void* p203 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p204 = last_address;
PRINT_POINTER(scalloc(52,122););
printStats();
void* p205 = last_address;
DEBUG_PRINT(sfree(p52););
printStats();
PRINT_POINTER(smalloc(157););
printStats();
void* p206 = last_address;
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(scalloc(177,219););
printStats();
void* p207 = last_address;
DEBUG_PRINT(sfree(p168););
printStats();
PRINT_POINTER(smalloc(75););
printStats();
void* p208 = last_address;
PRINT_POINTER(srealloc(p174,11););
printStats();
void* p209 = last_address;
DEBUG_PRINT(sfree(p187););
printStats();
DEBUG_PRINT(sfree(p203););
printStats();
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(smalloc(60););
printStats();
void* p210 = last_address;
PRINT_POINTER(srealloc(p23,189););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(235,169););
printStats();
void* p212 = last_address;
PRINT_POINTER(srealloc(p181,200););
printStats();
void* p213 = last_address;
PRINT_POINTER(scalloc(3,81););
printStats();
void* p214 = last_address;
PRINT_POINTER(srealloc(p196,196););
printStats();
void* p215 = last_address;
PRINT_POINTER(srealloc(p153,216););
printStats();
void* p216 = last_address;
PRINT_POINTER(srealloc(p206,189););
printStats();
void* p217 = last_address;
PRINT_POINTER(srealloc(p86,23););
printStats();
void* p218 = last_address;
DEBUG_PRINT(sfree(p140););
printStats();
PRINT_POINTER(scalloc(39,142););
printStats();
void* p219 = last_address;
PRINT_POINTER(scalloc(150,103););
printStats();
void* p220 = last_address;
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(smalloc(218););
printStats();
void* p221 = last_address;
PRINT_POINTER(scalloc(20,192););
printStats();
void* p222 = last_address;
PRINT_POINTER(smalloc(80););
printStats();
void* p223 = last_address;
DEBUG_PRINT(sfree(p163););
printStats();
DEBUG_PRINT(sfree(p189););
printStats();
PRINT_POINTER(smalloc(110););
printStats();
void* p224 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p225 = last_address;
PRINT_POINTER(scalloc(145,5););
printStats();
void* p226 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(scalloc(1,240););
printStats();
void* p227 = last_address;
PRINT_POINTER(srealloc(p192,179););
printStats();
void* p228 = last_address;
PRINT_POINTER(scalloc(89,4););
printStats();
void* p229 = last_address;
PRINT_POINTER(scalloc(175,150););
printStats();
void* p230 = last_address;
PRINT_POINTER(scalloc(196,167););
printStats();
void* p231 = last_address;
DEBUG_PRINT(sfree(p137););
printStats();
PRINT_POINTER(smalloc(23););
printStats();
void* p232 = last_address;
PRINT_POINTER(srealloc(p194,211););
printStats();
void* p233 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p234 = last_address;
PRINT_POINTER(srealloc(p213,194););
printStats();
void* p235 = last_address;
PRINT_POINTER(scalloc(74,69););
printStats();
void* p236 = last_address;
PRINT_POINTER(srealloc(p204,150););
printStats();
void* p237 = last_address;
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(smalloc(228););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p202,12););
printStats();
void* p239 = last_address;
DEBUG_PRINT(sfree(p237););
printStats();
DEBUG_PRINT(sfree(p229););
printStats();
PRINT_POINTER(scalloc(233,216););
printStats();
void* p240 = last_address;
PRINT_POINTER(srealloc(p178,236););
printStats();
void* p241 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p165););
printStats();
PRINT_POINTER(srealloc(p216,195););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p112););
printStats();
DEBUG_PRINT(sfree(p239););
printStats();
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(srealloc(p223,31););
printStats();
void* p244 = last_address;
DEBUG_PRINT(sfree(p208););
printStats();
PRINT_POINTER(scalloc(153,249););
printStats();
void* p245 = last_address;
PRINT_POINTER(scalloc(168,11););
printStats();
void* p246 = last_address;
PRINT_POINTER(srealloc(p210,237););
printStats();
void* p247 = last_address;
PRINT_POINTER(scalloc(186,157););
printStats();
void* p248 = last_address;
DEBUG_PRINT(sfree(p128););
printStats();
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(smalloc(95););
printStats();
void* p249 = last_address;
PRINT_POINTER(srealloc(p177,24););
printStats();
void* p250 = last_address;
PRINT_POINTER(srealloc(p167,249););
printStats();
void* p251 = last_address;
PRINT_POINTER(srealloc(p228,27););
printStats();
void* p252 = last_address;
DEBUG_PRINT(sfree(p246););
printStats();
PRINT_POINTER(smalloc(34););
printStats();
void* p253 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p254 = last_address;
PRINT_POINTER(scalloc(51,190););
printStats();
void* p255 = last_address;
DEBUG_PRINT(sfree(p227););
printStats();
PRINT_POINTER(srealloc(p247,173););
printStats();
void* p256 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p257 = last_address;
PRINT_POINTER(scalloc(42,118););
printStats();
void* p258 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p259 = last_address;
DEBUG_PRINT(sfree(p235););
printStats();
PRINT_POINTER(srealloc(p193,118););
printStats();
void* p260 = last_address;
PRINT_POINTER(srealloc(p211,189););
printStats();
void* p261 = last_address;
PRINT_POINTER(scalloc(0,201););
printStats();
void* p262 = last_address;
DEBUG_PRINT(sfree(p258););
printStats();
PRINT_POINTER(srealloc(p232,198););
printStats();
void* p263 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p264 = last_address;
PRINT_POINTER(srealloc(p218,228););
printStats();
void* p265 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p266 = last_address;
PRINT_POINTER(srealloc(p241,192););
printStats();
void* p267 = last_address;
PRINT_POINTER(srealloc(p264,0););
printStats();
void* p268 = last_address;
DEBUG_PRINT(sfree(p254););
printStats();
PRINT_POINTER(smalloc(164););
printStats();
void* p269 = last_address;
PRINT_POINTER(scalloc(10,47););
printStats();
void* p270 = last_address;
PRINT_POINTER(srealloc(p252,173););
printStats();
void* p271 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p272 = last_address;
PRINT_POINTER(scalloc(105,236););
printStats();
void* p273 = last_address;
DEBUG_PRINT(sfree(p245););
printStats();
DEBUG_PRINT(sfree(p120););
printStats();
PRINT_POINTER(scalloc(224,53););
printStats();
void* p274 = last_address;
PRINT_POINTER(srealloc(p256,133););
printStats();
void* p275 = last_address;
DEBUG_PRINT(sfree(p251););
printStats();
PRINT_POINTER(scalloc(8,164););
printStats();
void* p276 = last_address;
PRINT_POINTER(srealloc(p109,123););
printStats();
void* p277 = last_address;
DEBUG_PRINT(sfree(p224););
printStats();
PRINT_POINTER(smalloc(159););
printStats();
void* p278 = last_address;
PRINT_POINTER(scalloc(161,140););
printStats();
void* p279 = last_address;
PRINT_POINTER(scalloc(48,107););
printStats();
void* p280 = last_address;
DEBUG_PRINT(sfree(p219););
printStats();
PRINT_POINTER(srealloc(p221,198););
printStats();
void* p281 = last_address;
PRINT_POINTER(scalloc(169,246););
printStats();
void* p282 = last_address;
DEBUG_PRINT(sfree(p234););
printStats();
PRINT_POINTER(scalloc(26,156););
printStats();
void* p283 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p284 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p285 = last_address;
PRINT_POINTER(scalloc(220,141););
printStats();
void* p286 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p287 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p288 = last_address;
PRINT_POINTER(srealloc(p282,192););
printStats();
void* p289 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p290 = last_address;
PRINT_POINTER(scalloc(132,7););
printStats();
void* p291 = last_address;
PRINT_POINTER(srealloc(p273,178););
printStats();
void* p292 = last_address;
PRINT_POINTER(scalloc(226,109););
printStats();
void* p293 = last_address;
DEBUG_PRINT(sfree(p280););
printStats();
PRINT_POINTER(scalloc(167,221););
printStats();
void* p294 = last_address;
PRINT_POINTER(srealloc(p89,161););
printStats();
void* p295 = last_address;
DEBUG_PRINT(sfree(p291););
printStats();
PRINT_POINTER(scalloc(50,64););
printStats();
void* p296 = last_address;
PRINT_POINTER(scalloc(144,156););
printStats();
void* p297 = last_address;
PRINT_POINTER(scalloc(222,65););
printStats();
void* p298 = last_address;
PRINT_POINTER(scalloc(192,218););
printStats();
void* p299 = last_address;
PRINT_POINTER(srealloc(p238,152););
printStats();
void* p300 = last_address;
PRINT_POINTER(srealloc(p300,109););
printStats();
void* p301 = last_address;
PRINT_POINTER(scalloc(209,128););
printStats();
void* p302 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p303 = last_address;
DEBUG_PRINT(sfree(p220););
printStats();
PRINT_POINTER(smalloc(52););
printStats();
void* p304 = last_address;
PRINT_POINTER(scalloc(26,159););
printStats();
void* p305 = last_address;
PRINT_POINTER(scalloc(12,11););
printStats();
void* p306 = last_address;
DEBUG_PRINT(sfree(p302););
printStats();
PRINT_POINTER(smalloc(11););
printStats();
void* p307 = last_address;
PRINT_POINTER(scalloc(112,19););
printStats();
void* p308 = last_address;
PRINT_POINTER(scalloc(205,19););
printStats();
void* p309 = last_address;
PRINT_POINTER(srealloc(p274,16););
printStats();
void* p310 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p311 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p312 = last_address;
PRINT_POINTER(srealloc(p267,60););
printStats();
void* p313 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p314 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p315 = last_address;
PRINT_POINTER(scalloc(222,138););
printStats();
void* p316 = last_address;
PRINT_POINTER(scalloc(210,196););
printStats();
void* p317 = last_address;
PRINT_POINTER(srealloc(p308,179););
printStats();
void* p318 = last_address;
DEBUG_PRINT(sfree(p304););
printStats();
PRINT_POINTER(srealloc(p244,119););
printStats();
void* p319 = last_address;
PRINT_POINTER(srealloc(p318,81););
printStats();
void* p320 = last_address;
PRINT_POINTER(scalloc(172,241););
printStats();
void* p321 = last_address;
PRINT_POINTER(srealloc(p207,74););
printStats();
void* p322 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
PRINT_POINTER(scalloc(185,23););
printStats();
void* p323 = last_address;
DEBUG_PRINT(sfree(p299););
printStats();
PRINT_POINTER(smalloc(97););
printStats();
void* p324 = last_address;
PRINT_POINTER(srealloc(p190,184););
printStats();
void* p325 = last_address;
PRINT_POINTER(scalloc(224,164););
printStats();
void* p326 = last_address;
PRINT_POINTER(srealloc(p108,114););
printStats();
void* p327 = last_address;
PRINT_POINTER(srealloc(p323,59););
printStats();
void* p328 = last_address;
PRINT_POINTER(scalloc(94,157););
printStats();
void* p329 = last_address;
DEBUG_PRINT(sfree(p310););
printStats();
PRINT_POINTER(srealloc(p320,170););
printStats();
void* p330 = last_address;
PRINT_POINTER(srealloc(p205,103););
printStats();
void* p331 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p332 = last_address;
PRINT_POINTER(srealloc(p161,112););
printStats();
void* p333 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p334 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p335 = last_address;
DEBUG_PRINT(sfree(p266););
printStats();
DEBUG_PRINT(sfree(p214););
printStats();
PRINT_POINTER(srealloc(p242,22););
printStats();
void* p336 = last_address;
PRINT_POINTER(srealloc(p298,163););
printStats();
void* p337 = last_address;
PRINT_POINTER(srealloc(p316,81););
printStats();
void* p338 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p339 = last_address;
DEBUG_PRINT(sfree(p312););
printStats();
DEBUG_PRINT(sfree(p226););
printStats();
PRINT_POINTER(smalloc(222););
printStats();
void* p340 = last_address;
PRINT_POINTER(scalloc(161,122););
printStats();
void* p341 = last_address;
DEBUG_PRINT(sfree(p305););
printStats();
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(srealloc(p198,247););
printStats();
void* p342 = last_address;
DEBUG_PRINT(sfree(p289););
printStats();
PRINT_POINTER(smalloc(104););
printStats();
void* p343 = last_address;
DEBUG_PRINT(sfree(p290););
printStats();
PRINT_POINTER(scalloc(37,121););
printStats();
void* p344 = last_address;
PRINT_POINTER(srealloc(p225,242););
printStats();
void* p345 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p346 = last_address;
PRINT_POINTER(srealloc(p311,133););
printStats();
void* p347 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p348 = last_address;
PRINT_POINTER(srealloc(p200,63););
printStats();
void* p349 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(scalloc(206,69););
printStats();
void* p350 = last_address;
PRINT_POINTER(scalloc(6,135););
printStats();
void* p351 = last_address;
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(srealloc(p313,144););
printStats();
void* p352 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p353 = last_address;
PRINT_POINTER(srealloc(p325,83););
printStats();
void* p354 = last_address;
PRINT_POINTER(scalloc(176,196););
printStats();
void* p355 = last_address;
PRINT_POINTER(srealloc(p309,88););
printStats();
void* p356 = last_address;
PRINT_POINTER(srealloc(p331,46););
printStats();
void* p357 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p358 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p359 = last_address;
PRINT_POINTER(srealloc(p338,168););
printStats();
void* p360 = last_address;
PRINT_POINTER(srealloc(p125,230););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p362 = last_address;
DEBUG_PRINT(sfree(p188););
printStats();
DEBUG_PRINT(sfree(p317););
printStats();
PRINT_POINTER(smalloc(113););
printStats();
void* p363 = last_address;
PRINT_POINTER(scalloc(40,94););
printStats();
void* p364 = last_address;
PRINT_POINTER(scalloc(224,106););
printStats();
void* p365 = last_address;
DEBUG_PRINT(sfree(p261););
printStats();
PRINT_POINTER(scalloc(117,88););
printStats();
void* p366 = last_address;
PRINT_POINTER(scalloc(34,66););
printStats();
void* p367 = last_address;
PRINT_POINTER(srealloc(p255,3););
printStats();
void* p368 = last_address;
PRINT_POINTER(scalloc(209,177););
printStats();
void* p369 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p370 = last_address;
DEBUG_PRINT(sfree(p322););
printStats();
PRINT_POINTER(scalloc(179,179););
printStats();
void* p371 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p372 = last_address;
PRINT_POINTER(srealloc(p355,2););
printStats();
void* p373 = last_address;
PRINT_POINTER(srealloc(p363,35););
printStats();
void* p374 = last_address;
PRINT_POINTER(srealloc(p351,148););
printStats();
void* p375 = last_address;
PRINT_POINTER(scalloc(156,143););
printStats();
void* p376 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p377 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p378 = last_address;
PRINT_POINTER(srealloc(p352,184););
printStats();
void* p379 = last_address;
DEBUG_PRINT(sfree(p336););
printStats();
PRINT_POINTER(smalloc(164););
printStats();
void* p380 = last_address;
DEBUG_PRINT(sfree(p286););
printStats();
PRINT_POINTER(scalloc(138,63););
printStats();
void* p381 = last_address;
DEBUG_PRINT(sfree(p215););
printStats();
PRINT_POINTER(smalloc(177););
printStats();
void* p382 = last_address;
DEBUG_PRINT(sfree(p367););
printStats();
DEBUG_PRINT(sfree(p333););
printStats();
PRINT_POINTER(scalloc(218,58););
printStats();
void* p383 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p384 = last_address;
PRINT_POINTER(scalloc(105,231););
printStats();
void* p385 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p386 = last_address;
DEBUG_PRINT(sfree(p324););
printStats();
PRINT_POINTER(srealloc(p275,153););
printStats();
void* p387 = last_address;
DEBUG_PRINT(sfree(p385););
printStats();
PRINT_POINTER(smalloc(194););
printStats();
void* p388 = last_address;
PRINT_POINTER(scalloc(46,55););
printStats();
void* p389 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p390 = last_address;
PRINT_POINTER(srealloc(p276,8););
printStats();
void* p391 = last_address;
PRINT_POINTER(scalloc(45,228););
printStats();
void* p392 = last_address;
DEBUG_PRINT(sfree(p278););
printStats();
PRINT_POINTER(scalloc(143,228););
printStats();
void* p393 = last_address;
DEBUG_PRINT(sfree(p330););
printStats();
PRINT_POINTER(srealloc(p376,51););
printStats();
void* p394 = last_address;
PRINT_POINTER(srealloc(p359,143););
printStats();
void* p395 = last_address;
PRINT_POINTER(scalloc(161,0););
printStats();
void* p396 = last_address;
PRINT_POINTER(srealloc(p296,134););
printStats();
void* p397 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p398 = last_address;
PRINT_POINTER(srealloc(p176,106););
printStats();
void* p399 = last_address;
PRINT_POINTER(scalloc(30,198););
printStats();
void* p400 = last_address;
DEBUG_PRINT(sfree(p335););
printStats();
PRINT_POINTER(srealloc(p297,245););
printStats();
void* p401 = last_address;
PRINT_POINTER(srealloc(p270,96););
printStats();
void* p402 = last_address;
PRINT_POINTER(scalloc(36,32););
printStats();
void* p403 = last_address;
PRINT_POINTER(scalloc(210,95););
printStats();
void* p404 = last_address;
PRINT_POINTER(scalloc(86,143););
printStats();
void* p405 = last_address;
DEBUG_PRINT(sfree(p319););
printStats();
PRINT_POINTER(srealloc(p379,203););
printStats();
void* p406 = last_address;
PRINT_POINTER(srealloc(p378,151););
printStats();
void* p407 = last_address;
DEBUG_PRINT(sfree(p399););
printStats();
PRINT_POINTER(smalloc(34););
printStats();
void* p408 = last_address;
PRINT_POINTER(scalloc(245,32););
printStats();
void* p409 = last_address;
DEBUG_PRINT(sfree(p407););
printStats();
DEBUG_PRINT(sfree(p162););
printStats();
PRINT_POINTER(scalloc(194,175););
printStats();
void* p410 = last_address;
DEBUG_PRINT(sfree(p269););
printStats();
DEBUG_PRINT(sfree(p248););
printStats();
DEBUG_PRINT(sfree(p314););
printStats();
PRINT_POINTER(smalloc(174););
printStats();
void* p411 = last_address;
DEBUG_PRINT(sfree(p293););
printStats();
PRINT_POINTER(scalloc(128,157););
printStats();
void* p412 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
PRINT_POINTER(smalloc(241););
printStats();
void* p413 = last_address;
DEBUG_PRINT(sfree(p390););
printStats();
DEBUG_PRINT(sfree(p179););
printStats();
DEBUG_PRINT(sfree(p212););
printStats();
PRINT_POINTER(smalloc(51););
printStats();
void* p414 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p415 = last_address;
PRINT_POINTER(srealloc(p397,153););
printStats();
void* p416 = last_address;
PRINT_POINTER(scalloc(21,198););
printStats();
void* p417 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p418 = last_address;
PRINT_POINTER(scalloc(222,157););
printStats();
void* p419 = last_address;
PRINT_POINTER(srealloc(p301,150););
printStats();
void* p420 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p421 = last_address;
DEBUG_PRINT(sfree(p405););
printStats();
PRINT_POINTER(srealloc(p295,34););
printStats();
void* p422 = last_address;
PRINT_POINTER(scalloc(244,201););
printStats();
void* p423 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p424 = last_address;
DEBUG_PRINT(sfree(p369););
printStats();
PRINT_POINTER(smalloc(40););
printStats();
void* p425 = last_address;
PRINT_POINTER(srealloc(p423,172););
printStats();
void* p426 = last_address;
PRINT_POINTER(scalloc(92,209););
printStats();
void* p427 = last_address;
PRINT_POINTER(scalloc(15,45););
printStats();
void* p428 = last_address;
PRINT_POINTER(srealloc(p357,129););
printStats();
void* p429 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p430 = last_address;
PRINT_POINTER(scalloc(55,115););
printStats();
void* p431 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p432 = last_address;
PRINT_POINTER(srealloc(p284,94););
printStats();
void* p433 = last_address;
PRINT_POINTER(scalloc(203,214););
printStats();
void* p434 = last_address;
PRINT_POINTER(scalloc(221,201););
printStats();
void* p435 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p436 = last_address;
DEBUG_PRINT(sfree(p348););
printStats();
PRINT_POINTER(scalloc(52,58););
printStats();
void* p437 = last_address;
PRINT_POINTER(srealloc(p155,232););
printStats();
void* p438 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p439 = last_address;
DEBUG_PRINT(sfree(p406););
printStats();
PRINT_POINTER(srealloc(p130,202););
printStats();
void* p440 = last_address;
PRINT_POINTER(srealloc(p272,215););
printStats();
void* p441 = last_address;
PRINT_POINTER(scalloc(224,243););
printStats();
void* p442 = last_address;
PRINT_POINTER(srealloc(p404,105););
printStats();
void* p443 = last_address;
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(srealloc(p427,141););
printStats();
void* p444 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p445 = last_address;
PRINT_POINTER(scalloc(221,132););
printStats();
void* p446 = last_address;
DEBUG_PRINT(sfree(p201););
printStats();
PRINT_POINTER(smalloc(222););
printStats();
void* p447 = last_address;
DEBUG_PRINT(sfree(p398););
printStats();
PRINT_POINTER(smalloc(133););
printStats();
void* p448 = last_address;
DEBUG_PRINT(sfree(p368););
printStats();
DEBUG_PRINT(sfree(p370););
printStats();
PRINT_POINTER(srealloc(p353,0););
printStats();
void* p449 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p450 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p451 = last_address;
PRINT_POINTER(scalloc(169,23););
printStats();
void* p452 = last_address;
PRINT_POINTER(srealloc(p437,82););
printStats();
void* p453 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(smalloc(91););
printStats();
void* p454 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p455 = last_address;
PRINT_POINTER(scalloc(220,39););
printStats();
void* p456 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p457 = last_address;
PRINT_POINTER(scalloc(83,245););
printStats();
void* p458 = last_address;
DEBUG_PRINT(sfree(p416););
printStats();
PRINT_POINTER(scalloc(189,57););
printStats();
void* p459 = last_address;
PRINT_POINTER(scalloc(91,148););
printStats();
void* p460 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p461 = last_address;
PRINT_POINTER(scalloc(241,232););
printStats();
void* p462 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p463 = last_address;
DEBUG_PRINT(sfree(p433););
printStats();
PRINT_POINTER(scalloc(82,139););
printStats();
void* p464 = last_address;
DEBUG_PRINT(sfree(p387););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p465 = last_address;
DEBUG_PRINT(sfree(p236););
printStats();
PRINT_POINTER(srealloc(p409,132););
printStats();
void* p466 = last_address;
PRINT_POINTER(scalloc(67,207););
printStats();
void* p467 = last_address;
DEBUG_PRINT(sfree(p160););
printStats();
PRINT_POINTER(srealloc(p393,59););
printStats();
void* p468 = last_address;
PRINT_POINTER(scalloc(122,99););
printStats();
void* p469 = last_address;
DEBUG_PRINT(sfree(p346););
printStats();
PRINT_POINTER(smalloc(72););
printStats();
void* p470 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p471 = last_address;
PRINT_POINTER(scalloc(64,69););
printStats();
void* p472 = last_address;
PRINT_POINTER(scalloc(85,95););
printStats();
void* p473 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p474 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p475 = last_address;
PRINT_POINTER(srealloc(p328,238););
printStats();
void* p476 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p477 = last_address;
PRINT_POINTER(srealloc(p217,190););
printStats();
void* p478 = last_address;
PRINT_POINTER(srealloc(p389,52););
printStats();
void* p479 = last_address;
DEBUG_PRINT(sfree(p408););
printStats();
PRINT_POINTER(smalloc(154););
printStats();
void* p480 = last_address;
PRINT_POINTER(scalloc(215,233););
printStats();
void* p481 = last_address;
PRINT_POINTER(srealloc(p412,122););
printStats();
void* p482 = last_address;
PRINT_POINTER(srealloc(p262,147););
printStats();
void* p483 = last_address;
PRINT_POINTER(srealloc(p344,89););
printStats();
void* p484 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p485 = last_address;
DEBUG_PRINT(sfree(p448););
printStats();
DEBUG_PRINT(sfree(p484););
printStats();
PRINT_POINTER(scalloc(216,240););
printStats();
void* p486 = last_address;
PRINT_POINTER(scalloc(90,119););
printStats();
void* p487 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p488 = last_address;
PRINT_POINTER(scalloc(171,134););
printStats();
void* p489 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p490 = last_address;
PRINT_POINTER(srealloc(p326,172););
printStats();
void* p491 = last_address;
DEBUG_PRINT(sfree(p403););
printStats();
PRINT_POINTER(smalloc(44););
printStats();
void* p492 = last_address;
PRINT_POINTER(scalloc(185,243););
printStats();
void* p493 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p494 = last_address;
PRINT_POINTER(srealloc(p430,92););
printStats();
void* p495 = last_address;
DEBUG_PRINT(sfree(p463););
printStats();
PRINT_POINTER(srealloc(p454,57););
printStats();
void* p496 = last_address;
DEBUG_PRINT(sfree(p329););
printStats();
PRINT_POINTER(smalloc(163););
printStats();
void* p497 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p498 = last_address;
PRINT_POINTER(scalloc(91,68););
printStats();
void* p499 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p500 = last_address;
PRINT_POINTER(srealloc(p428,5););
printStats();
void* p501 = last_address;
PRINT_POINTER(srealloc(p263,133););
printStats();
void* p502 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p503 = last_address;
PRINT_POINTER(srealloc(p471,127););
printStats();
void* p504 = last_address;
PRINT_POINTER(srealloc(p487,204););
printStats();
void* p505 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p506 = last_address;
DEBUG_PRINT(sfree(p482););
printStats();
PRINT_POINTER(scalloc(125,242););
printStats();
void* p507 = last_address;
DEBUG_PRINT(sfree(p467););
printStats();
PRINT_POINTER(srealloc(p395,15););
printStats();
void* p508 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p509 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p510 = last_address;
DEBUG_PRINT(sfree(p315););
printStats();
PRINT_POINTER(srealloc(p499,138););
printStats();
void* p511 = last_address;
DEBUG_PRINT(sfree(p414););
printStats();
DEBUG_PRINT(sfree(p341););
printStats();
PRINT_POINTER(scalloc(177,86););
printStats();
void* p512 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p513 = last_address;
PRINT_POINTER(scalloc(167,71););
printStats();
void* p514 = last_address;
DEBUG_PRINT(sfree(p231););
printStats();
PRINT_POINTER(srealloc(p440,126););
printStats();
void* p515 = last_address;
DEBUG_PRINT(sfree(p458););
printStats();
PRINT_POINTER(smalloc(201););
printStats();
void* p516 = last_address;
DEBUG_PRINT(sfree(p366););
printStats();
PRINT_POINTER(smalloc(14););
printStats();
void* p517 = last_address;
PRINT_POINTER(scalloc(71,87););
printStats();
void* p518 = last_address;
DEBUG_PRINT(sfree(p517););
printStats();
PRINT_POINTER(scalloc(5,239););
printStats();
void* p519 = last_address;
PRINT_POINTER(scalloc(58,88););
printStats();
void* p520 = last_address;
DEBUG_PRINT(sfree(p446););
printStats();
PRINT_POINTER(smalloc(198););
printStats();
void* p521 = last_address;
PRINT_POINTER(srealloc(p456,85););
printStats();
void* p522 = last_address;
PRINT_POINTER(scalloc(196,194););
printStats();
void* p523 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p524 = last_address;
PRINT_POINTER(scalloc(23,77););
printStats();
void* p525 = last_address;
PRINT_POINTER(scalloc(216,214););
printStats();
void* p526 = last_address;
PRINT_POINTER(srealloc(p521,40););
printStats();
void* p527 = last_address;
DEBUG_PRINT(sfree(p307););
printStats();
DEBUG_PRINT(sfree(p402););
printStats();
DEBUG_PRINT(sfree(p339););
printStats();
PRINT_POINTER(scalloc(22,161););
printStats();
void* p528 = last_address;
PRINT_POINTER(scalloc(142,208););
printStats();
void* p529 = last_address;
PRINT_POINTER(scalloc(180,223););
printStats();
void* p530 = last_address;
PRINT_POINTER(srealloc(p511,112););
printStats();
void* p531 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p532 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p533 = last_address;
PRINT_POINTER(scalloc(74,138););
printStats();
void* p534 = last_address;
DEBUG_PRINT(sfree(p503););
printStats();
PRINT_POINTER(srealloc(p518,39););
printStats();
void* p535 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p536 = last_address;
PRINT_POINTER(scalloc(48,8););
printStats();
void* p537 = last_address;
PRINT_POINTER(scalloc(85,92););
printStats();
void* p538 = last_address;
PRINT_POINTER(srealloc(p418,225););
printStats();
void* p539 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p540 = last_address;
PRINT_POINTER(scalloc(157,224););
printStats();
void* p541 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p542 = last_address;
PRINT_POINTER(scalloc(181,242););
printStats();
void* p543 = last_address;
PRINT_POINTER(scalloc(148,123););
printStats();
void* p544 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p545 = last_address;
DEBUG_PRINT(sfree(p442););
printStats();
DEBUG_PRINT(sfree(p81););
printStats();
PRINT_POINTER(scalloc(190,44););
printStats();
void* p546 = last_address;
PRINT_POINTER(scalloc(55,13););
printStats();
void* p547 = last_address;
PRINT_POINTER(srealloc(p268,172););
printStats();
void* p548 = last_address;
PRINT_POINTER(scalloc(81,131););
printStats();
void* p549 = last_address;
DEBUG_PRINT(sfree(p494););
printStats();
PRINT_POINTER(srealloc(p513,59););
printStats();
void* p550 = last_address;
DEBUG_PRINT(sfree(p481););
printStats();
PRINT_POINTER(srealloc(p537,115););
printStats();
void* p551 = last_address;
PRINT_POINTER(scalloc(45,46););
printStats();
void* p552 = last_address;
PRINT_POINTER(srealloc(p539,193););
printStats();
void* p553 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p554 = last_address;
PRINT_POINTER(srealloc(p522,124););
printStats();
void* p555 = last_address;
PRINT_POINTER(srealloc(p230,34););
printStats();
void* p556 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p557 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p558 = last_address;
PRINT_POINTER(scalloc(239,169););
printStats();
void* p559 = last_address;
DEBUG_PRINT(sfree(p420););
printStats();
PRINT_POINTER(scalloc(146,218););
printStats();
void* p560 = last_address;
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(smalloc(19););
printStats();
void* p561 = last_address;
DEBUG_PRINT(sfree(p354););
printStats();
PRINT_POINTER(smalloc(230););
printStats();
void* p562 = last_address;
PRINT_POINTER(scalloc(249,75););
printStats();
void* p563 = last_address;
PRINT_POINTER(srealloc(p287,197););
printStats();
void* p564 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p565 = last_address;
DEBUG_PRINT(sfree(p452););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p566 = last_address;
PRINT_POINTER(srealloc(p435,194););
printStats();
void* p567 = last_address;
PRINT_POINTER(srealloc(p479,23););
printStats();
void* p568 = last_address;
PRINT_POINTER(scalloc(241,195););
printStats();
void* p569 = last_address;
PRINT_POINTER(scalloc(195,185););
printStats();
void* p570 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p571 = last_address;
DEBUG_PRINT(sfree(p519););
printStats();
PRINT_POINTER(scalloc(107,247););
printStats();
void* p572 = last_address;
PRINT_POINTER(scalloc(135,31););
printStats();
void* p573 = last_address;
PRINT_POINTER(srealloc(p195,87););
printStats();
void* p574 = last_address;
PRINT_POINTER(srealloc(p445,136););
printStats();
void* p575 = last_address;
DEBUG_PRINT(sfree(p476););
printStats();
DEBUG_PRINT(sfree(p558););
printStats();
PRINT_POINTER(scalloc(96,50););
printStats();
void* p576 = last_address;
PRINT_POINTER(scalloc(135,159););
printStats();
void* p577 = last_address;
PRINT_POINTER(scalloc(186,224););
printStats();
void* p578 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p579 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p580 = last_address;
PRINT_POINTER(srealloc(p439,19););
printStats();
void* p581 = last_address;
DEBUG_PRINT(sfree(p392););
printStats();
DEBUG_PRINT(sfree(p475););
printStats();
PRINT_POINTER(srealloc(p532,164););
printStats();
void* p582 = last_address;
PRINT_POINTER(srealloc(p542,184););
printStats();
void* p583 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p584 = last_address;
PRINT_POINTER(srealloc(p540,12););
printStats();
void* p585 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p586 = last_address;
DEBUG_PRINT(sfree(p410););
printStats();
PRINT_POINTER(srealloc(p557,88););
printStats();
void* p587 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p588 = last_address;
DEBUG_PRINT(sfree(p372););
printStats();
PRINT_POINTER(scalloc(105,245););
printStats();
void* p589 = last_address;
PRINT_POINTER(scalloc(205,198););
printStats();
void* p590 = last_address;
PRINT_POINTER(scalloc(91,151););
printStats();
void* p591 = last_address;
PRINT_POINTER(srealloc(p549,109););
printStats();
void* p592 = last_address;
PRINT_POINTER(scalloc(166,182););
printStats();
void* p593 = last_address;
PRINT_POINTER(srealloc(p529,200););
printStats();
void* p594 = last_address;
PRINT_POINTER(scalloc(146,25););
printStats();
void* p595 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p596 = last_address;
DEBUG_PRINT(sfree(p561););
printStats();
PRINT_POINTER(scalloc(58,173););
printStats();
void* p597 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p598 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p599 = last_address;
PRINT_POINTER(srealloc(p382,92););
printStats();
void* p600 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p601 = last_address;
PRINT_POINTER(scalloc(229,110););
printStats();
void* p602 = last_address;
PRINT_POINTER(srealloc(p394,42););
printStats();
void* p603 = last_address;
PRINT_POINTER(scalloc(107,228););
printStats();
void* p604 = last_address;
PRINT_POINTER(scalloc(165,248););
printStats();
void* p605 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p606 = last_address;
PRINT_POINTER(scalloc(75,91););
printStats();
void* p607 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p608 = last_address;
PRINT_POINTER(scalloc(14,162););
printStats();
void* p609 = last_address;
PRINT_POINTER(scalloc(139,147););
printStats();
void* p610 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p611 = last_address;
PRINT_POINTER(srealloc(p551,213););
printStats();
void* p612 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p613 = last_address;
PRINT_POINTER(scalloc(23,95););
printStats();
void* p614 = last_address;
DEBUG_PRINT(sfree(p607););
printStats();
DEBUG_PRINT(sfree(p576););
printStats();
DEBUG_PRINT(sfree(p524););
printStats();
PRINT_POINTER(scalloc(225,217););
printStats();
void* p615 = last_address;
PRINT_POINTER(srealloc(p547,9););
printStats();
void* p616 = last_address;
DEBUG_PRINT(sfree(p553););
printStats();
DEBUG_PRINT(sfree(p373););
printStats();
PRINT_POINTER(smalloc(28););
printStats();
void* p617 = last_address;
DEBUG_PRINT(sfree(p489););
printStats();
PRINT_POINTER(srealloc(p465,220););
printStats();
void* p618 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p619 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p620 = last_address;
PRINT_POINTER(srealloc(p259,82););
printStats();
void* p621 = last_address;
PRINT_POINTER(scalloc(125,23););
printStats();
void* p622 = last_address;
PRINT_POINTER(scalloc(126,83););
printStats();
void* p623 = last_address;
PRINT_POINTER(scalloc(80,75););
printStats();
void* p624 = last_address;
PRINT_POINTER(srealloc(p510,187););
printStats();
void* p625 = last_address;
PRINT_POINTER(srealloc(p623,222););
printStats();
void* p626 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p627 = last_address;
}
