#include "aux_macro.h"
#include "../malloc_2.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(16););
printStats();
void* p0 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(smalloc(195););
printStats();
void* p1 = last_address;
PRINT_POINTER(scalloc(70,107););
printStats();
void* p2 = last_address;
PRINT_POINTER(srealloc(p2,136););
printStats();
void* p3 = last_address;
PRINT_POINTER(scalloc(2,204););
printStats();
void* p4 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p5 = last_address;
PRINT_POINTER(scalloc(146,238););
printStats();
void* p6 = last_address;
PRINT_POINTER(scalloc(139,171););
printStats();
void* p7 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
PRINT_POINTER(srealloc(p4,30););
printStats();
void* p8 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p9 = last_address;
DEBUG_PRINT(sfree(p9););
printStats();
PRINT_POINTER(smalloc(148););
printStats();
void* p10 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p11 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(srealloc(p11,45););
printStats();
void* p12 = last_address;
PRINT_POINTER(scalloc(37,239););
printStats();
void* p13 = last_address;
DEBUG_PRINT(sfree(p12););
printStats();
PRINT_POINTER(srealloc(p6,201););
printStats();
void* p14 = last_address;
PRINT_POINTER(scalloc(143,30););
printStats();
void* p15 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p16 = last_address;
PRINT_POINTER(srealloc(p10,95););
printStats();
void* p17 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p18 = last_address;
PRINT_POINTER(srealloc(p8,35););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p20 = last_address;
DEBUG_PRINT(sfree(p3););
printStats();
PRINT_POINTER(scalloc(217,221););
printStats();
void* p21 = last_address;
DEBUG_PRINT(sfree(p14););
printStats();
DEBUG_PRINT(sfree(p19););
printStats();
PRINT_POINTER(srealloc(p20,217););
printStats();
void* p22 = last_address;
PRINT_POINTER(scalloc(181,7););
printStats();
void* p23 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p24 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p25 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(srealloc(p25,101););
printStats();
void* p26 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(scalloc(192,38););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(smalloc(86););
printStats();
void* p28 = last_address;
PRINT_POINTER(srealloc(p5,208););
printStats();
void* p29 = last_address;
PRINT_POINTER(scalloc(210,123););
printStats();
void* p30 = last_address;
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(srealloc(p23,79););
printStats();
void* p31 = last_address;
DEBUG_PRINT(sfree(p30););
printStats();
PRINT_POINTER(smalloc(164););
printStats();
void* p32 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p33 = last_address;
PRINT_POINTER(srealloc(p18,207););
printStats();
void* p34 = last_address;
PRINT_POINTER(scalloc(90,49););
printStats();
void* p35 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p36 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(129,181););
printStats();
void* p38 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
PRINT_POINTER(srealloc(p32,215););
printStats();
void* p39 = last_address;
PRINT_POINTER(srealloc(p26,210););
printStats();
void* p40 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p41 = last_address;
PRINT_POINTER(scalloc(152,137););
printStats();
void* p42 = last_address;
PRINT_POINTER(scalloc(154,112););
printStats();
void* p43 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
DEBUG_PRINT(sfree(p39););
printStats();
PRINT_POINTER(scalloc(77,78););
printStats();
void* p44 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p45 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p46 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(scalloc(158,242););
printStats();
void* p47 = last_address;
PRINT_POINTER(srealloc(p27,56););
printStats();
void* p48 = last_address;
PRINT_POINTER(scalloc(55,0););
printStats();
void* p49 = last_address;
DEBUG_PRINT(sfree(p48););
printStats();
PRINT_POINTER(srealloc(p42,95););
printStats();
void* p50 = last_address;
PRINT_POINTER(srealloc(p46,223););
printStats();
void* p51 = last_address;
PRINT_POINTER(scalloc(139,6););
printStats();
void* p52 = last_address;
PRINT_POINTER(srealloc(p43,204););
printStats();
void* p53 = last_address;
PRINT_POINTER(scalloc(115,217););
printStats();
void* p54 = last_address;
PRINT_POINTER(srealloc(p41,170););
printStats();
void* p55 = last_address;
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(scalloc(61,89););
printStats();
void* p56 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p57 = last_address;
PRINT_POINTER(srealloc(p51,121););
printStats();
void* p58 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p59 = last_address;
PRINT_POINTER(scalloc(209,207););
printStats();
void* p60 = last_address;
PRINT_POINTER(srealloc(p55,169););
printStats();
void* p61 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(scalloc(244,75););
printStats();
void* p62 = last_address;
DEBUG_PRINT(sfree(p58););
printStats();
PRINT_POINTER(srealloc(p59,204););
printStats();
void* p63 = last_address;
PRINT_POINTER(srealloc(p31,66););
printStats();
void* p64 = last_address;
PRINT_POINTER(srealloc(p61,134););
printStats();
void* p65 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p66 = last_address;
PRINT_POINTER(scalloc(84,69););
printStats();
void* p67 = last_address;
PRINT_POINTER(scalloc(182,57););
printStats();
void* p68 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p69 = last_address;
PRINT_POINTER(scalloc(95,97););
printStats();
void* p70 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
DEBUG_PRINT(sfree(p63););
printStats();
PRINT_POINTER(smalloc(172););
printStats();
void* p71 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p72 = last_address;
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(srealloc(p53,209););
printStats();
void* p73 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p74 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(smalloc(129););
printStats();
void* p75 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(srealloc(p52,23););
printStats();
void* p76 = last_address;
PRINT_POINTER(scalloc(100,118););
printStats();
void* p77 = last_address;
PRINT_POINTER(srealloc(p35,194););
printStats();
void* p78 = last_address;
PRINT_POINTER(scalloc(116,104););
printStats();
void* p79 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p80 = last_address;
DEBUG_PRINT(sfree(p76););
printStats();
PRINT_POINTER(scalloc(18,4););
printStats();
void* p81 = last_address;
PRINT_POINTER(srealloc(p47,101););
printStats();
void* p82 = last_address;
PRINT_POINTER(scalloc(180,222););
printStats();
void* p83 = last_address;
PRINT_POINTER(scalloc(36,141););
printStats();
void* p84 = last_address;
PRINT_POINTER(scalloc(162,187););
printStats();
void* p85 = last_address;
DEBUG_PRINT(sfree(p71););
printStats();
PRINT_POINTER(srealloc(p44,146););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p62,197););
printStats();
void* p87 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p88 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p89 = last_address;
DEBUG_PRINT(sfree(p54););
printStats();
PRINT_POINTER(smalloc(176););
printStats();
void* p90 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p91 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p92 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p93 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p95 = last_address;
PRINT_POINTER(scalloc(125,241););
printStats();
void* p96 = last_address;
PRINT_POINTER(scalloc(5,208););
printStats();
void* p97 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p98 = last_address;
PRINT_POINTER(srealloc(p92,133););
printStats();
void* p99 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(smalloc(19););
printStats();
void* p100 = last_address;
PRINT_POINTER(scalloc(199,14););
printStats();
void* p101 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p102 = last_address;
PRINT_POINTER(scalloc(123,215););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p103,58););
printStats();
void* p104 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p72,107););
printStats();
void* p106 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p107 = last_address;
PRINT_POINTER(scalloc(85,208););
printStats();
void* p108 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
PRINT_POINTER(srealloc(p75,225););
printStats();
void* p109 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p110 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p111 = last_address;
PRINT_POINTER(scalloc(21,239););
printStats();
void* p112 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p113 = last_address;
PRINT_POINTER(srealloc(p45,132););
printStats();
void* p114 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
DEBUG_PRINT(sfree(p95););
printStats();
PRINT_POINTER(smalloc(86););
printStats();
void* p115 = last_address;
DEBUG_PRINT(sfree(p93););
printStats();
PRINT_POINTER(srealloc(p114,83););
printStats();
void* p116 = last_address;
PRINT_POINTER(scalloc(125,246););
printStats();
void* p117 = last_address;
DEBUG_PRINT(sfree(p106););
printStats();
PRINT_POINTER(smalloc(115););
printStats();
void* p118 = last_address;
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(srealloc(p85,60););
printStats();
void* p119 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(srealloc(p105,36););
printStats();
void* p120 = last_address;
PRINT_POINTER(scalloc(116,186););
printStats();
void* p121 = last_address;
PRINT_POINTER(srealloc(p78,125););
printStats();
void* p122 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p123 = last_address;
}
