#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(100););
printStats();
void* p0 = last_address;
PRINT_POINTER(scalloc(11,115););
printStats();
void* p1 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p2 = last_address;
PRINT_POINTER(srealloc(p1,123););
printStats();
void* p3 = last_address;
PRINT_POINTER(srealloc(p2,98););
printStats();
void* p4 = last_address;
PRINT_POINTER(scalloc(116,24););
printStats();
void* p5 = last_address;
DEBUG_PRINT(sfree(p5););
printStats();
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(smalloc(219););
printStats();
void* p6 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p7 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p8 = last_address;
PRINT_POINTER(scalloc(75,58););
printStats();
void* p9 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p10 = last_address;
DEBUG_PRINT(sfree(p9););
printStats();
PRINT_POINTER(srealloc(p7,29););
printStats();
void* p11 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p12 = last_address;
PRINT_POINTER(scalloc(16,179););
printStats();
void* p13 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p14 = last_address;
PRINT_POINTER(srealloc(p13,67););
printStats();
void* p15 = last_address;
PRINT_POINTER(scalloc(125,164););
printStats();
void* p16 = last_address;
PRINT_POINTER(scalloc(240,211););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(83,56););
printStats();
void* p18 = last_address;
PRINT_POINTER(scalloc(39,226););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p20 = last_address;
PRINT_POINTER(srealloc(p14,83););
printStats();
void* p21 = last_address;
PRINT_POINTER(scalloc(63,154););
printStats();
void* p22 = last_address;
PRINT_POINTER(srealloc(p18,233););
printStats();
void* p23 = last_address;
PRINT_POINTER(scalloc(20,8););
printStats();
void* p24 = last_address;
PRINT_POINTER(srealloc(p21,96););
printStats();
void* p25 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p23,183););
printStats();
void* p27 = last_address;
PRINT_POINTER(scalloc(207,161););
printStats();
void* p28 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(scalloc(161,118););
printStats();
void* p29 = last_address;
PRINT_POINTER(scalloc(46,239););
printStats();
void* p30 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p31 = last_address;
PRINT_POINTER(srealloc(p15,43););
printStats();
void* p32 = last_address;
DEBUG_PRINT(sfree(p27););
printStats();
PRINT_POINTER(scalloc(46,144););
printStats();
void* p33 = last_address;
PRINT_POINTER(srealloc(p24,77););
printStats();
void* p34 = last_address;
PRINT_POINTER(scalloc(231,75););
printStats();
void* p35 = last_address;
PRINT_POINTER(srealloc(p34,51););
printStats();
void* p36 = last_address;
PRINT_POINTER(srealloc(p26,32););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(47,223););
printStats();
void* p38 = last_address;
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(smalloc(215););
printStats();
void* p39 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
PRINT_POINTER(smalloc(186););
printStats();
void* p40 = last_address;
PRINT_POINTER(scalloc(242,36););
printStats();
void* p41 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(smalloc(62););
printStats();
void* p42 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p43 = last_address;
PRINT_POINTER(srealloc(p10,172););
printStats();
void* p44 = last_address;
PRINT_POINTER(scalloc(83,97););
printStats();
void* p45 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p47 = last_address;
PRINT_POINTER(scalloc(167,91););
printStats();
void* p48 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(srealloc(p32,69););
printStats();
void* p49 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p50 = last_address;
PRINT_POINTER(srealloc(p17,89););
printStats();
void* p51 = last_address;
PRINT_POINTER(srealloc(p47,230););
printStats();
void* p52 = last_address;
PRINT_POINTER(scalloc(195,126););
printStats();
void* p53 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p54 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(scalloc(134,37););
printStats();
void* p55 = last_address;
PRINT_POINTER(srealloc(p44,140););
printStats();
void* p56 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p57 = last_address;
DEBUG_PRINT(sfree(p55););
printStats();
PRINT_POINTER(srealloc(p54,18););
printStats();
void* p58 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p59 = last_address;
PRINT_POINTER(srealloc(p25,239););
printStats();
void* p60 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
PRINT_POINTER(srealloc(p45,95););
printStats();
void* p61 = last_address;
DEBUG_PRINT(sfree(p19););
printStats();
PRINT_POINTER(scalloc(103,245););
printStats();
void* p62 = last_address;
PRINT_POINTER(scalloc(147,225););
printStats();
void* p63 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(scalloc(227,111););
printStats();
void* p64 = last_address;
PRINT_POINTER(scalloc(13,204););
printStats();
void* p65 = last_address;
PRINT_POINTER(srealloc(p6,163););
printStats();
void* p66 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
PRINT_POINTER(srealloc(p53,187););
printStats();
void* p67 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
PRINT_POINTER(smalloc(65););
printStats();
void* p68 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p69 = last_address;
DEBUG_PRINT(sfree(p63););
printStats();
DEBUG_PRINT(sfree(p29););
printStats();
PRINT_POINTER(scalloc(88,51););
printStats();
void* p70 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p71 = last_address;
PRINT_POINTER(scalloc(45,1););
printStats();
void* p72 = last_address;
DEBUG_PRINT(sfree(p58););
printStats();
DEBUG_PRINT(sfree(p20););
printStats();
PRINT_POINTER(srealloc(p30,47););
printStats();
void* p73 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p74 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p75 = last_address;
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(smalloc(127););
printStats();
void* p76 = last_address;
PRINT_POINTER(srealloc(p60,140););
printStats();
void* p77 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p78 = last_address;
PRINT_POINTER(srealloc(p78,103););
printStats();
void* p79 = last_address;
PRINT_POINTER(srealloc(p3,72););
printStats();
void* p80 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p81 = last_address;
PRINT_POINTER(srealloc(p65,212););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p83 = last_address;
PRINT_POINTER(scalloc(189,12););
printStats();
void* p84 = last_address;
DEBUG_PRINT(sfree(p75););
printStats();
DEBUG_PRINT(sfree(p36););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p85 = last_address;
PRINT_POINTER(srealloc(p82,215););
printStats();
void* p86 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p87 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p88 = last_address;
PRINT_POINTER(srealloc(p71,155););
printStats();
void* p89 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p90 = last_address;
PRINT_POINTER(scalloc(229,41););
printStats();
void* p91 = last_address;
PRINT_POINTER(scalloc(23,62););
printStats();
void* p92 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p93 = last_address;
PRINT_POINTER(srealloc(p77,38););
printStats();
void* p94 = last_address;
PRINT_POINTER(srealloc(p43,194););
printStats();
void* p95 = last_address;
PRINT_POINTER(scalloc(114,177););
printStats();
void* p96 = last_address;
PRINT_POINTER(srealloc(p83,38););
printStats();
void* p97 = last_address;
PRINT_POINTER(scalloc(155,101););
printStats();
void* p98 = last_address;
PRINT_POINTER(srealloc(p81,228););
printStats();
void* p99 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p100 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
DEBUG_PRINT(sfree(p56););
printStats();
PRINT_POINTER(smalloc(190););
printStats();
void* p101 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
DEBUG_PRINT(sfree(p87););
printStats();
PRINT_POINTER(srealloc(p84,12););
printStats();
void* p102 = last_address;
PRINT_POINTER(srealloc(p74,231););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p48,238););
printStats();
void* p104 = last_address;
PRINT_POINTER(scalloc(209,96););
printStats();
void* p105 = last_address;
DEBUG_PRINT(sfree(p101););
printStats();
DEBUG_PRINT(sfree(p31););
printStats();
PRINT_POINTER(srealloc(p91,127););
printStats();
void* p106 = last_address;
PRINT_POINTER(srealloc(p88,44););
printStats();
void* p107 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p108 = last_address;
PRINT_POINTER(srealloc(p72,179););
printStats();
void* p109 = last_address;
DEBUG_PRINT(sfree(p96););
printStats();
PRINT_POINTER(scalloc(197,133););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p12,12););
printStats();
void* p111 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p49,120););
printStats();
void* p113 = last_address;
DEBUG_PRINT(sfree(p86););
printStats();
DEBUG_PRINT(sfree(p110););
printStats();
PRINT_POINTER(smalloc(117););
printStats();
void* p114 = last_address;
PRINT_POINTER(scalloc(11,73););
printStats();
void* p115 = last_address;
DEBUG_PRINT(sfree(p57););
printStats();
PRINT_POINTER(scalloc(82,57););
printStats();
void* p116 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p117 = last_address;
PRINT_POINTER(srealloc(p112,237););
printStats();
void* p118 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p119 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(srealloc(p93,75););
printStats();
void* p120 = last_address;
DEBUG_PRINT(sfree(p111););
printStats();
DEBUG_PRINT(sfree(p115););
printStats();
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(srealloc(p40,223););
printStats();
void* p121 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p122 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p123 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p124 = last_address;
PRINT_POINTER(srealloc(p103,182););
printStats();
void* p125 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p126 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p127 = last_address;
DEBUG_PRINT(sfree(p99););
printStats();
PRINT_POINTER(scalloc(56,179););
printStats();
void* p128 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(scalloc(98,182););
printStats();
void* p129 = last_address;
PRINT_POINTER(srealloc(p98,51););
printStats();
void* p130 = last_address;
PRINT_POINTER(scalloc(9,55););
printStats();
void* p131 = last_address;
PRINT_POINTER(srealloc(p76,83););
printStats();
void* p132 = last_address;
DEBUG_PRINT(sfree(p79););
printStats();
PRINT_POINTER(scalloc(186,195););
printStats();
void* p133 = last_address;
DEBUG_PRINT(sfree(p107););
printStats();
PRINT_POINTER(smalloc(176););
printStats();
void* p134 = last_address;
PRINT_POINTER(scalloc(5,24););
printStats();
void* p135 = last_address;
PRINT_POINTER(scalloc(214,74););
printStats();
void* p136 = last_address;
PRINT_POINTER(scalloc(177,54););
printStats();
void* p137 = last_address;
PRINT_POINTER(srealloc(p126,238););
printStats();
void* p138 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p139 = last_address;
PRINT_POINTER(srealloc(p102,126););
printStats();
void* p140 = last_address;
PRINT_POINTER(srealloc(p108,55););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p35,200););
printStats();
void* p142 = last_address;
DEBUG_PRINT(sfree(p42););
printStats();
PRINT_POINTER(smalloc(62););
printStats();
void* p143 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p144 = last_address;
DEBUG_PRINT(sfree(p52););
printStats();
PRINT_POINTER(srealloc(p132,91););
printStats();
void* p145 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p146 = last_address;
PRINT_POINTER(srealloc(p80,153););
printStats();
void* p147 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(scalloc(1,14););
printStats();
void* p148 = last_address;
PRINT_POINTER(srealloc(p113,219););
printStats();
void* p149 = last_address;
PRINT_POINTER(scalloc(182,84););
printStats();
void* p150 = last_address;
PRINT_POINTER(scalloc(62,16););
printStats();
void* p151 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(scalloc(55,47););
printStats();
void* p152 = last_address;
PRINT_POINTER(scalloc(212,12););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(57,69););
printStats();
void* p154 = last_address;
PRINT_POINTER(srealloc(p61,49););
printStats();
void* p155 = last_address;
PRINT_POINTER(srealloc(p141,89););
printStats();
void* p156 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p157 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p158 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p159 = last_address;
PRINT_POINTER(scalloc(156,32););
printStats();
void* p160 = last_address;
DEBUG_PRINT(sfree(p106););
printStats();
PRINT_POINTER(smalloc(165););
printStats();
void* p161 = last_address;
DEBUG_PRINT(sfree(p143););
printStats();
DEBUG_PRINT(sfree(p121););
printStats();
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(scalloc(185,191););
printStats();
void* p162 = last_address;
DEBUG_PRINT(sfree(p138););
printStats();
PRINT_POINTER(smalloc(182););
printStats();
void* p163 = last_address;
PRINT_POINTER(scalloc(132,45););
printStats();
void* p164 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p165 = last_address;
PRINT_POINTER(scalloc(141,241););
printStats();
void* p166 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p167 = last_address;
PRINT_POINTER(srealloc(p146,76););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(205,206););
printStats();
void* p169 = last_address;
PRINT_POINTER(srealloc(p117,33););
printStats();
void* p170 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p171 = last_address;
DEBUG_PRINT(sfree(p125););
printStats();
PRINT_POINTER(scalloc(85,240););
printStats();
void* p172 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p173 = last_address;
PRINT_POINTER(srealloc(p123,175););
printStats();
void* p174 = last_address;
PRINT_POINTER(srealloc(p120,68););
printStats();
void* p175 = last_address;
PRINT_POINTER(scalloc(209,110););
printStats();
void* p176 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(srealloc(p153,41););
printStats();
void* p177 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p178 = last_address;
PRINT_POINTER(scalloc(168,155););
printStats();
void* p179 = last_address;
DEBUG_PRINT(sfree(p67););
printStats();
PRINT_POINTER(srealloc(p140,1););
printStats();
void* p180 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p181 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p182 = last_address;
DEBUG_PRINT(sfree(p168););
printStats();
PRINT_POINTER(smalloc(60););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(213,201););
printStats();
void* p184 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p185 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p186 = last_address;
DEBUG_PRINT(sfree(p137););
printStats();
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(smalloc(128););
printStats();
void* p187 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(smalloc(92););
printStats();
void* p188 = last_address;
PRINT_POINTER(srealloc(p154,133););
printStats();
void* p189 = last_address;
PRINT_POINTER(srealloc(p165,67););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p191 = last_address;
PRINT_POINTER(scalloc(40,157););
printStats();
void* p192 = last_address;
PRINT_POINTER(srealloc(p170,24););
printStats();
void* p193 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p194 = last_address;
PRINT_POINTER(scalloc(73,191););
printStats();
void* p195 = last_address;
PRINT_POINTER(scalloc(231,83););
printStats();
void* p196 = last_address;
PRINT_POINTER(scalloc(118,159););
printStats();
void* p197 = last_address;
PRINT_POINTER(srealloc(p131,82););
printStats();
void* p198 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p199 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p200 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p201 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p202 = last_address;
PRINT_POINTER(srealloc(p164,187););
printStats();
void* p203 = last_address;
PRINT_POINTER(srealloc(p179,235););
printStats();
void* p204 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p205 = last_address;
PRINT_POINTER(srealloc(p145,177););
printStats();
void* p206 = last_address;
PRINT_POINTER(srealloc(p62,123););
printStats();
void* p207 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p208 = last_address;
PRINT_POINTER(scalloc(203,110););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(15,14););
printStats();
void* p210 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p211 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p212 = last_address;
DEBUG_PRINT(sfree(p194););
printStats();
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(srealloc(p139,221););
printStats();
void* p213 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(smalloc(169););
printStats();
void* p214 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(srealloc(p207,75););
printStats();
void* p215 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
PRINT_POINTER(scalloc(182,77););
printStats();
void* p216 = last_address;
PRINT_POINTER(srealloc(p70,51););
printStats();
void* p217 = last_address;
DEBUG_PRINT(sfree(p211););
printStats();
PRINT_POINTER(smalloc(143););
printStats();
void* p218 = last_address;
PRINT_POINTER(scalloc(158,144););
printStats();
void* p219 = last_address;
DEBUG_PRINT(sfree(p219););
printStats();
PRINT_POINTER(scalloc(224,98););
printStats();
void* p220 = last_address;
PRINT_POINTER(srealloc(p167,198););
printStats();
void* p221 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p222 = last_address;
PRINT_POINTER(scalloc(20,60););
printStats();
void* p223 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p224 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p225 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p226 = last_address;
PRINT_POINTER(scalloc(103,116););
printStats();
void* p227 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p228 = last_address;
PRINT_POINTER(scalloc(35,106););
printStats();
void* p229 = last_address;
PRINT_POINTER(scalloc(243,184););
printStats();
void* p230 = last_address;
PRINT_POINTER(srealloc(p158,228););
printStats();
void* p231 = last_address;
PRINT_POINTER(srealloc(p212,246););
printStats();
void* p232 = last_address;
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(srealloc(p191,95););
printStats();
void* p233 = last_address;
DEBUG_PRINT(sfree(p155););
printStats();
PRINT_POINTER(scalloc(230,121););
printStats();
void* p234 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(srealloc(p221,182););
printStats();
void* p235 = last_address;
PRINT_POINTER(scalloc(177,83););
printStats();
void* p236 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p237 = last_address;
DEBUG_PRINT(sfree(p226););
printStats();
PRINT_POINTER(scalloc(62,70););
printStats();
void* p238 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p239 = last_address;
PRINT_POINTER(scalloc(214,16););
printStats();
void* p240 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p241 = last_address;
PRINT_POINTER(scalloc(118,47););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(smalloc(229););
printStats();
void* p243 = last_address;
PRINT_POINTER(srealloc(p136,217););
printStats();
void* p244 = last_address;
PRINT_POINTER(srealloc(p237,89););
printStats();
void* p245 = last_address;
PRINT_POINTER(scalloc(202,33););
printStats();
void* p246 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p247 = last_address;
PRINT_POINTER(srealloc(p198,110););
printStats();
void* p248 = last_address;
PRINT_POINTER(scalloc(51,2););
printStats();
void* p249 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p250 = last_address;
PRINT_POINTER(scalloc(62,243););
printStats();
void* p251 = last_address;
DEBUG_PRINT(sfree(p189););
printStats();
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(smalloc(182););
printStats();
void* p252 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p253 = last_address;
DEBUG_PRINT(sfree(p232););
printStats();
PRINT_POINTER(srealloc(p183,135););
printStats();
void* p254 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p255 = last_address;
PRINT_POINTER(scalloc(144,223););
printStats();
void* p256 = last_address;
DEBUG_PRINT(sfree(p171););
printStats();
PRINT_POINTER(srealloc(p163,188););
printStats();
void* p257 = last_address;
PRINT_POINTER(scalloc(147,49););
printStats();
void* p258 = last_address;
DEBUG_PRINT(sfree(p160););
printStats();
PRINT_POINTER(smalloc(164););
printStats();
void* p259 = last_address;
PRINT_POINTER(scalloc(214,166););
printStats();
void* p260 = last_address;
PRINT_POINTER(srealloc(p148,96););
printStats();
void* p261 = last_address;
PRINT_POINTER(srealloc(p217,52););
printStats();
void* p262 = last_address;
PRINT_POINTER(srealloc(p241,120););
printStats();
void* p263 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p264 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p265 = last_address;
DEBUG_PRINT(sfree(p130););
printStats();
PRINT_POINTER(scalloc(169,148););
printStats();
void* p266 = last_address;
PRINT_POINTER(scalloc(96,233););
printStats();
void* p267 = last_address;
PRINT_POINTER(scalloc(171,183););
printStats();
void* p268 = last_address;
PRINT_POINTER(scalloc(181,238););
printStats();
void* p269 = last_address;
DEBUG_PRINT(sfree(p244););
printStats();
PRINT_POINTER(scalloc(59,104););
printStats();
void* p270 = last_address;
PRINT_POINTER(srealloc(p245,224););
printStats();
void* p271 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p272 = last_address;
PRINT_POINTER(srealloc(p270,171););
printStats();
void* p273 = last_address;
PRINT_POINTER(scalloc(133,50););
printStats();
void* p274 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p275 = last_address;
PRINT_POINTER(scalloc(107,74););
printStats();
void* p276 = last_address;
DEBUG_PRINT(sfree(p273););
printStats();
PRINT_POINTER(srealloc(p105,1););
printStats();
void* p277 = last_address;
PRINT_POINTER(scalloc(183,89););
printStats();
void* p278 = last_address;
PRINT_POINTER(srealloc(p235,69););
printStats();
void* p279 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
DEBUG_PRINT(sfree(p73););
printStats();
PRINT_POINTER(smalloc(217););
printStats();
void* p280 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
PRINT_POINTER(scalloc(249,19););
printStats();
void* p281 = last_address;
DEBUG_PRINT(sfree(p92););
printStats();
PRINT_POINTER(srealloc(p246,20););
printStats();
void* p282 = last_address;
PRINT_POINTER(scalloc(21,124););
printStats();
void* p283 = last_address;
PRINT_POINTER(scalloc(7,73););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p275,197););
printStats();
void* p285 = last_address;
DEBUG_PRINT(sfree(p156););
printStats();
PRINT_POINTER(scalloc(52,4););
printStats();
void* p286 = last_address;
PRINT_POINTER(srealloc(p225,218););
printStats();
void* p287 = last_address;
PRINT_POINTER(scalloc(25,106););
printStats();
void* p288 = last_address;
PRINT_POINTER(scalloc(128,47););
printStats();
void* p289 = last_address;
PRINT_POINTER(scalloc(134,246););
printStats();
void* p290 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p291 = last_address;
DEBUG_PRINT(sfree(p169););
printStats();
PRINT_POINTER(scalloc(112,80););
printStats();
void* p292 = last_address;
PRINT_POINTER(scalloc(83,67););
printStats();
void* p293 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p294 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p295 = last_address;
PRINT_POINTER(srealloc(p289,57););
printStats();
void* p296 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p297 = last_address;
PRINT_POINTER(scalloc(44,96););
printStats();
void* p298 = last_address;
PRINT_POINTER(scalloc(134,224););
printStats();
void* p299 = last_address;
PRINT_POINTER(srealloc(p231,64););
printStats();
void* p300 = last_address;
PRINT_POINTER(srealloc(p286,224););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p302 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p303 = last_address;
PRINT_POINTER(scalloc(38,148););
printStats();
void* p304 = last_address;
PRINT_POINTER(scalloc(180,22););
printStats();
void* p305 = last_address;
DEBUG_PRINT(sfree(p262););
printStats();
PRINT_POINTER(scalloc(132,129););
printStats();
void* p306 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p307 = last_address;
DEBUG_PRINT(sfree(p233););
printStats();
PRINT_POINTER(scalloc(35,155););
printStats();
void* p308 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p309 = last_address;
PRINT_POINTER(srealloc(p290,55););
printStats();
void* p310 = last_address;
PRINT_POINTER(scalloc(202,234););
printStats();
void* p311 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p312 = last_address;
PRINT_POINTER(scalloc(93,207););
printStats();
void* p313 = last_address;
PRINT_POINTER(srealloc(p178,77););
printStats();
void* p314 = last_address;
PRINT_POINTER(scalloc(197,159););
printStats();
void* p315 = last_address;
PRINT_POINTER(srealloc(p312,99););
printStats();
void* p316 = last_address;
PRINT_POINTER(scalloc(175,45););
printStats();
void* p317 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p318 = last_address;
PRINT_POINTER(srealloc(p317,107););
printStats();
void* p319 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p320 = last_address;
DEBUG_PRINT(sfree(p253););
printStats();
PRINT_POINTER(srealloc(p187,157););
printStats();
void* p321 = last_address;
PRINT_POINTER(srealloc(p311,73););
printStats();
void* p322 = last_address;
PRINT_POINTER(srealloc(p291,6););
printStats();
void* p323 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p324 = last_address;
DEBUG_PRINT(sfree(p278););
printStats();
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(smalloc(143););
printStats();
void* p325 = last_address;
PRINT_POINTER(srealloc(p267,149););
printStats();
void* p326 = last_address;
PRINT_POINTER(srealloc(p269,111););
printStats();
void* p327 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
PRINT_POINTER(smalloc(229););
printStats();
void* p328 = last_address;
PRINT_POINTER(scalloc(237,158););
printStats();
void* p329 = last_address;
PRINT_POINTER(srealloc(p306,155););
printStats();
void* p330 = last_address;
PRINT_POINTER(scalloc(223,241););
printStats();
void* p331 = last_address;
PRINT_POINTER(srealloc(p292,214););
printStats();
void* p332 = last_address;
PRINT_POINTER(scalloc(214,47););
printStats();
void* p333 = last_address;
PRINT_POINTER(scalloc(73,116););
printStats();
void* p334 = last_address;
PRINT_POINTER(scalloc(77,116););
printStats();
void* p335 = last_address;
PRINT_POINTER(srealloc(p300,214););
printStats();
void* p336 = last_address;
PRINT_POINTER(scalloc(237,39););
printStats();
void* p337 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
DEBUG_PRINT(sfree(p285););
printStats();
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(scalloc(103,208););
printStats();
void* p338 = last_address;
PRINT_POINTER(scalloc(114,95););
printStats();
void* p339 = last_address;
PRINT_POINTER(scalloc(105,5););
printStats();
void* p340 = last_address;
DEBUG_PRINT(sfree(p256););
printStats();
DEBUG_PRINT(sfree(p319););
printStats();
PRINT_POINTER(scalloc(184,114););
printStats();
void* p341 = last_address;
PRINT_POINTER(scalloc(38,117););
printStats();
void* p342 = last_address;
PRINT_POINTER(scalloc(225,112););
printStats();
void* p343 = last_address;
PRINT_POINTER(srealloc(p177,194););
printStats();
void* p344 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p345 = last_address;
PRINT_POINTER(scalloc(91,211););
printStats();
void* p346 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p347 = last_address;
DEBUG_PRINT(sfree(p161););
printStats();
DEBUG_PRINT(sfree(p243););
printStats();
PRINT_POINTER(scalloc(244,208););
printStats();
void* p348 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p349 = last_address;
DEBUG_PRINT(sfree(p247););
printStats();
PRINT_POINTER(srealloc(p195,6););
printStats();
void* p350 = last_address;
PRINT_POINTER(srealloc(p293,104););
printStats();
void* p351 = last_address;
PRINT_POINTER(scalloc(191,159););
printStats();
void* p352 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p353 = last_address;
DEBUG_PRINT(sfree(p343););
printStats();
DEBUG_PRINT(sfree(p297););
printStats();
PRINT_POINTER(srealloc(p209,120););
printStats();
void* p354 = last_address;
DEBUG_PRINT(sfree(p128););
printStats();
PRINT_POINTER(smalloc(194););
printStats();
void* p355 = last_address;
PRINT_POINTER(srealloc(p347,175););
printStats();
void* p356 = last_address;
PRINT_POINTER(scalloc(73,24););
printStats();
void* p357 = last_address;
PRINT_POINTER(scalloc(79,95););
printStats();
void* p358 = last_address;
PRINT_POINTER(scalloc(3,1););
printStats();
void* p359 = last_address;
DEBUG_PRINT(sfree(p351););
printStats();
DEBUG_PRINT(sfree(p280););
printStats();
PRINT_POINTER(scalloc(11,228););
printStats();
void* p360 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p361 = last_address;
DEBUG_PRINT(sfree(p249););
printStats();
PRINT_POINTER(scalloc(9,170););
printStats();
void* p362 = last_address;
PRINT_POINTER(srealloc(p229,136););
printStats();
void* p363 = last_address;
PRINT_POINTER(srealloc(p192,207););
printStats();
void* p364 = last_address;
PRINT_POINTER(scalloc(222,169););
printStats();
void* p365 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p366 = last_address;
PRINT_POINTER(scalloc(31,87););
printStats();
void* p367 = last_address;
PRINT_POINTER(scalloc(79,210););
printStats();
void* p368 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p369 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
PRINT_POINTER(srealloc(p349,177););
printStats();
void* p370 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p371 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p372 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p373 = last_address;
PRINT_POINTER(srealloc(p242,75););
printStats();
void* p374 = last_address;
PRINT_POINTER(srealloc(p252,235););
printStats();
void* p375 = last_address;
DEBUG_PRINT(sfree(p338););
printStats();
PRINT_POINTER(smalloc(46););
printStats();
void* p376 = last_address;
PRINT_POINTER(srealloc(p151,65););
printStats();
void* p377 = last_address;
PRINT_POINTER(srealloc(p325,236););
printStats();
void* p378 = last_address;
DEBUG_PRINT(sfree(p299););
printStats();
PRINT_POINTER(srealloc(p202,228););
printStats();
void* p379 = last_address;
PRINT_POINTER(scalloc(131,29););
printStats();
void* p380 = last_address;
DEBUG_PRINT(sfree(p378););
printStats();
PRINT_POINTER(scalloc(209,93););
printStats();
void* p381 = last_address;
PRINT_POINTER(scalloc(172,44););
printStats();
void* p382 = last_address;
PRINT_POINTER(srealloc(p364,143););
printStats();
void* p383 = last_address;
PRINT_POINTER(srealloc(p66,128););
printStats();
void* p384 = last_address;
DEBUG_PRINT(sfree(p288););
printStats();
PRINT_POINTER(srealloc(p142,239););
printStats();
void* p385 = last_address;
PRINT_POINTER(srealloc(p196,170););
printStats();
void* p386 = last_address;
PRINT_POINTER(scalloc(50,5););
printStats();
void* p387 = last_address;
PRINT_POINTER(scalloc(209,144););
printStats();
void* p388 = last_address;
PRINT_POINTER(scalloc(5,221););
printStats();
void* p389 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p390 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p391 = last_address;
PRINT_POINTER(scalloc(110,233););
printStats();
void* p392 = last_address;
PRINT_POINTER(scalloc(176,124););
printStats();
void* p393 = last_address;
PRINT_POINTER(srealloc(p277,95););
printStats();
void* p394 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p395 = last_address;
DEBUG_PRINT(sfree(p266););
printStats();
PRINT_POINTER(srealloc(p162,168););
printStats();
void* p396 = last_address;
DEBUG_PRINT(sfree(p257););
printStats();
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(smalloc(132););
printStats();
void* p397 = last_address;
PRINT_POINTER(scalloc(203,23););
printStats();
void* p398 = last_address;
PRINT_POINTER(srealloc(p176,176););
printStats();
void* p399 = last_address;
PRINT_POINTER(srealloc(p399,92););
printStats();
void* p400 = last_address;
PRINT_POINTER(srealloc(p369,200););
printStats();
void* p401 = last_address;
PRINT_POINTER(srealloc(p152,152););
printStats();
void* p402 = last_address;
PRINT_POINTER(srealloc(p224,29););
printStats();
void* p403 = last_address;
PRINT_POINTER(srealloc(p222,18););
printStats();
void* p404 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p405 = last_address;
PRINT_POINTER(scalloc(106,241););
printStats();
void* p406 = last_address;
PRINT_POINTER(scalloc(86,8););
printStats();
void* p407 = last_address;
DEBUG_PRINT(sfree(p397););
printStats();
PRINT_POINTER(scalloc(123,221););
printStats();
void* p408 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p409 = last_address;
PRINT_POINTER(scalloc(23,96););
printStats();
void* p410 = last_address;
DEBUG_PRINT(sfree(p377););
printStats();
PRINT_POINTER(scalloc(180,129););
printStats();
void* p411 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p412 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p413 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p414 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p415 = last_address;
PRINT_POINTER(scalloc(244,114););
printStats();
void* p416 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p417 = last_address;
DEBUG_PRINT(sfree(p213););
printStats();
PRINT_POINTER(smalloc(84););
printStats();
void* p418 = last_address;
PRINT_POINTER(scalloc(240,130););
printStats();
void* p419 = last_address;
PRINT_POINTER(srealloc(p335,77););
printStats();
void* p420 = last_address;
PRINT_POINTER(srealloc(p409,121););
printStats();
void* p421 = last_address;
PRINT_POINTER(scalloc(40,183););
printStats();
void* p422 = last_address;
DEBUG_PRINT(sfree(p302););
printStats();
PRINT_POINTER(srealloc(p284,81););
printStats();
void* p423 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p424 = last_address;
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(scalloc(211,187););
printStats();
void* p425 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p426 = last_address;
PRINT_POINTER(srealloc(p308,239););
printStats();
void* p427 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p428 = last_address;
DEBUG_PRINT(sfree(p234););
printStats();
PRINT_POINTER(srealloc(p336,105););
printStats();
void* p429 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p430 = last_address;
PRINT_POINTER(srealloc(p260,106););
printStats();
void* p431 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p432 = last_address;
DEBUG_PRINT(sfree(p422););
printStats();
PRINT_POINTER(smalloc(132););
printStats();
void* p433 = last_address;
PRINT_POINTER(srealloc(p390,199););
printStats();
void* p434 = last_address;
PRINT_POINTER(srealloc(p342,92););
printStats();
void* p435 = last_address;
PRINT_POINTER(scalloc(247,0););
printStats();
void* p436 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p437 = last_address;
PRINT_POINTER(srealloc(p362,198););
printStats();
void* p438 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p439 = last_address;
PRINT_POINTER(scalloc(200,63););
printStats();
void* p440 = last_address;
PRINT_POINTER(scalloc(65,222););
printStats();
void* p441 = last_address;
PRINT_POINTER(scalloc(47,130););
printStats();
void* p442 = last_address;
PRINT_POINTER(srealloc(p340,115););
printStats();
void* p443 = last_address;
PRINT_POINTER(scalloc(176,1););
printStats();
void* p444 = last_address;
DEBUG_PRINT(sfree(p180););
printStats();
PRINT_POINTER(scalloc(239,164););
printStats();
void* p445 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p446 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p447 = last_address;
DEBUG_PRINT(sfree(p348););
printStats();
PRINT_POINTER(srealloc(p268,107););
printStats();
void* p448 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p449 = last_address;
PRINT_POINTER(srealloc(p227,28););
printStats();
void* p450 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p451 = last_address;
PRINT_POINTER(srealloc(p361,66););
printStats();
void* p452 = last_address;
PRINT_POINTER(srealloc(p346,151););
printStats();
void* p453 = last_address;
PRINT_POINTER(smalloc(221););
printStats();
void* p454 = last_address;
DEBUG_PRINT(sfree(p416););
printStats();
PRINT_POINTER(srealloc(p276,27););
printStats();
void* p455 = last_address;
DEBUG_PRINT(sfree(p337););
printStats();
PRINT_POINTER(smalloc(209););
printStats();
void* p456 = last_address;
PRINT_POINTER(srealloc(p421,205););
printStats();
void* p457 = last_address;
DEBUG_PRINT(sfree(p402););
printStats();
PRINT_POINTER(srealloc(p406,89););
printStats();
void* p458 = last_address;
DEBUG_PRINT(sfree(p412););
printStats();
PRINT_POINTER(scalloc(182,3););
printStats();
void* p459 = last_address;
PRINT_POINTER(scalloc(35,115););
printStats();
void* p460 = last_address;
DEBUG_PRINT(sfree(p200););
printStats();
PRINT_POINTER(srealloc(p206,72););
printStats();
void* p461 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p462 = last_address;
PRINT_POINTER(scalloc(29,170););
printStats();
void* p463 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p464 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p465 = last_address;
PRINT_POINTER(scalloc(192,179););
printStats();
void* p466 = last_address;
PRINT_POINTER(srealloc(p389,75););
printStats();
void* p467 = last_address;
PRINT_POINTER(scalloc(58,241););
printStats();
void* p468 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p469 = last_address;
PRINT_POINTER(scalloc(135,211););
printStats();
void* p470 = last_address;
DEBUG_PRINT(sfree(p215););
printStats();
DEBUG_PRINT(sfree(p367););
printStats();
PRINT_POINTER(srealloc(p439,34););
printStats();
void* p471 = last_address;
DEBUG_PRINT(sfree(p461););
printStats();
PRINT_POINTER(smalloc(137););
printStats();
void* p472 = last_address;
PRINT_POINTER(scalloc(65,107););
printStats();
void* p473 = last_address;
PRINT_POINTER(srealloc(p129,82););
printStats();
void* p474 = last_address;
DEBUG_PRINT(sfree(p201););
printStats();
DEBUG_PRINT(sfree(p295););
printStats();
PRINT_POINTER(srealloc(p95,87););
printStats();
void* p475 = last_address;
PRINT_POINTER(srealloc(p445,10););
printStats();
void* p476 = last_address;
PRINT_POINTER(srealloc(p228,119););
printStats();
void* p477 = last_address;
PRINT_POINTER(srealloc(p474,153););
printStats();
void* p478 = last_address;
PRINT_POINTER(srealloc(p380,240););
printStats();
void* p479 = last_address;
DEBUG_PRINT(sfree(p404););
printStats();
PRINT_POINTER(smalloc(100););
printStats();
void* p480 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p481 = last_address;
DEBUG_PRINT(sfree(p407););
printStats();
PRINT_POINTER(smalloc(57););
printStats();
void* p482 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p483 = last_address;
PRINT_POINTER(srealloc(p469,179););
printStats();
void* p484 = last_address;
PRINT_POINTER(srealloc(p248,193););
printStats();
void* p485 = last_address;
PRINT_POINTER(srealloc(p315,36););
printStats();
void* p486 = last_address;
PRINT_POINTER(scalloc(227,186););
printStats();
void* p487 = last_address;
DEBUG_PRINT(sfree(p333););
printStats();
PRINT_POINTER(srealloc(p360,112););
printStats();
void* p488 = last_address;
PRINT_POINTER(srealloc(p447,138););
printStats();
void* p489 = last_address;
DEBUG_PRINT(sfree(p430););
printStats();
PRINT_POINTER(smalloc(169););
printStats();
void* p490 = last_address;
PRINT_POINTER(srealloc(p432,178););
printStats();
void* p491 = last_address;
PRINT_POINTER(srealloc(p424,90););
printStats();
void* p492 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p493 = last_address;
DEBUG_PRINT(sfree(p157););
printStats();
PRINT_POINTER(smalloc(58););
printStats();
void* p494 = last_address;
DEBUG_PRINT(sfree(p135););
printStats();
DEBUG_PRINT(sfree(p462););
printStats();
PRINT_POINTER(smalloc(57););
printStats();
void* p495 = last_address;
DEBUG_PRINT(sfree(p326););
printStats();
PRINT_POINTER(srealloc(p365,152););
printStats();
void* p496 = last_address;
PRINT_POINTER(srealloc(p493,89););
printStats();
void* p497 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p498 = last_address;
PRINT_POINTER(scalloc(121,29););
printStats();
void* p499 = last_address;
DEBUG_PRINT(sfree(p443););
printStats();
PRINT_POINTER(smalloc(210););
printStats();
void* p500 = last_address;
PRINT_POINTER(scalloc(14,229););
printStats();
void* p501 = last_address;
PRINT_POINTER(srealloc(p455,64););
printStats();
void* p502 = last_address;
PRINT_POINTER(srealloc(p491,184););
printStats();
void* p503 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p504 = last_address;
PRINT_POINTER(srealloc(p354,194););
printStats();
void* p505 = last_address;
DEBUG_PRINT(sfree(p353););
printStats();
PRINT_POINTER(srealloc(p485,209););
printStats();
void* p506 = last_address;
DEBUG_PRINT(sfree(p304););
printStats();
PRINT_POINTER(smalloc(13););
printStats();
void* p507 = last_address;
PRINT_POINTER(srealloc(p322,40););
printStats();
void* p508 = last_address;
PRINT_POINTER(srealloc(p501,77););
printStats();
void* p509 = last_address;
DEBUG_PRINT(sfree(p329););
printStats();
PRINT_POINTER(scalloc(179,47););
printStats();
void* p510 = last_address;
PRINT_POINTER(scalloc(195,57););
printStats();
void* p511 = last_address;
PRINT_POINTER(srealloc(p133,23););
printStats();
void* p512 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p513 = last_address;
DEBUG_PRINT(sfree(p374););
printStats();
PRINT_POINTER(srealloc(p434,196););
printStats();
void* p514 = last_address;
DEBUG_PRINT(sfree(p383););
printStats();
PRINT_POINTER(smalloc(118););
printStats();
void* p515 = last_address;
DEBUG_PRINT(sfree(p496););
printStats();
PRINT_POINTER(smalloc(141););
printStats();
void* p516 = last_address;
PRINT_POINTER(scalloc(1,63););
printStats();
void* p517 = last_address;
PRINT_POINTER(scalloc(155,142););
printStats();
void* p518 = last_address;
PRINT_POINTER(srealloc(p433,200););
printStats();
void* p519 = last_address;
DEBUG_PRINT(sfree(p508););
printStats();
DEBUG_PRINT(sfree(p279););
printStats();
PRINT_POINTER(scalloc(43,44););
printStats();
void* p520 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p521 = last_address;
PRINT_POINTER(srealloc(p456,190););
printStats();
void* p522 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p523 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p524 = last_address;
PRINT_POINTER(scalloc(230,122););
printStats();
void* p525 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p526 = last_address;
PRINT_POINTER(scalloc(147,153););
printStats();
void* p527 = last_address;
PRINT_POINTER(srealloc(p521,193););
printStats();
void* p528 = last_address;
DEBUG_PRINT(sfree(p316););
printStats();
PRINT_POINTER(scalloc(130,166););
printStats();
void* p529 = last_address;
DEBUG_PRINT(sfree(p185););
printStats();
PRINT_POINTER(srealloc(p435,166););
printStats();
void* p530 = last_address;
PRINT_POINTER(srealloc(p328,74););
printStats();
void* p531 = last_address;
DEBUG_PRINT(sfree(p379););
printStats();
PRINT_POINTER(smalloc(39););
printStats();
void* p532 = last_address;
PRINT_POINTER(scalloc(200,28););
printStats();
void* p533 = last_address;
PRINT_POINTER(scalloc(33,159););
printStats();
void* p534 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p535 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p536 = last_address;
PRINT_POINTER(scalloc(111,87););
printStats();
void* p537 = last_address;
PRINT_POINTER(scalloc(149,122););
printStats();
void* p538 = last_address;
PRINT_POINTER(scalloc(49,191););
printStats();
void* p539 = last_address;
PRINT_POINTER(scalloc(54,12););
printStats();
void* p540 = last_address;
DEBUG_PRINT(sfree(p258););
printStats();
PRINT_POINTER(smalloc(126););
printStats();
void* p541 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p542 = last_address;
PRINT_POINTER(srealloc(p265,81););
printStats();
void* p543 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p544 = last_address;
PRINT_POINTER(scalloc(56,205););
printStats();
void* p545 = last_address;
DEBUG_PRINT(sfree(p371););
printStats();
DEBUG_PRINT(sfree(p463););
printStats();
PRINT_POINTER(smalloc(218););
printStats();
void* p546 = last_address;
PRINT_POINTER(srealloc(p410,182););
printStats();
void* p547 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p548 = last_address;
PRINT_POINTER(scalloc(241,204););
printStats();
void* p549 = last_address;
DEBUG_PRINT(sfree(p481););
printStats();
PRINT_POINTER(srealloc(p449,235););
printStats();
void* p550 = last_address;
PRINT_POINTER(scalloc(230,235););
printStats();
void* p551 = last_address;
PRINT_POINTER(scalloc(157,157););
printStats();
void* p552 = last_address;
PRINT_POINTER(scalloc(9,219););
printStats();
void* p553 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p554 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p555 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p556 = last_address;
PRINT_POINTER(srealloc(p147,88););
printStats();
void* p557 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p558 = last_address;
PRINT_POINTER(scalloc(112,101););
printStats();
void* p559 = last_address;
PRINT_POINTER(scalloc(219,61););
printStats();
void* p560 = last_address;
PRINT_POINTER(srealloc(p528,198););
printStats();
void* p561 = last_address;
PRINT_POINTER(scalloc(154,94););
printStats();
void* p562 = last_address;
DEBUG_PRINT(sfree(p425););
printStats();
DEBUG_PRINT(sfree(p541););
printStats();
DEBUG_PRINT(sfree(p559););
printStats();
PRINT_POINTER(smalloc(3););
printStats();
void* p563 = last_address;
PRINT_POINTER(srealloc(p525,179););
printStats();
void* p564 = last_address;
PRINT_POINTER(scalloc(106,13););
printStats();
void* p565 = last_address;
PRINT_POINTER(scalloc(35,47););
printStats();
void* p566 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p567 = last_address;
PRINT_POINTER(scalloc(134,72););
printStats();
void* p568 = last_address;
PRINT_POINTER(srealloc(p543,128););
printStats();
void* p569 = last_address;
PRINT_POINTER(scalloc(126,95););
printStats();
void* p570 = last_address;
DEBUG_PRINT(sfree(p459););
printStats();
PRINT_POINTER(smalloc(146););
printStats();
void* p571 = last_address;
PRINT_POINTER(scalloc(231,78););
printStats();
void* p572 = last_address;
PRINT_POINTER(scalloc(66,217););
printStats();
void* p573 = last_address;
PRINT_POINTER(srealloc(p182,35););
printStats();
void* p574 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p575 = last_address;
PRINT_POINTER(srealloc(p509,1););
printStats();
void* p576 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p577 = last_address;
DEBUG_PRINT(sfree(p465););
printStats();
PRINT_POINTER(srealloc(p477,107););
printStats();
void* p578 = last_address;
PRINT_POINTER(scalloc(209,119););
printStats();
void* p579 = last_address;
DEBUG_PRINT(sfree(p578););
printStats();
PRINT_POINTER(scalloc(103,119););
printStats();
void* p580 = last_address;
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(smalloc(147););
printStats();
void* p581 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p582 = last_address;
PRINT_POINTER(srealloc(p516,227););
printStats();
void* p583 = last_address;
DEBUG_PRINT(sfree(p368););
printStats();
PRINT_POINTER(scalloc(204,52););
printStats();
void* p584 = last_address;
PRINT_POINTER(scalloc(181,21););
printStats();
void* p585 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p586 = last_address;
PRINT_POINTER(scalloc(170,118););
printStats();
void* p587 = last_address;
PRINT_POINTER(scalloc(229,157););
printStats();
void* p588 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p589 = last_address;
}
