#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(103,155););
printStats();
void* p0 = last_address;
PRINT_POINTER(srealloc(p0,68););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(scalloc(23,2););
printStats();
void* p2 = last_address;
PRINT_POINTER(srealloc(p2,89););
printStats();
void* p3 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p4 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p5 = last_address;
PRINT_POINTER(scalloc(131,71););
printStats();
void* p6 = last_address;
PRINT_POINTER(srealloc(p5,23););
printStats();
void* p7 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
DEBUG_PRINT(sfree(p3););
printStats();
PRINT_POINTER(smalloc(121););
printStats();
void* p8 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p9 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p10 = last_address;
DEBUG_PRINT(sfree(p9););
printStats();
DEBUG_PRINT(sfree(p10););
printStats();
PRINT_POINTER(smalloc(219););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(4,249););
printStats();
void* p12 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p13 = last_address;
DEBUG_PRINT(sfree(p12););
printStats();
PRINT_POINTER(srealloc(p8,41););
printStats();
void* p14 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p15 = last_address;
PRINT_POINTER(scalloc(3,191););
printStats();
void* p16 = last_address;
PRINT_POINTER(srealloc(p15,183););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(139,57););
printStats();
void* p18 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p19 = last_address;
PRINT_POINTER(scalloc(70,69););
printStats();
void* p20 = last_address;
PRINT_POINTER(scalloc(62,2););
printStats();
void* p21 = last_address;
PRINT_POINTER(scalloc(236,98););
printStats();
void* p22 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p23 = last_address;
PRINT_POINTER(srealloc(p21,78););
printStats();
void* p24 = last_address;
DEBUG_PRINT(sfree(p23););
printStats();
PRINT_POINTER(smalloc(160););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(209,236););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p17,236););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
PRINT_POINTER(scalloc(14,126););
printStats();
void* p28 = last_address;
PRINT_POINTER(srealloc(p26,196););
printStats();
void* p29 = last_address;
DEBUG_PRINT(sfree(p27););
printStats();
PRINT_POINTER(scalloc(195,197););
printStats();
void* p30 = last_address;
PRINT_POINTER(scalloc(109,157););
printStats();
void* p31 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p32 = last_address;
PRINT_POINTER(srealloc(p25,19););
printStats();
void* p33 = last_address;
PRINT_POINTER(scalloc(236,52););
printStats();
void* p34 = last_address;
DEBUG_PRINT(sfree(p32););
printStats();
PRINT_POINTER(smalloc(228););
printStats();
void* p35 = last_address;
DEBUG_PRINT(sfree(p19););
printStats();
PRINT_POINTER(smalloc(234););
printStats();
void* p36 = last_address;
DEBUG_PRINT(sfree(p20););
printStats();
PRINT_POINTER(scalloc(60,158););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(110,203););
printStats();
void* p38 = last_address;
PRINT_POINTER(scalloc(120,194););
printStats();
void* p39 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
DEBUG_PRINT(sfree(p13););
printStats();
PRINT_POINTER(srealloc(p18,199););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p35,214););
printStats();
void* p41 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(scalloc(15,40););
printStats();
void* p42 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p43 = last_address;
PRINT_POINTER(scalloc(224,245););
printStats();
void* p44 = last_address;
PRINT_POINTER(scalloc(200,97););
printStats();
void* p45 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
DEBUG_PRINT(sfree(p22););
printStats();
DEBUG_PRINT(sfree(p42););
printStats();
DEBUG_PRINT(sfree(p43););
printStats();
PRINT_POINTER(scalloc(148,168););
printStats();
void* p46 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(srealloc(p37,1););
printStats();
void* p47 = last_address;
PRINT_POINTER(srealloc(p29,19););
printStats();
void* p48 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p49 = last_address;
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(scalloc(70,192););
printStats();
void* p50 = last_address;
PRINT_POINTER(scalloc(111,125););
printStats();
void* p51 = last_address;
PRINT_POINTER(scalloc(44,149););
printStats();
void* p52 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p53 = last_address;
PRINT_POINTER(srealloc(p6,201););
printStats();
void* p54 = last_address;
DEBUG_PRINT(sfree(p54););
printStats();
PRINT_POINTER(smalloc(118););
printStats();
void* p55 = last_address;
PRINT_POINTER(scalloc(204,24););
printStats();
void* p56 = last_address;
DEBUG_PRINT(sfree(p30););
printStats();
DEBUG_PRINT(sfree(p55););
printStats();
PRINT_POINTER(smalloc(244););
printStats();
void* p57 = last_address;
PRINT_POINTER(srealloc(p46,77););
printStats();
void* p58 = last_address;
DEBUG_PRINT(sfree(p58););
printStats();
PRINT_POINTER(smalloc(4););
printStats();
void* p59 = last_address;
PRINT_POINTER(srealloc(p48,1););
printStats();
void* p60 = last_address;
PRINT_POINTER(scalloc(213,23););
printStats();
void* p61 = last_address;
PRINT_POINTER(scalloc(197,156););
printStats();
void* p62 = last_address;
DEBUG_PRINT(sfree(p28););
printStats();
DEBUG_PRINT(sfree(p56););
printStats();
PRINT_POINTER(smalloc(219););
printStats();
void* p63 = last_address;
PRINT_POINTER(scalloc(14,152););
printStats();
void* p64 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p65 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p66 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p67 = last_address;
PRINT_POINTER(srealloc(p45,130););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p61,71););
printStats();
void* p69 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p70 = last_address;
PRINT_POINTER(srealloc(p70,70););
printStats();
void* p71 = last_address;
PRINT_POINTER(scalloc(236,148););
printStats();
void* p72 = last_address;
PRINT_POINTER(srealloc(p41,128););
printStats();
void* p73 = last_address;
PRINT_POINTER(scalloc(78,63););
printStats();
void* p74 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(scalloc(194,200););
printStats();
void* p75 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p76 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p77 = last_address;
DEBUG_PRINT(sfree(p76););
printStats();
DEBUG_PRINT(sfree(p57););
printStats();
PRINT_POINTER(smalloc(226););
printStats();
void* p78 = last_address;
PRINT_POINTER(srealloc(p65,153););
printStats();
void* p79 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p80 = last_address;
PRINT_POINTER(srealloc(p60,44););
printStats();
void* p81 = last_address;
PRINT_POINTER(srealloc(p79,136););
printStats();
void* p82 = last_address;
PRINT_POINTER(scalloc(116,246););
printStats();
void* p83 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p84 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
DEBUG_PRINT(sfree(p83););
printStats();
PRINT_POINTER(scalloc(194,185););
printStats();
void* p85 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(smalloc(2););
printStats();
void* p86 = last_address;
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(smalloc(72););
printStats();
void* p87 = last_address;
DEBUG_PRINT(sfree(p80););
printStats();
PRINT_POINTER(srealloc(p14,152););
printStats();
void* p88 = last_address;
DEBUG_PRINT(sfree(p51););
printStats();
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(scalloc(222,193););
printStats();
void* p89 = last_address;
DEBUG_PRINT(sfree(p53););
printStats();
PRINT_POINTER(srealloc(p84,58););
printStats();
void* p90 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(smalloc(194););
printStats();
void* p91 = last_address;
PRINT_POINTER(srealloc(p52,114););
printStats();
void* p92 = last_address;
DEBUG_PRINT(sfree(p88););
printStats();
PRINT_POINTER(srealloc(p74,75););
printStats();
void* p93 = last_address;
PRINT_POINTER(srealloc(p75,103););
printStats();
void* p94 = last_address;
PRINT_POINTER(srealloc(p82,148););
printStats();
void* p95 = last_address;
PRINT_POINTER(srealloc(p90,238););
printStats();
void* p96 = last_address;
PRINT_POINTER(scalloc(184,141););
printStats();
void* p97 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p98 = last_address;
PRINT_POINTER(scalloc(139,0););
printStats();
void* p99 = last_address;
DEBUG_PRINT(sfree(p87););
printStats();
DEBUG_PRINT(sfree(p63););
printStats();
DEBUG_PRINT(sfree(p36););
printStats();
PRINT_POINTER(srealloc(p97,128););
printStats();
void* p100 = last_address;
PRINT_POINTER(scalloc(136,57););
printStats();
void* p101 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p102 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p102,225););
printStats();
void* p104 = last_address;
PRINT_POINTER(scalloc(30,57););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p44,2););
printStats();
void* p106 = last_address;
PRINT_POINTER(scalloc(102,128););
printStats();
void* p107 = last_address;
PRINT_POINTER(srealloc(p92,55););
printStats();
void* p108 = last_address;
PRINT_POINTER(srealloc(p106,202););
printStats();
void* p109 = last_address;
DEBUG_PRINT(sfree(p49););
printStats();
PRINT_POINTER(srealloc(p47,220););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p108,190););
printStats();
void* p111 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p112 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p113 = last_address;
PRINT_POINTER(srealloc(p98,140););
printStats();
void* p114 = last_address;
DEBUG_PRINT(sfree(p96););
printStats();
PRINT_POINTER(scalloc(148,19););
printStats();
void* p115 = last_address;
DEBUG_PRINT(sfree(p103););
printStats();
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(smalloc(123););
printStats();
void* p116 = last_address;
PRINT_POINTER(srealloc(p34,74););
printStats();
void* p117 = last_address;
DEBUG_PRINT(sfree(p73););
printStats();
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(scalloc(210,21););
printStats();
void* p118 = last_address;
DEBUG_PRINT(sfree(p105););
printStats();
PRINT_POINTER(smalloc(97););
printStats();
void* p119 = last_address;
PRINT_POINTER(srealloc(p91,28););
printStats();
void* p120 = last_address;
PRINT_POINTER(srealloc(p119,114););
printStats();
void* p121 = last_address;
PRINT_POINTER(srealloc(p115,237););
printStats();
void* p122 = last_address;
PRINT_POINTER(srealloc(p122,217););
printStats();
void* p123 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p124 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(smalloc(220););
printStats();
void* p125 = last_address;
DEBUG_PRINT(sfree(p95););
printStats();
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(scalloc(35,231););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(55,81););
printStats();
void* p127 = last_address;
DEBUG_PRINT(sfree(p104););
printStats();
DEBUG_PRINT(sfree(p125););
printStats();
PRINT_POINTER(scalloc(50,125););
printStats();
void* p128 = last_address;
PRINT_POINTER(srealloc(p110,114););
printStats();
void* p129 = last_address;
DEBUG_PRINT(sfree(p120););
printStats();
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(smalloc(151););
printStats();
void* p130 = last_address;
DEBUG_PRINT(sfree(p93););
printStats();
PRINT_POINTER(srealloc(p107,120););
printStats();
void* p131 = last_address;
PRINT_POINTER(srealloc(p131,26););
printStats();
void* p132 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
PRINT_POINTER(srealloc(p117,225););
printStats();
void* p133 = last_address;
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(srealloc(p71,54););
printStats();
void* p134 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p135 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(srealloc(p134,80););
printStats();
void* p136 = last_address;
PRINT_POINTER(scalloc(187,164););
printStats();
void* p137 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p138 = last_address;
PRINT_POINTER(scalloc(8,212););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
PRINT_POINTER(srealloc(p127,180););
printStats();
void* p140 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(srealloc(p135,27););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p130,206););
printStats();
void* p142 = last_address;
PRINT_POINTER(srealloc(p126,217););
printStats();
void* p143 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p144 = last_address;
PRINT_POINTER(srealloc(p139,143););
printStats();
void* p145 = last_address;
DEBUG_PRINT(sfree(p144););
printStats();
DEBUG_PRINT(sfree(p137););
printStats();
PRINT_POINTER(smalloc(19););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p147 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p148 = last_address;
DEBUG_PRINT(sfree(p66););
printStats();
DEBUG_PRINT(sfree(p62););
printStats();
PRINT_POINTER(smalloc(128););
printStats();
void* p149 = last_address;
PRINT_POINTER(scalloc(203,241););
printStats();
void* p150 = last_address;
DEBUG_PRINT(sfree(p149););
printStats();
DEBUG_PRINT(sfree(p111););
printStats();
PRINT_POINTER(scalloc(196,45););
printStats();
void* p151 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(scalloc(175,56););
printStats();
void* p152 = last_address;
PRINT_POINTER(scalloc(9,53););
printStats();
void* p153 = last_address;
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(srealloc(p143,104););
printStats();
void* p154 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p155 = last_address;
PRINT_POINTER(scalloc(101,48););
printStats();
void* p156 = last_address;
DEBUG_PRINT(sfree(p140););
printStats();
DEBUG_PRINT(sfree(p153););
printStats();
PRINT_POINTER(smalloc(8););
printStats();
void* p157 = last_address;
PRINT_POINTER(scalloc(248,152););
printStats();
void* p158 = last_address;
DEBUG_PRINT(sfree(p158););
printStats();
DEBUG_PRINT(sfree(p133););
printStats();
PRINT_POINTER(srealloc(p114,154););
printStats();
void* p159 = last_address;
PRINT_POINTER(srealloc(p101,80););
printStats();
void* p160 = last_address;
PRINT_POINTER(srealloc(p118,139););
printStats();
void* p161 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p162 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p163 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(scalloc(190,62););
printStats();
void* p164 = last_address;
PRINT_POINTER(srealloc(p145,13););
printStats();
void* p165 = last_address;
PRINT_POINTER(srealloc(p112,107););
printStats();
void* p166 = last_address;
DEBUG_PRINT(sfree(p160););
printStats();
PRINT_POINTER(scalloc(84,58););
printStats();
void* p167 = last_address;
PRINT_POINTER(srealloc(p121,54););
printStats();
void* p168 = last_address;
DEBUG_PRINT(sfree(p138););
printStats();
DEBUG_PRINT(sfree(p151););
printStats();
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(srealloc(p168,218););
printStats();
void* p169 = last_address;
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(srealloc(p94,155););
printStats();
void* p170 = last_address;
DEBUG_PRINT(sfree(p68););
printStats();
DEBUG_PRINT(sfree(p157););
printStats();
DEBUG_PRINT(sfree(p156););
printStats();
PRINT_POINTER(scalloc(82,111););
printStats();
void* p171 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p172 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p173 = last_address;
PRINT_POINTER(scalloc(220,47););
printStats();
void* p174 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p154););
printStats();
PRINT_POINTER(scalloc(214,30););
printStats();
void* p176 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p177 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p178 = last_address;
PRINT_POINTER(srealloc(p169,30););
printStats();
void* p179 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p180 = last_address;
PRINT_POINTER(scalloc(78,219););
printStats();
void* p181 = last_address;
PRINT_POINTER(scalloc(145,158););
printStats();
void* p182 = last_address;
DEBUG_PRINT(sfree(p171););
printStats();
DEBUG_PRINT(sfree(p170););
printStats();
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(scalloc(152,25););
printStats();
void* p183 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p184 = last_address;
PRINT_POINTER(srealloc(p182,135););
printStats();
void* p185 = last_address;
DEBUG_PRINT(sfree(p177););
printStats();
PRINT_POINTER(scalloc(7,233););
printStats();
void* p186 = last_address;
PRINT_POINTER(srealloc(p67,193););
printStats();
void* p187 = last_address;
DEBUG_PRINT(sfree(p178););
printStats();
PRINT_POINTER(srealloc(p155,30););
printStats();
void* p188 = last_address;
PRINT_POINTER(scalloc(227,67););
printStats();
void* p189 = last_address;
PRINT_POINTER(srealloc(p167,152););
printStats();
void* p190 = last_address;
PRINT_POINTER(scalloc(20,41););
printStats();
void* p191 = last_address;
PRINT_POINTER(srealloc(p181,236););
printStats();
void* p192 = last_address;
PRINT_POINTER(scalloc(182,245););
printStats();
void* p193 = last_address;
DEBUG_PRINT(sfree(p179););
printStats();
PRINT_POINTER(srealloc(p192,54););
printStats();
void* p194 = last_address;
PRINT_POINTER(srealloc(p189,129););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p190););
printStats();
PRINT_POINTER(scalloc(238,158););
printStats();
void* p196 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p197 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p198 = last_address;
PRINT_POINTER(srealloc(p175,239););
printStats();
void* p199 = last_address;
PRINT_POINTER(srealloc(p194,139););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p128,128););
printStats();
void* p201 = last_address;
PRINT_POINTER(scalloc(151,58););
printStats();
void* p202 = last_address;
PRINT_POINTER(srealloc(p129,119););
printStats();
void* p203 = last_address;
DEBUG_PRINT(sfree(p81););
printStats();
DEBUG_PRINT(sfree(p163););
printStats();
PRINT_POINTER(smalloc(177););
printStats();
void* p204 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p205 = last_address;
PRINT_POINTER(srealloc(p176,69););
printStats();
void* p206 = last_address;
PRINT_POINTER(srealloc(p132,163););
printStats();
void* p207 = last_address;
DEBUG_PRINT(sfree(p136););
printStats();
PRINT_POINTER(scalloc(96,193););
printStats();
void* p208 = last_address;
PRINT_POINTER(scalloc(228,193););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(34,10););
printStats();
void* p210 = last_address;
DEBUG_PRINT(sfree(p207););
printStats();
PRINT_POINTER(srealloc(p146,64););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(92,190););
printStats();
void* p212 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
PRINT_POINTER(srealloc(p174,123););
printStats();
void* p213 = last_address;
DEBUG_PRINT(sfree(p172););
printStats();
PRINT_POINTER(scalloc(235,95););
printStats();
void* p214 = last_address;
PRINT_POINTER(scalloc(138,212););
printStats();
void* p215 = last_address;
PRINT_POINTER(srealloc(p193,188););
printStats();
void* p216 = last_address;
PRINT_POINTER(scalloc(50,211););
printStats();
void* p217 = last_address;
DEBUG_PRINT(sfree(p206););
printStats();
PRINT_POINTER(srealloc(p164,184););
printStats();
void* p218 = last_address;
PRINT_POINTER(srealloc(p184,56););
printStats();
void* p219 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
PRINT_POINTER(srealloc(p188,26););
printStats();
void* p220 = last_address;
DEBUG_PRINT(sfree(p219););
printStats();
PRINT_POINTER(smalloc(148););
printStats();
void* p221 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p222 = last_address;
DEBUG_PRINT(sfree(p198););
printStats();
PRINT_POINTER(srealloc(p217,242););
printStats();
void* p223 = last_address;
PRINT_POINTER(scalloc(243,145););
printStats();
void* p224 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p225 = last_address;
PRINT_POINTER(scalloc(237,159););
printStats();
void* p226 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p227 = last_address;
PRINT_POINTER(srealloc(p141,100););
printStats();
void* p228 = last_address;
DEBUG_PRINT(sfree(p224););
printStats();
PRINT_POINTER(srealloc(p191,187););
printStats();
void* p229 = last_address;
PRINT_POINTER(scalloc(19,100););
printStats();
void* p230 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p231 = last_address;
PRINT_POINTER(srealloc(p228,115););
printStats();
void* p232 = last_address;
DEBUG_PRINT(sfree(p213););
printStats();
PRINT_POINTER(srealloc(p197,109););
printStats();
void* p233 = last_address;
PRINT_POINTER(scalloc(211,149););
printStats();
void* p234 = last_address;
PRINT_POINTER(srealloc(p223,19););
printStats();
void* p235 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p236 = last_address;
PRINT_POINTER(scalloc(113,225););
printStats();
void* p237 = last_address;
PRINT_POINTER(scalloc(167,94););
printStats();
void* p238 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
PRINT_POINTER(srealloc(p199,55););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p221,42););
printStats();
void* p240 = last_address;
DEBUG_PRINT(sfree(p215););
printStats();
PRINT_POINTER(scalloc(193,233););
printStats();
void* p241 = last_address;
PRINT_POINTER(scalloc(233,158););
printStats();
void* p242 = last_address;
PRINT_POINTER(scalloc(4,191););
printStats();
void* p243 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p244 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p245 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p246 = last_address;
PRINT_POINTER(srealloc(p200,229););
printStats();
void* p247 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p248 = last_address;
PRINT_POINTER(scalloc(200,132););
printStats();
void* p249 = last_address;
PRINT_POINTER(scalloc(249,194););
printStats();
void* p250 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p251 = last_address;
PRINT_POINTER(scalloc(162,193););
printStats();
void* p252 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p253 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p254 = last_address;
DEBUG_PRINT(sfree(p185););
printStats();
PRINT_POINTER(srealloc(p249,180););
printStats();
void* p255 = last_address;
PRINT_POINTER(smalloc(221););
printStats();
void* p256 = last_address;
PRINT_POINTER(scalloc(167,33););
printStats();
void* p257 = last_address;
PRINT_POINTER(srealloc(p251,110););
printStats();
void* p258 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p259 = last_address;
PRINT_POINTER(scalloc(186,33););
printStats();
void* p260 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p261 = last_address;
PRINT_POINTER(srealloc(p204,166););
printStats();
void* p262 = last_address;
PRINT_POINTER(scalloc(38,113););
printStats();
void* p263 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p264 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p265 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p266 = last_address;
DEBUG_PRINT(sfree(p255););
printStats();
PRINT_POINTER(smalloc(88););
printStats();
void* p267 = last_address;
PRINT_POINTER(scalloc(4,78););
printStats();
void* p268 = last_address;
PRINT_POINTER(srealloc(p241,77););
printStats();
void* p269 = last_address;
DEBUG_PRINT(sfree(p187););
printStats();
PRINT_POINTER(scalloc(223,184););
printStats();
void* p270 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p271 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p272 = last_address;
DEBUG_PRINT(sfree(p265););
printStats();
DEBUG_PRINT(sfree(p263););
printStats();
PRINT_POINTER(srealloc(p234,114););
printStats();
void* p273 = last_address;
PRINT_POINTER(srealloc(p211,27););
printStats();
void* p274 = last_address;
PRINT_POINTER(scalloc(94,110););
printStats();
void* p275 = last_address;
DEBUG_PRINT(sfree(p244););
printStats();
PRINT_POINTER(smalloc(157););
printStats();
void* p276 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p277 = last_address;
DEBUG_PRINT(sfree(p258););
printStats();
DEBUG_PRINT(sfree(p252););
printStats();
PRINT_POINTER(scalloc(54,94););
printStats();
void* p278 = last_address;
PRINT_POINTER(srealloc(p99,65););
printStats();
void* p279 = last_address;
PRINT_POINTER(srealloc(p268,236););
printStats();
void* p280 = last_address;
DEBUG_PRINT(sfree(p208););
printStats();
PRINT_POINTER(smalloc(65););
printStats();
void* p281 = last_address;
DEBUG_PRINT(sfree(p278););
printStats();
PRINT_POINTER(scalloc(219,7););
printStats();
void* p282 = last_address;
PRINT_POINTER(scalloc(12,99););
printStats();
void* p283 = last_address;
PRINT_POINTER(scalloc(233,105););
printStats();
void* p284 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p285 = last_address;
DEBUG_PRINT(sfree(p195););
printStats();
PRINT_POINTER(smalloc(77););
printStats();
void* p286 = last_address;
PRINT_POINTER(scalloc(75,38););
printStats();
void* p287 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p288 = last_address;
PRINT_POINTER(srealloc(p233,237););
printStats();
void* p289 = last_address;
PRINT_POINTER(scalloc(120,136););
printStats();
void* p290 = last_address;
PRINT_POINTER(scalloc(78,126););
printStats();
void* p291 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p292 = last_address;
PRINT_POINTER(scalloc(70,171););
printStats();
void* p293 = last_address;
PRINT_POINTER(srealloc(p247,220););
printStats();
void* p294 = last_address;
PRINT_POINTER(scalloc(193,65););
printStats();
void* p295 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p296 = last_address;
DEBUG_PRINT(sfree(p239););
printStats();
PRINT_POINTER(scalloc(117,152););
printStats();
void* p297 = last_address;
PRINT_POINTER(srealloc(p269,134););
printStats();
void* p298 = last_address;
DEBUG_PRINT(sfree(p161););
printStats();
PRINT_POINTER(smalloc(82););
printStats();
void* p299 = last_address;
PRINT_POINTER(scalloc(0,231););
printStats();
void* p300 = last_address;
PRINT_POINTER(srealloc(p285,125););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p302 = last_address;
PRINT_POINTER(scalloc(44,73););
printStats();
void* p303 = last_address;
PRINT_POINTER(scalloc(127,105););
printStats();
void* p304 = last_address;
PRINT_POINTER(scalloc(204,111););
printStats();
void* p305 = last_address;
DEBUG_PRINT(sfree(p243););
printStats();
DEBUG_PRINT(sfree(p245););
printStats();
PRINT_POINTER(scalloc(103,139););
printStats();
void* p306 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p307 = last_address;
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(srealloc(p305,87););
printStats();
void* p308 = last_address;
DEBUG_PRINT(sfree(p230););
printStats();
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(srealloc(p271,75););
printStats();
void* p309 = last_address;
PRINT_POINTER(srealloc(p229,37););
printStats();
void* p310 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p311 = last_address;
DEBUG_PRINT(sfree(p202););
printStats();
DEBUG_PRINT(sfree(p308););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p312 = last_address;
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(smalloc(155););
printStats();
void* p313 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p314 = last_address;
DEBUG_PRINT(sfree(p279););
printStats();
PRINT_POINTER(scalloc(111,193););
printStats();
void* p315 = last_address;
PRINT_POINTER(srealloc(p270,88););
printStats();
void* p316 = last_address;
PRINT_POINTER(scalloc(207,115););
printStats();
void* p317 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p318 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p319 = last_address;
PRINT_POINTER(scalloc(36,46););
printStats();
void* p320 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p321 = last_address;
PRINT_POINTER(scalloc(128,159););
printStats();
void* p322 = last_address;
PRINT_POINTER(scalloc(51,14););
printStats();
void* p323 = last_address;
PRINT_POINTER(srealloc(p261,215););
printStats();
void* p324 = last_address;
DEBUG_PRINT(sfree(p242););
printStats();
PRINT_POINTER(smalloc(44););
printStats();
void* p325 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p326 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p327 = last_address;
DEBUG_PRINT(sfree(p318););
printStats();
PRINT_POINTER(srealloc(p293,179););
printStats();
void* p328 = last_address;
PRINT_POINTER(scalloc(236,159););
printStats();
void* p329 = last_address;
DEBUG_PRINT(sfree(p264););
printStats();
PRINT_POINTER(smalloc(92););
printStats();
void* p330 = last_address;
PRINT_POINTER(srealloc(p326,214););
printStats();
void* p331 = last_address;
PRINT_POINTER(srealloc(p246,159););
printStats();
void* p332 = last_address;
PRINT_POINTER(scalloc(237,227););
printStats();
void* p333 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p334 = last_address;
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(scalloc(146,131););
printStats();
void* p335 = last_address;
PRINT_POINTER(scalloc(231,138););
printStats();
void* p336 = last_address;
PRINT_POINTER(srealloc(p313,15););
printStats();
void* p337 = last_address;
PRINT_POINTER(scalloc(74,101););
printStats();
void* p338 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p339 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p340 = last_address;
DEBUG_PRINT(sfree(p273););
printStats();
PRINT_POINTER(srealloc(p296,8););
printStats();
void* p341 = last_address;
PRINT_POINTER(scalloc(232,111););
printStats();
void* p342 = last_address;
PRINT_POINTER(srealloc(p332,92););
printStats();
void* p343 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p344 = last_address;
PRINT_POINTER(scalloc(154,42););
printStats();
void* p345 = last_address;
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(smalloc(203););
printStats();
void* p346 = last_address;
PRINT_POINTER(scalloc(96,224););
printStats();
void* p347 = last_address;
DEBUG_PRINT(sfree(p309););
printStats();
PRINT_POINTER(srealloc(p290,163););
printStats();
void* p348 = last_address;
PRINT_POINTER(srealloc(p214,31););
printStats();
void* p349 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p350 = last_address;
PRINT_POINTER(scalloc(22,214););
printStats();
void* p351 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p352 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p353 = last_address;
PRINT_POINTER(srealloc(p209,138););
printStats();
void* p354 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p355 = last_address;
PRINT_POINTER(scalloc(159,194););
printStats();
void* p356 = last_address;
PRINT_POINTER(srealloc(p226,130););
printStats();
void* p357 = last_address;
PRINT_POINTER(srealloc(p281,75););
printStats();
void* p358 = last_address;
PRINT_POINTER(scalloc(109,120););
printStats();
void* p359 = last_address;
DEBUG_PRINT(sfree(p352););
printStats();
PRINT_POINTER(scalloc(198,68););
printStats();
void* p360 = last_address;
DEBUG_PRINT(sfree(p314););
printStats();
DEBUG_PRINT(sfree(p275););
printStats();
DEBUG_PRINT(sfree(p346););
printStats();
PRINT_POINTER(smalloc(189););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p362 = last_address;
PRINT_POINTER(scalloc(6,39););
printStats();
void* p363 = last_address;
PRINT_POINTER(scalloc(207,215););
printStats();
void* p364 = last_address;
PRINT_POINTER(srealloc(p240,243););
printStats();
void* p365 = last_address;
PRINT_POINTER(srealloc(p364,107););
printStats();
void* p366 = last_address;
PRINT_POINTER(srealloc(p303,170););
printStats();
void* p367 = last_address;
DEBUG_PRINT(sfree(p366););
printStats();
PRINT_POINTER(srealloc(p287,60););
printStats();
void* p368 = last_address;
PRINT_POINTER(scalloc(161,100););
printStats();
void* p369 = last_address;
PRINT_POINTER(scalloc(49,242););
printStats();
void* p370 = last_address;
PRINT_POINTER(scalloc(216,159););
printStats();
void* p371 = last_address;
DEBUG_PRINT(sfree(p322););
printStats();
DEBUG_PRINT(sfree(p166););
printStats();
DEBUG_PRINT(sfree(p237););
printStats();
PRINT_POINTER(scalloc(36,232););
printStats();
void* p372 = last_address;
PRINT_POINTER(srealloc(p328,39););
printStats();
void* p373 = last_address;
PRINT_POINTER(srealloc(p302,18););
printStats();
void* p374 = last_address;
PRINT_POINTER(scalloc(113,249););
printStats();
void* p375 = last_address;
PRINT_POINTER(scalloc(159,206););
printStats();
void* p376 = last_address;
DEBUG_PRINT(sfree(p320););
printStats();
PRINT_POINTER(scalloc(216,77););
printStats();
void* p377 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
DEBUG_PRINT(sfree(p232););
printStats();
DEBUG_PRINT(sfree(p329););
printStats();
DEBUG_PRINT(sfree(p324););
printStats();
PRINT_POINTER(smalloc(33););
printStats();
void* p378 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p379 = last_address;
PRINT_POINTER(srealloc(p284,85););
printStats();
void* p380 = last_address;
DEBUG_PRINT(sfree(p201););
printStats();
PRINT_POINTER(smalloc(190););
printStats();
void* p381 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p382 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p383 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p384 = last_address;
DEBUG_PRINT(sfree(p162););
printStats();
PRINT_POINTER(smalloc(202););
printStats();
void* p385 = last_address;
DEBUG_PRINT(sfree(p212););
printStats();
PRINT_POINTER(srealloc(p254,145););
printStats();
void* p386 = last_address;
PRINT_POINTER(scalloc(179,92););
printStats();
void* p387 = last_address;
DEBUG_PRINT(sfree(p359););
printStats();
PRINT_POINTER(smalloc(92););
printStats();
void* p388 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p389 = last_address;
DEBUG_PRINT(sfree(p276););
printStats();
PRINT_POINTER(smalloc(75););
printStats();
void* p390 = last_address;
DEBUG_PRINT(sfree(p291););
printStats();
DEBUG_PRINT(sfree(p371););
printStats();
PRINT_POINTER(scalloc(154,195););
printStats();
void* p391 = last_address;
PRINT_POINTER(srealloc(p345,73););
printStats();
void* p392 = last_address;
PRINT_POINTER(srealloc(p311,223););
printStats();
void* p393 = last_address;
PRINT_POINTER(srealloc(p340,186););
printStats();
void* p394 = last_address;
PRINT_POINTER(scalloc(21,131););
printStats();
void* p395 = last_address;
PRINT_POINTER(scalloc(28,242););
printStats();
void* p396 = last_address;
PRINT_POINTER(srealloc(p325,67););
printStats();
void* p397 = last_address;
PRINT_POINTER(scalloc(181,178););
printStats();
void* p398 = last_address;
PRINT_POINTER(scalloc(235,97););
printStats();
void* p399 = last_address;
DEBUG_PRINT(sfree(p365););
printStats();
PRINT_POINTER(srealloc(p220,233););
printStats();
void* p400 = last_address;
DEBUG_PRINT(sfree(p231););
printStats();
PRINT_POINTER(srealloc(p392,93););
printStats();
void* p401 = last_address;
DEBUG_PRINT(sfree(p372););
printStats();
PRINT_POINTER(scalloc(170,96););
printStats();
void* p402 = last_address;
DEBUG_PRINT(sfree(p331););
printStats();
DEBUG_PRINT(sfree(p321););
printStats();
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(srealloc(p378,47););
printStats();
void* p403 = last_address;
DEBUG_PRINT(sfree(p361););
printStats();
PRINT_POINTER(srealloc(p343,48););
printStats();
void* p404 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
PRINT_POINTER(scalloc(168,226););
printStats();
void* p405 = last_address;
DEBUG_PRINT(sfree(p369););
printStats();
PRINT_POINTER(smalloc(127););
printStats();
void* p406 = last_address;
PRINT_POINTER(srealloc(p399,50););
printStats();
void* p407 = last_address;
PRINT_POINTER(srealloc(p354,220););
printStats();
void* p408 = last_address;
PRINT_POINTER(scalloc(57,51););
printStats();
void* p409 = last_address;
DEBUG_PRINT(sfree(p396););
printStats();
PRINT_POINTER(scalloc(67,227););
printStats();
void* p410 = last_address;
DEBUG_PRINT(sfree(p408););
printStats();
PRINT_POINTER(srealloc(p260,229););
printStats();
void* p411 = last_address;
PRINT_POINTER(scalloc(22,66););
printStats();
void* p412 = last_address;
PRINT_POINTER(scalloc(136,89););
printStats();
void* p413 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p414 = last_address;
PRINT_POINTER(srealloc(p225,128););
printStats();
void* p415 = last_address;
DEBUG_PRINT(sfree(p376););
printStats();
PRINT_POINTER(srealloc(p410,44););
printStats();
void* p416 = last_address;
PRINT_POINTER(scalloc(190,79););
printStats();
void* p417 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p418 = last_address;
DEBUG_PRINT(sfree(p385););
printStats();
PRINT_POINTER(scalloc(187,165););
printStats();
void* p419 = last_address;
PRINT_POINTER(srealloc(p363,38););
printStats();
void* p420 = last_address;
PRINT_POINTER(scalloc(173,91););
printStats();
void* p421 = last_address;
PRINT_POINTER(srealloc(p394,187););
printStats();
void* p422 = last_address;
PRINT_POINTER(scalloc(91,161););
printStats();
void* p423 = last_address;
PRINT_POINTER(srealloc(p277,143););
printStats();
void* p424 = last_address;
PRINT_POINTER(srealloc(p383,41););
printStats();
void* p425 = last_address;
PRINT_POINTER(srealloc(p418,48););
printStats();
void* p426 = last_address;
DEBUG_PRINT(sfree(p310););
printStats();
PRINT_POINTER(srealloc(p348,54););
printStats();
void* p427 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p428 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p429 = last_address;
PRINT_POINTER(scalloc(200,134););
printStats();
void* p430 = last_address;
DEBUG_PRINT(sfree(p375););
printStats();
PRINT_POINTER(scalloc(38,59););
printStats();
void* p431 = last_address;
PRINT_POINTER(scalloc(37,44););
printStats();
void* p432 = last_address;
DEBUG_PRINT(sfree(p417););
printStats();
PRINT_POINTER(srealloc(p409,212););
printStats();
void* p433 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p434 = last_address;
PRINT_POINTER(srealloc(p315,59););
printStats();
void* p435 = last_address;
PRINT_POINTER(srealloc(p405,203););
printStats();
void* p436 = last_address;
PRINT_POINTER(scalloc(231,74););
printStats();
void* p437 = last_address;
PRINT_POINTER(scalloc(205,118););
printStats();
void* p438 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p439 = last_address;
DEBUG_PRINT(sfree(p289););
printStats();
PRINT_POINTER(smalloc(140););
printStats();
void* p440 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p441 = last_address;
PRINT_POINTER(srealloc(p272,105););
printStats();
void* p442 = last_address;
PRINT_POINTER(scalloc(199,135););
printStats();
void* p443 = last_address;
DEBUG_PRINT(sfree(p312););
printStats();
DEBUG_PRINT(sfree(p419););
printStats();
DEBUG_PRINT(sfree(p391););
printStats();
PRINT_POINTER(smalloc(20););
printStats();
void* p444 = last_address;
PRINT_POINTER(srealloc(p401,76););
printStats();
void* p445 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(srealloc(p347,171););
printStats();
void* p446 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p447 = last_address;
PRINT_POINTER(scalloc(223,0););
printStats();
void* p448 = last_address;
PRINT_POINTER(srealloc(p280,165););
printStats();
void* p449 = last_address;
PRINT_POINTER(scalloc(62,186););
printStats();
void* p450 = last_address;
PRINT_POINTER(scalloc(144,90););
printStats();
void* p451 = last_address;
DEBUG_PRINT(sfree(p425););
printStats();
DEBUG_PRINT(sfree(p301););
printStats();
PRINT_POINTER(smalloc(46););
printStats();
void* p452 = last_address;
DEBUG_PRINT(sfree(p374););
printStats();
PRINT_POINTER(srealloc(p292,90););
printStats();
void* p453 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p454 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p455 = last_address;
PRINT_POINTER(scalloc(132,96););
printStats();
void* p456 = last_address;
PRINT_POINTER(scalloc(219,11););
printStats();
void* p457 = last_address;
PRINT_POINTER(srealloc(p227,226););
printStats();
void* p458 = last_address;
PRINT_POINTER(srealloc(p298,34););
printStats();
void* p459 = last_address;
PRINT_POINTER(scalloc(84,167););
printStats();
void* p460 = last_address;
DEBUG_PRINT(sfree(p434););
printStats();
PRINT_POINTER(srealloc(p297,195););
printStats();
void* p461 = last_address;
PRINT_POINTER(srealloc(p461,200););
printStats();
void* p462 = last_address;
PRINT_POINTER(srealloc(p317,177););
printStats();
void* p463 = last_address;
PRINT_POINTER(srealloc(p319,58););
printStats();
void* p464 = last_address;
PRINT_POINTER(srealloc(p456,125););
printStats();
void* p465 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p466 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p467 = last_address;
PRINT_POINTER(scalloc(244,174););
printStats();
void* p468 = last_address;
PRINT_POINTER(scalloc(54,183););
printStats();
void* p469 = last_address;
DEBUG_PRINT(sfree(p428););
printStats();
DEBUG_PRINT(sfree(p236););
printStats();
PRINT_POINTER(srealloc(p299,208););
printStats();
void* p470 = last_address;
PRINT_POINTER(scalloc(144,139););
printStats();
void* p471 = last_address;
DEBUG_PRINT(sfree(p344););
printStats();
PRINT_POINTER(scalloc(76,181););
printStats();
void* p472 = last_address;
PRINT_POINTER(srealloc(p282,41););
printStats();
void* p473 = last_address;
PRINT_POINTER(scalloc(115,202););
printStats();
void* p474 = last_address;
PRINT_POINTER(scalloc(149,170););
printStats();
void* p475 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p476 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p477 = last_address;
PRINT_POINTER(srealloc(p451,201););
printStats();
void* p478 = last_address;
DEBUG_PRINT(sfree(p414););
printStats();
DEBUG_PRINT(sfree(p283););
printStats();
PRINT_POINTER(smalloc(196););
printStats();
void* p479 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p480 = last_address;
PRINT_POINTER(scalloc(98,238););
printStats();
void* p481 = last_address;
DEBUG_PRINT(sfree(p379););
printStats();
PRINT_POINTER(srealloc(p450,95););
printStats();
void* p482 = last_address;
DEBUG_PRINT(sfree(p482););
printStats();
PRINT_POINTER(srealloc(p463,132););
printStats();
void* p483 = last_address;
DEBUG_PRINT(sfree(p446););
printStats();
DEBUG_PRINT(sfree(p402););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p484 = last_address;
DEBUG_PRINT(sfree(p306););
printStats();
DEBUG_PRINT(sfree(p469););
printStats();
PRINT_POINTER(srealloc(p449,187););
printStats();
void* p485 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p486 = last_address;
PRINT_POINTER(srealloc(p327,153););
printStats();
void* p487 = last_address;
DEBUG_PRINT(sfree(p479););
printStats();
PRINT_POINTER(smalloc(245););
printStats();
void* p488 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p489 = last_address;
PRINT_POINTER(scalloc(53,15););
printStats();
void* p490 = last_address;
PRINT_POINTER(scalloc(36,82););
printStats();
void* p491 = last_address;
DEBUG_PRINT(sfree(p477););
printStats();
DEBUG_PRINT(sfree(p353););
printStats();
DEBUG_PRINT(sfree(p464););
printStats();
DEBUG_PRINT(sfree(p432););
printStats();
PRINT_POINTER(smalloc(146););
printStats();
void* p492 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p493 = last_address;
PRINT_POINTER(scalloc(127,52););
printStats();
void* p494 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p495 = last_address;
PRINT_POINTER(srealloc(p238,200););
printStats();
void* p496 = last_address;
PRINT_POINTER(srealloc(p384,174););
printStats();
void* p497 = last_address;
DEBUG_PRINT(sfree(p388););
printStats();
DEBUG_PRINT(sfree(p447););
printStats();
PRINT_POINTER(smalloc(18););
printStats();
void* p498 = last_address;
DEBUG_PRINT(sfree(p300););
printStats();
PRINT_POINTER(srealloc(p183,163););
printStats();
void* p499 = last_address;
DEBUG_PRINT(sfree(p478););
printStats();
DEBUG_PRINT(sfree(p412););
printStats();
PRINT_POINTER(smalloc(228););
printStats();
void* p500 = last_address;
PRINT_POINTER(srealloc(p429,148););
printStats();
void* p501 = last_address;
PRINT_POINTER(scalloc(186,72););
printStats();
void* p502 = last_address;
PRINT_POINTER(srealloc(p431,160););
printStats();
void* p503 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p504 = last_address;
PRINT_POINTER(scalloc(58,85););
printStats();
void* p505 = last_address;
PRINT_POINTER(srealloc(p437,50););
printStats();
void* p506 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p507 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p508 = last_address;
DEBUG_PRINT(sfree(p436););
printStats();
PRINT_POINTER(smalloc(113););
printStats();
void* p509 = last_address;
PRINT_POINTER(scalloc(209,202););
printStats();
void* p510 = last_address;
PRINT_POINTER(srealloc(p390,92););
printStats();
void* p511 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p512 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p513 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p514 = last_address;
PRINT_POINTER(scalloc(41,23););
printStats();
void* p515 = last_address;
PRINT_POINTER(scalloc(33,106););
printStats();
void* p516 = last_address;
DEBUG_PRINT(sfree(p368););
printStats();
PRINT_POINTER(srealloc(p422,168););
printStats();
void* p517 = last_address;
DEBUG_PRINT(sfree(p395););
printStats();
PRINT_POINTER(srealloc(p487,145););
printStats();
void* p518 = last_address;
DEBUG_PRINT(sfree(p491););
printStats();
DEBUG_PRINT(sfree(p165););
printStats();
PRINT_POINTER(scalloc(224,61););
printStats();
void* p519 = last_address;
PRINT_POINTER(scalloc(175,245););
printStats();
void* p520 = last_address;
PRINT_POINTER(scalloc(217,106););
printStats();
void* p521 = last_address;
DEBUG_PRINT(sfree(p288););
printStats();
PRINT_POINTER(smalloc(138););
printStats();
void* p522 = last_address;
DEBUG_PRINT(sfree(p503););
printStats();
DEBUG_PRINT(sfree(p495););
printStats();
PRINT_POINTER(srealloc(p521,93););
printStats();
void* p523 = last_address;
PRINT_POINTER(srealloc(p501,195););
printStats();
void* p524 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p525 = last_address;
DEBUG_PRINT(sfree(p350););
printStats();
PRINT_POINTER(srealloc(p458,143););
printStats();
void* p526 = last_address;
PRINT_POINTER(srealloc(p397,47););
printStats();
void* p527 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p528 = last_address;
PRINT_POINTER(scalloc(229,160););
printStats();
void* p529 = last_address;
PRINT_POINTER(srealloc(p335,37););
printStats();
void* p530 = last_address;
DEBUG_PRINT(sfree(p511););
printStats();
DEBUG_PRINT(sfree(p407););
printStats();
PRINT_POINTER(scalloc(108,144););
printStats();
void* p531 = last_address;
DEBUG_PRINT(sfree(p516););
printStats();
DEBUG_PRINT(sfree(p367););
printStats();
DEBUG_PRINT(sfree(p448););
printStats();
PRINT_POINTER(scalloc(150,28););
printStats();
void* p532 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p533 = last_address;
DEBUG_PRINT(sfree(p498););
printStats();
PRINT_POINTER(srealloc(p373,213););
printStats();
void* p534 = last_address;
PRINT_POINTER(scalloc(188,14););
printStats();
void* p535 = last_address;
PRINT_POINTER(scalloc(113,101););
printStats();
void* p536 = last_address;
DEBUG_PRINT(sfree(p337););
printStats();
PRINT_POINTER(smalloc(208););
printStats();
void* p537 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p538 = last_address;
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(srealloc(p499,97););
printStats();
void* p539 = last_address;
PRINT_POINTER(srealloc(p532,177););
printStats();
void* p540 = last_address;
DEBUG_PRINT(sfree(p415););
printStats();
PRINT_POINTER(srealloc(p485,207););
printStats();
void* p541 = last_address;
PRINT_POINTER(srealloc(p406,177););
printStats();
void* p542 = last_address;
PRINT_POINTER(scalloc(200,95););
printStats();
void* p543 = last_address;
PRINT_POINTER(srealloc(p493,3););
printStats();
void* p544 = last_address;
PRINT_POINTER(scalloc(153,92););
printStats();
void* p545 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
PRINT_POINTER(scalloc(231,156););
printStats();
void* p546 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p547 = last_address;
PRINT_POINTER(scalloc(130,155););
printStats();
void* p548 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p549 = last_address;
PRINT_POINTER(srealloc(p457,33););
printStats();
void* p550 = last_address;
PRINT_POINTER(srealloc(p473,15););
printStats();
void* p551 = last_address;
DEBUG_PRINT(sfree(p370););
printStats();
PRINT_POINTER(scalloc(154,181););
printStats();
void* p552 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p553 = last_address;
DEBUG_PRINT(sfree(p360););
printStats();
PRINT_POINTER(scalloc(155,16););
printStats();
void* p554 = last_address;
DEBUG_PRINT(sfree(p470););
printStats();
PRINT_POINTER(smalloc(92););
printStats();
void* p555 = last_address;
PRINT_POINTER(scalloc(128,140););
printStats();
void* p556 = last_address;
DEBUG_PRINT(sfree(p349););
printStats();
PRINT_POINTER(smalloc(138););
printStats();
void* p557 = last_address;
PRINT_POINTER(scalloc(76,26););
printStats();
void* p558 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p559 = last_address;
DEBUG_PRINT(sfree(p421););
printStats();
PRINT_POINTER(smalloc(249););
printStats();
void* p560 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p561 = last_address;
PRINT_POINTER(srealloc(p442,243););
printStats();
void* p562 = last_address;
PRINT_POINTER(scalloc(99,77););
printStats();
void* p563 = last_address;
PRINT_POINTER(srealloc(p538,8););
printStats();
void* p564 = last_address;
PRINT_POINTER(srealloc(p515,114););
printStats();
void* p565 = last_address;
PRINT_POINTER(srealloc(p496,122););
printStats();
void* p566 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p567 = last_address;
PRINT_POINTER(srealloc(p256,195););
printStats();
void* p568 = last_address;
DEBUG_PRINT(sfree(p543););
printStats();
PRINT_POINTER(srealloc(p257,77););
printStats();
void* p569 = last_address;
PRINT_POINTER(srealloc(p547,22););
printStats();
void* p570 = last_address;
DEBUG_PRINT(sfree(p556););
printStats();
PRINT_POINTER(smalloc(155););
printStats();
void* p571 = last_address;
DEBUG_PRINT(sfree(p235););
printStats();
DEBUG_PRINT(sfree(p518););
printStats();
PRINT_POINTER(scalloc(7,29););
printStats();
void* p572 = last_address;
PRINT_POINTER(scalloc(26,85););
printStats();
void* p573 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p574 = last_address;
PRINT_POINTER(srealloc(p552,113););
printStats();
void* p575 = last_address;
PRINT_POINTER(srealloc(p522,158););
printStats();
void* p576 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p577 = last_address;
DEBUG_PRINT(sfree(p441););
printStats();
PRINT_POINTER(smalloc(183););
printStats();
void* p578 = last_address;
PRINT_POINTER(srealloc(p569,15););
printStats();
void* p579 = last_address;
DEBUG_PRINT(sfree(p475););
printStats();
PRINT_POINTER(srealloc(p554,32););
printStats();
void* p580 = last_address;
PRINT_POINTER(scalloc(14,130););
printStats();
void* p581 = last_address;
PRINT_POINTER(srealloc(p514,206););
printStats();
void* p582 = last_address;
DEBUG_PRINT(sfree(p286););
printStats();
PRINT_POINTER(srealloc(p548,168););
printStats();
void* p583 = last_address;
PRINT_POINTER(srealloc(p540,160););
printStats();
void* p584 = last_address;
PRINT_POINTER(scalloc(114,40););
printStats();
void* p585 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p586 = last_address;
PRINT_POINTER(scalloc(170,145););
printStats();
void* p587 = last_address;
PRINT_POINTER(srealloc(p509,238););
printStats();
void* p588 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p589 = last_address;
PRINT_POINTER(scalloc(241,84););
printStats();
void* p590 = last_address;
DEBUG_PRINT(sfree(p497););
printStats();
PRINT_POINTER(srealloc(p582,177););
printStats();
void* p591 = last_address;
PRINT_POINTER(srealloc(p440,204););
printStats();
void* p592 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p593 = last_address;
DEBUG_PRINT(sfree(p362););
printStats();
PRINT_POINTER(smalloc(42););
printStats();
void* p594 = last_address;
PRINT_POINTER(srealloc(p500,246););
printStats();
void* p595 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p596 = last_address;
PRINT_POINTER(srealloc(p527,66););
printStats();
void* p597 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p598 = last_address;
PRINT_POINTER(scalloc(183,98););
printStats();
void* p599 = last_address;
DEBUG_PRINT(sfree(p544););
printStats();
PRINT_POINTER(scalloc(218,78););
printStats();
void* p600 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p601 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p602 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p603 = last_address;
DEBUG_PRINT(sfree(p562););
printStats();
PRINT_POINTER(smalloc(86););
printStats();
void* p604 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p605 = last_address;
PRINT_POINTER(scalloc(129,116););
printStats();
void* p606 = last_address;
PRINT_POINTER(scalloc(227,110););
printStats();
void* p607 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p608 = last_address;
DEBUG_PRINT(sfree(p462););
printStats();
PRINT_POINTER(srealloc(p512,88););
printStats();
void* p609 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p610 = last_address;
DEBUG_PRINT(sfree(p411););
printStats();
PRINT_POINTER(scalloc(32,152););
printStats();
void* p611 = last_address;
DEBUG_PRINT(sfree(p524););
printStats();
PRINT_POINTER(smalloc(237););
printStats();
void* p612 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p613 = last_address;
PRINT_POINTER(scalloc(44,35););
printStats();
void* p614 = last_address;
DEBUG_PRINT(sfree(p506););
printStats();
PRINT_POINTER(scalloc(19,149););
printStats();
void* p615 = last_address;
DEBUG_PRINT(sfree(p604););
printStats();
PRINT_POINTER(scalloc(224,6););
printStats();
void* p616 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p617 = last_address;
DEBUG_PRINT(sfree(p488););
printStats();
PRINT_POINTER(srealloc(p494,122););
printStats();
void* p618 = last_address;
DEBUG_PRINT(sfree(p248););
printStats();
PRINT_POINTER(scalloc(239,130););
printStats();
void* p619 = last_address;
PRINT_POINTER(srealloc(p413,144););
printStats();
void* p620 = last_address;
PRINT_POINTER(srealloc(p613,112););
printStats();
void* p621 = last_address;
PRINT_POINTER(srealloc(p460,95););
printStats();
void* p622 = last_address;
DEBUG_PRINT(sfree(p316););
printStats();
PRINT_POINTER(srealloc(p307,220););
printStats();
void* p623 = last_address;
PRINT_POINTER(scalloc(109,189););
printStats();
void* p624 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p625 = last_address;
PRINT_POINTER(srealloc(p466,91););
printStats();
void* p626 = last_address;
DEBUG_PRINT(sfree(p517););
printStats();
DEBUG_PRINT(sfree(p356););
printStats();
PRINT_POINTER(scalloc(125,168););
printStats();
void* p627 = last_address;
PRINT_POINTER(srealloc(p519,216););
printStats();
void* p628 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p629 = last_address;
PRINT_POINTER(srealloc(p304,124););
printStats();
void* p630 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p631 = last_address;
PRINT_POINTER(scalloc(187,141););
printStats();
void* p632 = last_address;
PRINT_POINTER(srealloc(p445,23););
printStats();
void* p633 = last_address;
PRINT_POINTER(scalloc(91,211););
printStats();
void* p634 = last_address;
DEBUG_PRINT(sfree(p330););
printStats();
PRINT_POINTER(smalloc(242););
printStats();
void* p635 = last_address;
DEBUG_PRINT(sfree(p444););
printStats();
PRINT_POINTER(smalloc(91););
printStats();
void* p636 = last_address;
PRINT_POINTER(scalloc(31,154););
printStats();
void* p637 = last_address;
DEBUG_PRINT(sfree(p377););
printStats();
PRINT_POINTER(smalloc(164););
printStats();
void* p638 = last_address;
PRINT_POINTER(srealloc(p553,49););
printStats();
void* p639 = last_address;
PRINT_POINTER(srealloc(p596,35););
printStats();
void* p640 = last_address;
PRINT_POINTER(scalloc(235,188););
printStats();
void* p641 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p642 = last_address;
DEBUG_PRINT(sfree(p599););
printStats();
PRINT_POINTER(srealloc(p575,89););
printStats();
void* p643 = last_address;
PRINT_POINTER(srealloc(p598,122););
printStats();
void* p644 = last_address;
PRINT_POINTER(srealloc(p574,174););
printStats();
void* p645 = last_address;
PRINT_POINTER(scalloc(28,232););
printStats();
void* p646 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p647 = last_address;
PRINT_POINTER(srealloc(p507,96););
printStats();
void* p648 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p649 = last_address;
PRINT_POINTER(srealloc(p634,249););
printStats();
void* p650 = last_address;
PRINT_POINTER(srealloc(p632,176););
printStats();
void* p651 = last_address;
PRINT_POINTER(srealloc(p594,148););
printStats();
void* p652 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p653 = last_address;
DEBUG_PRINT(sfree(p589););
printStats();
PRINT_POINTER(scalloc(111,160););
printStats();
void* p654 = last_address;
PRINT_POINTER(srealloc(p611,224););
printStats();
void* p655 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p656 = last_address;
PRINT_POINTER(srealloc(p266,237););
printStats();
void* p657 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p658 = last_address;
PRINT_POINTER(srealloc(p588,190););
printStats();
void* p659 = last_address;
PRINT_POINTER(srealloc(p570,92););
printStats();
void* p660 = last_address;
DEBUG_PRINT(sfree(p606););
printStats();
PRINT_POINTER(smalloc(210););
printStats();
void* p661 = last_address;
PRINT_POINTER(srealloc(p643,115););
printStats();
void* p662 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p663 = last_address;
DEBUG_PRINT(sfree(p648););
printStats();
PRINT_POINTER(srealloc(p531,131););
printStats();
void* p664 = last_address;
PRINT_POINTER(scalloc(158,164););
printStats();
void* p665 = last_address;
PRINT_POINTER(srealloc(p267,151););
printStats();
void* p666 = last_address;
PRINT_POINTER(scalloc(24,187););
printStats();
void* p667 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p668 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p669 = last_address;
DEBUG_PRINT(sfree(p357););
printStats();
DEBUG_PRINT(sfree(p660););
printStats();
DEBUG_PRINT(sfree(p571););
printStats();
DEBUG_PRINT(sfree(p398););
printStats();
DEBUG_PRINT(sfree(p355););
printStats();
PRINT_POINTER(srealloc(p654,201););
printStats();
void* p670 = last_address;
PRINT_POINTER(scalloc(220,238););
printStats();
void* p671 = last_address;
DEBUG_PRINT(sfree(p585););
printStats();
PRINT_POINTER(srealloc(p567,131););
printStats();
void* p672 = last_address;
PRINT_POINTER(srealloc(p670,248););
printStats();
void* p673 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p674 = last_address;
DEBUG_PRINT(sfree(p650););
printStats();
PRINT_POINTER(srealloc(p666,247););
printStats();
void* p675 = last_address;
DEBUG_PRINT(sfree(p609););
printStats();
PRINT_POINTER(smalloc(161););
printStats();
void* p676 = last_address;
DEBUG_PRINT(sfree(p430););
printStats();
DEBUG_PRINT(sfree(p675););
printStats();
DEBUG_PRINT(sfree(p563););
printStats();
PRINT_POINTER(scalloc(120,138););
printStats();
void* p677 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p678 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p679 = last_address;
PRINT_POINTER(srealloc(p420,229););
printStats();
void* p680 = last_address;
PRINT_POINTER(srealloc(p526,129););
printStats();
void* p681 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p682 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p683 = last_address;
DEBUG_PRINT(sfree(p486););
printStats();
PRINT_POINTER(srealloc(p295,98););
printStats();
void* p684 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p685 = last_address;
PRINT_POINTER(srealloc(p474,149););
printStats();
void* p686 = last_address;
PRINT_POINTER(srealloc(p677,195););
printStats();
void* p687 = last_address;
DEBUG_PRINT(sfree(p602););
printStats();
PRINT_POINTER(srealloc(p262,30););
printStats();
void* p688 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p689 = last_address;
DEBUG_PRINT(sfree(p467););
printStats();
PRINT_POINTER(scalloc(163,67););
printStats();
void* p690 = last_address;
PRINT_POINTER(srealloc(p339,88););
printStats();
void* p691 = last_address;
PRINT_POINTER(srealloc(p438,12););
printStats();
void* p692 = last_address;
PRINT_POINTER(scalloc(209,51););
printStats();
void* p693 = last_address;
DEBUG_PRINT(sfree(p631););
printStats();
PRINT_POINTER(scalloc(118,2););
printStats();
void* p694 = last_address;
PRINT_POINTER(scalloc(115,102););
printStats();
void* p695 = last_address;
PRINT_POINTER(srealloc(p617,161););
printStats();
void* p696 = last_address;
PRINT_POINTER(srealloc(p539,230););
printStats();
void* p697 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p698 = last_address;
PRINT_POINTER(scalloc(8,4););
printStats();
void* p699 = last_address;
PRINT_POINTER(srealloc(p333,174););
printStats();
void* p700 = last_address;
DEBUG_PRINT(sfree(p688););
printStats();
DEBUG_PRINT(sfree(p661););
printStats();
DEBUG_PRINT(sfree(p644););
printStats();
PRINT_POINTER(smalloc(21););
printStats();
void* p701 = last_address;
PRINT_POINTER(srealloc(p465,27););
printStats();
void* p702 = last_address;
PRINT_POINTER(srealloc(p381,224););
printStats();
void* p703 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p704 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p705 = last_address;
DEBUG_PRINT(sfree(p600););
printStats();
PRINT_POINTER(srealloc(p664,2););
printStats();
void* p706 = last_address;
PRINT_POINTER(srealloc(p489,30););
printStats();
void* p707 = last_address;
PRINT_POINTER(scalloc(195,165););
printStats();
void* p708 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p709 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p710 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p711 = last_address;
PRINT_POINTER(scalloc(178,50););
printStats();
void* p712 = last_address;
PRINT_POINTER(srealloc(p653,91););
printStats();
void* p713 = last_address;
PRINT_POINTER(scalloc(20,114););
printStats();
void* p714 = last_address;
PRINT_POINTER(srealloc(p671,214););
printStats();
void* p715 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p716 = last_address;
DEBUG_PRINT(sfree(p702););
printStats();
PRINT_POINTER(scalloc(172,122););
printStats();
void* p717 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p718 = last_address;
DEBUG_PRINT(sfree(p453););
printStats();
PRINT_POINTER(srealloc(p686,103););
printStats();
void* p719 = last_address;
PRINT_POINTER(scalloc(105,131););
printStats();
void* p720 = last_address;
PRINT_POINTER(srealloc(p708,99););
printStats();
void* p721 = last_address;
DEBUG_PRINT(sfree(p380););
printStats();
PRINT_POINTER(srealloc(p689,227););
printStats();
void* p722 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p723 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p724 = last_address;
PRINT_POINTER(srealloc(p618,14););
printStats();
void* p725 = last_address;
PRINT_POINTER(scalloc(66,48););
printStats();
void* p726 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p727 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p728 = last_address;
PRINT_POINTER(scalloc(171,44););
printStats();
void* p729 = last_address;
DEBUG_PRINT(sfree(p619););
printStats();
PRINT_POINTER(srealloc(p640,171););
printStats();
void* p730 = last_address;
PRINT_POINTER(scalloc(25,16););
printStats();
void* p731 = last_address;
PRINT_POINTER(srealloc(p672,154););
printStats();
void* p732 = last_address;
PRINT_POINTER(scalloc(5,19););
printStats();
void* p733 = last_address;
DEBUG_PRINT(sfree(p426););
printStats();
PRINT_POINTER(smalloc(46););
printStats();
void* p734 = last_address;
PRINT_POINTER(scalloc(80,224););
printStats();
void* p735 = last_address;
PRINT_POINTER(scalloc(92,23););
printStats();
void* p736 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p737 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p738 = last_address;
PRINT_POINTER(srealloc(p587,156););
printStats();
void* p739 = last_address;
PRINT_POINTER(scalloc(177,164););
printStats();
void* p740 = last_address;
PRINT_POINTER(scalloc(42,69););
printStats();
void* p741 = last_address;
PRINT_POINTER(scalloc(117,233););
printStats();
void* p742 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p743 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p744 = last_address;
PRINT_POINTER(scalloc(15,60););
printStats();
void* p745 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p746 = last_address;
PRINT_POINTER(srealloc(p423,230););
printStats();
void* p747 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p748 = last_address;
PRINT_POINTER(scalloc(104,41););
printStats();
void* p749 = last_address;
PRINT_POINTER(scalloc(123,27););
printStats();
void* p750 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p751 = last_address;
PRINT_POINTER(scalloc(31,23););
printStats();
void* p752 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p753 = last_address;
PRINT_POINTER(scalloc(199,195););
printStats();
void* p754 = last_address;
DEBUG_PRINT(sfree(p694););
printStats();
PRINT_POINTER(srealloc(p627,63););
printStats();
void* p755 = last_address;
DEBUG_PRINT(sfree(p508););
printStats();
PRINT_POINTER(srealloc(p678,16););
printStats();
void* p756 = last_address;
PRINT_POINTER(scalloc(26,238););
printStats();
void* p757 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p758 = last_address;
PRINT_POINTER(srealloc(p591,86););
printStats();
void* p759 = last_address;
PRINT_POINTER(scalloc(215,0););
printStats();
void* p760 = last_address;
DEBUG_PRINT(sfree(p716););
printStats();
PRINT_POINTER(scalloc(210,24););
printStats();
void* p761 = last_address;
PRINT_POINTER(srealloc(p341,182););
printStats();
void* p762 = last_address;
PRINT_POINTER(scalloc(98,220););
printStats();
void* p763 = last_address;
PRINT_POINTER(scalloc(99,195););
printStats();
void* p764 = last_address;
PRINT_POINTER(scalloc(50,133););
printStats();
void* p765 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p766 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p767 = last_address;
DEBUG_PRINT(sfree(p612););
printStats();
DEBUG_PRINT(sfree(p765););
printStats();
PRINT_POINTER(smalloc(66););
printStats();
void* p768 = last_address;
DEBUG_PRINT(sfree(p593););
printStats();
DEBUG_PRINT(sfree(p568););
printStats();
DEBUG_PRINT(sfree(p754););
printStats();
DEBUG_PRINT(sfree(p259););
printStats();
DEBUG_PRINT(sfree(p581););
printStats();
PRINT_POINTER(srealloc(p483,20););
printStats();
void* p769 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p770 = last_address;
PRINT_POINTER(scalloc(168,111););
printStats();
void* p771 = last_address;
DEBUG_PRINT(sfree(p658););
printStats();
PRINT_POINTER(scalloc(242,126););
printStats();
void* p772 = last_address;
DEBUG_PRINT(sfree(p535););
printStats();
DEBUG_PRINT(sfree(p691););
printStats();
PRINT_POINTER(scalloc(249,90););
printStats();
void* p773 = last_address;
PRINT_POINTER(srealloc(p741,20););
printStats();
void* p774 = last_address;
PRINT_POINTER(scalloc(61,85););
printStats();
void* p775 = last_address;
PRINT_POINTER(scalloc(16,225););
printStats();
void* p776 = last_address;
PRINT_POINTER(scalloc(155,190););
printStats();
void* p777 = last_address;
PRINT_POINTER(scalloc(210,217););
printStats();
void* p778 = last_address;
DEBUG_PRINT(sfree(p607););
printStats();
PRINT_POINTER(smalloc(202););
printStats();
void* p779 = last_address;
PRINT_POINTER(scalloc(187,83););
printStats();
void* p780 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p781 = last_address;
DEBUG_PRINT(sfree(p739););
printStats();
DEBUG_PRINT(sfree(p762););
printStats();
PRINT_POINTER(smalloc(16););
printStats();
void* p782 = last_address;
PRINT_POINTER(scalloc(98,4););
printStats();
void* p783 = last_address;
PRINT_POINTER(srealloc(p731,202););
printStats();
void* p784 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p785 = last_address;
DEBUG_PRINT(sfree(p638););
printStats();
DEBUG_PRINT(sfree(p690););
printStats();
PRINT_POINTER(srealloc(p620,233););
printStats();
void* p786 = last_address;
PRINT_POINTER(srealloc(p662,165););
printStats();
void* p787 = last_address;
DEBUG_PRINT(sfree(p557););
printStats();
PRINT_POINTER(srealloc(p683,143););
printStats();
void* p788 = last_address;
PRINT_POINTER(srealloc(p696,60););
printStats();
void* p789 = last_address;
PRINT_POINTER(srealloc(p699,127););
printStats();
void* p790 = last_address;
PRINT_POINTER(scalloc(115,144););
printStats();
void* p791 = last_address;
DEBUG_PRINT(sfree(p753););
printStats();
PRINT_POINTER(smalloc(56););
printStats();
void* p792 = last_address;
PRINT_POINTER(srealloc(p763,15););
printStats();
void* p793 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p794 = last_address;
DEBUG_PRINT(sfree(p476););
printStats();
PRINT_POINTER(scalloc(130,35););
printStats();
void* p795 = last_address;
DEBUG_PRINT(sfree(p745););
printStats();
PRINT_POINTER(srealloc(p621,72););
printStats();
void* p796 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p797 = last_address;
DEBUG_PRINT(sfree(p674););
printStats();
PRINT_POINTER(srealloc(p756,110););
printStats();
void* p798 = last_address;
DEBUG_PRINT(sfree(p673););
printStats();
PRINT_POINTER(smalloc(113););
printStats();
void* p799 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p800 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p801 = last_address;
PRINT_POINTER(srealloc(p729,81););
printStats();
void* p802 = last_address;
PRINT_POINTER(srealloc(p758,165););
printStats();
void* p803 = last_address;
PRINT_POINTER(srealloc(p789,97););
printStats();
void* p804 = last_address;
DEBUG_PRINT(sfree(p639););
printStats();
PRINT_POINTER(smalloc(13););
printStats();
void* p805 = last_address;
PRINT_POINTER(scalloc(113,215););
printStats();
void* p806 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p807 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p808 = last_address;
PRINT_POINTER(srealloc(p484,73););
printStats();
void* p809 = last_address;
PRINT_POINTER(scalloc(101,74););
printStats();
void* p810 = last_address;
DEBUG_PRINT(sfree(p679););
printStats();
DEBUG_PRINT(sfree(p635););
printStats();
PRINT_POINTER(srealloc(p719,83););
printStats();
void* p811 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p812 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p813 = last_address;
DEBUG_PRINT(sfree(p706););
printStats();
PRINT_POINTER(srealloc(p715,246););
printStats();
void* p814 = last_address;
PRINT_POINTER(scalloc(195,65););
printStats();
void* p815 = last_address;
PRINT_POINTER(srealloc(p623,121););
printStats();
void* p816 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p817 = last_address;
PRINT_POINTER(scalloc(249,88););
printStats();
void* p818 = last_address;
DEBUG_PRINT(sfree(p733););
printStats();
PRINT_POINTER(scalloc(105,239););
printStats();
void* p819 = last_address;
PRINT_POINTER(scalloc(128,187););
printStats();
void* p820 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p821 = last_address;
DEBUG_PRINT(sfree(p454););
printStats();
DEBUG_PRINT(sfree(p799););
printStats();
DEBUG_PRINT(sfree(p814););
printStats();
PRINT_POINTER(scalloc(99,69););
printStats();
void* p822 = last_address;
PRINT_POINTER(srealloc(p682,153););
printStats();
void* p823 = last_address;
PRINT_POINTER(srealloc(p748,127););
printStats();
void* p824 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p825 = last_address;
DEBUG_PRINT(sfree(p642););
printStats();
PRINT_POINTER(scalloc(152,16););
printStats();
void* p826 = last_address;
PRINT_POINTER(srealloc(p576,140););
printStats();
void* p827 = last_address;
PRINT_POINTER(srealloc(p216,163););
printStats();
void* p828 = last_address;
PRINT_POINTER(srealloc(p695,18););
printStats();
void* p829 = last_address;
DEBUG_PRINT(sfree(p705););
printStats();
DEBUG_PRINT(sfree(p667););
printStats();
PRINT_POINTER(srealloc(p656,172););
printStats();
void* p830 = last_address;
PRINT_POINTER(srealloc(p700,177););
printStats();
void* p831 = last_address;
DEBUG_PRINT(sfree(p435););
printStats();
PRINT_POINTER(scalloc(211,38););
printStats();
void* p832 = last_address;
DEBUG_PRINT(sfree(p782););
printStats();
DEBUG_PRINT(sfree(p797););
printStats();
PRINT_POINTER(scalloc(151,80););
printStats();
void* p833 = last_address;
PRINT_POINTER(srealloc(p646,224););
printStats();
void* p834 = last_address;
PRINT_POINTER(scalloc(131,84););
printStats();
void* p835 = last_address;
PRINT_POINTER(scalloc(239,180););
printStats();
void* p836 = last_address;
DEBUG_PRINT(sfree(p778););
printStats();
PRINT_POINTER(scalloc(158,17););
printStats();
void* p837 = last_address;
PRINT_POINTER(srealloc(p558,208););
printStats();
void* p838 = last_address;
PRINT_POINTER(srealloc(p492,94););
printStats();
void* p839 = last_address;
DEBUG_PRINT(sfree(p772););
printStats();
PRINT_POINTER(srealloc(p836,44););
printStats();
void* p840 = last_address;
PRINT_POINTER(scalloc(102,134););
printStats();
void* p841 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p842 = last_address;
PRINT_POINTER(srealloc(p382,116););
printStats();
void* p843 = last_address;
PRINT_POINTER(srealloc(p821,133););
printStats();
void* p844 = last_address;
PRINT_POINTER(srealloc(p559,231););
printStats();
void* p845 = last_address;
PRINT_POINTER(scalloc(50,140););
printStats();
void* p846 = last_address;
DEBUG_PRINT(sfree(p253););
printStats();
PRINT_POINTER(scalloc(6,53););
printStats();
void* p847 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p848 = last_address;
PRINT_POINTER(srealloc(p443,48););
printStats();
void* p849 = last_address;
PRINT_POINTER(scalloc(56,105););
printStats();
void* p850 = last_address;
DEBUG_PRINT(sfree(p776););
printStats();
DEBUG_PRINT(sfree(p584););
printStats();
PRINT_POINTER(smalloc(231););
printStats();
void* p851 = last_address;
DEBUG_PRINT(sfree(p787););
printStats();
DEBUG_PRINT(sfree(p566););
printStats();
PRINT_POINTER(srealloc(p848,19););
printStats();
void* p852 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p853 = last_address;
PRINT_POINTER(srealloc(p743,182););
printStats();
void* p854 = last_address;
DEBUG_PRINT(sfree(p537););
printStats();
PRINT_POINTER(scalloc(185,177););
printStats();
void* p855 = last_address;
PRINT_POINTER(srealloc(p528,57););
printStats();
void* p856 = last_address;
PRINT_POINTER(scalloc(65,167););
printStats();
void* p857 = last_address;
PRINT_POINTER(srealloc(p701,171););
printStats();
void* p858 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p859 = last_address;
DEBUG_PRINT(sfree(p817););
printStats();
PRINT_POINTER(srealloc(p850,210););
printStats();
void* p860 = last_address;
PRINT_POINTER(scalloc(101,205););
printStats();
void* p861 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p862 = last_address;
PRINT_POINTER(srealloc(p400,33););
printStats();
void* p863 = last_address;
DEBUG_PRINT(sfree(p468););
printStats();
DEBUG_PRINT(sfree(p711););
printStats();
PRINT_POINTER(scalloc(143,11););
printStats();
void* p864 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p865 = last_address;
DEBUG_PRINT(sfree(p592););
printStats();
PRINT_POINTER(smalloc(213););
printStats();
void* p866 = last_address;
PRINT_POINTER(srealloc(p732,17););
printStats();
void* p867 = last_address;
PRINT_POINTER(scalloc(193,10););
printStats();
void* p868 = last_address;
PRINT_POINTER(srealloc(p855,44););
printStats();
void* p869 = last_address;
PRINT_POINTER(scalloc(1,161););
printStats();
void* p870 = last_address;
DEBUG_PRINT(sfree(p649););
printStats();
DEBUG_PRINT(sfree(p730););
printStats();
PRINT_POINTER(srealloc(p857,15););
printStats();
void* p871 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p872 = last_address;
PRINT_POINTER(scalloc(44,196););
printStats();
void* p873 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p874 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p875 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p876 = last_address;
DEBUG_PRINT(sfree(p684););
printStats();
DEBUG_PRINT(sfree(p874););
printStats();
DEBUG_PRINT(sfree(p843););
printStats();
PRINT_POINTER(srealloc(p796,248););
printStats();
void* p877 = last_address;
PRINT_POINTER(srealloc(p624,47););
printStats();
void* p878 = last_address;
PRINT_POINTER(srealloc(p805,219););
printStats();
void* p879 = last_address;
DEBUG_PRINT(sfree(p759););
printStats();
PRINT_POINTER(smalloc(69););
printStats();
void* p880 = last_address;
PRINT_POINTER(srealloc(p710,14););
printStats();
void* p881 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p882 = last_address;
DEBUG_PRINT(sfree(p555););
printStats();
PRINT_POINTER(scalloc(71,27););
printStats();
void* p883 = last_address;
DEBUG_PRINT(sfree(p866););
printStats();
PRINT_POINTER(srealloc(p853,90););
printStats();
void* p884 = last_address;
PRINT_POINTER(srealloc(p773,200););
printStats();
void* p885 = last_address;
DEBUG_PRINT(sfree(p742););
printStats();
DEBUG_PRINT(sfree(p824););
printStats();
PRINT_POINTER(smalloc(236););
printStats();
void* p886 = last_address;
PRINT_POINTER(srealloc(p834,225););
printStats();
void* p887 = last_address;
PRINT_POINTER(srealloc(p717,226););
printStats();
void* p888 = last_address;
PRINT_POINTER(scalloc(103,222););
printStats();
void* p889 = last_address;
DEBUG_PRINT(sfree(p735););
printStats();
PRINT_POINTER(scalloc(193,52););
printStats();
void* p890 = last_address;
DEBUG_PRINT(sfree(p579););
printStats();
PRINT_POINTER(srealloc(p749,115););
printStats();
void* p891 = last_address;
PRINT_POINTER(srealloc(p573,156););
printStats();
void* p892 = last_address;
DEBUG_PRINT(sfree(p629););
printStats();
PRINT_POINTER(scalloc(48,67););
printStats();
void* p893 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p894 = last_address;
PRINT_POINTER(srealloc(p687,196););
printStats();
void* p895 = last_address;
PRINT_POINTER(scalloc(27,171););
printStats();
void* p896 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p897 = last_address;
PRINT_POINTER(srealloc(p873,94););
printStats();
void* p898 = last_address;
PRINT_POINTER(srealloc(p669,9););
printStats();
void* p899 = last_address;
PRINT_POINTER(srealloc(p697,247););
printStats();
void* p900 = last_address;
DEBUG_PRINT(sfree(p704););
printStats();
DEBUG_PRINT(sfree(p808););
printStats();
DEBUG_PRINT(sfree(p676););
printStats();
PRINT_POINTER(scalloc(109,182););
printStats();
void* p901 = last_address;
DEBUG_PRINT(sfree(p427););
printStats();
PRINT_POINTER(srealloc(p626,64););
printStats();
void* p902 = last_address;
PRINT_POINTER(srealloc(p665,183););
printStats();
void* p903 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p904 = last_address;
PRINT_POINTER(srealloc(p895,165););
printStats();
void* p905 = last_address;
PRINT_POINTER(srealloc(p810,92););
printStats();
void* p906 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p907 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p908 = last_address;
DEBUG_PRINT(sfree(p790););
printStats();
PRINT_POINTER(smalloc(229););
printStats();
void* p909 = last_address;
PRINT_POINTER(scalloc(108,218););
printStats();
void* p910 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p911 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
PRINT_POINTER(scalloc(243,94););
printStats();
void* p912 = last_address;
DEBUG_PRINT(sfree(p529););
printStats();
PRINT_POINTER(scalloc(57,159););
printStats();
void* p913 = last_address;
PRINT_POINTER(srealloc(p718,157););
printStats();
void* p914 = last_address;
DEBUG_PRINT(sfree(p502););
printStats();
PRINT_POINTER(srealloc(p393,24););
printStats();
void* p915 = last_address;
DEBUG_PRINT(sfree(p651););
printStats();
PRINT_POINTER(scalloc(193,183););
printStats();
void* p916 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p917 = last_address;
DEBUG_PRINT(sfree(p645););
printStats();
DEBUG_PRINT(sfree(p831););
printStats();
DEBUG_PRINT(sfree(p876););
printStats();
DEBUG_PRINT(sfree(p636););
printStats();
PRINT_POINTER(srealloc(p723,127););
printStats();
void* p918 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p919 = last_address;
PRINT_POINTER(scalloc(179,131););
printStats();
void* p920 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p921 = last_address;
DEBUG_PRINT(sfree(p703););
printStats();
PRINT_POINTER(scalloc(54,185););
printStats();
void* p922 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p923 = last_address;
PRINT_POINTER(scalloc(83,249););
printStats();
void* p924 = last_address;
DEBUG_PRINT(sfree(p849););
printStats();
PRINT_POINTER(smalloc(71););
printStats();
void* p925 = last_address;
PRINT_POINTER(scalloc(97,124););
printStats();
void* p926 = last_address;
PRINT_POINTER(srealloc(p580,143););
printStats();
void* p927 = last_address;
PRINT_POINTER(scalloc(203,244););
printStats();
void* p928 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p929 = last_address;
PRINT_POINTER(scalloc(146,108););
printStats();
void* p930 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p931 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p932 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p933 = last_address;
PRINT_POINTER(srealloc(p905,30););
printStats();
void* p934 = last_address;
PRINT_POINTER(srealloc(p802,226););
printStats();
void* p935 = last_address;
PRINT_POINTER(scalloc(137,122););
printStats();
void* p936 = last_address;
DEBUG_PRINT(sfree(p792););
printStats();
DEBUG_PRINT(sfree(p722););
printStats();
PRINT_POINTER(smalloc(246););
printStats();
void* p937 = last_address;
PRINT_POINTER(srealloc(p883,50););
printStats();
void* p938 = last_address;
PRINT_POINTER(scalloc(134,139););
printStats();
void* p939 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p940 = last_address;
PRINT_POINTER(scalloc(75,71););
printStats();
void* p941 = last_address;
}
