#include "aux_macro.h"
#include "../malloc_4.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(9,164););
printStats();
void* p0 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p1 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p2 = last_address;
PRINT_POINTER(srealloc(p1,182););
printStats();
void* p3 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(smalloc(181););
printStats();
void* p4 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(scalloc(247,169););
printStats();
void* p5 = last_address;
PRINT_POINTER(srealloc(p3,117););
printStats();
void* p6 = last_address;
PRINT_POINTER(srealloc(p5,118););
printStats();
void* p7 = last_address;
PRINT_POINTER(srealloc(p7,29););
printStats();
void* p8 = last_address;
PRINT_POINTER(srealloc(p4,140););
printStats();
void* p9 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p10 = last_address;
PRINT_POINTER(srealloc(p9,50););
printStats();
void* p11 = last_address;
PRINT_POINTER(srealloc(p11,141););
printStats();
void* p12 = last_address;
DEBUG_PRINT(sfree(p10););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p13 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p14 = last_address;
DEBUG_PRINT(sfree(p13););
printStats();
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(srealloc(p12,68););
printStats();
void* p15 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(smalloc(88););
printStats();
void* p16 = last_address;
PRINT_POINTER(scalloc(55,192););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(68,50););
printStats();
void* p18 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p20 = last_address;
PRINT_POINTER(scalloc(119,16););
printStats();
void* p21 = last_address;
PRINT_POINTER(srealloc(p18,131););
printStats();
void* p22 = last_address;
PRINT_POINTER(scalloc(183,14););
printStats();
void* p23 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p24 = last_address;
PRINT_POINTER(srealloc(p20,176););
printStats();
void* p25 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p26 = last_address;
PRINT_POINTER(scalloc(218,42););
printStats();
void* p27 = last_address;
PRINT_POINTER(scalloc(47,19););
printStats();
void* p28 = last_address;
PRINT_POINTER(scalloc(76,184););
printStats();
void* p29 = last_address;
PRINT_POINTER(srealloc(p6,25););
printStats();
void* p30 = last_address;
PRINT_POINTER(srealloc(p21,11););
printStats();
void* p31 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
PRINT_POINTER(smalloc(77););
printStats();
void* p32 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p33 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p34 = last_address;
PRINT_POINTER(scalloc(212,33););
printStats();
void* p35 = last_address;
PRINT_POINTER(srealloc(p8,49););
printStats();
void* p36 = last_address;
DEBUG_PRINT(sfree(p32););
printStats();
PRINT_POINTER(smalloc(103););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(223,44););
printStats();
void* p38 = last_address;
PRINT_POINTER(scalloc(219,173););
printStats();
void* p39 = last_address;
PRINT_POINTER(scalloc(6,190););
printStats();
void* p40 = last_address;
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(srealloc(p25,14););
printStats();
void* p41 = last_address;
PRINT_POINTER(srealloc(p19,85););
printStats();
void* p42 = last_address;
PRINT_POINTER(srealloc(p30,98););
printStats();
void* p43 = last_address;
DEBUG_PRINT(sfree(p23););
printStats();
PRINT_POINTER(smalloc(171););
printStats();
void* p44 = last_address;
PRINT_POINTER(srealloc(p33,13););
printStats();
void* p45 = last_address;
PRINT_POINTER(scalloc(110,26););
printStats();
void* p46 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
DEBUG_PRINT(sfree(p39););
printStats();
PRINT_POINTER(scalloc(109,217););
printStats();
void* p47 = last_address;
PRINT_POINTER(scalloc(241,88););
printStats();
void* p48 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p49 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p50 = last_address;
PRINT_POINTER(srealloc(p17,226););
printStats();
void* p51 = last_address;
DEBUG_PRINT(sfree(p49););
printStats();
PRINT_POINTER(smalloc(65););
printStats();
void* p52 = last_address;
PRINT_POINTER(srealloc(p41,36););
printStats();
void* p53 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(srealloc(p36,160););
printStats();
void* p54 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(srealloc(p16,44););
printStats();
void* p55 = last_address;
PRINT_POINTER(srealloc(p48,178););
printStats();
void* p56 = last_address;
PRINT_POINTER(scalloc(68,216););
printStats();
void* p57 = last_address;
DEBUG_PRINT(sfree(p27););
printStats();
PRINT_POINTER(scalloc(176,43););
printStats();
void* p58 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
DEBUG_PRINT(sfree(p57););
printStats();
DEBUG_PRINT(sfree(p47););
printStats();
PRINT_POINTER(srealloc(p34,164););
printStats();
void* p59 = last_address;
PRINT_POINTER(srealloc(p35,34););
printStats();
void* p60 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p61 = last_address;
PRINT_POINTER(scalloc(214,131););
printStats();
void* p62 = last_address;
PRINT_POINTER(srealloc(p62,144););
printStats();
void* p63 = last_address;
PRINT_POINTER(scalloc(70,7););
printStats();
void* p64 = last_address;
PRINT_POINTER(scalloc(224,90););
printStats();
void* p65 = last_address;
PRINT_POINTER(srealloc(p55,247););
printStats();
void* p66 = last_address;
PRINT_POINTER(scalloc(39,51););
printStats();
void* p67 = last_address;
DEBUG_PRINT(sfree(p67););
printStats();
DEBUG_PRINT(sfree(p22););
printStats();
DEBUG_PRINT(sfree(p54););
printStats();
PRINT_POINTER(srealloc(p51,1););
printStats();
void* p68 = last_address;
PRINT_POINTER(scalloc(93,158););
printStats();
void* p69 = last_address;
PRINT_POINTER(scalloc(123,129););
printStats();
void* p70 = last_address;
PRINT_POINTER(srealloc(p68,2););
printStats();
void* p71 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p72 = last_address;
PRINT_POINTER(scalloc(32,205););
printStats();
void* p73 = last_address;
PRINT_POINTER(srealloc(p58,108););
printStats();
void* p74 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p75 = last_address;
DEBUG_PRINT(sfree(p75););
printStats();
PRINT_POINTER(scalloc(57,95););
printStats();
void* p76 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p77 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p78 = last_address;
PRINT_POINTER(scalloc(5,248););
printStats();
void* p79 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p80 = last_address;
PRINT_POINTER(srealloc(p79,226););
printStats();
void* p81 = last_address;
PRINT_POINTER(scalloc(8,100););
printStats();
void* p82 = last_address;
DEBUG_PRINT(sfree(p82););
printStats();
PRINT_POINTER(srealloc(p81,51););
printStats();
void* p83 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(srealloc(p42,120););
printStats();
void* p84 = last_address;
PRINT_POINTER(srealloc(p60,129););
printStats();
void* p85 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p86 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p87 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p88 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p89 = last_address;
PRINT_POINTER(scalloc(242,133););
printStats();
void* p90 = last_address;
DEBUG_PRINT(sfree(p53););
printStats();
PRINT_POINTER(scalloc(216,140););
printStats();
void* p91 = last_address;
DEBUG_PRINT(sfree(p76););
printStats();
PRINT_POINTER(smalloc(100););
printStats();
void* p92 = last_address;
PRINT_POINTER(srealloc(p85,233););
printStats();
void* p93 = last_address;
PRINT_POINTER(scalloc(68,5););
printStats();
void* p94 = last_address;
PRINT_POINTER(srealloc(p63,147););
printStats();
void* p95 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p96 = last_address;
DEBUG_PRINT(sfree(p83););
printStats();
PRINT_POINTER(scalloc(247,32););
printStats();
void* p97 = last_address;
PRINT_POINTER(srealloc(p91,190););
printStats();
void* p98 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p99 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p100 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p101 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(scalloc(217,36););
printStats();
void* p102 = last_address;
PRINT_POINTER(scalloc(220,127););
printStats();
void* p103 = last_address;
DEBUG_PRINT(sfree(p99););
printStats();
PRINT_POINTER(scalloc(134,181););
printStats();
void* p104 = last_address;
DEBUG_PRINT(sfree(p44););
printStats();
PRINT_POINTER(srealloc(p102,150););
printStats();
void* p105 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p106 = last_address;
PRINT_POINTER(srealloc(p70,189););
printStats();
void* p107 = last_address;
PRINT_POINTER(scalloc(183,3););
printStats();
void* p108 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p109 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(scalloc(55,230););
printStats();
void* p110 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p111 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p112 = last_address;
PRINT_POINTER(scalloc(111,195););
printStats();
void* p113 = last_address;
PRINT_POINTER(scalloc(72,155););
printStats();
void* p114 = last_address;
PRINT_POINTER(srealloc(p101,148););
printStats();
void* p115 = last_address;
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(srealloc(p87,215););
printStats();
void* p116 = last_address;
PRINT_POINTER(srealloc(p71,55););
printStats();
void* p117 = last_address;
PRINT_POINTER(scalloc(158,53););
printStats();
void* p118 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p119 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p120 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p121 = last_address;
PRINT_POINTER(scalloc(127,14););
printStats();
void* p122 = last_address;
PRINT_POINTER(srealloc(p98,147););
printStats();
void* p123 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p124 = last_address;
PRINT_POINTER(scalloc(39,110););
printStats();
void* p125 = last_address;
PRINT_POINTER(scalloc(110,185););
printStats();
void* p126 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p127 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p128 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p129 = last_address;
PRINT_POINTER(scalloc(189,197););
printStats();
void* p130 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(srealloc(p109,209););
printStats();
void* p131 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p132 = last_address;
PRINT_POINTER(scalloc(140,64););
printStats();
void* p133 = last_address;
PRINT_POINTER(srealloc(p73,13););
printStats();
void* p134 = last_address;
PRINT_POINTER(srealloc(p133,58););
printStats();
void* p135 = last_address;
PRINT_POINTER(scalloc(140,17););
printStats();
void* p136 = last_address;
PRINT_POINTER(scalloc(113,219););
printStats();
void* p137 = last_address;
PRINT_POINTER(srealloc(p137,222););
printStats();
void* p138 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p135););
printStats();
PRINT_POINTER(smalloc(208););
printStats();
void* p140 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p64,229););
printStats();
void* p142 = last_address;
DEBUG_PRINT(sfree(p139););
printStats();
PRINT_POINTER(smalloc(75););
printStats();
void* p143 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p144 = last_address;
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(srealloc(p107,36););
printStats();
void* p145 = last_address;
DEBUG_PRINT(sfree(p65););
printStats();
DEBUG_PRINT(sfree(p129););
printStats();
PRINT_POINTER(srealloc(p93,89););
printStats();
void* p146 = last_address;
PRINT_POINTER(scalloc(5,243););
printStats();
void* p147 = last_address;
PRINT_POINTER(srealloc(p128,205););
printStats();
void* p148 = last_address;
PRINT_POINTER(srealloc(p94,91););
printStats();
void* p149 = last_address;
PRINT_POINTER(scalloc(105,124););
printStats();
void* p150 = last_address;
PRINT_POINTER(srealloc(p95,123););
printStats();
void* p151 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p152 = last_address;
PRINT_POINTER(scalloc(81,192););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(151,249););
printStats();
void* p154 = last_address;
PRINT_POINTER(scalloc(59,98););
printStats();
void* p155 = last_address;
DEBUG_PRINT(sfree(p110););
printStats();
DEBUG_PRINT(sfree(p155););
printStats();
PRINT_POINTER(scalloc(47,215););
printStats();
void* p156 = last_address;
PRINT_POINTER(scalloc(95,34););
printStats();
void* p157 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(smalloc(103););
printStats();
void* p158 = last_address;
PRINT_POINTER(srealloc(p145,119););
printStats();
void* p159 = last_address;
PRINT_POINTER(scalloc(204,63););
printStats();
void* p160 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(srealloc(p56,152););
printStats();
void* p161 = last_address;
PRINT_POINTER(scalloc(79,140););
printStats();
void* p162 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p163 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p164 = last_address;
PRINT_POINTER(scalloc(89,237););
printStats();
void* p165 = last_address;
PRINT_POINTER(scalloc(125,94););
printStats();
void* p166 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p167 = last_address;
PRINT_POINTER(srealloc(p112,237););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(30,43););
printStats();
void* p169 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p170 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p171 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p172 = last_address;
PRINT_POINTER(srealloc(p172,130););
printStats();
void* p173 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p174 = last_address;
PRINT_POINTER(srealloc(p118,233););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p106););
printStats();
PRINT_POINTER(smalloc(162););
printStats();
void* p176 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p177 = last_address;
PRINT_POINTER(srealloc(p164,116););
printStats();
void* p178 = last_address;
PRINT_POINTER(scalloc(74,25););
printStats();
void* p179 = last_address;
PRINT_POINTER(scalloc(146,154););
printStats();
void* p180 = last_address;
PRINT_POINTER(srealloc(p169,35););
printStats();
void* p181 = last_address;
DEBUG_PRINT(sfree(p126););
printStats();
PRINT_POINTER(smalloc(102););
printStats();
void* p182 = last_address;
PRINT_POINTER(scalloc(156,150););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(205,122););
printStats();
void* p184 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(scalloc(193,249););
printStats();
void* p185 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p186 = last_address;
PRINT_POINTER(scalloc(45,75););
printStats();
void* p187 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p188 = last_address;
PRINT_POINTER(scalloc(93,110););
printStats();
void* p189 = last_address;
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(smalloc(83););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p191 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p192 = last_address;
DEBUG_PRINT(sfree(p168););
printStats();
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(scalloc(231,137););
printStats();
void* p193 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p194 = last_address;
PRINT_POINTER(srealloc(p97,249););
printStats();
void* p195 = last_address;
PRINT_POINTER(srealloc(p187,130););
printStats();
void* p196 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p197 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p198 = last_address;
PRINT_POINTER(scalloc(139,225););
printStats();
void* p199 = last_address;
PRINT_POINTER(scalloc(239,199););
printStats();
void* p200 = last_address;
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(scalloc(143,24););
printStats();
void* p201 = last_address;
PRINT_POINTER(srealloc(p77,206););
printStats();
void* p202 = last_address;
PRINT_POINTER(srealloc(p160,6););
printStats();
void* p203 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p204 = last_address;
DEBUG_PRINT(sfree(p136););
printStats();
PRINT_POINTER(srealloc(p116,140););
printStats();
void* p205 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p206 = last_address;
PRINT_POINTER(scalloc(216,3););
printStats();
void* p207 = last_address;
PRINT_POINTER(srealloc(p201,76););
printStats();
void* p208 = last_address;
DEBUG_PRINT(sfree(p61););
printStats();
PRINT_POINTER(srealloc(p173,218););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(246,239););
printStats();
void* p210 = last_address;
PRINT_POINTER(scalloc(116,21););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(146,223););
printStats();
void* p212 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p213 = last_address;
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(scalloc(10,141););
printStats();
void* p214 = last_address;
PRINT_POINTER(scalloc(219,173););
printStats();
void* p215 = last_address;
PRINT_POINTER(scalloc(85,68););
printStats();
void* p216 = last_address;
PRINT_POINTER(srealloc(p150,24););
printStats();
void* p217 = last_address;
PRINT_POINTER(scalloc(204,161););
printStats();
void* p218 = last_address;
DEBUG_PRINT(sfree(p207););
printStats();
PRINT_POINTER(smalloc(37););
printStats();
void* p219 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p220 = last_address;
PRINT_POINTER(srealloc(p66,126););
printStats();
void* p221 = last_address;
PRINT_POINTER(scalloc(234,136););
printStats();
void* p222 = last_address;
DEBUG_PRINT(sfree(p220););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p223 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p224 = last_address;
PRINT_POINTER(srealloc(p103,220););
printStats();
void* p225 = last_address;
PRINT_POINTER(srealloc(p167,51););
printStats();
void* p226 = last_address;
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(srealloc(p108,76););
printStats();
void* p227 = last_address;
PRINT_POINTER(srealloc(p154,5););
printStats();
void* p228 = last_address;
PRINT_POINTER(scalloc(207,198););
printStats();
void* p229 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p230 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p231 = last_address;
PRINT_POINTER(srealloc(p223,242););
printStats();
void* p232 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p233 = last_address;
DEBUG_PRINT(sfree(p105););
printStats();
PRINT_POINTER(srealloc(p152,33););
printStats();
void* p234 = last_address;
PRINT_POINTER(scalloc(54,29););
printStats();
void* p235 = last_address;
PRINT_POINTER(srealloc(p198,190););
printStats();
void* p236 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p237 = last_address;
DEBUG_PRINT(sfree(p117););
printStats();
PRINT_POINTER(srealloc(p122,105););
printStats();
void* p238 = last_address;
DEBUG_PRINT(sfree(p235););
printStats();
DEBUG_PRINT(sfree(p229););
printStats();
PRINT_POINTER(scalloc(237,45););
printStats();
void* p239 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p240 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p241 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(srealloc(p140,208););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
PRINT_POINTER(smalloc(206););
printStats();
void* p244 = last_address;
PRINT_POINTER(scalloc(71,74););
printStats();
void* p245 = last_address;
PRINT_POINTER(srealloc(p59,184););
printStats();
void* p246 = last_address;
PRINT_POINTER(srealloc(p131,213););
printStats();
void* p247 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p248 = last_address;
PRINT_POINTER(scalloc(50,23););
printStats();
void* p249 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
DEBUG_PRINT(sfree(p197););
printStats();
PRINT_POINTER(smalloc(1););
printStats();
void* p250 = last_address;
PRINT_POINTER(scalloc(9,243););
printStats();
void* p251 = last_address;
PRINT_POINTER(srealloc(p182,212););
printStats();
void* p252 = last_address;
PRINT_POINTER(scalloc(193,139););
printStats();
void* p253 = last_address;
PRINT_POINTER(scalloc(226,7););
printStats();
void* p254 = last_address;
PRINT_POINTER(scalloc(235,163););
printStats();
void* p255 = last_address;
PRINT_POINTER(srealloc(p209,170););
printStats();
void* p256 = last_address;
DEBUG_PRINT(sfree(p184););
printStats();
PRINT_POINTER(scalloc(234,82););
printStats();
void* p257 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p258 = last_address;
PRINT_POINTER(srealloc(p224,145););
printStats();
void* p259 = last_address;
PRINT_POINTER(srealloc(p149,240););
printStats();
void* p260 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p261 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p262 = last_address;
PRINT_POINTER(scalloc(78,186););
printStats();
void* p263 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p264 = last_address;
PRINT_POINTER(scalloc(221,163););
printStats();
void* p265 = last_address;
PRINT_POINTER(srealloc(p144,82););
printStats();
void* p266 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p267 = last_address;
PRINT_POINTER(scalloc(60,100););
printStats();
void* p268 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p269 = last_address;
PRINT_POINTER(srealloc(p208,97););
printStats();
void* p270 = last_address;
PRINT_POINTER(srealloc(p265,188););
printStats();
void* p271 = last_address;
PRINT_POINTER(srealloc(p121,199););
printStats();
void* p272 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p273 = last_address;
PRINT_POINTER(scalloc(169,11););
printStats();
void* p274 = last_address;
PRINT_POINTER(scalloc(111,93););
printStats();
void* p275 = last_address;
PRINT_POINTER(scalloc(218,132););
printStats();
void* p276 = last_address;
PRINT_POINTER(srealloc(p96,146););
printStats();
void* p277 = last_address;
PRINT_POINTER(scalloc(203,200););
printStats();
void* p278 = last_address;
PRINT_POINTER(scalloc(157,112););
printStats();
void* p279 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p280 = last_address;
DEBUG_PRINT(sfree(p251););
printStats();
PRINT_POINTER(srealloc(p161,122););
printStats();
void* p281 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p282 = last_address;
PRINT_POINTER(scalloc(247,109););
printStats();
void* p283 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p185,36););
printStats();
void* p285 = last_address;
PRINT_POINTER(srealloc(p175,186););
printStats();
void* p286 = last_address;
DEBUG_PRINT(sfree(p88););
printStats();
DEBUG_PRINT(sfree(p219););
printStats();
PRINT_POINTER(srealloc(p50,161););
printStats();
void* p287 = last_address;
DEBUG_PRINT(sfree(p123););
printStats();
DEBUG_PRINT(sfree(p138););
printStats();
PRINT_POINTER(scalloc(20,172););
printStats();
void* p288 = last_address;
PRINT_POINTER(srealloc(p255,114););
printStats();
void* p289 = last_address;
PRINT_POINTER(srealloc(p143,198););
printStats();
void* p290 = last_address;
DEBUG_PRINT(sfree(p191););
printStats();
DEBUG_PRINT(sfree(p74););
printStats();
DEBUG_PRINT(sfree(p120););
printStats();
PRINT_POINTER(srealloc(p228,209););
printStats();
void* p291 = last_address;
DEBUG_PRINT(sfree(p247););
printStats();
PRINT_POINTER(scalloc(46,220););
printStats();
void* p292 = last_address;
PRINT_POINTER(srealloc(p111,136););
printStats();
void* p293 = last_address;
PRINT_POINTER(scalloc(28,125););
printStats();
void* p294 = last_address;
PRINT_POINTER(srealloc(p232,249););
printStats();
void* p295 = last_address;
PRINT_POINTER(srealloc(p166,178););
printStats();
void* p296 = last_address;
PRINT_POINTER(scalloc(95,226););
printStats();
void* p297 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p298 = last_address;
PRINT_POINTER(srealloc(p206,122););
printStats();
void* p299 = last_address;
DEBUG_PRINT(sfree(p225););
printStats();
PRINT_POINTER(scalloc(203,160););
printStats();
void* p300 = last_address;
PRINT_POINTER(srealloc(p216,29););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p302 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p303 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p304 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p305 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p306 = last_address;
PRINT_POINTER(scalloc(162,48););
printStats();
void* p307 = last_address;
PRINT_POINTER(scalloc(84,30););
printStats();
void* p308 = last_address;
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(srealloc(p177,155););
printStats();
void* p309 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(smalloc(219););
printStats();
void* p310 = last_address;
PRINT_POINTER(srealloc(p26,40););
printStats();
void* p311 = last_address;
DEBUG_PRINT(sfree(p276););
printStats();
PRINT_POINTER(srealloc(p248,16););
printStats();
void* p312 = last_address;
PRINT_POINTER(scalloc(106,206););
printStats();
void* p313 = last_address;
PRINT_POINTER(scalloc(82,154););
printStats();
void* p314 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p315 = last_address;
PRINT_POINTER(scalloc(200,189););
printStats();
void* p316 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p317 = last_address;
PRINT_POINTER(scalloc(136,34););
printStats();
void* p318 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p319 = last_address;
PRINT_POINTER(scalloc(207,55););
printStats();
void* p320 = last_address;
PRINT_POINTER(scalloc(69,31););
printStats();
void* p321 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p322 = last_address;
PRINT_POINTER(scalloc(48,223););
printStats();
void* p323 = last_address;
DEBUG_PRINT(sfree(p242););
printStats();
PRINT_POINTER(scalloc(233,145););
printStats();
void* p324 = last_address;
PRINT_POINTER(srealloc(p311,128););
printStats();
void* p325 = last_address;
PRINT_POINTER(srealloc(p249,138););
printStats();
void* p326 = last_address;
PRINT_POINTER(srealloc(p309,74););
printStats();
void* p327 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p328 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p329 = last_address;
PRINT_POINTER(scalloc(114,6););
printStats();
void* p330 = last_address;
PRINT_POINTER(srealloc(p291,52););
printStats();
void* p331 = last_address;
PRINT_POINTER(srealloc(p307,247););
printStats();
void* p332 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p333 = last_address;
PRINT_POINTER(scalloc(81,54););
printStats();
void* p334 = last_address;
DEBUG_PRINT(sfree(p240););
printStats();
PRINT_POINTER(srealloc(p215,76););
printStats();
void* p335 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p336 = last_address;
PRINT_POINTER(srealloc(p280,155););
printStats();
void* p337 = last_address;
PRINT_POINTER(scalloc(124,229););
printStats();
void* p338 = last_address;
PRINT_POINTER(scalloc(85,49););
printStats();
void* p339 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p340 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p341 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p342 = last_address;
DEBUG_PRINT(sfree(p153););
printStats();
PRINT_POINTER(srealloc(p194,53););
printStats();
void* p343 = last_address;
PRINT_POINTER(srealloc(p298,189););
printStats();
void* p344 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
PRINT_POINTER(smalloc(83););
printStats();
void* p345 = last_address;
PRINT_POINTER(srealloc(p253,185););
printStats();
void* p346 = last_address;
PRINT_POINTER(srealloc(p344,228););
printStats();
void* p347 = last_address;
DEBUG_PRINT(sfree(p317););
printStats();
DEBUG_PRINT(sfree(p241););
printStats();
PRINT_POINTER(smalloc(60););
printStats();
void* p348 = last_address;
PRINT_POINTER(scalloc(116,124););
printStats();
void* p349 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
DEBUG_PRINT(sfree(p204););
printStats();
PRINT_POINTER(scalloc(53,57););
printStats();
void* p350 = last_address;
PRINT_POINTER(srealloc(p257,152););
printStats();
void* p351 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p352 = last_address;
PRINT_POINTER(scalloc(217,220););
printStats();
void* p353 = last_address;
DEBUG_PRINT(sfree(p171););
printStats();
PRINT_POINTER(scalloc(146,159););
printStats();
void* p354 = last_address;
DEBUG_PRINT(sfree(p261););
printStats();
PRINT_POINTER(srealloc(p330,37););
printStats();
void* p355 = last_address;
DEBUG_PRINT(sfree(p188););
printStats();
DEBUG_PRINT(sfree(p264););
printStats();
DEBUG_PRINT(sfree(p268););
printStats();
DEBUG_PRINT(sfree(p314););
printStats();
PRINT_POINTER(smalloc(231););
printStats();
void* p356 = last_address;
DEBUG_PRINT(sfree(p348););
printStats();
PRINT_POINTER(smalloc(175););
printStats();
void* p357 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p358 = last_address;
DEBUG_PRINT(sfree(p214););
printStats();
PRINT_POINTER(smalloc(228););
printStats();
void* p359 = last_address;
DEBUG_PRINT(sfree(p284););
printStats();
DEBUG_PRINT(sfree(p350););
printStats();
PRINT_POINTER(srealloc(p104,227););
printStats();
void* p360 = last_address;
PRINT_POINTER(srealloc(p331,150););
printStats();
void* p361 = last_address;
PRINT_POINTER(scalloc(87,3););
printStats();
void* p362 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p363 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p364 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p365 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p366 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p367 = last_address;
DEBUG_PRINT(sfree(p84););
printStats();
DEBUG_PRINT(sfree(p151););
printStats();
PRINT_POINTER(srealloc(p271,63););
printStats();
void* p368 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p369 = last_address;
PRINT_POINTER(scalloc(234,39););
printStats();
void* p370 = last_address;
PRINT_POINTER(scalloc(64,245););
printStats();
void* p371 = last_address;
DEBUG_PRINT(sfree(p353););
printStats();
PRINT_POINTER(srealloc(p210,230););
printStats();
void* p372 = last_address;
PRINT_POINTER(srealloc(p297,126););
printStats();
void* p373 = last_address;
DEBUG_PRINT(sfree(p364););
printStats();
PRINT_POINTER(smalloc(25););
printStats();
void* p374 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p375 = last_address;
DEBUG_PRINT(sfree(p370););
printStats();
DEBUG_PRINT(sfree(p342););
printStats();
PRINT_POINTER(scalloc(249,227););
printStats();
void* p376 = last_address;
PRINT_POINTER(srealloc(p369,70););
printStats();
void* p377 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p378 = last_address;
PRINT_POINTER(srealloc(p189,222););
printStats();
void* p379 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p380 = last_address;
PRINT_POINTER(scalloc(189,83););
printStats();
void* p381 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p382 = last_address;
PRINT_POINTER(srealloc(p361,62););
printStats();
void* p383 = last_address;
PRINT_POINTER(srealloc(p246,130););
printStats();
void* p384 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
PRINT_POINTER(srealloc(p256,45););
printStats();
void* p385 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p386 = last_address;
PRINT_POINTER(scalloc(36,84););
printStats();
void* p387 = last_address;
DEBUG_PRINT(sfree(p227););
printStats();
PRINT_POINTER(smalloc(38););
printStats();
void* p388 = last_address;
DEBUG_PRINT(sfree(p237););
printStats();
DEBUG_PRINT(sfree(p258););
printStats();
PRINT_POINTER(smalloc(104););
printStats();
void* p389 = last_address;
PRINT_POINTER(srealloc(p363,243););
printStats();
void* p390 = last_address;
DEBUG_PRINT(sfree(p259););
printStats();
PRINT_POINTER(srealloc(p303,25););
printStats();
void* p391 = last_address;
PRINT_POINTER(scalloc(226,142););
printStats();
void* p392 = last_address;
DEBUG_PRINT(sfree(p324););
printStats();
PRINT_POINTER(scalloc(196,201););
printStats();
void* p393 = last_address;
DEBUG_PRINT(sfree(p374););
printStats();
PRINT_POINTER(scalloc(84,191););
printStats();
void* p394 = last_address;
PRINT_POINTER(scalloc(233,155););
printStats();
void* p395 = last_address;
PRINT_POINTER(scalloc(124,65););
printStats();
void* p396 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p397 = last_address;
PRINT_POINTER(scalloc(221,226););
printStats();
void* p398 = last_address;
PRINT_POINTER(scalloc(233,225););
printStats();
void* p399 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p400 = last_address;
PRINT_POINTER(srealloc(p80,110););
printStats();
void* p401 = last_address;
PRINT_POINTER(srealloc(p245,20););
printStats();
void* p402 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p403 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p404 = last_address;
PRINT_POINTER(srealloc(p273,29););
printStats();
void* p405 = last_address;
PRINT_POINTER(srealloc(p178,238););
printStats();
void* p406 = last_address;
PRINT_POINTER(srealloc(p338,56););
printStats();
void* p407 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
PRINT_POINTER(scalloc(211,119););
printStats();
void* p408 = last_address;
PRINT_POINTER(scalloc(92,39););
printStats();
void* p409 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p410 = last_address;
PRINT_POINTER(scalloc(178,121););
printStats();
void* p411 = last_address;
PRINT_POINTER(srealloc(p339,18););
printStats();
void* p412 = last_address;
DEBUG_PRINT(sfree(p404););
printStats();
PRINT_POINTER(srealloc(p299,76););
printStats();
void* p413 = last_address;
PRINT_POINTER(srealloc(p388,80););
printStats();
void* p414 = last_address;
DEBUG_PRINT(sfree(p326););
printStats();
PRINT_POINTER(srealloc(p336,182););
printStats();
void* p415 = last_address;
DEBUG_PRINT(sfree(p407););
printStats();
DEBUG_PRINT(sfree(p243););
printStats();
PRINT_POINTER(srealloc(p196,205););
printStats();
void* p416 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p417 = last_address;
DEBUG_PRINT(sfree(p212););
printStats();
DEBUG_PRINT(sfree(p403););
printStats();
PRINT_POINTER(smalloc(25););
printStats();
void* p418 = last_address;
PRINT_POINTER(srealloc(p399,49););
printStats();
void* p419 = last_address;
PRINT_POINTER(srealloc(p306,113););
printStats();
void* p420 = last_address;
PRINT_POINTER(scalloc(0,17););
printStats();
void* p421 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p422 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p423 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p424 = last_address;
DEBUG_PRINT(sfree(p385););
printStats();
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(scalloc(178,156););
printStats();
void* p425 = last_address;
PRINT_POINTER(scalloc(202,133););
printStats();
void* p426 = last_address;
DEBUG_PRINT(sfree(p394););
printStats();
PRINT_POINTER(srealloc(p424,113););
printStats();
void* p427 = last_address;
PRINT_POINTER(srealloc(p285,118););
printStats();
void* p428 = last_address;
DEBUG_PRINT(sfree(p356););
printStats();
DEBUG_PRINT(sfree(p283););
printStats();
PRINT_POINTER(smalloc(32););
printStats();
void* p429 = last_address;
PRINT_POINTER(scalloc(127,237););
printStats();
void* p430 = last_address;
PRINT_POINTER(srealloc(p162,188););
printStats();
void* p431 = last_address;
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(smalloc(53););
printStats();
void* p432 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p433 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p434 = last_address;
DEBUG_PRINT(sfree(p292););
printStats();
PRINT_POINTER(smalloc(115););
printStats();
void* p435 = last_address;
PRINT_POINTER(scalloc(32,168););
printStats();
void* p436 = last_address;
PRINT_POINTER(srealloc(p346,3););
printStats();
void* p437 = last_address;
PRINT_POINTER(srealloc(p368,134););
printStats();
void* p438 = last_address;
PRINT_POINTER(srealloc(p389,119););
printStats();
void* p439 = last_address;
DEBUG_PRINT(sfree(p332););
printStats();
DEBUG_PRINT(sfree(p360););
printStats();
PRINT_POINTER(smalloc(185););
printStats();
void* p440 = last_address;
DEBUG_PRINT(sfree(p430););
printStats();
PRINT_POINTER(scalloc(14,147););
printStats();
void* p441 = last_address;
PRINT_POINTER(scalloc(181,118););
printStats();
void* p442 = last_address;
DEBUG_PRINT(sfree(p132););
printStats();
PRINT_POINTER(scalloc(221,126););
printStats();
void* p443 = last_address;
PRINT_POINTER(scalloc(151,131););
printStats();
void* p444 = last_address;
DEBUG_PRINT(sfree(p427););
printStats();
PRINT_POINTER(scalloc(163,234););
printStats();
void* p445 = last_address;
DEBUG_PRINT(sfree(p157););
printStats();
PRINT_POINTER(scalloc(53,48););
printStats();
void* p446 = last_address;
PRINT_POINTER(srealloc(p371,61););
printStats();
void* p447 = last_address;
PRINT_POINTER(srealloc(p376,138););
printStats();
void* p448 = last_address;
PRINT_POINTER(scalloc(56,155););
printStats();
void* p449 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p450 = last_address;
PRINT_POINTER(scalloc(134,47););
printStats();
void* p451 = last_address;
DEBUG_PRINT(sfree(p180););
printStats();
PRINT_POINTER(smalloc(141););
printStats();
void* p452 = last_address;
PRINT_POINTER(scalloc(163,60););
printStats();
void* p453 = last_address;
PRINT_POINTER(scalloc(218,110););
printStats();
void* p454 = last_address;
PRINT_POINTER(srealloc(p428,41););
printStats();
void* p455 = last_address;
PRINT_POINTER(scalloc(201,207););
printStats();
void* p456 = last_address;
DEBUG_PRINT(sfree(p440););
printStats();
DEBUG_PRINT(sfree(p305););
printStats();
DEBUG_PRINT(sfree(p179););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p457 = last_address;
PRINT_POINTER(scalloc(199,134););
printStats();
void* p458 = last_address;
PRINT_POINTER(scalloc(186,125););
printStats();
void* p459 = last_address;
PRINT_POINTER(scalloc(164,90););
printStats();
void* p460 = last_address;
PRINT_POINTER(scalloc(189,209););
printStats();
void* p461 = last_address;
DEBUG_PRINT(sfree(p345););
printStats();
PRINT_POINTER(smalloc(140););
printStats();
void* p462 = last_address;
DEBUG_PRINT(sfree(p238););
printStats();
DEBUG_PRINT(sfree(p422););
printStats();
DEBUG_PRINT(sfree(p419););
printStats();
PRINT_POINTER(scalloc(211,105););
printStats();
void* p463 = last_address;
DEBUG_PRINT(sfree(p260););
printStats();
PRINT_POINTER(smalloc(122););
printStats();
void* p464 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p465 = last_address;
DEBUG_PRINT(sfree(p442););
printStats();
PRINT_POINTER(srealloc(p217,126););
printStats();
void* p466 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p467 = last_address;
PRINT_POINTER(srealloc(p310,8););
printStats();
void* p468 = last_address;
DEBUG_PRINT(sfree(p351););
printStats();
DEBUG_PRINT(sfree(p415););
printStats();
DEBUG_PRINT(sfree(p465););
printStats();
PRINT_POINTER(scalloc(193,70););
printStats();
void* p469 = last_address;
PRINT_POINTER(scalloc(173,84););
printStats();
void* p470 = last_address;
PRINT_POINTER(scalloc(98,154););
printStats();
void* p471 = last_address;
PRINT_POINTER(scalloc(173,214););
printStats();
void* p472 = last_address;
DEBUG_PRINT(sfree(p270););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p473 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p474 = last_address;
DEBUG_PRINT(sfree(p469););
printStats();
PRINT_POINTER(smalloc(86););
printStats();
void* p475 = last_address;
PRINT_POINTER(srealloc(p335,246););
printStats();
void* p476 = last_address;
PRINT_POINTER(srealloc(p318,192););
printStats();
void* p477 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p478 = last_address;
PRINT_POINTER(scalloc(25,113););
printStats();
void* p479 = last_address;
DEBUG_PRINT(sfree(p455););
printStats();
PRINT_POINTER(scalloc(52,173););
printStats();
void* p480 = last_address;
PRINT_POINTER(srealloc(p349,111););
printStats();
void* p481 = last_address;
PRINT_POINTER(scalloc(136,24););
printStats();
void* p482 = last_address;
PRINT_POINTER(scalloc(27,169););
printStats();
void* p483 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p484 = last_address;
PRINT_POINTER(srealloc(p281,228););
printStats();
void* p485 = last_address;
DEBUG_PRINT(sfree(p485););
printStats();
DEBUG_PRINT(sfree(p92););
printStats();
PRINT_POINTER(smalloc(209););
printStats();
void* p486 = last_address;
PRINT_POINTER(scalloc(27,237););
printStats();
void* p487 = last_address;
PRINT_POINTER(srealloc(p287,80););
printStats();
void* p488 = last_address;
DEBUG_PRINT(sfree(p396););
printStats();
PRINT_POINTER(scalloc(34,95););
printStats();
void* p489 = last_address;
DEBUG_PRINT(sfree(p481););
printStats();
PRINT_POINTER(srealloc(p325,121););
printStats();
void* p490 = last_address;
PRINT_POINTER(srealloc(p459,199););
printStats();
void* p491 = last_address;
PRINT_POINTER(srealloc(p125,219););
printStats();
void* p492 = last_address;
DEBUG_PRINT(sfree(p288););
printStats();
DEBUG_PRINT(sfree(p337););
printStats();
PRINT_POINTER(smalloc(144););
printStats();
void* p493 = last_address;
PRINT_POINTER(scalloc(113,246););
printStats();
void* p494 = last_address;
DEBUG_PRINT(sfree(p295););
printStats();
PRINT_POINTER(scalloc(58,120););
printStats();
void* p495 = last_address;
PRINT_POINTER(srealloc(p450,5););
printStats();
void* p496 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p497 = last_address;
DEBUG_PRINT(sfree(p434););
printStats();
PRINT_POINTER(srealloc(p439,18););
printStats();
void* p498 = last_address;
DEBUG_PRINT(sfree(p445););
printStats();
PRINT_POINTER(srealloc(p301,119););
printStats();
void* p499 = last_address;
DEBUG_PRINT(sfree(p262););
printStats();
PRINT_POINTER(srealloc(p461,146););
printStats();
void* p500 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p501 = last_address;
PRINT_POINTER(srealloc(p477,76););
printStats();
void* p502 = last_address;
PRINT_POINTER(scalloc(68,236););
printStats();
void* p503 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p504 = last_address;
PRINT_POINTER(scalloc(146,72););
printStats();
void* p505 = last_address;
DEBUG_PRINT(sfree(p501););
printStats();
PRINT_POINTER(srealloc(p470,144););
printStats();
void* p506 = last_address;
PRINT_POINTER(scalloc(47,42););
printStats();
void* p507 = last_address;
PRINT_POINTER(scalloc(136,215););
printStats();
void* p508 = last_address;
PRINT_POINTER(srealloc(p290,13););
printStats();
void* p509 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p510 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p511 = last_address;
PRINT_POINTER(srealloc(p402,162););
printStats();
void* p512 = last_address;
PRINT_POINTER(scalloc(208,16););
printStats();
void* p513 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p514 = last_address;
DEBUG_PRINT(sfree(p406););
printStats();
DEBUG_PRINT(sfree(p347););
printStats();
PRINT_POINTER(smalloc(149););
printStats();
void* p515 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p516 = last_address;
PRINT_POINTER(srealloc(p321,185););
printStats();
void* p517 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p518 = last_address;
PRINT_POINTER(scalloc(155,103););
printStats();
void* p519 = last_address;
DEBUG_PRINT(sfree(p213););
printStats();
DEBUG_PRINT(sfree(p278););
printStats();
PRINT_POINTER(smalloc(69););
printStats();
void* p520 = last_address;
PRINT_POINTER(scalloc(242,35););
printStats();
void* p521 = last_address;
DEBUG_PRINT(sfree(p480););
printStats();
PRINT_POINTER(smalloc(160););
printStats();
void* p522 = last_address;
PRINT_POINTER(srealloc(p221,167););
printStats();
void* p523 = last_address;
PRINT_POINTER(srealloc(p446,125););
printStats();
void* p524 = last_address;
PRINT_POINTER(srealloc(p373,245););
printStats();
void* p525 = last_address;
PRINT_POINTER(scalloc(65,117););
printStats();
void* p526 = last_address;
DEBUG_PRINT(sfree(p381););
printStats();
PRINT_POINTER(srealloc(p286,216););
printStats();
void* p527 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p528 = last_address;
DEBUG_PRINT(sfree(p289););
printStats();
PRINT_POINTER(scalloc(175,52););
printStats();
void* p529 = last_address;
DEBUG_PRINT(sfree(p507););
printStats();
PRINT_POINTER(srealloc(p320,197););
printStats();
void* p530 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p531 = last_address;
DEBUG_PRINT(sfree(p233););
printStats();
DEBUG_PRINT(sfree(p529););
printStats();
PRINT_POINTER(smalloc(18););
printStats();
void* p532 = last_address;
PRINT_POINTER(scalloc(244,192););
printStats();
void* p533 = last_address;
DEBUG_PRINT(sfree(p28););
printStats();
DEBUG_PRINT(sfree(p491););
printStats();
PRINT_POINTER(srealloc(p482,54););
printStats();
void* p534 = last_address;
DEBUG_PRINT(sfree(p432););
printStats();
PRINT_POINTER(srealloc(p316,218););
printStats();
void* p535 = last_address;
PRINT_POINTER(scalloc(21,101););
printStats();
void* p536 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p537 = last_address;
PRINT_POINTER(scalloc(192,194););
printStats();
void* p538 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
PRINT_POINTER(srealloc(p484,1););
printStats();
void* p539 = last_address;
PRINT_POINTER(scalloc(80,249););
printStats();
void* p540 = last_address;
PRINT_POINTER(scalloc(123,41););
printStats();
void* p541 = last_address;
PRINT_POINTER(scalloc(6,157););
printStats();
void* p542 = last_address;
DEBUG_PRINT(sfree(p300););
printStats();
PRINT_POINTER(srealloc(p523,154););
printStats();
void* p543 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p544 = last_address;
PRINT_POINTER(srealloc(p478,14););
printStats();
void* p545 = last_address;
DEBUG_PRINT(sfree(p401););
printStats();
PRINT_POINTER(scalloc(16,102););
printStats();
void* p546 = last_address;
DEBUG_PRINT(sfree(p495););
printStats();
PRINT_POINTER(srealloc(p473,50););
printStats();
void* p547 = last_address;
DEBUG_PRINT(sfree(p460););
printStats();
PRINT_POINTER(scalloc(28,197););
printStats();
void* p548 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p549 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p550 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p551 = last_address;
DEBUG_PRINT(sfree(p519););
printStats();
DEBUG_PRINT(sfree(p230););
printStats();
PRINT_POINTER(smalloc(155););
printStats();
void* p552 = last_address;
PRINT_POINTER(srealloc(p518,153););
printStats();
void* p553 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p554 = last_address;
PRINT_POINTER(srealloc(p441,195););
printStats();
void* p555 = last_address;
PRINT_POINTER(srealloc(p186,64););
printStats();
void* p556 = last_address;
PRINT_POINTER(srealloc(p476,184););
printStats();
void* p557 = last_address;
PRINT_POINTER(srealloc(p496,206););
printStats();
void* p558 = last_address;
DEBUG_PRINT(sfree(p354););
printStats();
DEBUG_PRINT(sfree(p411););
printStats();
PRINT_POINTER(smalloc(122););
printStats();
void* p559 = last_address;
PRINT_POINTER(srealloc(p408,84););
printStats();
void* p560 = last_address;
PRINT_POINTER(srealloc(p421,23););
printStats();
void* p561 = last_address;
PRINT_POINTER(srealloc(p467,232););
printStats();
void* p562 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p563 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p564 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p565 = last_address;
PRINT_POINTER(srealloc(p127,203););
printStats();
void* p566 = last_address;
PRINT_POINTER(scalloc(60,13););
printStats();
void* p567 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p568 = last_address;
PRINT_POINTER(srealloc(p379,4););
printStats();
void* p569 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p570 = last_address;
DEBUG_PRINT(sfree(p535););
printStats();
PRINT_POINTER(scalloc(40,103););
printStats();
void* p571 = last_address;
PRINT_POINTER(scalloc(223,166););
printStats();
void* p572 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(smalloc(171););
printStats();
void* p573 = last_address;
DEBUG_PRINT(sfree(p420););
printStats();
PRINT_POINTER(scalloc(88,126););
printStats();
void* p574 = last_address;
PRINT_POINTER(srealloc(p527,160););
printStats();
void* p575 = last_address;
PRINT_POINTER(srealloc(p266,72););
printStats();
void* p576 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p577 = last_address;
DEBUG_PRINT(sfree(p417););
printStats();
PRINT_POINTER(srealloc(p540,153););
printStats();
void* p578 = last_address;
PRINT_POINTER(scalloc(117,236););
printStats();
void* p579 = last_address;
PRINT_POINTER(srealloc(p494,26););
printStats();
void* p580 = last_address;
DEBUG_PRINT(sfree(p580););
printStats();
DEBUG_PRINT(sfree(p412););
printStats();
PRINT_POINTER(smalloc(106););
printStats();
void* p581 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(srealloc(p500,74););
printStats();
void* p582 = last_address;
PRINT_POINTER(srealloc(p552,69););
printStats();
void* p583 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p584 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p585 = last_address;
PRINT_POINTER(scalloc(205,133););
printStats();
void* p586 = last_address;
PRINT_POINTER(scalloc(8,134););
printStats();
void* p587 = last_address;
DEBUG_PRINT(sfree(p391););
printStats();
DEBUG_PRINT(sfree(p340););
printStats();
PRINT_POINTER(srealloc(p492,185););
printStats();
void* p588 = last_address;
PRINT_POINTER(scalloc(203,55););
printStats();
void* p589 = last_address;
PRINT_POINTER(scalloc(126,174););
printStats();
void* p590 = last_address;
PRINT_POINTER(scalloc(114,77););
printStats();
void* p591 = last_address;
PRINT_POINTER(scalloc(68,74););
printStats();
void* p592 = last_address;
PRINT_POINTER(scalloc(144,208););
printStats();
void* p593 = last_address;
PRINT_POINTER(srealloc(p471,99););
printStats();
void* p594 = last_address;
PRINT_POINTER(scalloc(57,108););
printStats();
void* p595 = last_address;
PRINT_POINTER(scalloc(204,142););
printStats();
void* p596 = last_address;
PRINT_POINTER(srealloc(p589,68););
printStats();
void* p597 = last_address;
PRINT_POINTER(srealloc(p558,143););
printStats();
void* p598 = last_address;
PRINT_POINTER(srealloc(p375,32););
printStats();
void* p599 = last_address;
DEBUG_PRINT(sfree(p586););
printStats();
DEBUG_PRINT(sfree(p510););
printStats();
DEBUG_PRINT(sfree(p532););
printStats();
PRINT_POINTER(smalloc(220););
printStats();
void* p600 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p601 = last_address;
PRINT_POINTER(scalloc(65,248););
printStats();
void* p602 = last_address;
PRINT_POINTER(srealloc(p594,20););
printStats();
void* p603 = last_address;
PRINT_POINTER(srealloc(p380,214););
printStats();
void* p604 = last_address;
PRINT_POINTER(scalloc(94,76););
printStats();
void* p605 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p606 = last_address;
PRINT_POINTER(srealloc(p565,135););
printStats();
void* p607 = last_address;
PRINT_POINTER(scalloc(213,158););
printStats();
void* p608 = last_address;
PRINT_POINTER(srealloc(p583,244););
printStats();
void* p609 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p610 = last_address;
PRINT_POINTER(srealloc(p174,12););
printStats();
void* p611 = last_address;
PRINT_POINTER(srealloc(p533,77););
printStats();
void* p612 = last_address;
PRINT_POINTER(scalloc(95,80););
printStats();
void* p613 = last_address;
PRINT_POINTER(scalloc(77,155););
printStats();
void* p614 = last_address;
PRINT_POINTER(scalloc(78,105););
printStats();
void* p615 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p616 = last_address;
PRINT_POINTER(srealloc(p156,187););
printStats();
void* p617 = last_address;
PRINT_POINTER(srealloc(p590,198););
printStats();
void* p618 = last_address;
DEBUG_PRINT(sfree(p115););
printStats();
PRINT_POINTER(smalloc(177););
printStats();
void* p619 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p620 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p621 = last_address;
PRINT_POINTER(scalloc(207,245););
printStats();
void* p622 = last_address;
PRINT_POINTER(scalloc(9,156););
printStats();
void* p623 = last_address;
PRINT_POINTER(srealloc(p312,240););
printStats();
void* p624 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p625 = last_address;
PRINT_POINTER(srealloc(p517,85););
printStats();
void* p626 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p627 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p628 = last_address;
PRINT_POINTER(scalloc(117,63););
printStats();
void* p629 = last_address;
DEBUG_PRINT(sfree(p449););
printStats();
DEBUG_PRINT(sfree(p568););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p630 = last_address;
PRINT_POINTER(srealloc(p493,150););
printStats();
void* p631 = last_address;
PRINT_POINTER(scalloc(240,19););
printStats();
void* p632 = last_address;
DEBUG_PRINT(sfree(p163););
printStats();
DEBUG_PRINT(sfree(p456););
printStats();
DEBUG_PRINT(sfree(p436););
printStats();
PRINT_POINTER(srealloc(p546,116););
printStats();
void* p633 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p634 = last_address;
PRINT_POINTER(srealloc(p279,48););
printStats();
void* p635 = last_address;
PRINT_POINTER(srealloc(p588,10););
printStats();
void* p636 = last_address;
PRINT_POINTER(srealloc(p528,234););
printStats();
void* p637 = last_address;
DEBUG_PRINT(sfree(p383););
printStats();
PRINT_POINTER(scalloc(103,2););
printStats();
void* p638 = last_address;
PRINT_POINTER(srealloc(p587,138););
printStats();
void* p639 = last_address;
DEBUG_PRINT(sfree(p551););
printStats();
PRINT_POINTER(scalloc(178,239););
printStats();
void* p640 = last_address;
PRINT_POINTER(srealloc(p571,79););
printStats();
void* p641 = last_address;
PRINT_POINTER(scalloc(175,30););
printStats();
void* p642 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p643 = last_address;
DEBUG_PRINT(sfree(p595););
printStats();
DEBUG_PRINT(sfree(p562););
printStats();
PRINT_POINTER(scalloc(153,13););
printStats();
void* p644 = last_address;
PRINT_POINTER(scalloc(224,117););
printStats();
void* p645 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p646 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p647 = last_address;
PRINT_POINTER(srealloc(p566,94););
printStats();
void* p648 = last_address;
PRINT_POINTER(scalloc(104,147););
printStats();
void* p649 = last_address;
DEBUG_PRINT(sfree(p591););
printStats();
DEBUG_PRINT(sfree(p570););
printStats();
PRINT_POINTER(smalloc(180););
printStats();
void* p650 = last_address;
PRINT_POINTER(scalloc(117,80););
printStats();
void* p651 = last_address;
PRINT_POINTER(scalloc(85,118););
printStats();
void* p652 = last_address;
PRINT_POINTER(srealloc(p648,239););
printStats();
void* p653 = last_address;
PRINT_POINTER(scalloc(110,180););
printStats();
void* p654 = last_address;
PRINT_POINTER(srealloc(p643,184););
printStats();
void* p655 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p656 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p657 = last_address;
DEBUG_PRINT(sfree(p639););
printStats();
PRINT_POINTER(scalloc(30,155););
printStats();
void* p658 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p659 = last_address;
PRINT_POINTER(srealloc(p488,246););
printStats();
void* p660 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p661 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p662 = last_address;
PRINT_POINTER(srealloc(p293,145););
printStats();
void* p663 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p664 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p665 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p666 = last_address;
PRINT_POINTER(scalloc(29,63););
printStats();
void* p667 = last_address;
PRINT_POINTER(srealloc(p585,115););
printStats();
void* p668 = last_address;
DEBUG_PRINT(sfree(p629););
printStats();
PRINT_POINTER(srealloc(p553,86););
printStats();
void* p669 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p670 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p671 = last_address;
PRINT_POINTER(srealloc(p448,14););
printStats();
void* p672 = last_address;
DEBUG_PRINT(sfree(p236););
printStats();
DEBUG_PRINT(sfree(p649););
printStats();
PRINT_POINTER(srealloc(p390,8););
printStats();
void* p673 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p674 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p675 = last_address;
PRINT_POINTER(srealloc(p211,207););
printStats();
void* p676 = last_address;
DEBUG_PRINT(sfree(p647););
printStats();
PRINT_POINTER(smalloc(1););
printStats();
void* p677 = last_address;
PRINT_POINTER(scalloc(92,143););
printStats();
void* p678 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p679 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p680 = last_address;
PRINT_POINTER(scalloc(210,167););
printStats();
void* p681 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(smalloc(102););
printStats();
void* p682 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p683 = last_address;
DEBUG_PRINT(sfree(p263););
printStats();
PRINT_POINTER(smalloc(111););
printStats();
void* p684 = last_address;
PRINT_POINTER(srealloc(p52,156););
printStats();
void* p685 = last_address;
PRINT_POINTER(srealloc(p582,174););
printStats();
void* p686 = last_address;
DEBUG_PRINT(sfree(p398););
printStats();
PRINT_POINTER(srealloc(p537,51););
printStats();
void* p687 = last_address;
DEBUG_PRINT(sfree(p302););
printStats();
PRINT_POINTER(scalloc(83,249););
printStats();
void* p688 = last_address;
PRINT_POINTER(scalloc(131,118););
printStats();
void* p689 = last_address;
DEBUG_PRINT(sfree(p569););
printStats();
PRINT_POINTER(smalloc(103););
printStats();
void* p690 = last_address;
PRINT_POINTER(scalloc(89,200););
printStats();
void* p691 = last_address;
DEBUG_PRINT(sfree(p575););
printStats();
PRINT_POINTER(scalloc(248,17););
printStats();
void* p692 = last_address;
PRINT_POINTER(srealloc(p652,140););
printStats();
void* p693 = last_address;
PRINT_POINTER(scalloc(91,185););
printStats();
void* p694 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p695 = last_address;
DEBUG_PRINT(sfree(p437););
printStats();
PRINT_POINTER(smalloc(206););
printStats();
void* p696 = last_address;
PRINT_POINTER(scalloc(115,220););
printStats();
void* p697 = last_address;
DEBUG_PRINT(sfree(p672););
printStats();
PRINT_POINTER(smalloc(35););
printStats();
void* p698 = last_address;
PRINT_POINTER(srealloc(p397,154););
printStats();
void* p699 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p700 = last_address;
PRINT_POINTER(scalloc(147,65););
printStats();
void* p701 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p702 = last_address;
DEBUG_PRINT(sfree(p395););
printStats();
DEBUG_PRINT(sfree(p561););
printStats();
PRINT_POINTER(scalloc(122,17););
printStats();
void* p703 = last_address;
PRINT_POINTER(srealloc(p691,242););
printStats();
void* p704 = last_address;
PRINT_POINTER(scalloc(117,232););
printStats();
void* p705 = last_address;
PRINT_POINTER(srealloc(p564,134););
printStats();
void* p706 = last_address;
PRINT_POINTER(scalloc(21,225););
printStats();
void* p707 = last_address;
PRINT_POINTER(scalloc(226,4););
printStats();
void* p708 = last_address;
PRINT_POINTER(srealloc(p392,101););
printStats();
void* p709 = last_address;
DEBUG_PRINT(sfree(p277););
printStats();
PRINT_POINTER(srealloc(p627,226););
printStats();
void* p710 = last_address;
DEBUG_PRINT(sfree(p541););
printStats();
DEBUG_PRINT(sfree(p641););
printStats();
PRINT_POINTER(smalloc(17););
printStats();
void* p711 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p712 = last_address;
DEBUG_PRINT(sfree(p706););
printStats();
DEBUG_PRINT(sfree(p474););
printStats();
DEBUG_PRINT(sfree(p304););
printStats();
DEBUG_PRINT(sfree(p315););
printStats();
PRINT_POINTER(scalloc(14,158););
printStats();
void* p713 = last_address;
PRINT_POINTER(scalloc(44,125););
printStats();
void* p714 = last_address;
PRINT_POINTER(scalloc(182,234););
printStats();
void* p715 = last_address;
DEBUG_PRINT(sfree(p630););
printStats();
PRINT_POINTER(srealloc(p343,153););
printStats();
void* p716 = last_address;
PRINT_POINTER(scalloc(106,209););
printStats();
void* p717 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p718 = last_address;
DEBUG_PRINT(sfree(p620););
printStats();
PRINT_POINTER(smalloc(107););
printStats();
void* p719 = last_address;
PRINT_POINTER(scalloc(92,9););
printStats();
void* p720 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p721 = last_address;
PRINT_POINTER(srealloc(p592,17););
printStats();
void* p722 = last_address;
PRINT_POINTER(scalloc(81,72););
printStats();
void* p723 = last_address;
PRINT_POINTER(srealloc(p200,2););
printStats();
void* p724 = last_address;
PRINT_POINTER(scalloc(181,68););
printStats();
void* p725 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p726 = last_address;
DEBUG_PRINT(sfree(p505););
printStats();
PRINT_POINTER(scalloc(125,30););
printStats();
void* p727 = last_address;
PRINT_POINTER(scalloc(145,97););
printStats();
void* p728 = last_address;
PRINT_POINTER(srealloc(p702,228););
printStats();
void* p729 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p730 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p731 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p732 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p733 = last_address;
PRINT_POINTER(scalloc(16,94););
printStats();
void* p734 = last_address;
PRINT_POINTER(srealloc(p454,85););
printStats();
void* p735 = last_address;
DEBUG_PRINT(sfree(p269););
printStats();
PRINT_POINTER(scalloc(103,108););
printStats();
void* p736 = last_address;
PRINT_POINTER(scalloc(229,161););
printStats();
void* p737 = last_address;
PRINT_POINTER(srealloc(p509,15););
printStats();
void* p738 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p739 = last_address;
DEBUG_PRINT(sfree(p724););
printStats();
PRINT_POINTER(scalloc(68,13););
printStats();
void* p740 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p741 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p742 = last_address;
PRINT_POINTER(scalloc(103,214););
printStats();
void* p743 = last_address;
PRINT_POINTER(scalloc(146,244););
printStats();
void* p744 = last_address;
PRINT_POINTER(srealloc(p146,109););
printStats();
void* p745 = last_address;
PRINT_POINTER(srealloc(p308,39););
printStats();
void* p746 = last_address;
PRINT_POINTER(scalloc(45,58););
printStats();
void* p747 = last_address;
DEBUG_PRINT(sfree(p254););
printStats();
PRINT_POINTER(srealloc(p746,118););
printStats();
void* p748 = last_address;
DEBUG_PRINT(sfree(p681););
printStats();
PRINT_POINTER(srealloc(p202,17););
printStats();
void* p749 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p750 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p751 = last_address;
PRINT_POINTER(scalloc(131,193););
printStats();
void* p752 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p753 = last_address;
PRINT_POINTER(srealloc(p734,139););
printStats();
void* p754 = last_address;
DEBUG_PRINT(sfree(p674););
printStats();
DEBUG_PRINT(sfree(p739););
printStats();
PRINT_POINTER(srealloc(p731,96););
printStats();
void* p755 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p756 = last_address;
PRINT_POINTER(srealloc(p682,28););
printStats();
void* p757 = last_address;
PRINT_POINTER(scalloc(246,146););
printStats();
void* p758 = last_address;
PRINT_POINTER(srealloc(p675,246););
printStats();
void* p759 = last_address;
PRINT_POINTER(srealloc(p713,205););
printStats();
void* p760 = last_address;
PRINT_POINTER(scalloc(89,156););
printStats();
void* p761 = last_address;
PRINT_POINTER(srealloc(p429,28););
printStats();
void* p762 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p763 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p764 = last_address;
PRINT_POINTER(scalloc(75,103););
printStats();
void* p765 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p766 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p767 = last_address;
PRINT_POINTER(scalloc(212,45););
printStats();
void* p768 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p769 = last_address;
PRINT_POINTER(srealloc(p633,242););
printStats();
void* p770 = last_address;
PRINT_POINTER(scalloc(84,234););
printStats();
void* p771 = last_address;
PRINT_POINTER(scalloc(100,8););
printStats();
void* p772 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p773 = last_address;
PRINT_POINTER(srealloc(p626,93););
printStats();
void* p774 = last_address;
PRINT_POINTER(scalloc(83,93););
printStats();
void* p775 = last_address;
DEBUG_PRINT(sfree(p453););
printStats();
PRINT_POINTER(srealloc(p673,101););
printStats();
void* p776 = last_address;
PRINT_POINTER(scalloc(202,221););
printStats();
void* p777 = last_address;
DEBUG_PRINT(sfree(p695););
printStats();
PRINT_POINTER(scalloc(51,179););
printStats();
void* p778 = last_address;
DEBUG_PRINT(sfree(p667););
printStats();
DEBUG_PRINT(sfree(p218););
printStats();
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(srealloc(p689,193););
printStats();
void* p779 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p780 = last_address;
PRINT_POINTER(srealloc(p438,107););
printStats();
void* p781 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p782 = last_address;
PRINT_POINTER(srealloc(p600,184););
printStats();
void* p783 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p784 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p785 = last_address;
PRINT_POINTER(scalloc(167,41););
printStats();
void* p786 = last_address;
PRINT_POINTER(scalloc(39,151););
printStats();
void* p787 = last_address;
PRINT_POINTER(scalloc(48,199););
printStats();
void* p788 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p789 = last_address;
}
