#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(184,234););
printStats();
void* p0 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p1 = last_address;
PRINT_POINTER(scalloc(77,144););
printStats();
void* p2 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p3 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(scalloc(91,233););
printStats();
void* p4 = last_address;
DEBUG_PRINT(sfree(p4););
printStats();
PRINT_POINTER(smalloc(64););
printStats();
void* p5 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
DEBUG_PRINT(sfree(p3););
printStats();
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(smalloc(165););
printStats();
void* p6 = last_address;
PRINT_POINTER(scalloc(225,169););
printStats();
void* p7 = last_address;
PRINT_POINTER(srealloc(p7,74););
printStats();
void* p8 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(srealloc(p6,189););
printStats();
void* p9 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p10 = last_address;
DEBUG_PRINT(sfree(p10););
printStats();
DEBUG_PRINT(sfree(p9););
printStats();
PRINT_POINTER(scalloc(59,137););
printStats();
void* p11 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
PRINT_POINTER(smalloc(207););
printStats();
void* p12 = last_address;
DEBUG_PRINT(sfree(p12););
printStats();
PRINT_POINTER(scalloc(65,237););
printStats();
void* p13 = last_address;
DEBUG_PRINT(sfree(p13););
printStats();
PRINT_POINTER(scalloc(223,169););
printStats();
void* p14 = last_address;
PRINT_POINTER(scalloc(38,48););
printStats();
void* p15 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p16 = last_address;
PRINT_POINTER(srealloc(p14,173););
printStats();
void* p17 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p18 = last_address;
PRINT_POINTER(scalloc(218,214););
printStats();
void* p19 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(smalloc(219););
printStats();
void* p20 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p21 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
DEBUG_PRINT(sfree(p17););
printStats();
DEBUG_PRINT(sfree(p19););
printStats();
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(srealloc(p20,201););
printStats();
void* p22 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p23 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p24 = last_address;
PRINT_POINTER(srealloc(p23,191););
printStats();
void* p25 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p24,34););
printStats();
void* p27 = last_address;
PRINT_POINTER(srealloc(p27,82););
printStats();
void* p28 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p29 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(scalloc(49,6););
printStats();
void* p30 = last_address;
PRINT_POINTER(srealloc(p28,231););
printStats();
void* p31 = last_address;
PRINT_POINTER(scalloc(214,164););
printStats();
void* p32 = last_address;
PRINT_POINTER(srealloc(p29,144););
printStats();
void* p33 = last_address;
PRINT_POINTER(scalloc(45,91););
printStats();
void* p34 = last_address;
PRINT_POINTER(srealloc(p34,106););
printStats();
void* p35 = last_address;
PRINT_POINTER(scalloc(65,173););
printStats();
void* p36 = last_address;
PRINT_POINTER(srealloc(p35,80););
printStats();
void* p37 = last_address;
DEBUG_PRINT(sfree(p26););
printStats();
PRINT_POINTER(scalloc(136,61););
printStats();
void* p38 = last_address;
PRINT_POINTER(srealloc(p31,47););
printStats();
void* p39 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p40,33););
printStats();
void* p41 = last_address;
PRINT_POINTER(scalloc(242,149););
printStats();
void* p42 = last_address;
PRINT_POINTER(scalloc(81,193););
printStats();
void* p43 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p44 = last_address;
PRINT_POINTER(srealloc(p33,190););
printStats();
void* p45 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p47 = last_address;
PRINT_POINTER(scalloc(200,106););
printStats();
void* p48 = last_address;
PRINT_POINTER(srealloc(p44,81););
printStats();
void* p49 = last_address;
PRINT_POINTER(srealloc(p46,152););
printStats();
void* p50 = last_address;
DEBUG_PRINT(sfree(p32););
printStats();
PRINT_POINTER(smalloc(97););
printStats();
void* p51 = last_address;
PRINT_POINTER(srealloc(p42,107););
printStats();
void* p52 = last_address;
PRINT_POINTER(srealloc(p47,113););
printStats();
void* p53 = last_address;
PRINT_POINTER(srealloc(p51,92););
printStats();
void* p54 = last_address;
DEBUG_PRINT(sfree(p48););
printStats();
PRINT_POINTER(smalloc(92););
printStats();
void* p55 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(srealloc(p54,119););
printStats();
void* p56 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p57 = last_address;
PRINT_POINTER(srealloc(p41,231););
printStats();
void* p58 = last_address;
PRINT_POINTER(srealloc(p49,164););
printStats();
void* p59 = last_address;
PRINT_POINTER(srealloc(p59,169););
printStats();
void* p60 = last_address;
PRINT_POINTER(srealloc(p57,244););
printStats();
void* p61 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p62 = last_address;
PRINT_POINTER(srealloc(p39,133););
printStats();
void* p63 = last_address;
DEBUG_PRINT(sfree(p58););
printStats();
DEBUG_PRINT(sfree(p53););
printStats();
DEBUG_PRINT(sfree(p63););
printStats();
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(srealloc(p38,91););
printStats();
void* p64 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p65 = last_address;
PRINT_POINTER(srealloc(p52,42););
printStats();
void* p66 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p67 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p68 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
DEBUG_PRINT(sfree(p66););
printStats();
PRINT_POINTER(srealloc(p30,164););
printStats();
void* p69 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p70 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p71 = last_address;
PRINT_POINTER(scalloc(55,11););
printStats();
void* p72 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p73 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p74 = last_address;
PRINT_POINTER(srealloc(p62,3););
printStats();
void* p75 = last_address;
PRINT_POINTER(srealloc(p73,88););
printStats();
void* p76 = last_address;
PRINT_POINTER(scalloc(215,121););
printStats();
void* p77 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
DEBUG_PRINT(sfree(p75););
printStats();
PRINT_POINTER(scalloc(96,195););
printStats();
void* p78 = last_address;
PRINT_POINTER(srealloc(p71,187););
printStats();
void* p79 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p80 = last_address;
PRINT_POINTER(srealloc(p65,215););
printStats();
void* p81 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p83 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(srealloc(p77,9););
printStats();
void* p84 = last_address;
PRINT_POINTER(srealloc(p56,216););
printStats();
void* p85 = last_address;
PRINT_POINTER(srealloc(p67,71););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p78,211););
printStats();
void* p87 = last_address;
PRINT_POINTER(srealloc(p82,165););
printStats();
void* p88 = last_address;
DEBUG_PRINT(sfree(p68););
printStats();
DEBUG_PRINT(sfree(p87););
printStats();
PRINT_POINTER(scalloc(108,105););
printStats();
void* p89 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p90 = last_address;
PRINT_POINTER(srealloc(p90,10););
printStats();
void* p91 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p92 = last_address;
PRINT_POINTER(scalloc(62,59););
printStats();
void* p93 = last_address;
DEBUG_PRINT(sfree(p74););
printStats();
PRINT_POINTER(scalloc(186,191););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p95 = last_address;
PRINT_POINTER(srealloc(p70,98););
printStats();
void* p96 = last_address;
PRINT_POINTER(scalloc(45,133););
printStats();
void* p97 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
PRINT_POINTER(srealloc(p72,81););
printStats();
void* p98 = last_address;
PRINT_POINTER(scalloc(52,26););
printStats();
void* p99 = last_address;
PRINT_POINTER(scalloc(178,60););
printStats();
void* p100 = last_address;
PRINT_POINTER(srealloc(p100,12););
printStats();
void* p101 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p102 = last_address;
PRINT_POINTER(scalloc(171,226););
printStats();
void* p103 = last_address;
PRINT_POINTER(scalloc(72,216););
printStats();
void* p104 = last_address;
PRINT_POINTER(scalloc(94,228););
printStats();
void* p105 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p106 = last_address;
DEBUG_PRINT(sfree(p88););
printStats();
PRINT_POINTER(smalloc(10););
printStats();
void* p107 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p108 = last_address;
PRINT_POINTER(srealloc(p98,229););
printStats();
void* p109 = last_address;
PRINT_POINTER(scalloc(237,52););
printStats();
void* p110 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p111 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p61,42););
printStats();
void* p113 = last_address;
DEBUG_PRINT(sfree(p79););
printStats();
DEBUG_PRINT(sfree(p104););
printStats();
DEBUG_PRINT(sfree(p103););
printStats();
PRINT_POINTER(scalloc(216,60););
printStats();
void* p114 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p115 = last_address;
PRINT_POINTER(scalloc(71,64););
printStats();
void* p116 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p117 = last_address;
PRINT_POINTER(srealloc(p86,167););
printStats();
void* p118 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p119 = last_address;
PRINT_POINTER(scalloc(94,72););
printStats();
void* p120 = last_address;
PRINT_POINTER(scalloc(103,118););
printStats();
void* p121 = last_address;
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p122 = last_address;
PRINT_POINTER(srealloc(p93,186););
printStats();
void* p123 = last_address;
PRINT_POINTER(scalloc(232,212););
printStats();
void* p124 = last_address;
PRINT_POINTER(srealloc(p92,83););
printStats();
void* p125 = last_address;
PRINT_POINTER(srealloc(p22,74););
printStats();
void* p126 = last_address;
PRINT_POINTER(srealloc(p84,27););
printStats();
void* p127 = last_address;
PRINT_POINTER(srealloc(p126,232););
printStats();
void* p128 = last_address;
PRINT_POINTER(srealloc(p106,66););
printStats();
void* p129 = last_address;
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(scalloc(94,186););
printStats();
void* p130 = last_address;
PRINT_POINTER(srealloc(p95,122););
printStats();
void* p131 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p132 = last_address;
PRINT_POINTER(srealloc(p80,195););
printStats();
void* p133 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p134 = last_address;
PRINT_POINTER(srealloc(p134,67););
printStats();
void* p135 = last_address;
PRINT_POINTER(srealloc(p133,1););
printStats();
void* p136 = last_address;
PRINT_POINTER(scalloc(145,171););
printStats();
void* p137 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p138 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p139 = last_address;
PRINT_POINTER(srealloc(p115,211););
printStats();
void* p140 = last_address;
PRINT_POINTER(srealloc(p125,15););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p111,68););
printStats();
void* p142 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
PRINT_POINTER(smalloc(115););
printStats();
void* p143 = last_address;
DEBUG_PRINT(sfree(p83););
printStats();
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(smalloc(195););
printStats();
void* p144 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p145 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p146 = last_address;
PRINT_POINTER(srealloc(p55,118););
printStats();
void* p147 = last_address;
PRINT_POINTER(scalloc(154,75););
printStats();
void* p148 = last_address;
DEBUG_PRINT(sfree(p107););
printStats();
DEBUG_PRINT(sfree(p122););
printStats();
DEBUG_PRINT(sfree(p137););
printStats();
PRINT_POINTER(srealloc(p142,227););
printStats();
void* p149 = last_address;
PRINT_POINTER(scalloc(179,84););
printStats();
void* p150 = last_address;
PRINT_POINTER(srealloc(p108,25););
printStats();
void* p151 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p152 = last_address;
PRINT_POINTER(srealloc(p105,59););
printStats();
void* p153 = last_address;
PRINT_POINTER(srealloc(p110,229););
printStats();
void* p154 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p155 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p156 = last_address;
PRINT_POINTER(srealloc(p101,167););
printStats();
void* p157 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p158 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p159 = last_address;
PRINT_POINTER(scalloc(158,63););
printStats();
void* p160 = last_address;
PRINT_POINTER(srealloc(p135,8););
printStats();
void* p161 = last_address;
PRINT_POINTER(scalloc(18,128););
printStats();
void* p162 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
DEBUG_PRINT(sfree(p143););
printStats();
DEBUG_PRINT(sfree(p156););
printStats();
PRINT_POINTER(srealloc(p145,241););
printStats();
void* p163 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p164 = last_address;
PRINT_POINTER(srealloc(p138,83););
printStats();
void* p165 = last_address;
DEBUG_PRINT(sfree(p136););
printStats();
PRINT_POINTER(srealloc(p97,37););
printStats();
void* p166 = last_address;
PRINT_POINTER(srealloc(p117,35););
printStats();
void* p167 = last_address;
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(scalloc(192,117););
printStats();
void* p168 = last_address;
DEBUG_PRINT(sfree(p151););
printStats();
DEBUG_PRINT(sfree(p112););
printStats();
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(srealloc(p89,241););
printStats();
void* p169 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p170 = last_address;
DEBUG_PRINT(sfree(p157););
printStats();
PRINT_POINTER(srealloc(p76,67););
printStats();
void* p171 = last_address;
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(scalloc(241,74););
printStats();
void* p172 = last_address;
PRINT_POINTER(scalloc(53,196););
printStats();
void* p173 = last_address;
DEBUG_PRINT(sfree(p121););
printStats();
PRINT_POINTER(scalloc(68,172););
printStats();
void* p174 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p175 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p176 = last_address;
PRINT_POINTER(scalloc(185,247););
printStats();
void* p177 = last_address;
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(srealloc(p81,193););
printStats();
void* p178 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p179 = last_address;
PRINT_POINTER(scalloc(40,91););
printStats();
void* p180 = last_address;
PRINT_POINTER(scalloc(10,51););
printStats();
void* p181 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
PRINT_POINTER(srealloc(p177,201););
printStats();
void* p182 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(48,70););
printStats();
void* p184 = last_address;
PRINT_POINTER(srealloc(p123,119););
printStats();
void* p185 = last_address;
PRINT_POINTER(scalloc(204,175););
printStats();
void* p186 = last_address;
PRINT_POINTER(scalloc(164,78););
printStats();
void* p187 = last_address;
DEBUG_PRINT(sfree(p99););
printStats();
PRINT_POINTER(scalloc(233,48););
printStats();
void* p188 = last_address;
PRINT_POINTER(scalloc(47,12););
printStats();
void* p189 = last_address;
PRINT_POINTER(scalloc(238,155););
printStats();
void* p190 = last_address;
PRINT_POINTER(srealloc(p179,94););
printStats();
void* p191 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p192 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p193 = last_address;
PRINT_POINTER(scalloc(72,54););
printStats();
void* p194 = last_address;
PRINT_POINTER(scalloc(138,199););
printStats();
void* p195 = last_address;
PRINT_POINTER(srealloc(p191,215););
printStats();
void* p196 = last_address;
PRINT_POINTER(scalloc(212,28););
printStats();
void* p197 = last_address;
PRINT_POINTER(srealloc(p183,177););
printStats();
void* p198 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p199 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p200 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p201 = last_address;
PRINT_POINTER(scalloc(153,30););
printStats();
void* p202 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p203 = last_address;
PRINT_POINTER(srealloc(p185,205););
printStats();
void* p204 = last_address;
DEBUG_PRINT(sfree(p160););
printStats();
PRINT_POINTER(srealloc(p193,169););
printStats();
void* p205 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p206 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p207 = last_address;
PRINT_POINTER(scalloc(121,94););
printStats();
void* p208 = last_address;
PRINT_POINTER(scalloc(148,222););
printStats();
void* p209 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p210 = last_address;
PRINT_POINTER(scalloc(213,209););
printStats();
void* p211 = last_address;
PRINT_POINTER(srealloc(p140,225););
printStats();
void* p212 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p213 = last_address;
PRINT_POINTER(srealloc(p200,168););
printStats();
void* p214 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p215 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p216 = last_address;
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(smalloc(222););
printStats();
void* p217 = last_address;
PRINT_POINTER(scalloc(75,221););
printStats();
void* p218 = last_address;
PRINT_POINTER(srealloc(p161,9););
printStats();
void* p219 = last_address;
PRINT_POINTER(srealloc(p194,27););
printStats();
void* p220 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
DEBUG_PRINT(sfree(p199););
printStats();
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(smalloc(179););
printStats();
void* p221 = last_address;
DEBUG_PRINT(sfree(p139););
printStats();
PRINT_POINTER(srealloc(p178,90););
printStats();
void* p222 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p223 = last_address;
PRINT_POINTER(scalloc(174,1););
printStats();
void* p224 = last_address;
PRINT_POINTER(scalloc(105,64););
printStats();
void* p225 = last_address;
PRINT_POINTER(srealloc(p146,132););
printStats();
void* p226 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p227 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p228 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p229 = last_address;
PRINT_POINTER(srealloc(p201,57););
printStats();
void* p230 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p231 = last_address;
PRINT_POINTER(srealloc(p227,237););
printStats();
void* p232 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p233 = last_address;
DEBUG_PRINT(sfree(p187););
printStats();
DEBUG_PRINT(sfree(p228););
printStats();
PRINT_POINTER(scalloc(94,225););
printStats();
void* p234 = last_address;
PRINT_POINTER(scalloc(230,84););
printStats();
void* p235 = last_address;
PRINT_POINTER(srealloc(p109,40););
printStats();
void* p236 = last_address;
PRINT_POINTER(scalloc(212,68););
printStats();
void* p237 = last_address;
DEBUG_PRINT(sfree(p168););
printStats();
PRINT_POINTER(srealloc(p237,186););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p190,98););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p234,69););
printStats();
void* p240 = last_address;
PRINT_POINTER(scalloc(12,71););
printStats();
void* p241 = last_address;
PRINT_POINTER(scalloc(187,209););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p184););
printStats();
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(smalloc(12););
printStats();
void* p243 = last_address;
PRINT_POINTER(srealloc(p114,180););
printStats();
void* p244 = last_address;
PRINT_POINTER(srealloc(p232,216););
printStats();
void* p245 = last_address;
PRINT_POINTER(srealloc(p192,244););
printStats();
void* p246 = last_address;
PRINT_POINTER(scalloc(172,204););
printStats();
void* p247 = last_address;
PRINT_POINTER(srealloc(p158,44););
printStats();
void* p248 = last_address;
PRINT_POINTER(srealloc(p180,249););
printStats();
void* p249 = last_address;
PRINT_POINTER(srealloc(p176,134););
printStats();
void* p250 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p251 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p252 = last_address;
DEBUG_PRINT(sfree(p243););
printStats();
PRINT_POINTER(smalloc(53););
printStats();
void* p253 = last_address;
DEBUG_PRINT(sfree(p132););
printStats();
PRINT_POINTER(srealloc(p215,70););
printStats();
void* p254 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p255 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p256 = last_address;
PRINT_POINTER(srealloc(p210,242););
printStats();
void* p257 = last_address;
PRINT_POINTER(scalloc(75,247););
printStats();
void* p258 = last_address;
PRINT_POINTER(scalloc(116,186););
printStats();
void* p259 = last_address;
PRINT_POINTER(srealloc(p224,58););
printStats();
void* p260 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p261 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p262 = last_address;
PRINT_POINTER(srealloc(p213,94););
printStats();
void* p263 = last_address;
PRINT_POINTER(scalloc(238,222););
printStats();
void* p264 = last_address;
DEBUG_PRINT(sfree(p189););
printStats();
PRINT_POINTER(scalloc(43,40););
printStats();
void* p265 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p266 = last_address;
PRINT_POINTER(scalloc(32,54););
printStats();
void* p267 = last_address;
PRINT_POINTER(srealloc(p198,88););
printStats();
void* p268 = last_address;
DEBUG_PRINT(sfree(p204););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p269 = last_address;
PRINT_POINTER(srealloc(p258,41););
printStats();
void* p270 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p271 = last_address;
PRINT_POINTER(srealloc(p270,188););
printStats();
void* p272 = last_address;
PRINT_POINTER(scalloc(136,185););
printStats();
void* p273 = last_address;
DEBUG_PRINT(sfree(p226););
printStats();
PRINT_POINTER(srealloc(p221,10););
printStats();
void* p274 = last_address;
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(srealloc(p162,31););
printStats();
void* p275 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
PRINT_POINTER(scalloc(104,99););
printStats();
void* p276 = last_address;
PRINT_POINTER(scalloc(136,163););
printStats();
void* p277 = last_address;
PRINT_POINTER(scalloc(25,114););
printStats();
void* p278 = last_address;
PRINT_POINTER(scalloc(181,178););
printStats();
void* p279 = last_address;
PRINT_POINTER(srealloc(p259,165););
printStats();
void* p280 = last_address;
PRINT_POINTER(srealloc(p265,71););
printStats();
void* p281 = last_address;
PRINT_POINTER(scalloc(203,124););
printStats();
void* p282 = last_address;
PRINT_POINTER(scalloc(140,138););
printStats();
void* p283 = last_address;
PRINT_POINTER(srealloc(p153,89););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p217,205););
printStats();
void* p285 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
DEBUG_PRINT(sfree(p238););
printStats();
DEBUG_PRINT(sfree(p267););
printStats();
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(scalloc(25,236););
printStats();
void* p286 = last_address;
PRINT_POINTER(scalloc(70,83););
printStats();
void* p287 = last_address;
DEBUG_PRINT(sfree(p275););
printStats();
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(smalloc(233););
printStats();
void* p288 = last_address;
PRINT_POINTER(srealloc(p279,177););
printStats();
void* p289 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p290 = last_address;
DEBUG_PRINT(sfree(p276););
printStats();
DEBUG_PRINT(sfree(p269););
printStats();
PRINT_POINTER(scalloc(74,198););
printStats();
void* p291 = last_address;
PRINT_POINTER(srealloc(p248,137););
printStats();
void* p292 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p293 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p294 = last_address;
DEBUG_PRINT(sfree(p252););
printStats();
PRINT_POINTER(srealloc(p281,79););
printStats();
void* p295 = last_address;
DEBUG_PRINT(sfree(p128););
printStats();
PRINT_POINTER(smalloc(57););
printStats();
void* p296 = last_address;
PRINT_POINTER(srealloc(p268,56););
printStats();
void* p297 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p298 = last_address;
PRINT_POINTER(srealloc(p144,245););
printStats();
void* p299 = last_address;
DEBUG_PRINT(sfree(p283););
printStats();
PRINT_POINTER(srealloc(p154,239););
printStats();
void* p300 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p302 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p303 = last_address;
PRINT_POINTER(srealloc(p280,199););
printStats();
void* p304 = last_address;
DEBUG_PRINT(sfree(p293););
printStats();
PRINT_POINTER(scalloc(59,70););
printStats();
void* p305 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p306 = last_address;
PRINT_POINTER(scalloc(36,192););
printStats();
void* p307 = last_address;
PRINT_POINTER(srealloc(p257,35););
printStats();
void* p308 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p309 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p310 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p311 = last_address;
PRINT_POINTER(srealloc(p150,12););
printStats();
void* p312 = last_address;
PRINT_POINTER(scalloc(188,223););
printStats();
void* p313 = last_address;
PRINT_POINTER(srealloc(p239,203););
printStats();
void* p314 = last_address;
PRINT_POINTER(srealloc(p284,64););
printStats();
void* p315 = last_address;
PRINT_POINTER(srealloc(p235,226););
printStats();
void* p316 = last_address;
DEBUG_PRINT(sfree(p216););
printStats();
PRINT_POINTER(srealloc(p205,56););
printStats();
void* p317 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p318 = last_address;
PRINT_POINTER(srealloc(p282,243););
printStats();
void* p319 = last_address;
PRINT_POINTER(srealloc(p214,245););
printStats();
void* p320 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p321 = last_address;
PRINT_POINTER(srealloc(p308,161););
printStats();
void* p322 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p323 = last_address;
PRINT_POINTER(srealloc(p317,143););
printStats();
void* p324 = last_address;
PRINT_POINTER(srealloc(p222,188););
printStats();
void* p325 = last_address;
PRINT_POINTER(srealloc(p196,218););
printStats();
void* p326 = last_address;
PRINT_POINTER(scalloc(127,12););
printStats();
void* p327 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p328 = last_address;
PRINT_POINTER(scalloc(205,116););
printStats();
void* p329 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p330 = last_address;
PRINT_POINTER(scalloc(158,129););
printStats();
void* p331 = last_address;
PRINT_POINTER(scalloc(82,56););
printStats();
void* p332 = last_address;
PRINT_POINTER(srealloc(p272,54););
printStats();
void* p333 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
DEBUG_PRINT(sfree(p287););
printStats();
PRINT_POINTER(scalloc(56,49););
printStats();
void* p334 = last_address;
DEBUG_PRINT(sfree(p307););
printStats();
PRINT_POINTER(smalloc(233););
printStats();
void* p335 = last_address;
PRINT_POINTER(scalloc(132,173););
printStats();
void* p336 = last_address;
PRINT_POINTER(srealloc(p206,115););
printStats();
void* p337 = last_address;
PRINT_POINTER(scalloc(36,186););
printStats();
void* p338 = last_address;
DEBUG_PRINT(sfree(p130););
printStats();
PRINT_POINTER(smalloc(216););
printStats();
void* p339 = last_address;
PRINT_POINTER(srealloc(p288,146););
printStats();
void* p340 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p341 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p342 = last_address;
DEBUG_PRINT(sfree(p195););
printStats();
PRINT_POINTER(scalloc(74,243););
printStats();
void* p343 = last_address;
PRINT_POINTER(srealloc(p332,145););
printStats();
void* p344 = last_address;
DEBUG_PRINT(sfree(p129););
printStats();
PRINT_POINTER(scalloc(11,90););
printStats();
void* p345 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p346 = last_address;
DEBUG_PRINT(sfree(p339););
printStats();
DEBUG_PRINT(sfree(p169););
printStats();
DEBUG_PRINT(sfree(p314););
printStats();
PRINT_POINTER(scalloc(201,62););
printStats();
void* p347 = last_address;
DEBUG_PRINT(sfree(p316););
printStats();
DEBUG_PRINT(sfree(p333););
printStats();
DEBUG_PRINT(sfree(p299););
printStats();
PRINT_POINTER(smalloc(64););
printStats();
void* p348 = last_address;
PRINT_POINTER(srealloc(p309,39););
printStats();
void* p349 = last_address;
PRINT_POINTER(scalloc(51,99););
printStats();
void* p350 = last_address;
PRINT_POINTER(srealloc(p302,140););
printStats();
void* p351 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
PRINT_POINTER(srealloc(p277,0););
printStats();
void* p352 = last_address;
DEBUG_PRINT(sfree(p327););
printStats();
PRINT_POINTER(scalloc(156,162););
printStats();
void* p353 = last_address;
PRINT_POINTER(scalloc(110,93););
printStats();
void* p354 = last_address;
PRINT_POINTER(srealloc(p245,99););
printStats();
void* p355 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p356 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p357 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p358 = last_address;
PRINT_POINTER(scalloc(6,47););
printStats();
void* p359 = last_address;
PRINT_POINTER(srealloc(p312,227););
printStats();
void* p360 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p361 = last_address;
PRINT_POINTER(srealloc(p165,116););
printStats();
void* p362 = last_address;
PRINT_POINTER(scalloc(212,58););
printStats();
void* p363 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p364 = last_address;
DEBUG_PRINT(sfree(p362););
printStats();
PRINT_POINTER(smalloc(147););
printStats();
void* p365 = last_address;
PRINT_POINTER(scalloc(248,161););
printStats();
void* p366 = last_address;
DEBUG_PRINT(sfree(p188););
printStats();
PRINT_POINTER(smalloc(200););
printStats();
void* p367 = last_address;
DEBUG_PRINT(sfree(p174););
printStats();
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(smalloc(134););
printStats();
void* p368 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p369 = last_address;
PRINT_POINTER(srealloc(p251,121););
printStats();
void* p370 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p371 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p372 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p373 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(scalloc(85,131););
printStats();
void* p374 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p375 = last_address;
PRINT_POINTER(scalloc(111,79););
printStats();
void* p376 = last_address;
PRINT_POINTER(scalloc(93,89););
printStats();
void* p377 = last_address;
PRINT_POINTER(srealloc(p172,72););
printStats();
void* p378 = last_address;
PRINT_POINTER(srealloc(p315,147););
printStats();
void* p379 = last_address;
PRINT_POINTER(scalloc(192,162););
printStats();
void* p380 = last_address;
PRINT_POINTER(scalloc(104,100););
printStats();
void* p381 = last_address;
PRINT_POINTER(scalloc(213,71););
printStats();
void* p382 = last_address;
PRINT_POINTER(scalloc(94,221););
printStats();
void* p383 = last_address;
PRINT_POINTER(scalloc(209,23););
printStats();
void* p384 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p385 = last_address;
PRINT_POINTER(srealloc(p357,115););
printStats();
void* p386 = last_address;
PRINT_POINTER(scalloc(152,27););
printStats();
void* p387 = last_address;
DEBUG_PRINT(sfree(p322););
printStats();
PRINT_POINTER(scalloc(238,32););
printStats();
void* p388 = last_address;
PRINT_POINTER(srealloc(p359,208););
printStats();
void* p389 = last_address;
PRINT_POINTER(scalloc(138,169););
printStats();
void* p390 = last_address;
PRINT_POINTER(srealloc(p256,38););
printStats();
void* p391 = last_address;
DEBUG_PRINT(sfree(p375););
printStats();
DEBUG_PRINT(sfree(p208););
printStats();
PRINT_POINTER(scalloc(37,239););
printStats();
void* p392 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p393 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p394 = last_address;
PRINT_POINTER(scalloc(90,106););
printStats();
void* p395 = last_address;
PRINT_POINTER(srealloc(p372,23););
printStats();
void* p396 = last_address;
PRINT_POINTER(scalloc(202,164););
printStats();
void* p397 = last_address;
DEBUG_PRINT(sfree(p368););
printStats();
PRINT_POINTER(smalloc(112););
printStats();
void* p398 = last_address;
PRINT_POINTER(scalloc(85,126););
printStats();
void* p399 = last_address;
PRINT_POINTER(srealloc(p211,83););
printStats();
void* p400 = last_address;
PRINT_POINTER(srealloc(p261,200););
printStats();
void* p401 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p402 = last_address;
PRINT_POINTER(srealloc(p381,82););
printStats();
void* p403 = last_address;
DEBUG_PRINT(sfree(p311););
printStats();
PRINT_POINTER(smalloc(171););
printStats();
void* p404 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p405 = last_address;
PRINT_POINTER(scalloc(216,38););
printStats();
void* p406 = last_address;
PRINT_POINTER(scalloc(31,104););
printStats();
void* p407 = last_address;
PRINT_POINTER(scalloc(88,185););
printStats();
void* p408 = last_address;
PRINT_POINTER(srealloc(p255,241););
printStats();
void* p409 = last_address;
DEBUG_PRINT(sfree(p326););
printStats();
DEBUG_PRINT(sfree(p149););
printStats();
PRINT_POINTER(srealloc(p286,235););
printStats();
void* p410 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p411 = last_address;
PRINT_POINTER(scalloc(115,67););
printStats();
void* p412 = last_address;
PRINT_POINTER(srealloc(p69,247););
printStats();
void* p413 = last_address;
DEBUG_PRINT(sfree(p320););
printStats();
PRINT_POINTER(scalloc(127,53););
printStats();
void* p414 = last_address;
PRINT_POINTER(srealloc(p389,7););
printStats();
void* p415 = last_address;
PRINT_POINTER(scalloc(46,37););
printStats();
void* p416 = last_address;
PRINT_POINTER(srealloc(p371,218););
printStats();
void* p417 = last_address;
PRINT_POINTER(scalloc(135,41););
printStats();
void* p418 = last_address;
DEBUG_PRINT(sfree(p411););
printStats();
DEBUG_PRINT(sfree(p297););
printStats();
PRINT_POINTER(scalloc(209,203););
printStats();
void* p419 = last_address;
DEBUG_PRINT(sfree(p380););
printStats();
PRINT_POINTER(smalloc(249););
printStats();
void* p420 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p421 = last_address;
DEBUG_PRINT(sfree(p398););
printStats();
PRINT_POINTER(smalloc(107););
printStats();
void* p422 = last_address;
PRINT_POINTER(srealloc(p410,97););
printStats();
void* p423 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p424 = last_address;
PRINT_POINTER(scalloc(234,115););
printStats();
void* p425 = last_address;
PRINT_POINTER(scalloc(214,124););
printStats();
void* p426 = last_address;
DEBUG_PRINT(sfree(p260););
printStats();
PRINT_POINTER(smalloc(239););
printStats();
void* p427 = last_address;
PRINT_POINTER(srealloc(p289,107););
printStats();
void* p428 = last_address;
PRINT_POINTER(srealloc(p166,158););
printStats();
void* p429 = last_address;
PRINT_POINTER(scalloc(150,134););
printStats();
void* p430 = last_address;
PRINT_POINTER(srealloc(p338,164););
printStats();
void* p431 = last_address;
DEBUG_PRINT(sfree(p409););
printStats();
DEBUG_PRINT(sfree(p292););
printStats();
PRINT_POINTER(scalloc(97,69););
printStats();
void* p432 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p433 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p434 = last_address;
DEBUG_PRINT(sfree(p377););
printStats();
PRINT_POINTER(smalloc(222););
printStats();
void* p435 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p436 = last_address;
PRINT_POINTER(scalloc(4,128););
printStats();
void* p437 = last_address;
DEBUG_PRINT(sfree(p155););
printStats();
PRINT_POINTER(scalloc(28,113););
printStats();
void* p438 = last_address;
PRINT_POINTER(scalloc(15,199););
printStats();
void* p439 = last_address;
PRINT_POINTER(scalloc(79,213););
printStats();
void* p440 = last_address;
PRINT_POINTER(scalloc(144,158););
printStats();
void* p441 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p442 = last_address;
PRINT_POINTER(scalloc(139,48););
printStats();
void* p443 = last_address;
PRINT_POINTER(scalloc(238,12););
printStats();
void* p444 = last_address;
PRINT_POINTER(srealloc(p363,63););
printStats();
void* p445 = last_address;
PRINT_POINTER(srealloc(p430,11););
printStats();
void* p446 = last_address;
PRINT_POINTER(srealloc(p298,155););
printStats();
void* p447 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p448 = last_address;
DEBUG_PRINT(sfree(p426););
printStats();
DEBUG_PRINT(sfree(p335););
printStats();
DEBUG_PRINT(sfree(p423););
printStats();
PRINT_POINTER(smalloc(82););
printStats();
void* p449 = last_address;
PRINT_POINTER(scalloc(194,27););
printStats();
void* p450 = last_address;
PRINT_POINTER(scalloc(148,53););
printStats();
void* p451 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p452 = last_address;
PRINT_POINTER(scalloc(132,105););
printStats();
void* p453 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p454 = last_address;
PRINT_POINTER(srealloc(p407,127););
printStats();
void* p455 = last_address;
DEBUG_PRINT(sfree(p433););
printStats();
DEBUG_PRINT(sfree(p330););
printStats();
PRINT_POINTER(smalloc(13););
printStats();
void* p456 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p457 = last_address;
PRINT_POINTER(srealloc(p418,156););
printStats();
void* p458 = last_address;
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(smalloc(148););
printStats();
void* p459 = last_address;
PRINT_POINTER(srealloc(p246,22););
printStats();
void* p460 = last_address;
PRINT_POINTER(scalloc(68,104););
printStats();
void* p461 = last_address;
PRINT_POINTER(scalloc(164,106););
printStats();
void* p462 = last_address;
DEBUG_PRINT(sfree(p241););
printStats();
PRINT_POINTER(scalloc(190,49););
printStats();
void* p463 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p464 = last_address;
PRINT_POINTER(scalloc(30,69););
printStats();
void* p465 = last_address;
PRINT_POINTER(srealloc(p120,8););
printStats();
void* p466 = last_address;
PRINT_POINTER(srealloc(p321,107););
printStats();
void* p467 = last_address;
PRINT_POINTER(srealloc(p349,166););
printStats();
void* p468 = last_address;
DEBUG_PRINT(sfree(p391););
printStats();
PRINT_POINTER(scalloc(143,22););
printStats();
void* p469 = last_address;
DEBUG_PRINT(sfree(p419););
printStats();
DEBUG_PRINT(sfree(p369););
printStats();
PRINT_POINTER(smalloc(117););
printStats();
void* p470 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p471 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p472 = last_address;
PRINT_POINTER(srealloc(p450,150););
printStats();
void* p473 = last_address;
PRINT_POINTER(scalloc(124,133););
printStats();
void* p474 = last_address;
PRINT_POINTER(srealloc(p290,162););
printStats();
void* p475 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p476 = last_address;
PRINT_POINTER(srealloc(p414,131););
printStats();
void* p477 = last_address;
DEBUG_PRINT(sfree(p167););
printStats();
PRINT_POINTER(srealloc(p96,148););
printStats();
void* p478 = last_address;
DEBUG_PRINT(sfree(p451););
printStats();
PRINT_POINTER(srealloc(p394,91););
printStats();
void* p479 = last_address;
DEBUG_PRINT(sfree(p373););
printStats();
PRINT_POINTER(smalloc(140););
printStats();
void* p480 = last_address;
PRINT_POINTER(scalloc(162,46););
printStats();
void* p481 = last_address;
DEBUG_PRINT(sfree(p448););
printStats();
PRINT_POINTER(srealloc(p247,111););
printStats();
void* p482 = last_address;
DEBUG_PRINT(sfree(p336););
printStats();
DEBUG_PRINT(sfree(p244););
printStats();
PRINT_POINTER(smalloc(89););
printStats();
void* p483 = last_address;
PRINT_POINTER(srealloc(p387,97););
printStats();
void* p484 = last_address;
PRINT_POINTER(scalloc(10,106););
printStats();
void* p485 = last_address;
PRINT_POINTER(srealloc(p202,216););
printStats();
void* p486 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p487 = last_address;
PRINT_POINTER(scalloc(138,221););
printStats();
void* p488 = last_address;
PRINT_POINTER(scalloc(59,130););
printStats();
void* p489 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p490 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p491 = last_address;
DEBUG_PRINT(sfree(p468););
printStats();
DEBUG_PRINT(sfree(p447););
printStats();
PRINT_POINTER(smalloc(95););
printStats();
void* p492 = last_address;
PRINT_POINTER(scalloc(53,69););
printStats();
void* p493 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p494 = last_address;
PRINT_POINTER(srealloc(p383,1););
printStats();
void* p495 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p496 = last_address;
PRINT_POINTER(scalloc(109,179););
printStats();
void* p497 = last_address;
DEBUG_PRINT(sfree(p318););
printStats();
DEBUG_PRINT(sfree(p231););
printStats();
DEBUG_PRINT(sfree(p382););
printStats();
PRINT_POINTER(smalloc(64););
printStats();
void* p498 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p499 = last_address;
DEBUG_PRINT(sfree(p483););
printStats();
PRINT_POINTER(srealloc(p491,106););
printStats();
void* p500 = last_address;
PRINT_POINTER(srealloc(p436,137););
printStats();
void* p501 = last_address;
PRINT_POINTER(srealloc(p163,11););
printStats();
void* p502 = last_address;
PRINT_POINTER(scalloc(209,146););
printStats();
void* p503 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p504 = last_address;
PRINT_POINTER(srealloc(p229,219););
printStats();
void* p505 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p506 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p507 = last_address;
PRINT_POINTER(srealloc(p348,169););
printStats();
void* p508 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p509 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p510 = last_address;
DEBUG_PRINT(sfree(p262););
printStats();
PRINT_POINTER(smalloc(155););
printStats();
void* p511 = last_address;
PRINT_POINTER(scalloc(44,177););
printStats();
void* p512 = last_address;
DEBUG_PRINT(sfree(p212););
printStats();
PRINT_POINTER(scalloc(95,105););
printStats();
void* p513 = last_address;
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(srealloc(p392,103););
printStats();
void* p514 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p515 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p516 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p517 = last_address;
DEBUG_PRINT(sfree(p355););
printStats();
PRINT_POINTER(srealloc(p356,20););
printStats();
void* p518 = last_address;
PRINT_POINTER(srealloc(p471,99););
printStats();
void* p519 = last_address;
DEBUG_PRINT(sfree(p421););
printStats();
PRINT_POINTER(scalloc(21,231););
printStats();
void* p520 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p521 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p522 = last_address;
DEBUG_PRINT(sfree(p488););
printStats();
PRINT_POINTER(smalloc(121););
printStats();
void* p523 = last_address;
DEBUG_PRINT(sfree(p494););
printStats();
PRINT_POINTER(smalloc(38););
printStats();
void* p524 = last_address;
DEBUG_PRINT(sfree(p504););
printStats();
PRINT_POINTER(scalloc(4,168););
printStats();
void* p525 = last_address;
DEBUG_PRINT(sfree(p403););
printStats();
DEBUG_PRINT(sfree(p474););
printStats();
PRINT_POINTER(scalloc(72,182););
printStats();
void* p526 = last_address;
DEBUG_PRINT(sfree(p449););
printStats();
PRINT_POINTER(smalloc(75););
printStats();
void* p527 = last_address;
DEBUG_PRINT(sfree(p413););
printStats();
DEBUG_PRINT(sfree(p440););
printStats();
PRINT_POINTER(scalloc(187,52););
printStats();
void* p528 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p529 = last_address;
PRINT_POINTER(scalloc(86,7););
printStats();
void* p530 = last_address;
DEBUG_PRINT(sfree(p511););
printStats();
PRINT_POINTER(smalloc(123););
printStats();
void* p531 = last_address;
PRINT_POINTER(srealloc(p300,22););
printStats();
void* p532 = last_address;
PRINT_POINTER(srealloc(p415,95););
printStats();
void* p533 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p534 = last_address;
DEBUG_PRINT(sfree(p296););
printStats();
PRINT_POINTER(smalloc(237););
printStats();
void* p535 = last_address;
DEBUG_PRINT(sfree(p384););
printStats();
DEBUG_PRINT(sfree(p342););
printStats();
PRINT_POINTER(srealloc(p480,122););
printStats();
void* p536 = last_address;
PRINT_POINTER(scalloc(234,149););
printStats();
void* p537 = last_address;
DEBUG_PRINT(sfree(p340););
printStats();
PRINT_POINTER(srealloc(p225,232););
printStats();
void* p538 = last_address;
PRINT_POINTER(scalloc(113,107););
printStats();
void* p539 = last_address;
DEBUG_PRINT(sfree(p510););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p540 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p541 = last_address;
PRINT_POINTER(srealloc(p404,205););
printStats();
void* p542 = last_address;
PRINT_POINTER(srealloc(p347,42););
printStats();
void* p543 = last_address;
DEBUG_PRINT(sfree(p304););
printStats();
PRINT_POINTER(srealloc(p350,68););
printStats();
void* p544 = last_address;
PRINT_POINTER(srealloc(p361,23););
printStats();
void* p545 = last_address;
PRINT_POINTER(scalloc(65,101););
printStats();
void* p546 = last_address;
PRINT_POINTER(srealloc(p454,241););
printStats();
void* p547 = last_address;
PRINT_POINTER(scalloc(211,17););
printStats();
void* p548 = last_address;
PRINT_POINTER(scalloc(112,203););
printStats();
void* p549 = last_address;
PRINT_POINTER(scalloc(99,58););
printStats();
void* p550 = last_address;
PRINT_POINTER(scalloc(179,31););
printStats();
void* p551 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p552 = last_address;
PRINT_POINTER(srealloc(p337,225););
printStats();
void* p553 = last_address;
DEBUG_PRINT(sfree(p266););
printStats();
DEBUG_PRINT(sfree(p524););
printStats();
PRINT_POINTER(srealloc(p487,103););
printStats();
void* p554 = last_address;
DEBUG_PRINT(sfree(p343););
printStats();
PRINT_POINTER(smalloc(89););
printStats();
void* p555 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p556 = last_address;
PRINT_POINTER(scalloc(142,61););
printStats();
void* p557 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p558 = last_address;
PRINT_POINTER(srealloc(p399,101););
printStats();
void* p559 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p560 = last_address;
DEBUG_PRINT(sfree(p402););
printStats();
DEBUG_PRINT(sfree(p345););
printStats();
PRINT_POINTER(srealloc(p295,122););
printStats();
void* p561 = last_address;
DEBUG_PRINT(sfree(p416););
printStats();
PRINT_POINTER(smalloc(90););
printStats();
void* p562 = last_address;
PRINT_POINTER(srealloc(p464,196););
printStats();
void* p563 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p564 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p565 = last_address;
PRINT_POINTER(srealloc(p351,175););
printStats();
void* p566 = last_address;
DEBUG_PRINT(sfree(p406););
printStats();
PRINT_POINTER(srealloc(p547,36););
printStats();
void* p567 = last_address;
DEBUG_PRINT(sfree(p164););
printStats();
DEBUG_PRINT(sfree(p207););
printStats();
DEBUG_PRINT(sfree(p458););
printStats();
PRINT_POINTER(srealloc(p501,218););
printStats();
void* p568 = last_address;
PRINT_POINTER(scalloc(178,112););
printStats();
void* p569 = last_address;
DEBUG_PRINT(sfree(p497););
printStats();
PRINT_POINTER(srealloc(p274,246););
printStats();
void* p570 = last_address;
DEBUG_PRINT(sfree(p393););
printStats();
DEBUG_PRINT(sfree(p182););
printStats();
PRINT_POINTER(scalloc(18,155););
printStats();
void* p571 = last_address;
PRINT_POINTER(srealloc(p514,195););
printStats();
void* p572 = last_address;
DEBUG_PRINT(sfree(p525););
printStats();
DEBUG_PRINT(sfree(p131););
printStats();
PRINT_POINTER(scalloc(82,99););
printStats();
void* p573 = last_address;
PRINT_POINTER(scalloc(118,7););
printStats();
void* p574 = last_address;
PRINT_POINTER(scalloc(73,216););
printStats();
void* p575 = last_address;
DEBUG_PRINT(sfree(p553););
printStats();
DEBUG_PRINT(sfree(p502););
printStats();
DEBUG_PRINT(sfree(p519););
printStats();
DEBUG_PRINT(sfree(p571););
printStats();
PRINT_POINTER(scalloc(145,232););
printStats();
void* p576 = last_address;
PRINT_POINTER(scalloc(65,245););
printStats();
void* p577 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p578 = last_address;
DEBUG_PRINT(sfree(p422););
printStats();
PRINT_POINTER(srealloc(p328,178););
printStats();
void* p579 = last_address;
DEBUG_PRINT(sfree(p564););
printStats();
DEBUG_PRINT(sfree(p459););
printStats();
PRINT_POINTER(scalloc(30,118););
printStats();
void* p580 = last_address;
PRINT_POINTER(scalloc(65,21););
printStats();
void* p581 = last_address;
PRINT_POINTER(srealloc(p489,109););
printStats();
void* p582 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p583 = last_address;
PRINT_POINTER(srealloc(p445,157););
printStats();
void* p584 = last_address;
DEBUG_PRINT(sfree(p568););
printStats();
DEBUG_PRINT(sfree(p455););
printStats();
PRINT_POINTER(smalloc(12););
printStats();
void* p585 = last_address;
PRINT_POINTER(srealloc(p273,86););
printStats();
void* p586 = last_address;
PRINT_POINTER(scalloc(210,133););
printStats();
void* p587 = last_address;
PRINT_POINTER(srealloc(p551,31););
printStats();
void* p588 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p589 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(smalloc(161););
printStats();
void* p590 = last_address;
PRINT_POINTER(srealloc(p412,148););
printStats();
void* p591 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p592 = last_address;
PRINT_POINTER(scalloc(221,206););
printStats();
void* p593 = last_address;
DEBUG_PRINT(sfree(p588););
printStats();
DEBUG_PRINT(sfree(p478););
printStats();
PRINT_POINTER(srealloc(p534,63););
printStats();
void* p594 = last_address;
DEBUG_PRINT(sfree(p425););
printStats();
DEBUG_PRINT(sfree(p561););
printStats();
DEBUG_PRINT(sfree(p374););
printStats();
DEBUG_PRINT(sfree(p353););
printStats();
PRINT_POINTER(srealloc(p537,101););
printStats();
void* p595 = last_address;
DEBUG_PRINT(sfree(p466););
printStats();
PRINT_POINTER(scalloc(16,46););
printStats();
void* p596 = last_address;
PRINT_POINTER(srealloc(p388,246););
printStats();
void* p597 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p598 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p599 = last_address;
PRINT_POINTER(srealloc(p549,163););
printStats();
void* p600 = last_address;
PRINT_POINTER(scalloc(115,76););
printStats();
void* p601 = last_address;
DEBUG_PRINT(sfree(p219););
printStats();
DEBUG_PRINT(sfree(p301););
printStats();
DEBUG_PRINT(sfree(p390););
printStats();
PRINT_POINTER(srealloc(p365,44););
printStats();
void* p602 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p603 = last_address;
DEBUG_PRINT(sfree(p306););
printStats();
PRINT_POINTER(smalloc(124););
printStats();
void* p604 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p605 = last_address;
PRINT_POINTER(scalloc(134,204););
printStats();
void* p606 = last_address;
DEBUG_PRINT(sfree(p441););
printStats();
PRINT_POINTER(smalloc(182););
printStats();
void* p607 = last_address;
PRINT_POINTER(srealloc(p532,174););
printStats();
void* p608 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p609 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p610 = last_address;
DEBUG_PRINT(sfree(p434););
printStats();
DEBUG_PRINT(sfree(p516););
printStats();
PRINT_POINTER(srealloc(p475,178););
printStats();
void* p611 = last_address;
PRINT_POINTER(srealloc(p236,91););
printStats();
void* p612 = last_address;
DEBUG_PRINT(sfree(p446););
printStats();
PRINT_POINTER(smalloc(146););
printStats();
void* p613 = last_address;
PRINT_POINTER(scalloc(121,39););
printStats();
void* p614 = last_address;
PRINT_POINTER(srealloc(p522,74););
printStats();
void* p615 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p616 = last_address;
PRINT_POINTER(srealloc(p507,156););
printStats();
void* p617 = last_address;
DEBUG_PRINT(sfree(p397););
printStats();
PRINT_POINTER(srealloc(p385,137););
printStats();
void* p618 = last_address;
PRINT_POINTER(srealloc(p319,25););
printStats();
void* p619 = last_address;
DEBUG_PRINT(sfree(p484););
printStats();
PRINT_POINTER(srealloc(p400,120););
printStats();
void* p620 = last_address;
DEBUG_PRINT(sfree(p550););
printStats();
DEBUG_PRINT(sfree(p592););
printStats();
PRINT_POINTER(srealloc(p493,200););
printStats();
void* p621 = last_address;
DEBUG_PRINT(sfree(p401););
printStats();
PRINT_POINTER(smalloc(33););
printStats();
void* p622 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p623 = last_address;
PRINT_POINTER(scalloc(126,194););
printStats();
void* p624 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p625 = last_address;
PRINT_POINTER(srealloc(p467,237););
printStats();
void* p626 = last_address;
DEBUG_PRINT(sfree(p370););
printStats();
PRINT_POINTER(smalloc(89););
printStats();
void* p627 = last_address;
PRINT_POINTER(scalloc(194,216););
printStats();
void* p628 = last_address;
PRINT_POINTER(scalloc(14,38););
printStats();
void* p629 = last_address;
DEBUG_PRINT(sfree(p428););
printStats();
PRINT_POINTER(srealloc(p617,230););
printStats();
void* p630 = last_address;
PRINT_POINTER(srealloc(p476,59););
printStats();
void* p631 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p632 = last_address;
PRINT_POINTER(srealloc(p533,24););
printStats();
void* p633 = last_address;
PRINT_POINTER(scalloc(14,2););
printStats();
void* p634 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p635 = last_address;
PRINT_POINTER(scalloc(225,50););
printStats();
void* p636 = last_address;
DEBUG_PRINT(sfree(p609););
printStats();
PRINT_POINTER(srealloc(p608,114););
printStats();
void* p637 = last_address;
PRINT_POINTER(srealloc(p518,3););
printStats();
void* p638 = last_address;
PRINT_POINTER(srealloc(p626,185););
printStats();
void* p639 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p640 = last_address;
PRINT_POINTER(scalloc(227,215););
printStats();
void* p641 = last_address;
PRINT_POINTER(scalloc(146,57););
printStats();
void* p642 = last_address;
PRINT_POINTER(srealloc(p641,118););
printStats();
void* p643 = last_address;
PRINT_POINTER(srealloc(p460,96););
printStats();
void* p644 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p645 = last_address;
PRINT_POINTER(scalloc(119,146););
printStats();
void* p646 = last_address;
PRINT_POINTER(scalloc(231,39););
printStats();
void* p647 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
PRINT_POINTER(scalloc(35,17););
printStats();
void* p648 = last_address;
PRINT_POINTER(scalloc(229,222););
printStats();
void* p649 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p650 = last_address;
DEBUG_PRINT(sfree(p628););
printStats();
PRINT_POINTER(scalloc(27,48););
printStats();
void* p651 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p652 = last_address;
PRINT_POINTER(srealloc(p233,23););
printStats();
void* p653 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p654 = last_address;
PRINT_POINTER(scalloc(54,54););
printStats();
void* p655 = last_address;
PRINT_POINTER(scalloc(89,242););
printStats();
void* p656 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p657 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p658 = last_address;
DEBUG_PRINT(sfree(p171););
printStats();
PRINT_POINTER(smalloc(62););
printStats();
void* p659 = last_address;
PRINT_POINTER(srealloc(p597,97););
printStats();
void* p660 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p661 = last_address;
DEBUG_PRINT(sfree(p610););
printStats();
DEBUG_PRINT(sfree(p632););
printStats();
PRINT_POINTER(scalloc(3,247););
printStats();
void* p662 = last_address;
PRINT_POINTER(scalloc(37,82););
printStats();
void* p663 = last_address;
DEBUG_PRINT(sfree(p435););
printStats();
DEBUG_PRINT(sfree(p650););
printStats();
PRINT_POINTER(srealloc(p580,43););
printStats();
void* p664 = last_address;
DEBUG_PRINT(sfree(p569););
printStats();
PRINT_POINTER(smalloc(236););
printStats();
void* p665 = last_address;
PRINT_POINTER(srealloc(p593,106););
printStats();
void* p666 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p667 = last_address;
PRINT_POINTER(scalloc(17,235););
printStats();
void* p668 = last_address;
PRINT_POINTER(srealloc(p520,84););
printStats();
void* p669 = last_address;
DEBUG_PRINT(sfree(p620););
printStats();
PRINT_POINTER(scalloc(110,102););
printStats();
void* p670 = last_address;
PRINT_POINTER(scalloc(197,114););
printStats();
void* p671 = last_address;
PRINT_POINTER(scalloc(125,9););
printStats();
void* p672 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p673 = last_address;
PRINT_POINTER(scalloc(246,19););
printStats();
void* p674 = last_address;
PRINT_POINTER(scalloc(149,86););
printStats();
void* p675 = last_address;
DEBUG_PRINT(sfree(p629););
printStats();
PRINT_POINTER(smalloc(91););
printStats();
void* p676 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p677 = last_address;
PRINT_POINTER(srealloc(p619,88););
printStats();
void* p678 = last_address;
PRINT_POINTER(srealloc(p662,131););
printStats();
void* p679 = last_address;
PRINT_POINTER(srealloc(p658,128););
printStats();
void* p680 = last_address;
PRINT_POINTER(scalloc(12,125););
printStats();
void* p681 = last_address;
PRINT_POINTER(scalloc(59,205););
printStats();
void* p682 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p683 = last_address;
PRINT_POINTER(srealloc(p535,166););
printStats();
void* p684 = last_address;
PRINT_POINTER(scalloc(47,164););
printStats();
void* p685 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p686 = last_address;
DEBUG_PRINT(sfree(p496););
printStats();
PRINT_POINTER(scalloc(158,137););
printStats();
void* p687 = last_address;
DEBUG_PRINT(sfree(p528););
printStats();
PRINT_POINTER(scalloc(90,218););
printStats();
void* p688 = last_address;
PRINT_POINTER(srealloc(p538,200););
printStats();
void* p689 = last_address;
PRINT_POINTER(scalloc(244,128););
printStats();
void* p690 = last_address;
PRINT_POINTER(scalloc(180,31););
printStats();
void* p691 = last_address;
DEBUG_PRINT(sfree(p581););
printStats();
PRINT_POINTER(smalloc(90););
printStats();
void* p692 = last_address;
PRINT_POINTER(srealloc(p604,162););
printStats();
void* p693 = last_address;
PRINT_POINTER(scalloc(229,105););
printStats();
void* p694 = last_address;
PRINT_POINTER(srealloc(p500,24););
printStats();
void* p695 = last_address;
PRINT_POINTER(scalloc(92,37););
printStats();
void* p696 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p697 = last_address;
PRINT_POINTER(scalloc(241,106););
printStats();
void* p698 = last_address;
PRINT_POINTER(srealloc(p376,233););
printStats();
void* p699 = last_address;
PRINT_POINTER(scalloc(55,174););
printStats();
void* p700 = last_address;
PRINT_POINTER(scalloc(72,116););
printStats();
void* p701 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p702 = last_address;
PRINT_POINTER(scalloc(132,38););
printStats();
void* p703 = last_address;
PRINT_POINTER(srealloc(p647,245););
printStats();
void* p704 = last_address;
DEBUG_PRINT(sfree(p698););
printStats();
DEBUG_PRINT(sfree(p602););
printStats();
PRINT_POINTER(scalloc(232,192););
printStats();
void* p705 = last_address;
PRINT_POINTER(srealloc(p565,43););
printStats();
void* p706 = last_address;
PRINT_POINTER(scalloc(74,199););
printStats();
void* p707 = last_address;
PRINT_POINTER(scalloc(7,188););
printStats();
void* p708 = last_address;
PRINT_POINTER(srealloc(p486,106););
printStats();
void* p709 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p710 = last_address;
PRINT_POINTER(scalloc(240,77););
printStats();
void* p711 = last_address;
DEBUG_PRINT(sfree(p556););
printStats();
PRINT_POINTER(scalloc(101,219););
printStats();
void* p712 = last_address;
PRINT_POINTER(srealloc(p346,166););
printStats();
void* p713 = last_address;
PRINT_POINTER(scalloc(49,123););
printStats();
void* p714 = last_address;
PRINT_POINTER(scalloc(16,202););
printStats();
void* p715 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p716 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p717 = last_address;
PRINT_POINTER(srealloc(p584,227););
printStats();
void* p718 = last_address;
DEBUG_PRINT(sfree(p636););
printStats();
DEBUG_PRINT(sfree(p405););
printStats();
PRINT_POINTER(srealloc(p678,211););
printStats();
void* p719 = last_address;
PRINT_POINTER(scalloc(173,246););
printStats();
void* p720 = last_address;
PRINT_POINTER(scalloc(2,148););
printStats();
void* p721 = last_address;
PRINT_POINTER(srealloc(p264,164););
printStats();
void* p722 = last_address;
PRINT_POINTER(scalloc(161,231););
printStats();
void* p723 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p724 = last_address;
DEBUG_PRINT(sfree(p615););
printStats();
DEBUG_PRINT(sfree(p657););
printStats();
PRINT_POINTER(srealloc(p699,44););
printStats();
void* p725 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p726 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p727 = last_address;
PRINT_POINTER(scalloc(99,248););
printStats();
void* p728 = last_address;
DEBUG_PRINT(sfree(p541););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p729 = last_address;
PRINT_POINTER(srealloc(p479,96););
printStats();
void* p730 = last_address;
PRINT_POINTER(srealloc(p453,10););
printStats();
void* p731 = last_address;
PRINT_POINTER(scalloc(118,44););
printStats();
void* p732 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p733 = last_address;
DEBUG_PRINT(sfree(p439););
printStats();
DEBUG_PRINT(sfree(p575););
printStats();
PRINT_POINTER(smalloc(20););
printStats();
void* p734 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p735 = last_address;
PRINT_POINTER(scalloc(6,235););
printStats();
void* p736 = last_address;
PRINT_POINTER(srealloc(p325,196););
printStats();
void* p737 = last_address;
DEBUG_PRINT(sfree(p707););
printStats();
PRINT_POINTER(srealloc(p443,159););
printStats();
void* p738 = last_address;
PRINT_POINTER(scalloc(68,28););
printStats();
void* p739 = last_address;
PRINT_POINTER(scalloc(47,199););
printStats();
void* p740 = last_address;
PRINT_POINTER(scalloc(53,96););
printStats();
void* p741 = last_address;
PRINT_POINTER(srealloc(p576,53););
printStats();
void* p742 = last_address;
PRINT_POINTER(srealloc(p344,159););
printStats();
void* p743 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p744 = last_address;
DEBUG_PRINT(sfree(p740););
printStats();
PRINT_POINTER(scalloc(228,178););
printStats();
void* p745 = last_address;
PRINT_POINTER(scalloc(205,34););
printStats();
void* p746 = last_address;
DEBUG_PRINT(sfree(p637););
printStats();
PRINT_POINTER(scalloc(226,96););
printStats();
void* p747 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p748 = last_address;
PRINT_POINTER(scalloc(135,205););
printStats();
void* p749 = last_address;
PRINT_POINTER(scalloc(171,176););
printStats();
void* p750 = last_address;
PRINT_POINTER(srealloc(p661,189););
printStats();
void* p751 = last_address;
DEBUG_PRINT(sfree(p668););
printStats();
PRINT_POINTER(scalloc(246,202););
printStats();
void* p752 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p753 = last_address;
PRINT_POINTER(scalloc(169,214););
printStats();
void* p754 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p755 = last_address;
DEBUG_PRINT(sfree(p683););
printStats();
PRINT_POINTER(srealloc(p755,73););
printStats();
void* p756 = last_address;
PRINT_POINTER(scalloc(97,50););
printStats();
void* p757 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p758 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p759 = last_address;
PRINT_POINTER(srealloc(p742,42););
printStats();
void* p760 = last_address;
PRINT_POINTER(scalloc(87,105););
printStats();
void* p761 = last_address;
PRINT_POINTER(scalloc(41,80););
printStats();
void* p762 = last_address;
PRINT_POINTER(scalloc(11,7););
printStats();
void* p763 = last_address;
DEBUG_PRINT(sfree(p719););
printStats();
PRINT_POINTER(scalloc(142,4););
printStats();
void* p764 = last_address;
DEBUG_PRINT(sfree(p481););
printStats();
PRINT_POINTER(srealloc(p324,30););
printStats();
void* p765 = last_address;
PRINT_POINTER(scalloc(204,67););
printStats();
void* p766 = last_address;
PRINT_POINTER(scalloc(98,90););
printStats();
void* p767 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p768 = last_address;
PRINT_POINTER(srealloc(p639,170););
printStats();
void* p769 = last_address;
DEBUG_PRINT(sfree(p506););
printStats();
DEBUG_PRINT(sfree(p303););
printStats();
PRINT_POINTER(scalloc(22,64););
printStats();
void* p770 = last_address;
PRINT_POINTER(srealloc(p752,67););
printStats();
void* p771 = last_address;
PRINT_POINTER(scalloc(169,129););
printStats();
void* p772 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p773 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p774 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p775 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p776 = last_address;
PRINT_POINTER(scalloc(152,146););
printStats();
void* p777 = last_address;
PRINT_POINTER(scalloc(249,14););
printStats();
void* p778 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p779 = last_address;
DEBUG_PRINT(sfree(p741););
printStats();
DEBUG_PRINT(sfree(p616););
printStats();
PRINT_POINTER(scalloc(24,145););
printStats();
void* p780 = last_address;
PRINT_POINTER(scalloc(127,178););
printStats();
void* p781 = last_address;
DEBUG_PRINT(sfree(p773););
printStats();
DEBUG_PRINT(sfree(p429););
printStats();
DEBUG_PRINT(sfree(p758););
printStats();
PRINT_POINTER(smalloc(188););
printStats();
void* p782 = last_address;
}
