#include "aux_macro.h"
#include "../malloc_4.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(113,113););
printStats();
void* p0 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(scalloc(191,35););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(scalloc(8,39););
printStats();
void* p2 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p3 = last_address;
DEBUG_PRINT(sfree(p3););
printStats();
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(smalloc(147););
printStats();
void* p4 = last_address;
PRINT_POINTER(srealloc(p4,161););
printStats();
void* p5 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p6 = last_address;
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(smalloc(190););
printStats();
void* p7 = last_address;
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(scalloc(34,27););
printStats();
void* p8 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
PRINT_POINTER(scalloc(160,209););
printStats();
void* p9 = last_address;
PRINT_POINTER(srealloc(p9,75););
printStats();
void* p10 = last_address;
DEBUG_PRINT(sfree(p10););
printStats();
PRINT_POINTER(smalloc(117););
printStats();
void* p11 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p12 = last_address;
PRINT_POINTER(srealloc(p8,86););
printStats();
void* p13 = last_address;
DEBUG_PRINT(sfree(p13););
printStats();
PRINT_POINTER(srealloc(p11,154););
printStats();
void* p14 = last_address;
DEBUG_PRINT(sfree(p14););
printStats();
DEBUG_PRINT(sfree(p12););
printStats();
PRINT_POINTER(scalloc(229,48););
printStats();
void* p15 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(scalloc(4,18););
printStats();
void* p16 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(62,98););
printStats();
void* p18 = last_address;
PRINT_POINTER(srealloc(p18,101););
printStats();
void* p19 = last_address;
DEBUG_PRINT(sfree(p19););
printStats();
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(srealloc(p17,135););
printStats();
void* p20 = last_address;
PRINT_POINTER(srealloc(p20,121););
printStats();
void* p21 = last_address;
PRINT_POINTER(scalloc(152,205););
printStats();
void* p22 = last_address;
PRINT_POINTER(scalloc(86,169););
printStats();
void* p23 = last_address;
PRINT_POINTER(srealloc(p21,24););
printStats();
void* p24 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(smalloc(83););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(113,247););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p23,197););
printStats();
void* p27 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p28 = last_address;
PRINT_POINTER(scalloc(214,220););
printStats();
void* p29 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
DEBUG_PRINT(sfree(p27););
printStats();
PRINT_POINTER(smalloc(115););
printStats();
void* p30 = last_address;
PRINT_POINTER(scalloc(130,94););
printStats();
void* p31 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
PRINT_POINTER(scalloc(62,238););
printStats();
void* p32 = last_address;
PRINT_POINTER(scalloc(156,147););
printStats();
void* p33 = last_address;
PRINT_POINTER(scalloc(125,167););
printStats();
void* p34 = last_address;
PRINT_POINTER(scalloc(197,124););
printStats();
void* p35 = last_address;
PRINT_POINTER(scalloc(189,177););
printStats();
void* p36 = last_address;
PRINT_POINTER(scalloc(129,220););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(239,38););
printStats();
void* p38 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(srealloc(p31,174););
printStats();
void* p39 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
PRINT_POINTER(srealloc(p34,146););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p30,47););
printStats();
void* p41 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p42 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(smalloc(127););
printStats();
void* p43 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p44 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p45 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
PRINT_POINTER(srealloc(p24,95););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p47 = last_address;
PRINT_POINTER(srealloc(p46,8););
printStats();
void* p48 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p49 = last_address;
PRINT_POINTER(scalloc(111,233););
printStats();
void* p50 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(scalloc(216,12););
printStats();
void* p51 = last_address;
PRINT_POINTER(srealloc(p28,39););
printStats();
void* p52 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p53 = last_address;
DEBUG_PRINT(sfree(p49););
printStats();
DEBUG_PRINT(sfree(p48););
printStats();
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(scalloc(141,89););
printStats();
void* p54 = last_address;
PRINT_POINTER(srealloc(p53,12););
printStats();
void* p55 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
PRINT_POINTER(srealloc(p51,236););
printStats();
void* p56 = last_address;
DEBUG_PRINT(sfree(p35););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(79,195););
printStats();
void* p58 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p59 = last_address;
DEBUG_PRINT(sfree(p58););
printStats();
PRINT_POINTER(smalloc(216););
printStats();
void* p60 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(srealloc(p42,102););
printStats();
void* p61 = last_address;
PRINT_POINTER(scalloc(15,230););
printStats();
void* p62 = last_address;
DEBUG_PRINT(sfree(p40););
printStats();
DEBUG_PRINT(sfree(p32););
printStats();
DEBUG_PRINT(sfree(p61););
printStats();
PRINT_POINTER(smalloc(219););
printStats();
void* p63 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(smalloc(72););
printStats();
void* p64 = last_address;
DEBUG_PRINT(sfree(p52););
printStats();
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(scalloc(135,92););
printStats();
void* p65 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p66 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p67 = last_address;
PRINT_POINTER(scalloc(107,122););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p62,137););
printStats();
void* p69 = last_address;
PRINT_POINTER(srealloc(p47,76););
printStats();
void* p70 = last_address;
PRINT_POINTER(srealloc(p26,196););
printStats();
void* p71 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p72 = last_address;
PRINT_POINTER(scalloc(119,99););
printStats();
void* p73 = last_address;
PRINT_POINTER(srealloc(p63,2););
printStats();
void* p74 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
DEBUG_PRINT(sfree(p54););
printStats();
PRINT_POINTER(srealloc(p65,99););
printStats();
void* p75 = last_address;
DEBUG_PRINT(sfree(p74););
printStats();
DEBUG_PRINT(sfree(p44););
printStats();
PRINT_POINTER(scalloc(208,62););
printStats();
void* p76 = last_address;
PRINT_POINTER(scalloc(164,115););
printStats();
void* p77 = last_address;
PRINT_POINTER(scalloc(114,82););
printStats();
void* p78 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p79 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(srealloc(p71,201););
printStats();
void* p80 = last_address;
DEBUG_PRINT(sfree(p55););
printStats();
PRINT_POINTER(smalloc(242););
printStats();
void* p81 = last_address;
PRINT_POINTER(scalloc(31,32););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p83 = last_address;
PRINT_POINTER(srealloc(p70,39););
printStats();
void* p84 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p85 = last_address;
PRINT_POINTER(srealloc(p67,88););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p79,238););
printStats();
void* p87 = last_address;
DEBUG_PRINT(sfree(p87););
printStats();
PRINT_POINTER(srealloc(p56,34););
printStats();
void* p88 = last_address;
PRINT_POINTER(scalloc(7,198););
printStats();
void* p89 = last_address;
PRINT_POINTER(scalloc(183,63););
printStats();
void* p90 = last_address;
PRINT_POINTER(scalloc(231,163););
printStats();
void* p91 = last_address;
PRINT_POINTER(srealloc(p91,201););
printStats();
void* p92 = last_address;
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(scalloc(175,48););
printStats();
void* p93 = last_address;
PRINT_POINTER(scalloc(18,17););
printStats();
void* p94 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p95 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p96 = last_address;
PRINT_POINTER(scalloc(144,233););
printStats();
void* p97 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p98 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p99 = last_address;
PRINT_POINTER(scalloc(13,207););
printStats();
void* p100 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(scalloc(194,18););
printStats();
void* p101 = last_address;
PRINT_POINTER(scalloc(10,57););
printStats();
void* p102 = last_address;
PRINT_POINTER(scalloc(148,166););
printStats();
void* p103 = last_address;
PRINT_POINTER(scalloc(93,222););
printStats();
void* p104 = last_address;
PRINT_POINTER(scalloc(62,151););
printStats();
void* p105 = last_address;
PRINT_POINTER(scalloc(142,235););
printStats();
void* p106 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p107 = last_address;
DEBUG_PRINT(sfree(p76););
printStats();
DEBUG_PRINT(sfree(p75););
printStats();
PRINT_POINTER(scalloc(47,76););
printStats();
void* p108 = last_address;
PRINT_POINTER(srealloc(p99,145););
printStats();
void* p109 = last_address;
DEBUG_PRINT(sfree(p73););
printStats();
DEBUG_PRINT(sfree(p80););
printStats();
PRINT_POINTER(scalloc(104,103););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p57,217););
printStats();
void* p111 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
DEBUG_PRINT(sfree(p108););
printStats();
PRINT_POINTER(smalloc(11););
printStats();
void* p112 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(scalloc(93,200););
printStats();
void* p113 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p114 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p115 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p116 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
DEBUG_PRINT(sfree(p114););
printStats();
DEBUG_PRINT(sfree(p112););
printStats();
PRINT_POINTER(smalloc(182););
printStats();
void* p117 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p118 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p119 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p120 = last_address;
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(smalloc(16););
printStats();
void* p121 = last_address;
PRINT_POINTER(scalloc(69,249););
printStats();
void* p122 = last_address;
DEBUG_PRINT(sfree(p88););
printStats();
PRINT_POINTER(scalloc(233,61););
printStats();
void* p123 = last_address;
PRINT_POINTER(scalloc(195,161););
printStats();
void* p124 = last_address;
PRINT_POINTER(scalloc(179,240););
printStats();
void* p125 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(183,44););
printStats();
void* p127 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
PRINT_POINTER(srealloc(p121,41););
printStats();
void* p128 = last_address;
DEBUG_PRINT(sfree(p126););
printStats();
DEBUG_PRINT(sfree(p103););
printStats();
PRINT_POINTER(smalloc(73););
printStats();
void* p129 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(srealloc(p129,243););
printStats();
void* p130 = last_address;
DEBUG_PRINT(sfree(p124););
printStats();
DEBUG_PRINT(sfree(p116););
printStats();
PRINT_POINTER(srealloc(p130,143););
printStats();
void* p131 = last_address;
PRINT_POINTER(srealloc(p94,21););
printStats();
void* p132 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(smalloc(159););
printStats();
void* p133 = last_address;
PRINT_POINTER(srealloc(p110,22););
printStats();
void* p134 = last_address;
PRINT_POINTER(srealloc(p90,3););
printStats();
void* p135 = last_address;
PRINT_POINTER(srealloc(p105,207););
printStats();
void* p136 = last_address;
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(srealloc(p107,9););
printStats();
void* p137 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p138 = last_address;
PRINT_POINTER(scalloc(182,183););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p106););
printStats();
PRINT_POINTER(srealloc(p117,0););
printStats();
void* p140 = last_address;
PRINT_POINTER(srealloc(p139,120););
printStats();
void* p141 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p142 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p143 = last_address;
PRINT_POINTER(srealloc(p131,213););
printStats();
void* p144 = last_address;
PRINT_POINTER(srealloc(p133,221););
printStats();
void* p145 = last_address;
PRINT_POINTER(scalloc(101,243););
printStats();
void* p146 = last_address;
PRINT_POINTER(scalloc(103,12););
printStats();
void* p147 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(smalloc(136););
printStats();
void* p148 = last_address;
PRINT_POINTER(srealloc(p125,125););
printStats();
void* p149 = last_address;
PRINT_POINTER(srealloc(p83,166););
printStats();
void* p150 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p151 = last_address;
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(smalloc(25););
printStats();
void* p152 = last_address;
PRINT_POINTER(scalloc(132,116););
printStats();
void* p153 = last_address;
DEBUG_PRINT(sfree(p143););
printStats();
DEBUG_PRINT(sfree(p146););
printStats();
DEBUG_PRINT(sfree(p135););
printStats();
PRINT_POINTER(scalloc(79,229););
printStats();
void* p154 = last_address;
DEBUG_PRINT(sfree(p111););
printStats();
DEBUG_PRINT(sfree(p136););
printStats();
DEBUG_PRINT(sfree(p137););
printStats();
PRINT_POINTER(srealloc(p138,149););
printStats();
void* p155 = last_address;
PRINT_POINTER(scalloc(237,144););
printStats();
void* p156 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p157 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
PRINT_POINTER(srealloc(p140,140););
printStats();
void* p158 = last_address;
PRINT_POINTER(srealloc(p150,87););
printStats();
void* p159 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p160 = last_address;
DEBUG_PRINT(sfree(p128););
printStats();
PRINT_POINTER(scalloc(35,139););
printStats();
void* p161 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p162 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p163 = last_address;
PRINT_POINTER(srealloc(p147,204););
printStats();
void* p164 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(scalloc(97,130););
printStats();
void* p165 = last_address;
PRINT_POINTER(scalloc(126,214););
printStats();
void* p166 = last_address;
PRINT_POINTER(srealloc(p162,216););
printStats();
void* p167 = last_address;
PRINT_POINTER(scalloc(221,240););
printStats();
void* p168 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p169 = last_address;
DEBUG_PRINT(sfree(p154););
printStats();
PRINT_POINTER(smalloc(162););
printStats();
void* p170 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p171 = last_address;
PRINT_POINTER(srealloc(p141,76););
printStats();
void* p172 = last_address;
PRINT_POINTER(scalloc(14,90););
printStats();
void* p173 = last_address;
PRINT_POINTER(scalloc(224,89););
printStats();
void* p174 = last_address;
PRINT_POINTER(scalloc(202,38););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p81););
printStats();
PRINT_POINTER(scalloc(43,35););
printStats();
void* p176 = last_address;
PRINT_POINTER(scalloc(211,70););
printStats();
void* p177 = last_address;
DEBUG_PRINT(sfree(p68););
printStats();
PRINT_POINTER(srealloc(p177,64););
printStats();
void* p178 = last_address;
PRINT_POINTER(srealloc(p66,242););
printStats();
void* p179 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p180 = last_address;
PRINT_POINTER(scalloc(247,158););
printStats();
void* p181 = last_address;
PRINT_POINTER(srealloc(p173,203););
printStats();
void* p182 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(35,101););
printStats();
void* p184 = last_address;
PRINT_POINTER(srealloc(p158,103););
printStats();
void* p185 = last_address;
PRINT_POINTER(scalloc(182,1););
printStats();
void* p186 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p187 = last_address;
PRINT_POINTER(srealloc(p159,197););
printStats();
void* p188 = last_address;
DEBUG_PRINT(sfree(p183););
printStats();
PRINT_POINTER(scalloc(159,203););
printStats();
void* p189 = last_address;
PRINT_POINTER(scalloc(31,115););
printStats();
void* p190 = last_address;
PRINT_POINTER(scalloc(119,190););
printStats();
void* p191 = last_address;
DEBUG_PRINT(sfree(p191););
printStats();
DEBUG_PRINT(sfree(p161););
printStats();
PRINT_POINTER(scalloc(54,129););
printStats();
void* p192 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p193 = last_address;
DEBUG_PRINT(sfree(p174););
printStats();
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(srealloc(p122,125););
printStats();
void* p194 = last_address;
PRINT_POINTER(srealloc(p168,215););
printStats();
void* p195 = last_address;
PRINT_POINTER(scalloc(97,12););
printStats();
void* p196 = last_address;
PRINT_POINTER(srealloc(p115,182););
printStats();
void* p197 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p198 = last_address;
DEBUG_PRINT(sfree(p185););
printStats();
PRINT_POINTER(smalloc(237););
printStats();
void* p199 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
DEBUG_PRINT(sfree(p182););
printStats();
PRINT_POINTER(scalloc(168,52););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p197,35););
printStats();
void* p201 = last_address;
PRINT_POINTER(srealloc(p165,217););
printStats();
void* p202 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p203 = last_address;
PRINT_POINTER(scalloc(33,144););
printStats();
void* p204 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
DEBUG_PRINT(sfree(p164););
printStats();
PRINT_POINTER(smalloc(93););
printStats();
void* p205 = last_address;
PRINT_POINTER(srealloc(p145,158););
printStats();
void* p206 = last_address;
DEBUG_PRINT(sfree(p132););
printStats();
PRINT_POINTER(smalloc(129););
printStats();
void* p207 = last_address;
PRINT_POINTER(scalloc(249,241););
printStats();
void* p208 = last_address;
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(smalloc(190););
printStats();
void* p209 = last_address;
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(scalloc(239,231););
printStats();
void* p210 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p211 = last_address;
PRINT_POINTER(srealloc(p198,21););
printStats();
void* p212 = last_address;
PRINT_POINTER(srealloc(p202,17););
printStats();
void* p213 = last_address;
PRINT_POINTER(scalloc(242,101););
printStats();
void* p214 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p215 = last_address;
DEBUG_PRINT(sfree(p179););
printStats();
PRINT_POINTER(smalloc(29););
printStats();
void* p216 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p217 = last_address;
PRINT_POINTER(scalloc(230,156););
printStats();
void* p218 = last_address;
PRINT_POINTER(scalloc(127,226););
printStats();
void* p219 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p220 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p221 = last_address;
DEBUG_PRINT(sfree(p220););
printStats();
PRINT_POINTER(scalloc(228,139););
printStats();
void* p222 = last_address;
DEBUG_PRINT(sfree(p192););
printStats();
PRINT_POINTER(smalloc(125););
printStats();
void* p223 = last_address;
PRINT_POINTER(srealloc(p96,103););
printStats();
void* p224 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
PRINT_POINTER(scalloc(147,222););
printStats();
void* p225 = last_address;
PRINT_POINTER(srealloc(p142,174););
printStats();
void* p226 = last_address;
DEBUG_PRINT(sfree(p206););
printStats();
DEBUG_PRINT(sfree(p219););
printStats();
}
