#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(183,228););
printStats();
void* p0 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(scalloc(109,82););
printStats();
void* p2 = last_address;
PRINT_POINTER(srealloc(p2,174););
printStats();
void* p3 = last_address;
PRINT_POINTER(scalloc(247,177););
printStats();
void* p4 = last_address;
PRINT_POINTER(srealloc(p1,49););
printStats();
void* p5 = last_address;
PRINT_POINTER(scalloc(207,207););
printStats();
void* p6 = last_address;
DEBUG_PRINT(sfree(p6););
printStats();
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(smalloc(134););
printStats();
void* p7 = last_address;
DEBUG_PRINT(sfree(p3););
printStats();
PRINT_POINTER(srealloc(p7,232););
printStats();
void* p8 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p9 = last_address;
PRINT_POINTER(scalloc(54,246););
printStats();
void* p10 = last_address;
PRINT_POINTER(srealloc(p9,36););
printStats();
void* p11 = last_address;
PRINT_POINTER(srealloc(p4,163););
printStats();
void* p12 = last_address;
PRINT_POINTER(srealloc(p12,10););
printStats();
void* p13 = last_address;
PRINT_POINTER(scalloc(148,46););
printStats();
void* p14 = last_address;
PRINT_POINTER(srealloc(p10,234););
printStats();
void* p15 = last_address;
PRINT_POINTER(srealloc(p13,29););
printStats();
void* p16 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(scalloc(167,177););
printStats();
void* p17 = last_address;
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(smalloc(145););
printStats();
void* p18 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p19 = last_address;
PRINT_POINTER(srealloc(p11,180););
printStats();
void* p20 = last_address;
PRINT_POINTER(scalloc(176,127););
printStats();
void* p21 = last_address;
PRINT_POINTER(srealloc(p16,25););
printStats();
void* p22 = last_address;
PRINT_POINTER(srealloc(p17,34););
printStats();
void* p23 = last_address;
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(srealloc(p23,193););
printStats();
void* p24 = last_address;
PRINT_POINTER(srealloc(p19,161););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(184,56););
printStats();
void* p26 = last_address;
PRINT_POINTER(scalloc(27,145););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p26););
printStats();
PRINT_POINTER(scalloc(101,23););
printStats();
void* p28 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p29 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p30 = last_address;
PRINT_POINTER(scalloc(218,172););
printStats();
void* p31 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p32 = last_address;
PRINT_POINTER(scalloc(96,84););
printStats();
void* p33 = last_address;
PRINT_POINTER(srealloc(p29,242););
printStats();
void* p34 = last_address;
PRINT_POINTER(srealloc(p15,19););
printStats();
void* p35 = last_address;
DEBUG_PRINT(sfree(p30););
printStats();
PRINT_POINTER(srealloc(p22,108););
printStats();
void* p36 = last_address;
PRINT_POINTER(scalloc(194,200););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(96,30););
printStats();
void* p38 = last_address;
PRINT_POINTER(srealloc(p37,239););
printStats();
void* p39 = last_address;
PRINT_POINTER(srealloc(p32,30););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p34,28););
printStats();
void* p41 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p42 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p43 = last_address;
PRINT_POINTER(srealloc(p31,230););
printStats();
void* p44 = last_address;
PRINT_POINTER(scalloc(176,172););
printStats();
void* p45 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p46 = last_address;
DEBUG_PRINT(sfree(p42););
printStats();
PRINT_POINTER(scalloc(213,131););
printStats();
void* p47 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
DEBUG_PRINT(sfree(p43););
printStats();
PRINT_POINTER(srealloc(p38,76););
printStats();
void* p48 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
PRINT_POINTER(scalloc(106,159););
printStats();
void* p49 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p50 = last_address;
PRINT_POINTER(scalloc(232,227););
printStats();
void* p51 = last_address;
DEBUG_PRINT(sfree(p49););
printStats();
PRINT_POINTER(scalloc(4,151););
printStats();
void* p52 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p53 = last_address;
PRINT_POINTER(scalloc(23,162););
printStats();
void* p54 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p55 = last_address;
DEBUG_PRINT(sfree(p27););
printStats();
PRINT_POINTER(srealloc(p52,244););
printStats();
void* p56 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p57 = last_address;
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(srealloc(p46,193););
printStats();
void* p58 = last_address;
PRINT_POINTER(srealloc(p44,244););
printStats();
void* p59 = last_address;
PRINT_POINTER(scalloc(190,173););
printStats();
void* p60 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p61 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p62 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(scalloc(126,71););
printStats();
void* p63 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p64 = last_address;
PRINT_POINTER(scalloc(140,220););
printStats();
void* p65 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p66 = last_address;
PRINT_POINTER(scalloc(71,206););
printStats();
void* p67 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(scalloc(4,20););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p51,78););
printStats();
void* p69 = last_address;
PRINT_POINTER(srealloc(p53,49););
printStats();
void* p70 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p71 = last_address;
PRINT_POINTER(srealloc(p55,131););
printStats();
void* p72 = last_address;
PRINT_POINTER(srealloc(p20,234););
printStats();
void* p73 = last_address;
PRINT_POINTER(scalloc(25,114););
printStats();
void* p74 = last_address;
PRINT_POINTER(scalloc(236,75););
printStats();
void* p75 = last_address;
PRINT_POINTER(srealloc(p75,238););
printStats();
void* p76 = last_address;
PRINT_POINTER(srealloc(p67,211););
printStats();
void* p77 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p78 = last_address;
PRINT_POINTER(srealloc(p77,164););
printStats();
void* p79 = last_address;
DEBUG_PRINT(sfree(p68););
printStats();
PRINT_POINTER(smalloc(90););
printStats();
void* p80 = last_address;
PRINT_POINTER(scalloc(46,172););
printStats();
void* p81 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p83 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(scalloc(133,196););
printStats();
void* p84 = last_address;
PRINT_POINTER(scalloc(0,180););
printStats();
void* p85 = last_address;
PRINT_POINTER(scalloc(141,97););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p65,137););
printStats();
void* p87 = last_address;
PRINT_POINTER(scalloc(164,246););
printStats();
void* p88 = last_address;
PRINT_POINTER(srealloc(p36,93););
printStats();
void* p89 = last_address;
PRINT_POINTER(scalloc(161,186););
printStats();
void* p90 = last_address;
PRINT_POINTER(srealloc(p84,1););
printStats();
void* p91 = last_address;
PRINT_POINTER(srealloc(p85,228););
printStats();
void* p92 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
DEBUG_PRINT(sfree(p58););
printStats();
PRINT_POINTER(scalloc(58,198););
printStats();
void* p93 = last_address;
PRINT_POINTER(scalloc(44,14););
printStats();
void* p94 = last_address;
PRINT_POINTER(srealloc(p81,236););
printStats();
void* p95 = last_address;
PRINT_POINTER(srealloc(p39,99););
printStats();
void* p96 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(srealloc(p86,150););
printStats();
void* p97 = last_address;
DEBUG_PRINT(sfree(p82););
printStats();
DEBUG_PRINT(sfree(p47););
printStats();
PRINT_POINTER(scalloc(153,176););
printStats();
void* p98 = last_address;
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(smalloc(202););
printStats();
void* p99 = last_address;
PRINT_POINTER(srealloc(p59,132););
printStats();
void* p100 = last_address;
PRINT_POINTER(scalloc(53,79););
printStats();
void* p101 = last_address;
PRINT_POINTER(srealloc(p69,201););
printStats();
void* p102 = last_address;
PRINT_POINTER(scalloc(96,170););
printStats();
void* p103 = last_address;
PRINT_POINTER(scalloc(5,163););
printStats();
void* p104 = last_address;
PRINT_POINTER(scalloc(211,127););
printStats();
void* p105 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(scalloc(15,183););
printStats();
void* p106 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(scalloc(30,93););
printStats();
void* p107 = last_address;
PRINT_POINTER(srealloc(p79,69););
printStats();
void* p108 = last_address;
DEBUG_PRINT(sfree(p87););
printStats();
PRINT_POINTER(smalloc(13););
printStats();
void* p109 = last_address;
DEBUG_PRINT(sfree(p104););
printStats();
PRINT_POINTER(srealloc(p64,123););
printStats();
void* p110 = last_address;
PRINT_POINTER(scalloc(42,224););
printStats();
void* p111 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p112 = last_address;
DEBUG_PRINT(sfree(p92););
printStats();
PRINT_POINTER(smalloc(190););
printStats();
void* p113 = last_address;
PRINT_POINTER(scalloc(215,67););
printStats();
void* p114 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p115 = last_address;
PRINT_POINTER(scalloc(128,122););
printStats();
void* p116 = last_address;
PRINT_POINTER(srealloc(p109,209););
printStats();
void* p117 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p118 = last_address;
PRINT_POINTER(srealloc(p74,47););
printStats();
void* p119 = last_address;
PRINT_POINTER(scalloc(40,65););
printStats();
void* p120 = last_address;
DEBUG_PRINT(sfree(p111););
printStats();
PRINT_POINTER(scalloc(77,57););
printStats();
void* p121 = last_address;
PRINT_POINTER(scalloc(102,54););
printStats();
void* p122 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p123 = last_address;
PRINT_POINTER(scalloc(161,210););
printStats();
void* p124 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p125 = last_address;
PRINT_POINTER(scalloc(152,2););
printStats();
void* p126 = last_address;
DEBUG_PRINT(sfree(p61););
printStats();
PRINT_POINTER(srealloc(p101,94););
printStats();
void* p127 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p128 = last_address;
PRINT_POINTER(scalloc(73,32););
printStats();
void* p129 = last_address;
PRINT_POINTER(srealloc(p105,235););
printStats();
void* p130 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p131 = last_address;
PRINT_POINTER(scalloc(31,244););
printStats();
void* p132 = last_address;
DEBUG_PRINT(sfree(p107););
printStats();
PRINT_POINTER(smalloc(189););
printStats();
void* p133 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
PRINT_POINTER(scalloc(221,95););
printStats();
void* p134 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p135 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p136 = last_address;
PRINT_POINTER(scalloc(181,44););
printStats();
void* p137 = last_address;
PRINT_POINTER(srealloc(p35,136););
printStats();
void* p138 = last_address;
PRINT_POINTER(scalloc(102,64););
printStats();
void* p139 = last_address;
PRINT_POINTER(srealloc(p127,245););
printStats();
void* p140 = last_address;
PRINT_POINTER(scalloc(179,150););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p66,208););
printStats();
void* p142 = last_address;
PRINT_POINTER(srealloc(p137,158););
printStats();
void* p143 = last_address;
PRINT_POINTER(srealloc(p54,242););
printStats();
void* p144 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p145 = last_address;
PRINT_POINTER(srealloc(p80,122););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
PRINT_POINTER(scalloc(30,120););
printStats();
void* p147 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p148 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
DEBUG_PRINT(sfree(p131););
printStats();
PRINT_POINTER(srealloc(p120,137););
printStats();
void* p149 = last_address;
DEBUG_PRINT(sfree(p93););
printStats();
DEBUG_PRINT(sfree(p130););
printStats();
PRINT_POINTER(scalloc(187,57););
printStats();
void* p150 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p151 = last_address;
PRINT_POINTER(scalloc(66,3););
printStats();
void* p152 = last_address;
PRINT_POINTER(srealloc(p132,51););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(210,8););
printStats();
void* p154 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p155 = last_address;
PRINT_POINTER(scalloc(20,85););
printStats();
void* p156 = last_address;
DEBUG_PRINT(sfree(p144););
printStats();
PRINT_POINTER(scalloc(191,223););
printStats();
void* p157 = last_address;
PRINT_POINTER(srealloc(p48,213););
printStats();
void* p158 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p159 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p160 = last_address;
PRINT_POINTER(srealloc(p106,122););
printStats();
void* p161 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p162 = last_address;
PRINT_POINTER(scalloc(148,42););
printStats();
void* p163 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p164 = last_address;
PRINT_POINTER(scalloc(146,42););
printStats();
void* p165 = last_address;
PRINT_POINTER(srealloc(p63,237););
printStats();
void* p166 = last_address;
PRINT_POINTER(srealloc(p124,162););
printStats();
void* p167 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p168 = last_address;
DEBUG_PRINT(sfree(p163););
printStats();
DEBUG_PRINT(sfree(p28););
printStats();
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(srealloc(p110,141););
printStats();
void* p169 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p170 = last_address;
PRINT_POINTER(srealloc(p139,121););
printStats();
void* p171 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p172 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p173 = last_address;
PRINT_POINTER(srealloc(p161,227););
printStats();
void* p174 = last_address;
PRINT_POINTER(scalloc(249,81););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p145););
printStats();
PRINT_POINTER(scalloc(132,22););
printStats();
void* p176 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p177 = last_address;
PRINT_POINTER(scalloc(233,61););
printStats();
void* p178 = last_address;
DEBUG_PRINT(sfree(p128););
printStats();
PRINT_POINTER(srealloc(p56,114););
printStats();
void* p179 = last_address;
DEBUG_PRINT(sfree(p177););
printStats();
DEBUG_PRINT(sfree(p135););
printStats();
DEBUG_PRINT(sfree(p141););
printStats();
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(smalloc(238););
printStats();
void* p180 = last_address;
PRINT_POINTER(srealloc(p156,166););
printStats();
void* p181 = last_address;
DEBUG_PRINT(sfree(p112););
printStats();
DEBUG_PRINT(sfree(p149););
printStats();
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(smalloc(96););
printStats();
void* p182 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p183 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p184 = last_address;
PRINT_POINTER(scalloc(132,166););
printStats();
void* p185 = last_address;
PRINT_POINTER(scalloc(168,175););
printStats();
void* p186 = last_address;
DEBUG_PRINT(sfree(p185););
printStats();
PRINT_POINTER(scalloc(183,217););
printStats();
void* p187 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p188 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p189 = last_address;
DEBUG_PRINT(sfree(p188););
printStats();
PRINT_POINTER(scalloc(144,122););
printStats();
void* p190 = last_address;
PRINT_POINTER(scalloc(20,107););
printStats();
void* p191 = last_address;
PRINT_POINTER(srealloc(p117,54););
printStats();
void* p192 = last_address;
PRINT_POINTER(scalloc(5,225););
printStats();
void* p193 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p194 = last_address;
DEBUG_PRINT(sfree(p165););
printStats();
PRINT_POINTER(smalloc(123););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(scalloc(98,62););
printStats();
void* p196 = last_address;
DEBUG_PRINT(sfree(p171););
printStats();
PRINT_POINTER(scalloc(63,105););
printStats();
void* p197 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(srealloc(p178,54););
printStats();
void* p198 = last_address;
PRINT_POINTER(scalloc(183,130););
printStats();
void* p199 = last_address;
PRINT_POINTER(srealloc(p193,56););
printStats();
void* p200 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p201 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p202 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p203 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p204 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(scalloc(197,175););
printStats();
void* p205 = last_address;
DEBUG_PRINT(sfree(p164););
printStats();
PRINT_POINTER(srealloc(p195,81););
printStats();
void* p206 = last_address;
PRINT_POINTER(srealloc(p186,188););
printStats();
void* p207 = last_address;
PRINT_POINTER(smalloc(55););
printStats();
void* p208 = last_address;
PRINT_POINTER(scalloc(118,190););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(170,165););
printStats();
void* p210 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p211 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(scalloc(221,74););
printStats();
void* p212 = last_address;
PRINT_POINTER(scalloc(234,11););
printStats();
void* p213 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p214 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p215 = last_address;
PRINT_POINTER(scalloc(125,238););
printStats();
void* p216 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p217 = last_address;
PRINT_POINTER(srealloc(p194,216););
printStats();
void* p218 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p219 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p220 = last_address;
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(srealloc(p219,111););
printStats();
void* p221 = last_address;
PRINT_POINTER(scalloc(99,151););
printStats();
void* p222 = last_address;
PRINT_POINTER(srealloc(p184,121););
printStats();
void* p223 = last_address;
PRINT_POINTER(srealloc(p155,233););
printStats();
void* p224 = last_address;
PRINT_POINTER(scalloc(95,232););
printStats();
void* p225 = last_address;
PRINT_POINTER(scalloc(137,39););
printStats();
void* p226 = last_address;
PRINT_POINTER(srealloc(p200,200););
printStats();
void* p227 = last_address;
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(srealloc(p138,10););
printStats();
void* p228 = last_address;
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(smalloc(210););
printStats();
void* p229 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p230 = last_address;
DEBUG_PRINT(sfree(p169););
printStats();
PRINT_POINTER(srealloc(p226,149););
printStats();
void* p231 = last_address;
PRINT_POINTER(srealloc(p121,114););
printStats();
void* p232 = last_address;
DEBUG_PRINT(sfree(p208););
printStats();
PRINT_POINTER(smalloc(78););
printStats();
void* p233 = last_address;
PRINT_POINTER(srealloc(p62,90););
printStats();
void* p234 = last_address;
PRINT_POINTER(scalloc(233,228););
printStats();
void* p235 = last_address;
PRINT_POINTER(srealloc(p233,196););
printStats();
void* p236 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p237 = last_address;
DEBUG_PRINT(sfree(p172););
printStats();
PRINT_POINTER(srealloc(p108,89););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p146,129););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p201,161););
printStats();
void* p240 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
PRINT_POINTER(srealloc(p238,170););
printStats();
void* p241 = last_address;
DEBUG_PRINT(sfree(p235););
printStats();
PRINT_POINTER(smalloc(229););
printStats();
void* p242 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p243 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p244 = last_address;
PRINT_POINTER(scalloc(169,140););
printStats();
void* p245 = last_address;
PRINT_POINTER(scalloc(57,79););
printStats();
void* p246 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p247 = last_address;
DEBUG_PRINT(sfree(p182););
printStats();
DEBUG_PRINT(sfree(p183););
printStats();
DEBUG_PRINT(sfree(p174););
printStats();
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(srealloc(p129,92););
printStats();
void* p248 = last_address;
PRINT_POINTER(srealloc(p244,9););
printStats();
void* p249 = last_address;
PRINT_POINTER(srealloc(p207,239););
printStats();
void* p250 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p251 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p252 = last_address;
PRINT_POINTER(scalloc(237,222););
printStats();
void* p253 = last_address;
PRINT_POINTER(scalloc(143,217););
printStats();
void* p254 = last_address;
PRINT_POINTER(srealloc(p99,228););
printStats();
void* p255 = last_address;
PRINT_POINTER(scalloc(81,147););
printStats();
void* p256 = last_address;
PRINT_POINTER(srealloc(p126,74););
printStats();
void* p257 = last_address;
DEBUG_PRINT(sfree(p192););
printStats();
DEBUG_PRINT(sfree(p191););
printStats();
PRINT_POINTER(smalloc(113););
printStats();
void* p258 = last_address;
PRINT_POINTER(scalloc(203,124););
printStats();
void* p259 = last_address;
PRINT_POINTER(srealloc(p125,65););
printStats();
void* p260 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p261 = last_address;
PRINT_POINTER(scalloc(249,180););
printStats();
void* p262 = last_address;
DEBUG_PRINT(sfree(p190););
printStats();
PRINT_POINTER(scalloc(135,1););
printStats();
void* p263 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p264 = last_address;
PRINT_POINTER(srealloc(p133,163););
printStats();
void* p265 = last_address;
PRINT_POINTER(srealloc(p261,11););
printStats();
void* p266 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p267 = last_address;
DEBUG_PRINT(sfree(p157););
printStats();
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(scalloc(30,244););
printStats();
void* p268 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p269 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p270 = last_address;
PRINT_POINTER(srealloc(p181,151););
printStats();
void* p271 = last_address;
PRINT_POINTER(srealloc(p136,120););
printStats();
void* p272 = last_address;
PRINT_POINTER(scalloc(151,150););
printStats();
void* p273 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p274 = last_address;
DEBUG_PRINT(sfree(p256););
printStats();
PRINT_POINTER(smalloc(120););
printStats();
void* p275 = last_address;
DEBUG_PRINT(sfree(p263););
printStats();
DEBUG_PRINT(sfree(p251););
printStats();
DEBUG_PRINT(sfree(p206););
printStats();
PRINT_POINTER(scalloc(220,107););
printStats();
void* p276 = last_address;
DEBUG_PRINT(sfree(p103););
printStats();
DEBUG_PRINT(sfree(p224););
printStats();
PRINT_POINTER(srealloc(p71,86););
printStats();
void* p277 = last_address;
PRINT_POINTER(srealloc(p198,153););
printStats();
void* p278 = last_address;
PRINT_POINTER(srealloc(p271,243););
printStats();
void* p279 = last_address;
PRINT_POINTER(srealloc(p212,30););
printStats();
void* p280 = last_address;
PRINT_POINTER(srealloc(p210,123););
printStats();
void* p281 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p282 = last_address;
PRINT_POINTER(srealloc(p280,59););
printStats();
void* p283 = last_address;
DEBUG_PRINT(sfree(p153););
printStats();
PRINT_POINTER(smalloc(75););
printStats();
void* p284 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p285 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(srealloc(p140,184););
printStats();
void* p286 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p287 = last_address;
PRINT_POINTER(srealloc(p57,147););
printStats();
void* p288 = last_address;
DEBUG_PRINT(sfree(p96););
printStats();
PRINT_POINTER(scalloc(53,182););
printStats();
void* p289 = last_address;
PRINT_POINTER(srealloc(p282,63););
printStats();
void* p290 = last_address;
PRINT_POINTER(scalloc(168,48););
printStats();
void* p291 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p292 = last_address;
DEBUG_PRINT(sfree(p189););
printStats();
PRINT_POINTER(scalloc(40,178););
printStats();
void* p293 = last_address;
PRINT_POINTER(srealloc(p213,226););
printStats();
void* p294 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p295 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p296 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p297 = last_address;
DEBUG_PRINT(sfree(p285););
printStats();
PRINT_POINTER(scalloc(147,236););
printStats();
void* p298 = last_address;
PRINT_POINTER(scalloc(226,67););
printStats();
void* p299 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p300 = last_address;
DEBUG_PRINT(sfree(p237););
printStats();
PRINT_POINTER(scalloc(75,212););
printStats();
void* p301 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
PRINT_POINTER(smalloc(232););
printStats();
void* p302 = last_address;
PRINT_POINTER(scalloc(184,217););
printStats();
void* p303 = last_address;
PRINT_POINTER(scalloc(223,204););
printStats();
void* p304 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p305 = last_address;
PRINT_POINTER(srealloc(p281,137););
printStats();
void* p306 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p307 = last_address;
PRINT_POINTER(srealloc(p134,31););
printStats();
void* p308 = last_address;
PRINT_POINTER(scalloc(233,20););
printStats();
void* p309 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p310 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p311 = last_address;
PRINT_POINTER(scalloc(36,101););
printStats();
void* p312 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p313 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p314 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p315 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p316 = last_address;
DEBUG_PRINT(sfree(p275););
printStats();
DEBUG_PRINT(sfree(p240););
printStats();
PRINT_POINTER(srealloc(p290,208););
printStats();
void* p317 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(scalloc(121,234););
printStats();
void* p318 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p319 = last_address;
PRINT_POINTER(scalloc(43,119););
printStats();
void* p320 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p321 = last_address;
DEBUG_PRINT(sfree(p227););
printStats();
PRINT_POINTER(scalloc(59,149););
printStats();
void* p322 = last_address;
PRINT_POINTER(scalloc(122,151););
printStats();
void* p323 = last_address;
DEBUG_PRINT(sfree(p260););
printStats();
PRINT_POINTER(srealloc(p288,104););
printStats();
void* p324 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p325 = last_address;
PRINT_POINTER(srealloc(p245,50););
printStats();
void* p326 = last_address;
DEBUG_PRINT(sfree(p242););
printStats();
PRINT_POINTER(scalloc(103,191););
printStats();
void* p327 = last_address;
DEBUG_PRINT(sfree(p83););
printStats();
DEBUG_PRINT(sfree(p168););
printStats();
PRINT_POINTER(smalloc(59););
printStats();
void* p328 = last_address;
DEBUG_PRINT(sfree(p316););
printStats();
PRINT_POINTER(srealloc(p100,201););
printStats();
void* p329 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p330 = last_address;
PRINT_POINTER(scalloc(111,81););
printStats();
void* p331 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p332 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p333 = last_address;
PRINT_POINTER(scalloc(149,189););
printStats();
void* p334 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p335 = last_address;
PRINT_POINTER(scalloc(65,204););
printStats();
void* p336 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
PRINT_POINTER(srealloc(p78,105););
printStats();
void* p337 = last_address;
PRINT_POINTER(srealloc(p273,52););
printStats();
void* p338 = last_address;
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(scalloc(91,239););
printStats();
void* p339 = last_address;
PRINT_POINTER(srealloc(p95,163););
printStats();
void* p340 = last_address;
PRINT_POINTER(srealloc(p338,102););
printStats();
void* p341 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p342 = last_address;
DEBUG_PRINT(sfree(p309););
printStats();
PRINT_POINTER(scalloc(35,120););
printStats();
void* p343 = last_address;
PRINT_POINTER(srealloc(p202,67););
printStats();
void* p344 = last_address;
PRINT_POINTER(srealloc(p259,190););
printStats();
void* p345 = last_address;
DEBUG_PRINT(sfree(p160););
printStats();
DEBUG_PRINT(sfree(p88););
printStats();
PRINT_POINTER(scalloc(196,195););
printStats();
void* p346 = last_address;
DEBUG_PRINT(sfree(p336););
printStats();
PRINT_POINTER(smalloc(128););
printStats();
void* p347 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p348 = last_address;
DEBUG_PRINT(sfree(p345););
printStats();
PRINT_POINTER(srealloc(p284,26););
printStats();
void* p349 = last_address;
PRINT_POINTER(scalloc(192,3););
printStats();
void* p350 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p351 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p352 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p353 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(scalloc(235,22););
printStats();
void* p354 = last_address;
PRINT_POINTER(srealloc(p289,98););
printStats();
void* p355 = last_address;
DEBUG_PRINT(sfree(p318););
printStats();
PRINT_POINTER(smalloc(48););
printStats();
void* p356 = last_address;
DEBUG_PRINT(sfree(p214););
printStats();
PRINT_POINTER(srealloc(p241,191););
printStats();
void* p357 = last_address;
PRINT_POINTER(scalloc(165,175););
printStats();
void* p358 = last_address;
PRINT_POINTER(scalloc(127,231););
printStats();
void* p359 = last_address;
PRINT_POINTER(srealloc(p197,66););
printStats();
void* p360 = last_address;
PRINT_POINTER(srealloc(p324,237););
printStats();
void* p361 = last_address;
PRINT_POINTER(scalloc(207,53););
printStats();
void* p362 = last_address;
PRINT_POINTER(scalloc(227,209););
printStats();
void* p363 = last_address;
PRINT_POINTER(srealloc(p301,73););
printStats();
void* p364 = last_address;
PRINT_POINTER(scalloc(115,41););
printStats();
void* p365 = last_address;
PRINT_POINTER(scalloc(36,214););
printStats();
void* p366 = last_address;
PRINT_POINTER(srealloc(p355,157););
printStats();
void* p367 = last_address;
PRINT_POINTER(srealloc(p266,177););
printStats();
void* p368 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p369 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p370 = last_address;
PRINT_POINTER(srealloc(p276,37););
printStats();
void* p371 = last_address;
PRINT_POINTER(srealloc(p339,205););
printStats();
void* p372 = last_address;
DEBUG_PRINT(sfree(p343););
printStats();
PRINT_POINTER(scalloc(128,226););
printStats();
void* p373 = last_address;
DEBUG_PRINT(sfree(p363););
printStats();
DEBUG_PRINT(sfree(p257););
printStats();
DEBUG_PRINT(sfree(p331););
printStats();
PRINT_POINTER(scalloc(233,49););
printStats();
void* p374 = last_address;
PRINT_POINTER(srealloc(p365,91););
printStats();
void* p375 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p376 = last_address;
PRINT_POINTER(scalloc(159,27););
printStats();
void* p377 = last_address;
PRINT_POINTER(scalloc(59,66););
printStats();
void* p378 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p379 = last_address;
DEBUG_PRINT(sfree(p264););
printStats();
PRINT_POINTER(scalloc(144,224););
printStats();
void* p380 = last_address;
PRINT_POINTER(srealloc(p314,128););
printStats();
void* p381 = last_address;
PRINT_POINTER(scalloc(240,157););
printStats();
void* p382 = last_address;
DEBUG_PRINT(sfree(p335););
printStats();
DEBUG_PRINT(sfree(p334););
printStats();
PRINT_POINTER(smalloc(129););
printStats();
void* p383 = last_address;
DEBUG_PRINT(sfree(p308););
printStats();
DEBUG_PRINT(sfree(p376););
printStats();
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(smalloc(20););
printStats();
void* p384 = last_address;
PRINT_POINTER(srealloc(p299,45););
printStats();
void* p385 = last_address;
DEBUG_PRINT(sfree(p287););
printStats();
PRINT_POINTER(smalloc(61););
printStats();
void* p386 = last_address;
DEBUG_PRINT(sfree(p347););
printStats();
PRINT_POINTER(smalloc(135););
printStats();
void* p387 = last_address;
DEBUG_PRINT(sfree(p248););
printStats();
DEBUG_PRINT(sfree(p381););
printStats();
PRINT_POINTER(scalloc(171,41););
printStats();
void* p388 = last_address;
DEBUG_PRINT(sfree(p346););
printStats();
PRINT_POINTER(smalloc(104););
printStats();
void* p389 = last_address;
PRINT_POINTER(scalloc(231,225););
printStats();
void* p390 = last_address;
DEBUG_PRINT(sfree(p234););
printStats();
PRINT_POINTER(srealloc(p247,29););
printStats();
void* p391 = last_address;
DEBUG_PRINT(sfree(p356););
printStats();
PRINT_POINTER(scalloc(123,86););
printStats();
void* p392 = last_address;
DEBUG_PRINT(sfree(p283););
printStats();
PRINT_POINTER(srealloc(p379,189););
printStats();
void* p393 = last_address;
PRINT_POINTER(scalloc(35,243););
printStats();
void* p394 = last_address;
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(scalloc(51,34););
printStats();
void* p395 = last_address;
PRINT_POINTER(srealloc(p298,65););
printStats();
void* p396 = last_address;
DEBUG_PRINT(sfree(p330););
printStats();
PRINT_POINTER(scalloc(241,33););
printStats();
void* p397 = last_address;
PRINT_POINTER(scalloc(63,233););
printStats();
void* p398 = last_address;
PRINT_POINTER(srealloc(p391,138););
printStats();
void* p399 = last_address;
PRINT_POINTER(srealloc(p329,77););
printStats();
void* p400 = last_address;
DEBUG_PRINT(sfree(p327););
printStats();
DEBUG_PRINT(sfree(p303););
printStats();
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(smalloc(64););
printStats();
void* p401 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p402 = last_address;
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(scalloc(188,162););
printStats();
void* p403 = last_address;
PRINT_POINTER(srealloc(p167,17););
printStats();
void* p404 = last_address;
DEBUG_PRINT(sfree(p383););
printStats();
PRINT_POINTER(smalloc(33););
printStats();
void* p405 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p406 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p407 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p408 = last_address;
PRINT_POINTER(scalloc(203,207););
printStats();
void* p409 = last_address;
PRINT_POINTER(srealloc(p269,135););
printStats();
void* p410 = last_address;
PRINT_POINTER(scalloc(160,97););
printStats();
void* p411 = last_address;
PRINT_POINTER(srealloc(p354,141););
printStats();
void* p412 = last_address;
PRINT_POINTER(scalloc(132,105););
printStats();
void* p413 = last_address;
DEBUG_PRINT(sfree(p412););
printStats();
PRINT_POINTER(srealloc(p390,124););
printStats();
void* p414 = last_address;
PRINT_POINTER(scalloc(3,204););
printStats();
void* p415 = last_address;
PRINT_POINTER(scalloc(172,191););
printStats();
void* p416 = last_address;
PRINT_POINTER(scalloc(159,149););
printStats();
void* p417 = last_address;
PRINT_POINTER(scalloc(68,55););
printStats();
void* p418 = last_address;
PRINT_POINTER(srealloc(p249,244););
printStats();
void* p419 = last_address;
PRINT_POINTER(scalloc(130,86););
printStats();
void* p420 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p421 = last_address;
PRINT_POINTER(scalloc(1,56););
printStats();
void* p422 = last_address;
PRINT_POINTER(scalloc(100,64););
printStats();
void* p423 = last_address;
PRINT_POINTER(srealloc(p325,177););
printStats();
void* p424 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p425 = last_address;
PRINT_POINTER(srealloc(p407,167););
printStats();
void* p426 = last_address;
PRINT_POINTER(scalloc(66,249););
printStats();
void* p427 = last_address;
PRINT_POINTER(scalloc(234,146););
printStats();
void* p428 = last_address;
PRINT_POINTER(scalloc(189,11););
printStats();
void* p429 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p430 = last_address;
PRINT_POINTER(scalloc(208,247););
printStats();
void* p431 = last_address;
PRINT_POINTER(srealloc(p94,114););
printStats();
void* p432 = last_address;
PRINT_POINTER(srealloc(p359,246););
printStats();
void* p433 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p434 = last_address;
DEBUG_PRINT(sfree(p291););
printStats();
PRINT_POINTER(smalloc(107););
printStats();
void* p435 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p436 = last_address;
DEBUG_PRINT(sfree(p353););
printStats();
PRINT_POINTER(srealloc(p396,83););
printStats();
void* p437 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p438 = last_address;
PRINT_POINTER(srealloc(p306,44););
printStats();
void* p439 = last_address;
PRINT_POINTER(scalloc(127,146););
printStats();
void* p440 = last_address;
PRINT_POINTER(srealloc(p435,29););
printStats();
void* p441 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p442 = last_address;
PRINT_POINTER(scalloc(152,239););
printStats();
void* p443 = last_address;
PRINT_POINTER(srealloc(p362,223););
printStats();
void* p444 = last_address;
DEBUG_PRINT(sfree(p428););
printStats();
PRINT_POINTER(srealloc(p228,119););
printStats();
void* p445 = last_address;
PRINT_POINTER(srealloc(p258,127););
printStats();
void* p446 = last_address;
PRINT_POINTER(scalloc(131,208););
printStats();
void* p447 = last_address;
PRINT_POINTER(scalloc(90,155););
printStats();
void* p448 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p449 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p450 = last_address;
PRINT_POINTER(srealloc(p270,59););
printStats();
void* p451 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p452 = last_address;
PRINT_POINTER(srealloc(p293,167););
printStats();
void* p453 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p454 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p455 = last_address;
DEBUG_PRINT(sfree(p254););
printStats();
DEBUG_PRINT(sfree(p430););
printStats();
DEBUG_PRINT(sfree(p333););
printStats();
PRINT_POINTER(srealloc(p387,58););
printStats();
void* p456 = last_address;
PRINT_POINTER(srealloc(p444,224););
printStats();
void* p457 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p458 = last_address;
DEBUG_PRINT(sfree(p351););
printStats();
DEBUG_PRINT(sfree(p349););
printStats();
DEBUG_PRINT(sfree(p395););
printStats();
PRINT_POINTER(scalloc(30,14););
printStats();
void* p459 = last_address;
PRINT_POINTER(scalloc(163,208););
printStats();
void* p460 = last_address;
PRINT_POINTER(srealloc(p458,216););
printStats();
void* p461 = last_address;
DEBUG_PRINT(sfree(p322););
printStats();
PRINT_POINTER(smalloc(125););
printStats();
void* p462 = last_address;
DEBUG_PRINT(sfree(p414););
printStats();
PRINT_POINTER(srealloc(p357,128););
printStats();
void* p463 = last_address;
DEBUG_PRINT(sfree(p403););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p464 = last_address;
PRINT_POINTER(srealloc(p443,89););
printStats();
void* p465 = last_address;
PRINT_POINTER(scalloc(249,83););
printStats();
void* p466 = last_address;
}
