#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(51););
printStats();
void* p0 = last_address;
PRINT_POINTER(srealloc(p0,139););
printStats();
void* p1 = last_address;
PRINT_POINTER(scalloc(65,206););
printStats();
void* p2 = last_address;
PRINT_POINTER(scalloc(51,140););
printStats();
void* p3 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(smalloc(149););
printStats();
void* p4 = last_address;
PRINT_POINTER(scalloc(37,29););
printStats();
void* p5 = last_address;
PRINT_POINTER(scalloc(39,74););
printStats();
void* p6 = last_address;
PRINT_POINTER(srealloc(p3,28););
printStats();
void* p7 = last_address;
PRINT_POINTER(srealloc(p7,167););
printStats();
void* p8 = last_address;
PRINT_POINTER(srealloc(p2,235););
printStats();
void* p9 = last_address;
PRINT_POINTER(scalloc(55,6););
printStats();
void* p10 = last_address;
DEBUG_PRINT(sfree(p10););
printStats();
PRINT_POINTER(scalloc(106,193););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(238,214););
printStats();
void* p12 = last_address;
PRINT_POINTER(srealloc(p8,209););
printStats();
void* p13 = last_address;
PRINT_POINTER(scalloc(41,24););
printStats();
void* p14 = last_address;
PRINT_POINTER(srealloc(p4,91););
printStats();
void* p15 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p16 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p17 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p18 = last_address;
DEBUG_PRINT(sfree(p14););
printStats();
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(srealloc(p13,175););
printStats();
void* p19 = last_address;
PRINT_POINTER(scalloc(206,85););
printStats();
void* p20 = last_address;
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(smalloc(66););
printStats();
void* p21 = last_address;
DEBUG_PRINT(sfree(p12););
printStats();
PRINT_POINTER(srealloc(p15,75););
printStats();
void* p22 = last_address;
PRINT_POINTER(srealloc(p5,99););
printStats();
void* p23 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(srealloc(p9,150););
printStats();
void* p24 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(srealloc(p23,44););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(200,206););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p20,64););
printStats();
void* p27 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p28 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p29 = last_address;
PRINT_POINTER(scalloc(228,92););
printStats();
void* p30 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(srealloc(p19,141););
printStats();
void* p31 = last_address;
PRINT_POINTER(srealloc(p27,205););
printStats();
void* p32 = last_address;
PRINT_POINTER(srealloc(p32,132););
printStats();
void* p33 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
DEBUG_PRINT(sfree(p31););
printStats();
PRINT_POINTER(smalloc(80););
printStats();
void* p34 = last_address;
PRINT_POINTER(scalloc(11,227););
printStats();
void* p35 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p36 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p37 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p38 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
DEBUG_PRINT(sfree(p11););
printStats();
DEBUG_PRINT(sfree(p36););
printStats();
DEBUG_PRINT(sfree(p26););
printStats();
DEBUG_PRINT(sfree(p25););
printStats();
PRINT_POINTER(scalloc(93,32););
printStats();
void* p39 = last_address;
PRINT_POINTER(srealloc(p38,245););
printStats();
void* p40 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p41 = last_address;
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(smalloc(68););
printStats();
void* p42 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p43 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(scalloc(220,55););
printStats();
void* p44 = last_address;
PRINT_POINTER(scalloc(167,164););
printStats();
void* p45 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p46 = last_address;
PRINT_POINTER(srealloc(p35,247););
printStats();
void* p47 = last_address;
PRINT_POINTER(srealloc(p30,205););
printStats();
void* p48 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p49 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
PRINT_POINTER(srealloc(p49,88););
printStats();
void* p50 = last_address;
PRINT_POINTER(srealloc(p39,47););
printStats();
void* p51 = last_address;
PRINT_POINTER(scalloc(85,50););
printStats();
void* p52 = last_address;
DEBUG_PRINT(sfree(p44););
printStats();
PRINT_POINTER(srealloc(p42,6););
printStats();
void* p53 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p54 = last_address;
PRINT_POINTER(scalloc(233,36););
printStats();
void* p55 = last_address;
PRINT_POINTER(scalloc(130,208););
printStats();
void* p56 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p57 = last_address;
DEBUG_PRINT(sfree(p51););
printStats();
DEBUG_PRINT(sfree(p53););
printStats();
PRINT_POINTER(srealloc(p57,18););
printStats();
void* p58 = last_address;
PRINT_POINTER(scalloc(78,97););
printStats();
void* p59 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p60 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p61 = last_address;
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(smalloc(82););
printStats();
void* p62 = last_address;
PRINT_POINTER(scalloc(86,129););
printStats();
void* p63 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p64 = last_address;
DEBUG_PRINT(sfree(p54););
printStats();
PRINT_POINTER(srealloc(p52,62););
printStats();
void* p65 = last_address;
PRINT_POINTER(scalloc(116,47););
printStats();
void* p66 = last_address;
DEBUG_PRINT(sfree(p61););
printStats();
PRINT_POINTER(smalloc(183););
printStats();
void* p67 = last_address;
PRINT_POINTER(srealloc(p45,153););
printStats();
void* p68 = last_address;
DEBUG_PRINT(sfree(p47););
printStats();
PRINT_POINTER(srealloc(p68,94););
printStats();
void* p69 = last_address;
DEBUG_PRINT(sfree(p67););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p70 = last_address;
PRINT_POINTER(srealloc(p48,28););
printStats();
void* p71 = last_address;
PRINT_POINTER(scalloc(48,94););
printStats();
void* p72 = last_address;
DEBUG_PRINT(sfree(p63););
printStats();
DEBUG_PRINT(sfree(p65););
printStats();
PRINT_POINTER(smalloc(63););
printStats();
void* p73 = last_address;
DEBUG_PRINT(sfree(p62););
printStats();
DEBUG_PRINT(sfree(p40););
printStats();
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(scalloc(81,212););
printStats();
void* p74 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p75 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(srealloc(p56,159););
printStats();
void* p76 = last_address;
PRINT_POINTER(srealloc(p71,0););
printStats();
void* p77 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p78 = last_address;
PRINT_POINTER(scalloc(208,18););
printStats();
void* p79 = last_address;
PRINT_POINTER(scalloc(243,249););
printStats();
void* p80 = last_address;
PRINT_POINTER(scalloc(202,153););
printStats();
void* p81 = last_address;
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(smalloc(89););
printStats();
void* p82 = last_address;
DEBUG_PRINT(sfree(p75););
printStats();
DEBUG_PRINT(sfree(p81););
printStats();
PRINT_POINTER(srealloc(p74,157););
printStats();
void* p83 = last_address;
PRINT_POINTER(srealloc(p70,137););
printStats();
void* p84 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(smalloc(154););
printStats();
void* p85 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p86 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p87 = last_address;
PRINT_POINTER(srealloc(p87,214););
printStats();
void* p88 = last_address;
PRINT_POINTER(scalloc(182,187););
printStats();
void* p89 = last_address;
PRINT_POINTER(srealloc(p86,50););
printStats();
void* p90 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
PRINT_POINTER(smalloc(27););
printStats();
void* p91 = last_address;
PRINT_POINTER(scalloc(165,9););
printStats();
void* p92 = last_address;
PRINT_POINTER(srealloc(p82,187););
printStats();
void* p93 = last_address;
PRINT_POINTER(srealloc(p55,77););
printStats();
void* p94 = last_address;
PRINT_POINTER(scalloc(168,230););
printStats();
void* p95 = last_address;
PRINT_POINTER(scalloc(30,10););
printStats();
void* p96 = last_address;
DEBUG_PRINT(sfree(p76););
printStats();
PRINT_POINTER(scalloc(137,132););
printStats();
void* p97 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(smalloc(124););
printStats();
void* p98 = last_address;
PRINT_POINTER(scalloc(228,33););
printStats();
void* p99 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p100 = last_address;
PRINT_POINTER(scalloc(206,51););
printStats();
void* p101 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p102 = last_address;
PRINT_POINTER(srealloc(p92,15););
printStats();
void* p103 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(srealloc(p89,11););
printStats();
void* p104 = last_address;
PRINT_POINTER(scalloc(134,46););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p88,156););
printStats();
void* p106 = last_address;
PRINT_POINTER(srealloc(p41,205););
printStats();
void* p107 = last_address;
PRINT_POINTER(scalloc(241,176););
printStats();
void* p108 = last_address;
PRINT_POINTER(scalloc(66,115););
printStats();
void* p109 = last_address;
PRINT_POINTER(srealloc(p80,173););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p93,113););
printStats();
void* p111 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(scalloc(170,211););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p95,202););
printStats();
void* p113 = last_address;
PRINT_POINTER(scalloc(204,11););
printStats();
void* p114 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p115 = last_address;
PRINT_POINTER(srealloc(p105,78););
printStats();
void* p116 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(srealloc(p101,162););
printStats();
void* p117 = last_address;
PRINT_POINTER(srealloc(p91,60););
printStats();
void* p118 = last_address;
PRINT_POINTER(srealloc(p69,71););
printStats();
void* p119 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p120 = last_address;
PRINT_POINTER(srealloc(p115,222););
printStats();
void* p121 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p122 = last_address;
PRINT_POINTER(srealloc(p120,179););
printStats();
void* p123 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(smalloc(66););
printStats();
void* p124 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p125 = last_address;
PRINT_POINTER(srealloc(p123,169););
printStats();
void* p126 = last_address;
PRINT_POINTER(srealloc(p107,199););
printStats();
void* p127 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p128 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p129 = last_address;
DEBUG_PRINT(sfree(p122););
printStats();
PRINT_POINTER(smalloc(61););
printStats();
void* p130 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p131 = last_address;
PRINT_POINTER(srealloc(p96,67););
printStats();
void* p132 = last_address;
PRINT_POINTER(scalloc(194,246););
printStats();
void* p133 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p134 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p135 = last_address;
PRINT_POINTER(srealloc(p117,2););
printStats();
void* p136 = last_address;
DEBUG_PRINT(sfree(p110););
printStats();
PRINT_POINTER(smalloc(114););
printStats();
void* p137 = last_address;
PRINT_POINTER(scalloc(177,80););
printStats();
void* p138 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
DEBUG_PRINT(sfree(p104););
printStats();
PRINT_POINTER(scalloc(69,151););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
DEBUG_PRINT(sfree(p112););
printStats();
PRINT_POINTER(srealloc(p118,179););
printStats();
void* p140 = last_address;
DEBUG_PRINT(sfree(p132););
printStats();
DEBUG_PRINT(sfree(p137););
printStats();
PRINT_POINTER(srealloc(p127,191););
printStats();
void* p141 = last_address;
DEBUG_PRINT(sfree(p108););
printStats();
PRINT_POINTER(scalloc(17,158););
printStats();
void* p142 = last_address;
PRINT_POINTER(scalloc(88,163););
printStats();
void* p143 = last_address;
PRINT_POINTER(srealloc(p103,211););
printStats();
void* p144 = last_address;
PRINT_POINTER(srealloc(p141,74););
printStats();
void* p145 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p146););
printStats();
PRINT_POINTER(scalloc(94,92););
printStats();
void* p147 = last_address;
PRINT_POINTER(srealloc(p111,184););
printStats();
void* p148 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p149 = last_address;
PRINT_POINTER(scalloc(2,171););
printStats();
void* p150 = last_address;
PRINT_POINTER(scalloc(138,175););
printStats();
void* p151 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p152 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(72,166););
printStats();
void* p154 = last_address;
DEBUG_PRINT(sfree(p99););
printStats();
PRINT_POINTER(smalloc(153););
printStats();
void* p155 = last_address;
PRINT_POINTER(scalloc(146,38););
printStats();
void* p156 = last_address;
PRINT_POINTER(srealloc(p126,164););
printStats();
void* p157 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p158 = last_address;
DEBUG_PRINT(sfree(p73););
printStats();
PRINT_POINTER(scalloc(98,23););
printStats();
void* p159 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p160 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p161 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p162 = last_address;
DEBUG_PRINT(sfree(p128););
printStats();
DEBUG_PRINT(sfree(p84););
printStats();
PRINT_POINTER(scalloc(87,52););
printStats();
void* p163 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p164 = last_address;
PRINT_POINTER(srealloc(p125,150););
printStats();
void* p165 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p166 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p167 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p168 = last_address;
PRINT_POINTER(srealloc(p162,87););
printStats();
void* p169 = last_address;
PRINT_POINTER(scalloc(42,159););
printStats();
void* p170 = last_address;
PRINT_POINTER(srealloc(p157,40););
printStats();
void* p171 = last_address;
DEBUG_PRINT(sfree(p66););
printStats();
DEBUG_PRINT(sfree(p124););
printStats();
PRINT_POINTER(smalloc(202););
printStats();
void* p172 = last_address;
DEBUG_PRINT(sfree(p106););
printStats();
PRINT_POINTER(smalloc(161););
printStats();
void* p173 = last_address;
PRINT_POINTER(scalloc(164,60););
printStats();
void* p174 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p175 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p176 = last_address;
PRINT_POINTER(srealloc(p147,41););
printStats();
void* p177 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p178 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p179 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p180 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p181 = last_address;
PRINT_POINTER(srealloc(p121,38););
printStats();
void* p182 = last_address;
PRINT_POINTER(srealloc(p167,47););
printStats();
void* p183 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p184 = last_address;
PRINT_POINTER(scalloc(92,48););
printStats();
void* p185 = last_address;
DEBUG_PRINT(sfree(p130););
printStats();
PRINT_POINTER(smalloc(205););
printStats();
void* p186 = last_address;
PRINT_POINTER(scalloc(177,56););
printStats();
void* p187 = last_address;
PRINT_POINTER(scalloc(164,197););
printStats();
void* p188 = last_address;
PRINT_POINTER(scalloc(178,11););
printStats();
void* p189 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p191 = last_address;
DEBUG_PRINT(sfree(p144););
printStats();
PRINT_POINTER(smalloc(26););
printStats();
void* p192 = last_address;
PRINT_POINTER(srealloc(p187,158););
printStats();
void* p193 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p194 = last_address;
DEBUG_PRINT(sfree(p189););
printStats();
PRINT_POINTER(smalloc(247););
printStats();
void* p195 = last_address;
PRINT_POINTER(srealloc(p182,22););
printStats();
void* p196 = last_address;
PRINT_POINTER(scalloc(175,237););
printStats();
void* p197 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p198 = last_address;
DEBUG_PRINT(sfree(p178););
printStats();
DEBUG_PRINT(sfree(p179););
printStats();
PRINT_POINTER(srealloc(p133,56););
printStats();
void* p199 = last_address;
PRINT_POINTER(scalloc(27,106););
printStats();
void* p200 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p201 = last_address;
PRINT_POINTER(scalloc(35,241););
printStats();
void* p202 = last_address;
PRINT_POINTER(scalloc(22,50););
printStats();
void* p203 = last_address;
PRINT_POINTER(scalloc(111,196););
printStats();
void* p204 = last_address;
DEBUG_PRINT(sfree(p191););
printStats();
PRINT_POINTER(scalloc(54,167););
printStats();
void* p205 = last_address;
PRINT_POINTER(scalloc(119,155););
printStats();
void* p206 = last_address;
PRINT_POINTER(srealloc(p155,159););
printStats();
void* p207 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(smalloc(149););
printStats();
void* p208 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p209 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p210 = last_address;
PRINT_POINTER(scalloc(136,95););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(192,217););
printStats();
void* p212 = last_address;
PRINT_POINTER(srealloc(p153,214););
printStats();
void* p213 = last_address;
DEBUG_PRINT(sfree(p149););
printStats();
PRINT_POINTER(scalloc(163,156););
printStats();
void* p214 = last_address;
PRINT_POINTER(scalloc(14,234););
printStats();
void* p215 = last_address;
PRINT_POINTER(srealloc(p173,222););
printStats();
void* p216 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(smalloc(127););
printStats();
void* p217 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p218 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p219 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p220 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p221 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p222 = last_address;
PRINT_POINTER(scalloc(82,133););
printStats();
void* p223 = last_address;
PRINT_POINTER(scalloc(237,229););
printStats();
void* p224 = last_address;
PRINT_POINTER(srealloc(p208,85););
printStats();
void* p225 = last_address;
DEBUG_PRINT(sfree(p224););
printStats();
PRINT_POINTER(scalloc(76,1););
printStats();
void* p226 = last_address;
PRINT_POINTER(srealloc(p183,201););
printStats();
void* p227 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p228 = last_address;
PRINT_POINTER(srealloc(p200,229););
printStats();
void* p229 = last_address;
PRINT_POINTER(scalloc(64,156););
printStats();
void* p230 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p231 = last_address;
PRINT_POINTER(scalloc(184,140););
printStats();
void* p232 = last_address;
PRINT_POINTER(scalloc(14,147););
printStats();
void* p233 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p234 = last_address;
PRINT_POINTER(srealloc(p102,49););
printStats();
void* p235 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
PRINT_POINTER(smalloc(16););
printStats();
void* p236 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p237 = last_address;
PRINT_POINTER(srealloc(p232,56););
printStats();
void* p238 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p234,8););
printStats();
void* p240 = last_address;
DEBUG_PRINT(sfree(p169););
printStats();
PRINT_POINTER(srealloc(p185,217););
printStats();
void* p241 = last_address;
PRINT_POINTER(scalloc(179,190););
printStats();
void* p242 = last_address;
PRINT_POINTER(srealloc(p134,14););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p202););
printStats();
DEBUG_PRINT(sfree(p215););
printStats();
PRINT_POINTER(smalloc(88););
printStats();
void* p244 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p245 = last_address;
PRINT_POINTER(srealloc(p145,193););
printStats();
void* p246 = last_address;
PRINT_POINTER(srealloc(p206,199););
printStats();
void* p247 = last_address;
PRINT_POINTER(scalloc(182,172););
printStats();
void* p248 = last_address;
DEBUG_PRINT(sfree(p150););
printStats();
DEBUG_PRINT(sfree(p151););
printStats();
PRINT_POINTER(srealloc(p161,62););
printStats();
void* p249 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p250 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p251 = last_address;
DEBUG_PRINT(sfree(p195););
printStats();
PRINT_POINTER(smalloc(94););
printStats();
void* p252 = last_address;
DEBUG_PRINT(sfree(p58););
printStats();
PRINT_POINTER(scalloc(128,149););
printStats();
void* p253 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p254 = last_address;
PRINT_POINTER(srealloc(p220,15););
printStats();
void* p255 = last_address;
PRINT_POINTER(scalloc(208,9););
printStats();
void* p256 = last_address;
DEBUG_PRINT(sfree(p251););
printStats();
PRINT_POINTER(srealloc(p203,136););
printStats();
void* p257 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p258 = last_address;
PRINT_POINTER(scalloc(88,212););
printStats();
void* p259 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p260 = last_address;
PRINT_POINTER(srealloc(p205,120););
printStats();
void* p261 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p262 = last_address;
PRINT_POINTER(srealloc(p138,4););
printStats();
void* p263 = last_address;
PRINT_POINTER(scalloc(134,151););
printStats();
void* p264 = last_address;
PRINT_POINTER(scalloc(210,32););
printStats();
void* p265 = last_address;
PRINT_POINTER(scalloc(212,124););
printStats();
void* p266 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p267 = last_address;
PRINT_POINTER(scalloc(113,52););
printStats();
void* p268 = last_address;
PRINT_POINTER(scalloc(171,115););
printStats();
void* p269 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p270 = last_address;
PRINT_POINTER(scalloc(95,240););
printStats();
void* p271 = last_address;
PRINT_POINTER(srealloc(p148,43););
printStats();
void* p272 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p273 = last_address;
PRINT_POINTER(srealloc(p231,129););
printStats();
void* p274 = last_address;
PRINT_POINTER(scalloc(100,52););
printStats();
void* p275 = last_address;
DEBUG_PRINT(sfree(p236););
printStats();
PRINT_POINTER(scalloc(85,57););
printStats();
void* p276 = last_address;
PRINT_POINTER(srealloc(p201,137););
printStats();
void* p277 = last_address;
DEBUG_PRINT(sfree(p269););
printStats();
PRINT_POINTER(smalloc(175););
printStats();
void* p278 = last_address;
DEBUG_PRINT(sfree(p261););
printStats();
PRINT_POINTER(scalloc(33,199););
printStats();
void* p279 = last_address;
PRINT_POINTER(srealloc(p131,98););
printStats();
void* p280 = last_address;
PRINT_POINTER(srealloc(p239,108););
printStats();
void* p281 = last_address;
DEBUG_PRINT(sfree(p211););
printStats();
PRINT_POINTER(scalloc(158,52););
printStats();
void* p282 = last_address;
DEBUG_PRINT(sfree(p165););
printStats();
DEBUG_PRINT(sfree(p256););
printStats();
PRINT_POINTER(srealloc(p129,159););
printStats();
void* p283 = last_address;
PRINT_POINTER(srealloc(p114,86););
printStats();
void* p284 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p285 = last_address;
DEBUG_PRINT(sfree(p275););
printStats();
PRINT_POINTER(scalloc(11,100););
printStats();
void* p286 = last_address;
PRINT_POINTER(scalloc(74,91););
printStats();
void* p287 = last_address;
PRINT_POINTER(scalloc(145,208););
printStats();
void* p288 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(smalloc(134););
printStats();
void* p289 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p290 = last_address;
PRINT_POINTER(scalloc(224,235););
printStats();
void* p291 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p292 = last_address;
DEBUG_PRINT(sfree(p259););
printStats();
DEBUG_PRINT(sfree(p223););
printStats();
DEBUG_PRINT(sfree(p270););
printStats();
PRINT_POINTER(smalloc(224););
printStats();
void* p293 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p294 = last_address;
PRINT_POINTER(srealloc(p235,136););
printStats();
void* p295 = last_address;
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(scalloc(122,246););
printStats();
void* p296 = last_address;
DEBUG_PRINT(sfree(p184););
printStats();
DEBUG_PRINT(sfree(p163););
printStats();
PRINT_POINTER(scalloc(48,126););
printStats();
void* p297 = last_address;
PRINT_POINTER(srealloc(p240,115););
printStats();
void* p298 = last_address;
PRINT_POINTER(scalloc(163,111););
printStats();
void* p299 = last_address;
PRINT_POINTER(scalloc(128,161););
printStats();
void* p300 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p302 = last_address;
PRINT_POINTER(srealloc(p237,38););
printStats();
void* p303 = last_address;
PRINT_POINTER(srealloc(p242,95););
printStats();
void* p304 = last_address;
PRINT_POINTER(scalloc(180,115););
printStats();
void* p305 = last_address;
DEBUG_PRINT(sfree(p303););
printStats();
DEBUG_PRINT(sfree(p295););
printStats();
DEBUG_PRINT(sfree(p299););
printStats();
DEBUG_PRINT(sfree(p225););
printStats();
PRINT_POINTER(srealloc(p207,185););
printStats();
void* p306 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(scalloc(187,135););
printStats();
void* p307 = last_address;
PRINT_POINTER(scalloc(1,53););
printStats();
void* p308 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p309 = last_address;
PRINT_POINTER(srealloc(p243,70););
printStats();
void* p310 = last_address;
PRINT_POINTER(srealloc(p241,123););
printStats();
void* p311 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p312 = last_address;
PRINT_POINTER(srealloc(p72,228););
printStats();
void* p313 = last_address;
DEBUG_PRINT(sfree(p194););
printStats();
DEBUG_PRINT(sfree(p246););
printStats();
PRINT_POINTER(srealloc(p281,133););
printStats();
void* p314 = last_address;
PRINT_POINTER(scalloc(186,49););
printStats();
void* p315 = last_address;
PRINT_POINTER(srealloc(p217,90););
printStats();
void* p316 = last_address;
DEBUG_PRINT(sfree(p198););
printStats();
PRINT_POINTER(smalloc(101););
printStats();
void* p317 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p318 = last_address;
PRINT_POINTER(scalloc(16,174););
printStats();
void* p319 = last_address;
PRINT_POINTER(srealloc(p154,119););
printStats();
void* p320 = last_address;
PRINT_POINTER(srealloc(p221,107););
printStats();
void* p321 = last_address;
PRINT_POINTER(scalloc(164,61););
printStats();
void* p322 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
DEBUG_PRINT(sfree(p172););
printStats();
DEBUG_PRINT(sfree(p255););
printStats();
PRINT_POINTER(scalloc(2,169););
printStats();
void* p323 = last_address;
PRINT_POINTER(scalloc(219,69););
printStats();
void* p324 = last_address;
PRINT_POINTER(srealloc(p164,33););
printStats();
void* p325 = last_address;
DEBUG_PRINT(sfree(p277););
printStats();
PRINT_POINTER(smalloc(63););
printStats();
void* p326 = last_address;
PRINT_POINTER(srealloc(p180,140););
printStats();
void* p327 = last_address;
PRINT_POINTER(srealloc(p310,22););
printStats();
void* p328 = last_address;
PRINT_POINTER(srealloc(p285,1););
printStats();
void* p329 = last_address;
DEBUG_PRINT(sfree(p238););
printStats();
PRINT_POINTER(smalloc(218););
printStats();
void* p330 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p331 = last_address;
PRINT_POINTER(srealloc(p97,133););
printStats();
void* p332 = last_address;
DEBUG_PRINT(sfree(p228););
printStats();
DEBUG_PRINT(sfree(p168););
printStats();
PRINT_POINTER(smalloc(106););
printStats();
void* p333 = last_address;
DEBUG_PRINT(sfree(p190););
printStats();
PRINT_POINTER(scalloc(217,240););
printStats();
void* p334 = last_address;
PRINT_POINTER(scalloc(155,187););
printStats();
void* p335 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p336 = last_address;
DEBUG_PRINT(sfree(p136););
printStats();
PRINT_POINTER(scalloc(176,245););
printStats();
void* p337 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p338 = last_address;
DEBUG_PRINT(sfree(p216););
printStats();
PRINT_POINTER(smalloc(74););
printStats();
void* p339 = last_address;
PRINT_POINTER(scalloc(0,47););
printStats();
void* p340 = last_address;
PRINT_POINTER(srealloc(p289,25););
printStats();
void* p341 = last_address;
PRINT_POINTER(scalloc(207,215););
printStats();
void* p342 = last_address;
PRINT_POINTER(srealloc(p284,45););
printStats();
void* p343 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p344 = last_address;
PRINT_POINTER(srealloc(p304,209););
printStats();
void* p345 = last_address;
PRINT_POINTER(srealloc(p302,93););
printStats();
void* p346 = last_address;
PRINT_POINTER(srealloc(p331,167););
printStats();
void* p347 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p348 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p349 = last_address;
PRINT_POINTER(srealloc(p309,23););
printStats();
void* p350 = last_address;
DEBUG_PRINT(sfree(p337););
printStats();
DEBUG_PRINT(sfree(p171););
printStats();
PRINT_POINTER(srealloc(p199,57););
printStats();
void* p351 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p352 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p353 = last_address;
DEBUG_PRINT(sfree(p257););
printStats();
PRINT_POINTER(srealloc(p263,219););
printStats();
void* p354 = last_address;
PRINT_POINTER(scalloc(244,80););
printStats();
void* p355 = last_address;
PRINT_POINTER(scalloc(100,34););
printStats();
void* p356 = last_address;
PRINT_POINTER(srealloc(p311,167););
printStats();
void* p357 = last_address;
PRINT_POINTER(scalloc(83,13););
printStats();
void* p358 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
DEBUG_PRINT(sfree(p338););
printStats();
PRINT_POINTER(smalloc(192););
printStats();
void* p359 = last_address;
PRINT_POINTER(srealloc(p316,48););
printStats();
void* p360 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p361 = last_address;
PRINT_POINTER(scalloc(109,179););
printStats();
void* p362 = last_address;
PRINT_POINTER(scalloc(105,34););
printStats();
void* p363 = last_address;
PRINT_POINTER(srealloc(p288,240););
printStats();
void* p364 = last_address;
PRINT_POINTER(srealloc(p83,229););
printStats();
void* p365 = last_address;
PRINT_POINTER(scalloc(57,65););
printStats();
void* p366 = last_address;
PRINT_POINTER(srealloc(p339,73););
printStats();
void* p367 = last_address;
PRINT_POINTER(scalloc(114,11););
printStats();
void* p368 = last_address;
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(scalloc(233,115););
printStats();
void* p369 = last_address;
PRINT_POINTER(scalloc(194,149););
printStats();
void* p370 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p371 = last_address;
PRINT_POINTER(srealloc(p230,198););
printStats();
void* p372 = last_address;
DEBUG_PRINT(sfree(p370););
printStats();
PRINT_POINTER(srealloc(p346,43););
printStats();
void* p373 = last_address;
PRINT_POINTER(srealloc(p368,246););
printStats();
void* p374 = last_address;
PRINT_POINTER(scalloc(76,210););
printStats();
void* p375 = last_address;
PRINT_POINTER(srealloc(p282,150););
printStats();
void* p376 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
DEBUG_PRINT(sfree(p273););
printStats();
DEBUG_PRINT(sfree(p308););
printStats();
PRINT_POINTER(smalloc(152););
printStats();
void* p377 = last_address;
PRINT_POINTER(scalloc(113,98););
printStats();
void* p378 = last_address;
DEBUG_PRINT(sfree(p342););
printStats();
DEBUG_PRINT(sfree(p365););
printStats();
DEBUG_PRINT(sfree(p135););
printStats();
PRINT_POINTER(scalloc(168,138););
printStats();
void* p379 = last_address;
PRINT_POINTER(scalloc(69,2););
printStats();
void* p380 = last_address;
DEBUG_PRINT(sfree(p188););
printStats();
DEBUG_PRINT(sfree(p298););
printStats();
PRINT_POINTER(smalloc(121););
printStats();
void* p381 = last_address;
DEBUG_PRINT(sfree(p286););
printStats();
PRINT_POINTER(scalloc(8,199););
printStats();
void* p382 = last_address;
DEBUG_PRINT(sfree(p312););
printStats();
PRINT_POINTER(scalloc(83,208););
printStats();
void* p383 = last_address;
PRINT_POINTER(srealloc(p332,61););
printStats();
void* p384 = last_address;
PRINT_POINTER(srealloc(p244,102););
printStats();
void* p385 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p386 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p387 = last_address;
PRINT_POINTER(srealloc(p253,127););
printStats();
void* p388 = last_address;
DEBUG_PRINT(sfree(p373););
printStats();
PRINT_POINTER(smalloc(151););
printStats();
void* p389 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p390 = last_address;
PRINT_POINTER(scalloc(1,14););
printStats();
void* p391 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p392 = last_address;
PRINT_POINTER(scalloc(7,243););
printStats();
void* p393 = last_address;
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(smalloc(96););
printStats();
void* p394 = last_address;
PRINT_POINTER(srealloc(p350,125););
printStats();
void* p395 = last_address;
DEBUG_PRINT(sfree(p381););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p396 = last_address;
DEBUG_PRINT(sfree(p325););
printStats();
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(scalloc(246,239););
printStats();
void* p397 = last_address;
PRINT_POINTER(srealloc(p385,145););
printStats();
void* p398 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p399 = last_address;
PRINT_POINTER(scalloc(113,127););
printStats();
void* p400 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p401 = last_address;
PRINT_POINTER(srealloc(p330,30););
printStats();
void* p402 = last_address;
PRINT_POINTER(scalloc(49,109););
printStats();
void* p403 = last_address;
PRINT_POINTER(scalloc(205,249););
printStats();
void* p404 = last_address;
PRINT_POINTER(srealloc(p113,142););
printStats();
void* p405 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p406 = last_address;
DEBUG_PRINT(sfree(p192););
printStats();
PRINT_POINTER(smalloc(72););
printStats();
void* p407 = last_address;
PRINT_POINTER(scalloc(91,231););
printStats();
void* p408 = last_address;
PRINT_POINTER(srealloc(p181,41););
printStats();
void* p409 = last_address;
DEBUG_PRINT(sfree(p212););
printStats();
PRINT_POINTER(scalloc(192,93););
printStats();
void* p410 = last_address;
PRINT_POINTER(srealloc(p401,0););
printStats();
void* p411 = last_address;
PRINT_POINTER(srealloc(p358,86););
printStats();
void* p412 = last_address;
PRINT_POINTER(scalloc(2,56););
printStats();
void* p413 = last_address;
PRINT_POINTER(srealloc(p219,151););
printStats();
void* p414 = last_address;
PRINT_POINTER(scalloc(115,73););
printStats();
void* p415 = last_address;
DEBUG_PRINT(sfree(p140););
printStats();
DEBUG_PRINT(sfree(p372););
printStats();
PRINT_POINTER(smalloc(117););
printStats();
void* p416 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p417 = last_address;
PRINT_POINTER(scalloc(176,224););
printStats();
void* p418 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p419 = last_address;
DEBUG_PRINT(sfree(p341););
printStats();
PRINT_POINTER(smalloc(12););
printStats();
void* p420 = last_address;
PRINT_POINTER(srealloc(p321,63););
printStats();
void* p421 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
DEBUG_PRINT(sfree(p293););
printStats();
PRINT_POINTER(srealloc(p366,22););
printStats();
void* p422 = last_address;
DEBUG_PRINT(sfree(p378););
printStats();
PRINT_POINTER(smalloc(189););
printStats();
void* p423 = last_address;
PRINT_POINTER(srealloc(p229,198););
printStats();
void* p424 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p425 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p426 = last_address;
PRINT_POINTER(srealloc(p413,125););
printStats();
void* p427 = last_address;
DEBUG_PRINT(sfree(p389););
printStats();
DEBUG_PRINT(sfree(p393););
printStats();
PRINT_POINTER(scalloc(207,13););
printStats();
void* p428 = last_address;
PRINT_POINTER(srealloc(p335,19););
printStats();
void* p429 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p430 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p431 = last_address;
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(srealloc(p265,127););
printStats();
void* p432 = last_address;
PRINT_POINTER(scalloc(105,113););
printStats();
void* p433 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p434 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p435 = last_address;
PRINT_POINTER(srealloc(p394,196););
printStats();
void* p436 = last_address;
DEBUG_PRINT(sfree(p318););
printStats();
DEBUG_PRINT(sfree(p355););
printStats();
DEBUG_PRINT(sfree(p436););
printStats();
PRINT_POINTER(scalloc(3,140););
printStats();
void* p437 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p438 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p439 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p440 = last_address;
PRINT_POINTER(srealloc(p420,233););
printStats();
void* p441 = last_address;
PRINT_POINTER(scalloc(77,166););
printStats();
void* p442 = last_address;
PRINT_POINTER(srealloc(p334,22););
printStats();
void* p443 = last_address;
PRINT_POINTER(srealloc(p196,77););
printStats();
void* p444 = last_address;
PRINT_POINTER(srealloc(p442,136););
printStats();
void* p445 = last_address;
PRINT_POINTER(scalloc(33,81););
printStats();
void* p446 = last_address;
DEBUG_PRINT(sfree(p380););
printStats();
PRINT_POINTER(srealloc(p252,64););
printStats();
void* p447 = last_address;
PRINT_POINTER(scalloc(135,160););
printStats();
void* p448 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p449 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p450 = last_address;
PRINT_POINTER(scalloc(70,60););
printStats();
void* p451 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p452 = last_address;
PRINT_POINTER(scalloc(240,108););
printStats();
void* p453 = last_address;
PRINT_POINTER(scalloc(30,57););
printStats();
void* p454 = last_address;
DEBUG_PRINT(sfree(p427););
printStats();
PRINT_POINTER(smalloc(169););
printStats();
void* p455 = last_address;
PRINT_POINTER(srealloc(p398,7););
printStats();
void* p456 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p457 = last_address;
PRINT_POINTER(srealloc(p407,61););
printStats();
void* p458 = last_address;
PRINT_POINTER(srealloc(p319,129););
printStats();
void* p459 = last_address;
PRINT_POINTER(srealloc(p356,179););
printStats();
void* p460 = last_address;
PRINT_POINTER(srealloc(p383,157););
printStats();
void* p461 = last_address;
PRINT_POINTER(scalloc(103,43););
printStats();
void* p462 = last_address;
DEBUG_PRINT(sfree(p193););
printStats();
PRINT_POINTER(srealloc(p414,46););
printStats();
void* p463 = last_address;
PRINT_POINTER(scalloc(175,227););
printStats();
void* p464 = last_address;
DEBUG_PRINT(sfree(p336););
printStats();
DEBUG_PRINT(sfree(p314););
printStats();
PRINT_POINTER(smalloc(193););
printStats();
void* p465 = last_address;
DEBUG_PRINT(sfree(p461););
printStats();
PRINT_POINTER(smalloc(248););
printStats();
void* p466 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p467 = last_address;
PRINT_POINTER(srealloc(p156,165););
printStats();
void* p468 = last_address;
PRINT_POINTER(srealloc(p426,187););
printStats();
void* p469 = last_address;
PRINT_POINTER(scalloc(179,186););
printStats();
void* p470 = last_address;
PRINT_POINTER(srealloc(p396,124););
printStats();
void* p471 = last_address;
PRINT_POINTER(scalloc(213,219););
printStats();
void* p472 = last_address;
PRINT_POINTER(srealloc(p264,79););
printStats();
void* p473 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
DEBUG_PRINT(sfree(p440););
printStats();
PRINT_POINTER(scalloc(46,145););
printStats();
void* p474 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p475 = last_address;
PRINT_POINTER(srealloc(p452,175););
printStats();
void* p476 = last_address;
PRINT_POINTER(srealloc(p409,50););
printStats();
void* p477 = last_address;
PRINT_POINTER(scalloc(133,191););
printStats();
void* p478 = last_address;
PRINT_POINTER(scalloc(191,240););
printStats();
void* p479 = last_address;
PRINT_POINTER(scalloc(243,246););
printStats();
void* p480 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p481 = last_address;
DEBUG_PRINT(sfree(p301););
printStats();
DEBUG_PRINT(sfree(p345););
printStats();
DEBUG_PRINT(sfree(p292););
printStats();
DEBUG_PRINT(sfree(p433););
printStats();
PRINT_POINTER(smalloc(226););
printStats();
void* p482 = last_address;
DEBUG_PRINT(sfree(p456););
printStats();
PRINT_POINTER(srealloc(p371,40););
printStats();
void* p483 = last_address;
PRINT_POINTER(srealloc(p344,192););
printStats();
void* p484 = last_address;
DEBUG_PRINT(sfree(p160););
printStats();
DEBUG_PRINT(sfree(p478););
printStats();
PRINT_POINTER(scalloc(244,79););
printStats();
void* p485 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p486 = last_address;
PRINT_POINTER(scalloc(89,97););
printStats();
void* p487 = last_address;
PRINT_POINTER(scalloc(2,158););
printStats();
void* p488 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p489 = last_address;
PRINT_POINTER(scalloc(72,0););
printStats();
void* p490 = last_address;
DEBUG_PRINT(sfree(p417););
printStats();
DEBUG_PRINT(sfree(p458););
printStats();
PRINT_POINTER(scalloc(73,115););
printStats();
void* p491 = last_address;
PRINT_POINTER(srealloc(p280,232););
printStats();
void* p492 = last_address;
PRINT_POINTER(srealloc(p360,16););
printStats();
void* p493 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p494 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p495 = last_address;
DEBUG_PRINT(sfree(p491););
printStats();
DEBUG_PRINT(sfree(p213););
printStats();
DEBUG_PRINT(sfree(p143););
printStats();
PRINT_POINTER(scalloc(92,193););
printStats();
void* p496 = last_address;
PRINT_POINTER(srealloc(p490,50););
printStats();
void* p497 = last_address;
PRINT_POINTER(scalloc(22,212););
printStats();
void* p498 = last_address;
PRINT_POINTER(scalloc(91,239););
printStats();
void* p499 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p500 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p501 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p502 = last_address;
PRINT_POINTER(srealloc(p486,70););
printStats();
void* p503 = last_address;
DEBUG_PRINT(sfree(p496););
printStats();
PRINT_POINTER(scalloc(38,221););
printStats();
void* p504 = last_address;
PRINT_POINTER(srealloc(p501,135););
printStats();
void* p505 = last_address;
PRINT_POINTER(scalloc(91,236););
printStats();
void* p506 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p507 = last_address;
PRINT_POINTER(scalloc(110,174););
printStats();
void* p508 = last_address;
PRINT_POINTER(srealloc(p400,123););
printStats();
void* p509 = last_address;
DEBUG_PRINT(sfree(p476););
printStats();
DEBUG_PRINT(sfree(p266););
printStats();
PRINT_POINTER(srealloc(p315,221););
printStats();
void* p510 = last_address;
DEBUG_PRINT(sfree(p233););
printStats();
PRINT_POINTER(scalloc(242,101););
printStats();
void* p511 = last_address;
PRINT_POINTER(scalloc(217,186););
printStats();
void* p512 = last_address;
PRINT_POINTER(srealloc(p379,112););
printStats();
void* p513 = last_address;
PRINT_POINTER(scalloc(20,173););
printStats();
void* p514 = last_address;
PRINT_POINTER(scalloc(136,126););
printStats();
void* p515 = last_address;
DEBUG_PRINT(sfree(p387););
printStats();
DEBUG_PRINT(sfree(p445););
printStats();
PRINT_POINTER(srealloc(p464,196););
printStats();
void* p516 = last_address;
PRINT_POINTER(scalloc(5,31););
printStats();
void* p517 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p518 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p519 = last_address;
PRINT_POINTER(srealloc(p504,249););
printStats();
void* p520 = last_address;
PRINT_POINTER(srealloc(p505,47););
printStats();
void* p521 = last_address;
PRINT_POINTER(scalloc(239,126););
printStats();
void* p522 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p523 = last_address;
DEBUG_PRINT(sfree(p158););
printStats();
PRINT_POINTER(smalloc(85););
printStats();
void* p524 = last_address;
PRINT_POINTER(scalloc(200,130););
printStats();
void* p525 = last_address;
PRINT_POINTER(scalloc(62,58););
printStats();
void* p526 = last_address;
PRINT_POINTER(scalloc(79,59););
printStats();
void* p527 = last_address;
PRINT_POINTER(scalloc(83,141););
printStats();
void* p528 = last_address;
PRINT_POINTER(srealloc(p377,77););
printStats();
void* p529 = last_address;
DEBUG_PRINT(sfree(p352););
printStats();
PRINT_POINTER(srealloc(p443,207););
printStats();
void* p530 = last_address;
PRINT_POINTER(scalloc(20,37););
printStats();
void* p531 = last_address;
PRINT_POINTER(scalloc(89,32););
printStats();
void* p532 = last_address;
DEBUG_PRINT(sfree(p517););
printStats();
DEBUG_PRINT(sfree(p493););
printStats();
DEBUG_PRINT(sfree(p471););
printStats();
PRINT_POINTER(srealloc(p519,152););
printStats();
void* p533 = last_address;
PRINT_POINTER(scalloc(129,37););
printStats();
void* p534 = last_address;
DEBUG_PRINT(sfree(p439););
printStats();
PRINT_POINTER(scalloc(147,190););
printStats();
void* p535 = last_address;
PRINT_POINTER(scalloc(143,155););
printStats();
void* p536 = last_address;
PRINT_POINTER(srealloc(p438,49););
printStats();
void* p537 = last_address;
PRINT_POINTER(scalloc(135,58););
printStats();
void* p538 = last_address;
PRINT_POINTER(scalloc(104,213););
printStats();
void* p539 = last_address;
PRINT_POINTER(scalloc(162,19););
printStats();
void* p540 = last_address;
DEBUG_PRINT(sfree(p271););
printStats();
PRINT_POINTER(scalloc(90,139););
printStats();
void* p541 = last_address;
PRINT_POINTER(scalloc(108,154););
printStats();
void* p542 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p543 = last_address;
DEBUG_PRINT(sfree(p541););
printStats();
PRINT_POINTER(scalloc(38,204););
printStats();
void* p544 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p545 = last_address;
DEBUG_PRINT(sfree(p363););
printStats();
DEBUG_PRINT(sfree(p521););
printStats();
PRINT_POINTER(srealloc(p415,91););
printStats();
void* p546 = last_address;
PRINT_POINTER(srealloc(p406,66););
printStats();
void* p547 = last_address;
PRINT_POINTER(srealloc(p349,30););
printStats();
void* p548 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p549 = last_address;
PRINT_POINTER(srealloc(p412,54););
printStats();
void* p550 = last_address;
PRINT_POINTER(srealloc(p354,245););
printStats();
void* p551 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p552 = last_address;
DEBUG_PRINT(sfree(p544););
printStats();
PRINT_POINTER(srealloc(p530,200););
printStats();
void* p553 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p554 = last_address;
PRINT_POINTER(scalloc(104,104););
printStats();
void* p555 = last_address;
DEBUG_PRINT(sfree(p547););
printStats();
PRINT_POINTER(smalloc(189););
printStats();
void* p556 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p557 = last_address;
PRINT_POINTER(srealloc(p542,161););
printStats();
void* p558 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p559 = last_address;
DEBUG_PRINT(sfree(p376););
printStats();
DEBUG_PRINT(sfree(p495););
printStats();
PRINT_POINTER(scalloc(77,218););
printStats();
void* p560 = last_address;
DEBUG_PRINT(sfree(p290););
printStats();
PRINT_POINTER(srealloc(p441,216););
printStats();
void* p561 = last_address;
DEBUG_PRINT(sfree(p247););
printStats();
DEBUG_PRINT(sfree(p287););
printStats();
PRINT_POINTER(srealloc(p459,126););
printStats();
void* p562 = last_address;
PRINT_POINTER(scalloc(219,49););
printStats();
void* p563 = last_address;
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(smalloc(68););
printStats();
void* p564 = last_address;
DEBUG_PRINT(sfree(p333););
printStats();
PRINT_POINTER(smalloc(249););
printStats();
void* p565 = last_address;
PRINT_POINTER(scalloc(84,227););
printStats();
void* p566 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p567 = last_address;
PRINT_POINTER(srealloc(p498,42););
printStats();
void* p568 = last_address;
PRINT_POINTER(scalloc(225,36););
printStats();
void* p569 = last_address;
PRINT_POINTER(scalloc(65,175););
printStats();
void* p570 = last_address;
PRINT_POINTER(scalloc(22,4););
printStats();
void* p571 = last_address;
PRINT_POINTER(srealloc(p369,13););
printStats();
void* p572 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p573 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p574 = last_address;
PRINT_POINTER(scalloc(155,117););
printStats();
void* p575 = last_address;
PRINT_POINTER(srealloc(p481,53););
printStats();
void* p576 = last_address;
PRINT_POINTER(scalloc(159,228););
printStats();
void* p577 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p578 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p579 = last_address;
DEBUG_PRINT(sfree(p245););
printStats();
PRINT_POINTER(scalloc(113,100););
printStats();
void* p580 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p581 = last_address;
PRINT_POINTER(scalloc(106,233););
printStats();
void* p582 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p583 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p584 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p585 = last_address;
DEBUG_PRINT(sfree(p566););
printStats();
DEBUG_PRINT(sfree(p328););
printStats();
PRINT_POINTER(smalloc(220););
printStats();
void* p586 = last_address;
PRINT_POINTER(scalloc(37,241););
printStats();
void* p587 = last_address;
PRINT_POINTER(srealloc(p268,127););
printStats();
void* p588 = last_address;
PRINT_POINTER(srealloc(p474,26););
printStats();
void* p589 = last_address;
PRINT_POINTER(scalloc(66,33););
printStats();
void* p590 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p591 = last_address;
DEBUG_PRINT(sfree(p499););
printStats();
PRINT_POINTER(srealloc(p283,134););
printStats();
void* p592 = last_address;
PRINT_POINTER(scalloc(214,171););
printStats();
void* p593 = last_address;
PRINT_POINTER(scalloc(241,143););
printStats();
void* p594 = last_address;
DEBUG_PRINT(sfree(p324););
printStats();
PRINT_POINTER(srealloc(p585,63););
printStats();
void* p595 = last_address;
PRINT_POINTER(scalloc(242,189););
printStats();
void* p596 = last_address;
DEBUG_PRINT(sfree(p523););
printStats();
PRINT_POINTER(smalloc(121););
printStats();
void* p597 = last_address;
DEBUG_PRINT(sfree(p307););
printStats();
PRINT_POINTER(smalloc(191););
printStats();
void* p598 = last_address;
DEBUG_PRINT(sfree(p561););
printStats();
DEBUG_PRINT(sfree(p467););
printStats();
DEBUG_PRINT(sfree(p249););
printStats();
PRINT_POINTER(srealloc(p588,90););
printStats();
void* p599 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p600 = last_address;
PRINT_POINTER(srealloc(p548,6););
printStats();
void* p601 = last_address;
PRINT_POINTER(srealloc(p569,0););
printStats();
void* p602 = last_address;
DEBUG_PRINT(sfree(p306););
printStats();
PRINT_POINTER(scalloc(201,146););
printStats();
void* p603 = last_address;
DEBUG_PRINT(sfree(p79););
printStats();
PRINT_POINTER(scalloc(94,64););
printStats();
void* p604 = last_address;
DEBUG_PRINT(sfree(p571););
printStats();
PRINT_POINTER(smalloc(214););
printStats();
void* p605 = last_address;
DEBUG_PRINT(sfree(p457););
printStats();
PRINT_POINTER(srealloc(p598,215););
printStats();
void* p606 = last_address;
PRINT_POINTER(scalloc(118,170););
printStats();
void* p607 = last_address;
DEBUG_PRINT(sfree(p507););
printStats();
PRINT_POINTER(srealloc(p508,10););
printStats();
void* p608 = last_address;
PRINT_POINTER(scalloc(77,249););
printStats();
void* p609 = last_address;
DEBUG_PRINT(sfree(p604););
printStats();
PRINT_POINTER(scalloc(120,210););
printStats();
void* p610 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p611 = last_address;
DEBUG_PRINT(sfree(p411););
printStats();
DEBUG_PRINT(sfree(p568););
printStats();
PRINT_POINTER(smalloc(129););
printStats();
void* p612 = last_address;
DEBUG_PRINT(sfree(p520););
printStats();
PRINT_POINTER(smalloc(62););
printStats();
void* p613 = last_address;
PRINT_POINTER(scalloc(227,53););
printStats();
void* p614 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p615 = last_address;
DEBUG_PRINT(sfree(p429););
printStats();
PRINT_POINTER(srealloc(p416,61););
printStats();
void* p616 = last_address;
DEBUG_PRINT(sfree(p254););
printStats();
DEBUG_PRINT(sfree(p574););
printStats();
PRINT_POINTER(srealloc(p614,95););
printStats();
void* p617 = last_address;
PRINT_POINTER(scalloc(248,135););
printStats();
void* p618 = last_address;
PRINT_POINTER(srealloc(p142,240););
printStats();
void* p619 = last_address;
PRINT_POINTER(srealloc(p551,164););
printStats();
void* p620 = last_address;
DEBUG_PRINT(sfree(p539););
printStats();
PRINT_POINTER(scalloc(41,23););
printStats();
void* p621 = last_address;
DEBUG_PRINT(sfree(p532););
printStats();
PRINT_POINTER(scalloc(171,139););
printStats();
void* p622 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p623 = last_address;
DEBUG_PRINT(sfree(p320););
printStats();
DEBUG_PRINT(sfree(p615););
printStats();
PRINT_POINTER(srealloc(p565,0););
printStats();
void* p624 = last_address;
DEBUG_PRINT(sfree(p422););
printStats();
PRINT_POINTER(smalloc(70););
printStats();
void* p625 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p626 = last_address;
PRINT_POINTER(scalloc(157,140););
printStats();
void* p627 = last_address;
PRINT_POINTER(srealloc(p434,237););
printStats();
void* p628 = last_address;
PRINT_POINTER(srealloc(p448,101););
printStats();
void* p629 = last_address;
DEBUG_PRINT(sfree(p549););
printStats();
PRINT_POINTER(smalloc(36););
printStats();
void* p630 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p631 = last_address;
PRINT_POINTER(scalloc(164,31););
printStats();
void* p632 = last_address;
DEBUG_PRINT(sfree(p608););
printStats();
PRINT_POINTER(scalloc(125,215););
printStats();
void* p633 = last_address;
PRINT_POINTER(srealloc(p553,120););
printStats();
void* p634 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p635 = last_address;
DEBUG_PRINT(sfree(p437););
printStats();
PRINT_POINTER(srealloc(p463,17););
printStats();
void* p636 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p637 = last_address;
PRINT_POINTER(scalloc(20,180););
printStats();
void* p638 = last_address;
PRINT_POINTER(scalloc(151,142););
printStats();
void* p639 = last_address;
PRINT_POINTER(srealloc(p480,44););
printStats();
void* p640 = last_address;
PRINT_POINTER(scalloc(177,97););
printStats();
void* p641 = last_address;
PRINT_POINTER(srealloc(p374,120););
printStats();
void* p642 = last_address;
PRINT_POINTER(srealloc(p227,77););
printStats();
void* p643 = last_address;
PRINT_POINTER(scalloc(166,237););
printStats();
void* p644 = last_address;
DEBUG_PRINT(sfree(p637););
printStats();
DEBUG_PRINT(sfree(p613););
printStats();
DEBUG_PRINT(sfree(p606););
printStats();
PRINT_POINTER(srealloc(p262,58););
printStats();
void* p645 = last_address;
PRINT_POINTER(scalloc(43,29););
printStats();
void* p646 = last_address;
PRINT_POINTER(srealloc(p494,83););
printStats();
void* p647 = last_address;
DEBUG_PRINT(sfree(p594););
printStats();
PRINT_POINTER(scalloc(80,232););
printStats();
void* p648 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p649 = last_address;
PRINT_POINTER(scalloc(241,23););
printStats();
void* p650 = last_address;
PRINT_POINTER(srealloc(p506,83););
printStats();
void* p651 = last_address;
PRINT_POINTER(srealloc(p572,22););
printStats();
void* p652 = last_address;
DEBUG_PRINT(sfree(p455););
printStats();
PRINT_POINTER(srealloc(p531,29););
printStats();
void* p653 = last_address;
DEBUG_PRINT(sfree(p510););
printStats();
DEBUG_PRINT(sfree(p587););
printStats();
DEBUG_PRINT(sfree(p466););
printStats();
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(srealloc(p418,26););
printStats();
void* p654 = last_address;
PRINT_POINTER(srealloc(p348,179););
printStats();
void* p655 = last_address;
PRINT_POINTER(scalloc(237,249););
printStats();
void* p656 = last_address;
PRINT_POINTER(srealloc(p633,22););
printStats();
void* p657 = last_address;
PRINT_POINTER(srealloc(p653,192););
printStats();
void* p658 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p659 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p660 = last_address;
PRINT_POINTER(srealloc(p375,105););
printStats();
void* p661 = last_address;
DEBUG_PRINT(sfree(p620););
printStats();
DEBUG_PRINT(sfree(p395););
printStats();
PRINT_POINTER(smalloc(74););
printStats();
void* p662 = last_address;
PRINT_POINTER(srealloc(p556,235););
printStats();
void* p663 = last_address;
PRINT_POINTER(srealloc(p600,80););
printStats();
void* p664 = last_address;
PRINT_POINTER(scalloc(205,119););
printStats();
void* p665 = last_address;
PRINT_POINTER(srealloc(p382,244););
printStats();
void* p666 = last_address;
PRINT_POINTER(scalloc(34,188););
printStats();
void* p667 = last_address;
PRINT_POINTER(srealloc(p624,117););
printStats();
void* p668 = last_address;
PRINT_POINTER(scalloc(200,178););
printStats();
void* p669 = last_address;
PRINT_POINTER(srealloc(p475,192););
printStats();
void* p670 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p671 = last_address;
DEBUG_PRINT(sfree(p322););
printStats();
PRINT_POINTER(srealloc(p446,207););
printStats();
void* p672 = last_address;
DEBUG_PRINT(sfree(p554););
printStats();
DEBUG_PRINT(sfree(p512););
printStats();
PRINT_POINTER(scalloc(199,52););
printStats();
void* p673 = last_address;
PRINT_POINTER(scalloc(80,136););
printStats();
void* p674 = last_address;
DEBUG_PRINT(sfree(p597););
printStats();
PRINT_POINTER(srealloc(p226,97););
printStats();
void* p675 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p676 = last_address;
PRINT_POINTER(srealloc(p351,2););
printStats();
void* p677 = last_address;
PRINT_POINTER(scalloc(186,88););
printStats();
void* p678 = last_address;
PRINT_POINTER(srealloc(p641,55););
printStats();
void* p679 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p680 = last_address;
PRINT_POINTER(scalloc(126,79););
printStats();
void* p681 = last_address;
PRINT_POINTER(scalloc(46,227););
printStats();
void* p682 = last_address;
PRINT_POINTER(scalloc(104,114););
printStats();
void* p683 = last_address;
PRINT_POINTER(srealloc(p479,205););
printStats();
void* p684 = last_address;
PRINT_POINTER(srealloc(p340,37););
printStats();
void* p685 = last_address;
PRINT_POINTER(scalloc(192,247););
printStats();
void* p686 = last_address;
DEBUG_PRINT(sfree(p627););
printStats();
PRINT_POINTER(srealloc(p430,192););
printStats();
void* p687 = last_address;
PRINT_POINTER(scalloc(93,71););
printStats();
void* p688 = last_address;
PRINT_POINTER(scalloc(46,51););
printStats();
void* p689 = last_address;
PRINT_POINTER(scalloc(152,45););
printStats();
void* p690 = last_address;
PRINT_POINTER(srealloc(p570,248););
printStats();
void* p691 = last_address;
DEBUG_PRINT(sfree(p423););
printStats();
PRINT_POINTER(srealloc(p555,176););
printStats();
void* p692 = last_address;
DEBUG_PRINT(sfree(p686););
printStats();
PRINT_POINTER(srealloc(p485,79););
printStats();
void* p693 = last_address;
PRINT_POINTER(scalloc(103,80););
printStats();
void* p694 = last_address;
PRINT_POINTER(srealloc(p305,203););
printStats();
void* p695 = last_address;
DEBUG_PRINT(sfree(p540););
printStats();
PRINT_POINTER(scalloc(8,26););
printStats();
void* p696 = last_address;
}
