#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(202););
printStats();
void* p0 = last_address;
PRINT_POINTER(scalloc(118,220););
printStats();
void* p1 = last_address;
PRINT_POINTER(srealloc(p1,119););
printStats();
void* p2 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(srealloc(p2,132););
printStats();
void* p3 = last_address;
PRINT_POINTER(scalloc(128,50););
printStats();
void* p4 = last_address;
PRINT_POINTER(scalloc(111,132););
printStats();
void* p5 = last_address;
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(smalloc(175););
printStats();
void* p6 = last_address;
PRINT_POINTER(srealloc(p6,239););
printStats();
void* p7 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p8 = last_address;
PRINT_POINTER(scalloc(72,145););
printStats();
void* p9 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
PRINT_POINTER(scalloc(135,44););
printStats();
void* p10 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(smalloc(182););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(6,87););
printStats();
void* p12 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p13 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
PRINT_POINTER(scalloc(100,155););
printStats();
void* p14 = last_address;
PRINT_POINTER(srealloc(p12,72););
printStats();
void* p15 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p16 = last_address;
DEBUG_PRINT(sfree(p3););
printStats();
PRINT_POINTER(srealloc(p15,230););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(68,1););
printStats();
void* p18 = last_address;
PRINT_POINTER(srealloc(p14,139););
printStats();
void* p19 = last_address;
PRINT_POINTER(srealloc(p9,205););
printStats();
void* p20 = last_address;
PRINT_POINTER(scalloc(63,223););
printStats();
void* p21 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p22 = last_address;
PRINT_POINTER(scalloc(226,190););
printStats();
void* p23 = last_address;
PRINT_POINTER(srealloc(p4,189););
printStats();
void* p24 = last_address;
PRINT_POINTER(scalloc(230,237););
printStats();
void* p25 = last_address;
DEBUG_PRINT(sfree(p20););
printStats();
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(smalloc(1););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p10,86););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(scalloc(27,5););
printStats();
void* p28 = last_address;
PRINT_POINTER(srealloc(p23,30););
printStats();
void* p29 = last_address;
PRINT_POINTER(scalloc(116,107););
printStats();
void* p30 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p31 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
PRINT_POINTER(scalloc(209,103););
printStats();
void* p32 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p33 = last_address;
PRINT_POINTER(srealloc(p33,159););
printStats();
void* p34 = last_address;
PRINT_POINTER(scalloc(81,39););
printStats();
void* p35 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p36 = last_address;
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(smalloc(62););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(226,33););
printStats();
void* p38 = last_address;
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(scalloc(221,22););
printStats();
void* p39 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p40 = last_address;
PRINT_POINTER(scalloc(205,123););
printStats();
void* p41 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
DEBUG_PRINT(sfree(p32););
printStats();
PRINT_POINTER(smalloc(102););
printStats();
void* p42 = last_address;
PRINT_POINTER(srealloc(p27,150););
printStats();
void* p43 = last_address;
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(srealloc(p41,196););
printStats();
void* p44 = last_address;
DEBUG_PRINT(sfree(p35););
printStats();
DEBUG_PRINT(sfree(p19););
printStats();
PRINT_POINTER(smalloc(65););
printStats();
void* p45 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p46 = last_address;
PRINT_POINTER(scalloc(170,133););
printStats();
void* p47 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p48 = last_address;
PRINT_POINTER(srealloc(p17,92););
printStats();
void* p49 = last_address;
PRINT_POINTER(srealloc(p43,203););
printStats();
void* p50 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(srealloc(p34,3););
printStats();
void* p51 = last_address;
PRINT_POINTER(srealloc(p49,152););
printStats();
void* p52 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(smalloc(89););
printStats();
void* p53 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p54 = last_address;
PRINT_POINTER(srealloc(p13,128););
printStats();
void* p55 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p56 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(16,3););
printStats();
void* p58 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p59 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p60 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p61 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p62 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p63 = last_address;
DEBUG_PRINT(sfree(p44););
printStats();
PRINT_POINTER(smalloc(59););
printStats();
void* p64 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(scalloc(162,72););
printStats();
void* p65 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p66 = last_address;
PRINT_POINTER(scalloc(85,103););
printStats();
void* p67 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p39,242););
printStats();
void* p69 = last_address;
PRINT_POINTER(srealloc(p42,165););
printStats();
void* p70 = last_address;
PRINT_POINTER(scalloc(167,64););
printStats();
void* p71 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
DEBUG_PRINT(sfree(p57););
printStats();
PRINT_POINTER(srealloc(p53,6););
printStats();
void* p72 = last_address;
PRINT_POINTER(scalloc(80,181););
printStats();
void* p73 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p74 = last_address;
PRINT_POINTER(scalloc(42,53););
printStats();
void* p75 = last_address;
DEBUG_PRINT(sfree(p73););
printStats();
PRINT_POINTER(smalloc(226););
printStats();
void* p76 = last_address;
PRINT_POINTER(srealloc(p68,169););
printStats();
void* p77 = last_address;
PRINT_POINTER(srealloc(p71,139););
printStats();
void* p78 = last_address;
PRINT_POINTER(srealloc(p78,34););
printStats();
void* p79 = last_address;
PRINT_POINTER(srealloc(p63,55););
printStats();
void* p80 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
DEBUG_PRINT(sfree(p79););
printStats();
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(smalloc(160););
printStats();
void* p81 = last_address;
PRINT_POINTER(srealloc(p48,15););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p83 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(scalloc(18,189););
printStats();
void* p84 = last_address;
DEBUG_PRINT(sfree(p54););
printStats();
PRINT_POINTER(srealloc(p62,247););
printStats();
void* p85 = last_address;
PRINT_POINTER(srealloc(p52,216););
printStats();
void* p86 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p87 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p88 = last_address;
DEBUG_PRINT(sfree(p81););
printStats();
PRINT_POINTER(srealloc(p66,51););
printStats();
void* p89 = last_address;
PRINT_POINTER(scalloc(73,50););
printStats();
void* p90 = last_address;
PRINT_POINTER(scalloc(102,200););
printStats();
void* p91 = last_address;
PRINT_POINTER(scalloc(42,93););
printStats();
void* p92 = last_address;
PRINT_POINTER(srealloc(p80,10););
printStats();
void* p93 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(scalloc(228,94););
printStats();
void* p94 = last_address;
PRINT_POINTER(srealloc(p47,147););
printStats();
void* p95 = last_address;
PRINT_POINTER(scalloc(129,118););
printStats();
void* p96 = last_address;
PRINT_POINTER(srealloc(p16,41););
printStats();
void* p97 = last_address;
PRINT_POINTER(smalloc(159););
printStats();
void* p98 = last_address;
PRINT_POINTER(scalloc(105,78););
printStats();
void* p99 = last_address;
PRINT_POINTER(scalloc(46,168););
printStats();
void* p100 = last_address;
PRINT_POINTER(scalloc(8,217););
printStats();
void* p101 = last_address;
PRINT_POINTER(scalloc(103,136););
printStats();
void* p102 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p96,164););
printStats();
void* p104 = last_address;
DEBUG_PRINT(sfree(p61););
printStats();
PRINT_POINTER(smalloc(173););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p83,16););
printStats();
void* p106 = last_address;
PRINT_POINTER(scalloc(229,181););
printStats();
void* p107 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(srealloc(p67,60););
printStats();
void* p108 = last_address;
PRINT_POINTER(srealloc(p97,218););
printStats();
void* p109 = last_address;
DEBUG_PRINT(sfree(p75););
printStats();
PRINT_POINTER(scalloc(214,64););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p65,10););
printStats();
void* p111 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
PRINT_POINTER(srealloc(p76,43););
printStats();
void* p112 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
DEBUG_PRINT(sfree(p55););
printStats();
DEBUG_PRINT(sfree(p25););
printStats();
DEBUG_PRINT(sfree(p104););
printStats();
DEBUG_PRINT(sfree(p64););
printStats();
DEBUG_PRINT(sfree(p74););
printStats();
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p113 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p114 = last_address;
DEBUG_PRINT(sfree(p92););
printStats();
PRINT_POINTER(scalloc(165,110););
printStats();
void* p115 = last_address;
PRINT_POINTER(scalloc(241,247););
printStats();
void* p116 = last_address;
PRINT_POINTER(srealloc(p88,120););
printStats();
void* p117 = last_address;
PRINT_POINTER(srealloc(p110,182););
printStats();
void* p118 = last_address;
PRINT_POINTER(srealloc(p99,229););
printStats();
void* p119 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p120 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p121 = last_address;
PRINT_POINTER(srealloc(p114,23););
printStats();
void* p122 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p123 = last_address;
PRINT_POINTER(scalloc(147,77););
printStats();
void* p124 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p125 = last_address;
PRINT_POINTER(srealloc(p118,25););
printStats();
void* p126 = last_address;
DEBUG_PRINT(sfree(p120););
printStats();
PRINT_POINTER(srealloc(p77,53););
printStats();
void* p127 = last_address;
PRINT_POINTER(srealloc(p82,231););
printStats();
void* p128 = last_address;
PRINT_POINTER(srealloc(p105,73););
printStats();
void* p129 = last_address;
PRINT_POINTER(scalloc(114,33););
printStats();
void* p130 = last_address;
PRINT_POINTER(srealloc(p95,146););
printStats();
void* p131 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p132 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p133 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p134 = last_address;
PRINT_POINTER(scalloc(155,78););
printStats();
void* p135 = last_address;
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(srealloc(p107,88););
printStats();
void* p136 = last_address;
DEBUG_PRINT(sfree(p125););
printStats();
PRINT_POINTER(srealloc(p131,184););
printStats();
void* p137 = last_address;
DEBUG_PRINT(sfree(p122););
printStats();
DEBUG_PRINT(sfree(p132););
printStats();
DEBUG_PRINT(sfree(p102););
printStats();
PRINT_POINTER(smalloc(70););
printStats();
void* p138 = last_address;
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(srealloc(p93,224););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p111););
printStats();
PRINT_POINTER(smalloc(241););
printStats();
void* p140 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(srealloc(p46,101););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p138,215););
printStats();
void* p142 = last_address;
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(smalloc(42););
printStats();
void* p143 = last_address;
PRINT_POINTER(srealloc(p124,191););
printStats();
void* p144 = last_address;
PRINT_POINTER(scalloc(238,146););
printStats();
void* p145 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(scalloc(8,103););
printStats();
void* p146 = last_address;
PRINT_POINTER(srealloc(p144,160););
printStats();
void* p147 = last_address;
PRINT_POINTER(scalloc(119,192););
printStats();
void* p148 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(scalloc(52,149););
printStats();
void* p149 = last_address;
PRINT_POINTER(scalloc(14,11););
printStats();
void* p150 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p151 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p152 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p153 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p154 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p155 = last_address;
PRINT_POINTER(scalloc(143,229););
printStats();
void* p156 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p157 = last_address;
DEBUG_PRINT(sfree(p137););
printStats();
PRINT_POINTER(srealloc(p151,172););
printStats();
void* p158 = last_address;
PRINT_POINTER(scalloc(98,94););
printStats();
void* p159 = last_address;
PRINT_POINTER(scalloc(22,208););
printStats();
void* p160 = last_address;
PRINT_POINTER(srealloc(p140,83););
printStats();
void* p161 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p162 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p163 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p164 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p165 = last_address;
DEBUG_PRINT(sfree(p115););
printStats();
PRINT_POINTER(scalloc(208,184););
printStats();
void* p166 = last_address;
PRINT_POINTER(scalloc(133,109););
printStats();
void* p167 = last_address;
PRINT_POINTER(scalloc(104,175););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(155,144););
printStats();
void* p169 = last_address;
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(scalloc(196,155););
printStats();
void* p170 = last_address;
PRINT_POINTER(srealloc(p153,3););
printStats();
void* p171 = last_address;
PRINT_POINTER(scalloc(128,114););
printStats();
void* p172 = last_address;
PRINT_POINTER(srealloc(p30,147););
printStats();
void* p173 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p174 = last_address;
DEBUG_PRINT(sfree(p112););
printStats();
PRINT_POINTER(scalloc(129,175););
printStats();
void* p175 = last_address;
PRINT_POINTER(scalloc(147,214););
printStats();
void* p176 = last_address;
PRINT_POINTER(srealloc(p26,210););
printStats();
void* p177 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p178 = last_address;
PRINT_POINTER(scalloc(11,76););
printStats();
void* p179 = last_address;
PRINT_POINTER(srealloc(p145,121););
printStats();
void* p180 = last_address;
PRINT_POINTER(srealloc(p148,65););
printStats();
void* p181 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p182 = last_address;
PRINT_POINTER(srealloc(p177,6););
printStats();
void* p183 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(smalloc(84););
printStats();
void* p184 = last_address;
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(srealloc(p157,119););
printStats();
void* p185 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
DEBUG_PRINT(sfree(p149););
printStats();
DEBUG_PRINT(sfree(p155););
printStats();
PRINT_POINTER(scalloc(152,198););
printStats();
void* p186 = last_address;
PRINT_POINTER(srealloc(p130,215););
printStats();
void* p187 = last_address;
PRINT_POINTER(scalloc(38,214););
printStats();
void* p188 = last_address;
PRINT_POINTER(srealloc(p94,127););
printStats();
void* p189 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p190 = last_address;
DEBUG_PRINT(sfree(p190););
printStats();
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(scalloc(206,120););
printStats();
void* p191 = last_address;
PRINT_POINTER(scalloc(168,224););
printStats();
void* p192 = last_address;
PRINT_POINTER(srealloc(p38,216););
printStats();
void* p193 = last_address;
PRINT_POINTER(srealloc(p158,151););
printStats();
void* p194 = last_address;
PRINT_POINTER(srealloc(p58,171););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
PRINT_POINTER(srealloc(p175,244););
printStats();
void* p196 = last_address;
PRINT_POINTER(srealloc(p119,73););
printStats();
void* p197 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p198 = last_address;
DEBUG_PRINT(sfree(p188););
printStats();
DEBUG_PRINT(sfree(p161););
printStats();
DEBUG_PRINT(sfree(p164););
printStats();
DEBUG_PRINT(sfree(p128););
printStats();
PRINT_POINTER(smalloc(12););
printStats();
void* p199 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p200 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
DEBUG_PRINT(sfree(p193););
printStats();
PRINT_POINTER(scalloc(249,225););
printStats();
void* p201 = last_address;
PRINT_POINTER(srealloc(p136,242););
printStats();
void* p202 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p203 = last_address;
PRINT_POINTER(scalloc(151,88););
printStats();
void* p204 = last_address;
PRINT_POINTER(scalloc(230,48););
printStats();
void* p205 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p206 = last_address;
PRINT_POINTER(scalloc(13,225););
printStats();
void* p207 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p208 = last_address;
PRINT_POINTER(srealloc(p203,19););
printStats();
void* p209 = last_address;
PRINT_POINTER(srealloc(p163,126););
printStats();
void* p210 = last_address;
DEBUG_PRINT(sfree(p178););
printStats();
DEBUG_PRINT(sfree(p108););
printStats();
PRINT_POINTER(srealloc(p198,21););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(41,98););
printStats();
void* p212 = last_address;
PRINT_POINTER(srealloc(p103,200););
printStats();
void* p213 = last_address;
DEBUG_PRINT(sfree(p211););
printStats();
PRINT_POINTER(smalloc(85););
printStats();
void* p214 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p215 = last_address;
PRINT_POINTER(scalloc(223,203););
printStats();
void* p216 = last_address;
PRINT_POINTER(srealloc(p200,212););
printStats();
void* p217 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p218 = last_address;
DEBUG_PRINT(sfree(p195););
printStats();
PRINT_POINTER(smalloc(205););
printStats();
void* p219 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p220 = last_address;
PRINT_POINTER(scalloc(20,65););
printStats();
void* p221 = last_address;
PRINT_POINTER(scalloc(127,163););
printStats();
void* p222 = last_address;
PRINT_POINTER(scalloc(209,224););
printStats();
void* p223 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p224 = last_address;
PRINT_POINTER(srealloc(p224,25););
printStats();
void* p225 = last_address;
PRINT_POINTER(scalloc(0,98););
printStats();
void* p226 = last_address;
PRINT_POINTER(srealloc(p221,8););
printStats();
void* p227 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p228 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p229 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p230 = last_address;
PRINT_POINTER(srealloc(p229,38););
printStats();
void* p231 = last_address;
PRINT_POINTER(srealloc(p117,142););
printStats();
void* p232 = last_address;
PRINT_POINTER(scalloc(51,84););
printStats();
void* p233 = last_address;
PRINT_POINTER(srealloc(p207,222););
printStats();
void* p234 = last_address;
DEBUG_PRINT(sfree(p183););
printStats();
PRINT_POINTER(smalloc(111););
printStats();
void* p235 = last_address;
DEBUG_PRINT(sfree(p213););
printStats();
PRINT_POINTER(scalloc(10,213););
printStats();
void* p236 = last_address;
DEBUG_PRINT(sfree(p189););
printStats();
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(scalloc(221,12););
printStats();
void* p237 = last_address;
PRINT_POINTER(srealloc(p225,226););
printStats();
void* p238 = last_address;
PRINT_POINTER(scalloc(27,65););
printStats();
void* p239 = last_address;
DEBUG_PRINT(sfree(p185););
printStats();
PRINT_POINTER(srealloc(p167,246););
printStats();
void* p240 = last_address;
PRINT_POINTER(srealloc(p160,197););
printStats();
void* p241 = last_address;
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(scalloc(125,186););
printStats();
void* p242 = last_address;
PRINT_POINTER(scalloc(230,167););
printStats();
void* p243 = last_address;
PRINT_POINTER(srealloc(p182,128););
printStats();
void* p244 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p245 = last_address;
PRINT_POINTER(srealloc(p186,56););
printStats();
void* p246 = last_address;
PRINT_POINTER(scalloc(147,171););
printStats();
void* p247 = last_address;
PRINT_POINTER(scalloc(118,121););
printStats();
void* p248 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(srealloc(p215,190););
printStats();
void* p249 = last_address;
PRINT_POINTER(srealloc(p231,220););
printStats();
void* p250 = last_address;
DEBUG_PRINT(sfree(p113););
printStats();
PRINT_POINTER(smalloc(233););
printStats();
void* p251 = last_address;
PRINT_POINTER(srealloc(p238,187););
printStats();
void* p252 = last_address;
PRINT_POINTER(scalloc(31,15););
printStats();
void* p253 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p254 = last_address;
DEBUG_PRINT(sfree(p252););
printStats();
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(smalloc(114););
printStats();
void* p255 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p256 = last_address;
DEBUG_PRINT(sfree(p245););
printStats();
PRINT_POINTER(scalloc(69,207););
printStats();
void* p257 = last_address;
DEBUG_PRINT(sfree(p233););
printStats();
PRINT_POINTER(smalloc(237););
printStats();
void* p258 = last_address;
PRINT_POINTER(scalloc(226,235););
printStats();
void* p259 = last_address;
PRINT_POINTER(srealloc(p222,94););
printStats();
void* p260 = last_address;
PRINT_POINTER(scalloc(144,124););
printStats();
void* p261 = last_address;
PRINT_POINTER(srealloc(p196,209););
printStats();
void* p262 = last_address;
PRINT_POINTER(scalloc(69,103););
printStats();
void* p263 = last_address;
PRINT_POINTER(scalloc(75,157););
printStats();
void* p264 = last_address;
DEBUG_PRINT(sfree(p237););
printStats();
PRINT_POINTER(scalloc(140,76););
printStats();
void* p265 = last_address;
PRINT_POINTER(srealloc(p184,0););
printStats();
void* p266 = last_address;
DEBUG_PRINT(sfree(p244););
printStats();
DEBUG_PRINT(sfree(p133););
printStats();
PRINT_POINTER(srealloc(p135,143););
printStats();
void* p267 = last_address;
PRINT_POINTER(scalloc(204,38););
printStats();
void* p268 = last_address;
PRINT_POINTER(scalloc(199,36););
printStats();
void* p269 = last_address;
PRINT_POINTER(srealloc(p220,166););
printStats();
void* p270 = last_address;
PRINT_POINTER(srealloc(p259,156););
printStats();
void* p271 = last_address;
PRINT_POINTER(srealloc(p235,147););
printStats();
void* p272 = last_address;
DEBUG_PRINT(sfree(p84););
printStats();
PRINT_POINTER(srealloc(p172,224););
printStats();
void* p273 = last_address;
PRINT_POINTER(scalloc(172,186););
printStats();
void* p274 = last_address;
PRINT_POINTER(srealloc(p191,79););
printStats();
void* p275 = last_address;
PRINT_POINTER(srealloc(p218,146););
printStats();
void* p276 = last_address;
PRINT_POINTER(srealloc(p206,218););
printStats();
void* p277 = last_address;
PRINT_POINTER(scalloc(66,193););
printStats();
void* p278 = last_address;
PRINT_POINTER(scalloc(65,241););
printStats();
void* p279 = last_address;
PRINT_POINTER(srealloc(p226,58););
printStats();
void* p280 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p281 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p282 = last_address;
DEBUG_PRINT(sfree(p265););
printStats();
PRINT_POINTER(scalloc(77,209););
printStats();
void* p283 = last_address;
DEBUG_PRINT(sfree(p243););
printStats();
PRINT_POINTER(scalloc(50,23););
printStats();
void* p284 = last_address;
DEBUG_PRINT(sfree(p129););
printStats();
PRINT_POINTER(srealloc(p281,119););
printStats();
void* p285 = last_address;
PRINT_POINTER(srealloc(p146,239););
printStats();
void* p286 = last_address;
DEBUG_PRINT(sfree(p165););
printStats();
DEBUG_PRINT(sfree(p194););
printStats();
PRINT_POINTER(scalloc(214,32););
printStats();
void* p287 = last_address;
PRINT_POINTER(srealloc(p121,4););
printStats();
void* p288 = last_address;
DEBUG_PRINT(sfree(p257););
printStats();
PRINT_POINTER(scalloc(24,186););
printStats();
void* p289 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p290 = last_address;
PRINT_POINTER(srealloc(p192,42););
printStats();
void* p291 = last_address;
PRINT_POINTER(srealloc(p276,202););
printStats();
void* p292 = last_address;
PRINT_POINTER(scalloc(32,43););
printStats();
void* p293 = last_address;
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(srealloc(p56,6););
printStats();
void* p294 = last_address;
DEBUG_PRINT(sfree(p162););
printStats();
PRINT_POINTER(smalloc(154););
printStats();
void* p295 = last_address;
DEBUG_PRINT(sfree(p242););
printStats();
PRINT_POINTER(srealloc(p248,128););
printStats();
void* p296 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p297 = last_address;
DEBUG_PRINT(sfree(p255););
printStats();
PRINT_POINTER(srealloc(p253,192););
printStats();
void* p298 = last_address;
PRINT_POINTER(srealloc(p214,101););
printStats();
void* p299 = last_address;
PRINT_POINTER(srealloc(p296,63););
printStats();
void* p300 = last_address;
DEBUG_PRINT(sfree(p179););
printStats();
PRINT_POINTER(smalloc(89););
printStats();
void* p301 = last_address;
PRINT_POINTER(srealloc(p171,30););
printStats();
void* p302 = last_address;
DEBUG_PRINT(sfree(p279););
printStats();
DEBUG_PRINT(sfree(p139););
printStats();
DEBUG_PRINT(sfree(p287););
printStats();
PRINT_POINTER(srealloc(p156,120););
printStats();
void* p303 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
PRINT_POINTER(srealloc(p106,186););
printStats();
void* p304 = last_address;
DEBUG_PRINT(sfree(p262););
printStats();
PRINT_POINTER(smalloc(61););
printStats();
void* p305 = last_address;
PRINT_POINTER(srealloc(p267,100););
printStats();
void* p306 = last_address;
PRINT_POINTER(scalloc(15,75););
printStats();
void* p307 = last_address;
PRINT_POINTER(scalloc(16,177););
printStats();
void* p308 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p309 = last_address;
PRINT_POINTER(scalloc(119,226););
printStats();
void* p310 = last_address;
PRINT_POINTER(srealloc(p240,160););
printStats();
void* p311 = last_address;
PRINT_POINTER(scalloc(64,189););
printStats();
void* p312 = last_address;
PRINT_POINTER(srealloc(p300,1););
printStats();
void* p313 = last_address;
PRINT_POINTER(srealloc(p202,104););
printStats();
void* p314 = last_address;
PRINT_POINTER(srealloc(p311,236););
printStats();
void* p315 = last_address;
PRINT_POINTER(srealloc(p310,164););
printStats();
void* p316 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p317 = last_address;
DEBUG_PRINT(sfree(p273););
printStats();
PRINT_POINTER(srealloc(p274,170););
printStats();
void* p318 = last_address;
PRINT_POINTER(srealloc(p285,231););
printStats();
void* p319 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p320 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p321 = last_address;
PRINT_POINTER(scalloc(192,32););
printStats();
void* p322 = last_address;
PRINT_POINTER(srealloc(p169,139););
printStats();
void* p323 = last_address;
PRINT_POINTER(scalloc(66,169););
printStats();
void* p324 = last_address;
DEBUG_PRINT(sfree(p280););
printStats();
DEBUG_PRINT(sfree(p154););
printStats();
PRINT_POINTER(srealloc(p278,106););
printStats();
void* p325 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p326 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p327 = last_address;
PRINT_POINTER(scalloc(92,19););
printStats();
void* p328 = last_address;
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(smalloc(187););
printStats();
void* p329 = last_address;
PRINT_POINTER(srealloc(p170,160););
printStats();
void* p330 = last_address;
PRINT_POINTER(srealloc(p297,130););
printStats();
void* p331 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p332 = last_address;
DEBUG_PRINT(sfree(p317););
printStats();
PRINT_POINTER(scalloc(100,96););
printStats();
void* p333 = last_address;
PRINT_POINTER(scalloc(214,107););
printStats();
void* p334 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
DEBUG_PRINT(sfree(p271););
printStats();
PRINT_POINTER(smalloc(16););
printStats();
void* p335 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p336 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
DEBUG_PRINT(sfree(p302););
printStats();
PRINT_POINTER(smalloc(172););
printStats();
void* p337 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p338 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p339 = last_address;
PRINT_POINTER(srealloc(p210,9););
printStats();
void* p340 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p341 = last_address;
PRINT_POINTER(smalloc(221););
printStats();
void* p342 = last_address;
PRINT_POINTER(srealloc(p299,147););
printStats();
void* p343 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
DEBUG_PRINT(sfree(p340););
printStats();
PRINT_POINTER(scalloc(234,33););
printStats();
void* p344 = last_address;
DEBUG_PRINT(sfree(p312););
printStats();
PRINT_POINTER(srealloc(p314,138););
printStats();
void* p345 = last_address;
DEBUG_PRINT(sfree(p328););
printStats();
DEBUG_PRINT(sfree(p291););
printStats();
PRINT_POINTER(srealloc(p286,231););
printStats();
void* p346 = last_address;
PRINT_POINTER(scalloc(162,87););
printStats();
void* p347 = last_address;
PRINT_POINTER(scalloc(144,174););
printStats();
void* p348 = last_address;
PRINT_POINTER(srealloc(p261,200););
printStats();
void* p349 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p350 = last_address;
PRINT_POINTER(srealloc(p263,116););
printStats();
void* p351 = last_address;
PRINT_POINTER(srealloc(p87,26););
printStats();
void* p352 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p353 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p354 = last_address;
PRINT_POINTER(srealloc(p234,67););
printStats();
void* p355 = last_address;
PRINT_POINTER(scalloc(24,28););
printStats();
void* p356 = last_address;
PRINT_POINTER(scalloc(50,75););
printStats();
void* p357 = last_address;
PRINT_POINTER(scalloc(125,88););
printStats();
void* p358 = last_address;
PRINT_POINTER(srealloc(p258,235););
printStats();
void* p359 = last_address;
PRINT_POINTER(scalloc(110,69););
printStats();
void* p360 = last_address;
PRINT_POINTER(scalloc(199,136););
printStats();
void* p361 = last_address;
PRINT_POINTER(scalloc(218,238););
printStats();
void* p362 = last_address;
DEBUG_PRINT(sfree(p264););
printStats();
PRINT_POINTER(smalloc(55););
printStats();
void* p363 = last_address;
DEBUG_PRINT(sfree(p335););
printStats();
PRINT_POINTER(scalloc(223,89););
printStats();
void* p364 = last_address;
DEBUG_PRINT(sfree(p333););
printStats();
PRINT_POINTER(scalloc(20,220););
printStats();
void* p365 = last_address;
PRINT_POINTER(scalloc(145,95););
printStats();
void* p366 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p367 = last_address;
PRINT_POINTER(srealloc(p241,63););
printStats();
void* p368 = last_address;
PRINT_POINTER(srealloc(p212,174););
printStats();
void* p369 = last_address;
PRINT_POINTER(srealloc(p331,239););
printStats();
void* p370 = last_address;
PRINT_POINTER(srealloc(p284,144););
printStats();
void* p371 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p372 = last_address;
PRINT_POINTER(scalloc(129,192););
printStats();
void* p373 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p374 = last_address;
PRINT_POINTER(scalloc(142,4););
printStats();
void* p375 = last_address;
PRINT_POINTER(srealloc(p375,232););
printStats();
void* p376 = last_address;
PRINT_POINTER(srealloc(p316,93););
printStats();
void* p377 = last_address;
PRINT_POINTER(srealloc(p355,171););
printStats();
void* p378 = last_address;
PRINT_POINTER(scalloc(88,208););
printStats();
void* p379 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p380 = last_address;
PRINT_POINTER(srealloc(p342,238););
printStats();
void* p381 = last_address;
PRINT_POINTER(srealloc(p266,16););
printStats();
void* p382 = last_address;
PRINT_POINTER(scalloc(81,244););
printStats();
void* p383 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p384 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p385 = last_address;
PRINT_POINTER(scalloc(177,139););
printStats();
void* p386 = last_address;
PRINT_POINTER(scalloc(205,232););
printStats();
void* p387 = last_address;
PRINT_POINTER(srealloc(p341,63););
printStats();
void* p388 = last_address;
PRINT_POINTER(srealloc(p324,43););
printStats();
void* p389 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p390 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p391 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(scalloc(54,148););
printStats();
void* p392 = last_address;
DEBUG_PRINT(sfree(p201););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p393 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p394 = last_address;
PRINT_POINTER(srealloc(p277,4););
printStats();
void* p395 = last_address;
PRINT_POINTER(srealloc(p208,118););
printStats();
void* p396 = last_address;
PRINT_POINTER(srealloc(p247,21););
printStats();
void* p397 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p398 = last_address;
PRINT_POINTER(srealloc(p387,108););
printStats();
void* p399 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p400 = last_address;
DEBUG_PRINT(sfree(p319););
printStats();
PRINT_POINTER(scalloc(29,238););
printStats();
void* p401 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p402 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p403 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p404 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p405 = last_address;
PRINT_POINTER(srealloc(p336,185););
printStats();
void* p406 = last_address;
PRINT_POINTER(srealloc(p321,17););
printStats();
void* p407 = last_address;
PRINT_POINTER(scalloc(58,2););
printStats();
void* p408 = last_address;
PRINT_POINTER(scalloc(174,141););
printStats();
void* p409 = last_address;
DEBUG_PRINT(sfree(p187););
printStats();
PRINT_POINTER(srealloc(p390,173););
printStats();
void* p410 = last_address;
PRINT_POINTER(scalloc(195,124););
printStats();
void* p411 = last_address;
PRINT_POINTER(scalloc(37,160););
printStats();
void* p412 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p413 = last_address;
PRINT_POINTER(srealloc(p327,208););
printStats();
void* p414 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p415 = last_address;
DEBUG_PRINT(sfree(p366););
printStats();
PRINT_POINTER(scalloc(158,118););
printStats();
void* p416 = last_address;
PRINT_POINTER(srealloc(p313,196););
printStats();
void* p417 = last_address;
PRINT_POINTER(scalloc(91,188););
printStats();
void* p418 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p419 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p420 = last_address;
PRINT_POINTER(srealloc(p150,35););
printStats();
void* p421 = last_address;
PRINT_POINTER(srealloc(p254,74););
printStats();
void* p422 = last_address;
PRINT_POINTER(srealloc(p180,169););
printStats();
void* p423 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p424 = last_address;
DEBUG_PRINT(sfree(p359););
printStats();
DEBUG_PRINT(sfree(p408););
printStats();
PRINT_POINTER(srealloc(p353,58););
printStats();
void* p425 = last_address;
PRINT_POINTER(scalloc(105,15););
printStats();
void* p426 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p427 = last_address;
PRINT_POINTER(srealloc(p230,119););
printStats();
void* p428 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
PRINT_POINTER(scalloc(185,35););
printStats();
void* p429 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p430 = last_address;
PRINT_POINTER(srealloc(p343,128););
printStats();
void* p431 = last_address;
PRINT_POINTER(scalloc(33,207););
printStats();
void* p432 = last_address;
PRINT_POINTER(scalloc(91,145););
printStats();
void* p433 = last_address;
PRINT_POINTER(srealloc(p349,3););
printStats();
void* p434 = last_address;
DEBUG_PRINT(sfree(p412););
printStats();
}
