#include "aux_macro.h"
#include "../malloc_2.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(207););
printStats();
void* p0 = last_address;
PRINT_POINTER(srealloc(p0,11););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(scalloc(173,21););
printStats();
void* p2 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(scalloc(57,24););
printStats();
void* p3 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p4 = last_address;
PRINT_POINTER(scalloc(65,144););
printStats();
void* p5 = last_address;
PRINT_POINTER(srealloc(p4,246););
printStats();
void* p6 = last_address;
PRINT_POINTER(scalloc(103,53););
printStats();
void* p7 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(smalloc(83););
printStats();
void* p8 = last_address;
PRINT_POINTER(srealloc(p6,173););
printStats();
void* p9 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(srealloc(p3,103););
printStats();
void* p10 = last_address;
PRINT_POINTER(srealloc(p9,133););
printStats();
void* p11 = last_address;
DEBUG_PRINT(sfree(p10););
printStats();
PRINT_POINTER(smalloc(246););
printStats();
void* p12 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p13 = last_address;
PRINT_POINTER(srealloc(p11,96););
printStats();
void* p14 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p15 = last_address;
PRINT_POINTER(srealloc(p14,210););
printStats();
void* p16 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p17 = last_address;
DEBUG_PRINT(sfree(p12););
printStats();
PRINT_POINTER(smalloc(245););
printStats();
void* p18 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p19 = last_address;
PRINT_POINTER(scalloc(229,40););
printStats();
void* p20 = last_address;
PRINT_POINTER(srealloc(p15,124););
printStats();
void* p21 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p22 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(srealloc(p13,11););
printStats();
void* p23 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p24 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(62,103););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p19,226););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(smalloc(124););
printStats();
void* p28 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
PRINT_POINTER(scalloc(142,12););
printStats();
void* p29 = last_address;
PRINT_POINTER(scalloc(235,183););
printStats();
void* p30 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p31 = last_address;
PRINT_POINTER(srealloc(p20,19););
printStats();
void* p32 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p33 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p34 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p35 = last_address;
DEBUG_PRINT(sfree(p35););
printStats();
PRINT_POINTER(srealloc(p29,105););
printStats();
void* p36 = last_address;
PRINT_POINTER(srealloc(p32,163););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(42,2););
printStats();
void* p38 = last_address;
PRINT_POINTER(scalloc(103,32););
printStats();
void* p39 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p40 = last_address;
PRINT_POINTER(scalloc(145,83););
printStats();
void* p41 = last_address;
PRINT_POINTER(srealloc(p34,25););
printStats();
void* p42 = last_address;
PRINT_POINTER(scalloc(58,101););
printStats();
void* p43 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p44 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p45 = last_address;
PRINT_POINTER(scalloc(42,17););
printStats();
void* p46 = last_address;
PRINT_POINTER(srealloc(p38,65););
printStats();
void* p47 = last_address;
PRINT_POINTER(srealloc(p26,228););
printStats();
void* p48 = last_address;
DEBUG_PRINT(sfree(p47););
printStats();
PRINT_POINTER(scalloc(202,158););
printStats();
void* p49 = last_address;
PRINT_POINTER(srealloc(p21,104););
printStats();
void* p50 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p51 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p52 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(scalloc(127,220););
printStats();
void* p53 = last_address;
PRINT_POINTER(srealloc(p40,69););
printStats();
void* p54 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p55 = last_address;
PRINT_POINTER(scalloc(140,95););
printStats();
void* p56 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p57 = last_address;
DEBUG_PRINT(sfree(p48););
printStats();
DEBUG_PRINT(sfree(p54););
printStats();
PRINT_POINTER(scalloc(12,137););
printStats();
void* p58 = last_address;
PRINT_POINTER(srealloc(p37,48););
printStats();
void* p59 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
DEBUG_PRINT(sfree(p23););
printStats();
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(smalloc(23););
printStats();
void* p60 = last_address;
PRINT_POINTER(scalloc(88,148););
printStats();
void* p61 = last_address;
PRINT_POINTER(srealloc(p31,185););
printStats();
void* p62 = last_address;
PRINT_POINTER(srealloc(p16,244););
printStats();
void* p63 = last_address;
PRINT_POINTER(srealloc(p53,144););
printStats();
void* p64 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
PRINT_POINTER(srealloc(p52,45););
printStats();
void* p65 = last_address;
DEBUG_PRINT(sfree(p42););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p66 = last_address;
DEBUG_PRINT(sfree(p49););
printStats();
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(scalloc(19,56););
printStats();
void* p67 = last_address;
PRINT_POINTER(srealloc(p33,52););
printStats();
void* p68 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p69 = last_address;
PRINT_POINTER(scalloc(234,164););
printStats();
void* p70 = last_address;
PRINT_POINTER(scalloc(91,109););
printStats();
void* p71 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p72 = last_address;
PRINT_POINTER(scalloc(18,209););
printStats();
void* p73 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p74 = last_address;
PRINT_POINTER(scalloc(94,211););
printStats();
void* p75 = last_address;
PRINT_POINTER(scalloc(232,59););
printStats();
void* p76 = last_address;
PRINT_POINTER(srealloc(p75,123););
printStats();
void* p77 = last_address;
PRINT_POINTER(srealloc(p76,189););
printStats();
void* p78 = last_address;
PRINT_POINTER(scalloc(227,166););
printStats();
void* p79 = last_address;
PRINT_POINTER(scalloc(89,202););
printStats();
void* p80 = last_address;
PRINT_POINTER(scalloc(112,96););
printStats();
void* p81 = last_address;
PRINT_POINTER(scalloc(122,241););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p83 = last_address;
PRINT_POINTER(scalloc(70,229););
printStats();
void* p84 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p85 = last_address;
PRINT_POINTER(srealloc(p72,71););
printStats();
void* p86 = last_address;
DEBUG_PRINT(sfree(p73););
printStats();
PRINT_POINTER(scalloc(81,59););
printStats();
void* p87 = last_address;
DEBUG_PRINT(sfree(p62););
printStats();
PRINT_POINTER(smalloc(243););
printStats();
void* p88 = last_address;
PRINT_POINTER(scalloc(173,162););
printStats();
void* p89 = last_address;
DEBUG_PRINT(sfree(p67););
printStats();
PRINT_POINTER(scalloc(239,29););
printStats();
void* p90 = last_address;
PRINT_POINTER(scalloc(84,169););
printStats();
void* p91 = last_address;
PRINT_POINTER(scalloc(40,221););
printStats();
void* p92 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(smalloc(231););
printStats();
void* p93 = last_address;
PRINT_POINTER(scalloc(9,91););
printStats();
void* p94 = last_address;
DEBUG_PRINT(sfree(p65););
printStats();
PRINT_POINTER(smalloc(45););
printStats();
void* p95 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p96 = last_address;
DEBUG_PRINT(sfree(p27););
printStats();
PRINT_POINTER(srealloc(p77,4););
printStats();
void* p97 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p98 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p99 = last_address;
PRINT_POINTER(srealloc(p96,196););
printStats();
void* p100 = last_address;
DEBUG_PRINT(sfree(p99););
printStats();
PRINT_POINTER(smalloc(111););
printStats();
void* p101 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p102 = last_address;
DEBUG_PRINT(sfree(p88););
printStats();
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(smalloc(30););
printStats();
void* p103 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p104 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p105 = last_address;
PRINT_POINTER(scalloc(69,150););
printStats();
void* p106 = last_address;
PRINT_POINTER(srealloc(p80,105););
printStats();
void* p107 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
PRINT_POINTER(srealloc(p98,164););
printStats();
void* p108 = last_address;
PRINT_POINTER(scalloc(213,169););
printStats();
void* p109 = last_address;
PRINT_POINTER(srealloc(p90,49););
printStats();
void* p110 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p111 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p58,4););
printStats();
void* p113 = last_address;
PRINT_POINTER(scalloc(80,37););
printStats();
void* p114 = last_address;
PRINT_POINTER(scalloc(216,112););
printStats();
void* p115 = last_address;
PRINT_POINTER(scalloc(10,238););
printStats();
void* p116 = last_address;
PRINT_POINTER(srealloc(p110,249););
printStats();
void* p117 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(scalloc(117,240););
printStats();
void* p118 = last_address;
DEBUG_PRINT(sfree(p105););
printStats();
PRINT_POINTER(scalloc(92,143););
printStats();
void* p119 = last_address;
DEBUG_PRINT(sfree(p56););
printStats();
DEBUG_PRINT(sfree(p87););
printStats();
DEBUG_PRINT(sfree(p115););
printStats();
PRINT_POINTER(scalloc(29,64););
printStats();
void* p120 = last_address;
DEBUG_PRINT(sfree(p44););
printStats();
PRINT_POINTER(srealloc(p82,42););
printStats();
void* p121 = last_address;
PRINT_POINTER(scalloc(134,54););
printStats();
void* p122 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p123 = last_address;
PRINT_POINTER(srealloc(p74,38););
printStats();
void* p124 = last_address;
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(srealloc(p124,212););
printStats();
void* p125 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(186,200););
printStats();
void* p127 = last_address;
PRINT_POINTER(srealloc(p113,115););
printStats();
void* p128 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p129 = last_address;
PRINT_POINTER(scalloc(131,145););
printStats();
void* p130 = last_address;
PRINT_POINTER(srealloc(p121,110););
printStats();
void* p131 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p132 = last_address;
PRINT_POINTER(scalloc(203,31););
printStats();
void* p133 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p134 = last_address;
PRINT_POINTER(srealloc(p100,17););
printStats();
void* p135 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(srealloc(p84,73););
printStats();
void* p136 = last_address;
DEBUG_PRINT(sfree(p133););
printStats();
PRINT_POINTER(smalloc(83););
printStats();
void* p137 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p138 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(srealloc(p71,245););
printStats();
void* p140 = last_address;
DEBUG_PRINT(sfree(p122););
printStats();
PRINT_POINTER(srealloc(p140,123););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p126,171););
printStats();
void* p142 = last_address;
PRINT_POINTER(scalloc(45,181););
printStats();
void* p143 = last_address;
DEBUG_PRINT(sfree(p120););
printStats();
PRINT_POINTER(srealloc(p70,183););
printStats();
void* p144 = last_address;
DEBUG_PRINT(sfree(p106););
printStats();
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(scalloc(149,148););
printStats();
void* p145 = last_address;
PRINT_POINTER(srealloc(p83,208););
printStats();
void* p146 = last_address;
PRINT_POINTER(srealloc(p144,162););
printStats();
void* p147 = last_address;
PRINT_POINTER(scalloc(44,104););
printStats();
void* p148 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
DEBUG_PRINT(sfree(p135););
printStats();
PRINT_POINTER(scalloc(188,186););
printStats();
void* p149 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
PRINT_POINTER(srealloc(p91,187););
printStats();
void* p150 = last_address;
PRINT_POINTER(scalloc(110,77););
printStats();
void* p151 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p152 = last_address;
PRINT_POINTER(srealloc(p36,30););
printStats();
void* p153 = last_address;
DEBUG_PRINT(sfree(p125););
printStats();
PRINT_POINTER(srealloc(p85,30););
printStats();
void* p154 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p155 = last_address;
PRINT_POINTER(srealloc(p57,201););
printStats();
void* p156 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p157 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p158 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
DEBUG_PRINT(sfree(p112););
printStats();
PRINT_POINTER(scalloc(35,191););
printStats();
void* p159 = last_address;
DEBUG_PRINT(sfree(p61););
printStats();
PRINT_POINTER(srealloc(p93,211););
printStats();
void* p160 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p161 = last_address;
PRINT_POINTER(srealloc(p129,25););
printStats();
void* p162 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p163 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p164 = last_address;
PRINT_POINTER(scalloc(179,147););
printStats();
void* p165 = last_address;
PRINT_POINTER(srealloc(p63,10););
printStats();
void* p166 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p167 = last_address;
DEBUG_PRINT(sfree(p141););
printStats();
PRINT_POINTER(scalloc(186,4););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(14,62););
printStats();
void* p169 = last_address;
PRINT_POINTER(scalloc(31,224););
printStats();
void* p170 = last_address;
PRINT_POINTER(scalloc(48,117););
printStats();
void* p171 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p172 = last_address;
PRINT_POINTER(scalloc(3,216););
printStats();
void* p173 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p174 = last_address;
PRINT_POINTER(srealloc(p169,173););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p164););
printStats();
PRINT_POINTER(srealloc(p139,68););
printStats();
void* p176 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(smalloc(169););
printStats();
void* p177 = last_address;
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(smalloc(242););
printStats();
void* p178 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p179 = last_address;
PRINT_POINTER(scalloc(116,62););
printStats();
void* p180 = last_address;
PRINT_POINTER(srealloc(p179,111););
printStats();
void* p181 = last_address;
PRINT_POINTER(srealloc(p107,222););
printStats();
void* p182 = last_address;
PRINT_POINTER(srealloc(p152,98););
printStats();
void* p183 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p184 = last_address;
DEBUG_PRINT(sfree(p117););
printStats();
PRINT_POINTER(smalloc(162););
printStats();
void* p185 = last_address;
PRINT_POINTER(srealloc(p171,44););
printStats();
void* p186 = last_address;
DEBUG_PRINT(sfree(p149););
printStats();
DEBUG_PRINT(sfree(p158););
printStats();
DEBUG_PRINT(sfree(p172););
printStats();
PRINT_POINTER(srealloc(p128,34););
printStats();
void* p187 = last_address;
DEBUG_PRINT(sfree(p30););
printStats();
PRINT_POINTER(smalloc(207););
printStats();
void* p188 = last_address;
PRINT_POINTER(srealloc(p162,87););
printStats();
void* p189 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p191 = last_address;
PRINT_POINTER(srealloc(p167,220););
printStats();
void* p192 = last_address;
PRINT_POINTER(srealloc(p136,54););
printStats();
void* p193 = last_address;
DEBUG_PRINT(sfree(p174););
printStats();
PRINT_POINTER(srealloc(p108,106););
printStats();
void* p194 = last_address;
PRINT_POINTER(scalloc(74,1););
printStats();
void* p195 = last_address;
PRINT_POINTER(scalloc(234,68););
printStats();
void* p196 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p197 = last_address;
PRINT_POINTER(srealloc(p50,233););
printStats();
void* p198 = last_address;
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(srealloc(p104,65););
printStats();
void* p199 = last_address;
PRINT_POINTER(srealloc(p131,238););
printStats();
void* p200 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p201 = last_address;
PRINT_POINTER(scalloc(137,153););
printStats();
void* p202 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p203 = last_address;
PRINT_POINTER(scalloc(67,150););
printStats();
void* p204 = last_address;
DEBUG_PRINT(sfree(p201););
printStats();
DEBUG_PRINT(sfree(p194););
printStats();
PRINT_POINTER(srealloc(p178,219););
printStats();
void* p205 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(srealloc(p68,242););
printStats();
void* p206 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(smalloc(157););
printStats();
void* p207 = last_address;
DEBUG_PRINT(sfree(p130););
printStats();
PRINT_POINTER(smalloc(39););
printStats();
void* p208 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(scalloc(150,53););
printStats();
void* p209 = last_address;
PRINT_POINTER(srealloc(p25,187););
printStats();
void* p210 = last_address;
PRINT_POINTER(scalloc(64,72););
printStats();
void* p211 = last_address;
DEBUG_PRINT(sfree(p193););
printStats();
PRINT_POINTER(srealloc(p192,16););
printStats();
void* p212 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p213 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p214 = last_address;
PRINT_POINTER(scalloc(109,155););
printStats();
void* p215 = last_address;
PRINT_POINTER(srealloc(p207,20););
printStats();
void* p216 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
PRINT_POINTER(scalloc(246,62););
printStats();
void* p217 = last_address;
PRINT_POINTER(scalloc(41,28););
printStats();
void* p218 = last_address;
PRINT_POINTER(srealloc(p185,126););
printStats();
void* p219 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p220 = last_address;
DEBUG_PRINT(sfree(p189););
printStats();
PRINT_POINTER(smalloc(107););
printStats();
void* p221 = last_address;
DEBUG_PRINT(sfree(p161););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p222 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p223 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p224 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p225 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p226 = last_address;
PRINT_POINTER(srealloc(p191,223););
printStats();
void* p227 = last_address;
PRINT_POINTER(srealloc(p97,195););
printStats();
void* p228 = last_address;
PRINT_POINTER(scalloc(108,102););
printStats();
void* p229 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p230 = last_address;
DEBUG_PRINT(sfree(p202););
printStats();
DEBUG_PRINT(sfree(p103););
printStats();
PRINT_POINTER(srealloc(p228,57););
printStats();
void* p231 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p232 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p233 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(srealloc(p226,37););
printStats();
void* p234 = last_address;
PRINT_POINTER(srealloc(p138,65););
printStats();
void* p235 = last_address;
DEBUG_PRINT(sfree(p154););
printStats();
PRINT_POINTER(smalloc(1););
printStats();
void* p236 = last_address;
PRINT_POINTER(srealloc(p181,130););
printStats();
void* p237 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p55,196););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p153,135););
printStats();
void* p240 = last_address;
PRINT_POINTER(scalloc(177,151););
printStats();
void* p241 = last_address;
PRINT_POINTER(srealloc(p227,231););
printStats();
void* p242 = last_address;
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(srealloc(p224,196););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(smalloc(82););
printStats();
void* p244 = last_address;
PRINT_POINTER(scalloc(225,204););
printStats();
void* p245 = last_address;
PRINT_POINTER(srealloc(p236,90););
printStats();
void* p246 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
DEBUG_PRINT(sfree(p196););
printStats();
PRINT_POINTER(srealloc(p142,208););
printStats();
void* p247 = last_address;
PRINT_POINTER(srealloc(p247,10););
printStats();
void* p248 = last_address;
PRINT_POINTER(srealloc(p200,85););
printStats();
void* p249 = last_address;
PRINT_POINTER(scalloc(52,135););
printStats();
void* p250 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(scalloc(237,173););
printStats();
void* p251 = last_address;
PRINT_POINTER(srealloc(p148,207););
printStats();
void* p252 = last_address;
PRINT_POINTER(srealloc(p160,0););
printStats();
void* p253 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p254 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p255 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(smalloc(128););
printStats();
void* p256 = last_address;
PRINT_POINTER(srealloc(p222,2););
printStats();
void* p257 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p258 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p259 = last_address;
PRINT_POINTER(srealloc(p238,61););
printStats();
void* p260 = last_address;
PRINT_POINTER(scalloc(226,164););
printStats();
void* p261 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p262 = last_address;
DEBUG_PRINT(sfree(p208););
printStats();
PRINT_POINTER(scalloc(231,166););
printStats();
void* p263 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p264 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p265 = last_address;
PRINT_POINTER(scalloc(38,189););
printStats();
void* p266 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p267 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p268 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p269 = last_address;
DEBUG_PRINT(sfree(p232););
printStats();
DEBUG_PRINT(sfree(p268););
printStats();
PRINT_POINTER(smalloc(141););
printStats();
void* p270 = last_address;
DEBUG_PRINT(sfree(p230););
printStats();
PRINT_POINTER(smalloc(111););
printStats();
void* p271 = last_address;
PRINT_POINTER(srealloc(p137,91););
printStats();
void* p272 = last_address;
PRINT_POINTER(scalloc(237,167););
printStats();
void* p273 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p274 = last_address;
PRINT_POINTER(srealloc(p212,128););
printStats();
void* p275 = last_address;
PRINT_POINTER(scalloc(167,136););
printStats();
void* p276 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p277 = last_address;
PRINT_POINTER(srealloc(p204,244););
printStats();
void* p278 = last_address;
PRINT_POINTER(srealloc(p248,165););
printStats();
void* p279 = last_address;
PRINT_POINTER(scalloc(186,189););
printStats();
void* p280 = last_address;
PRINT_POINTER(srealloc(p266,230););
printStats();
void* p281 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p282 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p283 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p269,16););
printStats();
void* p285 = last_address;
DEBUG_PRINT(sfree(p263););
printStats();
PRINT_POINTER(scalloc(164,143););
printStats();
void* p286 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(srealloc(p234,238););
printStats();
void* p287 = last_address;
PRINT_POINTER(scalloc(236,130););
printStats();
void* p288 = last_address;
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(srealloc(p216,189););
printStats();
void* p289 = last_address;
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(srealloc(p241,112););
printStats();
void* p290 = last_address;
DEBUG_PRINT(sfree(p183););
printStats();
PRINT_POINTER(scalloc(244,82););
printStats();
void* p291 = last_address;
PRINT_POINTER(scalloc(65,48););
printStats();
void* p292 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p293 = last_address;
PRINT_POINTER(srealloc(p275,147););
printStats();
void* p294 = last_address;
PRINT_POINTER(srealloc(p294,28););
printStats();
void* p295 = last_address;
DEBUG_PRINT(sfree(p249););
printStats();
PRINT_POINTER(smalloc(50););
printStats();
void* p296 = last_address;
PRINT_POINTER(srealloc(p237,244););
printStats();
void* p297 = last_address;
PRINT_POINTER(srealloc(p270,182););
printStats();
void* p298 = last_address;
PRINT_POINTER(scalloc(160,178););
printStats();
void* p299 = last_address;
PRINT_POINTER(srealloc(p51,111););
printStats();
void* p300 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p301 = last_address;
PRINT_POINTER(srealloc(p211,79););
printStats();
void* p302 = last_address;
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(smalloc(73););
printStats();
void* p303 = last_address;
DEBUG_PRINT(sfree(p195););
printStats();
DEBUG_PRINT(sfree(p292););
printStats();
PRINT_POINTER(smalloc(203););
printStats();
void* p304 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p305 = last_address;
PRINT_POINTER(srealloc(p156,58););
printStats();
void* p306 = last_address;
PRINT_POINTER(srealloc(p218,225););
printStats();
void* p307 = last_address;
PRINT_POINTER(scalloc(78,133););
printStats();
void* p308 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p309 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p310 = last_address;
PRINT_POINTER(scalloc(101,47););
printStats();
void* p311 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p312 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p313 = last_address;
PRINT_POINTER(srealloc(p290,208););
printStats();
void* p314 = last_address;
PRINT_POINTER(scalloc(227,226););
printStats();
void* p315 = last_address;
DEBUG_PRINT(sfree(p177););
printStats();
PRINT_POINTER(smalloc(207););
printStats();
void* p316 = last_address;
PRINT_POINTER(srealloc(p308,81););
printStats();
void* p317 = last_address;
}
