#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(85,43););
printStats();
void* p0 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p1 = last_address;
PRINT_POINTER(srealloc(p1,214););
printStats();
void* p2 = last_address;
PRINT_POINTER(scalloc(84,129););
printStats();
void* p3 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p4 = last_address;
DEBUG_PRINT(sfree(p3););
printStats();
PRINT_POINTER(scalloc(219,47););
printStats();
void* p5 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p6 = last_address;
PRINT_POINTER(srealloc(p0,242););
printStats();
void* p7 = last_address;
PRINT_POINTER(scalloc(94,34););
printStats();
void* p8 = last_address;
PRINT_POINTER(srealloc(p8,31););
printStats();
void* p9 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p10 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(121,104););
printStats();
void* p12 = last_address;
DEBUG_PRINT(sfree(p9););
printStats();
PRINT_POINTER(scalloc(96,235););
printStats();
void* p13 = last_address;
PRINT_POINTER(srealloc(p4,232););
printStats();
void* p14 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p15 = last_address;
DEBUG_PRINT(sfree(p10););
printStats();
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(smalloc(213););
printStats();
void* p16 = last_address;
PRINT_POINTER(srealloc(p15,193););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(93,172););
printStats();
void* p18 = last_address;
PRINT_POINTER(srealloc(p7,9););
printStats();
void* p19 = last_address;
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(scalloc(142,80););
printStats();
void* p20 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p21 = last_address;
PRINT_POINTER(scalloc(76,105););
printStats();
void* p22 = last_address;
PRINT_POINTER(scalloc(204,208););
printStats();
void* p23 = last_address;
PRINT_POINTER(scalloc(12,1););
printStats();
void* p24 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(93,16););
printStats();
void* p26 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
DEBUG_PRINT(sfree(p25););
printStats();
PRINT_POINTER(srealloc(p5,161););
printStats();
void* p27 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p28 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p29 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p30 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p31 = last_address;
PRINT_POINTER(srealloc(p18,198););
printStats();
void* p32 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(smalloc(152););
printStats();
void* p33 = last_address;
DEBUG_PRINT(sfree(p30););
printStats();
PRINT_POINTER(smalloc(191););
printStats();
void* p34 = last_address;
PRINT_POINTER(scalloc(180,119););
printStats();
void* p35 = last_address;
PRINT_POINTER(scalloc(81,124););
printStats();
void* p36 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(srealloc(p27,181););
printStats();
void* p37 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p38 = last_address;
PRINT_POINTER(scalloc(65,53););
printStats();
void* p39 = last_address;
PRINT_POINTER(scalloc(163,121););
printStats();
void* p40 = last_address;
PRINT_POINTER(scalloc(29,79););
printStats();
void* p41 = last_address;
PRINT_POINTER(srealloc(p29,82););
printStats();
void* p42 = last_address;
PRINT_POINTER(scalloc(1,91););
printStats();
void* p43 = last_address;
DEBUG_PRINT(sfree(p14););
printStats();
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(srealloc(p42,132););
printStats();
void* p44 = last_address;
PRINT_POINTER(srealloc(p41,86););
printStats();
void* p45 = last_address;
PRINT_POINTER(scalloc(94,32););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p47 = last_address;
PRINT_POINTER(srealloc(p12,202););
printStats();
void* p48 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(scalloc(162,87););
printStats();
void* p49 = last_address;
PRINT_POINTER(scalloc(70,23););
printStats();
void* p50 = last_address;
PRINT_POINTER(srealloc(p19,164););
printStats();
void* p51 = last_address;
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(scalloc(241,137););
printStats();
void* p52 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(scalloc(39,221););
printStats();
void* p53 = last_address;
PRINT_POINTER(srealloc(p28,22););
printStats();
void* p54 = last_address;
PRINT_POINTER(scalloc(26,53););
printStats();
void* p55 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p56 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
PRINT_POINTER(srealloc(p35,91););
printStats();
void* p57 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p58 = last_address;
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(srealloc(p47,79););
printStats();
void* p59 = last_address;
PRINT_POINTER(scalloc(13,31););
printStats();
void* p60 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p61 = last_address;
PRINT_POINTER(scalloc(145,33););
printStats();
void* p62 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(smalloc(88););
printStats();
void* p63 = last_address;
DEBUG_PRINT(sfree(p56););
printStats();
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(scalloc(15,43););
printStats();
void* p64 = last_address;
DEBUG_PRINT(sfree(p49););
printStats();
PRINT_POINTER(smalloc(170););
printStats();
void* p65 = last_address;
PRINT_POINTER(scalloc(162,29););
printStats();
void* p66 = last_address;
PRINT_POINTER(srealloc(p52,145););
printStats();
void* p67 = last_address;
PRINT_POINTER(srealloc(p32,87););
printStats();
void* p68 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(srealloc(p51,51););
printStats();
void* p69 = last_address;
DEBUG_PRINT(sfree(p53););
printStats();
PRINT_POINTER(srealloc(p58,234););
printStats();
void* p70 = last_address;
PRINT_POINTER(scalloc(14,82););
printStats();
void* p71 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p72 = last_address;
PRINT_POINTER(srealloc(p26,2););
printStats();
void* p73 = last_address;
PRINT_POINTER(srealloc(p54,93););
printStats();
void* p74 = last_address;
PRINT_POINTER(srealloc(p69,88););
printStats();
void* p75 = last_address;
PRINT_POINTER(scalloc(217,131););
printStats();
void* p76 = last_address;
PRINT_POINTER(srealloc(p71,12););
printStats();
void* p77 = last_address;
PRINT_POINTER(srealloc(p38,155););
printStats();
void* p78 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
DEBUG_PRINT(sfree(p39););
printStats();
PRINT_POINTER(scalloc(27,86););
printStats();
void* p79 = last_address;
PRINT_POINTER(srealloc(p62,62););
printStats();
void* p80 = last_address;
PRINT_POINTER(srealloc(p72,155););
printStats();
void* p81 = last_address;
DEBUG_PRINT(sfree(p65););
printStats();
PRINT_POINTER(srealloc(p81,77););
printStats();
void* p82 = last_address;
PRINT_POINTER(srealloc(p13,215););
printStats();
void* p83 = last_address;
DEBUG_PRINT(sfree(p44););
printStats();
PRINT_POINTER(smalloc(40););
printStats();
void* p84 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p85 = last_address;
PRINT_POINTER(scalloc(193,220););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p63,24););
printStats();
void* p87 = last_address;
PRINT_POINTER(scalloc(126,175););
printStats();
void* p88 = last_address;
PRINT_POINTER(srealloc(p66,230););
printStats();
void* p89 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
DEBUG_PRINT(sfree(p87););
printStats();
PRINT_POINTER(scalloc(49,166););
printStats();
void* p90 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(smalloc(42););
printStats();
void* p91 = last_address;
DEBUG_PRINT(sfree(p82););
printStats();
DEBUG_PRINT(sfree(p23););
printStats();
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(scalloc(228,18););
printStats();
void* p92 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p93 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(srealloc(p79,51););
printStats();
void* p94 = last_address;
PRINT_POINTER(srealloc(p48,105););
printStats();
void* p95 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
PRINT_POINTER(srealloc(p70,168););
printStats();
void* p96 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
PRINT_POINTER(smalloc(193););
printStats();
void* p97 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
PRINT_POINTER(scalloc(99,87););
printStats();
void* p98 = last_address;
PRINT_POINTER(srealloc(p20,209););
printStats();
void* p99 = last_address;
PRINT_POINTER(scalloc(230,168););
printStats();
void* p100 = last_address;
PRINT_POINTER(srealloc(p78,174););
printStats();
void* p101 = last_address;
PRINT_POINTER(scalloc(186,30););
printStats();
void* p102 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p103 = last_address;
PRINT_POINTER(scalloc(191,248););
printStats();
void* p104 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p73,59););
printStats();
void* p106 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p107 = last_address;
PRINT_POINTER(scalloc(75,189););
printStats();
void* p108 = last_address;
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(smalloc(144););
printStats();
void* p109 = last_address;
DEBUG_PRINT(sfree(p84););
printStats();
PRINT_POINTER(srealloc(p68,134););
printStats();
void* p110 = last_address;
DEBUG_PRINT(sfree(p104););
printStats();
PRINT_POINTER(srealloc(p95,192););
printStats();
void* p111 = last_address;
PRINT_POINTER(scalloc(58,80););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p98,162););
printStats();
void* p113 = last_address;
DEBUG_PRINT(sfree(p107););
printStats();
PRINT_POINTER(smalloc(214););
printStats();
void* p114 = last_address;
PRINT_POINTER(scalloc(200,219););
printStats();
void* p115 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p116 = last_address;
DEBUG_PRINT(sfree(p96););
printStats();
PRINT_POINTER(smalloc(154););
printStats();
void* p117 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
DEBUG_PRINT(sfree(p103););
printStats();
PRINT_POINTER(srealloc(p116,186););
printStats();
void* p118 = last_address;
PRINT_POINTER(srealloc(p112,190););
printStats();
void* p119 = last_address;
DEBUG_PRINT(sfree(p67););
printStats();
PRINT_POINTER(scalloc(14,187););
printStats();
void* p120 = last_address;
DEBUG_PRINT(sfree(p16););
printStats();
DEBUG_PRINT(sfree(p109););
printStats();
DEBUG_PRINT(sfree(p105););
printStats();
DEBUG_PRINT(sfree(p120););
printStats();
PRINT_POINTER(scalloc(51,38););
printStats();
void* p121 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(srealloc(p115,170););
printStats();
void* p122 = last_address;
PRINT_POINTER(scalloc(179,11););
printStats();
void* p123 = last_address;
PRINT_POINTER(srealloc(p119,92););
printStats();
void* p124 = last_address;
PRINT_POINTER(srealloc(p102,173););
printStats();
void* p125 = last_address;
DEBUG_PRINT(sfree(p55););
printStats();
PRINT_POINTER(smalloc(4););
printStats();
void* p126 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p127 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p128 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p129 = last_address;
PRINT_POINTER(scalloc(243,189););
printStats();
void* p130 = last_address;
PRINT_POINTER(scalloc(241,26););
printStats();
void* p131 = last_address;
DEBUG_PRINT(sfree(p108););
printStats();
PRINT_POINTER(scalloc(141,236););
printStats();
void* p132 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p133 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p134 = last_address;
PRINT_POINTER(srealloc(p110,89););
printStats();
void* p135 = last_address;
PRINT_POINTER(scalloc(215,134););
printStats();
void* p136 = last_address;
PRINT_POINTER(scalloc(69,6););
printStats();
void* p137 = last_address;
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(srealloc(p137,99););
printStats();
void* p138 = last_address;
PRINT_POINTER(srealloc(p75,63););
printStats();
void* p139 = last_address;
PRINT_POINTER(scalloc(81,120););
printStats();
void* p140 = last_address;
PRINT_POINTER(srealloc(p124,98););
printStats();
void* p141 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p142 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p143 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p144 = last_address;
PRINT_POINTER(srealloc(p126,236););
printStats();
void* p145 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p146 = last_address;
PRINT_POINTER(scalloc(49,164););
printStats();
void* p147 = last_address;
PRINT_POINTER(scalloc(67,162););
printStats();
void* p148 = last_address;
DEBUG_PRINT(sfree(p135););
printStats();
PRINT_POINTER(srealloc(p111,88););
printStats();
void* p149 = last_address;
PRINT_POINTER(scalloc(225,25););
printStats();
void* p150 = last_address;
DEBUG_PRINT(sfree(p121););
printStats();
PRINT_POINTER(srealloc(p146,192););
printStats();
void* p151 = last_address;
PRINT_POINTER(srealloc(p113,248););
printStats();
void* p152 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p153 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(srealloc(p92,59););
printStats();
void* p154 = last_address;
PRINT_POINTER(scalloc(102,167););
printStats();
void* p155 = last_address;
PRINT_POINTER(srealloc(p57,227););
printStats();
void* p156 = last_address;
PRINT_POINTER(scalloc(118,244););
printStats();
void* p157 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p158 = last_address;
PRINT_POINTER(srealloc(p22,214););
printStats();
void* p159 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p160 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p161 = last_address;
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(srealloc(p76,167););
printStats();
void* p162 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p163 = last_address;
PRINT_POINTER(srealloc(p138,31););
printStats();
void* p164 = last_address;
PRINT_POINTER(scalloc(73,103););
printStats();
void* p165 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
PRINT_POINTER(scalloc(113,238););
printStats();
void* p166 = last_address;
PRINT_POINTER(srealloc(p153,215););
printStats();
void* p167 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p168 = last_address;
DEBUG_PRINT(sfree(p154););
printStats();
DEBUG_PRINT(sfree(p88););
printStats();
PRINT_POINTER(smalloc(90););
printStats();
void* p169 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p170 = last_address;
PRINT_POINTER(srealloc(p164,188););
printStats();
void* p171 = last_address;
DEBUG_PRINT(sfree(p169););
printStats();
PRINT_POINTER(srealloc(p117,184););
printStats();
void* p172 = last_address;
PRINT_POINTER(scalloc(34,118););
printStats();
void* p173 = last_address;
PRINT_POINTER(scalloc(53,22););
printStats();
void* p174 = last_address;
PRINT_POINTER(srealloc(p157,173););
printStats();
void* p175 = last_address;
DEBUG_PRINT(sfree(p145););
printStats();
PRINT_POINTER(scalloc(19,11););
printStats();
void* p176 = last_address;
PRINT_POINTER(scalloc(59,144););
printStats();
void* p177 = last_address;
PRINT_POINTER(srealloc(p156,87););
printStats();
void* p178 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(srealloc(p125,90););
printStats();
void* p179 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p180 = last_address;
PRINT_POINTER(scalloc(165,21););
printStats();
void* p181 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(smalloc(54););
printStats();
void* p182 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(194,83););
printStats();
void* p184 = last_address;
DEBUG_PRINT(sfree(p74););
printStats();
PRINT_POINTER(smalloc(100););
printStats();
void* p185 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p186 = last_address;
PRINT_POINTER(srealloc(p184,125););
printStats();
void* p187 = last_address;
PRINT_POINTER(scalloc(128,79););
printStats();
void* p188 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p189 = last_address;
DEBUG_PRINT(sfree(p180););
printStats();
PRINT_POINTER(scalloc(155,67););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p191 = last_address;
PRINT_POINTER(scalloc(65,5););
printStats();
void* p192 = last_address;
PRINT_POINTER(srealloc(p80,180););
printStats();
void* p193 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p194 = last_address;
DEBUG_PRINT(sfree(p182););
printStats();
DEBUG_PRINT(sfree(p181););
printStats();
PRINT_POINTER(scalloc(194,80););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p171););
printStats();
PRINT_POINTER(scalloc(97,157););
printStats();
void* p196 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p197 = last_address;
DEBUG_PRINT(sfree(p127););
printStats();
DEBUG_PRINT(sfree(p166););
printStats();
DEBUG_PRINT(sfree(p143););
printStats();
PRINT_POINTER(scalloc(194,239););
printStats();
void* p198 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p199 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p200 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
DEBUG_PRINT(sfree(p130););
printStats();
PRINT_POINTER(smalloc(139););
printStats();
void* p201 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p202 = last_address;
PRINT_POINTER(srealloc(p178,128););
printStats();
void* p203 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(srealloc(p99,184););
printStats();
void* p204 = last_address;
PRINT_POINTER(scalloc(219,105););
printStats();
void* p205 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p206 = last_address;
PRINT_POINTER(scalloc(218,208););
printStats();
void* p207 = last_address;
PRINT_POINTER(scalloc(220,202););
printStats();
void* p208 = last_address;
PRINT_POINTER(scalloc(18,213););
printStats();
void* p209 = last_address;
PRINT_POINTER(srealloc(p122,50););
printStats();
void* p210 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p211 = last_address;
PRINT_POINTER(srealloc(p204,38););
printStats();
void* p212 = last_address;
PRINT_POINTER(scalloc(17,6););
printStats();
void* p213 = last_address;
PRINT_POINTER(srealloc(p149,121););
printStats();
void* p214 = last_address;
PRINT_POINTER(scalloc(197,158););
printStats();
void* p215 = last_address;
DEBUG_PRINT(sfree(p158););
printStats();
PRINT_POINTER(smalloc(163););
printStats();
void* p216 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p217 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p218 = last_address;
PRINT_POINTER(scalloc(52,241););
printStats();
void* p219 = last_address;
PRINT_POINTER(srealloc(p142,186););
printStats();
void* p220 = last_address;
PRINT_POINTER(srealloc(p190,205););
printStats();
void* p221 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(srealloc(p93,248););
printStats();
void* p222 = last_address;
PRINT_POINTER(scalloc(214,36););
printStats();
void* p223 = last_address;
PRINT_POINTER(srealloc(p167,244););
printStats();
void* p224 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p225 = last_address;
PRINT_POINTER(scalloc(144,165););
printStats();
void* p226 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p227 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p228 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p229 = last_address;
DEBUG_PRINT(sfree(p229););
printStats();
PRINT_POINTER(scalloc(30,123););
printStats();
void* p230 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p231 = last_address;
PRINT_POINTER(scalloc(26,109););
printStats();
void* p232 = last_address;
PRINT_POINTER(srealloc(p218,50););
printStats();
void* p233 = last_address;
PRINT_POINTER(srealloc(p219,235););
printStats();
void* p234 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p235 = last_address;
PRINT_POINTER(srealloc(p231,57););
printStats();
void* p236 = last_address;
PRINT_POINTER(scalloc(92,205););
printStats();
void* p237 = last_address;
PRINT_POINTER(scalloc(13,241););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p185,134););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p188,163););
printStats();
void* p240 = last_address;
PRINT_POINTER(srealloc(p201,218););
printStats();
void* p241 = last_address;
DEBUG_PRINT(sfree(p237););
printStats();
PRINT_POINTER(srealloc(p195,6););
printStats();
void* p242 = last_address;
PRINT_POINTER(srealloc(p139,156););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p221););
printStats();
PRINT_POINTER(scalloc(164,45););
printStats();
void* p244 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p245 = last_address;
PRINT_POINTER(srealloc(p233,208););
printStats();
void* p246 = last_address;
DEBUG_PRINT(sfree(p101););
printStats();
DEBUG_PRINT(sfree(p214););
printStats();
PRINT_POINTER(srealloc(p183,30););
printStats();
void* p247 = last_address;
PRINT_POINTER(srealloc(p61,141););
printStats();
void* p248 = last_address;
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(smalloc(151););
printStats();
void* p249 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p250 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p251 = last_address;
DEBUG_PRINT(sfree(p151););
printStats();
DEBUG_PRINT(sfree(p222););
printStats();
PRINT_POINTER(scalloc(185,1););
printStats();
void* p252 = last_address;
PRINT_POINTER(srealloc(p212,76););
printStats();
void* p253 = last_address;
PRINT_POINTER(srealloc(p159,171););
printStats();
void* p254 = last_address;
DEBUG_PRINT(sfree(p211););
printStats();
DEBUG_PRINT(sfree(p241););
printStats();
PRINT_POINTER(srealloc(p141,48););
printStats();
void* p255 = last_address;
PRINT_POINTER(scalloc(78,92););
printStats();
void* p256 = last_address;
PRINT_POINTER(scalloc(139,141););
printStats();
void* p257 = last_address;
DEBUG_PRINT(sfree(p227););
printStats();
PRINT_POINTER(srealloc(p246,159););
printStats();
void* p258 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p259 = last_address;
PRINT_POINTER(srealloc(p251,171););
printStats();
void* p260 = last_address;
DEBUG_PRINT(sfree(p136););
printStats();
PRINT_POINTER(srealloc(p83,166););
printStats();
void* p261 = last_address;
DEBUG_PRINT(sfree(p244););
printStats();
DEBUG_PRINT(sfree(p106););
printStats();
DEBUG_PRINT(sfree(p253););
printStats();
DEBUG_PRINT(sfree(p216););
printStats();
PRINT_POINTER(scalloc(194,119););
printStats();
void* p262 = last_address;
DEBUG_PRINT(sfree(p254););
printStats();
DEBUG_PRINT(sfree(p206););
printStats();
DEBUG_PRINT(sfree(p203););
printStats();
PRINT_POINTER(smalloc(186););
printStats();
void* p263 = last_address;
DEBUG_PRINT(sfree(p192););
printStats();
PRINT_POINTER(smalloc(185););
printStats();
void* p264 = last_address;
PRINT_POINTER(srealloc(p191,249););
printStats();
void* p265 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p266 = last_address;
DEBUG_PRINT(sfree(p260););
printStats();
PRINT_POINTER(srealloc(p250,28););
printStats();
void* p267 = last_address;
PRINT_POINTER(srealloc(p215,130););
printStats();
void* p268 = last_address;
PRINT_POINTER(srealloc(p205,180););
printStats();
void* p269 = last_address;
PRINT_POINTER(srealloc(p264,22););
printStats();
void* p270 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p271 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p272 = last_address;
PRINT_POINTER(scalloc(199,100););
printStats();
void* p273 = last_address;
DEBUG_PRINT(sfree(p209););
printStats();
DEBUG_PRINT(sfree(p271););
printStats();
PRINT_POINTER(smalloc(82););
printStats();
void* p274 = last_address;
DEBUG_PRINT(sfree(p132););
printStats();
PRINT_POINTER(smalloc(171););
printStats();
void* p275 = last_address;
DEBUG_PRINT(sfree(p259););
printStats();
DEBUG_PRINT(sfree(p243););
printStats();
PRINT_POINTER(scalloc(11,162););
printStats();
void* p276 = last_address;
PRINT_POINTER(srealloc(p197,73););
printStats();
void* p277 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p278 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p279 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p280 = last_address;
PRINT_POINTER(srealloc(p228,228););
printStats();
void* p281 = last_address;
PRINT_POINTER(srealloc(p189,158););
printStats();
void* p282 = last_address;
DEBUG_PRINT(sfree(p224););
printStats();
DEBUG_PRINT(sfree(p272););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p283 = last_address;
PRINT_POINTER(srealloc(p225,102););
printStats();
void* p284 = last_address;
DEBUG_PRINT(sfree(p276););
printStats();
DEBUG_PRINT(sfree(p140););
printStats();
PRINT_POINTER(scalloc(198,6););
printStats();
void* p285 = last_address;
PRINT_POINTER(srealloc(p258,235););
printStats();
void* p286 = last_address;
PRINT_POINTER(srealloc(p220,165););
printStats();
void* p287 = last_address;
PRINT_POINTER(scalloc(146,226););
printStats();
void* p288 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p289 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p290 = last_address;
PRINT_POINTER(srealloc(p270,33););
printStats();
void* p291 = last_address;
PRINT_POINTER(srealloc(p177,177););
printStats();
void* p292 = last_address;
DEBUG_PRINT(sfree(p198););
printStats();
DEBUG_PRINT(sfree(p263););
printStats();
PRINT_POINTER(smalloc(152););
printStats();
void* p293 = last_address;
PRINT_POINTER(scalloc(206,69););
printStats();
void* p294 = last_address;
PRINT_POINTER(srealloc(p172,236););
printStats();
void* p295 = last_address;
DEBUG_PRINT(sfree(p129););
printStats();
PRINT_POINTER(srealloc(p128,52););
printStats();
void* p296 = last_address;
DEBUG_PRINT(sfree(p279););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p297 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p298 = last_address;
DEBUG_PRINT(sfree(p296););
printStats();
PRINT_POINTER(smalloc(164););
printStats();
void* p299 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p300 = last_address;
DEBUG_PRINT(sfree(p281););
printStats();
PRINT_POINTER(scalloc(212,171););
printStats();
void* p301 = last_address;
DEBUG_PRINT(sfree(p278););
printStats();
PRINT_POINTER(srealloc(p144,198););
printStats();
void* p302 = last_address;
DEBUG_PRINT(sfree(p298););
printStats();
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(smalloc(178););
printStats();
void* p303 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p304 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p305 = last_address;
PRINT_POINTER(srealloc(p261,92););
printStats();
void* p306 = last_address;
DEBUG_PRINT(sfree(p133););
printStats();
PRINT_POINTER(scalloc(234,28););
printStats();
void* p307 = last_address;
DEBUG_PRINT(sfree(p283););
printStats();
PRINT_POINTER(smalloc(238););
printStats();
void* p308 = last_address;
PRINT_POINTER(scalloc(13,74););
printStats();
void* p309 = last_address;
DEBUG_PRINT(sfree(p299););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p310 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p311 = last_address;
PRINT_POINTER(scalloc(45,242););
printStats();
void* p312 = last_address;
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(scalloc(226,23););
printStats();
void* p313 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p314 = last_address;
DEBUG_PRINT(sfree(p284););
printStats();
PRINT_POINTER(scalloc(36,104););
printStats();
void* p315 = last_address;
PRINT_POINTER(scalloc(138,206););
printStats();
void* p316 = last_address;
PRINT_POINTER(scalloc(218,156););
printStats();
void* p317 = last_address;
DEBUG_PRINT(sfree(p234););
printStats();
DEBUG_PRINT(sfree(p312););
printStats();
PRINT_POINTER(srealloc(p297,210););
printStats();
void* p318 = last_address;
PRINT_POINTER(scalloc(211,5););
printStats();
void* p319 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p320 = last_address;
DEBUG_PRINT(sfree(p236););
printStats();
PRINT_POINTER(scalloc(99,222););
printStats();
void* p321 = last_address;
DEBUG_PRINT(sfree(p311););
printStats();
PRINT_POINTER(smalloc(5););
printStats();
void* p322 = last_address;
PRINT_POINTER(srealloc(p308,40););
printStats();
void* p323 = last_address;
PRINT_POINTER(scalloc(13,226););
printStats();
void* p324 = last_address;
DEBUG_PRINT(sfree(p242););
printStats();
PRINT_POINTER(scalloc(67,216););
printStats();
void* p325 = last_address;
PRINT_POINTER(scalloc(70,101););
printStats();
void* p326 = last_address;
DEBUG_PRINT(sfree(p207););
printStats();
DEBUG_PRINT(sfree(p301););
printStats();
PRINT_POINTER(srealloc(p162,192););
printStats();
void* p327 = last_address;
PRINT_POINTER(scalloc(207,200););
printStats();
void* p328 = last_address;
DEBUG_PRINT(sfree(p275););
printStats();
DEBUG_PRINT(sfree(p160););
printStats();
DEBUG_PRINT(sfree(p293););
printStats();
PRINT_POINTER(smalloc(102););
printStats();
void* p329 = last_address;
DEBUG_PRINT(sfree(p288););
printStats();
PRINT_POINTER(scalloc(117,148););
printStats();
void* p330 = last_address;
PRINT_POINTER(srealloc(p267,217););
printStats();
void* p331 = last_address;
DEBUG_PRINT(sfree(p328););
printStats();
PRINT_POINTER(srealloc(p309,52););
printStats();
void* p332 = last_address;
PRINT_POINTER(scalloc(136,232););
printStats();
void* p333 = last_address;
PRINT_POINTER(srealloc(p202,235););
printStats();
void* p334 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p335 = last_address;
DEBUG_PRINT(sfree(p230););
printStats();
PRINT_POINTER(smalloc(5););
printStats();
void* p336 = last_address;
PRINT_POINTER(scalloc(108,131););
printStats();
void* p337 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p338 = last_address;
PRINT_POINTER(scalloc(161,51););
printStats();
void* p339 = last_address;
PRINT_POINTER(scalloc(123,169););
printStats();
void* p340 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p341 = last_address;
PRINT_POINTER(srealloc(p248,64););
printStats();
void* p342 = last_address;
DEBUG_PRINT(sfree(p179););
printStats();
DEBUG_PRINT(sfree(p330););
printStats();
PRINT_POINTER(smalloc(147););
printStats();
void* p343 = last_address;
PRINT_POINTER(scalloc(245,219););
printStats();
void* p344 = last_address;
PRINT_POINTER(srealloc(p325,181););
printStats();
void* p345 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p346 = last_address;
DEBUG_PRINT(sfree(p262););
printStats();
PRINT_POINTER(smalloc(111););
printStats();
void* p347 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p348 = last_address;
DEBUG_PRINT(sfree(p326););
printStats();
PRINT_POINTER(smalloc(143););
printStats();
void* p349 = last_address;
DEBUG_PRINT(sfree(p300););
printStats();
DEBUG_PRINT(sfree(p346););
printStats();
DEBUG_PRINT(sfree(p333););
printStats();
PRINT_POINTER(smalloc(140););
printStats();
void* p350 = last_address;
PRINT_POINTER(srealloc(p327,83););
printStats();
void* p351 = last_address;
DEBUG_PRINT(sfree(p280););
printStats();
PRINT_POINTER(scalloc(236,192););
printStats();
void* p352 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p353 = last_address;
PRINT_POINTER(smalloc(80););
printStats();
void* p354 = last_address;
PRINT_POINTER(srealloc(p347,43););
printStats();
void* p355 = last_address;
PRINT_POINTER(smalloc(155););
printStats();
void* p356 = last_address;
PRINT_POINTER(scalloc(2,235););
printStats();
void* p357 = last_address;
PRINT_POINTER(scalloc(28,77););
printStats();
void* p358 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p359 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p360 = last_address;
PRINT_POINTER(srealloc(p343,113););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p362 = last_address;
PRINT_POINTER(scalloc(58,24););
printStats();
void* p363 = last_address;
PRINT_POINTER(scalloc(224,1););
printStats();
void* p364 = last_address;
DEBUG_PRINT(sfree(p339););
printStats();
PRINT_POINTER(srealloc(p292,44););
printStats();
void* p365 = last_address;
PRINT_POINTER(scalloc(139,199););
printStats();
void* p366 = last_address;
DEBUG_PRINT(sfree(p364););
printStats();
PRINT_POINTER(scalloc(132,84););
printStats();
void* p367 = last_address;
PRINT_POINTER(srealloc(p348,46););
printStats();
void* p368 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p369 = last_address;
PRINT_POINTER(scalloc(66,222););
printStats();
void* p370 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p371 = last_address;
PRINT_POINTER(scalloc(232,142););
printStats();
void* p372 = last_address;
PRINT_POINTER(scalloc(39,232););
printStats();
void* p373 = last_address;
PRINT_POINTER(scalloc(205,229););
printStats();
void* p374 = last_address;
PRINT_POINTER(scalloc(153,104););
printStats();
void* p375 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p376 = last_address;
DEBUG_PRINT(sfree(p370););
printStats();
DEBUG_PRINT(sfree(p310););
printStats();
PRINT_POINTER(smalloc(62););
printStats();
void* p377 = last_address;
DEBUG_PRINT(sfree(p217););
printStats();
PRINT_POINTER(scalloc(29,143););
printStats();
void* p378 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p379 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p380 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
PRINT_POINTER(smalloc(176););
printStats();
void* p381 = last_address;
PRINT_POINTER(scalloc(20,133););
printStats();
void* p382 = last_address;
PRINT_POINTER(srealloc(p380,99););
printStats();
void* p383 = last_address;
DEBUG_PRINT(sfree(p337););
printStats();
PRINT_POINTER(smalloc(114););
printStats();
void* p384 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p385 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p386 = last_address;
PRINT_POINTER(srealloc(p255,144););
printStats();
void* p387 = last_address;
PRINT_POINTER(srealloc(p358,177););
printStats();
void* p388 = last_address;
DEBUG_PRINT(sfree(p289););
printStats();
PRINT_POINTER(scalloc(154,112););
printStats();
void* p389 = last_address;
DEBUG_PRINT(sfree(p379););
printStats();
PRINT_POINTER(srealloc(p268,60););
printStats();
void* p390 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p391 = last_address;
PRINT_POINTER(scalloc(178,209););
printStats();
void* p392 = last_address;
PRINT_POINTER(scalloc(97,82););
printStats();
void* p393 = last_address;
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(scalloc(151,211););
printStats();
void* p394 = last_address;
PRINT_POINTER(srealloc(p200,98););
printStats();
void* p395 = last_address;
PRINT_POINTER(scalloc(170,116););
printStats();
void* p396 = last_address;
DEBUG_PRINT(sfree(p131););
printStats();
PRINT_POINTER(smalloc(218););
printStats();
void* p397 = last_address;
PRINT_POINTER(scalloc(187,8););
printStats();
void* p398 = last_address;
DEBUG_PRINT(sfree(p389););
printStats();
PRINT_POINTER(smalloc(29););
printStats();
void* p399 = last_address;
PRINT_POINTER(scalloc(35,88););
printStats();
void* p400 = last_address;
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(srealloc(p265,102););
printStats();
void* p401 = last_address;
PRINT_POINTER(srealloc(p307,216););
printStats();
void* p402 = last_address;
PRINT_POINTER(scalloc(156,161););
printStats();
void* p403 = last_address;
PRINT_POINTER(scalloc(87,130););
printStats();
void* p404 = last_address;
PRINT_POINTER(srealloc(p336,14););
printStats();
void* p405 = last_address;
PRINT_POINTER(scalloc(57,64););
printStats();
void* p406 = last_address;
PRINT_POINTER(scalloc(59,223););
printStats();
void* p407 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
DEBUG_PRINT(sfree(p383););
printStats();
PRINT_POINTER(srealloc(p329,42););
printStats();
void* p408 = last_address;
DEBUG_PRINT(sfree(p359););
printStats();
PRINT_POINTER(smalloc(63););
printStats();
void* p409 = last_address;
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(srealloc(p240,11););
printStats();
void* p410 = last_address;
DEBUG_PRINT(sfree(p208););
printStats();
DEBUG_PRINT(sfree(p378););
printStats();
PRINT_POINTER(srealloc(p273,2););
printStats();
void* p411 = last_address;
PRINT_POINTER(scalloc(128,60););
printStats();
void* p412 = last_address;
PRINT_POINTER(scalloc(25,179););
printStats();
void* p413 = last_address;
PRINT_POINTER(scalloc(221,217););
printStats();
void* p414 = last_address;
PRINT_POINTER(srealloc(p331,171););
printStats();
void* p415 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p416 = last_address;
DEBUG_PRINT(sfree(p396););
printStats();
PRINT_POINTER(scalloc(19,202););
printStats();
void* p417 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p418 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p419 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p420 = last_address;
DEBUG_PRINT(sfree(p317););
printStats();
PRINT_POINTER(scalloc(42,135););
printStats();
void* p421 = last_address;
PRINT_POINTER(scalloc(71,147););
printStats();
void* p422 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p423 = last_address;
PRINT_POINTER(scalloc(77,17););
printStats();
void* p424 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p425 = last_address;
PRINT_POINTER(scalloc(71,95););
printStats();
void* p426 = last_address;
PRINT_POINTER(scalloc(231,228););
printStats();
void* p427 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p428 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p429 = last_address;
PRINT_POINTER(srealloc(p386,199););
printStats();
void* p430 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p431 = last_address;
PRINT_POINTER(scalloc(233,7););
printStats();
void* p432 = last_address;
PRINT_POINTER(scalloc(52,91););
printStats();
void* p433 = last_address;
DEBUG_PRINT(sfree(p395););
printStats();
PRINT_POINTER(scalloc(47,37););
printStats();
void* p434 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p435 = last_address;
DEBUG_PRINT(sfree(p384););
printStats();
PRINT_POINTER(srealloc(p318,2););
printStats();
void* p436 = last_address;
PRINT_POINTER(srealloc(p390,235););
printStats();
void* p437 = last_address;
PRINT_POINTER(srealloc(p315,70););
printStats();
void* p438 = last_address;
DEBUG_PRINT(sfree(p421););
printStats();
DEBUG_PRINT(sfree(p302););
printStats();
DEBUG_PRINT(sfree(p437););
printStats();
DEBUG_PRINT(sfree(p357););
printStats();
PRINT_POINTER(scalloc(74,64););
printStats();
void* p439 = last_address;
PRINT_POINTER(scalloc(69,143););
printStats();
void* p440 = last_address;
DEBUG_PRINT(sfree(p404););
printStats();
PRINT_POINTER(scalloc(142,13););
printStats();
void* p441 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p442 = last_address;
DEBUG_PRINT(sfree(p438););
printStats();
PRINT_POINTER(srealloc(p338,186););
printStats();
void* p443 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p444 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p445 = last_address;
DEBUG_PRINT(sfree(p381););
printStats();
PRINT_POINTER(srealloc(p410,124););
printStats();
void* p446 = last_address;
PRINT_POINTER(scalloc(152,179););
printStats();
void* p447 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
PRINT_POINTER(scalloc(164,178););
printStats();
void* p448 = last_address;
DEBUG_PRINT(sfree(p392););
printStats();
PRINT_POINTER(scalloc(59,186););
printStats();
void* p449 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p450 = last_address;
PRINT_POINTER(scalloc(93,164););
printStats();
void* p451 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p452 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p453 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p454 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p455 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p456 = last_address;
DEBUG_PRINT(sfree(p363););
printStats();
PRINT_POINTER(srealloc(p417,132););
printStats();
void* p457 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p458 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p459 = last_address;
DEBUG_PRINT(sfree(p415););
printStats();
PRINT_POINTER(srealloc(p239,26););
printStats();
void* p460 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p461 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p462 = last_address;
PRINT_POINTER(scalloc(127,24););
printStats();
void* p463 = last_address;
PRINT_POINTER(scalloc(115,233););
printStats();
void* p464 = last_address;
PRINT_POINTER(scalloc(61,80););
printStats();
void* p465 = last_address;
PRINT_POINTER(scalloc(143,207););
printStats();
void* p466 = last_address;
PRINT_POINTER(srealloc(p399,58););
printStats();
void* p467 = last_address;
PRINT_POINTER(scalloc(217,74););
printStats();
void* p468 = last_address;
DEBUG_PRINT(sfree(p397););
printStats();
PRINT_POINTER(srealloc(p418,159););
printStats();
void* p469 = last_address;
DEBUG_PRINT(sfree(p408););
printStats();
PRINT_POINTER(srealloc(p462,133););
printStats();
void* p470 = last_address;
PRINT_POINTER(scalloc(17,174););
printStats();
void* p471 = last_address;
DEBUG_PRINT(sfree(p442););
printStats();
PRINT_POINTER(srealloc(p319,158););
printStats();
void* p472 = last_address;
PRINT_POINTER(scalloc(146,0););
printStats();
void* p473 = last_address;
PRINT_POINTER(srealloc(p345,70););
printStats();
void* p474 = last_address;
DEBUG_PRINT(sfree(p213););
printStats();
PRINT_POINTER(srealloc(p450,30););
printStats();
void* p475 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p476 = last_address;
DEBUG_PRINT(sfree(p305););
printStats();
DEBUG_PRINT(sfree(p256););
printStats();
PRINT_POINTER(srealloc(p446,203););
printStats();
void* p477 = last_address;
DEBUG_PRINT(sfree(p306););
printStats();
PRINT_POINTER(srealloc(p456,247););
printStats();
void* p478 = last_address;
DEBUG_PRINT(sfree(p459););
printStats();
PRINT_POINTER(scalloc(185,157););
printStats();
void* p479 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p480 = last_address;
PRINT_POINTER(scalloc(150,235););
printStats();
void* p481 = last_address;
PRINT_POINTER(scalloc(74,57););
printStats();
void* p482 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p483 = last_address;
DEBUG_PRINT(sfree(p406););
printStats();
PRINT_POINTER(scalloc(196,121););
printStats();
void* p484 = last_address;
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(srealloc(p460,198););
printStats();
void* p485 = last_address;
DEBUG_PRINT(sfree(p340););
printStats();
DEBUG_PRINT(sfree(p377););
printStats();
DEBUG_PRINT(sfree(p226););
printStats();
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(srealloc(p393,103););
printStats();
void* p486 = last_address;
PRINT_POINTER(srealloc(p354,229););
printStats();
void* p487 = last_address;
DEBUG_PRINT(sfree(p269););
printStats();
DEBUG_PRINT(sfree(p468););
printStats();
DEBUG_PRINT(sfree(p481););
printStats();
PRINT_POINTER(srealloc(p473,77););
printStats();
void* p488 = last_address;
PRINT_POINTER(scalloc(224,78););
printStats();
void* p489 = last_address;
DEBUG_PRINT(sfree(p466););
printStats();
PRINT_POINTER(scalloc(43,194););
printStats();
void* p490 = last_address;
PRINT_POINTER(scalloc(104,237););
printStats();
void* p491 = last_address;
DEBUG_PRINT(sfree(p447););
printStats();
PRINT_POINTER(smalloc(211););
printStats();
void* p492 = last_address;
DEBUG_PRINT(sfree(p472););
printStats();
PRINT_POINTER(scalloc(37,123););
printStats();
void* p493 = last_address;
PRINT_POINTER(srealloc(p155,103););
printStats();
void* p494 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p495 = last_address;
DEBUG_PRINT(sfree(p362););
printStats();
DEBUG_PRINT(sfree(p316););
printStats();
PRINT_POINTER(srealloc(p478,45););
printStats();
void* p496 = last_address;
DEBUG_PRINT(sfree(p492););
printStats();
PRINT_POINTER(scalloc(140,111););
printStats();
void* p497 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p498 = last_address;
DEBUG_PRINT(sfree(p420););
printStats();
PRINT_POINTER(srealloc(p194,20););
printStats();
void* p499 = last_address;
PRINT_POINTER(scalloc(25,15););
printStats();
void* p500 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p501 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p502 = last_address;
PRINT_POINTER(srealloc(p400,102););
printStats();
void* p503 = last_address;
PRINT_POINTER(srealloc(p369,120););
printStats();
void* p504 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p505 = last_address;
DEBUG_PRINT(sfree(p165););
printStats();
PRINT_POINTER(smalloc(142););
printStats();
void* p506 = last_address;
DEBUG_PRINT(sfree(p424););
printStats();
DEBUG_PRINT(sfree(p494););
printStats();
DEBUG_PRINT(sfree(p439););
printStats();
PRINT_POINTER(scalloc(98,179););
printStats();
void* p507 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p508 = last_address;
DEBUG_PRINT(sfree(p161););
printStats();
DEBUG_PRINT(sfree(p367););
printStats();
DEBUG_PRINT(sfree(p356););
printStats();
DEBUG_PRINT(sfree(p368););
printStats();
PRINT_POINTER(smalloc(47););
printStats();
void* p509 = last_address;
PRINT_POINTER(srealloc(p350,181););
printStats();
void* p510 = last_address;
PRINT_POINTER(srealloc(p387,33););
printStats();
void* p511 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p512 = last_address;
PRINT_POINTER(srealloc(p341,189););
printStats();
void* p513 = last_address;
PRINT_POINTER(scalloc(36,70););
printStats();
void* p514 = last_address;
PRINT_POINTER(srealloc(p445,47););
printStats();
void* p515 = last_address;
PRINT_POINTER(scalloc(97,174););
printStats();
void* p516 = last_address;
PRINT_POINTER(srealloc(p376,94););
printStats();
void* p517 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p518 = last_address;
PRINT_POINTER(srealloc(p405,37););
printStats();
void* p519 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p520 = last_address;
DEBUG_PRINT(sfree(p471););
printStats();
PRINT_POINTER(smalloc(94););
printStats();
void* p521 = last_address;
PRINT_POINTER(scalloc(67,10););
printStats();
void* p522 = last_address;
PRINT_POINTER(scalloc(99,124););
printStats();
void* p523 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p524 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p525 = last_address;
PRINT_POINTER(srealloc(p441,215););
printStats();
void* p526 = last_address;
PRINT_POINTER(srealloc(p495,60););
printStats();
void* p527 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p528 = last_address;
DEBUG_PRINT(sfree(p374););
printStats();
PRINT_POINTER(srealloc(p320,221););
printStats();
void* p529 = last_address;
PRINT_POINTER(srealloc(p174,200););
printStats();
void* p530 = last_address;
PRINT_POINTER(srealloc(p521,35););
printStats();
void* p531 = last_address;
PRINT_POINTER(scalloc(70,16););
printStats();
void* p532 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p533 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p534 = last_address;
PRINT_POINTER(srealloc(p501,221););
printStats();
void* p535 = last_address;
DEBUG_PRINT(sfree(p435););
printStats();
PRINT_POINTER(srealloc(p360,93););
printStats();
void* p536 = last_address;
PRINT_POINTER(scalloc(233,178););
printStats();
void* p537 = last_address;
PRINT_POINTER(srealloc(p407,245););
printStats();
void* p538 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p539 = last_address;
DEBUG_PRINT(sfree(p517););
printStats();
DEBUG_PRINT(sfree(p252););
printStats();
PRINT_POINTER(scalloc(101,97););
printStats();
void* p540 = last_address;
PRINT_POINTER(srealloc(p504,66););
printStats();
void* p541 = last_address;
DEBUG_PRINT(sfree(p488););
printStats();
PRINT_POINTER(srealloc(p455,83););
printStats();
void* p542 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p543 = last_address;
PRINT_POINTER(srealloc(p486,80););
printStats();
void* p544 = last_address;
DEBUG_PRINT(sfree(p235););
printStats();
DEBUG_PRINT(sfree(p539););
printStats();
DEBUG_PRINT(sfree(p449););
printStats();
PRINT_POINTER(smalloc(21););
printStats();
void* p545 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p546 = last_address;
PRINT_POINTER(srealloc(p321,68););
printStats();
void* p547 = last_address;
DEBUG_PRINT(sfree(p398););
printStats();
PRINT_POINTER(scalloc(237,236););
printStats();
void* p548 = last_address;
DEBUG_PRINT(sfree(p324););
printStats();
PRINT_POINTER(scalloc(72,30););
printStats();
void* p549 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p550 = last_address;
PRINT_POINTER(srealloc(p490,230););
printStats();
void* p551 = last_address;
PRINT_POINTER(srealloc(p483,22););
printStats();
void* p552 = last_address;
DEBUG_PRINT(sfree(p402););
printStats();
DEBUG_PRINT(sfree(p474););
printStats();
PRINT_POINTER(srealloc(p232,212););
printStats();
void* p553 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p554 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p555 = last_address;
PRINT_POINTER(srealloc(p522,173););
printStats();
void* p556 = last_address;
PRINT_POINTER(srealloc(p432,189););
printStats();
void* p557 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p558 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p559 = last_address;
PRINT_POINTER(srealloc(p464,232););
printStats();
void* p560 = last_address;
PRINT_POINTER(scalloc(230,146););
printStats();
void* p561 = last_address;
PRINT_POINTER(scalloc(92,215););
printStats();
void* p562 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p563 = last_address;
PRINT_POINTER(scalloc(224,181););
printStats();
void* p564 = last_address;
DEBUG_PRINT(sfree(p457););
printStats();
PRINT_POINTER(scalloc(150,79););
printStats();
void* p565 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p566 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p567 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p568 = last_address;
PRINT_POINTER(scalloc(133,246););
printStats();
void* p569 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p570 = last_address;
PRINT_POINTER(srealloc(p507,118););
printStats();
void* p571 = last_address;
PRINT_POINTER(scalloc(56,200););
printStats();
void* p572 = last_address;
DEBUG_PRINT(sfree(p290););
printStats();
DEBUG_PRINT(sfree(p458););
printStats();
PRINT_POINTER(srealloc(p537,2););
printStats();
void* p573 = last_address;
DEBUG_PRINT(sfree(p544););
printStats();
PRINT_POINTER(smalloc(220););
printStats();
void* p574 = last_address;
DEBUG_PRINT(sfree(p555););
printStats();
DEBUG_PRINT(sfree(p427););
printStats();
PRINT_POINTER(srealloc(p513,10););
printStats();
void* p575 = last_address;
DEBUG_PRINT(sfree(p503););
printStats();
PRINT_POINTER(srealloc(p549,170););
printStats();
void* p576 = last_address;
PRINT_POINTER(srealloc(p249,66););
printStats();
void* p577 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p578 = last_address;
PRINT_POINTER(srealloc(p556,248););
printStats();
void* p579 = last_address;
PRINT_POINTER(srealloc(p479,11););
printStats();
void* p580 = last_address;
PRINT_POINTER(srealloc(p413,204););
printStats();
void* p581 = last_address;
DEBUG_PRINT(sfree(p484););
printStats();
PRINT_POINTER(smalloc(2););
printStats();
void* p582 = last_address;
DEBUG_PRINT(sfree(p403););
printStats();
PRINT_POINTER(srealloc(p469,141););
printStats();
void* p583 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p584 = last_address;
PRINT_POINTER(srealloc(p247,243););
printStats();
void* p585 = last_address;
PRINT_POINTER(scalloc(120,155););
printStats();
void* p586 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p587 = last_address;
PRINT_POINTER(scalloc(50,99););
printStats();
void* p588 = last_address;
PRINT_POINTER(scalloc(137,10););
printStats();
void* p589 = last_address;
PRINT_POINTER(scalloc(240,12););
printStats();
void* p590 = last_address;
PRINT_POINTER(scalloc(116,208););
printStats();
void* p591 = last_address;
PRINT_POINTER(scalloc(13,204););
printStats();
void* p592 = last_address;
DEBUG_PRINT(sfree(p505););
printStats();
DEBUG_PRINT(sfree(p516););
printStats();
PRINT_POINTER(srealloc(p511,236););
printStats();
void* p593 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p594 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p595 = last_address;
PRINT_POINTER(scalloc(129,220););
printStats();
void* p596 = last_address;
PRINT_POINTER(srealloc(p193,219););
printStats();
void* p597 = last_address;
DEBUG_PRINT(sfree(p515););
printStats();
DEBUG_PRINT(sfree(p528););
printStats();
PRINT_POINTER(scalloc(44,115););
printStats();
void* p598 = last_address;
DEBUG_PRINT(sfree(p498););
printStats();
PRINT_POINTER(scalloc(171,21););
printStats();
void* p599 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p600 = last_address;
DEBUG_PRINT(sfree(p493););
printStats();
PRINT_POINTER(smalloc(46););
printStats();
void* p601 = last_address;
DEBUG_PRINT(sfree(p526););
printStats();
PRINT_POINTER(smalloc(143););
printStats();
void* p602 = last_address;
PRINT_POINTER(scalloc(118,20););
printStats();
void* p603 = last_address;
DEBUG_PRINT(sfree(p361););
printStats();
PRINT_POINTER(srealloc(p533,228););
printStats();
void* p604 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p605 = last_address;
PRINT_POINTER(scalloc(147,2););
printStats();
void* p606 = last_address;
DEBUG_PRINT(sfree(p366););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p607 = last_address;
PRINT_POINTER(scalloc(108,155););
printStats();
void* p608 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p609 = last_address;
PRINT_POINTER(scalloc(8,97););
printStats();
void* p610 = last_address;
DEBUG_PRINT(sfree(p385););
printStats();
DEBUG_PRINT(sfree(p428););
printStats();
PRINT_POINTER(srealloc(p552,111););
printStats();
void* p611 = last_address;
DEBUG_PRINT(sfree(p416););
printStats();
PRINT_POINTER(smalloc(100););
printStats();
void* p612 = last_address;
PRINT_POINTER(srealloc(p529,1););
printStats();
void* p613 = last_address;
DEBUG_PRINT(sfree(p454););
printStats();
PRINT_POINTER(srealloc(p411,49););
printStats();
void* p614 = last_address;
PRINT_POINTER(srealloc(p519,65););
printStats();
void* p615 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p616 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p617 = last_address;
PRINT_POINTER(srealloc(p352,102););
printStats();
void* p618 = last_address;
PRINT_POINTER(scalloc(54,53););
printStats();
void* p619 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p620 = last_address;
PRINT_POINTER(scalloc(77,165););
printStats();
void* p621 = last_address;
PRINT_POINTER(srealloc(p480,204););
printStats();
void* p622 = last_address;
DEBUG_PRINT(sfree(p578););
printStats();
DEBUG_PRINT(sfree(p570););
printStats();
DEBUG_PRINT(sfree(p564););
printStats();
DEBUG_PRINT(sfree(p463););
printStats();
PRINT_POINTER(scalloc(65,138););
printStats();
void* p623 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p624 = last_address;
PRINT_POINTER(scalloc(219,156););
printStats();
void* p625 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p626 = last_address;
PRINT_POINTER(scalloc(206,32););
printStats();
void* p627 = last_address;
PRINT_POINTER(scalloc(109,205););
printStats();
void* p628 = last_address;
DEBUG_PRINT(sfree(p388););
printStats();
PRINT_POINTER(scalloc(7,180););
printStats();
void* p629 = last_address;
PRINT_POINTER(srealloc(p575,240););
printStats();
void* p630 = last_address;
DEBUG_PRINT(sfree(p487););
printStats();
DEBUG_PRINT(sfree(p590););
printStats();
PRINT_POINTER(srealloc(p470,133););
printStats();
void* p631 = last_address;
PRINT_POINTER(scalloc(26,46););
printStats();
void* p632 = last_address;
PRINT_POINTER(srealloc(p353,217););
printStats();
void* p633 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p634 = last_address;
DEBUG_PRINT(sfree(p569););
printStats();
PRINT_POINTER(srealloc(p372,5););
printStats();
void* p635 = last_address;
PRINT_POINTER(scalloc(138,171););
printStats();
void* p636 = last_address;
PRINT_POINTER(srealloc(p452,233););
printStats();
void* p637 = last_address;
DEBUG_PRINT(sfree(p558););
printStats();
PRINT_POINTER(smalloc(182););
printStats();
void* p638 = last_address;
PRINT_POINTER(srealloc(p611,141););
printStats();
void* p639 = last_address;
PRINT_POINTER(srealloc(p382,170););
printStats();
void* p640 = last_address;
PRINT_POINTER(scalloc(27,30););
printStats();
void* p641 = last_address;
DEBUG_PRINT(sfree(p332););
printStats();
DEBUG_PRINT(sfree(p592););
printStats();
DEBUG_PRINT(sfree(p572););
printStats();
PRINT_POINTER(scalloc(237,169););
printStats();
void* p642 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p643 = last_address;
PRINT_POINTER(scalloc(16,119););
printStats();
void* p644 = last_address;
PRINT_POINTER(srealloc(p565,74););
printStats();
void* p645 = last_address;
PRINT_POINTER(srealloc(p431,116););
printStats();
void* p646 = last_address;
PRINT_POINTER(srealloc(p548,237););
printStats();
void* p647 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p648 = last_address;
PRINT_POINTER(srealloc(p617,145););
printStats();
void* p649 = last_address;
PRINT_POINTER(scalloc(5,116););
printStats();
void* p650 = last_address;
PRINT_POINTER(scalloc(133,133););
printStats();
void* p651 = last_address;
PRINT_POINTER(scalloc(228,117););
printStats();
void* p652 = last_address;
DEBUG_PRINT(sfree(p604););
printStats();
DEBUG_PRINT(sfree(p168););
printStats();
DEBUG_PRINT(sfree(p371););
printStats();
PRINT_POINTER(srealloc(p536,86););
printStats();
void* p653 = last_address;
PRINT_POINTER(srealloc(p506,222););
printStats();
void* p654 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p655 = last_address;
DEBUG_PRINT(sfree(p423););
printStats();
PRINT_POINTER(srealloc(p566,67););
printStats();
void* p656 = last_address;
PRINT_POINTER(smalloc(180););
printStats();
void* p657 = last_address;
PRINT_POINTER(scalloc(97,200););
printStats();
void* p658 = last_address;
PRINT_POINTER(srealloc(p597,164););
printStats();
void* p659 = last_address;
PRINT_POINTER(srealloc(p525,212););
printStats();
void* p660 = last_address;
PRINT_POINTER(srealloc(p344,190););
printStats();
void* p661 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p662 = last_address;
DEBUG_PRINT(sfree(p461););
printStats();
PRINT_POINTER(scalloc(146,95););
printStats();
void* p663 = last_address;
PRINT_POINTER(scalloc(179,7););
printStats();
void* p664 = last_address;
DEBUG_PRINT(sfree(p547););
printStats();
PRINT_POINTER(srealloc(p475,36););
printStats();
void* p665 = last_address;
PRINT_POINTER(scalloc(29,222););
printStats();
void* p666 = last_address;
DEBUG_PRINT(sfree(p314););
printStats();
DEBUG_PRINT(sfree(p621););
printStats();
PRINT_POINTER(scalloc(87,43););
printStats();
void* p667 = last_address;
PRINT_POINTER(scalloc(76,121););
printStats();
void* p668 = last_address;
DEBUG_PRINT(sfree(p285););
printStats();
PRINT_POINTER(scalloc(8,61););
printStats();
void* p669 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p670 = last_address;
PRINT_POINTER(scalloc(9,233););
printStats();
void* p671 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p672 = last_address;
DEBUG_PRINT(sfree(p627););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p673 = last_address;
PRINT_POINTER(scalloc(85,2););
printStats();
void* p674 = last_address;
PRINT_POINTER(scalloc(127,24););
printStats();
void* p675 = last_address;
PRINT_POINTER(scalloc(239,137););
printStats();
void* p676 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p677 = last_address;
PRINT_POINTER(scalloc(244,150););
printStats();
void* p678 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p679 = last_address;
PRINT_POINTER(scalloc(223,110););
printStats();
void* p680 = last_address;
PRINT_POINTER(srealloc(p583,240););
printStats();
void* p681 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p682 = last_address;
PRINT_POINTER(scalloc(183,109););
printStats();
void* p683 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p684 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p685 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p686 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p687 = last_address;
DEBUG_PRINT(sfree(p509););
printStats();
DEBUG_PRINT(sfree(p683););
printStats();
DEBUG_PRINT(sfree(p641););
printStats();
PRINT_POINTER(srealloc(p574,55););
printStats();
void* p688 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p689 = last_address;
PRINT_POINTER(scalloc(108,210););
printStats();
void* p690 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p691 = last_address;
DEBUG_PRINT(sfree(p512););
printStats();
PRINT_POINTER(scalloc(196,109););
printStats();
void* p692 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p693 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p694 = last_address;
PRINT_POINTER(srealloc(p355,66););
printStats();
void* p695 = last_address;
PRINT_POINTER(srealloc(p659,2););
printStats();
void* p696 = last_address;
PRINT_POINTER(srealloc(p657,163););
printStats();
void* p697 = last_address;
PRINT_POINTER(scalloc(208,92););
printStats();
void* p698 = last_address;
DEBUG_PRINT(sfree(p606););
printStats();
DEBUG_PRINT(sfree(p697););
printStats();
PRINT_POINTER(scalloc(247,112););
printStats();
void* p699 = last_address;
DEBUG_PRINT(sfree(p518););
printStats();
PRINT_POINTER(smalloc(85););
printStats();
void* p700 = last_address;
PRINT_POINTER(srealloc(p530,52););
printStats();
void* p701 = last_address;
PRINT_POINTER(srealloc(p553,95););
printStats();
void* p702 = last_address;
PRINT_POINTER(srealloc(p638,214););
printStats();
void* p703 = last_address;
DEBUG_PRINT(sfree(p444););
printStats();
PRINT_POINTER(smalloc(166););
printStats();
void* p704 = last_address;
PRINT_POINTER(scalloc(236,101););
printStats();
void* p705 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p706 = last_address;
PRINT_POINTER(srealloc(p661,145););
printStats();
void* p707 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p708 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p709 = last_address;
PRINT_POINTER(scalloc(198,240););
printStats();
void* p710 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p711 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p712 = last_address;
PRINT_POINTER(srealloc(p662,159););
printStats();
void* p713 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p714 = last_address;
PRINT_POINTER(scalloc(62,107););
printStats();
void* p715 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p716 = last_address;
DEBUG_PRINT(sfree(p588););
printStats();
PRINT_POINTER(srealloc(p557,57););
printStats();
void* p717 = last_address;
PRINT_POINTER(srealloc(p608,146););
printStats();
void* p718 = last_address;
PRINT_POINTER(scalloc(10,170););
printStats();
void* p719 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p720 = last_address;
PRINT_POINTER(scalloc(1,32););
printStats();
void* p721 = last_address;
DEBUG_PRINT(sfree(p709););
printStats();
PRINT_POINTER(srealloc(p616,140););
printStats();
void* p722 = last_address;
DEBUG_PRINT(sfree(p678););
printStats();
PRINT_POINTER(srealloc(p614,225););
printStats();
void* p723 = last_address;
PRINT_POINTER(srealloc(p665,198););
printStats();
void* p724 = last_address;
DEBUG_PRINT(sfree(p631););
printStats();
PRINT_POINTER(smalloc(160););
printStats();
void* p725 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p726 = last_address;
DEBUG_PRINT(sfree(p554););
printStats();
PRINT_POINTER(scalloc(55,17););
printStats();
void* p727 = last_address;
}
