#include "aux_macro.h"
#include "../malloc_4.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(30););
printStats();
void* p0 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(scalloc(226,165););
printStats();
void* p1 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p2 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(scalloc(146,214););
printStats();
void* p3 = last_address;
DEBUG_PRINT(sfree(p3););
printStats();
PRINT_POINTER(smalloc(165););
printStats();
void* p4 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p5 = last_address;
PRINT_POINTER(srealloc(p4,133););
printStats();
void* p6 = last_address;
PRINT_POINTER(scalloc(88,19););
printStats();
void* p7 = last_address;
PRINT_POINTER(scalloc(200,119););
printStats();
void* p8 = last_address;
PRINT_POINTER(srealloc(p7,243););
printStats();
void* p9 = last_address;
PRINT_POINTER(srealloc(p1,154););
printStats();
void* p10 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(srealloc(p9,63););
printStats();
void* p11 = last_address;
PRINT_POINTER(scalloc(146,51););
printStats();
void* p12 = last_address;
PRINT_POINTER(scalloc(90,246););
printStats();
void* p13 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p14 = last_address;
PRINT_POINTER(srealloc(p5,168););
printStats();
void* p15 = last_address;
DEBUG_PRINT(sfree(p13););
printStats();
PRINT_POINTER(scalloc(248,147););
printStats();
void* p16 = last_address;
PRINT_POINTER(srealloc(p12,217););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(123,214););
printStats();
void* p18 = last_address;
PRINT_POINTER(srealloc(p18,34););
printStats();
void* p19 = last_address;
DEBUG_PRINT(sfree(p17););
printStats();
PRINT_POINTER(srealloc(p10,16););
printStats();
void* p20 = last_address;
PRINT_POINTER(scalloc(132,20););
printStats();
void* p21 = last_address;
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(smalloc(108););
printStats();
void* p22 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p23 = last_address;
PRINT_POINTER(scalloc(237,14););
printStats();
void* p24 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p25 = last_address;
DEBUG_PRINT(sfree(p24););
printStats();
PRINT_POINTER(scalloc(59,9););
printStats();
void* p26 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
PRINT_POINTER(smalloc(190););
printStats();
void* p28 = last_address;
PRINT_POINTER(srealloc(p28,63););
printStats();
void* p29 = last_address;
PRINT_POINTER(scalloc(149,28););
printStats();
void* p30 = last_address;
PRINT_POINTER(srealloc(p14,142););
printStats();
void* p31 = last_address;
PRINT_POINTER(srealloc(p15,218););
printStats();
void* p32 = last_address;
PRINT_POINTER(srealloc(p20,211););
printStats();
void* p33 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p34 = last_address;
PRINT_POINTER(srealloc(p27,127););
printStats();
void* p35 = last_address;
PRINT_POINTER(scalloc(173,47););
printStats();
void* p36 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p37 = last_address;
PRINT_POINTER(scalloc(158,128););
printStats();
void* p38 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p39 = last_address;
PRINT_POINTER(scalloc(185,240););
printStats();
void* p40 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p41 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p42 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
PRINT_POINTER(scalloc(93,236););
printStats();
void* p43 = last_address;
PRINT_POINTER(srealloc(p41,199););
printStats();
void* p44 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
DEBUG_PRINT(sfree(p21););
printStats();
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(scalloc(70,152););
printStats();
void* p45 = last_address;
PRINT_POINTER(scalloc(214,185););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p47 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p48 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p49 = last_address;
DEBUG_PRINT(sfree(p19););
printStats();
PRINT_POINTER(scalloc(227,156););
printStats();
void* p50 = last_address;
PRINT_POINTER(srealloc(p42,243););
printStats();
void* p51 = last_address;
PRINT_POINTER(srealloc(p31,62););
printStats();
void* p52 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p53 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p54 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p55 = last_address;
DEBUG_PRINT(sfree(p46););
printStats();
PRINT_POINTER(scalloc(85,2););
printStats();
void* p56 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(197,168););
printStats();
void* p58 = last_address;
PRINT_POINTER(scalloc(235,224););
printStats();
void* p59 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p60 = last_address;
PRINT_POINTER(scalloc(11,207););
printStats();
void* p61 = last_address;
PRINT_POINTER(srealloc(p39,11););
printStats();
void* p62 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p63 = last_address;
PRINT_POINTER(srealloc(p60,47););
printStats();
void* p64 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p65 = last_address;
PRINT_POINTER(scalloc(208,189););
printStats();
void* p66 = last_address;
PRINT_POINTER(scalloc(6,150););
printStats();
void* p67 = last_address;
PRINT_POINTER(scalloc(208,185););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p59,246););
printStats();
void* p69 = last_address;
DEBUG_PRINT(sfree(p52););
printStats();
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(smalloc(8););
printStats();
void* p70 = last_address;
PRINT_POINTER(srealloc(p30,119););
printStats();
void* p71 = last_address;
DEBUG_PRINT(sfree(p49););
printStats();
PRINT_POINTER(scalloc(144,204););
printStats();
void* p72 = last_address;
PRINT_POINTER(scalloc(193,94););
printStats();
void* p73 = last_address;
DEBUG_PRINT(sfree(p51););
printStats();
DEBUG_PRINT(sfree(p23););
printStats();
PRINT_POINTER(scalloc(219,239););
printStats();
void* p74 = last_address;
DEBUG_PRINT(sfree(p26););
printStats();
DEBUG_PRINT(sfree(p45););
printStats();
PRINT_POINTER(srealloc(p72,142););
printStats();
void* p75 = last_address;
PRINT_POINTER(scalloc(18,190););
printStats();
void* p76 = last_address;
PRINT_POINTER(scalloc(122,41););
printStats();
void* p77 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p78 = last_address;
DEBUG_PRINT(sfree(p57););
printStats();
DEBUG_PRINT(sfree(p62););
printStats();
PRINT_POINTER(srealloc(p53,121););
printStats();
void* p79 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(scalloc(162,113););
printStats();
void* p80 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(srealloc(p68,219););
printStats();
void* p81 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p83 = last_address;
PRINT_POINTER(scalloc(135,64););
printStats();
void* p84 = last_address;
DEBUG_PRINT(sfree(p43););
printStats();
DEBUG_PRINT(sfree(p56););
printStats();
DEBUG_PRINT(sfree(p70););
printStats();
PRINT_POINTER(smalloc(84););
printStats();
void* p85 = last_address;
PRINT_POINTER(srealloc(p54,36););
printStats();
void* p86 = last_address;
DEBUG_PRINT(sfree(p47););
printStats();
PRINT_POINTER(srealloc(p64,54););
printStats();
void* p87 = last_address;
PRINT_POINTER(srealloc(p11,16););
printStats();
void* p88 = last_address;
PRINT_POINTER(scalloc(145,96););
printStats();
void* p89 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p90 = last_address;
DEBUG_PRINT(sfree(p84););
printStats();
PRINT_POINTER(scalloc(24,81););
printStats();
void* p91 = last_address;
PRINT_POINTER(srealloc(p34,126););
printStats();
void* p92 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p93 = last_address;
PRINT_POINTER(scalloc(71,6););
printStats();
void* p94 = last_address;
DEBUG_PRINT(sfree(p73););
printStats();
PRINT_POINTER(smalloc(75););
printStats();
void* p95 = last_address;
PRINT_POINTER(srealloc(p76,151););
printStats();
void* p96 = last_address;
DEBUG_PRINT(sfree(p82););
printStats();
PRINT_POINTER(scalloc(77,174););
printStats();
void* p97 = last_address;
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(scalloc(88,15););
printStats();
void* p98 = last_address;
PRINT_POINTER(srealloc(p81,16););
printStats();
void* p99 = last_address;
DEBUG_PRINT(sfree(p74););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p100 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p101 = last_address;
DEBUG_PRINT(sfree(p61););
printStats();
PRINT_POINTER(srealloc(p97,210););
printStats();
void* p102 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p103 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p104 = last_address;
PRINT_POINTER(srealloc(p22,45););
printStats();
void* p105 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(srealloc(p44,76););
printStats();
void* p106 = last_address;
PRINT_POINTER(scalloc(245,99););
printStats();
void* p107 = last_address;
PRINT_POINTER(scalloc(83,169););
printStats();
void* p108 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p109 = last_address;
PRINT_POINTER(srealloc(p104,55););
printStats();
void* p110 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p111 = last_address;
PRINT_POINTER(scalloc(181,60););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p96,88););
printStats();
void* p113 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p114 = last_address;
PRINT_POINTER(srealloc(p63,139););
printStats();
void* p115 = last_address;
PRINT_POINTER(srealloc(p92,213););
printStats();
void* p116 = last_address;
PRINT_POINTER(scalloc(220,185););
printStats();
void* p117 = last_address;
PRINT_POINTER(srealloc(p93,217););
printStats();
void* p118 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p119 = last_address;
PRINT_POINTER(scalloc(164,140););
printStats();
void* p120 = last_address;
PRINT_POINTER(srealloc(p99,121););
printStats();
void* p121 = last_address;
DEBUG_PRINT(sfree(p55););
printStats();
PRINT_POINTER(scalloc(229,32););
printStats();
void* p122 = last_address;
PRINT_POINTER(scalloc(23,73););
printStats();
void* p123 = last_address;
DEBUG_PRINT(sfree(p83););
printStats();
PRINT_POINTER(smalloc(43););
printStats();
void* p124 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
DEBUG_PRINT(sfree(p116););
printStats();
DEBUG_PRINT(sfree(p113););
printStats();
DEBUG_PRINT(sfree(p117););
printStats();
DEBUG_PRINT(sfree(p37););
printStats();
DEBUG_PRINT(sfree(p67););
printStats();
PRINT_POINTER(srealloc(p71,78););
printStats();
void* p125 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(srealloc(p48,41););
printStats();
void* p126 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
DEBUG_PRINT(sfree(p98););
printStats();
DEBUG_PRINT(sfree(p110););
printStats();
PRINT_POINTER(srealloc(p65,189););
printStats();
void* p127 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p128 = last_address;
PRINT_POINTER(scalloc(126,91););
printStats();
void* p129 = last_address;
DEBUG_PRINT(sfree(p108););
printStats();
DEBUG_PRINT(sfree(p106););
printStats();
DEBUG_PRINT(sfree(p122););
printStats();
PRINT_POINTER(srealloc(p120,167););
printStats();
void* p130 = last_address;
DEBUG_PRINT(sfree(p75););
printStats();
PRINT_POINTER(smalloc(59););
printStats();
void* p131 = last_address;
DEBUG_PRINT(sfree(p66););
printStats();
PRINT_POINTER(scalloc(226,87););
printStats();
void* p132 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p133 = last_address;
PRINT_POINTER(scalloc(83,172););
printStats();
void* p134 = last_address;
PRINT_POINTER(scalloc(223,51););
printStats();
void* p135 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p136 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p137 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p138 = last_address;
PRINT_POINTER(srealloc(p94,72););
printStats();
void* p139 = last_address;
PRINT_POINTER(srealloc(p135,214););
printStats();
void* p140 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(scalloc(6,241););
printStats();
void* p141 = last_address;
DEBUG_PRINT(sfree(p101););
printStats();
DEBUG_PRINT(sfree(p111););
printStats();
PRINT_POINTER(srealloc(p141,116););
printStats();
void* p142 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p143 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p144 = last_address;
DEBUG_PRINT(sfree(p125););
printStats();
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(srealloc(p126,139););
printStats();
void* p145 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p133););
printStats();
PRINT_POINTER(srealloc(p112,230););
printStats();
void* p147 = last_address;
PRINT_POINTER(srealloc(p107,98););
printStats();
void* p148 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p149 = last_address;
DEBUG_PRINT(sfree(p129););
printStats();
PRINT_POINTER(scalloc(91,172););
printStats();
void* p150 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
DEBUG_PRINT(sfree(p132););
printStats();
PRINT_POINTER(srealloc(p131,160););
printStats();
void* p151 = last_address;
PRINT_POINTER(srealloc(p103,46););
printStats();
void* p152 = last_address;
PRINT_POINTER(scalloc(179,213););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(54,38););
printStats();
void* p154 = last_address;
PRINT_POINTER(srealloc(p118,84););
printStats();
void* p155 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p156 = last_address;
PRINT_POINTER(srealloc(p123,119););
printStats();
void* p157 = last_address;
DEBUG_PRINT(sfree(p140););
printStats();
PRINT_POINTER(smalloc(22););
printStats();
void* p158 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p159 = last_address;
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(smalloc(48););
printStats();
void* p160 = last_address;
PRINT_POINTER(srealloc(p139,201););
printStats();
void* p161 = last_address;
DEBUG_PRINT(sfree(p121););
printStats();
PRINT_POINTER(smalloc(61););
printStats();
void* p162 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p163 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p164 = last_address;
DEBUG_PRINT(sfree(p143););
printStats();
PRINT_POINTER(smalloc(207););
printStats();
void* p165 = last_address;
PRINT_POINTER(scalloc(56,49););
printStats();
void* p166 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p167 = last_address;
PRINT_POINTER(scalloc(59,165););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(165,18););
printStats();
void* p169 = last_address;
PRINT_POINTER(srealloc(p148,130););
printStats();
void* p170 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p171 = last_address;
PRINT_POINTER(srealloc(p146,164););
printStats();
void* p172 = last_address;
PRINT_POINTER(srealloc(p155,86););
printStats();
void* p173 = last_address;
DEBUG_PRINT(sfree(p32););
printStats();
PRINT_POINTER(smalloc(207););
printStats();
void* p174 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p175 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p176 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p177 = last_address;
DEBUG_PRINT(sfree(p115););
printStats();
PRINT_POINTER(srealloc(p58,176););
printStats();
void* p178 = last_address;
PRINT_POINTER(srealloc(p174,194););
printStats();
void* p179 = last_address;
PRINT_POINTER(scalloc(226,119););
printStats();
void* p180 = last_address;
PRINT_POINTER(scalloc(76,139););
printStats();
void* p181 = last_address;
PRINT_POINTER(srealloc(p163,52););
printStats();
void* p182 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(scalloc(219,128););
printStats();
void* p183 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p184 = last_address;
PRINT_POINTER(scalloc(47,196););
printStats();
void* p185 = last_address;
PRINT_POINTER(scalloc(84,204););
printStats();
void* p186 = last_address;
PRINT_POINTER(scalloc(108,158););
printStats();
void* p187 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p188 = last_address;
PRINT_POINTER(scalloc(236,13););
printStats();
void* p189 = last_address;
PRINT_POINTER(srealloc(p105,148););
printStats();
void* p190 = last_address;
DEBUG_PRINT(sfree(p95););
printStats();
PRINT_POINTER(srealloc(p183,128););
printStats();
void* p191 = last_address;
PRINT_POINTER(srealloc(p170,33););
printStats();
void* p192 = last_address;
PRINT_POINTER(scalloc(53,54););
printStats();
void* p193 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p194 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p195 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p196 = last_address;
PRINT_POINTER(srealloc(p161,194););
printStats();
void* p197 = last_address;
PRINT_POINTER(scalloc(110,155););
printStats();
void* p198 = last_address;
PRINT_POINTER(scalloc(11,159););
printStats();
void* p199 = last_address;
PRINT_POINTER(scalloc(246,99););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p119,93););
printStats();
void* p201 = last_address;
PRINT_POINTER(srealloc(p190,0););
printStats();
void* p202 = last_address;
PRINT_POINTER(scalloc(110,53););
printStats();
void* p203 = last_address;
DEBUG_PRINT(sfree(p164););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p204 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(scalloc(92,7););
printStats();
void* p205 = last_address;
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(smalloc(112););
printStats();
void* p206 = last_address;
PRINT_POINTER(scalloc(14,99););
printStats();
void* p207 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p208 = last_address;
PRINT_POINTER(srealloc(p152,205););
printStats();
void* p209 = last_address;
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(srealloc(p192,170););
printStats();
void* p210 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(193,48););
printStats();
void* p212 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p213 = last_address;
PRINT_POINTER(scalloc(165,7););
printStats();
void* p214 = last_address;
PRINT_POINTER(srealloc(p124,128););
printStats();
void* p215 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p216 = last_address;
PRINT_POINTER(srealloc(p186,123););
printStats();
void* p217 = last_address;
DEBUG_PRINT(sfree(p137););
printStats();
PRINT_POINTER(scalloc(171,78););
printStats();
void* p218 = last_address;
PRINT_POINTER(scalloc(173,141););
printStats();
void* p219 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(scalloc(12,21););
printStats();
void* p220 = last_address;
PRINT_POINTER(scalloc(147,61););
printStats();
void* p221 = last_address;
PRINT_POINTER(srealloc(p172,241););
printStats();
void* p222 = last_address;
PRINT_POINTER(scalloc(153,9););
printStats();
void* p223 = last_address;
PRINT_POINTER(srealloc(p138,201););
printStats();
void* p224 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p225 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p226 = last_address;
PRINT_POINTER(srealloc(p147,36););
printStats();
void* p227 = last_address;
PRINT_POINTER(scalloc(226,210););
printStats();
void* p228 = last_address;
PRINT_POINTER(srealloc(p178,93););
printStats();
void* p229 = last_address;
PRINT_POINTER(srealloc(p136,20););
printStats();
void* p230 = last_address;
PRINT_POINTER(srealloc(p160,130););
printStats();
void* p231 = last_address;
DEBUG_PRINT(sfree(p201););
printStats();
DEBUG_PRINT(sfree(p165););
printStats();
PRINT_POINTER(srealloc(p158,118););
printStats();
void* p232 = last_address;
PRINT_POINTER(srealloc(p210,87););
printStats();
void* p233 = last_address;
DEBUG_PRINT(sfree(p220););
printStats();
PRINT_POINTER(srealloc(p128,220););
printStats();
void* p234 = last_address;
PRINT_POINTER(scalloc(135,173););
printStats();
void* p235 = last_address;
PRINT_POINTER(srealloc(p169,232););
printStats();
void* p236 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p237 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p238 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p239 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p240 = last_address;
DEBUG_PRINT(sfree(p151););
printStats();
DEBUG_PRINT(sfree(p222););
printStats();
PRINT_POINTER(smalloc(69););
printStats();
void* p241 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p242 = last_address;
PRINT_POINTER(scalloc(113,162););
printStats();
void* p243 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p244 = last_address;
PRINT_POINTER(scalloc(228,5););
printStats();
void* p245 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p246 = last_address;
PRINT_POINTER(scalloc(123,61););
printStats();
void* p247 = last_address;
PRINT_POINTER(srealloc(p189,244););
printStats();
void* p248 = last_address;
DEBUG_PRINT(sfree(p211););
printStats();
PRINT_POINTER(srealloc(p234,190););
printStats();
void* p249 = last_address;
PRINT_POINTER(srealloc(p203,108););
printStats();
void* p250 = last_address;
PRINT_POINTER(scalloc(204,220););
printStats();
void* p251 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p252 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p253 = last_address;
DEBUG_PRINT(sfree(p225););
printStats();
PRINT_POINTER(smalloc(28););
printStats();
void* p254 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p255 = last_address;
PRINT_POINTER(scalloc(115,200););
printStats();
void* p256 = last_address;
DEBUG_PRINT(sfree(p153););
printStats();
PRINT_POINTER(srealloc(p88,134););
printStats();
void* p257 = last_address;
PRINT_POINTER(srealloc(p224,56););
printStats();
void* p258 = last_address;
DEBUG_PRINT(sfree(p35););
printStats();
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(srealloc(p193,80););
printStats();
void* p259 = last_address;
PRINT_POINTER(srealloc(p255,54););
printStats();
void* p260 = last_address;
PRINT_POINTER(srealloc(p228,139););
printStats();
void* p261 = last_address;
PRINT_POINTER(srealloc(p149,241););
printStats();
void* p262 = last_address;
PRINT_POINTER(scalloc(116,201););
printStats();
void* p263 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p264 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p265 = last_address;
PRINT_POINTER(srealloc(p154,210););
printStats();
void* p266 = last_address;
DEBUG_PRINT(sfree(p229););
printStats();
PRINT_POINTER(smalloc(105););
printStats();
void* p267 = last_address;
DEBUG_PRINT(sfree(p231););
printStats();
PRINT_POINTER(smalloc(164););
printStats();
void* p268 = last_address;
PRINT_POINTER(scalloc(223,64););
printStats();
void* p269 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p270 = last_address;
PRINT_POINTER(scalloc(219,105););
printStats();
void* p271 = last_address;
PRINT_POINTER(scalloc(195,127););
printStats();
void* p272 = last_address;
DEBUG_PRINT(sfree(p182););
printStats();
PRINT_POINTER(smalloc(9););
printStats();
void* p273 = last_address;
PRINT_POINTER(srealloc(p242,18););
printStats();
void* p274 = last_address;
DEBUG_PRINT(sfree(p236););
printStats();
PRINT_POINTER(srealloc(p239,6););
printStats();
void* p275 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p276 = last_address;
DEBUG_PRINT(sfree(p207););
printStats();
PRINT_POINTER(srealloc(p217,130););
printStats();
void* p277 = last_address;
PRINT_POINTER(scalloc(31,121););
printStats();
void* p278 = last_address;
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(smalloc(177););
printStats();
void* p279 = last_address;
PRINT_POINTER(scalloc(66,121););
printStats();
void* p280 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p281 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(smalloc(80););
printStats();
void* p282 = last_address;
PRINT_POINTER(srealloc(p266,140););
printStats();
void* p283 = last_address;
PRINT_POINTER(srealloc(p258,205););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p237,229););
printStats();
void* p285 = last_address;
PRINT_POINTER(srealloc(p273,43););
printStats();
void* p286 = last_address;
PRINT_POINTER(srealloc(p213,227););
printStats();
void* p287 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p288 = last_address;
DEBUG_PRINT(sfree(p221););
printStats();
PRINT_POINTER(scalloc(80,86););
printStats();
void* p289 = last_address;
DEBUG_PRINT(sfree(p270););
printStats();
DEBUG_PRINT(sfree(p200););
printStats();
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(scalloc(168,197););
printStats();
void* p290 = last_address;
DEBUG_PRINT(sfree(p279););
printStats();
PRINT_POINTER(smalloc(47););
printStats();
void* p291 = last_address;
PRINT_POINTER(srealloc(p166,212););
printStats();
void* p292 = last_address;
DEBUG_PRINT(sfree(p235););
printStats();
PRINT_POINTER(scalloc(232,245););
printStats();
void* p293 = last_address;
PRINT_POINTER(srealloc(p208,134););
printStats();
void* p294 = last_address;
PRINT_POINTER(srealloc(p280,144););
printStats();
void* p295 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p296 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p297 = last_address;
DEBUG_PRINT(sfree(p77););
printStats();
PRINT_POINTER(smalloc(13););
printStats();
void* p298 = last_address;
DEBUG_PRINT(sfree(p276););
printStats();
PRINT_POINTER(scalloc(3,89););
printStats();
void* p299 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p300 = last_address;
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(scalloc(175,55););
printStats();
void* p301 = last_address;
PRINT_POINTER(scalloc(0,20););
printStats();
void* p302 = last_address;
DEBUG_PRINT(sfree(p298););
printStats();
PRINT_POINTER(smalloc(97););
printStats();
void* p303 = last_address;
PRINT_POINTER(scalloc(40,110););
printStats();
void* p304 = last_address;
PRINT_POINTER(scalloc(181,238););
printStats();
void* p305 = last_address;
DEBUG_PRINT(sfree(p233););
printStats();
PRINT_POINTER(srealloc(p272,23););
printStats();
void* p306 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p307 = last_address;
DEBUG_PRINT(sfree(p249););
printStats();
PRINT_POINTER(scalloc(15,91););
printStats();
void* p308 = last_address;
PRINT_POINTER(scalloc(5,202););
printStats();
void* p309 = last_address;
PRINT_POINTER(srealloc(p268,82););
printStats();
void* p310 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p311 = last_address;
PRINT_POINTER(srealloc(p195,1););
printStats();
void* p312 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p313 = last_address;
DEBUG_PRINT(sfree(p293););
printStats();
PRINT_POINTER(srealloc(p301,222););
printStats();
void* p314 = last_address;
PRINT_POINTER(scalloc(118,171););
printStats();
void* p315 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p316 = last_address;
PRINT_POINTER(srealloc(p282,60););
printStats();
void* p317 = last_address;
DEBUG_PRINT(sfree(p194););
printStats();
PRINT_POINTER(srealloc(p206,202););
printStats();
void* p318 = last_address;
PRINT_POINTER(srealloc(p85,158););
printStats();
void* p319 = last_address;
PRINT_POINTER(scalloc(245,145););
printStats();
void* p320 = last_address;
PRINT_POINTER(srealloc(p256,28););
printStats();
void* p321 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p322 = last_address;
PRINT_POINTER(scalloc(141,106););
printStats();
void* p323 = last_address;
PRINT_POINTER(scalloc(157,78););
printStats();
void* p324 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p325 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p326 = last_address;
PRINT_POINTER(smalloc(146););
printStats();
void* p327 = last_address;
PRINT_POINTER(srealloc(p248,117););
printStats();
void* p328 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p329 = last_address;
PRINT_POINTER(scalloc(96,4););
printStats();
void* p330 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p331 = last_address;
PRINT_POINTER(scalloc(101,7););
printStats();
void* p332 = last_address;
PRINT_POINTER(scalloc(77,209););
printStats();
void* p333 = last_address;
PRINT_POINTER(smalloc(63););
printStats();
void* p334 = last_address;
PRINT_POINTER(scalloc(49,102););
printStats();
void* p335 = last_address;
DEBUG_PRINT(sfree(p304););
printStats();
DEBUG_PRINT(sfree(p215););
printStats();
PRINT_POINTER(smalloc(153););
printStats();
void* p336 = last_address;
PRINT_POINTER(srealloc(p335,66););
printStats();
void* p337 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p338 = last_address;
PRINT_POINTER(srealloc(p257,237););
printStats();
void* p339 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p340 = last_address;
PRINT_POINTER(scalloc(148,22););
printStats();
void* p341 = last_address;
PRINT_POINTER(srealloc(p144,145););
printStats();
void* p342 = last_address;
DEBUG_PRINT(sfree(p180););
printStats();
PRINT_POINTER(smalloc(115););
printStats();
void* p343 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p344 = last_address;
PRINT_POINTER(scalloc(96,201););
printStats();
void* p345 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p346 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p347 = last_address;
PRINT_POINTER(srealloc(p275,216););
printStats();
void* p348 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
DEBUG_PRINT(sfree(p134););
printStats();
DEBUG_PRINT(sfree(p184););
printStats();
PRINT_POINTER(scalloc(223,148););
printStats();
void* p349 = last_address;
PRINT_POINTER(scalloc(67,81););
printStats();
void* p350 = last_address;
PRINT_POINTER(srealloc(p306,74););
printStats();
void* p351 = last_address;
PRINT_POINTER(scalloc(90,71););
printStats();
void* p352 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
PRINT_POINTER(smalloc(186););
printStats();
void* p353 = last_address;
PRINT_POINTER(scalloc(155,144););
printStats();
void* p354 = last_address;
DEBUG_PRINT(sfree(p264););
printStats();
DEBUG_PRINT(sfree(p302););
printStats();
PRINT_POINTER(scalloc(35,84););
printStats();
void* p355 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p356 = last_address;
DEBUG_PRINT(sfree(p240););
printStats();
DEBUG_PRINT(sfree(p80););
printStats();
PRINT_POINTER(srealloc(p338,218););
printStats();
void* p357 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p358 = last_address;
PRINT_POINTER(srealloc(p321,20););
printStats();
void* p359 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
DEBUG_PRINT(sfree(p269););
printStats();
DEBUG_PRINT(sfree(p290););
printStats();
DEBUG_PRINT(sfree(p310););
printStats();
PRINT_POINTER(srealloc(p168,92););
printStats();
void* p360 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p362 = last_address;
PRINT_POINTER(scalloc(68,83););
printStats();
void* p363 = last_address;
PRINT_POINTER(scalloc(233,75););
printStats();
void* p364 = last_address;
DEBUG_PRINT(sfree(p351););
printStats();
PRINT_POINTER(smalloc(126););
printStats();
void* p365 = last_address;
PRINT_POINTER(scalloc(167,224););
printStats();
void* p366 = last_address;
DEBUG_PRINT(sfree(p185););
printStats();
DEBUG_PRINT(sfree(p332););
printStats();
DEBUG_PRINT(sfree(p291););
printStats();
PRINT_POINTER(smalloc(67););
printStats();
void* p367 = last_address;
DEBUG_PRINT(sfree(p219););
printStats();
PRINT_POINTER(scalloc(154,97););
printStats();
void* p368 = last_address;
PRINT_POINTER(scalloc(241,172););
printStats();
void* p369 = last_address;
DEBUG_PRINT(sfree(p347););
printStats();
PRINT_POINTER(srealloc(p299,35););
printStats();
void* p370 = last_address;
PRINT_POINTER(srealloc(p353,134););
printStats();
void* p371 = last_address;
PRINT_POINTER(scalloc(199,194););
printStats();
void* p372 = last_address;
DEBUG_PRINT(sfree(p244););
printStats();
DEBUG_PRINT(sfree(p362););
printStats();
PRINT_POINTER(scalloc(212,12););
printStats();
void* p373 = last_address;
PRINT_POINTER(srealloc(p300,51););
printStats();
void* p374 = last_address;
PRINT_POINTER(srealloc(p241,239););
printStats();
void* p375 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p376 = last_address;
PRINT_POINTER(scalloc(19,221););
printStats();
void* p377 = last_address;
PRINT_POINTER(srealloc(p309,226););
printStats();
void* p378 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p379 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p380 = last_address;
DEBUG_PRINT(sfree(p198););
printStats();
DEBUG_PRINT(sfree(p288););
printStats();
PRINT_POINTER(scalloc(84,106););
printStats();
void* p381 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p382 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p383 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p384 = last_address;
DEBUG_PRINT(sfree(p354););
printStats();
PRINT_POINTER(scalloc(187,111););
printStats();
void* p385 = last_address;
PRINT_POINTER(scalloc(74,143););
printStats();
void* p386 = last_address;
PRINT_POINTER(srealloc(p311,175););
printStats();
void* p387 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p388 = last_address;
PRINT_POINTER(srealloc(p326,64););
printStats();
void* p389 = last_address;
DEBUG_PRINT(sfree(p368););
printStats();
PRINT_POINTER(smalloc(209););
printStats();
void* p390 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p391 = last_address;
PRINT_POINTER(srealloc(p259,51););
printStats();
void* p392 = last_address;
PRINT_POINTER(scalloc(216,48););
printStats();
void* p393 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p394 = last_address;
DEBUG_PRINT(sfree(p295););
printStats();
PRINT_POINTER(scalloc(200,225););
printStats();
void* p395 = last_address;
DEBUG_PRINT(sfree(p230););
printStats();
PRINT_POINTER(smalloc(140););
printStats();
void* p396 = last_address;
PRINT_POINTER(srealloc(p370,26););
printStats();
void* p397 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p398 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p399 = last_address;
PRINT_POINTER(scalloc(171,208););
printStats();
void* p400 = last_address;
DEBUG_PRINT(sfree(p379););
printStats();
PRINT_POINTER(scalloc(236,51););
printStats();
void* p401 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p402 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p403 = last_address;
PRINT_POINTER(srealloc(p226,154););
printStats();
void* p404 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p405 = last_address;
PRINT_POINTER(scalloc(174,67););
printStats();
void* p406 = last_address;
DEBUG_PRINT(sfree(p403););
printStats();
DEBUG_PRINT(sfree(p345););
printStats();
PRINT_POINTER(smalloc(179););
printStats();
void* p407 = last_address;
PRINT_POINTER(scalloc(87,9););
printStats();
void* p408 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p409 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p410 = last_address;
DEBUG_PRINT(sfree(p380););
printStats();
PRINT_POINTER(smalloc(89););
printStats();
void* p411 = last_address;
PRINT_POINTER(scalloc(99,106););
printStats();
void* p412 = last_address;
PRINT_POINTER(scalloc(25,189););
printStats();
void* p413 = last_address;
PRINT_POINTER(srealloc(p400,37););
printStats();
void* p414 = last_address;
PRINT_POINTER(srealloc(p297,23););
printStats();
void* p415 = last_address;
PRINT_POINTER(srealloc(p365,209););
printStats();
void* p416 = last_address;
DEBUG_PRINT(sfree(p383););
printStats();
PRINT_POINTER(scalloc(124,233););
printStats();
void* p417 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p418 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p419 = last_address;
PRINT_POINTER(srealloc(p227,228););
printStats();
void* p420 = last_address;
DEBUG_PRINT(sfree(p417););
printStats();
DEBUG_PRINT(sfree(p344););
printStats();
PRINT_POINTER(scalloc(108,186););
printStats();
void* p421 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p422 = last_address;
PRINT_POINTER(scalloc(195,197););
printStats();
void* p423 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p424 = last_address;
PRINT_POINTER(srealloc(p409,25););
printStats();
void* p425 = last_address;
DEBUG_PRINT(sfree(p262););
printStats();
PRINT_POINTER(scalloc(108,159););
printStats();
void* p426 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p427 = last_address;
PRINT_POINTER(srealloc(p281,62););
printStats();
void* p428 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p429 = last_address;
PRINT_POINTER(scalloc(78,221););
printStats();
void* p430 = last_address;
DEBUG_PRINT(sfree(p405););
printStats();
DEBUG_PRINT(sfree(p421););
printStats();
PRINT_POINTER(scalloc(8,1););
printStats();
void* p431 = last_address;
PRINT_POINTER(srealloc(p424,153););
printStats();
void* p432 = last_address;
DEBUG_PRINT(sfree(p372););
printStats();
DEBUG_PRINT(sfree(p349););
printStats();
PRINT_POINTER(scalloc(191,126););
printStats();
void* p433 = last_address;
DEBUG_PRINT(sfree(p145););
printStats();
PRINT_POINTER(smalloc(86););
printStats();
void* p434 = last_address;
DEBUG_PRINT(sfree(p330););
printStats();
PRINT_POINTER(smalloc(208););
printStats();
void* p435 = last_address;
PRINT_POINTER(scalloc(243,21););
printStats();
void* p436 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p437 = last_address;
PRINT_POINTER(srealloc(p382,239););
printStats();
void* p438 = last_address;
DEBUG_PRINT(sfree(p413););
printStats();
PRINT_POINTER(scalloc(103,192););
printStats();
void* p439 = last_address;
PRINT_POINTER(srealloc(p179,219););
printStats();
void* p440 = last_address;
PRINT_POINTER(srealloc(p316,205););
printStats();
void* p441 = last_address;
DEBUG_PRINT(sfree(p337););
printStats();
PRINT_POINTER(scalloc(10,3););
printStats();
void* p442 = last_address;
PRINT_POINTER(scalloc(159,168););
printStats();
void* p443 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p444 = last_address;
PRINT_POINTER(srealloc(p204,91););
printStats();
void* p445 = last_address;
PRINT_POINTER(srealloc(p212,247););
printStats();
void* p446 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p447 = last_address;
PRINT_POINTER(scalloc(87,19););
printStats();
void* p448 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p449 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p450 = last_address;
DEBUG_PRINT(sfree(p315););
printStats();
PRINT_POINTER(srealloc(p303,238););
printStats();
void* p451 = last_address;
PRINT_POINTER(scalloc(187,109););
printStats();
void* p452 = last_address;
PRINT_POINTER(srealloc(p340,89););
printStats();
void* p453 = last_address;
DEBUG_PRINT(sfree(p443););
printStats();
PRINT_POINTER(smalloc(175););
printStats();
void* p454 = last_address;
DEBUG_PRINT(sfree(p431););
printStats();
PRINT_POINTER(scalloc(217,88););
printStats();
void* p455 = last_address;
PRINT_POINTER(srealloc(p79,214););
printStats();
void* p456 = last_address;
PRINT_POINTER(srealloc(p375,3););
printStats();
void* p457 = last_address;
DEBUG_PRINT(sfree(p232););
printStats();
PRINT_POINTER(smalloc(185););
printStats();
void* p458 = last_address;
PRINT_POINTER(srealloc(p418,88););
printStats();
void* p459 = last_address;
PRINT_POINTER(scalloc(25,31););
printStats();
void* p460 = last_address;
DEBUG_PRINT(sfree(p322););
printStats();
PRINT_POINTER(scalloc(184,198););
printStats();
void* p461 = last_address;
PRINT_POINTER(srealloc(p407,29););
printStats();
void* p462 = last_address;
PRINT_POINTER(srealloc(p214,32););
printStats();
void* p463 = last_address;
DEBUG_PRINT(sfree(p425););
printStats();
PRINT_POINTER(scalloc(55,187););
printStats();
void* p464 = last_address;
DEBUG_PRINT(sfree(p420););
printStats();
DEBUG_PRINT(sfree(p450););
printStats();
PRINT_POINTER(scalloc(17,185););
printStats();
void* p465 = last_address;
DEBUG_PRINT(sfree(p333););
printStats();
PRINT_POINTER(srealloc(p336,228););
printStats();
void* p466 = last_address;
DEBUG_PRINT(sfree(p387););
printStats();
PRINT_POINTER(srealloc(p389,243););
printStats();
void* p467 = last_address;
PRINT_POINTER(srealloc(p181,123););
printStats();
void* p468 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p469 = last_address;
PRINT_POINTER(srealloc(p191,73););
printStats();
void* p470 = last_address;
PRINT_POINTER(srealloc(p458,119););
printStats();
void* p471 = last_address;
DEBUG_PRINT(sfree(p238););
printStats();
PRINT_POINTER(scalloc(162,129););
printStats();
void* p472 = last_address;
DEBUG_PRINT(sfree(p462););
printStats();
PRINT_POINTER(srealloc(p328,47););
printStats();
void* p473 = last_address;
PRINT_POINTER(srealloc(p445,155););
printStats();
void* p474 = last_address;
PRINT_POINTER(scalloc(85,40););
printStats();
void* p475 = last_address;
PRINT_POINTER(scalloc(198,61););
printStats();
void* p476 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p477 = last_address;
PRINT_POINTER(srealloc(p456,48););
printStats();
void* p478 = last_address;
PRINT_POINTER(scalloc(182,149););
printStats();
void* p479 = last_address;
PRINT_POINTER(srealloc(p271,223););
printStats();
void* p480 = last_address;
PRINT_POINTER(srealloc(p436,37););
printStats();
void* p481 = last_address;
PRINT_POINTER(scalloc(14,71););
printStats();
void* p482 = last_address;
PRINT_POINTER(scalloc(187,98););
printStats();
void* p483 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p484 = last_address;
DEBUG_PRINT(sfree(p292););
printStats();
DEBUG_PRINT(sfree(p476););
printStats();
PRINT_POINTER(smalloc(218););
printStats();
void* p485 = last_address;
DEBUG_PRINT(sfree(p447););
printStats();
PRINT_POINTER(scalloc(200,124););
printStats();
void* p486 = last_address;
PRINT_POINTER(scalloc(189,230););
printStats();
void* p487 = last_address;
PRINT_POINTER(scalloc(58,38););
printStats();
void* p488 = last_address;
PRINT_POINTER(scalloc(197,54););
printStats();
void* p489 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p490 = last_address;
PRINT_POINTER(scalloc(143,218););
printStats();
void* p491 = last_address;
PRINT_POINTER(srealloc(p346,74););
printStats();
void* p492 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p493 = last_address;
PRINT_POINTER(srealloc(p359,48););
printStats();
void* p494 = last_address;
PRINT_POINTER(srealloc(p415,71););
printStats();
void* p495 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p496 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p497 = last_address;
DEBUG_PRINT(sfree(p483););
printStats();
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(smalloc(65););
printStats();
void* p498 = last_address;
PRINT_POINTER(scalloc(84,174););
printStats();
void* p499 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p500 = last_address;
PRINT_POINTER(scalloc(151,208););
printStats();
void* p501 = last_address;
PRINT_POINTER(scalloc(129,193););
printStats();
void* p502 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p503 = last_address;
PRINT_POINTER(srealloc(p395,124););
printStats();
void* p504 = last_address;
PRINT_POINTER(srealloc(p396,69););
printStats();
void* p505 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p506 = last_address;
PRINT_POINTER(scalloc(75,17););
printStats();
void* p507 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p508 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p509 = last_address;
PRINT_POINTER(scalloc(77,156););
printStats();
void* p510 = last_address;
PRINT_POINTER(scalloc(113,153););
printStats();
void* p511 = last_address;
PRINT_POINTER(scalloc(5,149););
printStats();
void* p512 = last_address;
DEBUG_PRINT(sfree(p466););
printStats();
PRINT_POINTER(smalloc(198););
printStats();
void* p513 = last_address;
PRINT_POINTER(scalloc(17,25););
printStats();
void* p514 = last_address;
PRINT_POINTER(srealloc(p494,44););
printStats();
void* p515 = last_address;
PRINT_POINTER(srealloc(p355,75););
printStats();
void* p516 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p517 = last_address;
DEBUG_PRINT(sfree(p157););
printStats();
DEBUG_PRINT(sfree(p263););
printStats();
PRINT_POINTER(smalloc(157););
printStats();
void* p518 = last_address;
DEBUG_PRINT(sfree(p308););
printStats();
PRINT_POINTER(smalloc(167););
printStats();
void* p519 = last_address;
PRINT_POINTER(scalloc(30,223););
printStats();
void* p520 = last_address;
PRINT_POINTER(scalloc(187,114););
printStats();
void* p521 = last_address;
PRINT_POINTER(scalloc(123,225););
printStats();
void* p522 = last_address;
PRINT_POINTER(srealloc(p475,46););
printStats();
void* p523 = last_address;
PRINT_POINTER(scalloc(236,46););
printStats();
void* p524 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p525 = last_address;
PRINT_POINTER(scalloc(181,163););
printStats();
void* p526 = last_address;
PRINT_POINTER(srealloc(p252,33););
printStats();
void* p527 = last_address;
PRINT_POINTER(scalloc(138,108););
printStats();
void* p528 = last_address;
PRINT_POINTER(srealloc(p278,246););
printStats();
void* p529 = last_address;
DEBUG_PRINT(sfree(p245););
printStats();
PRINT_POINTER(srealloc(p508,31););
printStats();
void* p530 = last_address;
DEBUG_PRINT(sfree(p521););
printStats();
PRINT_POINTER(smalloc(27););
printStats();
void* p531 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p532 = last_address;
PRINT_POINTER(scalloc(212,100););
printStats();
void* p533 = last_address;
PRINT_POINTER(scalloc(128,157););
printStats();
void* p534 = last_address;
PRINT_POINTER(srealloc(p150,238););
printStats();
void* p535 = last_address;
DEBUG_PRINT(sfree(p246););
printStats();
PRINT_POINTER(srealloc(p422,139););
printStats();
void* p536 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p537 = last_address;
DEBUG_PRINT(sfree(p435););
printStats();
DEBUG_PRINT(sfree(p364););
printStats();
DEBUG_PRINT(sfree(p254););
printStats();
PRINT_POINTER(srealloc(p526,163););
printStats();
void* p538 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p539 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p540 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p541 = last_address;
PRINT_POINTER(scalloc(28,1););
printStats();
void* p542 = last_address;
PRINT_POINTER(scalloc(185,177););
printStats();
void* p543 = last_address;
PRINT_POINTER(srealloc(p511,231););
printStats();
void* p544 = last_address;
PRINT_POINTER(srealloc(p467,49););
printStats();
void* p545 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p546 = last_address;
PRINT_POINTER(scalloc(9,81););
printStats();
void* p547 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p548 = last_address;
DEBUG_PRINT(sfree(p478););
printStats();
PRINT_POINTER(scalloc(204,227););
printStats();
void* p549 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p550 = last_address;
PRINT_POINTER(scalloc(197,70););
printStats();
void* p551 = last_address;
PRINT_POINTER(scalloc(135,1););
printStats();
void* p552 = last_address;
PRINT_POINTER(srealloc(p519,156););
printStats();
void* p553 = last_address;
PRINT_POINTER(srealloc(p430,54););
printStats();
void* p554 = last_address;
PRINT_POINTER(scalloc(150,74););
printStats();
void* p555 = last_address;
PRINT_POINTER(srealloc(p540,150););
printStats();
void* p556 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p557 = last_address;
PRINT_POINTER(scalloc(10,58););
printStats();
void* p558 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p559 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p560 = last_address;
PRINT_POINTER(scalloc(80,46););
printStats();
void* p561 = last_address;
PRINT_POINTER(scalloc(23,31););
printStats();
void* p562 = last_address;
PRINT_POINTER(scalloc(61,225););
printStats();
void* p563 = last_address;
PRINT_POINTER(srealloc(p469,43););
printStats();
void* p564 = last_address;
PRINT_POINTER(srealloc(p434,77););
printStats();
void* p565 = last_address;
PRINT_POINTER(scalloc(217,137););
printStats();
void* p566 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p567 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p568 = last_address;
DEBUG_PRINT(sfree(p386););
printStats();
PRINT_POINTER(smalloc(185););
printStats();
void* p569 = last_address;
PRINT_POINTER(scalloc(246,105););
printStats();
void* p570 = last_address;
PRINT_POINTER(srealloc(p261,88););
printStats();
void* p571 = last_address;
PRINT_POINTER(scalloc(154,109););
printStats();
void* p572 = last_address;
PRINT_POINTER(srealloc(p428,63););
printStats();
void* p573 = last_address;
PRINT_POINTER(scalloc(22,232););
printStats();
void* p574 = last_address;
PRINT_POINTER(scalloc(98,35););
printStats();
void* p575 = last_address;
PRINT_POINTER(scalloc(107,133););
printStats();
void* p576 = last_address;
PRINT_POINTER(scalloc(11,193););
printStats();
void* p577 = last_address;
PRINT_POINTER(scalloc(160,215););
printStats();
void* p578 = last_address;
PRINT_POINTER(scalloc(90,153););
printStats();
void* p579 = last_address;
PRINT_POINTER(scalloc(211,20););
printStats();
void* p580 = last_address;
PRINT_POINTER(scalloc(202,104););
printStats();
void* p581 = last_address;
DEBUG_PRINT(sfree(p397););
printStats();
PRINT_POINTER(scalloc(59,190););
printStats();
void* p582 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p583 = last_address;
DEBUG_PRINT(sfree(p545););
printStats();
PRINT_POINTER(srealloc(p313,4););
printStats();
void* p584 = last_address;
DEBUG_PRINT(sfree(p505););
printStats();
PRINT_POINTER(scalloc(206,2););
printStats();
void* p585 = last_address;
DEBUG_PRINT(sfree(p341););
printStats();
DEBUG_PRINT(sfree(p572););
printStats();
PRINT_POINTER(srealloc(p325,112););
printStats();
void* p586 = last_address;
PRINT_POINTER(scalloc(248,64););
printStats();
void* p587 = last_address;
DEBUG_PRINT(sfree(p318););
printStats();
PRINT_POINTER(srealloc(p320,10););
printStats();
void* p588 = last_address;
PRINT_POINTER(scalloc(128,132););
printStats();
void* p589 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p590 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p591 = last_address;
PRINT_POINTER(srealloc(p416,63););
printStats();
void* p592 = last_address;
DEBUG_PRINT(sfree(p534););
printStats();
PRINT_POINTER(scalloc(211,157););
printStats();
void* p593 = last_address;
PRINT_POINTER(srealloc(p406,131););
printStats();
void* p594 = last_address;
DEBUG_PRINT(sfree(p385););
printStats();
PRINT_POINTER(smalloc(229););
printStats();
void* p595 = last_address;
PRINT_POINTER(scalloc(45,39););
printStats();
void* p596 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p597 = last_address;
DEBUG_PRINT(sfree(p541););
printStats();
PRINT_POINTER(smalloc(156););
printStats();
void* p598 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p599 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p600 = last_address;
PRINT_POINTER(scalloc(35,54););
printStats();
void* p601 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p602 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p603 = last_address;
PRINT_POINTER(srealloc(p527,173););
printStats();
void* p604 = last_address;
PRINT_POINTER(scalloc(241,161););
printStats();
void* p605 = last_address;
PRINT_POINTER(scalloc(142,118););
printStats();
void* p606 = last_address;
PRINT_POINTER(srealloc(p550,219););
printStats();
void* p607 = last_address;
DEBUG_PRINT(sfree(p427););
printStats();
PRINT_POINTER(smalloc(87););
printStats();
void* p608 = last_address;
DEBUG_PRINT(sfree(p524););
printStats();
PRINT_POINTER(scalloc(224,191););
printStats();
void* p609 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p610 = last_address;
PRINT_POINTER(srealloc(p398,92););
printStats();
void* p611 = last_address;
PRINT_POINTER(smalloc(90););
printStats();
void* p612 = last_address;
PRINT_POINTER(srealloc(p294,94););
printStats();
void* p613 = last_address;
DEBUG_PRINT(sfree(p331););
printStats();
PRINT_POINTER(scalloc(98,197););
printStats();
void* p614 = last_address;
PRINT_POINTER(scalloc(180,11););
printStats();
void* p615 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p616 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p617 = last_address;
DEBUG_PRINT(sfree(p477););
printStats();
PRINT_POINTER(srealloc(p363,93););
printStats();
void* p618 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p619 = last_address;
PRINT_POINTER(scalloc(119,145););
printStats();
void* p620 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p621 = last_address;
PRINT_POINTER(scalloc(14,244););
printStats();
void* p622 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p623 = last_address;
PRINT_POINTER(srealloc(p623,4););
printStats();
void* p624 = last_address;
PRINT_POINTER(scalloc(65,211););
printStats();
void* p625 = last_address;
PRINT_POINTER(srealloc(p471,242););
printStats();
void* p626 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p627 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p628 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p629 = last_address;
PRINT_POINTER(srealloc(p457,161););
printStats();
void* p630 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p631 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p632 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p633 = last_address;
DEBUG_PRINT(sfree(p609););
printStats();
PRINT_POINTER(scalloc(236,133););
printStats();
void* p634 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p635 = last_address;
PRINT_POINTER(srealloc(p523,111););
printStats();
void* p636 = last_address;
PRINT_POINTER(srealloc(p461,41););
printStats();
void* p637 = last_address;
PRINT_POINTER(scalloc(180,156););
printStats();
void* p638 = last_address;
DEBUG_PRINT(sfree(p580););
printStats();
PRINT_POINTER(scalloc(244,232););
printStats();
void* p639 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p640 = last_address;
PRINT_POINTER(scalloc(182,85););
printStats();
void* p641 = last_address;
DEBUG_PRINT(sfree(p468););
printStats();
PRINT_POINTER(srealloc(p459,111););
printStats();
void* p642 = last_address;
DEBUG_PRINT(sfree(p607););
printStats();
PRINT_POINTER(scalloc(137,89););
printStats();
void* p643 = last_address;
PRINT_POINTER(srealloc(p581,227););
printStats();
void* p644 = last_address;
DEBUG_PRINT(sfree(p504););
printStats();
PRINT_POINTER(scalloc(143,44););
printStats();
void* p645 = last_address;
PRINT_POINTER(srealloc(p277,103););
printStats();
void* p646 = last_address;
DEBUG_PRINT(sfree(p627););
printStats();
PRINT_POINTER(srealloc(p615,94););
printStats();
void* p647 = last_address;
PRINT_POINTER(scalloc(39,206););
printStats();
void* p648 = last_address;
PRINT_POINTER(srealloc(p218,247););
printStats();
void* p649 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p650 = last_address;
PRINT_POINTER(smalloc(80););
printStats();
void* p651 = last_address;
DEBUG_PRINT(sfree(p367););
printStats();
PRINT_POINTER(smalloc(188););
printStats();
void* p652 = last_address;
PRINT_POINTER(srealloc(p628,213););
printStats();
void* p653 = last_address;
PRINT_POINTER(scalloc(28,24););
printStats();
void* p654 = last_address;
DEBUG_PRINT(sfree(p493););
printStats();
PRINT_POINTER(scalloc(142,147););
printStats();
void* p655 = last_address;
PRINT_POINTER(srealloc(p562,160););
printStats();
void* p656 = last_address;
DEBUG_PRINT(sfree(p650););
printStats();
PRINT_POINTER(scalloc(30,128););
printStats();
void* p657 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p658 = last_address;
PRINT_POINTER(srealloc(p488,230););
printStats();
void* p659 = last_address;
PRINT_POINTER(scalloc(131,136););
printStats();
void* p660 = last_address;
PRINT_POINTER(srealloc(p634,48););
printStats();
void* p661 = last_address;
PRINT_POINTER(srealloc(p464,44););
printStats();
void* p662 = last_address;
DEBUG_PRINT(sfree(p531););
printStats();
PRINT_POINTER(srealloc(p329,139););
printStats();
void* p663 = last_address;
PRINT_POINTER(srealloc(p600,128););
printStats();
void* p664 = last_address;
DEBUG_PRINT(sfree(p576););
printStats();
PRINT_POINTER(scalloc(9,93););
printStats();
void* p665 = last_address;
PRINT_POINTER(scalloc(143,66););
printStats();
void* p666 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p667 = last_address;
PRINT_POINTER(srealloc(p574,233););
printStats();
void* p668 = last_address;
PRINT_POINTER(scalloc(208,116););
printStats();
void* p669 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(srealloc(p536,35););
printStats();
void* p670 = last_address;
PRINT_POINTER(srealloc(p410,244););
printStats();
void* p671 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p672 = last_address;
PRINT_POINTER(srealloc(p286,103););
printStats();
void* p673 = last_address;
DEBUG_PRINT(sfree(p656););
printStats();
PRINT_POINTER(srealloc(p596,137););
printStats();
void* p674 = last_address;
PRINT_POINTER(srealloc(p156,44););
printStats();
void* p675 = last_address;
DEBUG_PRINT(sfree(p658););
printStats();
PRINT_POINTER(smalloc(243););
printStats();
void* p676 = last_address;
PRINT_POINTER(scalloc(205,90););
printStats();
void* p677 = last_address;
DEBUG_PRINT(sfree(p588););
printStats();
PRINT_POINTER(smalloc(162););
printStats();
void* p678 = last_address;
PRINT_POINTER(srealloc(p243,52););
printStats();
void* p679 = last_address;
PRINT_POINTER(srealloc(p657,57););
printStats();
void* p680 = last_address;
PRINT_POINTER(scalloc(77,107););
printStats();
void* p681 = last_address;
PRINT_POINTER(scalloc(206,219););
printStats();
void* p682 = last_address;
PRINT_POINTER(srealloc(p515,212););
printStats();
void* p683 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p684 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p685 = last_address;
PRINT_POINTER(scalloc(165,205););
printStats();
void* p686 = last_address;
PRINT_POINTER(scalloc(12,30););
printStats();
void* p687 = last_address;
PRINT_POINTER(scalloc(144,170););
printStats();
void* p688 = last_address;
PRINT_POINTER(srealloc(p663,8););
printStats();
void* p689 = last_address;
PRINT_POINTER(srealloc(p419,22););
printStats();
void* p690 = last_address;
PRINT_POINTER(scalloc(91,155););
printStats();
void* p691 = last_address;
PRINT_POINTER(scalloc(176,126););
printStats();
void* p692 = last_address;
PRINT_POINTER(smalloc(75););
printStats();
void* p693 = last_address;
PRINT_POINTER(srealloc(p667,14););
printStats();
void* p694 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p695 = last_address;
PRINT_POINTER(scalloc(151,144););
printStats();
void* p696 = last_address;
PRINT_POINTER(scalloc(230,186););
printStats();
void* p697 = last_address;
DEBUG_PRINT(sfree(p695););
printStats();
DEBUG_PRINT(sfree(p621););
printStats();
PRINT_POINTER(smalloc(95););
printStats();
void* p698 = last_address;
PRINT_POINTER(srealloc(p587,172););
printStats();
void* p699 = last_address;
PRINT_POINTER(srealloc(p546,60););
printStats();
void* p700 = last_address;
PRINT_POINTER(scalloc(155,124););
printStats();
void* p701 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p702 = last_address;
PRINT_POINTER(srealloc(p528,78););
printStats();
void* p703 = last_address;
PRINT_POINTER(scalloc(51,89););
printStats();
void* p704 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p705 = last_address;
DEBUG_PRINT(sfree(p283););
printStats();
DEBUG_PRINT(sfree(p296););
printStats();
PRINT_POINTER(smalloc(39););
printStats();
void* p706 = last_address;
PRINT_POINTER(scalloc(27,192););
printStats();
void* p707 = last_address;
PRINT_POINTER(scalloc(24,119););
printStats();
void* p708 = last_address;
PRINT_POINTER(srealloc(p525,11););
printStats();
void* p709 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p710 = last_address;
PRINT_POINTER(scalloc(182,14););
printStats();
void* p711 = last_address;
PRINT_POINTER(srealloc(p636,108););
printStats();
void* p712 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p713 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p714 = last_address;
DEBUG_PRINT(sfree(p586););
printStats();
PRINT_POINTER(scalloc(164,158););
printStats();
void* p715 = last_address;
PRINT_POINTER(srealloc(p490,42););
printStats();
void* p716 = last_address;
PRINT_POINTER(scalloc(186,141););
printStats();
void* p717 = last_address;
PRINT_POINTER(srealloc(p510,19););
printStats();
void* p718 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p719 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p720 = last_address;
PRINT_POINTER(srealloc(p684,41););
printStats();
void* p721 = last_address;
PRINT_POINTER(scalloc(33,147););
printStats();
void* p722 = last_address;
PRINT_POINTER(srealloc(p601,45););
printStats();
void* p723 = last_address;
PRINT_POINTER(srealloc(p429,158););
printStats();
void* p724 = last_address;
PRINT_POINTER(srealloc(p629,238););
printStats();
void* p725 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p726 = last_address;
PRINT_POINTER(srealloc(p543,184););
printStats();
void* p727 = last_address;
PRINT_POINTER(scalloc(205,60););
printStats();
void* p728 = last_address;
PRINT_POINTER(scalloc(183,108););
printStats();
void* p729 = last_address;
PRINT_POINTER(scalloc(218,79););
printStats();
void* p730 = last_address;
DEBUG_PRINT(sfree(p566););
printStats();
PRINT_POINTER(smalloc(50););
printStats();
void* p731 = last_address;
PRINT_POINTER(srealloc(p660,62););
printStats();
void* p732 = last_address;
DEBUG_PRINT(sfree(p578););
printStats();
PRINT_POINTER(scalloc(178,234););
printStats();
void* p733 = last_address;
PRINT_POINTER(smalloc(119););
printStats();
void* p734 = last_address;
PRINT_POINTER(srealloc(p715,169););
printStats();
void* p735 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p736 = last_address;
PRINT_POINTER(srealloc(p402,153););
printStats();
void* p737 = last_address;
PRINT_POINTER(srealloc(p289,123););
printStats();
void* p738 = last_address;
DEBUG_PRINT(sfree(p679););
printStats();
PRINT_POINTER(srealloc(p701,174););
printStats();
void* p739 = last_address;
PRINT_POINTER(srealloc(p472,211););
printStats();
void* p740 = last_address;
PRINT_POINTER(scalloc(50,52););
printStats();
void* p741 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p742 = last_address;
DEBUG_PRINT(sfree(p724););
printStats();
PRINT_POINTER(srealloc(p529,228););
printStats();
void* p743 = last_address;
PRINT_POINTER(smalloc(187););
printStats();
void* p744 = last_address;
DEBUG_PRINT(sfree(p553););
printStats();
PRINT_POINTER(scalloc(152,90););
printStats();
void* p745 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p746 = last_address;
PRINT_POINTER(scalloc(53,27););
printStats();
void* p747 = last_address;
PRINT_POINTER(scalloc(222,34););
printStats();
void* p748 = last_address;
PRINT_POINTER(srealloc(p678,239););
printStats();
void* p749 = last_address;
PRINT_POINTER(srealloc(p725,213););
printStats();
void* p750 = last_address;
DEBUG_PRINT(sfree(p532););
printStats();
PRINT_POINTER(smalloc(173););
printStats();
void* p751 = last_address;
PRINT_POINTER(scalloc(106,225););
printStats();
void* p752 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p753 = last_address;
DEBUG_PRINT(sfree(p740););
printStats();
DEBUG_PRINT(sfree(p652););
printStats();
PRINT_POINTER(srealloc(p486,173););
printStats();
void* p754 = last_address;
PRINT_POINTER(scalloc(114,5););
printStats();
void* p755 = last_address;
PRINT_POINTER(srealloc(p631,85););
printStats();
void* p756 = last_address;
DEBUG_PRINT(sfree(p625););
printStats();
PRINT_POINTER(smalloc(209););
printStats();
void* p757 = last_address;
PRINT_POINTER(scalloc(222,180););
printStats();
void* p758 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p759 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p760 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p761 = last_address;
PRINT_POINTER(scalloc(176,192););
printStats();
void* p762 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p763 = last_address;
PRINT_POINTER(scalloc(202,57););
printStats();
void* p764 = last_address;
PRINT_POINTER(scalloc(65,79););
printStats();
void* p765 = last_address;
PRINT_POINTER(srealloc(p470,203););
printStats();
void* p766 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p767 = last_address;
PRINT_POINTER(scalloc(149,100););
printStats();
void* p768 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p769 = last_address;
PRINT_POINTER(srealloc(p565,122););
printStats();
void* p770 = last_address;
PRINT_POINTER(scalloc(26,3););
printStats();
void* p771 = last_address;
PRINT_POINTER(srealloc(p755,239););
printStats();
void* p772 = last_address;
DEBUG_PRINT(sfree(p479););
printStats();
PRINT_POINTER(srealloc(p513,246););
printStats();
void* p773 = last_address;
DEBUG_PRINT(sfree(p673););
printStats();
PRINT_POINTER(scalloc(209,13););
printStats();
void* p774 = last_address;
DEBUG_PRINT(sfree(p350););
printStats();
PRINT_POINTER(scalloc(91,221););
printStats();
void* p775 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p776 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p777 = last_address;
DEBUG_PRINT(sfree(p579););
printStats();
PRINT_POINTER(scalloc(24,210););
printStats();
void* p778 = last_address;
DEBUG_PRINT(sfree(p714););
printStats();
PRINT_POINTER(smalloc(70););
printStats();
void* p779 = last_address;
PRINT_POINTER(srealloc(p312,110););
printStats();
void* p780 = last_address;
PRINT_POINTER(scalloc(70,132););
printStats();
void* p781 = last_address;
PRINT_POINTER(scalloc(8,3););
printStats();
void* p782 = last_address;
DEBUG_PRINT(sfree(p727););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p783 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p784 = last_address;
PRINT_POINTER(scalloc(97,81););
printStats();
void* p785 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p786 = last_address;
PRINT_POINTER(srealloc(p454,17););
printStats();
void* p787 = last_address;
DEBUG_PRINT(sfree(p730););
printStats();
PRINT_POINTER(smalloc(119););
printStats();
void* p788 = last_address;
PRINT_POINTER(scalloc(47,201););
printStats();
void* p789 = last_address;
PRINT_POINTER(srealloc(p404,185););
printStats();
void* p790 = last_address;
PRINT_POINTER(scalloc(188,189););
printStats();
void* p791 = last_address;
PRINT_POINTER(srealloc(p617,207););
printStats();
void* p792 = last_address;
DEBUG_PRINT(sfree(p783););
printStats();
DEBUG_PRINT(sfree(p392););
printStats();
PRINT_POINTER(smalloc(61););
printStats();
void* p793 = last_address;
PRINT_POINTER(srealloc(p482,92););
printStats();
void* p794 = last_address;
PRINT_POINTER(srealloc(p708,113););
printStats();
void* p795 = last_address;
PRINT_POINTER(scalloc(167,37););
printStats();
void* p796 = last_address;
PRINT_POINTER(srealloc(p548,1););
printStats();
void* p797 = last_address;
PRINT_POINTER(srealloc(p591,52););
printStats();
void* p798 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p799 = last_address;
DEBUG_PRINT(sfree(p438););
printStats();
PRINT_POINTER(scalloc(161,72););
printStats();
void* p800 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p801 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p802 = last_address;
DEBUG_PRINT(sfree(p608););
printStats();
PRINT_POINTER(scalloc(31,188););
printStats();
void* p803 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p804 = last_address;
PRINT_POINTER(srealloc(p381,200););
printStats();
void* p805 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p806 = last_address;
PRINT_POINTER(scalloc(88,18););
printStats();
void* p807 = last_address;
PRINT_POINTER(srealloc(p659,186););
printStats();
void* p808 = last_address;
PRINT_POINTER(scalloc(188,26););
printStats();
void* p809 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p810 = last_address;
DEBUG_PRINT(sfree(p797););
printStats();
PRINT_POINTER(smalloc(239););
printStats();
void* p811 = last_address;
PRINT_POINTER(srealloc(p666,95););
printStats();
void* p812 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p813 = last_address;
PRINT_POINTER(srealloc(p171,150););
printStats();
void* p814 = last_address;
DEBUG_PRINT(sfree(p568););
printStats();
PRINT_POINTER(smalloc(230););
printStats();
void* p815 = last_address;
PRINT_POINTER(scalloc(12,203););
printStats();
void* p816 = last_address;
PRINT_POINTER(scalloc(102,234););
printStats();
void* p817 = last_address;
PRINT_POINTER(scalloc(101,213););
printStats();
void* p818 = last_address;
PRINT_POINTER(scalloc(33,174););
printStats();
void* p819 = last_address;
PRINT_POINTER(scalloc(246,62););
printStats();
void* p820 = last_address;
PRINT_POINTER(srealloc(p745,220););
printStats();
void* p821 = last_address;
PRINT_POINTER(scalloc(41,186););
printStats();
void* p822 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p823 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p824 = last_address;
PRINT_POINTER(srealloc(p356,235););
printStats();
void* p825 = last_address;
PRINT_POINTER(scalloc(187,22););
printStats();
void* p826 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p827 = last_address;
DEBUG_PRINT(sfree(p324););
printStats();
PRINT_POINTER(srealloc(p509,188););
printStats();
void* p828 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p829 = last_address;
PRINT_POINTER(srealloc(p683,26););
printStats();
void* p830 = last_address;
PRINT_POINTER(scalloc(116,170););
printStats();
void* p831 = last_address;
PRINT_POINTER(srealloc(p202,117););
printStats();
void* p832 = last_address;
PRINT_POINTER(scalloc(206,25););
printStats();
void* p833 = last_address;
DEBUG_PRINT(sfree(p785););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p834 = last_address;
DEBUG_PRINT(sfree(p737););
printStats();
PRINT_POINTER(srealloc(p726,210););
printStats();
void* p835 = last_address;
PRINT_POINTER(scalloc(245,25););
printStats();
void* p836 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p837 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p838 = last_address;
DEBUG_PRINT(sfree(p662););
printStats();
PRINT_POINTER(scalloc(6,169););
printStats();
void* p839 = last_address;
PRINT_POINTER(srealloc(p672,35););
printStats();
void* p840 = last_address;
PRINT_POINTER(smalloc(188););
printStats();
void* p841 = last_address;
PRINT_POINTER(srealloc(p343,14););
printStats();
void* p842 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p843 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p844 = last_address;
DEBUG_PRINT(sfree(p412););
printStats();
PRINT_POINTER(srealloc(p709,228););
printStats();
void* p845 = last_address;
DEBUG_PRINT(sfree(p680););
printStats();
PRINT_POINTER(smalloc(125););
printStats();
void* p846 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p847 = last_address;
PRINT_POINTER(srealloc(p130,63););
printStats();
void* p848 = last_address;
PRINT_POINTER(scalloc(138,8););
printStats();
void* p849 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p850 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p851 = last_address;
PRINT_POINTER(scalloc(96,72););
printStats();
void* p852 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p853 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p854 = last_address;
PRINT_POINTER(scalloc(160,191););
printStats();
void* p855 = last_address;
DEBUG_PRINT(sfree(p835););
printStats();
PRINT_POINTER(smalloc(53););
printStats();
void* p856 = last_address;
DEBUG_PRINT(sfree(p606););
printStats();
DEBUG_PRINT(sfree(p855););
printStats();
PRINT_POINTER(srealloc(p773,205););
printStats();
void* p857 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p858 = last_address;
PRINT_POINTER(scalloc(131,4););
printStats();
void* p859 = last_address;
PRINT_POINTER(scalloc(45,132););
printStats();
void* p860 = last_address;
PRINT_POINTER(smalloc(239););
printStats();
void* p861 = last_address;
PRINT_POINTER(srealloc(p861,30););
printStats();
void* p862 = last_address;
PRINT_POINTER(srealloc(p776,104););
printStats();
void* p863 = last_address;
PRINT_POINTER(srealloc(p777,193););
printStats();
void* p864 = last_address;
PRINT_POINTER(scalloc(182,215););
printStats();
void* p865 = last_address;
PRINT_POINTER(scalloc(61,169););
printStats();
void* p866 = last_address;
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(srealloc(p399,14););
printStats();
void* p867 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p868 = last_address;
PRINT_POINTER(scalloc(244,62););
printStats();
void* p869 = last_address;
DEBUG_PRINT(sfree(p837););
printStats();
PRINT_POINTER(srealloc(p393,147););
printStats();
void* p870 = last_address;
DEBUG_PRINT(sfree(p847););
printStats();
PRINT_POINTER(srealloc(p798,97););
printStats();
void* p871 = last_address;
DEBUG_PRINT(sfree(p307););
printStats();
PRINT_POINTER(srealloc(p378,1););
printStats();
void* p872 = last_address;
PRINT_POINTER(scalloc(56,227););
printStats();
void* p873 = last_address;
PRINT_POINTER(scalloc(23,78););
printStats();
void* p874 = last_address;
PRINT_POINTER(scalloc(33,211););
printStats();
void* p875 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p876 = last_address;
PRINT_POINTER(srealloc(p610,241););
printStats();
void* p877 = last_address;
DEBUG_PRINT(sfree(p557););
printStats();
PRINT_POINTER(srealloc(p439,77););
printStats();
void* p878 = last_address;
DEBUG_PRINT(sfree(p671););
printStats();
PRINT_POINTER(smalloc(160););
printStats();
void* p879 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p880 = last_address;
DEBUG_PRINT(sfree(p506););
printStats();
PRINT_POINTER(scalloc(213,184););
printStats();
void* p881 = last_address;
DEBUG_PRINT(sfree(p605););
printStats();
PRINT_POINTER(scalloc(31,171););
printStats();
void* p882 = last_address;
DEBUG_PRINT(sfree(p570););
printStats();
DEBUG_PRINT(sfree(p839););
printStats();
DEBUG_PRINT(sfree(p718););
printStats();
DEBUG_PRINT(sfree(p752););
printStats();
DEBUG_PRINT(sfree(p423););
printStats();
PRINT_POINTER(scalloc(134,163););
printStats();
void* p883 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
PRINT_POINTER(smalloc(226););
printStats();
void* p884 = last_address;
PRINT_POINTER(scalloc(47,125););
printStats();
void* p885 = last_address;
PRINT_POINTER(scalloc(146,181););
printStats();
void* p886 = last_address;
DEBUG_PRINT(sfree(p556););
printStats();
PRINT_POINTER(smalloc(198););
printStats();
void* p887 = last_address;
PRINT_POINTER(scalloc(26,105););
printStats();
void* p888 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p889 = last_address;
PRINT_POINTER(scalloc(69,236););
printStats();
void* p890 = last_address;
DEBUG_PRINT(sfree(p799););
printStats();
PRINT_POINTER(scalloc(92,81););
printStats();
void* p891 = last_address;
PRINT_POINTER(srealloc(p640,177););
printStats();
void* p892 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p893 = last_address;
PRINT_POINTER(scalloc(146,124););
printStats();
void* p894 = last_address;
DEBUG_PRINT(sfree(p696););
printStats();
DEBUG_PRINT(sfree(p305););
printStats();
PRINT_POINTER(scalloc(155,101););
printStats();
void* p895 = last_address;
PRINT_POINTER(scalloc(151,52););
printStats();
void* p896 = last_address;
PRINT_POINTER(srealloc(p846,198););
printStats();
void* p897 = last_address;
PRINT_POINTER(srealloc(p713,128););
printStats();
void* p898 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p899 = last_address;
PRINT_POINTER(scalloc(93,5););
printStats();
void* p900 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p901 = last_address;
PRINT_POINTER(srealloc(p890,216););
printStats();
void* p902 = last_address;
DEBUG_PRINT(sfree(p845););
printStats();
DEBUG_PRINT(sfree(p770););
printStats();
PRINT_POINTER(srealloc(p287,121););
printStats();
void* p903 = last_address;
PRINT_POINTER(scalloc(124,146););
printStats();
void* p904 = last_address;
PRINT_POINTER(srealloc(p216,224););
printStats();
void* p905 = last_address;
PRINT_POINTER(srealloc(p858,159););
printStats();
void* p906 = last_address;
PRINT_POINTER(scalloc(137,168););
printStats();
void* p907 = last_address;
PRINT_POINTER(srealloc(p705,54););
printStats();
void* p908 = last_address;
DEBUG_PRINT(sfree(p492););
printStats();
DEBUG_PRINT(sfree(p411););
printStats();
DEBUG_PRINT(sfree(p502););
printStats();
PRINT_POINTER(scalloc(170,16););
printStats();
void* p909 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p910 = last_address;
PRINT_POINTER(scalloc(210,138););
printStats();
void* p911 = last_address;
PRINT_POINTER(scalloc(232,174););
printStats();
void* p912 = last_address;
PRINT_POINTER(srealloc(p626,124););
printStats();
void* p913 = last_address;
PRINT_POINTER(smalloc(243););
printStats();
void* p914 = last_address;
DEBUG_PRINT(sfree(p317););
printStats();
PRINT_POINTER(smalloc(152););
printStats();
void* p915 = last_address;
PRINT_POINTER(srealloc(p635,179););
printStats();
void* p916 = last_address;
DEBUG_PRINT(sfree(p906););
printStats();
PRINT_POINTER(scalloc(83,140););
printStats();
void* p917 = last_address;
DEBUG_PRINT(sfree(p789););
printStats();
PRINT_POINTER(srealloc(p642,13););
printStats();
void* p918 = last_address;
PRINT_POINTER(scalloc(206,203););
printStats();
void* p919 = last_address;
PRINT_POINTER(srealloc(p599,235););
printStats();
void* p920 = last_address;
PRINT_POINTER(scalloc(202,79););
printStats();
void* p921 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p922 = last_address;
DEBUG_PRINT(sfree(p446););
printStats();
PRINT_POINTER(smalloc(8););
printStats();
void* p923 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p924 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p925 = last_address;
DEBUG_PRINT(sfree(p639););
printStats();
PRINT_POINTER(srealloc(p376,241););
printStats();
void* p926 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p927 = last_address;
PRINT_POINTER(srealloc(p361,70););
printStats();
void* p928 = last_address;
PRINT_POINTER(srealloc(p827,60););
printStats();
void* p929 = last_address;
PRINT_POINTER(scalloc(121,27););
printStats();
void* p930 = last_address;
PRINT_POINTER(srealloc(p500,113););
printStats();
void* p931 = last_address;
PRINT_POINTER(srealloc(p426,183););
printStats();
void* p932 = last_address;
DEBUG_PRINT(sfree(p498););
printStats();
PRINT_POINTER(smalloc(67););
printStats();
void* p933 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p934 = last_address;
PRINT_POINTER(scalloc(74,88););
printStats();
void* p935 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p936 = last_address;
DEBUG_PRINT(sfree(p733););
printStats();
PRINT_POINTER(srealloc(p753,185););
printStats();
void* p937 = last_address;
DEBUG_PRINT(sfree(p637););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p938 = last_address;
PRINT_POINTER(scalloc(131,187););
printStats();
void* p939 = last_address;
PRINT_POINTER(scalloc(51,138););
printStats();
void* p940 = last_address;
PRINT_POINTER(srealloc(p187,90););
printStats();
void* p941 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p942 = last_address;
PRINT_POINTER(srealloc(p879,35););
printStats();
void* p943 = last_address;
PRINT_POINTER(srealloc(p742,225););
printStats();
void* p944 = last_address;
PRINT_POINTER(srealloc(p432,102););
printStats();
void* p945 = last_address;
PRINT_POINTER(scalloc(191,232););
printStats();
void* p946 = last_address;
PRINT_POINTER(scalloc(77,122););
printStats();
void* p947 = last_address;
DEBUG_PRINT(sfree(p876););
printStats();
PRINT_POINTER(srealloc(p921,84););
printStats();
void* p948 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p949 = last_address;
DEBUG_PRINT(sfree(p598););
printStats();
PRINT_POINTER(scalloc(108,181););
printStats();
void* p950 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p951 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p952 = last_address;
DEBUG_PRINT(sfree(p624););
printStats();
PRINT_POINTER(srealloc(p883,228););
printStats();
void* p953 = last_address;
PRINT_POINTER(scalloc(22,8););
printStats();
void* p954 = last_address;
DEBUG_PRINT(sfree(p487););
printStats();
PRINT_POINTER(scalloc(170,12););
printStats();
void* p955 = last_address;
PRINT_POINTER(srealloc(p784,67););
printStats();
void* p956 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p957 = last_address;
DEBUG_PRINT(sfree(p893););
printStats();
PRINT_POINTER(scalloc(108,169););
printStats();
void* p958 = last_address;
PRINT_POINTER(scalloc(23,13););
printStats();
void* p959 = last_address;
DEBUG_PRINT(sfree(p611););
printStats();
PRINT_POINTER(smalloc(44););
printStats();
void* p960 = last_address;
PRINT_POINTER(srealloc(p790,55););
printStats();
void* p961 = last_address;
DEBUG_PRINT(sfree(p896););
printStats();
PRINT_POINTER(srealloc(p891,121););
printStats();
void* p962 = last_address;
PRINT_POINTER(srealloc(p685,181););
printStats();
void* p963 = last_address;
PRINT_POINTER(srealloc(p401,45););
printStats();
void* p964 = last_address;
DEBUG_PRINT(sfree(p904););
printStats();
PRINT_POINTER(srealloc(p810,169););
printStats();
void* p965 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p966 = last_address;
PRINT_POINTER(scalloc(182,89););
printStats();
void* p967 = last_address;
DEBUG_PRINT(sfree(p743););
printStats();
PRINT_POINTER(srealloc(p618,181););
printStats();
void* p968 = last_address;
DEBUG_PRINT(sfree(p762););
printStats();
DEBUG_PRINT(sfree(p946););
printStats();
PRINT_POINTER(srealloc(p758,164););
printStats();
void* p969 = last_address;
PRINT_POINTER(scalloc(27,208););
printStats();
void* p970 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p971 = last_address;
PRINT_POINTER(srealloc(p480,92););
printStats();
void* p972 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p973 = last_address;
PRINT_POINTER(scalloc(124,125););
printStats();
void* p974 = last_address;
PRINT_POINTER(scalloc(81,49););
printStats();
void* p975 = last_address;
PRINT_POINTER(srealloc(p949,148););
printStats();
void* p976 = last_address;
PRINT_POINTER(scalloc(216,216););
printStats();
void* p977 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p978 = last_address;
DEBUG_PRINT(sfree(p754););
printStats();
DEBUG_PRINT(sfree(p856););
printStats();
DEBUG_PRINT(sfree(p956););
printStats();
PRINT_POINTER(srealloc(p703,163););
printStats();
void* p979 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p980 = last_address;
PRINT_POINTER(srealloc(p902,169););
printStats();
void* p981 = last_address;
PRINT_POINTER(srealloc(p953,50););
printStats();
void* p982 = last_address;
PRINT_POINTER(scalloc(62,230););
printStats();
void* p983 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p984 = last_address;
DEBUG_PRINT(sfree(p736););
printStats();
PRINT_POINTER(srealloc(p647,39););
printStats();
void* p985 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p986 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p987 = last_address;
PRINT_POINTER(srealloc(p284,125););
printStats();
void* p988 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p989 = last_address;
DEBUG_PRINT(sfree(p712););
printStats();
PRINT_POINTER(srealloc(p507,92););
printStats();
void* p990 = last_address;
DEBUG_PRINT(sfree(p928););
printStats();
PRINT_POINTER(scalloc(217,176););
printStats();
void* p991 = last_address;
PRINT_POINTER(scalloc(237,54););
printStats();
void* p992 = last_address;
PRINT_POINTER(srealloc(p391,126););
printStats();
void* p993 = last_address;
PRINT_POINTER(srealloc(p497,43););
printStats();
void* p994 = last_address;
DEBUG_PRINT(sfree(p864););
printStats();
PRINT_POINTER(scalloc(44,131););
printStats();
void* p995 = last_address;
DEBUG_PRINT(sfree(p801););
printStats();
PRINT_POINTER(scalloc(102,96););
printStats();
void* p996 = last_address;
DEBUG_PRINT(sfree(p811););
printStats();
PRINT_POINTER(scalloc(155,193););
printStats();
void* p997 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p998 = last_address;
DEBUG_PRINT(sfree(p390););
printStats();
PRINT_POINTER(srealloc(p577,77););
printStats();
void* p999 = last_address;
PRINT_POINTER(scalloc(151,206););
printStats();
void* p1000 = last_address;
DEBUG_PRINT(sfree(p554););
printStats();
DEBUG_PRINT(sfree(p700););
printStats();
PRINT_POINTER(smalloc(71););
printStats();
void* p1001 = last_address;
DEBUG_PRINT(sfree(p955););
printStats();
PRINT_POINTER(scalloc(67,60););
printStats();
void* p1002 = last_address;
PRINT_POINTER(srealloc(p590,244););
printStats();
void* p1003 = last_address;
PRINT_POINTER(scalloc(201,137););
printStats();
void* p1004 = last_address;
PRINT_POINTER(scalloc(234,20););
printStats();
void* p1005 = last_address;
PRINT_POINTER(smalloc(20););
printStats();
void* p1006 = last_address;
PRINT_POINTER(scalloc(110,159););
printStats();
void* p1007 = last_address;
PRINT_POINTER(scalloc(161,133););
printStats();
void* p1008 = last_address;
PRINT_POINTER(srealloc(p982,119););
printStats();
void* p1009 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p1010 = last_address;
PRINT_POINTER(scalloc(144,143););
printStats();
void* p1011 = last_address;
DEBUG_PRINT(sfree(p998););
printStats();
PRINT_POINTER(smalloc(24););
printStats();
void* p1012 = last_address;
DEBUG_PRINT(sfree(p881););
printStats();
DEBUG_PRINT(sfree(p681););
printStats();
PRINT_POINTER(srealloc(p728,128););
printStats();
void* p1013 = last_address;
DEBUG_PRINT(sfree(p877););
printStats();
PRINT_POINTER(srealloc(p874,218););
printStats();
void* p1014 = last_address;
PRINT_POINTER(srealloc(p788,176););
printStats();
void* p1015 = last_address;
DEBUG_PRINT(sfree(p967););
printStats();
PRINT_POINTER(scalloc(190,211););
printStats();
void* p1016 = last_address;
PRINT_POINTER(srealloc(p744,69););
printStats();
void* p1017 = last_address;
PRINT_POINTER(scalloc(197,7););
printStats();
void* p1018 = last_address;
DEBUG_PRINT(sfree(p979););
printStats();
PRINT_POINTER(scalloc(202,8););
printStats();
void* p1019 = last_address;
PRINT_POINTER(srealloc(p539,209););
printStats();
void* p1020 = last_address;
PRINT_POINTER(scalloc(104,25););
printStats();
void* p1021 = last_address;
DEBUG_PRINT(sfree(p986););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p1022 = last_address;
DEBUG_PRINT(sfree(p954););
printStats();
DEBUG_PRINT(sfree(p583););
printStats();
PRINT_POINTER(srealloc(p866,39););
printStats();
void* p1023 = last_address;
PRINT_POINTER(srealloc(p897,173););
printStats();
void* p1024 = last_address;
PRINT_POINTER(scalloc(51,100););
printStats();
void* p1025 = last_address;
PRINT_POINTER(scalloc(90,106););
printStats();
void* p1026 = last_address;
PRINT_POINTER(srealloc(p818,125););
printStats();
void* p1027 = last_address;
PRINT_POINTER(scalloc(153,121););
printStats();
void* p1028 = last_address;
DEBUG_PRINT(sfree(p901););
printStats();
PRINT_POINTER(smalloc(171););
printStats();
void* p1029 = last_address;
PRINT_POINTER(srealloc(p593,71););
printStats();
void* p1030 = last_address;
DEBUG_PRINT(sfree(p992););
printStats();
PRINT_POINTER(scalloc(136,12););
printStats();
void* p1031 = last_address;
DEBUG_PRINT(sfree(p840););
printStats();
PRINT_POINTER(scalloc(39,46););
printStats();
void* p1032 = last_address;
PRINT_POINTER(scalloc(192,63););
printStats();
void* p1033 = last_address;
PRINT_POINTER(srealloc(p460,153););
printStats();
void* p1034 = last_address;
PRINT_POINTER(scalloc(196,95););
printStats();
void* p1035 = last_address;
DEBUG_PRINT(sfree(p1031););
printStats();
PRINT_POINTER(srealloc(p732,102););
printStats();
void* p1036 = last_address;
PRINT_POINTER(srealloc(p542,70););
printStats();
void* p1037 = last_address;
DEBUG_PRINT(sfree(p499););
printStats();
PRINT_POINTER(smalloc(229););
printStats();
void* p1038 = last_address;
DEBUG_PRINT(sfree(p1004););
printStats();
PRINT_POINTER(scalloc(237,197););
printStats();
void* p1039 = last_address;
DEBUG_PRINT(sfree(p880););
printStats();
PRINT_POINTER(scalloc(145,190););
printStats();
void* p1040 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p1041 = last_address;
PRINT_POINTER(scalloc(33,181););
printStats();
void* p1042 = last_address;
PRINT_POINTER(scalloc(200,191););
printStats();
void* p1043 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p1044 = last_address;
DEBUG_PRINT(sfree(p677););
printStats();
PRINT_POINTER(scalloc(74,62););
printStats();
void* p1045 = last_address;
PRINT_POINTER(scalloc(7,205););
printStats();
void* p1046 = last_address;
DEBUG_PRINT(sfree(p849););
printStats();
PRINT_POINTER(srealloc(p638,6););
printStats();
void* p1047 = last_address;
PRINT_POINTER(scalloc(104,213););
printStats();
void* p1048 = last_address;
DEBUG_PRINT(sfree(p930););
printStats();
PRINT_POINTER(scalloc(157,180););
printStats();
void* p1049 = last_address;
PRINT_POINTER(scalloc(200,37););
printStats();
void* p1050 = last_address;
DEBUG_PRINT(sfree(p433););
printStats();
PRINT_POINTER(smalloc(69););
printStats();
void* p1051 = last_address;
DEBUG_PRINT(sfree(p976););
printStats();
PRINT_POINTER(scalloc(47,11););
printStats();
void* p1052 = last_address;
PRINT_POINTER(scalloc(4,155););
printStats();
void* p1053 = last_address;
PRINT_POINTER(srealloc(p369,175););
printStats();
void* p1054 = last_address;
PRINT_POINTER(scalloc(238,209););
printStats();
void* p1055 = last_address;
PRINT_POINTER(scalloc(246,28););
printStats();
void* p1056 = last_address;
PRINT_POINTER(srealloc(p747,28););
printStats();
void* p1057 = last_address;
PRINT_POINTER(srealloc(p1003,115););
printStats();
void* p1058 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p1059 = last_address;
PRINT_POINTER(scalloc(1,116););
printStats();
void* p1060 = last_address;
PRINT_POINTER(srealloc(p552,79););
printStats();
void* p1061 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p1062 = last_address;
DEBUG_PRINT(sfree(p985););
printStats();
PRINT_POINTER(smalloc(28););
printStats();
void* p1063 = last_address;
PRINT_POINTER(scalloc(57,156););
printStats();
void* p1064 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p1065 = last_address;
PRINT_POINTER(scalloc(208,8););
printStats();
void* p1066 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p1067 = last_address;
DEBUG_PRINT(sfree(p1046););
printStats();
DEBUG_PRINT(sfree(p327););
printStats();
PRINT_POINTER(scalloc(170,229););
printStats();
void* p1068 = last_address;
PRINT_POINTER(srealloc(p496,90););
printStats();
void* p1069 = last_address;
PRINT_POINTER(scalloc(187,144););
printStats();
void* p1070 = last_address;
PRINT_POINTER(scalloc(137,23););
printStats();
void* p1071 = last_address;
PRINT_POINTER(scalloc(185,134););
printStats();
void* p1072 = last_address;
DEBUG_PRINT(sfree(p582););
printStats();
PRINT_POINTER(smalloc(111););
printStats();
void* p1073 = last_address;
DEBUG_PRINT(sfree(p913););
printStats();
PRINT_POINTER(srealloc(p971,215););
printStats();
void* p1074 = last_address;
DEBUG_PRINT(sfree(p871););
printStats();
PRINT_POINTER(srealloc(p314,103););
printStats();
void* p1075 = last_address;
DEBUG_PRINT(sfree(p501););
printStats();
PRINT_POINTER(srealloc(p941,35););
printStats();
void* p1076 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p1077 = last_address;
PRINT_POINTER(srealloc(p567,172););
printStats();
void* p1078 = last_address;
PRINT_POINTER(srealloc(p938,176););
printStats();
void* p1079 = last_address;
PRINT_POINTER(srealloc(p620,174););
printStats();
void* p1080 = last_address;
PRINT_POINTER(srealloc(p1028,22););
printStats();
void* p1081 = last_address;
PRINT_POINTER(scalloc(47,118););
printStats();
void* p1082 = last_address;
DEBUG_PRINT(sfree(p822););
printStats();
DEBUG_PRINT(sfree(p750););
printStats();
PRINT_POINTER(srealloc(p1044,14););
printStats();
void* p1083 = last_address;
PRINT_POINTER(srealloc(p842,184););
printStats();
void* p1084 = last_address;
PRINT_POINTER(scalloc(84,195););
printStats();
void* p1085 = last_address;
PRINT_POINTER(scalloc(7,95););
printStats();
void* p1086 = last_address;
PRINT_POINTER(scalloc(169,13););
printStats();
void* p1087 = last_address;
PRINT_POINTER(scalloc(4,81););
printStats();
void* p1088 = last_address;
DEBUG_PRINT(sfree(p555););
printStats();
DEBUG_PRINT(sfree(p1024););
printStats();
PRINT_POINTER(srealloc(p549,53););
printStats();
void* p1089 = last_address;
PRINT_POINTER(srealloc(p850,133););
printStats();
void* p1090 = last_address;
PRINT_POINTER(smalloc(80););
printStats();
void* p1091 = last_address;
PRINT_POINTER(scalloc(4,191););
printStats();
void* p1092 = last_address;
DEBUG_PRINT(sfree(p704););
printStats();
PRINT_POINTER(srealloc(p819,134););
printStats();
void* p1093 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p1094 = last_address;
PRINT_POINTER(scalloc(92,216););
printStats();
void* p1095 = last_address;
DEBUG_PRINT(sfree(p936););
printStats();
PRINT_POINTER(scalloc(154,103););
printStats();
void* p1096 = last_address;
PRINT_POINTER(scalloc(222,113););
printStats();
void* p1097 = last_address;
PRINT_POINTER(srealloc(p973,194););
printStats();
void* p1098 = last_address;
PRINT_POINTER(scalloc(223,91););
printStats();
void* p1099 = last_address;
DEBUG_PRINT(sfree(p794););
printStats();
DEBUG_PRINT(sfree(p597););
printStats();
DEBUG_PRINT(sfree(p485););
printStats();
PRINT_POINTER(scalloc(1,3););
printStats();
void* p1100 = last_address;
PRINT_POINTER(srealloc(p831,89););
printStats();
void* p1101 = last_address;
PRINT_POINTER(scalloc(203,119););
printStats();
void* p1102 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p1103 = last_address;
DEBUG_PRINT(sfree(p894););
printStats();
DEBUG_PRINT(sfree(p889););
printStats();
PRINT_POINTER(scalloc(222,25););
printStats();
void* p1104 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p1105 = last_address;
PRINT_POINTER(scalloc(216,181););
printStats();
void* p1106 = last_address;
PRINT_POINTER(scalloc(247,82););
printStats();
void* p1107 = last_address;
PRINT_POINTER(scalloc(52,147););
printStats();
void* p1108 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p1109 = last_address;
PRINT_POINTER(srealloc(p826,63););
printStats();
void* p1110 = last_address;
PRINT_POINTER(scalloc(240,163););
printStats();
void* p1111 = last_address;
PRINT_POINTER(srealloc(p503,14););
printStats();
void* p1112 = last_address;
DEBUG_PRINT(sfree(p441););
printStats();
DEBUG_PRINT(sfree(p760););
printStats();
DEBUG_PRINT(sfree(p1085););
printStats();
DEBUG_PRINT(sfree(p1075););
printStats();
DEBUG_PRINT(sfree(p778););
printStats();
PRINT_POINTER(srealloc(p978,20););
printStats();
void* p1113 = last_address;
DEBUG_PRINT(sfree(p1018););
printStats();
PRINT_POINTER(srealloc(p687,181););
printStats();
void* p1114 = last_address;
PRINT_POINTER(srealloc(p563,233););
printStats();
void* p1115 = last_address;
PRINT_POINTER(scalloc(56,92););
printStats();
void* p1116 = last_address;
DEBUG_PRINT(sfree(p463););
printStats();
PRINT_POINTER(scalloc(80,144););
printStats();
void* p1117 = last_address;
PRINT_POINTER(srealloc(p1051,44););
printStats();
void* p1118 = last_address;
DEBUG_PRINT(sfree(p388););
printStats();
PRINT_POINTER(smalloc(63););
printStats();
void* p1119 = last_address;
DEBUG_PRINT(sfree(p763););
printStats();
PRINT_POINTER(scalloc(13,118););
printStats();
void* p1120 = last_address;
PRINT_POINTER(srealloc(p805,48););
printStats();
void* p1121 = last_address;
PRINT_POINTER(srealloc(p942,163););
printStats();
void* p1122 = last_address;
PRINT_POINTER(srealloc(p834,202););
printStats();
void* p1123 = last_address;
PRINT_POINTER(srealloc(p1094,21););
printStats();
void* p1124 = last_address;
DEBUG_PRINT(sfree(p517););
printStats();
PRINT_POINTER(srealloc(p1061,152););
printStats();
void* p1125 = last_address;
PRINT_POINTER(srealloc(p1035,141););
printStats();
void* p1126 = last_address;
PRINT_POINTER(srealloc(p738,44););
printStats();
void* p1127 = last_address;
PRINT_POINTER(srealloc(p766,182););
printStats();
void* p1128 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p1129 = last_address;
PRINT_POINTER(srealloc(p995,229););
printStats();
void* p1130 = last_address;
PRINT_POINTER(scalloc(142,173););
printStats();
void* p1131 = last_address;
PRINT_POINTER(scalloc(211,7););
printStats();
void* p1132 = last_address;
DEBUG_PRINT(sfree(p616););
printStats();
PRINT_POINTER(scalloc(160,213););
printStats();
void* p1133 = last_address;
DEBUG_PRINT(sfree(p1103););
printStats();
DEBUG_PRINT(sfree(p455););
printStats();
PRINT_POINTER(smalloc(235););
printStats();
void* p1134 = last_address;
PRINT_POINTER(scalloc(99,69););
printStats();
void* p1135 = last_address;
}
