#include "aux_macro.h"
#include "../malloc_2.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(scalloc(64,11););
printStats();
void* p0 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p1 = last_address;
PRINT_POINTER(scalloc(26,137););
printStats();
void* p2 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p3 = last_address;
PRINT_POINTER(scalloc(7,11););
printStats();
void* p4 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p5 = last_address;
PRINT_POINTER(scalloc(92,138););
printStats();
void* p6 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p7 = last_address;
PRINT_POINTER(srealloc(p6,215););
printStats();
void* p8 = last_address;
PRINT_POINTER(scalloc(203,139););
printStats();
void* p9 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p10 = last_address;
PRINT_POINTER(srealloc(p4,168););
printStats();
void* p11 = last_address;
DEBUG_PRINT(sfree(p2););
printStats();
PRINT_POINTER(srealloc(p10,87););
printStats();
void* p12 = last_address;
PRINT_POINTER(scalloc(17,98););
printStats();
void* p13 = last_address;
PRINT_POINTER(srealloc(p3,75););
printStats();
void* p14 = last_address;
PRINT_POINTER(srealloc(p5,31););
printStats();
void* p15 = last_address;
PRINT_POINTER(srealloc(p12,49););
printStats();
void* p16 = last_address;
DEBUG_PRINT(sfree(p9););
printStats();
DEBUG_PRINT(sfree(p15););
printStats();
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(smalloc(21););
printStats();
void* p17 = last_address;
PRINT_POINTER(scalloc(170,68););
printStats();
void* p18 = last_address;
PRINT_POINTER(scalloc(42,243););
printStats();
void* p19 = last_address;
DEBUG_PRINT(sfree(p13););
printStats();
PRINT_POINTER(srealloc(p16,201););
printStats();
void* p20 = last_address;
PRINT_POINTER(scalloc(71,168););
printStats();
void* p21 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(smalloc(78););
printStats();
void* p22 = last_address;
PRINT_POINTER(scalloc(59,58););
printStats();
void* p23 = last_address;
PRINT_POINTER(srealloc(p7,55););
printStats();
void* p24 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(smalloc(29););
printStats();
void* p25 = last_address;
PRINT_POINTER(srealloc(p24,12););
printStats();
void* p26 = last_address;
PRINT_POINTER(scalloc(130,174););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(srealloc(p18,88););
printStats();
void* p28 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(srealloc(p27,44););
printStats();
void* p29 = last_address;
DEBUG_PRINT(sfree(p19););
printStats();
PRINT_POINTER(srealloc(p26,157););
printStats();
void* p30 = last_address;
PRINT_POINTER(scalloc(67,208););
printStats();
void* p31 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
PRINT_POINTER(scalloc(12,104););
printStats();
void* p32 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p33 = last_address;
DEBUG_PRINT(sfree(p11););
printStats();
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(scalloc(231,146););
printStats();
void* p34 = last_address;
PRINT_POINTER(srealloc(p20,126););
printStats();
void* p35 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p36 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p37 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p38 = last_address;
PRINT_POINTER(srealloc(p32,187););
printStats();
void* p39 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p39,64););
printStats();
void* p41 = last_address;
PRINT_POINTER(srealloc(p23,172););
printStats();
void* p42 = last_address;
DEBUG_PRINT(sfree(p30););
printStats();
PRINT_POINTER(scalloc(185,157););
printStats();
void* p43 = last_address;
PRINT_POINTER(scalloc(114,130););
printStats();
void* p44 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
DEBUG_PRINT(sfree(p35););
printStats();
PRINT_POINTER(scalloc(80,144););
printStats();
void* p45 = last_address;
PRINT_POINTER(scalloc(32,129););
printStats();
void* p46 = last_address;
PRINT_POINTER(srealloc(p17,237););
printStats();
void* p47 = last_address;
PRINT_POINTER(srealloc(p43,185););
printStats();
void* p48 = last_address;
PRINT_POINTER(srealloc(p44,12););
printStats();
void* p49 = last_address;
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(smalloc(137););
printStats();
void* p50 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
PRINT_POINTER(smalloc(185););
printStats();
void* p51 = last_address;
PRINT_POINTER(srealloc(p48,191););
printStats();
void* p52 = last_address;
PRINT_POINTER(scalloc(105,188););
printStats();
void* p53 = last_address;
PRINT_POINTER(scalloc(67,90););
printStats();
void* p54 = last_address;
PRINT_POINTER(srealloc(p54,124););
printStats();
void* p55 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
PRINT_POINTER(smalloc(194););
printStats();
void* p56 = last_address;
PRINT_POINTER(srealloc(p55,35););
printStats();
void* p57 = last_address;
PRINT_POINTER(srealloc(p37,131););
printStats();
void* p58 = last_address;
PRINT_POINTER(srealloc(p36,240););
printStats();
void* p59 = last_address;
PRINT_POINTER(scalloc(130,60););
printStats();
void* p60 = last_address;
DEBUG_PRINT(sfree(p42););
printStats();
PRINT_POINTER(smalloc(80););
printStats();
void* p61 = last_address;
PRINT_POINTER(smalloc(145););
printStats();
void* p62 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p63 = last_address;
PRINT_POINTER(scalloc(8,65););
printStats();
void* p64 = last_address;
PRINT_POINTER(scalloc(147,84););
printStats();
void* p65 = last_address;
PRINT_POINTER(scalloc(5,156););
printStats();
void* p66 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p67 = last_address;
PRINT_POINTER(srealloc(p46,83););
printStats();
void* p68 = last_address;
DEBUG_PRINT(sfree(p40););
printStats();
DEBUG_PRINT(sfree(p57););
printStats();
PRINT_POINTER(srealloc(p68,42););
printStats();
void* p69 = last_address;
PRINT_POINTER(srealloc(p59,25););
printStats();
void* p70 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p71 = last_address;
PRINT_POINTER(scalloc(44,177););
printStats();
void* p72 = last_address;
PRINT_POINTER(srealloc(p60,50););
printStats();
void* p73 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p74 = last_address;
PRINT_POINTER(scalloc(177,155););
printStats();
void* p75 = last_address;
DEBUG_PRINT(sfree(p47););
printStats();
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(srealloc(p63,197););
printStats();
void* p76 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p77 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p78 = last_address;
PRINT_POINTER(scalloc(230,83););
printStats();
void* p79 = last_address;
PRINT_POINTER(srealloc(p45,14););
printStats();
void* p80 = last_address;
PRINT_POINTER(srealloc(p73,127););
printStats();
void* p81 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p82 = last_address;
PRINT_POINTER(scalloc(232,32););
printStats();
void* p83 = last_address;
PRINT_POINTER(scalloc(240,170););
printStats();
void* p84 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p85 = last_address;
PRINT_POINTER(srealloc(p83,25););
printStats();
void* p86 = last_address;
PRINT_POINTER(scalloc(37,86););
printStats();
void* p87 = last_address;
PRINT_POINTER(srealloc(p80,146););
printStats();
void* p88 = last_address;
PRINT_POINTER(smalloc(183););
printStats();
void* p89 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p90 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p91 = last_address;
DEBUG_PRINT(sfree(p84););
printStats();
PRINT_POINTER(scalloc(242,30););
printStats();
void* p92 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p93 = last_address;
PRINT_POINTER(srealloc(p58,115););
printStats();
void* p94 = last_address;
DEBUG_PRINT(sfree(p81););
printStats();
DEBUG_PRINT(sfree(p49););
printStats();
PRINT_POINTER(scalloc(134,26););
printStats();
void* p95 = last_address;
DEBUG_PRINT(sfree(p72););
printStats();
PRINT_POINTER(scalloc(151,68););
printStats();
void* p96 = last_address;
PRINT_POINTER(scalloc(46,42););
printStats();
void* p97 = last_address;
PRINT_POINTER(scalloc(69,228););
printStats();
void* p98 = last_address;
PRINT_POINTER(srealloc(p90,27););
printStats();
void* p99 = last_address;
PRINT_POINTER(srealloc(p74,12););
printStats();
void* p100 = last_address;
PRINT_POINTER(scalloc(132,158););
printStats();
void* p101 = last_address;
PRINT_POINTER(srealloc(p99,56););
printStats();
void* p102 = last_address;
DEBUG_PRINT(sfree(p64););
printStats();
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(scalloc(167,159););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p70,149););
printStats();
void* p104 = last_address;
PRINT_POINTER(srealloc(p52,222););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p69,132););
printStats();
void* p106 = last_address;
PRINT_POINTER(scalloc(36,199););
printStats();
void* p107 = last_address;
PRINT_POINTER(srealloc(p104,4););
printStats();
void* p108 = last_address;
PRINT_POINTER(smalloc(106););
printStats();
void* p109 = last_address;
PRINT_POINTER(scalloc(13,64););
printStats();
void* p110 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(srealloc(p107,97););
printStats();
void* p111 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p112 = last_address;
PRINT_POINTER(srealloc(p79,93););
printStats();
void* p113 = last_address;
PRINT_POINTER(scalloc(201,124););
printStats();
void* p114 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
PRINT_POINTER(srealloc(p114,37););
printStats();
void* p115 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p116 = last_address;
PRINT_POINTER(srealloc(p106,198););
printStats();
void* p117 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p118 = last_address;
DEBUG_PRINT(sfree(p76););
printStats();
PRINT_POINTER(scalloc(198,35););
printStats();
void* p119 = last_address;
PRINT_POINTER(scalloc(162,81););
printStats();
void* p120 = last_address;
PRINT_POINTER(scalloc(180,235););
printStats();
void* p121 = last_address;
PRINT_POINTER(srealloc(p105,58););
printStats();
void* p122 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p123 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p124 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p125 = last_address;
PRINT_POINTER(scalloc(75,204););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(105,24););
printStats();
void* p127 = last_address;
PRINT_POINTER(scalloc(76,57););
printStats();
void* p128 = last_address;
PRINT_POINTER(srealloc(p65,240););
printStats();
void* p129 = last_address;
PRINT_POINTER(srealloc(p93,119););
printStats();
void* p130 = last_address;
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(srealloc(p78,224););
printStats();
void* p131 = last_address;
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(smalloc(28););
printStats();
void* p132 = last_address;
PRINT_POINTER(srealloc(p33,75););
printStats();
void* p133 = last_address;
DEBUG_PRINT(sfree(p53););
printStats();
PRINT_POINTER(smalloc(120););
printStats();
void* p134 = last_address;
DEBUG_PRINT(sfree(p116););
printStats();
PRINT_POINTER(scalloc(37,153););
printStats();
void* p135 = last_address;
PRINT_POINTER(scalloc(249,92););
printStats();
void* p136 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p137 = last_address;
PRINT_POINTER(scalloc(23,212););
printStats();
void* p138 = last_address;
PRINT_POINTER(srealloc(p137,12););
printStats();
void* p139 = last_address;
PRINT_POINTER(scalloc(189,62););
printStats();
void* p140 = last_address;
PRINT_POINTER(srealloc(p110,167););
printStats();
void* p141 = last_address;
PRINT_POINTER(scalloc(18,214););
printStats();
void* p142 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p143 = last_address;
PRINT_POINTER(srealloc(p103,199););
printStats();
void* p144 = last_address;
PRINT_POINTER(scalloc(67,14););
printStats();
void* p145 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p146 = last_address;
PRINT_POINTER(scalloc(54,65););
printStats();
void* p147 = last_address;
DEBUG_PRINT(sfree(p92););
printStats();
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(smalloc(174););
printStats();
void* p148 = last_address;
PRINT_POINTER(scalloc(96,58););
printStats();
void* p149 = last_address;
PRINT_POINTER(srealloc(p129,239););
printStats();
void* p150 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p151 = last_address;
DEBUG_PRINT(sfree(p115););
printStats();
DEBUG_PRINT(sfree(p86););
printStats();
PRINT_POINTER(scalloc(61,72););
printStats();
void* p152 = last_address;
PRINT_POINTER(scalloc(192,77););
printStats();
void* p153 = last_address;
DEBUG_PRINT(sfree(p91););
printStats();
DEBUG_PRINT(sfree(p66););
printStats();
PRINT_POINTER(smalloc(192););
printStats();
void* p154 = last_address;
PRINT_POINTER(scalloc(163,208););
printStats();
void* p155 = last_address;
PRINT_POINTER(smalloc(223););
printStats();
void* p156 = last_address;
DEBUG_PRINT(sfree(p145););
printStats();
PRINT_POINTER(smalloc(119););
printStats();
void* p157 = last_address;
PRINT_POINTER(srealloc(p133,118););
printStats();
void* p158 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(smalloc(114););
printStats();
void* p159 = last_address;
DEBUG_PRINT(sfree(p95););
printStats();
PRINT_POINTER(scalloc(153,22););
printStats();
void* p160 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p161 = last_address;
DEBUG_PRINT(sfree(p160););
printStats();
PRINT_POINTER(scalloc(129,152););
printStats();
void* p162 = last_address;
PRINT_POINTER(scalloc(236,216););
printStats();
void* p163 = last_address;
PRINT_POINTER(scalloc(86,115););
printStats();
void* p164 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p165 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p166 = last_address;
PRINT_POINTER(scalloc(207,158););
printStats();
void* p167 = last_address;
DEBUG_PRINT(sfree(p149););
printStats();
DEBUG_PRINT(sfree(p141););
printStats();
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(srealloc(p111,123););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(157,148););
printStats();
void* p169 = last_address;
PRINT_POINTER(scalloc(170,63););
printStats();
void* p170 = last_address;
PRINT_POINTER(srealloc(p162,10););
printStats();
void* p171 = last_address;
PRINT_POINTER(scalloc(109,50););
printStats();
void* p172 = last_address;
PRINT_POINTER(srealloc(p136,174););
printStats();
void* p173 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p174 = last_address;
PRINT_POINTER(srealloc(p171,5););
printStats();
void* p175 = last_address;
PRINT_POINTER(scalloc(193,236););
printStats();
void* p176 = last_address;
PRINT_POINTER(srealloc(p175,59););
printStats();
void* p177 = last_address;
PRINT_POINTER(scalloc(33,85););
printStats();
void* p178 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p179 = last_address;
DEBUG_PRINT(sfree(p120););
printStats();
DEBUG_PRINT(sfree(p135););
printStats();
PRINT_POINTER(smalloc(196););
printStats();
void* p180 = last_address;
DEBUG_PRINT(sfree(p163););
printStats();
DEBUG_PRINT(sfree(p118););
printStats();
PRINT_POINTER(scalloc(240,207););
printStats();
void* p181 = last_address;
PRINT_POINTER(scalloc(108,25););
printStats();
void* p182 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p183 = last_address;
PRINT_POINTER(scalloc(171,225););
printStats();
void* p184 = last_address;
PRINT_POINTER(srealloc(p113,40););
printStats();
void* p185 = last_address;
PRINT_POINTER(srealloc(p158,236););
printStats();
void* p186 = last_address;
PRINT_POINTER(scalloc(111,231););
printStats();
void* p187 = last_address;
PRINT_POINTER(srealloc(p146,220););
printStats();
void* p188 = last_address;
PRINT_POINTER(scalloc(130,219););
printStats();
void* p189 = last_address;
DEBUG_PRINT(sfree(p62););
printStats();
PRINT_POINTER(scalloc(111,51););
printStats();
void* p190 = last_address;
PRINT_POINTER(srealloc(p188,179););
printStats();
void* p191 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p192 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p193 = last_address;
PRINT_POINTER(srealloc(p89,32););
printStats();
void* p194 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p195 = last_address;
PRINT_POINTER(scalloc(35,63););
printStats();
void* p196 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p197 = last_address;
DEBUG_PRINT(sfree(p156););
printStats();
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(scalloc(11,183););
printStats();
void* p198 = last_address;
PRINT_POINTER(srealloc(p77,110););
printStats();
void* p199 = last_address;
DEBUG_PRINT(sfree(p161););
printStats();
PRINT_POINTER(scalloc(37,163););
printStats();
void* p200 = last_address;
DEBUG_PRINT(sfree(p152););
printStats();
PRINT_POINTER(smalloc(172););
printStats();
void* p201 = last_address;
PRINT_POINTER(srealloc(p87,220););
printStats();
void* p202 = last_address;
PRINT_POINTER(srealloc(p178,225););
printStats();
void* p203 = last_address;
PRINT_POINTER(scalloc(199,137););
printStats();
void* p204 = last_address;
PRINT_POINTER(srealloc(p144,61););
printStats();
void* p205 = last_address;
PRINT_POINTER(scalloc(204,27););
printStats();
void* p206 = last_address;
PRINT_POINTER(scalloc(228,150););
printStats();
void* p207 = last_address;
PRINT_POINTER(srealloc(p147,231););
printStats();
void* p208 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(srealloc(p182,98););
printStats();
void* p209 = last_address;
DEBUG_PRINT(sfree(p200););
printStats();
DEBUG_PRINT(sfree(p142););
printStats();
DEBUG_PRINT(sfree(p209););
printStats();
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(srealloc(p179,226););
printStats();
void* p210 = last_address;
DEBUG_PRINT(sfree(p108););
printStats();
PRINT_POINTER(srealloc(p61,61););
printStats();
void* p211 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p212 = last_address;
PRINT_POINTER(srealloc(p121,148););
printStats();
void* p213 = last_address;
PRINT_POINTER(srealloc(p109,223););
printStats();
void* p214 = last_address;
PRINT_POINTER(srealloc(p148,188););
printStats();
void* p215 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
PRINT_POINTER(srealloc(p197,38););
printStats();
void* p216 = last_address;
DEBUG_PRINT(sfree(p138););
printStats();
DEBUG_PRINT(sfree(p164););
printStats();
DEBUG_PRINT(sfree(p122););
printStats();
PRINT_POINTER(srealloc(p165,66););
printStats();
void* p217 = last_address;
PRINT_POINTER(srealloc(p140,115););
printStats();
void* p218 = last_address;
PRINT_POINTER(scalloc(233,111););
printStats();
void* p219 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p220 = last_address;
PRINT_POINTER(srealloc(p205,38););
printStats();
void* p221 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p222 = last_address;
DEBUG_PRINT(sfree(p131););
printStats();
PRINT_POINTER(srealloc(p88,155););
printStats();
void* p223 = last_address;
PRINT_POINTER(srealloc(p132,55););
printStats();
void* p224 = last_address;
DEBUG_PRINT(sfree(p221););
printStats();
DEBUG_PRINT(sfree(p204););
printStats();
PRINT_POINTER(smalloc(216););
printStats();
void* p225 = last_address;
PRINT_POINTER(srealloc(p191,106););
printStats();
void* p226 = last_address;
DEBUG_PRINT(sfree(p189););
printStats();
PRINT_POINTER(smalloc(233););
printStats();
void* p227 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(srealloc(p185,201););
printStats();
void* p228 = last_address;
DEBUG_PRINT(sfree(p194););
printStats();
PRINT_POINTER(scalloc(21,188););
printStats();
void* p229 = last_address;
PRINT_POINTER(srealloc(p96,105););
printStats();
void* p230 = last_address;
PRINT_POINTER(scalloc(164,171););
printStats();
void* p231 = last_address;
PRINT_POINTER(srealloc(p192,235););
printStats();
void* p232 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p233 = last_address;
DEBUG_PRINT(sfree(p167););
printStats();
PRINT_POINTER(srealloc(p201,213););
printStats();
void* p234 = last_address;
PRINT_POINTER(srealloc(p184,192););
printStats();
void* p235 = last_address;
PRINT_POINTER(scalloc(202,142););
printStats();
void* p236 = last_address;
DEBUG_PRINT(sfree(p198););
printStats();
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(smalloc(135););
printStats();
void* p237 = last_address;
DEBUG_PRINT(sfree(p217););
printStats();
PRINT_POINTER(srealloc(p226,177););
printStats();
void* p238 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p211,94););
printStats();
void* p240 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p241 = last_address;
PRINT_POINTER(srealloc(p180,160););
printStats();
void* p242 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(smalloc(236););
printStats();
void* p244 = last_address;
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(smalloc(153););
printStats();
void* p245 = last_address;
DEBUG_PRINT(sfree(p242););
printStats();
PRINT_POINTER(smalloc(69););
printStats();
void* p246 = last_address;
DEBUG_PRINT(sfree(p210););
printStats();
DEBUG_PRINT(sfree(p215););
printStats();
PRINT_POINTER(smalloc(186););
printStats();
void* p247 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p248 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p249 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p250 = last_address;
DEBUG_PRINT(sfree(p130););
printStats();
PRINT_POINTER(smalloc(120););
printStats();
void* p251 = last_address;
DEBUG_PRINT(sfree(p213););
printStats();
PRINT_POINTER(scalloc(232,188););
printStats();
void* p252 = last_address;
PRINT_POINTER(srealloc(p248,182););
printStats();
void* p253 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(srealloc(p151,218););
printStats();
void* p254 = last_address;
PRINT_POINTER(scalloc(54,95););
printStats();
void* p255 = last_address;
DEBUG_PRINT(sfree(p238););
printStats();
PRINT_POINTER(smalloc(72););
printStats();
void* p256 = last_address;
PRINT_POINTER(scalloc(171,110););
printStats();
void* p257 = last_address;
PRINT_POINTER(srealloc(p231,193););
printStats();
void* p258 = last_address;
DEBUG_PRINT(sfree(p239););
printStats();
PRINT_POINTER(smalloc(188););
printStats();
void* p259 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p260 = last_address;
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(srealloc(p117,130););
printStats();
void* p261 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p262 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p263 = last_address;
PRINT_POINTER(srealloc(p254,196););
printStats();
void* p264 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p265 = last_address;
PRINT_POINTER(scalloc(222,26););
printStats();
void* p266 = last_address;
PRINT_POINTER(srealloc(p203,101););
printStats();
void* p267 = last_address;
PRINT_POINTER(scalloc(139,15););
printStats();
void* p268 = last_address;
PRINT_POINTER(srealloc(p216,59););
printStats();
void* p269 = last_address;
DEBUG_PRINT(sfree(p139););
printStats();
DEBUG_PRINT(sfree(p154););
printStats();
PRINT_POINTER(srealloc(p119,73););
printStats();
void* p270 = last_address;
DEBUG_PRINT(sfree(p219););
printStats();
PRINT_POINTER(srealloc(p244,26););
printStats();
void* p271 = last_address;
DEBUG_PRINT(sfree(p230););
printStats();
PRINT_POINTER(smalloc(11););
printStats();
void* p272 = last_address;
PRINT_POINTER(srealloc(p265,202););
printStats();
void* p273 = last_address;
PRINT_POINTER(srealloc(p225,174););
printStats();
void* p274 = last_address;
PRINT_POINTER(scalloc(12,165););
printStats();
void* p275 = last_address;
PRINT_POINTER(scalloc(83,179););
printStats();
void* p276 = last_address;
PRINT_POINTER(scalloc(52,52););
printStats();
void* p277 = last_address;
DEBUG_PRINT(sfree(p245););
printStats();
PRINT_POINTER(scalloc(63,120););
printStats();
void* p278 = last_address;
PRINT_POINTER(scalloc(120,1););
printStats();
void* p279 = last_address;
DEBUG_PRINT(sfree(p228););
printStats();
PRINT_POINTER(smalloc(132););
printStats();
void* p280 = last_address;
PRINT_POINTER(srealloc(p168,0););
printStats();
void* p281 = last_address;
PRINT_POINTER(srealloc(p271,62););
printStats();
void* p282 = last_address;
PRINT_POINTER(scalloc(234,40););
printStats();
void* p283 = last_address;
DEBUG_PRINT(sfree(p268););
printStats();
PRINT_POINTER(srealloc(p183,179););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p236,34););
printStats();
void* p285 = last_address;
DEBUG_PRINT(sfree(p246););
printStats();
PRINT_POINTER(srealloc(p176,97););
printStats();
void* p286 = last_address;
DEBUG_PRINT(sfree(p233););
printStats();
PRINT_POINTER(srealloc(p193,168););
printStats();
void* p287 = last_address;
PRINT_POINTER(srealloc(p126,222););
printStats();
void* p288 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p289 = last_address;
PRINT_POINTER(scalloc(42,179););
printStats();
void* p290 = last_address;
DEBUG_PRINT(sfree(p260););
printStats();
DEBUG_PRINT(sfree(p235););
printStats();
PRINT_POINTER(scalloc(11,67););
printStats();
void* p291 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p292 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(srealloc(p289,217););
printStats();
void* p293 = last_address;
DEBUG_PRINT(sfree(p286););
printStats();
PRINT_POINTER(srealloc(p195,84););
printStats();
void* p294 = last_address;
PRINT_POINTER(scalloc(131,29););
printStats();
void* p295 = last_address;
PRINT_POINTER(srealloc(p255,137););
printStats();
void* p296 = last_address;
DEBUG_PRINT(sfree(p190););
printStats();
DEBUG_PRINT(sfree(p264););
printStats();
PRINT_POINTER(scalloc(25,0););
printStats();
void* p297 = last_address;
DEBUG_PRINT(sfree(p287););
printStats();
PRINT_POINTER(scalloc(77,26););
printStats();
void* p298 = last_address;
PRINT_POINTER(srealloc(p296,85););
printStats();
void* p299 = last_address;
DEBUG_PRINT(sfree(p267););
printStats();
PRINT_POINTER(smalloc(78););
printStats();
void* p300 = last_address;
DEBUG_PRINT(sfree(p128););
printStats();
PRINT_POINTER(smalloc(5););
printStats();
void* p301 = last_address;
PRINT_POINTER(smalloc(62););
printStats();
void* p302 = last_address;
DEBUG_PRINT(sfree(p293););
printStats();
PRINT_POINTER(scalloc(107,32););
printStats();
void* p303 = last_address;
PRINT_POINTER(srealloc(p294,222););
printStats();
void* p304 = last_address;
PRINT_POINTER(scalloc(117,193););
printStats();
void* p305 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p306 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p307 = last_address;
DEBUG_PRINT(sfree(p276););
printStats();
PRINT_POINTER(smalloc(123););
printStats();
void* p308 = last_address;
PRINT_POINTER(srealloc(p290,6););
printStats();
void* p309 = last_address;
PRINT_POINTER(scalloc(249,154););
printStats();
void* p310 = last_address;
DEBUG_PRINT(sfree(p112););
printStats();
PRINT_POINTER(scalloc(166,104););
printStats();
void* p311 = last_address;
PRINT_POINTER(srealloc(p202,197););
printStats();
void* p312 = last_address;
PRINT_POINTER(scalloc(143,53););
printStats();
void* p313 = last_address;
PRINT_POINTER(srealloc(p252,185););
printStats();
void* p314 = last_address;
PRINT_POINTER(srealloc(p241,54););
printStats();
void* p315 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p316 = last_address;
PRINT_POINTER(srealloc(p278,132););
printStats();
void* p317 = last_address;
DEBUG_PRINT(sfree(p249););
printStats();
PRINT_POINTER(smalloc(109););
printStats();
void* p318 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p319 = last_address;
PRINT_POINTER(scalloc(109,195););
printStats();
void* p320 = last_address;
PRINT_POINTER(srealloc(p240,203););
printStats();
void* p321 = last_address;
PRINT_POINTER(scalloc(138,159););
printStats();
void* p322 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p323 = last_address;
DEBUG_PRINT(sfree(p270););
printStats();
PRINT_POINTER(scalloc(182,147););
printStats();
void* p324 = last_address;
PRINT_POINTER(srealloc(p157,56););
printStats();
void* p325 = last_address;
PRINT_POINTER(scalloc(189,66););
printStats();
void* p326 = last_address;
PRINT_POINTER(srealloc(p326,201););
printStats();
void* p327 = last_address;
PRINT_POINTER(scalloc(247,80););
printStats();
void* p328 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p329 = last_address;
PRINT_POINTER(srealloc(p328,127););
printStats();
void* p330 = last_address;
PRINT_POINTER(srealloc(p258,243););
printStats();
void* p331 = last_address;
DEBUG_PRINT(sfree(p295););
printStats();
PRINT_POINTER(smalloc(163););
printStats();
void* p332 = last_address;
PRINT_POINTER(scalloc(45,194););
printStats();
void* p333 = last_address;
DEBUG_PRINT(sfree(p330););
printStats();
PRINT_POINTER(srealloc(p75,62););
printStats();
void* p334 = last_address;
DEBUG_PRINT(sfree(p224););
printStats();
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(smalloc(192););
printStats();
void* p335 = last_address;
DEBUG_PRINT(sfree(p155););
printStats();
DEBUG_PRINT(sfree(p314););
printStats();
DEBUG_PRINT(sfree(p331););
printStats();
DEBUG_PRINT(sfree(p332););
printStats();
PRINT_POINTER(scalloc(203,175););
printStats();
void* p336 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p337 = last_address;
DEBUG_PRINT(sfree(p334););
printStats();
DEBUG_PRINT(sfree(p313););
printStats();
PRINT_POINTER(smalloc(224););
printStats();
void* p338 = last_address;
PRINT_POINTER(srealloc(p321,143););
printStats();
void* p339 = last_address;
PRINT_POINTER(scalloc(149,8););
printStats();
void* p340 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p341 = last_address;
PRINT_POINTER(srealloc(p282,233););
printStats();
void* p342 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p343 = last_address;
DEBUG_PRINT(sfree(p311););
printStats();
DEBUG_PRINT(sfree(p243););
printStats();
PRINT_POINTER(smalloc(0););
printStats();
void* p344 = last_address;
DEBUG_PRINT(sfree(p232););
printStats();
DEBUG_PRINT(sfree(p283););
printStats();
DEBUG_PRINT(sfree(p341););
printStats();
PRINT_POINTER(scalloc(216,77););
printStats();
void* p345 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p346 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p347 = last_address;
PRINT_POINTER(srealloc(p169,159););
printStats();
void* p348 = last_address;
DEBUG_PRINT(sfree(p208););
printStats();
PRINT_POINTER(srealloc(p227,189););
printStats();
void* p349 = last_address;
PRINT_POINTER(srealloc(p300,21););
printStats();
void* p350 = last_address;
PRINT_POINTER(scalloc(100,189););
printStats();
void* p351 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p352 = last_address;
PRINT_POINTER(srealloc(p337,160););
printStats();
void* p353 = last_address;
PRINT_POINTER(srealloc(p329,41););
printStats();
void* p354 = last_address;
PRINT_POINTER(srealloc(p322,90););
printStats();
void* p355 = last_address;
PRINT_POINTER(srealloc(p298,76););
printStats();
void* p356 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p357 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p358 = last_address;
PRINT_POINTER(scalloc(112,82););
printStats();
void* p359 = last_address;
PRINT_POINTER(scalloc(32,209););
printStats();
void* p360 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
DEBUG_PRINT(sfree(p234););
printStats();
PRINT_POINTER(smalloc(180););
printStats();
void* p361 = last_address;
PRINT_POINTER(srealloc(p143,110););
printStats();
void* p362 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p363 = last_address;
PRINT_POINTER(srealloc(p333,102););
printStats();
void* p364 = last_address;
PRINT_POINTER(srealloc(p281,172););
printStats();
void* p365 = last_address;
PRINT_POINTER(srealloc(p302,223););
printStats();
void* p366 = last_address;
PRINT_POINTER(srealloc(p297,22););
printStats();
void* p367 = last_address;
DEBUG_PRINT(sfree(p315););
printStats();
DEBUG_PRINT(sfree(p285););
printStats();
PRINT_POINTER(srealloc(p363,238););
printStats();
void* p368 = last_address;
PRINT_POINTER(scalloc(196,48););
printStats();
void* p369 = last_address;
DEBUG_PRINT(sfree(p153););
printStats();
DEBUG_PRINT(sfree(p344););
printStats();
PRINT_POINTER(srealloc(p361,221););
printStats();
void* p370 = last_address;
DEBUG_PRINT(sfree(p259););
printStats();
PRINT_POINTER(scalloc(81,50););
printStats();
void* p371 = last_address;
PRINT_POINTER(srealloc(p199,182););
printStats();
void* p372 = last_address;
DEBUG_PRINT(sfree(p124););
printStats();
DEBUG_PRINT(sfree(p349););
printStats();
DEBUG_PRINT(sfree(p253););
printStats();
PRINT_POINTER(scalloc(74,152););
printStats();
void* p373 = last_address;
DEBUG_PRINT(sfree(p336););
printStats();
PRINT_POINTER(scalloc(74,26););
printStats();
void* p374 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p375 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
PRINT_POINTER(scalloc(234,83););
printStats();
void* p376 = last_address;
PRINT_POINTER(srealloc(p345,34););
printStats();
void* p377 = last_address;
PRINT_POINTER(srealloc(p327,223););
printStats();
void* p378 = last_address;
PRINT_POINTER(scalloc(45,191););
printStats();
void* p379 = last_address;
PRINT_POINTER(srealloc(p376,160););
printStats();
void* p380 = last_address;
PRINT_POINTER(srealloc(p365,222););
printStats();
void* p381 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p382 = last_address;
DEBUG_PRINT(sfree(p379););
printStats();
PRINT_POINTER(scalloc(194,84););
printStats();
void* p383 = last_address;
DEBUG_PRINT(sfree(p372););
printStats();
PRINT_POINTER(scalloc(147,223););
printStats();
void* p384 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p385 = last_address;
PRINT_POINTER(srealloc(p373,71););
printStats();
void* p386 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p387 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p388 = last_address;
PRINT_POINTER(srealloc(p187,74););
printStats();
void* p389 = last_address;
PRINT_POINTER(scalloc(12,28););
printStats();
void* p390 = last_address;
DEBUG_PRINT(sfree(p257););
printStats();
PRINT_POINTER(srealloc(p371,149););
printStats();
void* p391 = last_address;
PRINT_POINTER(scalloc(58,73););
printStats();
void* p392 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p393 = last_address;
PRINT_POINTER(scalloc(118,138););
printStats();
void* p394 = last_address;
PRINT_POINTER(scalloc(224,60););
printStats();
void* p395 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p396 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p397 = last_address;
PRINT_POINTER(scalloc(54,211););
printStats();
void* p398 = last_address;
PRINT_POINTER(srealloc(p312,75););
printStats();
void* p399 = last_address;
PRINT_POINTER(srealloc(p335,144););
printStats();
void* p400 = last_address;
PRINT_POINTER(srealloc(p348,155););
printStats();
void* p401 = last_address;
PRINT_POINTER(scalloc(166,123););
printStats();
void* p402 = last_address;
PRINT_POINTER(srealloc(p256,152););
printStats();
void* p403 = last_address;
DEBUG_PRINT(sfree(p356););
printStats();
DEBUG_PRINT(sfree(p338););
printStats();
PRINT_POINTER(scalloc(113,226););
printStats();
void* p404 = last_address;
PRINT_POINTER(srealloc(p388,183););
printStats();
void* p405 = last_address;
PRINT_POINTER(scalloc(94,226););
printStats();
void* p406 = last_address;
PRINT_POINTER(scalloc(83,240););
printStats();
void* p407 = last_address;
PRINT_POINTER(srealloc(p359,93););
printStats();
void* p408 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p409 = last_address;
PRINT_POINTER(scalloc(132,180););
printStats();
void* p410 = last_address;
PRINT_POINTER(srealloc(p352,213););
printStats();
void* p411 = last_address;
DEBUG_PRINT(sfree(p172););
printStats();
DEBUG_PRINT(sfree(p398););
printStats();
PRINT_POINTER(scalloc(10,149););
printStats();
void* p412 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p413 = last_address;
PRINT_POINTER(smalloc(221););
printStats();
void* p414 = last_address;
DEBUG_PRINT(sfree(p310););
printStats();
DEBUG_PRINT(sfree(p383););
printStats();
PRINT_POINTER(scalloc(1,8););
printStats();
void* p415 = last_address;
PRINT_POINTER(smalloc(161););
printStats();
void* p416 = last_address;
PRINT_POINTER(scalloc(71,113););
printStats();
void* p417 = last_address;
DEBUG_PRINT(sfree(p403););
printStats();
PRINT_POINTER(smalloc(44););
printStats();
void* p418 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p419 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p420 = last_address;
DEBUG_PRINT(sfree(p407););
printStats();
PRINT_POINTER(srealloc(p237,166););
printStats();
void* p421 = last_address;
DEBUG_PRINT(sfree(p406););
printStats();
PRINT_POINTER(smalloc(83););
printStats();
void* p422 = last_address;
PRINT_POINTER(scalloc(63,238););
printStats();
void* p423 = last_address;
DEBUG_PRINT(sfree(p404););
printStats();
DEBUG_PRINT(sfree(p421););
printStats();
PRINT_POINTER(scalloc(167,208););
printStats();
void* p424 = last_address;
PRINT_POINTER(srealloc(p382,129););
printStats();
void* p425 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
PRINT_POINTER(scalloc(151,237););
printStats();
void* p426 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p427 = last_address;
DEBUG_PRINT(sfree(p317););
printStats();
PRINT_POINTER(scalloc(72,239););
printStats();
void* p428 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p429 = last_address;
DEBUG_PRINT(sfree(p377););
printStats();
PRINT_POINTER(smalloc(127););
printStats();
void* p430 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p431 = last_address;
DEBUG_PRINT(sfree(p307););
printStats();
PRINT_POINTER(smalloc(83););
printStats();
void* p432 = last_address;
PRINT_POINTER(srealloc(p207,4););
printStats();
void* p433 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p434 = last_address;
PRINT_POINTER(srealloc(p418,141););
printStats();
void* p435 = last_address;
PRINT_POINTER(srealloc(p292,242););
printStats();
void* p436 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p437 = last_address;
PRINT_POINTER(smalloc(0););
printStats();
void* p438 = last_address;
DEBUG_PRINT(sfree(p438););
printStats();
PRINT_POINTER(scalloc(231,231););
printStats();
void* p439 = last_address;
PRINT_POINTER(srealloc(p419,185););
printStats();
void* p440 = last_address;
DEBUG_PRINT(sfree(p269););
printStats();
PRINT_POINTER(srealloc(p386,81););
printStats();
void* p441 = last_address;
PRINT_POINTER(scalloc(199,162););
printStats();
void* p442 = last_address;
PRINT_POINTER(srealloc(p366,34););
printStats();
void* p443 = last_address;
DEBUG_PRINT(sfree(p426););
printStats();
DEBUG_PRINT(sfree(p435););
printStats();
DEBUG_PRINT(sfree(p420););
printStats();
PRINT_POINTER(scalloc(180,110););
printStats();
void* p444 = last_address;
DEBUG_PRINT(sfree(p436););
printStats();
PRINT_POINTER(srealloc(p437,249););
printStats();
void* p445 = last_address;
PRINT_POINTER(srealloc(p303,223););
printStats();
void* p446 = last_address;
PRINT_POINTER(scalloc(103,29););
printStats();
void* p447 = last_address;
PRINT_POINTER(srealloc(p417,87););
printStats();
void* p448 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p449 = last_address;
PRINT_POINTER(scalloc(234,134););
printStats();
void* p450 = last_address;
PRINT_POINTER(smalloc(179););
printStats();
void* p451 = last_address;
PRINT_POINTER(srealloc(p346,135););
printStats();
void* p452 = last_address;
PRINT_POINTER(srealloc(p220,35););
printStats();
void* p453 = last_address;
DEBUG_PRINT(sfree(p177););
printStats();
PRINT_POINTER(srealloc(p222,115););
printStats();
void* p454 = last_address;
DEBUG_PRINT(sfree(p353););
printStats();
DEBUG_PRINT(sfree(p71););
printStats();
PRINT_POINTER(scalloc(172,154););
printStats();
void* p455 = last_address;
DEBUG_PRINT(sfree(p251););
printStats();
DEBUG_PRINT(sfree(p308););
printStats();
PRINT_POINTER(smalloc(95););
printStats();
void* p456 = last_address;
PRINT_POINTER(scalloc(34,126););
printStats();
void* p457 = last_address;
DEBUG_PRINT(sfree(p448););
printStats();
PRINT_POINTER(srealloc(p444,232););
printStats();
void* p458 = last_address;
PRINT_POINTER(srealloc(p415,53););
printStats();
void* p459 = last_address;
PRINT_POINTER(srealloc(p291,101););
printStats();
void* p460 = last_address;
DEBUG_PRINT(sfree(p351););
printStats();
PRINT_POINTER(scalloc(208,216););
printStats();
void* p461 = last_address;
PRINT_POINTER(scalloc(164,181););
printStats();
void* p462 = last_address;
PRINT_POINTER(scalloc(109,13););
printStats();
void* p463 = last_address;
PRINT_POINTER(srealloc(p399,80););
printStats();
void* p464 = last_address;
PRINT_POINTER(srealloc(p212,204););
printStats();
void* p465 = last_address;
PRINT_POINTER(scalloc(59,40););
printStats();
void* p466 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p467 = last_address;
PRINT_POINTER(srealloc(p464,35););
printStats();
void* p468 = last_address;
DEBUG_PRINT(sfree(p304););
printStats();
PRINT_POINTER(srealloc(p369,168););
printStats();
void* p469 = last_address;
PRINT_POINTER(srealloc(p389,59););
printStats();
void* p470 = last_address;
PRINT_POINTER(scalloc(181,113););
printStats();
void* p471 = last_address;
PRINT_POINTER(srealloc(p206,96););
printStats();
void* p472 = last_address;
DEBUG_PRINT(sfree(p433););
printStats();
PRINT_POINTER(srealloc(p432,16););
printStats();
void* p473 = last_address;
DEBUG_PRINT(sfree(p355););
printStats();
PRINT_POINTER(smalloc(142););
printStats();
void* p474 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p475 = last_address;
DEBUG_PRINT(sfree(p457););
printStats();
PRINT_POINTER(scalloc(10,84););
printStats();
void* p476 = last_address;
DEBUG_PRINT(sfree(p440););
printStats();
PRINT_POINTER(scalloc(172,248););
printStats();
void* p477 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p478 = last_address;
PRINT_POINTER(scalloc(185,185););
printStats();
void* p479 = last_address;
PRINT_POINTER(srealloc(p360,77););
printStats();
void* p480 = last_address;
PRINT_POINTER(srealloc(p325,91););
printStats();
void* p481 = last_address;
DEBUG_PRINT(sfree(p478););
printStats();
PRINT_POINTER(scalloc(108,80););
printStats();
void* p482 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p483 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p484 = last_address;
DEBUG_PRINT(sfree(p428););
printStats();
PRINT_POINTER(scalloc(236,192););
printStats();
void* p485 = last_address;
DEBUG_PRINT(sfree(p305););
printStats();
PRINT_POINTER(smalloc(236););
printStats();
void* p486 = last_address;
DEBUG_PRINT(sfree(p450););
printStats();
PRINT_POINTER(scalloc(94,98););
printStats();
void* p487 = last_address;
PRINT_POINTER(srealloc(p424,106););
printStats();
void* p488 = last_address;
DEBUG_PRINT(sfree(p364););
printStats();
PRINT_POINTER(scalloc(249,187););
printStats();
void* p489 = last_address;
DEBUG_PRINT(sfree(p483););
printStats();
PRINT_POINTER(smalloc(38););
printStats();
void* p490 = last_address;
DEBUG_PRINT(sfree(p476););
printStats();
PRINT_POINTER(srealloc(p67,167););
printStats();
void* p491 = last_address;
PRINT_POINTER(smalloc(78););
printStats();
void* p492 = last_address;
DEBUG_PRINT(sfree(p301););
printStats();
PRINT_POINTER(scalloc(201,93););
printStats();
void* p493 = last_address;
DEBUG_PRINT(sfree(p480););
printStats();
PRINT_POINTER(scalloc(35,90););
printStats();
void* p494 = last_address;
DEBUG_PRINT(sfree(p413););
printStats();
PRINT_POINTER(smalloc(93););
printStats();
void* p495 = last_address;
PRINT_POINTER(srealloc(p446,208););
printStats();
void* p496 = last_address;
DEBUG_PRINT(sfree(p347););
printStats();
PRINT_POINTER(smalloc(205););
printStats();
void* p497 = last_address;
DEBUG_PRINT(sfree(p229););
printStats();
PRINT_POINTER(srealloc(p387,212););
printStats();
void* p498 = last_address;
PRINT_POINTER(srealloc(p494,73););
printStats();
void* p499 = last_address;
PRINT_POINTER(srealloc(p490,35););
printStats();
void* p500 = last_address;
PRINT_POINTER(srealloc(p497,123););
printStats();
void* p501 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p502 = last_address;
DEBUG_PRINT(sfree(p214););
printStats();
PRINT_POINTER(smalloc(106););
printStats();
void* p503 = last_address;
DEBUG_PRINT(sfree(p482););
printStats();
PRINT_POINTER(scalloc(48,101););
printStats();
void* p504 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p505 = last_address;
PRINT_POINTER(scalloc(59,193););
printStats();
void* p506 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p507 = last_address;
DEBUG_PRINT(sfree(p414););
printStats();
PRINT_POINTER(smalloc(29););
printStats();
void* p508 = last_address;
DEBUG_PRINT(sfree(p401););
printStats();
PRINT_POINTER(srealloc(p390,233););
printStats();
void* p509 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p510 = last_address;
PRINT_POINTER(scalloc(160,242););
printStats();
void* p511 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p512 = last_address;
PRINT_POINTER(scalloc(98,9););
printStats();
void* p513 = last_address;
DEBUG_PRINT(sfree(p362););
printStats();
DEBUG_PRINT(sfree(p501););
printStats();
DEBUG_PRINT(sfree(p463););
printStats();
PRINT_POINTER(scalloc(242,208););
printStats();
void* p514 = last_address;
DEBUG_PRINT(sfree(p461););
printStats();
PRINT_POINTER(smalloc(203););
printStats();
void* p515 = last_address;
DEBUG_PRINT(sfree(p474););
printStats();
PRINT_POINTER(srealloc(p422,104););
printStats();
void* p516 = last_address;
PRINT_POINTER(smalloc(113););
printStats();
void* p517 = last_address;
PRINT_POINTER(scalloc(132,163););
printStats();
void* p518 = last_address;
PRINT_POINTER(scalloc(208,75););
printStats();
void* p519 = last_address;
DEBUG_PRINT(sfree(p445););
printStats();
PRINT_POINTER(scalloc(227,224););
printStats();
void* p520 = last_address;
DEBUG_PRINT(sfree(p500););
printStats();
PRINT_POINTER(srealloc(p370,34););
printStats();
void* p521 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p522 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p523 = last_address;
PRINT_POINTER(scalloc(114,172););
printStats();
void* p524 = last_address;
PRINT_POINTER(srealloc(p368,6););
printStats();
void* p525 = last_address;
PRINT_POINTER(srealloc(p466,225););
printStats();
void* p526 = last_address;
PRINT_POINTER(scalloc(156,116););
printStats();
void* p527 = last_address;
PRINT_POINTER(scalloc(234,167););
printStats();
void* p528 = last_address;
PRINT_POINTER(scalloc(151,81););
printStats();
void* p529 = last_address;
PRINT_POINTER(smalloc(162););
printStats();
void* p530 = last_address;
PRINT_POINTER(srealloc(p520,133););
printStats();
void* p531 = last_address;
DEBUG_PRINT(sfree(p523););
printStats();
PRINT_POINTER(srealloc(p340,19););
printStats();
void* p532 = last_address;
PRINT_POINTER(srealloc(p467,142););
printStats();
void* p533 = last_address;
DEBUG_PRINT(sfree(p384););
printStats();
PRINT_POINTER(srealloc(p279,227););
printStats();
void* p534 = last_address;
DEBUG_PRINT(sfree(p299););
printStats();
PRINT_POINTER(smalloc(201););
printStats();
void* p535 = last_address;
PRINT_POINTER(srealloc(p397,161););
printStats();
void* p536 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p537 = last_address;
PRINT_POINTER(scalloc(165,227););
printStats();
void* p538 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p539 = last_address;
PRINT_POINTER(srealloc(p506,129););
printStats();
void* p540 = last_address;
PRINT_POINTER(scalloc(180,105););
printStats();
void* p541 = last_address;
DEBUG_PRINT(sfree(p508););
printStats();
PRINT_POINTER(srealloc(p459,205););
printStats();
void* p542 = last_address;
PRINT_POINTER(srealloc(p275,74););
printStats();
void* p543 = last_address;
PRINT_POINTER(srealloc(p504,42););
printStats();
void* p544 = last_address;
PRINT_POINTER(srealloc(p519,190););
printStats();
void* p545 = last_address;
PRINT_POINTER(scalloc(117,25););
printStats();
void* p546 = last_address;
PRINT_POINTER(scalloc(20,98););
printStats();
void* p547 = last_address;
PRINT_POINTER(scalloc(100,160););
printStats();
void* p548 = last_address;
PRINT_POINTER(scalloc(18,74););
printStats();
void* p549 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p550 = last_address;
PRINT_POINTER(smalloc(200););
printStats();
void* p551 = last_address;
PRINT_POINTER(scalloc(204,232););
printStats();
void* p552 = last_address;
PRINT_POINTER(srealloc(p550,18););
printStats();
void* p553 = last_address;
PRINT_POINTER(srealloc(p503,246););
printStats();
void* p554 = last_address;
DEBUG_PRINT(sfree(p380););
printStats();
PRINT_POINTER(scalloc(97,136););
printStats();
void* p555 = last_address;
PRINT_POINTER(scalloc(10,21););
printStats();
void* p556 = last_address;
PRINT_POINTER(scalloc(123,15););
printStats();
void* p557 = last_address;
PRINT_POINTER(srealloc(p392,97););
printStats();
void* p558 = last_address;
PRINT_POINTER(scalloc(37,130););
printStats();
void* p559 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p560 = last_address;
PRINT_POINTER(scalloc(130,163););
printStats();
void* p561 = last_address;
PRINT_POINTER(srealloc(p385,233););
printStats();
void* p562 = last_address;
PRINT_POINTER(scalloc(88,171););
printStats();
void* p563 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p564 = last_address;
PRINT_POINTER(scalloc(230,102););
printStats();
void* p565 = last_address;
PRINT_POINTER(scalloc(44,39););
printStats();
void* p566 = last_address;
DEBUG_PRINT(sfree(p102););
printStats();
PRINT_POINTER(smalloc(58););
printStats();
void* p567 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p568 = last_address;
PRINT_POINTER(srealloc(p273,1););
printStats();
void* p569 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p570 = last_address;
PRINT_POINTER(scalloc(150,134););
printStats();
void* p571 = last_address;
PRINT_POINTER(scalloc(236,115););
printStats();
void* p572 = last_address;
PRINT_POINTER(smalloc(115););
printStats();
void* p573 = last_address;
PRINT_POINTER(scalloc(176,29););
printStats();
void* p574 = last_address;
PRINT_POINTER(scalloc(45,227););
printStats();
void* p575 = last_address;
PRINT_POINTER(scalloc(237,132););
printStats();
void* p576 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p577 = last_address;
PRINT_POINTER(scalloc(243,53););
printStats();
void* p578 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p579 = last_address;
PRINT_POINTER(srealloc(p247,212););
printStats();
void* p580 = last_address;
PRINT_POINTER(scalloc(77,238););
printStats();
void* p581 = last_address;
PRINT_POINTER(scalloc(56,198););
printStats();
void* p582 = last_address;
PRINT_POINTER(smalloc(231););
printStats();
void* p583 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p584 = last_address;
PRINT_POINTER(scalloc(112,114););
printStats();
void* p585 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p586 = last_address;
DEBUG_PRINT(sfree(p479););
printStats();
DEBUG_PRINT(sfree(p509););
printStats();
DEBUG_PRINT(sfree(p441););
printStats();
PRINT_POINTER(srealloc(p412,42););
printStats();
void* p587 = last_address;
DEBUG_PRINT(sfree(p565););
printStats();
DEBUG_PRINT(sfree(p354););
printStats();
PRINT_POINTER(smalloc(107););
printStats();
void* p588 = last_address;
PRINT_POINTER(scalloc(237,228););
printStats();
void* p589 = last_address;
PRINT_POINTER(srealloc(p556,38););
printStats();
void* p590 = last_address;
PRINT_POINTER(scalloc(60,222););
printStats();
void* p591 = last_address;
PRINT_POINTER(srealloc(p582,245););
printStats();
void* p592 = last_address;
PRINT_POINTER(scalloc(87,53););
printStats();
void* p593 = last_address;
PRINT_POINTER(srealloc(p536,18););
printStats();
void* p594 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p595 = last_address;
PRINT_POINTER(srealloc(p473,237););
printStats();
void* p596 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p597 = last_address;
PRINT_POINTER(srealloc(p266,196););
printStats();
void* p598 = last_address;
PRINT_POINTER(scalloc(90,227););
printStats();
void* p599 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p600 = last_address;
PRINT_POINTER(srealloc(p439,91););
printStats();
void* p601 = last_address;
PRINT_POINTER(srealloc(p574,94););
printStats();
void* p602 = last_address;
PRINT_POINTER(srealloc(p533,52););
printStats();
void* p603 = last_address;
DEBUG_PRINT(sfree(p586););
printStats();
DEBUG_PRINT(sfree(p456););
printStats();
PRINT_POINTER(scalloc(227,238););
printStats();
void* p604 = last_address;
PRINT_POINTER(scalloc(45,203););
printStats();
void* p605 = last_address;
DEBUG_PRINT(sfree(p593););
printStats();
PRINT_POINTER(srealloc(p585,0););
printStats();
void* p606 = last_address;
DEBUG_PRINT(sfree(p318););
printStats();
PRINT_POINTER(smalloc(26););
printStats();
void* p607 = last_address;
PRINT_POINTER(srealloc(p560,132););
printStats();
void* p608 = last_address;
DEBUG_PRINT(sfree(p579););
printStats();
PRINT_POINTER(scalloc(153,15););
printStats();
void* p609 = last_address;
DEBUG_PRINT(sfree(p339););
printStats();
DEBUG_PRINT(sfree(p548););
printStats();
PRINT_POINTER(scalloc(163,126););
printStats();
void* p610 = last_address;
PRINT_POINTER(srealloc(p277,37););
printStats();
void* p611 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p612 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p613 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p614 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p615 = last_address;
DEBUG_PRINT(sfree(p605););
printStats();
PRINT_POINTER(scalloc(91,184););
printStats();
void* p616 = last_address;
DEBUG_PRINT(sfree(p460););
printStats();
PRINT_POINTER(srealloc(p357,114););
printStats();
void* p617 = last_address;
PRINT_POINTER(scalloc(37,30););
printStats();
void* p618 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p619 = last_address;
DEBUG_PRINT(sfree(p343););
printStats();
PRINT_POINTER(smalloc(86););
printStats();
void* p620 = last_address;
PRINT_POINTER(smalloc(122););
printStats();
void* p621 = last_address;
PRINT_POINTER(scalloc(52,96););
printStats();
void* p622 = last_address;
DEBUG_PRINT(sfree(p549););
printStats();
DEBUG_PRINT(sfree(p564););
printStats();
DEBUG_PRINT(sfree(p557););
printStats();
PRINT_POINTER(srealloc(p472,163););
printStats();
void* p623 = last_address;
PRINT_POINTER(srealloc(p514,168););
printStats();
void* p624 = last_address;
PRINT_POINTER(srealloc(p515,93););
printStats();
void* p625 = last_address;
PRINT_POINTER(smalloc(92););
printStats();
void* p626 = last_address;
DEBUG_PRINT(sfree(p528););
printStats();
PRINT_POINTER(smalloc(28););
printStats();
void* p627 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
PRINT_POINTER(smalloc(136););
printStats();
void* p628 = last_address;
PRINT_POINTER(scalloc(181,237););
printStats();
void* p629 = last_address;
DEBUG_PRINT(sfree(p625););
printStats();
PRINT_POINTER(srealloc(p525,182););
printStats();
void* p630 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p631 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p632 = last_address;
PRINT_POINTER(srealloc(p544,110););
printStats();
void* p633 = last_address;
DEBUG_PRINT(sfree(p263););
printStats();
PRINT_POINTER(scalloc(94,146););
printStats();
void* p634 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p635 = last_address;
PRINT_POINTER(srealloc(p606,65););
printStats();
void* p636 = last_address;
DEBUG_PRINT(sfree(p538););
printStats();
PRINT_POINTER(srealloc(p402,67););
printStats();
void* p637 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p638 = last_address;
DEBUG_PRINT(sfree(p409););
printStats();
PRINT_POINTER(srealloc(p630,160););
printStats();
void* p639 = last_address;
PRINT_POINTER(srealloc(p573,31););
printStats();
void* p640 = last_address;
DEBUG_PRINT(sfree(p631););
printStats();
PRINT_POINTER(srealloc(p316,70););
printStats();
void* p641 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p642 = last_address;
PRINT_POINTER(scalloc(23,45););
printStats();
void* p643 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p644 = last_address;
PRINT_POINTER(srealloc(p539,106););
printStats();
void* p645 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p646 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p647 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p648 = last_address;
DEBUG_PRINT(sfree(p554););
printStats();
PRINT_POINTER(srealloc(p492,118););
printStats();
void* p649 = last_address;
PRINT_POINTER(smalloc(110););
printStats();
void* p650 = last_address;
DEBUG_PRINT(sfree(p532););
printStats();
PRINT_POINTER(smalloc(129););
printStats();
void* p651 = last_address;
DEBUG_PRINT(sfree(p454););
printStats();
PRINT_POINTER(srealloc(p416,134););
printStats();
void* p652 = last_address;
PRINT_POINTER(srealloc(p558,5););
printStats();
void* p653 = last_address;
DEBUG_PRINT(sfree(p429););
printStats();
PRINT_POINTER(srealloc(p650,48););
printStats();
void* p654 = last_address;
PRINT_POINTER(srealloc(p648,68););
printStats();
void* p655 = last_address;
PRINT_POINTER(srealloc(p567,213););
printStats();
void* p656 = last_address;
PRINT_POINTER(srealloc(p645,112););
printStats();
void* p657 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p658 = last_address;
PRINT_POINTER(scalloc(226,175););
printStats();
void* p659 = last_address;
DEBUG_PRINT(sfree(p430););
printStats();
PRINT_POINTER(scalloc(113,151););
printStats();
void* p660 = last_address;
DEBUG_PRINT(sfree(p563););
printStats();
PRINT_POINTER(srealloc(p512,227););
printStats();
void* p661 = last_address;
PRINT_POINTER(scalloc(140,135););
printStats();
void* p662 = last_address;
PRINT_POINTER(srealloc(p562,58););
printStats();
void* p663 = last_address;
DEBUG_PRINT(sfree(p393););
printStats();
PRINT_POINTER(srealloc(p566,180););
printStats();
void* p664 = last_address;
PRINT_POINTER(srealloc(p618,174););
printStats();
void* p665 = last_address;
PRINT_POINTER(scalloc(158,173););
printStats();
void* p666 = last_address;
PRINT_POINTER(srealloc(p505,50););
printStats();
void* p667 = last_address;
PRINT_POINTER(scalloc(200,157););
printStats();
void* p668 = last_address;
DEBUG_PRINT(sfree(p616););
printStats();
DEBUG_PRINT(sfree(p600););
printStats();
PRINT_POINTER(srealloc(p284,5););
printStats();
void* p669 = last_address;
PRINT_POINTER(srealloc(p319,143););
printStats();
void* p670 = last_address;
PRINT_POINTER(scalloc(123,5););
printStats();
void* p671 = last_address;
PRINT_POINTER(scalloc(246,99););
printStats();
void* p672 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p673 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p674 = last_address;
PRINT_POINTER(scalloc(245,76););
printStats();
void* p675 = last_address;
PRINT_POINTER(scalloc(154,34););
printStats();
void* p676 = last_address;
DEBUG_PRINT(sfree(p475););
printStats();
DEBUG_PRINT(sfree(p455););
printStats();
PRINT_POINTER(smalloc(125););
printStats();
void* p677 = last_address;
PRINT_POINTER(scalloc(232,171););
printStats();
void* p678 = last_address;
DEBUG_PRINT(sfree(p620););
printStats();
PRINT_POINTER(srealloc(p411,20););
printStats();
void* p679 = last_address;
PRINT_POINTER(srealloc(p663,165););
printStats();
void* p680 = last_address;
DEBUG_PRINT(sfree(p534););
printStats();
PRINT_POINTER(smalloc(73););
printStats();
void* p681 = last_address;
PRINT_POINTER(scalloc(176,43););
printStats();
void* p682 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p683 = last_address;
PRINT_POINTER(scalloc(5,67););
printStats();
void* p684 = last_address;
DEBUG_PRINT(sfree(p546););
printStats();
PRINT_POINTER(scalloc(14,149););
printStats();
void* p685 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p686 = last_address;
PRINT_POINTER(srealloc(p655,95););
printStats();
void* p687 = last_address;
DEBUG_PRINT(sfree(p306););
printStats();
PRINT_POINTER(smalloc(156););
printStats();
void* p688 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p689 = last_address;
PRINT_POINTER(srealloc(p261,0););
printStats();
void* p690 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p691 = last_address;
PRINT_POINTER(scalloc(94,1););
printStats();
void* p692 = last_address;
PRINT_POINTER(scalloc(210,163););
printStats();
void* p693 = last_address;
PRINT_POINTER(srealloc(p657,17););
printStats();
void* p694 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p695 = last_address;
PRINT_POINTER(scalloc(165,202););
printStats();
void* p696 = last_address;
PRINT_POINTER(scalloc(75,124););
printStats();
void* p697 = last_address;
PRINT_POINTER(srealloc(p174,202););
printStats();
void* p698 = last_address;
PRINT_POINTER(scalloc(206,137););
printStats();
void* p699 = last_address;
PRINT_POINTER(srealloc(p443,50););
printStats();
void* p700 = last_address;
PRINT_POINTER(srealloc(p589,123););
printStats();
void* p701 = last_address;
PRINT_POINTER(scalloc(1,81););
printStats();
void* p702 = last_address;
DEBUG_PRINT(sfree(p668););
printStats();
PRINT_POINTER(srealloc(p375,102););
printStats();
void* p703 = last_address;
PRINT_POINTER(srealloc(p651,103););
printStats();
void* p704 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p705 = last_address;
DEBUG_PRINT(sfree(p481););
printStats();
PRINT_POINTER(srealloc(p617,107););
printStats();
void* p706 = last_address;
DEBUG_PRINT(sfree(p675););
printStats();
PRINT_POINTER(scalloc(40,118););
printStats();
void* p707 = last_address;
DEBUG_PRINT(sfree(p551););
printStats();
PRINT_POINTER(smalloc(123););
printStats();
void* p708 = last_address;
DEBUG_PRINT(sfree(p576););
printStats();
PRINT_POINTER(scalloc(160,239););
printStats();
void* p709 = last_address;
PRINT_POINTER(smalloc(80););
printStats();
void* p710 = last_address;
PRINT_POINTER(srealloc(p451,213););
printStats();
void* p711 = last_address;
PRINT_POINTER(srealloc(p679,62););
printStats();
void* p712 = last_address;
PRINT_POINTER(scalloc(223,214););
printStats();
void* p713 = last_address;
DEBUG_PRINT(sfree(p622););
printStats();
PRINT_POINTER(srealloc(p575,15););
printStats();
void* p714 = last_address;
PRINT_POINTER(scalloc(216,135););
printStats();
void* p715 = last_address;
DEBUG_PRINT(sfree(p691););
printStats();
PRINT_POINTER(srealloc(p423,81););
printStats();
void* p716 = last_address;
PRINT_POINTER(srealloc(p531,102););
printStats();
void* p717 = last_address;
PRINT_POINTER(srealloc(p378,59););
printStats();
void* p718 = last_address;
DEBUG_PRINT(sfree(p553););
printStats();
PRINT_POINTER(smalloc(114););
printStats();
void* p719 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p720 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p721 = last_address;
DEBUG_PRINT(sfree(p721););
printStats();
PRINT_POINTER(srealloc(p615,138););
printStats();
void* p722 = last_address;
PRINT_POINTER(scalloc(76,168););
printStats();
void* p723 = last_address;
PRINT_POINTER(scalloc(198,184););
printStats();
void* p724 = last_address;
PRINT_POINTER(scalloc(124,146););
printStats();
void* p725 = last_address;
PRINT_POINTER(srealloc(p698,19););
printStats();
void* p726 = last_address;
PRINT_POINTER(scalloc(51,64););
printStats();
void* p727 = last_address;
PRINT_POINTER(srealloc(p607,51););
printStats();
void* p728 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p729 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p730 = last_address;
PRINT_POINTER(scalloc(171,36););
printStats();
void* p731 = last_address;
PRINT_POINTER(scalloc(234,219););
printStats();
void* p732 = last_address;
PRINT_POINTER(scalloc(9,135););
printStats();
void* p733 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p734 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p735 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p736 = last_address;
DEBUG_PRINT(sfree(p642););
printStats();
DEBUG_PRINT(sfree(p649););
printStats();
PRINT_POINTER(srealloc(p561,165););
printStats();
void* p737 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p738 = last_address;
DEBUG_PRINT(sfree(p526););
printStats();
DEBUG_PRINT(sfree(p591););
printStats();
PRINT_POINTER(scalloc(197,101););
printStats();
void* p739 = last_address;
PRINT_POINTER(scalloc(126,136););
printStats();
void* p740 = last_address;
DEBUG_PRINT(sfree(p738););
printStats();
PRINT_POINTER(smalloc(90););
printStats();
void* p741 = last_address;
DEBUG_PRINT(sfree(p629););
printStats();
PRINT_POINTER(smalloc(137););
printStats();
void* p742 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p743 = last_address;
DEBUG_PRINT(sfree(p498););
printStats();
PRINT_POINTER(srealloc(p502,191););
printStats();
void* p744 = last_address;
PRINT_POINTER(srealloc(p643,69););
printStats();
void* p745 = last_address;
PRINT_POINTER(srealloc(p537,142););
printStats();
void* p746 = last_address;
DEBUG_PRINT(sfree(p599););
printStats();
DEBUG_PRINT(sfree(p660););
printStats();
PRINT_POINTER(srealloc(p737,209););
printStats();
void* p747 = last_address;
PRINT_POINTER(srealloc(p692,191););
printStats();
void* p748 = last_address;
DEBUG_PRINT(sfree(p658););
printStats();
PRINT_POINTER(smalloc(47););
printStats();
void* p749 = last_address;
DEBUG_PRINT(sfree(p687););
printStats();
PRINT_POINTER(scalloc(27,20););
printStats();
void* p750 = last_address;
PRINT_POINTER(srealloc(p710,120););
printStats();
void* p751 = last_address;
PRINT_POINTER(srealloc(p656,144););
printStats();
void* p752 = last_address;
PRINT_POINTER(srealloc(p677,166););
printStats();
void* p753 = last_address;
DEBUG_PRINT(sfree(p487););
printStats();
PRINT_POINTER(smalloc(208););
printStats();
void* p754 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p755 = last_address;
PRINT_POINTER(smalloc(134););
printStats();
void* p756 = last_address;
PRINT_POINTER(scalloc(184,41););
printStats();
void* p757 = last_address;
PRINT_POINTER(srealloc(p583,206););
printStats();
void* p758 = last_address;
PRINT_POINTER(scalloc(232,209););
printStats();
void* p759 = last_address;
PRINT_POINTER(srealloc(p614,12););
printStats();
void* p760 = last_address;
DEBUG_PRINT(sfree(p720););
printStats();
PRINT_POINTER(scalloc(42,116););
printStats();
void* p761 = last_address;
DEBUG_PRINT(sfree(p703););
printStats();
PRINT_POINTER(scalloc(226,39););
printStats();
void* p762 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p763 = last_address;
PRINT_POINTER(scalloc(42,239););
printStats();
void* p764 = last_address;
PRINT_POINTER(srealloc(p674,23););
printStats();
void* p765 = last_address;
PRINT_POINTER(scalloc(27,44););
printStats();
void* p766 = last_address;
PRINT_POINTER(scalloc(66,128););
printStats();
void* p767 = last_address;
DEBUG_PRINT(sfree(p627););
printStats();
PRINT_POINTER(smalloc(248););
printStats();
void* p768 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p769 = last_address;
DEBUG_PRINT(sfree(p761););
printStats();
PRINT_POINTER(smalloc(157););
printStats();
void* p770 = last_address;
DEBUG_PRINT(sfree(p756););
printStats();
DEBUG_PRINT(sfree(p762););
printStats();
PRINT_POINTER(scalloc(102,57););
printStats();
void* p771 = last_address;
PRINT_POINTER(srealloc(p680,76););
printStats();
void* p772 = last_address;
PRINT_POINTER(srealloc(p518,78););
printStats();
void* p773 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p774 = last_address;
DEBUG_PRINT(sfree(p541););
printStats();
PRINT_POINTER(srealloc(p488,92););
printStats();
void* p775 = last_address;
DEBUG_PRINT(sfree(p661););
printStats();
PRINT_POINTER(srealloc(p732,55););
printStats();
void* p776 = last_address;
DEBUG_PRINT(sfree(p693););
printStats();
DEBUG_PRINT(sfree(p529););
printStats();
PRINT_POINTER(scalloc(95,20););
printStats();
void* p777 = last_address;
PRINT_POINTER(srealloc(p688,99););
printStats();
void* p778 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p779 = last_address;
PRINT_POINTER(srealloc(p711,2););
printStats();
void* p780 = last_address;
DEBUG_PRINT(sfree(p636););
printStats();
PRINT_POINTER(srealloc(p772,205););
printStats();
void* p781 = last_address;
PRINT_POINTER(srealloc(p471,228););
printStats();
void* p782 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p783 = last_address;
PRINT_POINTER(scalloc(6,191););
printStats();
void* p784 = last_address;
DEBUG_PRINT(sfree(p725););
printStats();
PRINT_POINTER(smalloc(95););
printStats();
void* p785 = last_address;
PRINT_POINTER(smalloc(184););
printStats();
void* p786 = last_address;
PRINT_POINTER(scalloc(186,118););
printStats();
void* p787 = last_address;
PRINT_POINTER(scalloc(85,230););
printStats();
void* p788 = last_address;
PRINT_POINTER(srealloc(p682,166););
printStats();
void* p789 = last_address;
DEBUG_PRINT(sfree(p752););
printStats();
PRINT_POINTER(smalloc(154););
printStats();
void* p790 = last_address;
PRINT_POINTER(smalloc(47););
printStats();
void* p791 = last_address;
PRINT_POINTER(scalloc(93,215););
printStats();
void* p792 = last_address;
PRINT_POINTER(srealloc(p792,133););
printStats();
void* p793 = last_address;
DEBUG_PRINT(sfree(p729););
printStats();
PRINT_POINTER(srealloc(p408,243););
printStats();
void* p794 = last_address;
PRINT_POINTER(scalloc(79,194););
printStats();
void* p795 = last_address;
DEBUG_PRINT(sfree(p491););
printStats();
PRINT_POINTER(srealloc(p700,233););
printStats();
void* p796 = last_address;
PRINT_POINTER(scalloc(66,101););
printStats();
void* p797 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p798 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p799 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p800 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p801 = last_address;
DEBUG_PRINT(sfree(p723););
printStats();
PRINT_POINTER(smalloc(143););
printStats();
void* p802 = last_address;
PRINT_POINTER(scalloc(96,87););
printStats();
void* p803 = last_address;
DEBUG_PRINT(sfree(p350););
printStats();
PRINT_POINTER(smalloc(150););
printStats();
void* p804 = last_address;
DEBUG_PRINT(sfree(p768););
printStats();
PRINT_POINTER(scalloc(92,142););
printStats();
void* p805 = last_address;
PRINT_POINTER(scalloc(206,193););
printStats();
void* p806 = last_address;
PRINT_POINTER(srealloc(p511,139););
printStats();
void* p807 = last_address;
PRINT_POINTER(srealloc(p730,231););
printStats();
void* p808 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p809 = last_address;
PRINT_POINTER(srealloc(p684,196););
printStats();
void* p810 = last_address;
PRINT_POINTER(scalloc(71,163););
printStats();
void* p811 = last_address;
PRINT_POINTER(scalloc(25,68););
printStats();
void* p812 = last_address;
PRINT_POINTER(scalloc(185,95););
printStats();
void* p813 = last_address;
PRINT_POINTER(srealloc(p775,214););
printStats();
void* p814 = last_address;
PRINT_POINTER(srealloc(p744,180););
printStats();
void* p815 = last_address;
PRINT_POINTER(scalloc(140,195););
printStats();
void* p816 = last_address;
DEBUG_PRINT(sfree(p646););
printStats();
DEBUG_PRINT(sfree(p552););
printStats();
PRINT_POINTER(srealloc(p647,18););
printStats();
void* p817 = last_address;
PRINT_POINTER(scalloc(3,74););
printStats();
void* p818 = last_address;
PRINT_POINTER(srealloc(p587,27););
printStats();
void* p819 = last_address;
DEBUG_PRINT(sfree(p522););
printStats();
PRINT_POINTER(scalloc(189,78););
printStats();
void* p820 = last_address;
PRINT_POINTER(scalloc(124,52););
printStats();
void* p821 = last_address;
PRINT_POINTER(smalloc(54););
printStats();
void* p822 = last_address;
PRINT_POINTER(srealloc(p640,67););
printStats();
void* p823 = last_address;
DEBUG_PRINT(sfree(p603););
printStats();
DEBUG_PRINT(sfree(p813););
printStats();
DEBUG_PRINT(sfree(p731););
printStats();
PRINT_POINTER(srealloc(p671,131););
printStats();
void* p824 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p825 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p826 = last_address;
PRINT_POINTER(smalloc(68););
printStats();
void* p827 = last_address;
PRINT_POINTER(srealloc(p559,13););
printStats();
void* p828 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p829 = last_address;
PRINT_POINTER(scalloc(249,159););
printStats();
void* p830 = last_address;
PRINT_POINTER(scalloc(243,101););
printStats();
void* p831 = last_address;
DEBUG_PRINT(sfree(p394););
printStats();
PRINT_POINTER(srealloc(p804,62););
printStats();
void* p832 = last_address;
PRINT_POINTER(scalloc(205,115););
printStats();
void* p833 = last_address;
PRINT_POINTER(srealloc(p763,116););
printStats();
void* p834 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p835 = last_address;
DEBUG_PRINT(sfree(p783););
printStats();
PRINT_POINTER(srealloc(p595,30););
printStats();
void* p836 = last_address;
PRINT_POINTER(scalloc(142,190););
printStats();
void* p837 = last_address;
PRINT_POINTER(smalloc(56););
printStats();
void* p838 = last_address;
PRINT_POINTER(srealloc(p797,40););
printStats();
void* p839 = last_address;
PRINT_POINTER(scalloc(92,218););
printStats();
void* p840 = last_address;
DEBUG_PRINT(sfree(p760););
printStats();
PRINT_POINTER(srealloc(p836,143););
printStats();
void* p841 = last_address;
PRINT_POINTER(srealloc(p667,230););
printStats();
void* p842 = last_address;
PRINT_POINTER(srealloc(p803,124););
printStats();
void* p843 = last_address;
PRINT_POINTER(scalloc(22,128););
printStats();
void* p844 = last_address;
PRINT_POINTER(srealloc(p524,50););
printStats();
void* p845 = last_address;
PRINT_POINTER(srealloc(p447,69););
printStats();
void* p846 = last_address;
DEBUG_PRINT(sfree(p758););
printStats();
PRINT_POINTER(srealloc(p830,101););
printStats();
void* p847 = last_address;
PRINT_POINTER(srealloc(p786,209););
printStats();
void* p848 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p849 = last_address;
PRINT_POINTER(smalloc(229););
printStats();
void* p850 = last_address;
PRINT_POINTER(scalloc(146,219););
printStats();
void* p851 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p852 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p853 = last_address;
PRINT_POINTER(scalloc(83,172););
printStats();
void* p854 = last_address;
PRINT_POINTER(srealloc(p588,223););
printStats();
void* p855 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p856 = last_address;
PRINT_POINTER(srealloc(p765,82););
printStats();
void* p857 = last_address;
PRINT_POINTER(srealloc(p669,88););
printStats();
void* p858 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p859 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p860 = last_address;
PRINT_POINTER(srealloc(p733,232););
printStats();
void* p861 = last_address;
DEBUG_PRINT(sfree(p747););
printStats();
DEBUG_PRINT(sfree(p736););
printStats();
DEBUG_PRINT(sfree(p734););
printStats();
DEBUG_PRINT(sfree(p702););
printStats();
PRINT_POINTER(srealloc(p713,95););
printStats();
void* p862 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p863 = last_address;
DEBUG_PRINT(sfree(p850););
printStats();
PRINT_POINTER(smalloc(3););
printStats();
void* p864 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p865 = last_address;
PRINT_POINTER(smalloc(242););
printStats();
void* p866 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p867 = last_address;
PRINT_POINTER(srealloc(p665,163););
printStats();
void* p868 = last_address;
PRINT_POINTER(srealloc(p632,123););
printStats();
void* p869 = last_address;
DEBUG_PRINT(sfree(p823););
printStats();
PRINT_POINTER(smalloc(124););
printStats();
void* p870 = last_address;
DEBUG_PRINT(sfree(p608););
printStats();
PRINT_POINTER(srealloc(p818,20););
printStats();
void* p871 = last_address;
PRINT_POINTER(srealloc(p610,71););
printStats();
void* p872 = last_address;
PRINT_POINTER(smalloc(1););
printStats();
void* p873 = last_address;
PRINT_POINTER(smalloc(237););
printStats();
void* p874 = last_address;
PRINT_POINTER(srealloc(p686,129););
printStats();
void* p875 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p876 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p877 = last_address;
PRINT_POINTER(srealloc(p644,240););
printStats();
void* p878 = last_address;
DEBUG_PRINT(sfree(p697););
printStats();
PRINT_POINTER(smalloc(42););
printStats();
void* p879 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p880 = last_address;
PRINT_POINTER(srealloc(p82,216););
printStats();
void* p881 = last_address;
PRINT_POINTER(srealloc(p581,157););
printStats();
void* p882 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p883 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p884 = last_address;
DEBUG_PRINT(sfree(p808););
printStats();
PRINT_POINTER(srealloc(p864,198););
printStats();
void* p885 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p886 = last_address;
DEBUG_PRINT(sfree(p865););
printStats();
PRINT_POINTER(smalloc(11););
printStats();
void* p887 = last_address;
PRINT_POINTER(smalloc(124););
printStats();
void* p888 = last_address;
PRINT_POINTER(srealloc(p853,115););
printStats();
void* p889 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p890 = last_address;
PRINT_POINTER(scalloc(65,155););
printStats();
void* p891 = last_address;
DEBUG_PRINT(sfree(p685););
printStats();
PRINT_POINTER(scalloc(181,41););
printStats();
void* p892 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p893 = last_address;
PRINT_POINTER(srealloc(p859,67););
printStats();
void* p894 = last_address;
DEBUG_PRINT(sfree(p875););
printStats();
PRINT_POINTER(srealloc(p499,58););
printStats();
void* p895 = last_address;
DEBUG_PRINT(sfree(p709););
printStats();
PRINT_POINTER(smalloc(173););
printStats();
void* p896 = last_address;
PRINT_POINTER(scalloc(105,64););
printStats();
void* p897 = last_address;
DEBUG_PRINT(sfree(p890););
printStats();
PRINT_POINTER(scalloc(127,45););
printStats();
void* p898 = last_address;
DEBUG_PRINT(sfree(p839););
printStats();
PRINT_POINTER(srealloc(p628,8););
printStats();
void* p899 = last_address;
DEBUG_PRINT(sfree(p798););
printStats();
PRINT_POINTER(smalloc(77););
printStats();
void* p900 = last_address;
PRINT_POINTER(scalloc(47,157););
printStats();
void* p901 = last_address;
DEBUG_PRINT(sfree(p770););
printStats();
PRINT_POINTER(smalloc(9););
printStats();
void* p902 = last_address;
DEBUG_PRINT(sfree(p391););
printStats();
PRINT_POINTER(scalloc(197,130););
printStats();
void* p903 = last_address;
PRINT_POINTER(srealloc(p749,166););
printStats();
void* p904 = last_address;
PRINT_POINTER(srealloc(p845,205););
printStats();
void* p905 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p906 = last_address;
PRINT_POINTER(srealloc(p637,94););
printStats();
void* p907 = last_address;
PRINT_POINTER(srealloc(p896,148););
printStats();
void* p908 = last_address;
DEBUG_PRINT(sfree(p670););
printStats();
DEBUG_PRINT(sfree(p899););
printStats();
DEBUG_PRINT(sfree(p374););
printStats();
PRINT_POINTER(smalloc(231););
printStats();
void* p909 = last_address;
PRINT_POINTER(srealloc(p598,134););
printStats();
void* p910 = last_address;
PRINT_POINTER(srealloc(p871,88););
printStats();
void* p911 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p912 = last_address;
DEBUG_PRINT(sfree(p410););
printStats();
PRINT_POINTER(srealloc(p809,52););
printStats();
void* p913 = last_address;
PRINT_POINTER(scalloc(210,158););
printStats();
void* p914 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p915 = last_address;
PRINT_POINTER(scalloc(92,196););
printStats();
void* p916 = last_address;
PRINT_POINTER(smalloc(203););
printStats();
void* p917 = last_address;
DEBUG_PRINT(sfree(p342););
printStats();
DEBUG_PRINT(sfree(p535););
printStats();
PRINT_POINTER(srealloc(p917,21););
printStats();
void* p918 = last_address;
PRINT_POINTER(scalloc(187,97););
printStats();
void* p919 = last_address;
PRINT_POINTER(srealloc(p288,100););
printStats();
void* p920 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p921 = last_address;
DEBUG_PRINT(sfree(p879););
printStats();
PRINT_POINTER(scalloc(144,100););
printStats();
void* p922 = last_address;
PRINT_POINTER(scalloc(233,73););
printStats();
void* p923 = last_address;
PRINT_POINTER(scalloc(156,131););
printStats();
void* p924 = last_address;
PRINT_POINTER(scalloc(181,204););
printStats();
void* p925 = last_address;
PRINT_POINTER(srealloc(p854,34););
printStats();
void* p926 = last_address;
PRINT_POINTER(scalloc(113,140););
printStats();
void* p927 = last_address;
PRINT_POINTER(srealloc(p892,44););
printStats();
void* p928 = last_address;
PRINT_POINTER(srealloc(p914,210););
printStats();
void* p929 = last_address;
PRINT_POINTER(srealloc(p922,68););
printStats();
void* p930 = last_address;
PRINT_POINTER(srealloc(p611,110););
printStats();
void* p931 = last_address;
PRINT_POINTER(scalloc(37,44););
printStats();
void* p932 = last_address;
PRINT_POINTER(srealloc(p913,52););
printStats();
void* p933 = last_address;
}
