#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(32););
printStats();
void* p0 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(srealloc(p1,74););
printStats();
void* p2 = last_address;
PRINT_POINTER(smalloc(174););
printStats();
void* p3 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p4 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p5 = last_address;
PRINT_POINTER(smalloc(170););
printStats();
void* p6 = last_address;
DEBUG_PRINT(sfree(p3););
printStats();
PRINT_POINTER(srealloc(p2,214););
printStats();
void* p7 = last_address;
PRINT_POINTER(srealloc(p4,14););
printStats();
void* p8 = last_address;
PRINT_POINTER(scalloc(238,10););
printStats();
void* p9 = last_address;
PRINT_POINTER(srealloc(p8,97););
printStats();
void* p10 = last_address;
PRINT_POINTER(scalloc(234,14););
printStats();
void* p11 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p12 = last_address;
PRINT_POINTER(smalloc(138););
printStats();
void* p13 = last_address;
DEBUG_PRINT(sfree(p6););
printStats();
PRINT_POINTER(smalloc(211););
printStats();
void* p14 = last_address;
DEBUG_PRINT(sfree(p9););
printStats();
PRINT_POINTER(scalloc(96,220););
printStats();
void* p15 = last_address;
DEBUG_PRINT(sfree(p10););
printStats();
DEBUG_PRINT(sfree(p12););
printStats();
PRINT_POINTER(srealloc(p5,25););
printStats();
void* p16 = last_address;
PRINT_POINTER(scalloc(39,121););
printStats();
void* p17 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p18 = last_address;
PRINT_POINTER(scalloc(37,153););
printStats();
void* p19 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p20 = last_address;
PRINT_POINTER(srealloc(p14,60););
printStats();
void* p21 = last_address;
DEBUG_PRINT(sfree(p21););
printStats();
PRINT_POINTER(smalloc(213););
printStats();
void* p22 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p23 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p24 = last_address;
PRINT_POINTER(smalloc(10););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(184,167););
printStats();
void* p26 = last_address;
PRINT_POINTER(srealloc(p11,197););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
PRINT_POINTER(srealloc(p16,208););
printStats();
void* p28 = last_address;
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(scalloc(52,147););
printStats();
void* p29 = last_address;
PRINT_POINTER(scalloc(4,151););
printStats();
void* p30 = last_address;
PRINT_POINTER(srealloc(p15,160););
printStats();
void* p31 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
PRINT_POINTER(smalloc(237););
printStats();
void* p32 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p33 = last_address;
PRINT_POINTER(scalloc(164,2););
printStats();
void* p34 = last_address;
PRINT_POINTER(srealloc(p17,28););
printStats();
void* p35 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p36 = last_address;
PRINT_POINTER(scalloc(232,14););
printStats();
void* p37 = last_address;
DEBUG_PRINT(sfree(p26););
printStats();
PRINT_POINTER(srealloc(p37,21););
printStats();
void* p38 = last_address;
PRINT_POINTER(scalloc(6,234););
printStats();
void* p39 = last_address;
PRINT_POINTER(srealloc(p32,134););
printStats();
void* p40 = last_address;
PRINT_POINTER(srealloc(p20,190););
printStats();
void* p41 = last_address;
PRINT_POINTER(srealloc(p40,168););
printStats();
void* p42 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
PRINT_POINTER(scalloc(34,146););
printStats();
void* p43 = last_address;
DEBUG_PRINT(sfree(p35););
printStats();
PRINT_POINTER(smalloc(55););
printStats();
void* p44 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p45 = last_address;
DEBUG_PRINT(sfree(p25););
printStats();
DEBUG_PRINT(sfree(p27););
printStats();
PRINT_POINTER(srealloc(p45,195););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p47 = last_address;
PRINT_POINTER(srealloc(p46,185););
printStats();
void* p48 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p49 = last_address;
PRINT_POINTER(srealloc(p24,224););
printStats();
void* p50 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p51 = last_address;
DEBUG_PRINT(sfree(p39););
printStats();
PRINT_POINTER(smalloc(124););
printStats();
void* p52 = last_address;
PRINT_POINTER(srealloc(p48,128););
printStats();
void* p53 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
PRINT_POINTER(srealloc(p13,239););
printStats();
void* p54 = last_address;
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(scalloc(18,75););
printStats();
void* p55 = last_address;
PRINT_POINTER(srealloc(p33,247););
printStats();
void* p56 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p57 = last_address;
PRINT_POINTER(scalloc(104,6););
printStats();
void* p58 = last_address;
DEBUG_PRINT(sfree(p54););
printStats();
PRINT_POINTER(scalloc(30,241););
printStats();
void* p59 = last_address;
PRINT_POINTER(srealloc(p53,231););
printStats();
void* p60 = last_address;
PRINT_POINTER(scalloc(31,43););
printStats();
void* p61 = last_address;
PRINT_POINTER(srealloc(p57,109););
printStats();
void* p62 = last_address;
PRINT_POINTER(srealloc(p19,9););
printStats();
void* p63 = last_address;
PRINT_POINTER(srealloc(p55,117););
printStats();
void* p64 = last_address;
PRINT_POINTER(srealloc(p22,109););
printStats();
void* p65 = last_address;
PRINT_POINTER(srealloc(p64,79););
printStats();
void* p66 = last_address;
PRINT_POINTER(srealloc(p58,30););
printStats();
void* p67 = last_address;
PRINT_POINTER(srealloc(p67,39););
printStats();
void* p68 = last_address;
DEBUG_PRINT(sfree(p50););
printStats();
PRINT_POINTER(srealloc(p68,40););
printStats();
void* p69 = last_address;
DEBUG_PRINT(sfree(p42););
printStats();
DEBUG_PRINT(sfree(p44););
printStats();
PRINT_POINTER(smalloc(130););
printStats();
void* p70 = last_address;
PRINT_POINTER(smalloc(43););
printStats();
void* p71 = last_address;
PRINT_POINTER(scalloc(129,65););
printStats();
void* p72 = last_address;
PRINT_POINTER(srealloc(p71,32););
printStats();
void* p73 = last_address;
PRINT_POINTER(scalloc(169,237););
printStats();
void* p74 = last_address;
PRINT_POINTER(scalloc(206,86););
printStats();
void* p75 = last_address;
PRINT_POINTER(srealloc(p41,161););
printStats();
void* p76 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p77 = last_address;
DEBUG_PRINT(sfree(p65););
printStats();
PRINT_POINTER(smalloc(3););
printStats();
void* p78 = last_address;
DEBUG_PRINT(sfree(p51););
printStats();
DEBUG_PRINT(sfree(p63););
printStats();
DEBUG_PRINT(sfree(p47););
printStats();
PRINT_POINTER(scalloc(183,39););
printStats();
void* p79 = last_address;
PRINT_POINTER(srealloc(p62,65););
printStats();
void* p80 = last_address;
PRINT_POINTER(srealloc(p69,199););
printStats();
void* p81 = last_address;
PRINT_POINTER(scalloc(235,43););
printStats();
void* p82 = last_address;
PRINT_POINTER(srealloc(p72,120););
printStats();
void* p83 = last_address;
DEBUG_PRINT(sfree(p38););
printStats();
DEBUG_PRINT(sfree(p75););
printStats();
PRINT_POINTER(srealloc(p74,156););
printStats();
void* p84 = last_address;
DEBUG_PRINT(sfree(p52););
printStats();
PRINT_POINTER(smalloc(223););
printStats();
void* p85 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p49,118););
printStats();
void* p87 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p88 = last_address;
DEBUG_PRINT(sfree(p56););
printStats();
DEBUG_PRINT(sfree(p84););
printStats();
PRINT_POINTER(srealloc(p61,21););
printStats();
void* p89 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p90 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(smalloc(156););
printStats();
void* p91 = last_address;
PRINT_POINTER(smalloc(144););
printStats();
void* p92 = last_address;
PRINT_POINTER(srealloc(p23,44););
printStats();
void* p93 = last_address;
DEBUG_PRINT(sfree(p91););
printStats();
PRINT_POINTER(scalloc(156,160););
printStats();
void* p94 = last_address;
DEBUG_PRINT(sfree(p92););
printStats();
PRINT_POINTER(scalloc(153,54););
printStats();
void* p95 = last_address;
PRINT_POINTER(scalloc(245,147););
printStats();
void* p96 = last_address;
DEBUG_PRINT(sfree(p89););
printStats();
PRINT_POINTER(smalloc(174););
printStats();
void* p97 = last_address;
PRINT_POINTER(scalloc(133,10););
printStats();
void* p98 = last_address;
PRINT_POINTER(scalloc(126,137););
printStats();
void* p99 = last_address;
PRINT_POINTER(scalloc(239,194););
printStats();
void* p100 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p101 = last_address;
PRINT_POINTER(srealloc(p97,115););
printStats();
void* p102 = last_address;
PRINT_POINTER(srealloc(p82,7););
printStats();
void* p103 = last_address;
PRINT_POINTER(srealloc(p73,178););
printStats();
void* p104 = last_address;
PRINT_POINTER(scalloc(131,24););
printStats();
void* p105 = last_address;
DEBUG_PRINT(sfree(p76););
printStats();
PRINT_POINTER(srealloc(p102,178););
printStats();
void* p106 = last_address;
PRINT_POINTER(srealloc(p77,233););
printStats();
void* p107 = last_address;
PRINT_POINTER(scalloc(129,86););
printStats();
void* p108 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p109 = last_address;
DEBUG_PRINT(sfree(p100););
printStats();
PRINT_POINTER(scalloc(89,229););
printStats();
void* p110 = last_address;
PRINT_POINTER(srealloc(p106,179););
printStats();
void* p111 = last_address;
DEBUG_PRINT(sfree(p105););
printStats();
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(srealloc(p87,140););
printStats();
void* p112 = last_address;
PRINT_POINTER(scalloc(128,99););
printStats();
void* p113 = last_address;
PRINT_POINTER(scalloc(215,108););
printStats();
void* p114 = last_address;
PRINT_POINTER(smalloc(49););
printStats();
void* p115 = last_address;
DEBUG_PRINT(sfree(p103););
printStats();
PRINT_POINTER(srealloc(p79,129););
printStats();
void* p116 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p117 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p118 = last_address;
PRINT_POINTER(scalloc(157,127););
printStats();
void* p119 = last_address;
PRINT_POINTER(scalloc(14,225););
printStats();
void* p120 = last_address;
DEBUG_PRINT(sfree(p104););
printStats();
PRINT_POINTER(srealloc(p88,27););
printStats();
void* p121 = last_address;
PRINT_POINTER(scalloc(234,28););
printStats();
void* p122 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
PRINT_POINTER(srealloc(p110,208););
printStats();
void* p123 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p124 = last_address;
PRINT_POINTER(scalloc(141,209););
printStats();
void* p125 = last_address;
PRINT_POINTER(srealloc(p113,168););
printStats();
void* p126 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p127 = last_address;
PRINT_POINTER(scalloc(131,246););
printStats();
void* p128 = last_address;
PRINT_POINTER(srealloc(p83,120););
printStats();
void* p129 = last_address;
PRINT_POINTER(smalloc(241););
printStats();
void* p130 = last_address;
PRINT_POINTER(scalloc(62,152););
printStats();
void* p131 = last_address;
PRINT_POINTER(srealloc(p125,49););
printStats();
void* p132 = last_address;
PRINT_POINTER(smalloc(11););
printStats();
void* p133 = last_address;
DEBUG_PRINT(sfree(p128););
printStats();
PRINT_POINTER(srealloc(p122,21););
printStats();
void* p134 = last_address;
DEBUG_PRINT(sfree(p114););
printStats();
DEBUG_PRINT(sfree(p133););
printStats();
PRINT_POINTER(srealloc(p131,16););
printStats();
void* p135 = last_address;
PRINT_POINTER(srealloc(p123,102););
printStats();
void* p136 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p137 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p138 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
PRINT_POINTER(srealloc(p120,157););
printStats();
void* p139 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(scalloc(93,55););
printStats();
void* p140 = last_address;
PRINT_POINTER(srealloc(p43,33););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p132,189););
printStats();
void* p142 = last_address;
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(scalloc(74,130););
printStats();
void* p143 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
DEBUG_PRINT(sfree(p127););
printStats();
PRINT_POINTER(srealloc(p66,73););
printStats();
void* p144 = last_address;
PRINT_POINTER(scalloc(210,94););
printStats();
void* p145 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p95););
printStats();
DEBUG_PRINT(sfree(p80););
printStats();
PRINT_POINTER(smalloc(234););
printStats();
void* p147 = last_address;
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(scalloc(48,182););
printStats();
void* p148 = last_address;
PRINT_POINTER(scalloc(130,201););
printStats();
void* p149 = last_address;
PRINT_POINTER(srealloc(p145,5););
printStats();
void* p150 = last_address;
PRINT_POINTER(srealloc(p93,36););
printStats();
void* p151 = last_address;
DEBUG_PRINT(sfree(p143););
printStats();
DEBUG_PRINT(sfree(p86););
printStats();
DEBUG_PRINT(sfree(p30););
printStats();
PRINT_POINTER(smalloc(197););
printStats();
void* p152 = last_address;
DEBUG_PRINT(sfree(p151););
printStats();
PRINT_POINTER(srealloc(p146,125););
printStats();
void* p153 = last_address;
PRINT_POINTER(scalloc(63,76););
printStats();
void* p154 = last_address;
DEBUG_PRINT(sfree(p138););
printStats();
PRINT_POINTER(srealloc(p99,134););
printStats();
void* p155 = last_address;
PRINT_POINTER(scalloc(36,191););
printStats();
void* p156 = last_address;
PRINT_POINTER(scalloc(81,33););
printStats();
void* p157 = last_address;
PRINT_POINTER(srealloc(p129,104););
printStats();
void* p158 = last_address;
PRINT_POINTER(scalloc(53,63););
printStats();
void* p159 = last_address;
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(smalloc(77););
printStats();
void* p160 = last_address;
DEBUG_PRINT(sfree(p108););
printStats();
PRINT_POINTER(smalloc(212););
printStats();
void* p161 = last_address;
PRINT_POINTER(smalloc(228););
printStats();
void* p162 = last_address;
PRINT_POINTER(scalloc(164,222););
printStats();
void* p163 = last_address;
DEBUG_PRINT(sfree(p96););
printStats();
PRINT_POINTER(srealloc(p117,1););
printStats();
void* p164 = last_address;
PRINT_POINTER(scalloc(6,239););
printStats();
void* p165 = last_address;
PRINT_POINTER(srealloc(p137,162););
printStats();
void* p166 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p167 = last_address;
PRINT_POINTER(srealloc(p163,88););
printStats();
void* p168 = last_address;
PRINT_POINTER(scalloc(130,130););
printStats();
void* p169 = last_address;
PRINT_POINTER(scalloc(147,158););
printStats();
void* p170 = last_address;
PRINT_POINTER(srealloc(p112,248););
printStats();
void* p171 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p172 = last_address;
PRINT_POINTER(scalloc(79,104););
printStats();
void* p173 = last_address;
PRINT_POINTER(srealloc(p160,26););
printStats();
void* p174 = last_address;
PRINT_POINTER(scalloc(94,14););
printStats();
void* p175 = last_address;
PRINT_POINTER(smalloc(60););
printStats();
void* p176 = last_address;
PRINT_POINTER(scalloc(26,46););
printStats();
void* p177 = last_address;
PRINT_POINTER(scalloc(65,60););
printStats();
void* p178 = last_address;
PRINT_POINTER(scalloc(44,10););
printStats();
void* p179 = last_address;
PRINT_POINTER(srealloc(p126,123););
printStats();
void* p180 = last_address;
DEBUG_PRINT(sfree(p141););
printStats();
DEBUG_PRINT(sfree(p136););
printStats();
PRINT_POINTER(scalloc(78,85););
printStats();
void* p181 = last_address;
PRINT_POINTER(scalloc(64,241););
printStats();
void* p182 = last_address;
DEBUG_PRINT(sfree(p159););
printStats();
PRINT_POINTER(srealloc(p118,233););
printStats();
void* p183 = last_address;
DEBUG_PRINT(sfree(p81););
printStats();
PRINT_POINTER(scalloc(51,207););
printStats();
void* p184 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p185 = last_address;
PRINT_POINTER(smalloc(104););
printStats();
void* p186 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p187 = last_address;
PRINT_POINTER(scalloc(123,186););
printStats();
void* p188 = last_address;
DEBUG_PRINT(sfree(p59););
printStats();
DEBUG_PRINT(sfree(p124););
printStats();
DEBUG_PRINT(sfree(p167););
printStats();
PRINT_POINTER(smalloc(213););
printStats();
void* p189 = last_address;
DEBUG_PRINT(sfree(p115););
printStats();
PRINT_POINTER(smalloc(179););
printStats();
void* p190 = last_address;
DEBUG_PRINT(sfree(p190););
printStats();
PRINT_POINTER(scalloc(70,151););
printStats();
void* p191 = last_address;
PRINT_POINTER(srealloc(p109,77););
printStats();
void* p192 = last_address;
PRINT_POINTER(srealloc(p130,166););
printStats();
void* p193 = last_address;
PRINT_POINTER(scalloc(109,81););
printStats();
void* p194 = last_address;
DEBUG_PRINT(sfree(p150););
printStats();
PRINT_POINTER(scalloc(50,2););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(srealloc(p162,240););
printStats();
void* p196 = last_address;
DEBUG_PRINT(sfree(p158););
printStats();
DEBUG_PRINT(sfree(p174););
printStats();
DEBUG_PRINT(sfree(p107););
printStats();
PRINT_POINTER(scalloc(65,35););
printStats();
void* p197 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p198 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p199 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p155,45););
printStats();
void* p201 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p202 = last_address;
PRINT_POINTER(scalloc(141,185););
printStats();
void* p203 = last_address;
PRINT_POINTER(scalloc(202,216););
printStats();
void* p204 = last_address;
PRINT_POINTER(scalloc(141,26););
printStats();
void* p205 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p206 = last_address;
PRINT_POINTER(smalloc(136););
printStats();
void* p207 = last_address;
PRINT_POINTER(scalloc(98,51););
printStats();
void* p208 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(srealloc(p175,224););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(57,81););
printStats();
void* p210 = last_address;
DEBUG_PRINT(sfree(p193););
printStats();
PRINT_POINTER(srealloc(p164,169););
printStats();
void* p211 = last_address;
PRINT_POINTER(scalloc(159,165););
printStats();
void* p212 = last_address;
PRINT_POINTER(scalloc(193,157););
printStats();
void* p213 = last_address;
PRINT_POINTER(scalloc(164,81););
printStats();
void* p214 = last_address;
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(srealloc(p195,39););
printStats();
void* p215 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p216 = last_address;
PRINT_POINTER(smalloc(129););
printStats();
void* p217 = last_address;
PRINT_POINTER(smalloc(185););
printStats();
void* p218 = last_address;
PRINT_POINTER(scalloc(200,209););
printStats();
void* p219 = last_address;
PRINT_POINTER(srealloc(p204,192););
printStats();
void* p220 = last_address;
DEBUG_PRINT(sfree(p168););
printStats();
PRINT_POINTER(scalloc(134,23););
printStats();
void* p221 = last_address;
PRINT_POINTER(scalloc(13,222););
printStats();
void* p222 = last_address;
PRINT_POINTER(srealloc(p182,52););
printStats();
void* p223 = last_address;
DEBUG_PRINT(sfree(p207););
printStats();
DEBUG_PRINT(sfree(p119););
printStats();
PRINT_POINTER(srealloc(p185,168););
printStats();
void* p224 = last_address;
PRINT_POINTER(srealloc(p211,51););
printStats();
void* p225 = last_address;
PRINT_POINTER(smalloc(52););
printStats();
void* p226 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p227 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p228 = last_address;
PRINT_POINTER(srealloc(p172,142););
printStats();
void* p229 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
PRINT_POINTER(srealloc(p98,173););
printStats();
void* p230 = last_address;
DEBUG_PRINT(sfree(p161););
printStats();
DEBUG_PRINT(sfree(p209););
printStats();
PRINT_POINTER(srealloc(p201,200););
printStats();
void* p231 = last_address;
PRINT_POINTER(scalloc(134,7););
printStats();
void* p232 = last_address;
PRINT_POINTER(scalloc(186,82););
printStats();
void* p233 = last_address;
PRINT_POINTER(srealloc(p219,73););
printStats();
void* p234 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p235 = last_address;
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(srealloc(p148,83););
printStats();
void* p236 = last_address;
DEBUG_PRINT(sfree(p230););
printStats();
DEBUG_PRINT(sfree(p191););
printStats();
PRINT_POINTER(srealloc(p153,169););
printStats();
void* p237 = last_address;
PRINT_POINTER(smalloc(34););
printStats();
void* p238 = last_address;
DEBUG_PRINT(sfree(p154););
printStats();
PRINT_POINTER(smalloc(76););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p238,233););
printStats();
void* p240 = last_address;
PRINT_POINTER(smalloc(100););
printStats();
void* p241 = last_address;
DEBUG_PRINT(sfree(p217););
printStats();
PRINT_POINTER(smalloc(85););
printStats();
void* p242 = last_address;
PRINT_POINTER(scalloc(25,230););
printStats();
void* p243 = last_address;
PRINT_POINTER(srealloc(p177,159););
printStats();
void* p244 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
PRINT_POINTER(scalloc(1,213););
printStats();
void* p245 = last_address;
DEBUG_PRINT(sfree(p111););
printStats();
DEBUG_PRINT(sfree(p234););
printStats();
PRINT_POINTER(smalloc(67););
printStats();
void* p246 = last_address;
PRINT_POINTER(scalloc(214,206););
printStats();
void* p247 = last_address;
PRINT_POINTER(scalloc(245,42););
printStats();
void* p248 = last_address;
PRINT_POINTER(srealloc(p202,143););
printStats();
void* p249 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p250 = last_address;
DEBUG_PRINT(sfree(p165););
printStats();
DEBUG_PRINT(sfree(p200););
printStats();
PRINT_POINTER(scalloc(108,110););
printStats();
void* p251 = last_address;
PRINT_POINTER(srealloc(p214,238););
printStats();
void* p252 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(scalloc(121,80););
printStats();
void* p253 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p254 = last_address;
PRINT_POINTER(scalloc(177,42););
printStats();
void* p255 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p256 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p257 = last_address;
DEBUG_PRINT(sfree(p179););
printStats();
PRINT_POINTER(smalloc(118););
printStats();
void* p258 = last_address;
DEBUG_PRINT(sfree(p194););
printStats();
PRINT_POINTER(smalloc(175););
printStats();
void* p259 = last_address;
PRINT_POINTER(scalloc(205,209););
printStats();
void* p260 = last_address;
PRINT_POINTER(scalloc(34,99););
printStats();
void* p261 = last_address;
PRINT_POINTER(srealloc(p227,91););
printStats();
void* p262 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p263 = last_address;
PRINT_POINTER(scalloc(92,204););
printStats();
void* p264 = last_address;
PRINT_POINTER(srealloc(p249,164););
printStats();
void* p265 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p266 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p267 = last_address;
PRINT_POINTER(smalloc(7););
printStats();
void* p268 = last_address;
DEBUG_PRINT(sfree(p135););
printStats();
PRINT_POINTER(scalloc(160,12););
printStats();
void* p269 = last_address;
PRINT_POINTER(scalloc(241,198););
printStats();
void* p270 = last_address;
PRINT_POINTER(smalloc(211););
printStats();
void* p271 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p272 = last_address;
PRINT_POINTER(scalloc(162,10););
printStats();
void* p273 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p274 = last_address;
DEBUG_PRINT(sfree(p170););
printStats();
DEBUG_PRINT(sfree(p273););
printStats();
PRINT_POINTER(scalloc(204,48););
printStats();
void* p275 = last_address;
DEBUG_PRINT(sfree(p245););
printStats();
PRINT_POINTER(scalloc(203,228););
printStats();
void* p276 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p277 = last_address;
DEBUG_PRINT(sfree(p223););
printStats();
DEBUG_PRINT(sfree(p140););
printStats();
PRINT_POINTER(scalloc(208,189););
printStats();
void* p278 = last_address;
PRINT_POINTER(srealloc(p184,99););
printStats();
void* p279 = last_address;
PRINT_POINTER(scalloc(103,117););
printStats();
void* p280 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p281 = last_address;
PRINT_POINTER(smalloc(37););
printStats();
void* p282 = last_address;
PRINT_POINTER(srealloc(p116,123););
printStats();
void* p283 = last_address;
PRINT_POINTER(scalloc(182,53););
printStats();
void* p284 = last_address;
PRINT_POINTER(smalloc(96););
printStats();
void* p285 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p286 = last_address;
PRINT_POINTER(srealloc(p225,31););
printStats();
void* p287 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p288 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p289 = last_address;
PRINT_POINTER(scalloc(39,160););
printStats();
void* p290 = last_address;
PRINT_POINTER(srealloc(p270,44););
printStats();
void* p291 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p292 = last_address;
DEBUG_PRINT(sfree(p232););
printStats();
PRINT_POINTER(srealloc(p292,87););
printStats();
void* p293 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p294 = last_address;
PRINT_POINTER(srealloc(p171,49););
printStats();
void* p295 = last_address;
DEBUG_PRINT(sfree(p247););
printStats();
PRINT_POINTER(srealloc(p178,54););
printStats();
void* p296 = last_address;
PRINT_POINTER(srealloc(p262,10););
printStats();
void* p297 = last_address;
PRINT_POINTER(srealloc(p180,48););
printStats();
void* p298 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p299 = last_address;
PRINT_POINTER(scalloc(57,164););
printStats();
void* p300 = last_address;
DEBUG_PRINT(sfree(p157););
printStats();
PRINT_POINTER(scalloc(135,205););
printStats();
void* p301 = last_address;
DEBUG_PRINT(sfree(p239););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p302 = last_address;
DEBUG_PRINT(sfree(p237););
printStats();
PRINT_POINTER(scalloc(215,25););
printStats();
void* p303 = last_address;
DEBUG_PRINT(sfree(p289););
printStats();
PRINT_POINTER(smalloc(238););
printStats();
void* p304 = last_address;
DEBUG_PRINT(sfree(p269););
printStats();
PRINT_POINTER(smalloc(60););
printStats();
void* p305 = last_address;
DEBUG_PRINT(sfree(p296););
printStats();
DEBUG_PRINT(sfree(p279););
printStats();
PRINT_POINTER(scalloc(243,246););
printStats();
void* p306 = last_address;
DEBUG_PRINT(sfree(p196););
printStats();
PRINT_POINTER(smalloc(191););
printStats();
void* p307 = last_address;
PRINT_POINTER(srealloc(p198,172););
printStats();
void* p308 = last_address;
PRINT_POINTER(smalloc(140););
printStats();
void* p309 = last_address;
PRINT_POINTER(scalloc(20,26););
printStats();
void* p310 = last_address;
PRINT_POINTER(srealloc(p228,103););
printStats();
void* p311 = last_address;
PRINT_POINTER(scalloc(66,45););
printStats();
void* p312 = last_address;
PRINT_POINTER(srealloc(p213,84););
printStats();
void* p313 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p314 = last_address;
PRINT_POINTER(scalloc(140,141););
printStats();
void* p315 = last_address;
PRINT_POINTER(srealloc(p189,146););
printStats();
void* p316 = last_address;
PRINT_POINTER(srealloc(p169,91););
printStats();
void* p317 = last_address;
PRINT_POINTER(scalloc(36,235););
printStats();
void* p318 = last_address;
PRINT_POINTER(srealloc(p212,156););
printStats();
void* p319 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p320 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p321 = last_address;
PRINT_POINTER(scalloc(143,222););
printStats();
void* p322 = last_address;
PRINT_POINTER(srealloc(p265,232););
printStats();
void* p323 = last_address;
PRINT_POINTER(srealloc(p275,170););
printStats();
void* p324 = last_address;
PRINT_POINTER(srealloc(p309,186););
printStats();
void* p325 = last_address;
PRINT_POINTER(srealloc(p304,218););
printStats();
void* p326 = last_address;
PRINT_POINTER(srealloc(p220,30););
printStats();
void* p327 = last_address;
PRINT_POINTER(srealloc(p276,114););
printStats();
void* p328 = last_address;
DEBUG_PRINT(sfree(p242););
printStats();
PRINT_POINTER(srealloc(p291,110););
printStats();
void* p329 = last_address;
PRINT_POINTER(scalloc(193,38););
printStats();
void* p330 = last_address;
PRINT_POINTER(srealloc(p139,173););
printStats();
void* p331 = last_address;
PRINT_POINTER(smalloc(131););
printStats();
void* p332 = last_address;
PRINT_POINTER(srealloc(p301,145););
printStats();
void* p333 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p334 = last_address;
PRINT_POINTER(srealloc(p287,6););
printStats();
void* p335 = last_address;
DEBUG_PRINT(sfree(p272););
printStats();
PRINT_POINTER(srealloc(p300,124););
printStats();
void* p336 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p337 = last_address;
PRINT_POINTER(scalloc(105,11););
printStats();
void* p338 = last_address;
PRINT_POINTER(scalloc(159,87););
printStats();
void* p339 = last_address;
PRINT_POINTER(scalloc(67,42););
printStats();
void* p340 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(srealloc(p314,101););
printStats();
void* p341 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p342 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p343 = last_address;
PRINT_POINTER(smalloc(51););
printStats();
void* p344 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p345 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p346 = last_address;
DEBUG_PRINT(sfree(p341););
printStats();
PRINT_POINTER(scalloc(13,200););
printStats();
void* p347 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p348 = last_address;
DEBUG_PRINT(sfree(p235););
printStats();
PRINT_POINTER(smalloc(176););
printStats();
void* p349 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p350 = last_address;
PRINT_POINTER(scalloc(98,44););
printStats();
void* p351 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p352 = last_address;
PRINT_POINTER(scalloc(29,1););
printStats();
void* p353 = last_address;
PRINT_POINTER(smalloc(213););
printStats();
void* p354 = last_address;
PRINT_POINTER(srealloc(p339,235););
printStats();
void* p355 = last_address;
PRINT_POINTER(scalloc(243,93););
printStats();
void* p356 = last_address;
DEBUG_PRINT(sfree(p306););
printStats();
PRINT_POINTER(scalloc(56,247););
printStats();
void* p357 = last_address;
PRINT_POINTER(scalloc(172,229););
printStats();
void* p358 = last_address;
PRINT_POINTER(scalloc(116,243););
printStats();
void* p359 = last_address;
DEBUG_PRINT(sfree(p205););
printStats();
PRINT_POINTER(scalloc(186,175););
printStats();
void* p360 = last_address;
DEBUG_PRINT(sfree(p308););
printStats();
DEBUG_PRINT(sfree(p256););
printStats();
DEBUG_PRINT(sfree(p197););
printStats();
PRINT_POINTER(srealloc(p330,19););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(208););
printStats();
void* p362 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p363 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p364 = last_address;
DEBUG_PRINT(sfree(p144););
printStats();
PRINT_POINTER(srealloc(p255,99););
printStats();
void* p365 = last_address;
PRINT_POINTER(scalloc(248,243););
printStats();
void* p366 = last_address;
DEBUG_PRINT(sfree(p328););
printStats();
PRINT_POINTER(scalloc(167,244););
printStats();
void* p367 = last_address;
PRINT_POINTER(scalloc(53,222););
printStats();
void* p368 = last_address;
DEBUG_PRINT(sfree(p215););
printStats();
DEBUG_PRINT(sfree(p183););
printStats();
PRINT_POINTER(scalloc(146,163););
printStats();
void* p369 = last_address;
PRINT_POINTER(scalloc(209,224););
printStats();
void* p370 = last_address;
PRINT_POINTER(srealloc(p229,234););
printStats();
void* p371 = last_address;
PRINT_POINTER(srealloc(p319,24););
printStats();
void* p372 = last_address;
PRINT_POINTER(scalloc(151,36););
printStats();
void* p373 = last_address;
DEBUG_PRINT(sfree(p312););
printStats();
PRINT_POINTER(smalloc(87););
printStats();
void* p374 = last_address;
PRINT_POINTER(scalloc(206,155););
printStats();
void* p375 = last_address;
DEBUG_PRINT(sfree(p324););
printStats();
PRINT_POINTER(srealloc(p288,183););
printStats();
void* p376 = last_address;
PRINT_POINTER(scalloc(216,39););
printStats();
void* p377 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p378 = last_address;
DEBUG_PRINT(sfree(p226););
printStats();
PRINT_POINTER(srealloc(p254,88););
printStats();
void* p379 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p380 = last_address;
PRINT_POINTER(scalloc(222,211););
printStats();
void* p381 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p382 = last_address;
PRINT_POINTER(smalloc(40););
printStats();
void* p383 = last_address;
PRINT_POINTER(scalloc(92,72););
printStats();
void* p384 = last_address;
PRINT_POINTER(scalloc(87,176););
printStats();
void* p385 = last_address;
DEBUG_PRINT(sfree(p337););
printStats();
PRINT_POINTER(smalloc(181););
printStats();
void* p386 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
PRINT_POINTER(srealloc(p295,40););
printStats();
void* p387 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p388 = last_address;
DEBUG_PRINT(sfree(p316););
printStats();
PRINT_POINTER(srealloc(p251,30););
printStats();
void* p389 = last_address;
PRINT_POINTER(smalloc(227););
printStats();
void* p390 = last_address;
PRINT_POINTER(srealloc(p297,151););
printStats();
void* p391 = last_address;
DEBUG_PRINT(sfree(p293););
printStats();
DEBUG_PRINT(sfree(p336););
printStats();
PRINT_POINTER(scalloc(126,130););
printStats();
void* p392 = last_address;
PRINT_POINTER(smalloc(91););
printStats();
void* p393 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p394 = last_address;
DEBUG_PRINT(sfree(p290););
printStats();
PRINT_POINTER(smalloc(65););
printStats();
void* p395 = last_address;
DEBUG_PRINT(sfree(p368););
printStats();
PRINT_POINTER(scalloc(78,98););
printStats();
void* p396 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p397 = last_address;
PRINT_POINTER(srealloc(p338,64););
printStats();
void* p398 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(scalloc(94,194););
printStats();
void* p399 = last_address;
DEBUG_PRINT(sfree(p221););
printStats();
DEBUG_PRINT(sfree(p264););
printStats();
PRINT_POINTER(smalloc(34););
printStats();
void* p400 = last_address;
PRINT_POINTER(scalloc(133,55););
printStats();
void* p401 = last_address;
PRINT_POINTER(scalloc(199,47););
printStats();
void* p402 = last_address;
PRINT_POINTER(srealloc(p398,30););
printStats();
void* p403 = last_address;
PRINT_POINTER(scalloc(233,54););
printStats();
void* p404 = last_address;
PRINT_POINTER(scalloc(109,56););
printStats();
void* p405 = last_address;
PRINT_POINTER(smalloc(143););
printStats();
void* p406 = last_address;
PRINT_POINTER(srealloc(p366,104););
printStats();
void* p407 = last_address;
PRINT_POINTER(scalloc(132,3););
printStats();
void* p408 = last_address;
PRINT_POINTER(srealloc(p369,22););
printStats();
void* p409 = last_address;
PRINT_POINTER(srealloc(p378,216););
printStats();
void* p410 = last_address;
PRINT_POINTER(scalloc(79,3););
printStats();
void* p411 = last_address;
PRINT_POINTER(srealloc(p359,34););
printStats();
void* p412 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(srealloc(p344,120););
printStats();
void* p413 = last_address;
DEBUG_PRINT(sfree(p282););
printStats();
DEBUG_PRINT(sfree(p224););
printStats();
PRINT_POINTER(smalloc(19););
printStats();
void* p414 = last_address;
DEBUG_PRINT(sfree(p407););
printStats();
PRINT_POINTER(srealloc(p405,131););
printStats();
void* p415 = last_address;
PRINT_POINTER(scalloc(134,206););
printStats();
void* p416 = last_address;
DEBUG_PRINT(sfree(p387););
printStats();
PRINT_POINTER(srealloc(p364,173););
printStats();
void* p417 = last_address;
PRINT_POINTER(srealloc(p347,239););
printStats();
void* p418 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p419 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p420 = last_address;
PRINT_POINTER(srealloc(p367,74););
printStats();
void* p421 = last_address;
PRINT_POINTER(scalloc(209,235););
printStats();
void* p422 = last_address;
DEBUG_PRINT(sfree(p267););
printStats();
PRINT_POINTER(srealloc(p187,188););
printStats();
void* p423 = last_address;
DEBUG_PRINT(sfree(p349););
printStats();
PRINT_POINTER(srealloc(p241,175););
printStats();
void* p424 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p425 = last_address;
PRINT_POINTER(srealloc(p415,118););
printStats();
void* p426 = last_address;
DEBUG_PRINT(sfree(p403););
printStats();
PRINT_POINTER(scalloc(64,126););
printStats();
void* p427 = last_address;
DEBUG_PRINT(sfree(p401););
printStats();
DEBUG_PRINT(sfree(p410););
printStats();
PRINT_POINTER(smalloc(232););
printStats();
void* p428 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p429 = last_address;
PRINT_POINTER(srealloc(p302,161););
printStats();
void* p430 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p431 = last_address;
PRINT_POINTER(srealloc(p327,76););
printStats();
void* p432 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p433 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p434 = last_address;
PRINT_POINTER(smalloc(15););
printStats();
void* p435 = last_address;
PRINT_POINTER(srealloc(p413,184););
printStats();
void* p436 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p437 = last_address;
PRINT_POINTER(smalloc(111););
printStats();
void* p438 = last_address;
PRINT_POINTER(srealloc(p409,240););
printStats();
void* p439 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p440 = last_address;
PRINT_POINTER(smalloc(35););
printStats();
void* p441 = last_address;
PRINT_POINTER(scalloc(176,213););
printStats();
void* p442 = last_address;
DEBUG_PRINT(sfree(p426););
printStats();
PRINT_POINTER(scalloc(28,201););
printStats();
void* p443 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p444 = last_address;
DEBUG_PRINT(sfree(p258););
printStats();
PRINT_POINTER(srealloc(p260,147););
printStats();
void* p445 = last_address;
PRINT_POINTER(smalloc(70););
printStats();
void* p446 = last_address;
PRINT_POINTER(srealloc(p329,219););
printStats();
void* p447 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p448 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p449 = last_address;
DEBUG_PRINT(sfree(p432););
printStats();
PRINT_POINTER(srealloc(p418,125););
printStats();
void* p450 = last_address;
PRINT_POINTER(srealloc(p438,191););
printStats();
void* p451 = last_address;
PRINT_POINTER(srealloc(p303,3););
printStats();
void* p452 = last_address;
PRINT_POINTER(srealloc(p439,56););
printStats();
void* p453 = last_address;
PRINT_POINTER(srealloc(p397,237););
printStats();
void* p454 = last_address;
DEBUG_PRINT(sfree(p419););
printStats();
PRINT_POINTER(srealloc(p321,234););
printStats();
void* p455 = last_address;
PRINT_POINTER(srealloc(p305,34););
printStats();
void* p456 = last_address;
PRINT_POINTER(srealloc(p394,133););
printStats();
void* p457 = last_address;
DEBUG_PRINT(sfree(p246););
printStats();
DEBUG_PRINT(sfree(p277););
printStats();
PRINT_POINTER(srealloc(p433,249););
printStats();
void* p458 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p459 = last_address;
PRINT_POINTER(scalloc(75,92););
printStats();
void* p460 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p461 = last_address;
PRINT_POINTER(srealloc(p285,38););
printStats();
void* p462 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p463 = last_address;
PRINT_POINTER(smalloc(233););
printStats();
void* p464 = last_address;
PRINT_POINTER(srealloc(p454,115););
printStats();
void* p465 = last_address;
PRINT_POINTER(scalloc(131,167););
printStats();
void* p466 = last_address;
DEBUG_PRINT(sfree(p298););
printStats();
PRINT_POINTER(scalloc(164,193););
printStats();
void* p467 = last_address;
PRINT_POINTER(smalloc(94););
printStats();
void* p468 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
PRINT_POINTER(scalloc(204,243););
printStats();
void* p469 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p470 = last_address;
PRINT_POINTER(srealloc(p463,157););
printStats();
void* p471 = last_address;
PRINT_POINTER(scalloc(104,102););
printStats();
void* p472 = last_address;
PRINT_POINTER(scalloc(86,102););
printStats();
void* p473 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p474 = last_address;
PRINT_POINTER(srealloc(p399,150););
printStats();
void* p475 = last_address;
PRINT_POINTER(scalloc(50,109););
printStats();
void* p476 = last_address;
DEBUG_PRINT(sfree(p192););
printStats();
PRINT_POINTER(smalloc(27););
printStats();
void* p477 = last_address;
DEBUG_PRINT(sfree(p350););
printStats();
PRINT_POINTER(srealloc(p383,90););
printStats();
void* p478 = last_address;
DEBUG_PRINT(sfree(p315););
printStats();
PRINT_POINTER(smalloc(213););
printStats();
void* p479 = last_address;
PRINT_POINTER(scalloc(18,25););
printStats();
void* p480 = last_address;
DEBUG_PRINT(sfree(p294););
printStats();
PRINT_POINTER(srealloc(p332,245););
printStats();
void* p481 = last_address;
DEBUG_PRINT(sfree(p248););
printStats();
PRINT_POINTER(scalloc(135,207););
printStats();
void* p482 = last_address;
PRINT_POINTER(scalloc(142,52););
printStats();
void* p483 = last_address;
PRINT_POINTER(scalloc(194,129););
printStats();
void* p484 = last_address;
PRINT_POINTER(smalloc(235););
printStats();
void* p485 = last_address;
DEBUG_PRINT(sfree(p475););
printStats();
DEBUG_PRINT(sfree(p253););
printStats();
DEBUG_PRINT(sfree(p404););
printStats();
DEBUG_PRINT(sfree(p478););
printStats();
PRINT_POINTER(smalloc(145););
printStats();
void* p486 = last_address;
PRINT_POINTER(smalloc(50););
printStats();
void* p487 = last_address;
PRINT_POINTER(srealloc(p451,3););
printStats();
void* p488 = last_address;
PRINT_POINTER(scalloc(198,96););
printStats();
void* p489 = last_address;
PRINT_POINTER(srealloc(p473,113););
printStats();
void* p490 = last_address;
DEBUG_PRINT(sfree(p479););
printStats();
DEBUG_PRINT(sfree(p402););
printStats();
DEBUG_PRINT(sfree(p244););
printStats();
PRINT_POINTER(smalloc(79););
printStats();
void* p491 = last_address;
DEBUG_PRINT(sfree(p208););
printStats();
PRINT_POINTER(srealloc(p474,227););
printStats();
void* p492 = last_address;
PRINT_POINTER(scalloc(35,51););
printStats();
void* p493 = last_address;
PRINT_POINTER(srealloc(p331,35););
printStats();
void* p494 = last_address;
PRINT_POINTER(scalloc(7,209););
printStats();
void* p495 = last_address;
PRINT_POINTER(srealloc(p362,85););
printStats();
void* p496 = last_address;
PRINT_POINTER(scalloc(118,138););
printStats();
void* p497 = last_address;
DEBUG_PRINT(sfree(p421););
printStats();
PRINT_POINTER(scalloc(237,84););
printStats();
void* p498 = last_address;
PRINT_POINTER(scalloc(235,1););
printStats();
void* p499 = last_address;
PRINT_POINTER(smalloc(137););
printStats();
void* p500 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p501 = last_address;
DEBUG_PRINT(sfree(p431););
printStats();
PRINT_POINTER(smalloc(132););
printStats();
void* p502 = last_address;
PRINT_POINTER(scalloc(73,161););
printStats();
void* p503 = last_address;
PRINT_POINTER(scalloc(217,63););
printStats();
void* p504 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p505 = last_address;
PRINT_POINTER(scalloc(144,105););
printStats();
void* p506 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p507 = last_address;
PRINT_POINTER(scalloc(57,164););
printStats();
void* p508 = last_address;
PRINT_POINTER(srealloc(p414,141););
printStats();
void* p509 = last_address;
PRINT_POINTER(scalloc(165,197););
printStats();
void* p510 = last_address;
PRINT_POINTER(srealloc(p381,114););
printStats();
void* p511 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p512 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p513 = last_address;
PRINT_POINTER(srealloc(p389,99););
printStats();
void* p514 = last_address;
DEBUG_PRINT(sfree(p121););
printStats();
PRINT_POINTER(smalloc(11););
printStats();
void* p515 = last_address;
PRINT_POINTER(srealloc(p252,170););
printStats();
void* p516 = last_address;
PRINT_POINTER(scalloc(127,67););
printStats();
void* p517 = last_address;
PRINT_POINTER(srealloc(p472,15););
printStats();
void* p518 = last_address;
DEBUG_PRINT(sfree(p444););
printStats();
PRINT_POINTER(srealloc(p357,92););
printStats();
void* p519 = last_address;
DEBUG_PRINT(sfree(p370););
printStats();
PRINT_POINTER(smalloc(177););
printStats();
void* p520 = last_address;
DEBUG_PRINT(sfree(p412););
printStats();
PRINT_POINTER(srealloc(p325,233););
printStats();
void* p521 = last_address;
PRINT_POINTER(srealloc(p286,231););
printStats();
void* p522 = last_address;
DEBUG_PRINT(sfree(p482););
printStats();
PRINT_POINTER(smalloc(6););
printStats();
void* p523 = last_address;
PRINT_POINTER(scalloc(97,73););
printStats();
void* p524 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p525 = last_address;
PRINT_POINTER(srealloc(p501,17););
printStats();
void* p526 = last_address;
DEBUG_PRINT(sfree(p385););
printStats();
PRINT_POINTER(scalloc(202,90););
printStats();
void* p527 = last_address;
PRINT_POINTER(srealloc(p430,93););
printStats();
void* p528 = last_address;
DEBUG_PRINT(sfree(p506););
printStats();
DEBUG_PRINT(sfree(p266););
printStats();
PRINT_POINTER(scalloc(11,34););
printStats();
void* p529 = last_address;
PRINT_POINTER(srealloc(p365,102););
printStats();
void* p530 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p531 = last_address;
PRINT_POINTER(scalloc(146,96););
printStats();
void* p532 = last_address;
DEBUG_PRINT(sfree(p460););
printStats();
PRINT_POINTER(smalloc(96););
printStats();
void* p533 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p534 = last_address;
PRINT_POINTER(smalloc(85););
printStats();
void* p535 = last_address;
PRINT_POINTER(scalloc(122,249););
printStats();
void* p536 = last_address;
DEBUG_PRINT(sfree(p425););
printStats();
PRINT_POINTER(smalloc(229););
printStats();
void* p537 = last_address;
DEBUG_PRINT(sfree(p352););
printStats();
PRINT_POINTER(smalloc(196););
printStats();
void* p538 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p539 = last_address;
DEBUG_PRINT(sfree(p166););
printStats();
PRINT_POINTER(srealloc(p384,63););
printStats();
void* p540 = last_address;
PRINT_POINTER(srealloc(p517,154););
printStats();
void* p541 = last_address;
PRINT_POINTER(scalloc(226,182););
printStats();
void* p542 = last_address;
PRINT_POINTER(scalloc(1,125););
printStats();
void* p543 = last_address;
PRINT_POINTER(smalloc(81););
printStats();
void* p544 = last_address;
PRINT_POINTER(scalloc(74,238););
printStats();
void* p545 = last_address;
PRINT_POINTER(srealloc(p448,139););
printStats();
void* p546 = last_address;
PRINT_POINTER(srealloc(p380,50););
printStats();
void* p547 = last_address;
PRINT_POINTER(srealloc(p408,100););
printStats();
void* p548 = last_address;
PRINT_POINTER(srealloc(p529,183););
printStats();
void* p549 = last_address;
PRINT_POINTER(srealloc(p445,92););
printStats();
void* p550 = last_address;
DEBUG_PRINT(sfree(p471););
printStats();
PRINT_POINTER(scalloc(7,242););
printStats();
void* p551 = last_address;
PRINT_POINTER(srealloc(p356,180););
printStats();
void* p552 = last_address;
DEBUG_PRINT(sfree(p467););
printStats();
PRINT_POINTER(scalloc(139,117););
printStats();
void* p553 = last_address;
PRINT_POINTER(srealloc(p504,133););
printStats();
void* p554 = last_address;
DEBUG_PRINT(sfree(p540););
printStats();
DEBUG_PRINT(sfree(p396););
printStats();
PRINT_POINTER(scalloc(88,99););
printStats();
void* p555 = last_address;
PRINT_POINTER(scalloc(38,148););
printStats();
void* p556 = last_address;
PRINT_POINTER(scalloc(116,17););
printStats();
void* p557 = last_address;
PRINT_POINTER(srealloc(p318,44););
printStats();
void* p558 = last_address;
DEBUG_PRINT(sfree(p488););
printStats();
PRINT_POINTER(srealloc(p465,244););
printStats();
void* p559 = last_address;
PRINT_POINTER(scalloc(81,52););
printStats();
void* p560 = last_address;
PRINT_POINTER(scalloc(201,169););
printStats();
void* p561 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p562 = last_address;
PRINT_POINTER(srealloc(p333,171););
printStats();
void* p563 = last_address;
PRINT_POINTER(srealloc(p156,226););
printStats();
void* p564 = last_address;
DEBUG_PRINT(sfree(p511););
printStats();
PRINT_POINTER(smalloc(220););
printStats();
void* p565 = last_address;
PRINT_POINTER(scalloc(53,246););
printStats();
void* p566 = last_address;
DEBUG_PRINT(sfree(p420););
printStats();
PRINT_POINTER(scalloc(200,163););
printStats();
void* p567 = last_address;
PRINT_POINTER(scalloc(102,21););
printStats();
void* p568 = last_address;
DEBUG_PRINT(sfree(p537););
printStats();
PRINT_POINTER(smalloc(43););
printStats();
void* p569 = last_address;
PRINT_POINTER(srealloc(p516,147););
printStats();
void* p570 = last_address;
PRINT_POINTER(srealloc(p559,170););
printStats();
void* p571 = last_address;
PRINT_POINTER(srealloc(p411,72););
printStats();
void* p572 = last_address;
PRINT_POINTER(srealloc(p434,148););
printStats();
void* p573 = last_address;
DEBUG_PRINT(sfree(p236););
printStats();
PRINT_POINTER(srealloc(p416,115););
printStats();
void* p574 = last_address;
PRINT_POINTER(srealloc(p526,39););
printStats();
void* p575 = last_address;
PRINT_POINTER(scalloc(248,94););
printStats();
void* p576 = last_address;
DEBUG_PRINT(sfree(p527););
printStats();
PRINT_POINTER(srealloc(p317,76););
printStats();
void* p577 = last_address;
PRINT_POINTER(srealloc(p574,216););
printStats();
void* p578 = last_address;
PRINT_POINTER(scalloc(156,122););
printStats();
void* p579 = last_address;
PRINT_POINTER(scalloc(45,56););
printStats();
void* p580 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p581 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p582 = last_address;
DEBUG_PRINT(sfree(p519););
printStats();
PRINT_POINTER(scalloc(242,217););
printStats();
void* p583 = last_address;
PRINT_POINTER(smalloc(150););
printStats();
void* p584 = last_address;
DEBUG_PRINT(sfree(p240););
printStats();
PRINT_POINTER(srealloc(p299,19););
printStats();
void* p585 = last_address;
DEBUG_PRINT(sfree(p551););
printStats();
PRINT_POINTER(srealloc(p423,159););
printStats();
void* p586 = last_address;
DEBUG_PRINT(sfree(p391););
printStats();
PRINT_POINTER(srealloc(p436,184););
printStats();
void* p587 = last_address;
PRINT_POINTER(scalloc(161,13););
printStats();
void* p588 = last_address;
}
