#include "aux_macro.h"
#include "../malloc_3.cpp"
#include <iostream>

void printStats()
                    {
                        std::cout << "_num_free_blocks: " << _num_free_blocks() << std::endl;
                        std::cout << "_num_free_bytes: " << _num_free_bytes() << std::endl;
                        std::cout << "_num_allocated_blocks: " << _num_allocated_blocks() << std::endl;
                        std::cout << "_num_allocated_bytes: " << _num_allocated_bytes() << std::endl;
                        std::cout << "_num_meta_data_bytes: " << _num_meta_data_bytes() << std::endl;
                        std::cout << "_size_meta_data: " << _size_meta_data() << std::endl;
                    }
                    int main()
                    {
                        PRINT_POINTER(smalloc(35););
printStats();
void* p0 = last_address;
DEBUG_PRINT(sfree(p0););
printStats();
PRINT_POINTER(scalloc(76,144););
printStats();
void* p1 = last_address;
DEBUG_PRINT(sfree(p1););
printStats();
PRINT_POINTER(smalloc(242););
printStats();
void* p2 = last_address;
PRINT_POINTER(smalloc(108););
printStats();
void* p3 = last_address;
PRINT_POINTER(srealloc(p2,243););
printStats();
void* p4 = last_address;
PRINT_POINTER(srealloc(p3,177););
printStats();
void* p5 = last_address;
PRINT_POINTER(scalloc(157,116););
printStats();
void* p6 = last_address;
DEBUG_PRINT(sfree(p5););
printStats();
PRINT_POINTER(srealloc(p6,2););
printStats();
void* p7 = last_address;
DEBUG_PRINT(sfree(p7););
printStats();
PRINT_POINTER(scalloc(125,172););
printStats();
void* p8 = last_address;
DEBUG_PRINT(sfree(p8););
printStats();
PRINT_POINTER(srealloc(p4,224););
printStats();
void* p9 = last_address;
DEBUG_PRINT(sfree(p9););
printStats();
PRINT_POINTER(smalloc(116););
printStats();
void* p10 = last_address;
PRINT_POINTER(scalloc(127,69););
printStats();
void* p11 = last_address;
PRINT_POINTER(srealloc(p10,244););
printStats();
void* p12 = last_address;
PRINT_POINTER(smalloc(193););
printStats();
void* p13 = last_address;
DEBUG_PRINT(sfree(p12););
printStats();
PRINT_POINTER(srealloc(p11,93););
printStats();
void* p14 = last_address;
DEBUG_PRINT(sfree(p14););
printStats();
PRINT_POINTER(smalloc(78););
printStats();
void* p15 = last_address;
PRINT_POINTER(scalloc(78,74););
printStats();
void* p16 = last_address;
PRINT_POINTER(srealloc(p13,123););
printStats();
void* p17 = last_address;
DEBUG_PRINT(sfree(p15););
printStats();
PRINT_POINTER(scalloc(174,11););
printStats();
void* p18 = last_address;
DEBUG_PRINT(sfree(p16););
printStats();
PRINT_POINTER(srealloc(p17,53););
printStats();
void* p19 = last_address;
DEBUG_PRINT(sfree(p18););
printStats();
DEBUG_PRINT(sfree(p19););
printStats();
PRINT_POINTER(scalloc(64,176););
printStats();
void* p20 = last_address;
DEBUG_PRINT(sfree(p20););
printStats();
PRINT_POINTER(scalloc(180,196););
printStats();
void* p21 = last_address;
PRINT_POINTER(srealloc(p21,188););
printStats();
void* p22 = last_address;
DEBUG_PRINT(sfree(p22););
printStats();
PRINT_POINTER(scalloc(101,147););
printStats();
void* p23 = last_address;
PRINT_POINTER(smalloc(207););
printStats();
void* p24 = last_address;
PRINT_POINTER(scalloc(4,97););
printStats();
void* p25 = last_address;
PRINT_POINTER(scalloc(29,70););
printStats();
void* p26 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p27 = last_address;
DEBUG_PRINT(sfree(p27););
printStats();
PRINT_POINTER(scalloc(243,116););
printStats();
void* p28 = last_address;
DEBUG_PRINT(sfree(p26););
printStats();
PRINT_POINTER(scalloc(85,53););
printStats();
void* p29 = last_address;
PRINT_POINTER(srealloc(p25,116););
printStats();
void* p30 = last_address;
PRINT_POINTER(scalloc(193,25););
printStats();
void* p31 = last_address;
DEBUG_PRINT(sfree(p31););
printStats();
DEBUG_PRINT(sfree(p23););
printStats();
PRINT_POINTER(scalloc(122,56););
printStats();
void* p32 = last_address;
PRINT_POINTER(srealloc(p24,19););
printStats();
void* p33 = last_address;
DEBUG_PRINT(sfree(p33););
printStats();
PRINT_POINTER(scalloc(153,35););
printStats();
void* p34 = last_address;
PRINT_POINTER(scalloc(192,51););
printStats();
void* p35 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p36 = last_address;
PRINT_POINTER(scalloc(132,227););
printStats();
void* p37 = last_address;
DEBUG_PRINT(sfree(p29););
printStats();
DEBUG_PRINT(sfree(p30););
printStats();
PRINT_POINTER(smalloc(245););
printStats();
void* p38 = last_address;
DEBUG_PRINT(sfree(p34););
printStats();
PRINT_POINTER(smalloc(60););
printStats();
void* p39 = last_address;
PRINT_POINTER(scalloc(144,39););
printStats();
void* p40 = last_address;
PRINT_POINTER(scalloc(235,133););
printStats();
void* p41 = last_address;
PRINT_POINTER(scalloc(186,188););
printStats();
void* p42 = last_address;
DEBUG_PRINT(sfree(p36););
printStats();
DEBUG_PRINT(sfree(p40););
printStats();
PRINT_POINTER(smalloc(181););
printStats();
void* p43 = last_address;
PRINT_POINTER(smalloc(46););
printStats();
void* p44 = last_address;
PRINT_POINTER(srealloc(p35,26););
printStats();
void* p45 = last_address;
PRINT_POINTER(smalloc(189););
printStats();
void* p46 = last_address;
PRINT_POINTER(smalloc(12););
printStats();
void* p47 = last_address;
PRINT_POINTER(smalloc(232););
printStats();
void* p48 = last_address;
PRINT_POINTER(srealloc(p38,8););
printStats();
void* p49 = last_address;
PRINT_POINTER(srealloc(p39,178););
printStats();
void* p50 = last_address;
DEBUG_PRINT(sfree(p47););
printStats();
PRINT_POINTER(smalloc(9););
printStats();
void* p51 = last_address;
DEBUG_PRINT(sfree(p32););
printStats();
DEBUG_PRINT(sfree(p48););
printStats();
DEBUG_PRINT(sfree(p28););
printStats();
PRINT_POINTER(srealloc(p45,130););
printStats();
void* p52 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p53 = last_address;
PRINT_POINTER(srealloc(p46,29););
printStats();
void* p54 = last_address;
DEBUG_PRINT(sfree(p41););
printStats();
PRINT_POINTER(smalloc(229););
printStats();
void* p55 = last_address;
PRINT_POINTER(smalloc(132););
printStats();
void* p56 = last_address;
PRINT_POINTER(scalloc(27,84););
printStats();
void* p57 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p58 = last_address;
PRINT_POINTER(smalloc(178););
printStats();
void* p59 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p60 = last_address;
PRINT_POINTER(srealloc(p42,5););
printStats();
void* p61 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p62 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p63 = last_address;
DEBUG_PRINT(sfree(p56););
printStats();
PRINT_POINTER(smalloc(5););
printStats();
void* p64 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p65 = last_address;
PRINT_POINTER(srealloc(p65,106););
printStats();
void* p66 = last_address;
DEBUG_PRINT(sfree(p60););
printStats();
DEBUG_PRINT(sfree(p64););
printStats();
PRINT_POINTER(smalloc(151););
printStats();
void* p67 = last_address;
DEBUG_PRINT(sfree(p54););
printStats();
PRINT_POINTER(scalloc(176,218););
printStats();
void* p68 = last_address;
PRINT_POINTER(srealloc(p63,170););
printStats();
void* p69 = last_address;
DEBUG_PRINT(sfree(p51););
printStats();
PRINT_POINTER(srealloc(p67,210););
printStats();
void* p70 = last_address;
DEBUG_PRINT(sfree(p57););
printStats();
PRINT_POINTER(srealloc(p68,7););
printStats();
void* p71 = last_address;
PRINT_POINTER(srealloc(p50,130););
printStats();
void* p72 = last_address;
PRINT_POINTER(srealloc(p49,90););
printStats();
void* p73 = last_address;
PRINT_POINTER(srealloc(p62,87););
printStats();
void* p74 = last_address;
PRINT_POINTER(srealloc(p44,77););
printStats();
void* p75 = last_address;
DEBUG_PRINT(sfree(p52););
printStats();
PRINT_POINTER(srealloc(p43,28););
printStats();
void* p76 = last_address;
PRINT_POINTER(srealloc(p72,245););
printStats();
void* p77 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p78 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p79 = last_address;
PRINT_POINTER(scalloc(184,156););
printStats();
void* p80 = last_address;
DEBUG_PRINT(sfree(p75););
printStats();
PRINT_POINTER(smalloc(236););
printStats();
void* p81 = last_address;
PRINT_POINTER(scalloc(222,221););
printStats();
void* p82 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p83 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p84 = last_address;
PRINT_POINTER(scalloc(31,11););
printStats();
void* p85 = last_address;
PRINT_POINTER(scalloc(99,57););
printStats();
void* p86 = last_address;
PRINT_POINTER(srealloc(p76,122););
printStats();
void* p87 = last_address;
PRINT_POINTER(scalloc(80,192););
printStats();
void* p88 = last_address;
DEBUG_PRINT(sfree(p87););
printStats();
DEBUG_PRINT(sfree(p84););
printStats();
DEBUG_PRINT(sfree(p69););
printStats();
PRINT_POINTER(scalloc(155,76););
printStats();
void* p89 = last_address;
PRINT_POINTER(scalloc(184,215););
printStats();
void* p90 = last_address;
DEBUG_PRINT(sfree(p70););
printStats();
PRINT_POINTER(srealloc(p88,104););
printStats();
void* p91 = last_address;
DEBUG_PRINT(sfree(p90););
printStats();
PRINT_POINTER(srealloc(p91,213););
printStats();
void* p92 = last_address;
PRINT_POINTER(scalloc(137,233););
printStats();
void* p93 = last_address;
DEBUG_PRINT(sfree(p93););
printStats();
DEBUG_PRINT(sfree(p73););
printStats();
DEBUG_PRINT(sfree(p59););
printStats();
PRINT_POINTER(smalloc(118););
printStats();
void* p94 = last_address;
DEBUG_PRINT(sfree(p61););
printStats();
PRINT_POINTER(smalloc(101););
printStats();
void* p95 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p96 = last_address;
DEBUG_PRINT(sfree(p83););
printStats();
PRINT_POINTER(scalloc(238,206););
printStats();
void* p97 = last_address;
PRINT_POINTER(scalloc(46,98););
printStats();
void* p98 = last_address;
PRINT_POINTER(smalloc(147););
printStats();
void* p99 = last_address;
PRINT_POINTER(srealloc(p55,143););
printStats();
void* p100 = last_address;
PRINT_POINTER(scalloc(163,194););
printStats();
void* p101 = last_address;
DEBUG_PRINT(sfree(p94););
printStats();
PRINT_POINTER(scalloc(228,222););
printStats();
void* p102 = last_address;
PRINT_POINTER(scalloc(116,57););
printStats();
void* p103 = last_address;
PRINT_POINTER(scalloc(52,127););
printStats();
void* p104 = last_address;
PRINT_POINTER(scalloc(244,24););
printStats();
void* p105 = last_address;
PRINT_POINTER(srealloc(p86,94););
printStats();
void* p106 = last_address;
DEBUG_PRINT(sfree(p37););
printStats();
PRINT_POINTER(smalloc(132););
printStats();
void* p107 = last_address;
DEBUG_PRINT(sfree(p85););
printStats();
PRINT_POINTER(smalloc(187););
printStats();
void* p108 = last_address;
PRINT_POINTER(srealloc(p105,48););
printStats();
void* p109 = last_address;
DEBUG_PRINT(sfree(p101););
printStats();
PRINT_POINTER(srealloc(p102,204););
printStats();
void* p110 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p111 = last_address;
PRINT_POINTER(scalloc(21,32););
printStats();
void* p112 = last_address;
PRINT_POINTER(smalloc(128););
printStats();
void* p113 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p114 = last_address;
PRINT_POINTER(srealloc(p100,219););
printStats();
void* p115 = last_address;
DEBUG_PRINT(sfree(p92););
printStats();
DEBUG_PRINT(sfree(p114););
printStats();
PRINT_POINTER(smalloc(183););
printStats();
void* p116 = last_address;
PRINT_POINTER(srealloc(p95,153););
printStats();
void* p117 = last_address;
PRINT_POINTER(smalloc(19););
printStats();
void* p118 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p119 = last_address;
PRINT_POINTER(smalloc(89););
printStats();
void* p120 = last_address;
PRINT_POINTER(scalloc(68,114););
printStats();
void* p121 = last_address;
PRINT_POINTER(srealloc(p104,190););
printStats();
void* p122 = last_address;
PRINT_POINTER(srealloc(p117,216););
printStats();
void* p123 = last_address;
PRINT_POINTER(scalloc(100,61););
printStats();
void* p124 = last_address;
PRINT_POINTER(srealloc(p106,219););
printStats();
void* p125 = last_address;
PRINT_POINTER(scalloc(100,205););
printStats();
void* p126 = last_address;
PRINT_POINTER(scalloc(238,28););
printStats();
void* p127 = last_address;
DEBUG_PRINT(sfree(p80););
printStats();
PRINT_POINTER(srealloc(p53,235););
printStats();
void* p128 = last_address;
PRINT_POINTER(scalloc(50,222););
printStats();
void* p129 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p130 = last_address;
DEBUG_PRINT(sfree(p129););
printStats();
DEBUG_PRINT(sfree(p58););
printStats();
DEBUG_PRINT(sfree(p121););
printStats();
DEBUG_PRINT(sfree(p74););
printStats();
PRINT_POINTER(smalloc(56););
printStats();
void* p131 = last_address;
PRINT_POINTER(srealloc(p79,164););
printStats();
void* p132 = last_address;
PRINT_POINTER(srealloc(p111,18););
printStats();
void* p133 = last_address;
DEBUG_PRINT(sfree(p124););
printStats();
DEBUG_PRINT(sfree(p120););
printStats();
PRINT_POINTER(scalloc(218,52););
printStats();
void* p134 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p135 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p136 = last_address;
PRINT_POINTER(srealloc(p118,114););
printStats();
void* p137 = last_address;
PRINT_POINTER(scalloc(237,178););
printStats();
void* p138 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p139 = last_address;
PRINT_POINTER(scalloc(208,125););
printStats();
void* p140 = last_address;
DEBUG_PRINT(sfree(p119););
printStats();
PRINT_POINTER(srealloc(p131,42););
printStats();
void* p141 = last_address;
PRINT_POINTER(srealloc(p116,189););
printStats();
void* p142 = last_address;
PRINT_POINTER(srealloc(p139,128););
printStats();
void* p143 = last_address;
DEBUG_PRINT(sfree(p109););
printStats();
PRINT_POINTER(scalloc(236,119););
printStats();
void* p144 = last_address;
PRINT_POINTER(srealloc(p77,188););
printStats();
void* p145 = last_address;
PRINT_POINTER(srealloc(p112,213););
printStats();
void* p146 = last_address;
DEBUG_PRINT(sfree(p78););
printStats();
PRINT_POINTER(scalloc(163,214););
printStats();
void* p147 = last_address;
PRINT_POINTER(srealloc(p122,114););
printStats();
void* p148 = last_address;
PRINT_POINTER(scalloc(51,59););
printStats();
void* p149 = last_address;
PRINT_POINTER(scalloc(186,103););
printStats();
void* p150 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p151 = last_address;
PRINT_POINTER(srealloc(p128,176););
printStats();
void* p152 = last_address;
DEBUG_PRINT(sfree(p127););
printStats();
DEBUG_PRINT(sfree(p98););
printStats();
PRINT_POINTER(srealloc(p81,225););
printStats();
void* p153 = last_address;
PRINT_POINTER(smalloc(58););
printStats();
void* p154 = last_address;
PRINT_POINTER(srealloc(p130,131););
printStats();
void* p155 = last_address;
PRINT_POINTER(scalloc(26,33););
printStats();
void* p156 = last_address;
PRINT_POINTER(srealloc(p137,64););
printStats();
void* p157 = last_address;
PRINT_POINTER(srealloc(p152,228););
printStats();
void* p158 = last_address;
PRINT_POINTER(scalloc(30,164););
printStats();
void* p159 = last_address;
PRINT_POINTER(scalloc(158,240););
printStats();
void* p160 = last_address;
PRINT_POINTER(srealloc(p140,103););
printStats();
void* p161 = last_address;
PRINT_POINTER(smalloc(88););
printStats();
void* p162 = last_address;
PRINT_POINTER(scalloc(218,134););
printStats();
void* p163 = last_address;
PRINT_POINTER(scalloc(11,220););
printStats();
void* p164 = last_address;
DEBUG_PRINT(sfree(p144););
printStats();
DEBUG_PRINT(sfree(p147););
printStats();
PRINT_POINTER(smalloc(236););
printStats();
void* p165 = last_address;
DEBUG_PRINT(sfree(p150););
printStats();
DEBUG_PRINT(sfree(p123););
printStats();
PRINT_POINTER(srealloc(p159,131););
printStats();
void* p166 = last_address;
PRINT_POINTER(scalloc(46,153););
printStats();
void* p167 = last_address;
DEBUG_PRINT(sfree(p142););
printStats();
PRINT_POINTER(scalloc(62,221););
printStats();
void* p168 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p169 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p170 = last_address;
DEBUG_PRINT(sfree(p143););
printStats();
PRINT_POINTER(smalloc(64););
printStats();
void* p171 = last_address;
PRINT_POINTER(scalloc(141,183););
printStats();
void* p172 = last_address;
PRINT_POINTER(srealloc(p156,122););
printStats();
void* p173 = last_address;
DEBUG_PRINT(sfree(p170););
printStats();
PRINT_POINTER(scalloc(41,43););
printStats();
void* p174 = last_address;
DEBUG_PRINT(sfree(p154););
printStats();
PRINT_POINTER(srealloc(p157,26););
printStats();
void* p175 = last_address;
PRINT_POINTER(srealloc(p169,151););
printStats();
void* p176 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p177 = last_address;
PRINT_POINTER(smalloc(4););
printStats();
void* p178 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p179 = last_address;
DEBUG_PRINT(sfree(p162););
printStats();
PRINT_POINTER(scalloc(193,37););
printStats();
void* p180 = last_address;
PRINT_POINTER(scalloc(113,191););
printStats();
void* p181 = last_address;
PRINT_POINTER(scalloc(150,186););
printStats();
void* p182 = last_address;
DEBUG_PRINT(sfree(p132););
printStats();
DEBUG_PRINT(sfree(p179););
printStats();
PRINT_POINTER(smalloc(174););
printStats();
void* p183 = last_address;
PRINT_POINTER(srealloc(p135,39););
printStats();
void* p184 = last_address;
PRINT_POINTER(scalloc(64,109););
printStats();
void* p185 = last_address;
PRINT_POINTER(scalloc(19,194););
printStats();
void* p186 = last_address;
DEBUG_PRINT(sfree(p181););
printStats();
DEBUG_PRINT(sfree(p161););
printStats();
PRINT_POINTER(scalloc(137,166););
printStats();
void* p187 = last_address;
PRINT_POINTER(srealloc(p167,202););
printStats();
void* p188 = last_address;
PRINT_POINTER(scalloc(35,35););
printStats();
void* p189 = last_address;
DEBUG_PRINT(sfree(p173););
printStats();
PRINT_POINTER(smalloc(51););
printStats();
void* p190 = last_address;
PRINT_POINTER(smalloc(224););
printStats();
void* p191 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p192 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p193 = last_address;
DEBUG_PRINT(sfree(p191););
printStats();
PRINT_POINTER(srealloc(p172,227););
printStats();
void* p194 = last_address;
PRINT_POINTER(scalloc(183,60););
printStats();
void* p195 = last_address;
DEBUG_PRINT(sfree(p176););
printStats();
PRINT_POINTER(scalloc(105,141););
printStats();
void* p196 = last_address;
DEBUG_PRINT(sfree(p186););
printStats();
PRINT_POINTER(scalloc(49,53););
printStats();
void* p197 = last_address;
PRINT_POINTER(srealloc(p113,27););
printStats();
void* p198 = last_address;
DEBUG_PRINT(sfree(p165););
printStats();
PRINT_POINTER(scalloc(134,108););
printStats();
void* p199 = last_address;
PRINT_POINTER(scalloc(13,97););
printStats();
void* p200 = last_address;
PRINT_POINTER(srealloc(p192,97););
printStats();
void* p201 = last_address;
DEBUG_PRINT(sfree(p110););
printStats();
DEBUG_PRINT(sfree(p177););
printStats();
PRINT_POINTER(srealloc(p195,188););
printStats();
void* p202 = last_address;
PRINT_POINTER(scalloc(231,142););
printStats();
void* p203 = last_address;
PRINT_POINTER(scalloc(111,192););
printStats();
void* p204 = last_address;
PRINT_POINTER(scalloc(38,46););
printStats();
void* p205 = last_address;
PRINT_POINTER(scalloc(187,175););
printStats();
void* p206 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p207 = last_address;
DEBUG_PRINT(sfree(p175););
printStats();
PRINT_POINTER(smalloc(101););
printStats();
void* p208 = last_address;
PRINT_POINTER(smalloc(32););
printStats();
void* p209 = last_address;
PRINT_POINTER(scalloc(0,170););
printStats();
void* p210 = last_address;
DEBUG_PRINT(sfree(p155););
printStats();
DEBUG_PRINT(sfree(p210););
printStats();
PRINT_POINTER(srealloc(p149,224););
printStats();
void* p211 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p212 = last_address;
PRINT_POINTER(scalloc(114,50););
printStats();
void* p213 = last_address;
PRINT_POINTER(scalloc(135,67););
printStats();
void* p214 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p215 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p216 = last_address;
PRINT_POINTER(smalloc(167););
printStats();
void* p217 = last_address;
PRINT_POINTER(srealloc(p208,209););
printStats();
void* p218 = last_address;
PRINT_POINTER(srealloc(p103,156););
printStats();
void* p219 = last_address;
DEBUG_PRINT(sfree(p136););
printStats();
PRINT_POINTER(srealloc(p202,69););
printStats();
void* p220 = last_address;
PRINT_POINTER(scalloc(60,179););
printStats();
void* p221 = last_address;
PRINT_POINTER(smalloc(149););
printStats();
void* p222 = last_address;
DEBUG_PRINT(sfree(p215););
printStats();
DEBUG_PRINT(sfree(p148););
printStats();
PRINT_POINTER(smalloc(45););
printStats();
void* p223 = last_address;
PRINT_POINTER(scalloc(138,154););
printStats();
void* p224 = last_address;
PRINT_POINTER(srealloc(p82,221););
printStats();
void* p225 = last_address;
PRINT_POINTER(scalloc(154,244););
printStats();
void* p226 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p227 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p228 = last_address;
PRINT_POINTER(srealloc(p66,103););
printStats();
void* p229 = last_address;
PRINT_POINTER(scalloc(185,20););
printStats();
void* p230 = last_address;
DEBUG_PRINT(sfree(p97););
printStats();
PRINT_POINTER(srealloc(p141,209););
printStats();
void* p231 = last_address;
PRINT_POINTER(smalloc(206););
printStats();
void* p232 = last_address;
PRINT_POINTER(smalloc(127););
printStats();
void* p233 = last_address;
DEBUG_PRINT(sfree(p163););
printStats();
PRINT_POINTER(scalloc(223,117););
printStats();
void* p234 = last_address;
PRINT_POINTER(scalloc(121,71););
printStats();
void* p235 = last_address;
DEBUG_PRINT(sfree(p204););
printStats();
PRINT_POINTER(srealloc(p230,234););
printStats();
void* p236 = last_address;
DEBUG_PRINT(sfree(p220););
printStats();
PRINT_POINTER(smalloc(136););
printStats();
void* p237 = last_address;
PRINT_POINTER(smalloc(125););
printStats();
void* p238 = last_address;
PRINT_POINTER(srealloc(p205,92););
printStats();
void* p239 = last_address;
PRINT_POINTER(srealloc(p99,51););
printStats();
void* p240 = last_address;
PRINT_POINTER(scalloc(32,204););
printStats();
void* p241 = last_address;
PRINT_POINTER(scalloc(195,117););
printStats();
void* p242 = last_address;
PRINT_POINTER(smalloc(173););
printStats();
void* p243 = last_address;
DEBUG_PRINT(sfree(p228););
printStats();
PRINT_POINTER(srealloc(p219,231););
printStats();
void* p244 = last_address;
PRINT_POINTER(srealloc(p225,14););
printStats();
void* p245 = last_address;
PRINT_POINTER(srealloc(p196,195););
printStats();
void* p246 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p247 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p248 = last_address;
DEBUG_PRINT(sfree(p126););
printStats();
PRINT_POINTER(scalloc(204,80););
printStats();
void* p249 = last_address;
PRINT_POINTER(srealloc(p243,110););
printStats();
void* p250 = last_address;
DEBUG_PRINT(sfree(p197););
printStats();
PRINT_POINTER(srealloc(p164,82););
printStats();
void* p251 = last_address;
PRINT_POINTER(srealloc(p245,42););
printStats();
void* p252 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p253 = last_address;
PRINT_POINTER(smalloc(39););
printStats();
void* p254 = last_address;
PRINT_POINTER(smalloc(13););
printStats();
void* p255 = last_address;
PRINT_POINTER(scalloc(154,170););
printStats();
void* p256 = last_address;
PRINT_POINTER(srealloc(p203,218););
printStats();
void* p257 = last_address;
DEBUG_PRINT(sfree(p234););
printStats();
DEBUG_PRINT(sfree(p107););
printStats();
PRINT_POINTER(smalloc(243););
printStats();
void* p258 = last_address;
PRINT_POINTER(smalloc(69););
printStats();
void* p259 = last_address;
PRINT_POINTER(scalloc(162,220););
printStats();
void* p260 = last_address;
PRINT_POINTER(smalloc(216););
printStats();
void* p261 = last_address;
PRINT_POINTER(scalloc(240,63););
printStats();
void* p262 = last_address;
PRINT_POINTER(smalloc(82););
printStats();
void* p263 = last_address;
PRINT_POINTER(scalloc(97,202););
printStats();
void* p264 = last_address;
PRINT_POINTER(scalloc(161,190););
printStats();
void* p265 = last_address;
DEBUG_PRINT(sfree(p253););
printStats();
PRINT_POINTER(smalloc(184););
printStats();
void* p266 = last_address;
PRINT_POINTER(srealloc(p236,34););
printStats();
void* p267 = last_address;
PRINT_POINTER(srealloc(p168,11););
printStats();
void* p268 = last_address;
PRINT_POINTER(srealloc(p96,139););
printStats();
void* p269 = last_address;
PRINT_POINTER(srealloc(p268,88););
printStats();
void* p270 = last_address;
PRINT_POINTER(srealloc(p235,170););
printStats();
void* p271 = last_address;
PRINT_POINTER(scalloc(126,51););
printStats();
void* p272 = last_address;
PRINT_POINTER(scalloc(181,23););
printStats();
void* p273 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p274 = last_address;
PRINT_POINTER(scalloc(80,20););
printStats();
void* p275 = last_address;
PRINT_POINTER(smalloc(151););
printStats();
void* p276 = last_address;
PRINT_POINTER(smalloc(33););
printStats();
void* p277 = last_address;
PRINT_POINTER(smalloc(97););
printStats();
void* p278 = last_address;
DEBUG_PRINT(sfree(p190););
printStats();
PRINT_POINTER(srealloc(p260,127););
printStats();
void* p279 = last_address;
PRINT_POINTER(scalloc(208,204););
printStats();
void* p280 = last_address;
DEBUG_PRINT(sfree(p274););
printStats();
PRINT_POINTER(srealloc(p239,87););
printStats();
void* p281 = last_address;
PRINT_POINTER(smalloc(186););
printStats();
void* p282 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p283 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p284 = last_address;
PRINT_POINTER(srealloc(p237,83););
printStats();
void* p285 = last_address;
PRINT_POINTER(srealloc(p242,75););
printStats();
void* p286 = last_address;
DEBUG_PRINT(sfree(p187););
printStats();
PRINT_POINTER(smalloc(246););
printStats();
void* p287 = last_address;
DEBUG_PRINT(sfree(p284););
printStats();
PRINT_POINTER(scalloc(126,147););
printStats();
void* p288 = last_address;
PRINT_POINTER(scalloc(88,18););
printStats();
void* p289 = last_address;
DEBUG_PRINT(sfree(p287););
printStats();
PRINT_POINTER(smalloc(92););
printStats();
void* p290 = last_address;
PRINT_POINTER(scalloc(224,41););
printStats();
void* p291 = last_address;
PRINT_POINTER(scalloc(191,0););
printStats();
void* p292 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p293 = last_address;
DEBUG_PRINT(sfree(p292););
printStats();
DEBUG_PRINT(sfree(p279););
printStats();
PRINT_POINTER(scalloc(207,145););
printStats();
void* p294 = last_address;
PRINT_POINTER(srealloc(p290,127););
printStats();
void* p295 = last_address;
PRINT_POINTER(srealloc(p133,181););
printStats();
void* p296 = last_address;
DEBUG_PRINT(sfree(p282););
printStats();
DEBUG_PRINT(sfree(p198););
printStats();
PRINT_POINTER(smalloc(190););
printStats();
void* p297 = last_address;
PRINT_POINTER(srealloc(p217,25););
printStats();
void* p298 = last_address;
PRINT_POINTER(srealloc(p180,15););
printStats();
void* p299 = last_address;
PRINT_POINTER(scalloc(21,108););
printStats();
void* p300 = last_address;
PRINT_POINTER(scalloc(41,134););
printStats();
void* p301 = last_address;
DEBUG_PRINT(sfree(p71););
printStats();
DEBUG_PRINT(sfree(p153););
printStats();
DEBUG_PRINT(sfree(p125););
printStats();
PRINT_POINTER(srealloc(p160,189););
printStats();
void* p302 = last_address;
DEBUG_PRINT(sfree(p267););
printStats();
PRINT_POINTER(smalloc(90););
printStats();
void* p303 = last_address;
PRINT_POINTER(scalloc(35,161););
printStats();
void* p304 = last_address;
PRINT_POINTER(srealloc(p89,49););
printStats();
void* p305 = last_address;
PRINT_POINTER(smalloc(165););
printStats();
void* p306 = last_address;
PRINT_POINTER(smalloc(153););
printStats();
void* p307 = last_address;
DEBUG_PRINT(sfree(p281););
printStats();
PRINT_POINTER(smalloc(183););
printStats();
void* p308 = last_address;
DEBUG_PRINT(sfree(p146););
printStats();
PRINT_POINTER(srealloc(p185,42););
printStats();
void* p309 = last_address;
DEBUG_PRINT(sfree(p307););
printStats();
DEBUG_PRINT(sfree(p145););
printStats();
DEBUG_PRINT(sfree(p276););
printStats();
DEBUG_PRINT(sfree(p302););
printStats();
PRINT_POINTER(srealloc(p108,0););
printStats();
void* p310 = last_address;
DEBUG_PRINT(sfree(p270););
printStats();
DEBUG_PRINT(sfree(p231););
printStats();
DEBUG_PRINT(sfree(p301););
printStats();
PRINT_POINTER(srealloc(p241,106););
printStats();
void* p311 = last_address;
PRINT_POINTER(scalloc(3,218););
printStats();
void* p312 = last_address;
PRINT_POINTER(srealloc(p232,207););
printStats();
void* p313 = last_address;
PRINT_POINTER(scalloc(176,77););
printStats();
void* p314 = last_address;
PRINT_POINTER(srealloc(p151,4););
printStats();
void* p315 = last_address;
PRINT_POINTER(srealloc(p257,79););
printStats();
void* p316 = last_address;
PRINT_POINTER(scalloc(78,22););
printStats();
void* p317 = last_address;
PRINT_POINTER(srealloc(p309,14););
printStats();
void* p318 = last_address;
PRINT_POINTER(scalloc(106,164););
printStats();
void* p319 = last_address;
PRINT_POINTER(smalloc(209););
printStats();
void* p320 = last_address;
PRINT_POINTER(scalloc(197,213););
printStats();
void* p321 = last_address;
DEBUG_PRINT(sfree(p312););
printStats();
PRINT_POINTER(scalloc(74,180););
printStats();
void* p322 = last_address;
DEBUG_PRINT(sfree(p297););
printStats();
PRINT_POINTER(smalloc(98););
printStats();
void* p323 = last_address;
PRINT_POINTER(srealloc(p188,101););
printStats();
void* p324 = last_address;
PRINT_POINTER(smalloc(154););
printStats();
void* p325 = last_address;
DEBUG_PRINT(sfree(p323););
printStats();
DEBUG_PRINT(sfree(p174););
printStats();
PRINT_POINTER(smalloc(167););
printStats();
void* p326 = last_address;
DEBUG_PRINT(sfree(p275););
printStats();
DEBUG_PRINT(sfree(p115););
printStats();
PRINT_POINTER(srealloc(p244,1););
printStats();
void* p327 = last_address;
PRINT_POINTER(srealloc(p213,77););
printStats();
void* p328 = last_address;
PRINT_POINTER(srealloc(p271,133););
printStats();
void* p329 = last_address;
DEBUG_PRINT(sfree(p263););
printStats();
DEBUG_PRINT(sfree(p293););
printStats();
PRINT_POINTER(srealloc(p328,160););
printStats();
void* p330 = last_address;
PRINT_POINTER(srealloc(p224,230););
printStats();
void* p331 = last_address;
PRINT_POINTER(scalloc(144,125););
printStats();
void* p332 = last_address;
DEBUG_PRINT(sfree(p291););
printStats();
PRINT_POINTER(scalloc(171,62););
printStats();
void* p333 = last_address;
DEBUG_PRINT(sfree(p194););
printStats();
PRINT_POINTER(smalloc(214););
printStats();
void* p334 = last_address;
PRINT_POINTER(smalloc(16););
printStats();
void* p335 = last_address;
PRINT_POINTER(scalloc(190,87););
printStats();
void* p336 = last_address;
DEBUG_PRINT(sfree(p211););
printStats();
DEBUG_PRINT(sfree(p183););
printStats();
PRINT_POINTER(smalloc(138););
printStats();
void* p337 = last_address;
DEBUG_PRINT(sfree(p254););
printStats();
PRINT_POINTER(smalloc(41););
printStats();
void* p338 = last_address;
PRINT_POINTER(scalloc(66,21););
printStats();
void* p339 = last_address;
PRINT_POINTER(srealloc(p201,174););
printStats();
void* p340 = last_address;
PRINT_POINTER(srealloc(p259,107););
printStats();
void* p341 = last_address;
PRINT_POINTER(smalloc(139););
printStats();
void* p342 = last_address;
PRINT_POINTER(scalloc(40,132););
printStats();
void* p343 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p344 = last_address;
PRINT_POINTER(scalloc(103,247););
printStats();
void* p345 = last_address;
PRINT_POINTER(scalloc(192,82););
printStats();
void* p346 = last_address;
DEBUG_PRINT(sfree(p305););
printStats();
DEBUG_PRINT(sfree(p252););
printStats();
PRINT_POINTER(scalloc(209,78););
printStats();
void* p347 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p348 = last_address;
PRINT_POINTER(scalloc(135,65););
printStats();
void* p349 = last_address;
PRINT_POINTER(scalloc(246,171););
printStats();
void* p350 = last_address;
PRINT_POINTER(srealloc(p349,40););
printStats();
void* p351 = last_address;
PRINT_POINTER(scalloc(165,229););
printStats();
void* p352 = last_address;
PRINT_POINTER(srealloc(p330,134););
printStats();
void* p353 = last_address;
PRINT_POINTER(smalloc(86););
printStats();
void* p354 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p355 = last_address;
PRINT_POINTER(smalloc(114););
printStats();
void* p356 = last_address;
PRINT_POINTER(scalloc(197,98););
printStats();
void* p357 = last_address;
DEBUG_PRINT(sfree(p250););
printStats();
PRINT_POINTER(scalloc(187,195););
printStats();
void* p358 = last_address;
PRINT_POINTER(scalloc(213,22););
printStats();
void* p359 = last_address;
PRINT_POINTER(scalloc(99,34););
printStats();
void* p360 = last_address;
DEBUG_PRINT(sfree(p350););
printStats();
PRINT_POINTER(smalloc(18););
printStats();
void* p361 = last_address;
PRINT_POINTER(smalloc(205););
printStats();
void* p362 = last_address;
PRINT_POINTER(scalloc(207,205););
printStats();
void* p363 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p364 = last_address;
PRINT_POINTER(smalloc(210););
printStats();
void* p365 = last_address;
PRINT_POINTER(smalloc(80););
printStats();
void* p366 = last_address;
PRINT_POINTER(smalloc(204););
printStats();
void* p367 = last_address;
DEBUG_PRINT(sfree(p358););
printStats();
PRINT_POINTER(smalloc(5););
printStats();
void* p368 = last_address;
DEBUG_PRINT(sfree(p352););
printStats();
PRINT_POINTER(scalloc(170,58););
printStats();
void* p369 = last_address;
DEBUG_PRINT(sfree(p227););
printStats();
DEBUG_PRINT(sfree(p322););
printStats();
PRINT_POINTER(srealloc(p303,82););
printStats();
void* p370 = last_address;
PRINT_POINTER(srealloc(p336,32););
printStats();
void* p371 = last_address;
PRINT_POINTER(smalloc(236););
printStats();
void* p372 = last_address;
PRINT_POINTER(smalloc(71););
printStats();
void* p373 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p374 = last_address;
DEBUG_PRINT(sfree(p255););
printStats();
PRINT_POINTER(srealloc(p189,152););
printStats();
void* p375 = last_address;
PRINT_POINTER(srealloc(p298,51););
printStats();
void* p376 = last_address;
PRINT_POINTER(smalloc(27););
printStats();
void* p377 = last_address;
PRINT_POINTER(scalloc(56,29););
printStats();
void* p378 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p379 = last_address;
PRINT_POINTER(srealloc(p286,214););
printStats();
void* p380 = last_address;
DEBUG_PRINT(sfree(p240););
printStats();
DEBUG_PRINT(sfree(p223););
printStats();
PRINT_POINTER(srealloc(p369,226););
printStats();
void* p381 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p382 = last_address;
PRINT_POINTER(smalloc(215););
printStats();
void* p383 = last_address;
DEBUG_PRINT(sfree(p348););
printStats();
PRINT_POINTER(srealloc(p216,112););
printStats();
void* p384 = last_address;
DEBUG_PRINT(sfree(p327););
printStats();
DEBUG_PRINT(sfree(p333););
printStats();
PRINT_POINTER(srealloc(p277,185););
printStats();
void* p385 = last_address;
PRINT_POINTER(srealloc(p334,114););
printStats();
void* p386 = last_address;
PRINT_POINTER(smalloc(25););
printStats();
void* p387 = last_address;
PRINT_POINTER(srealloc(p344,24););
printStats();
void* p388 = last_address;
PRINT_POINTER(srealloc(p324,95););
printStats();
void* p389 = last_address;
PRINT_POINTER(scalloc(202,154););
printStats();
void* p390 = last_address;
DEBUG_PRINT(sfree(p360););
printStats();
PRINT_POINTER(srealloc(p226,106););
printStats();
void* p391 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p392 = last_address;
PRINT_POINTER(scalloc(41,93););
printStats();
void* p393 = last_address;
DEBUG_PRINT(sfree(p199););
printStats();
PRINT_POINTER(srealloc(p265,112););
printStats();
void* p394 = last_address;
DEBUG_PRINT(sfree(p368););
printStats();
PRINT_POINTER(smalloc(152););
printStats();
void* p395 = last_address;
PRINT_POINTER(scalloc(69,143););
printStats();
void* p396 = last_address;
PRINT_POINTER(smalloc(217););
printStats();
void* p397 = last_address;
DEBUG_PRINT(sfree(p351););
printStats();
DEBUG_PRINT(sfree(p207););
printStats();
PRINT_POINTER(scalloc(79,89););
printStats();
void* p398 = last_address;
PRINT_POINTER(scalloc(83,208););
printStats();
void* p399 = last_address;
DEBUG_PRINT(sfree(p380););
printStats();
PRINT_POINTER(smalloc(110););
printStats();
void* p400 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p401 = last_address;
PRINT_POINTER(scalloc(81,110););
printStats();
void* p402 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p403 = last_address;
PRINT_POINTER(smalloc(218););
printStats();
void* p404 = last_address;
PRINT_POINTER(scalloc(161,181););
printStats();
void* p405 = last_address;
DEBUG_PRINT(sfree(p233););
printStats();
PRINT_POINTER(srealloc(p295,84););
printStats();
void* p406 = last_address;
PRINT_POINTER(smalloc(166););
printStats();
void* p407 = last_address;
DEBUG_PRINT(sfree(p308););
printStats();
DEBUG_PRINT(sfree(p262););
printStats();
PRINT_POINTER(smalloc(1););
printStats();
void* p408 = last_address;
DEBUG_PRINT(sfree(p138););
printStats();
PRINT_POINTER(srealloc(p377,207););
printStats();
void* p409 = last_address;
PRINT_POINTER(scalloc(154,136););
printStats();
void* p410 = last_address;
PRINT_POINTER(scalloc(9,78););
printStats();
void* p411 = last_address;
PRINT_POINTER(smalloc(238););
printStats();
void* p412 = last_address;
PRINT_POINTER(smalloc(248););
printStats();
void* p413 = last_address;
PRINT_POINTER(srealloc(p385,192););
printStats();
void* p414 = last_address;
PRINT_POINTER(scalloc(112,153););
printStats();
void* p415 = last_address;
PRINT_POINTER(srealloc(p264,140););
printStats();
void* p416 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p417 = last_address;
DEBUG_PRINT(sfree(p248););
printStats();
PRINT_POINTER(scalloc(18,104););
printStats();
void* p418 = last_address;
PRINT_POINTER(smalloc(74););
printStats();
void* p419 = last_address;
PRINT_POINTER(scalloc(148,17););
printStats();
void* p420 = last_address;
PRINT_POINTER(srealloc(p296,11););
printStats();
void* p421 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p422 = last_address;
PRINT_POINTER(smalloc(107););
printStats();
void* p423 = last_address;
PRINT_POINTER(smalloc(103););
printStats();
void* p424 = last_address;
PRINT_POINTER(scalloc(95,21););
printStats();
void* p425 = last_address;
PRINT_POINTER(srealloc(p209,147););
printStats();
void* p426 = last_address;
PRINT_POINTER(smalloc(201););
printStats();
void* p427 = last_address;
PRINT_POINTER(srealloc(p329,75););
printStats();
void* p428 = last_address;
DEBUG_PRINT(sfree(p134););
printStats();
PRINT_POINTER(srealloc(p317,122););
printStats();
void* p429 = last_address;
PRINT_POINTER(scalloc(19,66););
printStats();
void* p430 = last_address;
PRINT_POINTER(srealloc(p294,176););
printStats();
void* p431 = last_address;
PRINT_POINTER(srealloc(p364,231););
printStats();
void* p432 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p433 = last_address;
PRINT_POINTER(srealloc(p314,106););
printStats();
void* p434 = last_address;
PRINT_POINTER(scalloc(28,25););
printStats();
void* p435 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p436 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p437 = last_address;
PRINT_POINTER(scalloc(96,121););
printStats();
void* p438 = last_address;
PRINT_POINTER(scalloc(65,144););
printStats();
void* p439 = last_address;
DEBUG_PRINT(sfree(p316););
printStats();
PRINT_POINTER(scalloc(149,134););
printStats();
void* p440 = last_address;
PRINT_POINTER(srealloc(p389,143););
printStats();
void* p441 = last_address;
PRINT_POINTER(smalloc(41););
printStats();
void* p442 = last_address;
PRINT_POINTER(scalloc(41,155););
printStats();
void* p443 = last_address;
PRINT_POINTER(srealloc(p376,187););
printStats();
void* p444 = last_address;
DEBUG_PRINT(sfree(p222););
printStats();
PRINT_POINTER(scalloc(127,74););
printStats();
void* p445 = last_address;
DEBUG_PRINT(sfree(p278););
printStats();
PRINT_POINTER(srealloc(p425,17););
printStats();
void* p446 = last_address;
PRINT_POINTER(smalloc(196););
printStats();
void* p447 = last_address;
DEBUG_PRINT(sfree(p403););
printStats();
DEBUG_PRINT(sfree(p289););
printStats();
DEBUG_PRINT(sfree(p249););
printStats();
PRINT_POINTER(srealloc(p310,165););
printStats();
void* p448 = last_address;
PRINT_POINTER(srealloc(p443,4););
printStats();
void* p449 = last_address;
PRINT_POINTER(srealloc(p428,83););
printStats();
void* p450 = last_address;
DEBUG_PRINT(sfree(p393););
printStats();
DEBUG_PRINT(sfree(p193););
printStats();
PRINT_POINTER(scalloc(37,185););
printStats();
void* p451 = last_address;
PRINT_POINTER(scalloc(97,31););
printStats();
void* p452 = last_address;
DEBUG_PRINT(sfree(p321););
printStats();
DEBUG_PRINT(sfree(p246););
printStats();
PRINT_POINTER(srealloc(p414,117););
printStats();
void* p453 = last_address;
PRINT_POINTER(scalloc(211,152););
printStats();
void* p454 = last_address;
PRINT_POINTER(scalloc(95,68););
printStats();
void* p455 = last_address;
PRINT_POINTER(smalloc(123););
printStats();
void* p456 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p457 = last_address;
PRINT_POINTER(smalloc(120););
printStats();
void* p458 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p459 = last_address;
DEBUG_PRINT(sfree(p367););
printStats();
PRINT_POINTER(srealloc(p315,23););
printStats();
void* p460 = last_address;
DEBUG_PRINT(sfree(p171););
printStats();
DEBUG_PRINT(sfree(p406););
printStats();
PRINT_POINTER(smalloc(72););
printStats();
void* p461 = last_address;
PRINT_POINTER(scalloc(22,59););
printStats();
void* p462 = last_address;
DEBUG_PRINT(sfree(p424););
printStats();
PRINT_POINTER(smalloc(26););
printStats();
void* p463 = last_address;
DEBUG_PRINT(sfree(p381););
printStats();
PRINT_POINTER(srealloc(p436,60););
printStats();
void* p464 = last_address;
DEBUG_PRINT(sfree(p396););
printStats();
PRINT_POINTER(scalloc(201,138););
printStats();
void* p465 = last_address;
PRINT_POINTER(scalloc(209,164););
printStats();
void* p466 = last_address;
DEBUG_PRINT(sfree(p325););
printStats();
DEBUG_PRINT(sfree(p453););
printStats();
DEBUG_PRINT(sfree(p346););
printStats();
DEBUG_PRINT(sfree(p375););
printStats();
DEBUG_PRINT(sfree(p373););
printStats();
PRINT_POINTER(srealloc(p304,98););
printStats();
void* p467 = last_address;
PRINT_POINTER(smalloc(247););
printStats();
void* p468 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p469 = last_address;
PRINT_POINTER(srealloc(p338,44););
printStats();
void* p470 = last_address;
DEBUG_PRINT(sfree(p429););
printStats();
PRINT_POINTER(srealloc(p431,8););
printStats();
void* p471 = last_address;
PRINT_POINTER(smalloc(176););
printStats();
void* p472 = last_address;
PRINT_POINTER(srealloc(p435,16););
printStats();
void* p473 = last_address;
PRINT_POINTER(scalloc(131,200););
printStats();
void* p474 = last_address;
PRINT_POINTER(srealloc(p359,35););
printStats();
void* p475 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p476 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p477 = last_address;
PRINT_POINTER(scalloc(160,223););
printStats();
void* p478 = last_address;
PRINT_POINTER(smalloc(225););
printStats();
void* p479 = last_address;
PRINT_POINTER(srealloc(p457,199););
printStats();
void* p480 = last_address;
PRINT_POINTER(srealloc(p280,217););
printStats();
void* p481 = last_address;
DEBUG_PRINT(sfree(p206););
printStats();
PRINT_POINTER(srealloc(p427,49););
printStats();
void* p482 = last_address;
PRINT_POINTER(srealloc(p266,217););
printStats();
void* p483 = last_address;
PRINT_POINTER(srealloc(p420,50););
printStats();
void* p484 = last_address;
PRINT_POINTER(srealloc(p455,246););
printStats();
void* p485 = last_address;
PRINT_POINTER(smalloc(101););
printStats();
void* p486 = last_address;
DEBUG_PRINT(sfree(p448););
printStats();
DEBUG_PRINT(sfree(p480););
printStats();
PRINT_POINTER(srealloc(p419,218););
printStats();
void* p487 = last_address;
DEBUG_PRINT(sfree(p357););
printStats();
DEBUG_PRINT(sfree(p417););
printStats();
DEBUG_PRINT(sfree(p384););
printStats();
PRINT_POINTER(scalloc(227,22););
printStats();
void* p488 = last_address;
PRINT_POINTER(srealloc(p313,138););
printStats();
void* p489 = last_address;
PRINT_POINTER(scalloc(35,220););
printStats();
void* p490 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p491 = last_address;
PRINT_POINTER(smalloc(116););
printStats();
void* p492 = last_address;
PRINT_POINTER(scalloc(195,14););
printStats();
void* p493 = last_address;
DEBUG_PRINT(sfree(p251););
printStats();
PRINT_POINTER(smalloc(199););
printStats();
void* p494 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p495 = last_address;
PRINT_POINTER(smalloc(181););
printStats();
void* p496 = last_address;
PRINT_POINTER(smalloc(66););
printStats();
void* p497 = last_address;
PRINT_POINTER(scalloc(42,186););
printStats();
void* p498 = last_address;
PRINT_POINTER(scalloc(92,247););
printStats();
void* p499 = last_address;
PRINT_POINTER(scalloc(109,67););
printStats();
void* p500 = last_address;
PRINT_POINTER(srealloc(p269,29););
printStats();
void* p501 = last_address;
PRINT_POINTER(srealloc(p395,154););
printStats();
void* p502 = last_address;
PRINT_POINTER(scalloc(237,144););
printStats();
void* p503 = last_address;
PRINT_POINTER(scalloc(211,33););
printStats();
void* p504 = last_address;
PRINT_POINTER(smalloc(23););
printStats();
void* p505 = last_address;
DEBUG_PRINT(sfree(p392););
printStats();
PRINT_POINTER(srealloc(p430,8););
printStats();
void* p506 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p507 = last_address;
DEBUG_PRINT(sfree(p382););
printStats();
PRINT_POINTER(scalloc(232,68););
printStats();
void* p508 = last_address;
PRINT_POINTER(scalloc(98,136););
printStats();
void* p509 = last_address;
DEBUG_PRINT(sfree(p433););
printStats();
DEBUG_PRINT(sfree(p184););
printStats();
PRINT_POINTER(smalloc(14););
printStats();
void* p510 = last_address;
DEBUG_PRINT(sfree(p482););
printStats();
PRINT_POINTER(scalloc(154,45););
printStats();
void* p511 = last_address;
DEBUG_PRINT(sfree(p229););
printStats();
PRINT_POINTER(scalloc(104,90););
printStats();
void* p512 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p513 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p514 = last_address;
DEBUG_PRINT(sfree(p454););
printStats();
PRINT_POINTER(scalloc(63,52););
printStats();
void* p515 = last_address;
DEBUG_PRINT(sfree(p493););
printStats();
PRINT_POINTER(srealloc(p471,169););
printStats();
void* p516 = last_address;
PRINT_POINTER(smalloc(76););
printStats();
void* p517 = last_address;
DEBUG_PRINT(sfree(p399););
printStats();
DEBUG_PRINT(sfree(p477););
printStats();
PRINT_POINTER(smalloc(26););
printStats();
void* p518 = last_address;
PRINT_POINTER(smalloc(8););
printStats();
void* p519 = last_address;
DEBUG_PRINT(sfree(p446););
printStats();
PRINT_POINTER(smalloc(236););
printStats();
void* p520 = last_address;
DEBUG_PRINT(sfree(p365););
printStats();
PRINT_POINTER(scalloc(99,236););
printStats();
void* p521 = last_address;
PRINT_POINTER(smalloc(199););
printStats();
void* p522 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p523 = last_address;
PRINT_POINTER(srealloc(p458,42););
printStats();
void* p524 = last_address;
PRINT_POINTER(smalloc(141););
printStats();
void* p525 = last_address;
DEBUG_PRINT(sfree(p339););
printStats();
PRINT_POINTER(smalloc(49););
printStats();
void* p526 = last_address;
PRINT_POINTER(smalloc(202););
printStats();
void* p527 = last_address;
PRINT_POINTER(scalloc(218,15););
printStats();
void* p528 = last_address;
PRINT_POINTER(srealloc(p475,165););
printStats();
void* p529 = last_address;
PRINT_POINTER(scalloc(5,229););
printStats();
void* p530 = last_address;
PRINT_POINTER(smalloc(245););
printStats();
void* p531 = last_address;
PRINT_POINTER(scalloc(97,120););
printStats();
void* p532 = last_address;
PRINT_POINTER(scalloc(228,158););
printStats();
void* p533 = last_address;
PRINT_POINTER(scalloc(200,176););
printStats();
void* p534 = last_address;
DEBUG_PRINT(sfree(p522););
printStats();
PRINT_POINTER(smalloc(91););
printStats();
void* p535 = last_address;
DEBUG_PRINT(sfree(p463););
printStats();
PRINT_POINTER(srealloc(p421,72););
printStats();
void* p536 = last_address;
DEBUG_PRINT(sfree(p508););
printStats();
PRINT_POINTER(srealloc(p440,108););
printStats();
void* p537 = last_address;
PRINT_POINTER(scalloc(244,58););
printStats();
void* p538 = last_address;
PRINT_POINTER(srealloc(p488,71););
printStats();
void* p539 = last_address;
PRINT_POINTER(srealloc(p501,79););
printStats();
void* p540 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p541 = last_address;
PRINT_POINTER(scalloc(195,161););
printStats();
void* p542 = last_address;
PRINT_POINTER(smalloc(226););
printStats();
void* p543 = last_address;
PRINT_POINTER(srealloc(p498,99););
printStats();
void* p544 = last_address;
PRINT_POINTER(scalloc(232,133););
printStats();
void* p545 = last_address;
DEBUG_PRINT(sfree(p490););
printStats();
DEBUG_PRINT(sfree(p272););
printStats();
PRINT_POINTER(smalloc(219););
printStats();
void* p546 = last_address;
PRINT_POINTER(srealloc(p545,52););
printStats();
void* p547 = last_address;
PRINT_POINTER(scalloc(207,238););
printStats();
void* p548 = last_address;
DEBUG_PRINT(sfree(p413););
printStats();
PRINT_POINTER(srealloc(p158,186););
printStats();
void* p549 = last_address;
PRINT_POINTER(srealloc(p200,25););
printStats();
void* p550 = last_address;
PRINT_POINTER(srealloc(p528,210););
printStats();
void* p551 = last_address;
PRINT_POINTER(srealloc(p519,246););
printStats();
void* p552 = last_address;
PRINT_POINTER(scalloc(95,89););
printStats();
void* p553 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p554 = last_address;
PRINT_POINTER(smalloc(126););
printStats();
void* p555 = last_address;
DEBUG_PRINT(sfree(p341););
printStats();
PRINT_POINTER(srealloc(p512,156););
printStats();
void* p556 = last_address;
PRINT_POINTER(scalloc(202,10););
printStats();
void* p557 = last_address;
PRINT_POINTER(scalloc(246,62););
printStats();
void* p558 = last_address;
PRINT_POINTER(scalloc(206,161););
printStats();
void* p559 = last_address;
PRINT_POINTER(srealloc(p362,140););
printStats();
void* p560 = last_address;
PRINT_POINTER(smalloc(220););
printStats();
void* p561 = last_address;
PRINT_POINTER(scalloc(207,232););
printStats();
void* p562 = last_address;
DEBUG_PRINT(sfree(p536););
printStats();
PRINT_POINTER(scalloc(65,11););
printStats();
void* p563 = last_address;
PRINT_POINTER(srealloc(p408,158););
printStats();
void* p564 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p565 = last_address;
PRINT_POINTER(srealloc(p444,11););
printStats();
void* p566 = last_address;
PRINT_POINTER(smalloc(36););
printStats();
void* p567 = last_address;
PRINT_POINTER(smalloc(30););
printStats();
void* p568 = last_address;
PRINT_POINTER(scalloc(52,15););
printStats();
void* p569 = last_address;
PRINT_POINTER(scalloc(221,148););
printStats();
void* p570 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p571 = last_address;
PRINT_POINTER(scalloc(137,39););
printStats();
void* p572 = last_address;
DEBUG_PRINT(sfree(p285););
printStats();
PRINT_POINTER(scalloc(194,168););
printStats();
void* p573 = last_address;
PRINT_POINTER(smalloc(59););
printStats();
void* p574 = last_address;
PRINT_POINTER(srealloc(p445,90););
printStats();
void* p575 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p576 = last_address;
PRINT_POINTER(srealloc(p515,214););
printStats();
void* p577 = last_address;
PRINT_POINTER(scalloc(187,94););
printStats();
void* p578 = last_address;
PRINT_POINTER(srealloc(p468,20););
printStats();
void* p579 = last_address;
PRINT_POINTER(scalloc(219,155););
printStats();
void* p580 = last_address;
PRINT_POINTER(smalloc(191););
printStats();
void* p581 = last_address;
PRINT_POINTER(srealloc(p256,64););
printStats();
void* p582 = last_address;
PRINT_POINTER(scalloc(66,177););
printStats();
void* p583 = last_address;
PRINT_POINTER(smalloc(48););
printStats();
void* p584 = last_address;
DEBUG_PRINT(sfree(p247););
printStats();
PRINT_POINTER(srealloc(p569,193););
printStats();
void* p585 = last_address;
PRINT_POINTER(smalloc(2););
printStats();
void* p586 = last_address;
PRINT_POINTER(scalloc(201,189););
printStats();
void* p587 = last_address;
PRINT_POINTER(smalloc(244););
printStats();
void* p588 = last_address;
PRINT_POINTER(scalloc(147,6););
printStats();
void* p589 = last_address;
PRINT_POINTER(scalloc(81,154););
printStats();
void* p590 = last_address;
PRINT_POINTER(srealloc(p261,19););
printStats();
void* p591 = last_address;
PRINT_POINTER(scalloc(50,201););
printStats();
void* p592 = last_address;
PRINT_POINTER(srealloc(p575,91););
printStats();
void* p593 = last_address;
PRINT_POINTER(smalloc(105););
printStats();
void* p594 = last_address;
PRINT_POINTER(smalloc(24););
printStats();
void* p595 = last_address;
PRINT_POINTER(scalloc(49,124););
printStats();
void* p596 = last_address;
DEBUG_PRINT(sfree(p558););
printStats();
PRINT_POINTER(srealloc(p562,151););
printStats();
void* p597 = last_address;
PRINT_POINTER(srealloc(p479,154););
printStats();
void* p598 = last_address;
PRINT_POINTER(srealloc(p337,140););
printStats();
void* p599 = last_address;
PRINT_POINTER(smalloc(98););
printStats();
void* p600 = last_address;
PRINT_POINTER(smalloc(5););
printStats();
void* p601 = last_address;
DEBUG_PRINT(sfree(p589););
printStats();
PRINT_POINTER(srealloc(p596,245););
printStats();
void* p602 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p603 = last_address;
DEBUG_PRINT(sfree(p543););
printStats();
PRINT_POINTER(scalloc(216,165););
printStats();
void* p604 = last_address;
DEBUG_PRINT(sfree(p258););
printStats();
PRINT_POINTER(srealloc(p529,140););
printStats();
void* p605 = last_address;
DEBUG_PRINT(sfree(p579););
printStats();
PRINT_POINTER(srealloc(p386,140););
printStats();
void* p606 = last_address;
PRINT_POINTER(scalloc(3,41););
printStats();
void* p607 = last_address;
PRINT_POINTER(srealloc(p474,235););
printStats();
void* p608 = last_address;
PRINT_POINTER(smalloc(61););
printStats();
void* p609 = last_address;
PRINT_POINTER(scalloc(128,76););
printStats();
void* p610 = last_address;
PRINT_POINTER(smalloc(118););
printStats();
void* p611 = last_address;
PRINT_POINTER(smalloc(112););
printStats();
void* p612 = last_address;
PRINT_POINTER(srealloc(p390,95););
printStats();
void* p613 = last_address;
PRINT_POINTER(scalloc(242,4););
printStats();
void* p614 = last_address;
PRINT_POINTER(srealloc(p556,227););
printStats();
void* p615 = last_address;
PRINT_POINTER(srealloc(p514,220););
printStats();
void* p616 = last_address;
PRINT_POINTER(scalloc(249,97););
printStats();
void* p617 = last_address;
PRINT_POINTER(srealloc(p437,202););
printStats();
void* p618 = last_address;
PRINT_POINTER(scalloc(111,158););
printStats();
void* p619 = last_address;
DEBUG_PRINT(sfree(p472););
printStats();
PRINT_POINTER(srealloc(p478,189););
printStats();
void* p620 = last_address;
PRINT_POINTER(scalloc(205,87););
printStats();
void* p621 = last_address;
PRINT_POINTER(scalloc(163,141););
printStats();
void* p622 = last_address;
PRINT_POINTER(scalloc(52,10););
printStats();
void* p623 = last_address;
PRINT_POINTER(srealloc(p500,64););
printStats();
void* p624 = last_address;
PRINT_POINTER(smalloc(135););
printStats();
void* p625 = last_address;
DEBUG_PRINT(sfree(p411););
printStats();
PRINT_POINTER(scalloc(222,220););
printStats();
void* p626 = last_address;
PRINT_POINTER(smalloc(156););
printStats();
void* p627 = last_address;
PRINT_POINTER(smalloc(18););
printStats();
void* p628 = last_address;
DEBUG_PRINT(sfree(p625););
printStats();
PRINT_POINTER(scalloc(22,195););
printStats();
void* p629 = last_address;
DEBUG_PRINT(sfree(p564););
printStats();
DEBUG_PRINT(sfree(p566););
printStats();
PRINT_POINTER(smalloc(53););
printStats();
void* p630 = last_address;
PRINT_POINTER(srealloc(p568,97););
printStats();
void* p631 = last_address;
PRINT_POINTER(srealloc(p212,2););
printStats();
void* p632 = last_address;
PRINT_POINTER(scalloc(61,239););
printStats();
void* p633 = last_address;
DEBUG_PRINT(sfree(p238););
printStats();
PRINT_POINTER(smalloc(141););
printStats();
void* p634 = last_address;
DEBUG_PRINT(sfree(p509););
printStats();
PRINT_POINTER(scalloc(138,133););
printStats();
void* p635 = last_address;
DEBUG_PRINT(sfree(p465););
printStats();
PRINT_POINTER(smalloc(59););
printStats();
void* p636 = last_address;
DEBUG_PRINT(sfree(p461););
printStats();
PRINT_POINTER(scalloc(73,118););
printStats();
void* p637 = last_address;
PRINT_POINTER(srealloc(p481,81););
printStats();
void* p638 = last_address;
DEBUG_PRINT(sfree(p588););
printStats();
PRINT_POINTER(smalloc(7););
printStats();
void* p639 = last_address;
PRINT_POINTER(smalloc(53););
printStats();
void* p640 = last_address;
DEBUG_PRINT(sfree(p571););
printStats();
DEBUG_PRINT(sfree(p613););
printStats();
PRINT_POINTER(srealloc(p470,72););
printStats();
void* p641 = last_address;
PRINT_POINTER(scalloc(240,228););
printStats();
void* p642 = last_address;
DEBUG_PRINT(sfree(p409););
printStats();
PRINT_POINTER(scalloc(113,40););
printStats();
void* p643 = last_address;
PRINT_POINTER(scalloc(236,168););
printStats();
void* p644 = last_address;
PRINT_POINTER(smalloc(73););
printStats();
void* p645 = last_address;
DEBUG_PRINT(sfree(p273););
printStats();
PRINT_POINTER(smalloc(180););
printStats();
void* p646 = last_address;
PRINT_POINTER(srealloc(p611,212););
printStats();
void* p647 = last_address;
PRINT_POINTER(srealloc(p306,64););
printStats();
void* p648 = last_address;
DEBUG_PRINT(sfree(p532););
printStats();
DEBUG_PRINT(sfree(p439););
printStats();
PRINT_POINTER(scalloc(214,164););
printStats();
void* p649 = last_address;
DEBUG_PRINT(sfree(p602););
printStats();
PRINT_POINTER(srealloc(p639,125););
printStats();
void* p650 = last_address;
PRINT_POINTER(scalloc(114,125););
printStats();
void* p651 = last_address;
PRINT_POINTER(smalloc(87););
printStats();
void* p652 = last_address;
DEBUG_PRINT(sfree(p378););
printStats();
PRINT_POINTER(srealloc(p614,133););
printStats();
void* p653 = last_address;
DEBUG_PRINT(sfree(p585););
printStats();
PRINT_POINTER(smalloc(212););
printStats();
void* p654 = last_address;
PRINT_POINTER(srealloc(p371,83););
printStats();
void* p655 = last_address;
PRINT_POINTER(srealloc(p535,164););
printStats();
void* p656 = last_address;
PRINT_POINTER(smalloc(175););
printStats();
void* p657 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p658 = last_address;
PRINT_POINTER(scalloc(246,242););
printStats();
void* p659 = last_address;
PRINT_POINTER(scalloc(150,10););
printStats();
void* p660 = last_address;
DEBUG_PRINT(sfree(p467););
printStats();
PRINT_POINTER(scalloc(119,157););
printStats();
void* p661 = last_address;
PRINT_POINTER(srealloc(p407,76););
printStats();
void* p662 = last_address;
PRINT_POINTER(scalloc(227,116););
printStats();
void* p663 = last_address;
PRINT_POINTER(srealloc(p510,79););
printStats();
void* p664 = last_address;
PRINT_POINTER(srealloc(p355,13););
printStats();
void* p665 = last_address;
PRINT_POINTER(srealloc(p484,126););
printStats();
void* p666 = last_address;
PRINT_POINTER(srealloc(p299,53););
printStats();
void* p667 = last_address;
PRINT_POINTER(scalloc(74,174););
printStats();
void* p668 = last_address;
PRINT_POINTER(scalloc(61,203););
printStats();
void* p669 = last_address;
PRINT_POINTER(scalloc(242,215););
printStats();
void* p670 = last_address;
DEBUG_PRINT(sfree(p622););
printStats();
PRINT_POINTER(srealloc(p573,92););
printStats();
void* p671 = last_address;
DEBUG_PRINT(sfree(p416););
printStats();
DEBUG_PRINT(sfree(p657););
printStats();
PRINT_POINTER(smalloc(63););
printStats();
void* p672 = last_address;
PRINT_POINTER(srealloc(p402,165););
printStats();
void* p673 = last_address;
PRINT_POINTER(scalloc(185,166););
printStats();
void* p674 = last_address;
PRINT_POINTER(scalloc(233,84););
printStats();
void* p675 = last_address;
DEBUG_PRINT(sfree(p345););
printStats();
PRINT_POINTER(scalloc(212,30););
printStats();
void* p676 = last_address;
PRINT_POINTER(smalloc(44););
printStats();
void* p677 = last_address;
DEBUG_PRINT(sfree(p489););
printStats();
DEBUG_PRINT(sfree(p542););
printStats();
PRINT_POINTER(smalloc(234););
printStats();
void* p678 = last_address;
PRINT_POINTER(srealloc(p587,161););
printStats();
void* p679 = last_address;
PRINT_POINTER(srealloc(p675,187););
printStats();
void* p680 = last_address;
PRINT_POINTER(scalloc(103,140););
printStats();
void* p681 = last_address;
PRINT_POINTER(srealloc(p557,195););
printStats();
void* p682 = last_address;
PRINT_POINTER(srealloc(p353,159););
printStats();
void* p683 = last_address;
PRINT_POINTER(scalloc(163,145););
printStats();
void* p684 = last_address;
PRINT_POINTER(srealloc(p526,158););
printStats();
void* p685 = last_address;
DEBUG_PRINT(sfree(p643););
printStats();
PRINT_POINTER(scalloc(198,121););
printStats();
void* p686 = last_address;
PRINT_POINTER(scalloc(145,71););
printStats();
void* p687 = last_address;
PRINT_POINTER(scalloc(240,133););
printStats();
void* p688 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p689 = last_address;
PRINT_POINTER(srealloc(p288,155););
printStats();
void* p690 = last_address;
PRINT_POINTER(smalloc(171););
printStats();
void* p691 = last_address;
PRINT_POINTER(srealloc(p600,231););
printStats();
void* p692 = last_address;
PRINT_POINTER(scalloc(129,232););
printStats();
void* p693 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p694 = last_address;
DEBUG_PRINT(sfree(p572););
printStats();
PRINT_POINTER(srealloc(p616,97););
printStats();
void* p695 = last_address;
DEBUG_PRINT(sfree(p623););
printStats();
PRINT_POINTER(scalloc(174,203););
printStats();
void* p696 = last_address;
PRINT_POINTER(scalloc(220,123););
printStats();
void* p697 = last_address;
PRINT_POINTER(scalloc(178,31););
printStats();
void* p698 = last_address;
PRINT_POINTER(smalloc(152););
printStats();
void* p699 = last_address;
PRINT_POINTER(smalloc(163););
printStats();
void* p700 = last_address;
DEBUG_PRINT(sfree(p561););
printStats();
PRINT_POINTER(srealloc(p654,147););
printStats();
void* p701 = last_address;
DEBUG_PRINT(sfree(p697););
printStats();
DEBUG_PRINT(sfree(p629););
printStats();
PRINT_POINTER(srealloc(p483,95););
printStats();
void* p702 = last_address;
PRINT_POINTER(srealloc(p691,93););
printStats();
void* p703 = last_address;
PRINT_POINTER(smalloc(194););
printStats();
void* p704 = last_address;
DEBUG_PRINT(sfree(p590););
printStats();
PRINT_POINTER(srealloc(p537,95););
printStats();
void* p705 = last_address;
DEBUG_PRINT(sfree(p438););
printStats();
PRINT_POINTER(scalloc(46,48););
printStats();
void* p706 = last_address;
PRINT_POINTER(smalloc(230););
printStats();
void* p707 = last_address;
DEBUG_PRINT(sfree(p485););
printStats();
DEBUG_PRINT(sfree(p689););
printStats();
PRINT_POINTER(scalloc(158,109););
printStats();
void* p708 = last_address;
DEBUG_PRINT(sfree(p634););
printStats();
PRINT_POINTER(smalloc(124););
printStats();
void* p709 = last_address;
DEBUG_PRINT(sfree(p685););
printStats();
PRINT_POINTER(srealloc(p415,129););
printStats();
void* p710 = last_address;
DEBUG_PRINT(sfree(p397););
printStats();
PRINT_POINTER(srealloc(p320,168););
printStats();
void* p711 = last_address;
PRINT_POINTER(scalloc(83,9););
printStats();
void* p712 = last_address;
PRINT_POINTER(scalloc(55,129););
printStats();
void* p713 = last_address;
PRINT_POINTER(srealloc(p525,128););
printStats();
void* p714 = last_address;
PRINT_POINTER(scalloc(175,215););
printStats();
void* p715 = last_address;
DEBUG_PRINT(sfree(p694););
printStats();
PRINT_POINTER(smalloc(96););
printStats();
void* p716 = last_address;
PRINT_POINTER(scalloc(78,80););
printStats();
void* p717 = last_address;
DEBUG_PRINT(sfree(p366););
printStats();
PRINT_POINTER(smalloc(171););
printStats();
void* p718 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p719 = last_address;
PRINT_POINTER(srealloc(p665,175););
printStats();
void* p720 = last_address;
PRINT_POINTER(srealloc(p513,7););
printStats();
void* p721 = last_address;
PRINT_POINTER(srealloc(p340,62););
printStats();
void* p722 = last_address;
PRINT_POINTER(scalloc(239,217););
printStats();
void* p723 = last_address;
PRINT_POINTER(scalloc(47,28););
printStats();
void* p724 = last_address;
DEBUG_PRINT(sfree(p601););
printStats();
PRINT_POINTER(smalloc(171););
printStats();
void* p725 = last_address;
DEBUG_PRINT(sfree(p394););
printStats();
PRINT_POINTER(smalloc(172););
printStats();
void* p726 = last_address;
DEBUG_PRINT(sfree(p398););
printStats();
PRINT_POINTER(scalloc(210,54););
printStats();
void* p727 = last_address;
PRINT_POINTER(smalloc(142););
printStats();
void* p728 = last_address;
PRINT_POINTER(scalloc(161,240););
printStats();
void* p729 = last_address;
DEBUG_PRINT(sfree(p650););
printStats();
PRINT_POINTER(srealloc(p710,171););
printStats();
void* p730 = last_address;
PRINT_POINTER(smalloc(93););
printStats();
void* p731 = last_address;
PRINT_POINTER(smalloc(198););
printStats();
void* p732 = last_address;
PRINT_POINTER(srealloc(p574,65););
printStats();
void* p733 = last_address;
PRINT_POINTER(srealloc(p727,31););
printStats();
void* p734 = last_address;
PRINT_POINTER(smalloc(28););
printStats();
void* p735 = last_address;
PRINT_POINTER(srealloc(p705,0););
printStats();
void* p736 = last_address;
PRINT_POINTER(scalloc(109,124););
printStats();
void* p737 = last_address;
PRINT_POINTER(smalloc(182););
printStats();
void* p738 = last_address;
PRINT_POINTER(srealloc(p699,47););
printStats();
void* p739 = last_address;
PRINT_POINTER(scalloc(237,169););
printStats();
void* p740 = last_address;
PRINT_POINTER(smalloc(77););
printStats();
void* p741 = last_address;
DEBUG_PRINT(sfree(p633););
printStats();
PRINT_POINTER(scalloc(95,226););
printStats();
void* p742 = last_address;
DEBUG_PRINT(sfree(p218););
printStats();
PRINT_POINTER(scalloc(186,84););
printStats();
void* p743 = last_address;
PRINT_POINTER(scalloc(56,177););
printStats();
void* p744 = last_address;
PRINT_POINTER(srealloc(p604,178););
printStats();
void* p745 = last_address;
PRINT_POINTER(smalloc(249););
printStats();
void* p746 = last_address;
PRINT_POINTER(smalloc(99););
printStats();
void* p747 = last_address;
PRINT_POINTER(srealloc(p659,107););
printStats();
void* p748 = last_address;
PRINT_POINTER(smalloc(158););
printStats();
void* p749 = last_address;
PRINT_POINTER(smalloc(29););
printStats();
void* p750 = last_address;
PRINT_POINTER(scalloc(46,154););
printStats();
void* p751 = last_address;
DEBUG_PRINT(sfree(p738););
printStats();
PRINT_POINTER(scalloc(237,151););
printStats();
void* p752 = last_address;
PRINT_POINTER(scalloc(158,205););
printStats();
void* p753 = last_address;
PRINT_POINTER(smalloc(169););
printStats();
void* p754 = last_address;
DEBUG_PRINT(sfree(p667););
printStats();
PRINT_POINTER(srealloc(p379,22););
printStats();
void* p755 = last_address;
DEBUG_PRINT(sfree(p221););
printStats();
DEBUG_PRINT(sfree(p527););
printStats();
PRINT_POINTER(scalloc(104,238););
printStats();
void* p756 = last_address;
PRINT_POINTER(srealloc(p693,167););
printStats();
void* p757 = last_address;
PRINT_POINTER(smalloc(45););
printStats();
void* p758 = last_address;
PRINT_POINTER(scalloc(187,180););
printStats();
void* p759 = last_address;
DEBUG_PRINT(sfree(p672););
printStats();
PRINT_POINTER(smalloc(32););
printStats();
void* p760 = last_address;
PRINT_POINTER(scalloc(116,233););
printStats();
void* p761 = last_address;
DEBUG_PRINT(sfree(p214););
printStats();
PRINT_POINTER(smalloc(20););
printStats();
void* p762 = last_address;
PRINT_POINTER(smalloc(197););
printStats();
void* p763 = last_address;
PRINT_POINTER(scalloc(134,237););
printStats();
void* p764 = last_address;
PRINT_POINTER(smalloc(83););
printStats();
void* p765 = last_address;
PRINT_POINTER(smalloc(190););
printStats();
void* p766 = last_address;
PRINT_POINTER(smalloc(42););
printStats();
void* p767 = last_address;
PRINT_POINTER(smalloc(177););
printStats();
void* p768 = last_address;
PRINT_POINTER(smalloc(222););
printStats();
void* p769 = last_address;
PRINT_POINTER(scalloc(131,70););
printStats();
void* p770 = last_address;
PRINT_POINTER(scalloc(43,83););
printStats();
void* p771 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p772 = last_address;
DEBUG_PRINT(sfree(p451););
printStats();
PRINT_POINTER(srealloc(p580,150););
printStats();
void* p773 = last_address;
PRINT_POINTER(srealloc(p757,64););
printStats();
void* p774 = last_address;
DEBUG_PRINT(sfree(p447););
printStats();
PRINT_POINTER(scalloc(57,40););
printStats();
void* p775 = last_address;
PRINT_POINTER(scalloc(57,179););
printStats();
void* p776 = last_address;
PRINT_POINTER(smalloc(212););
printStats();
void* p777 = last_address;
PRINT_POINTER(smalloc(246););
printStats();
void* p778 = last_address;
PRINT_POINTER(srealloc(p649,171););
printStats();
void* p779 = last_address;
PRINT_POINTER(scalloc(232,152););
printStats();
void* p780 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p781 = last_address;
PRINT_POINTER(scalloc(159,247););
printStats();
void* p782 = last_address;
PRINT_POINTER(srealloc(p410,76););
printStats();
void* p783 = last_address;
PRINT_POINTER(scalloc(92,96););
printStats();
void* p784 = last_address;
PRINT_POINTER(srealloc(p711,120););
printStats();
void* p785 = last_address;
DEBUG_PRINT(sfree(p761););
printStats();
PRINT_POINTER(smalloc(211););
printStats();
void* p786 = last_address;
PRINT_POINTER(scalloc(242,182););
printStats();
void* p787 = last_address;
DEBUG_PRINT(sfree(p538););
printStats();
PRINT_POINTER(srealloc(p533,80););
printStats();
void* p788 = last_address;
PRINT_POINTER(smalloc(21););
printStats();
void* p789 = last_address;
DEBUG_PRINT(sfree(p560););
printStats();
PRINT_POINTER(scalloc(36,119););
printStats();
void* p790 = last_address;
DEBUG_PRINT(sfree(p610););
printStats();
PRINT_POINTER(srealloc(p730,74););
printStats();
void* p791 = last_address;
PRINT_POINTER(smalloc(160););
printStats();
void* p792 = last_address;
PRINT_POINTER(smalloc(214););
printStats();
void* p793 = last_address;
DEBUG_PRINT(sfree(p754););
printStats();
PRINT_POINTER(scalloc(87,29););
printStats();
void* p794 = last_address;
PRINT_POINTER(srealloc(p456,162););
printStats();
void* p795 = last_address;
PRINT_POINTER(scalloc(210,24););
printStats();
void* p796 = last_address;
DEBUG_PRINT(sfree(p765););
printStats();
PRINT_POINTER(smalloc(28););
printStats();
void* p797 = last_address;
DEBUG_PRINT(sfree(p565););
printStats();
PRINT_POINTER(srealloc(p674,7););
printStats();
void* p798 = last_address;
PRINT_POINTER(scalloc(16,222););
printStats();
void* p799 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p800 = last_address;
PRINT_POINTER(srealloc(p326,74););
printStats();
void* p801 = last_address;
PRINT_POINTER(smalloc(234););
printStats();
void* p802 = last_address;
PRINT_POINTER(srealloc(p706,214););
printStats();
void* p803 = last_address;
DEBUG_PRINT(sfree(p388););
printStats();
PRINT_POINTER(scalloc(58,235););
printStats();
void* p804 = last_address;
PRINT_POINTER(smalloc(109););
printStats();
void* p805 = last_address;
DEBUG_PRINT(sfree(p540););
printStats();
PRINT_POINTER(smalloc(159););
printStats();
void* p806 = last_address;
PRINT_POINTER(smalloc(130););
printStats();
void* p807 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p808 = last_address;
PRINT_POINTER(scalloc(216,237););
printStats();
void* p809 = last_address;
PRINT_POINTER(srealloc(p342,20););
printStats();
void* p810 = last_address;
PRINT_POINTER(scalloc(206,241););
printStats();
void* p811 = last_address;
PRINT_POINTER(smalloc(22););
printStats();
void* p812 = last_address;
PRINT_POINTER(scalloc(168,216););
printStats();
void* p813 = last_address;
PRINT_POINTER(srealloc(p608,42););
printStats();
void* p814 = last_address;
PRINT_POINTER(scalloc(24,2););
printStats();
void* p815 = last_address;
PRINT_POINTER(smalloc(168););
printStats();
void* p816 = last_address;
PRINT_POINTER(srealloc(p615,115););
printStats();
void* p817 = last_address;
PRINT_POINTER(smalloc(26););
printStats();
void* p818 = last_address;
PRINT_POINTER(smalloc(14););
printStats();
void* p819 = last_address;
PRINT_POINTER(scalloc(48,184););
printStats();
void* p820 = last_address;
PRINT_POINTER(srealloc(p755,220););
printStats();
void* p821 = last_address;
PRINT_POINTER(scalloc(246,42););
printStats();
void* p822 = last_address;
PRINT_POINTER(srealloc(p758,97););
printStats();
void* p823 = last_address;
PRINT_POINTER(scalloc(117,36););
printStats();
void* p824 = last_address;
DEBUG_PRINT(sfree(p775););
printStats();
DEBUG_PRINT(sfree(p363););
printStats();
DEBUG_PRINT(sfree(p700););
printStats();
PRINT_POINTER(scalloc(155,105););
printStats();
void* p825 = last_address;
PRINT_POINTER(smalloc(38););
printStats();
void* p826 = last_address;
PRINT_POINTER(srealloc(p496,136););
printStats();
void* p827 = last_address;
PRINT_POINTER(smalloc(219););
printStats();
void* p828 = last_address;
DEBUG_PRINT(sfree(p617););
printStats();
DEBUG_PRINT(sfree(p741););
printStats();
DEBUG_PRINT(sfree(p594););
printStats();
DEBUG_PRINT(sfree(p800););
printStats();
DEBUG_PRINT(sfree(p546););
printStats();
PRINT_POINTER(scalloc(0,197););
printStats();
void* p829 = last_address;
PRINT_POINTER(scalloc(154,210););
printStats();
void* p830 = last_address;
PRINT_POINTER(smalloc(133););
printStats();
void* p831 = last_address;
PRINT_POINTER(srealloc(p718,99););
printStats();
void* p832 = last_address;
PRINT_POINTER(smalloc(84););
printStats();
void* p833 = last_address;
PRINT_POINTER(scalloc(196,143););
printStats();
void* p834 = last_address;
PRINT_POINTER(scalloc(130,155););
printStats();
void* p835 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p836 = last_address;
PRINT_POINTER(scalloc(31,189););
printStats();
void* p837 = last_address;
DEBUG_PRINT(sfree(p837););
printStats();
PRINT_POINTER(scalloc(188,63););
printStats();
void* p838 = last_address;
PRINT_POINTER(scalloc(17,217););
printStats();
void* p839 = last_address;
PRINT_POINTER(smalloc(121););
printStats();
void* p840 = last_address;
PRINT_POINTER(smalloc(117););
printStats();
void* p841 = last_address;
DEBUG_PRINT(sfree(p423););
printStats();
PRINT_POINTER(scalloc(77,134););
printStats();
void* p842 = last_address;
PRINT_POINTER(srealloc(p840,101););
printStats();
void* p843 = last_address;
PRINT_POINTER(scalloc(232,12););
printStats();
void* p844 = last_address;
PRINT_POINTER(scalloc(232,80););
printStats();
void* p845 = last_address;
PRINT_POINTER(smalloc(57););
printStats();
void* p846 = last_address;
PRINT_POINTER(scalloc(211,49););
printStats();
void* p847 = last_address;
DEBUG_PRINT(sfree(p809););
printStats();
PRINT_POINTER(smalloc(129););
printStats();
void* p848 = last_address;
PRINT_POINTER(srealloc(p605,112););
printStats();
void* p849 = last_address;
PRINT_POINTER(scalloc(14,141););
printStats();
void* p850 = last_address;
PRINT_POINTER(srealloc(p842,213););
printStats();
void* p851 = last_address;
PRINT_POINTER(scalloc(79,185););
printStats();
void* p852 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p853 = last_address;
PRINT_POINTER(scalloc(150,104););
printStats();
void* p854 = last_address;
PRINT_POINTER(scalloc(180,69););
printStats();
void* p855 = last_address;
DEBUG_PRINT(sfree(p838););
printStats();
PRINT_POINTER(smalloc(206););
printStats();
void* p856 = last_address;
DEBUG_PRINT(sfree(p658););
printStats();
DEBUG_PRINT(sfree(p719););
printStats();
PRINT_POINTER(smalloc(71););
printStats();
void* p857 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p858 = last_address;
DEBUG_PRINT(sfree(p717););
printStats();
DEBUG_PRINT(sfree(p846););
printStats();
PRINT_POINTER(smalloc(92););
printStats();
void* p859 = last_address;
DEBUG_PRINT(sfree(p806););
printStats();
DEBUG_PRINT(sfree(p847););
printStats();
PRINT_POINTER(smalloc(12););
printStats();
void* p860 = last_address;
PRINT_POINTER(srealloc(p714,207););
printStats();
void* p861 = last_address;
PRINT_POINTER(smalloc(240););
printStats();
void* p862 = last_address;
PRINT_POINTER(smalloc(195););
printStats();
void* p863 = last_address;
PRINT_POINTER(srealloc(p486,188););
printStats();
void* p864 = last_address;
PRINT_POINTER(srealloc(p751,43););
printStats();
void* p865 = last_address;
PRINT_POINTER(srealloc(p609,151););
printStats();
void* p866 = last_address;
PRINT_POINTER(srealloc(p848,185););
printStats();
void* p867 = last_address;
PRINT_POINTER(srealloc(p361,180););
printStats();
void* p868 = last_address;
DEBUG_PRINT(sfree(p737););
printStats();
PRINT_POINTER(smalloc(88););
printStats();
void* p869 = last_address;
PRINT_POINTER(srealloc(p354,128););
printStats();
void* p870 = last_address;
DEBUG_PRINT(sfree(p603););
printStats();
DEBUG_PRINT(sfree(p786););
printStats();
PRINT_POINTER(smalloc(52););
printStats();
void* p871 = last_address;
PRINT_POINTER(scalloc(155,163););
printStats();
void* p872 = last_address;
PRINT_POINTER(srealloc(p869,125););
printStats();
void* p873 = last_address;
PRINT_POINTER(srealloc(p662,10););
printStats();
void* p874 = last_address;
DEBUG_PRINT(sfree(p516););
printStats();
DEBUG_PRINT(sfree(p673););
printStats();
PRINT_POINTER(smalloc(81););
printStats();
void* p875 = last_address;
PRINT_POINTER(smalloc(3););
printStats();
void* p876 = last_address;
PRINT_POINTER(smalloc(157););
printStats();
void* p877 = last_address;
DEBUG_PRINT(sfree(p839););
printStats();
PRINT_POINTER(srealloc(p523,4););
printStats();
void* p878 = last_address;
PRINT_POINTER(srealloc(p785,184););
printStats();
void* p879 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p880 = last_address;
PRINT_POINTER(scalloc(182,230););
printStats();
void* p881 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p882 = last_address;
DEBUG_PRINT(sfree(p878););
printStats();
PRINT_POINTER(smalloc(76););
printStats();
void* p883 = last_address;
DEBUG_PRINT(sfree(p391););
printStats();
PRINT_POINTER(scalloc(70,225););
printStats();
void* p884 = last_address;
PRINT_POINTER(srealloc(p879,142););
printStats();
void* p885 = last_address;
PRINT_POINTER(smalloc(6););
printStats();
void* p886 = last_address;
PRINT_POINTER(smalloc(192););
printStats();
void* p887 = last_address;
PRINT_POINTER(scalloc(174,29););
printStats();
void* p888 = last_address;
PRINT_POINTER(smalloc(79););
printStats();
void* p889 = last_address;
PRINT_POINTER(srealloc(p660,158););
printStats();
void* p890 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p891 = last_address;
DEBUG_PRINT(sfree(p776););
printStats();
PRINT_POINTER(smalloc(153););
printStats();
void* p892 = last_address;
PRINT_POINTER(smalloc(67););
printStats();
void* p893 = last_address;
PRINT_POINTER(srealloc(p374,5););
printStats();
void* p894 = last_address;
PRINT_POINTER(scalloc(10,176););
printStats();
void* p895 = last_address;
PRINT_POINTER(scalloc(140,158););
printStats();
void* p896 = last_address;
PRINT_POINTER(srealloc(p801,131););
printStats();
void* p897 = last_address;
PRINT_POINTER(smalloc(9););
printStats();
void* p898 = last_address;
PRINT_POINTER(srealloc(p795,206););
printStats();
void* p899 = last_address;
PRINT_POINTER(scalloc(26,7););
printStats();
void* p900 = last_address;
DEBUG_PRINT(sfree(p872););
printStats();
PRINT_POINTER(smalloc(70););
printStats();
void* p901 = last_address;
PRINT_POINTER(srealloc(p678,70););
printStats();
void* p902 = last_address;
PRINT_POINTER(scalloc(75,172););
printStats();
void* p903 = last_address;
PRINT_POINTER(smalloc(72););
printStats();
void* p904 = last_address;
PRINT_POINTER(scalloc(177,207););
printStats();
void* p905 = last_address;
DEBUG_PRINT(sfree(p166););
printStats();
DEBUG_PRINT(sfree(p808););
printStats();
PRINT_POINTER(srealloc(p553,139););
printStats();
void* p906 = last_address;
PRINT_POINTER(scalloc(177,246););
printStats();
void* p907 = last_address;
DEBUG_PRINT(sfree(p759););
printStats();
DEBUG_PRINT(sfree(p746););
printStats();
PRINT_POINTER(smalloc(212););
printStats();
void* p908 = last_address;
PRINT_POINTER(srealloc(p720,45););
printStats();
void* p909 = last_address;
PRINT_POINTER(scalloc(206,240););
printStats();
void* p910 = last_address;
PRINT_POINTER(srealloc(p828,151););
printStats();
void* p911 = last_address;
PRINT_POINTER(scalloc(243,65););
printStats();
void* p912 = last_address;
DEBUG_PRINT(sfree(p716););
printStats();
PRINT_POINTER(scalloc(14,81););
printStats();
void* p913 = last_address;
PRINT_POINTER(smalloc(172););
printStats();
void* p914 = last_address;
PRINT_POINTER(srealloc(p908,192););
printStats();
void* p915 = last_address;
PRINT_POINTER(scalloc(200,61););
printStats();
void* p916 = last_address;
PRINT_POINTER(scalloc(95,74););
printStats();
void* p917 = last_address;
PRINT_POINTER(srealloc(p861,73););
printStats();
void* p918 = last_address;
DEBUG_PRINT(sfree(p577););
printStats();
DEBUG_PRINT(sfree(p683););
printStats();
DEBUG_PRINT(sfree(p598););
printStats();
PRINT_POINTER(smalloc(1););
printStats();
void* p919 = last_address;
PRINT_POINTER(smalloc(65););
printStats();
void* p920 = last_address;
PRINT_POINTER(smalloc(31););
printStats();
void* p921 = last_address;
PRINT_POINTER(smalloc(64););
printStats();
void* p922 = last_address;
PRINT_POINTER(scalloc(139,50););
printStats();
void* p923 = last_address;
PRINT_POINTER(srealloc(p865,68););
printStats();
void* p924 = last_address;
DEBUG_PRINT(sfree(p888););
printStats();
PRINT_POINTER(scalloc(217,226););
printStats();
void* p925 = last_address;
PRINT_POINTER(smalloc(95););
printStats();
void* p926 = last_address;
PRINT_POINTER(smalloc(102););
printStats();
void* p927 = last_address;
PRINT_POINTER(srealloc(p695,24););
printStats();
void* p928 = last_address;
DEBUG_PRINT(sfree(p491););
printStats();
PRINT_POINTER(smalloc(3););
printStats();
void* p929 = last_address;
PRINT_POINTER(smalloc(17););
printStats();
void* p930 = last_address;
PRINT_POINTER(srealloc(p850,21););
printStats();
void* p931 = last_address;
PRINT_POINTER(smalloc(164););
printStats();
void* p932 = last_address;
PRINT_POINTER(scalloc(227,161););
printStats();
void* p933 = last_address;
PRINT_POINTER(scalloc(135,237););
printStats();
void* p934 = last_address;
DEBUG_PRINT(sfree(p530););
printStats();
DEBUG_PRINT(sfree(p883););
printStats();
PRINT_POINTER(srealloc(p740,7););
printStats();
void* p935 = last_address;
DEBUG_PRINT(sfree(p927););
printStats();
PRINT_POINTER(srealloc(p849,225););
printStats();
void* p936 = last_address;
PRINT_POINTER(smalloc(148););
printStats();
void* p937 = last_address;
PRINT_POINTER(scalloc(205,243););
printStats();
void* p938 = last_address;
PRINT_POINTER(scalloc(14,50););
printStats();
void* p939 = last_address;
PRINT_POINTER(scalloc(113,33););
printStats();
void* p940 = last_address;
DEBUG_PRINT(sfree(p404););
printStats();
}
